### ISSUE TITLE
com.google.android.exoplayer.text.webvtt.WebvttParser too strict

### ISSUE THREAD

**Issue by piterwilson** [google/ExoPlayer#609] opened 2015-07-08 12:07 UTC
A HLS Subtitle stream like http://www.iandevlin.com/html5test/webvtt/upc-video-subtitles-en.vtt fails to parse using `WebvttParser`.

The reason is that the first line of the file reads `WEBVTT FILE` instead of just `WEBVTT`. I came across this while testing the parser with different file samples found online.

Although this might seem like correct behaviour,  `WebvttParser` could benefit from a bit of leniency for cases like this. Other players (like Apple's) open the file without problem.

It's a simple change on line 113:

from:
```
 if (!line.equals("WEBVTT") && !line.equals("\uFEFFWEBVTT")) {
      throw new ParserException("Expected WEBVTT. Got " + line);
    }
```
to:

```
 if (!line.startsWith("WEBVTT") && !line.startsWith("\uFEFFWEBVTT")) {
      throw new ParserException("Expected WEBVTT. Got " + line);
    }
```

**Comment by andrewlewis** [comment] 2015-07-10 12:14
This should work correctly on the dev branch. See https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/text/webvtt/WebvttParser.java#L123.

**Comment by andrewlewis** [comment] 2015-07-10 12:17
Duplicate of #580.

**Closed by andrewlewis** 2015-07-10 12:17 UTC
