### ISSUE TITLE
Is there anyway to passthrough ac3,dts using extension-ffmpeg without mediacodec?

### ISSUE THREAD

**Issue by muhaozhang** [google/ExoPlayer#2832] opened 2017-05-16 09:50 UTC
My box is unsupport for hard-decoder ac3 and dts,so i try to use the extension of ffmpeg.
i do it like this:
1.i add the extension-ffmpeg to make the exoplayer can soft-decoder the ac3 and dts.
2.i transmit AudioCapabilities.getCapabilities(context) to FfmpegAudioRenderer like this:
try {
      Class<?> clazz =
          Class.forName("com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioRenderer");
      Constructor<?> constructor = clazz.getConstructor(Handler.class,
          AudioRendererEventListener.class, AudioCapabilities.class);
      Renderer renderer = (Renderer) constructor.newInstance(mainHandler, componentListener, AudioCapabilities.getCapabilities(context));
      out.add(extensionRendererIndex++, renderer);
      Log.i(TAG, "Loaded FfmpegAudioRenderer.");
    } catch (ClassNotFoundException e) {
      // Expected if the app was built without the extension.
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
but, i found it don't work for passthrough.
then i read the exoplayer source code carefully, i found that i have to custom  FfmpegAudioRenderer not extends SimpleDecoderAudioRenderer but a new audio render extends BaseRender like the MediaCodecRenderer did.it seems a little complicated.
And, I found the audio to be passthrough or not by mediacodec,is decided in the class MediaCodecAudioRenderer finally:
@Override
  protected void configureCodec(MediaCodec codec, Format format, MediaCrypto crypto) {
	
    if (passthroughEnabled) {
      // Override the MIME type used to configure the codec if we are using a passthrough decoder.
      passthroughMediaFormat = format.getFrameworkMediaFormatV16();
      passthroughMediaFormat.setString(MediaFormat.KEY_MIME, MimeTypes.AUDIO_RAW);
      codec.configure(passthroughMediaFormat, null, crypto, 0);
      passthroughMediaFormat.setString(MediaFormat.KEY_MIME, format.sampleMimeType);
    } else {
      codec.configure(format.getFrameworkMediaFormatV16(), null, crypto, 0);
      passthroughMediaFormat = null;
    }
  }
it used the method configure(...) of the class MediaCodec.
if i use ffmpeg ,is there a replace api like the codec.configure(passthroughMediaFormat, null, crypto, 0)?
so,my 2 question is:
1.How can i use ffmpeg to implementation ac3 and dts passthrough?
2.if this can be achieved，Is there A simpler implementation？

**Comment by andrewlewis** [comment] 2017-05-16 16:14
Is the goal to use HDMI passthrough if it's available, and use FfmpegAudioRenderer otherwise? I think this should just work if you add a MediaCodecAudioRenderer to the renderers list before the FfmpegAudioRenderer, as in [DefaultRenderersFactory](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L213). The DefaultTrackSelector should use the first renderer that supports the format, which will be the MediaCodecAudioRenderer if passthrough is supported (or the device has a built-in decoder for the format), and will be the FfmpegAudioRenderer otherwise.

If that's not what you're trying to do, please clarify. Thanks.

**Comment by muhaozhang** [comment] 2017-05-17 04:16
i do use the MediaCodecAudioRenderer as the first renderer in  DefaultRenderersFactory,but MediaCodecAudioRenderer doesn't support ac3 and dts,this is the log:

>    Renderer:1 [
>      Group:0, adaptive_supported=N/A [
>        [ ] Track:0, id=2, mimeType=audio/ac3, channels=6, sample_rate=48000, language=und, supported=NO_UNSUPPORTED_TYPE
>      ]
>      Group:1, adaptive_supported=N/A [
>        [ ] Track:0, id=3, mimeType=audio/ac3, channels=2, sample_rate=48000, language=und, supported=NO_UNSUPPORTED_TYPE
>      ]
>    ]

so i want to use ffmpeg instead,but i found it not work for passthrough.
i want to know if MediaCodecAudioRenderer is not support ac3 and dts,how can i passthrough ac3 and dts?

**Comment by andrewlewis** [comment] 2017-05-17 21:46
HDMI passthrough does not rely the device having any particular audio decoders. We provide the functionality via MediaCodecAudioRenderer because it's convenient. MediaCodecAudioRenderer will use HDMI passthrough if the AudioCapabilities passed to its constructor declare that passthrough is possible. FfmpegAudioRenderer on its own does not support passthrough.

To reiterate my previous comment, if HDMI passthrough is possible, MediaCodecAudioRenderer will use it. Otherwise, if there is an FfmpegAudioRenderer listed and compiled with the right decoders, it should be used and decode the audio to PCM. So you just need to make sure those two renderers are passed to the player, with the MediaCodecAudioRenderer first.

**Comment by muhaozhang** [comment] 2017-05-19 11:28
I understand what you are saying is that ,if HDMI passthrough is possible, MediaCodecAudioRenderer will use it , no matter that MediaCodecAudioRenderer can't decode ac3 and dts in my box.I don't know if i got it right?

I add log to some key locations,then i found that if MediaCodecAudioRenderer can't decode ac3 and dts，the type audio/ac3 will not be passed to method onInputFormatChanged() in class MediaCodecRenderer.This will cause method configureCodec() in class MediaCodecAudioRenderer and method getDecoderInfo() in class MediaCodecAudioRenderer not to be called.The method  getDecoderInfo() and configureCodec() is the important way to enable passthrough for ac3 and dts.

So ,i think when MediaCodecAudioRenderer can't decode ac3 and dts on some special boxes,there is something wrong on passthrough audio maybe.And i confirm that the box is support for ac3 and dts passthrough.

**Comment by andrewlewis** [comment] 2017-05-20 18:21
Please set a breakpoint in `MediaCodecAudioRenderer.supportsFormat` and confirm that [this branch](https://github.com/google/ExoPlayer/blob/0e6ef0e/library/core/src/main/java/com/google/android/exoplayer2/audio/MediaCodecAudioRenderer.java#L148) is taken. If not, passthrough mode is not available and you can step through the code to figure out why. Some possible explanations: the HDMI connection is not advertising support for those formats, or you're passing `null`/default AudioCapabilities to the renderer's constructor.

**Comment by darwinvtomy** [comment] 2017-05-22 12:19
I have the same issue with himedia box the HDMI connection is not advertising support for those formats,
Also OMX.google.raw compontent is not properly configured for Passthrough .
But the device will give passthrough if we are using default  videoview in android mediaplayer  
I am still waiting for the solution 
The box have kodi player which has a passthrough libraries ,i am looking for a solution to use it in Exoplayer

**Comment by andrewlewis** [comment] 2017-06-01 16:30
@darwinvtomy Could you provide more details about what you mean by "Also OMX.google.raw compontent is not properly configured for Passthrough ."? ExoPlayer relies on this component for passthrough mode in MediaCodecAudioRenderer.

**Comment by darwinvtomy** [comment] 2017-06-14 07:06
@andrewlewis the problem is with my box himedia h8 lite in which I have no idea about the passthrough decoder used .There is nothing wrong with the exoplayer  i got this error AudioTrack init failed: 0, Config(48000, 252, 20480) when i tried to use the OMX.google.raw.decoder .I tried the same app with Amazon Fire and its working perfectly

**Comment by andrewlewis** [comment] 2017-06-26 07:37
@darwinvtomy If the renderer got as far as initializing the AudioTrack then the codec may be fine. It sounds like this device has an issue with its passthrough implementation. Does passthrough mode work from any other applications on this device? How did you verify that audio is being output via passthrough, rather than being decoded on the device and output in PCM format?

**Comment by darwinvtomy** [comment] 2017-06-28 11:13
@andrewlewis This device comes with built in KODI player in the firmware which can give passthrough .But official Kodi player will not support . Passthrough is supported in the default video view player. I don't think the box has a build in decoder for AC3 contents it will just allow passthrough  for those contents but the kodi has a software decoder for downmixing it seems.

![vlcsnap-2017-06-28-16h12m36s805](https://user-images.githubusercontent.com/10060131/27633412-af3debe8-5c1c-11e7-88a4-8f26d10e2631.png)
**# DIGITAL AUDIO DECODER**
I am using following device to detect the stream It will detect the audio stream. I am using Exoplayer for seamless streaming also for down mixing of ac3 audio for TV's that are not capable of decoding it 


PS:- This device uses Android 5.1.1 OS but it cannot detect any audio capabilities of HDMI.Also It uses a Android mobile/tablet OS (**Typical Chinese TV Box** [Himedia H8](http://www.himediatech.com/h8core.html) )  
    **adb shell cat /system/etc/media_codecs.xml** 
[MediaCodecs.txt](https://github.com/google/ExoPlayer/files/1108454/MediaCodecs.txt)
Just enlighten me if I miss something please give me a solution or any reference to fix this issue .I already tried with the box manufactures believe me !!! they are so dump in handling this issue .
It uses a RK3368 based chip 
**I AM STILL TRYING TO FIGURE OUT A SOLUTION**

**Comment by andrewlewis** [comment] 2017-06-28 12:18
If the `AudioTrack` throws when trying to initialize encoded output, there's not much we can do unfortunately. Also, not having the correct HDMI audio capabilities is also problematic as there's no way for the app to detect that it should be able to output using passthrough. The provided `media_codecs.xml` files do not declare any on-device AC-3 decoders, so I don't think you're missing anything.

I suggest following up with the OEM regarding how the player in the firmware is able to use this feature. Please reopen if you get more information about how this can work, but I will close this for now as there's nothing actionable, and I think the questions from the original posts have been answered.

**Closed as completed by andrewlewis** 2017-06-28 12:18 UTC
Labels: question, need more info, documentation candidate
