### ISSUE TITLE
Preview thumbnails on DASH - Sample stream

### ISSUE THREAD

**Issue by alfonsoramosa** [google/ExoPlayer#11321] opened 2023-10-25 13:06 UTC
Hi,

we are looking into adding thumbnails preview to our DASH streams (live, catchup, vod) using a solution based on 
https://dashif-documents.azurewebsites.net/DASH-IF-IOP/pull/341/DASH-IF-IOP.html#thumbnails

Is it there any test stream that already has the thumbnails available, so we can try it with Exoplayer?

Thank you!

**Comment by icbaker** [comment] 2023-10-26 17:17
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

Duplicate of https://github.com/androidx/media/issues/769

**Closed as completed by icbaker** 2023-10-26 17:17 UTC
Labels: duplicate
