### ISSUE TITLE
Wrong currentWindowIndex onPlayerError

### ISSUE THREAD

**Issue by Khang-NT** [google/ExoPlayer#5407] opened 2019-01-19 03:04 UTC
### Issue description & Reproduction steps
When using `ConcatenatingMediaSource` to play a playlist of media, let say I'm playing at position `i`, and position `i + 1` failed to load. Then within `onPlayerError` callback, I expect`currentWindowIndex` should return `i + 1` but actually it return `i`. Is it intended behavior?

### Version of ExoPlayer being used
`2.9.3`

**Comment by tonihei** [comment] 2019-01-21 10:12
> Is it intended behavior?

That's not exactly intended behaviour and for load errors specifically we should report the loading source window index. Note that the non-fatal onLoadError callbacks already have the correct window index. However, the fatal onPlayerError always gets assigned to the currently playing window index. As we can't switch to the next window if there is a load error, you still see the previous window index in onPlayerError as the "playing" one.

**Comment by tonihei** [comment] 2019-01-21 10:32
Probably wasn't clear from my previous comment:
- `player.getCurrentWindowIndex` will still return the previous window index in all cases because we can't switch to the next item we don't get any samples.
- `EventTime.windowIndex` in the `AnalyticsListener` callbacks will contain the correct association from error to window.

**Comment by Khang-NT** [comment] 2019-01-22 14:37
This behavior will lead to:
* `PlayerView` display last video frame or thumbnail of item `i` while showing error message of item `i + 1`. When shuffle is enabled, it will confuse user because next item is unknown random position.
* I can't call `skip()` within `onPlayerError`. Because it actually set the window index to `i + 1` where the media item can't play. Then somehow I need to call `skip` "twice".

**Comment by tonihei** [comment] 2019-01-22 14:44
Fixing it in the way you describe would require some changes in how we progress internally through the playlist. Right now, we don't change the playing source to the next item until the next source is fully prepared. I agree that this not ideal, but it requires moving around some code in our core player. And a lot of care not to break things in the process. :) 

I'll re-open as an enhancement, but also mark it as low priority for now for the reason given above.

**Comment by tonihei** [comment] 2019-08-21 13:53
We fixed this issue with the two commits below.

**Closed as completed by tonihei** 2019-08-21 13:53 UTC
Labels: enhancement, low priority
