### ISSUE TITLE
IllegalArgumentException in BaseMediaSource.prepareSource

### ISSUE THREAD

**Issue by kashu1209** [google/ExoPlayer#7223] opened 2020-04-12 12:55 UTC
I am implementing a timeline recyclerview which will have mix of photos and videos. But I am getting an exception. I am using exoplayer version 2.10.8. Down below is the stack trace of that. Can you guys help me identify which might be causing it.

E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
        at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:136)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:444)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:311)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by icbaker** [comment] 2020-04-14 10:55
The [line](https://github.com/google/ExoPlayer/blob/r2.10.8/library/core/src/main/java/com/google/android/exoplayer2/source/BaseMediaSource.java#L136) throwing the error is `Assertions.checkArgument(this.looper == null || this.looper == looper);`.

This suggests you're preparing the `MediaSource` from different threads.

It's not possible to provide any more help with the information you've provided so far. If you'd like us to look at this further, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in a Android Studio project that we can clone and build ourselves.

**Comment by ojw28** [comment] 2020-04-14 20:32
This is indicative of providing the same `MediaSource` to multiple different player instances, which isn't a supported use case. If that's what you're doing, you should create a new instance for each player instead.

**Comment by kashu1209** [comment] 2020-04-15 01:57
I am trying to create a single player but update media source

**Comment by icbaker** [comment] 2020-04-15 09:16
We need more information to help you further. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in a Android Studio project that we can clone and build ourselves.

**Comment by kashu1209** [comment] 2020-04-19 12:39
Hi Ian/Oliver,
I was doing it from different threads and why is that creating this
problem? Can you help me understand?

**Comment by ojw28** [comment] 2020-04-19 16:17
ExoPlayer instances generally need to be accessed from a single thread, which in nearly all cases should be the application's main thread. You can read about the threading model [here](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html). If you're not doing this, then that might be a reason why you're seeing problems.

As already noted twice above, to provide more detailed guidance you'll need to provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in an Android Studio project that we can clone and build ourselves. Closing for now, since this has not been provided.

**Closed as completed by ojw28** 2020-04-19 16:17 UTC
Labels: question
