### ISSUE TITLE
jcenter shutdown May 1st

### ISSUE THREAD

**Issue by ToxicBakery** [google/ExoPlayer#8540] opened 2021-02-03 19:33 UTC
[jCenter will be shutdown on May 1st](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). ExoPlayer is currently still solely hosted here and will soon be unavailable. In the past, it was mentioned that [ExoPlayer would move to the Google repository "soon"](https://github.com/google/ExoPlayer/issues/5731#issuecomment-480184332) but that was well over a year ago now and it hasn't happened. Can we get a prioritized date on moving over to the Google Repository?

**Comment by ojw28** [comment] 2021-02-03 21:50
Yes, thanks for bringing this to our attention! We need to prioritize this migration. Marking as a duplicate of https://github.com/google/ExoPlayer/issues/5246.

**Closed as completed by ojw28** 2021-02-03 21:50 UTC
Labels: duplicate
