### ISSUE TITLE
Where to find the NalUnit?

### ISSUE THREAD

**Issue by imbichitra** [google/ExoPlayer#6623] opened 2019-11-07 02:27 UTC
Hi developer's ,
This is not a bug or issues but i want to know about Nal Units Actually i encrypted a mp4 video file where Nal headers are not encrypted only the data are encrypted and i also implement decryption logic which take encrypted  byte array chunks by chunk and decrepit it and after that I want to handover this decrypted byte array to renderer to play but i am unable to find the proper place where Nal Units are find and handhover to the renderer so that i call my own decryption logic by passing encrypted byte array.
Thanks.

**Comment by ojw28** [comment] 2019-11-07 10:37
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/6554. If you want to continue that discussion, please do so there instead of creating a new issue. Thanks!

**Closed as completed by ojw28** 2019-11-07 10:37 UTC
Labels: duplicate
