### ISSUE TITLE
Multiple fast clicks on notification play/pause button break notification

### ISSUE THREAD

**Issue by PawelDedio** [google/ExoPlayer#8027] opened 2020-10-01 13:19 UTC
### [REQUIRED] Issue description
In my application we received bug report about buggy play/pause button. If you click very fast multiple times on play/pause button on notification after some time notification doesn't respond. I found another app which use ExoPlayer `PlayerNotificationManager` and the problem also exists there. 

### [REQUIRED] Reproduction steps

- Clone this open source repository: https://github.com/SoftwareEngineeringDaily/software-engineering-daily-androi
- Open any article on home screen
- Click play button
- Click multiple times on play/pause button

Video: https://streamable.com/gfw2p1

### [REQUIRED] Link to test content
Test content is bundled inside this app: https://github.com/SoftwareEngineeringDaily/software-engineering-daily-android

### [REQUIRED] A full bug report captured from the device
[bugreport-sdk_gphone_x86-QSR1.200403.001-2020-10-01-13-57-31.zip](https://github.com/google/ExoPlayer/files/5312197/bugreport-sdk_gphone_x86-QSR1.200403.001-2020-10-01-13-57-31.zip)

### [REQUIRED] Version of ExoPlayer being used
`2.12.0` In my application, `2.10.1` in provided open source app

### [REQUIRED] Device(s) and version(s) of Android being used
Api 29, Api 28 and probably others

**Comment by marcbaechinger** [comment] 2020-10-01 14:09
That's a duplicate of #6657 

You can find this behaviour with any audio app I think. No matter whether the `PlayerNotificationManager` is used or not. 
We already reduced the number of updates to a minimum with [this commit](https://github.com/google/ExoPlayer/commit/bab8975438a609f2a0c3140333d91e4d54a6e771).

Please refer to #6657  for more details and join the conversation there I you want.
I'm closing this issue to keep everything about this in one issue.

**Closed as completed by marcbaechinger** 2020-10-01 14:09 UTC
Labels: duplicate, bug: in platform
