### ISSUE TITLE
How to stop buffering old mediaItem manifest when play other mediaitem?

### ISSUE THREAD

**Issue by thucngv** [google/ExoPlayer#10683] opened 2022-10-11 07:47 UTC
I have a mediaitem list, when I switch to another mediaitem, the player continues to load the manifest of the old mediaitem

**Comment by icbaker** [comment] 2022-10-11 12:29
Please provide clear & complete steps we can use to reproduce this - and also please provide a clear explanation of how you are measuring/observing "the player continues to load the manifest of the old mediaitem".

**Comment by thucngv** [comment] 2022-10-12 06:44
> Please provide clear & complete steps we can use to reproduce this - and also please provide a clear explanation of how you are measuring/observing "the player continues to load the manifest of the old mediaitem".

I play a mediaitem playlist .
when next mediaitem, old mediaitem still loading manifest.
You can check by logging http request

**Comment by icbaker** [comment] 2022-11-10 10:04
Closing because the clear repro steps requested weren't provided.

**Closed as completed by icbaker** 2022-11-10 10:04 UTC
Labels: question
