### ISSUE TITLE
Migrate from JCenter to MavenCentral

### ISSUE THREAD

**Issue by JcMinarro** [google/ExoPlayer#8547] opened 2021-02-04 11:03 UTC
[JFrog announced](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) yesterday that Bintray and JCenter repositories will be closed by May 1st.
You use JCenter to distribute your artifacts. 
Are you planning to migrate to MavenCentral or Google repository?

**Comment by andrewlewis** [comment] 2021-02-04 11:07
Yes, we are planning to migrate to GMaven.

**Comment by andrewlewis** [comment] 2021-02-04 11:07
Duplicate of #5246

**Closed as completed by andrewlewis** 2021-02-04 11:07 UTC
Labels: duplicate
