### ISSUE TITLE
Request: allow to show animated GIF/WEBP/HEIF, as well as static images

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#8143] opened 2020-11-01 01:50 UTC
### [REQUIRED] Use case description
This can be used to avoid creation of multiple views for a simple thing to show.
Or for a placeholder before we actually show the video, or while loading it.

### Proposed solution
We could tell it which to use. 
Even without the animation support, it could be nice to have static images, and we could set them using frame-by-frame for animation using Glide.
We could also show the first frame of the video, exactly as it will be about to be shown, or a cover of it.
Using the animation it could be a preview of the video.

### Alternatives considered
Another layer is sometimes a problem to make the transition nicely, and might have glitches on some devices.
Conversion to MP4 is also possible from images, but it's weird:
https://github.com/israel-fl/bitmap2video

**Comment by lcf87** [comment] 2020-11-02 18:19
We don't currently plan to support image playback.

#2874 may give a better context.

**Comment by AndroidDeveloperLB** [comment] 2020-11-02 18:27
@lcf87 Can you please give me a clue about how to have a workaround for this, perhaps?
I would really like to know how to show an image.
Otherwise I would probably convert an image to a video.
The link you've provided talks about `ImageRenderer extends BaseRenderer`. Not sure how this would work.
Someone else used it, perhaps?

**Comment by AndroidDeveloperLB** [comment] 2020-11-02 18:29
@ojw28 Have you perhaps implemented such a functionality ?

**Comment by ojw28** [comment] 2020-11-02 20:13
It's unclear what you need a workaround for. In order to assess what this means, you'd need to provide a concrete example showing how to reproduce such a glitch:

> Another layer is sometimes a problem to make the transition nicely, and might have glitches on some devices.

Note that ExoPlayer doesn't have access to any underlying magic that's not available to regular application code, so it's unclear how ExoPlayer would be able to do a better job of it than application code is able to do directly. In other words, if these glitches really are a significant problem for your application code, then they would likely be a problem for an implementation inside of ExoPlayer too.

**Comment by AndroidDeveloperLB** [comment] 2020-11-02 21:05
@ojw28 OK I will tell you.
ExoPlayer can be used even for live wallpaper, so developers can create live wallpapers that shows a short video file.
What I want is to also be able to show images and animated GIF/WEBP.

As for glitches, I once saw it when I worked on a more common case, of showing an ImageView on top of it. Maybe it was fixed. Maybe not. As what i did was very simple, I don't think it's a bug on my side.

**Comment by ojw28** [comment] 2020-11-15 17:15
Closing this as we have no plans to support this functionality, and because no concrete reproduction steps have been provided to demonstrate glitches when using additional views. It sounds somewhat unclear whether you're even sure there's an issue.

**Closed as completed by ojw28** 2020-11-15 17:15 UTC
Labels: enhancement

**Comment by AndroidDeveloperLB** [comment] 2020-11-15 17:57
@ojw28 Why close exactly? I told you what you wanted to know...
Why no plans? 
Animated GIF/WEBP is very similar to playing videos that don't have sound...
