### ISSUE TITLE
how to play control play next previous shewing in google map

### ISSUE THREAD

**Issue by nateshjammy** [google/ExoPlayer#8244] opened 2020-11-18 04:57 UTC
Before filing a feature request:
-----------------------
how to set the same as my own ExoPlayer. via intent
setting ->navigation setting -> default music app shows my media player app

how to play control play next the previous showing in google map

**Comment by icbaker** [comment] 2020-11-18 09:17
Duplicate of #8238

**Closed as completed by icbaker** 2020-11-18 09:17 UTC
Labels: enhancement
