### ISSUE TITLE
Black Screen with hls video when integration with flutter

### ISSUE THREAD

**Issue by likeconan** [google/ExoPlayer#8584] opened 2021-02-13 09:44 UTC
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app
or a small sample app that you’re able to share as source code on GitHub. To
increase the chance of your issue getting attention, please also include:

### Environment:

Android Version 7.0
Huawei device
Exoplayer: 2.13.1
Flutter: 1.22.6

### Description
When I implement AndroidViewSurface with exoplayer, the playback works fine with audio but video is black. **However after I press home screen button and then resume the app, the black screen is gone and video works again.**

For Android version 9.0 and above, the issue is gone.

So I guess maybe it has something wrong with the player compatibility.

Is there any hack solution for this, like just call some method on resume programmatically so that video works fine at first place.

**Comment by marcbaechinger** [comment] 2021-02-16 11:25
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app
or a small sample app that you’re able to share as source code on GitHub.

We can't help you if this is a Flutter integration issue, but we are happy to look into the issue if it's due to the stream not working on ExoPlayer. For that purpose you should post the HLS uri so we can check what is going on. The information of your post above doesn't provide enough information for us to do something.

**Comment by likeconan** [comment] 2021-02-16 12:52
I tried with ExoPlayer demo directly, this issue is not happened with Android 7.0, I will prepare a flutter example in github, please wait a moment. Thanks

**Comment by marcbaechinger** [comment] 2021-02-16 13:30
Thanks. If it works in the demo app we can probably not provide you with sufficient support I'm afraid. Best is probably to connect with the Flutter people.

You are saying that it happens related to be started/backgrounded/foregrounded so there is probably a problem with the integration rather than with ExoPlayer.

**Comment by likeconan** [comment] 2021-02-17 00:20
Oh... However maybe you can guide me how to programmatically fire some function kind of like resume? So that the issue is fixed by hack solution. Thanks a lot~

**Comment by ojw28** [comment] 2021-09-08 16:02
Closing because this did not reproduce with the ExoPlayer demo app, and so sounds like a Flutter integration problem rather than a problem with ExoPlayer.

**Closed as completed by ojw28** 2021-09-08 16:02 UTC
Labels: question
