### ISSUE TITLE
MultiWindowTimeBar for PlayerNotificationManager

### ISSUE THREAD

**Issue by imecstamas** [google/ExoPlayer#5281] opened 2018-12-19 17:15 UTC
Hi!

I want to show all the mediaSources of a ConcatenatingMediaSource in a single timeBar as a notification. Do you plan to integrate this support for MultiWindowTimeBar in case of notifications via the PlayerNotificationManager? If not, how can I achieve this? 

Thanks,
Tamas

**Comment by tonihei** [comment] 2018-12-20 13:55
That's a duplicate of #4868.

**Closed as completed by tonihei** 2018-12-20 13:55 UTC
Labels: duplicate, question

**Comment by marcbaechinger** [comment] 2018-12-20 14:56
The options of UI elements you can put in notifications is quite limited. There is no way to put arbitrary UI elements in a notification as far as I know. Instead actions are defined which then are rendered by the system in the notifications as buttons.
