### ISSUE TITLE
How to make a custom notification action compact?

### ISSUE THREAD

**Issue by mpivchev** [google/ExoPlayer#9467] opened 2021-09-22 11:08 UTC
Since there's also no way I found to provide my own `Intent` for the default actions, like play/pause and so on, I ended up creating custom actions via `PlayerNotificationManager.CustomActionReceiver`:

```kotlin
    override fun createCustomActions(context: Context, instanceId: Int): MutableMap<String, NotificationCompat.Action> {
        val action = NotificationCompat.Action(android.R.drawable.btn_radio, "closeBar", null)
        val actionMap: MutableMap<String, NotificationCompat.Action> = HashMap()
        actionMap["example"] = action
        return actionMap
    }

    override fun getCustomActions(player: Player): List<String> {
        val customActions: MutableList<String> = ArrayList()
        customActions.add("example")
        return customActions
    }

    override fun onCustomAction(player: Player, action: String, intent: Intent) {
        Timber.d("action: $action")
    }
```

...but there is no way to make this action appear in the compact notification.

In the documentation it's said that `getActionIndicesForCompactView` can be overridden so I can customize which actions are compact, but in the latest ExoPlayer version it's impossible to extend `PlayerNotificationManager`, as its constructor is now private. 

Is there no way to customize which actions go to the compact notification anymore? What about modifying the default actions besides an icon?

**Comment by marcbaechinger** [comment] 2021-09-22 11:26
I think this is a duplicate of #9303. Can you check whether this issue helps in your case? If not please re-open.

**Closed as completed by marcbaechinger** 2021-09-22 11:26 UTC
Labels: question
