### ISSUE TITLE
Cannot play some rtmp streams

### ISSUE THREAD

**Issue by kaiv2000** [google/ExoPlayer#6187] opened 2019-07-15 17:54 UTC
Exoplayer v.2.10.3 still cannot open next rtmp streams:

rtmp://ms.mix.net.ua:1935/live/camera130.stream
rtmp://ms.mix.net.ua:1935/live/camera171.stream
rtmp://ms.mix.net.ua:1935/live/camera172.stream

I try to open them using next code:

```
RtmpDataSourceFactory rtmpDataSourceFactory = new RtmpDataSourceFactory();
MediaSource mediaSource = new ExtractorMediaSource.Factory(rtmpDataSourceFactory).createMediaSource(url);
```

Tested on Android 9, Galaxy S9 device.

**Comment by vavadhani** [comment] 2019-07-16 10:38
Duplicate of #4319 

Fix is in progress in librtmp-client.

**Comment by ojw28** [comment] 2019-07-16 10:50
Closing as duplicate. Thanks @vavadhani .

**Closed as completed by ojw28** 2019-07-16 10:50 UTC
Labels: duplicate
