### ISSUE TITLE
Load different video while playing

### ISSUE THREAD

**Issue by samek** [google/ExoPlayer#85] opened 2014-10-21 09:17 UTC
My question is how would I approach this. 
I would need to load different video while current video is playing. 

Since player is created from renderer and url is added to that renderer how would I do something like: 

In PlayerControl method seekTo() I would need to call 
player.stop();
player.loadUrl(); //new url depending on seek time//
player.play();

**Comment by hansvdg** [comment] 2015-03-16 20:31
Since the previous comment a lot has changed in the library, on the current master branch I do not experience the issue mentioned above.
In the dev branch of December I was not able to create a reproducable scenario.

**Comment by PrasadShirsath** [comment] 2015-08-13 22:36
Anybody able to play different video while one is playing?

**Comment by NoGirlFriendException** [comment] 2015-12-08 12:26
why have no answer? ???

**Comment by chile-zhong** [comment] 2016-03-03 05:54
same question too, but dont know how to do ,any progress?

**Comment by cmdkhh** [comment] 2016-03-04 21:08
We have been able to play multiple videos at a time as well as play a video while we buffer another one to create a playlist. 
Your questions were a bit broad but if you have something specific I would be happy to help.

**Comment by andrewlewis** [comment] 2016-04-09 14:13
We are working on built-in support for playlists, tracked by #1270. The first comment in this issue will probably be addressed by that enhancement.

**Closed by andrewlewis** 2016-04-09 14:13 UTC
Labels: question
