### ISSUE TITLE
Video caching but not playing after    "  val dataSpec = DataSpec(videoUri,0,100*1024,null) " please help me with this

### ISSUE THREAD

**Issue by adnan94** [google/ExoPlayer#9735] opened 2021-11-26 11:22 UTC
Here is my VideoPlayerManagerCode

  public static StoriesVideoPlayManager getInstance() {
        if (instance == null) {
            synchronized (StoriesVideoPlayManager.class) {
                if (instance == null) {
                    httpDataSourceFactory = new DefaultHttpDataSource.Factory()
                            .setAllowCrossProtocolRedirects(true);

                    trackSelector = new DefaultTrackSelector(TelloApplication.applicationContext);

                    cacheDataSourceFactory = new CacheDataSource.Factory()
                            .setCache(simpleCache)
                            .setUpstreamDataSourceFactory(httpDataSourceFactory)
                            .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR);
                    instance = new StoriesVideoPlayManager();
Util.getUserAgent(TelloApplication.applicationContext, "TelloTalkStoriesPlayer"), bandwidthMeter);
                    player = new SimpleExoPlayer.Builder(TelloApplication.getInstance()).setMediaSourceFactory(new DefaultMediaSourceFactory(cacheDataSourceFactory)).build();
                    player.addAnalyticsListener(new EventLogger(trackSelector));

   MediaItem mediaItem = MediaItem.fromUri(uri);
        mediaSource = new ProgressiveMediaSource.Factory(cacheDataSourceFactory).createMediaSource(mediaItem);
        player.setPlayWhenReady(isPlay);
        player.setMediaSource(mediaSource, true);
        player.prepare();
     
                }
            }
        }
        return instance;
    }

here is video cache service

 override fun onHandleIntent(intent: Intent?) {
        mContext = applicationContext

        httpDataSourceFactory = DefaultHttpDataSource.Factory()
            .setAllowCrossProtocolRedirects(true)

        defaultDataSourceFactory = DefaultDataSourceFactory(
            this, httpDataSourceFactory
        )

        cacheDataSourceFactory = CacheDataSource.Factory()
            .setCache(simpleCache)
            .setUpstreamDataSourceFactory(httpDataSourceFactory)
            .createDataSource()

        if (intent != null) {
            val extras = intent.extras
            videosList = extras?.getStringArrayList(VIDEO_LIST)

            if (!videosList.isNullOrEmpty()) {
                preCacheVideo(videosList)
            }
        }
    }

    private fun preCacheVideo(videosList: ArrayList<String>?) {
        var videoUrl: String? = null
        if (!videosList.isNullOrEmpty()) {
            videoUrl = videosList[0]
            videosList.removeAt(0)
        } else {
            stopSelf()
        }
        if (!videoUrl.isNullOrBlank()) {
            val videoUri = Uri.parse(videoUrl)
            //set length of video according to requirement
            val dataSpec = DataSpec(videoUri,0,100*1024,null)
            val progressListener =
                CacheWriter.ProgressListener { requestLength, bytesCached, newBytesCached ->
                    val downloadPercentage: Double = (bytesCached * 100.0
                            / requestLength)
                    Log.d(TAG, "downloadPercentage $downloadPercentage requestLength: $requestLength")
                    Log.d(TAG, "downloadPercentage $downloadPercentage requestLength: $bytesCached")
                    Log.d(TAG, "downloadPercentage $downloadPercentage requestLength: $newBytesCached")
                    Log.d(TAG, "downloadPercentage $downloadPercentage videoUri: $videoUri")
                    Log.d(TAG, "downloadPercentage $downloadPercentage Space: ${simpleCache.keys}")
                }

            cachingJob = GlobalScope.launch(Dispatchers.IO) {
                cacheVideo(dataSpec, progressListener)
                preCacheVideo(videosList)
            }
        }
    }

    private fun cacheVideo(
        dataSpec: DataSpec,
        progressListener: CacheWriter.ProgressListener
    ) {
        runCatching {
            runCatching {
                CacheWriter(
                    cacheDataSourceFactory,
                    dataSpec,
                    true,
                    null,
                    progressListener
                ).cache()
            }.onFailure {
                it.printStackTrace()
            }
        }
    }

**Comment by adnan94** [comment] 2021-11-26 11:58
@marcbaechinger

**Comment by ojw28** [comment] 2021-11-29 16:57
Closing as duplicate of https://github.com/google/ExoPlayer/issues/9738

**Closed as completed by ojw28** 2021-11-29 16:57 UTC
Labels: question
