### ISSUE TITLE
Exoplayer : Playback error

### ISSUE THREAD

**Issue by AnjliPatel** [google/ExoPlayer#5516] opened 2019-02-14 13:37 UTC
I had recorded video of 1920 X 1080,1280 X720 size on device and Its stored in internal sotrage, now this  video unable to play, below you can find bug report and detail.
Device name: samsung galaxy j3 os 8.1.0,samsung S7 edge os 8.0.0, samsung s6
below 1920 X 1080 are worked properly,but using  above and this size got error like "playback error" while initialize exoplayer every time.
version of exoplayer : 2.9.0

```
E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1935)
        at android.media.MediaCodec.configure(MediaCodec.java:1864)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

**Comment by marcbaechinger** [comment] 2019-02-14 15:53
Thanks. This seems to be a codec issue on these devices with the Exynos codecs.
I mark it as a a device specific issue for now. I'd like to confirm this.

Can you please provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #5516".

**Comment by AnjliPatel** [comment] 2019-02-15 06:46
Thanks,
 Using external link its play perfectly, The error occurs when I recorded a video by the device  and play using exoplayer got an error like "playback error"

**Comment by marcbaechinger** [comment] 2019-02-15 10:48
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by AnjliPatel** [comment] 2019-02-20 07:09
Can you tell me what information you need? I will try my best to provide every information.

**Comment by marcbaechinger** [comment] 2019-02-21 21:57
The best procedure is to reproduce the error and then right after the exception has been thrown take a bug report. There are different ways to do that. I prefer the command line and do a

```
adb bugreport
```

This page describes other ways if you prefer something else: https://developer.android.com/studio/debug/bug-report

**Comment by AnjliPatel** [comment] 2019-02-22 11:53
[bugreport-2019-02-22-17-19-31.zip](https://github.com/google/ExoPlayer/files/2893783/bugreport-2019-02-22-17-19-31.zip)
I have generated bug report as per your instructions, please find attachment.

**Comment by dhaval-sunflowersolutions** [comment] 2019-02-26 15:18
I am facing the same issue. Do we have any update?

**Comment by marcbaechinger** [comment] 2019-02-26 15:38
Thanks for the bugreport. When looking into it I found these lines just before the exception:

```
17:19:18.310 media  2676  1766 I ResourceManagerService: ResourceManagerService checkCodecCapacity pid 20056 clientId 3476169120 useExtended 0 
02-22 17:19:18.310 media  2676  1766 I ResourceManagerService: fail to checkCodecCapacity ( res 2073600, remained 1935360, extended 0 )
02-22 17:19:18.310 10663 20056 20693 I MediaCodec: failed to configure codec bacause of codec capacity
```

It seems like the codec is running out of capacity. It's not obvious what the reason is. I searched our internal codebase and haven't found that error message (the word 'bacause' would be pretty obvious). So this message comes from the OEM implementation.

Codecs are shared resources on a device, so it might be that another app does compete at that moment. You are saying that you are capturing and encoding the video from the camera. So as a wild guess it may be that some resources are not yet completely freed on encoding side.

You can try verifying my guesses by making sure that you have freed all resources after capturing, make sure you are not allocating codec resources in other ways (like with a second player) or using a video which needs less resources (downsized) to see if my theory holds somehow.

**Comment by marcbaechinger** [comment] 2019-02-26 15:41
@dhaval-sunflowersolutions Can you elaborate on "the same issue"? :) Same device, same codec, same error code, identical stack traces?

Can you please send a bug report like AnjliPatel sent us? (see comments above)

**Comment by AnjliPatel** [comment] 2019-02-27 07:11
Thanks @marcbaechinger  
I have solved my issue,
there was a resource release problem, after releasing resources its works fine.

**Comment by marcbaechinger** [comment] 2019-03-06 16:58
Cool! Great to hear you have that sorted. I close this issue. Please reopen if you think we can ad something.

**Closed as completed by marcbaechinger** 2019-03-06 16:58 UTC
Labels: need more info
