### ISSUE TITLE
ClippingMediaSource requires isPrepared flag to correctly check clipping assertions

### ISSUE THREAD

**Issue by soygabimoreno** [google/ExoPlayer#5924] opened 2019-05-21 11:46 UTC
### Content description
When creating a ClippingMediaSource with an HTTP MediaSource for an AAC format source it fails to play and gives the following error, but if the startPosition=0 and the endPosition is the total duration of the song it works, meaning when it doesn't actually clip anything, but setting these parameters two trimming values will result in this error:

```
E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.source.ClippingMediaPeriod.selectTracks(ClippingMediaPeriod.java:115)
        at com.google.android.exoplayer2.source.DeferredMediaPeriod.selectTracks(DeferredMediaPeriod.java:163)
        at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:271)
        at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:233)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:165)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1632)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:348)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:165)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

### Link to test content
[c4ca4238a0b923820dcc509a6f75849b.zip](https://github.com/google/ExoPlayer/files/3202330/c4ca4238a0b923820dcc509a6f75849b.zip)

### Version of ExoPlayer being used
2.10.0

### Device(s) and version(s) of Android being used
Tested on Android 8.0 and 9.0 on Emulators then Huawei, Samsung and Nexus physical devices.

**Comment by tonihei** [comment] 2019-05-22 11:49
The issue is that the media is not seekable and thus it's not possible to actually start at a non-zero position. We should catch this problem earlier though and throw an IllegalClippingException instead.

**Comment by tonihei** [comment] 2019-05-22 12:01
As it turns out, we can't catch this earlier at the moment because `ClippingMediaSource` doesn't know whether the child source is not seekable because it's actually not seekable or because we don't have enough information yet. At the moment, we only check the clipping conditions if the duration of the child source is known, under the assumption that a known duration means that all information is available. However, for this particular AAC example, we never know the duration, so the check is not executed.

This problem can be fixed by adding a new flag to `Timeline` which indicates whether we are still waiting for information. Changing to `enhancement` to track adding this.

**Comment by soygabimoreno** [comment] 2019-05-22 12:10
Thank you so much, @tonihei!

**Comment by shaji-Dev** [comment] 2019-05-24 20:02
I´m having the same issue, tried multiple AAC files and non of them work, any quick fix for this?

**Comment by tonihei** [comment] 2019-05-28 08:13
@shaji-Dev  This is not about fixing clipping for AAC. If your file is not seekable, then it's also not clippable. This enhancement is just about catching this problem early on with a good error message instead of an obscure one later on.

**Comment by tonihei** [comment] 2020-03-12 14:04
Closing because issue is fixed now.

**Closed as completed by tonihei** 2020-03-12 14:04 UTC
Labels: enhancement, content not playing

**Comment by soygabimoreno** [comment] 2020-03-13 06:24
Thank you so much!! :rocket:
