### ISSUE TITLE
Video with low frame rate

### ISSUE THREAD

**Issue by ptran-gpfw** [google/ExoPlayer#411] opened 2015-04-23 01:35 UTC
How’s it going? I have a question about playing back a video with low frame rate.
It is an MP4 with 9 fps.

When using FrameworkSampleSource + MediaCodec{Audio,Video}TrackRenderer, the audio can be heard but the video frames do not play.

It seems the culprit is in `MediaCodecVideoTrackRenderer#processOutputBuffer`, where there is the check before calling `dropOutputBuffer`:

    if (earlyUs < -30000) {
      // We're more than 30ms late rendering the frame.
      dropOutputBuffer(codec, bufferIndex);
      return true;
    }

This code seems to expect frame rate to be no lower than 30 fps.

I put a log statement here and the earlyUs values range for the 9fps video ranges from -211000 to -190000.

I have a fix that that decreases the threshold like so:

    if (earlyUs < -300000) {

I thought frame rate might be available in MediaFormat using KEY_FRAME_RATE but its not populated.

For now I’ll use my own modified copy of MediaCodecVideoTrackRenderer but long-term it would be nice to parameterize the earlyUs threshold. Ideally it could updated dynamically after the decoding pipeline is already playing.

Thanks!

**Comment by ojw28** [comment] 2015-04-23 09:43
I don't think that code imposes any expectation on the video frame-rate. It just says that a frame should be dropped if we're more than 30ms late rendering it. Even if the video were 1fps, we should still be able to render each frame on time, and no more than 30ms late. Meeting this requirement is significantly easier for lower fps content, because less work needs to be done.

So I think something else is wrong either with the player or the media. It may well be that FrameworkSampleSource doesn't provide the video frames early enough. Changing the condition as you have done will fix the frames being dropped, but they'll still be rendered later than they're supposed to be. You should try switching to ExtractorSampleSource with Mp4Extractor on the dev branch. My hunch is that you'll find it works fine.

If all else fails, please provide the media, if possible.

**Comment by ptran-gpfw** [comment] 2015-04-23 16:06
I'll try ExtractorSampleSource with Mp4Extractor, thanks!


Btw, do you have an idea when those components will be merged to master? Just roughly speaking... i.e., days, weeks or months?

________________________________

**Comment by ojw28** [comment] 2015-04-27 22:24
Marking as closed for now. Feel free to re-open if you see the same with Mp4Extractor (although if that's the case, we'll probably need the media to reproduce).

**Closed by ojw28** 2015-04-27 22:24 UTC

**Comment by ptran-gpfw** [comment] 2015-04-27 23:26
Just tested, Mp4Extractor works fine with my 9fps video, thanks!
