### ISSUE TITLE
Player crashes with UnsupportedDrmException when initialising DrmSessionManager with wrong Drm UUID scheme

### ISSUE THREAD

**Issue by DimaSladkin** [google/ExoPlayer#7164] opened 2020-03-31 08:34 UTC
### [REQUIRED] Issue description
Player crashes when drm uuid scheme is invalid. 

Since version 2.11.0 initialization of `DrmSessionManager` requires `ExoMediaDrm.Provider` instead of an instance directly. When `FrameworkMediaDrm` is getting initialized, it can throw `UnsupportedSchemeException` which then can be handled and restart player with correct scheme uuid. Therefore when `FrameworkMediaDrm.newInstance(providedUUID)` throwing this exception in provider it can not be handled and player crashes. 

`DefaultDrmSessionManager.Builder()
            .setUuidAndExoMediaDrmProvider(
                uuid,
                ExoMediaDrm.Provider { providedUUID ->
                    FrameworkMediaDrm.newInstance(providedUUID)
                }
            )
            .build(drmCallback)`

To avoid this I am trying to create an instance of `FrameworkMediaDrm` before init of `DrmSessionManager` and see if there is no such exception occurred. 

`try {
            FrameworkMediaDrm.newInstance(uuid)
            true
        } catch (e: UnsupportedDrmException) {
            false
        }`

### [REQUIRED] Reproduction steps
Init DrmSession with wrong drm uuid scheme. Start playback. 

To try it out just put UUID.randomUUID() to the DrmSessionManager builder.

### [REQUIRED] A full bug report captured from the device
`Fatal Exception: android.media.MediaDrm$MediaDrmStateException: Failed to set property: Unsupported scheme or data format
       at android.media.MediaDrm.setPropertyString(MediaDrm.java)
       at com.google.android.exoplayer2.drm.FrameworkMediaDrm.setPropertyString + 210(FrameworkMediaDrm.java:210)
       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.setPropertyString + 294(DefaultDrmSessionManager.java:294)
       at com.glomex.vvsplayer.player.MediaSourceBuilder.buildDrmSessionManager + 190(MediaSourceBuilder.java:190)
       at com.glomex.vvsplayer.player.ExoPlayerInterfaceImpl.getDrmSessionManager + 492(ExoPlayerInterfaceImpl.java:492)
       at com.glomex.vvsplayer.player.ExoPlayerInterfaceImpl.initPlayer + 443(ExoPlayerInterfaceImpl.java:443)
       at com.glomex.vvsplayer.player.ExoPlayerInterfaceImpl.setContent + 270(ExoPlayerInterfaceImpl.java:270)
       at com.glomex.vvsplayer.player_api.PlayerApiStrategy.setPlayerContent + 437(PlayerApiStrategy.java:437)
       at com.glomex.vvsplayer.player_api.PlayerApiStrategy.setPlayerContent$default + 414(PlayerApiStrategy.java:414)
       at com.glomex.vvsplayer.player_api.PlayerApiStrategy.loadVideoBundle + 95(PlayerApiStrategy.java:95)
       at com.glomex.vvsplayer.player_api.PlayerApi.loadVideoBundle + 585(PlayerApi.java:585)
       at com.glomex.vvsplayer.player_api.PlayerApi.onVideoRetrieved + 557(PlayerApi.java:557)
       at com.glomex.vvsplayer.player_api.PlayerApi.access$onVideoRetrieved + 57(PlayerApi.java:57)
       at com.glomex.vvsplayer.player_api.PlayerApi$startVideoFetching$onVideoDataReceivedListener$1.onReceived + 490(PlayerApi.java:490)
       at com.glomex.vvsplayer.toolkit.VideoDataPublisher.maybeEmitVideoData + 31(VideoDataPublisher.java:31)
       at com.glomex.vvsplayer.toolkit.VideoDataPublisher.onVideoSourceReceived$vvsplayer_release + 22(VideoDataPublisher.java:22)
       at com.glomex.vvsplayer.toolkit.PlayerToolkitImpl$fetchContent$1$1.invokeSuspend + 448(PlayerToolkitImpl.java:448)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith + 33(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run + 241(DispatchedTask.java:241)
       at android.os.Handler.handleCallback + 751(Handler.java:751)
       at android.os.Handler.dispatchMessage + 95(Handler.java:95)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6186(ActivityThread.java:6186)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 889(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main + 779(ZygoteInit.java:779)`

### [REQUIRED] Version of ExoPlayer being used
2.11.0, 2.11.2, 2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Every device

**Comment by AquilesCanta** [comment] 2020-04-03 13:08
Seems to me like a duplicate of #7012.

**Closed as completed by AquilesCanta** 2020-04-03 13:08 UTC
Labels: duplicate
