### ISSUE TITLE
MediaCodecRenderer$DecoderInitializationException exception on multiperiod Dash streams

### ISSUE THREAD

**Issue by danielgliga3ss** [google/ExoPlayer#10076] opened 2022-03-15 15:02 UTC
We are getting this exception when trying to startover multiperiod dash streams (clear->secure)
`java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
`
 and then
`E/MediaCodecVideoRenderer: Video codec error
      com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome2.secure, Format(V0, null, null, video/avc, avc1.640028, 3659472, null, [1920, 1080, 25.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:989)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:540)`
        
Usually, when you start the stream the first time it works fine but the exception appears if you start over from the beginning and wait for the end of the first period or if you play another similar stream type (multiperiod dash).

We also contacted the device manufacturer and they said that this is due to the fact that the surface is already connected (probably not released by Exoplayer) when trying to connect to the surface.
`2022-03-14 17:46:39.986 26033-26428/se.tele2.tvhubmini D/SurfaceUtils: connecting to surface 0xeea8fbf8, reason connectToSurface
2022-03-14 17:46:39.986 22460-22572/? E/BufferQueueProducer: [SurfaceView - se.tele2.tvhubmini/tv.threess.threeready.ui.generic.activity.MainActivity#0](id:57bc00000009,api:3,p:26033,c:22460) connect: already connected (cur=3 req=3)
2022-03-14 17:46:39.987 26033-26428/se.tele2.tvhubmini E/SurfaceUtils: Failed to connect to surface 0xeea8fbf8, err -22
2022-03-14 17:46:39.987 26033-26428/se.tele2.tvhubmini E/MediaCodec: nativeWindowConnect returned an error: Invalid argument (-22)`

Logs:
[logs.txt](https://github.com/google/ExoPlayer/files/8254470/logs.txt)
Bug report:
[bugreport-SEI700TE-RTT0.210618.003-2022-03-14-17-47-28.zip](https://github.com/google/ExoPlayer/files/8254473/bugreport-SEI700TE-RTT0.210618.003-2022-03-14-17-47-28.zip)

Manifest:
[manifest.txt](https://github.com/google/ExoPlayer/files/8254532/manifest.txt)

ExoPlayer version: 2.16.1
SEI Robotics SEI700TE (https://www.androidtv-guide.com/pay-tv-provider/tele2-tv-hub-mini/) -> Android 11

**Comment by icbaker** [comment] 2022-03-15 17:21
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/8696. The workaround for that is included in 2.17.0.

**Closed as completed by icbaker** 2022-03-15 17:21 UTC
Labels: duplicate

**Comment by icbaker** [comment] 2022-03-15 17:28
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/8696. The workaround for that is included in 2.17.0.
