### ISSUE TITLE
Close caption: By default  m3u8  URL  has close caption and turn off by default How to turn on manually

### ISSUE THREAD

**Issue by sathishkumar1392** [google/ExoPlayer#4045] opened 2018-03-27 14:12 UTC
**Issue description**

Close caption: y default m3u8 URL has close caption and turn off by default How to turn on manually.
My code was turn manually 
 trackSelector.setRendererDisabled(2, false);

**Reproduction steps**

Parse HLS URL with transcription enabled to exoplayer

Audio closed caption
https://s3-eu-west-1.amazonaws.com/cyrano-temp/test-audio/aa10a5e5-0d88-dac7-400f-f20a7dce6841.m3u8

**Version of ExoPlayer being used**

Exoplayer version 2.6.0

**Device(s) and version(s) of Android being used**

Device: LG Nexus,
OS: Android 8.

**Comment by tonihei** [comment] 2018-03-27 14:14
Duplicate of #3998.

**Closed as completed by tonihei** 2018-03-27 14:14 UTC
