### ISSUE TITLE
DefaultDataSourceFactory not found

### ISSUE THREAD

**Issue by fluxxion82** [google/ExoPlayer#5808] opened 2019-04-26 22:58 UTC
Before filing a bug:
-----------------------
- Search existing issues, including issues that are closed.
- Consult our FAQs, supported devices and supported formats pages. These can be
  found at https://google.github.io/ExoPlayer/.
- Rule out issues in your own code. A good way to do this is to try and
  reproduce the issue in the ExoPlayer demo app. Information about the ExoPlayer
  demo app can be found here:
  http://google.github.io/ExoPlayer/demo-application.html.

When reporting a bug:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Issue description
Added the exoplayer library(full version, 2.9.6) and code to project. Followed the guide, copied code straight from demo app, but whenever I try to build or run the app, I get an exception when task 'app:kaptDevDebugKotlin' is run. Here is the exception:

```
e: error: cannot access DefaultDataSourceFactory
  class file for com.google.android.exoplayer2.upstream.DefaultDataSourceFactory not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.android.exoplayer2.upstream.DefaultDataSourceFactory not found
e: java.lang.IllegalStateException: Should not be called!
	at org.jetbrains.kotlin.types.ErrorUtils$1.getPackage(ErrorUtils.java:86)
	at org.jetbrains.kotlin.descriptors.DescriptorUtilKt.resolveClassByFqName(descriptorUtil.kt:21)
	at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion$checkCompilerArguments$1.invoke(ExperimentalUsageChecker.kt:222)
	at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion.checkCompilerArguments(ExperimentalUsageChecker.kt:245)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:108)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:375)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:123)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:159)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:57)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:442)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:102)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:1013)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:102)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:1055)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:1012)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:441)
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### [REQUIRED] Reproduction steps
Pretty much copied straight from demo player:
```
override fun getDataSourceFactory(): DataSource.Factory {
        val upstreamFactory = DefaultDataSourceFactory(application, buildHttpDataSourceFactory())
        return buildReadOnlyCacheDataSource(upstreamFactory, getDownloadCache())
    }

    private fun buildHttpDataSourceFactory(): HttpDataSource.Factory =
        DefaultHttpDataSourceFactory(Util.getUserAgent(application, "Demo"))

    @Synchronized
    private fun getDownloadCache(): Cache {
        if (downloadCache == null) {
            val downloadContentDirectory = getMediaPath()
            downloadCache = SimpleCache(downloadContentDirectory, NoOpCacheEvictor())
        }
        return downloadCache!!
    }

    private fun buildReadOnlyCacheDataSource(
        upstreamFactory: DefaultDataSourceFactory, cache: Cache
    ): CacheDataSourceFactory {
        return CacheDataSourceFactory(
            cache,
            upstreamFactory,
            FileDataSourceFactory(),
            null,
            CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR,
            null
        )
    }
```

Added java 8 support

### [REQUIRED] Link to test content
N/A - code doesn't compile

### [REQUIRED] A full bug report captured from the device
N/A - can't even compile code

### [REQUIRED] Version of ExoPlayer being used
com.google.android.exoplayer:exoplayer:2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Using Android Studio 3.5 canary 13 and Android Studio 3.4
minSdkVersion 23
tried both kotlin 1.3.21 and 1.3.31 (using kotlin coroutines also)
using dagger and dagger kotlin android-processor 2.22.1
androidx libs
...

**Comment by AquilesCanta** [comment] 2019-04-29 09:47
Please create a minimal sample project in github that reproduces the issue for us to have a look.

**Comment by ojw28** [comment] 2019-05-15 20:18
Closing due to lack of information.

**Closed as completed by ojw28** 2019-05-15 20:18 UTC
Labels: question, need more info
