### ISSUE TITLE
merging many ClippingMediaSource

### ISSUE THREAD

**Issue by ValeraC** [google/ExoPlayer#4912] opened 2018-10-04 20:52 UTC
### Issue description
I have video and audio(webm and ogg). I have to make next structure:
start video part -> "freeze frame(or one frame) part" -> finish video part and sync them all with audio, like this:
 (duration)
audio start == video start
audio finish == video finish
else audio will play for "one frame"

PROBLEM:
When "finish part" start playing audio starts from "start part". For example:
start part play from 0 to 10 seconds,
middle part play from 10 to 20 seconds
finish part play from 20 to 30 seconds but in my case it starts playing at  10 seconds (equal to "clipAt" see code )

My code:
```
long clipAt = _;
long videoLength = _;
long audioLength = _;

    MediaSource audioSource =  new ExtractorMediaSource(Uri.parse(audioURL),
                    dataSourceFactory, extractorsFactory, null, null);

    MediaSource videoSource = new ExtractorMediaSource(Uri.parse(videoURL),
                    dataSourceFactory, extractorsFactory, null, null);

    long a =  audioLength - (videoLength - clipAt);
    MergingMediaSource start = new MergingMediaSource(
                    new ClippingMediaSource(videoSource,0,clipAt),
                    new ClippingMediaSource(audioSource,0,a));

    MergingMediaSource finish= new MergingMediaSource(
                  new ClippingMediaSource(videoSource,clipAt,C.TIME_END_OF_SOURCE),
                  new ClippingMediaSource(audioSource,a,C.TIME_END_OF_SOURCE));

  concatenatedSource.addMediaSource(start);
  concatenatedSource.addMediaSource(finish);
```

I have also tried to create new video and audio MediaSource  for  finish part, but problem exists anyway!
If at first add audio media source to MergingMediaSource and then video -> audio play as expected. but video doesn't play(freezed).

### Reproduction steps
Invent stupid structure and kill all your day!

### Link to test content
I use webm with deleted audio track for video and ogg for audio

### Version of ExoPlayer being used
2.8.2

### Device(s) and version(s) of Android being used
xiaomi redmi note 4.
Android 7.0

**Comment by AquilesCanta** [comment] 2018-10-05 14:20
I don't understand the problem here. 

I think the best way to go is that you provide the sample media. I will then try the code you posted up here and reach back. If I notice anything weird, then we can diagnose as a bug. If I observe it's working as intended, then we can work on the issue description. Otherwise this consumes too much time doing guesswork.

**Comment by AquilesCanta** [comment] 2018-10-05 14:24
One extra thing to check is that the ogg audio you are using is seekable. If you play the ogg audio alone, can you seek in it? If not, you'll have to add metadata to enable seeking in the file.

**Comment by ojw28** [comment] 2018-11-23 21:47
Closing due to lack of follow up.

**Closed as completed by ojw28** 2018-11-23 21:47 UTC
Labels: question, need more info
