### ISSUE TITLE
Exact seeking for mp3

### ISSUE THREAD

**Issue by zjamshidi** [google/ExoPlayer#8361] opened 2020-12-17 11:20 UTC
To be continued from issue #7355: 
I updated the ExoPlayer to v2.12.2 and changed my code to:
```
        // demo: PlayerActivity.initializePlayer
        RenderersFactory renderersFactory =
                PlayerUtil.buildRenderersFactory(/* context= */ this);

        // accurate seeking: https://github.com/google/ExoPlayer/issues/7355
        DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory()
                .setMp3ExtractorFlags(Mp3Extractor.FLAG_ENABLE_INDEX_SEEKING);
        MediaSourceFactory mediaSourceFactory =
                new ProgressiveMediaSource.Factory(dataSourceFactory, extractorsFactory);

        // demo: PlayerActivity.initializePlayer
        DefaultTrackSelector trackSelector = new DefaultTrackSelector(/* context= */ this);
        trackSelector.setParameters(trackSelectorParameters);

        exoPlayer = new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
                .setMediaSourceFactory(mediaSourceFactory)
                .setTrackSelector(trackSelector)
                .build();

        // play the audio
        Uri uri = Uri.parse(mAudioUrl);

        @Nullable
        String adaptiveMimeType =
                Util.getAdaptiveMimeTypeForContentType(Util.inferContentType(uri, null));

        MediaItem mediaItem =
                new MediaItem.Builder()
                        .setUri(uri)
                        .setMediaMetadata(new MediaMetadata.Builder().setTitle(mItem.getTitle()).build())
                        .setMimeType(adaptiveMimeType)
                        .build();

        exoPlayer.addListener(eventListener);
        exoPlayer.setAudioAttributes(AudioAttributes.DEFAULT, /* handleAudioFocus= */ true);
        exoPlayer.setPlayWhenReady(isPlaying);
        exoPlayer.seekTo(seekTo);
        exoPlayer.setMediaItem(mediaItem);
        exoPlayer.prepare();
```

seeking is too slow and still it's not accurate. @krocard would you please help me find out why?

**Comment by tonihei** [comment] 2020-12-17 16:58
The flag is [documented](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/mp3/Mp3Extractor.html#FLAG_ENABLE_INDEX_SEEKING) that it should only be used if your file is small because it adds more initial computation before playback can start. That's probably why it appears to be slow.

To investigate why your seeking may still not be accurate, we'll probably need an example file and reproduction steps, e.g. where you seeked to and how you decided that it's not accurate. Assigning to @kim-vde in the meantime in case she can provide more details without having an example file.

**Comment by kim-vde** [comment] 2021-01-05 09:51
Indeed, I need an example file and some reproduction steps using our [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main). Thanks.

**Comment by zjamshidi** [comment] 2021-01-25 06:34
Sorry for my late reply. Since it imposes a long delay, we decided to ignore this exact seeking for now. If it becomes critical, we will check it later.
Thanks by the way

**Closed as completed** 2021-01-25 09:42 UTC
Labels: bug
