### ISSUE TITLE
sound hickup when changing to other stream on Samsung S7 EDGE

### ISSUE THREAD

**Issue by marcinOz** [google/ExoPlayer#1669] opened 2016-07-11 13:42 UTC
As in title sound hickup/deformation when changing to other stream or changing video quality on Samsung S7 EDGE. Visible in demo app eg. "Widevine Dash Policy Tests (GTS)"

Logs:
[logs.txt](https://github.com/google/ExoPlayer/files/357183/logs.txt)

**Comment by m-scheepers** [comment] 2016-11-17 14:20
This issue is also observed in recent versions of Exoplayer 1.x for Samsung S7 EDGE

Is there any way to avoid these issues?

**Comment by ojw28** [comment] 2016-11-25 16:09
I can reproduce the issue. It appears to occur only (or at least primarily) with encrypted content, where-as clear content appears to be unaffected.

**Comment by ojw28** [comment] 2016-11-25 16:53
I'm not sure there's much we can do to fix this at the ExoPlayer level. I'll pass the issue to Samsung; hopefully they'll be able to fix it in a future platform update.

**Comment by m-scheepers** [comment] 2016-11-25 17:01
Thanks for this feedback. Would you be able to provide a reference for the ticket at Samsung level? One of our customers will then also address this to Samsung if this relates to S7 device

Does this issue also occur in Exoplayer 2.x?

**Comment by ojw28** [comment] 2016-11-25 17:11
I was testing using 2.x and the issue still reproduces. I think the problem is in the underlying platform, and I wasn't able to come up with a workaround for it. I've reported through an internal channel and therefore there's no publicly visible ticket/reference. I'd suggest your customers' file their own ticket with Samsung, referencing this issue.

**Comment by ojw28** [comment] 2017-01-13 18:10
Samsung tell me this is fixed in their Nougat update.

**Closed as completed by ojw28** 2017-01-13 18:10 UTC
Labels: bug: device specific

**Comment by m-scheepers** [comment] 2017-01-13 18:27
Thanks. Our customer is currently assessing update to Nougat. I assume issue is fixed then.
