### ISSUE TITLE
Request: for PlayerView, add CTOR that has the surfaceType as parameter

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5401] opened 2019-01-17 10:38 UTC
Currently, if we wish to dynamically create a new PlayerView instance, it will always be of the type `SURFACE_TYPE_SURFACE_VIEW` , because there is only one CTOR that is meant to be used dynamically, which is `PlayerView(Context context)`, and it doesn't have an initialization function that can be overridden or called to handle it either.

Please add a new CTOR or initialization function for PlayerView, so that we could dynamically set if it will use SurfaceView or TextureView.

**Comment by ojw28** [comment] 2019-01-17 10:44
Duplicate of #5387.

As a general point, please consider your tone when contributing to this issue tracker. We've already made a decision about this and clearly explained why we don't believe this is a significant problem. The fact you disagree doesn't mean you should file another issue, wasting our time and the many people who receive email notifications from this tracker. This isn't the only example of you being unnecessarily argumentative on this issue tracker, either. See for example (e.g. #4599). Thanks.

**Closed as completed by ojw28** 2019-01-17 10:44 UTC
Labels: duplicate, question

**Comment by AndroidDeveloperLB** [comment] 2019-01-17 11:24
It's not a duplicate. It's a more specific request.
And there is no special tone here. I stated the facts alone.
And the issue there was closed without letting me answer, so I can't do anything about it.
I don't understand what I've done wrong here or there. I just write a feature request. If I've somehow hurt your feelings, I'm sorry.

**Comment by AndroidDeveloperLB** [comment] 2019-01-17 11:25
Why close this request though? What is the reason of not allowing us to set which type to use via a CTOR ? Shouldn't we have a choice of creating PlayerView dynamically instead of via a layout, like we have for other views?

**Comment by AndroidDeveloperLB** [comment] 2019-01-17 11:27
You even wrote there that you could add it, so I decided to write a more specific request:
"We could also provide PlayerView constructors that let you pass the surface type when you're instantiating a view directly in code,
"

**Comment by AndroidDeveloperLB** [comment] 2019-01-17 13:28
Also, just because you don't see other people request it, doesn't mean that it's not useful and some people would want it. It also isn't a measure of whether you will accept it or not. 
I've written a lot on the issue tracker, about both requests and bugs. See how much popularity I got on those, and yet Google still hasn't handled them:

https://issuetracker.google.com/issues/117486314
https://issuetracker.google.com/issues/62256231
https://issuetracker.google.com/issues/37010285
https://issuetracker.google.com/issues/112602629
https://issuetracker.google.com/issues/110433612
https://issuetracker.google.com/issues/68454482
https://issuetracker.google.com/issues/110436314
https://issuetracker.google.com/issues/69211494
https://issuetracker.google.com/issues/67187451
