### ISSUE TITLE
ProgressiveMediaSource calls ResolvingDataSource resolveDataSpec 1 time before playing the track, but HlsMediaSource calls resolveDataSpec immediately for the entire list of tracks

### ISSUE THREAD

**Issue by lewan42** [google/ExoPlayer#10921] opened 2023-01-12 10:08 UTC
That’s how we create our Media Source. At the time of receiving playlist we have not information about URI of tracks, so we use resolvingDataFactory

```
val mediaSources = playlist.map {
            HlsMediaSource.Factory(resolvingDataSourceFactory)
                .createMediaSource(
                    MediaItem.Builder().apply {
                        setTag(it)
                        setUri(it.getUri()) // id://track_id -> id://12345
                    }.build()
                )
        }
        mediaSource.setShuffleOrder(createShuffleOrder(true))
        mediaSource.addMediaSources(mediaSources)
        player.prepare(mediaSource, needResetPlayerState, needResetPlayerState)
```
        
Inside resolvingDataFactory we get the track id from the original URI and make a request to the server for a link to the playback file. Which can be mp3 or m3u8. And our problem is that for HlsMediaSource when playing one track, we have a lot requests for all playlist tracks

**Comment by christosts** [comment] 2023-01-13 10:55
Please share what version of ExoPlayer you are using and also a link to your HLS playlist so that we can test/repro.

It sounds like the player is downloading multiple playlists, which is not surprising. The player might need to download multiple playlists to get enough information about the available tracks. There is an improvement on HLS to reduce the amount of playlists downloaded, internally called [chunkless preparation](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6). The feature was enabled by default as of 2.17.0, but doesn't work on all HLS playlists. Hence the ask for ExoPlayer and an HLS playlist.

**Comment by hkarimka** [comment] 2023-01-13 13:54
We first tried on versions
```
    implementation 'com.google.android.exoplayer:exoplayer-core:2.11.1'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.11.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.11.1'
    implementation 'com.google.android.exoplayer:extension-mediasession:2.11.1'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.11.1'
```

Then we updated versions and tried on
```
    implementation 'com.google.android.exoplayer:exoplayer-core:2.18.2'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.18.2'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.18.2'
    implementation 'com.google.android.exoplayer:extension-mediasession:2.18.2'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.18.2'
```
We've got same behaviour on both versions: .mp3 files with ProgressiveMediaSource play as expected (resolving data source only on playing), but with .m3u8 files using HlsMediaSource player resolves whole playlist before playing and starts to play only after that.

Type of mediaSource is only thing we changed, and we expect that they both resolve DataSpecs similarly.

Please tell us what can we try and what's wrong with our code.

 .m3u8 format files additional info:
<img width="173" alt="Снимок экрана 2023-01-13 в 16 48 37" src="https://user-images.githubusercontent.com/43098658/212334929-adf51da4-4d72-4f6d-9367-681a68e56dc5.png">

**Comment by hkarimka** [comment] 2023-01-17 07:15
@christosts do you need our .m3u8 files?

**Comment by christosts** [comment] 2023-01-17 11:14
> do you need our .m3u8 files?

Yes, please share the `m3u8` files. We will load them in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html) in order to play the content and we will inspect what ExoPlayer does. 

Note, If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com with subject "Issue #10921" and then update this issue to indicate you've done this.

**Comment by lewan42** [comment] 2023-01-17 13:07
@christosts we sent the files with subject "Issue 10921"

**Comment by christosts** [comment] 2023-01-17 13:16
In the email, there are 5 playlists but I don't see a multivariant playlist attached. Can you explain in more detail what you give the player as input?

For example,
- is the input a URL to one of the attached files?
- or is the input a URL to multivariant playlist that contains further links to these playlists?

**Comment by lewan42** [comment] 2023-01-17 14:02
From the server we got a list of tracks and displayed them on the screen. Each track has: id, name, list of artists, etc. When the user clicks on the track, we make a request to our server (send id) and get m3u8 file to play. Then we change the URI -> `srcSpec.withUri(Uri.parse(file_m3u8)))`

**Comment by christosts** [comment] 2023-01-17 14:36
Thank you. And to clarify, in the snippet on the description, what is the type of `mediaSource`? Is it a `ConcatenatingMediaSource`?

**Comment by lewan42** [comment] 2023-01-17 14:46
yes, we use ConcatenatingMediaSource

**Comment by christosts** [comment] 2023-01-17 15:16
Ok, so I think the issue is not with HlsMediaSource but with ConcatenatingMediaSource which loads all internal media sources. I believe you are using the media source API incorrectly, it is working as intended for ConcatenatingMediaSource to proactively prepare all added media sources, for example in order to calculate total duration.

Instead of adding all tracks in the  ConcatenatingMediaSource proactively, your app should first get the url to the m3u8 playlist and then ask the player to play one item, i.e. one HlsMediaSource or MediaItem only.

**Comment by hkarimka** [comment] 2023-01-17 16:59
But it works correctly with ConcatenatingMediaSource and ProgressiveMediaSource.Factory.
And we can't add HlsMediaSource only after getting .m3u8 link, because we need to initialize whole playlist on clicking on album / selection etc.
Our scheme is: 
We create 
```
ProgressiveMediaSource.Factory(resolvingDataSourceFactory)
                    .createMediaSource(it.getUri()) // id://1234
```
for each element in list and then using resolvingDataSourceFactory we get actual .mp3 link when item is playing.

Our goal is replace ProgressiveMediaSource by HlsMediaSource, but in that case our resolvingDataSourceFactory resolves whole playlist immediately. 

How can we create MediaItems for whole playlist not using HlsMediaSource in initializing playlist?

**Comment by christosts** [comment] 2023-01-17 17:13
@marcbaechinger can you advise how to use MediaItem / MediaSources for this use case?

**Comment by marcbaechinger** [comment] 2023-01-17 17:39
> But it works correctly with ConcatenatingMediaSource and ProgressiveMediaSource.Factory.

I think this is expected because the `ProgressiveMediaSource` requires the URI only when the media period is created and prepared which is just before playback. Adaptive media sources with a manifest/playlist load the manifest immediately when the source is prepared. That would explain why your resolving data source is called at a different point in time for these types of sources.

> How can we create MediaItems for whole playlist not using HlsMediaSource in initializing playlist? 

I think you can try lazy preparation. With this a source is only prepared when used. This is either when the user seeks to a given media item or when the player is close to an automatic transition to the next item while playback. The disadvantage you may experience with this approach is that the timeline of the player knows the duration (Window.getDurationMs()) of adaptive sources only when these are prepared. I think this should not be a problem for you though, because you would have noticed this with progressive sources as well that get the duration only when the media period is prepared (and actual media data is downloaded).

If you are migrating your app to not use `ConcatenatingMediaSource` anymore but use the playlist API instead, then all the sources are loaded lazily by default. You would then just use `exoPlayer.addMediaSources()`. Your snippet from above would then look like something like this:

```
val mediaItems= playlist.map {
  MediaItem.Builder().apply {
    setTag(it)
    setUri(it.getUri()) // id://track_id -> id://12345
  }.build()
}
exoPlayer.setShuffleOrder(createShuffleOrder(true)) 
exoPlayer.setMediaItems(mediaItems, needResetPlayerState)
player.prepare()
```

You don't need to use `ConcatenatingMediaSource` anymore with the above and I'd recommend moving to the playlist API.

Alternatively, I'd try using the default constructor of `ConcatentatingMediaSource` which has a boolean argument  `useLazyPreparation` to make the preparation lazy. By default this is set to false.

```
public ConcatenatingMediaSource(
      boolean isAtomic,
      boolean useLazyPreparation,
      ShuffleOrder shuffleOrder,
      MediaSource... mediaSources)
```

**Comment by hkarimka** [comment] 2023-01-18 09:37
Thank you a lot! We will try and let you know.

**Comment by lewan42** [comment] 2023-02-07 12:32
@marcbaechinger 
I tried like you said, but now I get a mistake
`Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.MalformedURLException: unknown protocol: id`

I think it’s an expected mistake because I didn’t add `resolvingDataSourceFactory` and I can’t figure out where to add

this is my code
```
var player: ExoPlayer = ExoPlayer.Builder(context).build()
val mediaItems: List<MediaItem> = playlist.map {
    MediaItem.fromUri(it.getUri()) // id://track_id -> id://12345
}
player.setMediaItems(mediaItems)
player.prepare()
```

any help will be helpful

**Comment by marcbaechinger** [comment] 2023-02-07 13:55
You need to set the `DefaultMediaSourceFactory` when building the player and then inject the `ResolvingDataSource.Factory()` to the `DefaultMediaSourceFactory`.

Something like this:

```
ResolvingDataSource.Resolver resolver = new ResolvingDataSource.Resolver() {
    @Override
    public DataSpec resolveDataSpec(DataSpec dataSpec) throws IOException {
        if (dataSpec.uri.getScheme().equals("id")) {
            // do the mapping to the actual URI.
            return dataSpec.buildUpon().setUri(mapUri(dataSpec.uri));
        }
        return dataSpec;
    }
};

ExoPlayer.Builder playerBuilder =
          new ExoPlayer.Builder(/* context= */ this)
              .setMediaSourceFactory(
                  new DefaultMediaSourceFactory(
                      new ResolvingDataSource.Factory(upstreamFactory, resolver)));
Player player = p[layerBuilder.build();
```

**Comment by lewan42** [comment] 2023-02-07 21:27
I did everything you said and Mp3 is played! But hls is not. Here my error
```
2023-02-07 17:11:22.125 15848-16286/com.gogosongs E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:607)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
```

this is my code
`private val dataSourceFactory = DefaultHttpDataSource.Factory()`

```
var player = ExoPlayer.Builder(context)
    .setMediaSourceFactory(
        DefaultMediaSourceFactory(
            ResolvingDataSource.Factory(dataSourceFactory, resolver)
        )
    ).build()
```

in my resolver
```
val mediaItem = MediaItem.fromUri(res.url)
if (res.url.endsWith("mp3")) {

    val mediaSource =
        ProgressiveMediaSource.Factory(dataSourceFactory)
            .createMediaSource(mediaItem)
    player.addMediaSource(mediaSource)

} else {

    val mediaSource =
        HlsMediaSource.Factory(dataSourceFactory)
            .createMediaSource(mediaItem)
    player.addMediaSource(mediaSource)
    player.prepare()

}
srcSpec.withUri(Uri.parse(res.url))
```
Please tell me what I’m doing wrong?

**Comment by marcbaechinger** [comment] 2023-02-08 13:09
I'm not quite sure how you implemented this and I can't really give you 1:1 support for this I'm afraid. 

The error tells that some files that are expected to be media (ts or fmp4) are not recognized. Most likely because these are text files (playlists) or then there is a HTTP error that delivers a HTML error page. I'm guessing here, you need to look into what you are downloading to verify what actually happens.

However, in the case of HLS the player at a minimum needs to download the playlist and some media chunks. So there are multiple requests for multiple files. So a simple if else like the above is probably not sufficient. As far as I understand you are using a URI that starts with `id://`. So you should probably only handle these? Once the HLS playlist is downloaded the player will try to access either further playlist files or media segments that are referenced in the playlist. 

I suggest you look into how playback of a normal HLS works. Figure out how many HTTP URIs are involved for HLS. This dpeneds on the specific HLS stream that you are using. Then you can change your resolver logic to only re-write the URIs that you really want to re-write (my guess is these are those that start with `id://`. All other URIs are already fine?).

**Comment by lewan42** [comment] 2023-02-08 13:32
thanks for answering, I tried to detail my question

**Comment by lewan42** [comment] 2023-02-09 07:59
@marcbaechinger 
I was able to play mp3 and hls files in one playlist. I want to share a solution. Perhaps you can better understand my problem and suggest a better solution.

initially I have not https links and I can’t form a final URI. So I create a URI = id://track_id and install ResolvingDataSource.Factory to change my URI when I know the https link to mp3 or hls.

When I learned the https link to the track, I had to specify MimeTypes [MimeTypes.AUDIO_MPEG = mp3 or MimeTypes.APPLICATION_M3U8 = hls] so that Exoplayer could play the track. I have to install MimeTypes, I have to call player.setMediaItems(). You can do without player.setMediaItems(). 

please grade my decision

`val dataSourceFactory = DefaultDataSource.Factory(context)` 

```
var resolver =
        ResolvingDataSource.Resolver { srcSpec ->
            if (prefs.isOffline) {
                if (srcSpec.uri.scheme == "https" || srcSpec.uri.scheme == "http") throw OfflineException()
                else {
                    srcSpec.uri.host?.toIntOrNull()?.let { id ->
                        getDataSpecWithTrack(id, srcSpec)
                    } ?: throw Exception()
                }
            } else {
                if (srcSpec.uri.scheme == "https" || srcSpec.uri.scheme == "http") srcSpec
                else {
                    srcSpec.uri.host?.toIntOrNull()?.let { id ->
                        getDataSpecWithTrack(id, srcSpec)
                    } ?: throw Exception()
                }
            }
        }
```

```
var player = ExoPlayer.Builder(context)
        .setMediaSourceFactory(
            DefaultMediaSourceFactory(
                ResolvingDataSource.Factory(dataSourceFactory, resolver)
            )
        ).build()
```

```
private fun getDataSpecWithTrack(id: Int, srcSpec: DataSpec): DataSpec =
        runBlocking(Dispatchers.IO) {
            when (val res = trackManager.getTrackData(id)) {
                is TrackData.TrackFile -> {
                    srcSpec.withUri(Uri.fromFile(res.file))
                }
                is TrackData.TrackUrl -> {
                    withContext(Dispatchers.Main) {
                        if (res.url.endsWith("mp3")) {
                            val mediaItem = MediaItem.fromUri(res.url)
                                .buildUpon().setTag(currentPlayable.value)
                                .setMimeType(MimeTypes.AUDIO_MPEG).build()

                            //here i change my media items
                            mediaItems.apply {
                                removeAt(player.currentMediaItemIndex)
                                add(player.currentMediaItemIndex, mediaItem)
                            }

                            /**
                             * I’m rewriting all the media items. And I don’t think it’s a good decision,
                             * so maybe you can say how else i can change the media item to make MimeTypes apply to it.
                             * If i do ->
                             * player.addMediaItem()
                             * player.prepare()
                             * this code not apply MimeTypes
                             */
                            player.setMediaItems(mediaItems, player.currentMediaItemIndex, 0)
                            player.prepare()

                        } else {
                            val mediaItem = MediaItem.fromUri(res.url)
                                .buildUpon().setTag(currentPlayable.value)
                                .setMimeType(MimeTypes.APPLICATION_M3U8).build()

                            mediaItems.apply {
                                removeAt(player.currentMediaItemIndex)
                                add(player.currentMediaItemIndex, mediaItem)
                            }

                            player.setMediaItems(mediaItems, player.currentMediaItemIndex, 0)
                            player.prepare()
                        }
                    }
                    srcSpec.withUri(Uri.parse(res.url))
                }
            }
        }
```

**Comment by icbaker** [comment] 2023-02-09 08:58
You shouldn't be interacting with the player directly from **inside** `ResolvingDataSource.Resolver.resolveDataSpec`. That method **only** needs to map from one `DataSpec` (the one with your `id://` URI) to another with a URI that can be resolved by `DefaultDataSource` (e.g. `https://`).

So the lines inside your `getDataSpecWithTrack` method that call methods on `Player` look incorrect and you should remove them (or put them elsewhere).

`resolveDataSpec` is called when the player is trying to load data to start playback (i.e. the playlist etc is already setup with `setMediaItem`). Your current code is then effectively restarting that playback during the loading, which is very confusing.

----

If the URI ends in `.mp3` you don't need to set the MIME type manually, it will be detected by the player. HLS URIs are expected to end in `.m3u8`.

**Comment by lewan42** [comment] 2023-02-09 09:41
if I remove the strings 
```
mediaItems.apply {
    removeAt(player.currentMediaItemIndex)
    add(player.currentMediaItemIndex, mediaItem)
}
player.setMediaItems(mediaItems, player.currentMediaItemIndex, 0)
player.prepare()
```
из `ResolvingDataSource.Resolver.resolveDataSpec` ->

```
private fun getDataSpecWithTrack(id: Int, srcSpec: DataSpec): DataSpec =
    runBlocking(Dispatchers.IO) {
        when (val res = trackManager.getTrackData(id)) {
            is TrackData.TrackFile -> {
                srcSpec.withUri(Uri.fromFile(res.file))
            }
            is TrackData.TrackUrl -> {
                srcSpec.withUri(Uri.parse(res.url))
            }
        }
    }
```

i get an error while playing hls tracks ->
```
2023-02-09 12:35:49.640 22650-23004/com.gogosongs E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:607)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
tell me please what I can do so I can play hls tracks?

P.S. this is how I create the initial mediaItems

```
mediaItems = playlist.map {
    MediaItem.fromUri(it.getUri()).buildUpon().setTag(it).build() // it.getUri() = id://track_id -> id://432345
}.toMutableList()

player.setMediaItems(mediaItems, true)
```

**Comment by icbaker** [comment] 2023-02-09 09:48
Ah right, that's happening because `DefaultMediaSourceFactory` is trying to guess the 'type' of your URL (HLS, DASH, Progressive, something else) based on the **pre-resolved** URI (i.e. `id://`). It looks at the suffix of the URL to do this (looking for `.m3u8` for HLS) and if it doesn't recognise the file ending it falls back to `ProgressiveMediaSource` (which I suspect is why MP3 is working).

What happens if you set the MIME type of your HLS MediaItem to `MimeTypes.APPLICATION_M3U8` (that's the HLS MIME type)? That should help the `DefaultMediaSourceFactory` to correctly delegate to `HlsMediaSource.Factory`.

**Comment by lewan42** [comment] 2023-02-09 09:56
if i use set the MimeTypes.APPLICATION_M3U8, then hls is work. But mp3 is not work.
mediaItems = playlist.map {
    MediaItem.fromUri(it.getUri())
        .buildUpon()
        .setTag(it)
        .setMimeType(MimeTypes.APPLICATION_M3U8)
        .build()
}.toMutableList()

error with play mp3
```
2023-02-09 12:51:53.578 28054-28476/com.gogosongs E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:607)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.ParserException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:260)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:68)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:176)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by icbaker** [comment] 2023-02-09 09:57
That's expected if you add it to **every** `MediaItem`. `HlsMediaSource` does not know how to play MP3 files. You should only add the M3U8 MIME type to MediaItems that you know are HLS and not set it for MP3 ones.

**Comment by lewan42** [comment] 2023-02-09 10:02
my problem is that at this point I do not know what type I set. All I know is the track_id. When the playback queue reaches the track, the `ResolvingDataSource.Resolver.resolveDataSpec` method is called. In it I make a request for backend to get https link to track and only by the link I know it is hls or mp3

**Comment by icbaker** [comment] 2023-02-09 10:06
Ah OK, in that case I'm afraid your use-case is not supported - currently ExoPlayer must know the type of a stream before it loads it (and therefore before your `ResolvingDataSource.Resolver.resolveDataSpec` method is called). Changing this is tracked by https://github.com/google/ExoPlayer/issues/3165.

I'm going to close this issue as I don't think there's anything further we can offer here, you can follow the other issue for updates on that.

**Closed as completed by icbaker** 2023-02-09 10:06 UTC
Labels: question

**Comment by lewan42** [comment] 2023-02-09 10:07
Okay, thank you very much and have a good day!
