### ISSUE TITLE
Streaming one particular link gives  flickering video and green screen after upgrading to exoplayer to 2.11.8

### ISSUE THREAD

**Issue by tpuserhp** [google/ExoPlayer#7856] opened 2020-09-05 03:50 UTC
When using exoplayer 2.10.8, I have no problem playing my streams from my app on the Android 10 (Lineage OS 1.7) Oneplus one device. But after upgrading my app to use exoplayer 2.11.8, I started getting video, green screen and pixelation when playing one particular stream. If I fall back to Android 9 of Lineage 1.6, the problem also disappear. I have other devices running Android, 7, Android 9 and  Android 10 with no problem playing that stream with exoplayer 2.11.8. I would appreciate if I could get help to identify the source of the issue. A bugreport and the link are avilable for your analysis.  I will send them to the support email address once I have got the issue case number. Thanks again.

**Comment by tpuserhp** [comment] 2020-09-05 03:52
[bugreport.txt.zip](https://github.com/google/ExoPlayer/files/5177512/bugreport.txt.zip)

**Comment by tpuserhp** [comment] 2020-09-05 03:58
Sorry. Reopen the issue as it was closed by mistake

**Comment by tpuserhp** [comment] 2020-09-06 22:30
Deleted the bugreport from the previous comment area and resend it using email instead.

**Comment by christosts** [comment] 2020-09-07 14:31
The bug-report shows a similar problem reported in #7551 where the issue is coming from the software H264 decoder. May I ask a few questions to clarify where the problem may be:
- In your app, do you pass a custom component to ExoPlayer to prefer software decoders over hardware decoders, or is ExoPlayer using its default component to select which codec to use?
- Can you reproduce the issue when playing the content with the ExoPlayer demo app? Can you try with the demo app using ExoPlayer versions 2.10.8 and 2.11.8 on the specific device that fails? Do you still see v2.10.8 work and v2.11.8 producing the issue?

I would like to verify if ExoPlayer v2.10.8 and v2.11.8 pick different decoders on the specific device that fails, which would indicate it is a decoder problem. If you play the content with the demo app, you should see a log like

```
D/EventLogger: videoDecoderInitialized [eventTime=2.40, mediaPos=0.00, window=0, period=0, OMX.qcom.video.decoder.avc]
```

in which case the decoder is `OMX.qcom.video.decoder.avc`. Can you please tell us what decoder is picked up with v.2.10.8 and v2.11.8?

If you cannot play the content with the demo app, you can print these logs if you attach the event logger on the player by calling
```
player.addAnalyticsListener(new EventLogger(null));
```

on your app.

**Comment by christosts** [comment] 2020-09-07 15:02
From the attached bug report, I see an error similar to #7551. The player has picked up the software decoder which then turns into an error state. I'd like to verify if it's a decoder issue. You mentioned that the content plays fine with ExoPlayer v2.10.8 but not with v2.11.8 on the specific device. I assume this happens on the ExoPlayer demo app too, not only on your app, right? If yes, can you please play the content on the device that fails with v2.10.8 and v2.11.8 and tell us which decoders the player picked up? You can see that by inspecting the logcat and looking for a log like

```
D/EventLogger: decoderInitialized [eventTime=4.87, mediaPos=0.00, window=0, period=0, video, OMX.qcom.video.decoder.avc]
```

in which case `OMX.qcom.video.decoder.avc` is the software H264 decoder. This line should be printed twice per playback session, once for the video and once for the audio decoder.

**Comment by tpuserhp** [comment] 2020-09-07 18:32
Hi support. In my app, ExoPlayer using its default component to select which codec to use. I did try to specify DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER but the result was the same.  I did not install and try the ExoPlayer demo app. But I willl do that later.  I  just installed the app running  ExoPlayer 2.10.8 that the stream plays fine. I will send you the captured logrec.  It seems OMX.qcom.video.decoder.avc was selected. I copy and paste the first few entries below  for your review:

```
09-07 11:41:30.129 D/MediaCodecInfo(17284): NoSupport [codec.profileLevel, avc1.640029, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [bacon, A0001, OnePlus, 29]
09-07 11:41:30.130 D/MediaCodecInfo(17284): NoSupport [codec.profileLevel, avc1.640029, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [bacon, A0001, OnePlus, 29]
09-07 11:41:30.143 I/OMXClient(17284): IOmx service obtained
09-07 11:41:30.144 I/OMXMaster(461): makeComponentInstance(OMX.qcom.video.decoder.avc) in android.hardwar process
09-07 11:41:30.306 D/SurfaceUtils(17284): connecting to surface 0x8d43b008, reason connectToSurface
09-07 11:41:30.307 I/MediaCodec(17284): [OMX.qcom.video.decoder.avc] setting surface generation to 17698817
09-07 11:41:30.307 D/SurfaceUtils(17284): disconnecting from surface 0x8d43b008, reason connectToSurface(reconnect)
09-07 11:41:30.308 D/SurfaceUtils(17284): connecting to surface 0x8d43b008, reason connectToSurface(reconnect)
09-07 11:41:30.348 D/SurfaceUtils(17284): set up nativeWindow 0x8d43b008 for 1280x720, color 0x7fa30c04, rotation 0, usage 0x42002900
09-07 11:41:30.359 W/        (235): buffer descriptor with invalid usage bits 0x2002000
09-07 11:41:30.362 W/        (235): buffer descriptor with invalid usage bits 0x2002000
09-07 11:41:30.394 D/CCodec  (17284): allocate(c2.android.aac.decoder)
09-07 11:41:30.396 I/Codec2Client(17284): Available Codec2 services: "software"
09-07 11:41:30.396 I/Codec2Client(17284): Creating a Codec2 client to service "software"
09-07 11:41:30.397 I/Codec2Client(17284): Client to Codec2 service "software" created
09-07 11:41:30.398 V/C2Store (463): in init
09-07 11:41:30.398 V/C2Store (463): loading dll
09-07 11:41:30.404 I/CCodec  (17284): Created component [c2.android.aac.decoder]
```
Thanks for your help

**Comment by tpuserhp** [comment] 2020-09-07 22:28
Hi support. I tried to run  the  ExoPlayer demo app using my link but failed. My link does not work with https. When I used http for my link, the app came back with clear text not allowed message. Nothing in the logrec showed the decoderInitialized message. Are there any changes I could make in the demo app to get the link I provided in my email working? Also, the doc I got from my app shows OMX.qcom.video.decoder.avc was used for both 2.11.8 and 2.10.8.  Does this point to the decoder problem? Thanks.

**Comment by christosts** [comment] 2020-09-08 08:19
> Are there any changes I could make in the demo app to get the link I provided in my email working?

Yes, please follow the instructions described in [Fixing “Cleartext HTTP traffic not permitted” errors](https://exoplayer.dev/troubleshooting.html#fixing-cleartext-http-traffic-not-permitted-errors)

> Also, the doc I got from my app shows OMX.qcom.video.decoder.avc was used for both 2.11.8 and 2.10.8. Does this point to the decoder problem?

That indicates that the same decoder is used in both versions, therefore we cannot clearly point to an issue in the decoder. Please try with the demo app to verify the failure occurs with 2.11.8 but not with 2.10.8. 

If the failure does occur with the demo app, then please capture a bug-report and send it to us to analyse.

Thank you

**Comment by tpuserhp** [comment] 2020-09-08 13:17
Hi support. I managed to correct the cleartext issue from your doc and captured the Eventlogger message for the demo app running ExoPlayer 2.11.8:
09-08 06:25:27.932 D/EventLogger(15662): decoderInitialized [eventTime=2.27, mediaPos=0.00, window=0, period=0, video, c2.android.avc.decoder]
09-08 06:25:28.004 D/EventLogger(15662): decoderInitialized [eventTime=2.34, mediaPos=0.00, window=0, period=0, audio, c2.android.aac.decoder]
But I ran into another error when changing the demo app to use 2.10.8 on using spherical_gl_surface_view. 
Since I am just a beginner who wants to write some simple Android apps, it might take me lots of time in order to get the demo app working in order to capture the docs for the demo app. Since only one of my devices is not working for my app, 
I would like to close the issue now. Thank you very much for your effort and time on this.

**Comment by tpuserhp** [comment] 2020-09-12 20:12
Hi support, sorry I reopen the issue because I have new eventlogger information to provide below.
I put in eventlogging in my own app and captured the follwoing events under ExoPlayer 2.10.8 and 2.11.8:

Results using ExoPlayer 2.10.8:

09-12 11:49:41.494 D/EventLogger(848): decoderInitialized [1.73, 0.00, window=0, period=0, video, OMX.qcom.video.decoder.avc]
09-12 11:49:41.951 D/EventLogger(848): decoderInitialized [2.19, 0.00, window=0, period=0, audio, c2.android.aac.decoder]

Results using ExoPlayer 2.11.8:

09-12 12:52:40.939 D/EventLogger(8310): decoderInitialized [eventTime=1.49, mediaPos=0.00, window=0, period=0, video, c2.android.avc.decoder]
09-12 12:52:40.992 D/EventLogger(8310): decoderInitialized [eventTime=1.55, mediaPos=0.00, window=0, period=0, audio, c2.android.aac.decoder]

From the above, the video decoder used for 2.10.8 and 2.11.8 are not the same. 
My understanding is that OMX.qcom.video.decoder.avc is a hardware decoder used by ExoPlayer 2.10.8 which streams  my  link with no problems.
The video decoder used for 2.11.8 is a software decoder c2.android.avc.decoder which gives green and flickering streaming video.

Not sure why there is  the difference in the selection of the video decoder between 2.10.8 and 2.11.8.

I understand that you want me to use the demo app to provid the doc. But I was having problems to change the demo app to use ExoPlayer 2.10.8. It could be the demo zip file  I downloaded was  for 2.11.8. I could not find a similar demo zip file for 2.10.8. My problems could be due to my experience level. If you know where I can download the 2.10.8 demo app or changes I have to make to demo app for 2.10.8, please let me know. Thanks.

**Comment by christosts** [comment] 2020-09-14 09:44
Hi @tpuserhp,

The difference in decoders indicates there is an issue with the `c2.android.avc.decoder` decoder on your device. I need to dig why ExoPlayer v2.10.8 and v2.11.8 pick up different decoders. I will try on an Android 10 test device myself, however, I kindly ask you to do the following steps:

- ExoPlayer v.2.12 was just released, can you please try with the latest ExoPlayer and let me know if the problem persists?
- If yes, I do encourage you to reproduce with the ExoPlayer demo app and collect a bug-report when the issue happens. I think the easiest way to switch between versions is to checkout the ExoPlayer source code. Checkout the git repository and then switch between versions by checking out the respective git branches/tags, e.g. after you have cloned the source, the command `git checkout r.2.10.8` will checkout v2.10.8, and `git checkout r2.12` will check out v2.12.

To play your content on the demo app, please add your test stream on [media.exolist.json](https://github.com/google/ExoPlayer/blob/r2.12.0/demos/main/src/main/assets/media.exolist.json) by adding a new entry in the json file, e.g.
```
{
    "name": "GH 7856",
    "samples": [
      {
        "name": "test",
        "uri": "your_test_content_link_goes_here"
      }
    ]
  }
```

Don't forget to modify the demo app so that it can stream plain HTTP traffic as we discussed on the [comment above](https://github.com/google/ExoPlayer/issues/7856#issuecomment-688704599).

**Comment by christosts** [comment] 2020-09-14 12:21
Some further information:
- The test stream says the codec is `avc1.640029` which indicates the video is encoded with H264 high profile. Note that high-profile is not necessarily supported on Android devices, it's up to the specific device to support it, but not guaranteed for all Android certified devices (eg see [Supported formats](https://developer.android.com/guide/topics/media/media-formats)).
- As of version 2.11, ExoPlayer picks up decoder more carefully based on the codec capabilities reported from the Android platform, see [2.11 release notes](https://github.com/google/ExoPlayer/blob/r2.11.1/RELEASENOTES.md).
- You mention you are testing on a OnePlus One, which is a 2014 device. It may be that the platform reports that the specific hardware decoder does not support the H264 high profile, whereas the software decoder supports high-profile in Android 10. That would explain why ExoPlayer v2.11.8 picks up the software decoder.
- The fact that the video plays fine with the hardware decoder on ExoPlayer 2.10.8 can be that the hardware decoder seems to be able to decode the stream, even though the platform says it does not support it.
- The issues you are seeing on the stream with ExoPlayer 2.11.8 on the specific device on LineageOS 1.7 are probably caused by the implementation of the software decoder. Such problems are addressed by either the device vendor (if there is bug on the device firmware) or the android media framework team (if there is a bug in the android framework). However, I think that OnePlus One does not officially support Android 10, so I'm not sure this issue can be addressed.

I'd propose to try to use a different encoding with main profile, test your device with the operated system as provided by the vendor, or customize ExoPlayer and use your own provided logic to pick up decoders.

I'm closing this for now, feel free to reopen if you need more information.

**Closed as completed by christosts** 2020-09-14 12:21 UTC

**Comment by tpuserhp** [comment] 2020-09-14 17:36
Thanks support for your help. 2.12.0 does not help. Likely, there's not much you and I could do  for the enhancement introduced in  version 2.11 and higher that causes this issue.  For now, I just stick with 2.10.8 for my app. Thanks again.
Also, the suggested git command - git checkout r.2.10.8 - does not work. It does not match any files known to git.

**Comment by christosts** [comment] 2020-09-14 18:02
> git checkout r.2.10.8 - does not work

Apologies, I mistyped the version string, the command is `git checkout r2.10.8`

**Comment by tpuserhp** [comment] 2020-09-14 18:09
Great. It works.!Thanks!!

**Comment by tpuserhp** [comment] 2020-10-03 02:37
Hi support. Just an update. I've managed to work around the screen flickering issue -  streaming a link  on my OnePlus One device using ExoPlayer 2.11.8. I  customized  the MediaCodecSelector to force only the working video hardware decoder to be selected for my OnePlus one device. Now ithe link is streaming normaly like before when my app was using ExoPlayer 2.10.8. It was a good learning experience  for me and I am happy with the work around. It would be perfect if the source code of ExoPlayer could be modified for this issue. But since my device is no longer supported, I have to leave the problem  or fix it myself. Thanks for your support!
