### ISSUE TITLE
Missing audio track in HLS

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#4275] opened 2018-05-19 22:24 UTC
### Issue description
ExoPlayer identifies only 1 audio track for HLS which uses TS chunks with 2 audio tracks.
2 tracks are identified when TS chunk is played directly

**HLS:**
```
Tracks [
      Renderer:0 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=0, mimeType=video/avc, supported=YES
        ]
      ]
      Renderer:2 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, supported=YES
        ]
      ]
      Renderer:6 [
        Group:0, adaptive_supported=N/A [
          [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
        ]
      ]
      Renderer:7 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/21, mimeType=application/id3, supported=YES
        ]
      ]
    ]
```
**TS:**
```
Tracks [
      Renderer:0 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/258, mimeType=video/avc, res=1920x1080, supported=YES
        ]
      ]
      Renderer:2 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/256, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, supported=YES
        ]
        Group:1, adaptive_supported=N/A [
          [ ] Track:0, id=1/257, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, supported=YES
        ]
      ]
      Renderer:6 [
        Group:0, adaptive_supported=N/A [
          [ ] Track:0, id=1/8450, mimeType=application/cea-608, supported=YES
        ]
      ]
    ]
```

### Reproduction steps

1. start local test web server to serve HLS and it's chunks (all in provided archive). 
2. local server is available from emulator on 10.0.2.2
2. Update `media.exolist.json`:
```
[
  {
    "name": "Test Samples",
    "samples": [
      {
        "name": "HLS",
        "uri": "http://10.0.2.2:5000/static/3709.m3u8"
      },
      {
        "name": "TS",
        "uri": "http://10.0.2.2:5000/static/3709_2795.ts"
      }
    ]
  }
]
```
2nd sample is one of HLS chunks from 1st sample
3. Start Demo app
4. HLS exposes 1 audio track
TS exposes 2 audio tracks

### Link to test content
m3u8, TS chunks and simple test server using flask/python:
https://drive.google.com/open?id=1vDAwOSBGR6G32i284cFJ78XrAufZEGGr

### Version of ExoPlayer being used
dev-v2, 2b9c31a14f177bbfd6c190726dcb5d3fcb75f17b

### Device(s) and version(s) of Android being used
Got report from Sony Android TV, reproduced in emulator API P

**Comment by AquilesCanta** [comment] 2018-05-21 08:18
This is a duplicate of #2014.

**Closed as completed by AquilesCanta** 2018-05-21 08:18 UTC
Labels: duplicate
