### ISSUE TITLE
How to do try and catch error when try to play media source.

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#5551] opened 2019-02-21 09:54 UTC
Hi there, if I allow to user to play music with shuffle the problem that i facing right now is that the exoplayer crash my apps when try to play the media source which are not have inside Concatenating media source. The question is that, is there way try and catch if file not found so that exoplayer wouldn’t crash my apps. My exoplayer version : 2.8.4

**Comment by andrewlewis** [comment] 2019-02-21 10:27
Please see #4343, which seems related. When you say it crashes the app, is there an uncaught error, or just a call to `onPlayerError`?

**Comment by hafiz013** [comment] 2019-02-22 03:10
but it doesn't not go to on Player Error straight away crash my apps.

**Comment by andrewlewis** [comment] 2019-02-23 21:17
@hafiz013 Please could you provide a full bug report (`adb bugreport`) taken just after the crash?

**Comment by hafiz013** [comment] 2019-02-26 07:09
` com.google.android.exoplayer2.IllegalSeekPositionException
        at com.google.android.exoplayer2.ExoPlayerImpl.seekTo(ExoPlayerImpl.java:272)
        at com.google.android.exoplayer2.SimpleExoPlayer.seekTo(SimpleExoPlayer.java:747)`

and this is my sample of my code:

` musicPlayer.setShuffleModeEnabled(true);
                        musicPlayer.seekTo(musicPlayer.getNextWindowIndex(), C.TIME_UNSET);`

It begin crash when i start to shuffle. After that, when I reload again and click shuffle mode everything ok and not crash. Do you know what is problem with that and how to do try and catch error.

**Comment by tonihei** [comment] 2019-02-27 10:39
`player.getNextWindowIndex()` may return `C.INDEX_UNSET` if the current window is the last one. I guess that is what is happening here. If you attempt to seek to `C.INDEX_UNSET` it will throw an `IllegalSeekPositionException`.

**Comment by hafiz013** [comment] 2019-02-28 10:08
that's why exoplayer do not have exception try n error at least avoid the apps crashing.

**Comment by tonihei** [comment] 2019-02-28 10:15
I don't understand what you are trying to say. Throwing an exception is the usually the right thing if the application code calls a method with invalid parameters.

**Comment by hafiz013** [comment] 2019-03-01 07:18
what I mean is that if I call method with invalid parameters there is must exception so that this exoplayer could not make apps crash. This crash happen for starting only the rest follow same steps it is not crash anymore.

**Comment by tonihei** [comment] 2019-03-01 09:06
Are you saying that `player.getNextWindowIndex()` is `C.INDEX_UNSET` but it shouldn't? Or that `player.getNextWindowIndex()` is not `C.INDEX_UNSET` and `seekTo` still throws? 

In any case, it would be good if you can provide more detailed reproduction steps so that we can better understand the problem.

**Comment by hafiz013** [comment] 2019-03-01 09:42
step to reproduce the error:
1) When first time install the apps and i try to open the music with shuffle mode it is straight away crash by using this function :  
`musicPlayer.setShuffleModeEnabled(true); musicPlayer.seekTo(musicPlayer.getNextWindowIndex(), C.TIME_UNSET);`
2) Then i reload and open the apps again, I do same things which is click shuffle mode but this time no more crash happen.

For your info, music playlist I use concatenate media source and i use the same function above. So is there way if that function is call and got error not give change to the apps crash but somewhere it can hold it or throw it crash.

**Comment by tonihei** [comment] 2019-03-01 09:48
I still think you are calling `seekTo` while `getNextWindowIndex` is still unset. For example because you haven't called `player.prepare` yet or the the current window is the last one after enabling the shuffling mode. Please ensure that there actually is a next window before trying to seek to it.

**Comment by tonihei** [comment] 2019-03-19 10:10
Closing due to lack of new information. And the question was probably answered.

**Closed as completed by tonihei** 2019-03-19 10:10 UTC
Labels: question

**Comment by hafiz013** [comment] 2019-03-21 04:23
Don't close my case, how to check the the current window is the last one after enabling the shuffling mode?

**Comment by tonihei** [comment] 2019-03-21 08:48
You should be able the check if `player.getNextWindowIndex() == C.INDEX_UNSET`. As documented, this means that the current window is the last one.

**Comment by hafiz013** [comment] 2019-04-01 06:50
so in this case what should i do? 

`if(!musicPlayer.getShuffleModeEnabled()){
                        musicPlayer.setShuffleModeEnabled(true);
                        musicPlayer.seekTo(musicPlayer.getNextWindowIndex(), C.TIME_UNSET);
                    }` .  

only this code make it crash apps.  Only can setup C.TIME_UNSET.

**Comment by hafiz013** [comment] 2019-04-29 04:41
Still does not work , error code :

`com.google.android.exoplayer2.IllegalSeekPositionException
        at com.google.android.exoplayer2.ExoPlayerImpl.seekTo(ExoPlayerImpl.java:272)
        at com.google.android.exoplayer2.SimpleExoPlayer.seekTo(SimpleExoPlayer.java:747)`

My implement code use u suggested : 

` if(!musicPlayer.getShuffleModeEnabled()){
                        musicPlayer.setShuffleModeEnabled(true);
                    }

                    if (musicPlayer.getNextWindowIndex() == C.INDEX_UNSET){  // if last one
                        musicPlayer.seekTo(musicPlayer.getNextWindowIndex(), C.INDEX_UNSET);
                    }

                    if (!playCurrentMusic){
                        musicPlayer.setPlayWhenReady(true);
                    }`
