### ISSUE TITLE
Why does the CastPlayer never send a 'STATE_ENDED' playerState?

### ISSUE THREAD

**Issue by mikescamell** [google/ExoPlayer#9899] opened 2022-01-26 09:43 UTC
Hello!

I was wondering why the CastPlayer never sends a `STATE_ENDED` when listening via `onPlaybackStateChanged`?, we only ever get `STATE_IDLE`, is there a reason for this?

We use the `STATE_ENDED` message to do some things when we know we've finished playback of something, which works great with `ExoPlayer`, but digging into the `CastPlayer` source code I can't find any reference to `STATE_ENDED` being sent.

Would it be possible to check the Idle state reason in the `fetchPlaybackState` function in CastPlayer and send back a `STATE_ENDED` if the MediaStatus is `IDLE_REASON_FINISHED`?

```  
private static int fetchPlaybackState(RemoteMediaClient remoteMediaClient) {
    int receiverAppStatus = remoteMediaClient.getPlayerState();
    switch (receiverAppStatus) {
      case MediaStatus.PLAYER_STATE_BUFFERING:
        return STATE_BUFFERING;
      case MediaStatus.PLAYER_STATE_PLAYING:
      case MediaStatus.PLAYER_STATE_PAUSED:
        return STATE_READY;
      case MediaStatus.PLAYER_STATE_IDLE: // Can we check the idle reason here?
      case MediaStatus.PLAYER_STATE_UNKNOWN:
      default:
        return STATE_IDLE;
    }
  }
```

Thanks!

**Comment by marcbaechinger** [comment] 2022-01-26 11:40
This is a duplicate of #3969.

Roughly the `STATE_ENDED` wasn't implemented because the default cast receiver empties the queue when the end of the queue is reached.

May I ask you to add your interesting note about `IDLE_REASON_FINISHED` in a comment in #3969? I can obviously do this myself but I think it would be great to have the original author doing it in case we look into this.

**Closed as completed** 2022-01-26 11:41 UTC
Labels: question

**Comment by mikescamell** [comment] 2022-01-26 11:54
Thank you and sorry for the duplicate! 🙏 I will add a comment to the issue 👍
