### ISSUE TITLE
ExoPlaybackException: Source error 

### ISSUE THREAD

**Issue by mirlannur** [google/ExoPlayer#10238] opened 2022-05-04 14:46 UTC
### ExoPlayer Version

2.13.3

### Devices that reproduce the issue

* Mi MIX 3

### Reproducible in the demo app?

Not tested

### Reproduction steps

Try to play this video: https://livevoyage.club/api/video/374521e9-7c84-4d17-8c86-c4de07855322

### Expected result

The media plays successfully

### Actual result

Stacktrace:
`
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.EOFException
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:288)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:75)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:83)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:412)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:246)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1048)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

### Media

I am facing with following error when playing one hour long video throught http. With short videos everything is OK. 

Stack Trace
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.EOFException
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:288)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:75)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:83)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:412)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:246)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1048)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
`
Any ideas to resovle this?

**Comment by marcbaechinger** [comment] 2022-05-04 15:13
When I try the URI with curl it gives me `curl: (60) SSL certificate problem: unable to get local issuer certificate`. When playing the URI in the demo app it gives a similar response: 'Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false' It seems there is an issue with the SSL certificate on this server. 

The stack trace above shows an end of file exception while reading an Mp4 file. I don't think this is directly related to the ssl problem but probably to another issue on the server side. 

Can you check whether the URI is working as expected?

**Comment by mirlannur** [comment] 2022-05-14 10:59
The URL is working as expected. Before the long video, the exoplayer also worked fine

**Comment by mirlannur** [comment] 2022-05-14 13:12
I found the problem. The video on server is recorded with `ffmpeg -movflags +faststart`. For shorter videos it works fine, the problem occurs with long videos. If to record the long video with `ffmpeg -movflags +frag_keyframe` or `+empty_moov` flags, it plays the video but there is another problem in this case: the scrubber is not available, the video is not seekable.( 
Any idea?

**Comment by AndroidDeveloperLB** [comment] 2023-06-01 12:27
I have this issue too, but on a local file, right on the app itself. Here, prepared a sample project:

[ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/11625130/ExoPlayerTest.zip)

Can anyone please explain why it occurs, and how can I fix it?

**Comment by marcbaechinger** [comment] 2023-06-01 14:23
The sample app is violating some best practices that makes it difficult to rule out app problems. It for instance does build and prepare the player in `onCreate()`. To rule out app problems, you can try to reproduce with the [demo app](https://developer.android.com/guide/topics/media/exoplayer/demo-application). If you see the problem there as well, please do a [bug report](https://developer.android.com/studio/debug/bug-report) right after the problem occurred and upload it here together with the media URI, so we can investigate this.

**Comment by AndroidDeveloperLB** [comment] 2023-06-01 15:27
@marcbaechinger What do you mean it violates? I've followed the instructions from here:
https://exoplayer.dev/hello-world.html
It doesn't mention onCreate not allowed. Why would it be bad to do it?
Also, why is it relevant? The issue is with the video not being played. When I tried a different one, it played fine. That's even though both video files are supported on Android.

Your demo (https://github.com/androidx/media.git) is huge compared to the tiny sample I've created. I don't know how to add it there.
It doesn't seem like it's loading a video from within the app.
This is often the case with Google's samples. They show a lot of what's possible, but they are impossible to understand and learn from due to how much was written in them. I prefer tiny, minimal samples instead.


Here, tried the sample from the tutorial:
https://developer.android.com/codelabs/exoplayer-intro#1

Works for URL, doesn't work for the file  (exoplayer-codelab-00):
[exoplayer-intro-main.zip](https://github.com/google/ExoPlayer/files/11627779/exoplayer-intro-main.zip)

**Comment by marcbaechinger** [comment] 2023-06-01 16:20
Thanks for your suggestions on how to improve Google sample apps and your preferences about it. We will see how we can take these into account. 

For now, our demo app is sufficient for us and excellent to rule out problems from the app side. The fastest way for you to get us looking into the problem is adding your media to the demo app and report us problems when doing that. 

The link I posted above explains how you can add a sample to the demo app. This link here points you exactly to that section for convenience: https://developer.android.com/guide/topics/media/exoplayer/demo-application#1_editing_assetsmediaexolistjson

**Comment by AndroidDeveloperLB** [comment] 2023-06-01 16:42
@marcbaechinger I've already shown you on the sample of exoplayer, via the tutorial. Please check the attached.

**Comment by marcbaechinger** [comment] 2023-06-01 16:57
Closing this issue as the initial problems seems to be solved according to the author. Secondly, because we didn't come to an agreement how to repro with the second problem posted here.

Please file a new issue in case you want to negotiate again. If you do that , please file your issue in the new repo: https://github.com/androidx/media/issues 

If you want a reason why I insist on the demo app, then please check the media file you have embedded in your source folder. The file size is 0 Bytes. This makes the media difficult to play.

**Closed as completed by marcbaechinger** 2023-06-01 16:57 UTC
Labels: bug, need more info

**Comment by AndroidDeveloperLB** [comment] 2023-06-01 17:12
@marcbaechinger Oh the file became 0-size for some reason... Sorry about that

**Comment by AndroidDeveloperLB** [comment] 2023-06-01 18:40
@marcbaechinger Attached here the original video file.
[test2.zip](https://github.com/google/ExoPlayer/files/11628418/test2.zip)

I tried again on the tutorial project of ExoPlayer, and it still failed to play.

Do you want me to still use the demo? I don't understand what you want me to do there. How can I make it play this video file?

**Comment by marcbaechinger** [comment] 2023-06-01 18:49
The video is 4 seconds lang and plays without problems in the demo app.

**Comment by AndroidDeveloperLB** [comment] 2023-06-01 19:06
@marcbaechinger How did you test it out? Please show minimal project. Or at least explain in the demo app. The demo app has multiple samples. Which to run?
Which file have you changed, and to what?

I did as the tutorial shows.
The demo is huge. 70 MB just to clone...

Please update the tutorial and its project. It doesn't seem to work with the file I've provided.
