### ISSUE TITLE
java.lang.IllegalStateException at com.google.android.exoplayer2.util.Assertions.checkState thrown when connection is throttled playing HLS stream

### ISSUE THREAD

**Issue by aryehbaker** [google/ExoPlayer#8890] opened 2021-04-30 19:19 UTC
Exoplayer stops functioning when throttling API 30 emulator to network Type 'HSDPA' and signal strength 'poor'

Using the [IMA DAI Advanced Example](https://github.com/googleads/googleads-ima-android-dai/releases/download/3.22.3-0/AdvancedExample3.22.3-0.zip) with the Buck Bunny stream, before 10 ad breaks play the player stalls and the logcat shows:

```
com.google.ads.interactivemedia.v3.samples.videoplayerapp E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:586)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:86)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.getFirstSampleIndex(HlsMediaChunk.java:319)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.skipData(HlsSampleStreamWrapper.java:638)
        at com.google.android.exoplayer2.source.hls.HlsSampleStream.skipData(HlsSampleStream.java:86)
        at com.google.android.exoplayer2.BaseRenderer.skipSource(BaseRenderer.java:427)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.maybeDropBuffersToKeyframe(MediaCodecVideoRenderer.java:1059)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.processOutputBuffer(MediaCodecVideoRenderer.java:891)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1854)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:824)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by christosts** [comment] 2021-05-14 15:30
@tonihei can you take a look?

**Comment by tonihei** [comment] 2021-05-18 15:55
Duplicate of #8937

**Closed as completed by tonihei** 2021-05-18 15:55 UTC
Labels: duplicate
