### ISSUE TITLE
Pixel C no longer plays Widevine content (and cannot be provisioned after factory reset)

### ISSUE THREAD

**Issue by splrs** [google/ExoPlayer#8075] opened 2020-10-14 18:13 UTC
### Issue description
The Google Pixel C can no longer play Widevine encrypted content as a level 1 device, with the licence server rejecting licence requests - unfortunately I don't have a log this occurring while the device was provisioned...

Regarding it being provisioned: When I discovered that it would no longer play Widevine streams, I attempted a factory reset to see if re-provisioning would fix the issue. The provisioning server rejects requests from this device with a 400 response.

I'm aware that one workaround is to set its MediaDrm instance's `securityLevel` property to `L3` . I've opted against creating a device-specific pull request to this effect, as I'm unsure of the procedure for resolving issues such as this on end-of-life'd devices.

### Reproduction steps
Play Widevine DASH H264 > Secure (cenc).
This stream would previously play without issue, but will now fail when the provisioning request is rejected.

### Link to test content
Widevine DASH H264 - Secure (cenc)

### A full bug report captured from the device
I believe this is N/A - I believe the provisioning server is explicitly rejecting provisioning requests for these another older devices.

### Version of ExoPlayer being used
2.12.0

### Device(s) and version(s) of Android being used
* Pixel C
* 8.1.0

### Log of attempted playback

~~~
--------- beginning of system
--------- beginning of main
10-14 18:40:00.238 12490 12490 I ExoPlayerImpl: Init 83ab984 [ExoPlayerLib/2.12.0] [dragon, Pixel C, Google, 27]
10-14 18:40:00.242 12490 12490 D EventLogger: playWhenReady [eventTime=0.00, mediaPos=0.00, window=0, true, USER_REQUEST]
10-14 18:40:00.248 12490 12490 D EventLogger: timeline [eventTime=0.00, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
10-14 18:40:00.248 12490 12490 D EventLogger:   period [?]
10-14 18:40:00.248 12490 12490 D EventLogger:   window [?, false, true]
10-14 18:40:00.248 12490 12490 D EventLogger: ]
10-14 18:40:00.249 12490 12490 D EventLogger: mediaItem [eventTime=0.01, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
10-14 18:40:00.252 12490 12490 D EventLogger: state [eventTime=0.01, mediaPos=0.00, window=0, BUFFERING]
10-14 18:40:00.308 12490 12490 D EventLogger: surfaceSize [eventTime=0.07, mediaPos=0.00, window=0, 2560, 1640]
10-14 18:40:00.313 12490 12490 D EventLogger: loading [eventTime=0.07, mediaPos=0.00, window=0, period=0, true]
10-14 18:40:05.780 12490 12490 D EventLogger: timeline [eventTime=5.54, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
10-14 18:40:05.781 12490 12490 D EventLogger:   period [734.00]
10-14 18:40:05.781 12490 12490 D EventLogger:   window [734.00, true, false]
10-14 18:40:05.781 12490 12490 D EventLogger: ]
10-14 18:40:05.788 12490 12490 D EventLogger: videoEnabled [eventTime=5.55, mediaPos=0.00, window=0, period=0]
10-14 18:40:05.789 12490 12490 D EventLogger: audioEnabled [eventTime=5.55, mediaPos=0.00, window=0, period=0]
10-14 18:40:05.793 12490 12490 D EventLogger: tracks [eventTime=5.55, mediaPos=0.00, window=0, period=0
10-14 18:40:05.793 12490 12490 D EventLogger:   MediaCodecVideoRenderer [
10-14 18:40:05.793 12490 12490 D EventLogger:     Group:0, adaptive_supported=YES [
10-14 18:40:05.793 12490 12490 D EventLogger:       [X] Track:0, id=1, mimeType=video/avc, bitrate=772315, codecs=avc1.42c01e, res=320x142, fps=24.0, supported=YES
10-14 18:40:05.793 12490 12490 D EventLogger:       [X] Track:1, id=2, mimeType=video/avc, bitrate=1777315, codecs=avc1.4d401f, res=854x380, fps=24.0, supported=YES
10-14 18:40:05.793 12490 12490 D EventLogger:       [X] Track:2, id=3, mimeType=video/avc, bitrate=7206998, codecs=avc1.4d4028, res=1280x570, fps=24.0, supported=YES
10-14 18:40:05.793 12490 12490 D EventLogger:       [X] Track:3, id=4, mimeType=video/avc, bitrate=18320008, codecs=avc1.64002a, res=1920x856, fps=24.0, supported=YES
10-14 18:40:05.793 12490 12490 D EventLogger:     ]
10-14 18:40:05.793 12490 12490 D EventLogger:   ]
10-14 18:40:05.793 12490 12490 D EventLogger:   MediaCodecAudioRenderer [
10-14 18:40:05.793 12490 12490 D EventLogger:     Group:0, adaptive_supported=N/A [
10-14 18:40:05.793 12490 12490 D EventLogger:       [X] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=134359, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=en, supported=YES
10-14 18:40:05.793 12490 12490 D EventLogger:     ]
10-14 18:40:05.794 12490 12490 D EventLogger:   ]
10-14 18:40:05.794 12490 12490 D EventLogger:   TextRenderer []
10-14 18:40:05.794 12490 12490 D EventLogger:   MetadataRenderer []
10-14 18:40:05.794 12490 12490 D EventLogger:   CameraMotionRenderer []
10-14 18:40:05.794 12490 12490 D EventLogger: ]
10-14 18:40:06.009 12490 12490 D EventLogger: downstreamFormat [eventTime=5.76, mediaPos=0.00, window=0, period=0, id=0, mimeType=audio/mp4a-latm, bitrate=134359, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=en]
10-14 18:40:06.074 12490 12490 D EventLogger: audioInputFormat [eventTime=5.83, mediaPos=0.00, window=0, period=0, id=0, mimeType=audio/mp4a-latm, bitrate=134359, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=en]
10-14 18:40:06.084 12490 12490 D EventLogger: downstreamFormat [eventTime=5.84, mediaPos=0.00, window=0, period=0, id=3, mimeType=video/avc, bitrate=7206998, codecs=avc1.4d4028, res=1280x570, fps=24.0]
10-14 18:40:06.086 12490 12490 D EventLogger: videoInputFormat [eventTime=5.84, mediaPos=0.00, window=0, period=0, id=3, mimeType=video/avc, bitrate=7206998, codecs=avc1.4d4028, res=1280x570, fps=24.0]
10-14 18:40:38.136 12490 12490 D EventLogger: loading [eventTime=37.89, mediaPos=0.00, window=0, period=0, false]
10-14 18:40:41.631 12490 12490 E EventLogger: internalError [eventTime=41.39, mediaPos=0.00, window=0, period=0, drmSessionManagerError
10-14 18:40:41.631 12490 12490 E EventLogger:   com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:178)
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeProvisionRequest(HttpMediaDrmCallback.java:111)
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:590)
10-14 18:40:41.631 12490 12490 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:106)
10-14 18:40:41.631 12490 12490 E EventLogger:       at android.os.Looper.loop(Looper.java:164)
10-14 18:40:41.631 12490 12490 E EventLogger:       at android.os.HandlerThread.run(HandlerThread.java:65)
10-14 18:40:41.631 12490 12490 E EventLogger:   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:81)
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:75)
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:166)
10-14 18:40:41.631 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:161)
10-14 18:40:41.631 12490 12490 E EventLogger:       ... 5 more
10-14 18:40:41.631 12490 12490 E EventLogger: ]
10-14 18:40:41.654 12490 12490 D EventLogger: videoDecoderInitialized [eventTime=41.41, mediaPos=0.00, window=0, period=0, OMX.Nvidia.h264.decode]
10-14 18:40:41.679 12490 12490 D EventLogger: videoDisabled [eventTime=41.44, mediaPos=0.00, window=0, period=0]
10-14 18:40:41.680 12490 12490 D EventLogger: audioDisabled [eventTime=41.44, mediaPos=0.00, window=0, period=0]
10-14 18:40:41.694 12490 12490 E EventLogger: playerFailed [eventTime=41.45, mediaPos=0.00, window=0, period=0
10-14 18:40:41.694 12490 12490 E EventLogger:   com.google.android.exoplayer2.ExoPlaybackException: Source error
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
10-14 18:40:41.694 12490 12490 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-14 18:40:41.694 12490 12490 E EventLogger:       at android.os.Looper.loop(Looper.java:164)
10-14 18:40:41.694 12490 12490 E EventLogger:       at android.os.HandlerThread.run(HandlerThread.java:65)
10-14 18:40:41.694 12490 12490 E EventLogger:   Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:518)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionError(DefaultDrmSession.java:238)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$ProvisioningManagerImpl.onProvisionError(DefaultDrmSessionManager.java:768)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionResponse(DefaultDrmSession.java:375)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.DefaultDrmSession.access$000(DefaultDrmSession.java:57)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:554)
10-14 18:40:41.694 12490 12490 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:106)
10-14 18:40:41.694 12490 12490 E EventLogger:       ... 2 more
10-14 18:40:41.694 12490 12490 E EventLogger:   Caused by: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:178)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeProvisionRequest(HttpMediaDrmCallback.java:111)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:590)
10-14 18:40:41.694 12490 12490 E EventLogger:       ... 3 more
10-14 18:40:41.694 12490 12490 E EventLogger:   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:81)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:75)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:166)
10-14 18:40:41.694 12490 12490 E EventLogger:       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:161)
10-14 18:40:41.694 12490 12490 E EventLogger:       ... 5 more
10-14 18:40:41.694 12490 12490 E EventLogger: ]
10-14 18:40:41.697 12490 12490 D EventLogger: state [eventTime=41.45, mediaPos=0.00, window=0, period=0, IDLE]
10-14 18:40:45.347 12490 12490 D EventLogger: surfaceSize [eventTime=45.10, mediaPos=0.00, window=0, period=0, 0, 0]
10-14 18:40:45.608 12490 12490 I ExoPlayerImpl: Release 83ab984 [ExoPlayerLib/2.12.0] [dragon, Pixel C, Google, 27] [goog.exo.core, goog.exo.cronet, goog.exo.ui, goog.exo.dash]
~~~

**Comment by marcbaechinger** [comment] 2020-10-14 18:34
I think this is a duplicate of #7986

**Comment by marcbaechinger** [comment] 2020-10-14 18:36
Please see [this comment](https://github.com/google/ExoPlayer/issues/7986#issuecomment-701057240) in #7986 that explains how to use L3.

**Comment by lbwstco** [comment] 2020-10-15 09:19
@AquilesCanta Is Pixel C in the devices list that Widevine be revoked licensing?

**Comment by AquilesCanta** [comment] 2020-10-15 10:56
Unfortunately, I don't know. I'm sorry I can't help with this.  I suggest you contact Widevine support at https://www.widevine.com/contact.

**Comment by rrfrias** [comment] 2020-10-19 21:20
As AquilesCanta suggested you should contact Widevine support if you are a Widevine partner. 

> I'm aware that one workaround is to set its MediaDrm instance's securityLevel property to L3 . I've opted against creating a device-specific pull request to this effect, as I'm unsure of the procedure for resolving issues such as this on end-of-life'd devices.

If provisioning attempts fails with an HTTP 400 error (possibly more than once) you should consider falling back to L3. This will cover a wider range of failures than just the Provisioning service denying a request, including malformed requests etc. It will also avoid the need to maintain a list of devices. We are working on improving failure information conveyed to for app in future releases. 

Let us know if you have any more questions. If not, i will close this in two weeks.

**Comment by zilinx** [comment] 2020-10-23 07:15
Hi @rrfrias, you suggest:
> If provisioning attempts fails with an HTTP 400 error (possibly more than once) you should consider falling back to L3.

1. What is your recommended way in ExoPlayer 2.12 to do this? There is `DefaultMediaSourceFactory.setDrmSessionManager()`, but that is inconvenient because I would need to have the information about my asset at the time of creating the player. I would prefer to set a factory like the one used by default, if custom drm session manager is not set (`MediaSourceDrmHelper`), https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/DefaultMediaSourceFactory.java#L240.
2. Say, I do want to maintain my own list of devices which should fall back to L3, or have some other reasons why I would want to do that. What would be the right way to expand on the condition you have here: https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/FrameworkMediaDrm.java#L427 with my own conditions?

**Comment by rrfrias** [comment] 2020-11-16 10:00
@ojw28 can you review zilinx suggestions in case there are any recommendations for how to handle this?

**Comment by belgianwaves** [comment] 2020-11-25 10:48
Like already mentioned, other (older) devices might have this problem, like is the case for the HTC Nexus 9

**Comment by ojw28** [comment] 2020-12-03 18:02
I'm not sure there's an easy solution to this, unfortunately, but let's consolidate the discussion in https://github.com/google/ExoPlayer/issues/8108. Closing this as a duplicate of that one. Thanks!

**Closed as completed by ojw28** 2020-12-03 18:02 UTC
Labels: duplicate, bug: device specific, bug: in platform drm
