### ISSUE TITLE
Question: How to improve HLS seek performance?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#5127] opened 2018-11-20 12:46 UTC
In the same network environment and the same HLS stream, I compared the time-consuming of using the Android MediaPlayer and ExoPlayer to perform the seek operation . The ExoPlayer always takes more time than MediaPlayer。But the ExoPlayer seek exactly than MediaPlayer.
Question：I hope you can explain the difference between the two players in performing the seek operation.
My current solution is as followed: I only feed the key frame into codec.
### MediaCodecRenderer. feedInputBuffer()
![image](https://user-images.githubusercontent.com/9837705/48774223-93324f00-ed04-11e8-9566-fdde0578e81c.png)

I don't know whether there are other hidden dangers that I did not expect. Hope you give me some advices.

**Comment by tonihei** [comment] 2018-11-20 13:47
Have you tried setting the `SeekParameters` on the `Player` to `SeekParameters.CLOSEST_SYNC` or `SeekParameters.LAST_SYNC` to achieve the same behaviour as in MediaPlayer? The default is `SeekParameters.EXACT` which may take longer if you not seeking to a key frame.

**Comment by ojw28** [comment] 2018-11-20 16:14
`SeekParameters` don't do anything for HLS. Supporting them is tracked by https://github.com/google/ExoPlayer/issues/2882. I'd suggest this is most likely a duplicate of that issue.

**Comment by Romantic-LiXuefeng** [comment] 2018-11-21 01:12
@ojw28 @tonihei Thanks. As @ojw28 said,the SeekParameters don't do anything for HLS.  I just to know whether my changes cause problems that I can't think of?  Hope you give some advices

**Comment by ojw28** [comment] 2018-11-23 21:46
Closing as a duplicate of #2882. Regarding the modification to `feedInputBuffer`, that doesn't look right at all. I suspect it will break things, most likely including causing visual corruption of output buffers in some cases. I also don't think it will make seek performance any faster.

**Closed as completed by ojw28** 2018-11-23 21:46 UTC
Labels: question
