### ISSUE TITLE
Set surfaceholder after start video

### ISSUE THREAD

**Issue by szkrisz21** [google/ExoPlayer#3832] opened 2018-02-12 13:45 UTC
Setting SurfaceHolder by 'SimpleExoPlayer.setVideoSurfaceHolder' after starting playback gives an error. 
Calling mediaPlayer.setVideoSurfaceHolder(mVideoView.getHolder()) after start video. And when I stop it, the player remain in Player.STATE_READY. And when I try to 'prepare' it, the app hangs up. This is occurs only on Huawei P8 lite devices.

**Comment by tonihei** [comment] 2018-02-12 16:04
Can you provide more details of the error you get as requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE)?

**Comment by szkrisz21** [comment] 2018-02-13 07:06
- ExoPlayer version: any version of ExoPlayer after r2.4.4 With version r2.4.4 issue not appears on same device.
- Android version 6.0, EMUI 4.0.3
- Device Huawei P8 lite

Reproduce issue:
 
Important! Do not call mediaPlayer.setVideoSurfaceHolder(...) method before mediaPlayer.prepare(...)

.....
DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
SimpleExoPlayer mediaPlayer = ExoPlayerFactory.newSimpleInstance(mContext, new DefaultTrackSelector());
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(mContext, Util.getUserAgent(mContext, "Dummy"), bandwidthMeter);
                        HlsMediaSource videoSource = new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse("http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/1240_vod.m3u8"), new Handler(), eventListener);
mediaPlayer.prepare(videoSource, true, true);

The sound plays normally, and when call 

mediaPlayer.setVideoSurfaceHolder(mVideoView.getHolder());

After this call only current frame rendered and the sound is playing normally on mentioned device. On all other devices the video rendering normally.

mediaPlayer.stop();

The sound stops playing but player remains in state 'Player.STATE_READY'. The  Player.onPlayerStateChanged(...) not called anymore. On other devices works normally:  Player.onPlayerStateChanged(...) called and player goes to state 'Player.STATE_IDLE'

init videoSource and call again 

mediaPlayer.prepare(videoSource, true, true);

Player.onPlayerStateChanged(...) not called, video and sound not start anymore. And when call mediaPlayer.stop() method, the app not responds afterward. It also happens only mentioned device.

**Comment by szkrisz21** [comment] 2018-02-13 11:09
Hi,
It seems like app die after surface destroyed if setVideoSurfaceHolder(...) called after prepare(...) method. When prepare(...) called before setVideoSurfaceHolder(...) then no error on surface destroyed.

**Comment by tonihei** [comment] 2018-02-13 11:48
This seems to be a duplicate of #3724. Tested with the current dev and a Huawei L8 Lite and it works fine. The fix (or rather workaround) for this device will be part of the next release.

**Closed as completed by tonihei** 2018-02-13 11:48 UTC
Labels: duplicate
