### ISSUE TITLE
No exception when downloads fails.

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#7457] opened 2020-06-02 11:02 UTC
Is there any reason for not propagating exception to app when download fails. In earlier version we used to get Throwable which has more details about error.

In latest version's we have int definition for error which doesn't provide much info about error.

```
@IntDef({FAILURE_REASON_NONE, FAILURE_REASON_UNKNOWN})
  public @interface FailureReason {}
```

**Comment by ojw28** [comment] 2020-06-02 21:54
Downloads failures now need to be persisted in the download database. Trying to store and reconstruct a whole exception to/from the database doesn't feel like the right thing to do. Providing more fine-grained failure reasons is tracked by https://github.com/google/ExoPlayer/issues/5914, so I'll mark this as a duplicate of that issue. We could also look at storing the name of the Exception class alongside the failure reason, as a way of providing some additional insight.

**Closed as completed by ojw28** 2020-06-02 21:54 UTC
Labels: duplicate
