### ISSUE TITLE
ExoPlayer fails to get duration on local AAC files

### ISSUE THREAD

**Issue by hannojg** [google/ExoPlayer#4720] opened 2018-08-23 14:52 UTC
### Issue description
ExoPlayer doesn't get the duration, therefore seeking is not possible (and obviously to get the duration).

### Reproduction steps
The app downloads content as mp4 videos usually. Then it uses ffmpeg to extract the audio as an AAC file. The files usually don't have a file extension on the device. There 
Using android's `MediaMetadataRetriever().extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION);` works an returns expected values which shows that ExoPlayer should be able to do the same too. 

### Link to test content
A test file: https://goo.gl/PCgF6y

### Version of ExoPlayer being used
2.8.4

### Device(s) and version(s) of Android being used
Android 7 on Samsung Galaxy Tab A
Android 4.4 on Samsung XCover 3
Android 8 on Samsung Note 

### A full bug report captured from the device
```
08-23 16:47:14.596 11462-13852 I/OMXClient: MuxOMX ctor
08-23 16:47:14.598 11462-13852 I/ACodec: [OMX.google.aac.decoder] Now Loaded
08-23 16:47:14.599 11462-13852 I/ACodec: codec does not support config priority (err -2147483648)
08-23 16:47:14.601 11462-13852 I/ACodec: codec does not support config priority (err -2147483648)
08-23 16:47:14.603 11462-13852 I/ACodec: [OMX.google.aac.decoder] Now Loaded->Idle
08-23 16:47:14.609 11462-13852 I/ACodec: [OMX.google.aac.decoder] Now Idle->Executing
08-23 16:47:14.610 11462-13852 I/ACodec: [OMX.google.aac.decoder] Now Executing
08-23 16:47:14.616 11462-13852 I/ACodec: [OMX.google.aac.decoder] Now handling output port settings change
08-23 16:47:14.623 11462-13852 I/ACodec: [OMX.google.aac.decoder] Now Executing
08-23 16:47:14.643 11462-12143 D/AudioTrack: Client defaulted notificationFrames to 4725 for frameCount 14176
08-23 16:47:14.646 11462-12143 I/AudioTrack: This process already got info. FadeIn[0] FadeOut[0] FadeInRing[0]
```

If I forgot anything or was unclear about certain things, please say so. It is My first opening issue on a project 😄

**Comment by ojw28** [comment] 2018-08-23 16:10
Duplicate of https://github.com/google/ExoPlayer/issues/4548. Support is being added in 2.9.0.

**Closed as completed by ojw28** 2018-08-23 16:10 UTC
Labels: duplicate
