### ISSUE TITLE
1.5.4 - Mp3 playback glitch every 1-2 minutes

### ISSUE THREAD

**Issue by GoranStorytel** [google/ExoPlayer#1219] opened 2016-02-02 14:32 UTC
Since updating to 1.5.4 the playback glitches every 1-2 minutes, it is as if a mp3 frame is dropped.
DataSource seems not to matter so maybe bug is in extractor?
This bug was introduced after 1.5.2 (no issues on this version).

Phones that experience this issue (that we've identified so far):
Samsung Galaxy Note 4 running 5.1.1
Sony Xperia D5503 compact running 5.1.1
Samsung GT-I9300 running 4.3

Unaffected devices/versions (tested):
HTC One X+ running 4.2.2
API 23 Emulator (x86)
API 18 Emulator (x86)

**Comment by andrewlewis** [comment] 2016-02-03 12:13
I wasn't able to reproduce this on a Galaxy Note 4 (trlte), though the device is running 4.4.4. I hope to be able to test on 5.1.1 tomorrow.

Please could you provide full steps to reproduce the issue in the demo app? What stream are you playing? Does the glitch happen during the first two minutes of playback every time? Thanks.

**Comment by andrewlewis** [comment] 2016-02-05 14:06
I wasn't able to reproduce this on a Samsung Galaxy Note 4 (trlte) running 5.0.1 or 5.1.1 when playing MP3 streams via the demo app.

To diagnose this we will need the information described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). Also, do you have any idea what change between 1.5.2 and 1.5.4 caused the change in behavior you saw?

**Comment by ojw28** [comment] 2016-02-24 14:02
Closing due to lack of required information.

**Closed by ojw28** 2016-02-24 14:02 UTC
Labels: need more info
