### ISSUE TITLE
ImaAdsLoader.java line 1433 

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#6577] opened 2019-10-23 13:20 UTC
## [REQUIRED] Issue description
Still don't wanna be so sad and disappointed with all bug report that I made long time ago until now with this library and its stability issue :( All of a sudden got this error on one of my device when playing a video using ExoPlayer with IMA SDK. This never happens before though. I think it is pointing with WebView. Is IMA SDK using webview to show/load ads?

### [REQUIRED] Reproduction steps
Can't really tell since it only happens on specific device by just attempting to play video.

### [REQUIRED] Link to test content
with Single Skippable Inline ad and an mp4 video from Firebase Storage
https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags

### [REQUIRED] A full bug report captured from the device

**Report from Crashlytic Firebase**

`Fatal Exception: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
       at android.content.res.Resources.getText(Resources.java:330)
       at android.content.res.Resources.getString(Resources.java:428)
       at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
       at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
       at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:674)
       at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:823)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:662)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:597)
       at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:319)
       at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:104)
       at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:271)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:131)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:118)
       at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:115)
       at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:268)
       at android.webkit.WebView.<init>(WebView.java:591)
       at android.webkit.WebView.<init>(WebView.java:526)
       at android.webkit.WebView.<init>(WebView.java:509)
       at android.webkit.WebView.<init>(WebView.java:496)
       at android.webkit.WebView.<init>(WebView.java:486)
       at com.google.ads.interactivemedia.v3.internal.jd.<init>(IMASDK:1)
       at com.google.ads.interactivemedia.v3.internal.jc.<init>(IMASDK:29)
       at com.google.ads.interactivemedia.v3.internal.ii.<init>(IMASDK:14)
       at com.google.ads.interactivemedia.v3.internal.ii.<init>(IMASDK:9)
       at com.google.ads.interactivemedia.v3.api.ImaSdkFactory.createAdsLoader(IMASDK:10)
       at c.h.b.b.p0.a.a$b.a(ImaAdsLoader.java:1433)
       at c.h.b.b.p0.a.a.<init>(ImaAdsLoader.java:477)
       at c.h.b.b.p0.a.a.<init>(ImaAdsLoader.java:402)
       at com.bitwise.manilaaidandsafetyapp.exoplayer.b.i(ExoPlayerManager.java:269)
       at com.bitwise.manilaaidandsafetyapp.exoplayer.b.f(ExoPlayerManager.java:208)
       at com.bitwise.manilaaidandsafetyapp.b.og.d(ActivityMediaPageAdapter.java:280)
       at com.bitwise.manilaaidandsafetyapp.common.FullScreenActivity$a.c(FullScreenActivity.java:166)
       at com.bitwise.manilaaidandsafetyapp.common.t0.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Report with Android Studio**
`.chromium.android_webview.AwContents.<init>(AwContents.java:597)
        at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:319)
        at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:104)
        at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:271)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:131)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:118)
        at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:115)
        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:268)
        at android.webkit.WebView.<init>(WebView.java:591)
        at android.webkit.WebView.<init>(WebView.java:526)
        at android.webkit.WebView.<init>(WebView.java:509)
        at android.webkit.WebView.<init>(WebView.java:496)
        at android.webkit.WebView.<init>(WebView.java:486)
        at com.google.ads.interactivemedia.v3.internal.jd.<init>(IMASDK:1)
        at com.google.ads.interactivemedia.v3.internal.jc.<init>(IMASDK:29)
        at com.google.ads.interactivemedia.v3.internal.ii.<init>(IMASDK:14)
        at com.google.ads.interactivemedia.v3.internal.ii.<init>(IMASDK:9)
        at com.google.ads.interactivemedia.v3.api.ImaSdkFactory.createAdsLoader(IMASDK:10)
        at c.h.b.b.p0.a.a$b.a(ImaAdsLoader.java:1433)
        at c.h.b.b.p0.a.a.<init>(ImaAdsLoader.java:477)
        at c.h.b.b.p0.a.a.<init>(ImaAdsLoader.java:402)
        at com.bitwise.manilaaidandsafetyapp.exoplayer.b.i(ExoPlayerManager.java:269)
        at com.bitwise.manilaaidandsafetyapp.exoplayer.b.f(ExoPlayerManager.java:208)
        at com.bitwise.manilaaidandsafetyapp.b.ai.d(RecyclerMediaPageAdapter.java:226)
        at com.bitwise.manilaaidandsafetyapp.b.wg$c$a.c(AnnouncementRecyclerAdapter.java:1394)
        at com.bitwise.manilaaidandsafetyapp.b.j0.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
ALPS T702 Android L 5.1

**Comment by andrewlewis** [comment] 2019-10-23 13:27
Yes, the IMA SDK uses WebView internally (as I understand it, its core functionality is implemented in JavaScript).

I will look into this and follow-up soon.

**Comment by andrewlewis** [comment] 2019-10-23 13:29
Just a guess: are you using androidx.appcompat 1.1.0? If so maybe https://issuetracker.google.com/issues/141351441 is relevant.

**Comment by ArcherEmiya05** [comment] 2019-10-23 13:35
> androidx.appcompat 1.1.0

Yes yes 1.1.0

**Comment by ArcherEmiya05** [comment] 2019-10-23 13:39
The device I am using is just a clone which most likely a china refurbish software type, I am also facing issue when using a WebView with it as it does not come with WebView by default so app crash when trying to use it. But again and again I am wondering why I only get this crash today not from the very beginning? This SO might prove the problem with WebViews too with Lollipop
**[https://stackoverflow.com/questions/46810118/exception-on-new-webview-on-lollipop-5-1-devices](url)**

**Comment by andrewlewis** [comment] 2019-10-23 14:10
I'd try downgrading to androidx.appcompat 1.0.0 if you have that option, based on the report in https://issuetracker.google.com/issues/141351441.

**Comment by ArcherEmiya05** [comment] 2019-10-23 15:56
Thank you for quick response now I am somehow still facing the error on this Lollipop device even downgrading my appcompat to 1.0.0

**Comment by ArcherEmiya05** [comment] 2019-10-23 16:12
Just another supporting detail these is where the crash start on ExoPlayerManager.java:269
`adsLoader = new ImaAdsLoader(this.context, adsUri);`

**Comment by andrewlewis** [comment] 2019-10-28 15:38
Please see https://issuetracker.google.com/issues/141351441#comment6. Is your app doing anything special with resources?

**Comment by ArcherEmiya05** [comment] 2019-10-28 15:49
> 
> 
> Please see https://issuetracker.google.com/issues/141351441#comment6. Is your app doing anything special with resources?

What do you mean by anything special with resource?

**Comment by ArcherEmiya05** [comment] 2019-10-28 15:51
**UPDATED:** The apps works fine before but no idea why is it no longer playing and crash. Maybe because of updating some dependencies which I can't point out to what possible dependency that causing this issue until now. Before it never gets crash only now and still error with `String resource ID #0x2040003`
as far as I know this kind of error happens when you put `accidentally an int value like 1` in a `TextView.setText()` and the system thought will interpret this a **resource id** rather than a **String value**

**Comment by andrewlewis** [comment] 2019-10-29 17:47
The bug I linked to says mentions that wrapping resources is not supported. I'm not sure exactly what this means but it sounds like the issue is caused by the app's behavior and can't be fixed in appcompat itself, so I suggest checking how your app handles resources.

As another datapoint, I wasn't able to reproduce this issue on an Android L emulator image using the demo app and with a dependency on androidx.appcompat:appcompat:1.1.0.

**Closed as completed** 2019-11-12 13:27 UTC
Labels: wont fix: app issue
