### ISSUE TITLE
Player doesn't switch to play media if vast ad media timeout occurs.

### ISSUE THREAD

**Issue by shubhamvashisht** [google/ExoPlayer#10494] opened 2022-08-02 14:14 UTC
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

OnePlus Nord 

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Set Any AD tag URI with an ad break
2. wait for media timeout to happen. (you will get LOG event with error code 402)
3. Player will stuck ( wont switch back to media)

### Expected result

Player should switch back to media.

### Actual result

Player will stuck, No ads or Media will be resumed.

### Media

Not applicable

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment] 2022-08-03 11:43
Can you clarify how you trigger step 2 in your reproduction steps?
> wait for media timeout to happen. (you will get LOG event with error code 402)

If I just set any ad tag uri and play, there won't be any timeout because everything loads successfully.

**Comment by tonihei** [comment] 2022-08-10 13:16
Assuming this is the same issue as #10510 and closing as duplicate.

**Closed as completed by tonihei** 2022-08-10 13:16 UTC
Labels: duplicate
