### ISSUE TITLE
Failed to set frame packing format on component

### ISSUE THREAD

**Issue by PanCrucian** [google/ExoPlayer#3402] opened 2017-10-28 08:05 UTC
I use ExoPlayer v2.5.4 together with [LibRtmp-Client-for-Android](https://github.com/ant-media/LibRtmp-Client-for-Android), and when i try to play this stream _**rtmp://188.130.252.20:1935/live/test live=1**_ the stream displays the first frame and freezes (last incoming state STATE_BUFFERING)
For MediaSource used com.google.android.exoplayer2.source.ExtractorMediaSource

partial code:
```
RtmpDataSourceFactory dataSourceFactory = new RtmpDataSource.RtmpDataSourceFactory();
MediaSource mediaSource = new ExtractorMediaSource(Uri.parse("rtmp://188.130.252.20:1935/live/test live=1"), dataSourceFactory, new DefaultExtractorsFactory(), null, null);
```
log:
```
I/OMXClient: Using client-side OMX mux.
I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 18942978
I/ExtendedACodec: setupVideoDecoder()
I/ExtendedACodec: vpp-enable search is 0 and value is 0
I/ExtendedACodec: Decoder will be in frame by frame mode
W/ExtendedACodec: Failed to set frame packing format on component
W/ExtendedACodec: Failed to get Profile and Level from Component
W/ExtendedACodec: Failed to get Entropy from Component
```
Mister @mekya (author [rtmp lib](https://github.com/ant-media/LibRtmp-Client-for-Android)) [said](https://github.com/ant-media/LibRtmp-Client-for-Android/issues/51#issuecomment-340149517): "Yeah I have checked and you are right. It seems that it is a codec issue in ExoPlayer."
Can u please check too and fix codec issue
Device used for testing Le X527, API 23

**Comment by ojw28** [comment] 2017-11-01 14:51
The logging you're looking at isn't relevant (which is why it's always more useful to attach a full bug report than a snippet of logcat). This is a duplicate of #3188. There's also a workaround in that thread (replacing `readTagData` in `FlvExtractor` with the one suggested there).

**Closed as completed by ojw28** 2017-11-01 14:51 UTC
Labels: duplicate

**Comment by PanCrucian** [comment] 2017-11-01 14:59
Hmm ... this is not the answer I wanted to get. Did you at least check the rtmp link? or too lazy?

**Comment by ojw28** [comment] 2017-11-01 15:07
Yes I did check it, and I confirmed it was a duplicate of the issue I marked it a duplicate of, and I also confirmed that the workaround in that thread allows your link to play.

**Comment by PanCrucian** [comment] 2017-11-01 15:09
ok sorry
