### ISSUE TITLE
Synchronize current position and duration during live streaming. 

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#9146] opened 2021-07-03 10:23 UTC
During live streaming (DASH) exoplayer does not maintain the current position of the content in a stable way (currently scrubber moves from right to left as new content is added to the timeline), but many applications want to keep the scrubber stable (similar to youtube). Example can be found:

https://bitmovin.com/demos/stream-test?format=dash&manifest=https%3A%2F%2Flivesim.dashif.org%2Flivesim%2Fchunkdur_1%2Fato_7%2Ftestpic4_8s%2FManifest.mpd

Possible solution:

Move this buffering gap out of the timeline. In the example above the window size is 5 min, but only 4:20 min is presented to the user so I suspect that the 40 seconds are kept outside the timeline (reserving these for buffering) with this the scrubber can be kept at end of timeline.

**Comment by icbaker** [comment] 2021-07-05 08:40
The description of this problem seems very UI specific, but the proposed solution seems to suggest changing the core library.

If I'm understanding correctly, and this is a request for different behaviour of the scrubber bar in the ExoPlayer UI component, I think it's a duplicate of https://github.com/google/ExoPlayer/issues/2213. I'm going to close this - but feel free to reply here and clarify if I've misunderstood.

**Closed as completed by icbaker** 2021-07-05 08:40 UTC
Labels: duplicate

**Comment by javaboboApp** [comment] 2021-07-12 10:16
Thanks for replying the problems is ui stuff but I think that is related with the way that **PlayerViewController** works.
So this solution I guess should be related with change how this class behave , I do not think another way of changing this behaviour without modifying this class.

**Comment by javaboboApp** [comment] 2021-07-12 13:58
In the function **updateProgress**  located in **PlayerViewController**
player.getContentPosition() is increasing a decreasing I was expecting a constant increase (during live (linear) ) using dash protocol.  So it duration does not change let say that I fix the duration in timeline  timeBar.setDuration(59s); 
current time should increase every second, but for my surprise it does not happen. Can I know why?? It would be really helpful for me... 

**|** -> current position.

time =0 s, current_position(30s) |--------**|**--------| end (59s)
time =1 s, current_position(35s) |-------------**|**----| end (59s)
time =2 s, current_position(10s) |----**|**--------------| end (59s)

How Could I archive a constant increase?

**Comment by icbaker** [comment] 2021-07-12 14:00
This documentation should explain how `Player.getCurrentPosition()` is related to the current live window:
https://exoplayer.dev/live-streaming.html#detecting-and-monitoring-live-playbacks

**Comment by javaboboApp** [comment] 2021-07-12 14:12
Ok  so in order to archive a constant increase (1 s) I would have to omit totally getCurrentPosition...

**Comment by javaboboApp** [comment] 2021-07-13 09:18
Thanks for the link, according with the documentation:

**Player.getCurrentPosition returns the playback position relative to the start of the live window.**

If I want to archive constants increase in the ui part, current position synchronises with the windows.duration increase, should I consider to re-calculate getCurrentPosition() to make it relative to the start period?
