### ISSUE TITLE
Bug with counting time Exoplayer 2.17.0

### ISSUE THREAD

**Issue by Stinger2198** [google/ExoPlayer#10083] opened 2022-03-17 14:23 UTC
ExoPlayer version 2.17.0
Android version 7
Android device - Amazon Fire tv stick
When watching a video (streaming from the link), the video comes to the end of time but seconds continue to go further (for example, the video 30 seconds, when the video came to the end, the picture hangs, but the seconds continue to go 56/30) before updating the library, the OnPlayerStateChanged method from Playereventlistener class worked fine and now it is randomly, it can work immediately, and can after 30 seconds over time the video duration (59 out of 30 seconds) can work in a minute of 90 out of 30 seconds.
I can add apk for you test or example code from app.
My company using your player a long time and we never have had problem with that, but it came.
Thank you for help!!
![photo](https://user-images.githubusercontent.com/30195609/158827506-5c08a2ff-b6ac-4805-a4ae-a2f4ab265842.jpg)
!

**Comment by ojw28** [comment] 2022-03-18 14:07
This is likely due to an issue with the media where there's some samples that have timestamps beyond the end of the video track (e.g., metadata of text samples). If you want us to take a look, please provide us with a playable link to the media in question.

**Comment by Stinger2198** [comment] 2022-03-21 12:32
> This is likely due to an issue with the media where there's some samples that have timestamps beyond the end of the video track (e.g., metadata of text samples). If you want us to take a look, please provide us with a playable link to the media in question.

Hi!

**Comment by Stinger2198** [comment] 2022-03-21 12:32
This is my link for stream video - https://cdn.brid.tv/live/partners/7343/hd/443852.mp4

**Comment by ojw28** [comment] 2022-03-24 13:39
I was not able to reproduce the issue with either of the videos, and neither seem to correspond to the video for which you initially reported the problem. Please could you double check. If you're sure one of these videos reproduces the issue, please:

1. Specify which one we should use (we don't need two)
2. Let us know what duration the UI is displaying, and at what duration playback actually finishes (if at all)
3. Let us know which version of ExoPlayer you're using

**Comment by Stinger2198** [comment] 2022-03-24 15:27
> I was not able to reproduce the issue with either of the videos, and neither seem to correspond to the video for which you initially reported the problem. Please could you double check. If you're sure one of these videos reproduces the issue, please:
> 
> 1. Specify which one we should use (we don't need two)
> 2. Let us know what duration the UI is displaying, and at what duration playback actually finishes (if at all)
> 3. Let us know which version of ExoPlayer you're using

Hi @ojw28 
1. I leave one video link - https://cdn.brid.tv/live/partners/7343/hd/443852.mp4
2. Playing finished 04:53/03:45
3. I am using ExoPlayer version 2.17.0
![Screenshot 2022-03-24 172721](https://user-images.githubusercontent.com/30195609/159951639-4f617490-b624-45a4-944a-162150061ec2.png)
0

**Comment by Stinger2198** [comment] 2022-03-24 15:29
I am tested on browser - working fine, but on fire stick i have this trouble.

**Comment by ojw28** [comment] 2022-03-30 18:41
I am unable to reproduce the issue on a Pixel device. If this observed behavior is only on Fire TV Stick, I'd suggest you report it to Amazon because in that case it's likely to be device specific. You could try asking [here](https://github.com/amzn/exoplayer-amazon-port/issues). I would also suggest that you try and reproduce with the [demo app](https://exoplayer.dev/demo-application.html), to rule out any issues in your own code.

If you can reproduce the issue on an official Android device (i.e., not a device running Fire OS) with our demo app, please let us know the exact combination you're using so that we can try and reproduce. Else I'm not sure there's anything actionable for us to do here.

**Comment by ojw28** [comment] 2022-03-30 18:41
Tentatively marking this as a device specific issue.

**Comment by Stinger2198** [comment] 2022-04-20 15:37
Hi.
I am understood you.
But can somebody help me with that problem?
I tried different way, but nothing help me.
Best regards Andrew.

ср, 30 мар. 2022 г. в 21:41, Oliver Woodman ***@***.***>:

**Comment by Stinger2198** [comment] 2022-04-22 14:50
After some time i found where is the problem was.
I am using xml tags String for adding ads, when i am using this method - Util.getDataUriForString("application/xml", vastData); - for parsing to Uri, begin get this issues.
I am again describe problem - when video ended, it will freezed but timer counting time more than video duration (on screenshot).
After some time (random) switching to next video.
Without that method - all working fine, but without ads.
Can I using xml string for that? (looks like not).
Uri.parse (from Java) not worrking for that.
Somebody can help me with that?

**Comment by Stinger2198** [comment] 2022-04-22 15:08
@ojw28 Please check update. This is not device specific

**Comment by ojw28** [comment] 2022-04-22 15:19
I don't really understand the comment above, but I don't think you've provided clear reproduction steps. Please try and reproduce in our demo app (as already suggested above). If you can do so, please provide clear reproduction steps that allow us to efficiently reproduce the issue.

**Comment by Stinger2198** [comment] 2022-04-26 10:03
Hi @ojw28 
Can i send you java class from your demo app with my data? With demo app i have got this issues too.

**Comment by Stinger2198** [comment] 2022-04-26 10:22
https://user-images.githubusercontent.com/30195609/165279362-493f08c8-ef55-4c30-8796-8e4a856ca742.mp4

**Comment by Stinger2198** [comment] 2022-04-26 10:22
Please check screen record from demo app

**Comment by ojw28** [comment] 2022-04-26 10:29
You can send a modified demo app either by forking the repository and making changes to your fork on GitHub (ideal) or by emailing `dev.exoplayer@gmail.com`, with `Issue #10083` in the subject.

**Comment by Stinger2198** [comment] 2022-04-26 10:38
Sent to mail @ojw28

**Comment by Stinger2198** [comment] 2022-04-26 12:39
Before, that working like that (earlier version exoplayer library)
String vmap = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
          "<vmap:VMAP xmlns:vmap=\"http://www.iab.net/videosuite/vmap\" version=\"1.0\">\n" +
          " <vmap:AdBreak timeOffset=\"00:00:15.000\" breakType=\"linear\" breakId=\"midroll-1\">\n" +
          "  <vmap:AdSource id=\"midroll-1-ad-1\" allowMultipleAds=\"false\" followRedirects=\"true\">\n" +
          "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>\n" +
          "  </vmap:AdSource>\n" +
          " </vmap:AdBreak>\n" +
          "</vmap:VMAP>";

ImaAdsLoader.Builder builder = new ImaAdsLoader.Builder(context);
adsLoader = builder.setImaSdkSettings(new ImaSdkSettings()).buildForAdsResponse(vmap);

But now method want only Uri link for ads

**Comment by ojw28** [comment] 2022-04-26 12:50
You're trying to insert adverts 16 minutes into a 4 minute long video, as per `<vmap:AdBreak timeOffset="00:16:00.000"` in the `vastData` that you're adding into the `MediaItem`. This is why playback is not ending at `3:58`. The ad configuration needs to make sense for the video it's being inserted into.

If I remove all the `AdBreak` elements whose offsets are greater than the duration of the video, then playback ends as expected at `3:58`.

**Closed as completed by ojw28** 2022-04-26 12:50 UTC
Labels: question, bad media

**Comment by Stinger2198** [comment] 2022-04-26 13:42
Video can be different duration (example 30-40 minutes).
This vmap must be universal
Before that was working fine

**Comment by Stinger2198** [comment] 2022-04-26 14:05
@ojw28 thank you a lot for help with figure out that problem!!! 
Your advice really helped. 
Best regards Andrew.
