### ISSUE TITLE
Load subtitle file without any noticeable affect on user experience

### ISSUE THREAD

**Issue by Kaaveh** [google/ExoPlayer#9950] opened 2022-02-08 10:05 UTC
For loading a subtitle file, I used this code:

```kotlin
val subtitle: MediaItem.SubtitleConfiguration =
    MediaItem.SubtitleConfiguration.Builder(srtUri)
        .setMimeType(MimeTypes.APPLICATION_SUBRIP)
        .setLanguage("fa")
        .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
        .build()
val mediaItem: MediaItem = MediaItem.Builder()
    .setUri(viewModel.url)
    .setSubtitleConfigurations(ImmutableList.of(subtitle))
    .build()

player?.setMediaItem(mediaItem)
```
This is well but have a small problem. When user browse a `srt` file, It's start play video from beginning. Is there any way to load `srt` in middle of playing video without any noticeable affect on user experience?

**Comment by ojw28** [comment] 2022-02-08 13:56
Unfortunately adding subtitles mid-playback in a seamless way is a pending feature request. Closing as a duplicate of https://github.com/google/ExoPlayer/issues/1649.

**Closed as completed by ojw28** 2022-02-08 13:56 UTC
Labels: duplicate
