### ISSUE TITLE
Drm protected Video lagging when played offline on 2X speed

### ISSUE THREAD

**Issue by NitinSharma639** [google/ExoPlayer#9734] opened 2021-11-26 10:52 UTC
I am trying to play drm protected video which is downloaded. It is working fine on most of the device. It is lagging on tablet devices specifically on Samsung A7 tab(Smt-500).

When I am playing file from server the lagging very less visible but when I play offline video on 2x speed lagging is quite visible.

I am using exoplayer - 2.10.2. I am using following datasource factory.

For online:

```
val defaultHttpDataSourceFactory = DefaultHttpDataSourceFactory(userAgent, defaultBandwidthMeter)

                val mediaDataSourceFactory = DefaultDataSourceFactory(
                    context,
                    defaultBandwidthMeter,
                    defaultHttpDataSourceFactory
                )


                dashMediaSource=DashMediaSource.Factory(mediaDataSourceFactory)
                    .createMediaSource(videoViewModel.uri)
```
for offline:

```
cacheDataSourceFactory = CacheDataSourceFactory(cache, factory)

                    
dashMediaSource = DashMediaSource.Factory(videoViewModel.cacheDataSourceFactory)
                        .createMediaSource(videoViewModel.uri
)
```

Please provide some solution.

previous thread : https://github.com/google/ExoPlayer/issues/8657

Thanks in advance

**Comment by icbaker** [comment] 2021-11-26 11:00
I don't think there's much more we can add beyond https://github.com/google/ExoPlayer/issues/8657#issuecomment-792690825 - did you try the suggestions there?

It could be that the device in question just isn't powerful enough to do both the video decoding and DRM decryption at 2x speed.

**Comment by NitinSharma639** [comment] 2021-11-26 11:41
Yes @icbaker your previous solution improved our online video playback but still there is problem in offline playback. Please help us improve offline playback as well. We have tried a lot . Still it is not improving.

**Comment by icbaker** [comment] 2021-11-26 16:36
Have you identified the source of the lagging? I'm surprised you're seeing a difference between offline and streamed playback, I'd expect the media decoding and DRM decryption flows to be very similar between the two - is it possible the local storage you're loading the video from is slow? This would show up as rebuffering events.

There's not much more help we can provide I'm afraid - as I said, perhaps this device is just too slow for your use-case?

**Comment by NitinSharma639** [comment] 2021-11-30 06:13
@icbaker Can I send you bug report so that you reiterate over it. It is very strange behaviour by exoplayer.  I think
CacheDataSourceFactory is causing issues. Do you have any alternative for this or any better way to implement offline playback. Please if you can guide us.

**Comment by icbaker** [comment] 2021-12-03 12:07
> @icbaker Can I send you bug report so that you reiterate over it

For a BR to be useful in this case you will need to ensure that you're [using an `EventLogger` to provide additional debug logcat logging](https://exoplayer.dev/debug-logging.html). If you have a BR with `EventLogger` output in it then I'm happy to have a look - but I can't guarantee I'll be able to identify the source of the problem from it.

> I think CacheDataSourceFactory is causing issues

Could you go into more detail about why you believe this is the cause of the problems?

> Do you have any alternative for this or any better way to implement offline playback. Please if you can guide us.

Have you read through https://exoplayer.dev/downloading-media.html?

**Comment by NitinSharma639** [comment] 2021-12-06 09:10
Hi @icbaker 

I have sent the bug report. Please check. In the meantime we are checking https://exoplayer.dev/downloading-media.html.

Thanks

**Comment by icbaker** [comment] 2021-12-06 15:26
Thanks for the bug report, I see several lines like the following:
```
EventLogger: droppedFrames [218.22, 377.29, window=0, period=0, 50]
```
```
EventLogger: audioTrackUnderrun [214.94, 371.01, window=0, period=0, 61504, 320, 133]]
```

The final number in the `droppedFrames` indicate how many frames were dropped. This is usually `50` because these frame drops are accumulated and only logged when >= 50 have happened.

The final 3 numbers in the `audioTrackUnderrun` message are `bufferSize` (in bytes), `bufferSizeMs` and `elapsedSinceLastFeedMs`.

I don't see many state transitions from `READY` to `BUFFERING` - certainly not enough that would explain this problem as due to rebuffering. These are lines like:
```
EventLogger: state [1.17, 1314.00, window=0, period=0, true, BUFFERING]
```

An underrun occurs when the AudioTrack runs out of audio data, which suggests decoding isn't happening fast enough. The frame drops suggest the same. Neither of these suggest slowness when reading from the `DataSource` - that would show up as `BUFFERING` state transitions, which as I said, I don't see.

**Comment by NitinSharma639** [comment] 2021-12-07 05:56
Hi @icbaker 

Do you have any suggestion so that we can improve the performance? We can reproduce this on sample app provide by the exoplayer as well from [here](https://github.com/google/ExoPlayer). Please guide us. 

Thanks

**Comment by icbaker** [comment] 2021-12-07 10:39
I'm afraid there's not much I can suggest - you're trying to play encrypted content at 2x speed and it seems that the device just isn't performant enough to support this.

I don't know why you're seeing a difference between offline and streaming playback - if this is a DASH asset with different tracks with different bitrates available, is it possible that while streaming you're playing lower bitrate tracks (which the decoder can keep up with) whereas when playing offline the app has downloaded higher bitrate tracks (which the decoder is unable to decode at 2x speed)? If this is the case then you could customise your download logic to ensure the lower bitrate tracks are downloaded: https://exoplayer.dev/downloading-media.html#downloading-and-playing-adaptive-streams

**Comment by NitinSharma639** [comment] 2021-12-09 07:09
Hi @icbaker 

We can see lagging while playing on 360p in offline. We can reproduce this issue on multiple devices. Your following comment shows it is decoding issue.

"An underrun occurs when the AudioTrack runs out of audio data, which suggests decoding isn't happening fast enough." 

But some other apps are working fine on the same device. Can you provide us the some decoding technique? What areas we should explore to improve our video playing.

Following are the list of devices on which we can see lagging.

Samsung Galaxy Tab S6 lite | 11
Redmi note 5 pro | 10
POCO F1 | 10
SM-T500 | 10
Redmi Note 8 Pro | 10
Realme 6 | 11
Lenovo Tab | 11
Realme GT series | 11
Realme Tab | 10 & 11
Samsung Galaxy F4 | 11
Oppo f19 pro-Plus | 11
Samsung Galaxy A12 | 11
Samsung Galaxy Tab A7 | 11
Realme XT | 11
Redmi 6 Pro | 10

**Comment by icbaker** [comment] 2021-12-09 11:28
> But some other apps are working fine on the same device.

To confirm: When you play exactly the same (DRM'd) content in these other apps, at 2x speed, from an offline source, you don't see any performance issues?

Are these apps using `MediaCodec` or some other decoder (maybe one bundled in the app)?

**Comment by NitinSharma639** [comment] 2021-12-09 12:22
@icbaker 

We are suspecting the same. We know that they are using exoplayer with some customisation. We are not sure about what exactly they are using. I can send you the names of the apps in email. I do not want to share it here.

Also looking for guidance from you. 

Thanks

**Comment by icbaker** [comment] 2021-12-09 15:49
> We are suspecting the same. We know that they are using exoplayer with some customisation. We are not sure about what exactly they are using.

I'm afraid we can't really help you guess how other apps might be customising our library - the quickest way to get an answer is probably to ask them directly.

I'm going to close this issue as I don't think there's anything actionable for the ExoPlayer library here.

**Closed as completed by icbaker** 2021-12-09 15:49 UTC
Labels: question

**Comment by NitinSharma639** [comment] 2021-12-10 13:11
Hi @icbaker 

Can you give us some way we can improve on the player. It is just not about asking other apps. They will not give us there business logic. If there is some way we can improve our player. Please guide us.

Thanks
