### ISSUE TITLE
Deadlock with media2 extension

### ISSUE THREAD

**Issue by h6ah4i** [google/ExoPlayer#8765] opened 2021-03-28 12:53 UTC
I faced a deadlock issue by chance. I am using a dedicated thread for handling `SessionPlayer.PlayerCallback` events instead of the main thread. (I suppose this threading usage is allowed by ExoPlayer's design. Am I doing wrong...?)

- ExoPlayer version number: 2.13.1
- AndroidX media2 version number: 1.1.2
- Android version: 11
- Android device: Emulator

---

### Code sample

```kotlin
exoPlayer = SimpleExoPlayer.Builder(this).setAudioAttributes(...).build()

sessionPlayer = SessionPlayerConnector(exoPlayer)

playerEventExecutor = Executors.newSingleThreadExecutor { runnable ->
          Thread(runnable, "BuiltInPlayerCallbackHandlerThread")
        }

sessionPlayer.registerPlayerCallback(
        playerEventExecutor,
        object : SessionPlayer.PlayerCallback() {
          ...
        })
```

---

### Thread dump

```java
"main@15757" prio=5 tid=0x2 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for BuiltInPlayerCallbackHandlerThread@20246 to release lock on <0x537e> (a java.lang.Object)
	  at androidx.media2.session.MediaSessionImplBase.getPlayer(MediaSessionImplBase.java:393)   // !!! <-- getPlayer() takes a lock
	  at androidx.media2.session.MediaSession.getPlayer(MediaSession.java:262)
	  at com.google.android.exoplayer2.ext.media2.SessionCallback.buildAllowedCommands(SessionCallback.java:249)
	  at com.google.android.exoplayer2.ext.media2.SessionCallback.access$300(SessionCallback.java:49)
	  at com.google.android.exoplayer2.ext.media2.SessionCallback$PlayerCallback.updateAllowedCommands(SessionCallback.java:377)
	  at com.google.android.exoplayer2.ext.media2.SessionCallback$PlayerCallback.onBufferingStateChanged(SessionCallback.java:369)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.lambda$setBufferingState$18$SessionPlayerConnector(SessionPlayerConnector.java:554)
	  at com.google.android.exoplayer2.ext.media2.-$$Lambda$SessionPlayerConnector$b27JkDfvo1utAZsl3VBBcdR9wXc.callCallback(lambda:-1)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.lambda$notifySessionPlayerCallback$19(SessionPlayerConnector.java:568)
	  at com.google.android.exoplayer2.ext.media2.-$$Lambda$SessionPlayerConnector$MZZkjhyg_XkD-4ThzP2ij2-iAA0.run(lambda:-1)
	  at com.google.android.exoplayer2.ext.media2.-$$Lambda$PNiE7SuEFxRjAZH7pJpZIFOFjWg.execute(lambda:-1)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.notifySessionPlayerCallback(SessionPlayerConnector.java:568)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.setBufferingState(SessionPlayerConnector.java:553)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.access$300(SessionPlayerConnector.java:58)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector$ExoPlayerWrapperListener.onBufferingEnded(SessionPlayerConnector.java:711)
	  at com.google.android.exoplayer2.ext.media2.PlayerWrapper.updateBufferingState(PlayerWrapper.java:418)
	  at com.google.android.exoplayer2.ext.media2.PlayerWrapper.handlePlayerStateChanged(PlayerWrapper.java:445)
	  at com.google.android.exoplayer2.ext.media2.PlayerWrapper.access$300(PlayerWrapper.java:50)
	  at com.google.android.exoplayer2.ext.media2.PlayerWrapper$ComponentListener.onPlaybackStateChanged(PlayerWrapper.java:597)
	  at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$14(ExoPlayerImpl.java:1058)
	  at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$IyZUXxirQd_yqs72UV3Zn1-mksQ.invoke(lambda:-1)
	  at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:297)
	  at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:184)
	  at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(lambda:-1)
	  at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:205)
	  at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1101)
	  at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:965)
	  at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$ExoPlayerImpl(ExoPlayerImpl.java:181)
	  at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$nOBJYkeEQ2uz3sBKLToLWmzrgZk.run(lambda:-1)
	  at android.os.Handler.handleCallback(Handler.java:938)
	  at android.os.Handler.dispatchMessage(Handler.java:99)
	  at android.os.Looper.loop(Looper.java:223)
	  at android.app.ActivityThread.main(ActivityThread.java:7656)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

"BuiltInPlayerCallbackHandlerThread@20246" prio=5 tid=0x572 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks main@15757
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
	  at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:523)
	  at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:90)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.runPlayerCallableBlocking(SessionPlayerConnector.java:625)   // !!! <-- Waiting for the main thread
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.runPlayerCallableBlocking(SessionPlayerConnector.java:654)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.getCurrentPosition(SessionPlayerConnector.java:184)
	  at androidx.media2.session.MediaSessionImplBase$12.run(MediaSessionImplBase.java:560)
	  at androidx.media2.session.MediaSessionImplBase$12.run(MediaSessionImplBase.java:556)
	  at androidx.media2.session.MediaSessionImplBase.dispatchPlayerTask(MediaSessionImplBase.java:1106)
	  at androidx.media2.session.MediaSessionImplBase.getCurrentPosition(MediaSessionImplBase.java:556)
	  at androidx.media2.session.MediaSessionImplBase.createPlaybackStateCompat(MediaSessionImplBase.java:1011)
	  - locked <0x537e> (a java.lang.Object)    // !!! <-- createPlaybackStateCompat() takes a lock
	  at androidx.media2.session.MediaSessionLegacyStub$ControllerLegacyCbForBroadcast.onPlayerStateChanged(MediaSessionLegacyStub.java:816)
	  at androidx.media2.session.MediaSessionImplBase$SessionPlayerCallback$1.run(MediaSessionImplBase.java:1417)
	  at androidx.media2.session.MediaSessionImplBase.dispatchRemoteControllerTaskWithoutReturn(MediaSessionImplBase.java:1232)
	  at androidx.media2.session.MediaSessionImplBase$SessionPlayerCallback.onPlayerStateChanged(MediaSessionImplBase.java:1414)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.lambda$setState$17$SessionPlayerConnector(SessionPlayerConnector.java:543)
	  at com.google.android.exoplayer2.ext.media2.-$$Lambda$SessionPlayerConnector$pX4iY_5SaiNgV31Tj67e40OG44g.callCallback(lambda:-1)
	  at com.google.android.exoplayer2.ext.media2.SessionPlayerConnector.lambda$notifySessionPlayerCallback$19(SessionPlayerConnector.java:568)
	  at com.google.android.exoplayer2.ext.media2.-$$Lambda$SessionPlayerConnector$MZZkjhyg_XkD-4ThzP2ij2-iAA0.run(lambda:-1)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	  at java.lang.Thread.run(Thread.java:923)

```

**Comment by h6ah4i** [comment] 2021-03-28 15:28
[UPDATE] I think this is the media2 side issue. It seems that this issue has already been fixed by the following commit.

https://android.googlesource.com/platform/frameworks/support/+/e0188912b1e399906ec7814280f22f61ee42ce54%5E%21/#F1

**Comment by lcf87** [comment] 2021-03-29 13:31
It seems the issue is gone now? If so could you close the issue?

**Comment by h6ah4i** [comment] 2021-04-03 06:38
The fixed version of media2 will be v1.2.0 which is not released yet. I have resolved this issue by building the latest AndroidX code pulled from [their repository](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main).

**Comment by SungsooLim** [comment] 2021-04-06 02:34
I'll schedule media2 v1.2.0 ASAP.
I'm expecting it to be released early June.

2021년 4월 3일 (토) 오후 3:39, Haruki Hasegawa ***@***.***>님이 작성:

**Comment by SungsooLim** [comment] 2021-04-06 04:41
Since the stable release would take time, I'll cherry-pick the change into media2 release branch and release media2 1.1.3 first.

**Closed as completed** 2021-06-26 08:29 UTC
Labels: bug
