### ISSUE TITLE
In playlist, consecutive renderers getting data from SingleSampleMediaSource get the "onStreamChanged" callback too soon

### ISSUE THREAD

**Issue by b0g8** [google/ExoPlayer#2652] opened 2017-04-05 15:02 UTC
### Issue description
I have a playlist with several consecutive media, rendered by a custom renderer, getting data from SingleSampleMediaSource (read once the data, and display it for several seconds, according to parameters of SingleSampleMediaSource). The onStreamChanged callback is triggered several times during first media, with corresponding offsets(for each of them). The problem seem to arise in updatePeriods (ExoPlayerImplInternal.java), where renderer.replaceStream gets called for all media, while first media did not finish rendering.

Handling all of them (the streams) in the renderer is difficult, since each data is quite large. Workarounds would include: do not set hasReadStreamToEnd, until the end of the current media being rendered, or introduce initial discontinuity for each (don't know how to do that)

I would expect to get the callback for the next media after the current media is done rendering.

### Reproduction steps
Not that easy with the demo app. Anyway, code analysis of updatePeriods (ExoPlayerImplInternal.java) should reveal the issue.

### Link to test content
NA

### Version of ExoPlayer being used
Release 2.2.0

### Device(s) and version(s) of Android being used
Android 4.3, Samsung Galaxy S3, 100% reproduction, does not seem device dependent.

### A full bug report captured from the device
NA

**Comment by ojw28** [comment] 2017-04-06 17:49
This is working as intended. Some renderer implementations are pipelined (i.e. have a certain amount of internal buffer). If we were to wait for the first piece of the media to fully play out before moving to the next, that would require completely emptying the renderer pipelines. This in turn would result in stuttering at the point of transition. It would also break gapless audio playback.

> Handling all of them (the streams) in the renderer is difficult, since each data is quite large. Workarounds would include: do not set hasReadStreamToEnd, until the end of the current media being rendered, or introduce initial discontinuity for each (don't know how to do that)

I'm not really sure what you mean by this. It's up to your renderer implementation to choose how far it reads ahead, since it's the thing that's reading from the sample stream. If you feel your renderer is reading too far ahead, just don't read anything else from the sample stream for a while.

**Closed as completed by ojw28** 2017-04-06 17:49 UTC
Labels: question, wont fix: infeasible

**Comment by b0g8** [comment] 2017-04-10 11:27
Thanks.
