### ISSUE TITLE
ExoPlayer not normal end when playback HLS live streaming end 

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#2048] opened 2016-11-08 09:18 UTC
Use the ExoPlayer-dev2 latest code, use ExoPlayerDemo, playback HLS live streaming, when the hls live streaming end, the exoplayer still send state buffering, not normal end, the dev1 work well, playback HLS VOD video well

**Comment by AquilesCanta** [comment] 2016-11-08 09:47
See #1961. If not applicable(the playlist does contain the #EXT-X-ENDLIST tag), open a new one including the information required in the issue template.

**Comment by AquilesCanta** [comment] 2016-11-08 10:09
@ojw28 pointed out this is not working correctly. I will reproduce myself and will use this issue to track the bug. Sorry for closing it prematurely!

**Comment by AquilesCanta** [comment] 2016-11-08 10:44
This is indeed a bug in dev-v2 but has been fixed in the internal version. Wait for the next push and  it will be fixed. Will keep this open until confirmation. Thanks for reporting!

**Comment by crossle** [comment] 2016-11-08 10:46
ok, hope push today，😄

**Comment by ojw28** [comment] 2016-11-18 13:00
This should be fixed in `dev-v2`.

**Comment by crossle** [comment] 2016-11-18 16:00
no, still not normal end

**Comment by ojw28** [comment] 2016-11-18 16:06
Just saying "doesn't work" isn't particularly helpful to us. Are you certain `#EXT-X-ENDLIST` is being appended correctly?

**Comment by crossle** [comment] 2016-11-22 03:18
#EXT-X-ENDLIST correct, because dev-v1 work well

**Comment by AquilesCanta** [comment] 2016-11-22 15:32
Can you provide the exact ways to reproduce the issue?

- Are you seeking yourself directly to the end or do you let it play until the end is reached by itself? I assume you are not seeking at all, considering this is not supported in V1, but just in case.
- Is this a master playlist or a media playlist?
- If a master, how many media playlists are being handled at the same time? Do you have multiple audio renditions? Subtitles?
- The playback starts as live (i.e. It doesn't have an ENDLIST tag) but eventually you add it?

I will need some more context as I am not able to reproduce the issue. If you could attach a debugger and see what's going on in the player when it is stuck in buffering state that would also be great. I am now going to create and play a live stream, and see if I can reproduce. But if I cannot and no further information is provided, I will have to close the issue.

**Comment by ojw28** [comment] 2017-01-03 22:12
Closing due to lack of information.

**Closed as completed by ojw28** 2017-01-03 22:12 UTC
Labels: bug
