### ISSUE TITLE
ArrayIndexOutOfBoundsException due to invalid colr atom

### ISSUE THREAD

**Issue by liulei9385** [google/ExoPlayer#9332] opened 2021-08-25 06:17 UTC
**I'm play a simple mp4 file and cause those error below:**

```
2021-08-25 14:13:23.644 com.aoaojao.app.global E/EventLogger: playerFailed [eventTime=3228.55, mediaPos=0.00, window=10, period=10, errorCode=ERROR_CODE_IO_UNSPECIFIED
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=162; index=162
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:430)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=162; index=162
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedByte(ParsableByteArray.java:233)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:1203)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:949)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:308)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:130)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:483)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:442)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:424)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:242)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
    ]
```

I debug the AtomParsers.java the line 1203 method cause the problem.
![1629871704(1)](https://user-images.githubusercontent.com/8167763/130735683-0d996042-f264-4c2c-a4dd-f71ba7037597.jpg)

when I change parent data's position that make method pass then I can play video successfully.
**Is there any good way to avoid mistakes**

This is my video test link.
[the video link](https://drive.google.com/file/d/1C2n01KEVT-QE7EupMniaKg037UEImtVP/view?usp=sharing)

My exoplayer2 version is 2.15.0

**Comment by icbaker** [comment] 2021-08-25 11:32
I can play the attached video successfully on 2.14.2 and it crashes with the same stack trace on 2.15.0 so I agree this looks like a regression.

@kim-vde can you take a look?

**Comment by icbaker** [comment] 2021-08-25 11:35
Also @AquilesCanta FYI as the author of https://github.com/google/ExoPlayer/commit/ddc047c235c9d5e2d6816acc743ad319f65f39ac where this stack trace seems to originate.

**Comment by AquilesCanta** [comment] 2021-08-26 10:18
Is it also worth branching a github issue or internal bug for the correct assignment of an error code (instead of `ERROR_CODE_IO_UNSPECIFIED`)?

**Comment by icbaker** [comment] 2021-08-26 10:37
@AquilesCanta Filed [internal b/197832624].

**Comment by icbaker** [comment] 2021-08-31 18:07
The video file provided has an invalid `colr` box. Its size is reported as 18 bytes, but it has `color_type=nclx` which, according to section 8.5.2.2 of ISO/IEC 14496-12:2012(E) means the expected box size is 19 bytes (8 bytes for size & type, then 11 bytes for the `colr` box content).

The 162 in the stack trace comes from the ancestor `stsd` box which has a size of 162 bytes.

The `nclc` box defined by Apple is only expected to be 18 bytes, so this looks like a valid example of one of those - but it has `color_type=nclx`, not `nclc`.

How did you produce this file? The metadata suggests it might have come from ffmpeg? If so I think you should report this to them.

**Comment by liulei9385** [comment] 2021-09-01 07:47
I don’t know what conversion was done to this video, because it's upload from other mobile phones

**Comment by icbaker** [comment] 2021-09-01 11:29
Since this is the only example we've seen so far of a file broken in this way I'm going to close this as working-as-intended.

If we see a significant number of files that are invalid in the same way then we'll consider adding a workaround to ExoPlayer to handle this broken-ness more gracefully, but until then we're going to stick to implementing the spec as it's defined.

**Comment by onexuan** [comment] 2021-10-23 04:35
I can play my local video successfully on 2.14.2 but it crashes on 2.15.0, please fix it 
my local video can be played by other players

**Comment by ojw28** [comment] 2021-10-24 09:38
@onexuan - It sounds like you're seeing this when playing video recorded with your device camera. What device are you using? Please could you also send a sample video to `dev.exoplayer@gmail.com`.

Reopening this issue because it sounds like the bad media can be generated on device (on at least one device).

**Comment by onexuan** [comment] 2021-10-25 03:26
Please check your email @ojw28

**Comment by icbaker** [comment] 2021-10-25 10:41
@onexuan We haven't received your email. Please either upload the media here or send to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by onexuan** [comment] 2021-10-26 01:52
Please check it again

**Comment by icbaker** [comment] 2021-10-26 14:11
Thanks, I found the media (both the emails you sent were bounced back to you because you didn't use the requested subject line).

The media has the same symptoms as the original video in this issue: an 18 byte `colr` box with `colour_type=nclx`

**Comment by icbaker** [comment] 2021-10-26 14:14
I will modify ExoPlayer to handle files with this combination.

**Comment by onexuan** [comment] 2021-10-27 01:22
> I will modify ExoPlayer to handle files with this combination.

OK, I will test it after the new version is released

**Closed as completed** 2021-10-28 11:32 UTC
Labels: bug: device specific, bad media, content not playing
