### ISSUE TITLE
Bandwidth switch progressive media source

### ISSUE THREAD

**Issue by johnsky95** [google/ExoPlayer#7442] opened 2020-05-28 19:01 UTC
### [REQUIRED] Searched documentation and issues
I have looked on Stackoverflow mostly, some issues on this repo but unfortunately no success-

### [REQUIRED] Question
I have a list of URL which they point to Audio, Video, Video Only and Subtitle. 
I create ProgressiveMediaSource using these Urls and assign to Player.

How I initialize Exo Player

``` 
private val playerTrackSelector = DefaultTrackSelector(requireContext())

private fun initExoPlayer() {
        if (player == null) {
            player = SimpleExoPlayer.Builder(requireContext())
                .setTrackSelector(playerTrackSelector)
                .setBandwidthMeter(DefaultBandwidthMeter.Builder(requireContext()).build())
                .build()
            playerView.player = player
            playerView.keepScreenOn = true

            val resizeMode = PreferenceManager.getVideoResize(requireContext())
            if (resizeMode != null)
                playerView.resizeMode = resizeMode
        }
    }
```

I use the below method to play sources
The URI's are sorted by quality descending

```
private fun play(
        videos: Array<Uri>,
        audios: Array<Uri>,
        subtitles: Array<Subtitle>
    ) {
        val p = player!!

        val dataSourceFactory = DefaultDataSourceFactory(
            context,
            "ExoPlayer"
        )
        val factory = ProgressiveMediaSource.Factory(dataSourceFactory)
        val sources = ArrayList<MediaSource>()

        videos.forEach { sources.add(factory.createMediaSource(it)) }
        audios.forEach { sources.add(factory.createMediaSource(it)) }
        subtitles.forEach {
            val subtitleFormat =
                Format.createTextSampleFormat(
                    it.id, // An identifier for the track. May be null.
                    it.mime, // The mime type. Must be set correctly.
                    C.SELECTION_FLAG_DEFAULT, // Selection flags for the track.
                    it.language // The subtitle language. May be null.
                )

            sources.add(
                SingleSampleMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(it.uri, subtitleFormat, C.TIME_UNSET)
            )
        }

        p.prepare(MergingMediaSource(*sources.toTypedArray()))
        p.playWhenReady = true
    }
```

ExoPlayer ignores the Internet quality and always opens the first URI which points to videos like 1080p or even 2K 4K

I am trying to achieve that exo player detects what it is best to play instead of stuck on buffering with 50kbps internet on a 4K video.

**Comment by marcbaechinger** [comment] 2020-05-28 20:24
For adaptive behaviour you would need to use an adaptive format like DASH, HLS or SmoothStreaming. These have a manifest which tells ExoPlayer what qualities are available. 

Still it is not enough to have one single stream for each quality. Roughly explained, a stream for each quality is cut into chunks of let's say 4 seconds each. If indicated by the bandwidth estimation ExoPlayer will then switch to different qualities at the begin of the next chunk, play that chunk and at the end of the chunk decide what quality to pick for the next chunk and so on.

I think you could use a packager like MP4box to do this. I'm not an expert in such things so there might be better tools around for doing this: https://github.com/gpac/gpac/wiki/DASH-Support-in-MP4Box

**Comment by johnsky95** [comment] 2020-05-29 15:45
> For adaptive behaviour you would need to use an adaptive format like DASH, HLS or SmoothStreaming. These have a manifest which tells ExoPlayer what qualities are available.
> 
> Still it is not enough to have one single stream for each quality. Roughly explained, a stream for each quality is cut into chunks of let's say 4 seconds each. If indicated by the bandwidth estimation ExoPlayer will then switch to different qualities at the begin of the next chunk, play that chunk and at the end of the chunk decide what quality to pick for the next chunk and so on.
> 
> I think you could use a packager like MP4box to do this. I'm not an expert in such things so there might be better tools around for doing this: https://github.com/gpac/gpac/wiki/DASH-Support-in-MP4Box

Thanks for your quick feedback.

Is there any other way where I can change the source programmatically.
I have seen the Example App and it is used a dialog for that part, but the currentMappedTrackInfo is only available after player has started to play.

I want to play a uri from its index.
For example [8K, 4K, 2K, Full-Hd, 240p] given sources, I want the [Full-Hd] to be the default and not [8K]

**Comment by ojw28** [comment] 2020-06-10 14:37
Marking this as a duplicate of https://github.com/google/ExoPlayer/issues/7489.

**Closed as completed by ojw28** 2020-06-10 14:37 UTC
Labels: duplicate, question
