### ISSUE TITLE
Specific video takes ~ minutes to start on Samsung S8

### ISSUE THREAD

**Issue by davibe** [google/ExoPlayer#5199] opened 2018-12-05 10:51 UTC
Video url: https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

Opening this video with Samsung S8 (Android 8) results takes a lot of time before the video plays.
Tested with exoplayer release 2.9.2 and 2.6.1

Additionally, opening the video with a Samsung tab S2 works fine but it does not detect/show any subtitle track

Others devices i tested randomly are fine.

I attach `adb bugreport` for exoplayer 2.9.2 on Samsung S8 taken right after the video starts.
[bugreport-2018-12-05-11-48-10.zip](https://github.com/google/ExoPlayer/files/2648444/bugreport-2018-12-05-11-48-10.zip)

**Comment by ojw28** [comment] 2018-12-05 21:15
This is an Apple server configuration/certificate issue. I think behavior varies by Android version because they check the certificate(s) to a differing degree? In any case, this is a duplicate of
See https://github.com/google/ExoPlayer/issues/5103#issuecomment-440322017.

**Closed as completed by ojw28** 2018-12-05 21:15 UTC
Labels: duplicate
