### ISSUE TITLE
Placing IMA ADS UI container beneath Exoplayer Controls

### ISSUE THREAD

**Issue by krzysztofbalana** [google/ExoPlayer#7008] opened 2020-02-24 08:29 UTC
Hi! 

I have this problem. I would like to place adUiControls (learn more link, ad counter) layer beneath exoplayer controls, to let user manipulate stream during playback (rewind/forward/play/pause etc).

All my current ui elements on exoplayer are being added by com.google.android.exoplayer2.ui.PlayerView.getOverlayFrameLayout()

example below:

```
val container = exoplayer_view.overlayFrameLayout

container!!.apply {
    addView(adUiContainer)
    addView(controls as View)
    addView(playerSettingsMenu as View)
}

```

More visual example
![here](https://user-images.githubusercontent.com/48906839/75136818-25828900-56e6-11ea-90c6-e159a137ed5b.png)

Whenever "Learn More" webview appears, it covers exo ui controls and they're became unclickable. But I would like to have them operational...

Any ideas?

Thanks in advance!

**Comment by andrewlewis** [comment] 2020-03-10 16:59
I understand from a separate email thread that this relates to the DAI IMA SDK (not the IMA extension for client-side ad insertion), but please correct me if that's wrong.

If you dump the layout in Android Studio while an ad is playing, does the order of views match the order that they're being added when first initializing the UI? I wonder whether IMA's `WebView` or the player controls are getting reordered in their parent view causing the order to change.

**Comment by kbalana** [comment] 2020-03-12 08:05
Yes. This relates to DAI IMA SDK.

I've made some experiments with a test app from https://github.com/googleads/googleads-ima-android-dai/releases and I can confirm that there is no switching being made with layouts hierarchy. 

<img width="1240" alt="Screenshot 2020-03-12 at 08 20 05" src="https://user-images.githubusercontent.com/48906839/76498951-259cbb80-643e-11ea-9525-f44f4f37bab3.png">

It seems, that IMA SDK intercepts all tap/click events on player view. Thankfuly it emits those as an `AdEvent.AdEventType.TAPPED` and `AdEvent.AdEventType.CLICKED` and thanks to that I was able to came up with a walkaround. Not very clean, but working. I just react to those events and trigger controls manually.

However, this doesn't solve a problem at all and still I would treat it as bug, not a feature. Question is, who is real recipient of those problems...

**Comment by andrewlewis** [comment] 2020-03-12 09:51
@donato Please could you take a look at this issue relating to the DAI SDK? It seems strange that touch events are getting through to controls on top of the WebView -- is that working as expected?

**Comment by andrewlewis** [comment] 2020-03-12 09:55
@kbalana Just to be clear, is it the case that taps on the play button (on top of the web view) are not getting through? I think it's expected that the player view itself doesn't receive events as the web view is on top of it and can intercept taps.

**Comment by kbalana** [comment] 2020-03-12 10:18
In this particular case, tapping on play button work as expected, as this is the most frontmost layer and its visisibility is set to true (webview lays behind). Once it goes to invisible state, you wont be able to bring it back.

**Comment by andrewlewis** [comment] 2020-03-12 10:42
Edit: please ignore, I forgot this was server-side ad insertion not client-side (the UI components don't currently know whether an ad is playing with DAI). 

Hm, I wonder if the issue is just that player controls are completely hidden during ads (rather than this being a problem with events going to the wrong view). Have you tried setting `app:hide_during_ads` on the player view in the layout so that controls are visible while ads are playing?

**Comment by andrewlewis** [comment] 2020-03-12 10:47
If you force controls to always be visible (e.g., set `show_timeout` to 0) do they receive touch events while the ad is playing?

**Comment by kbalana** [comment] 2020-03-16 07:46
Hi!

It will work as the controls layer will be on top. I've tested it with my test app. Problem is only when player controls are switched to invisible state.

**Comment by andrewlewis** [comment] 2020-04-24 10:24
> It seems, that IMA SDK intercepts all tap/click events on player view. Thankfuly it emits those as an AdEvent.AdEventType.TAPPED and AdEvent.AdEventType.CLICKED and thanks to that I was able to came up with a walkaround. Not very clean, but working. I just react to those events and trigger controls manually.

I think this is probably the right way to solve the problem for now. It seems the IMA SDK is intercepting the events as you say, and so the ExoPlayer player view doesn't know to toggle control visibility, so you need to handle IMA's events and propagate those to the player view yourself. I will close this now as you have a way to make it work, and it seems that making it easier will require us to provide an IMA SDK SSAI + ExoPlayer integration, which doesn't exist yet.

@donato If we do an ExoPlayer integration for SSAI and that integration knows about the ExoPlayer UI components, we should probably take care of propagating unhandled touch events from the IMA SDK to the ExoPlayer UI components.

**Closed as completed by andrewlewis** 2020-04-24 10:24 UTC
Labels: question
