### ISSUE TITLE
Controller Layout with data binding

### ISSUE THREAD

**Issue by raman-nbg** [google/ExoPlayer#7320] opened 2020-05-02 16:59 UTC
### [REQUIRED] Use case description
I want to use SimpleExoPlayer with a custom layout. The custom layout contains some text fields containing information like the title and a short description of the video. I want to provide these information via data binding to the custom layout.

### Proposed solution
I have a view.xml that contains the PlayerView. The PlayerView has set `app:controller_layout_id`. The view also has data binding defined.

The ExoPlayer (PlayerControlView.java) inflates the controller layout, but it does not pass/set the data binding on the inflated layout. So there is no straight forward solution to set data binding.

### Alternatives considered
Current workaround is to set the data binding afterwards in the activity/fragment:

```kotlin
    private fun refreshData() {
        val post = viewModel?.post
        if (post != null) {
            initPlayer(post)

            val videoControlView = this.view?.findViewById<View>(R.id.post_video_player_layout)!!
            val binding = DataBindingUtil.bind<PostVideoPlayerLayoutBinding>(videoControlView)
            binding!!.viewModel = viewModel
        }
    }
```

A better approach would be to let the PlayerControlView do this stuff. Maybe https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L391 would be the correct place?

**Comment by ojw28** [comment] 2020-05-03 11:41
Duplicate of https://github.com/google/ExoPlayer/issues/5417

**Closed as completed by ojw28** 2020-05-03 11:41 UTC
Labels: duplicate

**Comment by BlaineOmega** [comment] 2020-05-18 19:30
What is the status of this? Ticket #5417 was closed too. Has this feature been implemented? Is there another ticket tracking it?

**Comment by ojw28** [comment] 2020-05-18 19:42
> Ticket #5417 was closed too.

It wasn't. It's still open.
