### ISSUE TITLE
Audio is truncated while using ConcatenatingMediaSource

### ISSUE THREAD

**Issue by babinoclock** [google/ExoPlayer#2446] opened 2017-02-13 07:17 UTC
Hi. I am working on an Android app that plays remote mp3 files continuously. I have used **ConcatenatingMediaSource** to to input the player. Some songs are started before previous one completed. Here the audio is truncated at end for 1-3 seconds. How can i overcome that?

**Comment by andrewlewis** [comment] 2017-03-27 13:46
Please could you provide detailed steps to reproduce the issue in the demo app, including links to the streams you are playing? Thanks.

**Comment by ojw28** [comment] 2017-04-27 10:04
Closing due to lack of information.

**Closed as completed by ojw28** 2017-04-27 10:04 UTC
Labels: need more info
