### ISSUE TITLE
Player state error changed between BUFFERING and READY repeatedly

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#7351] opened 2020-05-09 06:44 UTC
### [REQUIRED] Issue description
ExoPlayer version:  **Release f749d19 [ExoPlayerLib/2.9.6]**
I custom the LoadControl, reset the default buffer value and pre-allocate the memory used for my user case. And then in poor connection, the player state changed between BUFFERING and READY repeatedly.
```
public static final int DEFAULT_MIN_BUFFER_MS = 6000;
public static final int DEFAULT_MAX_BUFFER_MS = 10000;
public static final int DEFAULT_BUFFER_FOR_PLAYBACK_MS = 2000;
public static final int DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS = 5000;
```
```
public DefaultLoadControl createDefaultLoadControl() {
      createDefaultLoadControlCalled = true;
      if (allocator == null) {
      // pre-allocate 500 * 64 * 1024KB memory
        allocator = new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE,500);
      }
      return new DefaultLoadControl(
          allocator,
          minBufferMs,
          maxBufferMs,
          bufferForPlaybackMs,
          bufferForPlaybackAfterRebufferMs,
          targetBufferBytes,
          prioritizeTimeOverSizeThresholds,
          priorityTaskManager,
          backBufferDurationMs,
          retainBackBufferFromKeyframe);
    }
  }
```
### [REQUIRED] Reproduction steps
I used the proxy tool **Charles** 's Throttling setting to mock a poor internet scene. and I have create a demo repo [https://github.com/Romantic-LiXuefeng/ExoPlayer_Pre_Cache_Demo/tree/release-v2](https://github.com/Romantic-LiXuefeng/ExoPlayer_Pre_Cache_Demo/tree/release-v2) to reproduce this issue.  Thanks!

**Comment by Romantic-LiXuefeng** [comment] 2020-05-12 01:55
```
private boolean shouldTransitionToReadyState(boolean renderersReadyOrEnded) {
    if (enabledRenderers.length == 0) {
      // If there are no enabled renderers, determine whether we're ready based on the timeline.
      return isTimelineReady();
    }
    if (!renderersReadyOrEnded) {
      return false;
    }
//    if (!playbackInfo.isLoading) {
      // Renderers are ready and we're not loading. Transition to ready, since the alternative is
      // getting stuck waiting for additional media that's not being loaded.
//      return true;
//    }
    // Renderers are ready and we're loading. Ask the LoadControl whether to transition.
    MediaPeriodHolder loadingHolder = queue.getLoadingPeriod();
    boolean bufferedToEnd = loadingHolder.isFullyBuffered() && loadingHolder.info.isFinal;
    return bufferedToEnd
        || loadControl.shouldStartPlayback(
            getTotalBufferedDurationUs(), mediaClock.getPlaybackParameters().speed, rebuffering);
  }
```
I removed the code in  `shouldTransitionToReadyState` `if (!playbackInfo.isLoading) {`, there would be ok, but i don't know whether cause other issues.  @tonihei  Please give some advices!

**Comment by tonihei** [comment] 2020-05-13 08:40
Just to confirm the core changes:
 1. Reduce minBuffer to 6 seconds and maxBuffer to 10 seconds in DefaultLoadControl
 2. Throttle network speed to simulate a poor connection.
 3. Play a stream with a single non-adaptive 6.1Mbps track.

Observed effect:
 - Player state changes between BUFFERING and READY

Expected effect:
 - Player is always READY (?) 

If this summary is correct, then everything is probably working as intended. The throttling likely means the player can't buffer fast enough, so will run into rebuffers from time to time.

To avoid this situation, you can do multiple things:
 - Provide adaptive content with multiple bitrates. Just having a stream with 6.1Mbps is likely to cause issues in many network conditions.
 - Increase the maximum buffer of DefaultLoadControl so that more buffer is available when the 
network speed falls too low.
 - Provide download functionality so that the stream can be downloaded by the user before playback starts (see https://exoplayer.dev/downloading-media.html).

**Comment by Romantic-LiXuefeng** [comment] 2020-05-13 09:13
@tonihei  Please reproduce this issue with my provided demo.   It's not related with bitrate. 
[http://n2.vod01.icntvcdn.com/newtv2/2017/7/26/602fdfdfab1a3a679e97/ce0715892a1441b19e2316322f5fe3fc_21merge.m3u8](http://n2.vod01.icntvcdn.com/newtv2/2017/7/26/602fdfdfab1a3a679e97/ce0715892a1441b19e2316322f5fe3fc_21merge.m3u8) , you can test with this url with low bitrate.

Excepted: Not repeatedly changed BUFFERING and READY,   if due of poor connection, the player into re-buffer state, I think, it should at least buffer `DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS = 5000` media datas. but the result not like this, it's just changed from BUFFERING into READY.  Can accept stay a long time in BUFFERING state.

And the player should work in the same behavior controlled by `LoadControl` in different network speed.

**Comment by Romantic-LiXuefeng** [comment] 2020-05-13 09:41
> Increase the maximum buffer of DefaultLoadControl so that more buffer is available when the
> network speed falls too low.

I don't think it's a right way.   In good Internet, it's works well, I think the value of `public static final int DEFAULT_MAX_BUFFER_MS = 10000;` is ok.

**Comment by Romantic-LiXuefeng** [comment] 2020-05-14 03:13
#https://github.com/google/ExoPlayer/issues/7252

**Comment by Romantic-LiXuefeng** [comment] 2020-05-21 01:08
@tonihei  Do you have time to look at this issue?  Thanks!

**Comment by tonihei** [comment] 2020-05-26 09:49
I checked your demo application with a poor connection. Everything seems to work as expected, including waiting for at least 5 seconds of media before the state changes from BUFFERING to READY after a rebuffer. 

If you still think there is an issue, please attach the output of the `EventLogger` from logcat here and explain where you think the problem happens. The logcat output shows the timestamps and media positions of each state change.

**Comment by Romantic-LiXuefeng** [comment] 2020-05-26 16:00
```
2020-05-26 23:54:37.315 16757-16757/? I/zygote64: Late-enabling -Xcheck:jni
2020-05-26 23:54:37.445 16757-16757/com.google.android.exoplayer2.demo I/System: Daemon delayGCRequest, sDelayGCRequest=false, delay=true, sPendingGCRequest=false
2020-05-26 23:54:37.578 16757-16812/com.google.android.exoplayer2.demo D/OpenGLRenderer: RenderMonitor init!
2020-05-26 23:54:37.579 16757-16812/com.google.android.exoplayer2.demo D/OpenGLRenderer: RenderMonitor init completed!
2020-05-26 23:54:37.579 16757-16812/com.google.android.exoplayer2.demo D/OpenGLRenderer: HWUI GL Pipeline
2020-05-26 23:54:37.639 16757-16812/com.google.android.exoplayer2.demo I/Adreno: QUALCOMM build                   : 43848e7, I0ecbd03a6b
    Build Date                       : 08/07/18
    OpenGL ES Shader Compiler Version: EV031.23.02.01
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.8.R1.08.01.00.382.054
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2020-05-26 23:54:37.645 16757-16812/com.google.android.exoplayer2.demo I/Adreno: PFP: 0x016ee164, ME: 0x00000000
2020-05-26 23:54:37.649 16757-16812/com.google.android.exoplayer2.demo I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2020-05-26 23:54:37.649 16757-16812/com.google.android.exoplayer2.demo I/OpenGLRenderer: Initialized EGL, version 1.4
2020-05-26 23:54:37.649 16757-16812/com.google.android.exoplayer2.demo D/OpenGLRenderer: Swap behavior 2
2020-05-26 23:54:37.776 16757-16757/com.google.android.exoplayer2.demo W/InputMethodManager: Ignoring onBind: cur seq=4074, given seq=4073
2020-05-26 23:54:38.945 16757-16757/com.google.android.exoplayer2.demo I/System: Daemon delayGCRequest, sDelayGCRequest=true, delay=false, sPendingGCRequest=false
2020-05-26 23:54:39.981 16757-16765/com.google.android.exoplayer2.demo I/zygote64: Do partial code cache collection, code=25KB, data=28KB
2020-05-26 23:54:39.981 16757-16765/com.google.android.exoplayer2.demo I/zygote64: After code cache collection, code=25KB, data=28KB
2020-05-26 23:54:39.981 16757-16765/com.google.android.exoplayer2.demo I/zygote64: Increasing code cache capacity to 128KB
2020-05-26 23:54:40.856 16757-16757/com.google.android.exoplayer2.demo I/System: Daemon delayGCRequest, sDelayGCRequest=false, delay=true, sPendingGCRequest=false
2020-05-26 23:54:40.944 16757-16757/com.google.android.exoplayer2.demo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-05-26 23:54:40.958 16757-16757/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init 89ff3e6 [ExoPlayerLib/2.9.6] [ocean, OE106, smartisan, 27]
2020-05-26 23:54:40.970 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [0.01, 0.00, window=0, true, BUFFERING]
2020-05-26 23:54:40.995 16757-16765/com.google.android.exoplayer2.demo I/zygote64: Do partial code cache collection, code=61KB, data=55KB
2020-05-26 23:54:40.995 16757-16765/com.google.android.exoplayer2.demo I/zygote64: After code cache collection, code=61KB, data=55KB
2020-05-26 23:54:40.995 16757-16765/com.google.android.exoplayer2.demo I/zygote64: Increasing code cache capacity to 256KB
2020-05-26 23:54:41.052 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: surfaceSizeChanged [0.09, 0.00, window=0, 1080, 2100]
2020-05-26 23:54:41.551 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: timelineChanged [0.58, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
2020-05-26 23:54:41.551 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   period [34.84]
2020-05-26 23:54:41.552 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   window [34.84, true, false]
2020-05-26 23:54:41.552 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: ]
2020-05-26 23:54:41.576 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodCreated [0.61, 0.00, window=0, period=0]
2020-05-26 23:54:41.577 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: loading [0.61, 0.00, window=0, period=0, true]
2020-05-26 23:54:42.356 16757-16757/com.google.android.exoplayer2.demo I/System: Daemon delayGCRequest, sDelayGCRequest=true, delay=false, sPendingGCRequest=false
2020-05-26 23:54:42.774 16757-16925/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/cook
2020-05-26 23:54:42.775 16757-16925/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/dts
2020-05-26 23:54:42.793 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2020-05-26 23:54:42.793 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2020-05-26 23:54:42.795 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2020-05-26 23:54:42.795 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2020-05-26 23:54:42.799 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/divx
2020-05-26 23:54:42.801 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/DivX-3.11
2020-05-26 23:54:42.802 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/divx4
2020-05-26 23:54:42.804 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/Sorenson-H.263
2020-05-26 23:54:42.815 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2020-05-26 23:54:42.817 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2020-05-26 23:54:42.822 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-pn-realvideo
2020-05-26 23:54:42.824 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
2020-05-26 23:54:42.835 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2020-05-26 23:54:42.835 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2020-05-26 23:54:42.846 16757-16925/com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
2020-05-26 23:54:42.856 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2020-05-26 23:54:42.856 16757-16925/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2020-05-26 23:54:42.861 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: decoderEnabled [1.90, 0.00, window=0, period=0, video]
2020-05-26 23:54:42.862 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: decoderEnabled [1.90, 0.00, window=0, period=0, audio]
2020-05-26 23:54:42.862 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: tracksChanged [1.90, 0.00, window=0, period=0, 
2020-05-26 23:54:42.862 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:0 [
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=YES [
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=4000, supported=YES
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:1, id=1, mimeType=video/avc, bitrate=1500, supported=YES
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:     ]
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   ]
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:1 [
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, supported=YES
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:     ]
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   ]
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:2 [
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:     ]
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   ]
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:3 [
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1/21, mimeType=application/id3, supported=YES
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:     ]
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger:   ]
2020-05-26 23:54:42.863 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: ]
2020-05-26 23:54:42.866 16757-16933/com.google.android.exoplayer2.demo E/ACodec: found 1 codecs
2020-05-26 23:54:42.875 16757-16933/com.google.android.exoplayer2.demo I/OMXClient: Treble IOmx obtained
2020-05-26 23:54:42.885 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: loading [1.92, 0.00, window=0, period=0, false]
2020-05-26 23:54:42.886 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodReadingStarted [1.92, 0.00, window=0, period=0]
2020-05-26 23:54:42.886 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: downstreamFormatChanged [1.92, 0.00, window=0, period=0, id=0, mimeType=null, bitrate=4000]
2020-05-26 23:54:42.899 16757-16933/com.google.android.exoplayer2.demo E/ACodec: codec OMX.qcom.video.decoder.avc selected
2020-05-26 23:54:42.901 16757-16925/com.google.android.exoplayer2.demo W/MediaCodecVideoRenderer: Resolutions unknown. Codec max resolution: 1920x1080
2020-05-26 23:54:42.902 16757-16932/com.google.android.exoplayer2.demo D/SurfaceUtils: connecting to surface 0x73e9dab010, reason connectToSurface
2020-05-26 23:54:42.902 16757-16932/com.google.android.exoplayer2.demo I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 17159169
2020-05-26 23:54:42.902 16757-16932/com.google.android.exoplayer2.demo D/SurfaceUtils: disconnecting from surface 0x73e9dab010, reason connectToSurface(reconnect)
2020-05-26 23:54:42.902 16757-16932/com.google.android.exoplayer2.demo D/SurfaceUtils: connecting to surface 0x73e9dab010, reason connectToSurface(reconnect)
2020-05-26 23:54:42.903 16757-16933/com.google.android.exoplayer2.demo I/ExtendedACodec: setupVideoDecoder()
2020-05-26 23:54:42.905 16757-16933/com.google.android.exoplayer2.demo I/ExtendedACodec: Decoder will be in frame by frame mode
2020-05-26 23:54:42.905 16757-16933/com.google.android.exoplayer2.demo W/ExtendedACodec: Failed to set frame packing format on component
2020-05-26 23:54:42.907 16757-16933/com.google.android.exoplayer2.demo W/ExtendedACodec: getParameter for input extradata failed
2020-05-26 23:54:42.920 16757-16933/com.google.android.exoplayer2.demo D/SurfaceUtils: set up nativeWindow 0x73e9dab010 for 1920x1080, color 0x7fa30c06, rotation 0, usage 0x20002900
2020-05-26 23:54:42.925 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: decoderInitialized [1.96, 0.00, window=0, period=0, video, OMX.qcom.video.decoder.avc]
2020-05-26 23:54:42.926 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: decoderInputFormatChanged [1.96, 0.00, window=0, period=0, video, id=0, mimeType=video/avc, bitrate=4000, codecs=avc1.640028, res=1920x1080]
2020-05-26 23:54:42.931 16757-16937/com.google.android.exoplayer2.demo E/ACodec: found 1 codecs
2020-05-26 23:54:42.932 16757-16937/com.google.android.exoplayer2.demo I/OMXClient: Treble IOmx obtained
2020-05-26 23:54:42.934 16757-16937/com.google.android.exoplayer2.demo E/ACodec: codec OMX.google.aac.decoder selected
2020-05-26 23:54:42.935 16757-16937/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -2147483648)
2020-05-26 23:54:42.936 16757-16937/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -2147483648)
2020-05-26 23:54:42.937 16757-16937/com.google.android.exoplayer2.demo W/ExtendedACodec: Failed to get extension for extradata parameter
2020-05-26 23:54:42.949 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: decoderInitialized [1.98, 0.00, window=0, period=0, audio, OMX.google.aac.decoder]
2020-05-26 23:54:42.949 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: decoderInputFormatChanged [1.99, 0.00, window=0, period=0, audio, id=1/15, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100]
2020-05-26 23:54:42.968 16757-16765/com.google.android.exoplayer2.demo I/zygote64: Do full code cache collection, code=83KB, data=99KB
2020-05-26 23:54:42.968 16757-16765/com.google.android.exoplayer2.demo I/zygote64: After code cache collection, code=66KB, data=61KB
2020-05-26 23:54:42.982 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: audioSessionId [2.02, 0.00, window=0, period=0, 21257]
2020-05-26 23:54:42.997 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: videoSizeChanged [2.03, 0.00, window=0, period=0, 1920, 1080]
2020-05-26 23:54:43.047 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: surfaceSizeChanged [2.08, 0.00, window=0, period=0, 1080, 607]
2020-05-26 23:54:43.055 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: renderedFirstFrame [2.09, 0.00, window=0, period=0, Surface(name=null)/@0x7630d9c]
2020-05-26 23:54:43.063 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [2.10, 0.06, window=0, period=0, true, READY]
2020-05-26 23:54:43.659 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [2.69, 0.64, window=0, period=0, true, BUFFERING]
2020-05-26 23:54:44.267 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [3.30, 0.65, window=0, period=0, true, READY]
2020-05-26 23:54:44.305 16757-16757/com.google.android.exoplayer2.demo E/EventLogger: audioTrackUnderrun [3.34, 0.71, window=0, period=0, 56576, 320, 980]]
2020-05-26 23:54:44.975 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [4.01, 1.29, window=0, period=0, true, BUFFERING]
2020-05-26 23:54:46.287 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [5.32, 1.30, window=0, period=0, true, READY]
2020-05-26 23:54:46.328 16757-16757/com.google.android.exoplayer2.demo E/EventLogger: audioTrackUnderrun [5.36, 1.38, window=0, period=0, 56576, 320, 1681]]
2020-05-26 23:54:47.015 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [6.05, 1.96, window=0, period=0, true, BUFFERING]
2020-05-26 23:54:48.329 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [7.36, 1.97, window=0, period=0, true, READY]
2020-05-26 23:54:48.368 16757-16757/com.google.android.exoplayer2.demo E/EventLogger: audioTrackUnderrun [7.40, 2.03, window=0, period=0, 56576, 320, 1684]]
2020-05-26 23:54:49.054 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [8.09, 2.61, window=0, period=0, true, BUFFERING]
2020-05-26 23:54:49.146 16757-16765/com.google.android.exoplayer2.demo I/zygote64: Do partial code cache collection, code=115KB, data=91KB
2020-05-26 23:54:49.146 16757-16765/com.google.android.exoplayer2.demo I/zygote64: After code cache collection, code=115KB, data=91KB
2020-05-26 23:54:49.146 16757-16765/com.google.android.exoplayer2.demo I/zygote64: Increasing code cache capacity to 512KB
2020-05-26 23:54:49.147 16757-16765/com.google.android.exoplayer2.demo I/zygote64: Compiler allocated 7MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
2020-05-26 23:54:52.012 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [11.04, 2.61, window=0, period=0, true, READY]
2020-05-26 23:54:52.049 16757-16757/com.google.android.exoplayer2.demo E/EventLogger: audioTrackUnderrun [11.08, 2.68, window=0, period=0, 56576, 320, 3320]]
2020-05-26 23:54:52.783 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [11.82, 3.27, window=0, period=0, true, BUFFERING]
2020-05-26 23:54:55.447 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [14.48, 3.27, window=0, period=0, true, READY]
2020-05-26 23:54:55.492 16757-16757/com.google.android.exoplayer2.demo E/EventLogger: audioTrackUnderrun [14.53, 3.36, window=0, period=0, 56576, 320, 3040]]
2020-05-26 23:54:56.181 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [15.21, 3.94, window=0, period=0, true, BUFFERING]
2020-05-26 23:54:56.835 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [15.87, 3.94, window=0, period=0, true, READY]
2020-05-26 23:54:56.873 16757-16757/com.google.android.exoplayer2.demo E/EventLogger: audioTrackUnderrun [15.91, 4.03, window=0, period=0, 56576, 320, 1024]]
2020-05-26 23:54:57.057 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: loading [16.09, 4.13, window=0, period=0, true]
2020-05-26 23:54:57.533 16757-16757/com.google.android.exoplayer2.demo D/EventLogger: state [16.57, 4.61, window=0, period=0, true, BUFFERING]
2020-05-26 23:54:57.970 16757-16757/com.google.android.exoplayer2.demo E/EventLogger: audioTrackUnderrun [17.00, 4.61, window=0, period=0, 56576, 320, 798]]

```
@tonihei As the log, they are repeatedly changed between BUFFERING and READY at the beginning.  and when into BUFFERING, there occurs audio under run, I'm not clear why this. 
My throttle setting like this:
![throttle_setting](https://user-images.githubusercontent.com/9837705/82922731-8f902000-9fac-11ea-97b3-766fccb3efc6.png)

**Comment by tonihei** [comment] 2020-05-27 08:29
Thanks for the EventLogger output, this is helpful to understand the problem! I didn't observe this behaviour when trying your sample app locally with the same media and a slow network. 
 - Can you confirm that you are using exactly the sample app linked above?
 - What device are you using? It looks like the audio underruns could mean the player is BUFFERING intermittently because the of the underruns and not because there is no buffer loaded. That's why it immediately tries to continue playback. If this is true, then the device might not be fast enough to handle the data, but it's worth investigating to see why.
 - Could you try to pause at the beginning of playback until the maximum buffer (10 seconds) is loaded? And then check if the issue still persists. If yes, it's unrelated to the LoadControl settings.

**Comment by Romantic-LiXuefeng** [comment] 2020-05-27 08:57
> Can you confirm that you are using exactly the sample app linked above?

Yes. 

> What device are you using? It looks like the audio underruns could mean the player is 
BUFFERING intermittently because the of the underruns and not because there is no buffer loaded. That's why it immediately tries to continue playback. If this is true, then the device might not be fast enough to handle the data, but it's worth investigating to see why.

If the network is well, it plays well, not occurs underruns.   I can reproduce this issue on all my handed devices.  Some devices is fast enough.  So I think this is not related with devices performance.  I'm not clear what situations would happened underruns. Hope give some explain.


[https://github.com/google/ExoPlayer/issues/7351#issuecomment-627061112](https://github.com/google/ExoPlayer/issues/7351#issuecomment-627061112), as this comment, I have try to fixed this issue, because of  I found that when player is in BUFFERING state,  player not loads enough data setting by `LoadContorl(DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS)`, but the  `!playbackInfo.isLoading == false`, so the player transition to READY, I'm not clear what sense this logic works for?
```
if (!playbackInfo.isLoading) {
      Log.d("LoadControl","shouldTransitionToReadyState true....");
      // Renderers are ready and we're not loading. Transition to ready, since the alternative is
      // getting stuck waiting for additional media that's not being loaded.
      return true;
 }
```

**Comment by Romantic-LiXuefeng** [comment] 2020-05-27 13:55
> Could you try to pause at the beginning of playback until the maximum buffer (10 seconds) is loaded? And then check if the issue still persists. If yes, it's unrelated to the LoadControl settings.

It's not persists.

**Comment by Romantic-LiXuefeng** [comment] 2020-05-29 06:14
@tonihei  Could you reproduce this issue? Is there any thing I could support? Thanks!

**Comment by tonihei** [comment] 2020-06-01 13:10
> Could you reproduce this issue?

I tried again to see if I missed something but still can't reproduce. 

From what I see in your logcat output, the player didn't attempt to buffer in between those BUFFERING/READY changes. That is `isLoading` was `false` the whole time. 

> Is there any thing I could support?

Could you try to updating the ExoPlayer dependency to the latest version (preferably the dev-v2 branch) to see if the issue is still there? Maybe we already fixed that at some point.

**Comment by Romantic-LiXuefeng** [comment] 2020-06-02 05:59
I'm not clear why you still can't reproduce? For me,  it's easy to reproduce. 

> From what I see in your logcat output, the player didn't attempt to buffer in between those BUFFERING/READY changes. That is isLoading was false the whole time.

Yes,  so I think this is an issue.   Why isLoading was false the whole time?   and when in READY state,  I find that the audio render `rendererReadyOrEnded` is false, so it's transition to BUFFERING again. 

> Could you try to updating the ExoPlayer dependency to the latest version (preferably the dev-v2 branch) to see if the issue is still there? Maybe we already fixed that at some point.

I try to with the least version, the issue don's exist.   Hope to speed more time to reproduce with my demo,  point out what's the reason about this.  We build our sdk with the Release version 2.9.6, and do more works, it's not easy to update to the latest version. Thanks very much ! @tonihei

**Comment by tonihei** [comment] 2020-06-02 07:43
> I try to with the least version, the issue don's exist. 

Thanks for checking! In this case, I'll close the issue for now because it seems it's no longer a problem we can fix in our code. If you see the same problem happening on the latest version, please feel free to reopen.

**Comment by Romantic-LiXuefeng** [comment] 2020-06-02 08:03
@tonihei @ojw28  @andrewlewis  Could you give more information and point out why?  It's actual an issue on release version 2.9.6.  I will update to the latest version later.  Thanks!

**Comment by tonihei** [comment] 2020-06-02 08:08
Sorry for the confusion. I understood from your comment that you already tried the latest version. If you haven't tried yet, I'll reopen and mark as "need for info".

**Comment by Romantic-LiXuefeng** [comment] 2020-06-02 08:29
@tonihei I used the latest dev version to try, it's actual not exist.  To me, I can't update to least version at now.  I just want to know the reason why this happened and how to fixed this, because of the modify is in the most complex logic `ExoPlayerImplInternal` class, I'm not sure my modify try to fixed this issue whether cause more issues I can't image.

**Comment by tonihei** [comment] 2020-06-02 08:41
> I used the latest dev version to try, it's actual not exist. 

That means there is no problem in the dev-v2 branch, correct? 

> To me, I can't update to least version at now. I just want to know the reason why this happened and how to fixed this

We don't usually fix problems for older versions of ExoPlayer. So even if we find the exact reason why this happening in 2.9.6., we would still fix it in the latest dev-v2 branch only. 

> modify is in the most complex logic ExoPlayerImplInternal class, I'm not sure my modify try to fixed this issue whether cause more issues I can't image.

Do you mean the change mentioned here: https://github.com/google/ExoPlayer/issues/7351#issuecomment-627061112? If yes, then you can probably keep it because it's only a fallback for misconfigured LoadControl implementations.

**Closed as completed** 2020-06-15 06:25 UTC
Labels: question
