### ISSUE TITLE
Exoplayer having issues playing HLS streams featuring simple black and white text videos

### ISSUE THREAD

**Issue by jhowens89** [google/ExoPlayer#2163] opened 2016-12-06 21:07 UTC
Description of problem
----------------------
Some HLS streams are playing faster than normal. After testing against many streams, for some reason it seemed to only affect simple black and white videos with text. I came across this phenomenon, because I was using timer videos to test proper synchronization in my own app. In the count-up video stream linked, it's obvious betweens the numbers 4-5, 8-9, 12-13, etc. The demo app seekbar will stay in sync with the count up, but the bug can be validated when compared to a third party stopwatch. By the end of the 60 second video, a stopwatch will show > 10 second difference. 

The stream works correctly in Safari and with Explayer v1. Running Apple's mediastreamvalidator tool revealed the following two errors, but I don't believe they are an issue:

MUST fix issues
Error: Measured peak bitrate compared to master playlist declared value exceeds error tolerance
SHOULD fix issues
Warning: #EXT-X-ALLOW-CACHE has been deprecated

Observations/guesses
----------------------
I investigated the log "W/TsExtractor: Unexpected start code prefix:" for a bit. After digging around and putting some logs in the Exoplayer library, this log appears consistently near the start of every TS chunk after the first one. This particular check appears to fail in the first audio related extraction per TS chunk. I logged the bits of ParsableBitArray PesReader.pesScratch to see if there was an obvious off by 1 error and this did not appear to be the case. 

How to reproduce
----------------------
Substitute the following URL into the Exoplayer2 demo app. In my case I edited the method buildMediaSource in PlayerActivity to return an HlsMediaSource with Uri.parse(myCustomUrl)

https://s3-us-west-2.amazonaws.com/em-hls-test/60_second_count_up/index.m3u8

Version of ExoPlayer
----------------------
I'm using the current latest branch of release-v2 from github, r2.0.4

Reproducibility
----------------------
I was able to reproduce the bug on the follow devices:

- Samsung Galaxy S6 running 6.0.1
- LG G3 running 5.0.1
- Nexus 5 running 6.0.1
- Huawei ALE-L23 running EMUI 3.1 / Android 5.0.1

This bug is present in every run through. 

Bug Report
----------------------
Bug report from the Nexus 5 is attached. 

[bug_report_nexus_5_sdk_23.txt.zip](https://github.com/google/ExoPlayer/files/635033/bug_report_nexus_5_sdk_23.txt.zip)

**Comment by AquilesCanta** [comment] 2016-12-07 09:47
This is a proper bug report! Thanks! I'll look into it.

**Comment by AquilesCanta** [comment] 2016-12-07 10:39
This is a duplicate of #1978. The media breaks the spec because each chunk seems to reset the continuity counters, as explained in the referred issue.

**Closed as completed by AquilesCanta** 2016-12-07 10:39 UTC

**Comment by AquilesCanta** [comment] 2016-12-07 10:44
As a workaround (though not okay for real scenarios) you can force the creation of a new TS extractor for every chunk. That will fix the issue here, but might break a case where a sample is spread across different chunks, which I think is allowed.
