### ISSUE TITLE
Matroska(mka) files are not seekable if they do not contain Cues information

### ISSUE THREAD

**Issue by karthik3389** [google/ExoPlayer#11163] opened 2023-05-15 19:30 UTC
Exoplayer does not attempt to add seek functionality if the Matroska file does not contain Cue information

https://github.com/google/ExoPlayer/blob/cf49175f790dc4bbee85bb195c021ea40765d84b/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mkv/MatroskaExtractor.java#L685

But stagefright attempts to seek even if the cues are not available

https://cs.android.com/android/platform/superproject/+/refs/heads/master:frameworks/av/media/module/extractors/mkv/MatroskaExtractor.cpp;l=486

Is there a specific reason why it was not implemented on exoplayer. 
The mka files found under testdata does not contain any cue information. (Verified with mkvToolNix)

**Comment by karthik3389** [comment] 2023-05-25 19:32
Hi @rohitjoins Do you have any updates on this?

**Comment by rohitjoins** [comment] 2023-06-13 12:24
Duplicate of #9901.

**Closed as completed by rohitjoins** 2023-06-13 12:24 UTC
Labels: enhancement
