### ISSUE TITLE
Removing previously downloaded files after lib update

### ISSUE THREAD

**Issue by kakali** [google/ExoPlayer#6633] opened 2019-11-09 23:08 UTC
Hi,
I have an app on the store with v. 2.8.0, and I wanted to update it with an update of exoplayer to 2.10.7. However, the videos downloaded with v.2.8.0 do not get removed in version 2.10.7 (so if the user has any videos downloaded, then upgrades, they won't be able to delete them any more). What should I do so they get removed? Probably I messed something up. Should I assign some specific request id? Here are excerpts of my code in v. 2.8.0 and v. 2.10.7 for downloading and removing videos. Thank you.

Code before the update:
```
public void fetchVideo(final CachedVideo videoEntity) {
(...)
final String decryptedVideoDownloadUri = cacheProvider.decryptVideoDownloadUri(videoEntity);
final DownloadHelper downloadHelper = getDownloadHelper(decryptedVideoDownloadUri);
downloadHelper.prepare(new DownloadHelper.Callback() {
                @Override
                public void onPrepared(DownloadHelper helper) {
                    byte[] data = …
                    DownloadAction downloadAction = downloadHelper.getDownloadAction(data, new ArrayList<TrackKey>());
                    startServiceWithAction(downloadAction);
                }
            });
}

    private DownloadHelper getDownloadHelper(String decryptedDownloadUriString){
        return new ProgressiveDownloadHelper(Uri.parse(decryptedDownloadUriString));
    }

    private void startServiceWithAction(DownloadAction action) {
        DownloadService.startWithAction(context, WOWVideoExoDownloadService.class, action, false);
    }

 public void removeVideo(final CachedVideo videoEntity) {
        String decryptedVideoDownloadUri = cacheProvider.decryptVideoDownloadUri(videoEntity);
       byte[] data = …
        DownloadAction removeAction = getDownloadHelper(decryptedVideoDownloadUri).getRemoveAction(data);
        startServiceWithAction(removeAction);
}
```

Code after the update:

```
public void fetchVideo(final CachedVideo videoEntity) {
(...)
final String decryptedVideoDownloadUri = cacheProvider.decryptVideoDownloadUri(videoEntity);
byte[] data = … (same as before)
DownloadRequest downloadRequest = new DownloadRequest(
                    videoEntity.getUniqueId(),
                    DownloadRequest.TYPE_PROGRESSIVE,
                    Uri.parse(decryptedVideoDownloadUri),
                    /* streamKeys= */ EMPTY_LIST,
                    null,
                    data);
DownloadService.sendAddDownload(
                    context,
                    WOWVideoExoDownloadService.class,
                    downloadRequest,
                    false);
}

 public void removeVideo(final CachedVideo videoEntity) {
        DownloadService.sendRemoveDownload(
                context,
                WOWVideoExoDownloadService.class,
                videoEntity.getUniqueId(),
               /* foreground= */ false);
     }
```

**Comment by kakali** [comment] 2019-11-11 13:10
Forgot to mention that the downloaded videos go through AesCipher. I can post code for the DownloaderConstructorHelper, if necessary.

**Comment by ojw28** [comment] 2019-12-22 20:06
Why would your users want the downloads to be removed? Wouldn't they expect them to remain in place and still be usable? If the problem is that you're moving from the old `ActionFile` to the new `DownloadIndex` approach, you can perform an upgrade that causes the downloads to be written into the `DownloadIndex` [as shown here in the demo app](http://google3/third_party/java_src/android_libs/exoplayer/v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoApplication.java?l=132&rcl=274162076).

Does that solve your problem? We should properly document this [on this page](https://exoplayer.dev/downloading-media.html) if so.

**Comment by ojw28** [comment] 2020-01-17 19:35
Closing due to lack of follow-up.

**Closed as completed by ojw28** 2020-01-17 19:35 UTC
Labels: question
