### ISSUE TITLE
Version 2.15.0 of ExoPlayer injects MediaBrowserService intent into manifest

### ISSUE THREAD

**Issue by greyski** [google/ExoPlayer#9480] opened 2021-09-24 21:31 UTC
We've updated our version of ExoPlayer from `2.14.2` to `2.15.0` and we saw a change in our app's generated manifest. Our manifest now contains:

```
<intent>
        <action android:name="android.media.browse.MediaBrowserService"/>
</intent>
```

This happened immediately after we upgraded our ExoPlayer version and wanted to confirm this is expected behavior?

I assume one of ExoPlayer's dependencies requires to declare this intent in the app's manifest? If so, do we know why?

**Comment by greyski** [comment] 2021-09-24 23:35
I found the root cause, it was [the dependency upgrade](https://github.com/google/ExoPlayer/commit/dea52048cb4678711726ea512964224eb9b10206) of androidx:media from [1.2.1 ](https://android.googlesource.com/platform/frameworks/support/+/e2bbff9c767da61a875a84527e2cd643422b149b/media/media/src/main/AndroidManifest.xml) to [1.3.1](https://android.googlesource.com/platform/frameworks/support/+/25f9f769a5b0d47ffce6413a1b9a2311afc2ad4e/media/media/src/main/AndroidManifest.xml)

**Comment by greyski** [comment] 2021-09-25 00:05
[Related commit](https://android.googlesource.com/platform/frameworks/support/+/9cce1d644a9138e911d04b26cf91bb92ee975b6b%5E%21/media/media/src/main/AndroidManifest.xml) and [PR](https://android-review.googlesource.com/c/platform/frameworks/support/+/1411627). Not sure if there's anything you can do; I don't believe you can `tools:node="remove"` an `intent` placed in `queries`.

**Comment by ojw28** [comment] 2021-09-27 13:10
@sim0629 - Could you provide a quick response indicating whether this is working as intended, or something unexpected that needs fixing? Thanks!

**Comment by sim0629** [comment] 2021-09-27 13:21
Sure. I left a comment at https://android-review.googlesource.com/c/platform/frameworks/support/+/1411627. It was intended but decided to revert the library change in order not to inject the intent element into the manifest as multiple users pointed it out. https://android-review.googlesource.com/c/platform/frameworks/support/+/1836874 is ready for review.

**Comment by ojw28** [comment] 2021-09-27 13:28
Thanks! I'll mark this as a "bug" on the basis that this is something we intend to change.

**Comment by greyski** [comment] 2021-09-27 16:19
Thanks everyone! Looking forward to the fix.

**Comment by sim0629** [comment] 2021-10-18 06:13
The fix has been pushed the `dev-v2` branch.

**Closed as completed by sim0629** 2021-10-18 06:13 UTC
Labels: bug: in dependency
