### ISSUE TITLE
Upgrade mockito version to avoid getting warning for difference in hamcrest-core versions

### ISSUE THREAD

**Issue by raylee4204** [google/ExoPlayer#651] opened 2015-07-23 17:41 UTC
Since the latest update, I keep getting a warning message "Conflict with dependency 'org.hamcrest:hamcrest-core'. Resolved versions for app (1.1) and test app (1.3) differ."

I noticed that ExoPlayer uses older version of mockito, which uses 1.1 of hamcrest-core where as my app uses the latest version of junit for testing, which uses 1.3 of hamcrest-core.

**Comment by brillenheini** [comment] 2015-07-27 09:33
There is also a related problem with the uploaded pom file that causes the same warning when using ExoPlayer from jCenter.

The r1.3.3 Version did not have any dependencies:
https://bintray.com/artifact/download/google/exoplayer/com/google/android/exoplayer/exoplayer/r1.3.3/exoplayer-r1.3.3.pom

r1.4.1 has the test dependencies with scope runtime:
https://bintray.com/artifact/download/google/exoplayer/com/google/android/exoplayer/exoplayer/r1.4.1/exoplayer-r1.4.1.pom

I think there should be no dependencies at all in the pom.

**Comment by ojw28** [comment] 2015-07-27 12:13
Presumably that's the only actual problem. If the library didn't have any dependencies then there wouldn't be a warning, right? Only the tests should have those dependencies, and they should be able to use whatever version of mockito (etc) that they want, including the versions they use currently.

Does that sound right?

**Comment by ojw28** [comment] 2015-07-27 13:13
The pom issue was probably caused by https://github.com/novoda/bintray-release/issues/31 (and can be fixed by updating). There's also some confusion in the gradle file around androidTest and test, which is causing some problems.

**Comment by ojw28** [comment] 2015-07-27 15:16
I've manually correct the pom files for 1.4.0 and 1.4.1.

In dev, the tests will be moved from test to androidTest, which is where they should be located. We'll also upgrade to a newer version of bintray-release. The result will be that from the next release onwards (a) the pom files should be generated correctly automatically, and (b) the test setup in general will be corrected.

**Comment by ojw28** [comment] 2015-07-27 15:35
I think the manual pom fix + the change above should resolve this issue. Please shout if this isn't the case. Thanks.

**Comment by ened** [comment] 2015-07-28 01:32
@ojw28 are you still interested in the #661 PR so that you don't have to ship with the libraries inside the repository?

**Comment by brillenheini** [comment] 2015-07-28 09:25
Strangely gradle is downloading this url that still has the dependencies:
https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer/r1.4.1/exoplayer-r1.4.1.pom

**Comment by ojw28** [comment] 2015-07-29 13:03
@ened - How does that PR make it show the libraries don't need to be in the repository? It looks like it's just updating the versions being used to me.

**Comment by ojw28** [comment] 2015-07-29 13:21
I'm following up with Bintray regarding the url that still has the dependencies. Thanks.

**Comment by ojw28** [comment] 2015-07-29 19:33
Bintray have corrected the stale files.

**Closed by ojw28** 2015-07-29 19:33 UTC

**Comment by brillenheini** [comment] 2015-07-30 09:15
Great, thanks! It's working now.

**Comment by ened** [comment] 2015-07-31 07:24
@ojw28 my thought was to not bundle jars like in here: https://github.com/google/ExoPlayer/tree/master/third_party/dexmaker
Anyhow, case closed for now.

**Comment by ojw28** [comment] 2015-08-03 09:14
They're still needed for Eclipse, I think.
