### ISSUE TITLE
Render final frame of MPEG-TS video

### ISSUE THREAD

**Issue by arlimm318** [google/ExoPlayer#7909] opened 2020-09-15 02:15 UTC
This TS contains only one I frame，android Error while playing.
[bjws-20655436911.zip](https://github.com/google/ExoPlayer/files/5222085/bjws-20655436911.zip)

The error log：
09-15 10:07:06.325 6394-6394/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=4.32, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:487)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.maybeThrowPrepareError(ProgressiveMediaPeriod.java:239)
        at com.google.android.exoplayer2.source.MaskingMediaPeriod.maybeThrowPrepareError(MaskingMediaPeriod.java:144)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:838)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:410)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
    ]

**Comment by icbaker** [comment] 2020-09-15 16:07
I tried to reproduce with your provided file in the ExoPlayer demo app built from dev-v2 branch on a Pixel 3a XL running R. Playback seems to complete fine and I don't see any errors in logcat.

Can you provide the info requested in the issue template?
* Device name & OS version
* ExoPlayer version
* Full bugreport taken with `adb bugreport` and attached as a zip or emailed to dev.exoplayer@gmail.com with subject "Issue #7909".

**Comment by arlimm318** [comment] 2020-09-16 03:16
Device name & OS version: STB Based on the Hisilicon chip mv310,  android4.4.2
ExoPlayer version:dev-v2 2.11.7

The previous mistake was due to my negligence,Ignore the previous error. 
[device-2020-09-16-110936.zip](https://github.com/google/ExoPlayer/files/5229407/device-2020-09-16-110936.zip)
Now there are no errors, but no images are displayed.I recorded the video and the log.

**Comment by icbaker** [comment] 2020-09-16 15:12
I agree no image is shown. I don't see any image when I play the .ts video file in VLC either.

For such a short video what image are you expecting to see?

**Comment by arlimm318** [comment] 2020-09-16 15:18
You can see the picture with FFPlay.
This TS file contains only frame I，I think I should see the decoded frame I.

**Comment by icbaker** [comment] 2020-09-17 09:00
Thanks - I looked deeper into what's going on here.

When parsing MPEG-TS we use the start of the next frame as the trigger for calling `SampleQueue#sampleMetadata` call for the previous one:
https://github.com/google/ExoPlayer/blob/744c57c87d8308de1713246dc90ecb1a14083277/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/H264Reader.java#L466

We probably always fail to output the final frame properly. It just happens to be more visible when the final frame is also the first and only frame. We do it this way because MPEG-TS doesn't clearly indicate where the end of each sample is, unlike something like MP4/MKV.

We could use end-of-stream as a signal to flush out the final sample, but given MPEG-TS is often clipped in random places, that would quite likely cause a new problem where we output a partial frame as the last sample in some cases. So, I guess the question is whether upon seeing end-of-stream, there's a good way to determine whether the sample data that has been output is a complete sample, in which case we could call sampleMetadata conditionally on that check passing.

**Comment by arlimm318** [comment] 2020-09-17 09:20
Thanks very much.
I look forward to the resolution of this problem.

**Comment by icbaker** [comment] 2023-06-29 13:45
This should be resolved by https://github.com/androidx/media/pull/419

**Closed as completed by icbaker** 2023-06-29 13:45 UTC
Labels: bug, low priority
