### ISSUE TITLE
.srt subtitles don't display when they are not ordered in time

### ISSUE THREAD

**Issue by lldartsll** [google/ExoPlayer#3742] opened 2018-01-23 12:09 UTC
Greetings,
I am trying to play subtitles from url. 
the subtitles are in srt format they work as intended for the first 
3 minutes 29 seconds then they dont appear for the rest of the video.

the same subtitles were tested on a local website using html5 video they work fine.
they were also tested using another android video player and they work fine.
i converted the srt file to webvtt and it worked fine on exoplayer2

but i can't keep converting every srt file i have to webvtt 

My code:
`

private MediaSource subRibMedia(String subpath){
        DataSource.Factory factory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "exo app"));

        Format subtitleFormat = Format.createTextSampleFormat(
                "0", // An identifier for the track. May be null.
                MimeTypes.APPLICATION_SUBRIP, // The mime type. Must be set correctly.
                Format.NO_VALUE, // Selection flags for the track.
                "Ar"); // The subtitle language. May be null.
        MediaSource subtitleSource = new SingleSampleMediaSource(Uri.parse(subpath), factory, subtitleFormat, C.TIME_UNSET);

        return subtitleSource;
    }`
`

MediaSource mediaSource = buildMediaSource(uri);
        MediaSource sub=subRibMedia(subpath);

        MediaSource mergedmediasource=new MergingMediaSource(mediaSource,sub);

        player.prepare(mergedmediasource, false, false);`

PS.: it always says that "SingleSampleMediaSource() is deprecated" and i can't find an alternative 
PSS: the subs are in Arabic
[subs.zip](https://github.com/google/ExoPlayer/files/1655762/subs.zip)

**Comment by ojw28** [comment] 2018-01-23 14:23
Why are the captions in the file in a random order, rather than increasing with time?

**Comment by ojw28** [comment] 2018-01-23 14:26
>PS.: it always says that "SingleSampleMediaSource() is deprecated" and i can't find an alternative

The [Javadoc](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/SingleSampleMediaSource.html) tells you what to use instead.

**Comment by lldartsll** [comment] 2018-01-23 15:43
@ojw28 
thank you for the doc
as for your question. I don't know
and i have no control over the content or the subtitles
but the subtitles work normally using everything i have tried so far except exoplayer
(by everything i mean html5 video player, vlc media player and [this library](https://github.com/halilozercan/BetterVideoPlayer) )

**Comment by ojw28** [comment] 2018-01-24 21:21
I tried playing the provided subtitle files in MxPlayer, and I see things like this. Is this really expected? It does match what's in the files, but I'm not convinced that the files aren't just broken. Have you encountered any other problematic srt files, or is it just this one example?

![screenshot_20180124-210026](https://user-images.githubusercontent.com/7881572/35357799-89fcee80-014c-11e8-8750-c2c7bf863ece.png)

**Comment by lldartsll** [comment] 2018-01-26 20:55
@ojw28 
sorry for the late reply .
yes this is to be expected.
and i have yet to try it with enough samples to say for certain if this is the only problematic one.
i will check with other examples tomorrow and tell you my findings

**Comment by lldartsll** [comment] 2018-01-27 19:24
@ojw28 
ok so apparently the bug happens when the subtitles are not ordered by time(sorry if i am not making sense )  
for the sake of clarity i have included my test srt files
[SRTTest.zip](https://github.com/google/ExoPlayer/files/1670441/SRTTest.zip)

test.srt displays all three subtitles
while test1.srt shows only "subA"

**Comment by ojw28** [comment] 2018-01-29 09:27
It's correct that the issue occurs when subtitles are not ordered in time. It's always been assumed in our code that SubRip subtitles should be ordered. There's no sane reason to produce an out of order SubRip file, as far as I can tell? One problem with SubRip is that (again, as far as I can tell) there is no definition actually written down anywhere. Although Wikipedia does indicate the subtitles should be "sequential".

If this is just a single file that's been produced in a strange way, then I don't think it's worth us investing any time fixing the issue.

**Comment by lldartsll** [comment] 2018-01-29 09:33
@ojw28 
actually its not one file but the majority...
when translators write the subtitle file for lets say a series. they always put "translated by somename" at the end of the file but plays it minute 1 or 2 (they copy paste it with the time stamp).

**Comment by ojw28** [comment] 2018-01-29 09:46
We've supported SubRip without this issue being raised for well over 2 years, so it seems unlikely that the majority of SubRip files are affected. Perhaps it's just the majority of files from whatever your source is.

The original problematic file does not appear to be problematic because someone's added a "translated by somename" line at the end. The subtitles go in sequence up to around 23 minutes, and then there are  large number of subtitles around 2-3 minutes, then a final 4 subtitles around 23 minutes again.

**Comment by lldartsll** [comment] 2018-01-29 09:58
@ojw28 
yes sorry for the confusion i meant the majority of my SubRip files will be affected.
the original file was my first test. and yes it is just as you described it. but i also have files with "translated by" at the end that will also be affected.
Maybe if you can point me in the right direction i can create a module of exoplayer and tinker with it myself that would be greatly appreciated

**Comment by ojw28** [comment] 2018-02-16 12:30
What is the source of the affected files? I'm erring on the side of closing this as working as intended. Unless it can be demonstrated that a popular SubRip tool is generating affected files, then I think the correct solution would be to fix whatever is creating these files so that they're in a sensible order (i.e. increasing with time).

In case you wanted to tinker yourself, the package you'd need to look at is com.google.android.exoplayer2.text.subrip.

**Comment by lldartsll** [comment] 2018-02-17 07:13
@ojw28 
I don't know the source of the subtitles. 
thank you for pointing me in the right direction.

**for any one having the same problem** what I did was skipping exoplayer SubtitleView entirely  
(is it ok to post my workaround here?)

**Comment by ojw28** [comment] 2018-02-19 16:57
Feel free to post your solution here, although given no-one has filed a similar issue in the past 2 years, I doubt this is a widespread problem :). Closing for now.

**Closed as completed by ojw28** 2018-02-19 16:57 UTC
Labels: low priority

**Comment by lldartsll** [comment] 2018-02-19 20:02
so what i did was 
1-adding [this library](https://github.com/halilozercan/BetterVideoPlayer) as a model
and using its CaptionView 
2-in CaptionsView.java you have to replace the MediaPlayer with SimpleExoPlayer and you have to parse 
`simpleExoPlayer.getCurrentPosition() / 1000` to int
3-now in your main project in exo_simple_playerview.xml add the following 
`<com.halilibo.bettervideoplayer.subtitle.CaptionsView
            android:layout_gravity="bottom|center"
            android:id="@+id/cpns"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />`
4-just add the following to your player activity
 `captionsView.setCaptionsSource(Uri.parse("subtitleUrl"), CaptionsView.CMime.SUBRIP);
  captionsView.setPlayer(player);
and you are done 
`
