### ISSUE TITLE
ExoPlayer renders video outside of borders of DialogFragment when inside scrolled RecyclerView

### ISSUE THREAD

**Issue by SnowMonkey624** [google/ExoPlayer#6955] opened 2020-02-09 02:08 UTC
Issue description:
With ExoPlayer being used in a RecyclerView that itself is within a DialogFragment, if a video is scrolled to the end of the RecyclerView to a point where it should disappear from the DialogFragment's view, it continues to appear in the transparent margins at the edge of the DialogFragment.

Reproduction steps: 
Have a ViewHolder with a standard PlayerView, create an adapter to use that in a RecyclerView, and use that RecyclerView in a DialogFragment, then scroll a video to the edges of the DialogFragment. 

Link to test content:
https://github.com/SnowMonkey624/ExoPlayerBug
Screenshots in the screenshots directory, but clearest example is 
https://raw.githubusercontent.com/SnowMonkey624/ExoPlayerBug/master/screenshots/Screenshot_20200208-202311.png

A full bug report captured from the device:
No stacktrace relevant, this is purely a visual bug.

Version of ExoPlayer being used: 
2.11.1

Device(s) and version(s) of Android being used:
- Google Pixel XL (API 29)
- OnePlus 5T (API 26)
- Android Emulator (API 25)

**Comment by ojw28** [comment] 2020-02-09 12:17
This isn't really an ExoPlayer bug. ExoPlayer renders into whatever `Surface` is provided to it. How that `Surface` is then composited with other UI components is up to the underlying platform and graphics pipeline.

* Please could you file an issue on the [Android Issue Tracker](https://source.android.com/setup/contribute/report-bugs), with reproduction steps and linking to your test project (thanks for providing one - it makes it very easy to reproduce the issue!).
* Please update this issue with a link to the one you file on the Android Issue Tracker, when you do so, and we can help to make sure it's routed to the right people internally.
* In the meantime, you can work around this issue by setting `app:surface_type="texture_view"` on the `PlayerView` instances that you're using. `TextureView` is treated much more like a "normal" view than `SurfaceView` is, when it comes to compositing, and so is less prone to this type of issue. There are also some disadvantages. You can read about the pros and cons [here](https://exoplayer.dev/ui-components.html#choosing-a-surface-type).

**Comment by ojw28** [comment] 2020-03-09 22:40
[Internal ref: b/150506720]

**Comment by ojw28** [comment] 2022-07-07 15:17
Closing because this is not an ExoPlayer bug, as noted above.

**Closed as completed by ojw28** 2022-07-07 15:17 UTC
Labels: bug: in platform
