### ISSUE TITLE
Rewind live ProgressiveMediaSource

### ISSUE THREAD

**Issue by ilpelatodijavascript** [google/ExoPlayer#6863] opened 2020-01-12 14:13 UTC
Hi, I tried doing this
```
long currentPosition = simpleExoPlayer.getCurrentPosition();
long seekPosition = currentPosition - 1000;

simpleExoPlayer.seekTo(seekPosition);
```
to rewind one second of my live stream.

This is how I play my live source:
```
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getActivity(), Util.getUserAgent(getActivity(), "AppUA"));
MediaSource liveMedia = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(source));
simpleExoPlayer.prepare(liveMedia);
```

Is this even possible or I'm doing it wrong?
Thanks

**Comment by ojw28** [comment] 2020-01-13 22:01
Assuming it's a progressive stream (i.e., you're using `ProgressiveMediaSource`), seeking/rewinding is not supported. https://github.com/google/ExoPlayer/issues/6562 tracks adding support for that, however if you control the serving side you should consider using DASH or HLS instead, which are properly designed to support seeking in live content.

Closing as a duplicate of https://github.com/google/ExoPlayer/issues/6562.

**Closed as completed by ojw28** 2020-01-13 22:01 UTC
Labels: duplicate
