### ISSUE TITLE
Resume download with uri change 

### ISSUE THREAD

**Issue by mynew-github-account** [google/ExoPlayer#8149] opened 2020-11-02 15:00 UTC
I want to change some parameter in download uri after it expire after some time.
Here is detail 
1.Once I start download with uri == xyz.m3u8?token=abc
2.After some time token for this uri going to expire so want to replace with new token 

is there way to achieve this ?

**Comment by marcbaechinger** [comment] 2020-11-03 12:28
Does it help to use `DownloadRequest.Builder.setCustomCacheKey` together with a [`ResolvingDataSource`](https://exoplayer.dev/customization.html#customizing-server-interactions)?

**Comment by mynew-github-account** [comment] 2020-11-03 13:44
Nope it still start new download
i.e it doesn't not resume after URL change

**Comment by marcbaechinger** [comment] 2020-11-03 14:07
Ok. Can you please provide more information so this get actionable for me? Like can you describe what `not resume` means and if this gives you any errors or the like when the downloader tries downloading and what the expected behaviour would be?

**Comment by mynew-github-account** [comment] 2020-11-03 14:25
Ok here is detailed flow I want to achieve.
1--> User click on the download 
2 --> app will fetch m3u8 URL for download let say    abcxyz.m3u8?token=abc&policy=abc
3 --> Now using this URL video downloading start 
4 --> But this token in this URL has a validity of 5min ,so after 5 min server going to reject all request from this URL 
5 --> So now if video download stop(let see at 50%) due to some reason (No network)  or user manually stop the download 
6--> Now when user resume or network available, token used in URL is not valid so download failed as server reject a request as a token is invalid 
7 --> So now if I try to change token while resuming download it starts from 0% again 

So My question-- is there any way to change URI only or parameter of URL and resume download from 50% again??

**Comment by marcbaechinger** [comment] 2020-11-03 15:23
I think it could work if you use a `ResolvingDataSource`. You would then create the download request with a url without the token, like:

```
https://example.com/playlist.m3u8
```

This is the the url which is used by the cache to identify the playlist in the cache. So if it is requested again for playback that uri is looked up in the cache and if it is found, the cached playlist is returned. 

You can then use the `ResolvingDataSource` that converts the uri into for instance https://example.com/playlist.m3u8?token=1234 that does the actual network request.  Then the download can start looking into the playlist and download the segments with the uris referenced in the segments.

Then later at playback you ask for the same url without token again: `https://example.com/playlist.m3u8`. This would give the cached playlist with the uris referenced in there. Because all media is downloaded by these uri, the media data can be taken from the cache by the uris reference in the cached playlist.

I think I would try that this way. If it's worth for you to solve this, you may want to try this out. I can't really give you a step-by-step guidance for this I'm afraid.

**Comment by marcbaechinger** [comment] 2020-12-21 20:32
Closing due to inactivity.

**Closed as completed by marcbaechinger** 2020-12-21 20:32 UTC
Labels: question
