### ISSUE TITLE
r2.6.1 Demo App - Player View blinks when press back during playback

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#3699] opened 2018-01-12 12:02 UTC
Hi,
This can be reproduced on Nexus 6p Android 8.1.0 on Pixel 8.1.0 the blink is seen but in lower extent and on Nexus 5 Android 6.0 it is fine.

Any suggestion to avoid this behaviour?

This behaviour is the same for r2.6.0.
Gilad

**Comment by ojw28** [comment] 2018-01-21 18:48
I was not able to reproduce this. Please provide detailed reproduction steps using the ExoPlayer demo app, and attach the information requested in the issue template (including a full bug report).

**Comment by giladna** [comment] 2018-01-23 14:22
@ojw28 
No specific scenario
Just play the google glass with Nexus 6p 8.1.0 and press back to get back to the gallery
I will see the player destroying it self in the middle of the screen

BR,
Gilad.

**Comment by AquilesCanta** [comment] 2018-01-23 18:30
Reproducible on google/bullhead/bullhead:8.1.0/OC-MR1/4304643:userdebug/dev-keys

**Comment by ojw28** [comment] 2018-01-31 14:17
I've reported this internally [Ref: b/72734268], and will post an update when I have it. It may be possible to mitigate the issue by setting the visibility of the player view to INVISIBLE or GONE at some point before the activity transition, although obviously this should not be necessary,

**Comment by ojw28** [comment] 2018-02-01 11:26
This appears to be an Android platform bug that's fixed in P :(. I'm not really sure what to advise for 8.1.0 devices, unfortunately, although you can play around with the player view's visibility as noted above.

**Comment by ojw28** [comment] 2018-02-26 19:23
Closing because I don't think there's much we can do in ExoPlayer. This is a platform bug, and if there is a good workaround it's not going to be ExoPlayer specific.

**Closed as completed by ojw28** 2018-02-26 19:23 UTC
Labels: bug: in platform
