### ISSUE TITLE
ExoPlayer fails to play a specific fragmented m4a file

### ISSUE THREAD

**Issue by raja-baz** [google/ExoPlayer#7468] opened 2020-06-04 15:55 UTC
### [REQUIRED] Issue description

ExoPlayer fails to play files generated by ffmpeg with the following command line:

```
ffmpeg -i test.m4a -acodec aac -ab 128k -f mp4 -movflags frag_keyframe+faststart test2.m4a
```

ExoPlayer detects this file as fragmented but `FragmentedMp4Extractor` then fails to properly extract media from this. The actual reason seems to be that the file is missing a `moof` Atom after the `moov` Atom.

Note that this doesn't happen if we revert the following commit: [147deafd01e18621cb5221132f0e39598ceeb186](https://github.com/google/ExoPlayer/commit/147deafd01e18621cb5221132f0e39598ceeb186)

Note that we recently updated from a very old ExoPlayer version(2.7.3) that didn't have this issue, which is how we noticed this.

This commit doesn't directly cause the issue, it just causes the file to be (correctly?) identified as fragmented whereas this wasn't happening before. I see two possible solutions here:

1. Have the sniffer detect this particular case(single `mdat` Atom with no `moof`) detected as not fragmented even though an `mvex` Atom is present.
2. Fix `FragmentedMp4Extractor` to actually deal well with this type of fragmented file(no `sidx` but somehow seekable and no `moof` but works correctly, which is a situation completely not dealt with).

I am not familiar enough with the mp4 spec to figure out which of the above would be easiest or most correct to do. I don't even know if this type of file is legal, but ffmpeg seems to generate them.

### [REQUIRED] Reproduction steps

Try to play a file generated with the above ffmpeg command, it will fail to play in ExoPlayer. The duration loads correctly and it looks like it's playing but no content actually plays.

Personally, I reproduced this in the demo app by pointing one of the entries in `media.exolist.json` at a self-hosted copy of the file linked below with no other changes. The commit above was found by bisecting roughly 2 years of history while applying a patch to modify the media list and testing at every iteration.

### [REQUIRED] Link to test content

[Link to sample file which reproduces the issue](https://drive.google.com/file/d/1ExjJFZILFdxw--sXinTdrLHD75_FQFHY/view?usp=sharing)

### [REQUIRED] Version of ExoPlayer being used

2.11.4

**Comment by ojw28** [comment] 2020-06-04 16:53
@andrewlewis FYI - I didn't check, but it's possible this is a dupe of https://github.com/google/ExoPlayer/issues/7308.

**Comment by raja-baz** [comment] 2020-06-04 16:56
That indeed looks very likely from this discussion on that other thread, yes. My search-fu failed to find it.

**Comment by andrewlewis** [comment] 2020-06-08 09:26
Duplicate of #7308

**Closed as completed by andrewlewis** 2020-06-08 09:26 UTC
Labels: duplicate

**Comment by andrewlewis** [comment] 2020-06-08 09:29
Thanks for the report. Addressing #7308 is on our roadmap to be investigated soon. Until then, hopefully you can generate the file in a different way to avoid this problem (probably removing `frag_keyframe`?).
