### ISSUE TITLE
Wrong audio length

### ISSUE THREAD

**Issue by dawidwisniewski19992** [google/ExoPlayer#10531] opened 2022-08-17 08:49 UTC
Hi, I've implemented my own BaseDataSource implementation but I have some troubles with the total length displayed on the audio. I have some long audios in my app (over 1h) and when I'm playing it the total length of the audio is changing for example when I go to the next audio and get back. Is there any possibility to disable it and display the proper length from the beginning? I'm guessing that the problem is that the audio is not fully downloaded and that's why it's displaying length of the part of the audio. I've already found some similar issues like https://github.com/google/ExoPlayer/issues/10472 but I'm not sure how to exactly implement it correctly. This is my open and read methods:
```
 @Throws(FileDataSource.FileDataSourceException::class)
    override fun open(dataSpec: DataSpec): Long {
        val item = itemDataProvider.getItem(dataSpec.uri.toString())

        val audioFile = runBlocking { fileManager.fetchAudioFile(mediaDataProvider.extract(item)) }

        this.uri = audioFile.uri
        transferInitializing(dataSpec)
        file = openLocalFile(audioFile.uri)
        bytesRemaining = try {
            file!!.seek(dataSpec.position)
            if (dataSpec.length == C.LENGTH_UNSET.toLong()) file!!.length() - dataSpec.position else dataSpec.length
        } catch (e: IOException) {
            throw FileDataSource.FileDataSourceException(e, PlaybackException.ERROR_CODE_IO_UNSPECIFIED)
        }
        if (bytesRemaining < 0) {
            throw FileDataSource.FileDataSourceException(null, null, PlaybackException.ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE)
        }

        opened = true
        transferStarted(dataSpec)

        return bytesRemaining
    }

    @Throws(FileDataSource.FileDataSourceException::class)
    override fun read(buffer: ByteArray, offset: Int, length: Int): Int {
        return if (length == 0) {
            0
        } else if (bytesRemaining == 0L) {
            C.RESULT_END_OF_INPUT
        } else {
            val bytesRead: Int = try {
                Util.castNonNull(file).read(buffer, offset, min(bytesRemaining, length.toLong()).toInt())
            } catch (e: IOException) {
                throw FileDataSource.FileDataSourceException(e, PlaybackException.ERROR_CODE_IO_UNSPECIFIED)
            }
            if (bytesRead > 0) {
                bytesRemaining -= bytesRead.toLong()
                bytesTransferred(bytesRead)
            }
            bytesRead
        }
    }
```

**Comment by icbaker** [comment] 2022-08-19 09:45
There isn't enough information here to help you.

Can you reproduce the problem without using your `DataSource` implementation? That would help narrow down the potential cause of the error. It's also unclear to me why you seem to have partially re-implemented `FileDataSource` - it looks like you could instead have implemented this as a [`ResolvingDataSource`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/ResolvingDataSource.html) that just does the following two lines, and then delegates the actual file reading to `DefaultDataSource` or `FileDataSource`:

```
val item = itemDataProvider.getItem(dataSpec.uri.toString())
val audioFile = runBlocking { fileManager.fetchAudioFile(mediaDataProvider.extract(item)) }
```

Note that the duration of MP3 files is often hard to determine (I don't know if this is relevant, because you haven't mentioned what type of file you're playing): https://exoplayer.dev/troubleshooting.html#why-is-seeking-inaccurate-in-some-mp3-files

I suspect this problem is related to the media you're playing rather than to the `DataSource` implementation - but it's hard to be sure without more information.

**Closed as completed** 2022-09-19 01:04 UTC
Labels: question, closed-by-bot
