### ISSUE TITLE
HLS stream stop playback after a while

### ISSUE THREAD

**Issue by zgzong** [google/ExoPlayer#8564] opened 2021-02-08 15:23 UTC
When play a long HLS Vod content ( 3-4 hours long), the playback stops after a while. 

The issue lies in the way that exo-player determines the amount of available buffer for playback:
Playback buffer remaining is calculated as the total buffered time in the source from the start of playback (in content time as declared by metadata/hls playlist) minus the amount content time rendered at the renderer (current playback time)

This works as long as the metadata signalled durations are in line with the actual length of the playback chunks.

However, the metadata/playlist signals the chunk durations as integers (by spec, rounded up to the next whole integer) but the segment actually has a float number data. E.G. every segment may has 0.1 seconds less that the duration reported in metadata/hls playlist.  

After certain minutes, exo-player believes an extra DEFAULT_MAX_BUFFER_MS (50_000) of data exists in the source buffer that just isn't there, preventing the source from continuing buffering.

**Comment by ojw28** [comment] 2021-02-09 01:13
Duplicate of https://github.com/google/ExoPlayer/issues/2233.

**Closed as completed by ojw28** 2021-02-09 01:13 UTC
Labels: duplicate
