### ISSUE TITLE
"XmlPullParserException: unterminated entity ref"  for "DashManifestParser.parse(..)"

### ISSUE THREAD

**Issue by marcinOz** [google/ExoPlayer#4086] opened 2018-04-04 15:00 UTC
### Issue description
When starting to play the stream on devices with Android 4.4.4 (probably 4.x, with higher versions everything works) it starts playing and after a second or two player error is thrown.

EventLogger: internalError [5.09, loadError]
...
Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:62 in java.io.InputStreamReader@42226f88)

### Reproduction steps
To reproduce we would need to add your IP to whitelisting, so I hope Manifest would be enough.
1. Play stream
2. wait a while 
3. Player Error!

### Link to test content

last Manifest that comes before the error: [Manifest (1).zip](https://github.com/google/ExoPlayer/files/1876350/Manifest.1.zip)

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
SM-G357FZ Android 4.4.4, Sony Z1 Android 4.4.4

### A full bug report captured from the device
[logs.txt](https://github.com/google/ExoPlayer/files/1876340/logs.txt)

**Comment by andrewlewis** [comment] 2018-04-06 16:52
It sounds like this was fixed in Lollipop, but it would be useful to see the manifest being parsed when the error is thrown, in case there's a stray "&" or something else that should be escaped. I guess "1:62" indicates character 62 on line one but that doesn't include anything suspicious in the given manifest, so could you double check that the provided manifest corresponds to the one being loaded when the error was thrown?

**Comment by m-scheepers** [comment] 2018-05-02 13:41
I will request @marcinOz to provide further information to this ticket; 

The manifests received from the streaming server appear to be gzipped; something happens while parsing the gzipped manifest which causes this error.

When we decode the manifest ourselves first and pass it to the player then it appears to work fine. We implemented it is a temporary workaround but don't consider this to be something we would like to include in later updates of our apps.

I have also requested the provider of the streaming server if we could get a manifest which is not gzipped; but this is not by default the case for them.

**Comment by ojw28** [comment] 2018-06-05 21:26
Without a sample server response that causes this issue, or a way to get one, there's not a lot we can do to help. Closing for now. We'll re-open the issue if more information is provided.

**Closed as completed by ojw28** 2018-06-05 21:26 UTC
Labels: need more info

**Comment by ravirajjak** [comment] 2018-08-28 16:08
59 18570-18977/in.publicam.blueplanet E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT #EXTM3U
    #EXT-X-V...@16:1 in java.io.InputStreamReader@7ead5b8) 
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:101)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:54)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:126)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT #EXTM3U
    #EXT-X-V...@16:1 in java.io.InputStreamReader@7ead5b8) 
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:440)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:94)
        	... 6 more

**Comment by andrewlewis** [comment] 2018-08-28 16:33
@ravirajjak Looks like you need to use `HlsMediaSource` instead of `DashMediaSource`.

**Comment by nishant-castleglobal** [comment] 2018-11-14 10:52
I am facing the same/similar issue when opening this media in exoplayer.

@marcinOz can you help me with the temporary workaround that you mentioned. Or any other way to fix this issue.

https://hive-moderation.akamaized.net/72853fea-73eb-4afe-a1f5-5da7af7d8768?__token__=exp=1542195775~hmac=a809c77c5ebdc22a1688b1a7c8dcd599e3ba4e731817bf380aeefc3131c0e9e8


> 11-14 16:12:57.153 21297-21607/com.myproject.debug E/ExoPlayerImplInternal: Source error.
>     com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ID3��������vTIT2����...@2:5 in java.io.InputStreamReader@d047e6c) 
>         at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:105)
>         at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58)
>         at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>         at java.lang.Thread.run(Thread.java:818)
>      Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ID3��������vTIT2����...@2:5 in java.io.InputStreamReader@d047e6c) 
>         at org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
>         at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
>         at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:98)
>         at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58) 
>         at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130) 
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>         at java.lang.Thread.run(Thread.java:818)
