### ISSUE TITLE
How to use our custom notification for DownloadService

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#9211] opened 2021-07-21 10:34 UTC
I am looking at `DemoDownloadService` which uses `DownloadNotificationHelper` and shows the download progress in notification.

I want to use my custom notification to give more functionalities on Notification UI. Is there any way to customize it.
One approach, I am thinking to copy paste the class `DownloadNotificationHelper` in my custom class as `DownloadNotificationHelper` is final, i can not extend it. And then after having the same on my end, i can create the notifications.

Suppose, I put 1st media for downloading, i can see one notification. If I put 2nd media then download progress is merged and showed it on the notification.

I want to show multiple notifications for each download so that I can handle the pause/resume functionalities individually. 

ExoPlayer version: 2.14.1

**Comment by marcbaechinger** [comment] 2021-07-21 13:38
I think this is a duplicate of #8297. The comments there seem to answer your question. May I kindly ask you to check the other issue for more information.

I'm closing this issue. If you think your issue is different from  #8297, please reopen.

**Closed as completed by marcbaechinger** 2021-07-21 13:38 UTC
Labels: question
