### ISSUE TITLE
java.lang.IndexOutOfBoundsException: 

### ISSUE THREAD

**Issue by ummerakbar45** [google/ExoPlayer#5091] opened 2018-11-12 10:36 UTC
### Issue description
java.lang.IndexOutOfBoundsException: 

### Reproduction steps
As such there is no way to reproduce the issue, we found this issue on playstore  crashes

### Link to test content
No Link available

### Version of ExoPlayer being used
  implementation 'com.google.android.exoplayer:exoplayer:2.9.0'

### Device(s) and version(s) of Android being used
Almost on all devices and on all versions

### A full bug report captured from the device

java.lang.IndexOutOfBoundsException: 
  at com.google.android.exoplayer2.util.Assertions.checkIndex (Assertions.java:68)
  at com.google.android.exoplayer2.source.SinglePeriodTimeline.getWindow (SinglePeriodTimeline.java:151)
  at com.google.android.exoplayer2.source.ForwardingTimeline.getWindow (ForwardingTimeline.java:62)
  at com.google.android.exoplayer2.source.AbstractConcatenatedTimeline.getWindow (AbstractConcatenatedTimeline.java:195)
  at com.google.android.exoplayer2.Timeline.getWindow (Timeline.java:638)
  at com.google.android.exoplayer2.Timeline.getWindow (Timeline.java:625)
  at com.google.android.exoplayer2.ui.PlayerControlView.updateProgress (PlayerControlView.java:726)
  at com.google.android.exoplayer2.ui.PlayerControlView.access$800 (PlayerControlView.java:164)
  at com.google.android.exoplayer2.ui.PlayerControlView$ComponentListener.onTimelineChanged (PlayerControlView.java:1090)
  at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners (ExoPlayerImpl.java:839)
  at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo (ExoPlayerImpl.java:776)
  at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo (ExoPlayerImpl.java:713)
  at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent (ExoPlayerImpl.java:658)
  at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:129)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6146)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:755)

**Comment by tonihei** [comment] 2018-11-12 10:51
Duplicate of #4939.

**Closed as completed** 2018-11-12 10:51 UTC
Labels: duplicate
