### ISSUE TITLE
"Audio Underrun " followed by "A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 30427 (CodecLooper)" error!!!

### ISSUE THREAD

**Issue by robindanielk** [google/ExoPlayer#4426] opened 2018-06-26 04:11 UTC
Hi , I have been using the exoplayer setup  to stream video in android STB . Randomly i get the above errors and some times crashes. I have noticed that the error occurs before the start of media source and I use concatenating media sources. Attached the bug reports for both the cases.
[bugRPT2.txt](https://github.com/google/ExoPlayer/files/2135527/bugRPT2.txt)
[codecBug.txt](https://github.com/google/ExoPlayer/files/2135528/codecBug.txt)
 Need help in resolving this issue !!

**Comment by andrewlewis** [comment] 2018-06-26 18:06
Looking at the codec SIGABRT to start with, it looks like it's an issue with the H.264/AVC decoder output buffer size. There is a failing assertion

`frameworks/av/media/libstagefright/foundation/ABuffer.cpp:76 CHECK_LE( offset + size,mCapacity) failed: 3538944 vs. 3456000`

just after this capacity is set for video output buffers:

`ACodec  : [OMX.hisi.video.decoder.avc] Allocating 7 buffers from a native window of size 3456000 on output port.`.

You haven't provided the stream that was being played when this error was thrown, but I suspect this error may be caused by the resolution being signaled incorrectly in the container (2000 × 1152) or it may just be caused by the fact that this resolution is unconventional. Could you see if the problematic stream is a different resolution than other streams you're trying to play?

**Comment by robindanielk** [comment] 2018-06-27 04:08
Hi , I dont have the streams live currently , we just play from the files that are locally available.. but its very random ..thats the problem..!! And one more thing is that i took a log of the server from which those media sources are available and found that the time when the audiounderrun occurs , there seems to no log of the server at that  specific time.
Kindly explain  what do you mean by  " resolution being signaled incorrectly in the container (2000 × 1152) " ..!

**Comment by andrewlewis** [comment] 2018-06-27 07:31
Based on the logging, the video's resolution is 2000 × 1152 but the video decoder is allocating output buffers that are too small. It's really just a guess, but I wonder whether the resolution given in the container is wrong.

There's not much information to go on here. It could be a device-specific bug in the video decoder, or it could be that the media is bad. We'd probably need to see the stream that causes the crash to make progress. If you have control over what the videos being played I'd recommend using a more common resolution like 1080p or 720p.

**Comment by robindanielk** [comment] 2018-06-27 10:04
Those streams i have are of 1080p but some videos are of different resolution as you have mentioned. Like the same 1080p video appears full screen or with aspect ratio fit. with black bars above and below . Is there a workaround around for this issue and also noticed the same issues on other devices of the STB.!!

**Comment by robindanielk** [comment] 2018-06-27 10:33
**In the log cat the following take place before audioUnderrun ,**
  
> 06-27 15:59:11.609 23889-24964/com.example.ridsys_001.AsterTest E/OMXMaster: A component of name 'OMX.hisi.audio.ddpdec' already exists, ignoring this one.
06-27 15:59:11.617 23889-24964/com.example.ridsys_001.AsterTest I/MediaCodec: MediaCodec::setState == > mCrypto.clear
06-27 15:59:11.620 23889-24964/com.example.ridsys_001.AsterTest I/ACodec: [OMX.google.aac.decoder] Allocating 4 buffers of size 8192 on input port
    [OMX.google.aac.decoder] Allocating 4 buffers of size 32768 on output port
06-27 15:59:11.625 23889-24965/com.example.ridsys_001.AsterTest I/SoftAAC2: limiting to stereo output
06-27 15:59:11.629 23889-24965/com.example.ridsys_001.AsterTest I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
06-27 15:59:11.630 23889-24964/com.example.ridsys_001.AsterTest I/ACodec: [OMX.google.aac.decoder] OMX_EventPortSettingsChanged 0x00000000
06-27 15:59:11.632 23889-23889/com.example.ridsys_001.AsterTest D/EventLogger: decoderInitialized [396.51, 136.53, window=2, period=2, audio, OMX.google.aac.decoder]
06-27 15:59:11.634 23889-24964/com.example.ridsys_001.AsterTest I/ACodec: [OMX.google.aac.decoder] Output port now disabled.
06-27 15:59:11.635 23889-24964/com.example.ridsys_001.AsterTest I/ACodec: [OMX.google.aac.decoder] Allocating 4 buffers of size 32768 on output port
06-27 15:59:11.636 23889-24964/com.example.ridsys_001.AsterTest I/ACodec: [OMX.google.aac.decoder] Output port now reenabled.
06-27 15:59:11.638 23889-23889/com.example.ridsys_001.AsterTest D/EventLogger: downstreamFormatChanged [396.52, 136.55, window=2, period=2, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=und]
06-27 15:59:11.752 23889-24130/com.example.ridsys_001.AsterTest W/ACodec: [OMX.hisi.video.decoder.avc] Calculate FRC fail, use default value 1
06-27 15:59:11.782 23889-24130/com.example.ridsys_001.AsterTest W/ACodec: [OMX.hisi.video.decoder.avc] Calculate FRC fail, use default value 1
06-27 15:59:11.797 23889-24129/com.example.ridsys_001.AsterTest I/MediaCodec: MediaCodec::setState == > mCrypto.clear
06-27 15:59:11.859 23889-24129/com.example.ridsys_001.AsterTest I/MediaCodec: MediaCodec::setState == > mCrypto.clear
06-27 15:59:11.860 23889-24111/com.example.ridsys_001.AsterTest I/ACodec: FrcDestroy(0xc00000)
06-27 15:59:11.866 23889-24968/com.example.ridsys_001.AsterTest I/OMXClient: Using client-side OMX mux.
06-27 15:59:11.870 23889-24967/com.example.ridsys_001.AsterTest I/MediaCodec: MediaCodec::setState == > mCrypto.clear
06-27 15:59:11.874 23889-24968/com.example.ridsys_001.AsterTest E/ACodec: [OMX.hisi.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
06-27 15:59:11.875 23889-24968/com.example.ridsys_001.AsterTest I/ACodec: [OMX.hisi.video.decoder.avc] prepareForAdaptivePlayback(1920x1080)
06-27 15:59:11.887 23889-24968/com.example.ridsys_001.AsterTest I/ACodec: [OMX.hisi.video.decoder.avc] Allocating 4 buffers of size 2097152 on input port
06-27 15:59:11.895 23889-24968/com.example.ridsys_001.AsterTest I/ACodec: [OMX.hisi.video.decoder.avc] will output to SurfaceView
    Output will queue to overlay.
06-27 15:59:11.896 23889-24968/com.example.ridsys_001.AsterTest I/ACodec:  isVideoBypass -- omxBypass = 0, queuesToNativeWindow = 1
06-27 15:59:11.898 23889-24968/com.example.ridsys_001.AsterTest I/ACodec: [OMX.hisi.video.decoder.avc] Allocating 7 buffers from a native window of size 3110400 on output port
06-27 15:59:12.396 23889-23889/com.example.ridsys_001.AsterTest D/EventLogger: decoderInitialized [397.28, 137.09, window=2, period=2, video, OMX.hisi.video.decoder.avc]
06-27 15:59:12.405 23889-23889/com.example.ridsys_001.AsterTest E/EventLogger: audioTrackUnderrun [397.28, 137.09, window=2, period=2, 44100, 250, 612]]

**Comment by robindanielk** [comment] 2018-06-28 02:53
"[OMX.hisi.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648"
The above line always appears before the Audio Underrun is triggered..Kindly help me with a workaround!

**Comment by andrewlewis** [comment] 2018-06-28 08:26
The storeMetaDataInBuffers log line from the media framework is almost certainly unrelated; I've seen this on other devices, and it's indicative of an internal error but there is fallback logic so it doesn't actually cause any failure.

For the codec crash issue, I think this is either a problem with the media (we'd need the stream to verify that), or it could be a bug in this device's decoder (in which case you should report this to the manufacturer, but they'll likely need steps to reproduce it themselves).

I'm not convinced the audio underrun is related to the crash, and I'm not sure how to interpret "i took a log of the server from which those media sources are available and found that the time when the audiounderrun occurs , there seems to no log of the server at that specific time". At a guess, it's possible that a call to the codec is taking a very long time to return which causes the audio track to underrun. You could test that hypothesis using systrace with app tracing enabled. Or the player may just be starved of audio data from the server. I don't think we can investigate either case with the information provided here, though, so you'll need to debug this yourself.

I'm going to close this issue for now as I don't think there's anything else to suggest. If you can provide evidence that there's an ExoPlayer bug or if you can suggest workarounds for these devices I'll reopen it.

**Closed as completed by andrewlewis** 2018-06-28 08:26 UTC
Labels: need more info

**Comment by andrewlewis** [comment] 2018-06-28 08:29
One other thing you might want to try as an experiment: you could try returning false from `MediaCodecUtil.isCodecUsableDecoder` for the codec named "OMX.hisi.video.decoder.avc". This may result in fallback to a working software decoder which doesn't exhibit the same issues. If this works, that suggests that the codec is broken and you should report this to the device manufacturer.

**Comment by robindanielk** [comment] 2018-07-03 12:50
Hi , i tried the returning false for the codec and the player stuttered and crashed. And also i noted this behaviour of log before the app crashes and i am not able to catch the uncaught exception...Any guesses!!

Noticed AudioUndertrack and releasingBuffers() and finally crashed!
[1.txt](https://github.com/google/ExoPlayer/files/2159342/1.txt)
