### ISSUE TITLE
Radio stream stopped immediately when connection is lost

### ISSUE THREAD

**Issue by vicpinm** [google/ExoPlayer#3367] opened 2017-10-18 10:13 UTC
Hi, I'm using exoplayer 2.5.3. I want to increase the buffer size for radios, because when connection is lost, radio stops playing immediately. So I have increased the buffer, and now the radio spend more time to start, which is normal. But I don't understand why, when I activate airplane mode, the playback keeps stopping immediately. Shouldn't it keep playing for a few seconds at least? Is there something I'm missing?

My current implementation:

     private static final int DEFAULT_MIN_BUFFER_MS = 50000;
     private static final int DEFAULT_MAX_BUFFER_MS = 100000;
     private static final int DEFAULT_BUFFER_FOR_PLAYBACK_MS = 30000;

    DefaultLoadControl loadControl = new DefaultLoadControl(new DefaultAllocator(true, 
    C.DEFAULT_BUFFER_SEGMENT_SIZE),DEFAULT_MIN_BUFFER_MS, DEFAULT_MAX_BUFFER_MS, 
     DEFAULT_BUFFER_FOR_PLAYBACK_MS, DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS);

**Comment by ojw28** [comment] 2017-10-18 10:21
Duplicate of https://github.com/google/ExoPlayer/issues/1606

**Closed as completed by ojw28** 2017-10-18 10:21 UTC
Labels: duplicate
