### ISSUE TITLE
Fails to build locally using AS 3.1

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#4047] opened 2018-03-27 21:24 UTC
Sync/Build of project with local exoplayer built from sources fails due `javadoc_library.gradle`

Build tools:
```
classpath 'com.android.tools.build:gradle:3.1.0'

buildToolsVersion = '27.0.3'

compileSdkVersion = 27
minSdkVersion = 21
targetSdkVersion = 23

distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
```

Root cause of exception (whole callstack is really huge):
```
Caused by: org.gradle.api.InvalidUserCodeException: Cannot create variant 'android-lint' after configuration ':exoplayer-library-core:debugRuntimeElements' has been resolved
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationPublications$ConfigurationVariantFactory.create(DefaultConfigurationPublications.java:158)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationPublications$ConfigurationVariantFactory.create(DefaultConfigurationPublications.java:151)
	at org.gradle.api.internal.FactoryNamedDomainObjectContainer.doCreate(FactoryNamedDomainObjectContainer.java:100)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:67)
	at com.android.build.gradle.internal.scope.VariantScopeImpl.lambda$publishArtifactToConfiguration$2(VariantScopeImpl.java:378)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationPublications.variants(DefaultConfigurationPublications.java:139)
	at com.android.build.gradle.internal.scope.VariantScopeImpl.publishArtifactToConfiguration(VariantScopeImpl.java:376)
	at com.android.build.gradle.internal.scope.VariantScopeImpl.publishIntermediateArtifact(VariantScopeImpl.java:347)
	at com.android.build.gradle.internal.scope.VariantScopeImpl.addTaskOutput(VariantScopeImpl.java:298)
	at com.android.build.gradle.internal.TaskManager.configureGlobalLintTask(TaskManager.java:536)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:771)
	at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:650)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
```

problem is in `javadoc_library.gradle` with
```
classpath = files(variant.javaCompile.classpath.files,
	                  project.android.getBootClasspath())
```
Commenting whole task of this lines fixes problem

**Comment by ojw28** [comment] 2018-03-27 22:31
Duplicate of https://github.com/google/ExoPlayer/issues/3708

**Closed as completed by ojw28** 2018-03-27 22:31 UTC
Labels: duplicate
