### ISSUE TITLE
Dash + DRM live/vod stream fails to load on some devices : MediaCodecVideoRenderer error

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#8037] opened 2020-10-02 20:49 UTC
### [REQUIRED] Searched documentation and issues
Random media coded playback error

### [REQUIRED] Question
I have few DRM live streams. On some devices it works, on other it started giving following error(everything was fine before until 2-3 days ago). Not sure what it means. It is only appearing on physical devices, emulators are just fine.

Is it something to do with streams? 
Can you help me figure out this issue?

Devices : Pixel 3a with OS 11, Samsung galaxy s20 OS 10,  Samsung galaxy s20+ OS 10

### A full bug report captured from the device
```java
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984): Playback error
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video=2499968, null, null, video/avc, avc1.4D401F, 2499968, null, [1280, 720, 29.97003], [-1, -1]), format_supported=YES
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at android.os.Handler.dispatchMessage(Handler.java:103)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at android.os.Looper.loop(Looper.java:237)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at android.os.HandlerThread.run(HandlerThread.java:67)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):   Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2699)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:75)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1394)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:842)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
10-02 20:36:22.252 E/ExoPlayerImplInternal(26984):       ... 3 more
```

### Link to test content
Not needed at the moment

**Comment by tonihei** [comment] 2020-10-06 17:21
Could you please capture a full bugreport from the device and upload it here or send to `dev.exoplayer@gmail.com` with `Issue #8037` in the subject line? 

Assigning to @jt64 for further investigation. Is there a known set of issues that would result in this error?

**Comment by nishantkp** [comment] 2020-10-15 15:57
@tonihei @jt64  I have sent a full bug report on `dev.exoplayer@gmail.com`

**Comment by nishantkp** [comment] 2020-10-20 16:12
@jt64 any updates for this one?

**Comment by nishantkp** [comment] 2020-10-26 17:46
@jt64 @tonihei any updates?

**Comment by nishantkp** [comment] 2020-11-24 14:48
@jt64 @tonihei any updates?

**Comment by nishantkp** [comment] 2021-01-06 17:32
@tonihei Its been quite a while, do you have any updates on this one?

**Comment by rossinho2001** [comment] 2021-01-07 20:55
I hve also observed this error on an Samsung S20+ on Android 11 with the demo Exo-player. On this specific device - the issue was not occurring on Android 10 - only observed after update to 11. Happening frequently now for no reason I can fathom.

**Comment by jt64** [comment] 2021-03-10 00:32
Thank you for the bugreport and apologies for the delayed response. 

The bugreport indicates this error is coming from Samsung's DRM module:
10-14 14:55:15.035 E/wv_dash ( 5875): Trustlet did not send a valid return code: 24576
10-14 14:55:15.035 E/wv_dash ( 5875): process drm decrypt CENC failed. 6000 
10-14 14:55:15.035 E/wv_dash ( 5875): process drm decrypt CENC failed [d]
10-14 14:55:15.035 E/WVCdm   ( 5875): Decrypt error result in session sid3 during encrypted block: 178

We will need to open an internal bug to follow up with Samsung to understand why this error is occurring.

Can you confirm that the device has not been unlocked/rooted?

**Comment by nishantkp** [comment] 2021-03-10 16:09
Hi @jt64,

Thank you so much for picking this up. No Devices are not rooted/unlocked.

**Comment by rrfrias** [comment] 2021-03-11 22:56
Thanks for that information. We are following up with Samsung. If it is possible to share an app+test stream, can you please send instructions to dev.exoplayer@gmail.com

Internal ref: 182506753

**Comment by rrfrias** [comment] 2021-03-16 01:28
@nishantkp , we would like your permission to share the bugreport with Samsung. Can you please let us know?

I assume these devices are not connected to an external display. Also an app+test stream will be helpful, if possible.

**Comment by nishantkp** [comment] 2021-03-19 17:24
Hi, @rrfrias Yes, you can share bug reports with Samsung. Meanwhile, I will work on getting the test app + stream. 

Devices are not connected to an external display.

**Comment by nishantkp** [comment] 2021-03-19 19:11
@rrfrias I have sent an email for app + test content.

ExoPlayer version used is 2.13.2 (build is from release-v2 branch).

**Comment by saurabh-wynk** [comment] 2021-03-22 03:43
We have also started facing a similar issue on Samsung Note 20 Ultra.

CryptoException --> MediaCodecVideoRenderer error, index=0, format=Format(p0va0br250000, null, null, video/avc, avc1.42c015, 250000, null, [426, 240, 25.0], [-1, -1]), format_supported=YES

**Comment by rrfrias** [comment] 2021-03-22 08:24
@nishantkp Thanks! I have shared the app, test content and logcat with Samsung. Will let you know what they find.

@saurabh-wynk Can you send a bugreport or logcat to dev.exoplayer@gmail.com and let us know if we have your permission to share it with Samsung?

**Comment by saurabh-wynk** [comment] 2021-03-22 15:32
> @nishantkp Thanks! I have shared the app, test content and logcat with Samsung. Will let you know what they find.
> 
> @saurabh-wynk Can you send a bugreport or logcat to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) and let us know if we have your permission to share it with Samsung?

@rrfrias This error has been reported by the prod user and we have captured this log from our analytics pipeline, so currently we don't have the entire stack trace. Once it gets reproduced internally, or we have any detailed logs, I will share that with you.

**Comment by saurabh-wynk** [comment] 2021-03-28 17:11
> @nishantkp Thanks! I have shared the app, test content and logcat with Samsung. Will let you know what they find.
> 
> @saurabh-wynk Can you send a bugreport or logcat to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) and let us know if we have your permission to share it with Samsung?

@rrfrias i have shared the details on mail.

**Comment by nishantkp** [comment] 2021-03-29 20:29
hi @rrfrias any updates from Samsung?

**Comment by rrfrias** [comment] 2021-03-31 08:24
@nishantkp The internal tracker was incorrectly assigned. I have corrected that. I also built the apk and to speed Samsung's investigation.

@saurabh-wynk you shared a stack trace. There is not enough information to be useful. Is it possible to get a logcat or bugreport?

**Comment by saurabh-wynk** [comment] 2021-04-04 14:17
> @nishantkp The internal tracker was incorrectly assigned. I have corrected that. I also built the apk and to speed Samsung's investigation.
> 
> @saurabh-wynk you shared a stack trace. There is not enough information to be useful. Is it possible to get a logcat or bugreport?

@rrfrias As I mentioned earlier, this issue has been captured from production users' analytics events, while we have not been able to reproduce it internally. Hence we do not have any logcat or bug report. Will share other details, as soon as I get any.
 
But from the events, it appears that issue is intermittent. Since I am seeing some play events also for that user.

**Comment by rrfrias** [comment] 2021-04-13 08:43
@nishantkp, both Samsung and i ran into failures due to an invalid license response from the license service. This prevents us from investigating furthur. Can you check and share an apk?

**Comment by soutua** [comment] 2021-04-13 12:50
We are also seeing something similar on Pixel 4a with Android 11 when playing live streams with DASH + Widevine DRM:

`I/CCodecBufferChannel: [c2.qti.avc.decoder.secure#906] decrypt failed: result=-2147483648
W/MediaCodec: Log queueSecureInputBuffer error: -2147483648
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video=4499968, null, null, video/avc, avc1.640020, 4499968, null, [1280, 720, 50.0], [-1, -1]), format_supported=YES`

The error does not occur straight away, it's usually within 2-20 minutes of playback. Also the same streams with Android 10 devices work correctly and also Chromecast works correctly. We have also gotten feedback from at least one user that when he updated his two OnePlus 7 phones from Android 10 to 11, the live streams stopped working, so might be the same issue in those devices also. I don't currently have a test stream that I could share since these are production DRM streams I'm testing with, I need to see if we could make a test stream available, but I would assume that possibly all DASH+Widevine live streams might behave similarly?

Edit: Also for further information, DASH+Widevine non-live, e.g. VOD streams work correctly with the same device.

**Comment by nishantkp** [comment] 2021-04-13 13:07
@rrfrias can you try VPN to Canada?

**Comment by nishantkp** [comment] 2021-04-19 16:08
@rrfrias were you able to fix a valid DRM license after VPNing to Canada?

**Comment by rrfrias** [comment] 2021-04-20 23:17
I tried using a VPN and setting my location to Toronto. I am still seeing an invalid license response from the license service. Can you check and share an apk with  dev.exoplayer@gmail.com?

**Comment by nishantkp** [comment] 2021-04-21 14:17
@rrfrias, I have tried on my end with the previous file, and I wasn't able to get an invalid license response.

Sent you an email with a different media file.

**Comment by nishantkp** [comment] 2021-04-28 17:28
@rrfrias were you able to verify it with the new build?

**Comment by nishantkp** [comment] 2021-05-12 19:08
@rrfrias any updates?

**Comment by rrfrias** [comment] 2021-05-19 09:03
The media file helped. I was able to playback using when VPNing to Canada. I have shared the apk with Samsung to investigate. Will let you know when we hear back.

I also tested using a Galaxy S10+ (Build: QP1A.190711.020) and was unable to reproduce. When you see the problem does it always happen? Does it happen at the beginning of playback or do you have to play for a while?

@soutua I missed your comment earlier. If you are able to reproduce, can you share a bugreport with  dev.exoplayer@gmail.com. Mention "Issue #8037" in the subject.

**Comment by nishantkp** [comment] 2021-05-19 13:56
@rrfrias no playback at all, it happens just at the beginning.

**Comment by rrfrias** [comment] 2021-05-20 08:15
Thanks. Can you quantify the reproducibility rate (7 out of 10 etc)?

**Comment by nishantkp** [comment] 2021-05-20 13:52
Hi @rrfrias,

I checked on the following devices and the reproduction rate is 100% (10/10)
- Samsung Galaxy S21 (os11)
- Samsung Galaxy S21+ (os11)
- Samsung Galaxy S21 ultra (os10)
- Samsung Galaxy S20 ultra (os10)
- Samsung Galaxy S20+ (os10)
- Samsung Galaxy A51 (os10)
- Samsung Galaxy Note20 ultra (os10)
- Samsung Galaxy Note20 (os10)

Initially, I thought it is related to OS but a weird thing is...it works on Samsung Galaxy A11 (os10).
When I open this ticket, I saw similar issue on Pixel 3a with OS 11, but now it is resolved (not sure what fixed it).

**Comment by rrfrias** [comment] 2021-05-21 00:31
Thank you. That is very helpful. Samsung is taking a look.

**Comment by nishantkp** [comment] 2021-05-21 00:34
Thanks a bunch @rrfrias

**Comment by nishantkp** [comment] 2021-06-16 19:29
Hi @rrfrias,
any updates from Samsung on this codec issue?

**Comment by rrfrias** [comment] 2021-06-16 21:36
Samsung is having some problems reproducing this issue. I just sent them additional instructions and logs yesterday. Will see if that helps.

**Comment by rrfrias** [comment] 2021-07-14 00:14
@nishantkp, is there anyway to have a non-geo restricted service deliver the license? Samsung has tried both paid and free VPN services from South Korea and India and run into the same "failed to parse" key response errors. They think their VPN is correctly configured as other services recommend Canada relevant content.

**Comment by nishantkp** [comment] 2021-07-19 14:37
@rrfrias currently we do not have a non-geo restricted service to deliver a DRM license.

**Comment by rrfrias** [comment] 2021-09-08 01:58
@nishantkp can you try to repro and capture a dumpstate. I have tried on a number of Samsung devices S21 (android 11) and S20 but not been able to reproduce. Samsung unable to reproduce either (seeing failure that indicates that their VPN is not configured for Canada). Share the dumpstate log with dev.exoplayer@gmail.com and github# in the subject. Thanks!

Steps :
0. Reproduce the issue.
1. Dial *#9900#
2. Select first option i.e. "Run dumpstate/logcat/modem log"
3. Once 2nd step is over than select "Copy to sdcard (include CP Ramdump)" option.
4. Now from device open myfiles and share folder with "log" name.

**Closed as completed** 2021-10-07 01:04 UTC
Labels: bug: in platform drm, closed-by-bot
