### ISSUE TITLE
Exoplayer showing wrong duration of some local videos

### ISSUE THREAD

**Issue by Suleiman-Ahmad** [google/ExoPlayer#9593] opened 2021-10-22 20:19 UTC
I've been using Exoplayer to play short local videos gotten from querying the media store, but I tried playing videos with durations longer than one hour and I encountered the following issues:-
- showing wrong duration of video e.g shows 91:58:54 instead of 1:52:58.
- dragging the timebar makes the screen goes dark
I've search websites and forums like stackoverflow.com for answers to this but I couldn't find anything useful

This is the code I use to play the video
`// Build the media item.
MediaItem mediaItem = MediaItem.fromUri(video.getPath);
// Set the media item to be played.
player.setMediaItem(mediaItem);
// Prepare the player.
player.prepare();
// Start the playback.
player.play();`

**Comment by tonihei** [comment] 2021-10-22 21:08
Could you please provide the media file here and via email to dev.exoplayer@gmail.com with subject "Issue #9593"?Otherwise it's almost impossible to help you further.

**Comment by Suleiman-Ahmad** [comment] 2021-10-22 21:56
![IMG_20211022_112854](https://user-images.githubusercontent.com/92982478/138527247-d178785e-88b7-480f-aa1c-cd4fa09749aa.jpg)

Here's an image sample for the error.

**Comment by Suleiman-Ahmad** [comment] 2021-10-25 23:00
Hello, here's one of the local video files that's showing wrong duration if
the duration is more than one hour. Please fix this issue, it seems unique
for playing mediastore videos.

Reproduction steps...
Save on local storage
Query mediastore to obtain video path
Play with Exoplayer by using mediaitem created from file path
  wrong duration video.zip
<https://drive.google.com/file/d/1CtChZmS1XwQrXwC5sBEdNGoKhcz9qRrM/view?usp=drivesdk>

**Comment by Suleiman-Ahmad** [comment] 2021-10-25 23:07
I've submitted the video above. Please, go through it.

**Comment by Suleiman-Ahmad** [comment] 2021-10-29 05:59
I told you guys I'm stuck but I still don't know why you're ignoring me. Please tell me something.

**Comment by ojw28** [comment] 2021-10-29 07:48
We will look at your issue when we have time to do so. Until then, please stop spamming the issue tracker. Thanks.

**Comment by ojw28** [comment] 2021-10-29 12:58
You have not shared the video with `dev.exoplayer@gmail.com`. Please do so so that we can access it.

**Comment by Suleiman-Ahmad** [comment] 2021-10-30 06:24
The file wasn't public but now it is. Play it locally and you'll see the issue

**Comment by ojw28** [comment] 2021-11-01 12:19
The file contains incorrect track durations. In particular, it claims the video track is 22 hours long, and that the audio tracks are each 44 hours long. You can also see this incorrect information if you load the video you've provided into `https://gpac.github.io/mp4box.js/test/filereader.html`:

![Screenshot 2021-11-01 at 12 16 57](https://user-images.githubusercontent.com/7881572/139670224-c738cc37-caeb-4000-af21-9ec406d7e457.png)

ExoPlayer is simply displaying the largest of these durations, and it's not doing anything incorrect by doing this. Closing as "bad media", since the file itself is where the problem lies.

**Closed as completed by ojw28** 2021-11-01 12:19 UTC
Labels: bad media

**Comment by Suleiman-Ahmad** [comment] 2021-11-02 08:15
Okay, Sir. But it plays correctly in other video players and displays the correct duration.
And querying it's Mediastore.Video.Duration also returns the correct duration milliseconds.
And Sir, I have this issue this more  60% of video files I played and they all work correctly in other video players.

**Comment by Suleiman-Ahmad** [comment] 2021-11-02 08:17
Is there anything I can do to fix this?

**Comment by ojw28** [comment] 2021-11-02 09:21
> Okay, Sir. But it plays correctly in other video players and displays the correct duration.

There are a couple of different ways in which a player can choose to calculate the duration from an MP4 file. ExoPlayer derives the duration from the `mvhd` box in the MP4 file, which appears to have an incorrect `timescale` attribute in the video provided. This means that the `duration` attribute isn't scaled to the correct value.

If another player implementation derives the duration from a different box within the MP4 file that does not contain incorrect data, then it may show the correct duration. Note however that in some other case where the data that this player relies on is set incorrectly, this other player may show an incorrect duration whilst ExoPlayer may show a correct duration. My point is that one approach is not more or less correct than another. Ultimately the MP4 file needs to be created to contain correct data in all of its boxes, if it's to be broadly compatible with a wide range of players.

> Is there anything I can do to fix this?

Anyone who is playing this content from a legitimate source will not have the issue (or be using your app, most likely). Users who are playing pirated content are generally going to get a worse experience because the files being played are less likely to have been produced correctly, as is the case here. For obvious reasons, we're not going to be going out of our way to support this specific case.

> I have this issue this more 60% of video files I played

We've not seen any significant volume of this kind of issue being reported for the past 6+ years, so it's clearly not the case that this issue affects 60% of videos being played across the ecosystem. Most likely all of these files are coming from the same pirate source, and most likely whoever is producing these files is not doing so quite correctly.

**Comment by Suleiman-Ahmad** [comment] 2021-11-02 15:03
Okay, I understand, Sir. But why does it's Mediastore.Video.Duration return the correct duration of video file?

is there a way to set the duration like player.setDuration() method or something similar?

NB: I also experience this issue with videos I recorded with my camera that are over an hour long.

**Comment by ojw28** [comment] 2021-11-02 15:17
It probably looks at a different part of the file. it's pretty much the same as what I've already written above:

> If another player implementation derives the duration from a different box within the MP4 file that does not contain incorrect data, then it may show the correct duration. Note however that in some other case where the data that this player relies on is set incorrectly, this other player may show an incorrect duration whilst ExoPlayer may show a correct duration. My point is that one approach is not more or less correct than another. Ultimately the MP4 file needs to be created to contain correct data in all of its boxes, if it's to be broadly compatible with a wide range of players.

We're not going to spend any additional time on this issue, or on #9637 which is basically the same thing. If you're playing pirated content that hasn't been encoded properly, that's not our problem to solve.

If you have a legitimate video recorded with a camera that has a similar problem, please file a separate issue about that. It's not clear that the root cause is the same.

**Comment by Suleiman-Ahmad** [comment] 2021-11-04 05:29
Okay. Thank you.
