### ISSUE TITLE
Memory leak with ExoPlayer2 (r2.0.2)

### ISSUE THREAD

**Issue by gbhall** [google/ExoPlayer#1943] opened 2016-10-13 21:55 UTC
I've been using ExoPlayer r1.5.6 but upgraded a week ago to r2.0.2 to try and fix a crash I occasionally get due to using several instances at once (another issue).

I currently use ExoPlayer in a FragmentStatePagerAdapter with a few instances running, and when a user swipes between pages local mp4's on the device they play/pause.   

I use my own TextureView due to aspect ratio issues that I've already discussed here with @ojw28.

Since upgrading to ExoPlayer2, I've noticed a memory leak that I've spent several days to solve, and have no idea where to go from now. 

Before I open my activity with the ViewPager, I'm using around 30MB. 
This is me swiping through my ViewPager:
![mem ok](https://cloud.githubusercontent.com/assets/1142713/19367588/7304a82e-91ce-11e6-8e39-802012a82964.PNG)
This is after I've exited, and initiated GC (memory returns to baseline). 
![mem ok sweep](https://cloud.githubusercontent.com/assets/1142713/19367591/78e4e16e-91ce-11e6-80bc-72ad667b4790.PNG)

This is after upgrading to r2.0.2 and swiping through my ViewPager:
![mem bad](https://cloud.githubusercontent.com/assets/1142713/19367596/7cdc61ac-91ce-11e6-967f-88be7493f2a1.PNG)
After I exit my activity and initiate GC (memory remains at +20MB)
![mem bad sweep](https://cloud.githubusercontent.com/assets/1142713/19367606/817699e4-91ce-11e6-8c1d-50234ba41a74.PNG)

The problem is each time I enter, swipe around 10 times, and exit, my baseline memory grows by 20MB and stays there even after initiating GC. Enter and exit a few times and my app crashes with a MemoryException. 

I've tried everything I can think of to free this memory. I made everything global so I can try and remove any references in `onDestroyView`:

``` java
        if (mVideoTextureView != null) {
            mVideoTextureView.setSurfaceTextureListener(null);
            mVideoTextureView = null;
        }
        mVideoSurfaceTextureListener = null;
        mOnGlobalLayoutListener = null;
        mViewCreated = null;
        mActivity = null;
        mBus.unregister(this);
        releasePlayer();
        mExoPlayerSurface = null;
        mVideoTextureView = null;
        mVideoSurfaceTextureListener = null;
        mRenderers = null;
        mExoPlayerHandler = null;
        if (mTrackSelector != null) {
            mTrackSelector.removeListener(mTrackSelectorEventListener);
        }
        mTrackSelector = null;
        mMediaDataSourceFactory = null;
        mMediaSource = null;
        mLoopingMediaSource = null;
        mTrackSelectorEventListener = null;
        mExoPlayerEventListener = null;
        mExoPlayerMessage = null;
        mMediaCodecVideoRenderer = null;
        mAudioRenderer = null;
        mExtractorsFactory = null;
        mDefaultLoadControl = null;
```

My releasePlayer function looks like this:

``` java
    private void releasePlayer() {
        // Release mExoPlayer and record mExoPlayerPosition
        Log.i(TAG, "releasePlayer() called");

        if (mExoPlayer != null) {
            if (mExoPlayer.getPlayWhenReady() && mExoPlayer.getPlaybackState() != ExoPlayer.STATE_IDLE) {
                mExoPlayerPosition = mExoPlayer.getCurrentPosition();
            }
            mExoPlayer.prepare(null);
            mExoPlayer.removeListener(mExoPlayerEventListener);
            mExoPlayer.stop();
            mExoPlayer.release();
            mExoPlayer = null;
        }
    }
```

Here is how I set things up:

``` java
    // ---------------------------------------------------------------------------------------------
    // Video
    // ---------------------------------------------------------------------------------------------
    private void setupExoPlayer() {
        Log.d(TAG, "setupExoPlayer() called with: " + "");

        mExoPlayerHandler = new Handler();
        mMediaDataSourceFactory = new DefaultDataSourceFactory(XXXApplication.getInstance(),
                BANDWIDTH_METER,
                new DefaultHttpDataSourceFactory(Util.getUserAgent(XXXApplication.getInstance(), XXXApplication.class.getSimpleName()), BANDWIDTH_METER));

        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(BANDWIDTH_METER);
        mTrackSelector = new DefaultTrackSelector(mExoPlayerHandler, videoTrackSelectionFactory);
        mTrackSelectorEventListener = new TrackSelector.EventListener<MappingTrackSelector.MappedTrackInfo>() {
            @Override
            public void onTrackSelectionsChanged(TrackSelections<? extends MappingTrackSelector.MappedTrackInfo> trackSelections) {
                Log.d(TAG, "onTrackSelectionsChanged() called with: trackSelections = [" + trackSelections + "]");
            }
        };
        mTrackSelector.addListener(mTrackSelectorEventListener);

        ArrayList<Renderer> renderersList = new ArrayList<>();
        mMediaCodecVideoRenderer = new MediaCodecVideoRenderer(getContext(),
                MediaCodecSelector.DEFAULT, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
        renderersList.add(mMediaCodecVideoRenderer);
        mAudioRenderer = new MediaCodecAudioRenderer(MediaCodecSelector.DEFAULT);
        renderersList.add(mAudioRenderer);

        mRenderers = renderersList.toArray(new Renderer[renderersList.size()]);
        renderersList.clear();
        mDefaultLoadControl = new DefaultLoadControl();
        mExoPlayer = ExoPlayerFactory.newInstance(mRenderers, mTrackSelector, mDefaultLoadControl);

        mExoPlayerEventListener = new ExoPlayer.EventListener() {
            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                Log.d(TAG, "onPlayerStateChanged() called with: " + "playWhenReady = [" + playWhenReady + "], playbackState = [" + playbackState + "]");
            }

            @Override
            public void onPositionDiscontinuity() {
                Log.v(TAG, "onPositionDiscontinuity() called");
            }

            @Override
            public void onTimelineChanged(Timeline timeline, Object manifest) {
                Log.v(TAG, "onTimelineChanged() called with: timeline = [" + timeline + "], manifest = [" + manifest + "]");
            }

            @Override
            public void onLoadingChanged(boolean isLoading) {
                Log.v(TAG, "onLoadingChanged() called with: isLoading = [" + isLoading + "]");
            }

            @Override
            public void onPlayerError(ExoPlaybackException error) {
                Log.e(TAG, "onPlayerError() called with: " + "error = [" + error + "]");
                String errorString = null;
                if (error.type == ExoPlaybackException.TYPE_RENDERER) {
                    Exception cause = error.getRendererException();
                    if (cause instanceof MediaCodecRenderer.DecoderInitializationException) {
                        MediaCodecRenderer.DecoderInitializationException decoderInitializationException =
                                (MediaCodecRenderer.DecoderInitializationException) cause;
                        if (decoderInitializationException.decoderName == null) {
                            if (decoderInitializationException.getCause() instanceof MediaCodecUtil.DecoderQueryException) {
                                errorString = getString(R.string.error_querying_decoders);
                            } else if (decoderInitializationException.secureDecoderRequired) {
                                errorString = getString(R.string.error_no_secure_decoder,
                                        decoderInitializationException.mimeType);
                            } else {
                                errorString = getString(R.string.error_no_decoder,
                                        decoderInitializationException.mimeType);
                            }
                        } else {
                            errorString = getString(R.string.error_instantiating_decoder,
                                    decoderInitializationException.decoderName);
                        }
                    }
                }
                if (errorString == null) {
                    errorString = "Could not play back video due to an unknown error.";
                }
                EventBus.getDefault().post(new MessageEvent("Playback error: " + errorString));
                Log.e(TAG, "onPlayerError: cause:" + errorString);
            }
        };

        mExoPlayer.addListener(mExoPlayerEventListener);
    }

    // Called in onResume
    private void initiateNewVideo() {
        Log.d(TAG, "initiateNewVideo() called with: " + "");
        Log.d(TAG, "initiateNewVideo: mExoPlayerPosition=" + mExoPlayerPosition);
        Log.d(TAG, "initiateNewVideo: mContentUri=" + mContentUri);
        if (mExoPlayer != null) {
            // Reset mExoPlayer
            mExoPlayer.stop();
            mExoPlayer.seekTo(mExoPlayerPosition);

            // Play video
            if (mContentUri != null) {
                playNewVideo(mContentUri);
            }
        } else {
            EventBus.getDefault().post(new MessageEvent("Playback error: can't initiate video, player not ready"));
        }
    }

    private void playNewVideo(Uri contentUri) {
        if (mExoPlayer != null && mRenderers != null && mMediaDataSourceFactory != null
                && mExoPlayerHandler != null && mExoPlayerSurface != null) {
            mExtractorsFactory = new DefaultExtractorsFactory();
            mMediaSource = new ExtractorMediaSource(contentUri, mMediaDataSourceFactory, mExtractorsFactory, mExoPlayerHandler, null);
            mExoPlayerMessage = new ExoPlayer.ExoPlayerMessage(mRenderers[0], C.MSG_SET_SURFACE, mExoPlayerSurface);
            //mLoopingMediaSource = new LoopingMediaSource(mMediaSource);
            mExoPlayer.prepare(mMediaSource);
            mExoPlayer.sendMessages(mExoPlayerMessage);
            mExoPlayer.setPlayWhenReady(mIsFragmentVisible); 
        } else {
            EventBus.getDefault().post(new MessageEvent("Playback error: null check constraint"));
        }
    }
```

I've tried the last version before ExoPlayer2, r1.5.11, and that works perfectly too with 0 memory leak. 

If I can't resolve this, I'm going to have to revert back to r1.5.11 which will be a massive bummer. 

If there anyway to fix this memory leak in r2+? Thanks.

**Comment by ojw28** [comment] 2016-10-13 23:06
If you're using `PlaybackControlView` then you may well be running into https://github.com/google/ExoPlayer/issues/1908, which is fixed in `dev-v2` and will be in the next release.

Either way, it should be possible for you to analyze the leak yourself to at least diagnose the problem. Android Studio provides tools to allow you to find out what the leak is and what the chain of references is that leaks it. Specifically, once the leak has occurred:
1. Trigger a few GCs to make sure everything is GC'd that can be.
2. Dump the Java heap (purple icon with the downward arrow on the screenshots you've provided above)
3. Look at it ;). Specifically, look at the number of instances of classes for which you know there should be some known number (often 0). A good example is SimpleExoPlayer, which you would probably expect there to be 0 of after you've exited the activity in which playback occurs. If there are unexpected instances, you can select each one in turn, and look at the reference tree to work out the chain of references to a GC root that's stopping it from being GC'd. That's your leak.

**Comment by gbhall** [comment] 2016-10-13 23:59
I'm just adding this quickly in the hopes you are still at work and will have a look (it's 7.55am here so your feedback would be valuable else I have to wait for your tomorrow).

I trigger GC multiple times. I'm not using PlaybackControlView as far as I can see since I use my own TextureView's surface to render video on, and I am not using SimpleExoPlayer, just ExoPlayer. 

I have looked at the memory dumps, but am not get much insight.

Can you see anything suss as a quick look from this?
Before:
![before](https://cloud.githubusercontent.com/assets/1142713/19371223/11695d06-91e4-11e6-8228-24278bc738be.PNG)

After exiting the activity and cleaning up and initiating GC multiple times:
![after](https://cloud.githubusercontent.com/assets/1142713/19371224/14d14a6c-91e4-11e6-947c-1db5a57c7249.PNG)

Thanks Olly.

**Comment by gbhall** [comment] 2016-10-14 02:47
I've just emailed a simple demo that has the memory leak. 

These were my results:
1. Launch MainActivity. Note allocated mem is 18MB
2. Click LAUNCH PLAYER. 
3. Swipe from one end all the way to the opposite end 5 times. 
   Note: I did this really fast and didn't even bother waiting for the video to show/load. Sometimes you get a crash from the ViewPager, try again.
4. Click back. Initiate GC multiple times. Allocated mem is 50+MB
5. Repeat 2-4 for a 2nd time. Initiate GC. Allocated mem is 90+MB

**Comment by ojw28** [comment] 2016-10-14 10:05
I was able to reproduce. I didn't spend any time debugging, but did try using `dev-v2` tip-of-tree, and the issue is no longer present. So it looks like whatever the leak was, it's fixed. We'll be pushing a new release early next week.

**Closed as completed by ojw28** 2016-10-14 10:05 UTC
Labels: bug

**Comment by gbhall** [comment] 2016-10-14 16:31
I can confirm using the latest `dev-v2` resolved the memory leak. Thank you so much Olly for testing the demo app I sent you guys. It's a huge relief for me now. 

Thanks again, and I hope you enjoy your weekend.  Cheers.
