### ISSUE TITLE
Please provide support for MTS and M2TS video formats

### ISSUE THREAD

**Issue by NanyangTaiji** [google/ExoPlayer#8823] opened 2021-04-18 10:00 UTC
Since 2016, the issue is already raised in #1488, just wonder why it is still not solved. This type files are common for all professional video recorders, they are handled by VLC and other players. Several requests had been made and the issues are always closed for not enough information. If you need the video clips example, please download from:
https://filesamples.com/formats/mts

**Comment by ojw28** [comment] 2021-04-18 10:13
Closing as a duplicate of #1488 (please don't file duplicate issues when you know there is an existing open issue already tracking the same thing). The issue is marked as low priority. You are welcome to make a high quality pull request that adds support, if this is important to you.

**Closed as completed by ojw28** 2021-04-18 10:13 UTC
Labels: duplicate
