### ISSUE TITLE
Playback stuck buffering and not loading

### ISSUE THREAD

**Issue by idokit365** [google/ExoPlayer#8170] opened 2020-11-06 01:02 UTC
### [REQUIRED] Issue description
1. Load a large video(6GB more or less) and seek several times, then exoplayer trigger error.
2. It should not trigger error on seeking.

### [REQUIRED] Reproduction steps
1. Load a large video(6GB more or less) and seek several times, then exoplayer trigger error.
2. The issue happends on demo app and my own demo app.
3. My own demo code refer the attachment "*.java".

### [REQUIRED] Link to test content
1.  The video is a local large video, its size is 6GB more or less.
2.  Refer to the attachement "*.mp4".

### [REQUIRED] A full bug report captured from the device
1. Refer to the attachment "*.log".

### [REQUIRED] Version of ExoPlayer being used
1. The version is 2.12.0 and 2.12.1 has same issue.

### [REQUIRED] Device(s) and version(s) of Android being used
1. The issue happend seems to not matter android or device version.
2. My device info: vivo s5, android 9; and honor v10, android 10; and honor 8xMax, android 8.1

**Comment by idokit365** [comment] 2020-11-06 01:35
[GlMergeVideoView_SourceCode.zip](https://github.com/google/ExoPlayer/files/5498289/GlMergeVideoView_SourceCode.zip)

The log is from exoplayer demo app: https://github.com/google/ExoPlayer/tree/release-v2/demos,
and the issue is same to my code producted.

[bugreport-PD1932-PKQ1.181030.001-2020-11-06-09-31-06.zip](https://github.com/google/ExoPlayer/files/5498371/bugreport-PD1932-PKQ1.181030.001-2020-11-06-09-31-06.zip)

The issue happend at time : 2020-11-06 09:30:23.727

The video is large, so download from the cloud disk: 
Link：https://pan.baidu.com/s/1FwfqVHLq_fCZW60x8CvYHA 
Password：rl1b

**Comment by lcf87** [comment] 2020-11-06 02:53
Could you upload the file to a easier accessible web drive, say Google Drive, iCould, oneDrive or Dropbox, I'm getting KB speed from your link.

**Comment by idokit365** [comment] 2020-11-06 04:01
@lcf87 Hi, the video has saved to google drive: https://drive.google.com/file/d/19A-XKZ2U83e-oBRIBFy5VaZ6j6iUM1tV/view?usp=sharing

**Comment by idokit365** [comment] 2020-11-09 06:11
The issue can be reproducted ?

**Comment by lcf87** [comment] 2020-11-10 15:42
Yes I can reproduce on my end, assigning to Toni to take a look.

**Comment by tonihei** [comment] 2020-11-10 16:29
The error is thrown because your playback would be stuck in a buffering state otherwise. So throwing an exception is better because you can fail fast instead of getting stuck forever.

The reason why you are stuck is that your video track has a large gap. There are 4.7 hours of audio without video samples in the middle of your file (between timestamps `6914062844` and `23958259744` (in microseconds)). So if you seek within this range, the player waits until it has enough audio and video data to start playback. But in order to get enough video data, it needs to load all 4.7 hours of audio into memory first before it even reaches the first video sample. This is the point where the player gets stuck as it has an upper memory limit of around ~130MB by default.

**Comment by idokit365** [comment] 2020-11-11 01:35
@tonihei 
Thanks for the reply!
But the issue can not be avoid because of videos is not be controlled by me and I dont know the video has a large gap or not. 
So can the methods below resolved this issue :
1. enlarge memory limit;
2. mute it before seeking;
3. or any other method.

**Comment by tonihei** [comment] 2020-11-11 09:56
Yes, you could try both to solve the problem, but if you don't control the media and thus don't know what kind of problem it may have, it will be hard to choose the right approach I guess.

The upper memory limit can be set in `DefaultLoadControl.Builder.setTargetBufferBytes` or you can disable the memory check for as long as the buffered duration is less than the minimum by setting `DefaultLoadControl.Builder.setPrioritizeTimeOverSizeThresholds(true)`. 

To disable video playback, you need to disable the renderer in the `DefaultTrackSelector.Parameters`.

**Comment by tonihei** [comment] 2020-12-17 16:48
Closing because the question was answered.

**Closed as completed by tonihei** 2020-12-17 16:48 UTC
Labels: bad media, wont fix: intended behavior
