### ISSUE TITLE
Another phone with the OMX.SEC.mp3.dec bug: SM-G386T

### ISSUE THREAD

**Issue by DonnKey** [google/ExoPlayer#5280] opened 2018-12-19 17:06 UTC
### Issue description
The bug with not finishing/repeating a file because of a bug in the OMX.SEC.mp3.dec codec repeats with the SM-G386T phone. Another instance of https://github.com/google/ExoPlayer/issues/4519.

### Reproduction steps
Play (some) files with any app when playing an audiobook consisting of multiple files; only the first file plays. Hardware dependent (of course).

### Link to test content
http://etc.usf.edu/lit2go/1/alices-adventures-in-wonderland/
or (same content)
http://freeclassicaudiobooks.com/audiobooks/Alice/mp3/

You'll need at least chapters 1 and 2.

I've seen this on other audiobooks as well. I don't have a big enough sample to be sure, but "older" recordings look suspicious.

### Version of ExoPlayer being used
dev-v2 (and obviously anything earlier) pulled 12/18/18 around 7PM PST.

### Device(s) and version(s) of Android being used
SM-G386T Android 4.2.2 (highest available for that phone).

### A full bug report captured from the device
Not worth the trouble, since the obvious one-line fix of adding that phone to the list of blacklisted phones near line 325 of MediaCodecUtil.java fixes the problem for my phone.

Some additional notes.

The list of phones with the problem is getting long. Here's some additional info that may help fixing the "real" bug.
1) Replacing chapter 1 with a (very short) snippet of the same file created by Audacity (simply Export a trimmed version) causes it to behave correctly. (I can try with a full-legth Audacity copy if you would like.)
2) The phone's marketing name is Samsung Galaxy Avant, which was sold at Costco for a while, so it's probably fairly common (if old).
3) I haven't seen this line mentioned as being emitted in the debugger just as the failed file handoff should occur:
     E/AudioTrack: Discontinuity detected [expected 631954259, got 0]
In my repro both the behavior and the above line are solid (100% of the time). (And the one-line change takes it to "never fail").
4) My guess is that the "T" in the phone model number means "T-Mobile". A truncated string compare to pick up other carrier's versions might be wise.

Since I have the hardware (at least currently - it needs to be handed off soon) I can try a few things if that would help.

**Comment by ojw28** [comment] 2018-12-19 18:30
Closing this as a duplicate of the original issue, which I've re-opened. We'll add SM-G386T to the blacklist, and adjust the blacklist to also cover variants of the listed devices. I'm not sure if "T" does stand for "T-Mobile", but it is true that there are other SM-G386X variants (for different values of X), and that they probably all have the same issue. Similar rules likely apply for the other listed devices too.

**Closed as completed by ojw28** 2018-12-19 18:30 UTC
Labels: duplicate

**Comment by DonnKey** [comment] 2018-12-19 20:17
Thanks Oliver. That'll be fine. Any guesses as to when a release will be
made with this family of changes in it?

Now that I have your contact info: your page
https://medium.com/google-exoplayer/howto-2-depend-on-a-local-checkout-of-exoplayer-bcd7f8531720
is close to right but I think the ground has changed a bit underneath it.
Definitely gradle is complaining about using "compile" rather than
"implementation". I'm not experienced enough with Android Studio to be sure
I did it right, but I think there may need to be another step in getting
exoplayer integrated with the project; the change to settings.gradle
doesn't seem to be quite enough -- I needed to do something with importing
to get it to work (and whether it's as you intended isn't clear to me)...
there your experience would dominate. Oh, and the default version of gradle
that's requested doesn't work. gradle-wrapper.properties asks for gradle
4.4, which along with a number of other versions of gradle exhibits this
problem: https://github.com/novoda/bintray-release/issues/177. Gradle
4.10.3 (the last before gradle 5) works fine, and probably others as well.
(I avoided gradle 5 just to avoid any compatibility problems a new major
version number might create.)

Donn

**Comment by ojw28** [comment] 2018-12-19 20:55
I think it's generally pretty well understood that blog posts are written once and are accurate at the time of writing. We need to get better documentation elsewhere for things like this, which we should keep up to date, but I don't think we're ever going to be going back and updating blog posts in any significant way.
