### ISSUE TITLE
403 Error due to spaces in url below android 7 version

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#7197] opened 2020-04-06 15:20 UTC
##  com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403

in lower versions

## API 23, 22, 21

sample video url:
711bd0166e2c/dash/6e8252ab-18de-4499-a90c-ed568fb2f4d6-1.2 problems on limits(1).mpd

**Comment by AquilesCanta** [comment] 2020-04-06 23:12
Seems to me this is a duplicate of existing issues like #727, and #5983.

**Closed as completed by AquilesCanta** 2020-04-06 23:12 UTC
Labels: duplicate, bad media

**Comment by gokulkalagara** [comment] 2020-04-07 12:28
How we can change ' ' spaces in the manifest file content of MPD download in exoplayer?

or segments of mpd

**Comment by ojw28** [comment] 2020-04-07 20:48
Note that spaces in URLs are a violation of the DASH specification, at least for segment URLs and any other URLs present within the manifest. See [this comment](https://github.com/google/ExoPlayer/issues/6638#issuecomment-557230206) for details. In summary, if you *must* use spaces, they should already be encoded as %20 in the manifest to be specification compliant. However, a better solution is just to not use spaces in URLs at all. Use dashes (`-`) instead. So the correct thing to do here is to fix the media.

If you want a client side workaround, then you can use ExoPlayer's OkHttp extension rather than `DefaultHttpDataSource`, which will probably play the content despite the spaces.

**Comment by gokulkalagara** [comment] 2020-04-08 05:16
Tq
