### ISSUE TITLE
Encrypted DASH playback fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sandersaares** [google/ExoPlayer#835] opened 2015-10-02 11:36 UTC
I have here an encrypted video that fails to play back with ExoPlayer 1.4.1.

Video URL: http://media.axprod.net/ExoPlayer/Multisdk/Encrypted/manifest.mpd
Widevine license server URL: http://axpr-wv-fe.cloudapp.net:8080/LicensingService

An exception occurs during video loading and playback does not start. GitHub is not allowing me to attach the log file, so I uploaded it here: http://pastebin.com/g8JJpg8m

What is special about this video? It does not use a `senc` box to store the sample encryption information. Rather, it packs the data into the `mdat` box. An equivalent video with the `senc` box works fine with ExoPlayer. We do not wish to use the `senc` box because another Google player does not support it (yet) and we want to have the same video compatible with multiple players. Possibly ExoPlayer is having issues parsing the sample encryption information due to this?

The failure occurred with ExoPlayer 1.4.1. Testing with 1.5.0 is planned for next week - I will update with results for that version once available.

**Comment by ojw28** [comment] 2015-10-02 11:50
Hi. A couple of quick questions:

- Can you link to the working stream as well? It'll be good to have for comparison purposes.
- What are the other player(s) that you're targeting, and what's the time-frame for them supporting the `senc` box?

**Comment by sandersaares** [comment] 2015-10-02 12:31
I will attempt to provide the working video, as well. The working video is an intermediate step in our processing workflow and I appear to have already deleted the intermediate files for this particular video. I will generate a new set and amend the issue once it's available.

The other player we are targeting is one of those NDA don't-talk-about-it players. If you drop me a mail at saares@axinom.com, we can cover that part in a private conversation.

**Comment by ojw28** [comment] 2015-10-02 13:16
On reflection, the working stream probably isn't necessary. We do support encryption data being packed into the `mdat` box, but it looks like FragmentedMp4Extractor isn't liking what you're putting there.

Could you describe exactly what you're putting in the `mdat` box? The extractor expects the encryption data followed by the sample data, with nothing else in the box. It looks like encryption data is expected to be in the following format.

For each sample:
  Vector (for your stream it looks like we expect 8 byte vectors)
  Subsample count (2 byte unsigned int)
  For each subsample:
    Clear length (2 byte unsigned int)
    Encrypted length (4 byte unsigned int)

For your stream, the extractor is parsing a huge value as the subsample count for the first sample, which is the root cause of the subsequent index out of bounds failure, so we need to figure out why that's the case. Questions:

* Is there any chance your packing other data into the `mdat` box in addition to the encryption and sample data?
* The extractor thinks you're using 8 byte vectors. Is that correct?
* Does the format of the encryption data match the above?

Thanks!

**Comment by sandersaares** [comment] 2015-10-02 13:23
Yes, there are indeed 8 bytes of dummy data between the encryption data and the samples in the `mdat` box, namely the string "hackhack". This is where the `mdat` header previously used to be - we just overwrite it with dummy data as part of our modification process.

These 8 bytes should be ignored, as the offset of the samples (relative to the start of the `moof` box) is indicated by the data offset field in the `trun` box, which points to the correct location.

Off the top of my head, the format of the encryption data appears to match what we use.

**Comment by ojw28** [comment] 2015-10-02 13:28
I think there are 8 bytes of data before the encryption data as well (I'm not sure what they are; sample values are 0,0,0,2,0,0,0,-69). Is that intentional? We don't support extra stuff in the `mdat` box currently, so you'll probably need to change your modification process to actually remove it.

**Comment by sandersaares** [comment] 2015-10-02 13:32
That is unexpected but I can confirm that we are both seeing the same thing here. I will investigate. It is curious that the other player works fine in this scenario. Will get back to you on this next week.

**Comment by sandersaares** [comment] 2015-10-02 14:40
I can confirm that after removing all the extra data - both from the beginning of the mdat and between the encryption data and samples - we have successful playback on ExoPlayer.

Taking the big picture view, this seems like a spec violation by ExoPlayer - it should not assume anything about `mdat` structure, as the specifications intend it to be just an arbitrary data container for whatever, with the offsets in `trun` and `saio` boxes giving the offsets of the sample and encryption data, respectively.

**Comment by ojw28** [comment] 2015-10-02 15:14
Yes. As a more general point, I do think the spec is overly broad (as far as I can remember, it allows for things like putting the encryption data after the sample data, or putting sample data at a position that would be very inconvenient in practice). So whilst we'd like to support skipping of non-encryption and non-sample data in mdat boxes, I think we'll continue to assume that the ordering and approximate positioning of this data is "sensible". I've filed: https://github.com/google/ExoPlayer/issues/837 to track, and so will close this.

**Closed by ojw28** 2015-10-02 15:14 UTC
Labels: question
