### ISSUE TITLE
Getting Unable to connect to License server error while playback

### ISSUE THREAD

**Issue by khushank9** [google/ExoPlayer#8365] opened 2020-12-17 13:40 UTC
**Problem Statement:**
While playback of Widevine encypted content which has a renewal policy attached by the widevine license server, Exoplayer throws "Unable to Connect to License server Error"

Reproduction Steps:

- Use the Exoplayer sample App and insert the URL's in the media.exolist.json file.
- Playback the content
- Since the License associated with the content is a renewable license which is valid for 60s, the license will be renewed by the player after every 60s
- Notice that after some renewal calls the license give throws the following exception:
2020-12-15 22:51:39.116 12893-12893/com.google.android.exoplayer2.demo E/EventLogger: internalError [181.72, 180.05, window=0, period=0, drmSessionManagerError]
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to license server<License URL not provided due to security reasons Please check attached logs for more information>

- Though after 15 seconds of retry, the subsequent calls to the license server are successful.
- This issue happens again after some more license calls.

- Notice that when license renewal is done the drm keys are successfully loaded after every 60s 
```
	Line 451: 12-17 18:39:21.026 14572 14572 D EventLogger: drmKeysLoaded [0.89, 0.00, window=0, period=0]
	Line 915: 12-17 18:40:21.386 14572 14572 D EventLogger: drmKeysLoaded [61.25, 60.04, window=0, period=0]
	Line 1153: 12-17 18:41:20.413 14572 14572 D EventLogger: drmKeysLoaded [120.28, 119.07, window=0, period=0]
	Line 1584: 12-17 18:42:35.823 14572 14572 D EventLogger: drmKeysLoaded [195.69, 194.48, window=0, period=0]
	Line 1871: 12-17 18:43:35.753 14572 14572 D EventLogger: drmKeysLoaded [255.62, 254.41, window=0, period=0]
	Line 2311: 12-17 18:44:51.201 14572 14572 D EventLogger: drmKeysLoaded [331.07, 329.86, window=0, period=0]
	Line 2998: 12-17 18:45:51.167 14572 14572 D EventLogger: drmKeysLoaded [391.03, 389.80, window=0, period=0]
```
- Following are the adb logs when issue occurs

```
12-17 18:44:35.752 14572 14572 E EventLogger: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to license server<License URL not provided due to security reasons Please check attached logs for more information>
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:203)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:128)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:160)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:135)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:503)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at android.os.Looper.loop(Looper.java:214)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-17 18:44:35.752 14572 14572 E EventLogger: Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@99e5aaf2
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:200)
12-17 18:44:35.752 14572 14572 E EventLogger: 	... 10 more
12-17 18:44:35.752 14572 14572 E EventLogger: Caused by: java.io.EOFException: \n not found: size=0 content=...
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
12-17 18:44:35.752 14572 14572 E EventLogger: 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
```

Expectation:
We want to know whether the Exoplayer is timing out the license server calls after certain timeout, because the license server is up and running that's why many of the calls are successful.

1. The logs mentioned above are clearly visible in logcat when using  Exoplayer Version : 2.8.2 
2. These logs are not visible for Exoplayer version 2.11.1 , but we are able to see the charles logs that the Exoplayer is unable to connect to license server<License URL not provided due to security reasons Please check attached logs for more information>

-
[bugreport-OnePlus6T-QKQ1.190716.003-2020-12-17-18-47-09.zip](https://github.com/google/ExoPlayer/files/5709804/bugreport-OnePlus6T-QKQ1.190716.003-2020-12-17-18-47-09.zip)
[License_Issue_AdbLogs.txt](https://github.com/google/ExoPlayer/files/5709805/License_Issue_AdbLogs.txt)

- ExoPlayer version number : 2.8.2,2.11.1
- Android version: 10
- Android device OnePlus 6T

**Comment by icbaker** [comment] 2020-12-17 15:19
The DRM license URL seems to return 403 for me - maybe it's geo-blocked?

Can you please provide a URL that will allow me to try and reproduce the problem.

```
2020-12-17 15:17:03.631 12585-12585/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=6.37, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:585)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:523)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:518)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:481)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:57)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:194)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:598)
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:341)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:81)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:75)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:171)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:177)
```

**Comment by khushank9** [comment] 2020-12-17 16:30
Thanks @icbaker for checking the issue.
Can you please let me know which country you are trying to reproduce the issue so that i can make relevant settings  in the server.

**Comment by icbaker** [comment] 2020-12-17 17:14
Please make them available to the US and UK.

**Comment by khushank9** [comment] 2020-12-17 22:49
@icbaker requested country is added, can you please check the playback now.

**Comment by icbaker** [comment] 2020-12-21 10:44
Still getting 403s from the license server.

**Comment by khushank9** [comment] 2021-01-11 13:35
@icbaker Apologies for replying late, Can you please check now if you are able to playback the content. We have added the countries and removed the proxy detection too for this content.

**Comment by icbaker** [comment] 2021-01-11 17:17
Thanks for unblocking the content - I can play it.

I tried it at 2.8.2, 2.11.1 and dev-v2 (latest). At 2.8.2 I see the exception as you've posted in the original comment above. I also see a very similar exception at dev-v2 (the URL has been removed: https://github.com/google/ExoPlayer/commit/429bdfb974c67279137543b78aa333c483460c70).

At 2.11.1 there's no DRM event logging. This is because DRM event logging was broken in 2.11.0 and not fixed until 2.12.0: https://github.com/google/ExoPlayer/issues/6765.

In all cases the content kept playing despite the exceptions being logged. (I did see playback fail once on 2.11.1, that was due to a 500 response when trying to load the media itself [1]). 

Do you see a problem in playback when this happens? Or are you just asking about why the logging isn't present in 2.11.1?

> Expectation:
We want to know whether the Exoplayer is timing out the license server calls after certain timeout, because the license server is up and running that's why many of the calls are successful.

The exception doesn't look like a timeout to me, it looks like the server has responded with an empty response that doesn't terminate in a newline (which afaict is against the HTTP spec), and the Android network stack/OkHttp is choking on that:
```
Caused by: java.io.EOFException: \n not found: size=0 content=...
```

[1]
```
2021-01-11 17:02:17.178 3705-3705/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=562.77, mediaPos=559.88, window=0, period=0]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:487)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:288)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:118)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by khushank9** [comment] 2021-01-12 10:34
@icbaker I have sent charles logs to debug the issue further to <dev.exoplayer@gmail.com>

As per your comments :

> The exception doesn't look like a timeout to me, it looks like the server has responded with an empty response that doesn't terminate in a newline (which afaict is against the HTTP spec), and the Android network stack/OkHttp is choking on that:

Caused by: java.io.EOFException: \n not found: size=0 content=...

We couldn't see in the charles logs that the server responded with an empty response. Can you please help in understanding this further. Do you suspect that Keep-Alive connection is causing the client to disconnect with the license server.

**Comment by icbaker** [comment] 2021-01-12 18:01
Thanks for the Charles logs, it looks like there are 2 requests where Charles says:
> Remote server closed the connection before sending response header

This seems to match exactly with the stack trace from Android.

Closing because this seems more like a license server/network issue than an ExoPlayer issue.

**Closed as completed by icbaker** 2021-01-12 18:01 UTC
Labels: question
