### ISSUE TITLE
Documentation Site Is Down

### ISSUE THREAD

**Issue by ajcatarina** [google/ExoPlayer#8853] opened 2021-04-22 03:18 UTC
Hi, just checked today. Looks like your documentation site is down.

![image](https://user-images.githubusercontent.com/19162599/115650689-4b440600-a35c-11eb-9872-e7fb558f1dbe.png)

**Comment by mazabin** [comment] 2021-04-22 06:14
Duplicate of #8837

**Closed as completed** 2021-04-22 10:11 UTC
