### ISSUE TITLE
Sony Bravia 4k TV(5.1.1) Wrong Resolution Displayed when using DefaultHlsTrackSelector

### ISSUE THREAD

**Issue by JonWatson** [google/ExoPlayer#1881] opened 2016-09-30 19:15 UTC
We have an HLS playlist with up to 720p formats.  When using the DefaultHlsTrackSelector, I can see that it ramps up as expected from a low resolution to 720p.  I can see this by stepping through the selection process(VideoFormatSelectorUtil) and also in onDownstreamFormatChanged.  However, the TextureView is displaying a much lower resolution and looks like it's 240p or something very low.  

If we use a custom HlsTrackSelector that selects only the 720p bitrate, the video displays as expected on the TextureView.

Our HLS Stream is not the problem as the stream displays correctly on the Demo app.  And the BipBop Apple stream exhibits the same "low-res" problem when we load it in our app.

Any ideas where I should look or what might be the problem here?   We don't see this problem on FireTV's, FireSticks, NexusPlayer, Shield TV or any Mobile devices which all share the same player code.

**Comment by AquilesCanta** [comment] 2016-09-30 19:52
What are the chances of moving to version 2, where DefaultHlsTrackSelector does not exist? We are backporting bugfixes to v1. This is going to get more attention if you manage to reproduce it in v2. Please, give it a try and let me know.

**Comment by JonWatson** [comment] 2016-09-30 22:07
Seems like this is related to TextureView.  I switched to SurfaceView and the problem went away.  Unfortunately, that's not a solution for us.

**Comment by ojw28** [comment] 2016-10-03 12:04
I'm unsure about this (it sounds pretty strange). Why is SurfaceView not a solution for you? It generally gives better performance and smoother frame release.

**Comment by AquilesCanta** [comment] 2016-10-18 13:56
Any news about this? I cannot reproduce on a Sony Bravia TV.

**Comment by ojw28** [comment] 2017-01-13 17:14
Closing due to inactivity.

**Closed as completed** 2017-01-13 17:14 UTC
Labels: question
