### ISSUE TITLE
Jcenter will be shutdown on May 1st, can you migrate to mavenCentral?

### ISSUE THREAD

**Issue by apkelly** [google/ExoPlayer#8544] opened 2021-02-04 05:35 UTC
As per this article - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Jcenter will be shutdown on May 1st 2021, can you please publish the exoplayer artefacts to mavenCentral()

Thanks.

**Comment by andrewlewis** [comment] 2021-02-04 10:02
We're looking into migrating to GMaven (#5246).

**Comment by andrewlewis** [comment] 2021-02-04 10:02
Duplicate of #5246

**Closed as completed by andrewlewis** 2021-02-04 10:02 UTC
Labels: duplicate
