### ISSUE TITLE
StackOverflowError - CacheDataSource

### ISSUE THREAD

**Issue by Khang-NT** [google/ExoPlayer#5242] opened 2018-12-11 10:16 UTC
### Issue description
```
Fatal Exception: java.lang.StackOverflowError: stack size 1038KB
       at java.lang.reflect.Method.invoke(Method.java)
       at java.io.File.SystemProperties_getBoolean(File.java:487)
       at java.io.File.initDbgInfo(File.java:238)
       at java.io.File.delete(File.java:1340)
       at com.google.android.exoplayer2.upstream.cache.SimpleCache.commitFile(SourceFile:289)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSink.closeCurrentOutputStream(SourceFile:212)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSink.close(SourceFile:167)
       at com.google.android.exoplayer2.upstream.TeeDataSource.close(SourceFile:99)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.closeCurrentSource(SourceFile:549)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:340)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
       at com.google.android.exoplayer2.upstream.StatsDataSource.read(SourceFile:91)
       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(SourceFile:260)
       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(SourceFile:135)
       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(SourceFile:116)
       at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.peekEndOfStreamOrHeader(SourceFile:345)
       at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readSample(SourceFile:226)
       at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(SourceFile:218)
       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(SourceFile:902)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(SourceFile:381)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

### Reproduction steps
It happen sometime, my app is using `CacheDataSource`. Can't reproduce.

### Link to test content
Not available.

### Version of ExoPlayer being used
`2.9.2`

### Device(s) and version(s) of Android being used
Android 8. OnePlus

**Comment by ojw28** [comment] 2018-12-11 11:33
I'm guessing the printout of the stack removes a lot of duplicated lines that match
```
at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(SourceFile:342)
```
else the stack clearly isn't big enough to cause overflow? If so, we should fix this by making `read` non-recursive.

**Comment by ojw28** [comment] 2018-12-11 16:16
Actually, I can't really see how this happens. It looks like there's a repeated cache miss. Each time we try to request the data from the upstream source, and immediately read `RESULT_END_OF_INPUT`. However we think we know that more data should be available. This is unexpected.

What is the upstream `DataSource` in this case? Is it something other than `DefaultHttpDataSource` and/or is there any customization in the `DataSource` chain or the caching layer?

**Comment by Khang-NT** [comment] 2018-12-17 12:25
This is how I create cache data source
```kotlin
fun cacheDataSource(
        appContext: Context,
        preferenceStore: PreferenceStore,
        defaultDataSourceFactory: DefaultDataSourceFactory
): DataSource.Factory {
    val mediaCacheDir = File(appContext.cacheDir, MEDIA_CACHE_FOLDER)
    val maxCacheSize = preferenceStore.maxCacheSize
    if (maxCacheSize <= 0) {
        return defaultDataSourceFactory
    }

    val simpleCache = SimpleCache(mediaCacheDir,
            LeastRecentlyUsedCacheEvictor(Math.max(maxCacheSize, MIN_MEDIA_CACHE_SIZE_MB) * MB))
    return CacheDataSourceFactory(
            simpleCache,
            defaultDataSourceFactory,
            CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR,
            CacheDataSource.DEFAULT_MAX_CACHE_FILE_SIZE,
            object : CacheDataSource.EventListener {
                override fun onCachedBytesRead(cacheSizeBytes: Long, cachedBytesRead: Long) {
                    if (BuildConfig.DEBUG) {
                        Timber.d("onCachedBytesRead(%d, %d)", cacheSizeBytes, cachedBytesRead)
                    }
                }

                override fun onCacheIgnored(reason: Int) {
                    if (BuildConfig.DEBUG) {
                        Timber.d("onCacheIgnored(%d)", reason)
                    }
                }
            }
    )
}
```
I did one thing wrong. That's using `CacheDataSource` when create media source to play a local file `file://`.
I thought `CacheDataSource` only cache remote stream scheme like `http`, but it also cache `file`.
Now I'm using `DefaultDataSource` for local file, seem to be fine.

**Comment by ojw28** [comment] 2018-12-17 13:43
Playing a local file through `CacheDataSource` will indeed add the content to the cache, but it shouldn't cause a failure like the one being described here. Can you provide a piece of sample media that can reproduce the issue?

**Comment by ojw28** [comment] 2019-03-06 09:23
Closing due to lack of further information, and lack of other reports of this issue.

**Closed as completed by ojw28** 2019-03-06 09:23 UTC
Labels: need more info
