### ISSUE TITLE
Video and Audio get out of sync

### ISSUE THREAD

**Issue by SimonNumberTwo** [google/ExoPlayer#4798] opened 2018-09-10 12:20 UTC
### Issue description
We use the ExoPlayer with the ConcatenatingMediaSource to play several videos and while playing them the audio gets more and more out of sync. 

### Reproduction steps
I created a playlist in the ExoPlayer demo app and let it play. After a short time, the audio is out of sync with the video. I noticed after a short time, the audio is even one word ahead of the video which is really noticable. 

### Link to test content
Just add the following snippet into the `media.exolist.json` and play it.

```
{
    "name": "Test",
    "samples": [
      {
        "name": "Demo",
        "playlist": [
          {
            "uri": "...b4b3b055-ec67-42fa-8b8a-ba72c8a43161.mp4"
          },
          {
            "uri": "...e09efadd-ac5e-4532-ae8d-39a82a2554c6.mp4"
          },
          {
            "uri": "...aad2c8d5-3eef-4d0a-bfc0-605b4f087d3e.mp4"
          },
          {
            "uri": "...f6d37b36-4562-453c-9b9c-34f84b7a5f67.mp4"
          },
          {
            "uri": "...b97d158b-8376-490b-818a-113c8fc0d8b3.mp4"
          },
          {
            "uri": "...0da8afc2-6cf1-429c-ada8-ffe4cb0e488d.mp4"
          },
          {
            "uri": "...aaf713e3-322e-4b55-aca4-dd5149e83f7a.mp4"
          },
          {
            "uri": "...97c8dfb9-7273-4f7a-a884-9904c0eb287f.mp4"
          },
          {
            "uri": "...ea75e621-3ee4-4caa-a025-fa5b41057f50.mp4"
          },
          {
            "uri": "...bd6a884f-d24c-4bfa-a76d-1eb8adc99a9b.mp4"
          },
          {
            "uri": "...81d97d5b-3bd9-4f17-95a1-7e6d16dd25af.mp4"
          },
          {
            "uri": "...e02391ca-4372-4a5e-aeb3-f3568f7ba725.mp4"
          },
          {
            "uri": "...6a84494c-cc9c-4a9c-b3e4-f9ae43f60650.mp4"
          },
          {
            "uri": "...789d8e45-bc81-4033-b8c9-0d4b79e69c2a.mp4"
          },
          {
            "uri": "...673dea6f-bbf4-49ef-bdae-e50ec8f3f799.mp4"
          },
          {
            "uri": "...2e308387-6a51-4e57-be3f-a3fc82cd55a6.mp4"
          },
          {
            "uri": "...e79df479-e0e9-407c-abe7-5170b988150d.mp4"
          },
          {
            "uri": "...0b11f852-23c9-4f0d-90af-7deda848962d.mp4"
          },
          {
            "uri": "...4b5d25ac-d4fd-4c34-ac70-8e5a687ebadd.mp4"
          },
          {
            "uri": "...c881415f-74d7-44d4-bbe9-d82b37cc8a98.mp4"
          },
          {
            "uri": "...6a84494c-cc9c-4a9c-b3e4-f9ae43f60650.mp4"
          },
          {
            "uri": "...a6859216-66c5-4170-b72a-9a997269a601.mp4"
          },
          {
            "uri": "...ab9cc13e-b329-4b3a-82a8-b062c694d808.mp4"
          },
          {
            "uri": "...fefd8ffe-7ea2-4e56-8123-66ccac9ec791.mp4"
          },
          {
            "uri": "...97c8dfb9-7273-4f7a-a884-9904c0eb287f.mp4"
          },
          {
            "uri": "...67eaccc6-715f-4b22-af7e-d66e279f2094.mp4"
          },
          {
            "uri": "...9300ddd1-b388-4bca-9fa6-4c2a8abc74b5.mp4"
          },
          {
            "uri": "...c881415f-74d7-44d4-bbe9-d82b37cc8a98.mp4"
          },
          {
            "uri": "...97c8dfb9-7273-4f7a-a884-9904c0eb287f.mp4"
          },
          {
            "uri": "...130e3aa1-9cd4-4bab-be21-f95ec0ce0a01.mp4"
          },
          {
            "uri": "...0945a8c0-bb22-44e5-8287-6f6ed36e2474.mp4"
          },
          {
            "uri": "...6af7e385-731f-442c-bca1-1a99337ca3b9.mp4"
          }
        ]
      }
    ]
  }
```

### Version of ExoPlayer being used
I tested this with ExoPlayer 2.8.1 and 2.8.4 ad even the dev-v2 branch.

### Device(s) and version(s) of Android being used
Personally tested on a Samsung Galaxy S7 Edge, Samsung SM-G955F, Lenovo TB-X304L and HUAWEI BAH-W09.

### A full bug report captured from the device
Only thing I noticed were the following lines but I don`t know if it has something to do with it but these log lines occur after every video that has been shown and before the new one will be shown.

```
2018-09-10 13:37:07.486 895-895/com.google.android.exoplayer2.demo D/EventLogger: loading [317.39, 15.33, window=15, period=15, false]
2018-09-10 13:37:08.025 895-895/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodReleased [317.93, 15.87, window=15, period=15]
2018-09-10 13:37:08.041 895-895/com.google.android.exoplayer2.demo D/EventLogger: positionDiscontinuity [317.95, 0.01, window=16, period=16, PERIOD_TRANSITION]
2018-09-10 13:37:08.047 895-895/com.google.android.exoplayer2.demo D/EventLogger: tracksChanged [317.95, 0.03, window=16, period=16, 
2018-09-10 13:37:08.047 895-895/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:0 [
2018-09-10 13:37:08.048 895-895/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2018-09-10 13:37:08.048 895-895/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, res=1920x1080, supported=YES
2018-09-10 13:37:08.048 895-895/com.google.android.exoplayer2.demo D/EventLogger:     ]
2018-09-10 13:37:08.048 895-895/com.google.android.exoplayer2.demo D/EventLogger:   ]
2018-09-10 13:37:08.048 895-895/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:1 [
2018-09-10 13:37:08.048 895-895/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2018-09-10 13:37:08.049 895-895/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=eng, supported=YES
2018-09-10 13:37:08.049 895-895/com.google.android.exoplayer2.demo D/EventLogger:     ]
2018-09-10 13:37:08.049 895-895/com.google.android.exoplayer2.demo D/EventLogger:     Metadata [
2018-09-10 13:37:08.050 895-895/com.google.android.exoplayer2.demo D/EventLogger:       TSSE: value=Lavf57.83.100
2018-09-10 13:37:08.050 895-895/com.google.android.exoplayer2.demo D/EventLogger:     ]
2018-09-10 13:37:08.050 895-895/com.google.android.exoplayer2.demo D/EventLogger:   ]
2018-09-10 13:37:08.050 895-895/com.google.android.exoplayer2.demo D/EventLogger: ]
2018-09-10 13:37:13.347 895-895/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodReadingStarted [323.25, 5.32, window=17, period=17]
2018-09-10 13:37:13.348 895-895/com.google.android.exoplayer2.demo D/EventLogger: decoderInputFormatChanged [323.25, 5.34, window=17, period=17, video, id=1, mimeType=video/avc, res=1920x1080]
2018-09-10 13:37:13.350 895-895/com.google.android.exoplayer2.demo D/EventLogger: downstreamFormatChanged [323.25, 5.34, window=17, period=17, id=1, mimeType=video/avc, res=1920x1080]
2018-09-10 13:37:13.356 895-895/com.google.android.exoplayer2.demo D/EventLogger: decoderInputFormatChanged [323.26, 5.34, window=17, period=17, audio, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=eng]
2018-09-10 13:37:13.373 895-5100/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Executing->Idle
2018-09-10 13:37:13.378 895-5100/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Idle->Loaded
2018-09-10 13:37:13.379 895-5100/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Loaded
2018-09-10 13:37:13.379 895-5100/com.google.android.exoplayer2.demo I/ACodec:  [OMX.google.aac.decoder] Now kWhatShutdownCompleted event : 8594
2018-09-10 13:37:13.382 895-5100/com.google.android.exoplayer2.demo I/ACodec:  [OMX.google.aac.decoder] Now uninitialized
2018-09-10 13:37:13.382 895-5100/com.google.android.exoplayer2.demo I/ACodec:  [] Now kWhatShutdownCompleted event : 8594
2018-09-10 13:37:13.383 895-5100/com.google.android.exoplayer2.demo I/MediaCodec: Codec shutdown complete
2018-09-10 13:37:13.388 895-4681/com.google.android.exoplayer2.demo I/ACodec:  [] Now uninitialized
2018-09-10 13:37:13.391 895-5107/com.google.android.exoplayer2.demo I/ACodec: [] onAllocateComponent
2018-09-10 13:37:13.394 895-5107/com.google.android.exoplayer2.demo I/OMXClient: Treble IOmx obtained
2018-09-10 13:37:13.403 895-5107/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Loaded
2018-09-10 13:37:13.408 895-5107/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -2147483648)
2018-09-10 13:37:13.409 895-5107/com.google.android.exoplayer2.demo I/ACodec: codec does not support config operating rate (err -2147483648)
2018-09-10 13:37:13.413 895-5107/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Loaded->Idle
2018-09-10 13:37:13.434 895-5107/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Idle->Executing
2018-09-10 13:37:13.436 895-5107/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Executing
2018-09-10 13:37:13.438 895-895/com.google.android.exoplayer2.demo D/EventLogger: decoderInitialized [323.34, 5.36, window=17, period=17, audio, OMX.google.aac.decoder]
2018-09-10 13:37:13.440 895-895/com.google.android.exoplayer2.demo D/EventLogger: downstreamFormatChanged [323.34, 5.36, window=17, period=17, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=eng]
2018-09-10 13:37:13.446 895-5107/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now handling output port settings change
2018-09-10 13:37:13.461 895-5107/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Executing
```

**Comment by tonihei** [comment] 2018-09-10 12:55
This is a duplicate of #4559 and the issue be suppressed by setting the FLAG_WORKAROUND_IGNORE_EDIT_LISTS flag.

**Closed as completed by tonihei** 2018-09-10 12:55 UTC
Labels: duplicate

**Comment by SimonNumberTwo** [comment] 2018-09-10 19:04
Hey @tonihei thank you very much for your quick response. We finally were able to solve this issue. 

Big thank you 👍 Keep the good work going :-)
