### ISSUE TITLE
InflateException: Error inflating class StyledPlayerView

### ISSUE THREAD

**Issue by Luosoha** [google/ExoPlayer#10617] opened 2022-09-14 02:00 UTC
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Samsung Galaxy J6+ Android 10
Samsung Galaxy A02 Android 11
Samsung Galaxy S22 Ultra Android 12
Redmi 7A Android 9
Redmi Note 9 Android 10

### Reproducible in the demo app?

Not tested

### Reproduction steps

I can't reproduce the issue yet. This issue is reported in my app's crashlytics.

```
<FrameLayout
        android:id="@+id/content_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white">

        <com.google.android.exoplayer2.ui.StyledPlayerView
            android:id="@+id/player_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:resize_mode="zoom"
            app:shutter_background_color="@color/white"
            app:surface_type="texture_view"
            app:use_controller="false" />
</FrameLayout>
```

This is pretty much my layout where the crash happens.
Based on the logs I linked below, I believe it has something to do with the ImageButton of StyledPlayerView can't be inflated.

### Expected result

Not crash.

### Actual result

App crashed.

### Media

![image](https://user-images.githubusercontent.com/20939211/190041320-e6978de8-f6cb-45d3-a4f3-c1c72d63b5a1.png)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment] 2022-09-14 16:15
Duplicate of #10409

**Closed as not planned** 2022-09-14 16:16 UTC
Labels: duplicate
