### ISSUE TITLE
Ways to tune adaptive switching for HLS?

### ISSUE THREAD

**Issue by DavidMihola** [google/ExoPlayer#2477] opened 2017-02-20 12:52 UTC
After migrating our app from ExoPlayer 1 to ExoPlayer 2 it seems that the adaptive switching behavior when playing HLS streams is slightly different now. Particularly, it seems that switching up to a better stream quality now takes noticably longer that before. (Did ExoPlayer 1 switch up mid-chunk when possible?)

Are there any ways to influence the adaptive switching behavior for HLS streams in ExoPlayer 2?

**Comment by AquilesCanta** [comment] 2017-02-20 15:10
> Did ExoPlayer 1 switch up mid-chunk when possible?

Yes, but that aspect has not changed. That is, neither version can cancel a chunk download to start downloading a different variant, though we might do something about this in the future.  

> takes noticably longer that before

Something that might be worth checking is whether your streams contain multiple audio renditions. Ideally, please send a stream that reproduces the longer preparation time to dev.exoplayer@gmail.com, so I can run a few experiments. If you want to run some yourself, metrics will be welcome. 

> Are there any ways to influence the adaptive switching behavior for HLS streams in ExoPlayer 2?

To customize this, you can inject your own TrackSelection.Factory in the DefaultTrackSelector. There is useful information about this in #676 and related issues. Finally, the `trackselection` package is the best place to go. I will track hls adaptation related enhancements with this issue.

**Comment by jasonchuang** [comment] 2017-08-25 09:13
Try the ExoPlayer demo app with the following test content for adaptive switching experiment:

1. VOD with 10s segment, [url](https://vod.straas.net/companyId/100592/1496984341rl74rdlvsh/playlist.m3u8), init with 360p and switch to 720p in few seconds
2. VOD with 30s segment, [url](https://vod.straas.net/clax/bdaswoL5/149569465170q11x9uyj/playlist.m3u8), init with 360p and defer to switching up indefinitely due to `zero` bufferedDurationUs
3. LIVE with 3s segment, no url available, bufferedDurationUs is about 5 seconds in average and less than [min value](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L91) result in defering switching up indefinitely


As for the [defer switching policy](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L167) in AdaptiveTrackSelection, do you have any suggestions for dealing with different segment length ?  Or should I need to override `AdaptiveTrackSelection` to customize updateSelectedTrack policy for quick fix?

**Comment by james12695** [comment] 2017-08-25 23:28
@AquilesCanta I've tried the ExoPlayer demo app with the following test content for adaptive switching experiment:

1. VOD with 30s segment, init with 360p and defer to switching up indefinitely due to `zero` bufferedDurationUs
2. VOD with 10s segment, init with 360p and switch to 720p in few seconds
3. LIVE with 3s segment, bufferedDurationUs is about 5 seconds in average and less than [min value](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L91) result in defering switching up indefinitely

As for the [defer switching policy](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L164) in AdaptiveTrackSelection,
do you have any suggestions for dealing with different segment length ?
Or should I need to override `AdaptiveTrackSelection` to customize `updateSelectedTrack` policy for quick fix? Thanks

p.s. I've sent the test content url into dev.exoplayer's mail

**Comment by ojw28** [comment] 2017-08-31 09:01
- Why would you have 30 second segments? That's way longer than is recommended, and feels like it would be a bad choice for pretty much any possible scenario. I think Apple now recommend a 6s segment duration (having previously recommended 10s). In short, I don't think this is a case we need to worry about, since streaming providers really shouldn't be using segment durations anywhere near this long.
- We do need to fix (3), which is tracked by #3017.

**Comment by ojw28** [comment] 2017-11-01 19:03
(3) is now fixed in `dev-v2`. Marking as closed since (1) isn't a sensible use case (I don't think?) and (2) sounds like it's working correctly.

**Closed as completed by ojw28** 2017-11-01 19:03 UTC
Labels: enhancement
