### ISSUE TITLE
SinglePeriodTimeline NullPointerException

### ISSUE THREAD

**Issue by tuesda** [google/ExoPlayer#5653] opened 2019-03-20 03:10 UTC
### [REQUIRED] Issue description
There is a NullPointerException on consumer device

### [REQUIRED] Reproduction steps
normal play

### [REQUIRED] Link to test content
https://media-qncdn.ruguoapp.com/cda6c7ecaa94f9a755ec895340ce5a63314784dc50bfe0e4cde130c40e3de9f6-5c8e1e8c67816b05edcc44ce.m3u8

### [REQUIRED] A full bug report captured from the device
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'long com.google.android.exoplayer2.source.af.e' on a null object reference
       at com.google.android.exoplayer2.source.af.a(SinglePeriodTimeline.java:188)
       at com.google.android.exoplayer2.source.a.a(BaseMediaSource.java:148)
       at com.google.android.exoplayer2.j.a(ExoPlayerImplInternal.java:808)
       at com.google.android.exoplayer2.j.a(ExoPlayerImplInternal.java:735)
       at com.google.android.exoplayer2.j.handleMessage(ExoPlayerImplInternal.java:355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:201)
       at android.os.HandlerThread.run(HandlerThread.java:65)

### [REQUIRED] Version of ExoPlayer being used
exoplayer version: 2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Xiaomi MIX 2S
Android version: 9.0

**Comment by tonihei** [comment] 2019-03-20 15:13
The provided stream plays perfectly fine in the demo app.

Without more detailed reproduction steps and an obfuscated stack trace, it's not possible to say what may have gone wrong in your case.

**Comment by tonihei** [comment] 2019-03-25 09:13
Closing due to lack of information. Feel free to reopen if you can provide more details.

**Closed as completed by tonihei** 2019-03-25 09:13 UTC
Labels: need more info
