### ISSUE TITLE
Error caching music file

### ISSUE THREAD

**Issue by tangmingscau** [google/ExoPlayer#5540] opened 2019-02-20 09:25 UTC
Hi,We found a problem with caching music files, which have uncomfortable stimulating sounds. We have confirmed that the online source files are good. Can you give us some comments on this issue? Now we use exoplayer version 2.7.0.

[225.0.1550648539254.v3.mp3.zip](https://github.com/google/ExoPlayer/files/2883884/225.0.1550648539254.v3.mp3.zip)

**Comment by andrewlewis** [comment] 2019-02-20 09:46
I don't think we've got enough information here to help. The attached MP3 doesn't seem to be valid (I can hear distortion when playing it on my desktop, for example at 2:26) but you haven't described in detail how it was produced.

**Comment by tangmingscau** [comment] 2019-02-20 09:50
This MP3 file is cached by exoplayer. I just changed the suffix name exo to MP3 to make it easier for you to listen to him. This file is generated in the online environment. We don't have any more log information here. We just pulled the cached file out of the problem machine and found that the cached file had an uncomfortable sound.

**Comment by tangmingscau** [comment] 2019-02-20 09:53
We initially suspect that it is caused by network jitter. When writing cached files, duplicate writes or byte streams make errors in the location of files.

**Comment by andrewlewis** [comment] 2019-02-20 10:22
There is no guarantee that the cache files are actually valid streams, and they may be fragmented if the connection to the server is lost during caching. The correct way to read these back is using ExoPlayer's caching components, which take care of producing a valid stream out of cache data.

Setting that aside (assuming you're just reading the cache file as an MP3 to illustrate the issue): please could you try upgrading to the latest release, clearing the cache and trying to reproduce the issue? If the file was actually written using a version before 2.7.0 you may be hitting #3762.

**Comment by tangmingscau** [comment] 2019-02-21 02:17
This modification has been included in version 2.7.0, so it is not caused by this reason. This problem is very low probability. There are only a few mobile phones and there are no live ones. We are trying to reproduce them here, but there is no progress at present. Can you take a look at them again? This problem is mainly analyzed from the code level, especially writing the cache module, which you are most familiar with. It takes a lot of time for me to look at it here.

**Comment by andrewlewis** [comment] 2019-02-21 09:31
Is it possible that the file was written from a version before 2.7.0 (but is being read from a version >= 2.7.0)?

**Comment by tangmingscau** [comment] 2019-02-21 09:41
Once again, I confirm that the version I used contains this modification. The last version I used was 166c4ba submitted.

**Comment by andrewlewis** [comment] 2019-02-21 09:43
@erdemguven Please could you take a look? Thanks.

**Comment by tangmingscau** [comment] 2019-02-22 02:54
[mo bad sound.zip](https://github.com/google/ExoPlayer/files/2892199/mo.bad.sound.zip)
[mo nice sound.zip](https://github.com/google/ExoPlayer/files/2892200/mo.nice.sound.zip)
here are two voice.they are the same music.A voice is bad,A voice is nice.they all are from the exoplayer's cache

**Comment by tangmingscau** [comment] 2019-02-27 07:45
Usually an audio file has MD5 field, so can you add MD5 check in the cache module? If the check fails, inform the upper layer and let the upper application do the corresponding processing. I thought I would change it directly, but there are too many changes, for fear of bigger problems, I hope I can officially support this change.



Here is the response of the network request

  | HTTP/1.1 200 OK
-- | --
Server | Tengine
Content-Type | audio/m4a
Content-Length | 6699258
Date | Wed, 27 Feb 2019 07:12:37 GMT
x-oss-request-id | 5C763865370E4D3E09746DC8
Accept-Ranges | bytes
ETag | "96F47F1895A19004C06E0F12DA786851"
Last-Modified | Thu, 03 Jan 2019 06:13:38 GMT
x-oss-object-type | Normal
x-oss-hash-crc64ecma | 18337870066285813905
x-oss-storage-class | Standard
Content-MD5 | lvR/GJWhkATAbg8S2nhoUQ==
x-oss-server-time | 9
Via | cache13.l2cn656[86,304-0,H], cache29.l2cn656[115,0], vcache11.cn976[121,200-0,H], vcache15.cn976[140,0]
Ali-Swift-Global-Savetime | 1547507241
Age | 0
X-Cache | HIT TCP_REFRESH_HIT dirn:7:174648363
X-Swift-SaveTime | Wed, 27 Feb 2019 07:12:37 GMT
X-Swift-CacheTime | 3600
Access-Control-Allow-Methods | POST, GET, OPTIONS
Access-Control-Allow-Origin | *
Timing-Allow-Origin | *

**Comment by erdemguven** [comment] 2019-04-09 14:13
The files you shared, are they the original files created by exoplayer cache or did you concatenate multiple small cache files yourself?
Is the original source is a live stream? Can you share the url of the original source?

**Comment by ojw28** [comment] 2019-04-15 23:03
Closing this due to lack of concrete or actionable information. We really need proper reproduction steps to investigate this kind of issue.

> We initially suspect that it is caused by network jitter. When writing cached files, duplicate writes or byte streams make errors in the location of files.

This should never happen if you're using `https`. Hence there is no real need for us to be checking MD5 checksums in the cache module. It's far more likely something else is wrong. What you describe should never happen when using `http` either, however in this case it is possible that the data will not be as expected due to a man-in-the-middle altering the content. The solution to this is to use `https` instead.

**Closed as completed by ojw28** 2019-04-15 23:03 UTC
Labels: need more info
