### ISSUE TITLE
HLS no audio

### ISSUE THREAD

**Issue by LelloBello** [google/ExoPlayer#578] opened 2015-06-25 14:59 UTC
Hi everyone! I have one issue while using ExoPlayer demo project.  

I add the following sample to Samples.java: new Sample("Test", "http://178.33.229.111/live/mp4:Videolina/playlist.m3u8", DemoUtil.TYPE_HLS), video works perfectly but there is no audio.
Any ideas?

**Comment by ojw28** [comment] 2015-06-25 18:13
This is because we don't yet support MP3 audio in HLS. We support AAC only. The feature request is tracked by https://github.com/google/ExoPlayer/issues/71. The patch referenced above is a nearly working solution, but it doesn't seem quite stable enough to merge at this point.

**Comment by LelloBello** [comment] 2015-06-25 19:17
Thanks :+1:

**Comment by ojw28** [comment] 2015-06-26 13:47
We've merged support for this in the dev branch, and I can confirm that the stream appears to work correctly.

**Closed by ojw28** 2015-06-26 13:47 UTC
