### ISSUE TITLE
MPEG Audio layer1/2(mpga)

### ISSUE THREAD

**Issue by zhangabvc** [google/ExoPlayer#5212] opened 2018-12-07 06:59 UTC
If Exoplayer add  ffmpeg-extension , Whether to support this format （MPEG Audio layer1/2(mpga)）

![11111111111111111](https://user-images.githubusercontent.com/44994911/49632452-b2cdb500-fa30-11e8-8ba1-0397bbd00d4f.jpg)

**Comment by andrewlewis** [comment] 2018-12-07 09:58
Duplicate of #5204

**Closed as completed by andrewlewis** 2018-12-07 09:58 UTC
