### ISSUE TITLE
Why not separate feedInputBuffer() loop and drainOutputBuffer() loop into different threads?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#6086] opened 2019-06-24 10:00 UTC
In my opinion, MediaCodec should be more efficient if dequeue/enqueue operations are concurrent.  I have searched the `MediaCodec` document, not sure `MediaCodec` whether support to operation in multi threads.  Hope you give some useful information.

**Comment by umangsaini** [comment] 2019-06-24 12:09
“[Threading model](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html)” section of the ExoPlayer Javadoc throws light on the design.
There was a discussion on threading - #4463 . Quote from this issue by @natez0r  

>  "... The first reason was the thread safety of MediaCodec access on certain older devices (i believe Galaxy S5), we would see native crashes in the media stack if we did not create all of the Android MediaPlayer objects and do any MediaCodec interrogation (checking of codec supports main/high profile, etc...) and also release any android MediaPlayer instances." 

Essentially issuing codec operations from different threads may not be safe across all the devices.

**Comment by Romantic-LiXuefeng** [comment] 2019-06-26 01:18
@umangsaini  thanks! I have test some devices,  MediaCodec works fine. I am looking for Galaxy S5 to test.

**Comment by ojw28** [comment] 2019-08-02 15:42
Marking as a duplicate of #5796.

**Closed as completed by ojw28** 2019-08-02 15:42 UTC
Labels: duplicate
