### ISSUE TITLE
ShuffleOrder is reset when set in ConcatenatingMediaSource

### ISSUE THREAD

**Issue by thibseisel** [google/ExoPlayer#5686] opened 2019-03-26 21:03 UTC
### [REQUIRED] Use case description
When setting a `ShuffleOrder` in a `ConcatenatingMediaSource`, whether with the constructor or the `setShuffleOrder(ShuffleOrder)` function, that shuffle order is copied using `order.cloneAndClear()`.
This is problematic for my use case, because I want to start playback with a specific media (just like with issue #5426 ).

For example, let's consider a media list [A, B, C, D, E, F].
For those media, I calculated the shuffle order [2, 0, 5, 3, 4, 1].

#### Expected
With that shuffle order, media should be played that order: [C, A, F, D, E, B] (notice that I want it to start with C)

#### Actual
Media are played in any other order. The shuffle order created earlier is lost.

#### How to reproduce
1- Prepare the player with the following:
```java
// Create media sources for A, B, C, D, E, F.
MediaSource[] sources = createMediaSources();
long randomSeed = 42L;

// Create shuffled indices so that playback starts with C.
int[] shuffledIndices = createShuffleIndices(/*startIndex =*/2, sources.length, randomSeed);

// Create a shuffle order from the shuffled indices, and set it to a new ConcatenatingMediaSource
ShuffleOrder shuffleOrder = new ShuffleOrder.DefaultShuffleOrder(shuffledIndices, randomSeed);
ConcatenatingMediaSource concatSources = new ConcatenatingMediaSource(/*isAtomic=*/false, shuffleOrder, sources);

// Shuffle mode is already enabled for that player instance.
player.prepare(concatSources);
```

2- When playback is started, notice how media are not played in the defined order.

**Comment by marcbaechinger** [comment] 2019-03-26 22:34
Toni, can you please comment on this or whether this is a duplicate of #5426 for tracking?

**Comment by tonihei** [comment] 2019-03-28 09:46
That's unrelated to #5426 I think. But it's a duplicate of #4915. 
Basically, we currently don't keep the shuffle order as it is as long as the media source is not prepared. 

@thibseisel What you could potentially do as a workaround for now is to start playback at the intended start index (`player.seekToDefaultPosition(/*windowIndex*/ 2);` and `player.prepare(concatSources, /* resetPosition*/ false)`) and only set the custom shuffle order when you receive the first `onTimelineChanged` event.

**Comment by ojw28** [comment] 2019-04-05 21:40
Closing as duplicate.

**Closed as completed** 2019-04-05 21:40 UTC
Labels: duplicate

**Comment by thibseisel** [comment] 2019-06-05 07:42
@tonihei I tried your suggestion and it doesn't seem to work, I may have missed something.
Here is the attempted code:
```java
// Create media sources for A, B, C, D, E, F.
MediaSource[] sources = createMediaSources();
int startPosition = 2;
long randomSeed = 42L;

// Create shuffled indices so that playback starts with C.
int[] shuffledIndices = createShuffleIndices(startPosition, sources.length, randomSeed);

// Create a shuffle order from the shuffled indices, and set it to a new ConcatenatingMediaSource
final ShuffleOrder shuffleOrder = new ShuffleOrder.DefaultShuffleOrder(shuffledIndices, randomSeed);
final ConcatenatingMediaSource concatSources = new ConcatenatingMediaSource(/*isAtomic=*/false, shuffleOrder, sources);

player.seekTo(startPosition, C.TIME_UNSET);

// Shuffle mode is already enabled for that player instance.
player.prepare(concatSources, false, true);

final Player.Listener preparationListener = new Player.Listener() {
    @Override void onTimelineChanged(Timeline timeline, Object manifest, int reason) {
        concatSources.setShuffleOrder(shuffleOrder);
        player.removeListener(this);
    }
}

player.addListener(preparationListener);
```

Pre-specified shuffle order seems to be ignored in this case too.
Maybe that's because it is not immediately applied when calling `ConcatenatingMediaSource.setShuffleOrder(ShuffleOrder)` ?

**Comment by tonihei** [comment] 2019-06-05 11:17
It's applied almost immediately by sending a message to the playback thread. I tested your code in demo app and it works perfectly fine.
