### ISSUE TITLE
Crash in Exoplayer with imageButton Drawable Loading

### ISSUE THREAD

**Issue by CHRehan** [google/ExoPlayer#11281] opened 2023-09-05 12:53 UTC
### Bug

We've encountered a critical issue within the Exoplayer library, where the imageButton component fails to load the associated drawable resource, leading to a crash. We would like to report and address this problem, as it severely impacts our application's functionality.

**OS:** 8.1.0
**Device:** Nexus5x
**Rooted:** No
**Free Available Space:** 382 MB
**Device State:**  0% Background
 
```
Caused by android.view.InflateException: Binary XML file line #63: Error inflating class ImageButton

Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f08027f
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:253)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:760)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
       at android.content.res.Resources.loadDrawable(Resources.java:886)
       at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:953)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
       at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1363)
       at android.widget.ImageView.<init>(ImageView.java:188)
       at android.widget.ImageButton.<init>(ImageButton.java:86)
       at android.widget.ImageButton.<init>(ImageButton.java:82)
       at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:3)
       at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:3)
       at androidx.appcompat.app.AppCompatViewInflater.createImageButton(AppCompatViewInflater.java:14)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:14)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:14)
       at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:14)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.google.android.exoplayer2.ui.StyledPlayerControlView.<init>(StyledPlayerControlView.java:2)
       at com.google.android.exoplayer2.ui.StyledPlayerView.<init>(StyledPlayerView.java:7)
       at com.google.android.exoplayer2.ui.StyledPlayerView.<init>(StyledPlayerView.java:7)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at com.plume.common.ui.core.base.BaseFragment.onCreateView(BaseFragment.java:6)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:19)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:14)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:7)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:1)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
       at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:10)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:10)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:18)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:7)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:1)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:4)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:4)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:4)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
       at android.app.Activity.performStart(Activity.java:7029)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by icbaker** [comment] 2023-09-05 13:15
Duplicate of https://github.com/google/ExoPlayer/issues/10409

The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file any new issues in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

**Closed as completed by icbaker** 2023-09-05 13:15 UTC
Labels: duplicate
