### ISSUE TITLE
Videos dont play with IMA plugin

### ISSUE THREAD

**Issue by kelmer44** [google/ExoPlayer#4042] opened 2018-03-27 09:18 UTC
### Issue description

Since yesterday evening (everything was working prior to that), videos no longer play if IMA Media Source is passed. A message saying 

```
 W/IMASDK: Invalid internal message, ignoring. Please make sure the Google IMA SDK library is up to date. Message: gmsg://afma.google.com/omid?type=omidUnavailable&sid=*&dt=1522141705703
is shown in the logcat.
```

 is displayed

- Version of exoplayer is  2.6.1, playServices version is 11.0.4
- Updating exoplayer to 2.7 makes it work again.
- Removing Adsmediasoruce makes it work.

### Reproduction steps

- App with exoplayer & ima ads plugin, with play Services on the specified versions.
- build ads media source 

```

        mImaAdsLoader = new ImaAdsLoader(getContext(), tagUri);
     HlsMediaSource hlsMediaSource = new HlsMediaSource.Factory(mediaDataSourceFactory).createMediaSource(uri, mMainHandler, mEventLogger);
        return new AdsMediaSource(hlsMediaSource,
                mediaDataSourceFactory,
                mImaAdsLoader,
                mVideoView.getOverlayFrameLayout());

```
### Link to test content
Example:
https://mycujoosa1-lh.akamaihd.net/i/sk15847_1@370597/master.m3u8?play-only=primary&start=1522087127&end=1522094837

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Android 8, Android 7, Android 6
Google Pixel, Nexus 6P, Samsung S7
[bugreport-sailfish-OPM1.171019.021-2018-03-27-11-15-55.zip](https://github.com/google/ExoPlayer/files/1851272/bugreport-sailfish-OPM1.171019.021-2018-03-27-11-15-55.zip)

### A full bug report captured from the device
Attached

**Comment by andrewlewis** [comment] 2018-03-27 09:22
What is the ad tag URI? Please send it via email to `dev.exoplayer@gmail.com` if you don't want to post it here.

**Comment by kelmer44** [comment] 2018-03-27 09:42
Sent it to that address

**Comment by kelmer44** [comment] 2018-03-29 08:23
now with latest version of exoplayer (2.7.1) and play services (12.0.1) video is playing, but no ads are shown:

```
03-29 10:20:00.689 9320-9320/tv.mycujoo.mycujooplayer.beta.debug W/IMASDK: Invalid internal message, ignoring. Please make sure the Google IMA SDK library is up to date. Message: gmsg://afma.google.com/omid?type=omidUnavailable&sid=*&dt=1522311600566
03-29 10:20:01.640 9320-9320/tv.mycujoo.mycujooplayer.beta.debug W/IMASDK: Invalid internal message, ignoring. Please make sure the Google IMA SDK library is up to date. Message: gmsg://afma.google.com/activityMonitor?type=getPageSignals&sid=51a70c5f-a0c2-4258-b7ee-2ae19b2945cd&dt=1522311601630

```

IMA Tag uri:

`https://pubads.g.doubleclick.net/gampad/ads?sz=640x360&iu=/37686362/VIDEO_PREROLL&gdfp_req=1&env=vp&output=xml_vast3&unviewed_position_start=1&url=tv.mycujoo.mycujooplayer.beta.debug&description_url=description&correlator=1522311797397&cust_params=competition_id%3D991%26id_channel%3D194%26id_event%3D15439%26id_video%3D112863%26competition_name%3DIbercup+Cascais+U-15%26type%3Devent%26is_highlight%3Dfalse%26is_360%3D0&eid=420706069&sdkv=h.3.187.0&sdki=3c0d&scor=1522311797398&adk=679361705&u_so=l&osd=2&frm=0&sdr=1&is_amp=0&ged=ve4_td3_tt1_pd3_la0_er164.30.319.330_vi0.0.799.1536_vp100_eb24171`

**Comment by andrewlewis** [comment] 2018-03-29 16:57
I tried playing that ad tag in the demo app and got an empty response error from the IMA SDK: `AdError [errorType: LOAD, errorCode: AdErrorCode [name: VAST_EMPTY_RESPONSE, number: 1009], message: The VAST response document is empty.]`. ExoPlayer handles this error by resuming the content.

The error message about "Invalid internal message, ignoring." doesn't seem to be indicative of an actual issue. Could you check your ad serving configuration and make sure the ad tag is valid?

**Comment by kelmer44** [comment] 2018-03-30 19:22
I just loaded the tag uri I posted and it returns XAML VAST info --- If you refresh it will not though, to prevent showing the same ad continuously to the same ip address

**Comment by kelmer44** [comment] 2018-03-30 19:22
![image](https://user-images.githubusercontent.com/3629100/38150680-71ef4fee-3460-11e8-92a4-b2ea08d184db.png)

**Comment by andrewlewis** [comment] 2018-04-03 08:36
> I just loaded the tag uri I posted and it returns XAML VAST info --- If you refresh it will not though, to prevent showing the same ad continuously to the same ip address

There's an open bug about ad tags being requested twice (#3323) so maybe this is the cause of the problem.

**Comment by kelmer44** [comment] 2018-04-03 09:46
Yea that sounds like a possible cause for this bug.

**Comment by andrewlewis** [comment] 2018-04-03 09:55
I'll close this issue as #3323 tracks the double request bug already.

**Closed as completed by andrewlewis** 2018-04-03 09:55 UTC
Labels: need more info
