### ISSUE TITLE
How to pre-cache List of videos uisng exoplayer before playing it in recyclerview

### ISSUE THREAD

**Issue by AsitDixit** [google/ExoPlayer#10831] opened 2022-12-05 05:04 UTC
I'm able to cache a playing video using the below code:
```
 ProgressiveMediaSource mediaSource = new ProgressiveMediaSource.Factory(
                new CacheDataSource.Factory()
                        .setCache(SimpleMediaPlayer.simpleCache)
                        .setUpstreamDataSourceFactory(new DefaultDataSource.Factory(this,new DefaultHttpDataSource.Factory()))
                         .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
        ).createMediaSource(MediaItem.fromUri("https://xxxxxx.s3.us-north-2.amazonaws.com/xxxxxx.mp4"));

        playerView.setPlayer(player);
        player.setMediaSource(mediaSource);
        player.prepare();
```
But my problem is every video is buffering at least 5-10 seconds before playing in recyclerview. I don't want to cache full video , I just want to cache first 20-30 seconds of each video.

My flow is like fetch 15 videos(URL) from server and put it into recyclerview and before user scrolling I have already another 15 videos(URL) in my local database.

So I want that video should be cached(first 20-30) before playing it in recyclerview. I know something that is work manager but periodic work manager's minimum limit is 15 min to call a second work. I don't I'm confused, how to cache video. Should I run a for loop in background workmanager?

**Comment by marcbaechinger** [comment] 2022-12-06 13:48
I think you can cache a portion of a MP4 video with something like this:

```
CacheDataSource cacheDataSource =
    new CacheDataSource(
        yourCache,
        new DefaultDataSource(/* context= */ this, /* allowCrossProtocolRedirects= */ false));
DataSpec dataSpec = new DataSpec(uri, /* position= */ 0, length);
CacheWriter cacheWriter =
    new CacheWriter(
        cacheDataSource, dataSpec, /* temporaryBuffer= */ null, /* progrtessListener= */ null);
cacheWriter.cache();
```

this caches the first `length` bytes of the stream.

Then you can make the data source that you use for playback to be read-only by calling 

```
new CacheDataSource.Factory()
    .setCacheWriteDataSinkFactory(null)
    [...]
```

**Comment by AsitDixit** [comment] 2022-12-07 04:34
> I think you can cache a portion of a MP4 video with something like this:
> 
> ```
> CacheDataSource cacheDataSource =
>     new CacheDataSource(
>         yourCache,
>         new DefaultDataSource(/* context= */ this, /* allowCrossProtocolRedirects= */ false));
> DataSpec dataSpec = new DataSpec(uri, /* position= */ 0, length);
> CacheWriter cacheWriter =
>     new CacheWriter(
>         cacheDataSource, dataSpec, /* temporaryBuffer= */ null, /* progrtessListener= */ null);
> cacheWriter.cache();
> ```
> 
> this caches the first `length` bytes of the stream.
> 
> Then you can make the data source that you use for playback to be read-only by calling
> 
> ```
> new CacheDataSource.Factory()
>     .setCacheWriteDataSinkFactory(null)
>     [...]
> ```
My problem is how to cahce list of videos. Is there any way to cache list of videos in background?

**Comment by AsitDixit** [comment] 2022-12-07 06:08
@marcbaechinger Is there any inbuilt way to cache list of videos in same time parallelly. I donot want to cache full video at a time, but I want 10 videos to be cached 20seconds each. Can I achive this?

**Comment by marcbaechinger** [comment] 2022-12-07 10:23
Nah, I would have told you if there is a out-of-the-box solution. :)

A pro tip is to search the existing issues here on the issue tracker. I do that quite often and I can find useful information quite quickly and independently. Very useful.

When I do that for this topic I find for instance:

#3327: Support pre-buffering of next concatenated item
This issue tells that pre-buffering the playlist items is not available out of the box.
#7887: Is actually exactly about what you were asking. It has a couple of comments with code snippets. From the responses of users this seems helpful.

I will close this issue as a duplicate of #7887. Please re-open if you think your question is different.

**Closed as completed by marcbaechinger** 2022-12-07 10:23 UTC
Labels: question
