### ISSUE TITLE
Ad playback stuck after media timeouts

### ISSUE THREAD

**Issue by BucherTomas** [google/ExoPlayer#10510] opened 2022-08-09 13:59 UTC
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

Any that we have tested.

### Devices that do not reproduce the issue

n/a

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Add the following content in media.exolist.json and play it:
`[
  {
    "name": "Sample",
    "samples": [
      {
        "name": "VMAP",
        "uri": "https://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv",
        "ad_tag_uri": "https://devs.origin.cdn.cra.cz/ima/primavmap.xml"
      }
    ]
  }
]`
2. Leave it running until third or fourth midroll
3. Observe that playback gets completely stuck

### Expected result

Each midroll references the same VAST where there are three ads. The first two emulate slow media server response and return media only after 10 seconds, i.e. after the default timeout of 8 seconds. The third ad in midroll is served with regular speed.

IMA should gracefully skip the first two ads in each midroll and play the third midroll only. Each midroll should be playable the same way.

### Actual result

We have received reports from our customer that serves their own ads to our player that it occasionally gets stuck when playing ads. It helped knowing that their ad server tracker received in that case 402 error i.e. timeout as per https://support.google.com/admanager/answer/4442429?hl=en#zippy=%2Cunable-to-download-or-timeout-of-mediafile-uri.

So we prepared the environment with our own VMAP that would emulate the same behavior and first two ads time out from each midroll, only the third is immediately playable.

With this environment we can reproduce the player getting stuck most of the time during the third midroll at 1:30, seldomly at fourth midroll at 2:00. Tested with 2.15.1 and 2.18.1 with the same result.

A hint: it appears that while it works for the first few midrolls, the log can contain `java.net.SocketTimeoutException` but it doesn't when it gets stuck.

### Media

See reproduction steps section.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by BucherTomas** [comment] 2022-08-09 14:57
Actually, looks like the same circumstances already mentioned in https://github.com/google/ExoPlayer/issues/10494 . Here you have at least a VMAP to test with that will trigger those 402 timeouts.

**Comment by tonihei** [comment] 2022-08-11 08:44
Thanks for the excellent reproduction steps!

It seems the IMA SDK gets stuck and doesn't issue the expected callbacks any more. In fact, this seems to be caused by *not* timing out after the configured media timeout. We reported the issue to the IMA SDK team and will also provide a workaround in ExoPlayer that times out in this situation to ensure playback is unstuck.

**Comment by tonihei** [comment] 2022-09-06 10:23
The workaround will appear here soon and will be part of the next release.

**Closed as completed by tonihei** 2022-09-06 10:23 UTC
Labels: bug

**Comment by jmvillagra** [comment] 2022-09-22 09:52
Any updates on this issue? Thank you.
