### ISSUE TITLE
AdaptiveTrackSelection failed to switch up for live hls

### ISSUE THREAD

**Issue by james12695** [google/ExoPlayer#3224] opened 2017-08-31 01:38 UTC
I've tried the ExoPlayer demo app with my LIVE HLS with 3s segment and failed to switch up high quality track due to insufficient bufferedDurationUs in `AdaptiveTrackSelection`,  and found the similar issues #2477 and #3017 but both are marked as enhancement. So can we mark this issue as `bug` instead of `enhancement` and have a rough plan for this fix?
Thanks

**Comment by ojw28** [comment] 2017-08-31 09:03
Duplicate of #3017. Please avoid filing duplicate issues.

**Closed as completed by ojw28** 2017-08-31 09:03 UTC
Labels: duplicate
