### ISSUE TITLE
HLS Closed-Captions not showing up with DEFAULT selection.

### ISSUE THREAD

**Issue by ofuwape** [google/ExoPlayer#2742] opened 2017-04-27 17:43 UTC
**The Issue:**
Closed Captions doesn't show up when the DEFAULT option is selected.

**Exoplayer Version:** 2.4.0

**Devices:** 
- HTC Nexus 9 (Android 7.1.1 API 25)
- Nexus 6 (Android 6.0 API 23)

Tested with the sample/demo app

**HLS link:** https://cdn.curiositystream.com/system/Encoding/L3/000/000/781/249/preview_v2.m3u8

**Comment by ojw28** [comment] 2017-04-28 09:18
I gave this a try and it seems the captions display correctly in the demo app. They're a little bit out of sync, but they're out of sync in the source content, so that's not a player issue. Which specific captions that are in the [actual caption file](https://cdn.curiositystream.com/system/MediaClosedCaptions/ccs/000/003/185/original/Flight33_Miniverse_Rev4.vtt) do you see not being displayed, or not being displayed at the time specified in the caption file?

I'm going to close this because I'm pretty sure everything is working fine, but if you believe otherwise and can provide specific information as requested above, please let us know!

**Closed as completed by ojw28** 2017-04-28 09:18 UTC

**Comment by ofuwape** [comment] 2017-05-15 13:56
@ojw28 I tested again and this issue seems to occur with the **DEFAULT** option for closed captions

**Comment by AquilesCanta** [comment] 2017-05-15 18:11
@ofuwape, please clarify. What seems to occur with the default option? Out-of-syncness or subtitles not displaying? In order for us to look into this, please provide specific reproduction steps in the demo app. Try not to leave anything to interpretation, this is most likely not going to be looked into unless it is clear that there is an exoplayer issue.

**Comment by ofuwape** [comment] 2017-05-15 19:02
@ojw28 On the Demo App; The HLS url https://cdn.curiositystream.com/system/Encoding/L3/000/000/781/249/preview_v2.m3u8
does not show any closed-captions when the DEFAULT option is selected.

**Comment by AquilesCanta** [comment] 2017-05-15 19:53
If you are using 2.4, try the dev branch. There has been a bugfix on the DefaultTrackSelector that will make the vtt track the default selection for the provided stream.
