### ISSUE TITLE
Video plays with a green bar below the bottom of the video

### ISSUE THREAD

**Issue by troys-code** [google/ExoPlayer#8992] opened 2021-05-28 17:50 UTC
Video URI: https://mobile-plugins-demo-files.s3.eu-central-1.amazonaws.com/mp4/pad.mp4

### Expected behaviour

Video plays with no green bars shown.
For example, like this in Chrome - see [Screenshot_chrome](https://user-images.githubusercontent.com/13446008/120022802-373f9400-bfed-11eb-8903-f2ceb0bfb9b7.jpg).

### Actual behaviour

Video plays with a green bar below the bottom of the video.
See [Screenshot_exployer_demo](https://user-images.githubusercontent.com/13446008/120022877-4de5eb00-bfed-11eb-909f-9eabf92afa53.jpg).

### Additional info

adb bugreport:
[bugreport-OnePlus6-QKQ1.190716.003-2021-05-28-19-23-01.zip](https://github.com/google/ExoPlayer/files/6562509/bugreport-OnePlus6-QKQ1.190716.003-2021-05-28-19-23-01.zip)

- ExoPlayer version number: 2.14.0
- Android version: 10
- Android device: OnePlus 6
- The video was recorded by an iPad 6th Gen. This issue can also be reproduced with videos recorded by an iPad 11-inch Pro.
- This happens consistently with every video recorded by an iPad. These videos are created using iOS media apis (not the built-in screen recorder).

**Comment by marcbaechinger** [comment] 2021-06-01 11:01
I can repro this only with the ExoPlayer GL demo app on a real device (Pixel/Android 10 and Pixel 4/Android S). With emulators (Pixel XL/API 30 and Galaxy Nexus/API 30) the video is rendered correctly with the ExoPlayer GL demo app as well as with the normal demo app.

Can you confirm you are seeing this on the GL demo app only? 

I think we need to look into this anyways and see why the ExoPlayer GL demo app does render it this way on some devices. I think @andrewlewis is the best person to check whats behind this. May I ask you to take a look?

**Comment by troys-code** [comment] 2021-06-02 10:32
I can confirm this only happens in the GL demo app.

We're using `ExoPlayer.setVideoSurface` to play videos inside a game engine, so I think Open GL rendering is required in our specific case.

**Comment by andrewlewis** [comment] 2021-06-02 18:45
It looks like this is caused by not applying the transformation matrix from [`SurfaceTexture.getTransformMatrix`](https://developer.android.com/reference/android/graphics/SurfaceTexture#getTransformMatrix(float[])).

**Comment by ojw28** [comment] 2021-06-04 16:22
This should be fixed by the commit referenced above.

**Closed as completed** 2021-06-04 16:22 UTC
Labels: bug
