### ISSUE TITLE
Streaming one particular file gives glitched green & pink video

### ISSUE THREAD

**Issue by KatieBarnett** [google/ExoPlayer#8622] opened 2021-02-23 05:53 UTC
I have on particular video that is not playing correctly when using Exoplayer 2.13.7 (I have also seen the same with version 2.11.7) on some devices. 

Affected devices: Pixel 2 XL, Pixel 3 (both Android 11)
Working devices: Samsung S20 (Android 10)

The video is all distorted and green & pink. Other videos play correctly. The sound from the video is correct and undistorted.

I am not getting any 'NoSupport' messages from the MediaCodecInfo class.

I am able to reproduce the issue using the sample app.

Problematic video: 
https://abc-wcms-media-prod.s3-ap-southeast-2.amazonaws.com/media/8680998/v1/04%20COVER%20halsey_loveYourself.mp4

Working video:
https://abcmediastore.akamaized.net/media/11965050/v1/04%20Stella%20Donnelly%20COVER%20WEB.mp4

As far as I can tell the only difference in their encoding is the video size, the not working one is still not an overly large video.

I added the following to `"Widevine DASH (MP4, H264)"` in `media.exolist.json` to reproduce in the sample app. 
```
      {
        "name": "Test - Not Working",
        "uri": "https://abc-wcms-media-prod.s3-ap-southeast-2.amazonaws.com/media/8680998/v1/04%20COVER%20halsey_loveYourself.mp4"
      },
      {
        "name": "Test - Working",
        "uri": "https://abcmediastore.akamaized.net/media/11965050/v1/04%20Stella%20Donnelly%20COVER%20WEB.mp4"
      }
```

![Screenshot_20210223-152554](https://user-images.githubusercontent.com/5351053/108807098-9e693900-75f7-11eb-9ec9-8210fd05659e.png)

**Comment by Samrobbo** [comment] 2021-02-25 17:56
I've confirmed that this is reproducible on a Pixel 3a running Android 10, on the unchanged demo app.

**Comment by christosts** [comment] 2021-07-29 16:38
The non-working MP4 file contains interlaced video whereas the working MP4 is progressive. Android devices are not guaranteed to play interlaced video. 

Duplicate of #3468.

**Closed as completed by christosts** 2021-07-29 16:38 UTC
Labels: bug: device specific
