### ISSUE TITLE
Problem in Converting Interlaced stream to progressive stream

### ISSUE THREAD

**Issue by itssivashankar** [google/ExoPlayer#6673] opened 2019-11-20 07:42 UTC
I tried to build ffmpeg library into Exoplayer.
Build process is completed But de-interlaced is  not working for me

Kindly Guide me to Implement the de-interlaced option in Exoplayer

**Comment by AquilesCanta** [comment] 2019-11-21 16:21
I am guessing this is a duplicate of #2013. If it's not, please explain why, and provide all items required in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

**Closed as completed by AquilesCanta** 2019-11-21 16:21 UTC
Labels: duplicate
