### ISSUE TITLE
Android TV starts to slow down after recreating player instances

### ISSUE THREAD

**Issue by bivenik** [google/ExoPlayer#2681] opened 2017-04-13 05:24 UTC
### Issue description
Android TV starts to slow down after several releasing and recreating SimpleExoPlayer instanses (Application gets ANR).
Other media application on the TV can't play any video also after that.

### Reproduction steps
1) Create instanse of SimpleExoPlayer.
2) Play some DRM content.
3) Release player.
4) Repeat steps 1) - 3) several times in a row using one instanse of SurfaceView.

### Version of ExoPlayer being used
2.2.0

### Device(s) and version(s) of Android being used
Sony KD43X8309C - AndroidTV 5.1.1 - reproduces only on this device

### A full bug report captured from the device
Check email.

**Comment by ojw28** [comment] 2017-04-18 08:26
The bug reports you've provided both seem to be missing their top halves, which contain information we'd like to take a look at. How are you capturing the bug reports exactly? Is it possible for you to provide a complete one? Also, what type of DRM are you using to reproduce this (Widevine, or PlayReady, or does it reproduce with either)? Thanks!

**Comment by bivenik** [comment] 2017-04-18 12:56
Hello!

https://drive.google.com/open?id=0BxYi5ij_kpVoWG5QMThadzc1V1k - full  bug
report.

I'm using only PlayReady DRM.

**Comment by ojw28** [comment] 2017-04-18 13:05
Thanks. Are you able to also grab `/data/anr/traces.txt` from the device, or get the stack traces in your app when the ANR occurs from somewhere?

It's also possible that this will be fixed by Sony's M update, which coincidentally looks like it's set to resume rolling out tomorrow: http://sony-eur-eu-en-web--eur.custhelp.com/app/answers/detail/a_id/138486

**Comment by bivenik** [comment] 2017-04-19 10:56
Firstly I'll install update if it will be available for my device. If it not help - I'll come to you with traces.
Thanks for the link.

**Comment by ojw28** [comment] 2017-08-04 23:43
Does the lack of traces imply the update helped? Thanks.

**Comment by ojw28** [comment] 2018-01-02 17:02
Closing due to inactivity.

**Closed as completed by ojw28** 2018-01-02 17:02 UTC
Labels: need more info, bug: device specific
