### ISSUE TITLE
Exynos 7870 or SM-T580 has a problem with Widevine DRM Playback

### ISSUE THREAD

**Issue by workspace** [google/ExoPlayer#3775] opened 2018-01-31 08:49 UTC
Hi! I think my issue is device or core specific problem and related with #3561.

### Issue description
When try to play DRM Contents of ExoPlayer 2.6.1 demo app in Exynos 7870 devices such as SM-T580(Samsung Galaxy Tab A Tablet), black flicker has occured.

### Reproduction steps
use devices whose cpu is Exynos 7870
Device : SM-T580

Playing 2 sources to compare.
Without DRM (Youtube DASH – Google Glass(MP4, H264))
With DRM (Widevine DASH: MP4, H264 – WV:Secure HD (cenc, MP4, H264))
Without DRM, there will be no problem with playback, however, black flicker will be occured with DRM Playback. 

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
SM-T580 (or another Exynos 7870 device)

### A full bug report captured from the device
I sorry to say I don't have SM-T580 actually...I got this issue from my customer and checked it through attached video from him. Its size is too big for github issue system. Can I send this videos to assignee when assignee is determined.

Thank you and sorry for my English.

**Comment by wvpaf** [comment] 2018-02-01 22:39
@KiminRyu, does this particular content fail on all SM-T580s or just a sample?
The case you referenced is for live/key rotated content. Is this content live as well?
An ADB Bugreport is the best path forward, as we believe the report there are video artifacts so the video will not be needed. However, to help determine a root cause reviewing of the Bugreport is needed.

**Comment by workspace** [comment] 2018-02-02 00:16
All drm playback of our android app in SM-T580 has the same problem. Many SM-T580 users reviewed that there is black flickering. I tried to figure out the reason of problem with demo app, then someone attached video for the difference from normal playback and drm playback. As i mentioned above, I don't have SM-T580 device. So it is difficult to debug and get bugreport from it directly. I try to rent or buy used one...

**Comment by ojw28** [comment] 2018-02-02 13:00
If you're able to, please could you send a video showing the issue to `dev.exoplayer@gmail.com`?

**Comment by workspace** [comment] 2018-02-05 08:07
@ojw28 I sent it! 
Check email and reply to my email or leave comments if you need more informations about issue.

**Comment by wvpaf** [comment] 2018-02-13 22:22
While the video is helpful to understand the user impact the real useful information is in the ADB bugreport. If there is any chance to get that on a device with this issue that is what will be needed to dig in to this better.

**Comment by wvpaf** [comment] 2018-02-27 21:51
Any update on the full adb bugreport?

**Comment by workspace** [comment] 2018-02-28 15:49
@wvpaf There is no chance to get bugreport from devices which have a problem because I don't have one. I look forward to someone who has a device related to this issue will upload bugreport...

**Comment by RalphSleighC4** [comment] 2018-03-09 13:11
We have been able to reproduce this issue on the SM-T580, some notes:

Restarting the device fixed it, didn't occur again for months.
Affects the ExoPlayer demo and all other apps using Wildvine DRM.

While playing the logcat loops the following lines:

```
[ 03-07 13:59:31.680 2409: 2409 E/ ]
[PrimaryDisplay] failed to configure MPP (type:4, index:0) for layer 0
03-07 13:59:31.707 2409-2409/? D/libexynosgscaler: virtual CGscaler::~CGscaler()
03-07 13:59:31.707 2409-2409/? D/libexynosgscaler: virtual LibMpp::~LibMpp()

[ 03-07 13:59:31.707 2409: 2409 D/ ]
virtual MppFactory::~MppFactory()
03-07 13:59:31.709 2409-2409/? D/hwcutils: MppFactory::MppFactory()

[ 03-07 13:59:31.709 2409: 2409 D/ ]
virtual LibMpp *MppFactory::CreateMpp(int, int, int, int) dev(4) mode(0) drm(1), 
03-07 13:59:31.709 2409-2409/? D/libexynosgscaler: LibMpp::LibMpp()
03-07 13:59:31.796 2409-2409/? E/ion: ioctl c0144900 failed with code -1: Out of memory
03-07 13:59:31.796 2409-2409/? E/gralloc: invalid yuv format 2
03-07 13:59:31.796 2409-2409/? E/hwcutils: failed to allocate destination buffer(1200x1920): Invalid argument
```

We have not restarted it this time, so should be able to reproduce again so let me know if you need anything else.

**Comment by RalphSleighC4** [comment] 2018-03-12 15:07
@wvpaf I have e-mailed a bugreport taken while this was happening to dev.exoplayer@gmail.com

**Comment by wvpaf** [comment] 2018-03-15 21:30
The logs indicate, "gralloc failed" that the device is not capable of hanlding the content that is attempting to playback. 
If you limit the content to HD will this reproduce?

**Comment by RalphSleighC4** [comment] 2018-03-16 09:32
I can confirm this is happening when playing SD content, and the device played HD/SD content for some months without issue before this started happening.

I don't know if it could play the exoplayer UHD demo before the issue arose, and don't want to restart it to remove the issue to find out, given the difficulty in replicating it.

**Comment by jt64** [comment] 2018-04-24 22:43
Based on the log message you have attached this appears to be a problem with video memory allocation, possibly due to a memory leak or fragmentation.  We have opened an issue report with the manufacturer and will keep you updated as we learn more.

**Comment by ojw28** [comment] 2018-06-05 18:52
@jt64 - Did you hear from the manufacturer? Thanks.

**Comment by workspace** [comment] 2018-06-28 07:59
I tried to replicate this issue with sm-j730(Galaxy J7) which has same problem with sm-t580, however, it is not occured yet. Is there something to help with device before having problem?

**Comment by AlexM0k** [comment] 2018-07-31 13:55
Here is a video of the flickering issue https://streamable.com/v7yvi

**Comment by RalphSleighC4** [comment] 2019-02-13 11:49
We have kept our T580 up to date and playing video several hours a day and have not seen this issue in months, it's possible it was fixed in one of the monthly updates (we are on Nov 2018 security patch)

**Comment by paf-wv** [comment] 2019-02-26 23:17
Thanks @RalphSleighC4  for the update. We'll close as not reproducible.
It is probable that there was  fix that went out from the manufacture.

**Closed as completed by paf-wv** 2019-02-26 23:17 UTC
Labels: bug: in platform drm
