### ISSUE TITLE
Dash thumbnail's preview using exoplayer  

### ISSUE THREAD

**Issue by karamgharam** [google/ExoPlayer#8577] opened 2021-02-11 09:55 UTC
hello guys I need to load (retrieve)  thumbnail's images from this mpd URL 
https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-tiled-thumbnails-numbered.ism/.mpd
what the best implementation to parse and load thumbnails from this URL 
for seek bar thumbnail's  preview 
version 2.12.2 
thanks

**Comment by kim-vde** [comment] 2021-02-11 11:58
Duplicate of #7285.

I am afraid there is no easy way to do that in ExoPlayer at the moment. You could try to implement a custom video `Renderer` that retrieves thumbnails from the video samples and pass a custom `RenderersFactory` to a `SimpleExoPlayer` instance.

**Comment by marcbaechinger** [comment] 2021-02-11 21:52
Like kim-vde said this is not supported by ExoPlayer.

The manifest is parsed properly though and if you wanted you could extract the information about the sprites from the manifest, download the sprites and display it in your own UI. This is everything else than trivial though and we can't support you with that endeavor. It's pretty complicated and I haven't quickly found the specs tbh, so I don't know if you end up implementing something that works differently with other streams than the sample stream. If you are up to do your own you probably better off with a webvtt solution that is easier to parse. You may want to google for `Android webvtt thumbnails` or similar.

The ExoPlayer library does not support this either.

> what the best implementation to parse and load thumbnails from this URL

The code below is far from the best implementation to get that information, it's pretty hacky indeed, but shows you where to dig in case you want to look into this yourself. We really can't give you support for this as it is too complex to implement. Once you've downloaded the sprite you need to know how the timings are and the like. Best is probably to ask on StackOverflow.

```
    @Override
    public void onTimelineChanged(Timeline timeline, int reason) {
      DashManifest manifest = (DashManifest) timeline.getWindow(0, new Timeline.Window()).manifest;
      if (manifest == null) {
        return;
      }
      for (int i = 0; i < manifest.getPeriodCount(); i++) {
        Period period = manifest.getPeriod(i);
        long periodDurationUs = manifest.getPeriodDurationUs(i);
        for (int j = 0; j < period.adaptationSets.size(); j++) {
          AdaptationSet adaptationSet = period.adaptationSets.get(j);
          for (int k = 0; k < adaptationSet.representations.size(); k++) {
            Representation representation = adaptationSet
                .representations
                .get(k);
            String mimeType =
                representation
                    .format
                    .containerMimeType;
            if ("image/jpeg".equals(mimeType)) {
              Representation.MultiSegmentRepresentation multiSegmentRepresentation =
                  (Representation.MultiSegmentRepresentation) representation;
              for(int l = 1; l < multiSegmentRepresentation.getSegmentCount(periodDurationUs); l++) {
                Log.d("sprite_uri" , multiSegmentRepresentation.getSegmentUrl(l).resolveUri(representation.baseUrl).toString());
              }
              return;
            }
          }
        }
      }
```

The code above gives you urls like these: 
https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-tiled-thumbnails-numbered.ism/dash/tears-of-steel-tiled-thumbnails-numbered-img=4000-n-1.jpg

From the point when you have these uris, it is still a long way until you display these in the UI when the user is seeking. :)

**Closed as completed** 2021-02-24 13:13 UTC
Labels: duplicate, question
