### ISSUE TITLE
Mp4 video is not playing on demo app after a specific commit "a568fbdd5" with message "Parse frame rate from "mdta" metadata"

### ISSUE THREAD

**Issue by asaadaa** [google/ExoPlayer#5698] opened 2019-03-28 10:50 UTC
### [REQUIRED] Content description
this video url "https://video.euronews.com/mp4/med/EN/NW/SU/19/03/27/ar/190327_NWSU_7158954_7158958_95960_130739_ar.mp4" 
is not working on demo app with exoplayer update earlier than 2.9.3, after checking out your git repo commits, I found that the issue happens with this commit "a568fbdd5" with message "Parse frame rate from "mdta" metadata"

### [REQUIRED] Link to test content
https://video.euronews.com/mp4/med/EN/NW/SU/19/03/27/ar/190327_NWSU_7158954_7158958_95960_130739_ar.mp4

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
all devices

**Comment by ojw28** [comment] 2019-03-29 13:10
Duplicate of https://github.com/google/ExoPlayer/issues/5694.

**Closed as completed by ojw28** 2019-03-29 13:10 UTC
Labels: duplicate
