### ISSUE TITLE
HLS plays without audio

### ISSUE THREAD

**Issue by ashj11** [google/ExoPlayer#5580] opened 2019-02-28 03:59 UTC
### [REQUIRED] Content description
The HLS link given below, plays in Exoplayer without audio. VLC player is able to play the video with audio.
The content link below is valid for 90 days.
https://github.com/google/ExoPlayer/issues/71 shows that Exoplayer supports HLS auth MPEG audio, so i assume, this particular HLS Stream should be supported as well.

### [REQUIRED] Link to test content
https://photos.adobe.io/v2/assets/ca3d2b55828957848ac0171808400339/revisions/5371a41727358b34088630f35fb14db9/renditions/45d868a670c5cbcb847121e71661c1e5.m3u8?token=eyJhbGciOiJSUzI1NiIsImtleV9pdGVyYXRpb24iOjF9.eyJyZXNvdXJjZSI6eyJocmVmIjoiL3YyL2Fzc2V0cy9jYTNkMmI1NTgyODk1Nzg0OGFjMDE3MTgwODQwMDMzOS9yZXZpc2lvbnMvNTM3MWE0MTcyNzM1OGIzNDA4ODYzMGYzNWZiMTRkYjkvcmVuZGl0aW9ucy80NWQ4NjhhNjcwYzVjYmNiODQ3MTIxZTcxNjYxYzFlNSJ9LCJhY2Nlc3MiOiJyIiwiaWQiOiI0OTU2ODM1YS04MzgzLTQ1NTUtYjM5NC04N2I0NDNhOTAyOGMiLCJjcmVhdGVkX2F0IjoiMTU1MTI2OTgwNDAzOSIsImV4cGlyZXNfaW4iOiI3Nzc2MDAwMDAwIiwicHJveHkiOiJ0cnVlIiwiY2xpZW50X2lkIjoiTGlnaHRyb29tTW9iaWxlQW5kcm9pZDEifQ~~.sl7u7rgAter4aocGgnL_x9jlOHq-9fmrIB7v4tce5FtUqgz9jHOr1_aiRhNkPQ7QB6OsVPT7ppzFW6qf5nZ2yT8eCWE51kfYI9s0HHYz94FiUKVVlxXFWU-FEyJV-FJBAuXuNhpwKj3Bx0St-WgboHa-Y9m48DqIk8thq19sU2OVxeXt5xsighryTH6HAjrCvJ__9--ZcQWc82r4KUOv9JJbkFPnPoee8CJlprzcIN_L5qh7jblH8n6e7pTfOzAHWjl_qLO0bAmoMXLb_4dO4GhWpfgLTv-7rsDOtkZTCSp9S-f1lVdN95asDh6x7iezCB0P12nr3DmH08pxpHYrlA~~&api_key=LightroomMobileAndroid1

### [REQUIRED] Version of ExoPlayer being used
Release-v2 pointing to b88cc63951ae43e7d166867a56d2f04174f21936. ( Tried with dev-v2 too. Audio doesn't play with that as well.)

### [REQUIRED] Device(s) and version(s) of Android being used
Samsung Galaxy S7 with Android version 8.0.0

**Comment by AquilesCanta** [comment] 2019-02-28 16:45
This is a duplicate of #5537.

**Closed as completed by AquilesCanta** 2019-02-28 16:45 UTC
Labels: bad media
