### ISSUE TITLE
HLS Adaptive Streaming logic related question.

### ISSUE THREAD

**Issue by hbungshin** [google/ExoPlayer#9632] opened 2021-11-01 09:06 UTC
I have a question about HLS Adaptive Bitrate Streaming logic.
For example, if the HLS Manifest (master file) is configured as follows
In a bad network environment (150~300 kbps), it doesn't seem to go down to the lowest aac audio track, is this correct?
In this case, is there a way to make it work as an audio track?

please answer about my question.
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:CODECS="avc1.640028,mp4a.40.2",PROGRAM-ID=1,BANDWIDTH=4628000,RESOLUTION=1920x1080
1080/chunklist.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.64001f,mp4a.40.2",PROGRAM-ID=1,BANDWIDTH=3128000,RESOLUTION=1280x720
720/chunklist.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.64001f,mp4a.40.2",PROGRAM-ID=1,BANDWIDTH=1628000,RESOLUTION=854x480
480/chunklist.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.4d401e,mp4a.40.2",PROGRAM-ID=1,BANDWIDTH=768000,RESOLUTION=640x360
360/chunklist.m3u8
#EXT-X-STREAM-INF:CODECS="mp4a.40.2",PROGRAM-ID=1,BANDWIDTH=128000
aac/chunklist.m3u8

**Comment by icbaker** [comment] 2021-11-01 13:53
Just to confirm what you're expecting to happen: You want the player to swich from the `BANDWIDTH=768000` rendition (which contains both audio & video content) to the `BANDWIDTH=128000` rendition (which contains only audio)?

I don't think your playlist is expressing that, and I'm not sure HLS supports that directly.

The [spec](https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming) in [section 4.3.4.2.1](https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming#section-4.3.4.2.1) says:
> Every alternative Rendition associated with an `EXT-X-STREAM-INF`  tag MUST meet the constraints for a Variant Stream described in Section 6.2.4.

And [Section 6.2.4](https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming#section-6.2.4) says:
> Each Variant Stream MUST present the same content.

Given your `BANDWIDTH=128000` variant stream only has audio it, by definition, doesn't present the same content as the other variant streams (since they also contain video).

I suspect that to achieve what you want (disabling video in a low bandwidth environment) you need to implement custom track selection logic in ExoPlayer: https://exoplayer.dev/track-selection.html

**Comment by icbaker** [comment] 2021-11-01 14:00
My previous comment was wrong - it looks like this is a duplicate of https://github.com/google/ExoPlayer/issues/545.

**Closed as completed** 2021-11-01 14:00 UTC
Labels: duplicate
