### ISSUE TITLE
Internal track renderer error.

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#1758] opened 2016-08-21 06:23 UTC
Issue : Exoplayer crashes periodically 

Steps to Reproduce : play http://video.vcu.tv/86213_3b146e92bf8ca6a7c516df9024643a68/86213.mpd and occasionally the crash can be seen

The version of ExoPlayer being used : 1.5.5

Android version : 5.1 Multiple ARM devices

Full Bug Report : http://stagecms.vcu.tv/bc/temp/ytplayercrash.txt

Log messages from the crash : 

```
003 9084-9450/com.example.aguru.myapplication7 E/MediaCodec: Codec reported err 0xffffffff, actionCode 0, while in state 5
08-21 05:57:35.010 9084-9442/com.example.aguru.myapplication7 E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                       com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.hevc.decoder.awesome, MediaFormat(1, video/hevc, -1, -1, 1280, 720, 0, 1.0, -1, -1, null, 0, false, -1, -1)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:388)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729)
                                                                                           at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479)
                                                                                           at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                        Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.hevc.decoder.awesome, MediaFormat(1, video/hevc, -1, -1, 1280, 720, 0, 1.0, -1, -1, null, 0, false, -1, -1)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374) 
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                                           at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                                           at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                        Caused by: android.media.MediaCodec$CodecException: start failed
                                                                                           at android.media.MediaCodec.native_start(Native Method)
                                                                                           at android.media.MediaCodec.start(MediaCodec.java:616)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:366)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                                           at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                                           at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
08-21 05:57:35.010 9084-9418/com.example.aguru.myapplication7 E/VCU Log: internalError [0.20, decoderInitializationError]
                                                                         com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.hevc.decoder.awesome, MediaFormat(1, video/hevc, -1, -1, 1280, 720, 0, 1.0, -1, -1, null, 0, false, -1, -1)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729)
                                                                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479)
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                          Caused by: android.media.MediaCodec$CodecException: start failed
                                                                             at android.media.MediaCodec.native_start(Native Method)
                                                                             at android.media.MediaCodec.start(MediaCodec.java:616)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:366)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
08-21 05:57:35.011 9084-9418/com.example.aguru.myapplication7 D/VCU Log: Interface - VCUPlayer.listener, Method Name: onError - Exception com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.hevc.decoder.awesome, MediaFormat(1, video/hevc, -1, -1, 1280, 720, 0, 1.0, -1, -1, null, 0, false, -1, -1)
08-21 05:57:35.013 9084-9418/com.example.aguru.myapplication7 E/VCU Log: playerFailed [0.21]
                                                                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.hevc.decoder.awesome, MediaFormat(1, video/hevc, -1, -1, 1280, 720, 0, 1.0, -1, -1, null, 0, false, -1, -1)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:388)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729)
                                                                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479)
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                          Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.hevc.decoder.awesome, MediaFormat(1, video/hevc, -1, -1, 1280, 720, 0, 1.0, -1, -1, null, 0, false, -1, -1)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374) 
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                          Caused by: android.media.MediaCodec$CodecException: start failed
                                                                             at android.media.MediaCodec.native_start(Native Method)
                                                                             at android.media.MediaCodec.start(MediaCodec.java:616)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:366)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
08-21 05:57:35.013 9084-9442/com.example.aguru.myapplication7 E/ExoPlayerImplInternal: Stop failed.
                                                                                       java.lang.IllegalStateException
                                                                                           at android.media.MediaCodec.native_stop(Native Method)
                                                                                           at android.media.MediaCodec.stop(MediaCodec.java:632)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:441)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:408)
                                                                                           at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:289)
                                                                                           at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:231)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:561)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:548)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:525)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:242)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by andrewlewis** [comment] 2016-08-22 15:14
It looks like the H.265/HEVC codec is failing to initialize. There are a few possible causes, including: running out of device resources (due to an app not releasing the codec), a device-specific bug with the codec or an issue with the input media.

To investigate further, please could you try to reproduce this in the ExoPlayer demo app? Do other H.265/HEVC videos play reliably on this device? On what devices can you reproduce the error?

It looks like the provided bug report doesn't include the error stack trace, so if you provide another bug report taken just after seeing the issue we would have more information to go on. Thanks!

**Comment by abhiguru** [comment] 2016-08-28 13:03
Actually, codec/player/device has been working okay for last 6 to 8 months on the device using the same version of Exoplayer this is a random crash that happened only once a month maybe ? it is not just HEVC codec even the AVC codec used by the Android YT player stops playing video once this crash occurs... 

When it happens again I will try to get another bug report... reboot fixes the issue, I will have to use the demo app for a while to actually have this reproduce so when it happens in our app we will run the demo app and get the bug report for it too if that works... Stay tuned 

Device : Any AmLogic S905 but have also seen it on RK3288 devices

**Comment by Keopss** [comment] 2016-09-28 18:35
Hi @abhiguru i have same problem with .mp4 videos. Did you find any solution?

Thank you!

**Comment by ojw28** [comment] 2016-11-16 22:53
Closing for now since we don't have a bug report that captures the issue. It sounds a lot like underlying platform flakiness, so even if we do get a bug report it feels fairly unlikely that we'll be able to do much about it, although please do provide one if you see the issue again. Thanks!

**Closed as completed by ojw28** 2016-11-16 22:53 UTC
Labels: need more info

**Comment by andrewlewis** [comment] 2016-11-17 09:34
For what it's worth, the symptom that playback is broken for all apps after seeing this error and that it's fixed by reboot sounds very similar to what you might see when leaking a codec on some devices running older Android builds. You can sometimes identify this case by inspecting a bug report (depending on the device), but your bug report linked above seems to be inaccessible now. It might be worth checking your code to make sure you're releasing the player correctly. But an alternative explanation is simply platform flakiness as noted above.

**Comment by abhiguru** [comment] 2016-11-19 08:28
will do, it is probably the case.

**Comment by scn46** [comment] 2016-12-04 23:45
Not sure if anyone has any knowledge on this 
http://pastebin.com/EijG0GJz
Is there a fix for that error in question?it is fixed by a  reboot and l am using nougat or android N on a nexus 5 which doesn't have blobs or drivers for that android version.
Sorry if l shouldn't of posted here but find anyone who knows about this.

**Comment by andrewlewis** [comment] 2016-12-05 08:23
@scn46 If I understand correctly, you're using an unsupported build/device combination, so it's not surprising that you see instability. The underlying error is probably unrelated to ExoPlayer and trying to work around it is outside the scope of this issue tracker.

**Comment by scn46** [comment] 2016-12-05 19:12
Thankyou for your response that is correct l am using an unsupported version of android on my device but would still expect YouTube/exoplayer  to have the ability to maintain is function and not fail randomly.This issue is only present when using YouTube.apk and does occur when using YouTube in chrome browser.
 l appreciate your response l shall persevere was hoping you guys would see something obvious in the logcat.
Thanks again

**Comment by ojw28** [comment] 2016-12-05 19:23
I think your expectation is incorrect. The decoders we use are in the platform. If the unsupported build/device combination doesn't have correctly functioning decoders, then it's not possible for YouTube/ExoPlayer to still function. As an analogy, your expectation is kind of like expecting a game to work on a PC that has broken graphics card drivers installed.

Please let us know if you can reproduce the problem on a supported version of Android.

**Comment by scn46** [comment] 2016-12-05 19:58
No l cant reproduce the error  on marshmallow previous supported version of android.
I do get what your saying and understand the fact YouTube/exoplayer  is not functioning correctly due to the combination of device and android version.
I am just looking for guidance towards finding a fix as nobody else has a clue.
Thanks again
