### ISSUE TITLE
Not able to display captions using castplayer and MediaItem.Subtitle while casting

### ISSUE THREAD

**Issue by jazimm** [google/ExoPlayer#8955] opened 2021-05-18 06:48 UTC
I have implemented exoplayer2.ext.cast.CastPlayer utilizing dash and can view subtitles when calling setMediaItem on an instance of exoplayer2.Player.setMediaItem with a MediaItem that includes a MediaItem.Subtitle in the MediaItem.Builder(). The dash stream will play sucessfully on the Android TV device but I have not been able to determine how to turn on the captions while casting. When playing on the exoplayer on the phone I can set the preferred caption using the DefaultTrackSelector but can you inform me how to do the same on the Castalbe device. Thanks very much.

**Comment by icbaker** [comment] 2021-05-18 08:06
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/8669.

**Closed as completed by icbaker** 2021-05-18 08:06 UTC
