### ISSUE TITLE
ExoPlayer can't play pipeline source 

### ISSUE THREAD

**Issue by pulapulapin** [google/ExoPlayer#10721] opened 2022-10-25 07:58 UTC
ExoPlayer Version
2.18.1

Devices that reproduce the issue
Android TV 9.0

Expected result
The media is plays successfully.

Actual result
onPlayerError :com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.IOException: lseek failed: ESPIPE (Illegal seek)

_**Q: maybe FileDataSource can't read pipeline source ? its there any ohter DataSourceFactory can read pipeline source ?**_

    try {
      file.seek(dataSpec.position);
      bytesRemaining =
          dataSpec.length == C.LENGTH_UNSET ? file.length() - dataSpec.position : dataSpec.length;
    } catch (IOException e) {
      throw new FileDataSourceException(e, PlaybackException.ERROR_CODE_IO_UNSPECIFIED);
    }

**Comment by icbaker** [comment] 2022-10-25 08:52
Please describe exactly what you mean by 'pipeline source' - ideally with an example we can use to reproduce the problem.

**Comment by pulapulapin** [comment] 2022-10-26 07:01
> 

 Oh sorry about the bewildered title ,We have a Server write ts format in Android Paht eg:/data/data/com.xxxx.xxxx/cache/00:28:f8:c0:16:ed,  **cause the pipe feature(Signal in process), its likes ring buffer FIFO**. I have no idea how to use the default DataSource Factory 
distinguish the source

**Comment by icbaker** [comment] 2022-11-10 10:02
Closing because the information requested wasn't clearly provided.

**Closed as completed by icbaker** 2022-11-10 10:02 UTC
Labels: question
