### ISSUE TITLE
Can we support seek options like SEEK_PREVIOUS_SYNC

### ISSUE THREAD

**Issue by kneep** [google/ExoPlayer#2973] opened 2017-06-20 07:49 UTC
I think the seekTo method in ExoPlayer seeks to the exact position. But in most cases, users prefer better performance over precision. Can we support something like SEEK_PREVIOUS_SYNC as the platform API does? Thank you.

**Comment by ojw28** [comment] 2017-06-20 08:26
Dupe of https://github.com/google/ExoPlayer/issues/2882.

**Closed as completed by ojw28** 2017-06-20 08:26 UTC
Labels: duplicate
