### ISSUE TITLE
Negative timestamps in TS file causes playback to stay in buffering state forever

### ISSUE THREAD

**Issue by alexeyr15** [google/ExoPlayer#8220] opened 2020-11-13 15:02 UTC
### [REQUIRED] Issue description
Video playback doesn't start for .ts file. It works in other players.

### [REQUIRED] Reproduction steps
1. Open the provided test stream in ExoPlayer Demo app
2. Video playback doesn't start

### [REQUIRED] Link to test content
Provided by email

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
N/A

**Comment by kim-vde** [comment] 2020-11-17 14:41
The problem comes from the fact that the first audio timestamps are negative.

The content starts with video samples and the adjuster time offset is set to the DTS of the first sample. Audio samples are then read, but their timestamp is less than the video DTS and therefore less than the offset, leading to negative timestamps.

The corresponding code is given [here](https://github.com/google/ExoPlayer/blob/r2.12.1/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/PesReader.java#L243).

**Comment by alexeyr15** [comment] 2020-11-17 14:56
Thanks for investigation. Is there some way to work around this? After changing position via a seekbar, the video is playing normally.

**Comment by kim-vde** [comment] 2020-11-18 11:49
@christosts Does ExoPlayer support negative timestamps? And does it support the case where audio samples start with negative timestamps, and video samples start with positive timestamps?

What is happening here is that the MediaCodecVideoRenderer is never getting ready. Execution goes through the following steps:
- The MediaCodecVideoRenderer is enabled with offsetUs = 0 and MediaCodecVideoRenderer#outputStreamOffsetUs is therefore set to 0.
- The extractor extracts audio frames with negative timestamps.
- [This line](https://github.com/google/ExoPlayer/blob/r2.12.1/library/core/src/main/java/com/google/android/exoplayer2/audio/MediaCodecAudioRenderer.java#L565) is executed with buffer.timeUs < 0 and ExoPlayerImplInternal#rendererPositionUs therefore goes from 0 to a negative value.
- As a result, the MediaCodecVideoRenderer is never ready because, in [here](https://github.com/google/ExoPlayer/blob/r2.12.1/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L792), positionUs is negative and outputStreamOffsetUs is 0.

Note that it works sometimes, so there is probably a race condition somewhere.

This is related to [Internal ref: b/160461756] and to [Internal ref: cl/272434814].

**Comment by kim-vde** [comment] 2020-11-18 12:31
EDIT: after discussion with @tonihei, we do not currently support negative timestamps.

**Comment by kim-vde** [comment] 2020-11-25 17:18
@alexey-rabets We won't be able to fix this in the near future because it is not trivial.

What you could do as a workaround is to implement your own `TimestampAdjuster` and to pass it to the `TsExtractor` in a custom `ExtractorsFactory`. You could then pass the `ExtractorsFactory` to the `SimpleExoPlayer` builder. In this timestamp adjuster, you could for example offset all the timestamps by a fixed value to avoid negative values.

I'll mark this issue as an improvement so that we keep track of it (we generally do not fully support the specs). I'll also mark it as low-priority because this logic is present for a long time and this is the first time (at least that I am aware of) that it is causing problems.

**Comment by andrewlewis** [comment] 2022-02-23 10:51
@alexey-rabets Is this still reproducible on the latest version? I think we may have added back a default stream offset which might work around this problem.

**Comment by alexeyr15** [comment] 2022-02-23 11:10
It looks like this issue is not reproducible anymore for my use case.

**Comment by andrewlewis** [comment] 2022-02-23 11:16
Thanks. In that case I'll close this.

**Closed as completed by andrewlewis** 2022-02-23 11:16 UTC
Labels: enhancement, low priority
