### ISSUE TITLE
Support widevine DRM Key Rotation

### ISSUE THREAD

**Issue by asgharhussain** [google/ExoPlayer#1298] opened 2016-02-23 03:50 UTC
Hello,

We are working with Live TV (DASH) ABR packaging. The packager creates the MPD manifest while continuously rotating the Widevine(DRM) key. When I play the stream using ExoPlayer, the video does not play. The same video plays on Shaka Player.

If the DRM key policy is changed to static, then ExoPlayer (and Shaka Player) plays the stream.

Please let me know if there is a solution to this issue.

Thanks.

-Asghar

**Comment by ojw28** [comment] 2016-02-23 11:23
We don't support key rotation yet, but it's on our radar.

**Comment by abouda** [comment] 2016-11-17 18:25
Hello,
I wanted to know if key rotation is supported in ExoPlayer 2 or is it being worked on.

**Comment by zhanghuicuc** [comment] 2016-12-20 04:19
+1 
I also want to know if key rotation is supported in ExoPlayer 2 or is it being worked on. Thanks.

**Comment by mcart666** [comment] 2017-07-14 09:49
Any updates? Can you provide an approximate date when keys rotation may be available in Exo2?

**Comment by ojw28** [comment] 2017-07-14 10:19
Does anyone have test streams available, that we can easily make use of (i.e. they should not be geo-restricted or require authentication, and the license server should always issue licenses)?

**Comment by mcart666** [comment] 2017-07-14 12:01
What about streams from Axinom? See: https://github.com/Axinom/dash-test-vectors

I've checked the current version of Exo2 on "v7-MultiDRM-MultiKey" and "v7-MultiDRM-MultiKey-MultiPeriod", in particular:
https://media.axprod.net/TestVectors/v7-MultiDRM-MultiKey/Manifest_1080p.mpd
https://media.axprod.net/TestVectors/v7-MultiDRM-MultiKey-MultiPeriod/Manifest_1080p.mpd
https://media.axprod.net/TestVectors/v7-MultiDRM-MultiKey-MultiPeriod/Manifest_AudioOnly.mpd

The playback of the last one works until Exo is about to enter 2nd period, then fails with:
android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
However seeking over the moment of key change works correctly. For the first two streams Exo raises the exception just when the playback is about to start.

**Comment by ojw28** [comment] 2017-07-14 12:49
That's not key rotation (which would be within a single period). Although that does separately sound like a problem.

**Comment by adrianrdzv** [comment] 2017-07-14 13:25
@ojw28 We have key rotation in our streams, we can provide them to you for testing in a private message.

**Comment by mcart666** [comment] 2017-07-14 15:02
@ojw28 So you're saying that this particular case (each period encrypted with a different key) is expected to work in Exo2?

**Comment by ojw28** [comment] 2017-09-20 19:03
Key rotation should work in `dev-v2` as of https://github.com/google/ExoPlayer/commit/b62eab63a4d13945d07431be3d30628392646260. You'll need to set `multiSession=true` when instantiating your `DefaultDrmSessionManager`. If you're trying to test streams in the ExoPlayer demo app and wish to add one to `media.exolist.json`, you can specify `"drm_multi_session": true,` for the sample to enable multiSession mode.

**Comment by ueno-yuhei** [comment] 2017-12-05 13:01
@ojw28 
Hello, I was helped by this task.
Thank you very much.

https://github.com/google/ExoPlayer/commit/b62eab63a4d13945d07431be3d30628392646260 was merged into release-v2 so I used it immediately.

The screen flickers black when doing Key Rotation, but can this be countermeasured?

**Comment by ojw28** [comment] 2017-12-05 13:25
Are you setting `multiSession` to true?

**Comment by ueno-yuhei** [comment] 2017-12-05 15:33
@ojw28 Thank you for answering.
yes, Setting multiSession to true.

It is specified when instantiating DefaultDrmSessionManager.
If multiSession is set to false, it seems that the key rotation video can not be played.

**Comment by ojw28** [comment] 2017-12-05 18:06
There shouldn't be any flickering. You'd need to provide concrete reproduction steps (and probably a sample stream) for us to help work out why.

**Comment by ueno-yuhei** [comment] 2017-12-06 03:35
@ojw28 Thank you for answering!

I will send a sample stream by email.
I will send it today.
I'm sorry but I would like you to do verification with that.

**Comment by ueno-yuhei** [comment] 2017-12-07 03:53
@ojw28 I sent an e-mail to dev.exoplayer@gmail.com.
If you know something, please contact us.

**Comment by ojw28** [comment] 2017-12-07 11:31
I'm able to reproduce. I'm not sure why it's happening though, unfortunately. I would guess there's something wrong with the way the content has been prepared, or how the license policy is configured. Or at least, that there's something in these areas that our implementation is unhappy with.

For comparison, here's a key rotation sample stream we have that plays fine in the demo app. One option could be for you to spent a bit of time working out what's different:

```
{
  "name": "Sintel - 3 minutes key rotation",
  "uri": "https://storage.googleapis.com/playerinfra/wv/sintel_3min_rotate.mpd",
  "drm_scheme": "widevine",
  "drm_multi_session": true,
  "drm_license_url": "https://widevine-proxy.appspot.com/proxy"
}
```

**Comment by ojw28** [comment] 2017-12-07 11:34
Closing this issue because the feature is implemented now.

@wvpaf - Do we provide any tools/diagnostics/guidance for producing content in which the keys rotate?

**Comment by ueno-yuhei** [comment] 2017-12-07 11:56
@ojw28 Thank you for answering!

"Sintel - 3 minutes key rotation"
I checked it.
It seems to be black and flicker after 3 minutes.
It seems that the following error has appeared at that time.

12-07 20:47:58.482 26068-26068/com.google.android.exoplayer2.demo E/EventLogger: internalError [364.05, audioTrackUnderrun [49248, 256, 483]]

adb logcat log
[NexusPlayerLog.txt](https://github.com/google/ExoPlayer/files/1538912/NexusPlayerLog.txt)

If you know something, please contact us.

**Comment by ojw28** [comment] 2017-12-07 12:11
Heh, I looked more closely and see it too. It does seem to be far less severe than when using your test stream though, so I'm not sure whether there's something additional broken in that case. Re-opening this issue to work out what's going wrong for the sample I ref'd above in any case, thanks!

**Comment by ojw28** [comment] 2017-12-07 12:42
The reason for the black flicker is that although `MediaDrm` session sharing is enabled, the secure video decoder is still being recreated. That shouldn't be happening. I've filed https://github.com/google/ExoPlayer/issues/3561 to track this issue, and will close this again as it was really intended to track the initial implementation. Thanks!

**Closed by ojw28** 2017-12-07 12:42 UTC
Labels: enhancement
