### ISSUE TITLE
How to prevent removing previous subtitle when receiving an empty cue?

### ISSUE THREAD

**Issue by henninghall** [google/ExoPlayer#7374] opened 2020-05-13 15:32 UTC
### [REQUIRED] Searched documentation and issues
Searched github issues, documentation and stackoverflow.

### [REQUIRED] Question
The subtitles are disappearing too quickly, and the reason seems to be that I receive empty cues that remove the previously displayed subtitle. How can I prevent this to happen? 

**EDIT:** Realizing the question might actually be: Why do I get empty cues where I shouldn't?

**Comment by henninghall** [comment] 2020-05-14 07:56
Probably related to this https://github.com/google/ExoPlayer/issues/2669 but they the problem also occurs every 6th second.

**Comment by icbaker** [comment] 2020-05-14 10:31
> reason seems to be that I receive empty cues that remove the previously displayed subtitle.

What do you mean by "receive" here? Are you talking about calls to `TextOutput#onCues` e.g. in SubtitleView:
https://github.com/google/ExoPlayer/blob/7d3f54a375fac04a746ca76a8f2e1ad32c8b45b2/library/ui/src/main/java/com/google/android/exoplayer2/ui/SubtitleView.java#L80

Does "empty cues" mean an empty `List<Cue>`, or a `List<Cue>` containing at least one `Cue` with both `Cue.text == null` and `Cue.bitmap == null`? (i.e. an empty list of cues, or a list of empty cues?)

> **EDIT:** Realizing the question might actually be: Why do I get empty cues where I shouldn't?

What do you mean by "shouldn't"? We use an empty list of cues to signal the cues should be removed from the display - this usually happens because the underlying subtitle format tells us the duration of the cues. e.g. in the following subrip example we'd call `onCues` with `cues=[Cue{text="How did he do that?"}]` at 20:41.150 and then with `cues=[]` at 20:45.109.

```
168
00:20:41,150 --> 00:20:45,109
How did he do that?
```

It sounds like that given the media you're using you're seeing these empty cue-lists arriving at unexpected times? Without access to the media in question it's very hard to debug further. If you're unable to share the media publicly, please send it to dev.exoplayer@gmail.com using a subject "Issue #7374". Please also update this issue to indicate you’ve done this.

**Comment by henninghall** [comment] 2020-05-14 12:07
Thanks for the quick reply! 

With "empty cues" I mean a `List<Cue>` with size 0. 

The problematic onCue triggers seem to come from this place:
https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/text/TextRenderer.java#L203

Here is a media where the issue is present at several points, very clearly at 0:18. 
https://streaming.sfanytime.com/sfa_prod/ted-for-karlekens-skull/trailer/27326_c.ism/manifest.mpd

If you prefer a reproducible sample you can try this one, just start any playback and observe the subtitles around 0:18. 
https://github.com/henninghall/ExoPlayer/tree/reproduce-subtitle-disappear-issue

**Comment by icbaker** [comment] 2020-05-14 15:55
Thanks for the media link, I can reproduce the problem: When watching with Danish subtitles I see "hvilken herlig dag" appear briefly and then disappear. Upon inspecting the subtitles it looks like it is supposed to start at 17.48s and last until 20.28s but disappears at about 18s.

I've had a closer look at the media, I think the problem is that this subtitle is in the [12s - 18s segment](https://streaming.sfanytime.com/sfa_prod/ted-for-karlekens-skull/trailer/27326_c.ism/27326_c-textstream_dan=2000-12000.dash) but is expected to last until 20.28s. It's then not repeated in the [18s - 24s segment](https://streaming.sfanytime.com/sfa_prod/ted-for-karlekens-skull/trailer/27326_c.ism/27326_c-textstream_dan=2000-18000.dash).

The DASH spec requires data that is expected to be displayed on both sides of a segment boundary be repeated at the end of segment N and again at the beginning of segment N+1 (i.e. every segment contains enough data to show all the expected display data):
https://dashif-documents.azurewebsites.net/Guidelines-TimingModel/master/Guidelines-TimingModel.html#necessary-references-static

So what's happening in this case is that at 18s we switch to reading subtitles from the 18 - 24s segment, but this segment only contains a single subtitle to be displayed at 23.44s. So when we ask the segment "what subtitles should be on screen at 18s?" it answers "none" and we pass an empty cue list to `SubtitleOutput`.

The fix for this is to repeat the final subtitle sample in the 12s - 18s at the beginning of the 18s - 24s segment.

Additionally (though I don't think it's causing any of the problems in this issue), it seems your 12s - 18s segment contains 3 TTML `<p>` tags in a single sample. As far as I can tell from ISO/IEC 14496-30:2014(E) it's expected that each sample contains a 'static' subtitle representation, so the 3 tags should be in 3 separate samples. See Figure 1 in Section 6.3 and also Section 7.8 which shows a more complex example of 3 overlapping subtitles being split into 5 samples (this is a WebVTT example but I believe the same 'static' principle applies to TTML).

**Comment by icbaker** [comment] 2020-06-02 13:04
Closing due to inactivity.

**Closed as completed by icbaker** 2020-06-02 13:04 UTC
Labels: question, bad media

**Comment by henninghall** [comment] 2020-06-02 14:21
Thanks a lot for all your help @icbaker!! 😇  It was really helpful and we managed to figure it out.
