### ISSUE TITLE
Exception when playing a corrupted Mp4 stream

### ISSUE THREAD

**Issue by dbedev** [google/ExoPlayer#3130] opened 2017-08-02 14:20 UTC
### Issue description
Expolayer generated an exception on trying to play a corrupt mp4 stream. 

What we managed to find out before we lost the corrupted stream is that the corrupted stream somehow generates a state in which the mp4 extractor readAtomPayload method will call  input.skipFully with an atomPayloadSize of -8.  This in the end causes an exeception on the systemArrayCopy as it's source is set to -8. We traced back this was caused by the atomSize being 0 and atomHeaderBytesRead being 8.  

From source we think easiest robustness enhancement around this would be  to do a check on the atomSize  as read in the readAtomHeader and return false which then should indicate an end of stream in case the size is invalid. We are however not sure though what the exact valid ranges should be for this mp4 atomSize . Is this minimum of 8 as expected by the (readAtomPayload )  implementation or is it even bigger by mp4 spec ?

### Reproduction steps
Play the corrupted stream

### Link to test content
We no longer have the corrupted stream sequence on which the original issue occurs

### Version of ExoPlayer being used
1.5.16

### Device(s) and version(s) of Android being used
Custom android 4.3 based device

### A full bug report captured from the device

4:19.119  1754  1777 E LoadTask: Unexpected exception loading stream
08-02 12:54:19.119  1754  1777 E LoadTask: java.lang.ArrayIndexOutOfBoundsException: src.length=8192 srcPos=-8 dst.length=8192 dstPos=0 length=8
08-02 12:54:19.119  1754  1777 E LoadTask:      at java.lang.System.arraycopy(Native Method)
08-02 12:54:19.119  1754  1777 E LoadTask:      at com.google.android.exoplayer.extractor.DefaultExtractorInput.updatePeekBuffer(DefaultExtractorInput.java:213)
08-02 12:54:19.119  1754  1777 E LoadTask:      at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFromPeekBuffer(DefaultExtractorInput.java:183)
08-02 12:54:19.119  1754  1777 E LoadTask:      at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:92)
08-02 12:54:19.119  1754  1777 E LoadTask:      at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:103)
08-02 12:54:19.119  1754  1777 E LoadTask:      at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:240)
08-02 12:54:19.119  1754  1777 E LoadTask:      at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:130)
08-02 12:54:19.119  1754  1777 E LoadTask:      at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:835)
08-02 12:54:19.119  1754  1777 E LoadTask:      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)

**Comment by ojw28** [comment] 2017-08-02 14:24
What's wrong with the existing failure mode?

**Comment by dbedev** [comment] 2017-08-03 09:37
Not sure what would be considered right/wrong on this topic. I just started reading up on the failure handling for Exoplayer. What is the intended behavior ? Which kind of issues does the libary expect the app/ player level  to handle and which kind of issues will the library handle by itself ? And what level of information does exoplayer intend to give about encountered failures ?

If I read the code the for the "Unexpected exception loading stream" print  statement in Loader.java the the code comment states "This should never happen, but handle it anyway."  

According to the log it eventually does report a loadError towards the app, so will check on our app why it does not exit the playback because of this. 

Four our code we typically deal with java.lang.ArrayIndexOutOfBoundsException as being a programming error hence we would not want it to occur at all for our code.  So I was premature in assuming we should just avoid the exception. I guess from lib perspective it would be more generic to have some form of error reported back as it does now.  

Not sure if it is very usefull to just have a loadError reported for both data validity as data availability issues though. 

As the lib/player does seem to recover I agree  it seems more of a nice to have enhancement on error reporting than a really a bug.

**Comment by ojw28** [comment] 2017-08-03 10:15
The intended behavior is that playback fails and an error is propagated to the application (by the player invoking `EventListener.onPlayerError` on any registered listeners). The error will be an `ExoPlaybackException` and the `type` field will be set to `TYPE_SOURCE`, I think. This tells you the error was in loading/parsing as opposed to anything when rendering the media.

Calling `getSourceException` on the exception allows you to get the underlying exception, which will be the `ArrayIndexOutOfBoundsException`. This isn't particularly helpful, but unless you think your network stack throws runtime exceptions, you can probably reasonably accurately state that whenever the cause is a runtime exception, it's probably going to be a parsing failure, which is indicative of malformed media.

**Comment by ojw28** [comment] 2017-08-03 10:16
As a more fundamental question: How does you end up trying to play a corrupt MP4 in the first place? In any case where you control the content, you should never end up in such a position. If the user is sideloading content then you can't guarantee avoidance, but in this case showing a generic error for failures such as this seems adequate.

**Comment by dbedev** [comment] 2017-08-07 12:52
Thank you for the information, will look what we can implement in our app part by adding some logic to the listener.

"Control the content" still has many intermediate steps in our case so not sure if it does not fall in the side load category. In my experience so far a corrupt/ miss formed stream somehow seem to slip through eventually.  So would not consider it to be completely avoidable. 

In this case for example the prime root suspect is the IT managed update that got executed over the weekend and most likely messed up one of the automated upload jobs that should normally take care of streams being correct. 

For us the point is more that this kind of issue always gets pushed to the player device. Hence the question on how to accurately report the issue to user/tester from an app perspective as there is indeed nothing wrong at the player side in this case.

As such I still think it is a nice to have enhancement to get the library itself to tell the app what went wrong in stead of having to translate the encountered low level exception in the app.

**Comment by ojw28** [comment] 2017-08-07 13:00
It's not particularly feasible for the client to detect whether a stream is corrupt (and how) in the general case. It would be quite expensive and involve adding loads of sanity checks throughout the code base. This isn't a good trade-off. This is particularly true if the developer controls the serving-side. Running these kind of checks all of the time on every client just in case someone misconfigures something on the serving side doesn't seem like an appropriate trade-off, when there exists the alternative of ensuring there are sufficient serving side checks/tests in place to prevent this from happening.

So whilst I agree we should never crash when encountering malformed media, explicit stream sanity checking during playback and providing precise reasons for failure just doesn't seem like a good idea. Closing as a result; I think the existing exception gets you pretty close to being able to determine its a media issue in any case.

**Closed as completed by ojw28** 2017-08-07 13:00 UTC
Labels: question
