### ISSUE TITLE
Add an AviExtractor

### ISSUE THREAD

**Issue by xufuji456** [google/ExoPlayer#6352] opened 2019-08-29 06:31 UTC
description:
ExoPlayer can't play video of avi format, but Android system MediaPlayer can play.
It seems that MediaCodec support decode avi format.
When use ExoPlayer to play avi video, it throws an exception:

```
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, FlacExtractor) could read the stream.
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:232)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

Proposed solution:
Add an AviExtractor to support parsing the container of avi video.

**Comment by xufuji456** [comment] 2019-08-29 11:40
@marcbaechinger  Thank you for your quick response. Please let me know, if you need any other info about this issue. Thanks again sincerely. Wish ExoPlayer will become more and more perfect the day after tomorrow.

**Comment by ojw28** [comment] 2019-09-02 12:19
Duplicate of https://github.com/google/ExoPlayer/issues/2092

**Closed as completed by ojw28** 2019-09-02 12:19 UTC
Labels: duplicate, enhancement
