### ISSUE TITLE
Content failed after bitrate switch to HD in L3 device

### ISSUE THREAD

**Issue by rajeshghosh1978** [google/ExoPlayer#5166] opened 2018-11-28 20:48 UTC
### Issue description
I am trying to play a content in L3 device. It played for the first few seconds with the lowest bitrate (SD) but it gets failed when tries to switch to higher bitrate i.e HD. Based on our DRM policy it should fail in L3 device. But why Exopayer tries to switch to an upper bitrate when it knows the device doesn't have those capacities.

### Reproduction steps
I can't share the link of our content. But based on our DRM policy, it should play only SD in L3 device.

### Link to test content

I can't share the content link in anyways.

### Version of ExoPlayer being used
2.9.2

### Device(s) and version(s) of Android being used
Device Model Number : BLU ENERGY X PLUS . (L3 Device)
Android Version : 5.0

### A full bug report captured from the device

[L3.txt](https://github.com/google/ExoPlayer/files/2626538/L3.txt)

**Comment by ojw28** [comment] 2018-11-28 21:03
> But why Exopayer tries to switch to an upper bitrate when it knows the device doesn't have those capacities.

I think the short answer is that ExoPlayer doesn't know. We know that the MediaDrm implementation is L3, but we don't know which of the loaded keys are usable for decryption. L3 doesn't always mean HD wont work. That's a property of your license policies rather than the MediaDrm implementation itself.

There's platform APIs we can use on API level 23 and above to find out which keys are usable, but given nearly all developers are supporting earlier API levels, that points to the developer needing to filter unplayable streams at the application level anyway for older devices. Which makes it less urgent that we prioritize solving the problem on newer API levels.

If it turns out we can parse key usability directly from the key response, without using a platform API, then we can and should do that on all API levels. We need Widevine's input on whether that's possible.

Anyway, for now advice is for you to not select unplayable streams in application code, based on knowledge of your license policies. If your policy is that HD requires L1, you can simply query the MediaDrm level on device, and then set a resolution constraint on DefaultTrackSelector if it's only L3.

The issue itself is being discussed on #4825, so this is a duplicate of that issue.

**Closed as completed by ojw28** 2018-11-28 21:03 UTC
Labels: duplicate, question

**Comment by rajeshghosh1978** [comment] 2018-11-28 21:35
Thank you for your prompt response. I am able to play the content by restricting HD from app side using
trackSelector.setParameters(new DefaultTrackSelector.ParametersBuilder().setMaxVideoSize(1008,719));

**Comment by jhnbwrs** [comment] 2019-03-01 04:22
This actually works with Shaka player just so you know.   I know the API's are different for web vs native and maybe there is nothing you can easily do, but you might look at what they did and consider if you can do something similar or provide some sort of solution here.  We have the same issue switching to HD on an L3 device.   Security level 4 is required by our Policy for HD, and having playback just fail when an L3 device attempts to switch to HD is a pretty lousy playback experience.

https://github.com/google/shaka-player/issues/652

**Comment by ojw28** [comment] 2019-03-04 08:46
> having playback just fail when an L3 device attempts to switch to HD is a pretty lousy playback experience.

There's no requirement that this is your end user app experience, since you have all the information you need to avoid ending up in this state (i.e. you can query the device to determine whether it's L1 and L3, and you know what your license policies are).

> This actually works with Shaka player just so you know.

My interpretation of that thread is that it works correctly on API level 23 and above, and most likely blanket limits to SD on API level 22 and below, based on the "in the absence of information, we act conservatively to avoid a critical failure" together with the fact that there's no API to determine key status on earlier API levels. We do intend to start querying key status on API level 23 and above, which is what #4825 is tracking. However until apps start dropping support for earlier API levels, I think the best option is still for an app to use the specific knowledge that it has to do the right thing. It's a bit more work for the app developer, but it seems better than having the player just blanket limit to SD on many older devices.
