### ISSUE TITLE
Get few seconds black screen when switching to empty mid roll with DRM protected video

### ISSUE THREAD

**Issue by z423821123** [google/ExoPlayer#8568] opened 2021-02-09 09:48 UTC
[REQUIRED] Issue description
-------------------------
Playing DRM protected video in empty mid roll will appear about 1 seconds black screen. It's easy to reproduce in demo app. 

[REQUIRED] Reproduction steps
-------------------------
1. Add this ads tag uri "https://vastsynthesizer.appspot.com/empty-midroll-2" info DRM protected video in demo app
```json
"name": "Widevine DASH (MP4, H264)",
    "samples": [
      {
        "name": "HD (cenc)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?provider=widevine_test",
        "ad_tag_uri": "https://vastsynthesizer.appspot.com/empty-midroll-2"
      },
      {
        "name": "UHD (cenc)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears_uhd.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
      },
      {
        "name": "HD (cbcs)",
        "uri": "https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
      },
      {
        "name": "UHD (cbcs)",
        "uri": "https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs_uhd.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
      },
      {
        "name": "Secure -> Clear -> Secure (cenc)",
        "uri": "https://storage.googleapis.com/exoplayer-test-media-1/widevine/tears_enc_clear_enc.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?provider=widevine_test",
        "drm_session_for_clear_content": true
      }
    ]
  }
```
2.Click HD(cenc) 
![image](https://user-images.githubusercontent.com/26051891/107344364-52010200-6afd-11eb-961a-6ac3b5de7956.png)

3.Found that frame become black  about 1 seconds  with the second empty mid roll 

[REQUIRED] Version
-------------------------
2.13.0

[REQUIRED] Device 
-------------------------
Samsung Galaxy S10, Android 10

**Comment by icbaker** [comment] 2021-02-09 15:30
I can't reproduce what you're seeing with a Pixel 3a XL.

However I suspect it might be related to switching between secure and clear decoders. Can you try adding `"drm_session_for_clear_content": true` to the same JSON snippet and see what happens?
```
{
  "name": "HD (cenc)",
  "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
  "drm_scheme": "widevine",
  "drm_license_uri": "https://proxy.uat.widevine.com/proxy?provider=widevine_test",
  "ad_tag_uri": "https://vastsynthesizer.appspot.com/empty-midroll-2",
  "drm_session_for_clear_content": true
},
```

More info: https://exoplayer.dev/drm.html#drm-sessions-for-clear-content

**Comment by z423821123** [comment] 2021-02-10 03:14
Still reproduce in demo app when I adding `"drm_session_for_clear_content": true` to the JSON. I will email the attachment to `dev.exoplayer@gmail.com`

**Comment by icbaker** [comment] 2021-02-11 14:56
Thanks for trying that - sorry it didn't work. I took a closer look and realised the `drm_session_for_clear_content` flag isn't properly propagated all the way down when using the `MediaItem` API. I've sent a change to fix that.

I determined I couldn't reproduce because the symptom is device specific - a colleague was able to reproduce with their Samsung device.

**Comment by z423821123** [comment] 2021-02-16 08:49
Thanks for your support,But I tested 2.13.1 and it still getting black frame 1 seconds when the timeline approaches empty vast ad break, and I pass `"drm_session_for_clear_content": true` value to JSON haven't any help.

I assume that `AdsMediaSource` has update source information which is `AD_STATE_ERROR` `AdPlaybackState` via `maybeUpdateSourceInfo()`.
 
```
 private void maybeUpdateSourceInfo() {
    @Nullable Timeline contentTimeline = this.contentTimeline;
    if (adPlaybackState != null && contentTimeline != null) {
      adPlaybackState = adPlaybackState.withAdDurationsUs(getAdDurationsUs());
      Timeline timeline =
          adPlaybackState.adGroupCount == 0
              ? contentTimeline
              : new SinglePeriodAdTimeline(contentTimeline, adPlaybackState);
      refreshSourceInfo(timeline);
    }
  }
```
@icbaker @ojw28

**Comment by icbaker** [comment] 2021-02-17 12:35
You're right - there's two different things interacting here and we only fixed one of them.

Specifically when the mid-roll is empty we still release and re-initialize the (secure) video decoder.

With `"drm_session_for_clear_content": false` you can see the secure decoder being released and replaced by an insecure video decoder for each non-empty midroll (10s and 30s). But at the empty one (12.2s) we just release & immediately reacquire the secure decoder:
```
videoDecoderInitialized [eventTime=1.19, mediaPos=0.00, window=0, period=0, c2.qti.avc.decoder.secure]               
videoDecoderReleased [eventTime=11.71, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, c2.qti.avc.decoder.secure]
videoDecoderInitialized [eventTime=11.81, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, c2.qti.avc.decoder]    
videoDecoderReleased [eventTime=21.75, mediaPos=10.00, window=0, period=0, c2.qti.avc.decoder]                       
videoDecoderInitialized [eventTime=21.87, mediaPos=10.00, window=0, period=0, c2.qti.avc.decoder.secure]             
videoDecoderReleased [eventTime=24.05, mediaPos=12.21, window=0, period=0, c2.qti.avc.decoder.secure]                
videoDecoderInitialized [eventTime=24.38, mediaPos=12.21, window=0, period=0, c2.qti.avc.decoder.secure]             
videoDecoderReleased [eventTime=42.51, mediaPos=0.00, window=0, period=0, adGroup=2, ad=0, c2.qti.avc.decoder.secure]
videoDecoderInitialized [eventTime=42.60, mediaPos=0.00, window=0, period=0, adGroup=2, ad=0, c2.qti.avc.decoder]    
videoDecoderReleased [eventTime=52.56, mediaPos=30.00, window=0, period=0, c2.qti.avc.decoder]                       
videoDecoderInitialized [eventTime=52.66, mediaPos=30.00, window=0, period=0, c2.qti.avc.decoder.secure]             
```

With `"drm_session_for_clear_content": true` the secure decoder is kept for both the non-empty midrolls, but it's **still** released/reacquired at the empty one:
```
videoDecoderInitialized [eventTime=1.28, mediaPos=0.00, window=0, period=0, c2.qti.avc.decoder.secure]
videoDecoderReleased [eventTime=24.26, mediaPos=12.24, window=0, period=0, c2.qti.avc.decoder.secure]
videoDecoderInitialized [eventTime=24.60, mediaPos=12.24, window=0, period=0, c2.qti.avc.decoder.secure]
``` 

This is what's causing the black screen you're seeing.

I foolishly only checked that the decoder was kept for the non-empty midroll when testing (because that fires first) and didn't consider there might be a secondary behaviour that only affects empty ones.

Re-opening to track keeping decoders alive during empty mid-roll ads.

**Comment by icbaker** [comment] 2021-05-20 11:06
The secure decoder re-initialization is fixed by removing the `TODO` and associated logic discussed in https://github.com/google/ExoPlayer/issues/8842#issuecomment-843047273.

I'll dupe this to that (since it affects more than just empty mid-rolls) - please follow that issue for further updates.

**Closed as completed by icbaker** 2021-05-20 11:06 UTC
Labels: bug, documentation candidate
