### ISSUE TITLE
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/dolby-vision, hev1.08.04, -1, null, [1920, 1080, 29.978088], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#9474] opened 2021-09-23 09:19 UTC
ExoPlayer version number 2.15.0
Android version 10, 11
Android device:
- Emulator: 720 x 1600, api 29 (Android 10), RAM size 1536
- Vivo V2027 Android: 10 RAM: 4G
- Oppo A73 Android: 11
---------
- I try use ExoPlayer to play video, some video work find, some get an error:
`com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/dolby-vision, hev1.08.04, -1, null, [1920, 1080, 29.978088], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES`
- More info about video error:
dimensions: 1080 x 1920
codecs: AAC, HEVC
colour profile: BT.2020 HLG (9-18-9)
type: .mp4 (i also setMimeType(MimeTypes.APPLICATION_MP4) for exo player)
- I searched in issues tap but haven't found a solution yet, pls help me!

**Comment by icbaker** [comment] 2021-09-23 09:48
Please can you try on 2.15.1? This might be resolved by https://github.com/google/ExoPlayer/commit/54418eb644ac3b0330a1ad6154a5a9417a83207e

**Comment by ghost** [comment] 2021-09-27 03:13
> Please can you try on 2.15.1? This might be resolved by [54418eb](https://github.com/google/ExoPlayer/commit/54418eb644ac3b0330a1ad6154a5a9417a83207e)

@icbaker i tried and failed

**Comment by icbaker** [comment] 2021-09-27 11:16
Please provide media we can use to reproduce the problem and an `adb bugreport` taken after reproducing the failure in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html).

Please either upload these here or send them to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by ghost** [comment] 2021-09-29 03:04
> Please provide media we can use to reproduce the problem and an `adb bugreport` taken after reproducing the failure in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html).
> 
> Please either upload these here or send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

@icbaker i sent an email to dev.exoplayer@gmail.com. Hope to hear from you soon. Thank you!

**Comment by icbaker** [comment] 2021-09-30 10:34
Thanks for the videos. Both play fine on a physical Pixel 5 on Android 12. Both fail to play on an emulated Pixel 5 on Android 12.

There's no requirement for Android devices to support Dolby Vision (or HDR content in general: https://source.android.com/devices/tech/display/hdr). It's up to the app to check for compatibility before trying to play content like this.

So I suspect that the devices where you see playback failures don't support this content, and that's expected.

**Comment by ghost** [comment] 2021-09-30 12:41
> So I suspect that the devices where you see playback failures don't support this content, and that's expected.
------------------
@icbaker Yepp!! The devices don't support to play the videos, call onPlayerError() has called and i handle it with sendCustomMessage() to show error message to user. 
Unfortunately, i have an issue when i play this videos on device Huawei (OS: Android 9, Resolution: 2340x1080, CPU: Hisilicon Kirin 710, RAM: 4 GB). In callback onPLaybackStateChanged(), i seen state of player change from ExoPlayer.STATE_BUFFERING to ExoPlayer.STATE_READY, player controller also run after secondary progress load full, but no any frame generated.
Can you support me for this issue?
I can provide video test if you need.

**Comment by icbaker** [comment] 2021-09-30 12:55
If the device reports this as `format_supported=NO_EXCEEDS_CAPABILITIES` then that's likely expected. The device has said 'I don't support this format', but we still try and play because often it still works (and the alternative is just not playing it, which seems strictly worse).

If the device reports this as `format_supported=YES` then that seems more surprising - can you provide an `adb bugreport` from playing in the demo app on that device?

**Comment by ghost** [comment] 2021-09-30 12:58
@icbaker when i play this videos on device Huawei, callback onPlayerError() not called, how i can provide an `abd bugreport`?

**Comment by icbaker** [comment] 2021-09-30 13:03
https://developer.android.com/studio/debug/bug-report

**Comment by ghost** [comment] 2021-10-04 01:42
@icbaker hey bro, i sent an email with `adb bugreport` file details attachment to dev.exoplayer@gmail.com. Please check it. Thankiu!

**Comment by icbaker** [comment] 2021-10-04 15:19
Thanks for the bugreport, but it doesn't seem to contain any of the logging I'd expect to see from a playback in the [demo app](https://exoplayer.dev/demo-application.html). Did you capture this after reproducing the problem in the demo app? Specifically I'd expect to see a large number of lines from `EventLogger` because the demo app enables additional debug logging as described here: https://exoplayer.dev/debug-logging.html

**Comment by ghost** [comment] 2021-10-07 04:20
@icbaker i sent an email attachments debug logging to dev.exoplayer@gmail.com. Please check it again!

**Comment by icbaker** [comment] 2021-10-08 17:07
The drive link provided over email seems to be restricted, I'm not able to access it.

**Comment by ghost** [comment] 2021-10-09 04:39
@icbaker sorry, please check again. i sent a new one

**Comment by icbaker** [comment] 2021-10-18 13:06
Thanks, I took at a look at `bug_report.txt`.

Everything seems to be working as intended for `video_error_1.mp4`. The decoder reports `format_supported=NO_EXCEEDS_CAPABILITIES` and then it throws an exception.

----

For `video_error_2.mp4`, the logging suggests the decoder does support the video (`supported=YES`). Are you saying that when you play this video nothing is shown on screen?

Unfortunately there isn't enough info in the logcat snippet provided to see if there's any logs from MediaCodec during playback. Please capture a full bug report (`adb bugreport`) rather than just logcat snippets, as the bug report contains additional info that may help us to understand the issue.

**Comment by ghost** [comment] 2021-11-05 02:11
> Hey @baonq-2356. We need more information to resolve this issue but there hasn't been an update in 14 weekdays. I'm marking the issue as stale and if there are no new updates in the next 7 days I will close it automatically.
> 
> If you have more information that will help us get to the bottom of this, just add a comment!

@icbaker  @google-oss-bot ohh sorry, i still need your help to resolve this issue, i will provide more information but now i am not free. You can close this issue now but i hope when i already available then i can immediately reopen it. Thank you so much!

**Closed as completed** 2021-11-19 16:31 UTC
Labels: question
