### ISSUE TITLE
use setVolume(0F) to mute, after phone call, the video playing with audio

### ISSUE THREAD

**Issue by FrankdeBoers** [google/ExoPlayer#8451] opened 2021-01-12 12:33 UTC
i  use exoplayer version 2.12.2, and `player.setVolume(0F)` to mute video, it worked.
then phone call coming, after i hang up, the demo plays with audio.

i debug, found exoplayer use `AudioFocusListener`, when audioFocus loss and gain again, whether the volume is 0 or 1, exoplayer will `setVolume(manager.getStreamVolume(AudioManager.STREAM_MUSIC).toFloat())`

exoplayer should keep volume 0F whether audiofocus changes.

I reproduce this in Xiaomi5X and Xiaomi 9.

ExoPlayer version number: 2.12.2
Android version: 8 and 10
Android device:  Xiaomi5X and Xiaomi 9

Thanks!

**Comment by lcf87** [comment] 2021-01-12 13:24
@krocard Kevin could you take a look at this?

**Comment by krocard** [comment] 2021-01-12 14:40
> exoplayer should keep volume 0F whether audiofocus changes.

Agreed, the volume should be restored identically when the audio focus is regained. I believe though that it is the current behaviour of ExoPlayer.

> i debug, found exoplayer use `AudioFocusListener`, when audioFocus loss and gain again, whether the volume is 0 or 1, exoplayer will `setVolume(manager.getStreamVolume(AudioManager.STREAM_MUSIC).toFloat())`

I'm sorry but I can't reproduce in our demo app, nor find any interaction in the code between  ExoPlayer's [AudioFocus handling code](https://github.com/google/ExoPlayer/blob/r2.12.2/library/core/src/main/java/com/google/android/exoplayer2/AudioFocusManager.java) and the stream volume.

As a matter of fact, I can't find any other place than in `StreamVolumeManager` where `AudioManager.getStreamVolume` is used. And `StreamVolumeManager` is only used on direct calls from the app (`Player.getDeviceVolume`) or UI update.

Could you please point me to where you found such logic implemented during your debugging?

**Comment by ojw28** [comment] 2021-01-12 15:14
This is probably a duplicate of https://github.com/google/ExoPlayer/issues/3923. Note that it was a platform issue, not an issue with ExoPlayer. The issue was fixed in [this platform commit](https://android.googlesource.com/platform/frameworks/base/+/8ba7d406025afc6a993845c5b953a51c9a5c86d7).

This would explain why @krocard cannot find any corresponding code in ExoPlayer. There is not a known workaround for the issue, unfortunately. It might work to re-apply the volume somehow, but the difficulty is knowing _when_ to do so.

**Comment by krocard** [comment] 2021-01-13 09:48
I had forgotten this old issue. I agree with @ojw28 that it would be quite difficult to know when to re-apply the volume.
I think the only case where this could be safely done, would be if the player is paused after the loss of audio focus due to the phone call. When audio focus is re-aquired after the call, the volume could be re-set before resuming playback.

**Comment by FrankdeBoers** [comment] 2021-01-14 08:51
> This is probably a duplicate of #3923. Note that it was a platform issue, not an issue with ExoPlayer. The issue was fixed in this platform commit.
> 
> This would explain why @krocard cannot find any corresponding code in ExoPlayer. There is not a known workaround for the issue, unfortunately. It might work to re-apply the volume somehow, but the difficulty is knowing when to do so.


@ojw28 Thanks, i think my problem is same with #3923.

> but the difficulty is knowing when to do so.

i add OnAudioFocusChangeListener, after audiofocus regain, i do this:
```
private var onAudioFocusChangeListener = OnAudioFocusChangeListener { focusChange ->
        when (focusChange) {
            AudioManager.AUDIOFOCUS_GAIN -> {
               for (i in 0 until 500) {
                   exoPlayer.volume = 0.001F
                   exoPlayer.volume = 0F
              }
            }
        }
    }
```
this is violent but effective, and 500 times is the result after my try, different devices might has different re-apply times.

**Comment by krocard** [comment] 2021-01-14 10:31
I don't think you would need to set it to 0.001F before setting it to 0.
Additionally, are you sure you need this loop at all? Is the volume really set to 1 by the system after your app receive the audiofocus GAIN?

Of course this is a workaround that ExoPlayer can use itself, but if it works for your app use-case, I think it is good enough.

**Comment by krocard** [comment] 2021-01-14 10:53
Closing issue as duplicate of #3923 as ExoPlayer cannot workaround the problem which is fixed in Android 10.

**Closed as completed by krocard** 2021-01-14 10:53 UTC
Labels: bug

**Comment by FrankdeBoers** [comment] 2021-01-15 09:04
@krocard 
> I don't think you would need to set it to 0.001F before setting it to 0.

in SDK's source code (SimpleExoPlayer.java)

```
@Override
  public void setVolume(float audioVolume) {
    verifyApplicationThread();
    audioVolume = Util.constrainValue(audioVolume, /* min= */ 0, /* max= */ 1);
    if (this.audioVolume == audioVolume) {
      return;
    }
    this.audioVolume = audioVolume;
    sendVolumeToRenderers();
    for (AudioListener audioListener : audioListeners) {
      audioListener.onVolumeChanged(audioVolume);
    }
  }
```


  
```
if (this.audioVolume == audioVolume) {
      return;
    }
```


if setting the same volume value, it returns.   
So i have to set set it to 0.001F before setting it to 0.  And 0.001F is low enough to avoid crackle.

**Comment by krocard** [comment] 2021-01-15 10:53
Indeed setting alternating values is needed.
