### ISSUE TITLE
Video playback freezes after closed captions track change

### ISSUE THREAD

**Issue by alexeyr15** [google/ExoPlayer#8203] opened 2020-11-11 09:55 UTC
### [REQUIRED] Issue description
Video playback freezes after changing the closed captions track when using FFmpeg extension.

### [REQUIRED] Reproduction steps
1. Build ExoPlayer Demo app with FFmpeg extension enabled (use "withDecoderExtensions" build variant also)
2. Play the provided test stream
3. Open the track selection dialog and change the closed captions track
4. Video playback freezes

### [REQUIRED] Link to test content
Provided by email.

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
No device specific

**Comment by kim-vde** [comment] 2020-11-11 11:59
I get a 404 when opening the link you sent by email. Could you please send a new link and update this issue when you have done it?

**Comment by alexeyr15** [comment] 2020-11-11 15:38
I have updated the link.

**Comment by skogl** [comment] 2020-11-16 10:10
I can see this issue as well after upgrading from 2.11.5 to 2.12.1. The issue is only noticed when actually using a ffmpeg audio track and then switching text track. If I were to play a stream which is supported by my device (and ffmpeg is not needed) I do not see this issue.

**Comment by skogl** [comment] 2020-11-18 10:19
Is this issue being looked at? It really makes an upgrade impossible.

**Comment by ojw28** [comment] 2020-11-18 17:26
Yes. This is a fairly obscure issue where `MediaCodecAudioRenderer` (which is not being used) inadvertently resets the state of the `AudioSink` that's shared across all of the audio renderers.

As a workaround, you can implement an `RenderersFactory` to provide each audio renderer with its own `AudioSink`, rather than doing what `DefaultRenderersFactory` is doing and sharing a single instance.

**Comment by ojw28** [comment] 2020-11-19 10:18
I got a few class names wrong in my response above, so it didn't make much sense. I've updated it to be correct now (if reading by email, please open the thread on GitHub to see the correct version). Thanks!

**Comment by skogl** [comment] 2020-11-19 10:23
Thank you for your answer. I was just composing my answer with a question if you meant `RenderersFactory` and not `ExtractorsFactory`.
The workaround is working.

**Comment by ojw28** [comment] 2020-11-19 17:15
This is fixed by the change ref'd above. We'll include this in `2.12.2`, which is due in the next couple of weeks. Note that:

1. Once using `2.12.2`, the workaround will be unnecessary.
1. We didn't fix this by having each renderer use its own `AudioSink`. Instead, we fixed the problem that was causing sharing of the `AudioSink` to not work.

**Closed as completed by ojw28** 2020-11-19 17:15 UTC
Labels: bug
