### ISSUE TITLE
RTMP - Player transitions to STATE_ENDED before stream ends

### ISSUE THREAD

**Issue by jinfanzon** [google/ExoPlayer#4337] opened 2018-06-01 18:01 UTC
Hi, I've recently implemented the RTMP exo player extension, and the stream is correct, but randomly  after a certain amount of time the screen freezes, with no exception being thrown. After adding some logs, I can see the the player listener **onPlayerStateChanged** is triggered with state ENDED. I'm appending a section of my code

This is how I initialize the player:

`          

@Override

            public void onResponse(Call call, Response response) throws IOException {

                RtmpDataSourceFactory rtmpDataSourceFactory = new RtmpDataSourceFactory();

                MediaSource mediaSource = new ExtractorMediaSource.Factory(rtmpDataSourceFactory)
                        .createMediaSource(Utils.streamURLGenerator(
                                response.body().string(),
                                findChannel(PreferenceUtils.getStringPreferences("CHANNEL", "")).getId()));

                player.prepare(mediaSource, true, true);

                player.setPlayWhenReady(true);
            }
`

This is how the URL is being created:

`
 
   public static Uri streamURLGenerator(String loadBalancerUrl, String channel)

    {

        return Uri.parse("http://"+loadBalancerUrl+":1935/live/"+channel+" live=1");

    }
`

Why is it going to state ENDED? Is there a workaround to recover or avoid this state?

I'll be appending in an email the stream url.

**Comment by jinfanzon** [comment] 2018-06-01 18:13
``

**Comment by ojw28** [comment] 2018-06-04 10:19
I found some simpler reproduction steps involving toggling airplane mode on and off again. This appears to be an issue in LibRtmp rather than ExoPlayer, which I've reported here: https://github.com/ant-media/LibRtmp-Client-for-Android/issues/69

**Comment by ojw28** [comment] 2018-06-04 10:45
The only workaround I can think of, until the root cause is fixed in the dependency, is to listen for state changes to the ended state, and re-prepare the player when such a transition occurs.

**Closed as completed** 2019-09-01 22:26 UTC
Labels: bug: in dependency
