### ISSUE TITLE
playing instagram cache chunks

### ISSUE THREAD

**Issue by sajjadyousefnia** [google/ExoPlayer#5106] opened 2018-11-14 18:50 UTC
I want to play instagram videocahce chunk files which have .exo format, how can i play them with cachedatasource in exoplayer?

**Comment by tonihei** [comment] 2018-11-15 09:02
That's a duplicate of #4937. 

Given that the downloaded files are not from your app, you probably shouldn't play them anyway. They may also be encrypted.

**Closed as completed by tonihei** 2018-11-15 09:02 UTC
Labels: duplicate
