### ISSUE TITLE
ArrayIndexOutOfBoundsException on MPEG-TS

### ISSUE THREAD

**Issue by xuxucode** [google/ExoPlayer#1875] opened 2016-09-29 17:01 UTC
```
E/LoadTask: Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=19; index=21
        at com.google.android.exoplayer2.audio.Ac3Util.getAc3SyncframeSize(Ac3Util.java:234)
        at com.google.android.exoplayer2.audio.Ac3Util.parseAc3SyncframeSize(Ac3Util.java:183)
        at com.google.android.exoplayer2.extractor.ts.Ac3Extractor.sniff(Ac3Extractor.java:109)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:657)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:592)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

I use dev-v2 (2016-09-29) ExoPlayer to play a mpeg-ts stream on the Amlogic Venz tv box, this exception occurs sometimes.

**Comment by AquilesCanta** [comment] 2016-09-29 17:44
I have an idea of what the problem is, but please provide a piece of media that reproduces the issue, as stated in the issue template.

**Comment by xuxucode** [comment] 2016-10-04 10:12
Thanks, I've tried many times, but it's hard to reproduce when playing a piece of problematic media extracted from live MPEG-TS. In general this happens to the live.

**Comment by AquilesCanta** [comment] 2016-10-04 10:24
Okay, I will try to provide a fix for this by the next push hoping it is what I suspect. Once the fix is pushed we will close this. If you run into this again, just open a new issue. Make sure you include media to reproduce this! Thanks for reporting this.

**Closed as completed** 2016-10-04 22:47 UTC
Labels: bug
