### ISSUE TITLE
Can not play midroll

### ISSUE THREAD

**Issue by z423821123** [google/ExoPlayer#8428] opened 2021-01-05 06:48 UTC
[REQUIRED] Issue description
-------------------------

- When I first initialize the player and jump to the position behind of the midroll, I can't play the midroll. I confirm that it works fine with Exoplayer 2.11.0. However when I upgrade Exoplayer to 2.12.2 and this issue was happened. It is easy to reproduce in demo app.

[REQUIRED] Reproduction steps
-------------------------

1. Call seekto() in demo app, such as player.seekTo(startWindow, 60000);
2. Select this item in demo app
![image](https://user-images.githubusercontent.com/26051891/103614356-5ddc3000-4f63-11eb-8104-973b265025c3.png)
3.Can not play mid-roll 

Here is the ImaAdsLoader debug log

2021-01-05 14:27:56.798 11876-11876/com.google.android.exoplayer2.demo W/ImaAdsLoader: onEnded without ad media info
2021-01-05 14:28:07.457 11876-11876/com.google.android.exoplayer2.demo I/ImaAdsLoader: AdEvent: {errorMessage=VAST media file loading reached a timeout of 8 seconds., errorCode=402, type=adPlayError}

[REQUIRED] Version of ExoPlayer being used
-------------------------
2.12.2

[REQUIRED] Device(s) and version(s) of Android being used
-------------------------
Samsung Galaxy S10, Android 10

**Comment by z423821123** [comment] 2021-01-15 07:25
Hi @andrewlewis , could you take a look？

**Comment by sravan1213** [comment] 2021-01-15 08:37
looks like duplicate of https://github.com/google/ExoPlayer/issues/8349

**Comment by z423821123** [comment] 2021-01-15 09:18
It's still happened with exoplayer 2.12.3

**Comment by z423821123** [comment] 2021-01-15 09:19
It's still happened with exoplayer 2.12.3 @sravan1213

**Comment by z423821123** [comment] 2021-01-15 09:36
I tested with Exoplayer 2.12.3, but it didn't go well.
1st pre-roll is in 00:00:00, 2st mid-roll in 00:05:00, 3st mid-roll in 00:10:00
The 1st pre-roll was played successfully  when I skip to 3 minutes(00:03:00).
The 2st mid-roll still cannot played when I skip to 7 minutes(00:07:00).
@sravan1213

**Comment by z423821123** [comment] 2021-01-18 09:28
@andrewlewis can you have a look?

**Comment by andrewlewis** [comment] 2021-01-21 10:06
Thanks for reporting. Just after we report the seek position to the IMA SDK we get `CONTENT_RESUME_REQUESTED` then `CONTENT_PAUSE_REQUESTED` for the ad. The problem is that the first `CONTENT_RESUME_REQUESTED` is interpreted as a request to skip the ad by IMA extension, due to the workaround added to skip VPAID ads in #7832. I will revert that workaround and replace it with a more robust workaround where we instead timeout loading an initial VPAID ad, which should fix the regression.

**Closed as completed** 2021-02-01 18:16 UTC
Labels: bug
