### ISSUE TITLE
java.io.EOFException Playing DASH url from Background after player release and reinitialize 

### ISSUE THREAD

**Issue by manishmips** [google/ExoPlayer#2435] opened 2017-02-09 18:01 UTC
I am using r2.2.0 and getting exception while playing video using DASH url .Scenario is while I pressed home button between playing content some time its resume video but some time I am getting java.io.EOFException following is exception log please help .

```logcat
EventLogger: internalError [3.97, loadError] java.io.EOFException at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252) at
com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67) at
com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76) at
com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:346) at
com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:248) at
com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127) at 
com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) at
java.util.concurrent.FutureTask.run(FutureTask.java:237) at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

ExoPlayerImplInternal: Source error. java.io.EOFException at
com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252) at
com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67) at
com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76) at
com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:346) at
com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:248) at
com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127) at
com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) at
java.util.concurrent.FutureTask.run(FutureTask.java:237) at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at
java.lang.Thread.run(Thread.java:841) E/EventLogger: playerFailed [3.98] 

com.google.android.exoplayer2.ExoPlaybackException at
com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:345) at
android.os.Handler.dispatchMessage(Handler.java:98) at
android.os.Looper.loop(Looper.java:136) at
android.os.HandlerThread.run(HandlerThread.java:61) at
com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) Caused by: 

java.io.EOFException at
com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:252) at
com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:67) at
com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:76) at
com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:346) at
com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:248) at
com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127) at
com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) at
java.util.concurrent.FutureTask.run(FutureTask.java:237) at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at
java.lang.Thread.run(Thread.java:841)
```

**Comment by AquilesCanta** [comment] 2017-02-09 18:11
Please provide all the information required in the issue template.

**Comment by manishmips** [comment] 2017-02-10 05:24
Thanks for response can you explain which type of information you required from my side 
Steps to reproduce issue
gradel dependecy
`compile 'com.google.android.exoplayer:exoplayer:r2.2.0'`
` compileSdkVersion 24
        buildToolsVersion '24.0.2'
        minSdkVersion 16
        targetSdkVersion 24`
Android version 4.4.4 api 19
and lollipop 

1. Playing DASH url from exoplayer 
2. In between video playing player release
3. Again initialize player it seek to current resume postion
 ` resumeWindow = player.getCurrentWindowIndex();
        resumePosition = player.isCurrentWindowSeekable() ? Math.max(0, player.getCurrentPosition()): C.TIME_UNSET;`
.Some time it resume and play video very fine but some time its call Player error state 
4 .On playerError state I am showing retry button and from retry button 
`initializePlayer()` but it never resume again 
5. when I seek it to start postion retry start work 

I have observed that when I get error some times `player.isCurrentWindowSeekable()` giving me false 
on override method 

` @Override
    public void onPositionDiscontinuity() {
        if (playerNeedsSource) {
            resumeWindow = player.getCurrentWindowIndex();
        resumePosition = player.isCurrentWindowSeekable() ? Math.max(0, player.getCurrentPosition()): C.TIME_UNSET;
        }
    }` 


IF you got my problem please suggest me

**Comment by RamIndani** [comment] 2017-02-11 01:42
I am facing similar issue on Android 5.1 - please update if found solution.

**Comment by ojw28** [comment] 2017-02-13 17:06
Can you explain how to reproduce this using the ExoPlayer demo app, or some minimal variant of it? Does it only reproduce for certain streams? If so, please provide one that reproduces the issue.

**Comment by manishmips** [comment] 2017-02-15 09:31
This issue occurs when I press home and then resume again and again 
I have observed a case when I hit retry its not resume but when I drag seek bar it to start position  Player resume from start correctly .

This scenario occurs in Demo also but player set to start position automatically

**Comment by ojw28** [comment] 2017-02-15 15:34
Please can you provide precise reproduction steps for the demo app (i.e. exactly which stream you're playing, exactly what steps you're following, and how often the issue reproduces)? There's really not enough information here for us to reproduce the issue.

**Comment by manishmips** [comment] 2017-02-16 11:35
@ojw28 
Just talking about Exoplayer demo application I am sharing a video with reproduction steps on youtube 
`Device version -kitkat 4.4.4
Model number -HM NOTE 1LTE`

**Video url -https://www.youtube.com/watch?v=pRi7bJJcACE**
In video I am playing from demo video list  **Widevine DASH :MP4,H264** ->first video 

1. Open video and select above video for playing
2. seek video to a particular position 
3.Now press home button and open app from recent again and again after 4-5 time 
4. Video starts from starting position 
I have attached full log 
[exolog.txt](https://github.com/google/ExoPlayer/files/779927/exolog.txt)

**Comment by ojw28** [comment] 2017-02-16 17:51
There's no EOFException in the latest attached log. Neither is there any visible failure in the attached video. It's very unclear what the issue is you're trying to report.

**Comment by ojw28** [comment] 2017-02-16 17:51
I see the playback starting from the beginning rather than the previous position, but this seems to be completely unrelated to the rest of this issue, which is about EOFException?

**Comment by manishmips** [comment] 2017-02-17 06:59
Yes its completely unrelated but with my streaming url for same scenario I
am getting EOFException .I just wanted to know particular problem arise
with me only .I am using amazon DASH url .Should I handle EOFException
onPlayerError()?

**Comment by ojw28** [comment] 2017-02-17 14:42
Despite multiple requests, you've yet to provide proper reproduction steps for the issue being reported. I'm going to close this. If you want to file a new issue that includes all of the information that's clearly requested in the issue template, please feel free to do so!

**Closed as completed by ojw28** 2017-02-17 14:42 UTC
Labels: need more info
