### ISSUE TITLE
HLS precaching

### ISSUE THREAD

**Issue by ArunkarthickNallasamy** [google/ExoPlayer#8780] opened 2021-03-30 12:46 UTC
I know there are so many questions related to HLS preaching but i am not sure what is the working solution. 
What we have achieved so far:-
We were able to precache an mp4 video by defining size in DataSpec
```
 var customSpecBuilder = DataSpec.Builder()
                            .setUri(Uri.parse(videoUrl))
                            .setLength((0.5*1024*1024).toLong())
                            .setKey(cacheKey)
                            .build()
                    val dataSource: DataSource =
                            DefaultDataSourceFactory(
                                    context,
                                    Util.getUserAgent(context, "Playback")
                            ).createDataSource()
                            
                            val cacheDataSource = CacheDataSource(simpleCache, dataSource)
                            val cacheWriter = CacheWriter(
                                    cacheDataSource,  // Your cache data source which is used for playback also
                                    customSpecBuilder,  // the data spec for which you want to cache data. See DataSpec.Builder to see how
                                    // to restrict to the start of the file only.
                                    /* allowShortContent= */
                                    true,  // Whether it's allowed for the content to end before the request
                                    /* temporaryBuffer= */
                                    null  // likely to be just null in your use case
                                    /* progressListener= */
                            ) { requestLength, bytesCached, _ ->
                                }

                            } 
                            cacheWriter.cache()
```
Question is, Is there a way we can cache an m3u8 file to 3 or 4 sec or for first 500kb of it?

**Comment by ArunkarthickNallasamy** [comment] 2021-03-31 05:33
I get 

>  com.google.android.exoplayer2.upstream.DataSourceException

 when i send a m3u8 url in DataSpec.Builder() for cacheWriter.cache()

**Comment by lcf87** [comment] 2021-03-31 13:35
I'm not sure I understand what you mean. Do you want to pre-buffer some HLS content for some duration? That is achievable with `LoadControl`.
Or, is it "downloading" the first 5 second worth of media before hand, in case the user may hit the play button?

**Comment by ArunkarthickNallasamy** [comment] 2021-03-31 13:51
When we mean precache we want to cache certain portion of URL's without passing URL to the player, FYI URL can be either mp4 or HLS. We were able to precache mp4 url's with help of cacheWriter for sizes we define but the same function is failing if an HLS is supplied. The idea behind precaching is to load videos faster when user scrolls to the cached URL's position in the list.

**Comment by lcf87** [comment] 2021-03-31 15:00
I still don't understand. Do you want to "precache" before or after the playback has started? I assume it's after based on your explanation.

> The idea behind precaching is to load videos faster when user scrolls to the cached URL's position in the list.

What do you mean by cached URL's position? What list are you referring to?

**Comment by ArunkarthickNallasamy** [comment] 2021-03-31 15:21
We need to precache before playback has started. 
`What do you mean by cached URL's position? What list are you referring to?`
Videos are played in a RecyclerView, so while i am in video 1, I would like to preload video 2,3,4 behind the screens. Todo so i am using cacheWriter.cache() for mp4 url's, is there anything similar to this for HLS? Is it still unclear?

**Comment by ojw28** [comment] 2021-04-01 09:39
This issue is basically a duplicate of https://github.com/google/ExoPlayer/issues/1497.

This is something we would like to support, but we do not support it currently. It's theoretically possible for application code to implement this functionality directly, but it's a non-trivial amount of work, and it's not something we can provide detailed guidance on at this stage.

Closing as a duplicate of https://github.com/google/ExoPlayer/issues/1497.

**Closed as completed by ojw28** 2021-04-01 09:39 UTC
Labels: duplicate
