### ISSUE TITLE
Couldn't select audio track

### ISSUE THREAD

**Issue by bene25** [google/ExoPlayer#2056] opened 2016-11-10 16:22 UTC
Hello.
We have m3u8 file format such as:

#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=490000,RESOLUTION=640x360
http://XXX.XXX.XX.XXX:31213/MEDIA/76336503.....583609776254/161/4161/
#EXT-X-STREAM-INF:BANDWIDTH=1500000,RESOLUTION=720x576
http://XXX.XXX.XX.XXX:31213/MEDIA/76336503.....583609776254/161/3161/
#EXT-X-STREAM-INF:BANDWIDTH=2500000,RESOLUTION=1280x720
http://XXX.XXX.XX.XXX:31213/MEDIA/76336503.....583609776254/161/2161/

Each EXT-X-STREAM-INF tag link to file like:

#EXTM3U
#EXT-X-TARGETDURATION:5
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:35156
#EXT-X-START:TIME-OFFSET=-25,PRECISE=YES
#EXT-X-KEY:METHOD=AES-128,URI="http://XXX.XXX.XX.XXX:02444/xxXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/191/2191/aeskey_191_
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/3020314583628416652818934133893/191/2191/seg_XXXXX.ts
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/6545456465456456465454564/191/2191/seg_191_XXXXX.ts
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/6545456465456456465454564/191/2191/seg_191_XXXXX.ts
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/6545456465456456465454564/191/2191/seg_191_XXXXX.ts
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/6545456465456456465454564/191/2191/seg_191_XXXXX.ts

Audio and subtitles are embeded in TS file.
trackSelector.getCurrentSelections().info.getTrackGroups() method doesnt work. How can I get audio and subtitles?

**Comment by Avetri** [comment] 2016-11-10 17:54
<pre>
--- library/src/main/java/com/google/android/exoplayer2/source/hls/HlsChunkSource.java  (revision )
+++ library/src/main/java/com/google/android/exoplayer2/source/hls/HlsChunkSource.java  (revision )
@@ -399,7 +399,7 @@
           }
         }
         extractor = new TsExtractor(timestampAdjuster,
-            new DefaultTsPayloadReaderFactory(esReaderFactoryFlags), true);
+            new DefaultTsPayloadReaderFactory(esReaderFactoryFlags), false);
       }
     } else {
       // MPEG-2 TS segments, and we need to continue using the same extractor.
</pre>

**Comment by ojw28** [comment] 2016-11-10 18:46
I doubt the above response is relevant.

**Comment by Avetri** [comment] 2016-11-11 08:16
Yes, I just have noticed that my solution is not for the issue. I got only 1 audio track.

I suppose the issue is an encryption related.

**Comment by bene25** [comment] 2016-11-13 21:44
I could switch tracks on VLC or SM player. Android media player also can recognize it.
I've inserted my stream link to ExoPlayer 2 demo app and it doesn't identify any track except main video stream. Also somehow he chooses one of the two or three audiotracks and play it.

**Comment by bene25** [comment] 2016-11-15 07:40
Any news for this issue?

**Comment by AquilesCanta** [comment] 2016-11-15 14:40
Have you seen #2014 ? Is this related? If so, this is a duplicate. If that's the case, please close the issue. If not, please clarify, as I might be misunderstanding the problem.

**Comment by AquilesCanta** [comment] 2016-11-15 14:41
Also, if not a duplicate, try to provide a link for us to have a look. That makes everything easier. You can do so at dev.exoplayer@gmail.com.

**Comment by bene25** [comment] 2016-11-29 10:05
This is our .ts file sample.
I hope this helps.

https://drive.google.com/open?id=0B6PilUifi8koMkpmMzdaYk5fYkE

**Comment by AquilesCanta** [comment] 2016-11-29 10:21
This is a duplicate of #2014 .

**Closed as completed by AquilesCanta** 2016-11-29 10:21 UTC
Labels: need more info

**Comment by AquilesCanta** [comment] 2016-11-29 10:30
It won't work perfectly well, but it would be interesting to try @Avetri 's patch(above). The language would be incorrectly set, but I wonder how it would work. @bene25 , give it a try and let me know the outcome. Or send your HLS link to dev.exoplayer@gmail.com.

**Comment by bene25** [comment] 2016-11-30 16:05
@Avetri could you please explain more detail your solution? Where you get DefaultTsPayloadReaderFactory?

**Comment by bene25** [comment] 2016-12-06 10:32
@Avetri solution helps.
But method name is DefaultStreamReaderFactory instead of DefaultTsPayloadReaderFactory

**Comment by AquilesCanta** [comment] 2016-12-06 10:46
You are probably using an older Exoplayer version, that's why.

**Comment by bene25** [comment] 2016-12-06 11:33
r2.0.4

**Comment by bene25** [comment] 2016-12-12 11:03
Could you help me please.
@Avetri solution helps, bu there is another issue , after fast switching several streams (4-6), trackSelection on last selected channel returns previous channel value.

**Comment by Avetri** [comment] 2016-12-12 11:57
@bene25 , I have not noticed a notification from You. I just have seen it.
I am sorry.

**Comment by bene25** [comment] 2016-12-12 14:19
How to force notifyTrackSelectionsChanged again without setting TrackSelections?
I want only update trackSelection on current values.
