### ISSUE TITLE
Crash on Fabric : Fatal Exception: java.lang.NoClassDefFoundError net.butterflytv.rtmp_client.RtmpClient

### ISSUE THREAD

**Issue by atif-afridi** [google/ExoPlayer#4521] opened 2018-07-17 07:10 UTC
i have looked the issue on SO and the issues list of exoplayer but couldn't find yet. 

i have received this crash recently on fabric for 4.4. , 4.3 and 4.4.4   OS 

Crash Log : 

Fatal Exception: java.lang.NoClassDefFoundError: net.butterflytv.rtmp_client.RtmpClient
       at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:56)
       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

in build.gradle its 

com.google.android.exoplayer:exoplayer-core:2.8.1
com.google.android.exoplayer:exoplayer-ui:2.8.1
com.google.android.exoplayer:extension-rtmp:2.8.1

this is the full log for crash nothing more on fabric.

thanks for the help in advance :)

**Comment by ojw28** [comment] 2018-07-17 11:09
Duplicate of https://github.com/google/ExoPlayer/issues/4506

**Closed as completed by ojw28** 2018-07-17 11:09 UTC
Labels: duplicate

**Comment by botaydotcom** [comment] 2018-07-17 11:19
"i have received this crash recently on fabric for 4.4. , 4.3 and 4.4.4 OS"

With this addition info, I think one probable reason is it may have something to do with multi-dex (if your app happens to use this).
I still don't think we can offer any help from ExoPlayer though.

**Comment by atif-afridi** [comment] 2018-07-17 19:22
@botaydotcom yes i am using it in my app . so what are the precautions in that case ?

**Comment by botaydotcom** [comment] 2018-07-18 08:55
I don't have much experience with that either, but a quick [Google search](https://www.google.co.uk/search?q=Fatal+Exception%3A+java.lang.NoClassDefFoundError+multidex+lollipop) shows lots of people with similar crashes (maybe with different classes).
I think you will have more luck with this question on a site such as StackOverFlow.
