### ISSUE TITLE
Request: show in sample how to normalize volume of audio files

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4541] opened 2018-07-20 08:07 UTC
As a user, one of the most annoying things when I play some music, is that some songs have very different volume levels than others, so I find myself often changing the volume level manually.

And if you use Google Maps while playing music, it gets even worse, because you might have the navigation speaks in very high/low volume as they both use the same volume type (that's why I requested a change for it, [here](https://issuetracker.google.com/issues/111408330)).

Now, I know people asked for a similar feature about this, [here](https://github.com/google/ExoPlayer/issues/3349) (yet about video), but I think it's a very common issue that people have, and yet there is no music player out there that fixes it well.

I think that if Google shows a sample of how to do it, more and more music players will have this feature too.

Can you guys please add into the sample, how to normalize the current audio file volume level , to prevent this problem from occurring?

**Comment by andrewlewis** [comment] 2018-07-20 08:30
Regarding music playback during navigation, the documentation on [audio focus](https://developer.android.com/guide/topics/media-apps/audio-focus) may help, especially the part about audio ducking.

I think the request to add normalization support is already addressed by #3349. The files need to be scanned to get information about how loud they are before we can normalize their audio levels. The scanning step is best left up to the app, as there isn't a fast and efficient way to do it in the player in general. (ExoPlayer isn't designed for batch processing out of the box.)

We could potentially add an AudioProcessor for changing the sample level (#2659), but this wouldn't provide an end-to-end solution which I think is what you're asking for. I'll close this for now as I don't think it's in scope for the project, but we'll bear it in mind for consideration in the future. Thanks!

**Closed as completed by andrewlewis** 2018-07-20 08:30 UTC
Labels: question

**Comment by AndroidDeveloperLB** [comment] 2018-07-20 11:55
About audio focus, how is it related? Also, out of curiosity, could this be useful for apps that need to play an alternative ringtone while having an incoming call, by using the same volume type as of ringtones, and avoid having the real ringtone play?

There is no code or sample on the first link you've provided. Is it a hard thing to do?

I didn't ask for adding the feature. I asked for how to do it, by showing it in the sample.

**Comment by andrewlewis** [comment] 2018-07-23 08:24
It seems like part of the issue is that music drowns out navigation sounds, and audio ducking could help with that, but this actually doesn't solve the main problem of navigation sounds being too loud/quiet having set the stream volume for the music. The ringtones question seems to be covered by #4546. Implementing support for audio focus handling is not very difficult, though it won't address your main problem of having input audio at inconsistent volume levels.

One thing you could look into is whether the audio you're trying to play already has metadata about volume levels (e.g., [iTunNORM](http://id3.org/iTunes%20Normalization%20settings)). If so, you could add support for extracting the metadata, storing it in the input media `Format` like the gapless playback metadata, then applying the correction with an `AudioProcessor`.

**Comment by andrewlewis** [comment] 2018-07-23 08:55
As an aside: I think the suggestion of having a separate volume for navigation, which is part of the [issue you filed](https://issuetracker.google.com/issues/111408330), is not really going to help with the actual problem here. If that was added, users would still need to change volume when playing different unnormalized music sources in your app, and they'd also have the inconvenience of needing to change a separate volume when wanting the spoken navigation volume to change. The trend appears to be towards simplified volume controls, not more complicated ones. And it's probably not going to work very well for the system to listen to audio and change the volume dynamically because it can't tell whether audio is going to get louder or quieter in future.

**Comment by AndroidDeveloperLB** [comment] 2018-07-23 09:12
How could audio-ducking help? I'm talking about volume. The volume I hear is very different between the navigation and the music, even though they are on the same volume type (audio source is media) .

The ringtone question isn't answered yet, as I don't get how to do it. I tried to use the available API which give clues that it's possible, but since it's not describing enough what the various flags do, I can't be sure, and I don't understand what they really do, if not what I think they are supposed to do.

About the metadata, can you please add it to the sample? But will it always be possible? You wrote that it can be a solution if the metadata exists...

About separate volume for navigation, it's true that the user will still need to change volume, but at least it will affect only the music volume, and not the navigation volume. The user will still be able to hear the navigation related audio as usual, without hearing it in too low or too high volume.

It solved at least this problem. Not the annoyance of music songs with different volume values, but at least not missing navigation instructions due to low volume of it, or being "bombard" with very loud navigation instructions ("GO LEFT!!!") .

I don't know of any music playing app that has normalizing volume and solves the music issue, so I request both things:
1. Show here in sample how to normalize the volume, hoping that other music players will do the same, seeing how good this solution is, solving a very common issue.
2. Have a navigation volume type, that will solve the issue I've presented, and can soften the issue of the common user, of having a music app that doesn't implement volume normalization.

**Comment by andrewlewis** [comment] 2018-07-23 09:31
> How could audio-ducking help? I'm talking about volume. The volume I hear is very different between the navigation and the music, even though they are on the same volume type (audio source is media) .

If music continues playing uninterrupted at the same volume while directions play, the user may miss directions played "on top". Audio focus/ducking helps with that because it tells your app when to reduce the music volume (via `simpleExoPlayer.setVolume`), so you should implement support for it. But as you say, if the media volume is too loud/quiet this doesn't fully solve the problem.

> The ringtone question isn't answered yet, as I don't get how to do it. I tried to use the available API which give clues that it's possible, but since it's not describing enough what the various flags do, I can't be sure, and I don't understand what they really do, if not what I think they are supposed to do.

I don't think it's an ExoPlayer bug or feature request so we can't provide detailed guidance. You'll need to do your own research or ask on a general programming help site.

> About the metadata, can you please add it to the sample? But will it always be possible? You wrote that it can be a solution if the metadata exists...

We don't have resources to do this now I'm afraid. As mentioned before, we'll reconsider in future when we plan what to work on next.

I guess it's also worth mentioning that it looks like tools exist to do this server-side, so if you're serving the music yourself you can just normalize it there.

> About separate volume for navigation, it's true that the user will still need to change volume, but at least it will affect only the music volume, and not the navigation volume. The user will still be able to hear the navigation related audio as usual, without hearing it in too low or too high volume.
> 
> It solved at least this problem. Not the annoyance of music songs with different volume values, but at least not missing navigation instructions due to low volume of it, or being "bombard" with very loud navigation instructions ("GO LEFT!!!") .
> 
> I don't know of any music playing app that has normalizing volume and solves the music issue, so I request both things:
> 
> Show here in sample how to normalize the volume, hoping that other music players will do the same, seeing how good this solution is, solving a very common issue.

See above.

> Have a navigation volume type, that will solve the issue I've presented, and can soften the issue of the common user, of having a music app that doesn't implement volume normalization.

Tracked by [your issue](https://issuetracker.google.com/issues/111408330), but I'd guess it's unlikely to happen due to complicating the user experience.

**Comment by AndroidDeveloperLB** [comment] 2018-07-23 10:45
About audio-ducking, again, it's true that it's a good thing in general to use it, but it's irrelevant to the issue I'm describing. I'm talking about volume level, that since it's shared with navigation instructions, and since the user could change the volume level due to songs with different volume levels in them, it will affect the navigation instructions too.

About the ringtone, it is related to ExoPlayer, because I'm talking about its API. All functions and flags are of ExoPlayer.

About the metadata, you wrote that it might not always work, right? If the metadata is missing this won't work, right?

I think the best solution is volume normalization, by going through the entire audio/video file, and then deciding which volume to use. 

I ask this not just for me as a developer, but actually more as a user. My hope is that if you do add this to the sample, more apps will follow. I hate this common issue, of needing to change volume in the car, while music is playing. And the worse scenario is when I play music while also having a navigation app running.

Having a server can't be a solution, because most music/video players don't do it, and you could have a mix of local and cloud media files.

About the issue I wrote about, of requesting the navigation volume type, I think it's better than nothing. I can't force all music player apps to have a normalizing volume feature, and I don't think it's possible to have a system wide volume-normalization mechanism (could be cool, though). The navigation volume solves a part of the issue, at least.
