### ISSUE TITLE
Unexpected CONTENT_RESUME_REQUESTED without stopAd

### ISSUE THREAD

**Issue by Gobi1989** [google/ExoPlayer#3525] opened 2017-11-30 09:42 UTC
Hi All,

**Issue description**
I'm using Exoplayer for playing DRM content along with Ads. As the player starts well with Preroll Ads and resume back to content video as well.It has some issue in midroll 1 and midroll 2, postroll also working as expected. The midroll get skipped or stucked.

**Reproduction steps**
Forwarded the content video before some few of midroll then allow the player to continue the video at the time of midroll 1 it just skips the Ads or it stuck in the Ad. I had checked the log of ImaAdsLoader it shows that **Unexpected CONTENT_RESUME_REQUESTED without stopAd**. 

This issue happens frequently but not regularly. Even there is no Exception too except **Unexpected CONTENT_RESUME_REQUESTED without stopAd** this log.

**Version of ExoPlayer being used**
com.google.android.exoplayer:exoplayer:r2.5.4
com.google.android.exoplayer:exoplayer-core:r2.5.4
com.google.android.exoplayer:exoplayer-dash:r2.5.4
com.google.android.exoplayer:exoplayer-ui:r2.5.4
compile 'com.google.ads.interactivemedia.v3:interactivemedia:3.7.4'

**Device(s) and version(s) of Android being used**
Samsung GALAXY Note4, Android 6.0.1

**# Note:- We cannot replicate the issue as per the reproduction steps, sometimes its works well**

**Implementation**
ImaAdsLoader was implemented as per link below
https://medium.com/google-exoplayer/playing-ads-with-exoplayer-and-ima-868dfd767ea

Please find the logs where Ads skipped at midroll 2
[ads_log.txt](https://github.com/google/ExoPlayer/files/1517354/ads_log.txt)

**Comment by andrewlewis** [comment] 2017-12-04 15:26
It's possible that this is an IMA SDK issue relating to preloading [internal bug: b/38354028].

**Comment by andrewlewis** [comment] 2018-02-27 16:04
Please could you try to reproduce this on the latest release 2.7.0? It includes several fixes for ad playback.

**Comment by ojw28** [comment] 2018-04-22 22:43
Closing on the assumption this is fixed, due to lack of follow up. If this is still an issue with 2.7.0 or later, please let us know. Thanks!

**Closed as completed by ojw28** 2018-04-22 22:43 UTC
Labels: bug: in dependency
