### ISSUE TITLE
Can I get silence duration which skipped?

### ISSUE THREAD

**Issue by tuesda** [google/ExoPlayer#7360] opened 2020-05-12 09:33 UTC
When I enabled skipSilence with

```
player.setPlaybackParameters(PlaybackParameters(1f, 1f, true))
```
How can I get silence duration which skipped?

**Comment by andrewlewis** [comment] 2020-05-12 12:43
Duplicate of #5666.

**Closed as completed by andrewlewis** 2020-05-12 12:43 UTC
Labels: duplicate
