### ISSUE TITLE
MergingMediaSource is not supported by DownloadHelper

### ISSUE THREAD

**Issue by spuday90** [google/ExoPlayer#9802] opened 2021-12-22 05:01 UTC
Hi,
Im unable to download a drm stream if external cc is added to it. I have tried the same stream in the exoplayer sample also and faced same issue. Getting streamKeys from downloadrequest empty. Please help.

**Comment by marcbaechinger** [comment] 2021-12-22 10:37
Can you describe in a bit more detail what you are trying to do and how? Are you creating a `MergingMediaSource` to sideload subtitles? How do you attempt to download the stream?  Please give us some more details to make your issue actionable.

**Comment by spuday90** [comment] 2021-12-22 12:22
Hi @marcbaechinger ,
I'm loading subtitles using MediaItem.AdsConfiguration to MediaItem.
We have followed the sample code to initiate the download.
After selecting the Video quality when we call getDownloadRequest
In the below method Stream keys from mediapreparer are getting empty.
  
```
public DownloadRequest getDownloadRequest(String id, @Nullable byte[] data) {
    DownloadRequest.Builder requestBuilder =
        new DownloadRequest.Builder(id, localConfiguration.uri)
            .setMimeType(localConfiguration.mimeType)
            .setKeySetId(
                localConfiguration.drmConfiguration != null
                    ? localConfiguration.drmConfiguration.getKeySetId()
                    : null)
            .setCustomCacheKey(localConfiguration.customCacheKey)
            .setData(data);
    if (mediaSource == null) {
      return requestBuilder.build();
    }
    assertPreparedWithMedia();
    List<StreamKey> streamKeys = new ArrayList<>();
    List<ExoTrackSelection> allSelections = new ArrayList<>();
    int periodCount = trackSelectionsByPeriodAndRenderer.length;
    for (int periodIndex = 0; periodIndex < periodCount; periodIndex++) {
      allSelections.clear();
      int rendererCount = trackSelectionsByPeriodAndRenderer[periodIndex].length;
      for (int rendererIndex = 0; rendererIndex < rendererCount; rendererIndex++) {
        allSelections.addAll(trackSelectionsByPeriodAndRenderer[periodIndex][rendererIndex]);
      }
      streamKeys.addAll(mediaPreparer.mediaPeriods[periodIndex].getStreamKeys(allSelections));
    }
    return requestBuilder.setStreamKeys(streamKeys).build();
  }
```
  

  Note: We are using Widevine  url. 
  Please let me know if u need any other information

**Comment by marcbaechinger** [comment] 2021-12-24 15:14
If the `streamKeys` are empty at the end of this code something is odd indeed. From the information available, it could be that there are no tracks selected and hence the `streamKeys` list is empty. How do you create the `DownloadHelper` to which the above `getDownloadRequest` method belongs to? Can you please post the code that creates the `DownloadHelper`?

Further, can you provide us with a URI to the stream and the additional data required to access the stream (DRM scheme and license server URL and if required Authentication HTTP headers)? This way we can figure out if this working and give you some advice. It's currently very hard to tell what the problem is.

**Comment by spuday90** [comment] 2021-12-27 08:25
Hi @marcbaechinger ,
We are creating the DownloadHelper as 
`DownloadHelper.forMediaItem(context, mediaItem, renderersFactory, httpDataSourceFactory),`.

You can reproduce the same issue in the exoplayer sample code. Just add some Subtitles uri to the WIdevine Dash content and try to download the video and observe. You'll see a Toast message as "Stream keys error".

This is how we are creating MediaItem.

```
private MediaItem createMediaItem(Bundle intent, Uri uri){
            MediaItem.Builder mediaItemBuilder;
            MediaItem mediaItem;
            String drmLicenseUrl = intent.getString(DRM_LICENSE_URL);
            String[] keyRequestPropertiesArray = intent.getStringArray(DRM_KEY_REQUEST_PROPERTIES);
            UUID drmSchemeUuid = intent.containsKey(DRM_SCHEME_UUID_EXTRA)
                    ? UUID.fromString(intent.getString(DRM_SCHEME_UUID_EXTRA)) : null;

            DownloadRequest downloadRequest =
                    ((OTTApplication) (getActivity()).getApplication())
                            .getDownloadTracker()
                            .getDownloadRequest(uri);
            if (downloadRequest != null) {
                Map<String, String> headers = new HashMap<>();
                if(drmSchemeUuid != null) {

                    if (keyRequestPropertiesArray != null) {
                        for (int i = 0; i < keyRequestPropertiesArray.length; i += 2) {
                            headers.put(keyRequestPropertiesArray[i], keyRequestPropertiesArray[i + 1]);
                        }
                    }
                }
                mediaItem = new MediaItem.Builder()
                        .setMediaId(downloadRequest.id)
                        .setUri(downloadRequest.uri)
                        .setCustomCacheKey(downloadRequest.customCacheKey)
                        .setMimeType(downloadRequest.mimeType)
                        .setStreamKeys(downloadRequest.streamKeys)
                        .setDrmKeySetId(downloadRequest.keySetId)
                        .setDrmLicenseRequestHeaders(headers)
                        .setDrmUuid(drmSchemeUuid)
                        .setDrmLicenseUri(drmLicenseUrl)
                        .build();
                return mediaItem;
            }

            Map<String, String> headers = new HashMap<>();
            if (keyRequestPropertiesArray != null) {
                for (int i = 0; i < keyRequestPropertiesArray.length; i += 2) {
                    headers.put(keyRequestPropertiesArray[i], keyRequestPropertiesArray[i + 1]);
                }
            }
            MediaItem.DrmConfiguration drmConfiguration = new MediaItem.DrmConfiguration.Builder(drmSchemeUuid)
                    .setLicenseUri(Uri.parse(drmLicenseUrl))
                    .setLicenseRequestHeaders(headers)
                    .build();
            Uri adTag = getAdTagUri();
            MediaItem.AdsConfiguration adsConfiguration = new MediaItem.AdsConfiguration.Builder(adTag).build();
            mediaItemBuilder = new MediaItem.Builder()
                    .setUri(uri)
                    .setAdsConfiguration(adsConfiguration)
                    .setDrmConfiguration(drmConfiguration);

            List<MediaItem.SubtitleConfiguration> subtitleConfigurations = new ArrayList<>();

            Uri uriurl = Uri.parse("some path to cc file");
            MediaItem.SubtitleConfiguration subtitleConfiguration =
                    new MediaItem.SubtitleConfiguration.Builder(uriurl)
                            .setMimeType("application/ttml+xml")
                            .setLanguage("en")
                            .build();
            subtitleConfigurations.add(subtitleConfiguration);

            if(subtitleConfigurations.size() > 0)
                mediaItemBuilder.setSubtitleConfigurations(subtitleConfigurations);

            return mediaItemBuilder.build();
        }
```

**Comment by marcbaechinger** [comment] 2021-12-27 12:59
Ah, ok, I see. Thanks for the details. 

This is something which is not supported. The complex media item that is augmenting a content media source with ads and subtitles, is not supported by the `DownloadHelper`. Actually, it's more like that the `MergingMediaSource` that sideloads the subtitles and is created by the `DefaultMediaSourceFactory` is not supporting downloading. I'm not quite sure how complex it would be to make this work, but I think there may be quite some number of details that can make this difficult and non-trivial.

For the observed behavior: After preparation a `MediaPeriod` is requested by the 'MediaPreparer' to which the `getStreamKeys` method is delegated. This method is currently not implemented by `MergingMediaPeriod`, so it just returns an empty list of the default implementation.

For the given call to `getStreamKeys(List<ExoTrackSelection> trackSelections)` it would at least be required that the track selections are split up and then be delegated to `getStreamKeys(List<ExoTrackSelection> trackSelections)` of the underlying media periods that have been merged.

So for now I can't give you a better answer then saying this is not supported. If you want to support downloading text tracks, you need to integrate them into a adaptive manifest (DASH) or playlist (HLS). This works fine because the underlying media source is a `DashMediaSource/HlsMediaSource` that integrates the subtitles just as video and audio tracks. 

I mark this issue as an improvement in the sense that we may want to look into make `MergingMediaSource` support downloading better for the case of sideloading subtitles.  Although, I think we won't be able to work on this any time soon. So for now I think you need to look into the DASH/HLS option for supporting subtitles. Supporting ads with offline is even less likely to be supported soon I'm afraid.

**Comment by ojw28** [comment] 2021-12-29 18:04
Duplicate of https://github.com/google/ExoPlayer/issues/5615

**Closed as completed by ojw28** 2021-12-29 18:04 UTC
Labels: enhancement, low priority
