### ISSUE TITLE
Almost frame accurate pause (HLS Stream)

### ISSUE THREAD

**Issue by bdezso** [google/ExoPlayer#10558] opened 2022-08-26 16:35 UTC
Is there any **frame accurate** pause solution for **HLS** streamed video?

Our use case is stop a video at a specific position.
Currently we're using PlayerMessage, but it's not as accurate as our requirements.

Same happen on the iOS side with AVPlayer:
https://stackoverflow.com/questions/73500374/avplayer-currenttime-not-match-with-the-displayed-frame-after-many-seeking-hls

If we can't do this with ExoPlayer, is there any other solution? 
Maybe change HLS encode, or use other player?
I read somewhere the root cause could be the m3u8 itself.
[Link to m3u8](https://mrkresz-content-bucket.s3.eu-central-1.amazonaws.com/applicationData/extended-path-videos/4b0046fd-0be7-4a07-bc7c-c1a0069116b1/released/50816bc9-6118-4dd1-a90e-fb72652bb06f-final-from-anonymized.m3u8)

I hope someone could help us, because we're stuck with this problem.

**Comment by icbaker** [comment] 2022-08-26 16:41
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/5660.

**Closed as completed** 2022-08-26 16:41 UTC
Labels: duplicate
