### ISSUE TITLE
How to obtain programmatically video type - Live or DVR

### ISSUE THREAD

**Issue by AlexDundar** [google/ExoPlayer#5906] opened 2019-05-18 08:21 UTC
I use the last version of `ExoPlayer` (2.10.0) in my `Android` app. And I want to play different video types (VOD, LIVE, DVR) with different videoplayer interface. For example, I want to show `DefaultTimeBar` on `ExoPlayer` controlls in VOD and DVR videos and I want to hide this view when video is LIVE. 

All videos play well, but I dont know, how to check programmatically the type of video. I was looking for information and found that I can use flags `isCurrentWindowDynamic` and `isCurrentWindowSeekable` of `SimpleExoPlayer` object. But when I show them in logs, I see the next:
1) VOD video, url ="https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/hls/GoogleIO-2014-CastingToTheFuture.m3u8"
```
videoPlayer?.isCurrentWindowDynamic // returns false
videoPlayer?.isCurrentWindowSeekable // returns true
```

2) DVR video, url = "https://svs.itworkscdn.net/lanatvlive/lana/playlist.m3u8?DVR"
```
videoPlayer?.isCurrentWindowDynamic // returns true
videoPlayer?.isCurrentWindowSeekable // returns true
```

3) LIVE video, url = "https://live-k2301-kbp.1plus1.video/189931/smil:189931.smil/playlist.m3u8"
```
videoPlayer?.isCurrentWindowDynamic // returns true
videoPlayer?.isCurrentWindowSeekable // returns true
```

Both flags in DVR and LIVE are the same. So, how to distinguish the type DVR or LIVE programmatically?

**Comment by AlexDundar** [comment] 2019-05-20 09:29
Nobody knows?

**Comment by tonihei** [comment] 2019-05-20 09:32
That's a duplicate of #2668. We don't have this flag currently and you can only guess based on the other flags. Note though, that our implementation will still include some guesswork because their is often not a clear-cut boundary between live and on-demand (think about an ended live stream for example).

**Closed as completed** 2019-05-20 09:33 UTC
Labels: duplicate
