### ISSUE TITLE
Caused by android.content.res.Resources$NotFoundException Unable to find resource ID #0x7f08010f

### ISSUE THREAD

**Issue by ayushi-sk** [google/ExoPlayer#10619] opened 2022-09-14 08:58 UTC
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

- Samsung Galaxy A13
- Samsung Galaxy A50
- Samsung Galaxy A22
- Xiomi Redmi 10 Prime
- Xiomi Redmi Note 9 Pro Max
- Xiomi Redmi Note 11

### Reproducible in the demo app?

No

### Reproduction steps

It crashed on app open

### Expected result

It should not crash

### Actual result

Caused by android.view.InflateException
Binary XML file line #33 in layout/exo_player_control_view: Binary XML file line #33 in layout/exo_player_control_view: Error inflating class android.widget.ImageButton

### Media

Caused by android.view.InflateException
Binary XML file line #33 in layout/exo_player_control_view: Binary XML file line #33 in :layout/exo_player_control_view: Error inflating class android.widget.ImageButton

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment] 2022-09-14 10:36
Duplicate of #10409

**Closed as not planned** 2022-09-14 10:37 UTC
Labels: duplicate
