### ISSUE TITLE
DASH + DRM Error

### ISSUE THREAD

**Issue by AndresECG** [google/ExoPlayer#8444] opened 2021-01-11 14:40 UTC
Hi, I'm playing a DASH live stream with DRM Widevine... the code works fine, but on certain devices (emulators and some tv boxes) it doesn't seem to read the license and plays a black video. Is there a solution to this? Can I detect when it doesn't read the license and run another function?

- Dash code + drm: [here](https://github.com/halilozel1903/ExoPlayerDrm) (Java)
- Url: https://cdn.cvattv.com.ar/live/c3eds/TheFilmZoneHD/SA_Live_dash_enc_2A/TheFilmZoneHD.mpd
- Drm: https://canales.televisionenvivo-internet.online/packfutbol/cv.php
- ExoPlayer version: 2.10.1

**Comment by lcf87** [comment] 2021-01-11 18:08
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

**Comment by grovertb** [comment] 2021-01-19 02:42
@AndresECG  Following the example of exoplayer I managed to reproduce the video dash with the links you attached and it works correctly for me.

**Comment by AndresECG** [comment] 2021-01-19 03:10
> @AndresECG Following the example of exoplayer I managed to reproduce the video dash with the links you attached and it works correctly for me.

The transmission is reproduced perfectly on mobile phones, the problem is in the emulators and some TV boxes... have you tried any of them?

**Comment by ojw28** [comment] 2021-06-14 19:21
Closing because the information requested in the issue template, and in https://github.com/google/ExoPlayer/issues/8444#issuecomment-758126620, was not provided. Without the requested information it is not possible for us to efficiently investigate the issue.

**Closed as completed by ojw28** 2021-06-14 19:21 UTC
Labels: question
