### ISSUE TITLE
UnrecognizedInputFormatException when DataSpec resolving to m3u8 format in ResolvingDataSource.Resolver

### ISSUE THREAD

**Issue by Kamil-H** [google/ExoPlayer#8487] opened 2021-01-21 15:16 UTC
I've got custom `ResolvingDataSource.Resolver` that is resolving URI to the stream (m3u8) media file. Unfortunately returning stream file from `resolveDataSpec` function results in the following exception:
```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1028)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Sample app that reproduces an error:
https://github.com/Kamil-H/ExoPlayer-Crash/tree/resolver_problem

`ResolvingDataSource.Resolver` implementation:
https://github.com/Kamil-H/ExoPlayer-Crash/blob/resolver_problem/app/src/main/java/com/nomtek/exoplayercrash/media/CustomResolver.kt
When you run this app you will see that media items are not getting played. It is because an exception thrown by ExoPlayer.
However when you comment out the line with `.m3u8` url and uncomment the line with `.mp3` url you will see that media item is playing properly.

I saw the same behavior in the ExoPlayer 2.11.X (before Playlist API). When I'm wrapping my source with `ProgressiveMediaSource` it is getting resolved properly. When I'm wrapping with `HlsMediaSource`, ExoPlayer crashes.

- ExoPlayer version number - 2.12.3
- Android version - 11
- Android device - Google Pixel 4

**Comment by ojw28** [comment] 2021-01-21 15:20
Duplicate of https://github.com/google/ExoPlayer/issues/8476. Please avoid fragmenting the discussion across multiple issues. Thanks.

**Closed as completed by ojw28** 2021-01-21 15:20 UTC
Labels: duplicate

**Comment by Kamil-H** [comment] 2021-01-21 15:23
Previous thread was about "making a call just before playback", since this one contains an issue description and reproducible sample project, that's why I thought it makes sense to create a new ticket 🙂
