### ISSUE TITLE
Video freeze on video track change in tunnel mode 

### ISSUE THREAD

**Issue by jyee-brcm** [google/ExoPlayer#6947] opened 2020-02-04 22:54 UTC
### [REQUIRED] Issue description
Video freeze when changing video track in tunnel mode
The underlying issue here is in tunnel mode, when video track is changed, on the audio side we do not see a stop/start. The video decoder require this to occur in order to be put in the right state and proceed to play the new track properly. This can be solved by performing stop/start on the audio side or perform a seek to the PTS corresponding to the video track change.

### [REQUIRED] Reproduction steps
1. ExoPlayer demo app version 2.11.1, enable "Request multimeddia tunneling"
2. Play video under SmoothStreaming -> Super Speed
3. While video is playing go to SELECT TRACKS, under "VIDEO" select any track to trigger a video track change.
4. Observe that the video is frozen.

### [REQUIRED] Link to test content
Test content used is contained in the exoplayer demo app as described above.

### [REQUIRED] A full bug report captured from the device
Will email bugreport.zip to dev.exoplayer@gmail.com separately.

### [REQUIRED] Version of ExoPlayer being used
Version 2.11.1

### [REQUIRED] Device(s) and version(s) of Android being used
Android Version P
Device: Broadcom Android Platform.
Reproducibility: 100%

**Comment by AquilesCanta** [comment] 2020-02-06 13:51
@andrewlewis, would you kindly take a look / retriage?

**Comment by andrewlewis** [comment] 2020-02-11 12:50
> The underlying issue here is in tunnel mode, when video track is changed, on the audio side we do not see a stop/start. The video decoder require this to occur in order to be put in the right state and proceed to play the new track properly. This can be solved by performing stop/start on the audio side or perform a seek to the PTS corresponding to the video track change.

Please could you provide some more details about what behavior you are expecting to see from the application/ExoPlayer in this case? I don't think we are doing anything different in the lifecycle of the video codec or `AudioTrack` for the tunneling case compared to non-tunneled playback, but please correct me if I'm wrong.

Fundamentally, it seems like the implementation of tunneling on the device can still take hardware A/V sync timestamps from the start of audio buffers and use those to display video frames at the right time, even if a new video decoder or audio track is created.

**Comment by navluis** [comment] 2020-02-13 20:09
Hi Andrew,
When switching a video track during tunneling things get a bit tricky. As you know, audio and video are tightly coupled during tunneling, given that audio is usually driving the playback clock for a/v synchronization. 
In our tunneling implementation, after a flush call or at the start of playback, the omx video decoder always waits for the audio hal to signal the value of the first audio timestamp. This is helpful to control things such as:
1) Artifact-free playback startup. As you may know, the timestamps of audio and video streams are not necessarily aligned. Blindly playing every audio/video frame at the start would often result in video-only playback followed by audio or the other way around, this would happen for a short period but nevertheless customers don't like it.
2) Accurate seeking: Similarly to above, it is often required to discard a large number of decoded video frames before resuming playback after seeking.

Because the two features above are very important for customers, we assumed that whenever the video decoder is flushed or re-started, it will wait for the audio hal to indicate the first audio timestamp. The audio hal only sends that signal whenever the AudioTrack instance is re-created or stopped/started.

For this particular use case, the video decoder is released and re-instantiated but the audio track isn't, therefore resulting on the video decoder waiting indefinitely for a signal from the audio hal.

Perhaps our design assumptions can be revised but the fundamental problem is that the omx IL interface doesn't provide mechanisms to smoothly handle use-cases such as seeking with tunneling. We're basically using an integration layer to handle use cases that should be handled by a 'player' kind of interface, because we don't have another choice.

We have advised our customers to re-start the audio track when doing a video track change if they want the feature to work with tunneling. Because some of them want to keep using the vanilla exoplayer version, we would like to see if such behavior can be incorporated in the development branch.

Hope this is clear? Otherwise please let me know and I'll try to clarify further.

Thks
Luis

**Comment by andrewlewis** [comment] 2020-02-14 09:20
Hi Luis, thanks for the information!

If we can find a way to avoid creating a new `AudioTrack` for a video track change that would be 
strongly preferable. The main reason is that audio playback will likely be audibly interrupted on the track change, which impacts the user experience. Also, we already have a fair amount of conditional code for integrating video tunneling into the library, which adds complexity and increases the chance of introducing a bug (especially as we generally need to test for regressions in tunneling manually). So I really want to avoid changing this behavior if possible.

> The audio hal only sends that signal whenever the AudioTrack instance is re-created or stopped/started.

As I understand it, the audio HAL is device-specific and should be under your control, so wouldn't it be possible to fix this on your side by adding an extra signaling path for a new video decoder to request a timestamp update?

Or if this would actually require changes in the media framework and it's not feasible to fix on your side, please could you describe what extra signaling would be needed in detail and I'll pass on the information to the framework team? Thanks.

**Comment by navluis** [comment] 2020-02-18 20:25
Hi Andrew,

>> As I understand it, the audio HAL is device-specific and should be under your control, so wouldn't it be possible to fix this on your side by adding an extra signaling path for a new video decoder to request a timestamp update?

Yes, we were trying to avoid that as we preferred the communication between the audio hal and omx decoder to stay simple. So far, we've managed to keep it one-way, only signaling from audio to video decoder but I guess we'll have to look into extending this model.
Anyway, I understand your point of trying to keep the tunnel/non-tunnel logic consistent and the potential audio artifact that would occur if the audio track is re-started. I guess we can for now keep asking customers to re-start the audio track while we work on the platform changes.


>> Or if this would actually require changes in the media framework and it's not feasible to fix on your side, please could you describe what extra signaling would be needed in detail and I'll pass on the information to the framework team? Thanks.

It'd be ideal if we could have some support from the framework for this signaling. In fact, I would expect this to have been part of the tunneling design given that I would expect most OEMs to need some form of communication between audio and video for tunneling. I'll look into what would be useful to have for this signaling and send you some info to pass it by the framework team.

**Comment by andrewlewis** [comment] 2020-02-21 08:30
Hi Luis, here is the reply from the video framework team: "For a new video decoder, I assume it would get KEY_AUDIO_SESSION_ID from the app side, which triggers configureVideoTunnel API to their HAL with the audio track hardware sync ID. I believe this should be enough signalling from framework to HAL for setting up the tunnel."

**Comment by navluis** [comment] 2020-02-27 01:03
Thanks Andrew,
We had an internal discussion and decided to extend the signaling between audio hal and bomx decoder to better handle cases such as track changes for video tunneling. Therefore we won't be needing any custom change for tunneling when the video track is changed. I'll close this ticket.

Thanks for the help anyway,
Luis

**Comment by navluis** [comment] 2020-02-27 01:05
Actually I don't think I can close the ticket, can I ? Please close it on your end.
Thks
Luis

**Closed as completed** 2020-02-27 14:03 UTC
Labels: need more info
