### ISSUE TITLE
The memory is accumulated in one instance of "com.google.android.exoplayer2.source.SampleQueue

### ISSUE THREAD

**Issue by cassiohoffmann** [google/ExoPlayer#4539] opened 2018-07-20 03:18 UTC
### Problem description
Hello friends, I am using Exoplayer version 2.8.2 for a project in which the video is stored on tvbox a95x.
After some time of use, about 1 hour, the application stop respond and, analyzing the hprof memory dump , seems to have something wrong with the resource release process that I can not identify.
Each time you viewed a video, I create my player as follows:

playerListener = new Player.EventListener() {
                        @Override
                        public void onTimelineChanged(Timeline timeline, Object o, int i) {
                        }

                        @Override
                        public void onTracksChanged(TrackGroupArray trackGroupArray, TrackSelectionArray trackSelectionArray) {
                        }

                        @Override
                        public void onLoadingChanged(boolean b) {
                        }

                        @Override
                        public void onPlayerStateChanged(boolean b, int i) {
                        }

                        @Override
                        public void onRepeatModeChanged(int i) {
                        }

                        @Override
                        public void onShuffleModeEnabledChanged(boolean b) {
                        }

                        @Override
                        public void onPlayerError(ExoPlaybackException e) {
                            logger.error("erroVideo", e);
                        }

                        @Override
                        public void onPositionDiscontinuity(int i) {
                        }

                        @Override
                        public void onPlaybackParametersChanged(PlaybackParameters playbackParameters) {
                        }

                        @Override
                        public void onSeekProcessed() {
                        }
                    };

                    TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
                    trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
                    DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

                    bandwidthMeter = new DefaultBandwidthMeter();
                    mediaDataSourceFactory = new DefaultDataSourceFactory(displayActivity, Util.getUserAgent(displayActivity, "mediaPlayerSample"), (TransferListener<? super DataSource>) bandwidthMeter);

                    MediaSource mediaSource = new ExtractorMediaSource(Uri.parse(videoPath), mediaDataSourceFactory, extractorsFactory, null, null);

                    player = ExoPlayerFactory.newSimpleInstance(displayActivity, trackSelector);
                    player.setVideoScalingMode(MediaPlayer.VIDEO_SCALING_MODE_SCALE_TO_FIT);
                    player.addListener(playerListener);
                    player.setVolume(midia.isReproduzirAudio ? 1f : 0f);

                    player.prepare(mediaSource);
                    player.setPlayWhenReady(true);

                    playerView = displayActivity.getPlayerView();
                    playerView.setPlayer(player);
                    playerView.setPlaybackPreparer(this);

and in the end

try {
			            player.removeListener(playerListener);
            			player.stop(false); // TODO testar com true
			            player.clearVideoSurface();
			            player.release();
			        } catch (Exception ignore) {
			        }

			        trackSelector = null;
			        bandwidthMeter = null;
			        mediaDataSourceFactory = null;

			        player = null; 

Did you ever see something like this or do you have any suggestions for giving it to me?
my application needs to stay active for hours during the day.
I really appreciate your response and attention.

<img width="955" alt="screen shot 2018-07-19 at 11 45 56 pm" src="https://user-images.githubusercontent.com/19987318/42981234-87eb022c-8bb1-11e8-901e-542ab562e0bd.png">

<img width="1008" alt="screen shot 2018-07-19 at 11 43 36 pm" src="https://user-images.githubusercontent.com/19987318/42981222-7c5683aa-8bb1-11e8-9971-9aae8a459c44.png">

[logcat.zip](https://github.com/google/ExoPlayer/files/2212310/logcat.zip)

**Comment by ojw28** [comment] 2018-07-20 09:58
Is that showing around 15MB of buffer? That sounds expected to me. How do you know it's a leak and/or is accumulating? The post above doesn't seem to justify this claim.

**Comment by cassiohoffmann** [comment] 2018-07-20 13:46
Hi, thanks for the feedback!
Before using the Exoplayer I used the Mediaplayer and the application was running for more than 24 hours uninterrupted but the Mediaplayer does not answer for other needs.
The prints shown above were collected from Eclipse Mat as a helper because I saw that this number only increases until the application stops responding in + - 1 hour
is there any more log I can pass to help detect why the application stops responding?
Just to better explain the operation of the application, I have a loop of + - 20 videos that are playing one after the other. I have doubt if the problem can be in the fact of creating an instance of exoplayer every time I play the video and it is not releasing memory and only accumulating until the app stops responding.
Is there any way to unload completes what was used from memory to prevent this?
then the analysis of the mat to the end of a video playback only.


I did an isolated test with only 1 video being played. it plays, finalizes everything and loads again.
after + 50 displays, note that Mat starts complaining about resource allocation that is not released and the longer
is displaying the videos, but this number grows until the app stops responding.
[mat.hprof.zip](https://github.com/google/ExoPlayer/files/2214118/mat.hprof.zip)


<img width="953" alt="screen shot 2018-07-20 at 10 41 40 am" src="https://user-images.githubusercontent.com/19987318/43005668-f2e7bea0-8c09-11e8-9dd8-1ae942b6f300.png">

**Comment by ojw28** [comment] 2018-07-20 15:00
It's hard to know what to make of the screenshot (I haven't used Eclipse Mat for a long time), but a single instance of `ExtractorMediaPeriod` consuming 9MB or 15MB or RAM doesn't sound unusual. I took a look at the attached hprof in Android Studio and I don't see anything to suggest there's excessive memory usage. Was that captured at the point where the issue occurs? If not, please capture one at that point in time.

If you run your app with Android Studio's memory profiler running, do you see the consumption increase after the initial buffering phase? I'm not convinced your problem is related to memory at this point. If it were I'd probably also expect the app to crash with `OutOfMemoryError`, rather than stop responding.

**Comment by cassiohoffmann** [comment] 2018-07-20 19:37
Hello, I followed your orientations and I monitored by AndoiStudio. see if it helps identify.
It seems that objects are being allocated but are not being released for some unknown reason
<img width="1399" alt="screen shot 2018-07-20 at 3 20 14 pm" src="https://user-images.githubusercontent.com/19987318/43021687-efd4b82c-8c3a-11e8-872a-bac22132aa4c.png">
[AndroidStudioDump.zip](https://github.com/google/ExoPlayer/files/2215180/AndroidStudioDump.zip)

**Comment by cassiohoffmann** [comment] 2018-07-22 14:33
Hi friend, I did a simulation using mediaplayer and the application keeps running for more than 1 day without interruptions. The purpose of the test is to try to help solve what may be causing the Exoplayer not to be running for that same time.
If you need more information, log or if you have any suggestions for me to apply in the test I am at your disposal. I really liked the exoplayer and I'm willing to help with whatever is necessary to solve this situation soon and further improve its usability.
How can I help you more, I look forward to returning.
[Archive.zip](https://github.com/google/ExoPlayer/files/2217077/Archive.zip)

**Comment by ojw28** [comment] 2018-07-22 20:08
> It seems that objects are being allocated but are not being released for some unknown reason

I'm not sure I understand how you reached that conclusion from the screenshot attached. It seems to show relatively stable memory usage.

Can you reproduce this issue using the ExoPlayer demo app, or a small modification of it that causes media to loop? If so then please can you share that patch with us, or else share some other way in which we can reproduce the issue. Right now there's not really solid evidence in this thread pointing to an ExoPlayer problem.

**Comment by cassiohoffmann** [comment] 2018-07-22 20:40
Hello, I have not yet come to an exact conclusion.
in the last test posted I made the exchange of the exoplayer by the mediaplayer and worked more than a 1 day without giving problem presented when I use the exoplayer. When I returned the exoplayer, it gave back trouble.
I will provide a simpler test for you to play in your test environment!

**Comment by ojw28** [comment] 2018-08-14 10:51
Closing due to lack of actionable information. Please comment again here if you're able to provide a simpler test an reproduction steps.

**Closed as completed by ojw28** 2018-08-14 10:51 UTC
Labels: need more info
