### ISSUE TITLE
DRM Widevine (L1) exception Android 7 (Nougat) 

### ISSUE THREAD

**Issue by billyjoker** [google/ExoPlayer#8905] opened 2021-05-05 15:16 UTC
Hi I have a problem with a playback with DRM. The media is playing well with other device with Android 9 and Widevine L3, but with Android Nougat and L1 is failing. I used the exoplayer demo release v2 and I have included my asset

- ExoPlayer version number
2.13.3
- Android version
7.0
- Android device
Nvidia Shield Tablet

This is the logcat:

```
2021-05-05 17:00:10.840 14628-14628/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=6.21, mediaPos=0.00, window=0, period=0, drmSessionManagerError
      com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:194)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:602)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:81)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:75)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:174)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:177)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:602) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
    ]
2021-05-05 17:00:10.840 14628-14674/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:524)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:519)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:482)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:194)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:602)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:81)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:75)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:174)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:177)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:602) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
2021-05-05 17:00:10.920 14628-14628/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=6.29, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:524)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:519)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:482)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:194)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:602)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:81)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:75)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:174)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:177)
        at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:602) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
    ]
```

Using the same media with my app I've got this one:

```
2021-05-05 17:09:56.739 748-1116/? E/bt_btm: BTM_BleObserve Observe Already Active
2021-05-05 17:09:57.488 662-709/? E/wifi: wifi_get_supported_feature_set returned error = 0xffffffa1
2021-05-05 17:09:57.535 748-1116/? E/bt_btm: BTM_BleObserve Observe Already Active
2021-05-05 17:10:00.496 662-5491/? E/ActivityManager: applyOptionsLocked: Unknown animationType=0
2021-05-05 17:10:00.708 269-11014/? E/oemcrypto_cenc: OEMCrypto_APIVersion: 11
2021-05-05 17:10:00.764 269-269/? E/oemcrypto_cenc: OEMCrypto_APIVersion: 11
2021-05-05 17:10:00.801 267-1105/? E/OMXNodeInstance: setConfig(10b0059:Nvidia.h264.decode.secure, ??(0x7fc0001f)) ERROR: UnsupportedIndex(0x8000101a)
2021-05-05 17:10:00.801 267-267/? E/OMXNodeInstance: setConfig(10b0059:Nvidia.h264.decode.secure, ??(0x7fc00020)) ERROR: UnsupportedIndex(0x8000101a)
2021-05-05 17:10:00.808 267-1108/? E/OMXNodeInstance: getConfig(10b0059:Nvidia.h264.decode.secure, ConfigCommonOutputCrop(0x700000f)) ERROR: BadParameter(0x80001005)
2021-05-05 17:10:00.809 267-334/? E/OMXNodeInstance: setConfig(10b0059:Nvidia.h264.decode.secure, ??(0x7fc0001f)) ERROR: UnsupportedIndex(0x8000101a)
2021-05-05 17:10:00.810 267-1100/? E/OMXNodeInstance: getConfig(10b0059:Nvidia.h264.decode.secure, ??(0x7fc00020)) ERROR: UnsupportedIndex(0x8000101a)
2021-05-05 17:10:00.876 267-1105/? E/OMXNodeInstance: setConfig(10b005a:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2021-05-05 17:10:00.877 267-1108/? E/OMXNodeInstance: setConfig(10b005a:google.aac.decoder, ConfigOperatingRate(0x6f800003)) ERROR: Undefined(0x80001001)
2021-05-05 17:10:01.326 269-11015/? E/WVCdm: CdmEngine::AddKey: no key_data
2021-05-05 17:10:01.327 14628-14860/com.google.android.exoplayer2.demo E/MediaDrm-JNI: Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2965 (-2965)
2021-05-05 17:10:01.328 14628-14628/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=0.78, mediaPos=0.00, window=0, period=0, drmSessionManagerError
      android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965
        at android.media.MediaDrm.provideKeyResponse(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:228)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:492)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
    ]
2021-05-05 17:10:01.338 14628-14860/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:524)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:519)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:504)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965
        at android.media.MediaDrm.provideKeyResponse(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:228)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:492)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
2021-05-05 17:10:01.426 14628-14628/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.88, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:524)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:519)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:504)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965
        at android.media.MediaDrm.provideKeyResponse(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:228)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:492)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:58) 
        at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:563) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by icbaker** [comment] 2021-05-05 17:27
I tried playing the provided content on the demo app on a Pixel 3a XL and it failed with the following error:

```
2021-05-05 18:13:20.348 14468-14524/com.google.android.exoplayer2.demo W/MediaDrm: MediaDrm went away with unhandled events
2021-05-05 18:13:20.351 14468-14468/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=1.40, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(p0va0br1803544, null, null, video/avc, avc1.640028, 1803544, null, [1920, 1080, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2821)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:145)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1387)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:852)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
```

I also tried playing it with the [Shaka player demo](https://shaka-player-demo.appspot.com) and it failed with a 'DRM expired' error that linked here: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6014

Then I retried playing it with Shaka and it succeeded. And I retried with the ExoPlayer demo app and it succeeded. It seems like maybe your DRM server is a little flaky?

The upshot is that I haven't been able to reproduce the problem you're seeing.

----
>```
> 2021-05-05 17:00:10.840 14628-14628/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=6.21, mediaPos=0.00, window=0, period=0, drmSessionManagerError
>       com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
>         at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:194)
>         at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:153)
>```

This looks like your DRM license server is returning a 500 error code. You should look at the server logs to understand more details of what's going on there. I'm not sure this part is device specific.

----

I don't have an Nvidia Shield to reproduce on - can you capture a [bug report](https://developer.android.com/studio/debug/bug-report) after reproducing the `Failed to handle key response: DRM vendor-defined error: -2965` error (as above, the 500 error probably isn't interesting from ExoPlayer's perspective). You can send the bug report zip file to the same email address you sent the content.

**Comment by billyjoker** [comment] 2021-05-06 15:01
Hi I've just attached a bug report. Please could you say me what is the `DRM vendor-defined error: -2965` mean?

**Comment by billyjoker** [comment] 2021-05-06 15:55
This is debugged object data at `DefaultDrmSession` class with values until the exception is occurred:

```
postKeyRequest method debuggged:

scope = {byte[4]@10934} 
 0 = 115
 1 = 105
 2 = 100
 3 = 55
type = 1
allowretry = true
-----------------------
schemeDatas = {Collections$UnmodifiableRandomAccessList@10936}  size = 1
 0 = {DrmInitData$SchemeData@10961} 
  data = {byte[84]@10970} 
  hashCode = 0
  licenseServerUrl = null
  mimeType = "video/mp4"
  requiresSecureDecryption = false
  uuid = {UUID@10972} "edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"
  shadow$_klass_ = {Class@10547} "class com.google.android.exoplayer2.drm.DrmInitData$SchemeData"
  shadow$_monitor_ = -2133160810
-----------------------------
optionalKeyRequestParameters = null
--------------------------
onKeyResponse method debugged:
sessionId = {byte[4]@11054} 
 0 = 115
 1 = 105
 2 = 100
 3 = 56
byte[] keySetId = mediaDrm.provideKeyResponse(sessionId, responseData);
responseData {byte[0]@11162}
mediaDrm = {FrameworkMediaDrm@11137} 
 mediaDrm = {MediaDrm@11181} 
 uuid = {UUID@11182} "edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"
 shadow$_klass_ = {Class@9670} "class com.google.android.exoplayer2.drm.FrameworkMediaDrm"
 shadow$_monitor_ = -2093819389
mediaDrm.provideKeyResponse(sessionId, responseData); //when executed produces as belows:
result = {MediaDrm$MediaDrmStateException@11189} Method threw 'android.media.MediaDrm$MediaDrmStateException' exception.
 mDiagnosticInfo = "android.media.MediaDrm.error_neg_2965"
 mErrorCode = -2965
 backtrace = null
 cause = {MediaDrm$MediaDrmStateException@11189} "android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965"
 detailMessage = "Failed to handle key response: DRM vendor-defined error: -2965"
 stackTrace = {StackTraceElement[8]@11193} 
 suppressedExceptions = {Collections$EmptyList@11194}  size = 0
 shadow$_klass_ = {Class@4302} "class android.media.MediaDrm$MediaDrmStateException"
 shadow$_monitor_ = 1201985246
```

**Comment by icbaker** [comment] 2021-05-10 13:08
> Hi I've just attached a bug report. Please could you say me what is the `DRM vendor-defined error: -2965` mean?

The file provided is not a bugreport, it appears to be a logcat snippet in a text file wrapped in a zip file. A bugreport is the zip file generated by running `adb bugreport` (or one of the other methods described on the page I linked above). It includes more information than just the logcat and may give us a clue about what the -2965 error is related to.

"vendor-defined" means it's defined by the device/chipset manufacturer, not the Android framework, and certainly not by ExoPlayer. So I suspect you should contact Nvidia for a canonical answer as to what it means.

**Comment by billyjoker** [comment] 2021-05-10 15:26
Ok you are right, so I have just sent you by email the correct bugreport file.

**Comment by icbaker** [comment] 2021-05-10 17:40
Thanks for the bugreport - just before the ExoPlayer stack trace I see this error from the Widevine Content Decryption Module (`WVCdm`) complaining about some `key_data` missing:
```
05-10 17:22:41.065   252   339 E WVCdm   : CdmEngine::AddKey: no key_data
```

If you can attach a debugger while reproducing you could perhaps look at the value of `responseData` going into `MediaDrm#provideKeyResponse()`. It's a somewhat opaque byte string, but you can make at least check that it's non-empty. If it is non-empty and you'd like to dig further, I think you'll find it's a serialized protocol buffer of type `SignedModularDrmResponse` as defined here: 
https://github.com/google/shaka-packager/blob/master/packager/media/base/widevine_common_encryption.proto

And the `signature` field of that message I believe ought to be another serialized proto of type `CommonEncryptionResponse` from the same file.

So you can parse the response, and maybe check that it has all the fields the CDM is expecting to be present.

When I do this with the content link you provided I see the response data seems to be present - but the content also plays fine on my device so I'm not sure that proves anything...

**Comment by billyjoker** [comment] 2021-05-14 11:48
Hi @icbaker , I've checked as you said and I have figured out this while debugging this part:

```
  @Override
  @Nullable
  public byte[] provideKeyResponse(byte[] scope, byte[] response)
      throws NotProvisionedException, DeniedByServerException {
    if (C.CLEARKEY_UUID.equals(uuid)) {
      response = ClearKeyUtil.adjustResponseData(response);
    }

    return mediaDrm.provideKeyResponse(scope, response);
  }
```
I've checked that the var `byte[] response`, which is a {byte[0]@6215} I think that is the opaque byte that you said, and when I debug `response.length` it results as 0

What does it mean?

By the other hand I see that main clue is that:
`com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500`

But it has no sense that it results with this device and is not occurring with other devices that they work well.

**Comment by icbaker** [comment] 2021-05-14 12:25
That `byte[]` is plumbed directly through from the [`MediaDrmCallback#executeKeyRequest`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/MediaDrmCallback.html#executeKeyRequest-java.util.UUID-com.google.android.exoplayer2.drm.ExoMediaDrm.KeyRequest-) implementation you provide. In the demo app this is an `HttpMediaDrmCallback` and passes the HTTP response body received from the server directly along.

If it's empty it means either your license server is returning an empty response, or your `MediaDrmCallback` implementation is dropping the response somewhere. I would debug further - and if you discover an empty response coming back from the server then you should look in the license server logs to understand why that's happening.

----

> By the other hand I see that main clue is that:
> `com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500`

I'm confused. Are you seeing both the 500 error and the -2965 error in the same failure? If you're using `HttpMediaDrmCallback` with `DefaultHttpDataSource`, I would expect the HTTP 500 response to cause an exception to be thrown here - and thus the control flow should never reach `provideKeyResponse()` - so I don't understand how you could see the -2965 error from `MediaDrm` if the server responds with a 500 error (unless you're using a custom `MediaDrmCallback` or `HttpDataSource` implementation that behaves differently?):
https://github.com/google/ExoPlayer/blob/0ba317b1337eaa789f05dd6c5241246478a3d1e5/library/common/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L371-L391

And that exception should get caught and rethrown here:
https://github.com/google/ExoPlayer/blob/0ba317b1337eaa789f05dd6c5241246478a3d1e5/library/core/src/main/java/com/google/android/exoplayer2/drm/HttpMediaDrmCallback.java#L178-L182

And then caught here:
https://github.com/google/ExoPlayer/blob/0ba317b1337eaa789f05dd6c5241246478a3d1e5/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSession.java#L612-L615

And handled here:
https://github.com/google/ExoPlayer/blob/0ba317b1337eaa789f05dd6c5241246478a3d1e5/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSession.java#L481-L484

----

This sounds to me like an incompatibility between the Nvidia Shield and your license server - I'm not sure there's an ExoPlayer problem here.

I think you should look at your license server logs to understand why it's responding with 500 errors to the license requests from your Nvidia Shield.

**Comment by Stonos** [comment] 2021-05-14 13:01
I believe that the Nvidia Shield K1 Tablet has had its Widevine L1 license revoked (similar to #7986 and #8075). I also have the same tablet, and Widevine L1 stopped working at some point.

The only workaround I found was to force L3 instead of L1 (which may not be possible in your case). There is an open ticket to automatically fallback to L3 if playback with L1 fails: #8108

**Comment by billyjoker** [comment] 2021-05-20 09:56
@Stonos finally that workaround it worked for me!!. Forcing L3 does the trick for this device. Notce that the same problem occoured with Nexus5 and the fix worked again. Many thanks.

@icbaker I could see both errors in diferent executions, I mean,  sometimes I have seen the http 500 error, and sometimes I've seen the -2965 vendor error. I know it sounds strange, maybe while debugging the system thinks the response is delaying, I do not know exactly. Anyway, I thank you your efforts to go deeply with this issue.

Now I am working in a fix that applies the force L3 workaround, I've seen some code in Exoplayer2, at `com.google.android.exoplayer2.drm.FrameworkMediaDrm` that patches L3 with a specific device model ASUS_Z00AD (Zenfone2, Android 6.0.1, also with Widevine L1), it would be nice to have a list of affected device in order to patch all of them.

```
  private FrameworkMediaDrm(UUID uuid) throws UnsupportedSchemeException {
    Assertions.checkNotNull(uuid);
    Assertions.checkArgument(!C.COMMON_PSSH_UUID.equals(uuid), "Use C.CLEARKEY_UUID instead");
    this.uuid = uuid;
    this.mediaDrm = new MediaDrm(adjustUuid(uuid));
    if (C.WIDEVINE_UUID.equals(uuid) && needsForceWidevineL3Workaround()) {
      forceWidevineL3(mediaDrm);
    }
  }
```

```
  private static boolean needsForceWidevineL3Workaround() {
    return "ASUS_Z00AD".equals(Util.MODEL);
  }
```

**Comment by icbaker** [comment] 2021-05-20 10:34
Glad you resolved the problem.

Unfortunately there isn't a published list of devices that have been revoked.

I'm going to close this as I don't think there's anything additional we can do here.

**Closed as completed by icbaker** 2021-05-20 10:34 UTC
Labels: bug: device specific

**Comment by billyjoker** [comment] 2021-05-25 10:25
I have to add some useful info about the message error:

`android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2965`

It is the same message reported by Google Nexus 5, I mean, it seems it does not owe to Nvidia internal log reports.
