### ISSUE TITLE
Previous button in Notification Repeats the same song some times

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#7222] opened 2020-04-12 10:35 UTC
Previous button in Notification Repeats the same song some times

This is the Code I am trying

the    player.setRepeatMode(Player.REPEAT_MODE_ALL);
so when we click the previous button in notification It sometimes repeats the same song , sometimes it happens for the same song multiple  times, ie same song is repeated a lot of times 
 ```
 public void playermanager() {
        player = ExoPlayerFactory.newSimpleInstance(AudioPlayerService.this, new DefaultTrackSelector());
        dataSourceFactory = new DefaultDataSourceFactory(this
                , Util.getUserAgent(this, "neoariaplayer"));
        concatenatingMediaSource = new ConcatenatingMediaSource();
        for (int i = 0; i < SongsList.size(); i++) {
            mediaSource = new ProgressiveMediaSource.
                    Factory(dataSourceFactory).createMediaSource(Uri.parse(SongsList.get(i)._path));
            concatenatingMediaSource.addMediaSource(mediaSource);
        }
        player.prepare(concatenatingMediaSource);
        player.setRepeatMode(Player.REPEAT_MODE_ALL);
        player.seekTo(songId, C.TIME_UNSET);
        player.addListener(new Player.EventListener() {
            @Override
            public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
                Intent intent = new Intent(ConstantValues.MAINACTIVITY_BROADCAST_SONG_DETAILS);
                sendBroadcast(intent);
                Intent intent1 = new Intent(ConstantValues.MAINACTIVITY_BROADCAST_COUNT);
                sendBroadcast(intent1);
  
            }

        });

        notifcationmgr();
        player.setPlayWhenReady(true);

        stopper();
    }

    public void notifcationmgr() {
        playerNotificationManager = playerNotificationManager.createWithNotificationChannel(AudioPlayerService.this,
                ConstantValues.PLAYBACK_CHANNEL_ID, R.string.app_name, R.string.app_name, ConstantValues.PLAYBACK_NOTIFICATION_ID,
                new PlayerNotificationManager.MediaDescriptionAdapter() {
                    @Override
                    public String getCurrentContentTitle(Player player) {
                        Title = SongsList.get(player.getCurrentWindowIndex())._title;
                        AlbumName = SongsList.get(player.getCurrentWindowIndex())._album;
                        SongPathway = SongsList.get(player.getCurrentWindowIndex())._path;
                        Album_ID = SongsList.get(player.getCurrentWindowIndex())._albumId;
                        MediaID = SongsList.get(player.getCurrentWindowIndex())._id;
                        return Title;
                    }


                    @Nullable
                    @Override
                    public PendingIntent createCurrentContentIntent(Player player) {
                        Intent intent = new Intent(AudioPlayerService.this, Blankact.class);
                        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
                        return PendingIntent.getActivity(AudioPlayerService.this, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
                    }


                    @Nullable
                    @Override
                    public String getCurrentContentText(Player player) {
                        return AlbumName;
                    }

                    @Nullable
                    @Override
                    public Bitmap getCurrentLargeIcon(Player player, PlayerNotificationManager.BitmapCallback
                            callback) {
                        bitmap = otherUtils.getAlbumartImage(AudioPlayerService.this, SongsList.get(player.getCurrentWindowIndex())._albumId);
                        return bitmap;
                    }
                },
                new PlayerNotificationManager.NotificationListener() {

                    @Override
                    public void onNotificationCancelled(int notificationId, boolean dismissedByUser) {
                        shouldsave = false;
                        Intent intent = new Intent(AudioPlayerService.this, ColseActivity.class);
                        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
                        startActivity(intent);
                        stopped = "stopped";
                        stopForeground(true);
                        stopSelf();
                    }

                    @Override
                    public void onNotificationPosted(int notificationId, Notification notification, boolean ongoing) {
                        startForeground(notificationId, notification);
                    }
                }
        );


        playerNotificationManager.setPriority(NotificationCompat.PRIORITY_HIGH);
        playerNotificationManager.setPlayer(player);
        playerNotificationManager.setFastForwardIncrementMs(0);
        playerNotificationManager.setRewindIncrementMs(0);
        playerNotificationManager.setUseChronometer(false);
        playerNotificationManager.setUsePlayPauseActions(true);
        playerNotificationManager.setUseStopAction(true);
        playerNotificationManager.setUseNavigationActionsInCompactView(true);
        mediaSession = new MediaSessionCompat(AudioPlayerService.this, ConstantValues.MEDIA_SESSION_TAG);
        mediaSession.setActive(true);
        playerNotificationManager.setMediaSessionToken(mediaSession.getSessionToken());
        mediaSessionConnector = new MediaSessionConnector(mediaSession);
        mediaSessionConnector.setQueueNavigator(new TimelineQueueNavigator(mediaSession) {
            @Override
            public MediaDescriptionCompat getMediaDescription(Player player, int windowIndex) {
                return getMediaDescriptionl(SongsList, windowIndex);
            }
        });
        mediaSessionConnector.setPlayer(player);

        playerNotificationManager.setControlDispatcher(new DefaultControlDispatcher() {
            @Override
            public boolean dispatchSetPlayWhenReady(Player player, boolean playWhenReady) {
                
                player.setPlayWhenReady(playWhenReady);
                if (!player.isPlaying()) {
                    if (player.getRepeatMode() == Player.REPEAT_MODE_OFF && !player.hasNext()) {
                        if (player.getCurrentPosition() > (player.getDuration() - 1000)) {
                            playnextnow();
                        }
                    }
                }
               return true;
            }
        });
    }

```

It happens it player controls provieded by the exoplayer as well , but I have implemented my own playercontrols where I call player.next(); and  player.previous(); 

It works fine there

I have noticed the play next button in playerNotificationManager works fine, (though there might be a bug there aswell icould not find it during my testing)

I have noticed these difference in the codes in baseplayer, 

```
@Override
  public final void previous() {
    int previousWindowIndex = getPreviousWindowIndex();
    if (previousWindowIndex != C.INDEX_UNSET) {
      seekToDefaultPosition(previousWindowIndex);
    }
  }

   
  @Override
  public final void next() {
    int nextWindowIndex = getNextWindowIndex();
    if (nextWindowIndex != C.INDEX_UNSET) {
      seekToDefaultPosition(nextWindowIndex);
    }
  }
```

and In PlayerNotificationManager

```
private void previous(Player player) {
    Timeline timeline = player.getCurrentTimeline();
    if (timeline.isEmpty() || player.isPlayingAd()) {
      return;
    }
    int windowIndex = player.getCurrentWindowIndex();
    timeline.getWindow(windowIndex, window);
    int previousWindowIndex = player.getPreviousWindowIndex();
    if (previousWindowIndex != C.INDEX_UNSET
        && (player.getCurrentPosition() <= MAX_POSITION_FOR_SEEK_TO_PREVIOUS
            || (window.isDynamic && !window.isSeekable))) {
      seekTo(player, previousWindowIndex, C.TIME_UNSET);
    } else {
      seekTo(player, windowIndex, /* positionMs= */ 0);
    }
  }

private void next(Player player) {
    Timeline timeline = player.getCurrentTimeline();
    if (timeline.isEmpty() || player.isPlayingAd()) {
      return;
    }
    int windowIndex = player.getCurrentWindowIndex();
    int nextWindowIndex = player.getNextWindowIndex();
    if (nextWindowIndex != C.INDEX_UNSET) {
      seekTo(player, nextWindowIndex, C.TIME_UNSET);
    } else if (timeline.getWindow(windowIndex, window).isDynamic) {
      seekTo(player, windowIndex, C.TIME_UNSET);
    }
  }
```

**Instead of implementing the new logic in PlayerNotificationManager , can we call baseplayer's next and previous methods from the PlayerNotificationManager** 

The way to reproduce the error is play a list of songs using concatenatingMediaSource and try to play previous songs a few times

**its the same issue with ### ### MediaSessionCompat*

_**I have noticed this fault in Google Music player as well**_

**Comment by marcbaechinger** [comment] 2020-04-14 14:12
I think the behaviour you are describing works as intended. You can't change this with the release version but we fixed this already in the dev-v2 branch.

The previous button does only transition to the previous window if the current position is below 3 seconds of the duration. If it's above 3 seconds the player does skip to the start of the current window first. 

To verify this, you should be able to skip to previous by tapping the previous button twice, when you are behind 3 seconds in the content. That's the code you pasted above or which you can find [here](https://github.com/google/ExoPlayer/blob/7d3f54a375fac04a746ca76a8f2e1ad32c8b45b2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L1227).

If you are looking into the dev-v2 branch, you will find that we already fixed this behaviour. previous() as well as next() has been moved into the ControlDispatcher which is by default implemented by DefaultControlDispatcher. You can customize that behaviour by overriding [`DefaultControlDispatcher.dispatchPrevious()`](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/DefaultControlDispatcher.java#L65).

So you can try the dev-v2 branch or wait until the change lands in the release branch. As you see from your code snippet, the method is currently private so you can't change this behaviour with the current release branch.

Can you please confirm that the behaviour you see happens only when playback is past the first 3 seconds?

**Comment by pawaom** [comment] 2020-04-15 04:07
I tried to use the **dev-v2** 

using this 

implementation 'com.github.google:ExoPlayer:dev-v2-SNAPSHOT'

i kept getting the warning 

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.(i am currently busy with other work as well, will look into it later)

I will wait for the release branch

any idea when it will be released , thanks. hoepfully my issues will be resolved, please keep this issue active till then

**Comment by marcbaechinger** [comment] 2020-04-17 10:32
We can't give you a concrete timeframe for when this is released.

I'm going to close this issue. It will not be deleted, I just change the state to closed. You can re-open at any time if you think that the problem the issue is about is not solved or needs fixing.

**Closed as completed by marcbaechinger** 2020-04-17 10:32 UTC
Labels: question

**Comment by pawaom** [comment] 2020-06-09 11:29
@marcbaechinger 
I recently updated the exoplayer in my app to version 

```
implementation 'com.google.android.exoplayer:exoplayer-core:2.11.5'
implementation 'com.google.android.exoplayer:exoplayer-ui:2.11.5'
implementation 'com.google.android.exoplayer:extension-mediasession:2.11.5'
```

How ever I have noticed the changes you had mentioned earlier , which were included in  **dev-v2**

regarding 
https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/DefaultControlDispatcher.java#L65

have not been included

All I want is to call 

 ```
if (player.hasPrevious()) {
            player.previous();
        } else {
            player.seekTo((SongsList.size() - 1), C.TIME_UNSET);
        }
```

When the previous Button in notification is clicked , not the 3000ms `MAX_POSITION_FOR_SEEK_TO_PREVIOUS` that has been implemented in the original 
`playernotificationmanager` , as far as I know there is no way to detect the previous button click in the player notification, I tried using Dev-2 but it was a  mess, is there a simple solution for a not so big problem 

thanks
