### ISSUE TITLE
OutOfMemoryError - ExoPlayer 2.2

### ISSUE THREAD

**Issue by suresh-s** [google/ExoPlayer#2586] opened 2017-03-21 14:09 UTC
We are using Exoplayer 2.2 version in our Android project.  In Development environment, we are not getting OutOfMemoryError.  But in Production, We are getting OutOfMemoryError. In Development, can't able to reproduce.  Leak Canary doesn't show any issue. Could you help us to fix this issue?

java.lang.OutOfMemoryError: Failed to allocate a 792016 byte allocation with 566325 free bytes and 553KB until OOM
	at com.google.android.exoplayer2.extractor.DefaultTrackOutput$InfoQueue.a()(null:881)
	at com.google.android.exoplayer2.extractor.DefaultTrackOutput.a()(null:540)
	at com.google.android.exoplayer2.extractor.ts.AdtsReader.c()(null:332)
	at com.google.android.exoplayer2.extractor.ts.AdtsReader.a()(null:145)
	at com.google.android.exoplayer2.extractor.ts.PesReader.a()(null:132)
	at com.google.android.exoplayer2.extractor.ts.TsExtractor.a()(null:246)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.e()(null:257)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.c()(null:194)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run()(null:295)
	at java.util.concurrent.Executors$RunnableAdapter.call()(Executors.java:422)
	at java.util.concurrent.FutureTask.run()(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run()(Thread.java:818)

thread 1 - main:
android.os.MessageQueue.nativePollOnce()(MessageQueue.java:-2)
android.os.MessageQueue.next()(MessageQueue.java:143)
android.os.Looper.loop()(Looper.java:122)
android.app.ActivityThread.main()(ActivityThread.java:5268)
java.lang.reflect.Method.invoke()(Method.java:-2)
java.lang.reflect.Method.invoke()(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()(ZygoteInit.java:902)
com.android.internal.os.ZygoteInit.main()(ZygoteInit.java:697)

thread 73 - Signal Catcher:

thread 74 - ReferenceQueueDaemon:
java.lang.Object.wait()(Object.java:-2)
java.lang.Daemons$ReferenceQueueDaemon.run()(Daemons.java:134)
java.lang.Thread.run()(Thread.java:818)

thread 75 - FinalizerDaemon:
java.lang.Object.wait()(Object.java:-2)
java.lang.Object.wait()(Object.java:422)
java.lang.ref.ReferenceQueue.remove()(ReferenceQueue.java:101)
java.lang.ref.ReferenceQueue.remove()(ReferenceQueue.java:72)
java.lang.Daemons$FinalizerDaemon.run()(Daemons.java:174)
java.lang.Thread.run()(Thread.java:818)

thread 76 - FinalizerWatchdogDaemon:
java.lang.Thread.sleep()(Thread.java:-2)
java.lang.Thread.sleep()(Thread.java:1031)
java.lang.Thread.sleep()(Thread.java:985)
java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor()(Daemons.java:258)
java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization()(Daemons.java:269)
java.lang.Daemons$FinalizerWatchdogDaemon.run()(Daemons.java:217)
java.lang.Thread.run()(Thread.java:818)

thread 77 - HeapTrimmerDaemon:
dalvik.system.VMRuntime.trimHeap()(VMRuntime.java:-2)
java.lang.Daemons$HeapTrimmerDaemon.run()(Daemons.java:313)
java.lang.Thread.run()(Thread.java:818)

thread 78 - GCDaemon:
java.lang.Object.wait()(Object.java:-2)
java.lang.Daemons$GCDaemon.run()(Daemons.java:344)
java.lang.Thread.run()(Thread.java:818)

thread 79 - Binder_1:

thread 80 - Binder_2:

thread 81 - WifiManager:
android.os.MessageQueue.nativePollOnce()(MessageQueue.java:-2)
android.os.MessageQueue.next()(MessageQueue.java:143)
android.os.Looper.loop()(Looper.java:122)
android.os.HandlerThread.run()(HandlerThread.java:61)

thread 83 - pool-1-thread-1:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take()(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask()(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

thread 84 - NsdManager:
android.os.MessageQueue.nativePollOnce()(MessageQueue.java:-2)
android.os.MessageQueue.next()(MessageQueue.java:143)
android.os.Looper.loop()(Looper.java:122)
android.os.HandlerThread.run()(HandlerThread.java:61)

thread 85 - Thread-85:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.PriorityBlockingQueue.take()(PriorityBlockingQueue.java:510)
com.olalabs.platform.servicediscovery.ServiceDiscoveryManager$SendThread.run()(null:677)

thread 86 - RenderThread:

thread 89 - NR_AppStateMon-1:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.parkNanos()(LockSupport.java:197)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos()(AbstractQueuedSynchronizer.java:2055)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:1060)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:776)
java.util.concurrent.ThreadPoolExecutor.getTask()(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

thread 91 - NR_TaskQueue-1:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.parkNanos()(LockSupport.java:197)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos()(AbstractQueuedSynchronizer.java:2055)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:1060)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:776)
java.util.concurrent.ThreadPoolExecutor.getTask()(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

thread 94 - NR_Sampler-1:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:1048)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:776)
java.util.concurrent.ThreadPoolExecutor.getTask()(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

thread 95 - Thread-95:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.PriorityBlockingQueue.take()(PriorityBlockingQueue.java:510)
com.android.volley.CacheDispatcher.run()(null:90)

thread 96 - Thread-96:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.PriorityBlockingQueue.take()(PriorityBlockingQueue.java:510)
com.android.volley.NetworkDispatcher.run()(null:90)

thread 97 - Thread-97:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.PriorityBlockingQueue.take()(PriorityBlockingQueue.java:510)
com.android.volley.NetworkDispatcher.run()(null:90)

thread 98 - Thread-98:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.PriorityBlockingQueue.take()(PriorityBlockingQueue.java:510)
com.android.volley.NetworkDispatcher.run()(null:90)

thread 99 - Thread-99:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.PriorityBlockingQueue.take()(PriorityBlockingQueue.java:510)
com.android.volley.NetworkDispatcher.run()(null:90)

thread 100 - Binder_3:

thread 134 - NR_Sampler-1:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:1048)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:776)
java.util.concurrent.ThreadPoolExecutor.getTask()(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

thread 135 - ChoreographerOwner:Handler:
android.os.MessageQueue.nativePollOnce()(MessageQueue.java:-2)
android.os.MessageQueue.next()(MessageQueue.java:143)
android.os.Looper.loop()(Looper.java:122)
android.os.HandlerThread.run()(HandlerThread.java:61)

thread 181 - Binder_4:

thread 232 - NR_Harvester-1:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.parkNanos()(LockSupport.java:197)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos()(AbstractQueuedSynchronizer.java:2055)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:1060)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take()(ScheduledThreadPoolExecutor.java:776)
java.util.concurrent.ThreadPoolExecutor.getTask()(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

thread 236 - Thread-236:
libcore.io.Posix.recvfromBytes()(Posix.java:-2)
libcore.io.Posix.recvfrom()(Posix.java:185)
libcore.io.BlockGuardOs.recvfrom()(BlockGuardOs.java:250)
libcore.io.IoBridge.recvfrom()(IoBridge.java:553)
java.net.PlainSocketImpl.read()(PlainSocketImpl.java:485)
java.net.PlainSocketImpl.access$000()(PlainSocketImpl.java:37)
java.net.PlainSocketImpl$PlainSocketInputStream.read()(PlainSocketImpl.java:237)
java.io.InputStream.read()(InputStream.java:162)
java.io.BufferedInputStream.fillbuf()(BufferedInputStream.java:149)
java.io.BufferedInputStream.read()(BufferedInputStream.java:295)
libcore.io.Streams.readFully()(Streams.java:81)
java.io.DataInputStream.readInt()(DataInputStream.java:103)
com.olalabs.platform.servicediscovery.NSDMessageHandler.run()(null:61)
java.lang.Thread.run()(Thread.java:818)

thread 237 - Thread-237:
libcore.io.Posix.recvfromBytes()(Posix.java:-2)
libcore.io.Posix.recvfrom()(Posix.java:185)
libcore.io.BlockGuardOs.recvfrom()(BlockGuardOs.java:250)
libcore.io.IoBridge.recvfrom()(IoBridge.java:553)
java.net.PlainSocketImpl.read()(PlainSocketImpl.java:485)
java.net.PlainSocketImpl.access$000()(PlainSocketImpl.java:37)
java.net.PlainSocketImpl$PlainSocketInputStream.read()(PlainSocketImpl.java:237)
java.io.InputStream.read()(InputStream.java:162)
java.io.BufferedInputStream.fillbuf()(BufferedInputStream.java:149)
java.io.BufferedInputStream.read()(BufferedInputStream.java:295)
libcore.io.Streams.readFully()(Streams.java:81)
java.io.DataInputStream.readInt()(DataInputStream.java:103)
com.olalabs.platform.servicediscovery.NSDMessageHandler.run()(null:61)
java.lang.Thread.run()(Thread.java:818)

thread 238 - Thread-238:
libcore.io.Posix.recvfromBytes()(Posix.java:-2)
libcore.io.Posix.recvfrom()(Posix.java:185)
libcore.io.BlockGuardOs.recvfrom()(BlockGuardOs.java:250)
libcore.io.IoBridge.recvfrom()(IoBridge.java:553)
java.net.PlainSocketImpl.read()(PlainSocketImpl.java:485)
java.net.PlainSocketImpl.access$000()(PlainSocketImpl.java:37)
java.net.PlainSocketImpl$PlainSocketInputStream.read()(PlainSocketImpl.java:237)
java.io.InputStream.read()(InputStream.java:162)
java.io.BufferedInputStream.fillbuf()(BufferedInputStream.java:149)
java.io.BufferedInputStream.read()(BufferedInputStream.java:295)
libcore.io.Streams.readFully()(Streams.java:81)
java.io.DataInputStream.readInt()(DataInputStream.java:103)
com.olalabs.platform.servicediscovery.NSDMessageHandler.run()(null:61)
java.lang.Thread.run()(Thread.java:818)

thread 249 - ExoPlayerImplInternal:Handler:
com.google.android.exoplayer2.extractor.DefaultTrackOutput$InfoQueue.a()(null:881)
com.google.android.exoplayer2.extractor.DefaultTrackOutput.a()(null:540)
com.google.android.exoplayer2.extractor.ts.AdtsReader.c()(null:332)
com.google.android.exoplayer2.extractor.ts.AdtsReader.a()(null:145)
com.google.android.exoplayer2.extractor.ts.PesReader.a()(null:132)
com.google.android.exoplayer2.extractor.ts.TsExtractor.a()(null:246)
com.google.android.exoplayer2.source.hls.HlsMediaChunk.e()(null:257)
com.google.android.exoplayer2.source.hls.HlsMediaChunk.c()(null:194)
com.google.android.exoplayer2.upstream.Loader$LoadTask.run()(null:295)
java.util.concurrent.Executors$RunnableAdapter.call()(Executors.java:422)
java.util.concurrent.FutureTask.run()(FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

thread 250 - HlsPlaylistTracker:MasterPlaylist:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take()(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask()(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

thread 251 - Loader:HlsSampleStreamWrapper:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park()(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await()(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take()(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask()(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

thread 252 - MediaCodec_looper:

thread 253 - OkHttp ConnectionPool:
java.lang.Object.wait()(Object.java:-2)
java.lang.Thread.parkFor()(Thread.java:1220)
sun.misc.Unsafe.park()(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.parkNanos()(LockSupport.java:197)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos()(AbstractQueuedSynchronizer.java:2055)
java.util.concurrent.LinkedBlockingQueue.poll()(LinkedBlockingQueue.java:435)
java.util.concurrent.ThreadPoolExecutor.getTask()(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
java.lang.Thread.run()(Thread.java:818)

**Comment by AquilesCanta** [comment] 2017-03-21 14:21
It is virtually impossible for us to diagnose the issue with this amount of information. We will need to reproduce ourselves. From the stack trace, I assume you are feeding a transport stream. Try figuring out what are the characteristics of the stream that produce the leak, that differ from a regular TS which, according to what you said, does not reproduce the issue.

**Comment by ojw28** [comment] 2017-03-21 14:28
Note also that the memory leak could be anywhere in your application. In the OOM shown ExoPlayer is asking for an allocation of less than 1MB, which isn't by itself unreasonable. Something in your app is consuming a lot of memory, which is why the allocation fails, but there's no evidence it's ExoPlayer that's doing this. It could equally be anything else in your application code.

**Comment by suresh-s** [comment] 2017-03-21 14:29
There is no difference in Transport Stream in both Development TS file and Production TS file.  Exception is as follows

java.lang.OutOfMemoryError: Failed to allocate a 792016 byte allocation with 566325 free bytes and 553KB until OOM
at com.google.android.exoplayer2.extractor.DefaultTrackOutput$InfoQueue.a()(null:881)
at com.google.android.exoplayer2.extractor.DefaultTrackOutput.a()(null:540)
at com.google.android.exoplayer2.extractor.ts.AdtsReader.c()(null:332)
at com.google.android.exoplayer2.extractor.ts.AdtsReader.a()(null:145)
at com.google.android.exoplayer2.extractor.ts.PesReader.a()(null:132)
at com.google.android.exoplayer2.extractor.ts.TsExtractor.a()(null:246)
at com.google.android.exoplayer2.source.hls.HlsMediaChunk.e()(null:257)
at com.google.android.exoplayer2.source.hls.HlsMediaChunk.c()(null:194)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run()(null:295)
at java.util.concurrent.Executors$RunnableAdapter.call()(Executors.java:422)
at java.util.concurrent.FutureTask.run()(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker()(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run()(ThreadPoolExecutor.java:587)
at java.lang.Thread.run()(Thread.java:818)

**Comment by ojw28** [comment] 2017-03-21 14:31
Closing for now, since there's nothing actionable here and no evidence ExoPlayer is the root cause. If it were ExoPlayer, I'd expect other users of the library to be reporting the same thing. I'm not sure we've received any other reports, which kind of points toward something specific to your application code (or streams).

**Closed as completed by ojw28** 2017-03-21 14:31 UTC
Labels: need more info

**Comment by AquilesCanta** [comment] 2017-03-21 14:38
As @ojw28 said above, the stack trace only shows what triggers the exception.

I'd suggest emulating the circumstances under which the error was reported. After a few hours, a memory dump should show a suspiciously high amount of a specific type of object allocated. That will give you a significant hint pointing towards the root cause.
