### ISSUE TITLE
When the audio is playing, when it is about to end, the value obtained by getCurrentPosition is greater than the total duration

### ISSUE THREAD

**Issue by 756230883** [google/ExoPlayer#11210] opened 2023-06-14 04:04 UTC
### Bug

![image](https://github.com/google/ExoPlayer/assets/9440937/b56d0f31-5827-4a75-a593-63e35f180673)

Please look at this log,The front of the log is the current progress, followed by the total duration,the value obtained through getCurrentPosition is greater than the value of getDuration. This happens for a few seconds, and then playback is complete
The audio address is 
https://oss.nbs.cn/M00/22/E4/wKhkDmPZ1uSAJWFwAlYRLUW4gK0892.mp3
Please help to find out where the problem is, thank you.

**Comment by rohitjoins** [comment] 2023-06-14 08:00
Please use the existing issue. Closing as duplicate of #11205.

**Closed as completed by rohitjoins** 2023-06-14 08:00 UTC
Labels: bug, duplicate
