### ISSUE TITLE
Video issue with tunnel mode enable  

### ISSUE THREAD

**Issue by ErezNe** [google/ExoPlayer#4225] opened 2018-05-08 15:05 UTC
Hi ,
I enable on the fly  tunnel mode on 2.5.4 version with HEVC content over DASH without
 DRM  encrypted ,
 while enable the video tunnel and try to play the  content I can not  see  video but only  hear audio  ! 

I trace logs via logcat   and can see The issue happened at ExoPlayerImplInternal
The following is the detail information.

• up layer create video instance for tunnel mode and destroy it after about 400ms. 
• com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer try to create the audio track and initial it failed.

see attach logcat  starting at ~ 05-07 09:17:29.9 

why the application(exoplayer or third party) create the audio track or initial audio track failed?
Do you familiar with such an issue on ver 2.5.4 ?
Does some thing change \fix between ver 2.5.4 to 2.7.0 regarding Video tunnel ?

Erez

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
Technicolor STB 
AndriodTV ver 7.0

[tunnel_not_OK.log](https://github.com/google/ExoPlayer/files/1984477/tunnel_not_OK.log)

**Comment by ojw28** [comment] 2018-05-08 15:56
Duplicate of https://github.com/google/ExoPlayer/issues/3675.

**Closed as completed by ojw28** 2018-05-08 15:56 UTC
Labels: duplicate
