### ISSUE TITLE
I found a strange bug may be due to proguard.

### ISSUE THREAD

**Issue by AlanCheen** [google/ExoPlayer#748] opened 2015-08-31 02:50 UTC
I found my app can't play some videos well when i proguarded my app but play the same video well when debug.

At first i think it's Color OS's bug,cause it happens on ColorOS only but when i build a debug app it plays well.

Then, i tried the exoplayer demo ,but nothing changed.

So i think may be it's the proguard affect the exoplayer? I can't find any other reason.  

e.g. URL : `http://s.5dktv.com/hls/f4/30100127_72_1.m3u8`

The log when can't play:
```
08-31 10:07:24.297  23357-23357/? D/EventLogger﹕ start [0]
08-31 10:07:24.297  23357-23357/? D/EventLogger﹕ state [0.00, false, P]
08-31 10:07:24.307  23357-23357/? D/EventLogger﹕ state [0.01, true, P]
08-31 10:07:27.841  23357-23357/? D/EventLogger﹕ state [3.54, true, B]
08-31 10:07:27.851  23357-23357/? D/EventLogger﹕ videoFormat [3.55, 0, 0]
08-31 10:07:28.001  23357-23357/? D/EventLogger﹕ decoderInitialized [3.70, OMX.qcom.video.decoder.avc]
08-31 10:07:28.262  23357-23357/? D/EventLogger﹕ videoSizeChanged [320, 568, 1.0]
08-31 10:07:29.673  23357-23357/? D/EventLogger﹕ state [5.38, true, R]
08-31 10:07:29.893  23357-23357/? E/EventLogger﹕ internalError [5.59, loadError]
    com.google.android.exoplayer.i.u$d: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.i.u$b.run(Loader.java:222)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.j.n.c(ParsableBitArray.java:147)
            at com.google.android.exoplayer.e.c.k$b.b(TsExtractor.java:552)
            at com.google.android.exoplayer.e.c.k$b.a(TsExtractor.java:471)
            at com.google.android.exoplayer.e.c.k.a(TsExtractor.java:149)
            at com.google.android.exoplayer.f.c.a(HlsExtractorWrapper.java:225)
            at com.google.android.exoplayer.f.p.h(TsChunk.java:110)
            at com.google.android.exoplayer.i.u$b.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
08-31 10:07:30.814  23357-23357/? E/EventLogger﹕ internalError [6.51, loadError]
    com.google.android.exoplayer.i.s$a: Unable to connect to http://s.5dktv.com/hls/f4/30100127_72_1-0.ts
            at com.google.android.exoplayer.i.p.a(DefaultHttpDataSource.java:192)
            at com.google.android.exoplayer.i.q.a(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.f.p.h(TsChunk.java:103)
            at com.google.android.exoplayer.i.u$b.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.net.ConnectException: failed to connect to s.5dktv.com/221.181.200.237 (port 80) after 8000ms: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.IoBridge.connect(IoBridge.java:114)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
            at java.net.Socket.connect(Socket.java:842)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
            at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
            at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
            at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
            at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
            at libcore.net.http.HttpEngine.connect(HttpEngine.java:311)
            at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
            at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
            at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
            at com.google.android.exoplayer.i.p.b(DefaultHttpDataSource.java:340)
            at com.google.android.exoplayer.i.p.a(DefaultHttpDataSource.java:190)
            at com.google.android.exoplayer.i.q.a(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.f.p.h(TsChunk.java:103)
            at com.google.android.exoplayer.i.u$b.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: libcore.io.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.Posix.connect(Native Method)
            at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:144)
            at libcore.io.IoBridge.connect(IoBridge.java:112)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
            at java.net.Socket.connect(Socket.java:842)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
            at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
            at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
            at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
            at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
            at libcore.net.http.HttpEngine.connect(HttpEngine.java:311)
            at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
            at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
            at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
            at com.google.android.exoplayer.i.p.b(DefaultHttpDataSource.java:340)
            at com.google.android.exoplayer.i.p.a(DefaultHttpDataSource.java:190)
            at com.google.android.exoplayer.i.q.a(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.f.p.h(TsChunk.java:103)
            at com.google.android.exoplayer.i.u$b.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
08-31 10:07:30.844  23357-23357/? D/EventLogger﹕ state [6.55, true, B]
08-31 10:07:31.825  23357-23357/? E/EventLogger﹕ internalError [7.52, loadError]
    com.google.android.exoplayer.i.s$a: Unable to connect to http://s.5dktv.com/hls/f4/30100127_72_1-0.ts
            at com.google.android.exoplayer.i.p.a(DefaultHttpDataSource.java:192)
            at com.google.android.exoplayer.i.q.a(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.f.p.h(TsChunk.java:103)
            at com.google.android.exoplayer.i.u$b.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.net.ConnectException: failed to connect to s.5dktv.com/221.181.200.237 (port 80) after 8000ms: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.IoBridge.connect(IoBridge.java:114)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
            at java.net.Socket.connect(Socket.java:842)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
            at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
            at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
            at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
            at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
            at libcore.net.http.HttpEngine.connect(HttpEngine.java:311)
            at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
            at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
            at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
            at com.google.android.exoplayer.i.p.b(DefaultHttpDataSource.java:340)
            at com.google.android.exoplayer.i.p.a(DefaultHttpDataSource.java:190)
            at com.google.android.exoplayer.i.q.a(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.f.p.h(TsChunk.java:103)
            at com.google.android.exoplayer.i.u$b.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: libcore.io.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
            at libcore.io.Posix.connect(Native Method)
            at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:144)
            at libcore.io.IoBridge.connect(IoBridge.java:112)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
            at java.net.Socket.connect(Socket.java:842)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
            at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
            at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
            at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
            at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
            at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
            at libcore.net.http.HttpEngine.connect(HttpEngine.java:311)
            at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
            at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
            at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
            at com.google.android.exoplayer.i.p.b(DefaultHttpDataSource.java:340)
            at com.google.android.exoplayer.i.p.a(DefaultHttpDataSource.java:190)
            at com.google.android.exoplayer.i.q.a(DefaultUriDataSource.java:136)
            at com.google.android.exoplayer.f.p.h(TsChunk.java:103)
            at com.google.android.exoplayer.i.u$b.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
08-31 10:07:33.827  23357-23357/? E/EventLogger﹕ internalError [9.53, loadError]
08-31 10:07:33.847  23357-23357/? E/EventLogger﹕ playerFailed [9.55]
08-31 10:07:34.008  23357-23357/? D/EventLogger﹕ state [9.70, true, I]
08-31 10:07:35.549  23357-23357/? D/EventLogger﹕ end [11.25]

```
Sorry for my poor english,may the url and log will help you understand what i said.
Thank you in advance.

**Comment by AlanCheen** [comment] 2015-08-31 09:15
Update more details:
Device: OnePlus A0001(4.3),ExoPlayer 1.4.1
`ArrayIndexOutOfBoundsException` 

The log:
```
08-31 17:06:41.840  29968-30228/? E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
            at com.google.android.exoplayer.util.ParsableBitArray.readBits(ParsableBitArray.java:162)
            at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.parseHeader(TsExtractor.java:552)
            at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:471)
            at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:149)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:225)
            at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:110)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
```

I don't know why the byteOffset will be 9 .
Hope you can fix this bug or give me some advice.

**Comment by ojw28** [comment] 2015-08-31 14:22
Was the second stack trace non-obfuscated because you de-obfuscated it, or because it wasn't obfuscated in the first place (in which case the issue isn't proguard related)? Does this definitely not occur if you don't apply proguard?

**Comment by AlanCheen** [comment] 2015-09-01 02:35
The first stack is obfuscated and the second is non-obfuscated.
This issue definitely not occur if i don't apply proguard.
And it seems only happened on OnePlus A0001(4.3) .

**Comment by AlanCheen** [comment] 2015-09-01 02:39
BTW,there is nothing in my proguard-rules.pro file.
Just set minifyEnabled :
```
buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.adhoc
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by ojw28** [comment] 2015-09-01 14:14
I don't really know what to say about this. It works fine with or without proguard on approved Android devices. It's hard to say whether it's a proguard issue or a ColorOS issue. It's unlikely to be an ExoPlayer issue, at first glance.

**Comment by gongshoudao** [comment] 2015-09-04 16:09
I find this bug ,too. android 4.1~4.2,and 4.4+ is ok.bug 4.3 has this bug.
If I don't proguard,All versions are no problem.
Has any way to fix this ?

**Comment by AlanCheen** [comment] 2015-09-06 03:37
It seems ExoPlayer has bug on android 4.3 ? Because the OnePlus A0001 i have mentioned is 4.3 too.
What's more, @gongshoudao said `but 4.3 has this bug`
Have you tested with any device on android 4.3? @ojw28
I don't have any other device on android 4.3 so i can't figuare out the reason which really cause the bug.

**Comment by souji1103** [comment] 2015-09-16 02:37
@AlanCheen
I resolved same problem below modification.
#796

If possible, please check whether the exceptions of your device clear by this codes.

**Comment by AlanCheen** [comment] 2015-09-16 03:35
@souji1103 
Thanks a lot.
I will have a try.Keep in touch.

**Comment by ojw28** [comment] 2015-09-18 17:34
We believe this is now fixed thanks to @souji1103 . Please re-open if not.

**Closed** 2015-09-18 17:34 UTC
Labels: need more info

**Comment by gongshoudao** [comment] 2015-09-22 13:52
Thanks @ojw28 .I have tested.It's has resolved.

**Comment by AlanCheen** [comment] 2015-09-25 01:46
@souji1103 @ojw28 
It is fixed.Thanks
