### ISSUE TITLE
Crashes with java.lang.IllegalStateException

### ISSUE THREAD

**Issue by evorotilova** [google/ExoPlayer#1311] opened 2016-02-25 11:24 UTC
Hello,

We detected a frequent crash while playing DRM. The details are: Android  4.4.4, Samsung GT-N7100.

We play any MRDM content and after that our application crashes. Here is the link to Fabric with detailed information about the crash - http://crashes.to/s/4a09f97c41a
Also ADB-log file is attached.
[log_mdrm.txt](https://github.com/google/ExoPlayer/files/146343/log_mdrm.txt)

**Comment by AquilesCanta** [comment] 2016-03-11 10:36
Sorry for the delay. We need you to provide a way to reproduce the crash ourselves, as stated in the issue template.

**Comment by evorotilova** [comment] 2016-03-11 10:47
Hello,

We cannot reproduce the crash ourselves. It reproduces on our customers' devices, we just got the crash issue in Fabric. Our devices play MRDM correctly.
We would like you to catch and handle the exception and return us a callback with an error.

**Comment by AquilesCanta** [comment] 2016-03-11 10:57
I will see what I can do. I will write back soon.

**Comment by evorotilova** [comment] 2016-03-25 16:50
Hi,
Any update?

**Comment by AquilesCanta** [comment] 2016-03-28 00:49
Should have assigned it to myself, I lost track of this. I doubt we will be able to do anything about the error itself, considering you are not able to reproduce this (and looks device specific). It is strange, though, that it happens with any DRMed content, it would be helpful for us to know what "any" means in that context.

On the other topic, the error callback method, I doubt this is a good way for us to go. The exception, being an IllegalStateException, shouldn't be in the category of "things that should be handled". In the application point of view, I guess you want to fail gracefully, which I understand. But in the library point of view, you don't want to add error handling for states which are expected not to occur. 

Considering this is a very specific and not reproducible error, I think this should be handled on application code as elegantly as possible, I guess you could use your own patch if needed. I don't think modifications to the library of this kind are a very sound design, it would mean that the thrown exception is not appropriate. @ojw28 will have the final word on this.

**Comment by evorotilova** [comment] 2016-03-28 11:00
We observe a plenty of such crash, more than a hundred a day so it is not the single case. Unfortunately we don't have any device where the error occurs.
I understand your doubts about impossibility to reproduce it. So what additional information or details may help you?

**Comment by wvpaf** [comment] 2016-05-10 22:27
A full ADB bug report will be helpful, however if this is not easily repro'ed we will need close as 'no repro'.

**Comment by evorotilova** [comment] 2016-05-11 13:14
> A full ADB bug report will be helpful, however if this is not easily repro'ed we will need close as 'no repro'.

Here it is.
[fulladblog.txt](https://github.com/google/ExoPlayer/files/259331/fulladblog.txt)

**Comment by wvpaf** [comment] 2016-06-07 22:29
Sorry can we get an ADB Bugreport?  The log does not provide enough data.

**Comment by evorotilova** [comment] 2016-06-09 10:41
> Sorry can we get an ADB Bugreport? The log does not provide enough data.

The fragment of an ADB log is inside of fulladblog.txt. It is in frames "adblog >>>".

**Comment by wvpaf** [comment] 2016-08-02 22:13
Hi @evorotilova  any full logs?  If not we will consider the case closed in  7 days.

**Closed** 2016-08-09 20:37 UTC
Labels: need more info
