### ISSUE TITLE
Changing textureView between activities

### ISSUE THREAD

**Issue by SlavaVoltfman** [google/ExoPlayer#3536] opened 2017-12-02 07:48 UTC
Hi,
I am using Brightcove lib version 6.0.0 with ExoPlayer 2 r2.5.3.
I am trying to make video transition between two activities, to show smooth video transition.
i tried to switch surfaces, but when i do so on android devices with OS upper than 6 everything is working good. on OS under, i have incurred a problem. In some devices like Nexus 5, Samsung S5 (OS 6.0.1) and Samsung j7(OS 5), in the second activity video isn't playing and starts playing only if i rotate screen to landscape mode. is there a good way to continue playing my video from the last position in the second activity without any hiccups?

[VideoTransitionSample.zip](https://github.com/google/ExoPlayer/files/1523635/VideoTransitionSample.zip)

**Comment by botaydotcom** [comment] 2017-12-04 10:32
Duplicate of #677 .

**Closed as completed by botaydotcom** 2017-12-04 10:32 UTC
Labels: duplicate
