### ISSUE TITLE
Unable to play DRM content in multiple devices

### ISSUE THREAD

**Issue by sridhard** [google/ExoPlayer#10155] opened 2022-04-05 14:31 UTC
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Oneplus

### Devices that do not reproduce the issue

Samsung

### Reproducible in the demo app?

Not tested

### Reproduction steps

It is happening in customer devices. We are getting multiple tickets for this issue. Mobile device failed to get the DRM license.
I have checked other bug reports like #8373 #8175 #8039. All these issues are open from long time. Can you please provide a way for re-provisioning in exoplayer or can you provide a way how application can do it? many of our users are facing this issue and we are under pressure to solve it .  

```
04-02 18:01:41.243 30996 11114 W System  : A resource failed to call release. 
04-02 18:01:41.243 30996 11114 W System  : A resource failed to call close. 
04-02 18:01:41.242 30996 11114 W System  : A resource failed to call close. 
04-02 18:01:34.777 30996 15775 W System.err: 	... 10 more
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:428)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:165)
04-02 18:01:34.777 30996 15775 W System.err: 	at android.media.MediaDrm.getKeyRequest(Native Method)
04-02 18:01:34.777 30996 15775 W System.err: Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
04-02 18:01:34.777 30996 15775 W System.err: 	at java.lang.Thread.run(Thread.java:923)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.learnyst.lstdrmv2.LstDrmv2Module$9.run(LstDrmv2Module.java:808)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.learnyst.lstdrmv2.LstDrmv2Module.lstDownloadWidevineLicense(LstDrmv2Module.java:1131)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.learnyst.lstdrmv2.WidevineLicense.downloadWidevineLicense(WidevineLicense.java:147)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.OfflineLicenseHelper.downloadLicense(OfflineLicenseHelper.java:174)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:243)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:259)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:536)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:271)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:388)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:432)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:481)
04-02 18:01:34.777 30996 15775 W System.err: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:486)
04-02 18:01:34.777 30996 15775 W System.err: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
04-02 18:01:34.773 30996 15775 E MediaDrm-JNI: Illegal state exception: Failed to get key request: General DRM error (-2000)
```

### Expected result

DRM license should be success

### Actual result

Not able to get license

### Media

We cannot reproduce. it is happening in customer device. 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rrfrias** [comment] 2022-04-20 00:56
Might it be possible to get us an exception from an android S device? We have added more detail that should help us investigate the specific failure. If you have a bugreport, that would be much appreciated.

It is not clear without knowing more about the error whether reprovisioning might help (see https://github.com/google/ExoPlayer/issues/8039#issuecomment-738177785)

@icbaker might you be able to provide some suggestions to reprovision?

**Comment by icbaker** [comment] 2022-04-20 09:49
I added a new comment to #8039 with a suggestion of how to manually trigger re-provisioning: https://github.com/google/ExoPlayer/issues/8039#issuecomment-1103723535

**Comment by rrfrias** [comment] 2022-04-20 21:43
@sridhard You can use @icbaker suggestions to reprovision. If you can capture an exception from an android S device or a bugreport, that would be helpful for us to root cause the issue. If there are no other action items, we will close this in issue in 2 weeks.

**Closed as completed** 2022-05-06 10:50 UTC
Labels: need more info, bug: in platform drm
