### ISSUE TITLE
ExoPlayer fails to play from starting of Hls stream when trying to play second time 

### ISSUE THREAD

**Issue by mcse541** [google/ExoPlayer#2602] opened 2017-03-24 08:49 UTC
When trying to play hls streams in my application initially playback happens but when trying to play the same video next time , the frame starts at a random position and start playing, After 5-10 seconds of playback the player is in buffering state and does not play any more.

But this issue is not observed in ExoPlayer demo app with same stream. I tried with the same PlayerActivity which is used in the demo app.
ExoPlayer Version - 2.0.4
Device(s) and version(s) of Android - Sony AndroidTV with version 5.1.1
This issue is not occurring in Nexus Player with version 7.1.1

Attached the logs of the issue.Please take a look on it.

[exoplayer logs for the same stream.txt](https://github.com/google/ExoPlayer/files/867290/exoplayer.logs.for.the.same.stream.txt)

[Log when player is in buffer state and  no playback happens further.txt](https://github.com/google/ExoPlayer/files/867639/Log.when.player.is.in.buffer.state.and.no.playback.happens.further.txt)
[Log when back pressed from PlayerActivity.txt](https://github.com/google/ExoPlayer/files/867638/Log.when.back.pressed.from.PlayerActivity.txt)

**Comment by mcse541** [comment] 2017-03-24 08:50
[Log when back pressed from PlayerActivity.txt](https://github.com/google/ExoPlayer/files/867298/Log.when.back.pressed.from.PlayerActivity.txt)
[exoplayer logs for the same stream.txt](https://github.com/google/ExoPlayer/files/867297/exoplayer.logs.for.the.same.stream.txt)

**Comment by ojw28** [comment] 2017-03-27 09:22
Please provide clear reproduction steps in the demo app if you want us to look at this, including what test media we should use.

**Comment by ojw28** [comment] 2017-04-27 10:05
Closing due to lack of information. Also, if the issue doesn't reproduce in the demo app, that suggests the problem is in your own code rather than ExoPlayer.

**Closed as completed by ojw28** 2017-04-27 10:05 UTC
Labels: need more info
