### ISSUE TITLE
[CastPlayer] Detecting media source ended

### ISSUE THREAD

**Issue by mkaflowski** [google/ExoPlayer#4130] opened 2018-04-16 13:01 UTC
How to detect that media has finished for CastPlayer? For Exoplayer there is state STATE_ENDED but CastPlayer goes into STATE_IDLE. The STATE_IDLE occurs when I connect to Chromecast device so I cannot use it as well.

**Comment by AquilesCanta** [comment] 2018-04-16 13:07
Would it be not possible for you to track changes from READY to IDLE? Session state needs to be tracked separately, though.

**Comment by mkaflowski** [comment] 2018-04-16 13:42
The player is READY when I cast, when I stop casting and return to casting it goes to IDLE and then to READY so I would get the recognize it as complete then as well. Is that normal behaviour that it goes to IDLE during connecting to Chromecast or I messed up something?

**Comment by AquilesCanta** [comment] 2018-04-16 14:18
> Is that normal behaviour that it goes to IDLE during connecting to Chromecast or I messed up something?

It is normal. This has generated internal discussions, actually. When Cast ends playing a media queue, it empties it. In Player terms, this means the timeline gets emptied. Now, transitioning to ENDED state makes sense. It is documented as follows:

`The player has finished playing the media.`

However, transitioning to IDLE state also makes sense due to the behavior described above:

`The player does not have any media to play.`

This has put on the table the possibility of removing the ended state. For the time being, the discussion is in stand by.
> when I stop casting

Do you mean the session ends? I don't fully understand your usecase, but tracking the session state + the player state does not solve your issue?

**Comment by mkaflowski** [comment] 2018-04-16 14:32
By stoping casting I mean tapping MediaRouteButton and tap the button "Stop Casting". The CastPlayer is in the READY state and when I want to reconnect to Chromecast by tapping MediaRouteButton and selecting device I get IDLE (current state is still READY) and READY then.

[Edit] The use-case video: [Video](https://drive.google.com/open?id=1G88Nih4G89IbDuTbTtWkZ7oboJ5brlCD)

**Comment by deRonbrown** [comment] 2018-08-29 15:27
Would it be possible to make `CastPlayer#getMediaStatus()` public?
```
private @Nullable MediaStatus getMediaStatus() {
  return remoteMediaClient != null ? remoteMediaClient.getMediaStatus() : null;
}
```

With that information one could use [getIdleReason()](https://developers.google.com/android/reference/com/google/android/gms/cast/MediaStatus.html#getIdleReason()).  That value would be one of `IDLE_REASON_CANCELED`, `IDLE_REASON_ERROR`, `IDLE_REASON_FINISHED`, `IDLE_REASON_INTERRUPTED`, or `IDLE_REASON_NONE`.

**Comment by deRonbrown** [comment] 2018-08-29 15:43
Actually, no need to make that method public. Just grab the `IDLE_REASON` directly from the `CastSession`:

```
SessionManager sessionManager = CastContext.getSharedInstance(context).getSessionManager();
CastSession castSession = sessionManager.getCurrentCastSession();
if (castSession != null) {
  RemoteMediaClient remoteMediaClient = castSession.getRemoteMediaClient();
  if (remoteMediaClient != null) {
    if (MediaStatus.IDLE_REASON_FINISHED == remoteMediaClient.getIdleReason()) {
      // TODO                            
    }
  }
}
```

**Comment by meenukrishnamurthy** [comment] 2019-03-04 10:16
Any update on this??

**Comment by ojw28** [comment] 2019-09-14 22:19
Marking as a duplicate of https://github.com/google/ExoPlayer/issues/3969

**Closed as completed by ojw28** 2019-09-14 22:19 UTC
Labels: duplicate
