### ISSUE TITLE
Baby Step: Query String to sub m3u8 file

### ISSUE THREAD

**Issue by Rajeshr34** [google/ExoPlayer#6065] opened 2019-06-19 17:14 UTC
Hello 
In the below filler log (Proxy Log) i got below response.

`GET: http://example.com/And_Pictures_HD/And_Pictures_HD.m3u8?jt=w99HKZoqtszkcyKc=1560969436`

Response:
```

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,CLOSED-CAPTIONS=NONE,BANDWIDTH=400000
And_Pictures_HD_400.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,CLOSED-CAPTIONS=NONE,BANDWIDTH=600000
And_Pictures_HD_600.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,CLOSED-CAPTIONS=NONE,BANDWIDTH=800000
And_Pictures_HD_800.m3u8
```

But Soon After ExoPlayer Tries to get first m3u8 file like this

GET:  http://example.com/And_Pictures_HD/And_Pictures_HD_400.m3u8

Response:
```
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

I would like to add same query String to the above url how can i do that. I have spent 20+hrs finding the above issue please a little help would be great.

Result Wanted: 
http://example.com/And_Pictures_HD/And_Pictures_HD_400.m3u8?jt=w99HKZoqtszkcyKc=1560969436

**Comment by AquilesCanta** [comment] 2019-06-19 18:16
This is a duplicate of #4501.

I can see two ways: 
- The first (better) is fixing the content so that it includes the token in the master playlist's URLs.
- The second is injecting a custom DataSource using [HlsDataSourceFactory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/HlsDataSourceFactory.html) that intercepts requests for segments and injects the token into the requested URIs.

Hope this helps!

**Comment by tonihei** [comment] 2019-06-20 08:08
For the second issue, you can also use a `ResolvingDataSource` which is added in 2.10.2. That makes the implementation for such cases a lot easier.

**Comment by cobookman** [comment] 2019-09-05 06:46
@tonihei, would the following be how to use ResolvingDataSource for injecting QueryStrings to video segments?


```
public class MainActivity extends AppCompatActivity {
  @Override
  protected void onCreate ( Bundle savedInstanceState ) {
    Context context = getApplicationContext();

    // URL pointing to the DASH Manifest
    Uri dashManifest = Uri.parse("https://myservice.com/manifest.mpd");

    // query string to inject for HTTP calls to resources listed in the manifest (cough video, audio, subtitle)
    String queryStringInjection = "?someQuery=string&with=values";


    // Create a data source factory.
    DataSource.Factory upstreamDataSource = new DefaultHttpDataSourceFactory(Util.getUserAgent(context, "app-name"));

    // Code which determines how to resolve network resources
    ResolvingDataSource.Resolver resolver = new Resolver() {
      // Not modifing dataSpec.
      DataSpec resolveDataSpec(DataSpec dataSpec) throws IOException {
        return dataSpec;
      }

      /**
       * Injects Signed URL Query String
       * The ResolvingDataSource first grabs a Network Request generated
       * by an upstreamDataSource. Then resolvReportedUri(uri) is called for 
       * getUri(..) calls. 
       */
      default Uri resolveReportedUri(Uri uri) {
        return uri + queryStringInjection;
      }
    };

    DataSource.Factory dataSourceFactory = new ResolvingDataSource.Factory(upstreamDataSource, resolver);


    // Create a DASH media source pointing to a DASH manifest uri.
    MediaSource mediaSource = new DashMediaSource.Factory(dataSourceFactory).createMediaSource(dashManifest);

    // Create a player instance.
    SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(context);

    // Prepare the player with the DASH media source.
    player.prepare(mediaSource);
  }
}
```

**Comment by ojw28** [comment] 2020-06-08 23:22
@tonihei - Please see the question above.

**Comment by tonihei** [comment] 2020-07-06 09:21
Sorry for the delayed answer, I didn't realize you posted a reply!

The `ResolvingDataSource` needs to amend the `DataSpec` to do what you'd like to do:

```
new ResolvingDataSource.Factory(
    upstreamDataSource, 
    dataSpec -> dataSpec.withUri(uri + queryStringInjection);
```

There is no need to override `resolveReportedUri` unless you want to revert the operation for event reporting.

**Comment by tonihei** [comment] 2020-08-27 13:21
Closing this issue again because the extra question was answered.

**Closed as completed by tonihei** 2020-08-27 13:21 UTC
Labels: question
