### ISSUE TITLE
Support crossfading

### ISSUE THREAD

**Issue by frakc** [google/ExoPlayer#4414] opened 2018-06-23 15:26 UTC
If there is concatinatingmediasource i wonder if there is feature which does following:
player plays last 10 seconds of a track whth volume goes down to 0
and at same time next tack startswith volume which goes from 0 to current level, effectivly makeing 2 tracks sounds in same time at some point. 
I did not notice mediasource with such option when i scroll though them and assume the only way is to use 2 players at same time utilising clipmediasource and runnable action on their completion

**Comment by DKillWorld** [comment] 2018-06-24 17:31
What you want is cross-fade between mediasources. but there is no option for this yet.

**Comment by ojw28** [comment] 2018-06-25 10:02
@andrewlewis - Feel free to dupe this if there's already a tracking issue (I couldn't find one).

**Comment by DKillWorld** [comment] 2018-06-25 11:59
It would be helpful to have Crossfade object with as simple constructor as crossfade(boolean forcedCrossfade, long time). 

forcedCrossfade - false if you dont want to fade between tracks when you are manually changing tracks (default).  true for opposite.
time - actual crossfade time for which both tracks should be played in.

**Comment by BrainCrumbz** [comment] 2018-07-20 15:54
It looks like this is a duplicate of #3438

**Comment by andrewlewis** [comment] 2018-07-20 15:58
Duplicate of #3438

**Closed as completed by andrewlewis** 2018-07-20 15:58 UTC
Labels: enhancement
