### ISSUE TITLE
How to download a drm file which has multiple drm keys

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#8924] opened 2021-05-10 07:03 UTC
Problem
======
We have a Widevine drm content which has the following properties

1. Audio track is encrypted with one drm key
2. The video tracks below 720p are encrypted with a 2nd drm key
3. The video tracks above 720p are encrypted with a 3rd drm key (L1 widevine)

Question
=======
1. How can we download multiple keys for each of these tracks separately and play the downloaded content? 

When we call **offlineLicenseHelper.downloadLicense()** with drmInitData, we are getting one byte array as drm key

2. If there is a way to download multiple drm keys then how can we pass the keys when we play the audio and video track?

Please let us know if this feature is available in exoplayer. Our current exoplayer version is 2.11.8

**Comment by ojw28** [comment] 2021-05-10 11:21
This is documented as a limitation on the [DRM page](https://exoplayer.dev/drm.html#offline-keys) of our documentation. That page also links to the tracking issue (https://github.com/google/ExoPlayer/issues/3872). Closing as a duplicate of that issue.

**Closed as completed by ojw28** 2021-05-10 11:21 UTC
Labels: duplicate
