### ISSUE TITLE
Auto Adaptive bit-rate in Exoplayer (Stuck in lowest resolution)

### ISSUE THREAD

**Issue by jboisjo** [google/ExoPlayer#3320] opened 2017-10-03 19:09 UTC
Hi, when i play a video using exoplayer, it keeps getting stuck in the lowest profile in our m3u8 playlist. Is there a way that the plays gets the next and highest profile?

I tried on a Nvidia Shield on Android 7.0 and with exoplayer:r2.5.1'

Here's my class...

```
public class MainActivity extends Activity implements VideoRendererEventListener {


    private SimpleExoPlayerView simpleExoPlayerView;
    private String hlsVideoUri = "m3u8 playlist url";

    private SimpleExoPlayer player;
    private ProgressBar progressBar;

    private TextView resolutionTextView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // 1. Create a default TrackSelector
        Handler mainHandler = new Handler();
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);

        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        

        // 2. Create a default LoadControl
        LoadControl loadControl = new DefaultLoadControl();


        // 3. Create the player
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);

        simpleExoPlayerView = new SimpleExoPlayerView(this);
        simpleExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.player_view);


        simpleExoPlayerView.setUseController(true);
        simpleExoPlayerView.requestFocus();

        simpleExoPlayerView.setPlayer(player);


        // Measures bandwidth during playback. Can be null if not required.
        DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter();
        // Produces DataSource instances through which media data is loaded.

        DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory("User-Agent", defaultBandwidthMeter);

        // Produces Extractor instances for parsing the media data.
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();


        // This is the MediaSource representing the media to be played.

         HlsMediaSource hlsMediaSource = new HlsMediaSource(Uri.parse(hlsVideoUri), dataSourceFactory, mainHandler, new AdaptiveMediaSourceEventListener() {
            @Override
            public void onLoadStarted(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs) {

            }

            @Override
            public void onLoadCompleted(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

            }

            @Override
            public void onLoadCanceled(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

            }

            @Override
            public void onLoadError(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded, IOException error, boolean wasCanceled) {

            }

            @Override
            public void onUpstreamDiscarded(int trackType, long mediaStartTimeMs, long mediaEndTimeMs) {

            }

            @Override
            public void onDownstreamFormatChanged(int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaTimeMs) {

            }
        });

        final LoopingMediaSource loopingSource = new LoopingMediaSource(hlsMediaSource);
        player.prepare(loopingSource);
        simpleExoPlayerView.requestFocus();
        player.setPlayWhenReady(true);

        progressBar = (ProgressBar) findViewById(R.id.progressBar);
    }


    @Override
    protected void onPause() {
        super.onPause();
        if (player != null) {
            player.setPlayWhenReady(false); //to pause a video because now our video player is not in focus
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        player.release();
    }


    @Override
    public void onVideoEnabled(DecoderCounters counters) {

    }

    @Override
    public void onVideoDecoderInitialized(String decoderName, long initializedTimestampMs, long initializationDurationMs) {

    }

    @Override
    public void onVideoInputFormatChanged(Format format) {

    }

    @Override
    public void onDroppedFrames(int count, long elapsedMs) {

    }

    @Override
    public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio) {
        Log.d("height", "wi" + width);
        resolutionTextView.setText("RES:(WxH):"+width+"X"+height +"\n           "+height+"p");
    }

    @Override
    public void onRenderedFirstFrame(Surface surface) {

    }

    @Override
    public void onVideoDisabled(DecoderCounters counters) {

    }
}

```

**Comment by ojw28** [comment] 2017-10-04 00:50
Are you playing a live stream, or is this on-demand? If you're playing a live stream, this is most likely a duplicate of #3017, which is fixed in the `dev-v2` branch.

If you're playing an on-demand stream and are seeing this issue, we'd need access to the stream to investigate. Please clarify. Thanks!

**Comment by jboisjo** [comment] 2017-10-04 15:30
it's a livestream and it keeps doing the samething even with the dev-v2 branch. When i set the DEFAULT_MAX_INITIAL_BITRATE to higher, it gets the higher available, but still doesn't switch up inside the masterPlaylist :(

**Comment by botaydotcom** [comment] 2017-10-04 15:49
Hi Jay,
In dev-v2 branch, after this commit [5019da3](https://github.com/google/ExoPlayer/commit/5019da3e7b499f50dadfe691af807327e79b5d7c) there was another parameter in AdaptiveTrackSelection `bufferedFractionToLiveEdgeForQualityIncrease` specifically added for livestreaming case. This is the fraction of duration from current playback position until the live edge that should have been buffered to allow player to switch up to a higher quality stream. Default value = 0.75.
Could you try to tweak this (most likely reduce) and see if it makes any difference? Thank you.

**Comment by ojw28** [comment] 2017-10-04 17:36
Please also provide us with the stream you're using when you see this issue, so that we can reproduce.

**Comment by jboisjo** [comment] 2017-10-04 18:43
i found the issue, it's this BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter(); needs to have the mainHandler and the BandwidthMeter.EventListener of the activity....

```
public class MainActivity extends Activity implements BandwidthMeter.EventListener

DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter(mainHandler, this);
```

Now, is there a way to reset the default bandwidth when switching for a new playlist?

Thanks guys for your help!

**Comment by ojw28** [comment] 2017-10-04 19:30
I wouldn't have thought you'd want to. If you have a bandwidth estimate, why would you want to throw it away?

**Comment by jboisjo** [comment] 2017-10-04 19:32
well, on Google Cast and iOS (AVPlayer) when you insert a new playlist, it resets the bandwidth every time, looks like its a standard in HLS...:/

**Comment by ojw28** [comment] 2017-10-04 19:33
Doesn't that mean we're . . . better than standard ;)?

**Comment by jboisjo** [comment] 2017-10-04 19:37
lol ;) if i want to have that, do i need to release or kill the player everytime i insert a new playlist? :)

**Comment by ojw28** [comment] 2017-10-04 19:45
* You could make your own `BandwidthMeter` that you can reset, if it's important to you.
* By the way, I'm pretty sure you don't have to give `DefaultBandwidthMeter` a handler or event listener. The ExoPlayer demo app source code doesn't do that, and adapts successfully. It's likely you just weren't plumbing the instance to somewhere that it was needed.

**Closed as completed by ojw28** 2017-10-04 19:45 UTC
Labels: need more info

**Comment by ojw28** [comment] 2017-10-04 19:48
The problem was that your code was creating two separate instances of `DefaultBandwidthMeter`, one for the adaptive track selection and a separate one for the data source factory. They needed to be the same instance.

**Comment by jboisjo** [comment] 2017-10-04 20:29
Yes exactly! Ty :D
