### ISSUE TITLE
HlsSampleStreamWrapper for text chunks gets stuck loading in TimestampAdjuster.sharedInitializeOrWait()

### ISSUE THREAD

**Issue by Jacko07** [google/ExoPlayer#9203] opened 2021-07-19 10:49 UTC
hi, I have used exoplayer to play hls,m3u8 steam,most fo them play well.but this m3u8 steam was frozen at first frame without any exceptions reported, which it can play well at chrome or linux tv:
[...](url)

this m3u8 steam cannot play in exoplayer demo either, please have a look, thanks!
these below are my config:

```

    implementation 'com.google.android.exoplayer:exoplayer:2.14.1'
    implementation 'com.google.android.exoplayer:extension-ima:2.14.1'
    implementation 'com.google.android.exoplayer:extension-cronet:2.14.1'

```

```

boolean preferExtensionDecoders = false;
RenderersFactory renderersFactory =
        WLPlayerUtil.buildRenderersFactory(/* context= */ this, preferExtensionDecoders);
DataSource.Factory dataSourceFactory = WLPlayerUtil.getDataSourceFactory(/* context= */ this);
MediaSourceFactory mediaSourceFactory =
        new DefaultMediaSourceFactory(dataSourceFactory)
                .setAdsLoaderProvider(this::getAdsLoader)
                .setAdViewProvider(playerView);

DefaultTrackSelector trackSelector = new DefaultTrackSelector(/* context= */ this);
DefaultTrackSelector.ParametersBuilder builder =
        new DefaultTrackSelector.ParametersBuilder(/* context= */ this);
DefaultTrackSelector.Parameters trackSelectorParameters = builder.build();
trackSelector.setParameters(trackSelectorParameters);

player =
        new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
                .setMediaSourceFactory(mediaSourceFactory)
                .setTrackSelector(trackSelector)
                .build();

```

**Comment by marcbaechinger** [comment] 2021-07-19 12:23
Thanks for your report! I can play the stream in the demo app when I disable text tracks. WIth text tracks enabled it stops at the first frame like you report. I can confirm something is not working as expected. When text track is enabled we never get out of the buffering state and the renderers never get started. Besides I also don't see that we actually start loading the subtitle file (only the subtitle playlist is loaded).

There are two text tracks. I think one is in-band (cea-608) and one is a separate vtt track that is selected by default. The web vtt tracks eem to deliver an empty file though when I download with curl:

```
curl "https://linear-142.frequency.stream/dist/zeasn/142/hls/master/playlist_webvtt_121944__1169974.vtt"
WEBVTT
X-TIMESTAMP-MAP=LOCAL:1908:52:27.672,MPEGTS:207000
```

@Jacko07 Can you confirm that subtitle rendering works on the other players you are reporting the stream plays fine?

@icbaker Can you have a look whether I am not mistaken and whether we can avoid on our end whether this blocks rendering of text and video?

**Comment by icbaker** [comment] 2021-07-19 13:13
I think given the WebVTT files are never downloaded, this is probably something related to ExoPlayer's HLS machinery rather than subtitle handling.

(Aside: A mostly empty WebVTT file like that seems fine - I would assume it just means there are no subtitles for the selected segment)

**Comment by Jacko07** [comment] 2021-07-27 10:31
> Thanks for your report! I can play the stream in the demo app when I disable text tracks. WIth text tracks enabled it stops at the first frame like you report. I can confirm something is not working as expected. When text track is enabled we never get out of the buffering state and the renderers never get started. Besides I also don't see that we actually start loading the subtitle file (only the subtitle playlist is loaded).
> 
> There are two text tracks. I think one is in-band (cea-608) and one is a separate vtt track that is selected by default. The web vtt tracks eem to deliver an empty file though when I download with curl:
> 
> ```
> curl "https://linear-142.frequency.stream/dist/zeasn/142/hls/master/playlist_webvtt_121944__1169974.vtt"
> WEBVTT
> X-TIMESTAMP-MAP=LOCAL:1908:52:27.672,MPEGTS:207000
> ```
> 
> @Jacko07 Can you confirm that subtitle rendering works on the other players you are reporting the stream plays fine?
> 
> @icbaker Can you have a look whether I am not mistaken and whether we can avoid on our end whether this blocks rendering of text and video?

hi,on the web player, it also cannot show subtitle. i think steam' empty file cause this error https://github.com/google/ExoPlayer/issues/9203

**Comment by marcbaechinger** [comment] 2021-07-27 19:29
It looks like this issue has the same root cause as #9153. 

With text renderer turned on, execution flow goes into `TimestampAdjuster.sharedInitializeOrWait` and runs into the `wait()` statement that is never released by `notifyAll`. This is the reason why the `HlsSampleStreamWrapper` of the text track never loads a vtt media chunk for which the player actually waits before starting playback. This causes the player to never transition from `STATE_BUFFERING` to `STATE_READY` because `ExoPlayerImplInternal.shouldTransitionToReadyState()` never gets sufficient buffered data from the playing period (`HlsMediaPeriod`).

This situation is removed as soon as the text track is disabled and the `HlsMediaPeriod` has only a single `HlsSampleStreamWrapper` for the ts chunks.

**Comment by ojw28** [comment] 2021-08-02 12:16
Whilst #9153 was a regression introduced by 6f8a8fb, this is not. The stream didn't play successfully even before that commit.

**Comment by ojw28** [comment] 2021-08-02 15:09
I'm not sure exactly what's going on here, but I think the `EXT-X-DISCONTINUITY-SEQUENCE` tags in the media playlists are incorrect. In particular, the WebVTT subtitle playlist appears to have it set correctly, but the other playlists appear to have it incorrectly set to 0.

Weirdly the other playlists are of the following form in the master playlist:
```
#EXT-X-STREAM-INF:...,NAME="url_a",...
url_b
```
When requesting `url_a` the `EXT-X-DISCONTINUITY-SEQUENCE` tag seems to be set properly, but when requesting from `url_b` (as the player should do) it's not. I think we can close this issue because the media appears to be broken.

**Closed as completed by ojw28** 2021-08-02 15:09 UTC
Labels: bad media
