### ISSUE TITLE
How to use IMA extension with Leanback extension?

### ISSUE THREAD

**Issue by sswierczek** [google/ExoPlayer#5369] opened 2019-01-11 12:21 UTC
### Issue description
I am trying to use ExoPlayer with  **Leanback extension** and **IMA extension** to play ads on Android TV. When I just use `AdsMediaSource` I have issues with player controls.

How can I properly use these two or is it not supported yet?

### Reproduction steps
Controls auto hide is broken after ads
- Prepare video with `AdsMediaSource` and any content source
- Wait till ads end
- Controls are not hidden automatically 

This can be "fixed" by clicking pause and play in player controls

I used Leanback example app to demonstrate this: https://github.com/googlesamples/androidtv-Leanback/compare/master...sswierczek:leanback-with-exoplayer-and-ima-extension

### Version of ExoPlayer being used
2.8.4

### Device(s) and version(s) of Android being used
Android TV emulator (API 26), Fire Stick (Fire OS 5.2.6.7)

### A full bug report captured from the device
[bugreport-sdk_google_atv_x86-OSR1.180418.007-2019-01-11-13-18-47.zip](https://github.com/google/ExoPlayer/files/2749561/bugreport-sdk_google_atv_x86-OSR1.180418.007-2019-01-11-13-18-47.zip)

**Comment by andrewlewis** [comment] 2019-01-14 12:17
I wasn't able to get the example working as adding the IMA dependency caused errors with `LoaderManager` probably due to dejetification not working properly. Please let me know if you encountered the same problem and were able to fix it.

We probably need to update `LeanbackPlayerAdapter` to handle disabling/reenabling controls depending on whether the player is showing ads. I am a bit confused about your comment that controls are not hidden automatically. Could you record a video with `adb screenrecord` to show the behavior you're seeing, attach it here and also describe the behavior you want to see? Thanks.

**Comment by sswierczek** [comment] 2019-01-14 13:03
> I wasn't able to get the example working as adding the IMA dependency caused errors with `LoaderManager` probably due to dejetification not working properly. Please let me know if you encountered the same problem and were able to fix it.

I've manage to build without problems. Maybe I will add ima extension on top commit without Android X? 

> We probably need to update `LeanbackPlayerAdapter` to handle disabling/reenabling controls depending on whether the player is showing ads. I am a bit confused about your comment that controls are not hidden automatically. Could you record a video with `adb screenrecord` to show the behavior you're seeing, attach it here and also describe the behavior you want to see? Thanks.

Without IMA extension player controls disappear after a few seconds from video start or after showing them with pressing any key. When ads are enabled they are visible forever unless user pause and play video again. Setting `setControlsOverlayAutoHideEnabled` doesn't help. Looks like controls state is somehow broken and back to normal after pause/play. 

Without IMA:
![jan-14-2019 14-01-21](https://user-images.githubusercontent.com/1423368/51114237-f7edbf80-1804-11e9-9458-93bb7df787ff.gif)

With IMA:
![jan-14-2019 14-01-48](https://user-images.githubusercontent.com/1423368/51114244-fb814680-1804-11e9-847c-186a6cc5edfe.gif)

**Comment by andrewlewis** [comment] 2019-01-14 15:24
> > I wasn't able to get the example working as adding the IMA dependency caused errors with `LoaderManager` probably due to dejetification not working properly. Please let me know if you encountered the same problem and were able to fix it.
> 
> I've manage to build without problems. Maybe I will add ima extension on top commit without Android X?

Strangely the compilation error seemed to be linked to moving the `import static` line above the rest of the imports in `PlaybackFragment` (part of AS optimizing imports). It works after moving it back.
 
> > We probably need to update `LeanbackPlayerAdapter` to handle disabling/reenabling controls depending on whether the player is showing ads. I am a bit confused about your comment that controls are not hidden automatically. Could you record a video with `adb screenrecord` to show the behavior you're seeing, attach it here and also describe the behavior you want to see? Thanks.
> 
> Without IMA extension player controls disappear after a few seconds from video start or after showing them with pressing any key.

Is this definitely true? After the playback controls hide themselves at the beginning of playback, I find that pressing a button causes them to show until playback ends, both with and without IMA. Do I need to enable some other option to reproduce the behavior?

**Comment by sswierczek** [comment] 2019-01-14 15:49
> Is this definitely true? After the playback controls hide themselves at the beginning of playback, I find that pressing a button causes them to show until playback ends, both with and without IMA. Do I need to enable some other option to reproduce the behavior?

Yes, you are right. I was wrong about the pressing buttons, sorry. Seems calling `showControlsOverlay` does the same as pressing buton and controls don't hide after timeout

Anyway i think issue with controls still persists. For me desired behaviour here should be:
- controls are hidden during ads playback and blocked
- controls are showed after ads and hide after timeout when there is no user interaction (like with video start) 

From `PlayerAdapter` interface i assume there is no possibility to show/hide player controls. Seems this should be solved on Leanback side and then ExoPlayer could control overlay in case of ads playback?

**Comment by andrewlewis** [comment] 2019-01-15 12:50
Having discussed with the Leanback team, the suggestion is to try the following on the app side:
- Intercept and drop key events while an ad is playing (when `player.isPlayingAd()` returns true).
- When an ad starts playing call `hideControlsOverlay(false)`. This is needed in `onPositionDiscontinuity` with `DISCONTINUITY_REASON_AD_INSERTION`, and I think also when you get a non-empty timeline if `isPlayingAd` returns true (I haven't checked this case though).
- Call `setControlsOverlayAutoHideEnabled(false)` in `onCreate` so that the controls are not shown automatically on play/pause.

Please let us know if it works, and if so I can make a feature request to access this functionality from the player adapter.

**Comment by sswierczek** [comment] 2019-01-15 16:31
> Having discussed with the Leanback team, the suggestion is to try the following on the app side:
> 
> * Intercept and drop key events while an ad is playing (when `player.isPlayingAd()` returns true).
> * When an ad starts playing call `hideControlsOverlay(false)`. This is needed in `onPositionDiscontinuity` with `DISCONTINUITY_REASON_AD_INSERTION`, and I think also when you get a non-empty timeline if `isPlayingAd` returns true (I haven't checked this case though).
> * Call `setControlsOverlayAutoHideEnabled(false)` in `onCreate` so that the controls are not shown automatically on play/pause.
> 
> Please let us know if it works, and if so I can make a feature request to access this functionality from the player adapter.

- user can still see controls after pressing any button during the ads but at least there is no way to skip or pause them. I could hacky resolve visibility locking  make whole controls GONE but this is not ideal solution:

` view?.findViewById<View>(R.id.playback_controls_dock)?.visibility = View.GONE
`

I think to resolve this from app or player this would require having two methods like:

- `hideOverlayControlsAndLock() `called at ads start, where controls visibility and buttons are locked
- `showOverlayControlsWithTimeout()` method with default timeout to use after ads

**Comment by andrewlewis** [comment] 2019-01-15 16:43
> * user can still see controls after pressing any button during the ads but at least there is no way to skip or pause them. I could hacky resolve visibility locking  make whole controls GONE but this is not ideal solution:

Does intercepting key events in the playback fragment avoid that?

> * `hideOverlayControlsAndLock() `called at ads start, where controls visibility and buttons are locked
> * `showOverlayControlsWithTimeout()` method with default timeout to use after ads

Yes. I've asked the Leanback team about adding making these capabilities available to player adapters so we can make updating the controls automatic, but until that's available it should be possible to implement this on the app side.

**Comment by sswierczek** [comment] 2019-01-15 16:57
> > * user can still see controls after pressing any button during the ads but at least there is no way to skip or pause them. I could hacky resolve visibility locking  make whole controls GONE but this is not ideal solution:
> 
> Does intercepting key events in the playback fragment avoid that?
> 

I've tried with overriding `onKey` in `PlaybackBannerControlGlue` and keys are locked but controls can be still showed.

With returning true in `setOnKeyInterceptListener` of `VideoSupportFragment` buttons are completely unlocked. Should I use sth else in Fragment?

**Comment by andrewlewis** [comment] 2019-01-18 13:52
I had a quick look at suppressing key events in-app but couldn't find a clean way to do it. Please update here if you did find way!

The Leanback team has filed a externally-visible feature request for preventing showing the controls on key events: https://issuetracker.google.com/issues/122918400. If that's not going to be sufficient to get it to work perhaps you could file another issue in the same component and I'll reassign it as appropriate if you reply with the URL here. Thanks.

**Comment by sswierczek** [comment] 2019-01-18 16:15
> I had a quick look at suppressing key events in-app but couldn't find a clean way to do it. Please update here if you did find way!

I've just managed to make a hack with view visibility to remove controls completely. **This it not the best solution but works.** Controls are hidden and there is no way to show them with pressing buttons.

```kotlin
fun VideoSupportFragment.hideAndLockControls() {
    hideControlsOverlay(false)
    view?.findViewById<View>(R.id.playback_controls_dock)?.visibility = View.GONE
}

fun VideoSupportFragment.unlockControls() {
    view?.findViewById<View>(R.id.playback_controls_dock)?.visibility = View.VISIBLE
}
```
> 
> The Leanback team has filed a externally-visible feature request for preventing showing the controls on key events: https://issuetracker.google.com/issues/122918400. If that's not going to be sufficient to get it to work perhaps you could file another issue in the same component and I'll reassign it as appropriate if you reply with the URL here. Thanks.

Thanks for the help :) I will observe that issue.

**Comment by tonihei** [comment] 2019-05-07 13:44
I'll close this issue because it seems to be partly solved by the workaround above and/or tracked by the leanback bug. Feel free to reopen if there is anything else we need to do on the ExoPlayer side.

**Closed as completed by tonihei** 2019-05-07 13:44 UTC
Labels: need more info
