### ISSUE TITLE
HLS stream issue

### ISSUE THREAD

**Issue by kaiv2000** [google/ExoPlayer#6622] opened 2019-11-06 16:31 UTC
Next HLS stream play without video, only sound is playing, no picture, in VLC player it show picture with sound:
https://real-g2.sobor.net/hls-live/live/_definst_/liveevent/livestream.m3u8

**Comment by AquilesCanta** [comment] 2019-11-12 17:35
This is a duplicate of #5537, except the PMT contains audio, but not video.

```
First PMT:

            Stream_type: 15 (0x0f)  [= ISO/IEC 13818-7 Audio with ADTS transport sytax]
            reserved_1: 7 (0x07)
            Elementary_PID: 258 (0x0102)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)

Second PMT:

            Stream_type: 27 (0x1b)  [= AVC video stream as defined in ITU-T Rec. H.264 | ISO/IEC 14496-10 Video]
            reserved_1: 7 (0x07)
            Elementary_PID: 257 (0x0101)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)


            Stream_type: 15 (0x0f)  [= ISO/IEC 13818-7 Audio with ADTS transport sytax]
            reserved_1: 7 (0x07)
            Elementary_PID: 258 (0x0102)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)
```

**Closed as completed by AquilesCanta** 2019-11-12 17:35 UTC
Labels: bad media
