### ISSUE TITLE
How to setup ads marker in Leanback Player Glue using Exo player

### ISSUE THREAD

**Issue by SakthivelMuruganS** [google/ExoPlayer#6789] opened 2019-12-19 14:04 UTC
Use case description
I want to display markers for ads in Exoplayer using the Leanback Adapter and Glue.
I've used Player Adapter & PlaybackTransportControlGlue (androidx.leanback.media) to stream the content. I'm able to load ads using Ima ads Loader in the video but I want to show the ad marker in lean-back seek bar like Exo player default time bar for different types of ad roll (pre-roll, mid-roll & post-roll).

Proposed solution
Leankback Seek bar should be updated with ad marker by analyzing the AD types (pre-roll, mid-roll & post-roll). Like the same thing, it was updated by PlayerControlView by analyzing the ad time milliseconds in an array.

**Comment by ojw28** [comment] 2019-12-19 14:10
Duplicate of https://github.com/google/ExoPlayer/issues/6695

**Closed as completed by ojw28** 2019-12-19 14:10 UTC
Labels: duplicate
