### ISSUE TITLE
Unable to cast m3u8 media using exoplayer cast

### ISSUE THREAD

**Issue by heddii** [google/ExoPlayer#10639] opened 2022-09-21 10:49 UTC
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

OnePlus 8
Google nexus 4

### Reproducible in the demo app?

Yes

### Reproduction steps

-Click on floating add button
-Choose "Clear Hls: Angel One"
-Press ok
-Press the remote media button
-Select the remote device

### Expected result

Display controllers and the video in the screen of remote device

### Actual result

Black screen, nothing shown except the title of the media
![IMG_20220921_124605](https://user-images.githubusercontent.com/52507549/191485244-fbe5ef44-cb24-48ee-83d0-8d28ce21bdf9.jpg)

### Media

https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8

Media object is constrcuted like this 
MediaItem.Builder()
            .setUri("https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8")
            .setMediaMetadata(new MediaMetadata.Builder().setTitle("Clear HLS: Angel one").build())
            .setMimeType(MIME_TYPE_HLS)
            .build());

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment] 2022-09-22 13:57
This is a duplicate of #7891 and not an ExoPlayer problem. Some cast devices are not able to play that media.

**Closed as completed by marcbaechinger** 2022-09-22 13:57 UTC
Labels: duplicate, bug: device specific
