### ISSUE TITLE
ExoPlayer SurfaceView in RecyclerView - performance issue?

### ISSUE THREAD

**Issue by DavidMihola** [google/ExoPlayer#1572] opened 2016-06-03 17:41 UTC
I am almost sure that my problem is more related to `SurfaceView` and how its content is rendered than ExoPlayer itself but I still think this is the place most likely to get me a competent response - I hope you don't mind that I ask it here.

I have a `RecyclerView` where each item contains the `SurfaceView` into which an instance of `ExoPlayer` is rendering its output. Now, when I quickly scroll the RecyclerView the contents of the SurfaceView seem to lag behind the actual position of the SurfaceView itself. Which is to say, the padding window around the SurfaceView moves exactly parallel to the scrolling motion, but the video image itself moves a bit slower and needs some frames to catch up.

I have made a short video demonstrating the effect: https://www.youtube.com/watch?v=lDh4t3m0DDA
Pay attention to the black bars above and below the video while I am scrolling.

The video was made on an LG G2. The effect was much less noticable on a Nexus 6P, but may not completely absent.

So my question: Is this just a performance issue resulting from the way SurfaceView is drawn or is it an indication that I am doing something wrong?

**Comment by brianchu** [comment] 2016-06-03 17:45
I have the same problem, 'fix' by using TextureView.

**Comment by ojw28** [comment] 2016-06-03 18:51
SurfaceView rendering wasn't properly synchronized with view animations in older releases of Android (by design, since I believe there were some trade-offs involved). So it's expected that you may see the content of a SurfaceView lagging slightly behind an animation in the way that you describe. This has been fixed in N, where SurfaceView rendering is properly synchronized.

If this is causing issues in your app then TextureView can be used on M and earlier to resolve the problem. For N and later you should prefer SurfaceView if possible, because SurfaceView provides get better video frame release timing, tighter AV sync, and lower power consumption.

**Comment by DavidMihola** [comment] 2016-06-03 18:56
Thank you so much @brianchu and @ojw28 - that's exactly why I came here!

**Comment by ojw28** [comment] 2016-06-06 18:09
This is now on our new FAQ page.

**Closed by ojw28** 2016-06-06 18:09 UTC
Labels: question

**Comment by vkislicins** [comment] 2016-09-28 14:36
@ojw28 I've been adding ExoPlayer to my app and testing it on various devices. From what I'm seeing, using `SurfaceView` inside a `RecyclerView` even on Android 7.0 is causing an issue (performance is slow and jerky). My ExoPlayer version is 'com.google.android.exoplayer:exoplayer:r1.5.10'
