### ISSUE TITLE
NullPointerException - ExoPlayerImpl.updatePlaybackInfo

### ISSUE THREAD

**Issue by nilsorathiya** [google/ExoPlayer#5425] opened 2019-01-23 04:01 UTC
Fatal Exception: java.lang.NullPointerException
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(SourceFile:717)
       at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(SourceFile:648)
       at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(SourceFile:593)
       at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(SourceFile:125)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tonihei** [comment] 2019-01-23 09:19
Please provide all the information requested in the issue template when filing an issue.

Besides that, the line numbers suggest you are using an old version of ExoPlayer and we made some changes to that class recently. So please update and check whether the issue still occurs.

My best guess would be that you are using ExoPlayer from two different threads simultaneously and run into problems because of concurrent modification of the same value.

**Comment by tonihei** [comment] 2019-01-23 09:20
Closing for now. If you have the full requested information and can still reproduce in the latest version, please reopen.

**Closed as completed by tonihei** 2019-01-23 09:20 UTC
Labels: bug: in platform
