### ISSUE TITLE
android.media.MediaCodec$CryptoException: Crypto key not available

### ISSUE THREAD

**Issue by narasimharao11** [google/ExoPlayer#9882] opened 2022-01-21 08:55 UTC
we are updated the exoplayer version 2.16.0 , unable to play the DRM content in Redmi6 in Exoplayer demo Application as well.

before update exoplayer we are using 2.11.2, in this version Drm content is playing fine without any issue.

```
2022-01-21 12:31:50.020 30932-30932/com.tru E/EventLogger: playerFailed [16.76, 9.61, window=0, period=0]
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(12, null, null, video/avc, avc1.640028, 2300000, null, [1920, 1080, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2821)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:171)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1307)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:780)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

- ExoPlayer version number : **2.16.0**
- Android version: **9**
- Android device: **Redmi 6**

**Comment by icbaker** [comment] 2022-01-21 14:55
We need more information to investigate this.

> unable to play the DRM content in Redmi6 in Exoplayer demo Application as well.

Please list precisely what DRM samples you tried from the demo app and which ones worked and which ones failed. Do any of them work?

Please also provide the zip file produced by `adb bugreport`. Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by narasimharao11** [comment] 2022-01-31 15:20
we have mailed all the information, we are completely blocked with this issue, please help us ASAP.

**Comment by icbaker** [comment] 2022-01-31 17:22
I played the provided media URI for 1 minute. It played successfully on both a OnePlus AC2003 (Android 11) and a Pixel 5 (Android 12).

Do you observe this issue on all devices you tried or just the Redmi 6?

> Please also provide the zip file produced by `adb bugreport`. 

The txt file provided is a logcat snippet and **not** a full bug report. Please provide the full output of `adb bugreport`, as it often contains additional `MediaCodec` or `MediaDrm` error information that can help to diagnose an issue.

**Comment by narasimharao11** [comment] 2022-02-01 14:58
Hi Icbaker,

- We are using Redmi6 (Android 9) , Redmi 5A (Android 8) after 9 seconds throwing an error 
  android.media.MediaCodec$CryptoException: Crypto key not available.
-  But its working fine in Oneplus 8T (Android 11), Redmi Note 7S (Android 10) .

Before updating exoplayer version to 2.16.0, we were using 2.11.2,  in this version DRM content is playing fine in same device(Redmi 6) without any issue.

we have mailed all the information .

**Comment by icbaker** [comment] 2022-02-01 16:29
The bug report requested has not been provided. Given this is a device-specific issue, and I don't have the specific device available, the only way I will be able to investigate further is to look for information in a bug report.

**Comment by icbaker** [comment] 2022-02-01 17:08
I also played the provided content on an original Pixel running Android 8 and it played successfully (so this looks like a device-specific, rather than OS-specific, issue).

**Comment by narasimharao11** [comment] 2022-02-02 04:10
We have sent an email bug report.

**Comment by icbaker** [comment] 2022-02-02 10:28
Thanks, looking in the BR I see an HTTP 401 exception being logged from inside `DefaultDrmSession`. Later, when it gets propagated out as a 'source error' it's tagged with [`ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/PlaybackException.html#ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED), meaning it was the license server that returned 401.

I recommend you look in the logs of the license server, or contact the license server provider, to understand why it's returning a 401 response (presumably for only the specific problematic devices).

(In general, when providing bug reports for debugging issues like this, it's much more helpful if you can ensure stack traces etc are de-obfuscated. In this case there was enough information present elsewhere to diagnose the issue, but sometimes the class names and line numbers in a stack trace are crucial to understanding exactly what happened)

```
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession: DRM session error
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:   c1.n0: e3.z$e: Response code: 401
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at c1.k0.c(Unknown Source:111)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at c1.k0.a(Unknown Source:84)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at c1.g$c.handleMessage(Unknown Source:21)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at android.os.Handler.dispatchMessage(Handler.java:106)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at android.os.Looper.loop(Looper.java:176)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at android.os.HandlerThread.run(HandlerThread.java:65)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:   Caused by: e3.z$e: Response code: 401
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at e3.v.b(Unknown Source:257)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at e3.l0.b(Unknown Source:12)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at e3.o.a(Unknown Source:8)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at e3.o.read(Unknown Source:7)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at e3.o.read(Unknown Source:2)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at g3.u0.g1(Unknown Source:9)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       at c1.k0.c(Unknown Source:47)
02-01 19:18:23.174 10300 32149  1178 E DefaultDrmSession:       ... 5 more

...

02-01 19:18:23.274 10300 32149 32149 E EventLogger: playerFailed [eventTime=11.89, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED
02-01 19:18:23.274 10300 32149 32149 E EventLogger:   w0.p: Source error
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at w0.c1.G(Unknown Source:16)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at w0.c1.handleMessage(Unknown Source:329)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:102)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at android.os.Looper.loop(Looper.java:176)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at android.os.HandlerThread.run(HandlerThread.java:65)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:   Caused by: c1.o$a: c1.n0: e3.z$e: Response code: 401
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at c1.g.u(Unknown Source:6)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at c1.g.w(Unknown Source:15)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at c1.g.v(Unknown Source:21)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at c1.g.l(Unknown Source:0)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at c1.g$e.handleMessage(Unknown Source:18)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:106)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       ... 2 more
02-01 19:18:23.274 10300 32149 32149 E EventLogger:   Caused by: c1.n0: e3.z$e: Response code: 401
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at c1.k0.c(Unknown Source:111)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at c1.k0.a(Unknown Source:84)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at c1.g$c.handleMessage(Unknown Source:21)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       ... 3 more
02-01 19:18:23.274 10300 32149 32149 E EventLogger:   Caused by: e3.z$e: Response code: 401
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at e3.v.b(Unknown Source:257)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at e3.l0.b(Unknown Source:12)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at e3.o.a(Unknown Source:8)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at e3.o.read(Unknown Source:7)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at e3.o.read(Unknown Source:2)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at g3.u0.g1(Unknown Source:9)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       at c1.k0.c(Unknown Source:47)
02-01 19:18:23.274 10300 32149 32149 E EventLogger:       ... 5 more
02-01 19:18:23.274 10300 32149 32149 E EventLogger: ]
```

**Comment by icbaker** [comment] 2022-02-08 10:21
Closing as the root cause of the issue seems to be a 401 response from the DRM license server, suggesting this isn't an ExoPlayer issue.

**Closed as completed by icbaker** 2022-02-08 10:21 UTC
Labels: question
