### ISSUE TITLE
HLS preloading

### ISSUE THREAD

**Issue by VeraUvads** [google/ExoPlayer#10490] opened 2022-08-02 05:01 UTC
My task is to pre-load 2-3 seconds of the video, and after the Internet is turned off it should work.

Format video: like in tik tok.  I reuse one istance of exo player in every Recycler.ViewHolder. 

My first solution:

   ```
// preload every video 
     runCatching {
            CacheWriter(
                cacheDataSourceFactory.createDataSource(),
                dataSpec,
                null,
                progressListener
            ).cache()
        }.onFailure {
            it.printStackTrace()
        } 
        
 //  then get it like this      
  override fun play(mediaUrl: String) {
        exoPlayer.apply {
            stop()
            clearMediaItems()
            setMediaSource(getMediaSource(mediaUrl), true)
            prepare()
            play()
        }
    }

    private fun getMediaSource(url: String): HlsMediaSource {
        return HlsMediaSource.Factory(
            cacheDataSourceFactory
        ).createMediaSource(MediaItem.fromUri(url))
    }

```

But if I turn off the internet, I will have an error:
2022-08-02 07:51:12.345 16693-16900/com.umbrella.player.sample E/ExoPlayerImplInternal: Playback error
      UnknownHostException (no network)

But I checked: Every video exists in the cache.

Second solution: 

```
            runCatching {
                val hlsDownloader = HlsDownloader(
                    MediaItem.Builder()
                        .setUri(uriList[position])
                        .setStreamKeys(
                            Collections.singletonList(
                                StreamKey(HlsMultivariantPlaylist.GROUP_INDEX_VARIANT, position)
                            )
                        )
                        .build(),
                    cacheDataSourceFactory
                )

                hlsDownloader.download { contentLength, bytesDownloaded, percentDownloaded ->
                    if (percentDownloaded >= 20) hlsDownloader.cancel()
                }
            }.onFailure {
                it.printStackTrace()
            }

```
Same issue

 Third solution:

```
   val mediaItem: MediaItem =
            MediaItem.Builder()
                .setUri(uriList[position])
                .build()
        val downloadHelper = DownloadHelper.forMediaItem(
            context,
            mediaItem,
            null,
            cacheDataSourceFactory
        )
        downloadHelper.prepare(object : DownloadHelper.Callback {
            override fun onPrepared(helper: DownloadHelper) {
                val request: DownloadRequest =
                    helper.getDownloadRequest(
                        url,
                        null
                    )
                DownloadService.sendAddDownload(
                    context,
                    PreloadingCacheService::class.java,
                    request,
                    false
                )
            }

            override fun onPrepareError(helper: DownloadHelper, e: IOException) {
            }
        })
```

It caches great and works without Interner, but I can't find a way how I can preload only a few (2-3) seconds of video, or maybe just part of the video (20 percent). Please, help. Maybe a should upgrade one of my solutions?

**Comment by muhammed122** [comment] 2022-08-02 07:47
Hello,
I have same task but I need some help to achieve your result 
could I get GitHub link of your app ?

**Comment by VeraUvads** [comment] 2022-08-02 10:23
Sorry, I wish I could, but it's private.
But I can share projects I used for research.

https://github.com/thanductaimgt/exo-player-pre-cache-sample
https://github.com/AndroidDeveloperLB/ExoPlayerCacheSample
https://github.com/andriiginting/instagram-preloading

Hope it helps.

**Comment by muhammed122** [comment] 2022-08-02 13:10
thanks for response,
could i get any contact for you , to ask something ?

**Comment by icbaker** [comment] 2022-08-02 14:46
Partial downloads is not supported. It's tracked by https://github.com/google/ExoPlayer/issues/1497 so I'm going to mark this as a duplicate of that issue.

**Closed as completed by icbaker** 2022-08-02 14:46 UTC
Labels: duplicate

**Comment by VeraUvads** [comment] 2022-08-03 04:18
@icbaker ok, but could you tell me why it doesn't work correctly in the first cases?

**Comment by VeraUvads** [comment] 2022-08-03 04:20
@muhammed122 you can find me on telegram as @ uvads
