### ISSUE TITLE
No duration and possbility to seek in PlayerControlView for some video

### ISSUE THREAD

**Issue by alexeyr15** [google/ExoPlayer#7156] opened 2020-03-28 13:07 UTC
### [REQUIRED] Issue description
During playback of some video files, there is no duration info in PlayerControlView and possbility to seek the video via the timebar is disabled. Other video players show duration and allow to seek the video.

### [REQUIRED] Reproduction steps
1. Add the provided link to the test video to Demo app
2. Open the test video in Demo app
3. Observe that there is no duration info in PlayerControlView and it's not possible to seek the video

### [REQUIRED] Link to test content
Provided via email

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Any device

**Comment by andrewlewis** [comment] 2020-03-30 08:43
The provided stream is an MPEG-TS stream where the default timestamp search range is too low to be able to derive the duration of the stream. Improving this behavior is tracked by #5097 so I will mark this as a duplicate.

**Comment by andrewlewis** [comment] 2020-03-30 08:44
Duplicate of #5097

**Closed as completed by andrewlewis** 2020-03-30 08:44 UTC
Labels: question
