### ISSUE TITLE
Video with DTS-HD audio playing error

### ISSUE THREAD

**Issue by dirondir** [google/ExoPlayer#7059] opened 2020-03-08 06:48 UTC
### [REQUIRED] Issue description
I'm trying to play a movie (.mkv, DTS-HD sound) with my NVidea Shield 2017 (has DTS-HD on the board and it should works with pass-through). Have an error:
```
E/ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(2, null, null, audio/vnd.dts, null, -1, en, [-1, -1, -1.0], [8, 48000]), rendererSupport=NO_UNSUPPORTED_TYPE
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(2, null, null, audio/vnd.dts, null, -1, en, [-1, -1, -1.0], [8, 48000])
```
The most strange thing is that this movie played well with ExoPlayer till 2.11.x. 

### [REQUIRED] Reproduction steps

```
val adaptiveTrackSelectionFactory = AdaptiveTrackSelection.Factory()
val trackSelector = DefaultTrackSelector(this, adaptiveTrackSelectionFactory)

val extensionRendererMode = DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON

val renderersFactory = DefaultRenderersFactory(this).setExtensionRendererMode(extensionRendererMode)

player = SimpleExoPlayer.Builder(this, renderersFactory).setTrackSelector(trackSelector).setLoadControl(
                    DefaultLoadControl.Builder().createDefaultLoadControl()).build()
```
than start playing as

```
val bandwidthMeter = DefaultBandwidthMeter.Builder(this).build()
val mediaDataSourceFactory = DefaultDataSourceFactory(this, bandwidthMeter,
                DefaultHttpDataSourceFactory("xxx", bandwidthMeter, 3000, 3000, true))

val media = ProgressiveMediaSource.Factory(mediaDataSourceFactory)
                    .createMediaSource(uri)
player?.prepare(media, true, true)
```

### [REQUIRED] Link to test content
sent to dev.exoplayer@gmail.com

### [REQUIRED] A full bug report captured from the device
sent to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
2.11.3 (2020-02-19)

### [REQUIRED] Device(s) and version(s) of Android being used
NVidia Shield 2017 (model P2897)
SW Shield Android TV 8.0.2 (32.5.205.105)

**Comment by tonihei** [comment] 2020-03-12 13:36
The code snippet above suggests that the format is not supported (NO_UNSUPPORTED_TYPE), so it's not unexpected that the renderer fails. 

When you say it used to work until 2.11.x - do you see the same NO_UNSUPPORTED_TYPE message for the format or does it show something else?

**Comment by dirondir** [comment] 2020-03-12 17:36
> The code snippet above suggests that the format is not supported (NO_UNSUPPORTED_TYPE), so it's not unexpected that the renderer fails.

Could you explain a little bit more? How do I need to play the file with pass-through?
Because I've been using ExoPlayer since the 2.9.0 version and the same test file was played well.

> When you say it used to work until 2.11.x - do you see the same NO_UNSUPPORTED_TYPE

I don't know. It worked.

**Comment by tonihei** [comment] 2020-03-13 09:37
> Could you explain a little bit more? How do I need to play the file with pass-through?

This should happen automatically I think.

> played well with ExoPlayer till 2.11.x.

We recently had some pull requests that added additional support for Dolby AC4 (e.g. #5303). Sounds as if some of these changes may have made a difference. 

@ybai001  Do you have an idea if or how your changes may have had an influence on this case? 
We currently can't access test devices, so it's hard to reproduce and debug for now.

**Comment by ybai001** [comment] 2020-03-13 12:33
@tonihei I have no device to test DTS-HD stream either. Here are some thoughts of mine based on the information in this page:

1.  [#5303](https://github.com/google/ExoPlayer/pull/5303) was merged since v2.10.0 in last year. We can ask submitter to test this case on v2.10.x and check whether this issue can be reproduced.

2.  From submitter's log,
> E/ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(2, null, null, audio/vnd.dts, null, -1, en, [-1, -1, -1.0], [8, 48000]), rendererSupport=NO_UNSUPPORTED_TYPE
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(2, null, null, audio/vnd.dts, null, -1, en, [-1, -1, -1.0], [8, 48000])

this audio is identified as "audio/vnd.dts"(AUDIO_DTS) rather than "audio/vnd.dts.hd"(AUDIO_DTS_HD). I don't know the details of DTS codec since I'm from Dolby. But this is a point we can check' (I have no test media file so that I can't analyze more.

3. The log says exception is triggered in MediaCodecRenderer. If it is pass-through case as submitter said, why MediaCodecRenderer is created? I"m not familiar with pass-through use case. But my understanding is, for pass-through case, the DTS-HD stream should be sent to HAL via AudioTrack/AudioFlinger directly. It should NOT be related to MediaCodec, right?

4. If using MediaCodec to decode this stream is intention, this stream is identified as audio/vnd.dts, could we ask submitter to provide the media codec list on device? If there is only DTS-HD decoder in HAL and no related decoder as OMX/Codec2 component, I think it is not strange to return NO_SUITABLE_DECODER_ERROR (error code -49999, same as the one in log.)

5. The AC-4 related pull request are #5303, #6797, #6836.
- I went through #5303 and didn't find it is related to this issue (Maybe I'm wrong. By code review, I didn't find the hint.)
- #6797 is about AC-4 DRM, which should not be related to this issue.
- #6836 modified the code of MP4Extractor and FragmentedMp4Extractor. Since this test stream is .mkv, it should not related to this issue.

**Comment by tonihei** [comment] 2020-03-13 12:51
Thanks @ybai001 for the detailed analysis! Sorry to loop you in because your changes are apparently unrelated after all.

We'll have a look at other potential changes that may have made a difference between 2.10 and 2.11 then.

**Comment by tonihei** [comment] 2020-03-13 13:10
@dirondir  We also noticed that the apparently unsupported track should never have been selected by the track selector. Did you overwrite any `DefaultTrackSelector` settings?

**Comment by ybai001** [comment] 2020-03-13 13:45
> Thanks @ybai001 for the detailed analysis! Sorry to loop you in because your changes are apparently unrelated after all.
> 
> We'll have a look at other potential changes that may have made a difference between 2.10 and 2.11 then.

You are welcome. Feel free to loop me in in future if there is any issue that is possible to be related with Dolby contribution code. I'm always happy to provide help. :)

**Comment by ojw28** [comment] 2020-03-13 13:58
I have access to an nVidia Shield 2017. I tried playing the video you provided in the 2.11.3 ExoPlayer demo app, and it plays fine for me in passthrough mode. The nVidia platform software was version 8.0.0(32.5.205.42), although I then updated to the latest version and saw the same results

```
EventLogger: state [eventTime=0.01, mediaPos=0.00, window=0, true, BUFFERING]
EventLogger: surfaceSize [eventTime=0.08, mediaPos=0.00, window=0, 1920, 1080]
EventLogger: timeline [eventTime=0.08, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
EventLogger:   period [?]
EventLogger:   window [?, false, false]
EventLogger: ]
EventLogger: mediaPeriodCreated [eventTime=0.19, mediaPos=0.00, window=0, period=0]
EventLogger: loading [eventTime=0.19, mediaPos=0.00, window=0, period=0, true]
EventLogger: timeline [eventTime=0.29, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
EventLogger:   period [60.44]
EventLogger:   window [60.44, true, false]
EventLogger: ]
EventLogger: decoderEnabled [eventTime=0.44, mediaPos=0.00, window=0, period=0, video]
EventLogger: decoderEnabled [eventTime=0.44, mediaPos=0.00, window=0, period=0, audio]
EventLogger: tracks [eventTime=0.44, mediaPos=0.00, window=0, period=0, 
EventLogger:   Renderer:0 [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=1, mimeType=video/hevc, res=3840x2160, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger:   Renderer:1 [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=2, mimeType=audio/vnd.dts, channels=8, sample_rate=48000, language=en, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger: ]
EventLogger: mediaPeriodReadingStarted [eventTime=0.44, mediaPos=0.00, window=0, period=0]
EventLogger: downstreamFormat [eventTime=0.44, mediaPos=0.00, window=0, period=0, id=1, mimeType=video/hevc, res=3840x2160]
EventLogger: decoderInitialized [eventTime=0.50, mediaPos=0.00, window=0, period=0, video, OMX.Nvidia.h265.decode]
EventLogger: decoderInputFormat [eventTime=0.50, mediaPos=0.00, window=0, period=0, video, id=1, mimeType=video/hevc, res=3840x2160]
EventLogger: downstreamFormat [eventTime=0.51, mediaPos=0.00, window=0, period=0, id=2, mimeType=audio/vnd.dts, channels=8, sample_rate=48000, language=en]
EventLogger: decoderInitialized [eventTime=0.65, mediaPos=0.00, window=0, period=0, audio, OMX.google.raw.decoder]
EventLogger: decoderInputFormat [eventTime=0.65, mediaPos=0.00, window=0, period=0, audio, id=2, mimeType=audio/vnd.dts, channels=8, sample_rate=48000, language=en]
EventLogger: audioSessionId [eventTime=0.84, mediaPos=0.00, window=0, period=0, 57]
EventLogger: videoSize [eventTime=0.86, mediaPos=0.00, window=0, period=0, 3840, 2160]
```

If I manually disable passthrough mode (by modifying then code), then playback of the audio track is not supported. This implies the device does not have a suitable decoder built in, and supports `audio/vnd.dts` in passthrough only.  If I go back and try the 2.9.0 demo app, I get identical results.

It looks to me like your nVidia Shield is connected to a device that doesn't support receiving `audio/vnd.dts`, which is why the track is marked as `NO_UNSUPPORTED_TYPE `. I think you may have application code that's then force selecting the unsupported track, which then causes playback to fail. This is expected, and I think you'll see the same if you use 2.9.0 with your current setup.

If there is something wrong here, please could you capture bug reports just after playing the same content you provided to us in the ExoPlayer demo app, rather than your own app. Please do this for 2.11.3 and an older version that works correctly, so we can compare. Thanks!

**Comment by dirondir** [comment] 2020-03-13 14:42
@ojw28 , @ybai001 , @tonihei 
Thank you everyone for your help. 

> @dirondir We also noticed that the apparently unsupported track should never have been selected by the track selector.

The reason was that I tried to select this track (because original file has 8 audio tracks). I commented the selection in code and the file started to play... @tonihei thank you for pointing to this moment.

But what to do if I have several audio tracks DTS? How to select a specific track?

if I use ffmpeg extension with the dca encoder and try to select such an unsupported track should it work or I will see the same error?

**Comment by ojw28** [comment] 2020-03-13 15:41
> But what to do if I have several audio tracks DTS? How to select a specific track?

There's nothing wrong with selecting a track. The problem is with selecting an unsupported track, which you can also do, but then you shouldn't be surprised if playback fails :). You can query whether tracks are supported before trying to select them. You can also use constraint based selection in many cases, which is generally a lot easier to use. See [DefaultTrackSelector's Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html) for more details.

> if I use ffmpeg extension with the dca encoder and try to select such an unsupported track should it work or I will see the same error?

If you build the FFmpeg extension with an appropriate encoder included, then the track would no longer be unsupported and selection would work properly.

**Comment by ojw28** [comment] 2020-03-13 15:42
Marking this as a question for now, because it doesn't seem to me that anything has changed. If you think there is a bug, please provide the information requested above. I.e.

> If there is something wrong here, please could you capture bug reports just after playing the same content you provided to us in the ExoPlayer demo app, rather than your own app. Please do this for 2.11.3 and an older version that works correctly, so we can compare. Thanks!

**Comment by dirondir** [comment] 2020-03-15 10:40
@ojw28 is there a simple way to check that ffmpeg was compiled correctly and attached to ExoPlayer?
I tried to compile ffmpeg as it is said (to check how it works with the file) and it looks like ffmpeg doesn't work.
I compiled it with –enable-decoder=dca and didn't have errors during compilation but still have the same error with audio selection...
Thank you in advance

**Comment by ojw28** [comment] 2020-03-15 11:57
If you attach an `EventLogger` as described [here](https://exoplayer.dev/listening-to-player-events.html#using-eventlogger) and then capture the logging using `adb logcat EventLogger:* ExoPlayerImpl:* LibraryLoader:* *:s`, you can tell quite a lot about what's going on.

Look in particular for failure to load the native parts of the extension:
```
LibraryLoader: Failed to load [avutil, avresample, swresample, avcodec, ffmpeg]
```
and when the player is released after playback, which extensions were loaded:
```
ExoPlayerImpl: Release fbcfb18 [ExoPlayerLib/2.11.3] [flame, Pixel 4, Google, 29] [goog.exo.core, goog.exo.ui, goog.exo.dash, goog.exo.ffmpeg]
```
Feel free to post complete output of the `logcat` command above if you want us to take a look at it.

**Comment by dirondir** [comment] 2020-03-22 06:24
@ojw28 thank you.
I found that ffmpeg was compiled wrong and didn't work correctly. 
So I recompiled it and now it works well and my problem with playing DTS-HD is solved. 
Thank you for support!

**Closed as completed** 2020-03-22 06:24 UTC
Labels: question
