### ISSUE TITLE
Nokia 8.1 Android Q DRM Playback Fails

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#5910] opened 2019-05-19 15:43 UTC
### [REQUIRED] Reproduction steps

Run Ver 2.10 Exo Demo App on Nokia 8.1 
Run WideVine Dash Section WebM,VP9  -> run the First secure sample SD&HD 
Result: DRM playback fails

### [REQUIRED] Link to test content
DRM content in Demo App

[bugreport-PNX_00WW_FIH-QKQ1.190406.002-2019-05-19-18-11-03.zip](https://github.com/google/ExoPlayer/files/3195258/bugreport-PNX_00WW_FIH-QKQ1.190406.002-2019-05-19-18-11-03.zip)

**Comment by giladna** [comment] 2019-05-20 08:11
I have filed all data I have 
I think it is all that required

**Comment by giladna** [comment] 2019-05-21 08:19
@erdemguven  actually it happen in 3 devices out of 4 we tested running Q with same errors
OnePlus
Realme
Nokia
the only device where we tested and it is working is pixel3

**Comment by tonihei** [comment] 2019-06-13 12:01
Sounds like a duplicate of a known issue in some of the Q builds [internal: b/133481571], which is apparently fixed already. Closing under this assumption, but feel free to reopen if the issue still occurs on upcoming Q beta releases.

**Closed as completed by tonihei** 2019-06-13 12:01 UTC
Labels: bug: in platform

**Comment by giladna** [comment] 2019-07-03 06:28
@tonihei 
Could you add more information in which version it was fixed?
Since in realm me 3 pro in May patch the issue is still there

**Comment by tonihei** [comment] 2019-07-03 08:06
@giladna It'll only be fixed in patches with a datestamp >= 20190610. So that's going to be the next released beta version I think.
