### ISSUE TITLE
DASH trickmode support

### ISSUE THREAD

**Issue by bastova** [google/ExoPlayer#7125] opened 2020-03-23 00:57 UTC
### [REQUIRED] Use case description
I can't seem to find any evidence that exoplayer supports dash trick play protocol.
I've searched for any references to "http://dashif.org/guidelines/trickmode" and couldn't find anywhere in the code. I also built the demo app and supplied it with my DASH manifest which defines trick mode adaptation sets and while scrubbing I didn't see any of the trick mode assets being used (my trick mode assets are much lower in bitrate from main playback, so I would have noticed)

### Proposed solution
Just need an answer to begin with, is it supported or not, and if not is there any plan to support it? Otherwise is there a recommendation of how to achieve smooth scrubbing?

### Alternatives considered
Use another player?

**Comment by ojw28** [comment] 2020-03-23 12:51
Duplicate of https://github.com/google/ExoPlayer/issues/6054

**Closed as completed by ojw28** 2020-03-23 12:51 UTC
Labels: duplicate, enhancement
