### ISSUE TITLE
player.getCurrentPosition() return value is negative when using ClippingMediaSource

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#4873] opened 2018-09-27 02:25 UTC
ExoPlayer version: v2.8.4
The sample code is :
```
 MediaSource[] mediaSources = new MediaSource[uris.length];
 for (int i = 0; i < uris.length; i++) {
     mediaSources[i] = buildMediaSource(uris[i], extensions[i], null);
 }
 if (mediaSources.length == 1){
    ClippingMediaSource content1 = new ClippingMediaSource(mediaSources[0], 0, 15000000,null);
    ClippingMediaSource content2 = new ClippingMediaSource(mediaSources[0], 15000000, C.TIME_END_OF_SOURCE,null);
    mediaSource = new ConcatenatingMediaSource(
          content1,            // content[0~15s]
          content2 );           // content[15s ~ end]
}
```
 I use a ClippingMediaSource to split one video into two video at point 15s, then concatenate them. 
 When the player begins to play the second video, I pressed home button, then resume to play, I find
 that the TimeBar's current position is negative.  The logs like this:
```
  E/EventLogger: player position = [-6421] bufferedPosition = [-1742]
  E/EventLogger:player position = [-5006] bufferedPosition = [4760]
```

**Comment by Romantic-LiXuefeng** [comment] 2018-09-28 02:37
@ojw28 Did you already had the time to look into this issue? Is there anything I can do to support you?

**Comment by erdemguven** [comment] 2018-09-28 10:16
Reproducible on the latest development branch.

**Comment by tonihei** [comment] 2018-09-28 16:52
Thanks for reporting. We'll provide a fix for this soon.

**Comment by tonihei** [comment] 2018-10-02 15:15
The commit above fixes the issue.

**Closed as completed by tonihei** 2018-10-02 15:15 UTC
Labels: bug

**Comment by Romantic-LiXuefeng** [comment] 2018-10-09 07:46
@tonihei  thanks! Hope to give me some information about how was this bug generated?

**Comment by Romantic-LiXuefeng** [comment] 2018-10-09 08:43
@ojw28   I find that  when the player plays the first clip video ,press home button, then resume to play,there is no this bug. Hope you give me some explanation.

**Comment by tonihei** [comment] 2018-10-11 08:19
The bug occurred because the player creates the element at which playback starts with a default position of zero until we know more. In your case, this default position was non-zero (because of the clipping) and we forgot to set the right offset at one point. 

Not sure why you don't see the bug with the first video? I was able to reproduce the issue with the first and the second video in a concatenation.
