### ISSUE TITLE
No video is shown on protected DASH stream on some Android 9.0 devices

### ISSUE THREAD

**Issue by rs146** [google/ExoPlayer#6946] opened 2020-02-04 14:26 UTC
### [REQUIRED] Issue description
No video content is displayed in the player - however we can hear audio in the DASH stream.

### [REQUIRED] Reproduction steps
Use the ExoPlayer demo app and start playback. We have to specify the manifest stream url and drm license url. We are using widevine DRM.

### [REQUIRED] Link to test content
I will send a message to dev.exoplayer@gmail.com a sample DASH manifest URL, DRM license URL.

### [REQUIRED] A full bug report captured from the device
[logcat.txt](https://github.com/google/ExoPlayer/files/4153897/logcat.txt)

### [REQUIRED] Version of ExoPlayer being used
2.11.1, 2.10.8 and 2.10.4.

### [REQUIRED] Device(s) and version(s) of Android being used
This bug is reproducible on the Google Pixel 3 XL and One plus 6T running on Android 9.0. Please aim to test the demo app on these devices.

However, this is not reproducible on a Google Pixel 3 XL running on Android 10. So it seems to be a combination of Android 9.0 and some Android devices.

Should you need any further information, please contact me via email/via the GitHub thread: rahul.singh@deltatre.com

**Comment by AquilesCanta** [comment] 2020-02-06 13:50
Please provide a full bugreport as required in the issue template. A bugreport is obtained by running adb bugreport shortly after reproducing the issue. Thanks.

**Comment by rs146** [comment] 2020-02-21 15:11
@AquilesCanta - unfortunately we cannot reproduce this anymore. Should it arise again - we can re-open this with the full adb bugreport. Thanks for having a look anyway.

**Comment by rs146** [comment] 2020-02-21 15:21
Please see the attached the bugreport for this issue.
[bugreport-crosshatch-PQ3A.190801.002-2020-02-21-15-16-37.zip](https://github.com/google/ExoPlayer/files/4236722/bugreport-crosshatch-PQ3A.190801.002-2020-02-21-15-16-37.zip)

**Comment by ojw28** [comment] 2020-03-12 16:29
@jt64 - Could you take a look at this? Likely a duplicate of #6974 (please feel free to dupe one onto the other).

**Comment by jt64** [comment] 2020-03-24 22:40
Duplicate of #6974, there is updated information in that bug that may be helpful.

**Closed as completed** 2020-03-24 22:41 UTC
Labels: bug, bug: in platform drm
