### ISSUE TITLE
Only audio is playing and video is stuck when seeking before the playback start position while using AdsMediaSource

### ISSUE THREAD

**Issue by Sara-Tareq** [google/ExoPlayer#3734] opened 2018-01-21 07:24 UTC
### Issue description
Using an AdsMediaSource for a pre-roll video ad with an HlsMediaSource and seeking the playback to a position after the stream start position after the ad ends if I seeked back below the playback start position (not the stream start position) only the audio is working and the video is stuck.

### Reproduction steps
AdsMediaSource(HlsMediaSource)
player.seekTo(startPos)
after ad ends seek back 

### Link to test content
sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
Exoplayer 2.6.1 dev-v2 branch.

### Device(s) and version(s) of Android being used
Nexus 9 with Android version 7.1.1

### A full bug report captured from the device
sent to dev.exoplayer@gmail.com

**Comment by andrewlewis** [comment] 2018-02-14 15:06
The HLS stream provided via email wouldn't load (I got a 403 error). Perhaps it is georestricted or has expired. I tried using a different live HLS stream and a preroll sample ad tag and the ad played as expected, then I was able to seek around the live window.

Please could you provide a content stream and ad tag we can use to reproduce the issue here? It would also be useful to have precise steps to reproduce in the sample app (I'm not sure exactly what you mean by "seeked back below the playback start position (not the stream start position)"). Thanks!

**Comment by ojw28** [comment] 2018-02-26 18:26
Closing due to lack of a working test stream. Note that we've fixed quite a lot of issues with our IMA ads integration in 2.7.0, so it's worth trying to upgrade to see if that fixes it. If you're still seeing the issue and are able to provide a working test stream and concrete reproduction steps, please reply here and we'll re-open the issue.

**Closed as completed by ojw28** 2018-02-26 18:26 UTC
Labels: need more info
