### ISSUE TITLE
HLS stream not playing

### ISSUE THREAD

**Issue by vovan888** [google/ExoPlayer#3467] opened 2017-11-15 18:50 UTC
### Issue description
Live stream does not play with ExoPlayer demo app. Just a black screen shown, nothing more.
VLC plays it without issues.

### Reproduction steps
Add a sample stream to media.exolist.json and try to play it.

### Link to test content
Sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.6.0

### Device(s) and version(s) of Android being used
MECOOL M8Spro+ Android 7.1.1

### A full bug report captured from the device
Sent to dev.exoplayer@gmail.com

**Comment by ojw28** [comment] 2017-11-15 21:36
This is a duplicate of https://github.com/google/ExoPlayer/issues/3455. The content should contain IDR frames, and we're compliant with the HLS RFC in discarding media indefinitely from streams that do not contain any. There is a workaround, as described in https://github.com/google/ExoPlayer/issues/3455#issuecomment-344557128.

**Closed as completed by ojw28** 2017-11-15 21:36 UTC
Labels: duplicate

**Comment by vovan888** [comment] 2017-11-15 21:43
Thank you.
