### ISSUE TITLE
onDownstreamFormatChanged vs onDecoderInputFormatChanged

### ISSUE THREAD

**Issue by oliveroneill** [google/ExoPlayer#6604] opened 2019-10-31 01:52 UTC
### [REQUIRED] Searched documentation and issues
Relevant issues: https://github.com/google/ExoPlayer/issues/4692 and https://github.com/google/ExoPlayer/issues/5956
Comments in these issues indicate that both onDownstreamFormatChanged and onDecoderInputFormatChanged should pick up track switches.

[Documentation on AnalyticsListener](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html)

### [REQUIRED] Question
In AnalyticsListener, what is the difference between onDownstreamFormatChanged and onDecoderInputFormatChanged? What are their intended usecases?

I think they come from two different sources within the ExoPlayer architecture, but should I expect there to be situations where one is called and not the other? 

onDecoderInputFormatChanged doesn't seem to be triggered when the bitrate changes but the resolution stays the same, while onDownstreamFormatChanged is triggered. Is that expected behaviour?

**Comment by tonihei** [comment] 2019-10-31 15:20
That's a duplicate of #5956, in particular [this answer.](https://github.com/google/ExoPlayer/issues/5956#issuecomment-496540080)

(Note that `onVideoInputFormatChanged` is equivalent to `onDecoderInputFormatChanged`)

**Closed as completed** 2019-10-31 15:21 UTC
Labels: duplicate, question, documentation candidate

**Comment by oliveroneill** [comment] 2019-10-31 20:57
Thanks @tonihei. It's still not clear what their intended use-cases are. So if I only cared about video changes, then `onDownstreamFormatChanged` and `onDecoderInputFormatChanged` would be equivalent? Does that mean it's a bug that `onDecoderInputFormatChanged` doesn't pick up bitrate changes of the same resolution?

**Comment by tonihei** [comment] 2019-11-05 15:42
Please see the explanations in the linked answer above. The difference is relevant for muxed formats (like the ones you often get in HLS) where `onDownstreamFormatChanged` tells you about changes in the selected format on the input side (e.g. muxed audio/video), whereas `onDecoderInputFormatChanged` tells you about changes to the format handled on a decoder level (e.g. demuxed audio/video). For cases where the media is demuxed already, you'll simply get both callbacks with the same Format.
