### ISSUE TITLE
Request: provide small sample projects to show how to play local files too

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#11194] opened 2023-06-02 14:55 UTC
Both of the next websites don't show how to play local files:
https://developer.android.com/codelabs/exoplayer-intro#0
https://developer.android.com/guide/topics/media/exoplayer/demo-application

The "demo" one doesn't even have a sample of just playing a video. It is so bloated that it became more than 70MB...

By "local files" I mean those that don't need Internet connection, meaning in raw folder, in assets folder, and in the file system (using storage permission).

Please offer as minimal sample as possible, so that it would be easy to read it and understand how it's done.
Also please mention in the tutorial how to do it. 
Not all video/audio files are to be played from the Internet, after all...

I tried to do it using the steps explained in the tutorial. Worked for me for a URL, but I couldn't find for raw resource.

In the past I could use this:

```
fun Player.playRawVideo(context: Context, @RawRes rawVideoRes: Int) {
    val dataSpec = DataSpec(RawResourceDataSource.buildRawResourceUri(rawVideoRes))
    val rawResourceDataSource = RawResourceDataSource(context)
    rawResourceDataSource.open(dataSpec)
    val factory: DataSource.Factory = DataSource.Factory { rawResourceDataSource }
    prepare(LoopingMediaSource(ExtractorMediaSource.Factory(factory).createMediaSource(rawResourceDataSource.uri)))
}
```
But now it won't work because things got removed, and the migration also doesn't mention about it either, as "ExtractorMediaSource" isn't mentioned anywhere:
https://developer.android.com/guide/topics/media/exoplayer/mappings

It's even worse, as I tried others, and this doesn't work:

```
exoPlayer.setMediaItem(MediaItem.fromUri(
    RawResourceDataSource.buildRawResourceUri(R.raw.test2)
))
```

And this:

```
exoPlayer.setMediaItem(MediaItem.fromUri(Uri.parse("android.resource://$packageName/${R.raw.test2}")))
```

See attached video and the sample I tried to use from the tutorial:

[studio64_2023-06-02_17-59-50.zip](https://github.com/google/ExoPlayer/files/11636511/studio64_2023-06-02_17-59-50.zip)

[exoplayer-intro-main.zip](https://github.com/google/ExoPlayer/files/11636516/exoplayer-intro-main.zip)

It seems I'm not the only one frustrated by this. There are questions on StackOverflow, some are outdated too.
The API changed a lot and there is no mention in the tutorial and the demo about how it's done.

Examples:
https://stackoverflow.com/questions/73538296/android-media3-exoplayer-play-video-from-sd-card-or-raw-directory
https://stackoverflow.com/q/40276012/878126
https://tonyowen.medium.com/playing-local-r-raw-files-with-exoplayer2-1a62276ebeaa

**Comment by icbaker** [comment] 2023-06-02 15:17
Are you aware that everywhere in https://developer.android.com/guide/topics/media/exoplayer/demo-application that 'uri' is referenced, this doesn't have to be an HTTP URI hosted on the web? It can be a local file URI (`file:///path/to/your/media`) or a raw resource one (see [`RawResourceDataSource`](https://developer.android.com/reference/androidx/media3/datasource/RawResourceDataSource) for the different URI schemes that can be used here).

Given that, I think the pages you link already show how to play a local file?

**Comment by AndroidDeveloperLB** [comment] 2023-06-02 18:31
@icbaker 
1. About uri, I do know that it should support it all and not just URLs. The issue is that none of the samples show how it's done, and the tutorial doesn't show or even mention it, and also that the migration guide doesn't show about it.
2. About `RawResourceDataSource` , I had to search about it, and not only that it shows a warning about using it , but it didn't work. I've shown on the attached files a video and a project using it. Please check them out. I've also shown the video file is fine.
The warning about it is:

```
This declaration is opt-in and its usage should be marked with @androidx.media3.common.util.UnstableApi or @OptIn(markerClass = androidx.media3.common.util.UnstableApi.class)
```

Adding the annotation also doesn't help, BTW.

3. The pages I've linked don't show how to play a local file. Searching for "RawResourceDataSource " in the demo project shows results that belong to Proguard, comments, and the library of media3.lib-datasource.* . 
They are all URLs, and in the demo project it's even worse: It has it all in a weird json. That's not minimal at all. I was surprised to see a project that takes 70 MB and doesn't have a single video/audio file to show how to play it. After building it, it takes more than 300MB... Checking why, such files do exist, but they are all in tests, and none in the samples themselves.

4. Please, provide a minimal sample of just that. You can have it with all possible ways to play a video/audio if you wish, but don't over-complicate it as done on the demo, and yet don't miss one like on the tutorial .
Please also update the tutorial website.

5. I've found a bug in the IDE for adding the annotation. Not sure if it's related to the library, so reported here:

https://youtrack.jetbrains.com/issue/IDEA-321659/Bug-quick-fix-to-add-annotation-puts-it-in-the-wrong-place

**Comment by icbaker** [comment] 2023-06-05 14:23
> But now it won't work because things got removed, and the migration also doesn't mention about it either, as "ExtractorMediaSource" isn't mentioned anywhere:
> https://developer.android.com/guide/topics/media/exoplayer/mappings

`ExtractorMediaSource` was deprecated a while ago, and then later removed in 2.14.0, as documented in the [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2140-2021-05-13):
> Remove `ExtractorMediaSource`. Use `ProgressiveMediaSource` instead.

The exoplayer2 -> media3 migration guide is not relevant here. That is about migrating from an exoplayer2 release to **the equivalent** media3 release. The earliest ExoPlayer release with an equivalent media3 release is 2.17.0 (as documented in the [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2170-2022-02-24))

---

> It's even worse, as I tried others, and this doesn't work:
> 
> ```
> exoPlayer.setMediaItem(MediaItem.fromUri(
>     RawResourceDataSource.buildRawResourceUri(R.raw.test2)
> ))
> ```

I downloaded your `exoplayer-intro-main.zip` attachment and added that code to the `codelab-00` version of `PlayerActivity.kt`. It worked to play the video, though there was something odd about the playback timestamps (seems there was a black screen for 2s before playback?) and seeking is disabled. However VLC agrees there's something odd about the timestamps, and seeking also doesn't work. When I play it in VLC it says the 'current position' is `351909:41:27`  (i.e. 351909 hours, 41 mins and 27 seconds, or `906874887` seconds), while the video duration is only `00:03` (i.e. 3 seconds). So I think the video sample you're using isn't completely valid - maybe it was naively cut out of a longer file without maintaining the MKV structure correctly?

---

I agree our 'main' demo app tries to do too much stuff, and as such it's a little hard to pick out a simple use-case from it. Improving this with more, smaller, targeted demo apps is tracked by https://github.com/google/ExoPlayer/issues/5854.

However:
1. We likely won't create an app focussed on playing a local `file:///` URI, since:
    1. This is very similar to playing a URI hosted on the web except for [requesting local file access permissions](https://developer.android.com/training/data-storage) (which is a general Android question, not specific to ExoPlayer)
    2. It's impossible to write an app that hard-codes a local `file:///` path, since the user of the demo app would need to manually `adb push` the file to the right place.
2. We won't be measuring the 'complexity' of any demo app by the size of the generated APK (it's not clear where your 70MB and 300MB numbers come from, but in case these refer to APK size). It's possible to write a very simple app that is huge (due to lots of dependencies) and a very complex one that is actually smaller. In fact, reducing APK size with ExoPlayer generally results in **more** non-library code in your app: https://developer.android.com/guide/topics/media/exoplayer/shrinking

I'm going to close this issue as a duplicate of https://github.com/google/ExoPlayer/issues/5854. You've raised some other concerns here, but none have enough information to be conclusively answered. If you need answers for these please file new, separate issues with complete context and reproduction instructions and we will be happy to take a look.

**Closed as completed by icbaker** 2023-06-05 14:23 UTC
Labels: duplicate

**Comment by AndroidDeveloperLB** [comment] 2023-06-06 07:39
@icbaker 
About the migration, sadly I couldn't see it back then. Where can I find the migration guide/s for this? Release notes deep in the Github make it hard to keep track of it...
There are probably more things I should take care of. Noticed about CacheDataSourceFactory too, but in its docs it doesn't say what to replace it with. Says it in the release notes though. There is also `SimpleExoPlayer.prepare` that I can't find what replaces it.

About the video being played, are you saying you've succeeded playing it on the device? How come it doesn't work for me? I've tested on both real device and emulator.

About the sample:
1. Why not showing all kinds of sources to play from ? Not all sources are URLs...
And you don't even need storage permission or a file on the file system being pushed by the user. You can have a file copied by the sample itself, prior to playing it.

2. I meant that cloning the sample from Github took this much space (and time). I thought I will surely find there one that shows how to play from files, because it takes a lot of space and there are video files there. Later I've found out all video files are used by tests and not the samples.

Please do offer multiple tiny samples. I learn better from them than full-fledged apps...
