### ISSUE TITLE
ArrayOutOfBounds when playing MP4 file in the DemoPlayer (dev branch)

### ISSUE THREAD

**Issue by elixiroflife4u** [google/ExoPlayer#576] opened 2015-06-23 23:40 UTC
The following two files fail to play in the DemoPlayer and give an array out of bounds exception

http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4

A similar issue was resolved in #554, but that does not solve the exception of these files.

 Stack trace below
<pre>
06-23 16:13:25.827   7133-23064/com.google.android.exoplayer.demo E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at com.google.android.exoplayer.util.CodecSpecificDataUtil.parseAudioSpecificConfig(CodecSpecificDataUtil.java:53)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:546)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:342)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:66)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:227)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:611)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
06-23 16:13:27.098   7133-23064/com.google.android.exoplayer.demo E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at com.google.android.exoplayer.util.CodecSpecificDataUtil.parseAudioSpecificConfig(CodecSpecificDataUtil.java:53)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:546)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:342)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:66)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:227)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:611)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
06-23 16:13:29.200    7133-7137/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_CONCURRENT freed 2717K, 47% free 5877K/10928K, paused 2ms+3ms, total 20ms
06-23 16:13:29.370   7133-23064/com.google.android.exoplayer.demo E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at com.google.android.exoplayer.util.CodecSpecificDataUtil.parseAudioSpecificConfig(CodecSpecificDataUtil.java:53)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:546)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:342)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:66)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:227)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:611)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
</pre>

**Comment by srikieonline** [comment] 2015-06-24 00:48
The content has 2 audio tracks : one for MP3 and other is Dolby. 

The issue is as follows:

In parseAudioSampleEntry function, after parsing ESDS box, it does not check the ObjectTypeIndication of DecoderConfigDescriptor , and assumes its as AAC (0x40), and as per Audio ISO/IEC 14496-3 goes ahead and tries to use util.parseAudioSpecificConfig to parse out the channel Count and Sampling Frequency. This leads to index out of bounds exception because it assumes a minimum of 2 bytes of config data - whereas only 1 byte is present.

In these content, the ObjectTypeIndication is actually 0x6B which is corresponding to MP3 (i.e Audio ISO/IEC 11172-3) as per ISO-IEC-14496-1.

Code reference:
1. parseAudioSampleEntry function:
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/extractor/mp4/AtomParsers.java#L512

2. Call to parseAudioSpecificConfig without checking value of ObjectTypeIndication
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/extractor/mp4/AtomParsers.java#L515

**Comment by ojw28** [comment] 2015-06-24 11:38
Request is to support MP3 in MP4.

**Comment by ojw28** [comment] 2015-06-26 14:03
This is kind of working after the change above, but we're seeing issues where the underlying mp3 codec will crash. Keeping open to see if we're feeding bad data and/or we can work around the issue.

**Comment by ojw28** [comment] 2015-06-26 15:57
These streams should now play reliably on the dev branch, as of https://github.com/google/ExoPlayer/commit/588be2bd4b44fd15fd4636a0f7f482647190d4fa. Closing.

**Closed by ojw28** 2015-06-26 15:57 UTC
Labels: bug, enhancement
