### ISSUE TITLE
Incorrect duration reported when playing an MPEG-DASH Widevine content

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#4131] opened 2018-04-16 15:09 UTC
When playing a Widevine MPEG-DASH content in ExoPlayer 2.7.2 demo application, the calculated duration is incorrect. Instead of using the duration in:

`<Period duration="PT12M14.250S">`

it seems to use the SegmentTimeline of one of the content subtitles:

`<AdaptationSet codecs="stpp" contentType="text" group="3" lang="en" maxBandwidth="1000" mimeType="application/mp4" minBandwidth="1000">
      <SegmentTemplate initialization="tears-of-steel-dash-widevine-$RepresentationID$.dash" media="tears-of-steel-dash-widevine-$RepresentationID$-$Time$.dash" timescale="1000">
        <SegmentTimeline>
          <S d="60000" r="8" t="0"/>
          <S d="27000"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation bandwidth="1000" id="textstream_eng=1000">
      </Representation>
    </AdaptationSet>`

This way, instead of reporting 12m14s (734 seconds), it is reporting 9m27s (567 seconds) which is:

((60000 x 9) + 27000) / 1000

In order to reproduce the issue, you just need to add a the related content to the demo app samples, 
I can provide a sample content url by email.
Can you please investigate this issue?
Please, let me know if any further information is needed.
Kind regards,

Moacir

**Comment by ojw28** [comment] 2018-04-16 15:12
Dupe of https://github.com/google/ExoPlayer/issues/4029. Note that content with "short" representations, as is probably the case for your content, is likely to be forbidden by DASH IOP going forward.

**Closed as completed by ojw28** 2018-04-16 15:12 UTC
Labels: duplicate

**Comment by moacir69** [comment] 2018-04-16 15:14
Thank you for the quick reply. Will check issue #4029.
Warm regards,

Moacir
