### ISSUE TITLE
Issues with dash live streaming (wowza)

### ISSUE THREAD

**Issue by davibe** [google/ExoPlayer#397] opened 2015-04-16 05:24 UTC
Hi,

I put up a server that generates a continous live stream using Wowza 3.6.4 (which basically does the same dash as 4.0 does). Wowza supports 2 mpd syntaxes: one with timed based url templates, one with a simple list of segments

list: http://peer.wim.tv:1935/live/foo/manifest_mpm4sav_mvlist_w12345679.mpd
time: http://peer.wim.tv:1935/live/foo/manifest_mpm4sav_mvtime_w12345679.mpd

None of those work correctly with exoplayer and I would like to figure out what is wrong. For my needs i care mostly about the "list" version.

Result with exoplayer (any version I tried including master)
- list: the player does not start playing
- time: the player starts playing but after a while the image freezes

I was able to fix those problems but the patches i came up with do not make sense to me yet. Unfortunately i don't have much time to understand the issues and make proper patches. I suggest someone with more experience with exoplayer could try to play the stream and help me with this.

Here is my patch https://github.com/davibe/ExoPlayer/commit/ae088d967ce585cde73815826288201874f92450

**Comment by ojw28** [comment] 2015-04-16 11:08
I see the same issue as you do on master, but both samples work just fine on the dev branch. I suggest you try that. It's likely that we fixed whatever the underlying issue is.

**Comment by ojw28** [comment] 2015-04-16 11:12
Actually, even when using the dev branch, they freeze after a while.

**Comment by davibe** [comment] 2015-04-16 11:35
I have never tried the dev branch indeed. I will try it in the next days.
With my patch, once started, it never freezes.

Maybe you can turn it into something useful. The freeze was happening when
the DashDataSource was looking for a segment that is not in the MPD. It was
looking for it because it was doing some wrong estimation of segment index
based on time. My patch detects that and fixes it (in a bad way probably).

**Comment by ojw28** [comment] 2015-04-16 11:47
The problem is either with the manifest itself, or somewhere much deeper in the Manifest parsing code (probably SegmentBase).java. I think the manifest might be invalid, but the spec is so ambiguous about how "startNumber" is supposed to work, it's hard to tell. I'll have to give it some more thought.

**Comment by ojw28** [comment] 2015-08-08 20:37
Not sure what the status of this is, but the samples are no longer available. Closing. Please open a new issue if you're still seeing problems (referencing this one).

**Closed by ojw28** 2015-08-08 20:37 UTC
