### ISSUE TITLE
After some time "Source error" occurs

### ISSUE THREAD

**Issue by sneps85** [google/ExoPlayer#1985] opened 2016-10-24 08:39 UTC
After playing an online audio stream with ExoPlayer v2 for a while (can be 5mins, can be 3 hours), the player stops with the following error:

> E/ExoPlayerImplInternal: Source error.

What causes this error and how can i continue the stream when the error occurs?

I am connected to a WiFi-Network, which may has some instabilities.

**Comment by andrewlewis** [comment] 2016-10-24 09:01
We need more information to diagnose this, and in particular a full bug report output by `adb bugreport`. Please provide all the information requested in the issue template.

**Comment by ojw28** [comment] 2016-11-16 22:32
Closing due to insufficient information.

**Closed as completed by ojw28** 2016-11-16 22:32 UTC
Labels: need more info

**Comment by hannunehg** [comment] 2017-02-28 17:52
This happened with us after a while of playing one video. Here are the logs: ( all at the same time happened, I mean at the same milli second)

`Source error.
                                                                    java.io.EOFException
                                                                        at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:491)
                                                                        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:441)
                                                                        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:153)
                                                                        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:635)
                                                                        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:841)`

then followed by this exception at the same milli second: (handled from event logger)

`onPlayerError: Unexpected exception
                                                                   com.google.android.exoplayer2.ExoPlaybackException
                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:345)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                    Caused by: java.io.EOFException
                                                                       at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:491)
                                                                       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:441)
                                                                       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:153)
                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:635)
                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:841)`

other debug messages at the same milli second:
`updateButtonVisibilities: 0 track is: 2131230867`
`updateButtonVisibilities: 1 track is: 2131230822`
`showControls: Error Happened`


After 10 milli seconds the following exception occured:
`playerFailed [172.27]
                                                          com.google.android.exoplayer2.ExoPlaybackException
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:345)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:136)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                              at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                           Caused by: java.io.EOFException
                                                              at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:491)
                                                              at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:441)
                                                              at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:153)
                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:635)
                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                              at java.lang.Thread.run(Thread.java:841)`

I am using this library:
` compile 'com.google.android.exoplayer:exoplayer:r2.2.0'`
