### ISSUE TITLE
Sometimes UnrecognizedInputFormatException throws

### ISSUE THREAD

**Issue by MaksTuev** [google/ExoPlayer#1730] opened 2016-08-09 07:14 UTC
I use ExoPlayer  in real application and some users sometimes gets UnrecognizedInputFormatException when play mp3 file from internet or device memory. This bug elusive and I reproduce it once, after that player back to normal. Bug does not depend on android version and device.

Stacktrace:
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, PsExtractor) could read the stream.
       at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
       at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
       at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, PsExtractor) could read the stream.
       at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:794)
       at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:725)
       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by andrewlewis** [comment] 2016-08-09 08:22
You mention seeing this error when playing an MP3 file "from internet or device memory" -- just to check, have you definitely seen this with local streams? What stream were you playing the one time you managed to reproduce the error? If you see it again, please take a full bug report with `adb bugreport`. Thanks.

**Comment by ojw28** [comment] 2016-08-16 22:12
Closing due to lack of information.

**Closed as completed by ojw28** 2016-08-16 22:12 UTC
Labels: need more info
