### ISSUE TITLE
Ts video file can't read duration

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#7436] opened 2020-05-28 10:45 UTC
Before filing a bug:
-----------------------
- Search existing issues, including issues that are closed:
  https://github.com/google/ExoPlayer/issues/6894 https://github.com/google/ExoPlayer/issues/5097

### [REQUIRED] Issue description
I got a ts file, try to play, and it can't seekable and it can't get video duration.

### [REQUIRED] Link to test content
https://github.com/VeiZhang/Test/blob/master/video/ts_no_duration.ts?raw=true

### [REQUIRED] Version of ExoPlayer being used
The latest

### [REQUIRED] Device(s) and version(s) of Android being used
Android 7.1, Amlogic 905x

**Comment by ojw28** [comment] 2020-05-28 12:32
Duplicate of https://github.com/google/ExoPlayer/issues/5097.

**Closed as completed by ojw28** 2020-05-28 12:32 UTC
Labels: duplicate
