### ISSUE TITLE
Call method OfflineLicenseHelper.getLicenseDurationRemainingSec while playback is playing will cause the player to drop FPS or lags

### ISSUE THREAD

**Issue by 247az** [google/ExoPlayer#10700] opened 2022-10-19 02:24 UTC
## Issue
We have an episode screen, and below playback there's a list of content lists, which show which content has downloaded or not.
When we scroll that list, we have a license request to check if the content's license has expired.
But when scroll up or down, it will cause lag or FPS drop while the video is playing.

This error you can reproduce very easily. As long as you call method `OfflineLicenseHelper.getLicenseDurationRemainingSec` while a video is playing, the error can be reproduced immediately.

### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

* Any devices

### Reproducible in the demo app?

Yes

### Reproduction steps
This error you can reproduce very easily. As long as you call method `OfflineLicenseHelper.getLicenseDurationRemainingSec` while a video is playing, the error can be reproduced immediately.

1. Play any content (downloaded or streaming)
2. At that screen, in the state of the video being played, call the method `validateOfflineLicense` as shown below.
3. Please notice the video is playing, the FPS drops or lags a lot.

```
fun validateOfflineLicense(licenseUrl: String, keySetId: ByteArray?): Boolean {
        if (licenseUrl.isEmpty()) return false
        keySetId ?: return false
        val offlineLicenseHelper = createOfflineLicenseHelper(licenseUrl)

        var existsLicense = true
        val result =  try {
            val remainingSecPair = offlineLicenseHelper.getLicenseDurationRemainingSec(keySetId)
            remainingSecPair.first > 0L
        } catch (e: Exception) {
            existsLicense = false
            false
        }

        if(!result && existsLicense) {
            offlineLicenseHelper.releaseLicense(keySetId)
        }

        return result
}

private fun createOfflineLicenseHelper(licenseUrl: String) = if (licenseUrl.isNotEmpty()) {
        OfflineLicenseHelper.newWidevineInstance(licenseUrl, true, httpDataSourceFactory, DrmSessionEventListener.EventDispatcher())
} else {
        throw IllegalArgumentException("License URL is empty")
}

httpDataSourceFactory = getHttpDataSourceFactory(context)
fun getHttpDataSourceFactory(context: Context): HttpDataSource.Factory {
        var dataSourceFactory: HttpDataSource.Factory? = null
        val cronetEngine = CronetUtil.buildCronetEngine(context.applicationContext, userAgent, false)
        cronetEngine?.let {
            dataSourceFactory = CronetDataSource.Factory(cronetEngine, Executors.newSingleThreadExecutor())
        }

        dataSourceFactory ?: run {
            CookieHandler.setDefault(CookieManager().also { it.setCookiePolicy(CookiePolicy.ACCEPT_ORIGINAL_SERVER) })
            dataSourceFactory = DefaultHttpDataSource.Factory().setUserAgent(userAgent)
        }

        return dataSourceFactory!!
}
````

### Expected result

While the video is playing, the FPS will not drop or lag if you call method: `OfflineLicenseHelper.getLicenseDurationRemainingSec(keySetId)`

### Actual result

 While the video is playing, the FPS drops or lags a lot if you call method: `OfflineLicenseHelper.getLicenseDurationRemainingSec(keySetId)`

We tried the methods below, but it still doesn't work.
Call `validateOfflineLicense` in another thread
Try 1: 
```
CoroutineScope(Dispatchers.IO).launch {
   val result = validateOfflineLicense(licenseUrl, drmHeader)
   callback(result)
}
```
or even:
```
CoroutineScope(Dispatchers.IO.limitedParallelism(1000)).launch {
   val result = validateOfflineLicense(licenseUrl, drmHeader)
   callback(result)
}
```
or even
```
val dispatcher = Executors.newFixedThreadPool(1000).asCoroutineDispatcher()
CoroutineScope(dispatcher).launch {
   val result = validateOfflineLicense(licenseUrl, drmHeader)
   callback(result)
}
```

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-10-21 09:33
I suspect there's some detail missing from your reproduction instructions. Please can you clarify the following points before I spend time trying to reproduce this:

> * Play any content (downloaded or streaming)

Does the content need to be DRM protected? What scheme?

> * At that screen, in the state of the video being played, call the method `validateOfflineLicense` as shown below.

Does it matter what parameters I pass to `validateOfflineLicense`? e.g. does the problem still reproduce if I pass `licenseUrl = ""` or `keySetId = null`?

**Comment by icbaker** [comment] 2022-10-21 09:33
It might be easiest to fork our demo app and make some small modifications then share a link to the fork here.

**Comment by 247az** [comment] 2022-10-21 10:01
@icbaker 
Thank you for your reply.
> Does the content need to be DRM protected? What scheme?

I've tested it even on content without DRM, and when I call `offlineLicenseHelper.getLicenseDurationRemainingSec(keySetId)` this error still occurs. I'm using `Widevine` scheme.

> Does it matter what parameters I pass to validateOfflineLicense? e.g. does the problem still reproduce if I pass licenseUrl = "" or keySetId = null?

I have checked that if licenseUrl or keySetId = null it will return false, so it won't call `offlineLicenseHelper.getLicenseDurationRemainingSec(keySetId)`. I also don't think we can pass in a licenseUrl="" or keySetId=null, because it will throw an exception.

**Comment by 247az** [comment] 2022-10-21 10:46
@icbaker 
> It might be easiest to fork our demo app and make some small modifications then share a link to the fork here.

Sorry for keeping you waiting so long. I made an example for you to see.
Please download the content below, then open it, then press the `SELECT TRACKS` button to see what happens.

Below is the content that I used in the demo app. As for the code, I encapsulate it in the file below. Can you check for me.
![Screenshot_20221021_193756](https://user-images.githubusercontent.com/114720380/197177326-d08caece-1f97-4e07-9839-3f3205f4b7e8.png)

I made it from 2.17.1 version.
<img width="386" alt="Screen Shot 2022-10-21 at 19 45 12" src="https://user-images.githubusercontent.com/114720380/197178313-8c5c5d08-0c53-4020-abb3-2a0cd57b31ab.png">

Code (Based on v2.17.1 TAG):
[demo_issue_10700.diff.zip](https://github.com/google/ExoPlayer/files/9838303/demo_issue_10700.diff.zip)

**Comment by 247az** [comment] 2022-10-21 10:50
@icbaker 
Here is the video (Sorry because its a DRM content)
https://user-images.githubusercontent.com/114720380/197181546-42a6f2e6-67e3-40f9-ad07-2d9a4027f11c.mp4

**Comment by icbaker** [comment] 2022-10-24 09:58
Similar symptoms were reported in https://github.com/google/ExoPlayer/issues/9265

I proposed a hacky approach that would keep the same `MediaDrm` instance for each call, which I found did speed things up a bit: https://github.com/google/ExoPlayer/issues/9265#issuecomment-894366296

The ultimate conclusion on that issue is that this call will likely always be slow - and you may want to cache the value in your app to avoid repeatedly calling down into the TEE. As noted in that issue, it's much harder for ExoPlayer to correctly implement this caching logic because each app has more context on how they interact with offline licenses.

I'm going to close this because the slowness here is in the underlying DRM framework, not our library - and there's not much we can do to speed that up.

**Closed as completed by icbaker** 2022-10-24 09:58 UTC
Labels: question

**Comment by 247az** [comment] 2022-10-24 12:32
@icbaker 
Thank you for your reply.
I know someone has asked about this before: https://github.com/google/ExoPlayer/issues/9265
But even though I followed your suggestion, while playback is playing and calling method `getLicenseDurationRemainingSec(keySetId)` only once, video playback still lags.
It doesn't solve the problem I'm having.
Is there no way to fix it?
