### ISSUE TITLE
Some videos cannot be played on a specific phone

### ISSUE THREAD

**Issue by Caij** [google/ExoPlayer#4502] opened 2018-07-12 05:05 UTC
version : 2.8.2
device: oppo A1601 Android 5.1
url: http://gslb.miaopai.com/stream/JIHEFOTZY6YVDfqyNtMtNRBAerfiO5EZocqYIQ__.mp4?yx=&refer=weibo_app&Expires=1531373212&ssig=v4Toq%2B49LN&KID=unistore,vide

but on xiaomi 6 android 8.0 is success.

[logcat.txt](https://github.com/google/ExoPlayer/files/2187153/logcat.txt)

**Comment by botaydotcom** [comment] 2018-07-12 09:32
Seems to be a duplicate of #3265.

**Closed as completed by botaydotcom** 2018-07-12 09:32 UTC
Labels: duplicate, bug: device specific
