### ISSUE TITLE
IMA SDK AD_BUFFERING event prevents from firing any other event.

### ISSUE THREAD

**Issue by atrope** [google/ExoPlayer#8270] opened 2020-11-23 16:26 UTC
### [REQUIRED] Issue description
When Preloading an AD and playing it after, if the AD_BUFFERING Event is triggered, IMA SDK does not fire any other PROGRESS EVENT

### [REQUIRED] Reproduction steps

Test with slow internet speed and receive a buffer before loading all ad.
Tested with DEMO TAG

Toggling enable preloading does not seem to affect anything..

### [REQUIRED] Link to test content
Demo Tag https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=instream&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=

 and SilenceMediaSource after

### [REQUIRED] A full bug report captured from the device
Full Log when Buffer fire:

```
2020-11-23 13:25:29.234 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (LOADED)
2020-11-23 13:25:29.247 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (CONTENT_PAUSE_REQUESTED)
2020-11-23 13:25:29.410 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_BUFFERING)
2020-11-23 13:25:29.423 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (PAUSED)

```

Full Log Without:

```
2020-11-23 13:24:37.041 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (LOADED)
2020-11-23 13:24:37.059 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (CONTENT_PAUSE_REQUESTED)
2020-11-23 13:24:37.133 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (PAUSED)
2020-11-23 13:24:37.356 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (RESUMED)
2020-11-23 13:24:37.882 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (STARTED)
2020-11-23 13:24:37.888 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:37.940 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.034 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.134 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.234 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.336 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.437 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.539 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.639 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.736 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.836 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:38.936 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.036 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.142 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.241 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.351 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.441 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.568 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.686 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.769 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.869 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:39.972 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.070 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.168 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.269 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.375 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.475 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.500 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (FIRST_QUARTILE)
2020-11-23 13:24:40.573 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.674 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.775 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.874 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:40.982 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.079 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.178 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.279 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.386 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.481 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.581 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.685 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.781 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.881 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:41.984 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.081 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.187 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.285 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.386 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.488 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.585 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.685 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.786 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.895 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:42.997 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.037 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (MIDPOINT)
2020-11-23 13:24:43.085 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.187 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.287 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.388 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.488 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.591 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.693 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.789 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.891 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:43.994 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.090 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.192 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.293 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.393 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.493 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.593 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.693 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.794 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.895 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:44.996 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.097 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.196 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.296 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.396 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.496 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.543 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (THIRD_QUARTILE)
2020-11-23 13:24:45.595 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.697 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.797 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.897 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:45.999 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:46.099 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:46.199 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:46.300 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:46.401 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:46.501 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:46.602 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:46.706 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:46.802 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:46.907 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.003 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.105 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.208 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.306 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.405 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.508 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.608 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.706 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.813 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (AD_PROGRESS)
2020-11-23 13:24:47.895 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (COMPLETED)
2020-11-23 13:24:47.913 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (CONTENT_RESUME_REQUESTED)
2020-11-23 13:24:47.931 26637-26637/com.example.bannertest D/AdPlayerManager$$special$$inlined$apply$lambda: EVENT RECEIVED 1 (ALL_ADS_COMPLETED)
```

### [REQUIRED] Version of ExoPlayer being used
2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
Tested with Android 6,8,9,10,11

**Comment by icbaker** [comment] 2020-11-23 17:27
Possibly related to https://github.com/google/ExoPlayer/issues/8239?

**Comment by atrope** [comment] 2020-11-23 18:26
@icbaker looks like it!

**Comment by atrope** [comment] 2020-11-24 15:46
@icbaker @andrewlewis this is affecting our prod app so we wouldl have to downgrade to exoplayer 2.11.X but we can't because 2.12 brings a fix to the companion banner on audio ads.. Do you think it will get prioritized to next version?

Thanks

**Comment by andrewlewis** [comment] 2020-11-24 16:00
I'm looking into this now. To be confirmed, but I think it's likely we'll be able to get a fix into a minor release soon (although this will need to be done carefully as `dev-v2` is diverging due to moving code around to add support for ads in playlists).

**Comment by andrewlewis** [comment] 2020-11-24 17:06
I have a fix ready and it should be easy to cherry-pick into the next minor release.

I'll mark this issue as a duplicate of the other one for now. Thanks!

**Comment by andrewlewis** [comment] 2020-11-24 17:07
Duplicate of #8239

**Comment by atrope** [comment] 2020-11-24 17:07
@andrewlewis Perfect! Thanks.
I Will be waiting for this next release.

**Closed as completed by andrewlewis** 2020-11-24 17:07 UTC
Labels: duplicate
