### ISSUE TITLE
Commit "Implement format to encoding for AAC" causing playback issue

### ISSUE THREAD

**Issue by fgl27** [google/ExoPlayer#7407] opened 2020-05-21 07:14 UTC
### [REQUIRED] Issue description
After the commit
https://github.com/google/ExoPlayer/commit/535e14cb4d69ca41f91118cf2bd201ea94746d53

Some TV devices start to have a issue, those TV devices are connected to soundbar devices and have the issue, if the soundbar is disconnected no issue.

The player doesn't play only shows a frame as if it was paused no sound.

See more here:
https://github.com/fgl27/SmartTwitchTV/issues/10 

### [REQUIRED] Reproduction steps
Play a video AVC/MP4 on that particularly TV/Soundbar config

### [REQUIRED] Link to test content
Any AVC/MP4 video causes it

### [REQUIRED] A full bug report captured from the device

[bugreport-BRAVIA_ATV2_EU-OPR2.170623.027.S30-2020-05-12-08-24-13.zip](https://github.com/google/ExoPlayer/files/4660997/bugreport-BRAVIA_ATV2_EU-OPR2.170623.027.S30-2020-05-12-08-24-13.zip)

I have added this commit:
https://github.com/fgl27/ExoPlayer/commit/a18257d2b55ac18a9b33ab36436913d933b00cec
That included some logs with the tag **AAC_CHECK** plus the app running has the tag **STTV_PlayerActivity**

On bellow logcat the resume from the bug report, of the starting the app until the bug report start be generated

[logcat_AAC_CHECK.txt](https://github.com/google/ExoPlayer/files/4661003/logcat_AAC_CHECK.txt)

Is possible to see that the player goes to all steps `prepare(), Player.STATE_BUFFERING, Player.STATE_READY`, but the player doesn't play for the user, only a frame is display as if it was paused no sound.

### [REQUIRED] Version of ExoPlayer being used
dev-v2 branch

### [REQUIRED] Device(s) and version(s) of Android being used

TV Sony ZD9 4K 
OS Android 8.0
Soundbar Sony ZF9

**Comment by andrewlewis** [comment] 2020-05-21 08:12
This looks similar to #7404.

**Comment by fgl27** [comment] 2020-05-21 08:26
Yes seems so hadn't notice it before open this. Issues can be combine if necessary, please close this if that is the case.

The reference of commit  https://github.com/google/ExoPlayer/commit/0de9c007afcbc0fb6c753794afc902eb4aaa47b4 on the other issue seems odd after all it change variables name.

Only the commit from the title of this issue affects the devices according to users test.

**Comment by andrewlewis** [comment] 2020-05-21 09:22
@fgl27 Thank you for the information.

Could you log what the supported encodings are in the `AudioCapabilities` just before [this line](https://github.com/google/ExoPlayer/blob/df0d115/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L421)? I think one possible explanation is that the device is reporting support for AAC passthrough but it doesn't actually work. Or if the app is passing a custom `AudioCapabilities` instance to the audio renderer, could you give some more information on how you create it?

**Comment by fgl27** [comment] 2020-05-21 10:22
OK, I made a request for the users that have the defective device, as I don't . They will send a bugreport and I share the `AudioCapabilities` result after.

I start the player without changing `AudioCapabilities` you can see it here:

https://github.com/fgl27/SmartTwitchTV/blob/master/apk/app/src/main/java/com/fgl27/twitch/PlayerActivity.java#L345

Technically the only renderer changed is to disable SW video decoder because some device worryingly report more capable SW decoder then HW one as result some streams don't work properly (they lag because the lower performance of SW decoder), but I don't think that is a issue, the user can overwrite the custom `BlackListMediaCodecSelector` and enable all video decoder if that is a needed tested.

**Comment by fgl27** [comment] 2020-05-21 12:38
Here is the device AudioCapabilities:

`AudioCapabilities[maxChannelCount=8, supportedEncodings=[2, 5, 6, 7, 8, 10, 11, 12]]`

**Comment by andrewlewis** [comment] 2020-05-21 12:42
Thanks! That maps onto ENCODING_PCM_16BIT, ENCODING_AC3, ENCODING_E_AC3, ENCODING_DTS, ENCODING_DTS_HD, ENCODING_AAC_LC, ENCODING_AAC_HE_V1, ENCODING_AAC_HE_V2.

I'm a bit surprised that the AAC encodings are included, and we should only try to use those once we are sure `DefaultAudioSink` handles them correctly and that passthrough playback actually works with them. I have made a change that will prevent trying to use AAC passthrough and that will appear on `dev-v2` soon.

**Comment by andrewlewis** [comment] 2020-05-21 12:44
For now I will mark this as a duplicate of the other issue as the underlying cause is probably the same. Please follow that issue to get an update when we push the fix. Thanks again for the debugging help!

Duplicate of #7404

**Closed as completed by andrewlewis** 2020-05-21 12:44 UTC
Labels: duplicate

**Comment by fgl27** [comment] 2020-05-21 12:45
OK you welcome. We test again dev-v2 and let you know the result after I see the new changes.
