### ISSUE TITLE
How to fix rotate incorrect problem with under Android 4.0 device?

### ISSUE THREAD

**Issue by ghostknow** [google/ExoPlayer#4763] opened 2018-09-03 08:22 UTC
As title, The video play with Android 5.0+ is correct orientation. How to fix it with Android 4.0 device.
Thanks.

**Comment by tonihei** [comment] 2018-09-04 08:22
Please provide the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) for us to take a closer look. Thanks!

**Comment by tonihei** [comment] 2018-09-04 15:28
This is probably also a duplicate of #91. Please have a look at the `unappliedRotationDegrees` reported through the `VideoListener.onVideoSizeChanged` callback.

**Closed as completed** 2018-09-11 07:59 UTC
Labels: duplicate, need more info
