### ISSUE TITLE
Downloading DASH with external subtitles

### ISSUE THREAD

**Issue by AGasztold** [google/ExoPlayer#8908] opened 2021-05-06 14:09 UTC
Hello,

I need to download external subtitles (VTT format) simultaneously with the video/audio tracks. 
I have added subtitles to 
`MediaItem.PlaybackProperties List<Subtitle> subtitles` (This mediaItem is passed to `DownloadHelper.forMediaItem(..)`), so it is possible to select Text track inside TrackSelectionDialog for download. 
Unfortunatelly, streamKeys are empty in this case -> 
`  public DownloadRequest getDownloadRequest(String id, @Nullable byte[] data) {
...
      streamKeys.addAll(mediaPreparer.mediaPeriods[periodIndex].getStreamKeys(allSelections));
...
}`  getStreamKeys returns empty list for MergingMediaPeriod (there is no problem for DashMediaPeriod - as it has its own implementation of getStreamKeys).  
Download attempt for DASH was OK, but without subtitles. 
The question is -> what is the best way to add external subtitles for download?
I will appreciate Your help.

**Comment by christosts** [comment] 2021-05-06 16:00
@ojw28 can you take a look?

**Comment by ojw28** [comment] 2021-05-07 12:39
This is not something we support directly, so for now you have to download the subtitle file yourself, and also specify it at playback time (presumably using a `file:///` URI that points to where the file has been downloaded).

Providing direct support is tracked by https://github.com/google/ExoPlayer/issues/5615, so closing as a duplicate of that issue.

**Closed as completed by ojw28** 2021-05-07 12:39 UTC
Labels: duplicate
