### ISSUE TITLE
How to get ima ads loader Exception ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#3687] opened 2018-01-09 11:26 UTC
I want to get ima ads loader Exception. but i can not found any listener or add any listener to catch ima ads loader exception ?

**Comment by marcbaechinger** [comment] 2018-01-09 22:35
I assume you are looking for the IMA AdError (https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/AdError).

The AdsMediaSource has an extended constructor to which you can pass a `Handler` and an `EventListener`. The event listener has a `onAdLoadError` callback which delivers an `IOException`.

With the `ImaAdsLoader` the AdError is the cause of that IOException, hence you can do:

```
public void onAdLoadError(IOException ex) {
   if (ex.getCause() instanceof AdError) {
       // ...
   }
}
```

Edit: Since 2.6.0 there is a [getter on the ImaAdsLoader](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.html#getAdsLoader--) which lets you access the IMA AdsLoader on which you can register your own listener.

**Comment by giladna** [comment] 2018-01-11 19:35
@marcbaechinger 
Thats correct, one problem I can tell as a developre is that the method name does not implies that it is fired on every error
since there is a difference between adLoad phase and ad playback phase 

@andrewlewis since `onLoadError` will be fired not only on "load" 
could you please change its name like `onAdError` that is more expressive to fire upon all kinds of errors?
maybe IMA error code could be added as well?

10x
Gilad.
 

private void maybeNotifyAdError() {
    if (eventListener != null && pendingAdErrorEvent != null) {
      IOException exception =
          new IOException("Ad error: " + pendingAdErrorEvent, pendingAdErrorEvent.getError());
      eventListener.onLoadError(exception);
      pendingAdErrorEvent = null;
    }
  }

**Comment by andrewlewis** [comment] 2018-02-12 16:27
@giladna IMA's `AdError` is provided as the cause of the notified error, so you can get the error code using `((AdError) error.getCause()).getErrorCode()`. I'll look at renaming the error callback.

**Comment by andrewlewis** [comment] 2018-02-16 08:55
@giladna Have you seen `AdErrors` with the [`PLAY` type](https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/AdError.AdErrorType) while using the IMA extension? I'm open to renaming the callback, but I want to understand what non-loading errors are causing the confusion first. It seems a bit strange for an `AdsLoader` to surface non-loading errors. Thanks.

**Comment by ojw28** [comment] 2018-03-05 20:58
Closing due to lack of follow-up.

**Closed as completed by ojw28** 2018-03-05 20:58 UTC
Labels: question
