### ISSUE TITLE
Exoplayer stucks while playing video

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#7444] opened 2020-05-29 07:27 UTC
```
isPlaying [eventTime=16.85,   mediaPos=0.00, window=0, period=0, true]
audioTrackUnderrun [eventTime=17.80,   mediaPos=0.19, window=0, period=0, 61568, 320, 575]]
audioTrackUnderrun [eventTime=19.05,   mediaPos=1.14, window=0, period=0, 61568, 320, 1049]]
audioTrackUnderrun [eventTime=20.28,   mediaPos=1.74, window=0, period=0, 61568, 320, 988]]
audioTrackUnderrun [eventTime=21.02,   mediaPos=2.06, window=0, period=0, 61568, 320, 569]]
audioTrackUnderrun [eventTime=21.76,   mediaPos=2.26, window=0, period=0, 61568, 320, 726]]
audioTrackUnderrun [eventTime=23.08,   mediaPos=2.80, window=0, period=0, 61568, 320, 1095]]
droppedFrames [eventTime=23.82,   mediaPos=3.12, window=0, period=0, 74]
```

**Device Details**
Android Lib Version | 5.8.3 |  
Android Manufacturer | samsung |  
Android Model | SM-J810G |  
Android OS Version | 9 |  
Android OS | Android |

**Comment by marcbaechinger** [comment] 2020-05-29 10:36
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

**Comment by gokulkalagara** [comment] 2020-05-30 16:43
### [REQUIRED] Issue description
Exoplayer struck while playing the secure dash in 
**SAMSUNG J7, J8**


### [REQUIRED] Reproduction steps
[EventLogger.xlsx](https://github.com/google/ExoPlayer/files/4706032/EventLogger.xlsx)


### [REQUIRED] Version of ExoPlayer being used
**ExoPlayerLib/2.11.4**

### [REQUIRED] Device(s) and version(s) of Android being used
**SAMSUNG** 
Model: SM-G615F, OS Version: 8.1.0
Model: SM-J810G, OS Version: 9

I share the video URL, code, log report and bug details via email

**Comment by marcbaechinger** [comment] 2020-06-01 09:36
Thanks for sending the bugreport by email. I looked into it but I could not find any logs from ExoPlayer. Searching for one of the lines you posted above like 'audioTrackUnderrun' gives me no result. Can you double check whether the logs in the bugreport contain what you expected to be there?

It would also be helpful if you could clarify what you mean by 'Exoplayer struck while playing the secure dash in'. Is it not working at all or do you see frame drops as shown with the log messages above?

**Comment by gokulkalagara** [comment] 2020-06-01 14:10
In above sent EventLogger file 
Inline 86 there is a 
**droppedFrames   [eventTime=17.46, mediaPos=3.03, window=0, period=0, 50]**

**Sample Video**
https://res.cloudinary.com/developer1439/video/upload/v1591020571/videos/video_ftekhk.mp4

**Comment by marcbaechinger** [comment] 2020-06-01 14:46
I'm afraid but I'm not going to look at log files which are stored in a spreadsheet and of which I do not know how it is related to the bug report you sent by email.

Please create a bug report of a device right after the problem happened. Further it would be helpful if you could explain what the problem is you are actually seeing and what the expected behaviour would be.

May I ask you to create a proper bug report reflecting the issue? many thanks.

**Comment by gokulkalagara** [comment] 2020-06-02 06:51
Cross-check the below bug report this latest one. Please help me

[bugreport-2020-06-02-12-13-40.zip](https://github.com/google/ExoPlayer/files/4715309/bugreport-2020-06-02-12-13-40.zip)

**Comment by marcbaechinger** [comment] 2020-06-04 10:24
Thanks. The bug report contains logs of a part of a playback starting at mediaPos=494.55.
I see frame drops and dropped frames in the logs but I'm not sure whether I see something which makes me think of a bug. When I play the media on my device this runs through the end without any of these.

In case you see the dropped frames as the problem, I don't think I can do much about it I'm afraid. The media seems to play well.

**Comment by gokulkalagara** [comment] 2020-06-04 16:36
what I have to do?

**Comment by gokulkalagara** [comment] 2020-06-07 16:13
@ojw28 @jt64 @marcbaechinger @rrfrias 
What I have to do

**Comment by gokulkalagara** [comment] 2020-06-14 12:19
Redmi Note 8 pro also getting frame drops while playing, please cross check why this happened

**Comment by gokulkalagara** [comment] 2020-06-16 18:55
@AquilesCanta please cross-check this almost 12 days is completed

**Comment by ojw28** [comment] 2020-06-16 19:05
@gokulkalagara - Please can you start using this issue tracker appropriately:

* Stop spamming issues requesting updates.
* Stop using `@Person` to cause emails to be sent to issues that the person isn't assigned to or helping with. `@AquilesCanta` is not assigned this issue and has no involvement on it.
* Properly fill out our issue template when initially filing issues.

**Comment by gokulkalagara** [comment] 2020-06-17 07:26
I already filled it

**Comment by gokulkalagara** [comment] 2020-06-28 15:51
can I know the status

**Closed as completed** 2020-09-12 16:17 UTC
Labels: question
