### ISSUE TITLE
Subtitles inconsistent rendering

### ISSUE THREAD

**Issue by ianflitman** [google/ExoPlayer#5544] opened 2019-02-20 13:25 UTC
Hi Exoplayer Team

Great software btw. I am using 2.9.5.
I am concatenating merged media sources using 4 test audio files with 4 srts - one for each file and each with two cues.

```
private ConcatenatingMediaSource concatMediaSources(){
        ConcatenatingMediaSource returnConcatenatedMediaSource = new ConcatenatingMediaSource();
        Format subtitleFormat = Format.createTextSampleFormat(
                null, MimeTypes.APPLICATION_SUBRIP, C.SELECTION_FLAG_DEFAULT, null);
        mDataSpecs = new DataSpec[4];
        mSubtitleDataSpecs = new DataSpec[4];
        for (int a = 0; a < 4; a++) {
            mDataSpecs[a] = new DataSpec(Uri.parse("asset:///m4a/londonUnderground_" + Integer.toString(a + 1) + ".m4a"));
            mSubtitleDataSpecs [a] = new DataSpec(Uri.parse("asset:///m4a/srt/londonUnderground_" + Integer.toString(a + 1) + ".srt"));
            try {
                mAssetDataSource.open(mDataSpecs[a]);
            }catch (AssetDataSource.AssetDataSourceException e){
                e.printStackTrace();
            }
            MediaSource mediaSource = new ExtractorMediaSource.Factory(mFactory).createMediaSource(mAssetDataSource.getUri());

            try {
                mAssetDataSource.open(mSubtitleDataSpecs[a]);
            }catch (AssetDataSource.AssetDataSourceException e){
                e.printStackTrace();
            }
            MediaSource subtitleSource = new SingleSampleMediaSource.Factory(mFactory).createMediaSource(mAssetDataSource.getUri(), subtitleFormat, C.TIME_UNSET);

            MergingMediaSource mergedSource = new MergingMediaSource(mediaSource, subtitleSource);
            returnConcatenatedMediaSource.addMediaSource(mergedSource);
}
```

This sometimes works and sometimes does not in terms of the subtitles showing up or being logged. I have the following TextRenderer code attached to the player:

```
mPlayer.addTextOutput(new TextRenderer.Output() {
            public void onCues(List<Cue> cues) {
                if(cues.size()> 0){
                    for(Cue cue: cues){
                        Log.e("cues are ", cue.text.toString());
                    }
                }else{
                    Log.e("cue list object","empty");
                }
                if(mSubtitleView!=null && cues.size()> 0){
                    mSubtitleView.onCues(cues);
                }
            }
        });
```

As you can see I am logging the subtitle text and also since I get quite a few empty 'List<Cue>' objects.
This functionality is critical since somewhat cheekily I am using json payloads to tell me what to do at certain points during playback. I intent to load dynamically different files depending on other interactions and the logic contained in the json.If this does not work I will have to resort to other means to achieve the same end.

 Basically not all srt files are being rendered or found as they should i.e. "part 1 / cue 1",  "part 1/ cue 2", "part 2 / cue 1" etc up to "part 4 / cue 2". Some are being skipped somewhat randomly. Sometimes it all works fine. Nothing to reply on. The test log after several playbacks is.

```
> 
2019-02-20 13:26:28.889 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:26:31.058 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:26:32.106 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 1/cue 1"}
2019-02-20 13:26:34.600 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:26:38.799 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [5,6,7],"string": "part 1/cue 2"}
2019-02-20 13:26:41.805 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:26:49.086 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:26:50.078 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 2/cue 1"}
2019-02-20 13:26:52.578 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:26:55.773 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [10,20,30],"string": "part 2/cue 2"}
2019-02-20 13:26:58.768 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:26:59.557 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:05.005 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:26.563 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:26.589 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:28.706 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:29.761 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 1/cue 1"}
2019-02-20 13:27:32.266 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:36.462 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [5,6,7],"string": "part 1/cue 2"}
2019-02-20 13:27:39.466 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:46.737 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:47.732 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 2/cue 1"}
2019-02-20 13:27:50.228 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:53.433 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [10,20,30],"string": "part 2/cue 2"}
2019-02-20 13:27:56.433 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:57.218 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:27:58.196 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 3 _cue 1"}
2019-02-20 13:28:00.697 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:28:02.199 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [11,12,13],"string": "part 3_cue 2"}
2019-02-20 13:28:03.702 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:28:03.720 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:17.931 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:19.091 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 1/cue 1"}
2019-02-20 13:37:21.585 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:25.793 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [5,6,7],"string": "part 1/cue 2"}
2019-02-20 13:37:28.791 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:36.067 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:37.060 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 2/cue 1"}
2019-02-20 13:37:39.557 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:42.760 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [10,20,30],""string": "part 2/cue 2"}
2019-02-20 13:37:45.758 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:46.531 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:47.532 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 3 _cue 1"}
2019-02-20 13:37:50.030 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:51.526 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [11,12,13],"string": "part 3_cue 2"}
2019-02-20 13:37:53.038 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:53.064 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [111,122,133],"string": "part_4 / cue 1"}
2019-02-20 13:37:55.483 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:37:59.997 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 4 /cue 2"}
2019-02-20 13:38:03.486 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:05.162 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:05.232 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:06.736 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:06.759 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:07.869 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:08.962 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 1/cue 1"}
2019-02-20 13:38:11.474 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:15.667 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [5,6,7],"string": "part 1/cue 2"}
2019-02-20 13:38:18.668 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:25.954 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:36.407 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:41.874 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:42.369 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [111,122,133],"string": "part_4 / cue 1"}
2019-02-20 13:38:45.372 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:49.868 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 4 /cue 2"}
2019-02-20 13:38:53.364 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:57.500 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:57.637 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:38:58.745 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 1/cue 1"}
2019-02-20 13:39:01.248 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:05.451 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [5,6,7],"string": "part 1/cue 2"}
2019-02-20 13:39:08.451 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:15.723 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:16.721 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 2/cue 1"}
2019-02-20 13:39:19.223 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:22.420 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [10,20,30],"string": "part 2/cue 2"}
2019-02-20 13:39:25.423 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:26.198 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:27.188 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 3 _cue 1"}
2019-02-20 13:39:29.695 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:31.188 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [11,12,13], "part 3_cue 2"}
2019-02-20 13:39:32.696 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:32.720 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [111,122,133],"string": "part_4 / cue 1"}
2019-02-20 13:39:35.148 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:39.652 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 4 /cue 2"}
2019-02-20 13:39:43.145 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:46.685 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:46.703 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:48.842 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:49.891 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 1/cue 1"}
2019-02-20 13:39:52.394 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:39:56.598 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [5,6,7],"string": "part 1/cue 2"}
2019-02-20 13:39:59.593 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:06.868 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:17.346 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:18.354 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 3 _cue 1"}
2019-02-20 13:40:20.837 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:22.336 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [11,12,13],"string": "part 3_cue 2"}
2019-02-20 13:40:23.838 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:23.865 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [111,122,133],"string": "part_4 / cue 1"}
2019-02-20 13:40:26.296 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:30.800 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 4 /cue 2"}
2019-02-20 13:40:34.288 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:37.830 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:37.853 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:37.932 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:39.043 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 1/cue 1"}
2019-02-20 13:40:41.559 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:45.755 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [5,6,7],"string": "part 1/cue 2"}
2019-02-20 13:40:48.755 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:56.031 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:40:57.035 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 2/cue 1"}
2019-02-20 13:40:59.517 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:02.718 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [10,20,30],"string": "part 2/cue 2"}
2019-02-20 13:41:05.717 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:06.490 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:07.506 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 3 _cue 1"}
2019-02-20 13:41:10.000 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:11.493 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [11,12,13],"string": "part 3_cue 2"}
2019-02-20 13:41:12.992 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:13.011 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:28.386 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:28.410 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:29.554 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:30.594 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 1/cue 1"}
2019-02-20 13:41:33.109 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:38.627 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [5,6,7],"string": "part 1/cue 2"}
2019-02-20 13:41:41.393 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:48.665 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:49.657 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 2/cue 1"}
2019-02-20 13:41:52.164 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:55.364 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [10,20,30],"string": "part 2/cue 2"}
2019-02-20 13:41:58.360 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:41:59.141 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:00.137 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 3 _cue 1"}
2019-02-20 13:42:02.637 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:04.204 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [11,12,13],"string": "part 3_cue 2"}
2019-02-20 13:42:05.629 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:05.660 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [111,122,133],"string": "part_4 / cue 1"}
2019-02-20 13:42:08.092 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:12.590 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 4 /cue 2"}
2019-02-20 13:42:16.089 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:23.644 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:23.662 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:23.732 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:41.854 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:42.856 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 2/cue 1"}
2019-02-20 13:42:45.351 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:48.550 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [10,20,30],,"string": "part 2/cue 2"}
2019-02-20 13:42:51.550 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:52.318 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:57.776 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:42:58.273 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [111,122,133],"string": "part_4 / cue 1"}
2019-02-20 13:43:01.273 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
2019-02-20 13:43:05.771 5697-5697/com.ianflitman.exoplayer E/cues are: {"array": [1,2,3],"string": "part 4 /cue 2"}
2019-02-20 13:43:09.273 5697-5697/com.ianflitman.exoplayer E/cue list object: empty
```

Am I doing something wrong or is this a known issue?

best
ian

**Comment by ojw28** [comment] 2019-02-20 19:29
We cannot help with this unless you provide proper reproduction steps.

**Comment by ojw28** [comment] 2019-03-06 09:21
Closing due to lack of further information.

**Closed as completed by ojw28** 2019-03-06 09:21 UTC
Labels: need more info
