### ISSUE TITLE
DefaultLoadControl looks not like working well

### ISSUE THREAD

**Issue by changja88** [google/ExoPlayer#4398] opened 2018-06-21 05:01 UTC
Method "shouldContinueLoading" in DefalutLoadControl class does not work well.
I do not know why, but I guess bufferedDurationUs parameter has 10time bigger than it should have. Because of this issues, player I made can not maintain buffered size.

Thanks.

**Comment by tonihei** [comment] 2018-06-21 08:21
Can you give some more concrete examples and/or reproduction steps? That would hep to understand your issue.

**Comment by changja88** [comment] 2018-06-21 09:07
First, symptom I can see is that, because bufferedDurationUs parameter is too larger, shouldContinueLoading method always return false, it makes player can maintain buffer size. 
For example, let's say min buffer is 5 sec. than while player should keep trying to maintain 5sec buffer size, but because shouldContinueLoading method always return false, player start getting buffer when player has nothing to play.

I can not measure exact buffered size,(min buffer is 15) I can see buffer duration is less than 15sec through DefaultTimeBar. But incoming bufferedDurationUs parameter is much larger than 15sec, and it return false.

I am sorry my bad English.

**Comment by tonihei** [comment] 2018-06-21 09:32
What you see on the time bar and what is passed to DefaultLoadControl should be exactly the same value. Can you provide us with an example media file where this happens and steps to reproduce in our demo app?

**Comment by tonihei** [comment] 2018-06-21 09:53
One thing to keep in mind is also that the value passed to DefaultLoadControl is in microseconds - so the values naturally will be very large. Could that be the source of confusion?

**Comment by changja88** [comment] 2018-06-21 10:12
Yea. I can not remember exactly but I know that value is microsecond or nanosecond. What I wanna say is that that parameter is almost always much bigger than minBuffer size.

**Comment by changja88** [comment] 2018-06-21 10:28
My company does not providing video for free, so I can not give you video
info on Github.
So, I will give example video, in this email.
And video is applied streaming + HLS

Url :
http://laftelmediaservice.streaming.mediaservices.windows.net/c465ed8c-eb29-44a4-9f86-d85dea5a53de/TestVideo_360x240_30mb.ism/manifest(format=m3u8-aapl)
Token :
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiI5YWZmMGZmMS01NWVjLTQxYmYtYTE2MS0wNGQzYjljMWIxMWUiLCJpc3MiOiJodHRwOi8vd3d3LmxhZnRlbC5uZXQiLCJhdWQiOiJ1cm46bGFmdGVsIiwiaWF0IjoxNTI5NTc2NzI4LCJuYmYiOjE1Mjk1NzY3MjgsImV4cCI6MTUyOTg1MjQwMCwidW5pcXVlX25hbWUiOiIwQDAifQ.jh9TwcLweMLfe1odypzabkrjC9fQAtsxJcJZSdRBhbs

(Token is valid until 6/26 00:00)

Thanks.

2018-06-21 18:53 GMT+09:00 tonihei <notifications@github.com>:

**Comment by tonihei** [comment] 2018-06-21 10:41
I deleted your previous post because its contents were publicly visible. If you want to send us information privately, please send an email to dev.exoplayer@gmail.com and use "Issue #4398" as subject.

**Comment by tonihei** [comment] 2018-06-21 11:48
I can't play the link you provided because I'm unsure how you add the access token. Can you give some details where to put it? Is it a HTTP request property or do I need to add it the url?

**Comment by changja88** [comment] 2018-06-22 03:06
I made a sample video without drm.
Uri :
http://laftelmediaservice.streaming.mediaservices.windows.net/4843f7a7-e518-4d6b-8315-563fe0e49745/TestVideo_360x240_30mb.ism/manifest(format=m3u8-aapl)

Thanks
Have a nice day.

2018-06-21 20:49 GMT+09:00 tonihei <notifications@github.com>:

**Comment by tonihei** [comment] 2018-06-22 08:28
I tested this file with our demo app and it plays perfectly fine. The buffered duration displayed in the UI exactly matches the values I get in `shouldContinueLoading`.

Could you try to play your file in our demo app and explain how exactly we can reproduce the problem?

**Comment by ojw28** [comment] 2018-06-29 16:31
Closing due to lack of information.

**Closed as completed by ojw28** 2018-06-29 16:31 UTC
Labels: need more info
