### ISSUE TITLE
Error inflating Player view 

### ISSUE THREAD

**Issue by appsapiconsole** [google/ExoPlayer#11110] opened 2023-04-10 07:28 UTC
### Bug
Exo Player version 2.18.5

I m facing bug in PlayerControlView line # 422 

![image](https://user-images.githubusercontent.com/56867915/230848630-2742ade1-e73f-47cf-9cd8-f29afb14acef.png)

while inflating R.layout.exo_player_control_view line # 64

![image](https://user-images.githubusercontent.com/56867915/230848869-bae8073f-98ed-4f10-a706-d01ccbd22e97.png)

after style code review. I found some mistake in ExoStyledControls.Button.Bottom.VR (@drawable/exo_styled_controls_vr)

![image](https://user-images.githubusercontent.com/56867915/230849110-ba37923f-d144-42d1-bc9c-37666b90e132.png)

these drawables are in drawable-v4 folder

![image](https://user-images.githubusercontent.com/56867915/230849500-303bb936-bbfb-4cb0-a4b8-a256f0b4b549.png) 

**move these icon to simple drawable folder will solve this issue.**

InflateException: Binary XML file line #21: Error inflating class androidx.media3.ui.PlayerView

Caused by android.view.InflateException: Binary XML file line #64: Error inflating class ImageButton
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at androidx.media3.ui.PlayerControlView.<init>(PlayerControlView.java:422)
       at androidx.media3.ui.PlayerView.<init>(PlayerView.java:455)
       at androidx.media3.ui.PlayerView.<init>(PlayerView.java:276)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       
       
![image](https://user-images.githubusercontent.com/56867915/230849638-dc1a14ad-0ea4-4993-9562-fb081ecbc8e0.png)
       
![image](https://user-images.githubusercontent.com/56867915/230848367-7e73742a-f8f1-478a-8821-726b9b589c0b.png)

**Comment by icbaker** [comment] 2023-04-11 17:01
Duplicate of https://github.com/androidx/media/issues/309

**Closed as completed by icbaker** 2023-04-11 17:01 UTC
Labels: duplicate
