### ISSUE TITLE
Obtaining video duration is abnormal

### ISSUE THREAD

**Issue by MrLizhiguang** [google/ExoPlayer#8491] opened 2021-01-22 04:12 UTC
Personal guess is that the decoder reads the video duration (milliseconds) and decimals
Test address：https://ops-aiops.oss-cn-hongkong.aliyuncs.com/vod/311_620_Venom20184K_play.ts

**Comment by MrLizhiguang** [comment] 2021-01-22 05:17
If the length is not available, all return -9223372036854775807

**Comment by ojw28** [comment] 2021-01-22 11:48
Yes. This is [clearly documented in the Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getDuration--):

> Returns the duration of the current content window or ad in milliseconds, **or C.TIME_UNSET if the duration is not known**.

**Comment by MrLizhiguang** [comment] 2021-01-22 11:55
Yes, I see that this suspicion is caused by this reason. Is there a way to solve this? Mediaplay is normal

**Comment by ojw28** [comment] 2021-01-22 12:00
https://github.com/google/ExoPlayer/issues/5097 is tracking an improvement that would make ExoPlayer better at inferring the duration of MPEG-TS streams, so this issue is effectively a duplicate of that one.

That aside, if you have any control over the media itself, the best solution is to use a modern container format such as MP4 or MKV, which are better designed to support efficiently determining the duration and performing seek operations.

Closing as a duplicate of https://github.com/google/ExoPlayer/issues/5097.

**Closed as completed by ojw28** 2021-01-22 12:00 UTC
Labels: duplicate

**Comment by MrLizhiguang** [comment] 2021-01-22 12:06
It is difficult to replace the container because the video is 4K, which is not conducive to network transmission

**Comment by ojw28** [comment] 2021-01-22 12:25
I do not understand what this means. The higher the resolution, the _worse_ MPEG-TS is as a choice of container (and the better MP4/MKV are, relative to MPEG-TS).

**Comment by MrLizhiguang** [comment] 2021-01-22 12:26
Video needs to be sliced

**Comment by ojw28** [comment] 2021-01-22 12:44
Sorry, I do not understand what that means. MP4 and MKV are well suited to streaming of 4K content.
