### ISSUE TITLE
Error in ExoPlayerFactory.newSimpleInstance method (No static method newSimpleInstance) when running exoplayer locally

### ISSUE THREAD

**Issue by Felipaorfr** [google/ExoPlayer#6071] opened 2019-06-20 21:34 UTC
I'm getting this error only when I'm running exoplayer locally with my project. If I import it from com.google.android.exoplayer:exoplayer-core:2.10.1 for instance, this doesn't happen.

The reason I'm trying to run locally it's because I'm getting this error in my project:

```
W/AudioCapabilities: Unsupported mime audio/ac4
W/AudioCapabilities: Unsupported mime audio/x-ima
W/AudioCapabilities: Unsupported mime audio/x-ape
W/AudioCapabilities: Unsupported mime audio/eac3-joc
W/AudioCapabilities: Unsupported mime audio/mpeg-L1
W/AudioCapabilities: Unsupported mime audio/mpeg-L2
W/AudioCapabilities: Unsupported mime audio/x-ms-wma
W/VideoCapabilities: Unsupported mime image/vnd.android.heic
W/System: A resource failed to call close. 
W/VideoCapabilities: Unrecognized profile 4 for video/hevc
W/VideoCapabilities: Unsupported mime video/mp43
W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
    Unrecognized profile/level 32768/2 for video/mp4v-es
    Unrecognized profile/level 32768/64 for video/mp4v-es
W/VideoCapabilities: Unsupported mime video/wvc1
W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
```

So I'm trying to run with the ffmpeg extension locally to see if it works. In my settings.gradle file I have:

```
gradle.ext.exoplayerRoot = 'path_to_exoplayer'
gradle.ext.exoplayerModulePrefix = 'exoplayer-'
apply from: new File(gradle.ext.exoplayerRoot, 'core_settings.gradle')
```
and in my build.gradle I have

```
compileOnly project(':exoplayer-library-core')
```

When I run the project, I get this error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.highway.radio, PID: 28450
    java.lang.NoSuchMethodError: No static method newSimpleInstance(Landroid/content/Context;Lcom/google/android/exoplayer2/RenderersFactory;Lcom/google/android/exoplayer2/trackselection/TrackSelector;Lcom/google/android/exoplayer2/LoadControl;)Lcom/google/android/exoplayer2/SimpleExoPlayer; in class Lcom/google/android/exoplayer2/ExoPlayerFactory; or its super classes (declaration of 'com.google.android.exoplayer2.ExoPlayerFactory' appears in /data/app/com.highway.radio-AKhXzhBGYk_Kwp_Vor1BCg==/base.apk)
        at smarttones.com.sdk.player.SimpleSTPlayer.<init>(STPlayer.kt:120)
        at smarttones.com.sdk.STViewController.onCreate(STViewController.java:175)
        at android.app.Activity.performCreate(Activity.java:7326)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

The relevant parts of code:

```
init {
        val trackSelector = DefaultTrackSelector()
        val loadControl = DefaultLoadControl()
        val renderersFactory = object : DefaultRenderersFactory(context) {
           //Lots of code
           
        }
       //It breaks in this line
        exoPlayer = ExoPlayerFactory.newSimpleInstance(context, renderersFactory, trackSelector, loadControl)
    }
```

The "lots of code" part I don't think it's relevant, it works when I import exoplayer from com.google.android, and it breaks running exoplayer locally even if I remove everything and leave just  
```
val renderersFactory = DefaultRenderersFactory(context)
```
It's weird because the class does have this method. What am I missing?

Thanks in advance!

**Comment by umangsaini** [comment] 2019-06-21 05:02
Library uses Java 8 features. Can you try adding following to your build.gradle to support Java 8

```
android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    ...
}
```

**Comment by andrewlewis** [comment] 2019-06-21 10:56
Just a side note about the `AudioCapabilities` and `VideoCapabilities` logging: I'm pretty sure that is expected 'log spam' and working as intended. However, the log line `System: A resource failed to call close.` may indicate an actual issue.

**Comment by Felipaorfr** [comment] 2019-06-21 17:38
I already have the java 8 options in my build.gradle exactly like this.

**Comment by ojw28** [comment] 2019-06-21 17:46
> and in my build.gradle I have `compileOnly project(':exoplayer-library-core')`

Why are you using `compileOnly`? I think that's supposed to indicate that the dependency is only needed at compile time. If so it's not surprising that compilation succeeds (because exoplayer-library-core is used) but then the app crashes at runtime (because you've specified that you don't need the dependency at runtime).

You should be using `implementation` (probably) or `api` (possibly), instead of `compileOnly`.

**Comment by Felipaorfr** [comment] 2019-06-21 17:59
If I use implementation or api, it gives this error

```
Error: Program type already present: com.google.android.exoplayer2.C$AudioContentType
```
which I know what it means but was absolutely impossible to get rid of it. Any suggestions?

Here is the list of dependencies from my project, I have no idea what causes to crash with api or implementation.

```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.android.volley:volley:1.1.0'
    implementation 'com.mani:ThinDownloadManager:1.3.0'
    implementation 'com.snappydb:snappydb-lib:0.5.2'
    implementation 'com.esotericsoftware.kryo:kryo:2.24.0'
    testImplementation 'junit:junit:4.12'
    implementation 'com.intrasonics:IntrasonicsSDK-release@aar'
    implementation 'com.mufin.audioid.framework:mufin-audioid@aar'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'com.baoyz.swipemenulistview:library:1.3.0'
    implementation 'com.squareup.okhttp3:okhttp:3.14.0'
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    api project(':exoplayer-library-core')
//    implementation 'com.google.android.exoplayer:exoplayer-core:2.10.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.squareup.retrofit2:converter-gson:2.1.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.1.0'
    implementation 'androidx.room:room-runtime:2.0.0'
    annotationProcessor 'androidx.room:room-compiler:2.0.0'
    kapt 'androidx.room:room-compiler:2.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    kapt 'androidx.lifecycle:lifecycle-compiler:2.0.0'
    implementation 'org.zeroturnaround:zt-zip:1.13'
    implementation 'com.mindorks.android:prdownloader:0.4.0'
    implementation 'com.github.ghost1372:Mzip-Android:0.4.0'
    implementation 'com.github.ashqal:android-libresample:0.3.0'
    implementation 'saschpe.android:exoplayer2-ext-icy:1.0.1'
}
```

**Comment by ojw28** [comment] 2019-06-21 18:08
You're including two different versions of ExoPlayer. One version is pulled in as source code. A second version is pulled in as a transient dependency, since `saschpe.android:exoplayer2-ext-icy:1.0.1` pulls in `com.google.android.exoplayer:exoplayer-core:2.6.1`. This is not a valid thing to do.

Note that ExoPlayer 2.10.1 supports ICY metadata directly (see [this blog post](https://medium.com/google-exoplayer/exoplayer-2-10-whats-new-15d344eaa8b9)). So perhaps the best approach for you is to transition over to using the direct ICY metadata support, then remove your dependency on `saschpe.android:exoplayer2-ext-icy:1.0.1`, and at that point everything will probably just work.

Closing, since this is an issue with your application's build setup, rather than something wrong with ExoPlayer.

**Closed as completed by ojw28** 2019-06-21 18:08 UTC
Labels: question
