### ISSUE TITLE
Any plan to enable downloading SS/DASH/HLS into one single mp4 file?

### ISSUE THREAD

**Issue by robin2046** [google/ExoPlayer#4646] opened 2018-08-13 02:31 UTC
The newly added download manager feature can download and cache the streams on device storage. However, is it possible to provide the function to assemble them into a single mp4 file?

For example, I saw the RedditIsFun app can download the short video clip from https://v.redd.it (served as DASH) in a single mp4 file and then user can share the video clip easily. When I tried to use ExoPlayer to download the same DASH stream, it was stored in several parts.

Will ExoPlayer provide some feature to download the stream in a single file (compatible with other simple media player) in future?

**Comment by andrewlewis** [comment] 2018-08-13 10:37
Duplicate of #4540

**Closed as completed by andrewlewis** 2018-08-13 10:37 UTC
Labels: duplicate
