### ISSUE TITLE
com.google.android.exoplayer2.ExoPlaybackException: Source error

### ISSUE THREAD

**Issue by sannykhan3777** [google/ExoPlayer#9245] opened 2021-08-01 16:31 UTC
**Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)**

I am getting error when I play a .m3u8 video. Its basically a live news video.
I am using flutter 2.0. 

**Dependencies Used :**
video_player: ^2.1.12
chewie: ^1.0.0

I tried many time but error persists.
When I play a video which has extension .mp4 it plays the video without error. But error occurs when I play HLS m3u8  live video.
Anyone can solve it please?

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class LiveNewsScreen extends StatefulWidget {
  @override
  _LiveNewsScreenState createState() => _LiveNewsScreenState();
}
class _LiveNewsScreenState extends State<LiveNewsScreen> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'http://161.97.162.167:1936/live/tnnnews/playlist.m3u8')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: VideoPlayer(_controller),
          )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
```

**Comment by andrewlewis** [comment] 2021-08-02 09:16
Please can you provide the full stack trace for the `ExoPlaybackException` including the cause of the source error? There's not enough information here to go on but if the URL's correct I'd guess the error may be [due to not using `https`](https://exoplayer.dev/troubleshooting.html#fixing-cleartext-http-traffic-not-permitted-errors).

You could also try playing the stream in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html). If that works then it's likely to be a problem with how Flutter is using ExoPlayer so should be reported to the Flutter project.

**Comment by andrewlewis** [comment] 2021-08-02 11:02
The stream plays fine for me in the demo app if I enable cleartext traffic so I will close this issue as I don't think there is an ExoPlayer bug here. Please try [enabling cleartext traffic](https://exoplayer.dev/troubleshooting.html#fixing-cleartext-http-traffic-not-permitted-errors) and if that doesn't work report the issue to Flutter.

**Closed as completed by andrewlewis** 2021-08-02 11:02 UTC
Labels: question
