### ISSUE TITLE
ExoPlayer Subtitles disappear upon changing the orientation

### ISSUE THREAD

**Issue by RosalineMakar** [google/ExoPlayer#3502] opened 2017-11-26 21:52 UTC
### Issue description
We have an activity that hosts a retained fragment, the retained fragment holds instance of the ExoPlayer. The video has subtitles, and runs smoothly with the subtitles being displayed, however On Orientation change, the video continue playing and the subtitles disappear, but, if we seek to any point of the video while on play mode, the subtitles show normally.
I think it is a bug in Exoplayer because the subtitles are loaded correctly and works fine when you make a seek after the orientation change. would you please advise?

### Reproduction steps
1) create an activity that has a retained fragment. the fragment maintains an instance of the video player (SimpleExoPlayer). The activity has 2 layouts for landscape and portrait.
2) start the video and enable the subtitles, and the subtitles will start displaying
3) change the orientation and the video will continue playing but the subtitles will disappear
4) seek to anypoint of the video, and the subtitles will show again.

### Version of ExoPlayer being used
For V2.5.4

### Device(s) and version(s) of Android being used
Emulator Tablet Nexus 10, API 23

**Comment by ojw28** [comment] 2017-11-28 12:00
Is it possible for you to provide a simple demo project (as source) that reproduces the issue?

**Comment by ojw28** [comment] 2018-01-02 18:55
Closing due to lack of information that would allow us to (efficiently) reproduce the problem.

**Closed as completed by ojw28** 2018-01-02 18:55 UTC
Labels: need more info
