### ISSUE TITLE
Offline license drm + ABR for streaming content

### ISSUE THREAD

**Issue by tiaragizka** [google/ExoPlayer#8368] opened 2020-12-18 01:58 UTC
How to use offline license drm + abr for streaming content ?
I've tried to use offline license for drm without abr and it worked, but when i try offline license to play drm source with abr, exo always tells me error "Crypto key not available", meanwhile when i try online license to play drm source with abr or without abr Player runs normally. is there anything else you need to do to play drm + abr source on an offline license?

i try sample offline license from exoplayer for play drm source + abr but same problem exo tell me error "crypto key not available"

I hope to help my problem.

**Comment by tonihei** [comment] 2020-12-18 17:16
Please don't file duplicate issues. Closing as duplicate of #8350.

**Closed as completed by tonihei** 2020-12-18 17:16 UTC
Labels: duplicate
