### ISSUE TITLE
Is it possible to set volume greater than 1.0f (amplification)

### ISSUE THREAD

**Issue by devnullpointer** [google/ExoPlayer#3657] opened 2018-01-02 18:01 UTC
### Issue description
Is it possible to set the volume in exoplayer to a value greater than 1.0f to create an "amplification" effect for videos that have been recorded with low audio levels?

### Reproduction steps
1) add a seekbar in the overriden exo_playback_control_view
2) add the following onseekbarchangelistener in the player activity 
```Java
seekBar.setMax(200);
seekBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener()
        {
            @Override
            public void onProgressChanged(final SeekBar seekBar, final int progress, final boolean fromUser)
            {
                final float adjust = (float) progress / 100;
                Log.d(TAG, "Volume: " + adjust);
                player.setVolume(adjust);
            }

            @Override
            public void onStartTrackingTouch(final SeekBar seekBar)
            {
            }

            @Override
            public void onStopTrackingTouch(final SeekBar seekBar)
            {
            }
        });
```
Any volume level greater than 1.0f has no audio effect, lower than 1.0 will reduce the volume.

### Version of ExoPlayer being used
2.6.0

### Device(s) and version(s) of Android being used
Android KitKat 4.4

**Comment by andrewlewis** [comment] 2018-01-03 08:48
It should be possible to implement this kind of postprocessing via a custom `AudioProcessor`. Marking as an enhancement for now, but it's unlikely we will get round to it soon. Feel free to send a PR.

**Comment by andrewlewis** [comment] 2018-01-03 13:48
Marking as a duplicate of #2659 as that is also a request for a volume controlling `AudioProcessor`.

**Closed as completed by andrewlewis** 2018-01-03 13:48 UTC
Labels: duplicate
