### ISSUE TITLE
Motorola G5: Internal runtime error if not using a deprecated DefaultTrackSelector constructor

### ISSUE THREAD

**Issue by AndrazP** [google/ExoPlayer#6189] opened 2019-07-16 00:24 UTC
### [REQUIRED] Issue description
ExoPlayer fails to play DASH video content with "Internal runtime error" on Motorola Moto G5 if a [non deprecated DefaultTrackSelector](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html#DefaultTrackSelector--) is used.

Only one ExoPlayer instance is used. Code was forked from [UniversalMusicPlayer example](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/common/src/main/java/com/example/android/uamp/media/MusicService.kt).

Working with [deprecated constructor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html#DefaultTrackSelector-com.google.android.exoplayer2.upstream.BandwidthMeter-):
```Kotlin
val trackSelector = DefaultTrackSelector(DefaultBandwidthMeter())
ExoPlayerFactory.newSimpleInstance(this, CustomRenderersFactory(this), trackSelector)
```

Not Working:
```Kotlin
val trackSelector = DefaultTrackSelector()
ExoPlayerFactory.newSimpleInstance(this, CustomRenderersFactory(this), trackSelector)
```

[DefaultRenderersFactory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultRenderersFactory.html) is extended so that MediaCodecVideoRenderer can be instantiated with _enableDecoderFallback_ = true

### [REQUIRED] Reproduction steps
- Call ExoPlayer newSimpleInstance with DefaultTrackSelector()
- Play DASH video content on Motorola Moto G5 and stop it
- Play again the same or different video

### [REQUIRED] Link to test content
Please let me know if it's needed and I will share it with you privately.

### [REQUIRED] A full bug report captured from the device
Full bug report was emailed to dev.exoplayer@gmail.com

Logcat crash report
```E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2576)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal: Disable failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2060)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:702)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:604)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:580)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:451)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:158)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1088)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:851)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
E/EventLogger: playerFailed [24.34, 0.00, window=0, period=0]
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:397)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2576)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:653)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
D/EventLogger: decoderDisabled [24.34, 0.00, window=0, period=0, video]
D/EventLogger: decoderDisabled [24.34, 0.00, window=0, period=0, audio]
E/ExoPlayerImplInternal: Reset failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2013)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:609)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:594)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:587)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:460)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:164)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:860)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

### [REQUIRED] Version of ExoPlayer being used
2.10.3

### [REQUIRED] Device(s) and version(s) of Android being used
Motorola Moto G5 running Android 7.0 It can always be reproduced.
It **can't** be reproduced on Samsung S3 4.4, Samsung S5 6.0.1, Samsung S7 8.0, Pixel 3 9.0,...

**Comment by andrewlewis** [comment] 2019-07-16 07:43
At the point of setting up the decoder for 1080p, it looks like there are not enough resources:

```
07-15 15:17:11.765  1894  2652 D SurfaceUtils: set up nativeWindow 0x8209c408 for 1920x1080, color 0x7fa30c04, rotation 0, usage 0x2002900
[...]
07-15 15:17:11.774   724  2658 E OMX-VDEC-1080P: Failed to call stream on OUTPUT due to HW_OVERLOAD
07-15 15:17:11.774   724  2658 E OMX-VDEC-1080P: empty_this_buffer_proxy failure due to HW overload
07-15 15:17:11.774   724  2658 E OMX-VDEC-1080P: ERROR: Sending OMX_ErrorInsufficientResources to Client
07-15 15:17:11.775   724  2658 E OMX-VDEC-1080P: Failed to qbuf to driver, send FTB back to client
```

The highest resolution streams are:

```
D EventLogger:       [X] Track:0, id=137, mimeType=video/avc, bitrate=3565945, codecs=avc1.640028, res=1920x1080, fps=25.0, supported=YES
D EventLogger:       [ ] Track:1, id=299, mimeType=video/avc, bitrate=5012960, codecs=avc1.64002a, res=1920x1080, fps=50.0, supported=NO_EXCEEDS_CAPABILITIES
```

avc1.640028 is H.264/AVC High profile level 4.0.

In the case where you don't see the error, is the 1080p stream being selected?

**Comment by AndrazP** [comment] 2019-07-31 01:46
My further observations: 
- I've updated the reproduction steps. Playback stops working on the second play.
- Playback stops working only when "Auto" quality level is selected. If I switch to specific quality (for example 1080p) video starts playing. 

Our code for setting quality level:
```kotlin
fun selectTrackById(qualityLevel: QualityLevel) {
    val trackInfo = trackSelector.currentMappedTrackInfo ?: return
    val indices = qualityLevel.indices ?: return
    val parametersBuilder = trackSelector.buildUponParameters()

    when (qualityLevel) {
        is QualityLevel.Auto -> parametersBuilder
            .setRendererDisabled(indices.rendererIndex, false)
            .clearSelectionOverride(indices.rendererIndex, trackInfo.getTrackGroups(indices.rendererIndex))
        is QualityLevel.AudioOnly -> parametersBuilder
            .setRendererDisabled(indices.rendererIndex, true)
        else -> parametersBuilder
            .setRendererDisabled(indices.rendererIndex, false)
            .setSelectionOverride(
                indices.rendererIndex,
                trackInfo.getTrackGroups(indices.rendererIndex),
                DefaultTrackSelector.SelectionOverride(indices.groupIndex, indices.trackIndex)
            )
    }
    trackSelector.parameters = parametersBuilder.build()
}
```

**Comment by ojw28** [comment] 2021-06-07 15:44
This is a device specific issue. The device is 4+ years old, and discontinued. Realistically, we can't dedicate resources to investigating further on our side. Even if we were to root cause an issue in the underlying platform, it seems unlikely that it would be fixed. Hence closing this as obsolete.

**Closed as completed by ojw28** 2021-06-07 15:44 UTC
Labels: bug: device specific
