### ISSUE TITLE
parseEsdsFromParent throw exception with "Top bit not zero: -1"

### ISSUE THREAD

**Issue by zgzong** [google/ExoPlayer#10419] opened 2022-07-07 15:33 UTC
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

This is not device related issue. Any device can reproduce this issue. 

### Reproducible in the demo app?

Yes

### Reproduction steps

This is dashif test vector stream, add it into exoplayer demo app media.exolist.json
      {
        "name": "DASH TestVector Testcase 1b Thomson2",
        "uri" : "http://dash.edgesuite.net/dash264/TestCases/1b/thomson-networks/2/manifest_bug.mpd"
      }

And the issue will occurred when try to play it.

### Expected result

The stream can be played smoothly. 

### Actual result

The following exception thrown. 

2022-07-07 16:09:46.688 17621-17720/com.google.android.exoplayer2.demo E/LoadTask: Unexpected exception loading stream
      java.lang.IllegalStateException: Top bit not zero: -1
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:371)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseEsdsFromParent(AtomParsers.java:1686)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:1516)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:987)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:311)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:132)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onMoovContainerAtomRead(FragmentedMp4Extractor.java:516)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onContainerAtomRead(FragmentedMp4Extractor.java:486)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.processAtomEnded(FragmentedMp4Extractor.java:466)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:461)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:338)
        at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor.read(BundledChunkExtractor.java:147)
        at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:102)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

This stream can be played smoothly with exoplayer 2.16.1.

### Media

http://dash.edgesuite.net/dash264/TestCases/1b/thomson-networks/2/manifest_bug.mpd

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-07-07 15:55
Duplicate of #10381

**Closed as completed by icbaker** 2022-07-07 15:55 UTC
Labels: duplicate
