### ISSUE TITLE
exoplayer-ui-2.12.1.aar contains references to both AndroidX and old support library. 

### ISSUE THREAD

**Issue by ag2s20150909** [google/ExoPlayer#8745] opened 2021-03-22 07:46 UTC
WARNING: [Processor] Library 'C:\Users\XXX\.gradle\caches\modules-2\files-2.1\com.google.android.exoplayer\exoplayer-ui\2.12.1\6b33e4f62e15ece19b04fbb9747434267b45e02f\exoplayer-ui-2.12.1.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/core/app/NotificationCompat$Builder'
 Example of support library reference: 'android/support/v4/media/session/MediaSessionCompat$Token'

**Comment by andrewlewis** [comment] 2021-03-22 08:47
Duplicate of #8580

**Closed as completed by andrewlewis** 2021-03-22 08:47 UTC
Labels: duplicate
