### ISSUE TITLE
Black screen appears when we seek over an AdGroup.

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#5507] opened 2019-02-13 14:03 UTC
When playing ads using AdsMediaSource and AdsLoader, if we seek over an adGroup black screen appears until the ad is loaded. This does not happen when we seek within content before adGroup, it will retain the previous frame until seek position data is available.

This issue is easily reproducible in sample app. Please look into this, also provide some info where I can look in ExoPlayer to understand what is happening.

**Comment by marcbaechinger** [comment] 2019-02-13 21:47
Thanks for your report!

I can reproduce this behaviour with an mid roll ad tag like the sample tag added below. In case a user seeks over ad marker from a position at which the ad has not yet been loaded, the surface is immediately rendered black. 

https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=

**Comment by sravan1213** [comment] 2019-02-27 12:12
@marcbaechinger @andrewlewis is there any update on this issue. If this not in your priority list could you please guide me in helping where to look in source code to fix this.

Thanks in advance.

**Comment by ojw28** [comment] 2020-06-09 09:04
This happens because we close the shutter when seeking to an unprepared period. The same issue occurs if seeking to a different (unprepared) period within the same piece of DASH content.

I think we should suppress closing the shutter in this case, provided the old and new periods belong to the same window.

**Comment by ojw28** [comment] 2020-06-11 11:33
Fixed by the commit referenced above.

**Closed as completed by ojw28** 2020-06-11 11:33 UTC
Labels: bug

**Comment by ojw28** [comment] 2020-06-23 15:46
This will be released in 2.11.6.
