### ISSUE TITLE
Some decoders advertise audio/mpeg-L2 support but do not correctly implement it

### ISSUE THREAD

**Issue by Norhan-El-Ashry** [google/ExoPlayer#3108] opened 2017-07-26 22:17 UTC
Hii

When I tried to play .ts live streams e.x.

http://avatar-iptv.net:1795/live/az5130/PPYnz6ewcVb1/213.ts

It works in some devices but with no audio track

in other devices it gives me that error

```
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.sprd.mp3.decoder, Format(1/257, null, audio/mpeg-L2, -1, null, [-1, -1, -1.0], [2, 48000])
com.google.android.exoplayer2.ExoPlaybackException
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:380)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:367)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796)
at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.sprd.mp3.decoder, Format(1/257, null, audio/mpeg-L2, -1, null, [-1, -1, -1.0], [2, 48000])
... 9 more
Caused by: java.lang.IllegalStateException
at android.media.MediaCodec.native_configure(Native Method)
at android.media.MediaCodec.configure(MediaCodec.java:262)
at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.configureCodec(MediaCodecAudioRenderer.java:201)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:356)
... 8 more
```

I guess that there is a problem with audio track. Is there a way to fix it or download an alternative track?
and how can I get the track and merge it with video.

Thank you

**Comment by AquilesCanta** [comment] 2017-07-27 09:20
See [supported sample formats](https://google.github.io/ExoPlayer/supported-formats.html#sample-formats). Since mpeg-L2 is not part of the CDD, not many devices include decoders for this format. You can always bundle your own, for example using the ffmpeg extension. 

However, please do provide a list of devices where an exception is thrown. If this is reproducible in the DemoApp, then this is something we would like to fix.

**Comment by Norhan-El-Ashry** [comment] 2017-07-27 10:20
Thank you for for your reply.
Could you please tell me more information about bundling my own decoder and
how to use it with exoplayer.
any tutorials or examples will very helpful.

about devices list.
until now the error occurred in two devices

samsung GT-I9060I 4.4.4 KITKAT

HUAWEI T1-701u 4.4.2 KITKAT

and the video plays with no voice in

HUAWEI CAM-L21 6.0 LOLLIPOP_MR1


On Thu, Jul 27, 2017 at 11:20 AM, Santiago Seifert <notifications@github.com

**Comment by ojw28** [comment] 2017-11-19 14:35
You'd be better off using a more modern format, however if you do need to bundle your own decoder you can try the [FFmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) configured with `–enable-decoder=mp3` as described [here](https://google.github.io/ExoPlayer/supported-formats.html).

Let's use this issue to track blacklisting decoders, specifically for audio/mpeg-L2, that advertise audio/mpeg-L2 support but don't correctly implement that support.

**Comment by ojw28** [comment] 2017-11-19 14:36
Another case we should look to blacklist is described in https://github.com/google/ExoPlayer/issues/3266.

**Comment by ojw28** [comment] 2019-03-06 19:46
I don't think device specific issues on KitKat devices, when using audio/mpeg-L2, is going to be an effective use of our time at this point. Closing as obsolete.

**Closed as completed by ojw28** 2019-03-06 19:46 UTC
Labels: bug: device specific
