### ISSUE TITLE
isEncodingLinearPcm return false for FireOS 5 device (AFTT)

### ISSUE THREAD

**Issue by xiaoluluxian** [google/ExoPlayer#10561] opened 2022-08-27 06:34 UTC
### ExoPlayer Version

2.13.3

### Devices that reproduce the issue

FireTV Tank FOS 5 device running Android API 22

### Devices that do not reproduce the issue

FireTV Mantis FOS 6 device running Android API 23

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play the media in app causing the error below.
```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:589)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:41)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:525)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onOutputFormatChanged(MediaCodecAudioRenderer.java:485)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.updateOutputFormatForTime(MediaCodecRenderer.java:649)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:838)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:954)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:480)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```
DefaultAudioSink.configure actually checking isEncodingLinearPcm() and this return false causing Assertions.checkArgument throw IllegalArgumentException

### Expected result

Media plays successfully

### Actual result

Exoplayer throws error below
```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:589)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:41)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:525)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onOutputFormatChanged(MediaCodecAudioRenderer.java:485)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.updateOutputFormatForTime(MediaCodecRenderer.java:649)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:838)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:954)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:480)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-08-30 09:50
`com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:525)` This line does not call `Assertions.checkArgument` in version 2.13.3 of this library:

https://github.com/google/ExoPlayer/blob/03263db378392385e290c40505d80e990c85a5cb/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L525

The `isEncodingLinearPcm` check is on L511 in 2.13.3:

https://github.com/google/ExoPlayer/blob/03263db378392385e290c40505d80e990c85a5cb/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L511

The assertion is on L525 of the FireOS port of ExoPlayer:
https://github.com/amzn/exoplayer-amazon-port/blob/3668eaf71ae8e6ae8e64d0f5d584d704d23f631c/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L525

If you have an issue with that library, I suggest you ask on their issue tracker. Ah, you already have: https://github.com/amzn/exoplayer-amazon-port/issues/122 :)

I'll close this as a duplicate of that.

**Closed as completed by icbaker** 2022-08-30 09:50 UTC
Labels: duplicate
