### ISSUE TITLE
Exoplayer play with Using Retrofit

### ISSUE THREAD

**Issue by mkarthick92** [google/ExoPlayer#4537] opened 2018-07-19 13:02 UTC
Hi, 
I am facing the issue is the video streaming url in exoplayer 2.1.0 they play the video only the android version 7 and 8 but not play the video in the android lower version like 6,5,4.4..
The HLS Stream method i get the video properly in the nougat and oreo based device but not able to get the video but the duration of the video is display but the video is not playing.
and my log cat is 

the Logcat preview:

```EventLogger: internalError [1.15, loadError]
                                                                                      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:235)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:187)
                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:841)
07-19 18:29:32.392 16661-16665/? E/mnl_linux: mtk_gps_sys_gps_mnl_callback: Get SV info success
07-19 18:29:32.831 12166-12166/asianetmobiletvplus.asianetmobiletv.com E/EventLogger: internalError [1.68, loadError]
                                                                                      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:235)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:187)
                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:841)
07-19 18:29:33.392 16661-16665/? E/mnl_linux: mtk_gps_sys_gps_mnl_callback: Get SV info success
07-19 18:29:34.384 12166-12166/asianetmobiletvplus.asianetmobiletv.com E/EventLogger: internalError [3.23, loadError]
                                                                                      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:235)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:187)
                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:841)
07-19 18:29:34.392 16661-16665/? E/mnl_linux: mtk_gps_sys_gps_mnl_callback: Get SV info success
07-19 18:29:35.391 16661-16665/? E/mnl_linux: mtk_gps_sys_gps_mnl_callback: Get SV info success
07-19 18:29:36.393 16661-16665/? E/mnl_linux: mtk_gps_sys_gps_mnl_callback: Get SV info success
07-19 18:29:36.944 12166-16919/asianetmobiletvplus.asianetmobiletv.com E/ExoPlayerImplInternal: Source error.
                                                                                                com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
                                                                                                    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                                    at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                                    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:235)
                                                                                                    at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:187)
                                                                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                    at java.lang.Thread.run(Thread.java:841)
07-19 18:29:36.947 12166-12166/asianetmobiletvplus.asianetmobiletv.com E/EventLogger: internalError [5.79, loadError]
                                                                                      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:235)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:187)
                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:841)
07-19 18:29:36.953 12166-12166/asianetmobiletvplus.asianetmobiletv.com E/EventLogger: playerFailed [5.80]
                                                                                      com.google.android.exoplayer2.ExoPlaybackException
                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                       Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:212)
                                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:235)
                                                                                          at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:187)
                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                          at java.lang.Thread.run(Thread.java:841)
07-19 18:29:37.394 16661-16665/? E/mnl_linux: mtk_gps_sys_gps_mnl_callback: Get SV info success
07-19 18:29:38.395 16661-16665/? E/mnl_linux: mtk_gps_sys_gps_mnl_callback: Get SV info success
```

android device working:
version 8 - oreo
version 7 & 7.1 - nougat

android device not working
version 6 - marshmallow
version 5 - lolipop
version 4.4 - kitkat

**Comment by ojw28** [comment] 2018-07-19 14:35
`InvalidResponseCodeException: Response code: 400` is a "Bad Request" response from the server. You need to figure out why your server is responding in that way. It doesn't look like an ExoPlayer issue.

**Comment by mkarthick92** [comment] 2018-07-20 04:38
Hi ojw28,
But the video url play in vlc player and also they play in android version 7 & 8 devices

**Comment by ojw28** [comment] 2018-07-20 10:34
That doesn't necessarily mean it's an ExoPlayer issue. Most likely you see that samples in our demo app do not have this issue, which suggests the issue is specific to the server you're requesting content from. Perhaps it's responding with 400 based on the user agent or something, and ExoPlayer is setting a user agent that the server is failing to handle on those API levels.

We can take a quick look if you provide us with a working test stream. Without that there's nothing we can do to help. If you control the server you should also just look in your server logs to find out why the server is responding in the way that it is.

**Comment by ojw28** [comment] 2018-07-22 19:53
Closing because we don't have a working test stream. Please respond here if you're able to provide one.

**Closed as completed by ojw28** 2018-07-22 19:53 UTC
Labels: question
