### ISSUE TITLE
ArrayIndexOutOfBoundsException in ImaAdsLoader.loadAd

### ISSUE THREAD

**Issue by asidahan** [google/ExoPlayer#3552] opened 2017-12-05 13:19 UTC
Hi,
we have videos with ads in our app, and we have ArrayIndexOutOfBoundsException in the ima extension. We don't have a specific scenario for this crash and it happens randomly on many devices. I attach the stack trace below:

```
length=1; index=-1
java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
	at com.google.android.exoplayer2.ext.ima.AdPlaybackState.addAdUri(AdPlaybackState.java:111)
	at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.loadAd(ImaAdsLoader.java:461)
	at com.google.obf.hm.safedk_VideoAdPlayer_loadAd_38ec4ebf3a116296f255437bbde61c86(IMASDK)
	at com.google.obf.hm.a(IMASDK:36)
	at com.google.obf.hj.e(IMASDK:151)
	at com.google.obf.hj.a(IMASDK:45)
	at com.google.obf.hk.b(IMASDK:39)
	at com.google.obf.hk$1.shouldOverrideUrlLoading(IMASDK:4)
	at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
	at com.android.webview.chromium.Ap.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:72)
	at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15)
	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160)
	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by andrewlewis** [comment] 2017-12-07 13:17
Thanks for reporting this. Would you be able to share the ad tag so we can investigate the cause for this? (Please email it to dev.exoplayer@gmail.com if you don't want to share it publicly.)

The IMA SDK is telling us to load an ad but the `LOADED` ad event hasn't been delivered, so this case is unexpected. I'll see if I can make the loader more robust to this case.

**Comment by ojw28** [comment] 2018-02-26 19:48
@andrewlewis - Did 2.7.0 fix this?

**Comment by andrewlewis** [comment] 2018-02-26 20:19
Yes, I think this should be fixed.

**Closed as completed by andrewlewis** 2018-02-26 20:19 UTC
Labels: bug
