### ISSUE TITLE
Low resolution on HD streams since v2.18.2

### ISSUE THREAD

**Issue by cemrich** [google/ExoPlayer#10898] opened 2023-01-02 17:21 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

* Pixel 2 emulator, Android 10
* Lenova Tablet Tab M10 FHD Plus, Android 10

### Devices that do not reproduce the issue

* Pixel 7, Android 13
* Fairphone 3, Android 11
* Fold-out emulator, Android 11
* Samsung S7, Android 8

### Reproducible in the demo app?

Yes

### Reproduction steps

Play back the German public broadcasting stream `https://mcdn.daserste.de/daserste/de/master.m3u8` with Exoplayer 2.18.2.

This issue does not occur with Exoplayer 2.18.1

### Expected result

Exoplayer should select the HD resolution

![android-11](https://user-images.githubusercontent.com/403202/210262173-5f8350bf-894b-488e-acfd-e9e5eb115a20.JPG)

### Actual result

Exoplayer does select a very low and blurry 480x270 resolution

![android-10](https://user-images.githubusercontent.com/403202/210262221-302bb56a-a6ac-4164-a3a8-5ed781f46baf.JPG)

This issue was first reported on the Zapp open source project: https://github.com/mediathekview/zapp/issues/346

### Media

https://mcdn.daserste.de/daserste/de/master.m3u8

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment] 2023-01-05 10:21
We changed our codec support check in 2.18.2 to check additional performance point data. I don't have a Lenova Tablet Tab M10 FHD Plus, but what happens on the Pixel 2 Android 10 emulator is that it says it supports the format up to 1920x1088 and 960 fps. This is what the decoder is capable of decoding if you give it enough time. But it also tells us that it only supports up to 30 fps for real-time playback (this is what we started checking in addition). Because your stream is only available in 50 fps, none of the available resolutions is deemed supported because they all exceed the maximum supported frame rate. ExoPlayer then still attempts to play the stream, but only in the lowest possible configuration, under the assumption that if it needs to exceed capabilities anyway, then it should select the format that is most likely to work. 

So this is all working as intended from the player code perspective, but I'd say it's a device-specific bug for this Lenovo tablet if it underreports its capabilities. In fact, the [Android CDD](https://source.android.com/docs/compatibility/10/android-10-cdd#5_3_4_h_264) requires all Android 10 devices to support H264 1280x720x 60 fps at least as long as the display has at least as many pixels. Did you see this issue on any other device?

**Comment by cemrich** [comment] 2023-01-05 10:27
@tonihei Thank you very much for the feedback. A user reported having issues with multiple devices. I will ask for more specific information and report back to you. I myself have no other test device with this issue.

**Comment by cemrich** [comment] 2023-01-06 18:45
After reaching out to the user, the issue can only be reproduced on this single device (in addition to the emulator).

I was stumped by the drastic behaviour change between bugfix releases. But now it is looking like a set of rather rare cirumstances.

**Comment by S0und** [comment] 2023-01-24 21:25
I have this issue (max available resolution is 1080p60 but the player picks the lowest 480p30) on two devices, at least that's how much was reported.

* Android TV emulator 
* Google Chromecast 4K (assuming the normal has this issue also)

The same build runs fine on a Nvidia Shield 2019, FireTV Max, Sony Bravia. I've personally tested all mentioned devices. All of them correctly pick the highest stream, meanwhile, the Chromecast and the Emulator are stuck on 480p30. 

@tonihei 
> We changed our codec support check in 2.18.2 to check additional performance point data

Am I able to circumvent this behavior? Other than downgrading to 2.18.1. 
```
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="chunked",NAME="1080p60 (source)",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=9001805,RESOLUTION=1920x1080,CODECS="avc1.42C02A,mp4a.40.2",VIDEO="chunked",FRAME-RATE=60.000
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p60",NAME="720p60",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=3422999,RESOLUTION=1280x720,CODECS="avc1.4D401F,mp4a.40.2",VIDEO="720p60",FRAME-RATE=60.000
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="480p30",NAME="480p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=1427999,RESOLUTION=852x480,CODECS="avc1.4D401F,mp4a.40.2",VIDEO="480p30",FRAME-RATE=30.000
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="360p30",NAME="360p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=630000,RESOLUTION=640x360,CODECS="avc1.4D401F,mp4a.40.2",VIDEO="360p30",FRAME-RATE=30.000
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="160p30",NAME="160p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=230000,RESOLUTION=284x160,CODECS="avc1.4D401F,mp4a.40.2",VIDEO="160p30",FRAME-RATE=30.000
```
These are pretty standard resolution / framerates in my opinion. 

Eventlogs for the few seconds 

`2.18.2`
[Chromecast with Google TV](https://gist.github.com/S0und/fc7725ba079f994b621a0aec336a0983)
[Android TV emulator](https://gist.github.com/S0und/89a174b44d00276634ee4dd5f1c4aca9)

[Nvidia Shield 2019](https://gist.github.com/S0und/740a60616b672f8bdcf6f9c0c49df054)
[Sony Bravia](https://gist.github.com/S0und/f1125f9fd2678d86a066f6583e30e608)


`2.18.1`
[Chromecast with Google TV](https://gist.github.com/S0und/d53d86a68006a1c63047adc4ed8f632a)

Also I find that interesting that on 2.18.1 and below the Emulator still supported 720p, and even 1080p on way earlier versions.

```
2.18.1

group [
  [ ] Track:0, id=0, mimeType=video/avc, bitrate=9002733, codecs=avc1.42C02A, res=1920x1080, fps=60.0, supported=NO_EXCEEDS_CAPABILITIES
  [X] Track:1, id=1, mimeType=video/avc, bitrate=3422999, codecs=avc1.4D401F, res=1280x720, fps=60.0, supported=YES
  [X] Track:2, id=2, mimeType=video/avc, bitrate=1427999, codecs=avc1.4D401F, res=852x480, fps=30.0, supported=YES
  [X] Track:3, id=3, mimeType=video/avc, bitrate=630000, codecs=avc1.4D401F, res=640x360, fps=30.0, supported=YES
  [X] Track:4, id=4, mimeType=video/avc, bitrate=230000, codecs=avc1.4D401F, res=284x160, fps=30.0, supported=YES
]

```

**Comment by tonihei** [comment] 2023-01-25 09:26
@S0und : This is working as intended from the library because the two mentioned devices don't reliably support 60fps playback according to the device itself. The previous ExoPlayer versions just didn't check the capabilities correctly and hence incorrectly marked the format as supported. We can try to reproduce with the Chromecast with Google TV device and file an internal bug, because it seems to me the device should be able to support 60fps streams. 

You can also manually adjust the selection with `TrackSelectionParameters`. For example, you can specify `TrackSelectionOverride` to directly select tracks or you could force 60fps by setting `setMinVideoFrameRate(60)`.

**Comment by S0und** [comment] 2023-01-26 08:20
@tonihei Thanks for your answer!

**Comment by tonihei** [comment] 2023-02-27 10:38
We haven't got any good indication if and when the Chromecast device bug can be fixed. I'm going to add a workaround for this device and the Lenovo M10 FHD Plus instead.

**Comment by S0und** [comment] 2023-02-27 12:02
@tonihei I still think it would be great if we could control this "obey device supported max resolution/framerate" behavior because if a manufacturer didn't set up the device correctly - even tho the device hardware is capable of higher resolution/framerate - the player will play the lowest quality. If that's the case, we could still command the player to ignore the hardware specifications and try to play the highest quality anyway. Since there are probably more devices with incorrect hardware settings, there is no way to test and add all of them to Exoplayer.

**Comment by tonihei** [comment] 2023-02-27 13:59
@S0und  Are you looking for a parameter that forces the track selector to always exceed renderer capabilities when selecting tracks? We already have `exceedRendererCapabilitiesIfNecessary` (true by default) that allows to use a single track to exceed capabilities, but only if no other fully supported track can be found. I guess you are looking more for a `allowExceedingRendererCapabilities`. Note that this may be quite hard to use in a generic way because it would then always assume support even if the media contains formats far exceeding capabilities (let's say 8K@120fps). It's not really scalable for any app to verify that this actually works for a set of formats. That's the reason we generally rely on device reported capabilities and only add workaround/exceptions for cases where we have a good reason to change it. 

Alternatives are:
 - Manually override any selection by specifying `TrackSelectionOverride`s. 
 - Turn on `allowVideoMixedDecoderSupportAdaptiveness` to also select tracks that are officially only support by secondary codecs. (This would work on the Chromecast for example). 
 - Force 60fps by setting `setMinVideoFrameRate(60)`. 
 - Customize video selection to your needs by overriding `DefaultTrackSelector.selectVideoTrack`, call the `super` method first and then update the list of track indices in the returned `ExoTrackSelection.Definition` to your liking.
 - Customize renderer support logic by overriding `MediaCodecVideoRenderer.supportsFormat` and then for example always setting `FORMAT_HANDLED` for specific resolutions or frame rates.

**Comment by jonas-coded** [comment] 2023-03-22 13:43
I also have a problem with this on my Samsung Galaxy Tab A7 (SM-T500, Android 12). ExoPlayer reports that tracks in 1080p with a frame rate >30 FPS are exceeding the device capabilities, although I could not see any issues while force playing 60 FPS in the demo app. I came across this issue because the app from my IPTV provider (https://play.google.com/store/apps/details?id=de.telekom.entertaintv.smartphone) has an issue playing specific videos in HD since around a year and also uses ExoPlayer.

**Comment by tonihei** [comment] 2023-03-22 15:26
> has an issue playing specific videos in HD since around a year and also uses ExoPlayer.

This must be unrelated to the issue above, because the code has only been released 4 months ago.

If the device reports that it doesn't support a certain frame rate and you think it should mark it as supported, it's actually best to report this to the device manufacturer itself. The only scalable way to track support for formats across all devices is to let devices declare their level of support directly, because we can't possibly maintain a separate set of supported formats for all devices.

**Comment by tidoemanuele** [comment] 2023-09-13 18:46
@tonihei Thank you for the comprehensive explanation of the codec support check in version 2.18.2. 
I own a tablet TECLAST P20HD, and when I check its video capabilities using the "**getSupportedWidthsFor(720)**" function, the response is: "videoCapabilities: [2, 1024]." 
This means that with the latest player version, it may not be possible to play videos at 1280x720@25 resolution. 
However, if I include it in the "needsIgnorePerformancePointsWorkaround" function, the video plays smoothly at 1280x720@25fps.

I understand the concept of using video capabilities to filter out certain video tracks, but it would be beneficial if the player exhibited some flexibility. For instance, if the device indicates support for **1024x720@25**, it might also be capable of handling **1280x720@25**  (this is the case of the TECLAST). During playback, the player could continuously monitor the vfpo (visual frame presentation offset) value and exclude that track if vfpo consistently reports negative values.

**Comment by tonihei** [comment] 2023-09-13 20:39
> but it would be beneficial if the player exhibited some flexibility

@tidoemanuele How would you implement this logic exactly?  ExoPlayer already attempts to exceed the capabilities if the no fully compatible track available. But it's hard to define a logic that works in all cases and to scale well to all devices we really have to rely on reported capabilities.

**Comment by tidoemanuele** [comment] 2023-09-13 23:01
> @tidoemanuele How would you implement this logic exactly? 

ExoPlayer already incorporates a similar approach by rounding down the frame rate. 

My suggestion is to introduce a level of tolerance to the parameters: width, height, and framerate. To illustrate, consider the following code example with tolerance adjustments, which would grant the TECLAST P20HD and others the capability to play content at 1280x720@25fps while still rejecting potentially too higher resolutions like 1280x720@60fps or 1920x1080@25fps.

```
PerformancePoint targetPerformancePoint =
          new PerformancePoint(width - (width * 0.25), height - (height * 0.05), (int) frameRate - (frameRate * 0.05));

```

**Comment by tonihei** [comment] 2023-09-15 14:38
I agree in principle that there is likely some room for tolerance, but it's unfortunately not clear how to set it. To make your example work, we'd need to apply 25% tolerance, which is a lot. Codecs can reasonably fail if the formats exceed the maximum size, so exceeding the declared maximum by 25% already feels quite excessive. 

> ExoPlayer already incorporates a similar approach by rounding down the frame rate

This is true, but this is within integer rounding errors (2-3% tolerance max) and the frame rate is more complicated to define accurately than the resolution (in particular if the stream declares its effective frame rate based on actual timestamps, that may very slightly exceed the expected value, like 30.002 instead of 30.0). 

The interesting remaining question is then: What can you as an app do to explicitly exceed the capabilities if you want to? 

If you'd like to customize the logic around which format is support by the renderer/decoders, the best way is probably to override `MediaCodecVideoRenderer.supportsFormat` to add additional logic:

```
@Override
protected @Capabilities int supportsFormat(
    MediaCodecSelector mediaCodecSelector, Format format) 
        throws MediaCodecUtil.DecoderQueryException {
  @Capabilities int support = super.supportsFormat(mediaCodecSelector, format);
  if (RendererCapabilities.getFormatSupport(support) == C.FORMAT_HANDLED) {
    return support;
  }
  // Try again with lower resolution.
  Format lowerResFormat = 
      format.buildUpon()
          .setWidth(format.width * 4 / 5)
          .setHeight(format.height * 4 / 5)
          .build();
  return super.supportsFormat(mediaCodecSelector, lowerResFormat);
}
```

I'll close this issue now too because the original device-specific problem has been addressed.

**Closed as completed by tonihei** 2023-09-15 14:38 UTC
Labels: bug: device specific

**Comment by tidoemanuele** [comment] 2023-09-15 16:43
@tonihei thank you for helping us enhance the resilience of our app without compromising the player integrity. We truly appreciate your assistance.
