### ISSUE TITLE
Live audio plays only first segment from 2.12.x version

### ISSUE THREAD

**Issue by cruiz666** [google/ExoPlayer#9128] opened 2021-06-28 22:50 UTC
I'll send example and url to reproduce the issue via mail. Thanks

**Comment by kim-vde** [comment] 2021-06-29 16:48
I have just requested access on the file you provided.

**Comment by cruiz666** [comment] 2021-06-29 17:10
Done!

**Comment by kim-vde** [comment] 2021-06-30 09:21
I can reproduce by trying the stream URI in the demo app. It is working in 2.12.3 but not in dev-v2. The content is live HLS. Can you have a look @christosts ?

**Comment by christosts** [comment] 2021-07-27 16:57
@cruiz666, please grant me access to the file too

**Comment by cruiz666** [comment] 2021-07-27 17:12
@christosts, done!

**Comment by christosts** [comment] 2021-07-28 15:32
This is a duplicate of #9153 - please track that issue for updates.

**Closed as completed by christosts** 2021-07-28 15:32 UTC
Labels: bug
