### ISSUE TITLE
Failed to resolve - com.google.android.exoplayer:exoplayer-core:2.8.3

### ISSUE THREAD

**Issue by PatilManoj1717** [google/ExoPlayer#5228] opened 2018-12-10 06:27 UTC
Failed to resolve: com.google.android.exoplayer:exoplayer-core:2.8.3
Install Repository and sync project
Open File
Show in Project Structure dialog

Failed to resolve: com.google.android.exoplayer:exoplayer-dash:2.8.3
Install Repository and sync project
Open File
Show in Project Structure dialog

**Comment by nambv** [comment] 2018-12-10 07:58
I meet this problem too, but I haven't add exoplayer gradle dependences in my project yet. Can you take a look?

**Comment by KimiChiu** [comment] 2018-12-10 08:27
Same here. Some of the ad network sdks uses these libraries in my app.
But then it starts showing this error after I upgraded to gradle plugin 3.2.1.

**Comment by nambv** [comment] 2018-12-10 08:29
I used facebook sdk audience network in my project, too

@PatilManoj1717 @KimiChiu solved by adding:

```maven { url 'https://google.bintray.com/exoplayer/' }``` 

into repositories:

```
repositories {
        google()
        jcenter()
        maven { url 'https://google.bintray.com/exoplayer/' }
    }
```

**Comment by KimiChiu** [comment] 2018-12-10 08:34
@nambv Great! This works too. `maven { url 'http://repo.spring.io/libs-release/' }`
Found it from here, [https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer/2.8.3](https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer/2.8.3)

**Comment by ojw28** [comment] 2018-12-10 08:47
Duplicate of #5225

**Closed as completed by ojw28** 2018-12-10 08:47 UTC

**Comment by kesha-antonov** [comment] 2018-12-10 21:30
> I used facebook sdk audience network in my project, too
> 
> @PatilManoj1717 @KimiChiu solved by adding:
> 
> `maven { url 'https://google.bintray.com/exoplayer/' }`
> 
> into repositories:
> 
> ```
> repositories {
>         google()
>         jcenter()
>         maven { url 'https://google.bintray.com/exoplayer/' }
>     }
> ```

thanks!

**Comment by sabiou** [comment] 2018-12-11 00:51
Thanks ! got this issue after upgrading to Android Studio 3.3 preview

**Comment by ojw28** [comment] 2018-12-11 00:53
Please see the duplicate issue ref'd above.
