### ISSUE TITLE
play video failed when switched between two page, sometimes

### ISSUE THREAD

**Issue by duduniao** [google/ExoPlayer#4523] opened 2018-07-17 09:02 UTC
devices: samsung galaxy s7 sm-g930s ,  lib version: 2.8.2

```
07-17 18:25:45.742 20152-22029/caller.live.screen.callscreen E/Surface: IGraphicBufferProducer::setBufferCount(1) returned Invalid argument
07-17 18:25:45.742 20152-22029/caller.live.screen.callscreen E/ACodec: native_window_set_buffer_count failed: Invalid argument (22)
07-17 18:25:45.744 20152-22026/caller.live.screen.callscreen E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1954)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:915)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:405)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:372)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:861)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:829)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:811)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:328)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by ojw28** [comment] 2018-07-17 11:03
Please provide all of the information requested in the issue template. There's not much we can do to investigate this without clear reproduction steps and a proper bug report.

**Comment by ojw28** [comment] 2018-07-24 13:41
Closing due to lack of information. If you're able to provide the information in the issue template, please respond with it here and we'll re-open the issue.

**Closed as completed by ojw28** 2018-07-24 13:41 UTC
Labels: need more info
