### ISSUE TITLE
When switching HLS tracks stream frozes

### ISSUE THREAD

**Issue by JanKokalj** [google/ExoPlayer#546] opened 2015-06-15 13:03 UTC
Hi, I found a bug (on dev branch) when you switch HLS video or audio tracks the player stops. Tested on apple hls streams (nexus 6).

I narrowed it down to merge commit c992d9c on dev branch.

**Comment by ojw28** [comment] 2015-06-15 13:15
That change didn't modify anything related to HLS. Are you sure that's the correct commit?

**Comment by JanKokalj** [comment] 2015-06-16 05:20
Yes, before this merge commit the demo was working fine.

**Comment by ojw28** [comment] 2015-06-16 11:47
Do you mean when you manually switch the tracks (e.g. by selecting a different track in the demo app)? If so then yes, I can reproduce that. Looks like the issue was introduced in b806109cfd63f4aedf19f388c1091b81f61bead2 rather than the commit you reference.

**Comment by JanKokalj** [comment] 2015-06-16 11:51
Yes, this occurs when manually switching tracks and sorry for the wrong commit reference.

**Comment by ojw28** [comment] 2015-06-16 12:51
Should be fixed by ecf7d1be9e68d665bb61d1b43b3daec0933e0ddd. Thanks for the report!

**Closed by ojw28** 2015-06-16 12:51 UTC
Labels: bug
