### ISSUE TITLE
Garbled Slow Audio

### ISSUE THREAD

**Issue by haydenkaizeta** [google/ExoPlayer#10536] opened 2022-08-18 21:36 UTC
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

- Pixel 6 running Android 12
- Pixel 4 XL running Android 12

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play attached media in the demo app
2. Slow to 0.5x

### Expected result

1. Audio quality matches other available players, such as youtube, or Elmedia Video Player (macOS)

### Actual result

1. Audio quality is garbled, numerous artifacts from the slow speed.

### Media

https://c10.patreonusercontent.com/4/patreon-media/p/post/70286733/402c5694b4a0479aab412edf7c9c2b8d/eyJhIjoxLCJwIjoxfQ%3D%3D/1.mp3?token-time=1660953600&token-hash=lZVhJemCGBFQV1LSH1MS3ayHgLbhZJvlEuBynO_1sjQ%3D

(this url will expire)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by haydenkaizeta** [comment] 2022-08-18 21:37
Github does not allow mp3 uploads and I have not yet tried to reproduce after transforming the file. The above url will work for a short time or I can share the mp3 through another method

**Comment by moneytoo** [comment] 2022-08-19 09:05
Github will accept that mp3 if you put it in a zip archive. ;-)

**Comment by rohitjoins** [comment] 2022-08-19 14:55
[lit.mp3.zip](https://github.com/google/ExoPlayer/files/9383090/lit.mp3.zip)
Attached mp3 audio file.

**Comment by haydenkaizeta** [comment] 2022-08-31 18:42
Hello, what's the expected timeline to get this checked out? Any additional information needed?

**Comment by tonihei** [comment] 2022-09-06 10:57
I just tested the attached mp3 file (from @rohitjoins's comment above) and it plays perfectly fine without any problems on a Pixel 4 on the latest code state. Is this the same file you uploaded and have problems with?

**Comment by haydenkaizeta** [comment] 2022-09-09 18:20
It is. Did you play it in a slowed state (0.5x) on the code available in the (2.17.1) sample app? A side by side with another audio player shows that it is clearly worse and my team has repro'd on a few devices

**Comment by tonihei** [comment] 2022-09-16 05:01
Sorry, I didn't fully realize that changing the playback speed was part of the reproduction steps.

The reason is simply that the library we are using for time-stretching (Sonic) was written for spoken content like podcasts and may not perform very well for music. If you know or have another speed adjustment library for audio data that works well for music, please let us know and we can see if it's feasible to use that instead. Otherwise I will just close this as infeasible. We also have #6575 that tracks finding an alternative library that performs time stretching for music well.

**Closed as completed by tonihei** 2022-09-16 05:01 UTC
Labels: duplicate, wont fix: infeasible

**Comment by haydenkaizeta** [comment] 2022-09-19 19:03
Ok good to know, I assume not many are slowing down music so this should be fine for now
