### ISSUE TITLE
How do play local videos with Exoplayer 

### ISSUE THREAD

**Issue by Suleiman-Ahmad** [google/ExoPlayer#9599] opened 2021-10-24 04:42 UTC
How can I use Exoplayer to play local videos gotten from the Mediastore. All code samples regarding to Exoplayer I've seen were only on streaming videos not playing locally. I've also searched and asked on stackoverflow.com but unfortunately no useful results.
I just need a proper code sample to get started.
Thank you.

**Comment by Suleiman-Ahmad** [comment] 2021-10-25 04:23
I need your assistance please. Someone should reply

**Comment by ojw28** [comment] 2021-10-26 15:17
This is mostly a question about Android storage. The [documentation about storage](https://developer.android.com/training/data-storage/shared/media) explains how to request the necessary permissions, and also how to build a content URI for an entry in the media store, by appending the ID with `ContentUris.withAppendedId`.

Once you have the necessary permissions and URI, you should be able to play it in `ExoPlayer` just like you'd play any other URI, by using `MediaItem.fromUri` and then passing the generated `MediaItem` to the player.

It's unclear which step you're stuck on, but you should work through the documentation linked above until you're able to read the media file bytes directly from a generated content URI in your own application code. Once you've got that far, the ExoPlayer specific step should be as simple as replacing the code you've added to actually read the media file bytes, with code that builds a `MediaItem` from the content URI and passes it to the player (which should then be able to read and play the media file).

**Comment by Suleiman-Ahmad** [comment] 2021-10-27 07:25
My issue is that it plays some local videos correct but not others.
It gives a different (very large) duration to other videos eg 1:20:56
becomes 99:58:34. And this messes up everything.

I give a detailed explanation in
https://github.com/google/ExoPlayer/issues/9593 but none of you have
responded yet. Please go through this issue, it's the only thing delaying
me right now. Thank you.

**Comment by Suleiman-Ahmad** [comment] 2021-10-27 07:30
Please go through https://github.com/google/ExoPlayer/issues/9593
That's the only issue I have right now.

**Comment by ojw28** [comment] 2021-10-27 08:14
Closing as a duplicate of https://github.com/google/ExoPlayer/issues/9593.

**Closed as completed by ojw28** 2021-10-27 08:14 UTC
Labels: duplicate, question
