### ISSUE TITLE
Provide a way to dynamically enable/disable seeking

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#8836] opened 2021-04-20 15:42 UTC
I am using DAI with ExoPlayer and IMA.

As you can see from the video..when an Ad is playing I can scrub on `TimeBar` even though I call `setEnabled(false)` on it.
From the `DefaultTimeBar` implementation,

```java
 @Override
  public void setEnabled(boolean enabled) {
    super.setEnabled(enabled);
    if (scrubbing && !enabled) {
      stopScrubbing(/* canceled= */ true);
    }
  }
```

`scrubbing` flag prevents `TimeBar` to stop scrubbing.

I would like to achieve no scrubbing on the time bar. What should I do? 

https://user-images.githubusercontent.com/32653955/115424499-c37bc180-a1cc-11eb-9dbd-3227aa024a86.mp4

**Comment by ojw28** [comment] 2021-04-20 17:30
From the video, it looks like this is a custom UI, so it's unclear why this is an ExoPlayer issue. `DefaultTimeBar` disables scrubbing by checking `isEnabled()` in various places and preventing scrubbing from taking place if `false` is returned. Your custom UI component(s) would need to do something equivalent to that.

If you can reproduce this with standard ExoPlayer UI components, then please let us know. If you cannot then this seems like an issue with your custom UI components, which falls outside the scope of this issue tracker.

**Comment by nishantkp** [comment] 2021-04-20 18:31
Hi @ojw28,

I am able to produce it in IMA-DAI's Advanced example and I have also attached a file.

You can check the below method in `SampleVideoPlayer` class.

```java
 public void setCanSeek(boolean canSeek) {
}
```

[IMAAdvancedExample.zip](https://github.com/google/ExoPlayer/files/6345863/IMAAdvancedExample.zip)

**Comment by ojw28** [comment] 2021-04-20 19:25
Is that a modified version of the IMA-DAI example? I tried with the official version [available here](https://github.com/googleads/googleads-ima-android-dai/tree/master/AdvancedExample), and I did not see the problematic behaviour because they hide the controller whilst ads are playing.

Digging around with  `((DefaultTimeBar)activity.findViewById(R.id.exo_progress)).setEnabled(canSeek);` isn't going to work, because `PlayerControlView` that owns the `DefaultTimeBar` is also calling `setEnabled` on the same view. It does this based on whether the media content being played is seekable, which it is.

I don't think there is a good way of disabling scrubbing at the UI level currently, when using `PlayerView` or `PlayerControlView`. You'd probably have to fork the UI components and edit them directly to get exactly what you want. That said, this more or less works as a hack:

```
public void setCanSeek(boolean canSeek) {
  this.canSeek = canSeek;
  if (canSeek) {
    ((DefaultTimeBar) activity.findViewById(R.id.exo_progress)).showScrubber();
  } else {
    ((DefaultTimeBar) activity.findViewById(R.id.exo_progress)).hideScrubber(false);
  }
}
```

We're currently working on changes that will allow the player to specify which commands are currently enabled for use, that the UI components will query. We will also provide a `ForwardingPlayer` that makes it easy to disable commands that the underlying player would otherwise indicate as being available. This will provide a good solution to this problem. I'll leave it open as an enhancement to track implementing this.

**Comment by ojw28** [comment] 2021-04-20 19:52
Assigning to @christosts since I think this will be solved by `ForwardingPlayer`.

**Comment by ojw28** [comment] 2021-09-07 14:37
@kim-vde and @christosts (not sure who): Is this something that we support now? If so, could we provide a code snippet and close this? Thanks!

**Comment by kim-vde** [comment] 2021-09-07 15:35
Yes.

To disable seekbar scrubbing, you can make command `COMMAND_SEEK_IN_CURRENT_WINDOW` unavailable by wrapping the player passed to the `(Styled)PlayerView` in a `ForwardingPlayer`:

```java
ForwardingPlayer forwardingPlayer =
    new ForwardingPlayer(player) {
      @Override
      public boolean isCommandAvailable(int command) {
        if (command == COMMAND_SEEK_IN_CURRENT_WINDOW) {
          return false;
        }
        return super.isCommandAvailable(command);
      }

      @Override
      public Commands getAvailableCommands() {
        return super.getAvailableCommands()
            .buildUpon()
            .remove(COMMAND_SEEK_IN_CURRENT_WINDOW)
            .build();
      }
    };
playerView.setPlayer(forwardingPlayer);
```

**Closed as completed** 2021-09-07 15:36 UTC
Labels: enhancement
