### ISSUE TITLE
Encrypted Playback Cache causing downloaded content to fail

### ISSUE THREAD

**Issue by NathanSass** [google/ExoPlayer#8674] opened 2021-03-04 01:03 UTC
Issue:
-------------------------
When I implemented a cache for playback it broke playing downloads. Downloads still appear to complete but when I try to play them, playback fails. When I remove the encryption components, it functions as expected.

How can I resolve this to play downloaded encrypted content?

Thank you! I would be so grateful for any help.

Searched Documentation and Existing issues:
-------------------------
- [#6231](https://github.com/google/ExoPlayer/issues/6231)

Reproduction steps:
-------------------------
Fork: https://github.com/NathanSass/ExoPlayer/tree/nathans
Diff: https://github.com/google/ExoPlayer/pull/8673/files

- Clone fork
- Open demo app
- go to content ( Nathan -> Mp3 )
- play content ( Works as expected)
- Go back 
- Download content
- Download completes
- Play Content ( Playback Fails) 

Stack Trace:
-------------------------

```
2021-03-03 16:22:44.459 15576-15704/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (Mp3Extractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1026)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-03-03 16:22:44.460 15576-15576/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=0.57, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (Mp3Extractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1026)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    ]
2021-03-03 16:22:44.460 15576-15576/com.google.android.exoplayer2.demo E/NATHAN: com.google.android.exoplayer2.ExoPlaybackException: Source error

```

Device and Versions:
-------------------------
- ExoPlayer version number 2.13.2
- Android version 11
- Android device Pixel 3

**Comment by krocard** [comment] 2021-03-04 07:05
@icbaker can you take a look at this drm offload playback issue?
Note that this has been discussed multiple time recently: #7347 and #7202.

**Comment by icbaker** [comment] 2021-03-04 09:15
The provided source code example is using AES encryption, not DRM (i.e. MediaDrm).

This looks more like a caching/downloading question - assigning to @marcbaechinger.

(@NathanSass providing a fork to repro the problem is **really** helpful, thanks for that! But fyi you don't need to file a PR in order for us to view the diff, we can do it directly from this URL: https://github.com/NathanSass/ExoPlayer/compare/nathans)

**Comment by ojw28** [comment] 2021-04-01 12:12
This is just a bug in your application code, [here](https://github.com/NathanSass/ExoPlayer/blob/nathans/demos/main/src/main/java/com/google/android/exoplayer2/demo/CacheManager.java#L20) and [here](https://github.com/NathanSass/ExoPlayer/blob/nathans/demos/main/src/main/java/com/google/android/exoplayer2/demo/CacheManager.java#L32). `setCacheReadDataSourceFactory` sets the `DataSource` for reading a file from the cache. It's not supposed to include any kind of fallback to upstream. Note that falling back to upstream is already handled by setting the upstream via `setUpstreamDataSourceFactory`.

The correct argument to pass to `ExoplayerEncryption.dataSourceFactory` on these two lines is `new FileDataSource.Factory()`, and doing so fixes playback. Note that you could also just move this directly into your `ExoplayerEncryption.dataSourceFactory` implementation; there's no need for it to be passed as an argument.

**Closed as completed by ojw28** 2021-04-01 12:12 UTC
Labels: wont fix: app issue
