### ISSUE TITLE
Software codec supported in Exoplayer

### ISSUE THREAD

**Issue by Kaviya-M** [google/ExoPlayer#10705] opened 2022-10-19 08:44 UTC
In exoplayer documentation [https://exoplayer.dev/supported-formats.html] only able to view exoplayer supported media formats.
Any idea/ API's  that we can use to list out the software codec that is supported in Exoplayer?

**Comment by christosts** [comment] 2022-10-19 16:51
Closing, I assume this is a duplicate of #10703

**Closed as completed by christosts** 2022-10-19 16:51 UTC
Labels: duplicate, question
