### ISSUE TITLE
Decoder failed: c2.android.avc.decoder

### ISSUE THREAD

**Issue by DragonSpirit** [google/ExoPlayer#10576] opened 2022-09-02 08:42 UTC
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Android emulator, sdk 30, arm64-v8a, Mac m1

### Devices that do not reproduce the issue

Android emulator, sdk 31, arm64-v8a, Mac m1

### Reproducible in the demo app?

Yes

### Reproduction steps

- Open main demo app
- Pick video
- Pause video
- Wait few seconds (up to 5)

### Expected result

Pause works properly, remaining paused until the play button is pressed

### Actual result

Got playback error
<details>

<summary>stacktrace</summary>

```2022-09-02 11:31:06.656 15358-15430/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0x80000000, actionCode 0, while in state 6
2022-09-02 11:31:07.471 15358-15411/com.google.android.exoplayer2.demo E/MediaCodecVideoRenderer: Video codec error
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-09-02 11:31:07.474 15358-15411/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(4, null, null, video/avc, avc1.64002A, 18320008, null, [1920, 856, 24.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2022-09-02 11:31:07.476 15358-15411/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2298)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:166)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:870)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:710)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:561)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1651)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1392)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1355)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:582)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-09-02 11:31:07.496 15358-15358/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=31.19, mediaPos=22.78, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(4, null, null, video/avc, avc1.64002A, 18320008, null, [1920, 856, 24.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1190)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
```
</details>

### Media

Widevine DASH (MP4, H264) HD (cenc) from demo app

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-09-02 08:59
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/10485 - I believe it's an emulator problem, though I was unable to reproduce it on an x86-based emulator, so I suspect it might be related to the arm-based emulator.

Do you have an x86 environment available where you could try and reproduce? That would add strength to this theory.

**Comment by DragonSpirit** [comment] 2022-09-02 10:20
Yep, I do.
I tried to reproduce it on x86_64 image on intel based mac and can't reproduce this issue

**Comment by giladna** [comment] 2022-09-04 19:20
@icbaker  we had such issue some time ago on Pixel3 Android 11 and we had some thoughts implementing the below code for specific devices

we got such errors 

11-30 13:48:03.421 3378 21485 E OMXNodeInstance: getConfig(0xf03685d0:amlogic.avc.decoder.awesome2.secure, ??(0x7f00000c)) ERROR: UnsupportedSetting(0x80001019)



11-30 14:12:30.116 3378 21485 E OMXNodeInstance: setConfig(0xf03685d0:amlogic.avc.decoder.awesome2.secure, ConfigOperatingRate(0x6f800003)) ERROR: UnsupportedIndex(0x8000101a)
11-30 14:12:30.116 20755 556 I ACodec : codec does not support config operating rate (err -1010)


* example for removal of such decoder

```
renderersFactory.setMediaCodecSelector((mimeType, requiresSecureDecoder, requiresTunnelingDecoder) -> {
List<MediaCodecInfo> codecsList =  new ArrayList<>(MediaCodecUtil.getDecoderInfos(mimeType, requiresSecureDecoder, requiresTunnelingDecoder));
ListIterator<MediaCodecInfo> iter = codecsList.listIterator();
while(iter.hasNext()){
String name = iter.next().name;
if(name.startsWith("OMX.google") || name.startsWith("c2.android")) {
iter.remove();
}
}
return  codecsList;
});

```

**Comment by icbaker** [comment] 2022-09-21 16:47
Given that this only reproduces on the arm emulator, I recommend you file a bug against the emulator as described: https://developer.android.com/studio/report-bugs#emulator-bugs

I'm going to close this, because I don't think there's any change expected/needed in the library here.

**Closed as completed by icbaker** 2022-09-21 16:47 UTC
Labels: bug: in platform

**Comment by gb103** [comment] 2022-10-05 18:50
I can reproduce this issue on Realme C11 2021 device easily, whenever I pause the video, in next 5 seconds Decoder failed error comes. it is similar to https://github.com/google/ExoPlayer/issues/10485

Here are the logs attached.

[live_issue.txt](https://github.com/google/ExoPlayer/files/9718218/live_issue.txt)

**Comment by icbaker** [comment] 2022-10-06 09:08
@gb103 Looks like a duplicate of #9256.
