### ISSUE TITLE
play local encrypt flac file (AES/OFB/NoPadding ) fail

### ISSUE THREAD

**Issue by FlogFly** [google/ExoPlayer#10144] opened 2022-04-01 08:24 UTC
I have a local flac encrypted file. So I use the local encrypted file to encrypt the entire file with Cipher and save it to the local to generate a decrypt.flac file, it can be played smoothly by playing it directly with the FileDataSource.
```
private void cipherByAesOfbNoPadding(String fileName, String encryptedFileName, int opmode) {
        try (
                FileInputStream in = new FileInputStream(fileName);
                BufferedOutputStream out = new
                        BufferedOutputStream(new
                        FileOutputStream(encryptedFileName), 1024 * 1024 * 8);) {
            Cipher cipher = Cipher.getInstance("AES/OFB/NoPadding");
            byte[] keyValue = keyVal.getBytes();
            SecretKeySpec encryKey = new SecretKeySpec(keyValue, "AES");
            IvParameterSpec iv = new IvParameterSpec(ivVal.getBytes());
            cipher.init(opmode, encryKey, iv);
            byte[] buffer = new byte[bufferSize];
            int n = 0;
            while ((n = in.read(buffer)) != -1) {
                byte[] encryptedInput = cipher.doFinal(buffer);
                out.write(encryptedInput, 0, n);
            }
            out.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

But now I want to directly read and decrypt the encrypted file and play it, but it can't be successful。Currently, according to the knowledge in the issues, I use a custom FileDataSource:

```
public final class CustomFileDataSource extends BaseDataSource {

    ............
    ............
    ............
    

    private long bytesRemaining;
    Cipher cipher;
    CipherInputStream cipherInputStream;
    FileInputStream fileInputStream;


    @Override
    public long open(DataSpec dataSpec) throws com.google.android.exoplayer2.upstream.FileDataSource.FileDataSourceException {

        try {
            cipher =  Cipher.getInstance("AES/OFB/NoPadding");

        } catch (NoSuchAlgorithmException | NoSuchPaddingException e) {
            throw new RuntimeException(e);
        }

        Key cipherKey = new SecretKeySpec("xxxxxx".getBytes(), "AES");
        IvParameterSpec cipherIV = new IvParameterSpec("yyyyyy".getBytes());

        try {
            cipher.init(Cipher.DECRYPT_MODE, cipherKey, cipherIV);
        } catch (InvalidKeyException | InvalidAlgorithmParameterException e) {
            throw new RuntimeException(e);
        }


        File filex = new File(dataSpec.uri.getPath());
        try {
            fileInputStream = new FileInputStream(filex);
            cipherInputStream =  new CipherInputStream(fileInputStream, cipher);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        try {
            bytesRemaining =
                    dataSpec.length == C.LENGTH_UNSET ? filex.length() - dataSpec.position : dataSpec.length;
        } catch (IOException e) {
            throw new com.google.android.exoplayer2.upstream.FileDataSource.FileDataSourceException(e, PlaybackException.ERROR_CODE_IO_UNSPECIFIED);
        }
        if (bytesRemaining < 0) {
            throw new com.google.android.exoplayer2.upstream.FileDataSource.FileDataSourceException(
                    /* message= */ null,
                    /* cause= */ null,
                    PlaybackException.ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE);
        }

        return bytesRemaining;
    }

    @Override
    public int read(byte[] buffer, int offset, int length) throws com.google.android.exoplayer2.upstream.FileDataSource.FileDataSourceException {


        if (length == 0) {
            return 0;
        } else if (bytesRemaining == 0) {
            return C.RESULT_END_OF_INPUT;
        } else {
            int bytesRead = 0;
            try {

                int bytesToRead = (int) Math.min(bytesRemaining, length);
                try {
                    bytesRead = cipherInputStream.read(buffer, offset, bytesToRead);
                }catch (Exception e) {
                    throw new com.google.android.exoplayer2.upstream.FileDataSource.FileDataSourceException(e, PlaybackException.ERROR_CODE_IO_UNSPECIFIED);
                }
                if (bytesRead > 0) {
                    bytesRemaining -= bytesRead;
                    bytesTransferred(bytesRead);
                }

                return bytesRead;
            }
        }
    }

    ................
    ................
   
}
```
I used cipherInputStream to read, but the current phenomenon is that the read method is constantly being called, and the content of cipherInputStream is read into the byte group of buffer, but no sound is played. I compared and played the entire decrypted file（decrypt.flac）, and decrypting this encrypted file while reading, the content of the byte group that distinguishes read is not the same。

So is my custom FileDataSource written wrong? I see that others have written it like this.

**Comment by icbaker** [comment] 2022-04-01 10:00
I'm afraid we don't have the resources to review custom code like this by hand, however we have some automated tests you can wire up to test a custom `DataSource` implementations, you can find more details here: https://medium.com/google-exoplayer/standardising-datasource-implementations-through-testing-b7a8ab04f8d1

-----

That said, this looks suspicious (it may not be the cause of your problems though):

```
File filex = new File(dataSpec.uri.getPath());
try {
  fileInputStream = new FileInputStream(filex);
  cipherInputStream =  new CipherInputStream(fileInputStream, cipher);
} catch (FileNotFoundException e) {
  e.printStackTrace();
}
```

If the file doesn't exist then `DataSource#open()` should throw an exception, so you should probably change the `e.printStackTrace()` call to something that will throw an exception and halt execution. I haven't worked through exactly what the impliciations are of continuing execution as you currently do, but `File#length()` will return `0` (and not throw) if a file isn't found, which will likely mess up the maths on this line:
```
bytesRemaining =
    dataSpec.length == C.LENGTH_UNSET ? filex.length() - dataSpec.position : dataSpec.length;
```

**Comment by FlogFly** [comment] 2022-04-02 07:32
@icbaker   _Thanks for the answer.I did not describe in detail enough above, so I will give a complete description here.

I have two questions：one is Play the entire file after decryption, the other  is  play while decrypting。_


**First :  decrypt the entire file :** 

I have a 106M music file encrypted by AES/OFB/NoPadding. I want to decrypt the whole file and then generate an unencrypted file to play.

I first decrypt the entire file:



use ``decryptedFileByAesOfbNoPadding``  method The file decrypted by this method is problematic。The generated decrypted file cannot be played after it is taken out (using the FileDataSource that comes with exoplayer)
```
 public void decryptedFileByAesOfbNoPadding(String encryptedFileName, String decryptedFileName) throws Exception {
        FileInputStream fis = new FileInputStream(encryptedFileName);
        FileOutputStream fos = new FileOutputStream(decryptedFileName);
        SecretKeySpec key = new SecretKeySpec("xxxxxxx".getBytes(), "AES");
        IvParameterSpec iv = new IvParameterSpec("yyyyyyy".getBytes());
        Cipher cipher = Cipher.getInstance("AES/OFB/NoPadding");
        cipher.init(cipher.DECRYPT_MODE, key, iv);
        CipherInputStream cis = new CipherInputStream(fis, cipher);
        byte[] buffer = new byte[1024 * 2];
        int n = 0;
        while ((n = cis.read(buffer)) != -1) {
            fos.write(buffer, 0, n);
        }
        cis.close();
        fos.close();
    }
```
but use ``cipherByAesOfbNoPadding`` method is ok。The generated decrypted file cant be played after it is taken out (using the FileDataSource that comes with exoplayer)
```
private void cipherByAesOfbNoPadding(String fileName, String encryptedFileName) {
        try {
            FileInputStream in = new FileInputStream(fileName);
            FileOutputStream out = new  FileOutputStream(encryptedFileName);
            Cipher cipher = Cipher.getInstance("AES/OFB/NoPadding");
            byte[] keyValue = "xxxxxxxxx".getBytes();
            SecretKeySpec encryKey = new SecretKeySpec(keyValue, "AES");
            IvParameterSpec iv = new IvParameterSpec("yyyyyyyy".getBytes());
            cipher.init(cipher.DECRYPT_MODE, encryKey, iv);
            byte[] buffer = new byte[1024 * 2];
            int n = 0;
            while ((n = in.read(buffer)) != -1) {
                byte[] encryptedInput = cipher.doFinal(buffer);
                out.write(encryptedInput, 0, n);
            }
            out.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```


Why is there a problem with decrypting with CipherInputStream？？？？




**Second : Decrypt and play again and again:**  

The following is what I wrote custom FileDataSource :

_CustomFileDataSource.java :_
```
import android.net.Uri;
import android.util.Log;

import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.PlaybackException;
import com.google.android.exoplayer2.upstream.BaseDataSource;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DataSpec;
import com.google.android.exoplayer2.upstream.TransferListener;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.Key;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;

import javax.crypto.Cipher;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;

import androidx.annotation.Nullable;

/**
 * @author: dyp
 * @date: 2022/4/2
 * Description:  CustomFileDataSource
 */
public class CustomFileDataSource extends BaseDataSource {

    private long bytesRemaining;

    private Cipher cipher;
    private InputStream inputStream;
    private Uri uri;
    private File file;
    private byte[] tempBytes;

    /**
     * Creates base data source.
     *
     * @param isNetwork Whether the data source loads data through a network.
     */
    protected CustomFileDataSource(boolean isNetwork) {
        super(false);
    }

    @Override
    public long open(DataSpec dataSpec) throws IOException {

        try {

            cipher =  Cipher.getInstance("AES/OFB/NoPadding");
            Key cipherKey = new SecretKeySpec("xxxxxxxx".getBytes(), "AES");
            IvParameterSpec cipherIV = new IvParameterSpec("yyyyyyyyyy".getBytes());
            cipher.init(Cipher.DECRYPT_MODE, cipherKey, cipherIV);

        } catch (NoSuchAlgorithmException | NoSuchPaddingException e) {
            throw new RuntimeException(e);
        }catch (InvalidKeyException | InvalidAlgorithmParameterException e) {
            throw new RuntimeException(e);
        }

        uri = dataSpec.uri;
        try {

            file = new File(dataSpec.uri.getPath());
            FileInputStream fileInputStream = new FileInputStream(file);
            inputStream =  fileInputStream;

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        try {
            bytesRemaining =
                    dataSpec.length == C.LENGTH_UNSET ? file.length() - dataSpec.position : dataSpec.length;
        } catch (Exception e) {
            throw new com.google.android.exoplayer2.upstream.FileDataSource.FileDataSourceException(e, PlaybackException.ERROR_CODE_IO_UNSPECIFIED);
        }
        if (bytesRemaining < 0) {
            throw new com.google.android.exoplayer2.upstream.FileDataSource.FileDataSourceException(
                    /* message= */ null,
                    /* cause= */ null,
                    PlaybackException.ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE);
        }

        transferStarted(dataSpec);

        return bytesRemaining;
    }

    @Nullable
    @Override
    public Uri getUri() {
        return uri;
    }

    @Override
    public void close() throws IOException {
        try {
            if(inputStream != null){
                inputStream.close();
                inputStream = null;
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    @Override
    public int read(byte[] buffer, int offset, int length) throws IOException {

        if (length == 0) {
            return 0;
        } else if (bytesRemaining == 0) {
            return C.RESULT_END_OF_INPUT;
        } else {
            int bytesRead = 0;
            try {
                int bytesToRead = (int) Math.min(bytesRemaining, length);

                tempBytes = new byte[buffer.length];

                try {

                    bytesRead = inputStream.read(buffer, offset, bytesToRead);
                    tempBytes = cipher.doFinal(buffer);

                   System.arraycopy(tempBytes,0,buffer,0,tempBytes.length);

                } catch (IOException e) {
                    e.printStackTrace();
                }
            } catch (Exception e) {
                throw new com.google.android.exoplayer2.upstream.FileDataSource.FileDataSourceException(e, PlaybackException.ERROR_CODE_IO_UNSPECIFIED);
            }
            if (bytesRead > 0) {
                bytesRemaining -= bytesRead;
                bytesTransferred(bytesRead);
            }
            return bytesRead;
        }
    }


    public static final class Factory implements DataSource.Factory {

        @Nullable private TransferListener listener;

        public CustomFileDataSource.Factory setListener(@Nullable TransferListener listener) {
            this.listener = listener;
            return this;
        }

        @Override
        public CustomFileDataSource createDataSource() {
            CustomFileDataSource dataSource = new CustomFileDataSource(false);
            if (listener != null) {
                dataSource.addTransferListener(listener);
            }
            return dataSource;
        }
    }
}


```


At present, it can run normally, but there is no sound. I found that it is the``read(byte[] buffer, int offset, int length)`` method. It should be correct when the header stream detects the flac flag bit after first reading and decryption, so you can continue to read, but the subsequent reading After decryption, the content is wrong, so no sound can be played. And after running for a while, the error stops:

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.ParserException: Failed to decode stream metadata
        at com.google.android.exoplayer2.ext.flac.FlacDecoderJni.decodeStreamMetadata(FlacDecoderJni.java:170)
        at com.google.android.exoplayer2.ext.flac.FlacExtractor.decodeStreamMetadata(FlacExtractor.java:204)
        at com.google.android.exoplayer2.ext.flac.FlacExtractor.read(FlacExtractor.java:138)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```


Currently I don't know where is the problem .  Please help me, thank you very much

**Comment by icbaker** [comment] 2022-04-13 16:23
I'm closing this because the question is too general and open-ended, and I'm afraid we don't have the resources to review such large amounts of custom code in order to understand what might be wrong.

**Closed as completed by icbaker** 2022-04-13 16:23 UTC
Labels: question
