### ISSUE TITLE
how to get correct Duration time in exoplayer when url get changed in casting?

### ISSUE THREAD

**Issue by vashisthumesh** [google/ExoPlayer#5030] opened 2018-10-31 10:33 UTC
i have implemented exo-player with chrome cast my problem is when i am changing URL after connecting to cast device i was getting incorrect duration time and the connected sign of the chrome cast not changing to show its connected some how URL is changed. Reproduction steps-

1.open app ,go to the video section and open it.
2.exo-player start with URL,now i am connecting cast with cast icon
3.cast connected,now kill the app ,go to again on videos section
4.i am checking if cast session is available or not using  if(castPlayer?.isCastSessionAvailable!!) suppose session is available then 
5.on selecting another video cast screen comes.but here,i am getting wrong duration time and cast icon not showing connected.
i am using this url 
first url: -http://ondemand.meridix.com/ondemand/134969.mp4/playlist.m3u8(duration is near about 5 hours)
then after chnaging url
second url: -http://ondemand.meridix.com/ondemand/134950.mp4/playlist.m3u8(duration is near about 3 hours)
but when second playing after above step its shows total duration is 5 hours.

**Comment by ojw28** [comment] 2020-01-17 21:34
I can't reproduce this on 2.11.0. Closing for now, but please let us know if this problem still occurs on more recent releases.

**Closed as completed by ojw28** 2020-01-17 21:34 UTC
Labels: bug
