### ISSUE TITLE
Stream crash when selecting textTrack in TTML format 

### ISSUE THREAD

**Issue by AgataZiolkowska** [google/ExoPlayer#10960] opened 2023-02-02 11:40 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Probably any device.

### Reproducible in the demo app?

Yes

### Reproduction steps

I'm using DASH with widevine DRM.

1.  Play stream (which contains text track in ttml format)
2.  Select ttml text track

The issue is not 100% reproducible. Sometimes it takes a few minutes until the crash occurs. 

### Expected result

The stream continues playing. The text track is successfully selected.

### Actual result

Stream crashes. 

`E/EventLogger: playerFailed [6.88]
    com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:621)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at com.google.android.exoplayer2.text.ttml.TtmlSubtitle.getEventTime(TtmlSubtitle.java:62)
        at com.google.android.exoplayer2.text.SubtitleOutputBuffer.getEventTime(SubtitleOutputBuffer.java:53)
        at com.google.android.exoplayer2.text.TextRenderer.getCurrentEventTimeUs(TextRenderer.java:426)
        at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:259)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) `
                                                                                                   	
The issue is not present in the 2.18.1 version. I was checking the demo app with our content which caused the same crash with an identical stacktrace.

### Media

I will send a sample by email.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2023-02-02 15:26
Duplicate of https://github.com/google/ExoPlayer/issues/10867

**Closed as completed by icbaker** 2023-02-02 15:26 UTC
Labels: duplicate
