### ISSUE TITLE
DRM error trying to play DRM protected content on Android TV with Android 12

### ISSUE THREAD

**Issue by axelbau24** [google/ExoPlayer#10498] opened 2022-08-02 19:00 UTC
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

- Any emulator with Android TV API 31 (Android 12)

### Devices that do not reproduce the issue

- Regular phone devices/emulators with Android 12

### Reproducible in the demo app?

Yes

### Reproduction steps

- Launch demo app
- Choose any DRM Widevine content (e.g Widevine DASH (MP4, H265) )
- Choose any quality
- Playback fails with error **ERROR_DRM_UNKNOWN**

### Expected result

Playback should be successful.

### Actual result

Playback failed with error

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:586)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to open session: ERROR_DRM_UNKNOWN
      ============================== Beginning of DRM Plugin Log ==============================
        08-02 18:44:07.204 I found instance=clearkey version=android.hardware.drm@1.4::IDrmFactory
        08-02 18:44:07.204 I found instance=default version=android.hardware.drm@1.0::IDrmFactory
        08-02 18:44:08.478 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
      ============================== End of DRM Plugin Log ==============================
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:544)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.openInternal(DefaultDrmSession.java:387)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:314)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:790)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:690)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:573)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:519)
        at com.google.android.exoplayer2.source.SampleQueue.onFormatResult(SampleQueue.java:926)
        at com.google.android.exoplayer2.source.SampleQueue.peekSampleMetadata(SampleQueue.java:697)
        at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:423)
        at com.google.android.exoplayer2.source.chunk.ChunkSampleStream.readData(ChunkSampleStream.java:392)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:425)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:961)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
```

### Media

Demo from media app

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-08-03 08:56
Duplicate of https://github.com/google/ExoPlayer/issues/10158

**Closed as completed** 2022-08-03 12:02 UTC
Labels: duplicate
