### ISSUE TITLE
IMA pre-rolls do not load (VAST_LINEAR_ASSET_MISMATCH)

### ISSUE THREAD

**Issue by ChetanPatelSS** [google/ExoPlayer#9840] opened 2022-01-05 12:00 UTC
**Our problem as we have also a WEB frontend, and ad server serves both for Android and Web (and website successfully plays all the ads types). So we’ll appreciate for this error handling bug to fixed ASAP or any recommendation/link how to separate Android&Web front ends in the ad server settings.**

There is a lack of information, we have really have searched through the Internet for the solution, but found nothing. So we will be grateful for any clue.

Version of ExoPlayer being used: 
   **implementation 'com.google.android.exoplayer:exoplayer-core:2.16.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.16.1'
    implementation 'com.google.android.exoplayer:extension-ima:2.16.1'**

**Issue** **IMA sample tags are working, but Live/Production tags have issue**
I open activity with ExoPlayerView, video starts, prerolls are skipped, in logs with debug mode I can see messages:
**Ad error: AdError 403: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities**

```
022-01-05 17:26:25.592 16053-16053/com.google.ads.interactivemedia.v3.samples.videoplayerapp I/chromium: [INFO:CONSOLE(1058)] " [  1.335s] [ima.admanager.VideoAdManager] Ad error: AdError 403: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities. [object Object]", source: https://imasdk.googleapis.com/native/core/3.298.1/native_bridge_debug__en_in.js (1058)
2022-01-05 17:26:25.594 16053-16053/com.google.ads.interactivemedia.v3.samples.videoplayerapp I/chromium: [INFO:CONSOLE(1058)] " [  1.338s] [UrlReporter] Reporting urls for event : error ", source: https://imasdk.googleapis.com/native/core/3.298.1/native_bridge_debug__en_in.js (1058)
2022-01-05 17:26:25.596 16053-16053/com.google.ads.interactivemedia.v3.samples.videoplayerapp I/chromium: [INFO:CONSOLE(1058)] " [  1.340s] [UrlReporter] Reporting urls for event : verificationNotExecuted ", source: https://imasdk.googleapis.com/native/core/3.298.1/native_bridge_debug__en_in.js (1058)
2022-01-05 17:26:25.624 16053-16053/com.google.ads.interactivemedia.v3.samples.videoplayerapp D/AdTagLoader: onAdError
      AdError [errorType: PLAY, errorCode: AdErrorCode [name: VAST_LINEAR_ASSET_MISMATCH, number: 403], message: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.]
        at com.google.ads.interactivemedia.v3.internal.ajb.f(IMASDK:1)
        at com.google.ads.interactivemedia.v3.internal.ajx.k(IMASDK:50)
        at com.google.ads.interactivemedia.v3.internal.akd.f(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.aka.shouldOverrideUrlLoading(IMASDK:2)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(Unknown Source:90)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:342)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:7851)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
2022-01-05 17:26:25.624 16053-16053/com.google.ads.interactivemedia.v3.samples.videoplayerapp D/AdTagLoader: Removing ad 0 in ad group 0
2022-01-05 17:26:25.625 16053-16053/com.google.ads.interactivemedia.v3.samples.videoplayerapp D/adsLoader: onAdError: CodeAdErrorCode [name: VAST_LINEAR_ASSET_MISMATCH, number: 403]Message Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.
2022-01-05 17:26:25.625 16053-16053/com.google.ads.interactivemedia.v3.samples.videoplayerapp D/adsLoader: onAdError: **getErrorAdError [errorType: PLAY, errorCode: AdErrorCode [name: VAST_LINEAR_ASSET_MISMATCH, number: 403], message: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.]**
2022-01-05 17:26:25.630 16053-16053/com.google.ads.interactivemedia.v3.samples.videoplayerapp W/AdTagLoader: onEnded without ad media info
2022-01-05 17:26:25.640 16053-16053/com.google.ads.interactivemedia.v3.samples.videoplayerapp D/AdTagLoader: onAdEvent: ALL_ADS_COMPLETED
```

How to fix this problem? No one of listeners are called in this situation. And I dont understand how to skip this midroll. 

Thank you in advance!

**Comment by ojw28** [comment] 2022-01-05 18:36
> How to fix this problem? No one of listeners are called in this situation. And I dont understand how to skip this midroll.

I'm a bit unclear on exactly what you're asking here. It looks like you're dealing with pre-rolls rather than mid-rolls, and I also think the the ad is skipped automatically if it can't be played (due to https://github.com/google/ExoPlayer/commit/5bd744000cde6dd6a9521f75d4824a00be046280), so it's unclear exactly what your question about skipping is about. Could you clarify?

I think your main problem is that you want the ads to play successfully, but are seeing a `VAST_LINEAR_ASSET_MISMATCH` error. As per the documentation, this means:

> Assets were found in the VAST ad response for nonlinear ad, but none of them matched the video player's capabilities.

Most likely the ad response contains ads that use an unsupported MIME type, either because it's (a) obscure, (b) incorrect, (c) you're configuring ExoPlayer in a non-standard way that restricts the supported MIME types, or (d) ExoPlayer doesn't declare support for a MIME type that it should declare support for. By default ExoPlayer will support the following MIME types:

```
application/dash+xml
application/x-mpegURL
video/mp4
video/webm
video/3gpp
audio/mp4
audio/mpeg
```

You should be able to take a look in the ad response to see what types of ads are included. Alternatively, you could provide us with a publicly accessible ad tag URI that we could try from within our demo app, then we could take a look.

**Comment by ChetanPatelSS** [comment] 2022-01-06 07:23
@ojw28 Thanks for quick replay.
My issue is IMA sample tags URL are working fine Android app , but Live/Production tags URL didn't load ads

Work fine in sample tag URL  :https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=

Error on Live ads Tag Url
**Ad error: AdError 403: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities**

**Comment by ojw28** [comment] 2022-01-06 09:58
My response above already explained why that might be the case, and what you need to look at or provide for us to investigate further. Linking to a tag that works fine isn't useful for helping us to reproduce the issue.

**Comment by ChetanPatelSS** [comment] 2022-01-06 11:31
Yes issue is  AdError 403: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities

face issue in bellow ads tag URL. let me know what was the issue?

**Comment by ojw28** [comment] 2022-01-06 11:46
What type of ad are you expecting to be displayed? The only ad defined in the ad tag seems to be `type="application/javascript"`, which is not a video ad. ExoPlayer's IMA extension only supports video ads.

**Comment by ChetanPatelSS** [comment] 2022-01-06 11:49
@ojw28 thanks for the quick replay
Also please check below ads tag URL -> same error we got  AdError 403: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities

**Comment by ojw28** [comment] 2022-01-06 11:53
Yes, that's the same. Note you can easily look at this yourself simply by opening the file and looking at the `type`: `type="application/javascript"`.

**Comment by ChetanPatelSS** [comment] 2022-01-06 11:54
> What type of ad are you expecting to be displayed? The only ad defined in the ad tag seems to be `type="application/javascript"`, which is not a video ad. ExoPlayer's IMA extension only supports video ads.

we want to play video ads in our exoplayer Android. 

can you please give me a Live video tag URL?

**Comment by ojw28** [comment] 2022-01-06 12:05
As above, the type of ads included in these ad tags are not video ads compatible with ExoPlayer, so from ExoPlayer's perspective this is working as intended. Please see the following site for more information about which ad types are compatible with different platforms. I suspect these ads may be using VPAID 2, which is only supported on web as per the table:

https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/compatibility

I'm going to close this issue, since things are working as intended from ExoPlayer's perspective. If you need further support about ad compatibility across different platforms, you should probably ask in the [IMA SDK forum](https://groups.google.com/g/ima-sdk/), since this is not ExoPlayer specific.

**Closed as completed by ojw28** 2022-01-06 12:05 UTC
Labels: question
