### ISSUE TITLE
mpd content not visible 

### ISSUE THREAD

**Issue by appsoft124** [google/ExoPlayer#11147] opened 2023-05-03 08:42 UTC
### Bug

I'm experiencing an issue where the video is playing but the content is not visible

  private void initializePlayer() {
        String URL = "https://1185-vos.dtvott.com/DASH/manifest.mpd";

        DefaultHttpDataSource.Factory defaultHttpDataSourceFactory = new DefaultHttpDataSource.Factory()
                .setUserAgent(USER_AGENT)
                .setTransferListener(new DefaultBandwidthMeter.Builder(this)
                        .setResetOnNetworkTypeChange(false)
                        .build());

        DashChunkSource.Factory dashChunkSourceFactory = new DefaultDashChunkSource.Factory(defaultHttpDataSourceFactory);
        DefaultHttpDataSource.Factory manifestDataSourceFactory = new DefaultHttpDataSource.Factory().setUserAgent(USER_AGENT);

//        String keyId = "fad9eaf7a980300686af7809c0377a00";// keyId
//        String keyValue = "0d270d4c1ef2a319aeaf2f424e9b1442";// key value
        String keyString = "{\"keys\":[{\"kty\":\"oct\",\"k\":\"DScNTB7yoxmury9CTpsUQg\",\"kid\":\"+tnq96mAMAaGr3gJwDd6AA\"}],'type':\"temporary\"}";
//        String keyString = "{\"keys\":[{\"kty\":\"oct\",\"k\":\"0d270d4c1ef2a319aeaf2f424e9b1442\",\"kid\":\"fad9eaf7a980300686af7809c0377a00\"}],'type':\"temporary\"}";

        LocalMediaDrmCallback drmCallback = new LocalMediaDrmCallback(keyString.getBytes());

        DashMediaSource dashMediaSource = new DashMediaSource.Factory(dashChunkSourceFactory, manifestDataSourceFactory)
                .setDrmSessionManagerProvider(mediaItem -> new DefaultDrmSessionManager.Builder()
                        .setPlayClearSamplesWithoutKeys(true)
                        .setMultiSession(true)
                        .setKeyRequestParameters(new HashMap<String, String>())
                        .setUuidAndExoMediaDrmProvider(C.CLEARKEY_UUID, FrameworkMediaDrm.DEFAULT_PROVIDER)
                        .build(drmCallback))

//                .createMediaSource(new MediaItem.Builder()
//                        .setUri(Uri.parse(URL))
//                        .setMimeType(MimeTypes.APPLICATION_MPD)
//                        .setTag(null)
//                        .build());

                .createMediaSource(new MediaItem.Builder()
                        .setUri(Uri.parse(URL))
                        // DRM Configuration
                        .setDrmConfiguration(new MediaItem.DrmConfiguration
                                .Builder(C.CLEARKEY_UUID)
                                .setMultiSession(true)
                                .setForceSessionsForAudioAndVideoTracks(true)
                                .build())
                        .setTag(null)
                        .build());

        // Prepare the player.
        player = new ExoPlayer.Builder(this).build();
        player.setPlayWhenReady(true);
        binding.playerView.setPlayer(player);
        player.setMediaSource(dashMediaSource, true);
        player.prepare();
        player.addListener(new Player.Listener() {
            @Override
            public void onPlaybackStateChanged(int playbackState) {
                switch (playbackState) {
                    case Player.STATE_IDLE:
                        Log.d("PlayerLogs", "onPlaybackStateChanged - IDLE");
                        break;
                    case Player.STATE_BUFFERING:
                        Log.d("PlayerLogs", "onPlaybackStateChanged - BUFFERING");
                        break;
                    case Player.STATE_READY:
                        Log.d("PlayerLogs", "onPlaybackStateChanged - READY");
                        break;
                    case Player.STATE_ENDED:
                        Log.d("PlayerLogs", "onPlaybackStateChanged - ENDED");
                        break;
                }
                Player.Listener.super.onPlaybackStateChanged(playbackState);
            }

            @Override
            public void onPlayerError(@NonNull PlaybackException error) {
                Log.e("PlayerLogs", "onPlayerError - error: " + error.getMessage(), error);
                Player.Listener.super.onPlayerError(error);
            }
        });
    }

**Comment by icbaker** [comment] 2023-05-03 09:00
Duplicate of https://github.com/google/ExoPlayer/issues/11146 (same URI)

**Closed as completed by icbaker** 2023-05-03 09:00 UTC
Labels: duplicate

**Comment by appsoft124** [comment] 2023-05-03 09:06
please fix the issue u are not fixing the issue our app is live
