### ISSUE TITLE
Is there any way to pass DataSpec flags to ExtractorMediaSource?

### ISSUE THREAD

**Issue by ZumiKua** [google/ExoPlayer#4551] opened 2018-07-23 09:11 UTC
DataSpec has a FLAG_ALLOW_CACHING_UNKNOWN_LENGTH flag and CacheDataSink will check this flag in its open method, but when using ExtractorMediaSource, DataSpec is created by ExtractorMediaSource and we can't change it's flags field, which results in we can't cache unkonwn length file while playing it with ExtractorMediaSource. 
Currently, I'm creating a custom ForceUnknownCacheDataSource to override it's open method and recreate a new DataSpec with this flag, but I think it would be more convenient to add a setDataSpecFlag method to ExtractorMediaSource.Factory or ExtractorMediaSource.

**Comment by AquilesCanta** [comment] 2018-07-23 16:39
@erdemguven, would you mind taking a look at this?

**Comment by AlienAsRoger** [comment] 2018-12-11 20:46
Any updates here? I'm wondering why it's marked as enhancement... is there a way to set `FLAG_ALLOW_CACHING_UNKNOWN_LENGTH` flag for `CacheDataSource` ? I haven't found one.

**Comment by tfrysinger** [comment] 2019-03-27 00:17
Any updates here? @erdemguven, there is a comment in CacheDataSource.java that seems to indicate it is somehow possible to update the DataSpec passed into open():

```
/**
 * A {@link DataSource} that reads and writes a {@link Cache}. Requests are fulfilled from the cache
 * when possible. When data is not cached it is requested from an upstream {@link DataSource} and
 * written into the cache.
 *
 * <p>By default requests whose length can not be resolved are not cached. This is to prevent
 * caching of progressive live streams, which should usually not be cached. Caching of this kind of
 * requests can be enabled per request with {@link DataSpec#FLAG_ALLOW_CACHING_UNKNOWN_LENGTH}.
 */
```

Is it really possible to do this? How?

**Comment by ojw28** [comment] 2019-03-27 23:21
There is no easy way to set the flag for progressive playbacks (i.e. playbacks that use `ExtractorMediaSource`). Hence why this is marked as an enhancement. As per the original post by @ZumiKua in this issue, it is possible to set the flag. It's just not particularly convenient.

I'm somewhat curious as to what the actual use case is for needing to set the flag. If the content length cannot be resolved then that normally implies a live stream (in which case enabling caching is the wrong thing to do), or a poor server implementation (if it's not a live stream, why isn't the server indicating the content length in the response headers).

**Comment by tfrysinger** [comment] 2019-04-03 13:00
My use case for needing this flag has to do with supporting providers that don't provide a direct HTTP or HTTPS link by default.

My mobile app allows users to select video/image files from various sources (local to the device, or surfaced on the Internet from a variety of providers) to be defined as a "playlist", then streamed (in the case where the source is external to the device) when the playlist is executed. 

In some cases, providers don't **easily** allow even authenticated users to have access to a URL that would be sufficient to hand to ExoPlayer . For example, consider Dropbox. Unless the user takes the extra step of creating a "public link" or the extra step of "sharing" their file (which I would not want to force them to do prior to making it "selectable" in my app), there is no way to provide a direct URL to ExoPlayer to the video - even for a user who is logged in to their own account. Instead, the Dropbox APIs I work with use an access token (to validate authentication) and document ID string (which is returned from a specific API call) to identify the file and to pass to another API call which enables a "Downloader" component to stream the file.

So what I did to facilitate the browsing, selecting and streaming of the file was to write a custom  DocumentsProvider class adhering to the Storage Access Framework specific to Dropbox. The app provides settings for the user to input their Dropbox authentication credentials, then the DocumentsProvider uses that + the Dropbox API to do the browsing. When they select a file, I get a `content://` type URI back which I send to ExoPlayer. When ExoPlayer uses it, it causes my DocumentsProvider openDocument() method to get called, and the ParcelDescriptor I return from that method is a Pipe - the back end of which is a thread that is streaming the contents of the file out:
```

            DbxClientV2 mDbxClient;
            FileMetadata fileMetadata;
            try {
                mDbxClient = DropboxClientFactory.getClient();
                fileMetadata = (FileMetadata) mDbxClient.files().getMetadata(documentId);
            } catch (DbxException e) {
                Timber.d("Got IDbxException when getting file metadata for document with ID: %s, message was: %s", documentId, e.getMessage());
                return null;
            }
            if ( InTouchUtils.isVideoFile(fileMetadata.getName()) ) {
                // Return a descriptor that will stream the file
                Timber.d("In openDocument of DropboxProvider for Id: %s, streaming from source", documentId);
                ParcelFileDescriptor[] pipe;
                try {
                    pipe = ParcelFileDescriptor.createPipe();

                    // Get input stream for the pipe
                    DbxDownloader downloader = mDbxClient.files().download(fileMetadata.getPathLower(), fileMetadata.getRev());
                    new TransferThread(downloader.getInputStream(), new ParcelFileDescriptor.AutoCloseOutputStream(pipe[1]), signal, fileMetadata.getSize()).start();
                    return pipe[0];
                } catch (DbxException dbe) {
                    Timber.d("Got IDbxException when streaming content: %s", dbe.getMessage());
                } catch (IOException ioe) {
                    Timber.d("Got IOException when streaming content: %s", ioe.getMessage());
                } catch (Exception e) {
                    Timber.d("Got Exception when streaming content: %s", e.getMessage());
                }
                return null;

```
I also wish to cache the resulting stream so if/when the user plays it again it doesn't have to hit the Internet to get it. But of course, I need to insure the video isn't going to blow up the storage on the device. So what I do is when setting up the MediaSource for this file, I make a check to insure that the video file isn't larger than the entire cache. If it is, then I don't use my custom DataSource/DataSourceFactory to grab it, I use the default which doesn't use the cache:

```
                // Check that we can actually handle this in the cache, some of our providers
                // are streaming directly and thus ExoPlayer doesn't know the size ahead of time.
                // To compensate, cachedMediaSourceFactory is written to stream directly to the
                // cache regardless of size, so we need to make sure first that the size isn't
                // larger than the cache!
                long currentCacheSize = PreferenceManager.getDefaultSharedPreferences(context).getLong(context.getString(R.string.pref_default_cache_size_key), DEFAULT_MEDIA_CACHE_SIZE_IN_MB) * (1024*1024);
                // How much room is in the cache?
                if ( size > currentCacheSize ) {
                    // Cache not large enough for this file, even if we evict everything else in there!
                    mediaSource = getDefaultMediaSourceFactory(context).createMediaSource(uri);
                } else {
                    mediaSource = getCachedMediaSourceFactory(context).createMediaSource(uri);
                }

```

What I was trying to do was find a simple way to set this flag so I didn't have to create a whole new copy of the class only to override open():

```
    public long open(DataSpec dataSpec) throws IOException {
        try {
            key = cacheKeyFactory.buildCacheKey(dataSpec);
            uri = dataSpec.uri;
            actualUri = getRedirectedUriOrDefault(cache, key, /* defaultUri= */ uri);
            httpMethod = dataSpec.httpMethod;
            if ( !dataSpec.isFlagSet(DataSpec.FLAG_ALLOW_CACHING_UNKNOWN_LENGTH) ) { // <-- update here
                flags = (dataSpec.flags | DataSpec.FLAG_ALLOW_CACHING_UNKNOWN_LENGTH);
            } else {
                flags = dataSpec.flags;
            }

```

**Comment by ojw28** [comment] 2019-04-03 13:56
Is `fileMetadata.getSize()` the total size of the file? If so, isn't there just a plumbing problem here. I.e. You're trying to turn on caching of content that has an unknown size, but you actually know the size and it's just not getting to where it needs to be?

**Comment by tfrysinger** [comment] 2019-04-03 15:09
Not sure what you mean by "plumbing problem". Is there a different flow other than passing a URL to let ExoPlayer know the size of a file ahead of time? Remember - I can't simply pass a URL back in this use case.

**Comment by tfrysinger** [comment] 2019-04-03 15:09
And yes, I actually do know the size ahead of time. But I didn't see a way to bridge that info. Is there one?

**Comment by ojw28** [comment] 2019-04-03 15:34
If you give ExoPlayer a `content://` URI, then internally the player will end up using its `ContentDataSource` to request the data. That class attempts to read the content length from the asset file descriptor:

https://github.com/google/ExoPlayer/blob/r2.9.6/library/core/src/main/java/com/google/android/exoplayer2/upstream/ContentDataSource.java#L94

and if that fails it tries to read it from the file channel:

https://github.com/google/ExoPlayer/blob/r2.9.6/library/core/src/main/java/com/google/android/exoplayer2/upstream/ContentDataSource.java#L99

The problem is that neither of these will be reading the correct size. The file descriptor is something that I think is being provided from your side, and you're providing a `ParcelFileDescriptor`. This then gets wrapped in an `AssetDataSource` with an unknown length inside of `ContentResolver`. If you instead take the `ParcelFileDescriptor` on your side, wrap it in an `AssetFileDescriptor` yourself with the length set to the known value, and provide that, then I suspect this will solve your problem by correctly plumbing the length through to the player. Please give this a try.

An alternative to this approach is not to use `content://` URIs at all. There's nothing stopping you from implementing a custom `DataSource` that reads the data you're downloading in the most direct way possible. You could then inject that custom `DataSource` into the player. You can also make up your own URI scheme for it.

I'd try the first of these two options first, since it probably fixes your problem with minimal effort.

**Comment by tfrysinger** [comment] 2019-04-04 16:14
Thanks for the info.

As I am using a custom DocumentsProvider to give a unified UI experience to the user for browsing/selecting files, I don't see how I have the option to _wrap it in an AssetFileDescriptor and provide that_. The openDocument() method in DocumentsProvider is defined to return a ParcelFileDescriptor. And the "content://" URI is what is returned to me by the SAF when the user selects a file. 

There is a openTypedDocument() method that returns an AssetFileDescriptor but its not (yet) clear to me that I can somehow force the flow that would insure this getting called.

**Comment by tfrysinger** [comment] 2019-04-04 16:19
In reviewing the SAF, it appears the openTypedDocument() is called only when a particular file is declared as a VIRTUAL file. Reading through the SAF docs, this would appear to be a solution as the SAF would then automatically return an AssetFileDescriptor. Although the problem for me with it is it is only supported from API 24 (Android 7.0) and higher. My app needs to run on Lollipop 5.0 (API 21) and higher.

**Comment by tfrysinger** [comment] 2019-04-04 16:40
Looking at ContentResolver.openAssetFileDescriptor(Uri uri, String, mode) (which ExoPlayer calls on line 79 of ContentDataSource), this winds up calling openAssetFile() of the DocumentsProvider. Herein lies the problem:

```
    public final AssetFileDescriptor openAssetFile(Uri uri, String mode)
            throws FileNotFoundException {
        enforceTree(uri);
        final ParcelFileDescriptor fd = openDocument(getDocumentId(uri), mode, null);
        return fd != null ? new AssetFileDescriptor(fd, 0, -1) : null;
    }

```

This method is final, so I can't override it. Blech. And you can see the problem - it is indeed returning an AssetFileDescriptor but is returning a -1 for the length. 

I suppose I could create my own DocumentsProvider class and play around with overriding the above method and somehow contextually return a length when it makes sense to do so. But I'm concerned about what might break elsewhere if I did that. It would be really helpful to know from that team why they did it this way.

I think I'm stuck with my current solution, as long as I use the SAF and until I can use API 24 as my floor.

**Comment by ojw28** [comment] 2019-04-05 22:12
From ExoPlayer's point of view what we want is (1) random access into the content, and (2) to know how long the content is. Pretty much all servers and file systems are able to support these requirements efficiently. It seems like you have what you need to support these requirements too, but the way you're exposing the content to ExoPlayer does not support them. This seems like an issue with your app's design, rather than an issue with ExoPlayer. It's likely that you could expose content to ExoPlayer some other way, which would solve this issue.

I think we can close this issue. There's no strong use case stated here for needing to be able to set the flag.

**Closed as completed by ojw28** 2019-04-05 22:12 UTC
Labels: enhancement

**Comment by tfrysinger** [comment] 2019-04-29 21:11
Thanks for your thoughts, but I don't think you are fully understanding the issue here.

You say "Pretty much all servers and file systems are able to support these requirements". Well, DropBox doesn't (for example), unless the user creates a shareable public link. Even as a logged in user with their API I can't get a URL directly to files that I own. I either have to programmatically use the API to create that link or I have to stream the content. Creating links has its own issues (usability, security, privacy) that make that route problematic.

_The way I'm exposing the content to ExoPlayer_ is the only way given to me via the SAF. It isn't my choice, I don't have control and it isn't me exposing the content. I get the content:// URI back from the SAF, and at that point handing it to ExoPlayer ultimately causes methods to be called within the SAF framework that that essentially bypass being able to indicate the size of the file to ExoPlayer.

I have the info I need to support the requirements, but not in the flow the way ExoPlayer currently has to have them.

So this feels to me a bit like you're punting on the issue. I'm not sure what "app design" approach would work in a case where one can't easily get programmatic access to URL/URI that is directly to the file.

**Comment by ojw28** [comment] 2019-04-30 00:02
> The way I'm exposing the content to ExoPlayer is the only way given to me via the SAF. It isn't my choice, I don't have control and it isn't me exposing the content. I get the content:// URI back from the SAF, and at that point handing it to ExoPlayer ultimately causes methods to be called within the SAF framework that that essentially bypass being able to indicate the size of the file to ExoPlayer.

I don't really follow the logic here. You have the `content://` URI from SAF, and you also have `FileMetadata` including the content length. There are options for exposing the content to ExoPlayer other than just directly passing the `content://` URI. For example, you could implement your own `DataSource` that integrates directly with SAF (e.g. `SafDataSource`). You could use the `ContentDataSource` implementation as a starting point, and change it so that it can get the length from SAF `FileMetadata`.

**Comment by ojw28** [comment] 2019-04-30 00:07
>You say "Pretty much all servers and file systems are able to support these requirements". Well, DropBox doesn't (for example), unless the user creates a shareable public link.

DropBox isn't a server or a file system. It's a service and as such they control the API that they expose. If their API doesn't support what's required for video streaming, then they're opting to not support that use case with their service. It's somewhat unclear to me whether this is the case, however, seeing as they do provide an API for accessing the content length via `FileMetadata`. It's unclear to me how efficiently they support random access into a file.
