### ISSUE TITLE
Discontinuity detected  and video freeze

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#6969] opened 2020-02-12 10:46 UTC
### [REQUIRED] Issue description
I am playing the video discontinuity detected and video freeze for once and then play. I am using 

### [REQUIRED] Reproduction steps
Simple playing the local video . 

### [REQUIRED] Link to test content
I am playing the local video 
https://drive.google.com/file/d/13cPGZghCKIAeRYbTlRbMW2GGPaMrEVqH/view?usp=sharing
### [REQUIRED] A full bug report captured from the device
https://drive.google.com/file/d/1Y9Ykz1PXCn9qK2mu0UCJwiSgbj4yxXsN/view
### [REQUIRED] Version of ExoPlayer being used
2.11.xx  

### [REQUIRED] Device(s) and version(s) of Android being used
vivo android v9

**Comment by kim-vde** [comment] 2020-02-12 12:04
Duplicate of #6970.

**Closed as completed by kim-vde** 2020-02-12 12:04 UTC
Labels: duplicate, question
