### ISSUE TITLE
DASH Widevine not playing CBCS content in android 9/10

### ISSUE THREAD

**Issue by sridhard** [google/ExoPlayer#10141] opened 2022-03-31 15:34 UTC
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

ASUS Zenfone Max Pro M1 - addroid 9
moto one power, Android version- 10

### Devices that do not reproduce the issue

Samsung, Redmi

### Reproducible in the demo app?

Yes

### Reproduction steps

Just play CBCS content from the demo app.

There is no error error logs. The video will be just green screen (Corrupted video), 

### Expected result

Device is running android 9 which is API version > 25 required to play CBCS content. So the video should be played successfully. If the video cannot be played because of some CDM issue then exoplayer should report the error.

### Actual result

Video is just green screen

### Media

Use the demo app CBCS content

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by sridhard** [comment] 2022-04-01 05:09
@icbaker This is the video of the issue https://shaka-packager-debug.s3.ap-south-1.amazonaws.com/WhatsApp+Video+2022-02-03+at+12.13.01+PM.mp4

This video is not from demo app, but from our app. The output is same using the exoplayer demo app from playstore. CTR content plays. But "widevine DASH:MP4,H264"->"WV:Secure SD&HD(cbcs,mp4,h264)" has the issue.

**Comment by icbaker** [comment] 2022-04-01 09:17
> The output is same using the exoplayer demo app from playstore.

We do not publish our demo app on the play store. You have to build it from source, as described here: https://exoplayer.dev/demo-application.html

I don't know what app you installed, but assuming someone else has published our demo app and judging by the sample name you reference, it looks like it was published before https://github.com/google/ExoPlayer/commit/b9abe2d0d6e68768a70af2a9cc1fffe5b19e7dab (when that sample was renamed). That commit was made in May 2020 and is included in version 2.12.0, suggesting the app you're using is based on version 2.11.8 of the library or earlier (i.e. pretty old).

Given you've said this only repros on some devices and not others I'm marking this as device-specific.

> Device is running android 9 which is API version > 25 required to play CBCS content. So the video should be played successfully. If the video cannot be played because of some CDM issue then exoplayer should report the error.

I agree with this in principle, however the ExoPlayer library cannot report any errors to an app if the CDM or MediaCodec doesn't report any errors up to us, which I suspect might be what's happening here (I don't know why).

I'm afraid I don't have access to the problematic devices you describe. Would you be able to do the following to help us a dig a bit deeper:
1. Install the [demo app](https://exoplayer.dev/demo-application.html) from the release-v2 branch of this git repo (i.e. version 2.17.1)
2. Reproduce the problem
3. Take a bug report with `adb bugreport` immediately after reproducing the problem and email the resulting zip file to dev.exoplayer@gmail.com with subject `Issue #10141`.

It would be great if you could do this for both devices you have that reproduce the problem.

**Comment by sridhard** [comment] 2022-04-04 04:04
Hi @icbaker 
We dont have the device. It is happening in our customer device. We have placed order for new device. Once we get the device i will share the logs

**Comment by sridhard** [comment] 2022-04-06 08:07
Hi @icbaker we have reproduced the issue with the demo app from the latest exoplayer code. I have send the bugreport and also logcat logs to dev.exoplayer@gmail.com with subject Issue #10141.

**Comment by icbaker** [comment] 2022-04-06 08:49
@rrfrias Please take a look at the emailed BR, it seems that widevine decryption isn't working correctly but not reporting any errors up to the app. There are some DRM/CDM related logs in logcat, but I don't know if they indicate real problems or not.

**Comment by sridhard** [comment] 2022-04-08 12:05
@rrfrias do you need any more information? we have the device and can get any details easily

**Comment by sridhard** [comment] 2022-04-11 03:51
@rrfrias @icbaker can you please help us to fix this issue

**Comment by sridhard** [comment] 2022-04-15 14:38
@icbaker @rrfrias the issue is happening in multiple mobiles. How can we debug this?

**Comment by sridhard** [comment] 2022-04-30 16:01
@icbaker @rrfrias the issue is happening in multiple mobiles. How can we debug this?

**Comment by sridhard** [comment] 2022-05-06 10:49
@icbaker @rrfrias can you pls help

**Comment by sridhard** [comment] 2022-05-14 05:53
@icbaker @rrfrias why there is no reply? you dont want to solve this issue or it is not a issue of exoplayer?

We are facing this issue in multiple mobiles. please check this issue

**Comment by rrfrias** [comment] 2022-05-15 16:35
Sorry for the delay in investigating this issue. I see only one set of errors in the log.

> 04-06 13:13:30.226   669   669 E DrmWidevineDash: OEMCrypto_DecryptCENC Legacy 8996/660 Path

This is usually associated with low frame rates and stuttering. Qualcomm has issued updates to OEMs but there are power implications and not all OEMs choose to apply this. But you are seeing a green screen for which I see no errors in the log from DRM or decode. 

Do you know if you are still seeing issues on ASUS Zenphone or Moto one power for android releases after the ones mentioned in the first comment? Can you try falling back to security level L3? A different encode might be another option. Even if we do find a root cause, getting OEMs to pick up patches/test/verify/issue releases and users to accept updates for older devices has proven to be difficult in the past.

**Comment by sridhard** [comment] 2022-05-25 13:08
@rrfrias Sorry for the late reply.

Yes we are still getting this issue. This is happening for multiple users. We have purchased ASUS Zenphone and we can easily reproduce in ASUS Zenphone.

We are using only security level L3. Also this is happening in some high end mobiles like OnePlus also.

As you said it is difficult to push patches.

If application is able to get the error, then we can handle this in the application. Currently if exoplayer can give the error to application it is enough for us

Thanks

**Comment by rrfrias** [comment] 2022-06-01 08:59
Can we get another logcat/bugreport since you are able to reproduce? I took another look at the bugreport you sent. That device was running L1. The  "OEMCrypto_DecryptCENC Legacy 8996/660 Path" logs appear 10 seconds after license has been loaded, rather than immediately. I expect you would then see frame freeze rather than green screen/mactoblocking. 

> If application is able to get the error, then we can handle this in the application. Currently if exoplayer can give the error to application it is enough for us

We are not seeing errors from the decrypt/decode path that allow the plugin to throw an exception. What Exoplayer test clip are you using "WV: Secure SD (cbcs, MP4, H264)" or HD/UHD?

**Closed as completed** 2022-06-30 01:04 UTC
Labels: bug: device specific, bug: in platform drm, closed-by-bot
