### ISSUE TITLE
How to get duration of playlist ?

### ISSUE THREAD

**Issue by iamkdblue** [google/ExoPlayer#8400] opened 2020-12-27 09:43 UTC
Thanks, dev for this great library.

I am trying to get a duration of the playlist, but I am not getting the correct duration of the playlist, sometimes it's showing a negative number. am I doing something wrong?

I am using this version of exoplayer

```
  api "com.google.android.exoplayer:exoplayer-core:2.12.0"
  api "com.google.android.exoplayer:exoplayer-ui:2.12.0"
  api "com.google.android.exoplayer:extension-mediasession:2.12.0"
```

I am using ConcatenatingMediaSource for making a playlist

```
 val concatenatingMediaSource = ConcatenatingMediaSource()
        songs.forEach { song ->
            val mediaItem:MediaItem = MediaItem.fromUri(song.getString(METADATA_KEY_MEDIA_URI).toUri())
            val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(mediaItem)
            concatenatingMediaSource.addMediaSource(mediaSource)
        }

```

```
val timeline: Timeline = exoPlayer.currentTimeline
        val currentWindowIndex: Int = exoPlayer.currentWindowIndex
        var currentPosition: Long = exoPlayer.currentPosition
        var totalTime: Long = 0
        val tmpWindow = Timeline.Window()
        for (i in 0 until timeline.windowCount) {
            val windowDuration = timeline.getWindow(i, tmpWindow).durationMs
            totalTime += windowDuration
            if (i < currentWindowIndex) {
                currentPosition += windowDuration
            }
        }
```

![Screenshot 2020-12-27 at 3 11 15 PM](https://user-images.githubusercontent.com/17172841/103167998-d5200e80-4855-11eb-8673-4c6a069327ea.png)

**Comment by marcbaechinger** [comment] 2020-12-29 14:58
I don't think you are doing something wrong. With progressive media, the duration is available only when the period of the source is created. For this the player needs to download parts of the media which is deferred until the data is really needed. This is even true [if you set `lazyPreparation` to `false`](https://github.com/google/ExoPlayer/blob/8a0d52be4b5402af0987fc7d009bc49977c72b67/library/core/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L440) (aside: you could use the [playlist API](https://exoplayer.dev/playlists.html) instead of the `ConcatenatingMediaSource`).

So the negative values you are seeing is coming from `C.TIME_UNSET` that is returned from `window.getDurationMs()` in case the duration is not yet known. So in your code you need to check `windowDuration != C.TIME_UNSET` to recognize this.

If you have the `EventLogger` you can inspect this in the logs. These statements show that onTimelineChanged is called at position 68.90 which is when the start of the third window has been buffered and the duration of the period/window got known:

```
2020-12-29 14:37:18.270 10227-10227/com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=95.62, mediaPos=68.90, window=1, period=1, periodCount=4, windowCount=4, reason=SOURCE_UPDATE
2020-12-29 14:37:18.271 10227-10227/com.google.android.exoplayer2.demo D/EventLogger:   period [25.00]
2020-12-29 14:37:18.271 10227-10227/com.google.android.exoplayer2.demo D/EventLogger:   period [128.27]
2020-12-29 14:37:18.272 10227-10227/com.google.android.exoplayer2.demo D/EventLogger:   period [19.30]
2020-12-29 14:37:18.272 10227-10227/com.google.android.exoplayer2.demo D/EventLogger:   ...
2020-12-29 14:37:18.272 10227-10227/com.google.android.exoplayer2.demo D/EventLogger:   window [25.00, seekable=true, dynamic=false]
2020-12-29 14:37:18.273 10227-10227/com.google.android.exoplayer2.demo D/EventLogger:   window [128.27, seekable=true, dynamic=false]
2020-12-29 14:37:18.273 10227-10227/com.google.android.exoplayer2.demo D/EventLogger:   window [19.30, seekable=true, dynamic=false]
2020-12-29 14:37:18.273 10227-10227/com.google.android.exoplayer2.demo D/EventLogger:   ...
2020-12-29 14:37:18.273 10227-10227/com.google.android.exoplayer2.demo D/EventLogger: ]
```

We have an open enhancement about this behaviour (#4727). There is also a comment with [some advice how you could work around the behavior](https://github.com/google/ExoPlayer/issues/4727#issuecomment-416497405).

I'm closing as a duplicate of the above.

Duplicate of #4727.

**Closed as completed by marcbaechinger** 2020-12-29 14:58 UTC
Labels: question

**Comment by iamkdblue** [comment] 2021-01-02 13:18
@marcbaechinger Thanks for your response,
I tried to implement the given link but those are related to when you play audios from server or online!
My playlist will play audios from local storage not from online. so it is possible to get all audios duration in starting?

**Comment by ojw28** [comment] 2021-01-17 23:18
This is not something we currently support. As per @marcbaechinger 's response above, supporting this is essentially a duplicate of #4727. Please follow that issue to see when support is added.
