### ISSUE TITLE
Local build fails due exoplayerSettingsDir

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#7550] opened 2020-06-26 12:03 UTC
### [REQUIRED] Issue description
Local build fails due changes introduced with 4138e28d626be428f5d84b77138f90006b233c08

### [REQUIRED] Reproduction steps
build exoplayer library locally (as part of the app project).
I have next project layout:
```
/settings.gradle
/build.gradle
/app/                         <-- app
/app/build.gradle
/app/src/..
...
/extern/ExoPlayer/            <-- exoplayer root
```

I have next settings in the project `settings.gradle`:
```
gradle.ext.exoplayerRoot = 'extern/ExoPlayer'
gradle.ext.exoplayerModulePrefix = 'exoplayer-'
apply from: new File(gradle.ext.exoplayerRoot, 'core_settings.gradle')
```

```
Build file '/home/astar/dev/tvirl/develop/extern/ExoPlayer/extensions/av1/build.gradle' line: 14

* What went wrong:
A problem occurred evaluating project ':exoplayer-extension-av1'.
> Could not read script '/home/astar/dev/tvirl/develop/extern/ExoPlayer/extensions/av1/extern/ExoPlayer/common_library_config.gradle' as it does not exist.
```

so it adds relative path to CWD of library and gets invalid one.
I was trying to workaround it using absolute path or using "../.." for `exoplayerSettingsDir` - but it's ignored (the only one which is applied is "..")

### [REQUIRED] Link to test content
not applicable

### [REQUIRED] A full bug report captured from the device
not applicable

### [REQUIRED] Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".

### [REQUIRED] Device(s) and version(s) of Android being used
not applicable

**Comment by tonihei** [comment] 2020-06-29 08:20
That's a duplicate of #7554.

**Closed as completed by tonihei** 2020-06-29 08:20 UTC
Labels: duplicate
