### ISSUE TITLE
 internet disruption slows down surface texture update (FPS drop)

### ISSUE THREAD

**Issue by IanMcCabe** [google/ExoPlayer#4792] opened 2018-09-07 21:15 UTC
### Issue description
A surface texture that is connected to the exoplayer and referenced externally, has reduced update time when the application is disconnected from wifi, and reconnected (causing a perceived FPS drop).

Basically, the internet connection is disrupted, it seems as though the exoplayer doesn't delivery frames to the surface texture fast enough resulting in an FPS drop.

### Reproduction steps
1. In the exoplayer interface, create a function that makes a surface texture and returns it's ID, Then call the function in Unity to connect the texture to a material. (shown in attached files.)
2. In the Unity code, call the exoplayer interface functions to prepare and load a video.
3. As the video starts playing, take note of the initial FPS.
4. As the video plays, disconnect and reconnect the wifi (easiest way is you swipe from the top of the phone to see the quick drop down bar). You should now see that the video is playing back at a slower framerate.

### Link to test content
will be delivered to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
Exoplayer Core - 2.8.1
Exoplayer Dash - 2.8.1

### Device(s) and version(s) of Android being used
- Device: Pixel, Android: 8.0.0, Reproduces: 100%
- Device: Samsung Galaxy S7, Android: 7.0, Reproduces: 100%

### A full bug report captured from the device
will be delivered to dev.exoplayer@gmail.com

**Comment by ojw28** [comment] 2018-09-12 12:45
I appreciate the reproduction steps, but they're equivalent to us re-implementing everything you've done, and getting up to speed on libraries we may not have used before (e.g. Unity). That would probably take at least a week, and we simply don't have that amount of time to spend on a single issue. Please provide a sample app as source code that we can use to easily reproduce the problem, if you wish for us to take a look.

**Comment by IanMcCabe** [comment] 2018-09-18 15:35
Hi @ojw28, I have emailed a link to dev.exoplayer@gmail.com which contains a Unity and Android project that displays more information and an example of the issue described above.

**Comment by ojw28** [comment] 2018-09-27 18:55
I couldn't reproduce this using the pre-built, although performance seemed really bad in general. I get a whole bunch of errors when I try and build from source (I think I might need to downgrade my NDK or something).

It seems pretty unlikely this is really an ExoPlayer issue, as opposed to something in app code or the underlying platform, so marking as low priority for now, given the overhead that's involved in looking at the issue.

**Comment by ojw28** [comment] 2018-09-27 18:57
@AquilesCanta - Might be worth spending 30 minutes or so on this, if it's easy for you to get up and running.

**Comment by tonihei** [comment] 2019-05-07 14:52
@AquilesCanta Did you find a chance to give that a try?

**Comment by AquilesCanta** [comment] 2019-05-09 20:31
Hi, is this issue still reproducible? Any chance you provide a fresh link for us to reproduce?

**Comment by ojw28** [comment] 2020-06-08 22:13
Closing as obsolete / never reproduced.

**Closed as completed by ojw28** 2020-06-08 22:13 UTC
Labels: low priority, wont fix: not reproducible
