### ISSUE TITLE
Questions regarding caching and possible bugs.

### ISSUE THREAD

**Issue by tomtaila-wesayhi** [google/ExoPlayer#9273] opened 2021-08-09 21:08 UTC
Hey ExoPlayer Team!

I have a couple of things I'd like to understand about caching that maybe you can help with. 

Observation A:
Suppose I have a .m3u8 file for some HLS stream with url == `someUrl`
Now imagine I stream that .m3u8 file via `exoPlayer.prepare(someUrl)`.
When that's stored into my Cache and then I call `downloadIndex.getDownload(someUrl)` I will get `null` which means that  the DownloadManager (which I use separately for predownloading) thinks that the file has not been downloaded. 

Why is that?

Note that for the above example I am using the same Cache when constructing my DownloadService dependencies and my ExoPlayer dependencies.

Observation B:
If I download some media with url == `someUrl` via the DownloadService and then the user goes to their settings and clears the app's cache, why does `downloadIndex.getDownload(someUrl)` != null? (i.e. why does it think there is still a valid file and how can I get it to correct itself?)
Is this a bug?

Sorry if either of these questions are obvious.

**Comment by ojw28** [comment] 2021-08-16 12:06
> Observation A:

`DownloadManager` is implemented on top of ExoPlayer's caching layer (i.e., if you download something using `DownloadManager`, it writes the media data into a `Cache`). However, if you cache media directly into the `Cache` underneath `DownloadManager`, it's not the case that `DownloadManager` will notice and update its state to indicate the content is downloaded. That's by design.

Note also that HLS content will typically consist of many hundreds of small files, and includes redundancy (i.e., only a subset of the files are needed). The subset that you pick is fundamentally different for download use cases (you'll typically download in a single variant/quality) and streaming playback (the player will dynamically adapt the variant/quality based on bandwidth). If you stream and cache the HLS content but the player had to drop down to a really low resolution at some point during the playback, would that be considered as downloaded or not?

> Observation B:

What directory are you using for your cache? The ExoPlayer demo app uses `getExternalFilesDir` or `getFilesDir`, which are not cleared when you press the "clear cache" button in settings. If your app is doing the same, it's correct that the app will still think there's a valid download, because the download will still be there. ​You would need to use "clear data" to remove downloads in this case. This works correctly in the demo app. If I change the demo app to use `getExternalCacheDir` or `getCacheDir` instead, then I am able to reproduce in that case.

`DownloadManager` is designed primarily for use cases where the user explicitly downloads content (e.g., by pressing a download button in the app, like in the demo app). The implementation reflects that:

* In a typical video app (e.g., a movie rental service), a user would not expect that watching a piece of content would be sufficient for it to be marked as downloaded in the UI. This is why Observation A is the way it is.
* When the user explicitly marks a piece of content as downloaded, they'd not expect the OS to be able to remove it silently (imagine getting onto a flight and finding all your downloads have disappeared). This could happen if using `getExternalCacheDir` or `getCacheDir`. Hence we generally expect apps to be using `getExternalFilesDir` or `getFilesDir` for caches that are used by `DownloadManager`, which to some extent explains Observation B. I consider the behavior when using `getExternalCacheDir` or `getCacheDir` as an oversight, but use of these directories is not really expected for typical use of `DownloadManager`. We could look at fixing it, but I'm not sure it's high priority.

**Closed as completed** 2021-09-07 19:22 UTC
Labels: question
