### ISSUE TITLE
Question on achieving a low latency HLS live stream

### ISSUE THREAD

**Issue by joaquim-verges** [google/ExoPlayer#4217] opened 2018-05-07 20:54 UTC
I'm using Exoplayer to play HLS live streams with a 30 sec window and 2 second segments, and I'am trying to optimize for low latency.

Everything works great using all the default settings for `LoadControl` and the default `HlsExtractorFactory`, with playback starting 3 segments before the end of the window as expected. 

The issue i'm seeing is when I'm on a good connection, I often get into a very short buffering states (around a second) after playing the stream for a few seconds.

This happens even more frequently if I lower the resolution of my stream to the lowest possible, and stay on a fast internet connection.

After debugging what's happening, it looks like the renderers are asking for the next segment, but the backend hasn't made that next segment available yet. Almost as if the renderer is ahead of the backend, and when asking for more, instead of just waiting and continuing playback (there's still buffered data to be played), it immediately sets the player state to `Player.STATE_BUFFERING`, until the new segment is available.

If I set the stream to start further back in the window, say 4-5 segments from the edge, the problem disappears completely, and my buffer sizes stay healthy, but I obviously loose in latency.

I'm surprised by this behavior as it seems like a common case for live HLS live streams to try to be as close as possible to the edge of the window.

I'm trying to understand why I'm getting this behavior, and wondering if I'm missing a configuration setting on the client, or if it's something that needs to be tweaked on the backend.

Thanks in advance!

### Version of ExoPlayer being used
2.7.3

### Device(s) and version(s) of Android being used
Google Pixel XL 2

**Comment by tonihei** [comment] 2018-05-08 09:50
Can you provide us with a link to your test stream to ensure we can reproduce the issue? 

I tested another HLS live stream and manually set the start position to a few seconds to the end of the window. This also causes some buffering as soon as I reach the end of the  window. However, this is clearly caused by running out of media as the playlist update and prebuffering of the next segment doesn't happen fast enough. 

Note that our  `DefaultLoadControl` waits until it has 5 seconds of buffered media before continuing playback when in `STATE_BUFFERING`. This is the `bufferForPlaybackAfterRebufferMs` parameter.
When I set this to zero, it continues playing immediately after getting new media. That allowed me to set the playback position to 1-2 seconds behind the live edge while still having a smooth playback with only the occasional small hick-up when loading didn't catch up fast enough.

**Comment by joaquim-verges** [comment] 2018-05-09 18:38
Thank you for the prompt reply @tonihei! That makes much more sense now, didn't think of reducing the `bufferForPlaybackAfterRebufferMs` value, it does help getting better latency on good connections.

I'll play with the right value to balance between latency and good experience for slower connections.

I'm also thinking of subclassing `DefaultLoadControl` to increase the `bufferForPlaybackAfterRebufferMs` value as I hit more buffer empties, to make the value more dynamic.

Seems like something like this should work?

```
// bufferForPlaybackAfterRebufferUs == 1 sec initially

@Override
public boolean shouldStartPlayback(long bufferedDurationUs, float playbackSpeed, boolean rebuffering) {
	boolean shouldStartPlayback = super.shouldStartPlayback(bufferedDurationUs, playbackSpeed, rebuffering);
	if (rebuffering) {
		// add new condition to start playback dependent on the rebuffer count 
		shouldStartPlayback &= bufferedDurationUs >= bufferForPlaybackAfterRebufferUs * rebufferCount;
                 // increment rebuffer count when we resume playback
                if (shouldStartPlayback) {
	                rebufferCount++;
                }
	}
	return shouldStartPlayback;
}
```

Does this makes sense for a live stream rebuffer behavior to keep requiring more buffered data as we hit more hiccups? and is `DefaultLoadController.shouldStartPlayback` the right place to add this logic?

Thanks again for the precious help.

**Comment by joaquim-verges** [comment] 2018-05-11 05:46
Just wanted to post an update for my buffering issue. I was lucky enough to meet @AquilesCanta from your team at Google I/O, and after inspecting a stream that reproduced the issue, he pointed out that I had an incorrect `#EXT-X-TARGETDURATION` of 5 seconds, while my segments are only 2 seconds.

This was causing exoplayer to only load new segments every 5 seconds, which I believe was the main cause of my rebuffering issue.

To verify this, I recompiled the HLS module with a hardcoded value of 2 seconds for `targetDurationUs` when building new `HlsMediaPlaylist` objects, and indeed the issue is now completely gone! I'm getting great latency and smooth playback :)

Wanted to post this in case it helps other people, and say a huge thanks to @AquilesCanta for helping me debug the issue.

Congrats on a great library, and keep up the good work!

**Comment by AquilesCanta** [comment] 2018-05-11 13:38
Great news, Joaquim! Nice meeting you. Feel free to reach out if you run into any more issues.

**Comment by tonihei** [comment] 2018-05-11 13:57
Closing the issue then, as it seems the question was solved.

**Closed as completed by tonihei** 2018-05-11 13:57 UTC
Labels: question, need more info
