### ISSUE TITLE
How I linstening the video is almost finished

### ISSUE THREAD

**Issue by aaironman** [google/ExoPlayer#5374] opened 2019-01-14 08:25 UTC
I don't know how linstening the video is almost finished.I want to know video is about to be played before it's finished a few seconds and Prompt the user.I don't find the listener,so I create TimerTask to calculate the position of the playing video.In the version of 2.0.0,it is no promblem,but I update the version to 2.9.2,the log shows "Player is accessed on the wrong thread. See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean".

new TimerTask() {
                @Override
                public void run() {
                    try {
                        if (player != null) {
                          
                            final long duration = player.getDuration();
                            final long currentPosition = player.getCurrentPosition();
                            if (login) {
                                if (duration > 0 && currentPosition > duration && !mPlayNext) {
                                    if (mHandler != null) {
                                        mHandler.sendMessage(mHandler.obtainMessage(PLAY_NEXT_CHAPTER, -1));
                                    }
                                } else {
                                    long difference = (duration - currentPosition) / 1000;
                                    if (difference <=5 && duration > 0 ) {
                                        if (mHandler != null) {
                                            mHandler.sendMessage(mHandler.obtainMessage(PLAY_COUNTDOWN, (int) (difference), -1));
                                        }
                                    }
                                }
                            }
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            };

How I fix the bug?

**Comment by tonihei** [comment] 2019-01-14 09:22
As the linked warning already says, you are accessing the player on the wrong thread. I guess the Handler is running not on the same thread that was used to create the player. 

As as alternative solution, you can also consider sending a message at the intended position:
```
player.createMessage(messageAction).setPosition(duration - 5000).setHandler(playerHandler).send();
```

**Comment by aaironman** [comment] 2019-01-16 10:13
> As the linked warning already says, you are accessing the player on the wrong thread. I guess the Handler is running not on the same thread that was used to create the player.
> 
> As as alternative solution, you can also consider sending a message at the intended position:
> 
> ```
> player.createMessage(messageAction).setPosition(duration - 5000).setHandler(playerHandler).send();
> ```
Thanks,I have an other similar question.There is a need to watch video when the full 30 minutes will request the server,and the initial viewing time comes from server in first entry.So I create Timer to calculate the total time every second.How I solve the promble?The total time is the time of staying looking the video to plus the initial time and the initial time will be update in changing the play state from server.

**Comment by tonihei** [comment] 2019-01-16 10:17
Not sure I can completely follow the question. If you want to track the time a user spent watching, please listen to `onPlayerStateChanged` events and use that to calculate the time in different states.

**Comment by aaironman** [comment] 2019-01-16 11:03
@tonihei I want to calculate the time every second in playing status.

**Comment by tonihei** [comment] 2019-01-16 16:45
I'm still unsure what you are trying to achieve, but it sounds like a duplicate of #5352.

**Comment by aaironman** [comment] 2019-01-16 22:13
Thank you very much!

**Closed as completed** 2019-01-17 02:06 UTC
Labels: question
