### ISSUE TITLE
stuck after Seek

### ISSUE THREAD

**Issue by 13217300237** [google/ExoPlayer#2723] opened 2017-04-25 09:13 UTC
## 
### Issue description
Playing HLS REPLY,sometimes it will stuck.

### Reproduction steps
We put the exoplayer as kernel player embedded in our own system.
HLS REPLAY is mean, we intercept HLS LIVE as a movie to play with..
We have found that play the replay,  there is a certain probability to stuck when seeking .
exception when stuck is the row - 199 of DefaultHttpDataSource.java:responseCode = connection.getResponseCode();

### Link to test content
Source is our Intranet resources.

### Version of ExoPlayer being used
2.3.0

### Device(s) and version(s) of Android being used
PAD Nexus  9 Android7.1.1

### A full bug report captured from the device
https://github.com/18598925736/hankstest/blob/master/npvrSeek.rar

**Comment by 13217300237** [comment] 2017-04-25 09:15
I really need your help.pls contact with me with email hzhou@quiptel.com

**Comment by 13217300237** [comment] 2017-04-25 09:15
thank you !

**Comment by AquilesCanta** [comment] 2017-04-26 11:20
Can you provide reproduction steps in the demo app? If not, can you provide a minimal code setup that reproduces the issue?  It is not clear what the issue is:

> Playing HLS REPLY,sometimes it will stuck.

What is HLS REPLY, and what does it mean it gets stuck? Does it transition into buffering state and does not go to ready state or does it block the application from responding?

**Comment by 13217300237** [comment] 2017-04-27 02:19
got it,I will check it about 
![image](https://cloud.githubusercontent.com/assets/16287718/25465098/f3431df6-2b32-11e7-833a-c3a49bae2637.png)

**Comment by ojw28** [comment] 2017-05-11 04:31
Closing due to lack of clear reproduction steps.

**Closed as completed by ojw28** 2017-05-11 04:31 UTC
Labels: need more info
