### ISSUE TITLE
Decoder failed: c2.android.avc.decoder

### ISSUE THREAD

**Issue by Jaydipnathani** [google/ExoPlayer#9644] opened 2021-11-03 04:11 UTC
> `DefaultRenderersFactory. setEnableDecoderFallback(true)`

After using this my issue was resolved when I test in debug mode. But when I did App release, the issue started coming back to my user so the issue was not resolved.

A version of ExoPlayer being used  2.14.1

I have an issue with ...
***Device Name:-*** 

**Samsung** 
  
- Galaxy J1(2016)  -  Android: 5.1.1
- Galaxy A20 - Android: 11
- Galaxy A20e - Android: 11
- Galaxy J6+ - Android: 10
- Galaxy A10 - Android: 10
- Galaxy C7 -  Android: 8.0.0
- Galaxy A2 - Core Android: 8.1.0
- Galaxy J7 - Android: 5.1.1
```
Non-fatal Exception: java.lang.Exception: Title : Videoview Blackscreen issue : Activity
Function : prepareVideo()
Callback : videoview setOnErrorListener()
Error : MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1920, 1080, 29.970028], [-1, -1]), format_supported=YES
Error_code : 1
App_name : 
Message : Video path : file:///data/user/0/packagename/files/app_templates/32717/602d038a0e280_zip_file_1613562762/602d038a0e280_zip_file_1613562762/title_video_mkf16.mp4
 Is Video path exist? : true
 Error rendererName : MediaCodecVideoRenderer
 Error rendererFormat : Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1920, 1080, 29.970028], [-1, -1])
 Error rendererFormatSupport4
 Error LocalizedMessage : Decoder failed: c2.android.avc.decoder
 Error Message : Decoder failed: c2.android.avc.decoder
```
Video :- [title_video_mkf16.mp4](https://drive.google.com/file/d/1YTKz_ILRIswqmgMO-facXknueJPKrH5j/view?usp=sharing)
***HUAWEI***

- HUAWEI Y5 2019 - android : 9
- Huawei MediaPad T5 - android : 8.0.0
- HUAWEI P smart 2019 - android : 10
- Mate 20 Pro - android : 10
- Mate 20 - android : 10
- P20 - android : 10
- 荣耀畅玩7X - android : 9
- HUAWEI P20 Lite - android : 9
```
Non-fatal Exception: java.lang.Exception: Title : Videoview Blackscreen issue : Activity
Function : prepareVideo()
Callback : videoview setOnErrorListener()
Error : MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1]), format_supported=YES
Error_code : 1
App_name : 
Message : Video path : file:///data/user/0/packagename/files/app_templates/36028/bd468f5a62b44_zip_file_1625309727657/bd468f5a62b44_zip_file_1625309727657/outro_video_pgg3.mp4
 Is Video path exist? : true
 Error rendererName : MediaCodecVideoRenderer
 Error rendererFormat : Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1])
 Error rendererFormatSupport4
 Error LocalizedMessage : Decoder init failed: OMX.hisi.video.decoder.avc, Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1])
 Error Message : Decoder init failed: OMX.hisi.video.decoder.avc, Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1])
```

Video :- [outro_video_pgg3.mp4](https://drive.google.com/file/d/156RHLpUY2vQQFuKOAmyuF2xih74Hn9ut/view?usp=sharing)

***VIVO***
- V2029 Android: 10
 ```
Non-fatal Exception: java.lang.Exception: Title : Videoview Blackscreen issue : Activity
Function : prepareVideo()
Callback : videoview setOnErrorListener()
Error : MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 30.0], [-1, -1]), format_supported=YES
Error_code : 1
App_name :
Message : Video path : file:///storage/emulated/0/Android/data/packagename/files/Movies/1Intro/bg_video_trim/fcb9c851f0564_trim_video_file_1629262336212.mp4
 Is Video path exist? : true
 Error rendererName : MediaCodecVideoRenderer
 Error rendererFormat : Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 30.0], [-1, -1])
 Error rendererFormatSupport4
 Error LocalizedMessage : Decoder failed: c2.android.avc.decoder
 Error Message : Decoder failed: c2.android.avc.decoder 
```

**Layout:**

``` 
<com.google.android.exoplayer2.ui.PlayerView
                    android:id="@+id/videoView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_gravity="center"
                    android:gravity="center"
                    app:use_controller="false" />
```

**Java Code.**

```
     private PlayerView playerView ;
     private SimpleExoPlayer simpleExoPlayer;
    private View surfaceView;

  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
      videoPlayerView = findViewById(R.id.videoView);
      initializePlayer();
}

```

```
 @Override
    protected void onPause() {
        super.onPause();

      onDestroyPlayerView();  
    }

```
```
  @Override
    protected void onResume() {
        super.onResume();

        Log.e(TAG, "onResume: ");
         initializePlayer();
       }

```
```


 public void initializePlayer() {

        Log.i(TAG, "initializePlayer: ");
        Log.e(TAG, "Exoplayer INIT: ");

        DefaultRenderersFactory rf = new DefaultRenderersFactory(context.getApplicationContext()).setEnableDecoderFallback(true);
        simpleExoPlayer = new SimpleExoPlayer.Builder(context, rf).build();

        if (playerView != null) {
            playerView.setPlayer(simpleExoPlayer);
            playerView.setUseController(setController);
            playerView.setResizeMode(RESIZE_MODE);
            surfaceView = playerView.getVideoSurfaceView();
            if (surfaceView != null) {
                Log.i(TAG, "initializePlayer: SURFACE Found!!");
            } else {
                Log.i(TAG, "initializePlayer: SURFACE = NULL ");
            }
           setSurfaceViewToExoPlayer();
        }
    }

```

```
public void setSurfaceViewToExoPlayer() {

        Log.i(TAG, "setSurfaceViewToExoPlayer: ");
        if (surfaceView != null) {
            if (simpleExoPlayer != null) {
                if (surfaceView instanceof SurfaceView) {
                    simpleExoPlayer.setVideoSurfaceView((SurfaceView) surfaceView);
                }
            }
        }
    }

    public void prepareVideo() {
     
        if (simpleExoPlayer != null && videoPath != null && videoPath.length() > 0) {

            MediaItem mediaItem = new MediaItem.Builder()
                    .setUri(Uri.fromFile(FileUtils.getValidFile(videoPath.replace(" ", "%20"))))
                    .setMimeType(MimeTypes.VIDEO_MP4)
                    .build();

            if (simpleExoPlayer.getMediaItemCount() > 0) {
                simpleExoPlayer.clearMediaItems();
            }

            simpleExoPlayer.setMediaItem(mediaItem);
            simpleExoPlayer.setRepeatMode(repeatMode);
            simpleExoPlayer.setPlayWhenReady(isPlayWhenReady);
            simpleExoPlayer.setVolume(1f);
            simpleExoPlayer.seekTo(0, 0);
            simpleExoPlayer.addListener(this);
            simpleExoPlayer.prepare();
        }
    }

```

```
public void onDestroyPlayerView() {

            simpleExoPlayer.pause();
            if (simpleExoPlayer.getMediaItemCount() > 0) {
                simpleExoPlayer.clearMediaItems();
            }
            Log.e(TAG, "Exoplayer RELEASE: ");

            simpleExoPlayer.stop(true);
            simpleExoPlayer.clearVideoSurface();
            simpleExoPlayer.removeListener(this);
            simpleExoPlayer.release();
            simpleExoPlayer = null;
     
    }
```

Please help me with how to fix this issue. @christosts @ojw28 @marcbaechinger @andrewlewis

**I think this issue is not a device-specific issue. Many devices have issues.**

_Originally posted by @Jaydipnathani in https://github.com/google/ExoPlayer/issues/9230#issuecomment-901661806_

**Comment by icbaker** [comment] 2021-11-03 10:02
Duplicate of https://github.com/google/ExoPlayer/issues/9230

**Closed as completed by icbaker** 2021-11-03 10:02 UTC
Labels: duplicate

**Comment by Jaydipnathani** [comment] 2021-11-09 11:24
Hi, Team

My problem was not solved so please review my issue. #9230 and #9396
