### ISSUE TITLE
Auto Adaptive bit-rate in Exoplayer v2

### ISSUE THREAD

**Issue by ManojJangra** [google/ExoPlayer#3068] opened 2017-07-15 10:49 UTC
I have update ExoPlayer v2 and facing some issue.
In older version, When i play video HLS file, It was start playing with low bit-rate (low quality) and After 4 or 5 sec It was automatically playing with high bit-rate (high quality).
But in new version, It's never start playing with high bit-rate automatically.

Please provide me solution for same.

**Comment by ojw28** [comment] 2017-07-15 21:10
It should auto switch up to high quality as in V1. Please provide proper reproduction steps and the other information requested in the issue template (e.g. a full bug report) if you want us to look at your issue. Thanks.

**Comment by ManojJangra** [comment] 2017-07-17 05:27
In older exo version1 gave **public final boolean adaptive**  under MediaFormat Class that provide adaptive bit-rate(Low to high quality) but in Exo version2 like that no any functionality for adaptive bit-rate.
for ex.  exo older version1 to check adaptive bit-rate
private static String buildTrackName(MediaFormat format) {
        if (format.adaptive) {
            return "Auto";
        }
.....
 Thanks.

**Comment by ojw28** [comment] 2017-07-17 08:10
In V2 an adaptive track is represented by a group of formats, so there's no need for an individual format to have an adaptive boolean. There are lots of things that are different in V2.

In order for us to help with whatever the problem is your facing, please provide proper reproduction steps and other information requested in the issue template (e.g. a full bug report) if you want us to look at your issue. Thanks.

**Comment by ManojJangra** [comment] 2017-07-24 05:15
Hi,
We want to  implement Pre-Roll  IMA Ads  with exo player V2.4.4. Please guide me, way of implementation  in my application.

**Comment by andrewlewis** [comment] 2017-07-24 10:11
@ManojJangra Please don't reuse an existing issue for an unrelated question, and post the same question multiple times. (#2617 tracks this already.)

**Comment by ojw28** [comment] 2017-07-31 14:59
[Deleting unrelated responses to this thread]

**Comment by ojw28** [comment] 2017-07-31 15:00
Also closing this issue because it doesn't contain sufficient information for us to help.

**Closed as completed by ojw28** 2017-07-31 15:00 UTC
Labels: need more info
