### ISSUE TITLE
Top bit not zero error when I play mp4 file

### ISSUE THREAD

**Issue by zhanganlong** [google/ExoPlayer#3567] opened 2017-12-09 02:48 UTC
when I use the 2.6.0 version Exoplayer to play the url below
http://online.pcvideo.com.cn/pconline/vpconline/2017/10/13/1507900474046-vpconline-78317-1_2.mp4
it can play normal, but when I seek the video, it report a error 
"Top bit not zero"  in code Mp4Extractor.readSample 
is this the right action?the video can play right int pc or other player

**Comment by ojw28** [comment] 2017-12-10 22:38
This sample video is working fine for me in the ExoPlayer demo app. Please provide concrete reproduction steps, a full bug report, and all of the other information requested in the issue template. Thanks.

**Comment by zhanganlong** [comment] 2017-12-11 02:12
tips:
1.use the video url in your demo: 
http://online.pcvideo.com.cn/pconline/vpconline/2017/10/13/1507900474046-vpconline-78317-1_2.mp4, please don't download the video in your own Server
2. seek the video to the time that has not been buffered yet 
then you can reproduction  the question

**Comment by zhanganlong** [comment] 2017-12-11 02:22
[top_error.log](https://github.com/google/ExoPlayer/files/1546374/top_error.log)
this is the all the log in my phone.I use the demo-ima test, replace contentUrl with the url (http://online.pcvideo.com.cn/pconline/vpconline/2017/10/13/1507900474046-vpconline-78317-1_2.mp4) in the PlayerManager.java init interface.I add some log which without modify any logic.
```
12-11 10:17:55.337 E/LoadTask(14967): Unexpected exception loading stream
12-11 10:17:55.337 E/LoadTask(14967): java.lang.IllegalStateException: Top bit not zero: -100547140
12-11 10:17:55.337 E/LoadTask(14967): 	at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:391)
12-11 10:17:55.337 E/LoadTask(14967): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:515)
12-11 10:17:55.337 E/LoadTask(14967): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:183)
12-11 10:17:55.337 E/LoadTask(14967): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:726)
12-11 10:17:55.337 E/LoadTask(14967): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
12-11 10:17:55.337 E/LoadTask(14967): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-11 10:17:55.337 E/LoadTask(14967): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-11 10:17:55.337 E/LoadTask(14967): 	at java.lang.Thread.run(Thread.java:762)
```

**Comment by zhanganlong** [comment] 2017-12-11 02:24
This sample video is working fine for me in the ExoPlayer demo app too when I put the video in my own apache server. 
Thanks!

**Comment by ojw28** [comment] 2017-12-11 11:45
The sample video works fine for me, even when using the exact url provided. I'm not downloading it or hosting it elsewhere. It's possible that the url redirects one of us to a different physical server, or that your ISP or mobile network provider is intercepting the request and serving it from its own caching infrastructure, or similar. That could account for different behavior observed. Note that using https is a good way to avoid the latter of these two types of issue.

I think we can close this issue, since it's highly likely to be a server/ISP/provider issue that's outside of our control. In particular, it's likely whatever infrastructure you're hitting is not handling range requests correctly, which would explain why you only see the issue after seeking.

**Closed as completed by ojw28** 2017-12-11 11:45 UTC
Labels: wont fix: infeasible

**Comment by zhanganlong** [comment] 2017-12-11 12:39
ok, thank you for your explanation!
