### ISSUE TITLE
ExoPlayer lockscreen image

### ISSUE THREAD

**Issue by vixez** [google/ExoPlayer#4979] opened 2018-10-18 18:23 UTC
Hello,

I'm using ExoPlayer in combination with PlayerNotificationManager. This all works fine, I can also set the album artwork in the notification.

However, when music is playing, the lockscreen background turns black. How can I set the album artwork as lockscreen image while music is playing? I can't seem to find anything about this.

Thanks!

**Comment by andrewlewis** [comment] 2018-10-19 17:55
When you say the lockscreen background is turning black: does this mean that the background is not changing at all from the default lock screen that you see when nothing is playing, or does it look like the system is trying to show the album art but it's not loading properly? In the latter case a bug report may help (`adb bugreport`).

I think the album art should just show up so I'm not sure what's going on here. @marcbaechinger may have ideas.

**Comment by vixez** [comment] 2018-10-21 12:49
Well, turns out it isn't changing at all. I though it was black, but that was because the player notification was covering up the middle part of my default lockscreen background (it's a simple black background with a deer on it).

So the album art is not showing at all.

**Comment by andrewlewis** [comment] 2018-10-21 15:24
Could you provide steps to reproduce the issue? In particular it would be useful to have the album art bitmap and  the code snippet used to set it. Do you see the same behavior on the emulator?

**Comment by vixez** [comment] 2018-10-22 08:23
This is the code I'm using.
The AudioController keeps track of the tracks that are playing for the main app UI, has nothing to do with the notifications/lockscreen, so not really relevant.

`
    @Override
    public void onCreate() {
    super.onCreate();

    //Player
    TrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory();
    player = ExoPlayerFactory.newSimpleInstance(this, new DefaultTrackSelector(trackSelectionFactory));

    // Notification manager
    playerNotificationManager = PlayerNotificationManager.createWithNotificationChannel(
            context,
            PLAYBACK_CHANNEL_ID,
            R.string.playback_channel_name,
            PLAYBACK_NOTIFICATION_ID,
            new MediaDescriptionAdapter() {
                @Override
                public String getCurrentContentTitle(Player player) {
                    return AudioController.getInstance().getCurrentTitle();
                }

                @Nullable
                @Override
                public PendingIntent createCurrentContentIntent(Player player) {
                    Intent intent = new Intent(context, AudioPlayerService.class);
                    return PendingIntent.getActivity(context, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
                }

                @Nullable
                @Override
                public String getCurrentContentText(Player player) {
                    return AudioController.getInstance().getCurrentText();
                }

                @Nullable
                @Override
                public Bitmap getCurrentLargeIcon(Player player, BitmapCallback callback) {
                    return getBitmap(
                            context, R.drawable.h1);
                }
            }
    );
    playerNotificationManager.setNotificationListener(new NotificationListener() {
        @Override
        public void onNotificationStarted(int notificationId, Notification notification) {
            startForeground(notificationId, notification);
        }

        @Override
        public void onNotificationCancelled(int notificationId) {
            stopSelf();
        }
    });

    // omit skip previous and next actions
    playerNotificationManager.setUseNavigationActions(true);
    // omit fast forward action by setting the increment to zero
    playerNotificationManager.setFastForwardIncrementMs(0);
    // omit rewind action by setting the increment to zero
    playerNotificationManager.setRewindIncrementMs(0);

    playerNotificationManager.setPlayer(player);


    // Media session
    mediaSession = new MediaSessionCompat(context, "TestAudio");
    mediaSession.setActive(true);

    mediaSessionConnector = new MediaSessionConnector(mediaSession);
    mediaSessionConnector.setQueueNavigator(new TimelineQueueNavigator(mediaSession) {
        @Override
        public MediaDescriptionCompat getMediaDescription(int windowIndex) {
            return updateMediaSessionMetaData();
        }
    });
    mediaSessionConnector.setPlayer(player, null);

    PlaybackStateCompat playbackStateCompat = new PlaybackStateCompat.Builder()
            .setActions(
                    PlaybackStateCompat.ACTION_SEEK_TO |
                            PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS |
                            PlaybackStateCompat.ACTION_SKIP_TO_NEXT |
                            PlaybackStateCompat.ACTION_PLAY |
                            PlaybackStateCompat.ACTION_PAUSE |
                            PlaybackStateCompat.ACTION_STOP
            )
            .setState(
                    PlaybackStateCompat.STATE_PAUSED,
                    0,
                    1.0f)
            .build();
    mediaSession.setPlaybackState(playbackStateCompat);
    playerNotificationManager.setMediaSessionToken(mediaSession.getSessionToken());

    // Binder
    binder = new AudioBinder();

    }

    private MediaDescriptionCompat updateMediaSessionMetaData() {
    MediaMetadataCompat.Builder metaDataBuilder = new MediaMetadataCompat.Builder();
    Bitmap albumArtBitmap = BitmapFactory.decodeResource(getResources(),
            R.drawable.h1);
    metaDataBuilder.putBitmap(MediaMetadata.METADATA_KEY_ALBUM_ART, albumArtBitmap);
    metaDataBuilder.putBitmap(MediaMetadata.METADATA_KEY_ART, albumArtBitmap);

    mediaSession.setMetadata(metaDataBuilder.build());

    MediaDescriptionCompat description = metaDataBuilder.build().getDescription();
    return description;
    }`

This is the picture I'mm using (the h1 drawable): https://i.imgur.com/LFZS9Vn.png

**Comment by andrewlewis** [comment] 2018-11-05 12:08
I tried to reproduce this by adding the provided image as a resource in the [io18 audio demo app](https://github.com/google/ExoPlayer/tree/io18) and setting the bitmap for the first sample to the new resource, but the image showed up as expected. Looking through your code snippet I didn't spot anything obviously wrong. Could you try using this demo app yourself and see whether the album art shows up on the lock screen as expected?

**Comment by ojw28** [comment] 2018-12-18 13:26
Closing due to lack of follow up.

**Closed as completed by ojw28** 2018-12-18 13:26 UTC
Labels: need more info
