### ISSUE TITLE
Help needed to add the Subtitles to cast using 

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#8875] opened 2021-04-27 09:57 UTC
```
MediaMetadata.Builder builder = new MediaMetadata.Builder().setTitle("Video Title");
List <MediaItem.Subtitle> subtitleList = new ArrayList<>(); 
MediaItem.Subtitle subtitle = new MediaItem.Subtitle(subtitleUri, MimeTypes.APPLICATION_SUBRIP, "en", C.SELECTION_FLAG_DEFAULT);
subtitleList.add(subtitle);
MediaItem.Builder mMediaItemBuilder = new MediaItem.Builder()
                .setUri(videoSourceUri)
                .setMediaMetadata(builder.build())
                .setSubtitles(subtitleList)
                .setMimeType(mimeType);
castPlayer.setMediaItem(mMediaItemBuilder.build(), resumePosition);
```

This is not displaying the selected subtitle on Chrome Cast
PS : Local ExoPlayer with new style player control working as expected
Cast Demo app is not updated and cast demo don't include subtitle implementation

**Comment by icbaker** [comment] 2021-04-27 10:26
I think this is a duplicate of #8669, specifically [this comment](https://github.com/google/ExoPlayer/issues/8669#issuecomment-792723005) from @marcbaechinger discusses adding support for subtitle tracks in `DefaultMediaItemConverter`.

**Comment by marcbaechinger** [comment] 2021-04-27 19:31
Yes, @icbaker is right that this is currently not supported and is tracked with #8669 that is marked as an enhancement. I updated the title of the other issue to clarify this. 

We don't have an ETA for this right now but  you can inject your own `MediaItemConverter` into `CastPlayer` to do that conversion yourself.

Please add you rcomments regarding this to #8669. I'm closing this as a duplicate. Please re-open if you think we need to continue here.

**Closed as completed by marcbaechinger** 2021-04-27 19:31 UTC
Labels: question
