### ISSUE TITLE
 A bug in the Exoplayer

### ISSUE THREAD

**Issue by GYT-cool** [google/ExoPlayer#8864] opened 2021-04-24 15:34 UTC
The embedded subtitle in the black edge will not be displayed when playing Dolby Vision MKV files.

**Comment by icbaker** [comment] 2021-04-26 08:20
Hi! Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.

**Comment by GYT-cool** [comment] 2021-04-27 02:13
Please look at the picture below, the problem is that the embedded subtitles in the red box area cannot be displayed, this only happens when playing Dolby Vision MKV files.
![IMG_20210427_004032](https://user-images.githubusercontent.com/45682244/116174102-57efa200-a740-11eb-8512-741aed0d917c.jpg)

**Comment by kim-vde** [comment] 2021-04-27 07:40
Please share an example of media that has the issue. If you're unable to share
test content publicly, please send it to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by GYT-cool** [comment] 2021-04-27 09:22
Well, only 10 MB of attachments can be uploaded here, so I sent the example of media to dev.exoplayer@gmail.com.

**Comment by icbaker** [comment] 2021-04-27 14:37
Neither of the provided media files (P7 and P8) contain subtitle tracks (according to both `mediainfo` and ExoPlayer).

I played them both in the demo app. P7's video codec wasn't supported by my device. P8 played on my device and I saw the text shown in the screenshots in your email. Above the video I saw "Vacation \\ Go Go's" and then later, below the video I saw "Can't seem to get my mind off of you".

This text must be burnt in to the video since ExoPlayer found no separate subtitle tracks (i.e. the video includes some black letterboxing and adds the text into it. This makes sense because the video is encoded at 16:9 but the image content in your screenshots is wider than that) - so if you're not seeing the text that means some of the video is being cut off.

It's hard to say why that would be happening - but based on the screenshot in this issue, could the text just be being obscured temporarily by the UI elements of the player...? It's not clear to me if those UI elements come from ExoPlayer or are custom - certainly the top bar looks unfamiliar to me.

I'm going to close this because I'm unable to reproduce the problem with the media provided.

**Closed as completed by icbaker** 2021-04-27 14:37 UTC
Labels: question
