### ISSUE TITLE
Offline play error

### ISSUE THREAD

**Issue by Envitec** [google/ExoPlayer#11246] opened 2023-07-13 06:30 UTC
### Bug

I have a bizarre situation while playing offline content. I adapted Axinom’s offline sample application to play content offline. Everything works fine as longs as there is only one content download for play. 

As soon as second content is downloaded for playing, the first one stops. The error file is attached below. This only happen on the device I am using, Samsung S20 running Android 13. Target API is API 33.

It works perfectly well on Windows Subsystem for Android API 33 and other Android Emulators. There is no issues with playing content Online.

I am not able to determine if the root cause of this issue is ExoPlayer or the license. I would appreciate if you can give me some pointer to look in right direction.

The issue is very consistent. Download second content and the first one give the error as described in the file. 

Can ExoPlayer persist only one license?

I am reading KeyIds from storage and using
**mMediaDrm = new MediaDrm(C.WidevineUuid);
mSessionId = mMediaDrm.OpenSession();
defaultDrmSessionManager.SetMode(DefaultDrmSessionManager.ModeQuery, keyIds);
mMediaDrm.RestoreKeys(mSessionId, keySetId);**

Thanks
Rajesh
[error.txt](https://github.com/google/ExoPlayer/files/12036045/error.txt)

**Comment by Envitec** [comment] 2023-07-13 09:45
I am able to narrow it down to this one particular call:
**mMediaDrm.RestoreKeys(mSessionId, keySetId);**

When a new offline license is downloaded, restoring the the previous ones gives this error:

**[DrmHalHidl] uuid=[edef8ba979d64ace a3c827dcd51d21ed] No supported hal instance found
[DrmHalHidl] Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
[DrmHalHidl] framework logs size 7; plugin logs size 0
[MediaDrm-JNI] Illegal state exception: Failed to restore keys: ERROR_DRM_UNKNOWN
[MediaDrm-JNI] ============================== Beginning of DRM Plugin Log ==============================
[MediaDrm-JNI]   07-13 15:10:20.406 I found instance=clearkey version=android.hardware.drm@1.3::IDrmFactory
[MediaDrm-JNI]   07-13 15:10:20.406 I found instance=widevine version=android.hardware.drm@1.3::IDrmFactory
[MediaDrm-JNI]   07-13 15:10:20.406 E uuid=[edef8ba979d64ace a3c827dcd51d21ed] No supported hal instance found
[MediaDrm-JNI]   07-13 15:11:41.693 E uuid=[edef8ba979d64ace a3c827dcd51d21ed] No supported hal instance found
[MediaDrm-JNI]   07-13 15:11:41.748 E uuid=[edef8ba979d64ace a3c827dcd51d21ed] No supported hal instance found
[MediaDrm-JNI]   07-13 15:11:53.535 E uuid=[edef8ba979d64ace a3c827dcd51d21ed] No supported hal instance found
[MediaDrm-JNI]   07-13 15:12:10.152 W Cannot cast android.hardware.drm@1.0::IDrmPlugin obj to android.hardware.drm@1.4::IDrmPlugin plugin
[MediaDrm-JNI] ============================== End of DRM Plugin Log ============================== (-2000)**

**Comment by tonihei** [comment] 2023-07-14 13:05
It looks like you are using the platform `MediaDrm` classes directly and not the ExoPlayer classes. So I'm afraid this is outside of what this issue tracker can help you with. If you are using ExoPlayer, please explain how this problem can be reproduced with a regular player integration.

**Comment by Envitec** [comment] 2023-07-14 13:56
I found issues that are logged here similar to what I am facing except that in my case it is not multi-key in the same content but keys in different content.

[How to download a drm file which has multiple drm keys · Issue #8924 · google/ExoPlayer](https://github.com/google/ExoPlayer/issues/8924)

[Multikey DRM - Allow restoring multiple keysets for offline playbacks · Issue #3872 · google/ExoPlayer](https://github.com/google/ExoPlayer/issues/3872)

[Does mediaDrm.restoreKeys() support offline multiple session? · Issue #7124 · google/ExoPlayer](https://github.com/google/ExoPlayer/issues/7124)

Do you think I can use ExoMediaDrm in place of platform MediaDrm? I will give it a try and see how that works.

Thanks
Rajesh

**Comment by tonihei** [comment] 2023-07-14 16:24
`ExoMediaDrm` is just a wrapper interface for the platform class, so it won't make a big difference I'd guess. The linked issues sound related indeed and I suggest to try to read through the solutions and comments there. Because you are not using ExoPlayer, this is still not the right forum to discuss more details and I'm going to close this issue for now. If you see a specific problem when using ExoPlayer (that isn't covered by the linked existing issues), please feel free to reopen or file a new one.

**Closed as completed by tonihei** 2023-07-14 16:24 UTC
Labels: question
