### ISSUE TITLE
Poor performance when using TextureView for rendering?

### ISSUE THREAD

**Issue by tmm1** [google/ExoPlayer#7376] opened 2020-05-14 08:10 UTC
I have been experiencing poor performance when using `TextureView` instead of `SurfaceView` for rendering, and have traced the root cause back to https://issuetracker.google.com/issues/37079050

It seems the [`onFrameAvailable` callback](https://android.googlesource.com/platform/frameworks/base.git/+/71f2cf116aab893e224056c38ab146bd1538dd3e/core/jni/android/graphics/SurfaceTexture.cpp#146) used by `SurfaceTexture` will invoke `AttachCurrentThread`/`DetachCurrentThread` for every incoming frame. This is used to bind the native pthread into the JVM (by assigning a JNIEnv*, which is wrapped in a `java.lang.Thread` object on the JVM side). Unfortunately doing this repeatedly (i.e. at 30fps or 60fps) causes many hundreds of these `Thread` objects to be generated over time, putting a lot of strain on the GC and causing performance loss like occasional frame drops.

This is clearly an Android OS bug, however I'm opening this here to:

1) provide an FYI for Exoplayer users who may be considering using TextureView
2) see if anyone else has experienced this problem first hand
3) ask for help in surfacing this issue to the android development team

**Comment by andrewlewis** [comment] 2020-05-14 12:48
The graphics team commented that this was basically working as intended in 2016 [Internal ref: b/26842782#comment2], saying that "The thread is a Binder thread receiving the onFrameAvailable callback. Because it's a Binder thread, not something we explicitly create or control, we do have to attach it to the VM before calling into the VM. And since we don't know if/when it will go away (so we can't detach at thread destruction) we have to detach before returning from the callback.".

Previously I tried to reproduce frame drops due to this behavior but the GC pauses were very short on my test device (0.5 ms every 30 seconds on Nexus 6P running Android O MR1) [Internal ref: b/111329805], and I'd expect the GC to be more efficient on recent Android versions. Of course on other devices or at very high frame rates they may be problematic. Unless you need to do some GL-based processing of video frames, `SurfaceView` is likely to be a better option (see also [this documentation](https://exoplayer.dev/ui-components.html#choosing-a-surface-type).

**Comment by andrewlewis** [comment] 2020-05-14 12:49
I'll actually leave this open a bit in case there is any follow-up and add an item to raise it with the graphics team next time we talk to them, in case there are any updates (but it sounded like a fairly fundamental limitation so I wouldn't be optimistic!). Thanks.

**Comment by tmm1** [comment] 2020-05-14 16:38
> The graphics team commented that this was basically working as intended in 2016 [Internal ref: b/26842782#comment2]

Really appreciate you surfacing this up to us.

> "The thread is a Binder thread receiving the onFrameAvailable callback. Because it's a Binder thread, not something we explicitly create or control, we do have to attach it to the VM before calling into the VM. And since we don't know if/when it will go away (so we can't detach at thread destruction) we have to detach before returning from the callback."

Interesting. I am not very familiar with the internals of Binder. What about it prevents the thread from using the detach at thread destruction technique?

> Previously I tried to reproduce frame drops due to this behavior but the GC pauses were very short on my test device (0.5 ms every 30 seconds on Nexus 6P running Android O MR1) [Internal ref: b/111329805], and I'd expect the GC to be more efficient on recent Android versions.

What I have noticed is that the behavior gets worse if we store large objects on the java heap. For instance if you create about 12MB of String objects on the java heap, all of a sudden you will start seeing that Binder thread causing blocking GC. Turning on `largeHeap="true"` can help mitigate this, but that has its own set of drawbacks.

> Unless you need to do some GL-based processing of video frames, `SurfaceView` is likely to be a better option

Yep I'm using SurfaceView when possible, but that's not always the case.

**Comment by andrewlewis** [comment] 2021-10-25 08:50
A change was merged internally that should fix this:

```
    Fix SurfaceTexture listener performance
   
    Attaching & detaching threads from JavaVM isn't cheap. There's
    no reason to do a detach anyway, so just don't. This avoids
    subsequent callbacks needing to re-attach.
   
    This aligns SurfaceTexture to the common pattern elsewhere
    in the platform for attaching as a daemon if it's not a java
    thread.
```

This should go into the next version of Android (I don't think it made it for Android S).

> Interesting. I am not very familiar with the internals of Binder. What about it prevents the thread from using the detach at thread destruction technique?

I'm afraid I don't know, but hopefully the answer doesn't matter if there's a fix to avoid the expensive operation!

**Closed as completed by andrewlewis** 2021-10-25 08:50 UTC
Labels: question
