### ISSUE TITLE
Suddenly jumps to the last position (flac file).

### ISSUE THREAD

**Issue by Empressia** [google/ExoPlayer#9368] opened 2021-09-01 03:15 UTC
### Summary

I have two silent FLAC files of about 20 seconds.  
File.A : track number 1. file size 16,846 bytes.  
File.B : track number 2. file size 16,846 bytes.  
The other metadata is the same.  

When I play File B, the exo_position TextView of PlayerControlView suddenly appears as "00:20".  
File A can be played normally.  

* Do I need a special way to play Flac files?

I can provide the two files in question.

### Environment
* ExoPlayer 2.15.0
* Xperia 10 II
* Android 11

**Comment by kim-vde** [comment] 2021-09-01 19:55
Please provide the 2 FLAC files so that I can try to reproduce. If you're unable to share  test content publicly, please send it to dev.exoplayer@gmail.com using subject #9368. Please also update this issue to indicate you've done this.

**Comment by Empressia** [comment] 2021-09-02 10:14
I sent it by e-mail. I have sent it twice, but it may have failed once.

**Comment by kim-vde** [comment] 2021-09-02 17:25
Thanks. Both files seem to play normally for me. Could you try playing them on our [demo app](https://github.com/google/ExoPlayer/tree/r2.15.0/demos/main) to see if you see the error there as well? You will need to add your media files to [media.exolist.json](https://github.com/google/ExoPlayer/blob/r2.15.0/demos/main/src/main/assets/media.exolist.json).

> When I play File B, the exo_position TextView of PlayerControlView suddenly appears as "00:20".

What happens then? Does playback ends directly (given that the file duration is 20 seconds)? Feel free to send us a video showing what you observe.

Are you using the [FLAC extension](https://github.com/google/ExoPlayer/tree/r2.15.0/extensions/flac)?

**Comment by Empressia** [comment] 2021-09-03 03:42
> What happens then?

If repeat mode is enabled, it will immediately return to the beginning and play.
If repeat mode is disabled, the number of seconds is counted up. Like 00:20 -> 00:21 -> 00:22 ... .

------

This issue has been solved with the following changes.
https://github.com/google/ExoPlayer/issues/9349#issuecomment-912229412

**Comment by kim-vde** [comment] 2021-09-03 17:12
I will close this issue as the problem is already being tracked by #9349.

**Closed as completed by kim-vde** 2021-09-03 17:12 UTC
Labels: bug
