### ISSUE TITLE
ExoPlayer freezes before playing midroll

### ISSUE THREAD

**Issue by AlexDundar** [google/ExoPlayer#4941] opened 2018-10-12 08:17 UTC
**Version of ExoPlayer being used:**  2.9.0
**Issue description:** I have ads with 2 prerolls, several midrolls and postroll. Here is the sample with vast xml: [ads_xml_with_freezing.txt](https://github.com/google/ExoPlayer/files/2472104/ads_xml_with_freezing.txt)
**Reproduction steps:** I open activity with ExoPlayerView, video starts, prerolls are skipped, in logs with debug mode I can see messages: 
1) [  0.883s] [ima.common.ErrorUtils] Error log dispatched: AdError 1009: The response does not contain any valid ads."
2) [  0.914s] [ima.common.ErrorUtils] Error play dispatched: AdError 403: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities."
3) I/ImaAdsLoader: AdEvent: {type=adPlayError, errorCode=403, errorMessage=Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.}

But its okay, because prerolls are skipped and video plays well. When midroll time has come, player freezes and doesnt play ads and video content. I cannt see the video content after that. In logs I see the next messages: 
[logs.txt](https://github.com/google/ExoPlayer/files/2472168/logs.txt)
This does not always happen, but very often.

**Device(s) and version(s) of Android being used:** Android os versions: 7.0, 9.0. Devices: samsung s6, google pixel, lg g3s.

Here is my code:

 ```
private MediaSource buildMediaSourceWithAds(Uri uri) {
ImaSdkSettings imaSdkSettings = ImaSdkFactory.getInstance().createImaSdkSettings();
        imaSdkSettings.setAutoPlayAdBreaks(true);
        imaSdkSettings.setDebugMode(true);

        adsLoader = new ImaAdsLoader.Builder(this)
                .setImaSdkSettings(imaSdkSettings)
                .setMediaLoadTimeoutMs(9 * 1000)
                .setVastLoadTimeoutMs(9 * 1000)
                .setAdEventListener(adEvent -> {
                    Utills.showLog("adEventadEvent " + adEvent.getType().name());
                })
                .buildForAdsResponse("here is xml from file");

        AdsMediaSource adsMediaSource = new AdsMediaSource(
                buildMediaSource(uri),
                this,
                adsLoader,
                simpleExoPlayerView.getOverlayFrameLayout());

      return adsMediaSource;
}

private MediaSource buildMediaSource(Uri uri) {
        DefaultHttpDataSourceFactory httpDataSourceFactory = new DefaultHttpDataSourceFactory(userAgent,
                bandwidthMeter,
                DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
                true);
        DefaultDataSourceFactory defaultDataSourceFactory = new DefaultDataSourceFactory(this,
                bandwidthMeter,
                httpDataSourceFactory);
        OkHttpDataSourceFactory okHttpDataSourceFactory = new OkHttpDataSourceFactory(okHttpClient,
                userAgent,
                bandwidthMeter);

        int type = Util.inferContentType(uri);
        switch (type) {
            case C.TYPE_SS:
                return new SsMediaSource.Factory(new DefaultSsChunkSource.Factory(okHttpDataSourceFactory), defaultDataSourceFactory)
                        .createMediaSource(uri);
            case C.TYPE_DASH:
                return new DashMediaSource.Factory(new DefaultDashChunkSource.Factory(okHttpDataSourceFactory), defaultDataSourceFactory)
                        .createMediaSource(uri);
            case C.TYPE_HLS:
                return new HlsMediaSource.Factory(okHttpDataSourceFactory)
                        .createMediaSource(uri);
            case C.TYPE_OTHER:
                return new ExtractorMediaSource.Factory(okHttpDataSourceFactory)
                        .createMediaSource(uri);
            default:
                Toast.makeText(this, "Unsupported video type", Toast.LENGTH_LONG).show();
                return null;
        }
    }
```
And for start playing video:
```
  currentMediaSource = buildMediaSourceWithAds(Uri.parse(videoUrl));
  player.prepare(currentMediaSource, true, false);
```

How to fix this problem? No one of listeners are called in this situation. And I dont understand how to skip this midroll. Thanks.

**Comment by andrewlewis** [comment] 2018-10-19 16:53
When the IMA SDK tries to load these ads, it seems to surface a different type of error from the ones that we handle at the moment. Please could you double-check your ad serving configuration and make sure you're serving ad media that is compatible with Android? That may be the quickest way to fix your issue.

We should handle these types of ad playback errors more gracefully but this will require more investigation.

**Comment by AlexDundar** [comment] 2018-10-22 08:58
@andrewlewis , thank you for your reply!

Our problem as we have also a WEB frontend, and ad server serves both for Android and Web (and website successfully plays all the ads types). So we’ll appreciate for this error handling bug to fixed ASAP or any recommendation/link how to separate Android&Web front ends in the ad server settings.

There is a lack of information, we have really have searched through the Internet for the solution, but found nothing. So we will be grateful for any clue.

Thank you in advance!

**Comment by andrewlewis** [comment] 2019-02-12 14:44
@AlexDundar Sorry for being slow to reply. I was looking into this again today but found that I couldn't reproduce the error: the midrolls are either empty or play as expected, and the player doesn't get stuck. Do you have an up to date ad tag that can be used to reproduce the original problem, or have you found a way to work around it? Thanks.

**Comment by ojw28** [comment] 2019-04-16 16:12
Should this be closed as not reproducible?

**Comment by andrewlewis** [comment] 2019-04-17 08:04
Closing as not reproducible for now. We can reopen if an updated ad tag is provided.

**Closed as completed by andrewlewis** 2019-04-17 08:04 UTC
Labels: need more info
