### ISSUE TITLE
[Bug] MediaCodec: Codec reported err 0xfffffff4/NO_MEMORY on Android 13 devices

### ISSUE THREAD

**Issue by 247az** [google/ExoPlayer#10661] opened 2022-09-30 05:55 UTC
### ExoPlayer Version

2.17.1
2.18.1

### Devices that reproduce the issue

* Pixel 4
* Pixel 4XL
* Pixel 4a
* Pixel 4a (5G)
* Pixel 5
* Pixel 5a

### Devices that do not reproduce the issue

Pixel 6
Pixel 6 Pro

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Use the demo example of ExoPlayer: https://github.com/google/ExoPlayer/releases/tag/r2.18.1

3. Build the Demo and play Video with named: 60fps DASH / 4K (MP4, H264, Widevine cenc) content on Pixel 4a..etc device, Android 13 operating system.

5. Use the SEEK or SKIP function (continuously for a short period of time). You may need to keep using the SEEK function continuously until an error occurs.
Maybe this error will not occur as soon as you seek the video, maybe you will need to seek continuously until the error occurs. But sometimes it happens the first time you seek.
I also don't know how much I need to seek, if the error will occur, there is no exact data.

6. Error will be displayed after you SEEK or SKIP a few times.

You can also keep playing the video without having to use the SEEK or SKIP function to reproduce this error. It will appear after a certain amount of time. It could be 3 minutes, 5 minutes, or more than 10 or 15 minutes.

You can also use the demo example on the version: https://github.com/google/ExoPlayer/releases/tag/r2.10.6, with Youtube DASH/Google Glass (MP4, H264) or Google Play (MP4, H264) . 
It seems more difficult to reproduce the error in version 2.18.1 than in version 2.10.6, but it still happens.

### Expected result

We have not found a specific solution yet, so we hope you can review and solve it for us. Or at least suggest a specific workaround that can solve this problem.

Our current application is still using version 2.10.6, and currently it is not possible to upgrade to the latest version. So if you have any solutions for 2.10.6 version, I would be very grateful.

Sincerely Thank 

### Actual result

Our project is currently using the ExoPlayer library to play video contents or live streaming. But when the user uses the SEEK or SKIP function or some times even does nothing, after about 15-20 minutes, the video player will have an error and cannot continue playing.

The members of the project's development team tried to debug and find the reason for the above problem, the results were as follows:
```
・It only happens on Android 13, Android 12 or earlier version does not.
・Currently our team only tested on a few devices, most of the devices below will have the above error, others seem to not.
```

Devices where the error occurred:
* Pixel 4
* Pixel 4XL
* Pixel 4a
* Pixel 4a (5G)
* Pixel 5
* Pixel 5a

Devices that do not appear to be error-prone:
* Pixel 6
* Pixel 6 Pro

At the moment we can only test on the above devices, so it is possible that other devices that we have not tested are also possible.

After members of our development team checked the log of the errors that occurred, it is mainly related to the MediaCodec class on the framework side of the system.
To make sure it has something to do with the version of the ExoPlayer library we're using, we've also tested it on the most recent version of the current ExoPlayer, and the above error still occurs, all on the above devices. And they all have the same error, both in the MediaCodec class.

I have attached the error log and where the error occurred and the necessary information.

Where the error occurs ?
```
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo E/CCodec: Resume request for Input Buffers failed
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0xfffffff4/NO_MEMORY, actionCode 0, while in state 6/STARTED
```

Which ExoPlayer version using ?
```
ExoPlayer 2.10.6
ExoPlayer 2.17.1
ExoPlayer 2.18.1
```

Operating system version:
```
Android 13 Build version: TP1A.220905.004
```

Error log:
```
2022-09-30 13:49:59.513 16086-16142/com.google.android.exoplayer2.demo D/MediaCodec: keep callback message for reclaim
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo I/CCodecConfig: query failed after returning 17 values (BAD_INDEX)
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo W/Codec2Client: query -- param skipped: index = 1342179345.
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo W/Codec2Client: query -- param skipped: index = 2415921170.
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo W/Codec2Client: query -- param skipped: index = 1610614798.
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo W/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] start: cannot allocate memory at all
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo E/CCodec: Resume request for Input Buffers failed
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0xfffffff4/NO_MEMORY, actionCode 0, while in state 6/STARTED
2022-09-30 13:49:59.513 16086-16157/com.google.android.exoplayer2.demo D/SurfaceUtils: disconnecting from surface 0x72f662aaf0, reason disconnectFromSurface
2022-09-30 13:49:59.514 16086-16165/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] Ignoring stale input buffer done callback: last flush index = 1520, frameIndex = 1519
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] flushed work; ignored.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] Discard frames from previous generation.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] flushed work; ignored.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] Discard frames from previous generation.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] flushed work; ignored.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] Discard frames from previous generation.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] flushed work; ignored.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] Discard frames from previous generation.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] flushed work; ignored.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] Discard frames from previous generation.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] flushed work; ignored.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] Discard frames from previous generation.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] flushed work; ignored.
2022-09-30 13:49:59.514 16086-16159/com.google.android.exoplayer2.demo D/CCodecBufferChannel: [c2.qti.avc.decoder.secure#299] Discard frames from previous generation.
2022-09-30 13:49:59.518 16086-16173/com.google.android.exoplayer2.demo D/CCodecBuffers: [c2.android.aac.decoder#926:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 0
2022-09-30 13:49:59.518 16086-16173/com.google.android.exoplayer2.demo D/CCodecBuffers: [c2.android.aac.decoder#926:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 1
2022-09-30 13:49:59.518 16086-16173/com.google.android.exoplayer2.demo D/CCodecBuffers: [c2.android.aac.decoder#926:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 2
2022-09-30 13:49:59.518 16086-16173/com.google.android.exoplayer2.demo D/CCodecBuffers: [c2.android.aac.decoder#926:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 3
2022-09-30 13:49:59.519 16086-16142/com.google.android.exoplayer2.demo D/MediaCodec: keep callback message for reclaim
2022-09-30 13:49:59.519 16086-16173/com.google.android.exoplayer2.demo I/CCodecConfig: query failed after returning 20 values (BAD_INDEX)
2022-09-30 13:49:59.519 16086-16173/com.google.android.exoplayer2.demo W/Codec2Client: query -- param skipped: index = 1342179345.
2022-09-30 13:49:59.519 16086-16173/com.google.android.exoplayer2.demo W/Codec2Client: query -- param skipped: index = 2415921170.
2022-09-30 13:49:59.519 16086-16173/com.google.android.exoplayer2.demo W/Codec2Client: query -- param skipped: index = 1610614798.
2022-09-30 13:49:59.521 16086-16142/com.google.android.exoplayer2.demo E/MediaCodecVideoRenderer: Video codec error
      android.media.MediaCodec$CodecException: Error 0xfffffff4
2022-09-30 13:49:59.522 16086-16142/com.google.android.exoplayer2.demo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x60.0] [c2.qti.avc.decoder.secure, video/avc] [sunfish, Pixel 4a, Google, 33]
2022-09-30 13:49:59.524 16086-16142/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, 19382783, null, [3840, 2160, 60.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.avc.decoder.secure
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
2022-09-30 13:49:59.525 16086-16142/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2388)
        at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:237)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:864)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:857)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:710)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:561)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:186)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1671)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1411)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1374)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:591)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```
![ExoPlayer_2 18 1_error](https://user-images.githubusercontent.com/114720380/193198594-2eb5c991-258d-48e2-91fb-68d6337ee572.png)

### Media

ExoPlayer 2.18.1
60fps DASH / 4K (MP4, H264, Widevine cenc)
![ExoPlayer_2 18 1_List](https://user-images.githubusercontent.com/114720380/193198367-e5832fe1-dd8c-4651-988f-9e70cfa5fe5b.png)

ExoPlayer 2.10.6
Youtube DASH/Google Glass (MP4, H264) or Google Play (MP4, H264) 
![ExoPlayer_2 10 6_List](https://user-images.githubusercontent.com/114720380/193198470-c2adfcc8-69f4-4569-b238-0811712eedff.png)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-09-30 08:55
This is a known issue in the Android 13 `MediaCodec` implementation [internal b/237656746]. It should be fixed in Android 13 QPR1, can you try installing or flashing a QPR1 beta build and see if you can still reproduce? https://developer.android.com/about/versions/13/get-qpr

**Comment by icbaker** [comment] 2022-09-30 08:56
Ah it looks like the fix isn't included in QPR 1 Beta 1, which is the only one available publicly so far. It should be fixed in a subsequent QPR1 Beta release.

**Comment by 247az** [comment] 2022-10-03 23:46
@icbaker 
I apologize for replying you late.
Thank you very much for confirming and responding to my problem.

But I have a question, so this problem is not related to the version of ExoPlayer ? It will probably be fixed after I update to the new version of the operating system ?

**Comment by icbaker** [comment] 2022-10-04 09:03
> But I have a question, so this problem is not related to the version of ExoPlayer ? It will probably be fixed after I update to the new version of the operating system ?

That's correct, you shouldn't see the problem on Android 12 and you shouldn't see it on Android 13 QPR1 either (when that's released). The only affected version is the original Android 13 release.

**Comment by kevdliu** [comment] 2022-10-09 20:53
Do you know of any workarounds we can implement on the application side to alleviate this bug (besides disabling seeking)?

**Comment by icbaker** [comment] 2022-10-10 09:25
I believe the problem occurs when seeks are too frequent. You may be able to implement logic in your app to mitigate this by intercepting calls to seek on your player and delaying consecutive seek calls for a short while.

You could do this with `ForwardingPlayer` (you need to ensure you override all `seek`-related methods). See more info: https://exoplayer.dev/customization.html#intercepting-method-calls-with-forwardingplayer

**Comment by 247az** [comment] 2022-10-10 12:22
@icbaker 
Thank you for your reply,
But sometimes this error occurs when you do nothing (not only in case seeks are too frequent). When you play any content, and after playing for a while, it will happen.
There are cases when you change the bitrate it will happen as well.

**Comment by christosts** [comment] 2022-10-10 15:00
@raku10dev 
We are not aware of this issue happening on regular playback, i.e. with no seeking involved. Can you confirm that is exactly the same error (`0xfffffff4/NO_MEMORY`)? If the error is raised on regular playback, can you give us detailed information to reproduce, for example is this also reproducible on the demo app, and can you attach a bug report obtained from the device after the error occurs?

Thank you

**Comment by 247az** [comment] 2022-10-11 07:09
@christosts 
Yes, it has the same error as error `0xfffffff4/NO_MEMORY`.
To reproduce when you don't use seeking is very unlikely, it happens randomly, and there is no specific step to reproduce it. Currently, I haven't been able to reproduce it, it's probably very low occurrence rate.

**Comment by 247az** [comment] 2022-10-11 09:17
@icbaker @christosts 
Looks like the QPR1 b2 version has just been released.
https://developer.android.com/about/versions/13/release-notes#beta2
I checked again on this version, it seems that this error is gone.
Is it fixed on this version ? Or was I wrong?

**Comment by yzcslam** [comment] 2022-10-14 02:51
Has the problem been solved?

**Comment by icbaker** [comment] 2022-10-14 13:31
@yzcslam: The Android 13 QPR1 Beta 2 release linked above contains the fix.

**Closed as completed** 2022-10-14 13:32 UTC
Labels: bug: in platform

**Comment by hushhw** [comment] 2022-11-09 03:50
The Pixel4 XL has not been released a beta version, and the problem still exists.

**Comment by qianzhang613** [comment] 2022-11-17 09:43
Hi ,

I have the same issue when runing cts test for flush case.

11-17 14:52:19.844 10097  7881  7930 W CCodecBufferChannel: [c2.v4l2.avc.decoder#626] start: cannot allocate memory at all
11-17 14:52:19.844 10097  7881  7930 E CCodec  : Resume request for Input Buffers failed
11-17 14:52:19.844 10097  7881  7930 E MediaCodec: Codec reported err 0xfffffff4/NO_MEMORY, actionCode 0, while in state 6/STARTED

It is framework bug for original android13 release, is it right?
Can you help to send out the bug fix patch for this issue? Thanks.

**Comment by christosts** [comment] 2022-11-17 10:05
The fix included in [Android 13 QPR1 Beta 2](https://developer.android.com/about/versions/13/release-notes#beta2) build, [here](https://issuetracker.google.com/issues/237538712#comment6) is the issue that tracked the platform bug.
