### ISSUE TITLE
How to same Ad cuepoint multiple times during same playback session?

### ISSUE THREAD

**Issue by pokuri3** [google/ExoPlayer#3805] opened 2018-02-06 08:24 UTC
As Imaloader accepts Ad uri or Ad response and combined with media and play.During playback once Ad played it won't be play again.If i want to play that ad again if rach the point by rewind, how can i achieve that?

**Comment by andrewlewis** [comment] 2018-02-06 08:58
Once the user has viewed an ad group it is marked as played and won't be shown again. This is the intended behavior of the IMA SDK and I'm not aware of any ways to customize it.

If you want to work around this, you can probably handle requests to seek backwards by creating a new ads loader and media source, and re-preparing the player with the new media source. The new loader will see all ad groups as unplayed. This is a bit inefficient, though, as you'll be discarding the player state on every seek, and re-requesting the ad tag.

**Closed as completed by andrewlewis** 2018-02-06 08:58 UTC
Labels: question
