### ISSUE TITLE
infinite buffer state for live content on low bandwidth conditions

### ISSUE THREAD

**Issue by spakanati123** [google/ExoPlayer#4584] opened 2018-07-26 19:38 UTC
To fix buffering issues on Amazon fire stick models we customized the **DefaultHttpDataSource** so that in our custom class if connection open and read operation(complete chunk data) should finish in specified interval say 10 sec.
If not we will throw **HttpDataSourceException**, for vod it is working like as expected like if chunk does not download in 10sec retry mechanism applied for 3 times and player aborted on the failure of all attempts.

But in live case, the manifest is very minimal size so i can see it keeps on download for the configured interval even chunks download failing in 10 sec. Since the manifest download getting success the player never aborts and buffer state can see forever. I can't see retry mechanism for live chunk like observed for vod chunk file.
For Vod the same chunk retried for 3 times whereas for live it's random either one or two times, so please help me to understand retry mechanism for live content.

**Link to test content**
Observe on any Dash content

**Version of ExoPlayer being used**
2.6.1

**Device(s) and version(s) of Android being used**
Amzon 4k, fire stick gen 2

**Comment by ojw28** [comment] 2018-07-27 09:13
> To fix buffering issues on Amazon fire stick models we customized the DefaultHttpDataSource so that in our custom class if connection open and read operation(complete chunk data) should finish in specified interval say 10 sec.

Can you expand on why you need to do this. What happens if you don't, and why is it specific to Fire Stick? Is there a bug filed on the device somewhere that you can reference? Also, you might want to see if switching to our OkHttp extension solves the problem in a simpler and better way.

> Since the manifest download getting success the player never aborts

I don't think such logic exists in our code base. The difference you're seeing is probably that for live content we try and switch to a different representation before failing.

@AquilesCanta - The way blacklisting works currently, is it possible that we can end up buffering forever if trying the other available representations takes longer than the period we blacklist any single representation for? If so, perhaps making some forward progress (i.e. successfully downloading a chunk in any representation) should be required for removing from the blacklist.

**Comment by AquilesCanta** [comment] 2018-07-30 08:20
> is it possible that we can end up buffering forever if trying the other available representations takes longer than the period we blacklist any single representation for

I strongly doubt it. We only blacklist 404 and 410s right now. For this to happen you'd need the server to take up to `60 / number of variants` seconds to return each 404 /410. Sounds unlikely to reproduce easily.

> perhaps making some forward progress should be required for removing from the blacklist

This is a gray area. I think we should only do it if simple to implement/maintain. The behavior would still require a 60+ seconds buffering period with the default values. Am I missing something maybe?

**Comment by ojw28** [comment] 2018-08-14 09:05
@spakanati123 - Could you answer my questions above?

**Comment by ojw28** [comment] 2018-11-05 00:41
Closing due to lack of required information. If you're able to provide it, please do so here and we'll re-open the issue.

**Closed as completed by ojw28** 2018-11-05 00:41 UTC
Labels: need more info
