### ISSUE TITLE
Exoplayer shows the freeze last frame of the previous video when add fragment

### ISSUE THREAD

**Issue by mrj976** [google/ExoPlayer#7076] opened 2020-03-12 13:25 UTC
When i play video in first fragment and want add second fragment and play new video, shows the freeze last frame of the previous video.
This problem solved When i replace fragment but i want add fragment.
please help me.
thanks

**Comment by tonihei** [comment] 2020-03-12 13:30
It's hard to understand what happens here without more detailed reproduction steps and explanations. Could you be more specific what the problem is and what you do exactly?

**Comment by mrj976** [comment] 2020-03-12 14:04
Thanks.
In Fragment1, play exoplayer in recyclerview like instagram with framelayout and its ok.
But when i add fragment with this code:

```
 Bundle bundle = new Bundle();
                        bundle.putString(Constants.VIDEO_ID, id);
                        AppCompatActivity activity = (AppCompatActivity) view.getContext();
                        Fragment myFragment = new Fragment2();
                        myFragment.setArguments(bundle);
                        activity.getSupportFragmentManager().beginTransaction().add(R.id.frame_fragment_containers, myFragment).addToBackStack(null).commit();
```
and play new video by exoplayer in framelayout, video show like [this image](https://i.stack.imgur.com/FZRcA.jpg).
last frame of the previous video play with new video.
two frames in one exoplayer framelayout.

when i replace fragment, solved this problem but i want add fragment.

**Comment by mrj976** [comment] 2020-03-12 14:05
> It's hard to understand what happens here without more detailed reproduction steps and explanations. Could you be more specific what the problem is and what you do exactly?

Thanks.
In Fragment1, play exoplayer in recyclerview like instagram with framelayout and its ok.
But when i add fragment with this code:

```
 Bundle bundle = new Bundle();
                        bundle.putString(Constants.VIDEO_ID, id);
                        AppCompatActivity activity = (AppCompatActivity) view.getContext();
                        Fragment myFragment = new Fragment2();
                        myFragment.setArguments(bundle);
                        activity.getSupportFragmentManager().beginTransaction().add(R.id.frame_fragment_containers, myFragment).addToBackStack(null).commit();
```
and play new video by exoplayer in framelayout, video show like [this image](https://i.stack.imgur.com/FZRcA.jpg).
last frame of the previous video play with new video.
two frames in one exoplayer framelayout.

when i replace fragment, solved this problem but i want add fragment.

**Comment by tonihei** [comment] 2020-03-12 14:20
Still slightly unclear - sorry. 

How many ExoPlayers do you create? One for each fragment or are you using the same player instance?

What does it mean that the last frame of previous video is playing with the new video? If you add the fragment it makes sense to me that both videos are shown.

**Comment by mrj976** [comment] 2020-03-12 14:31
> Still slightly unclear - sorry.
> 
> How many ExoPlayers do you create? One for each fragment or are you using the same player instance?
> 
> What does it mean that the last frame of previous video is playing with the new video? If you add the fragment it makes sense to me that both videos are shown.

In Fragment1 i use [this code](https://androidwave.com/exoplayer-in-recyclerview-in-android/) and list items by recyclerview and play videos in list by exoplayer. like instagram.
In Fragment2 i use One SimpleExoPlayer and add PlayerView to FrameLayout, shows the freeze last frame of the previous video played in recyclerview in Fragment1 and new video.
Like [this Image](https://i.stack.imgur.com/FZRcA.jpg).
Up frame is new video and down frame is freezed video.

**Comment by tonihei** [comment] 2020-03-12 17:02
As far as I understand your problem description, it sounds like expected behaviour. 
When you add a new fragment 2 with a new ExoPlayer, it will start playing the new video in there. But the existing fragment1 is still there and still shows the previous state of the video (e.g. the last frame).

If this is not what you're asking, please clarify.

**Comment by mrj976** [comment] 2020-03-12 22:35
@tonihei 
Yes that's right.  But I don't want to destroy the Fragment1 or exoplayer in Fragment1. and when I add the Fragment2, the video pause in the Fragment1 in recyclerview list and play new video in Fragment2.
I want play new video in added Fragment without freezed frame.

**Comment by tonihei** [comment] 2020-03-13 10:09
This is probably more of a generic Android issue after all I think. If you don't want to show the fragment with the last frame of the previous video, then you need to hide it somehow or replace it with something else.  I'd encourage you to ask these more generic Android question on StackOverflow or similar pages. You may also want to have a look at #867 where people shared a lot of experiences with using ExoPlayer in RecyclerViews.

Closing for now under the assumption it's not really an ExoPlayer issue where we can do something. We may want to provide some guidance on how to integrate ExoPlayer into Recyclerviews in the future, but this is already tracked by #867.

**Closed as completed by tonihei** 2020-03-13 10:09 UTC
Labels: question
