### ISSUE TITLE
Problem with playing video after upgrading to 2.6.1 from 2.4.4 on some devices

### ISSUE THREAD

**Issue by AntonAndev** [google/ExoPlayer#3834] opened 2018-02-12 14:49 UTC
Hello, I use ExoPlayer 2.4.4 in app for a long time. 1 week ago I decided to upgrade to version 2.6.1. After release I get claims from users. Claims are about problem with playing video. Only first frame is rendered or grey box. Only audio is working normally.

Users who reported about problem with 1 star have following devices:
Redmi Note 4 (mido)
M8S_PRO_W
nexbox_a95x
g_eight
q201
Mi Max 2
Redmi 4 pro
Redmi 5a
q201_9377
p212 (most popular)
q201
p281
MI MAX 2 (oxygen)
P9 lite (HWVNS-H)
m3note

Devices have Android 5, 6, 7.

I returned back to 2.4.4 and problem was solved.

Video codec H264 avc1.64001e

**Comment by tonihei** [comment] 2018-02-12 14:54
We are not aware of such an issue yet and it's not possible to find the reason without some sample media to reproduce the problem. Could you provide a sample and reproduction steps here or by sending an email to dev.exoplayer@gmail.com?

**Comment by tonihei** [comment] 2018-02-15 16:08
I tried to reproduce using a Redmi Note 4 and the example stream you have sent via email. Plays perfectly fine for me in our demo app. Are you able to reproduce this problem in our demo app or only in your own app. If you can see it in the demo app, can you describe what you did to reproduce the bug?

**Comment by AntonAndev** [comment] 2018-02-15 17:41
I do not have device from this list :(

**Comment by tonihei** [comment] 2018-02-15 17:50
I also only have the mentioned Redmi Note 4 and it works fine, so maybe it doesn't affect all of the devices in your list? Can you attempt to recreate the issue somehow? 

As I guess, it might be related to #3835 or #3439 - but in these cases, we never saw that the first frame was rendered or the audio continued. So the guess might be completely wrong.

**Comment by ojw28** [comment] 2018-02-26 19:02
Closing due to lack of actionable information.

**Closed as completed by ojw28** 2018-02-26 19:02 UTC
Labels: need more info
