### ISSUE TITLE
Sometimes Video Rotates automatically sometimes not in viewpager when scroll up for video rotation degree is 90 in metadata

### ISSUE THREAD

**Issue by Manli123** [google/ExoPlayer#10814] opened 2022-11-25 09:49 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

All versions of android

### Reproducible in the demo app?

Yes

### Reproduction steps

I am using this to decode video.

```
DefaultRenderersFactory rf = new DefaultRenderersFactory(mContext)
                .setExtensionRendererMode(EXTENSION_RENDERER_MODE_PREFER).setMediaCodecSelector(
                        new MediaCodecSelector() {
                            @Override
                            public List<MediaCodecInfo> getDecoderInfos(String mimeType,
                                                                        boolean requiresSecureDecoder, boolean requiresTunnelingDecoder)
                                    throws MediaCodecUtil.DecoderQueryException {
                                List<MediaCodecInfo> decoderInfos = MediaCodecSelector.DEFAULT
                                        .getDecoderInfos(mimeType, requiresSecureDecoder, requiresTunnelingDecoder);
                                if (MimeTypes.VIDEO_H264.equals(mimeType)) {
                                    // copy the list because MediaCodecSelector.DEFAULT returns an unmodifiable list
                                    decoderInfos = new ArrayList<>(decoderInfos);
                                    Collections.reverse(decoderInfos);
                                }
                                return decoderInfos;
                            }
                        });

  exoPlayer = new ExoPlayer.Builder(holder.mVideoView.getContext(),rf).setLoadControl(loadControl).build();


    holder.mVideoView.setPlayer(exoPlayer);

        holder.mVideoView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM);
        holder.mVideoView.setShutterBackgroundColor(Color.TRANSPARENT);
        holder.mVideoView.setKeepContentOnPlayerReset(true);
        exoPlayer.seekTo(0);
        exoPlayer.setRepeatMode(Player.REPEAT_MODE_ONE);

         mediaSource = new ProgressiveMediaSource.Factory(
                new CacheDataSource.Factory()
                        .setCache(SimpleMediaPlayer.getInstance(mContext))
                        .setUpstreamDataSourceFactory(new DefaultHttpDataSource.Factory()
                                .setUserAgent(mContext.getString(R.string.app_name)))
                        .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
        ).createMediaSource(MediaItem.fromUri(videoItem.videoURL));

        exoPlayer.addMediaSource(mediaSource);

        exoPlayer.prepare();

        exoPlayer.setPlayWhenReady(true);
        exoPlayer.play();

```

### Expected result

Video play with correct rotation.

### Actual result

it rotates video sometimes and sometimes not.

### Media

any media url.It randomly rotates.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by Manli123** [comment] 2022-11-28 14:12
is anyone checking this?Or anyone has solution for this.I know it is because renders factory but if i did not use it then i am not able to play high resolution video.Please tell me what will be solution for this.

**Comment by marcbaechinger** [comment] 2022-12-12 10:33
Closing as a duplicate of #10835

**Closed as completed by marcbaechinger** 2022-12-12 10:33 UTC
Labels: duplicate, wont fix: app issue
