### ISSUE TITLE
How to update ClippingMediaSource start position and end position dynamically

### ISSUE THREAD

**Issue by zivids** [google/ExoPlayer#7368] opened 2020-05-12 15:25 UTC
Hi, I found the updateClipping(long startUs, long endUs) in ClippingPeriod class, but not found in ClippingMediaSource. How to update clipping dynamically?

**Comment by andrewlewis** [comment] 2020-05-12 15:40
Duplicate of #3163.

**Closed as completed by andrewlewis** 2020-05-12 15:40 UTC
Labels: duplicate
