### ISSUE TITLE
ArrayIndexOutOfBounds when playing MP4 audio stream

### ISSUE THREAD

**Issue by pflammertsma** [google/ExoPlayer#601] opened 2015-07-06 13:34 UTC
We're attempting to stream from two MP4 files simultaneously--one for audio and one for video. The video track in itself plays fine, but singling out the audio or playing it in conjunction gives the following internal exception:

    Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
        at com.google.android.exoplayer.util.ParsableByteArray.readInt(ParsableByteArray.java:190)
        at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:116)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:234)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:615)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
    Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
        at com.google.android.exoplayer.util.ParsableByteArray.readInt(ParsableByteArray.java:190)
        at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:116)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:234)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:615)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
    Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
        at com.google.android.exoplayer.util.ParsableByteArray.readInt(ParsableByteArray.java:190)
        at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:116)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:234)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:615)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
    Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
        at com.google.android.exoplayer.util.ParsableByteArray.readInt(ParsableByteArray.java:190)
        at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:116)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:234)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
        at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:615)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

The MP4 audio file that causes this problem can be found here:  
http://pixplicity.com/tests/mp4-audio.mp4

I'm attempting to play the file using the Mp4Extractor, only slightly modified from the DemoPlayer sample code, such that the audio URL is provided separately. My changes around ExtractorRendererBuilder are:

    @Override
    public void buildRenderers(DemoPlayer player, DemoPlayer.RendererBuilderCallback callback) {
        // Build the video and audio renderers.
        DataSource dataSourceVideo = new DefaultUriDataSource(context, userAgent);
        ExtractorSampleSource sampleSourceVideo = new ExtractorSampleSource(
                videoUri, dataSourceVideo, extractor, 2,
                BUFFER_SIZE);
        ExtractorSampleSource sampleSourceAudio;
        if (audioUri == null) {
            sampleSourceAudio = sampleSourceVideo;
        } else {
            DataSource dataSourceAudio = new DefaultUriDataSource(context, userAgent);
            sampleSourceAudio = new ExtractorSampleSource(
                    audioUri, dataSourceAudio, extractor, 2,
                    BUFFER_SIZE);
        }
        MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(
                sampleSourceVideo,
                null, true, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 5000, null, player.getHandler(),
                player, 50);
        MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(
                sampleSourceAudio,
                null, true, player.getHandler(), player);

        // Build the debug renderer.
        TrackRenderer debugRenderer = debugTextView != null
                ? new DebugTrackRenderer(debugTextView, player, videoRenderer) : null;

        // Invoke the callback.
        TrackRenderer[] renderers = new TrackRenderer[DemoPlayer.RENDERER_COUNT];
        renderers[DemoPlayer.TYPE_VIDEO] = videoRenderer;
        renderers[DemoPlayer.TYPE_AUDIO] = audioRenderer;
        renderers[DemoPlayer.TYPE_DEBUG] = debugRenderer;
        callback.onRenderers(null, null, renderers);
    }

Let me know if there's anything I can do to help diagnose the problem.

**Comment by pflammertsma** [comment] 2015-07-06 13:44
Using FragmentMp4Extractor plays the audio file without any problems.

I don't know if this is related, though, but providing the separate video and audio files causes the ExoPlayer to indefinitely hang on the preparing state.

**Comment by andrewlewis** [comment] 2015-07-06 17:53
FragmentedMp4Extractor is the right extractor to use for this file, as it contains a movie fragment (moof) box. We hope to add format sniffing soon (#438), which will hopefully avoid the confusion!

Playback seems to work using that extractor. Did you see any other problems when you switched to the fragmented MP4 extractor, or can I close the issue? Thanks.

**Comment by iNdieboyjeff** [comment] 2015-07-07 08:22
I also very occasionally get a similar error when playing HLS

```
com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=9; index=9
       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=9; index=9
       at com.google.android.exoplayer.util.ParsableBitArray.readBits(ParsableBitArray.java:147)
       at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.parseHeader(TsExtractor.java:544)
       at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:463)
       at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:147)
       at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:225)
       at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:110)
       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by pflammertsma** [comment] 2015-07-07 10:46
Yes, thanks @andrewlewis, this issue can be closed unless @iNdieboyjeff's issue is relevant.

I sorted out my problems with getting two separate file streams playing by providing separate Extrators. It would be nice if ExoPlayer figured out for itself if FragmentedMp4Extractor is needed, as I can't tell from my source what the contents of the MP4 is.

**Comment by andrewlewis** [comment] 2015-07-07 16:05
@iNdieboyjeff That looks like a separate issue. I'd be grateful if you could open a bug with a sample stream and steps to reproduce the error so we can take a look.

**Closed by andrewlewis** 2015-07-07 16:05 UTC

**Comment by gongshoudao** [comment] 2015-09-04 16:18
I found this bug,if open Proguard
