### ISSUE TITLE
Play MergingMediaSource media,When i select track with a erro

### ISSUE THREAD

**Issue by wangxuan217** [google/ExoPlayer#8066] opened 2020-10-12 06:37 UTC
### These My Code

``` java
mTrackSelector = new DefaultTrackSelector(this);
mVideoPlayer = new SimpleExoPlayer.Builder(this).setTrackSelector(mTrackSelector).build();
```

``` java
 MediaSource audioSource = new ProgressiveMediaSource.Factory(new FileDataSource.Factory())
            .createMediaSource(MediaItem.fromUri("/storage/ra1_sda1/test/74898-m.wav"));
        MediaSource videoSource = new ProgressiveMediaSource.Factory(new FileDataSource.Factory())
            .createMediaSource(MediaItem.fromUri("/storage/ra1_sda1/test/74898.mp4"));
        mVideoPlayer.setMediaSource(new MergingMediaSource(true,videoSource, audioSource), true);
        mVideoPlayer.prepare();
        mVideoPlayer.setPlayWhenReady(true);
```

``` java
// index: 0 is mp4 track,2 is wav track
 public void testTrack(int index)
    {
        MappingTrackSelector.MappedTrackInfo mappedTrackInfo = mTrackSelector.getCurrentMappedTrackInfo();
        TrackGroupArray rendererTrackGroups = mappedTrackInfo.getTrackGroups(1);
        DefaultTrackSelector.SelectionOverride selectionOverride = new DefaultTrackSelector.SelectionOverride(index, 0);
        mTrackSelector.setParameters(
            mTrackSelector.buildUponParameters().setSelectionOverride(1, rendererTrackGroups, selectionOverride));
    }
```

### when use teskTrack method is erro with log 

``` java
10-12 14:22:12.747 15561-15592/com.whitesky.exoplayertest W/DefaultLoadControl: Target buffer size reached with less than 500ms of buffered media data.
10-12 14:22:12.747 15561-15592/com.whitesky.exoplayertest W/DefaultLoadControl: Target buffer size reached with less than 500ms of buffered media data.
10-12 14:22:12.749 15561-15592/com.whitesky.exoplayertest E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:959)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

### Here's is my 2.10.5 code 

``` java
  mTrackSelector = new DefaultTrackSelector();
 mVideoPlayer = ExoPlayerFactory.newSimpleInstance(this, mTrackSelector);
```

``` java
    MediaSource audioSource = new ProgressiveMediaSource.Factory(new FileDataSourceFactory())
            .createMediaSource(Uri.parse("/storage/ra1_sda1/test/74898-m.wav"));
        MediaSource videoSource = new ProgressiveMediaSource.Factory(new FileDataSourceFactory())
            .createMediaSource(Uri.parse("/storage/ra1_sda1/test/74898.mp4"));
        mVideoPlayer.prepare(new MergingMediaSource(videoSource, audioSource), true, false);
        mVideoPlayer.setPlayWhenReady(true);
```

``` java
 public void testTrack(int index)
    {
        MappingTrackSelector.MappedTrackInfo mappedTrackInfo = mTrackSelector.getCurrentMappedTrackInfo();
        TrackGroupArray rendererTrackGroups = mappedTrackInfo.getTrackGroups(1);
        DefaultTrackSelector.SelectionOverride selectionOverride = new DefaultTrackSelector.SelectionOverride(index, 0);
        mTrackSelector.setParameters(
            mTrackSelector.buildUponParameters().setSelectionOverride(1, rendererTrackGroups, selectionOverride));
    }
```
@krocard  @marcbaechinger 

### The Version 2.11.8 is right, too

**Comment by wangxuan217** [comment] 2020-10-13 09:55
@icbaker hi  can you look this question.

**Comment by marcbaechinger** [comment] 2020-10-13 09:59
The log lines tell that the player is stuck with an almost empty buffer, but the load control decided not to load. The `DefaultLoadControl` reports this already just before the exception occurs. 

I was able to run the such a merged source with http:// and a file:///android_asset/video.mp4 with the `DefaultDataSourceFactory`. I didn't got this to work with such an absolute path into `/storage/`. Can you try with a http url or an asset file as well, so we can see whether the problem is specific to when reading from an sdcard with an absolute path?

If it does not work with the sdcard path but works with http, please provide a bug report.

**Comment by wangxuan217** [comment] 2020-10-13 10:02
> The log lines tell that the player is stuck with an almost empty buffer, but the load control decided not to load. The `DefaultLoadControl` reports this already just before the exception occurs.
> 
> I was able to run the such a merged source with http:// and a file:///android_asset/video.mp4 with the `DefaultDataSourceFactory`. I didn't got this to work with such an absolute path into `/storage/`. Can you try with a http url or an asset file as well, so we can see whether the problem is specific to when reading from an sdcard with an absolute path?
> 
> If it does not work with the sdcard path but works with http, please provide a bug report.

ok I try to do this, and give you a reply. @marcbaechinger

**Comment by wangxuan217** [comment] 2020-10-13 10:22
hi @marcbaechinger I try to use asset way, but the erro is same.

``` java
MediaSource audioSource = new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(this))
            .createMediaSource(Uri.parse("file:///android_asset/74898-m.wav"));
        MediaSource videoSource = new ProgressiveMediaSource.Factory(new  DefaultDataSourceFactory(this))
            .createMediaSource(Uri.parse("file:///android_asset/74898.mp4"));
        mVideoPlayer.prepare(new MergingMediaSource(videoSource, audioSource), true, false);
        mVideoPlayer.setPlayWhenReady(true);
```

``` java
10-13 18:19:48.472 17698-17727/com.whitesky.exoplayertest E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:959)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 

```
The http way,I still need some time to build the environment.I guess the result is the same.The video is play normally.when 
i try to change track, the erro occurred. and the version 2.11.8 is have not this erro,the play is right

**Comment by marcbaechinger** [comment] 2020-10-13 11:50
That's great, thanks!

Can you make the media available to me so I can test whether it's a problem with that specific media only? When I try the http approach with [media from the demo samples it works fine](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json#L353). If it works with that media we probably need to look into this with the exact same media you are using to rule out a problem of the media or a problem of ExoPlayer with that specific media.

**Comment by wangxuan217** [comment] 2020-10-14 01:22
ok the file is a large file , this limit 10MB ,so I will try to upload my GitHub ,but the large file limit, too.I try to change other file with play.so have same error,I think the media file is No problem. when i play only one media file like this

``` java
 MediaSource videoSource = new ProgressiveMediaSource.Factory(new  FileDataSource.Factory())
            .createMediaSource(MediaItem.fromUri("/storage/ra1_sda1/test/74898.mp4"));
        mVideoPlayer.setMediaSource(videoSource);
        mVideoPlayer.prepare();
        mVideoPlayer.setPlayWhenReady(true);
```

and I select track like this

``` java
// @param original true 0 track, false 1 track
public void setPlayTrack(boolean original)
    {
        MappingTrackSelector.MappedTrackInfo trackInfo = mTrackSelector.getCurrentMappedTrackInfo();
        if (trackInfo != null)
        {
            if (original)
            {
                mTrackSelector.setParameters(mTrackSelector.buildUponParameters()
                    .setSelectionOverride(1,
                        trackInfo.getTrackGroups(1),
                        new DefaultTrackSelector.SelectionOverride(1, 0)));
            }
            else
            {
                mTrackSelector.setParameters(mTrackSelector.buildUponParameters()
                    .setSelectionOverride(1,
                        trackInfo.getTrackGroups(1),
                        new DefaultTrackSelector.SelectionOverride(0, 0)));
            }
        }
    }
```

this is no problem,It can change track, when i use **MergingMediaSource** and select track ,the error happened.So I think question is when i use  **MergingMediaSource**,how to switch tracks correctly.I change track, like this
``` java
// index: 0 is mp4 track,2 is wav track
 public void testTrack(int index)
    {
        MappingTrackSelector.MappedTrackInfo mappedTrackInfo = mTrackSelector.getCurrentMappedTrackInfo();
        TrackGroupArray rendererTrackGroups = mappedTrackInfo.getTrackGroups(1);
        DefaultTrackSelector.SelectionOverride selectionOverride = new DefaultTrackSelector.SelectionOverride(index, 0);
        mTrackSelector.setParameters(
            mTrackSelector.buildUponParameters().setSelectionOverride(1, rendererTrackGroups, selectionOverride));
    }
```

These code is right in Exoplayer 2.11.8 and I can to change track.The error occurred in version 2.12.0. So I don't understand what's change in 2.12.0 with **MergingMediaSource**
@marcbaechinger

**Comment by marcbaechinger** [comment] 2020-10-14 16:13
Can you play the wave file standalone too?

```
 MediaSource videoSource = new ProgressiveMediaSource.Factory(new  FileDataSource.Factory())
            .createMediaSource(MediaItem.fromUri("/storage/ra1_sda1/test/74898-m.wav"));
```

**Comment by wangxuan217** [comment] 2020-10-15 01:27
> Can you play the wave file standalone too?
> 
> ```
>  MediaSource videoSource = new ProgressiveMediaSource.Factory(new  FileDataSource.Factory())
>             .createMediaSource(MediaItem.fromUri("/storage/ra1_sda1/test/74898-m.wav"));
> ```

yes ,the wave file play standalone too.the mp4 and wav are play standalone too, these can Merge play but they can't select track, when i try to select track, the error is occurred.I think you can try to use ** MergingMediaSource**,and merge two media file play,and change one of them track.I think the erro is occurred, too.

or

you can give me two media urls,I verify http way.

@marcbaechinger

**Comment by marcbaechinger** [comment] 2020-10-15 09:59
It worked for me with these two files:

Audio: https://storage.googleapis.com/exoplayer-test-media-1/gen-3/screens/dash-vod-single-segment/audio-141.mp4"
Video: https://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv

**Comment by wangxuan217** [comment] 2020-10-15 10:05
> It worked for me with these two files:
> 
> Audio: https://storage.googleapis.com/exoplayer-test-media-1/gen-3/screens/dash-vod-single-segment/audio-141.mp4"
> Video: https://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv
excuse, can you take me, how to change track's method?
@marcbaechinger

**Comment by wangxuan217** [comment] 2020-10-15 10:23
HI  @marcbaechinger I use you take mine media file,I test the code
``` java
 MediaSource audioSource = new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(this))
            .createMediaSource(MediaItem.fromUri("/storage/ra1_sda1/test/audio-141.mp4"));
        MediaSource videoSource = new ProgressiveMediaSource.Factory(new  DefaultDataSourceFactory(this))
            .createMediaSource(MediaItem.fromUri("/storage/ra1_sda1/test/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv"));
        mVideoPlayer.setMediaSource(new MergingMediaSource(true,videoSource, audioSource), true);
        mVideoPlayer.prepare();
        mVideoPlayer.setPlayWhenReady(true);
```

select track code 

``` java
 public void testTrack(int index)
    {
        MappingTrackSelector.MappedTrackInfo mappedTrackInfo = mTrackSelector.getCurrentMappedTrackInfo();
        // rendererIndex 0 为视频渲染索引 1为音频渲染索引
        TrackGroupArray rendererTrackGroups = mappedTrackInfo.getTrackGroups(1);
        // groupIndex 0 1 为视频的音轨 2为混合后音频音轨
        DefaultTrackSelector.SelectionOverride selectionOverride = new DefaultTrackSelector.SelectionOverride(index, 0);
        mTrackSelector.setParameters(
            mTrackSelector.buildUponParameters().setSelectionOverride(1, rendererTrackGroups, selectionOverride));
    }
```

the error is same, so can you take me, how to select track for you.

**Comment by wangxuan217** [comment] 2020-10-16 09:30
so can you tell me how to use select tarck with MergingMediaSource. @marcbaechinger

**Comment by wangxuan217** [comment] 2020-10-19 01:37
hi @marcbaechinger V2.12.0 how to select track with MergingMediaSource and it is used MediaItem? can you take me doc or example, thanks!

**Comment by wangxuan217** [comment] 2020-10-20 10:03
hi  I hope you can give me some help. thanks @marcbaechinger

**Comment by wangxuan217** [comment] 2020-10-21 01:13
v2.12.0 how to select track with merge media @ojw28

**Comment by icbaker** [comment] 2020-10-21 08:28
@Dreamxiaoxuan Please stop spamming this issue and tagging random people - it's not going to make us help you any faster.

**Comment by wangxuan217** [comment] 2020-10-21 09:21
ok   @icbaker i am so sorry.
 but i find the question, when i use android studio debug these code 
``` java
MappingTrackSelector.MappedTrackInfo mappedTrackInfo = mTrackSelector.getCurrentMappedTrackInfo();
        TrackGroupArray rendererTrackGroups = mappedTrackInfo.getTrackGroups(1);
        DefaultTrackSelector.SelectionOverride selectionOverride = new DefaultTrackSelector.SelectionOverride(index, 0);
        mTrackSelector.setParameters(
            mTrackSelector.buildUponParameters().setSelectionOverride(1, rendererTrackGroups, selectionOverride));
```
the erro is nothing, so i think when i select track maybe need some times, but 2.11.8 version is don't need these time,i think pay attention to this issue.

The log
``` java
10-21 17:13:26.842 11569-11600/com.whitesky.exoplayertest E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:959)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

I am sorry to you,Again.   i am very thanks to you and your team give me help.

**Comment by marcbaechinger** [comment] 2020-10-21 12:37
Thanks for your patience!

I tried your use case out by modifying the demo app with media uri `file:///android_asset/...` and a merged media source. I used the track selection dialog of the demo app to change tracks and this worked for me without exceptions or the like. 

For me this is working (see below as well). Im testing with the media as reported in [my comment above](https://github.com/google/ExoPlayer/issues/8066#issuecomment-709061510).

I asked you to make your media available [in this comment](https://github.com/google/ExoPlayer/issues/8066#issuecomment-707686433) but you've chosen not to.

Please see the snippet. If this does not work for you, please send me your media if you want me to look into this again.

Here is how I prepare the player in the `PlayerActivity` of the demo app:
```
    MediaSource videoSource = new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(this))
        .createMediaSource(MediaItem.fromUri("file:///android_asset/video.mkv"));
    MediaSource audioSource = new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(this))
        .createMediaSource(MediaItem.fromUri("file:///android_asset/audio.mp3"));
    player.setMediaSource(new MergingMediaSource(videoSource, audioSource));

    player.prepare();
```

Then in `onTrackChanged` I select the audio track from the audio file merged in above:
```
@Nullable MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
if (mappedTrackInfo != null) {
  for (int i = 0; i < mappedTrackInfo.getRendererCount(); i++) {
    if (mappedTrackInfo.getRendererType(i) == C.TRACK_TYPE_AUDIO) {
      trackSelector.setParameters(
          trackSelector.buildUponParameters()
              .setSelectionOverride(
                  i,
                  mappedTrackInfo.getTrackGroups(/* rendererIndex= */ i),
                  // this selects the first track of the second track group. Please note this is hardcoded according to 
                 //  how the MergingMediaSource above is setup
                  new DefaultTrackSelector.SelectionOverride(
                      /* groupIndex= */ 1, /* tracks= */ 0)));
      break;
    }
  }
}
```

**Comment by wangxuan217** [comment] 2020-10-22 02:00
ok thanks i try to test your media file, and Let me demonstrate the debug steps below.


###  1.Create a new button to switch the audio tracks for video and audio files.
![1](https://user-images.githubusercontent.com/8827749/96808065-ac8d2a00-144a-11eb-997d-42b4eefb38bf.jpg)
![2](https://user-images.githubusercontent.com/8827749/96808074-b151de00-144a-11eb-8054-cb4ac80d5ac8.jpg)
![3](https://user-images.githubusercontent.com/8827749/96809337-435ae600-144d-11eb-9e73-f5fc38fa9b54.jpg)

###  2.From the figure above, we can see that the video file has two tracks, the index 0 and 1, and the audio file has a track, which is the index 2.
### 3.With the button we pass in 0 or 2 to control whether the switch track is from a video file or an audio file.
### 4.the method code like this

``` java
// 0 is video's track,2 is audio's track
private void test(int index)
{
    @Nullable MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
if (mappedTrackInfo != null) {
  for (int i = 0; i < mappedTrackInfo.getRendererCount(); i++) {
    if (mappedTrackInfo.getRendererType(i) == C.TRACK_TYPE_AUDIO) {
      trackSelector.setParameters(
          trackSelector.buildUponParameters()
              .setSelectionOverride(
                  i,
                  mappedTrackInfo.getTrackGroups(/* rendererIndex= */ i),
                  // this selects the first track of the second track group. Please note this is hardcoded according to 
                 //  how the MergingMediaSource above is setup
                  new DefaultTrackSelector.SelectionOverride(
                      /* groupIndex= */ index, /* tracks= */ 0)));
      break;
    }
  }
}
}
```

### 5. You quickly switch between video and audio tracks,and the error is happened.My question is why there is no such problem in version 2.11.8.the error is happen in 2.12.0

### android logcat 

``` java
10-22 09:52:50.816 12667-12697/com.whitesky.exoplayertest E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:959)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

or my use way 

``` java
  findViewById(R.id.bt_test).setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View v)
            {
                if (!isOrigin)
                {
                    mPresentationService.test(0);
                    isOrigin = true;
                }else {
                    mPresentationService.test(2);
                    isOrigin = false;
                }

            }
        });
```

@marcbaechinger

**Comment by marcbaechinger** [comment] 2020-10-22 10:00
Please send me your media so I can test with the media.

**Comment by marcbaechinger** [comment] 2020-10-22 10:34
```
// 0 is video's track,2 is audio's track
private void test(int index)
```

I think the above statement is not entirely correct when you say 2 is audio track. 

Please look at the snippet I sent you:

```
@Nullable MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
if (mappedTrackInfo != null) {
  for (int i = 0; i < mappedTrackInfo.getRendererCount(); i++) {
    if (mappedTrackInfo.getRendererType(i) == C.TRACK_TYPE_AUDIO) {
      trackSelector.setParameters(
          trackSelector.buildUponParameters()
              .setSelectionOverride(
                  i,
                  mappedTrackInfo.getTrackGroups(/* rendererIndex= */ i),
                  // this selects the first track of the second track group. 
                  new DefaultTrackSelector.SelectionOverride(
                      /* groupIndex= */ 1, /* tracks= */ 0))); 
      break;
    }
  }
}
```
There are two renderer. A video renderer and an audio renderer. In you case with a merging media source, the audio renderer that is identified with `mappedTrackInfo.getRendererType(i) == C.TRACK_TYPE_AUDIO` has two track groups. the first track group is the audio track coming from the video file. The second track group is coming from the audio file that is merged in.

> we pass in 0 or 2

I don't think that you need to pass an index of 2 anywhere in this example because this is an index of 2 refers to the third track group, but there are only two track groups for the audio renderer.

**Comment by wangxuan217** [comment] 2020-10-23 01:33
**index2** (the mark in figure3)is from WAV file, I can find that there's only one track in WAV file by the audio tools, also can find that there's two tracks in the MP4 file(figure1, figure2), they means **index0** and **index1**, so I want to select the track from WAV file and pass in 2. but the result you gave, in my opinion,  says that the track is merged by the WAV and MP4 files, is this right? but the what it plays definitely comes from WAV file under version 1.1.8, so according to your answer, if the merged track is in the **index1** after version 2.12.0? @marcbaechinger

**Comment by marcbaechinger** [comment] 2020-12-21 20:30
Closing due to inactivity.

**Closed as completed by marcbaechinger** 2020-12-21 20:30 UTC
Labels: question
