### ISSUE TITLE
SegmentBase getSegmentTimeUs does not perform a bounds check, results in out of bounds error

### ISSUE THREAD

**Issue by kamaroyl** [google/ExoPlayer#11014] opened 2023-02-24 02:59 UTC
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

* Pixel 6 Pro

### Reproducible in the demo app?

Yes

### Reproduction steps

Provide a dash manifest with an empty segmentTimeline, `getSegmentTimeUs` attempts to index into `segmentTimeline` which is empty, resulting in an  out of bounds error.

### Expected result

Something other than an out of bounds error, perhaps an error or warn that the segmentTimeline is empty.

### Actual result

Index out of bounds exception

### Media

This was the mpd in question. May violate DASH spec, but a more useful error would be appreciated
[DASH_EXAMPLE.zip](https://github.com/google/ExoPlayer/files/10820260/DASH_EXAMPLE.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment] 2023-02-27 15:53
The attached MPD fails to parse because it has `id="2-sd-video"` in one of the `AdaptationSet` nodes, which is just not allowed because the value is supposed to be an unsigned integer. Even if I hackily ignore this issue in code, I can't see the problem with `getSegmentTimeUs` you are describing? It would also help to see a stack trace to know how the problem is triggered.

**Comment by kamaroyl** [comment] 2023-03-06 01:03
Ah, apologies, that was an early pass when the packager was putting in the wrong id. I'm able to reproduce by hosting this mpd with a python simple http server and setting the ExoPlayer demo to allow clear text traffic.
[ExoPlayerException.zip](https://github.com/google/ExoPlayer/files/10893480/ExoPlayerException.zip)

**Comment by tonihei** [comment] 2023-03-07 11:30
Thanks, we'll provide a fix for this.

**Closed as completed** 2023-04-04 08:33 UTC
Labels: bug
