### ISSUE TITLE
Disabling autoplay in ConcatenatingMediaSource

### ISSUE THREAD

**Issue by AndrazP** [google/ExoPlayer#6665] opened 2019-11-18 12:21 UTC
### [REQUIRED] Searched documentation and issues
Checked ConcatenatingMediaSource, TimelineQueueNavigator, Player.EventListener documentation and source code.

### [REQUIRED] Question
Is it possible to disable Disable autoplay in ConcatenatingMediaSource?
I tried to pause the player in onPositionDiscontinuity (if the reason of discontinuity is DISCONTINUITY_REASON_PERIOD_TRANSITION), but the player still plays like 1-2 seconds of the next source.

**Comment by AquilesCanta** [comment] 2019-11-18 14:02
@tonihei mind having a look?

**Comment by tonihei** [comment] 2019-11-18 14:15
That's a duplicate of #5660.

**Closed as completed by tonihei** 2019-11-18 14:15 UTC
Labels: duplicate

**Comment by AndrazP** [comment] 2019-11-19 10:31
Hi @tonihei,
thanks for linking to the similar question, it didn't show up in my search results.

So if I **summarise** the linked thread, **it's not possible to disable/stop** autoplay in ConcatenatingMediaSource before proceeding to next video.

**I kindly ask you to consider supporting this case.**
My application is similar to YouTube Premium. Video playback in foreground, audio in background.
Why I would still like to use ConcatenatingMediaSource vs. preparing one by one:
- Correct media session and notification handling out of the box. If media sources are prepared one by one media notification shows incorrect state of skip to next(>>) action.
I had to extend [QueueNavigator](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.QueueNavigator.html), [MediaMetadataProvider](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.DefaultMediaMetadataProvider.html) and add some workarounds to support media notifications. 
Example: Player timeline is empty between switching media sources, MediaMetadataProvider can not extract MediaMetadata and MediaController is not able to receive MediaMetadata needed to show in notification. Skipping between items from notification is not smooth.
- Build in lazy preparation, nicer transitions between videos.
