### ISSUE TITLE
Changing sideloading subtitle track with hls contents, video/audio renderers are resetted for a while

### ISSUE THREAD

**Issue by HyowonHwang** [google/ExoPlayer#10248] opened 2022-05-09 05:43 UTC
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Samsung Z Flip3 os 12
All devices.

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Add information of external subtitle to any hls contents in `media.exolist.json`

  ``` json
 {
        "name": "Apple multivariant playlist advanced (TS)",
        "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8",
        "subtitle_uri": "https://storage.googleapis.com/exoplayer-test-media-1/webvtt/numeric-lines.vtt",
        "subtitle_mime_type": "text/vtt",
        "subtitle_language": "en"
      }
```
2. Change text track to external subtitle.
3. Player state change to `Buffering` -> `Ready` shortly.

### Expected result

It should change without reset of audio/video renderers.

This only happen playing external subtitles when playing hls contents.

With 2.16.0 release, it goes well. 

### Actual result

  Audio/Video renderers  are resetted for a while.

### Media

Modify media from demo app

  ``` json
 {
        "name": "Apple multivariant playlist advanced (TS)",
        "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8",
        "subtitle_uri": "https://storage.googleapis.com/exoplayer-test-media-1/webvtt/numeric-lines.vtt",
        "subtitle_mime_type": "text/vtt",
        "subtitle_language": "en"
      }
```

### Bug Report

**Comment by tonihei** [comment] 2022-05-17 13:47
Thanks for reporting! This is indeed a bug we introduced in 2.17.0 caused by a missing `equals` method. We'll provide a fix in the next release.

**Comment by HyowonHwang** [comment] 2022-05-18 06:55
@tonihei Thanks for response. I will check it again with next release.

**Comment by tonihei** [comment] 2022-06-09 12:46
This is fixed by the commit above.

**Closed as completed by tonihei** 2022-06-09 12:46 UTC
Labels: bug
