### ISSUE TITLE
Video freezes (but audio continue playing)

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#5195] opened 2018-12-04 15:30 UTC
### Issue description
Video freezes at 00:24. I've recorded this moment - https://yadi.sk/i/0dl088vxwNxD5w. Audio plays successfully all the time (before and after freeze's moment).

Logcat shows the next messages during freezing:
12-04 18:29:27.133 W/SoftAAC2(15602): aacDecoder_DecodeFrame decoderErr = 0x4004
12-04 18:29:27.133 W/SoftAAC2(15602): AAC decoder returned error 0x4004, substituting silence

### Link to test content
http://stand.netup.tv/downloads/T2965/manifest.m3u8

### Version of ExoPlayer being used
2.9.1

### Device(s) and version(s) of Android being used
STB GIEC MP1113 (chip Amlogic s905x)
STB Geniatech 495X (chip Amlogic s905x)
Android 6.0.1 (on both devices)

### A full bug report captured from the device
[bugreport.txt](https://github.com/google/ExoPlayer/files/2644645/bugreport.txt) (from GIEC device)

**Comment by erdemguven** [comment] 2018-12-05 17:55
I tried the media on exoplayer demo app on Android 7 and VLC.
On both the video doesn't freeze but gets corrupted.
Also on android I saw decoderErr line.
I'll try on a Android 6.0.1 device.

**Comment by tipoc123** [comment] 2018-12-06 11:12
Have you tried our media on Android 6.0.1 device?

**Comment by tipoc123** [comment] 2018-12-07 00:24
?

Currently, it's the last problem with our streams and we are all in great expectation.

**Comment by tipoc123** [comment] 2018-12-10 11:15
Any news about this issue? It's very important for us.

**Comment by tipoc123** [comment] 2018-12-13 12:11
Up!

**Comment by erdemguven** [comment] 2019-01-24 11:27
Sorry for late return, I finally tried on a Nexus 6 6.0.1 and couldn't reproduce the problem. It looks like a device specific issue.

**Comment by theprogrammerin** [comment] 2019-02-13 11:29
All these issues look similar to the following: 
https://github.com/google/ExoPlayer/issues/5323
https://github.com/google/ExoPlayer/issues/5488
https://github.com/google/ExoPlayer/issues/5444

**Comment by ojw28** [comment] 2019-03-06 19:03
You really need to be serving correctly formed media. Closing as bad media. What happens when malformed media is encountered may vary from device to device based on the underlying platform decoder implementations, however ultimately you shouldn't be serving malformed content in the first place.

**Closed as completed by ojw28** 2019-03-06 19:03 UTC
Labels: bad media
