### ISSUE TITLE
IMA extension: Playback ends before post roll completes

### ISSUE THREAD

**Issue by dbrain** [google/ExoPlayer#7552] opened 2020-06-26 12:27 UTC
### [REQUIRED] Issue description
When using the IMA extension on ad supported content with a post roll, the player frequently (>50% of the time from my guestimation) hits an ended state before the post roll has completed.

It also seems to not render the ad UI in the scenario where the ad will terminate before completion.

This was initially noticed in our application (iflix), we then dropped into the demo application to confirm it wasn't something dodgy in our code.

### [REQUIRED] Reproduction steps
- Open the demo app (built against 2.11.6 release-v2 with extensions enabled)
- Open any? of the IMA demos with post rolls, I've tried "VMAP post-roll", "VMAP pre,mid,post, single ads"
- Seek to just before the end
- Watch the post roll play and then end with the sample post roll timer at a value >1, in my testing so far the lowest I've seen it get, when it will fail, is 6 of 10s remaining.

You may need to repeat this a few times to see the issue reproduce. Personally it seems to happen 50% or more of the time, but I've seen it work a couple of times in a row before breaking again for e.g.

### [REQUIRED] Link to test content
This is reproducible in the demo app. But if necessary I can supply real world examples. 

### [REQUIRED] A full bug report captured from the device
[bugreport-marlin-QP1A.191005.007.A3-2020-06-26-22-23-46.zip](https://github.com/google/ExoPlayer/files/4836882/bugreport-marlin-QP1A.191005.007.A3-2020-06-26-22-23-46.zip)

### [REQUIRED] Version of ExoPlayer being used
Reproducible on 2.11.6 release in a real world app, but also reproduced on a 2.11.6 release-v2 demo build with extensions (as described above).
This also seems to be reproducible on 2.11.5 after checking out the tag and running the demo app. So it does not seem to be related to the fixes in 2.11.6.

I've also tested with the IMA version bumped to 3.19.2 (compared to 3.19.0 that ExoPlayer currently depends on) as it has some kind of fix around content completion. This did not improve the situation.

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel XL, Android 10.

**Comment by andrewlewis** [comment] 2020-06-26 14:12
I thought this was fixed by df10fdf773fae4715eed7593c04856b4fdc1e14f but then it wouldn't be reproducible on 2.11.6. I will take another look.

**Comment by andrewlewis** [comment] 2020-06-29 10:10
This appears to be fixed by eb9de7a120240d34f3cd40bacdffa5860dfa782a which will go into 2.11.7: on 2.11.6 I can repro the issue about 5/10 times, but with that fix I don't see the issue on 20 attempts.

**Comment by andrewlewis** [comment] 2020-06-29 13:52
@dbrain Please could you try reproducing this with r2.11.7 and let me know you can still get the same behavior? I will reopen this issue and take another look if so. Thanks!

**Closed as completed by andrewlewis** 2020-06-29 13:52 UTC
Labels: bug

**Comment by dbrain** [comment] 2020-06-30 03:27
Thanks @andrewlewis, seems to be working a lot better. 

Noticed a few little things, unsure if they are known issues/non-issues, but thought I'd mention to be annoying.

Demo app:
- If you seek far enough into content, e.g. 2 seconds left, it doesn't bother to snapback to midroll. Not sure if intentional.
- After playing until the end then leaving player seeing constant progress update logs. Seems like it's leaking some kind of listener? The more times I test the content the more frequent log lines, presumably from the listeners building up. IIRC there was a separate issue along these lines so might be a known issue. 
```D/ImaAdsLoader: Content progress: VideoProgressUpdate [currentTime=128.287, duration=128.266]```

Our app (i.e. real ads):
- Saw one instance of a midroll acting like post rolls did before your commit, i.e. it played for a few seconds with no ad UI then skipped. But can not reproduce to grab debug info. Gremlins.

**Comment by andrewlewis** [comment] 2020-06-30 07:49
Thanks for the extra information!

> If you seek far enough into content, e.g. 2 seconds left, it doesn't bother to snapback to midroll. Not sure if intentional.

This is a side effect of how postrolls got triggered originally (we triggered 'content complete' based on receiving a buffering even with the player position near the end). The IMA SDK now preloads postrolls so we may be able to get rid of this behavior, but I am skeptical about whether preloading of postrolls will continue to work as it does now indefinitely so wanted to keep the old behavior too for robustness, at least for the time being (related [Internal: b/156018896]).

> After playing until the end then leaving player seeing constant progress update logs. Seems like it's leaking some kind of listener? The more times I test the content the more frequent log lines, presumably from the listeners building up. IIRC there was a separate issue along these lines so might be a known issue.

I think I've seen this in the past but wasn't aware it was still happening. The IMA SDK is the component requesting content position so I think it should stop doing that after the `AdsManager` has been destroyed. It's likely that this is related to the leak in #7344, as the root cause of that is that the the WebView's message to clean up the ads manager never arrives back at the Java layer.

It is a bit inconvenient that the content progress update provider has to be set on the ads request not on the ads manager, and we don't currently keep a reference to the ads request, but it may be worth retaining it and trying to clear the progress updater by passing in `null` when we destroy the ads manager. Let me know if this workaround seems worth pursuing, otherwise I will advocate for getting #7344 fixed in the expectation that will resolve this.

> Saw one instance of a midroll acting like post rolls did before your commit, i.e. it played for a few seconds with no ad UI then skipped. But can not reproduce to grab debug info. Gremlins.

It would be useful to replicate this with `ImaAdsLoader.DEBUG = true` and get the logging to understand what is going on. The observed behavior suggests that we loaded the ad but the IMA SDK thinks we haven't started playing it.

**Comment by dbrain** [comment] 2020-07-05 23:29
@andrewlewis I've sent an email to `dev.exoplayer@...` with some additional logs/videos/charles logs of the midroll issue (plays for a few seconds with no ad UI then content continues). One of our testers seems to be able to consistently reproduce this, which is odd, as I'm struggling to make it happen to debug it properly. For context this is occurring when the player is dragged passed the cuepoint, and a snapback is occurring to play the skipped midroll ad.

It kind of looks like there's some kind of ad load timeout happening, which is then stopping the current ad. But I need to deep dive into ImaAdsLoader/IMA SDK in general to understand how it all works. I'm guessing (based on nothing and probably wrong) it's something like the ad mp4 is being muxed into the media source and loaded externally to the rest of the ads information, which loads via the IMA SDK at ad playback time, but the SDK side of that is failing in this instance triggering playback to resume mid playing the preloaded ad. 

It's kind of odd as it's getting a media load timeout (8s) but Charles does not have the request running anywhere near that long (5s max kind of thing), and the video ad is already playing. Could IMA not be wiring up the media load timeout correctly? We actually manually override it to 10s for media, 5s for VAST. Possible it's using the VAST value for media as well?
