### ISSUE TITLE
Degradation of the reading of a 50 fps stream between 2.12 and 2.16

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#10032] opened 2022-03-07 15:02 UTC
Hello,
	
	After testing the 50 fps streams on version 2.14, we noticed some degradations
	of the stream playback.
	Indeed, we have activated the configs in rendererFactory below: 
		RenderersFactory rendererFactory = new DefaultRenderersFactory(/* context= */ this)
		.setExtensionRendererMode(extensionRendererMode)
		  .experimentalSetAsynchronousBufferQueueingEnabled(true)
		  .experimentalSetForceAsyncQueueingSynchronizationWorkaround(true);
		  
    Despite the activation of these config, we still see the same behavior (without activation of the configs) as before 
	frequent freezes.
	Contrary to the version of ExoPlayer 2.12.3, the rendering is quite stable after the activation of the OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING mode via the config below:
	
	RenderersFactory rendererFactory = new DefaultRenderersFactory(context.getApplicationContext())
    .setExtensionRendererMode(extensionRendererMode)
    .experimentalSetVideoMediaCodecOperationMode(MediaCodecRenderer.OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING)
	
	Do you have any idea how to get the same behavior of 2.12 in 2.14? Do you have another configuration to get it?

BR,

**Comment by ojw28** [comment] 2022-03-07 19:22
Are you playing live streams, or on-demand?

If you're playing live streams, then I think I can probably suggest what's going on (and a workaround for it). If you're playing on-demand streams, then please provide a same test stream, as well as details about specifically which devices are affected by the change in performance. Thanks!

**Comment by Xlcghs** [comment] 2022-03-07 20:56
Thanks  for your quick return.
I play live stream content.

**Comment by ojw28** [comment] 2022-03-07 22:08
You can most likely workaround this problem by calling the following on `MediaItem.Builder` when creating a `MediaItem` to play:

```
mediaItemBuilder.setLiveMaxPlaybackSpeed(1);
mediaItemBuilder.setLiveMinPlaybackSpeed(1);
```

The problem is also fixed by upgrading to 2.17, so that would be another option.

**Comment by ojw28** [comment] 2022-03-07 22:49
An alternative workaround for 2.16, which is probably easier than the `MediaItem` approach described above, is to do the following when creating the player:

```
player =
    new ExoPlayer.Builder(...)
        ...
        .setLivePlaybackSpeedControl(
            new DefaultLivePlaybackSpeedControl.Builder()
                .setFallbackMinPlaybackSpeed(1f)
                .setFallbackMaxPlaybackSpeed(1f)
                .build())
        ...
        .build();
```

**Comment by ojw28** [comment] 2022-03-14 19:29
Closing for now. You can still reply here if the suggestions above don't resolve the issue, and we will re-open the issue. Thanks!

**Comment by Xlcghs** [comment] 2022-03-17 13:57
Hi,
Sorry for the late return.

We did some tests with the PlaybackSpeed configurations mentioned in your message.
But the problem is still there.

At startup, we had freezes and then the playback stabilizes.

FYI: this problem is not reproduced on version 2.12.3.

Do you have another way of correction ?

Can you please open this issue. Thank you

BR,

**Comment by Xlcghs** [comment] 2022-03-28 11:41
Do you have any news please?
Can you guide me to solve this problem?

Thank you.

**Comment by tonihei** [comment] 2022-05-04 12:38
Could you let us know which device(s) you are using for testing? And as mentioned above, it would be helpful to have a test stream in case it's media related (you can a send a link to dev.exoplayer@gmail.com with "Issue #10032" in the subject).

**Comment by Xlcghs** [comment] 2022-06-09 12:53
Hi,
The stream was sent privately to dev.exoplayer@gmail.com to reproduce the problem.
FYI, To access this stream can you give me your public IP of the test machine to allow it.

Best regards,

**Comment by tonihei** [comment] 2022-06-09 13:10
We can't really provide an IP address for accessing streams. Would it be possible to make this stream more accessible from any machine? 

And please also let us know which device exactly you are using for testing, because this is likely a device-specific issue.

**Comment by tonihei** [comment] 2022-11-01 15:53
I tested the stream you provided (sorry for the delay!), but can't see any frame freezes on the device I tested. As indicated above, this may likely be device specific and it would help if you can specify on which device you observed the issue.

**Closed as completed** 2022-11-29 02:04 UTC
Labels: question, closed-by-bot
