### ISSUE TITLE
SCTE-35 : timestamp adjustment is not used?

### ISSUE THREAD

**Issue by cdongieux** [google/ExoPlayer#11211] opened 2023-06-14 12:30 UTC
Hi,

I'm working on SCTE-35, it seems `Metadata` events (`TimeSignalCommand`s) are not rendered at the right time, but earlier. I'm on ExoPlayer 2.18.6, I'm using `DefaultRenderersFactory` so `MetadataRenderer.outputMetadataEarly` is set to `false`.

I'm wondering if this is related to the fact that `SpliceInfoDecoder` does not use adjusted timestamps extracted from `SpliceInsertCommand`/`TimeSignalCommand`. Don't these adjusted timestamps should be used somewhere in the Metadata rendering chain for them to be fired at the right time?

Best regards

**Comment by cdongieux** [comment] 2023-06-14 13:07
In deed, with something like this, Metadata events are rendered when expected:

In `SpliceInfoDecoder`:

```
  protected Metadata decode(MetadataInputBuffer inputBuffer, ByteBuffer buffer) {
    ....
    long presentationTimeUs = C.TIME_UNSET;
    switch (spliceCommandType) {
      case TYPE_SPLICE_NULL:
        command = new SpliceNullCommand(descriptors);
        break;
      case TYPE_SPLICE_SCHEDULE:
        command = SpliceScheduleCommand.parseFromSection(sectionData, descriptors);
        break;
      case TYPE_SPLICE_INSERT:
        command =
            SpliceInsertCommand.parseFromSection(sectionData, ptsAdjustment, timestampAdjuster,
                descriptors);
        break;
      case TYPE_TIME_SIGNAL:
        TimeSignalCommand timeSignalCommand = TimeSignalCommand.parseFromSection(sectionData, ptsAdjustment, timestampAdjuster,
            descriptors);
        presentationTimeUs = timeSignalCommand.playbackPositionUs;
        command = timeSignalCommand;
        break;
      case TYPE_PRIVATE_COMMAND:
        command = PrivateCommand.parseFromSection(sectionData, spliceCommandLength, ptsAdjustment,
            descriptors);
        break;
      default:
        // Do nothing.
        break;
    }
    return command == null ? new Metadata() : new Metadata(presentationTimeUs, command);
  }
```

And in `MetadataRenderer`:

```
  private void readMetadata() {
      ...
            if (!entries.isEmpty()) {
              long presentationTimeUs;
              if (metadata.presentationTimeUs == C.TIME_UNSET) {
                presentationTimeUs = getPresentationTimeUs(buffer.timeUs);
              } else {
                presentationTimeUs = metadata.presentationTimeUs;
              }
              Metadata expandedMetadata =
                  new Metadata(presentationTimeUs - 1000000000000L, entries);
              pendingMetadata = expandedMetadata;
            }
    ...
  }
```

**Comment by icbaker** [comment] 2023-06-26 16:39
Duplicate of https://github.com/androidx/media/issues/471

**Closed as completed by icbaker** 2023-06-26 16:39 UTC
Labels: duplicate
