### ISSUE TITLE
custom MediaSource related

### ISSUE THREAD

**Issue by tanpuer** [google/ExoPlayer#6002] opened 2019-06-06 03:47 UTC
I use concatenatingMediaSource to play my video list seamlessly. But recently I need to pause video when current video reaches to end before playing next video. I paused the video in the onPositionDiscontinuity callback, but the first frame of next video occurred. I also tryed to stop decode thread in the method "canKeepCodec" in MediaCodecVideoRenderer, but still didn't satisfy my need.
Should I custom a new MediaSource?

**Comment by tonihei** [comment] 2019-06-06 08:02
That's a duplicate of #5660. In short, you need to send a message which pauses the player at the end of the playback. But sending messages is not precise enough by default to do that in the right moment. So the linked enhancement is to allow sending precise messages for cases where playback needs to be interrupted at a precise playback position.

**Closed as completed by tonihei** 2019-06-06 08:02 UTC
Labels: duplicate

**Comment by tanpuer** [comment] 2019-06-06 08:13
Thanks @tonihei 
when will exoplayer allow precise messages? Right now, I should add next mediasource and seek to it instead when STATE_EDN?

**Comment by tonihei** [comment] 2019-06-06 08:26
Yes, that's one way to work around that. Unfortunately, you won't get the automatic prebuffering in this case and buffering will only start when you seek.
