### ISSUE TITLE
Could we avoid default method interfaces in Java at least in internal implementations?

### ISSUE THREAD

**Issue by dryganets** [google/ExoPlayer#7119] opened 2020-03-21 00:28 UTC
I have noticed that the default methods got higher and higher adoption in the ExoPlayer library.

The problem is that not every build toolchain supports it equally well. We have some issues using BUCK for example. 

While most of the issues could be work-arounded by just overriding the default implementation, some of the cases can't be fixed that easy.

Example of that is DUMMY DrmFactory which is always created by default.

I understand that code looks a bit better with default implementation, but NoOp implementation should be able to fix it as well without burden of de-sugaring and extra build infrastructure issues.

What do you think about banning default methods completely?
Would you approve a PR which removes at least internal usage of the default implementation?

**Comment by ojw28** [comment] 2020-03-21 17:26
Default methods aren't just about making code look nicer. They add significant additional flexibility because it becomes possible to add to an interface without breaking all implementations of that interface (you can achieve something similar with an abstract class, but that approach has the significant limitation of not allowing multiple inheritance).

* Please could you point us at a specific issue or issues on the BUCK issue tracker related to default methods, so we can better understand the problems you're running into? Without knowledge of the specifics, it's not really possible for us to have an informed opinion on your particular case.
* If any other developers have feedback on this, to give us a better overall picture, that would be appreciated. What other toolchains are impacted, and why? What adoption do these toolchains have? Why aren't the toolchains being fixed to support (not particularly new) language features?

> What do you think about banning default methods completely? Would you approve a PR which removes at least internal usage of the default implementation?

This issue does not yet make a good case for doing this. We would need a lot more specifics to even form an opinion, starting with those requested above.

**Comment by dryganets** [comment] 2020-03-23 17:27
For my particular case, I'd rather make a small PR to the ExoPlayer.

We are using an older version of BUCK for the developer builds, we are working on upgrade in the mean time.

I understand the value of defaults methods, just saying that there is a cost for some users of the library. I agree that everyone that uses modern toolchains like d8 should be able to deal with it.

If somebody else has the similar issues he probably chime in into the conversation, I've seen a number of AbstractMethod errors complains in the bug tracker, but I guess most of the cases were related to miss-configuration fo the gradle build-script.

**Comment by ojw28** [comment] 2020-03-23 17:38
I don't think your particular case is justification for regressing ExoPlayer's adoption of default methods. It seems likely that default methods benefit the majority of developers, and impact on a much smaller number of developers who are using outdated and/or unofficial toolchains. It's probably working as intended that the latter group may have to jump through a few extra hoops to get things functioning properly, and this should serve as motivation for that group to update their toolchains to ones that provide better support.

As a more general point, when developing a library that's as widely adopted as ExoPlayer, it's simply not possible to keep all developers happy all of the time. We frequently see requests in the other direction (i.e., complaints that we're too slow adopting new technology; Kotlin being a current example). It's our job to keep most developers happy most of the time, and I don't think there's a good argument around default methods to suggest that we're not doing this.

I will leave this issue open for a while in case any other developers want to weigh in.

**Comment by dryganets** [comment] 2020-03-25 02:20
Thank you for keeping it open!

I posted the quick fix PR + described couple of other ways to fix it. Feel free to pick your favorite, or just edit the change the way you like it.

I verified that this is enough to unblock our upgrade to the new version.

**Comment by ojw28** [comment] 2020-03-25 10:23
To be clear, leaving the issue open does not imply we're likely to accept any pull requests for this issue.

**Comment by dryganets** [comment] 2020-03-25 17:03
Thanks,
I understand that it doesn't imply that you will merge anything.

I opened the PR to start dialog and find out if you think one of the options I propose will be acceptable for the project.

The least invasive options will be to rather add the constructor to factory to allow passing your own implementation of the DrmSession.

**Comment by ojw28** [comment] 2020-03-25 17:26
Unless there's a significant amount of additional feedback, we're not planning to accept any kind of pull request for this. If only a small number of developers are affected, the easiest solution is for them to check the project out as source and make whatever the necessary modifications are locally (or, preferably, update to better supported tool chains).

**Comment by dyue** [comment] 2020-03-25 21:57
One problem with default methods in an interface is that default methods are only transferred over during compilation.

Here's an example:
1) A library v1 implements AnalyticsListener and is compiled against ExoPlayer 2.10.  The implementation uses default methods for the unimplemented methods.
2) ExoPlayer 2.11 changed the AnalyticsListener interface by adding a new method and associated a default implementation for the method.
3) A user uses library v1 with ExoPlayer 2.11, but library v1 implementation will not have the new method implemented since it was compiled against ExoPlayer 2.10 and fails when ExoPlayer 2.11 calls the new virtual method in the AnalyticsListener since it's unimplemented.

This actually introduces quite a number of problems:
1) We can't upgrade to a newer version of ExoPlayer unless all the libraries that depend on ExoPlayer are compiled against that version.
2) If a library doesn't mention which version of ExoPlayer is supported, it's way too risky to upgrade ExoPlayer because the error only exhibits at runtime.

Would be nice if DefaultAnalyticsListener and as such are not deprecated so that libraries can have the option to not rely on default method interfaces.

**Comment by ojw28** [comment] 2020-03-26 09:10
@dyue - Are you sure that's how default method de-sugaring works? I didn't look in detail, but my understanding is that default method de-sugaring doesn't happen when library V1 is compiled, and instead happens when building the final application binary that V1 is included in. I don't think de-sugaring can happen before that, because the way de-sugaring is performed depends on the minimum API level of the application binary, and that information is not known at the point of compiling V1. Note that if de-sugaring works in the way I describe, the issue you describe does not exist.

**Comment by tonihei** [comment] 2020-03-26 12:47
As an additional note - we don't support mixing versions of ExoPlayer. So if library V1 depends on 2.10 and is actually exporting ExoPlayer APIs as part of their library, then you can't depend on 2.11 at the same time. The gradle build system prevents that with a build error for example.

**Comment by ojw28** [comment] 2020-05-03 11:30
I don't think a good argument has been made for avoiding default methods. Closing.

**Closed as completed by ojw28** 2020-05-03 11:30 UTC
Labels: question
