### ISSUE TITLE
How to set track selection overrides to specific media source in ConcatenatingMediaSource?

### ISSUE THREAD

**Issue by arochevdev** [google/ExoPlayer#9984] opened 2022-02-17 18:26 UTC
In our application, we use ConcatenatingMediaSource for smooth transition between subsequent media streams. When first media stream is near the end, next one is added to ConcatenatingMediaSource so that it will be prepared by ExoPlayer.

We also use TrackSelectionOverrides API to override selection of tracks. TrackSelectionOverride are created for specific track groups and added to TrackSelectionOverrides which is then passed to DefaultTrackSelector.

It works well when there is only one media source in ConcatenatingMediaSource, but breaks when adding another one. When next media source is added, ExoPlayer prepares it and applies current track selection overrides to it (overrides that were created for tracks from previous media source). Since the next media source has different track groups, it triggers internal ExoPlayer assertion:

```
2022-02-17 19:09:09.990 27013-30178/com.gsgroup.tricoloronline E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:612)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
        at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:314)
        at com.google.android.exoplayer2.MediaPeriodHolder.applyTrackSelection(MediaPeriodHolder.java:259)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:193)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2209)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:505)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

Is this not correct way to work with TrackSelectionOverrides and ConcatenatingMediaSource and if not how are we supposed to do it?
ExoPlayer version is 2.16.1

**Comment by ojw28** [comment] 2022-02-17 20:34
A `TrackSelectionOverride` should only be applied if the media contains a `TrackGroup` equal to the one in the override.

I tried playing a playlist and setting a `TrackSelectionOverride` for a `TrackGroup` in the first playlist item, but was not able to reproduce the playback failure you're seeing when moving to the second item in the playlist. Please could you provide concrete reproduction steps? In theory it should be possible to reproduce it using just our demo app, if the issue is as you describe it, although it's possible you may need to add specific media to it. Thanks!

**Comment by arochevdev** [comment] 2022-02-18 12:09
I managed to reproduce this with sample app when transitioning between two HlsMediaSources with the same URL. In real case, two streams have different URLs but their HLS manifests are the same and MPEG-TS segments have same tracks (sorry for not mentioning it originally).

https://github.com/arochevdev/exoplayer-assert-sample

What this sample does is:
1. Creates ConcatenatingMediaSource with single HlsMediaSource from "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8" URL.
2. Overrides selection of single text track.
3. Seeks it to the 30 seconds from end.
4. Adds another HlsMediaSource with the same URL to ConcatenatingMediaSource.

In about 10 seconds, internal ExoPlayer assertion occurs.

**Comment by ojw28** [comment] 2022-02-20 18:01
The playback failure you're encountering is already fixed in `dev-v2`. It was fixed by https://github.com/google/ExoPlayer/commit/8c90ba5db462ee0c1bfadd67a817092ee23af0eb. This will be included in `2.17`.

Whether your code does what you want after this fix, I'm not sure. What is the actual intention of your code? It appears to be trying to select an English subtitle, but if that's the case I think you'd be better off using constraint based preferences that naturally apply across multiple items, rather than trying to select per-item overrides. For example:

```
TrackSelectionParameters newParameters = currentParameters
     .buildUpon()
     .setPreferredTextLanguage("en")
     .build();
```

If constraint based preferences don't work for you, but you think they should, then I'd suggest you explain your use case and also why the existing constraint based options don't work for you. Thanks!

**Comment by arochevdev** [comment] 2022-02-20 20:45
It possible that there is multiple subtitle tracks with the same language in the stream (e.g. subtitles and captions). While there is `setPreferredTextRoleFlags` alongside with `setPreferredTextLanguage`, there is no guarantee that role flags will be set (AFAIK ExoPlayer doesn't support them for HLS (please correct me if I'm wrong) and for DASH they are optional). In that case the only way to distinguish between such tracks is to compare their `Format.label` values which can only be done manually.

**Comment by arochevdev** [comment] 2022-02-21 10:20
Basically, the use case is two-fold:
1. We need to be able to select specific track based on user choice (e.g. selection in menu). This is currently done by selecting specific track using its TrackGroup and index.
2. Track selected by user needs to be saved (outside of scope of player), and then the track "closest" to it (ideally the same one if its is present) needs to be automatically selected when playback starts with different media (possibly with different tracks altogether). This should work both when player is started from scratch and when new MediaSource is added to ConcatenatingMediaSource. This is currently done by manually searching for "closest" track on `onTracksInfoChanged()` and selecting it explicitly via its TrackGroup and index.

**Comment by ojw28** [comment] 2022-02-21 13:27
If you're aware of any flagging mechanism in HLS master playlists that (a) maps onto ExoPlayer role flags, and (b) we don't have the necessary plumbing in place for, then please let us know and we can take a look at adding support.

It is true that role flags in DASH manifests are optional (I suspect the same is true for HLS as well), although of course if you control the content you can ensure that they're always specified. If you don't control the content then I don't think there's any guarantee that whatever your "closest match" logic does will pick the right track, although you can probably get it right more often than not.

The main problem with your approach is that `onTracksInfoChanged` is only called when playback actually transitions to the next item, where-as buffering happens before this (because the next item will be pre-buffered when the current item has nearly finished playing). What you're doing might work fine for text, but for something like demuxed audio tracks, the player may end up pre-buffering the wrong track, and then having to re-buffer when the transition occurs and you specify your override.

There is no high level API to select an override for tracks during pre-buffering. For playlist use cases we think constraint based track selection is more appropriate, and for manual selection by the user you'd generally only show the currently playing tracks, else it would be very confusing.

If you do need to override the tracks during pre-buffering you'll need to provide a custom `TrackSelector`. For example, by extending `DefaultTrackSelector` and overriding the methods needed to perform your preferred selections. The `TrackSelector` is invoked to make the initial selection at the start of pre-buffering.

I think we can close this issue, since the playback failure is fixed, your code may "just work" for what you need on 2.17, and if it doesn't the correct approach to use instead is described above.

**Closed as completed by ojw28** 2022-02-21 13:27 UTC
Labels: question
