### ISSUE TITLE
DecoderInitializationException: Decoder init failed: AACDecoder

### ISSUE THREAD

**Issue by whoyouni** [google/ExoPlayer#1210] opened 2016-01-30 02:27 UTC
```
Could not find class 'android.media.MediaCodec$CodecException', referenced from method com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException.a
01-30 10:26:52.055  17127-17315/? E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: AACDecoder, MediaFormat(2, audio/mp4a-latm, -1, 746, -1, -1, -1, -1.0, 2, 48000, und, 1643000, false, -1, -1)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.a(MediaCodecTrackRenderer.java:359)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.j(MediaCodecTrackRenderer.java:346)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.a(MediaCodecTrackRenderer.java:709)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.e(MediaCodecTrackRenderer.java:470)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.a(MediaCodecTrackRenderer.java:451)
            at com.google.android.exoplayer.f.i(ExoPlayerImplInternal.java:431)
            at com.google.android.exoplayer.f.handleMessage(ExoPlayerImplInternal.java:213)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.a.l.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: AACDecoder, MediaFormat(2, audio/mp4a-latm, -1, 746, -1, -1, -1, -1.0, 2, 48000, und, 1643000, false, -1, -1)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.j(MediaCodecTrackRenderer.java:346)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.a(MediaCodecTrackRenderer.java:709)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.e(MediaCodecTrackRenderer.java:470)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.a(MediaCodecTrackRenderer.java:451)
            at com.google.android.exoplayer.f.i(ExoPlayerImplInternal.java:431)
            at com.google.android.exoplayer.f.handleMessage(ExoPlayerImplInternal.java:213)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.a.l.run(PriorityHandlerThread.java:40)
     Caused by: java.io.IOException: Failed to allocate component instance
            at android.media.MediaCodec.native_setup(Native Method)
            at android.media.MediaCodec.<init>(MediaCodec.java:210)
            at android.media.MediaCodec.createByCodecName(MediaCodec.java:204)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.j(MediaCodecTrackRenderer.java:331)
```

**Comment by andrewlewis** [comment] 2016-01-30 20:17
It looks like the actual problem is `DecoderInitializationException: Decoder init failed: AACDecoder`, but we currently don't use this decoder on platform API version < 21 ([see the check here](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecUtil.java#L193)).

Are you using an up to date version of ExoPlayer? Please also paste the output of `adb shell getprop ro.build.fingerprint`.

**Comment by ojw28** [comment] 2016-02-01 19:13
This is most likely fixed by using an up to date version of ExoPlayer, where the check mentioned by @andrewlewis most likely fixes the issue. Please let us know if not.

**Closed by ojw28** 2016-02-01 19:13 UTC

**Comment by Ltty** [comment] 2016-02-19 06:24
This issue still occurs in Exo r1.5.5 on Android KitKat. Could reproduce it testing default HLS playback on a Motorola Droid X with Android 4.4. Here's the full stack trace:

`02-19 06:00:46.009 14486-14486/com.pocketlifestyle.streamingdemo E/dalvikvm: Could not find class 'android.media.PlaybackParams', referenced from method com.google.android.exoplayer.MediaCodecAudioTrackRenderer.handleMessage
02-19 06:00:46.862 14486-14673/com.pocketlifestyle.streamingdemo E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
02-19 06:00:46.921 14486-14709/com.pocketlifestyle.streamingdemo E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
02-19 06:00:46.924 14486-14709/com.pocketlifestyle.streamingdemo E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -1010
02-19 06:00:46.925 14486-14708/com.pocketlifestyle.streamingdemo E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -1010)
02-19 06:00:46.927 14486-14673/com.pocketlifestyle.streamingdemo E/dalvikvm: Could not find class 'android.media.MediaCodec$CodecException', referenced from method com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException.getDiagnosticInfoV21
02-19 06:00:46.934 14486-14486/com.pocketlifestyle.streamingdemo E/EventLogger: internalError [1.65, decoderInitializationError]
                                                                                com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(null, video/avc, -1, -1, 1500, 1500, -1, 1.0, -1, -1, null, -1, false, -1, -1)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729)
                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479)
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: java.lang.IllegalStateException
                                                                                    at android.media.MediaCodec.native_configure(Native Method)
                                                                                    at android.media.MediaCodec.configure(MediaCodec.java:262)
                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:363)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
02-19 06:00:46.936 14486-14673/com.pocketlifestyle.streamingdemo E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                          com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(null, video/avc, -1, -1, 1500, 1500, -1, 1.0, -1, -1, null, -1, false, -1, -1)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:388)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729)
                                                                                              at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479)
                                                                                              at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                              at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                           Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(null, video/avc, -1, -1, 1500, 1500, -1, 1.0, -1, -1, null, -1, false, -1, -1)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374) 
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                                              at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                                              at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                              at android.os.Looper.loop(Looper.java:136) 
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                              at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                           Caused by: java.lang.IllegalStateException
                                                                                              at android.media.MediaCodec.native_configure(Native Method)
                                                                                              at android.media.MediaCodec.configure(MediaCodec.java:262)
                                                                                              at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:363)
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                                              at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                                              at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                                              at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                              at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                              at android.os.Looper.loop(Looper.java:136) 
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                              at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
02-19 06:00:46.947 14486-14486/com.pocketlifestyle.streamingdemo E/EventLogger: playerFailed [1.66]
                                                                                com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(null, video/avc, -1, -1, 1500, 1500, -1, 1.0, -1, -1, null, -1, false, -1, -1)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:388)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729)
                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479)
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                 Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(null, video/avc, -1, -1, 1500, 1500, -1, 1.0, -1, -1, null, -1, false, -1, -1)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374) 
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                 Caused by: java.lang.IllegalStateException
                                                                                    at android.media.MediaCodec.native_configure(Native Method)
                                                                                    at android.media.MediaCodec.configure(MediaCodec.java:262)
                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:363)
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729) 
                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334) 
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496) 
                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479) 
                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129) 
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
`
