### ISSUE TITLE
Google Exoplayer : HLS Redundant stream is not working (Issue #9047)

### ISSUE THREAD

**Issue by SUNYTYAGI** [google/ExoPlayer#9054] opened 2021-06-14 17:38 UTC
Hi I am creating new issue , since i do not have access to re-open close issue (#9047)

Please check my last comment on the issue (#9047 )

https://github.com/google/ExoPlayer/issues/9047#issuecomment-860863669

**Comment by SUNYTYAGI** [comment] 2021-06-14 17:39
+@christosts

**Comment by ojw28** [comment] 2021-06-14 18:13
Closing as a duplicate of #9047 (which I will re-open).

**Closed as completed by ojw28** 2021-06-14 18:13 UTC
Labels: duplicate
