### ISSUE TITLE
BandWidthMeter over estimates on slow network, causing adaptive streaming not working for audio-only playback

### ISSUE THREAD

**Issue by tagerjump** [google/ExoPlayer#10307] opened 2022-05-31 19:36 UTC
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

Pixel 3a physical device
Pixel 4 emulator

### Reproducible in the demo app?

Yes

### Reproduction steps

- In demo app PlayerActivity, add some logs like
```
      player.addAnalyticsListener(
          new AnalyticsListener() {
            @Override
            public void onDownstreamFormatChanged(
                AnalyticsListener.EventTime eventTime,
                MediaLoadData mediaLoadData
            ) {
              Log.d(" -buggy meter- ", "onDownstreamFormatChanged, trackFormat: " + mediaLoadData.trackFormat);
            }

            @Override
            public void onBandwidthEstimate(EventTime eventTime, int totalLoadTimeMs,
                long totalBytesLoaded, long bitrateEstimate) {
              Log.d(" -buggy meter- ", "onBandwidthEstimate, bitrateEstimate: " + bitrateEstimate/1000 + "Kbps");

            }
          }
      );
```
- throttle the network to lower than 150 kbps
    - For emulator: adb emu network speed gprs
    - For physical device use proxy app like Throttly

### Expected result

BandWidthMeter should report correct bandwidth with acceptable accuracy like 125-175 for 150 as the real speed.

### Actual result

- Watching logs that bandWidthMeter is reporting cautious bandwidth estimate of 250+ where the actual network speed is lower than 100Kbps. 
`onBandwidthEstimate, bitrateEstimate: 257Kbps`

I also verified network speed with on some websites, the Throttly is trust worth.

This bug is not noticeable for video content as BandWidthMeter is working properly at high speed network. However, for audio only content, this bug causes adaptive streaming not working properly. It causes track selector always picks the higher track than the real network capacities and causes buffer timeout or playback failure.

This could be the root cause of this open issue https://github.com/google/ExoPlayer/issues/5313.

### Media

Not needed, you can repro this on any media.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment] 2022-06-06 12:17
There are some known issues with our current bandwidth meter (see [analysis from 2019](https://docs.google.com/document/d/1e3jVkZ6nxNWgCqTNibqV8uJcKo8d597XVl3nJkY7P8c/edit#heading=h.2zer3ifwclzq)) and this may be the visible effect of some of them. 

Depending on the throttling technique you used, the environment may also not be very realistic. Many throttling tools just ensure that the transfer of large files doesn't exceed a certain bandwidth *on average*. So measuring short transfer bursts may give you misleading measurements because the throttling doesn't work as it should. 

Note that we are also actively working on various bandwidth measurement improvements that may help with this case. The described issue is not specific or reproducible enough to track this as a bug though I believe.

Final note: #5313 is unrelated to this question because it tracks an HLS specific track duplication issue.

**Comment by tagerjump** [comment] 2022-06-08 19:37
Could you verify this using your throttling technique? For me, I can repro this with both Throttly and adb command.

**Comment by tonihei** [comment] 2022-06-09 12:11
Yes, we were also able to see similar issues (see the linked analysis doc above), in particular for small transfers. I just wanted to warn you that throttling is not necessarily a good replacement for an actually slow network as it may behave differently.

**Comment by tonihei** [comment] 2022-06-09 12:50
I'll close the issue because it's not a specific bug we can address directly, but rather a generic improvement in bandwidth measuring we are already working on.

**Closed as completed by tonihei** 2022-06-09 12:50 UTC
Labels: question
