### ISSUE TITLE
Error inflating class com.google.android.exoplayer2.ui.PlayerView

### ISSUE THREAD

**Issue by Hardyal-s** [google/ExoPlayer#6132] opened 2019-07-04 13:59 UTC
### [REQUIRED] Issue description
Hello,

I am using following code:

Layout:

```
<com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/videoView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:resize_mode="zoom"
        app:shutter_background_color="@android:color/transparent"
        app:surface_type="texture_view"
        app:use_controller="false" />
```

Kotlin code (Inside Fragment):

 ```
private fun initializePlayer(path: String) {
        val mPlayer = ExoPlayerFactory.newSimpleInstance(
            requireContext()
        )
        mPlayer?.repeatMode = REPEAT_MODE_ONE
        val mediaSource = buildMediaSource(path)
        mPlayer?.prepare(mediaSource, true, false)
        videoView?.player = mPlayer
        videoView?.player?.addListener(this)
    }

private fun buildMediaSource(uri: Uri): MediaSource {
    return ProgressiveMediaSource
        .Factory(
                DefaultHttpDataSourceFactory("user-agent")
        )
        .createMediaSource(uri)
}
```
I am getting following error.

### [REQUIRED] Reproduction steps
Launch the app and open the selected fragment. Play the video, crash appears.

### [REQUIRED] Link to test content
URL: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

### [REQUIRED] A full bug report captured from the device
```
Fatal Exception: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class com.google.android.exoplayer2.ui.PlayerView

Caused by android.view.InflateException: Binary XML file line #13: Error inflating class com.google.android.exoplayer2.ui.PlayerView

Caused by java.lang.reflect.InvocationTargetException

Caused by android.view.InflateException: Binary XML file line #17: Binary XML file line #33: Error inflating class ImageButton

Caused by android.view.InflateException: Binary XML file line #33: Error inflating class ImageButton

Caused by android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f070094

Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f070094
```
### [REQUIRED] Version of ExoPlayer being used
2.10.0

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel and Pixel 2 , Android 9
Thank you.

**Comment by tonihei** [comment] 2019-07-04 16:01
Adding similar code to an example Kotlin project works fine for me. I'd suggest to rebuild your app and maybe also to invalidate Android Studio caches. That often helps for such problems.

**Comment by Hardyal-s** [comment] 2019-07-05 04:47
I got this crash in fabric crashlytics report from the production build which is live on Google play store. I don't have Pixel/Pixel 2 device to test this but i tried on Pixel 2 emulator and many other devices with android version 6,7,8,9. But i am not able to reproduce this crash at my end.

**Comment by tonihei** [comment] 2019-07-05 07:51
That's hard to debug if it can't be reproduced. Is that an issue occurring often or just a rare incident? In any case, there is not much we can do and it also sounds like a generic Android problem with resource management rather than an ExoPlayer problem.

**Comment by ojw28** [comment] 2019-07-08 18:36
Closing because this does not appear to be an ExoPlayer problem.

**Closed as completed by ojw28** 2019-07-08 18:36 UTC
Labels: wont fix: app issue
