### ISSUE TITLE
Cannot open m3u8 url

### ISSUE THREAD

**Issue by mdtuyen** [google/ExoPlayer#4678] opened 2018-08-18 01:40 UTC
I can use Chrome to play that url but can't open with Exoplayer.
This is the log:

>  com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to ﻿http://app.tivi8k.net/sctvcl.php?u=elive/_definst_/smil:sctv2_HD.smil/chunklist_w661438291_b692000_tkbXl0b2tlbnN0YXJ0dGltZT0xNTM0NTU0OTI4Jm15dG9rZW5lbmR0aW1lPTE1MzQ1OTg0MjgmbXl0b2tlbmhhc2g9S3J5WWFxdllGdW9DM1ZWT0YzdWJ3OWJrSVJ4bndmakpOaFE1UmN5QzVTZz0=.m3u8
>         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
>         at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
>         at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
>         at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>         at java.lang.Thread.run(Thread.java:760)
>      Caused by: java.net.MalformedURLException: no protocol: ﻿http://app.tivi8k.net/sctvcl.php?u=elive/_definst_/smil:sctv2_HD.smil/chunklist_w661438291_b692000_tkbXl0b2tlbnN0YXJ0dGltZT0xNTM0NTU0OTI4Jm15dG9rZW5lbmR0aW1lPTE1MzQ1OTg0MjgmbXl0b2tlbmhhc2g9S3J5WWFxdllGdW9DM1ZWT0YzdWJ3OWJrSVJ4bndmakpOaFE1UmN5QzVTZz0=.m3u8
>         at java.net.URL.<init>(URL.java:589)
>         at java.net.URL.<init>(URL.java:486)
>         at java.net.URL.<init>(URL.java:435)
>         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:341)
>         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137) 
>         at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
>         at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
>         at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114) 
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
>         at java.lang.Thread.run(Thread.java:760) 

In chrome I don't need setup UserAgent or Referer. I don't know why Exoplayer can't open that.

**Comment by ojw28** [comment] 2018-08-19 18:40
Please can you provide complete details of the problem, as requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). I'm not able to reproduce the issue with the information provided.

**Comment by ojw28** [comment] 2018-08-27 18:33
Closing due to lack of required information.

**Closed as completed by ojw28** 2018-08-27 18:33 UTC
Labels: need more info
