### ISSUE TITLE
Audio out of sync when seeking in HLS source

### ISSUE THREAD

**Issue by strangesource** [google/ExoPlayer#9411] opened 2021-09-09 10:59 UTC
## Description
When playing back an HLS stream and seeking directly to the end of the stream, audio is out of sync and continues playing for severals seconds.
This started happening after updating from ExoPlayer `2.12.3` to `2.13.3` and is also reproducible in the latest `2.15.0`.

## Steps to reproduce
1. Load HLS stream `https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8` into the demo app
2. Seek right to the end
3. Observe audio playing back for several seconds and current time ticking up to `15:05` of `14:48`

When playing back the content from e.g. `13:50` and not seeking very close to the end, this does not occur.

Thanks in advance!

Edit: forgot to mention that the audio track has additional segments in it. I.e. video has 443 segments with 2sec each while audio has 452 segments with the same length.

**Comment by christosts** [comment] 2021-10-08 14:37
The root cause is similar to that of #2233, although it manifests differently in recent ExoPlayer versions (we are now in `2.15.1` compared to `2.1` at #2233).

The segment durations listed in the audio media playlists are rounded to integer precision. When the player seeks, it picks a segment based on the playlist information however the timestamps of the downloaded audio segments are behind the expected timestamp. 

In `2.12.3`, that made seeking slow: the player starts downloading audio segments and then drops them because it realizes they are behind the seek point. That adds delay until the player is able to resume playback after a seek.

As of `2.13` however, the samples are not dropped and instead the player adjusts the timestamps (in an attempt to fix a timestamp drift), causing the sync issues. Apart from the sync issue when seeking at the end of the video, seeking in general is also not good with this playlist: testing with `2.15.1`, when you seek, there's a frozen video frame with audio playing and video starts playing later.

The HLS spec does allow durations to be rounded up, however Apple's [HLS Authoring Specification, section 8.1](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices) says

> 8.1. You MUST use sufficiently accurate segment durations to ensure that the sum of the EXTINF durations of any contiguous group of segments is within one video frame duration of the actual duration of the content.


My recommendation is to update the playlist with accurate segment durations. The player should address the case of inaccurate segment durations but this is likely going to be a low priority. I'll mark this as a duplicate and close it in favor of #2233.

**Closed as completed by christosts** 2021-10-08 14:37 UTC
Labels: bug

**Comment by strangesource** [comment] 2021-10-12 07:53
Thanks for the detailed feedback, I will have a closer look and take according actions. 👍
