### ISSUE TITLE
ExoPlayer volume is reset after a phone call

### ISSUE THREAD

**Issue by mr-thierry** [google/ExoPlayer#3923] opened 2018-03-01 19:45 UTC
I'm using ExoPlayer 2.7.0 on my Nexus 6P with Android 8.1

I'm using SimpleExoPlayer to play a video. I set the volume to zero to mute it. If I receive a phone call while the video is playing, when the call is ended, the volume is back to 100%. 

Note that SimpleExoPlayer still says that the volume is zero, but the sound is heard.

**Comment by ojw28** [comment] 2018-04-22 22:39
Please can you provide some more concrete reproduction steps, or ideally source code for a simple demo app that reproduces the issue? It's difficult to know what's actually happening from the description provided.

**Comment by mr-thierry** [comment] 2018-04-25 13:31
Hi 'ojw28'
I have created a GitHub project to show the issue. See https://github.com/thierryd/ExoPlayerSoundBug

I hope this help! Keep me informed if you have any question / issue / stuff I need to change. :)

**Comment by ojw28** [comment] 2018-04-28 14:57
Thanks! I'm able to reproduce the issue. I suspect it's a bug in the underlying platform, which isn't something we can do much about, unfortunately, except report it so that it gets fixed in future releases. I'll check whether it reproduces on Android P, and file an issue on the Audio team if it does.

**Comment by ojw28** [comment] 2018-05-01 14:07
Confirmed this is still reproducible on Android P. Filed a bug with the Android media team [Internal ref: b/78930229]

**Comment by komissarovdenis** [comment] 2018-06-26 09:24
@ojw28 hi, how about bug status? (Couldn't check it by myself, because it's internal one and hidden).
Thank you.

**Comment by ojw28** [comment] 2018-06-26 09:27
No update I'm afraid.

**Comment by oxied** [comment] 2018-08-06 09:26
It may help somehow: https://github.com/google/ExoPlayer/issues/4546

```    player!!.audioAttributes = AudioAttributes.Builder().setFlags(C.FLAG_AUDIBILITY_ENFORCED).setUsage(C.USAGE_NOTIFICATION_RINGTONE).setContentType(C.CONTENT_TYPE_SPEECH).build()```

**Comment by RsnRohith** [comment] 2018-10-08 12:14
Hi @ojw28 , any update on this bug ?

**Comment by RsnRohith** [comment] 2018-10-08 15:59
Hi @ojw28 , still experiencing this issue. Any update on this ?

**Comment by ojw28** [comment] 2018-10-10 22:29
As noted above, the issue is in the underlying platform, and isn't something we can do much about in ExoPlayer. We have a bug filed on the platform team, who will hopefully look at it for Android Q.

**Comment by AndroidDeveloperLB** [comment] 2019-02-27 14:51
I've noticed such an issue too. Using v2.9.5 of ExoPlayer, and noticed on Pixel 2 with Android P. The bug is very similar: play a video that is muted. Have an outgoing call. End call. Go back to app which should call `playWhenReady = true`.
Is there a workaround? Does it occur on all Android versions and devices?
I think this should work, that each time 

            player!!.volume = 1f
            player!!.volume = 0f
            player!!.playWhenReady = true

It seems to work, but for a split of a second I can still hear the sound of the video... :(

**Comment by andrewlewis** [comment] 2019-03-11 08:03
Closing as this should be fixed in the next Android release. Unfortunately I don't think there's a workaround.

**Closed as completed by andrewlewis** 2019-03-11 08:03 UTC
Labels: bug: in platform

**Comment by AndroidDeveloperLB** [comment] 2019-03-11 08:18
@andrewlewis Can you please show the issue on the issue tracker? 
You mean it will be fixed only on the next version, Android Q ? 
Are you sure there is no workaround? Can't it re-initialize itself with the volume set to 0 .
