### ISSUE TITLE
Add some failure reasons to Download.FailureReason

### ISSUE THREAD

**Issue by noamtamim** [google/ExoPlayer#6261] opened 2019-08-04 08:55 UTC
### [REQUIRED] Use case description
Currently there's only one "failure reason" - UNKONWN. I saw an issue (#5914) requesting a reason for insufficient space, but there should be even more.

### Proposed solution
After the initial preparation step, the most likely reason for a failure is network issues (timeout, some http error codes, server not found, etc). These should be reported.

### Alternatives considered
Stick with "unknown" - unless I'm missing some other way of knowing why a download has failed.

**Comment by ojw28** [comment] 2019-08-05 09:56
Marking as a duplicate of #5914, which has been generalized.

**Closed as completed by ojw28** 2019-08-05 09:56 UTC
Labels: enhancement
