### ISSUE TITLE
Passing offline keys to drm session manager but sometimes it calling license server

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#7504] opened 2020-06-15 10:51 UTC
**While playing the online dash video with offline license**

```
 byte[] license = getCacheLicense(uri.toString());
 drmSessionManager.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, license);
```

**Exoplayer calling license server sometimes why this happened even offlineLicenseKeySetId exist**
I download license of URL and store to the database and getting licenses from DB to exist based on URL as per expiry time limit

```
OfflineLicenseHelper<FrameworkMediaCrypto> offlineLicenseHelper = new OfflineLicenseHelper<FrameworkMediaCrypto>(C.WIDEVINE_UUID,
                                FrameworkMediaDrm.DEFAULT_PROVIDER,
                                httpMediaDrmCallback,
                                null);
HttpDataSource dataSource = HelperApplication.getInstance().buildHttpDataSourceFactory().createDataSource();

DataSpec dataSpec = new DataSpec(Uri.parse(dashUrlsModel.getDashUrl()));
DataSourceInputStream inputStream = new DataSourceInputStream(dataSource, dataSpec);
String manifestData = Util.fromUtf8Bytes(Util.toByteArray(inputStream));
DashManifest dashManifest = DashUtil.loadManifest(new ByteArrayDataSource(manifestData.getBytes()), Uri.parse(dashUrlsModel.getDashUrl()));
DrmInitData drmInitData = DashUtil.loadDrmInitData(dataSource, dashManifest.getPeriod(0));
byte[] offlineLicenses = offlineLicenseHelper.downloadLicense(drmInitData);
```

What I have to do?

**Comment by AquilesCanta** [comment] 2020-06-15 20:04
@ojw28 mind providing some assistance here?

**Comment by ojw28** [comment] 2020-06-16 17:43
As per our response to other issues filed by yourself, if you're going to file an issue, please properly fill in the issue template and provide us with proper reproduction steps. Ideally in the form of a minimal project on GitHub that demonstrates the issue. Ignoring this advice is an inefficient both your time, and ours.

From the information provided it's impossible to know whether this is simply a bug in your application code (the code snippets provided are not sufficient to fully understand what you're doing), an expected behaviour, or an ExoPlayer or Android platform issue.

**Comment by gokulkalagara** [comment] 2020-06-16 19:04
### Issue description
I download licenses and store to the DB, for reusability
we are passing offline keys to DRM session manager but sometimes it calling license server.

### Reproduction steps
Exoplayer calling license server sometimes why this happened even offlineLicenseKeySetId exist
I download license of URL and store to the database and getting licenses from DB to exist based on URL as per expiry time limit

### Version of ExoPlayer
**ExoPlayerLib/2.11.5**

### [REQUIRED] Device(s) and version(s) of Android being used
Model: MOTO G5 S plus, OS Version: 8.1.0

**Comment by ojw28** [comment] 2020-06-16 19:07
Marking as "need more info" due to lack of clear reproduction steps. It's not reasonable for you expect us to guess what you've done, try and recreate it, and then see if we can reproduce the issue? Please provide proper reproduction steps, or preferably a minimal project on GitHub that demonstrates the issue.

**Comment by gokulkalagara** [comment] 2020-06-17 07:25
can we play an online dash video URL with offlineLicenseKeySetId?

**Comment by gokulkalagara** [comment] 2020-06-17 08:50
### Reproduction Steps:

I have offline licenses for list dash video URLs
some of them use offline licenses to play. but DRM session manager calling license URL for playing some videos. why this happening?

### For Checking:
**I put empty text to defaultLicenseUrl**
HttpMediaDrmCallback httpMediaDrmCallback = new HttpMediaDrmCallback( "",true, factory);

some URLs are playing, some URL got an error to unable to fetch license due to empty license URL, it throws exception

com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect

**Comment by gokulkalagara** [comment] 2020-06-17 13:21
Event Logger File
[Log-File.txt](https://github.com/google/ExoPlayer/files/4792721/Log-File.txt)

**Closed as completed** 2020-06-17 14:30 UTC
Labels: question
