### ISSUE TITLE
How to import ExoPlayer library as a module into my project ?

### ISSUE THREAD

**Issue by qlthd** [google/ExoPlayer#2989] opened 2017-06-23 10:13 UTC
Hi,
I'd like to modify existing files in ExoPlayer, but how can I import it so that i could modify it ?

**Comment by ojw28** [comment] 2017-06-23 10:43
Dupe of https://github.com/google/ExoPlayer/issues/2974.

**Closed as completed by ojw28** 2017-06-23 10:43 UTC
Labels: duplicate

**Comment by qlthd** [comment] 2017-06-23 10:52
Why closing an issue that doesn't have any answer for the moment ?

**Comment by ojw28** [comment] 2017-06-23 11:38
Because you already have an open issue that's exactly the same, which is https://github.com/google/ExoPlayer/issues/2974.
