### ISSUE TITLE
AVSync issue: Frequent frame drops and same audio repeats after player goes to buffer state while network switch happens.

### ISSUE THREAD

**Issue by rameshandroid** [google/ExoPlayer#2041] opened 2016-11-06 05:57 UTC
Hi,

I am trying to play hls content in exoplayer demo app.Whenever network bandwidth is low (network speed slow (avg: below 500 kbps)) or frequent change in n/w speed ,player goes to buffering state. once buffering is done it's trying to play buffered content.
The issue is it's playing only audio but where as video got freezed (sometime for 2 to 10 seconds) .
       Log: com.google.android.exoplayer.demo D/EventLogger: droppedFrames [248.25, 50].

After some time both audio and video plays normally but repeats the same audio which already been played.
      Log: ## **com.google.android.exoplayer.demo E/AudioTrack: Discontinuity detected [expected 2087509333, got 2091498666]**

I tested this issue in exoplayer 1.5.8 and 1.5.11 and found in both of them.

also attched adb_logs.txt for more details.

While checking frame drop i found earlyUs is -30000 and then it's dropping the frames.

   if (earlyUs < -30000) {
            // We're more than 30ms late rendering the frame.
            dropOutputBuffer(codec, bufferIndex);
            return true;
        }

What i suspect is either decoder has given same output buffer to the renderer more than once. (same o/p buffer means : output buffer already rendered and agian same o/p was passed to renderer) or source has given same video content to the decoder, that's why earlyUs < -30000. I am not sure which one is going wrong here. 
Please let me know how to fix this problem.

[adb_logs.txt](https://github.com/google/ExoPlayer/files/573668/adb_logs.txt)

**Comment by ojw28** [comment] 2016-11-07 08:25
You'll need to provide sample media for us to reproduce this. Please also try using ExoPlayer V2.

**Comment by rameshandroid** [comment] 2016-11-08 16:03
Hi @ojw28 ,

thanks for quick reply.

sample media url: **http://www.nacentapps.com/m3u8/index.m3u8**

 Above media has 8 bitrates(profiles).based on the network speed exoplayer internally selects the suitable bitrate and plays the content.but the problem is when ever n/w speed changes from higher speed to lower speed that time video was freezed(frames are getting dropped) but audio is played. after some time both audio and video will be sync.

To reproduce this issue we have to throttle the network speed from high to low. 

I have not seen this issue in ExoPlayerV2.but i cannot migrate to ExoPlayerV2 immediately.i want to check what is wrong in 1.x.

if you need more info please let me know.

Thanks

**Comment by ojw28** [comment] 2016-11-29 18:05
If the issue is fixed in V2 then I'm not sure we'll be able to help much beyond advising you to update. @AquilesCanta might have some insight into what's been fixed, but unless it was an isolated change (unlikely for HLS, since we've been making some pretty big changes there) we're unlikely to back-port.

**Comment by AquilesCanta** [comment] 2016-11-30 18:07
I'm getting a 509. Any chance of fixing it?

**Comment by AquilesCanta** [comment] 2017-01-09 17:01
I can't reproduce the issue in either version. Have you found out any more useful information? I have tried random adaptation in V2 and reducing network capabilities and manually adapting to lower bitrate variants in V1. If you have figured out the root cause or have some extra insight for us to look into, please share it.

**Comment by AquilesCanta** [comment] 2017-02-20 15:03
Closing due to lack of information.

**Closed as completed by AquilesCanta** 2017-02-20 15:03 UTC
Labels: question
