### ISSUE TITLE
How to limit available audio tracks for exoplayer?

### ISSUE THREAD

**Issue by luna-vulpo** [google/ExoPlayer#9179] opened 2021-07-12 08:41 UTC
I have a DASH (or HLS) stream which contains many audio tracks. 
My additional code  relies heavily on on information from exoplayer.
But for same reason I have to limit the available tracks so is there possibility to tell exoplayer to ignore same audio tracks?

**Comment by Samrobbo** [comment] 2021-07-14 13:12
I'm going to need some more information to be able to help more, as it's hard to understand your situation.

That being said, have you considered looking into [DefaultTrackSelector](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java), potentially implementing your own TrackSelector or extending the Default?

**Comment by luna-vulpo** [comment] 2021-07-15 13:47
I'm looked in TrackSelector but implementing it seems to be complicated. 
For my case the base scenario would be extending DefaultTrackSelector by method: `setAllowedAudioLanguages(String... langs`)

Now I have the track selector defined like below:
```
val trackSelector = DefaultTrackSelector(
        context,
        AdaptiveTrackSelection.Factory(
            AdaptiveTrackSelection.DEFAULT_MIN_DURATION_FOR_QUALITY_INCREASE_MS,
            AdaptiveTrackSelection.DEFAULT_MAX_DURATION_FOR_QUALITY_DECREASE_MS,
            AdaptiveTrackSelection.DEFAULT_MIN_DURATION_TO_RETAIN_AFTER_DISCARD_MS,
            BANDWIDTH_FACTOR
        )
```

And prefered api would be: `trackSelector.setAllowedAudioLanguages("en","de","fr","hu")`

Suppose that we have a stream which contains be, br, en, de, ru, lv, lt, cz, se, fi, fr, hu, it audio tracks. And after call above method the stream would behave as stream which contains only "en","de","fr","hu"

But I don't know how to implement it. :(

**Comment by Samrobbo** [comment] 2021-07-19 10:51
@christosts, when you're available, can you have a look into this?

**Comment by ojw28** [comment] 2021-07-19 11:08
You can use `trackSelector.setParameters(trackSelector.buildUponParameters().setPreferredAudioLanguages(...));` to specify preferred audio languages.

However, it sounds like you want the player to behave as though the other tracks don't exist at all (e.g., have the player not even list them as tracks when you query the player for the tracks that exist). There's no easy way to make the player do this.

I think a more typical solution to this kind of problem would be to serve the correct manifest to the client in the first place (i.e., containing only the subset of variants that the client should consider as being allowed). Depending on how dynamic you need the logic to be for determining allowed languages, this could be as simple as hosting multiple static manifests with different subsets of the variants, or something a bit more complicated where the client specifies some query parameters in its manifest request that the server can use to construct/filter the correct manifest for the requesting client.

**Comment by luna-vulpo** [comment] 2021-07-19 11:25
> However, it sounds like you want the player to behave as though the other tracks don't exist at all (e.g., have the player not even list them as tracks when you query the player for the tracks that exist). 

exactly. 

>There's no easy way to make the player do this.

: ( 

> I think a more typical solution to this kind of problem would be to serve the correct manifest to the client in the first place

There is a external provider of stream which doesn't want to change current manifest or provide a new one.

I saw setPreferredAudioLanguages in doc but for exo 2.12.1 I see only setPreferredAudioLanguage (without "s")

**Comment by ojw28** [comment] 2021-07-19 11:33
> I saw setPreferredAudioLanguages in doc but for exo 2.12.1 I see only setPreferredAudioLanguage (without "s")

setPreferredAudioLanguages was added in 2.13.0. I don't think it really does what you want though.

This issue isn't really making a strong case for what you're requesting being important. For example, what's the concrete and valid case where it's both important that the client support this, and where you wouldn't have cooperation from the provider of the stream? If you can make a good case we can leave this open as a feature request. Else I'm inclined to close it as unsupported by design.

**Comment by luna-vulpo** [comment] 2021-07-21 15:11
My app gets a configuration from backend. The configuration varies depend on market.
But content provider is a just proxy and aggregator so the provider has very little possibility to change manifests.
So the app is a guard of policy for concrete market. 

I solved most of the issue on UI but the code is a little bit complicated. So such functionality would simplify logic.
I have to solve last thing: sometime playback starts with language which is not allowed. Because it's mixed with original.

**Comment by ojw28** [comment] 2021-07-26 15:57
This still sounds fairly strange/niche to me. Closing as unsupported by design.

**Closed as completed by ojw28** 2021-07-26 15:57 UTC
Labels: question
