### ISSUE TITLE
Audio file not seekable 

### ISSUE THREAD

**Issue by RahulSOpenXcell** [google/ExoPlayer#10585] opened 2022-09-06 05:11 UTC
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

All Device found that issue.

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play the attached media file. some audio file is working fine. maybe some issue in the media file.
[MeeraBai-Kaain Laage Gopal Meera Tharo.zip](https://github.com/google/ExoPlayer/files/9493432/MeeraBai-Kaain.Laage.Gopal.Meera.Tharo.zip)

### Expected result

audio file seekable for any position.

### Actual result

Audio file not seekable.

### Media

[MeeraBai-Kaain Laage Gopal Meera Tharo.zip](https://github.com/google/ExoPlayer/files/9493440/MeeraBai-Kaain.Laage.Gopal.Meera.Tharo.zip)

**Comment by RahulSOpenXcell** [comment] 2022-09-06 05:15
I have checked by using FLAG_ENABLE_INDEX_SEEKING, which can be set on a DefaultExtractorsFactory using setMp3ExtractorFlags. it is working fine for that audio but any other audio file gets the duration value wrong when I have used mp3ExtractorFlag.

**Comment by icbaker** [comment] 2022-09-08 16:12
This looks like it's probably a duplicate of https://github.com/google/ExoPlayer/issues/9408 (i.e. you're seeing issues due to using `FLAG_ENABLE_INDEX_SEEKING` when playing a file where it's not appropriate).

**Comment by icbaker** [comment] 2022-10-05 17:04
Duplicate of #9408

**Closed as completed by icbaker** 2022-10-05 17:04 UTC
Labels: duplicate
