### ISSUE TITLE
Internal runtime error, IllegalStateException

### ISSUE THREAD

**Issue by JanKokalj** [google/ExoPlayer#337] opened 2015-03-05 07:38 UTC
Hi, I am getting this error on one phone: HUAWEI Y330-U01 Android 4.2.2, Im using ExoPlayer version from r1.2.3 tag.
```
4346-4623/com.bee7.demo.publisher.ui E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:732)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:448)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:194)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Im getting similar exception in demo app:
```
4910-4910/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [1.74]
    com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:194)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:732)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:448)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:194)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Test stream to reproduce: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8

On other phones (4.1+) it works fine. What can I do in such scenarios? Fallback to native android player?

**Comment by JanKokalj** [comment] 2015-03-06 06:15
In demo app hls streams works fine if I turn off video, so I can just listen to audio.

**Comment by jbekas** [comment] 2015-04-30 04:44
Anyone know what causes this in the video renderer so I can know before a failure that it won't work? I can reproduce on 4.2.2, 4.3.

**Comment by ojw28** [comment] 2015-10-11 20:09
Closing because this is quite old. Please let us know if this still occurs on 1.5.0+, and we'll take a closer look. Thanks!

**Closed by ojw28** 2015-10-11 20:09 UTC

**Comment by zeeshan999** [comment] 2015-11-13 11:51
@ojw28 kindly reopen this issue.
regards
