### ISSUE TITLE
Source error appears after several minutes of playing an audiostream.

### ISSUE THREAD

**Issue by Realerik** [google/ExoPlayer#3962] opened 2018-03-08 08:09 UTC
Hello, 
i have the problem, that after an online audio stream has been played for several minutes an E/ExoPlayerImplInternal: Source error happens. 
Sadly the ExoPlayer does not give me any more information, but the people who have this problem all use android 7 on their devices.
As i have seen, there has been raised at least one other issue about this problem, but it has been locked and limited to collaborators, so i do not have any idea, if there has been a solution.
I am using exoplayer 2.6.1. at the moment, but had this problem with older versions also.

**Comment by andrewlewis** [comment] 2018-03-08 08:18
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by Realerik** [comment] 2018-03-27 10:13
### Issue description
After an online audio stream has been played for several minutes an E/ExoPlayerImplInternal: Source error happens.
The people who have this problem all use android 7 on their devices.
I am using a service, that is running in the foreground. I am also using a wifi lock, a wake lock and i have increased the timeout of the player to 15 seconds.

### Version of ExoPlayer being used
r2.5.4 and in another project 2.6.1. (happens in both versions)

### A full bug report
[bugreport-NMF26O-2018-03-27-11-33-11.zip](https://github.com/google/ExoPlayer/files/1851470/bugreport-NMF26O-2018-03-27-11-33-11.zip)


### Exception
E/ExoPlayerImplInternal: Source error.
                                                                                   com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://stream.104.6rtl.com/rtl-live/mp3-128/AppleTVApp/
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
                                                                                       at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                       at java.lang.Thread.run(Thread.java:761)
                                                                                    Caused by: java.net.SocketTimeoutException: connect timed out
                                                                                       at java.net.PlainSocketImpl.socketConnect(Native Method)
                                                                                       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:341)
                                                                                       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                                                                                       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                                                                                       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                                                                                       at java.net.Socket.connect(Socket.java:635)
                                                                                       at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
                                                                                       at com.android.okhttp.Connection.connectSocket(Connection.java:221)
                                                                                       at com.android.okhttp.Connection.connect(Connection.java:197)
                                                                                       at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:392)
                                                                                       at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                                                       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:356)
                                                                                       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:273)
                                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
                                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                                                                                       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                                                                       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)

**Comment by andrewlewis** [comment] 2018-03-28 15:58
Are you sure this isn't just a case of connecting timing out due to network unreliability?

**Comment by Realerik** [comment] 2018-03-30 13:49
I am not sure. I can only say, that this is the exception, that i regulary see and as i said before it seems to happen only on android 7 devices, if the app is in the background.

**Comment by andrewlewis** [comment] 2018-04-05 18:51
Do you have steps to reproduce the issue or any other information that might help diagnosing it? There isn't much to go on (and the provided bug report doesn't seem to include the exception stack trace above).

**Comment by ojw28** [comment] 2018-04-21 08:42
Closing due to lack of information.

**Closed as completed by ojw28** 2018-04-21 08:42 UTC
Labels: need more info
