### ISSUE TITLE
Network type in DefaultBandwidthMeter is always unknown on first playback

### ISSUE THREAD

**Issue by vishnuchilakala** [google/ExoPlayer#10728] opened 2022-10-28 11:42 UTC
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

All devices

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Create a DefaultBandwidthMeter and override the initial bandwidth estimate for your network type. Since I am working on a WiFi network, I have overridden the estimate as below. 
2. Hook it to the player in `PlayerActivity.java` using Exoplayer.Builder.
```kotlin
DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter.Builder(getApplicationContext())
          .setInitialBitrateEstimate(C.NETWORK_TYPE_WIFI, 100L)
          .build();
// PlayerActivity.java - Line 273
ExoPlayer.Builder playerBuilder = new ExoPlayer.Builder(/* context= */ this)
              .setMediaSourceFactory(createMediaSourceFactory())
              .setBandwidthMeter(defaultBandwidthMeter);
```
3. Check the bitrate using `BandwidthMeter.getBitrateEstimate`.

### Expected result

The bitrate estimate should be overridden by the value I provided i.e. 100L.

### Actual result

The bitrate estimate always is 100000L i.e. the default value for unknown network type on the first playback attempt. On the subsequent playbacks, the bandwidth value is as expected.

### Media

Any media would work.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by vishnuchilakala** [comment] 2022-10-28 14:36
PR raised to fix this issue: https://github.com/google/ExoPlayer/pull/10729

**Comment by tonihei** [comment] 2022-11-01 15:37
> The bitrate estimate always is 100000L i.e. the default value for unknown network type on the first playback attempt. 

How did you test this? I just checked in our demo with the default config and with an explicit override for the initial estimate and it all worked as expected. 

> Check the bitrate using BandwidthMeter.getBitrateEstimate

Note that the network type is determined asynchronously (it requires a single message sent to the main handler to be precise) and if you immediately query the bitrate estimate in the method that creates the BandwidthMeter, it is still on the unknown network type. This doesn't effect playback though as the network init happens instantly within one message sent to the main thread and starting playback requires much more preparation than that. 


I'll close this issue assuming everything is working as intended.

**Closed as completed** 2022-11-01 15:42 UTC
Labels: wont fix: intended behavior
