### ISSUE TITLE
Please help me convert RGB_565 to ARGB_8888,

### ISSUE THREAD

**Issue by Witype** [google/ExoPlayer#2566] opened 2017-03-17 02:33 UTC
I use extension-vp9 module ,the method renderRgbFrame convert .webm file to RGB_565 Frame,it not support alpha channel,I want make the black background to transparent,such as ARGB_8888,ARGB4444，anybody can help me solve this question,will be thanks for any help!
~~~
  private void renderRgbFrame(VpxOutputBuffer outputBuffer, boolean scale) {
    if (bitmap == null || bitmap.getWidth() != outputBuffer.width
        || bitmap.getHeight() != outputBuffer.height) {
      bitmap = Bitmap.createBitmap(outputBuffer.width, outputBuffer.height, Bitmap.Config.RGB_565);
    }
    bitmap.copyPixelsFromBuffer(outputBuffer.data);
    Canvas canvas = surface.getHolder().lockCanvas();
    if (scale) {
      canvas.scale(((float) canvas.getWidth()) / outputBuffer.width,
          ((float) canvas.getHeight()) / outputBuffer.height);
    }
    canvas.drawBitmap(bitmap, 0, 0, null);
    surface.getHolder().unlockCanvasAndPost(canvas);
  }
~~~
![image](https://cloud.githubusercontent.com/assets/6899329/24026537/c67fffba-0afc-11e7-93c8-b2aef985886a.png)

**Comment by ojw28** [comment] 2017-03-23 18:26
Duplicate of https://github.com/google/ExoPlayer/issues/2588.

**Closed as completed by ojw28** 2017-03-23 18:26 UTC
Labels: question
