### ISSUE TITLE
Support seeking in FLV

### ISSUE THREAD

**Issue by lulululbj** [google/ExoPlayer#3284] opened 2017-09-22 07:26 UTC
In  `FlvExtractor.java` ，we can't seek  the progress when we play the flv video in default.

```
  @Override
  public boolean isSeekable() {
    return false;
  }
```
Is it necessary to make FLV unseakable ?

**Comment by VCone** [comment] 2017-09-22 15:41
to ExoPlayer, see this post for context :  
https://stackoverflow.com/questions/46359518/seekable-of-flv-with-exoplayer

Where  asker took **_return false;_** and it was changed to  **_return true;_** .  
Seeking within an FLV timeline now worked.

**Comment by ojw28** [comment] 2017-09-22 15:44
I'm pretty sure that StackOverflow post is incorrect. Changing false to true doesn't enable anything (other than resetting the position to the start of the file).

**Comment by ojw28** [comment] 2017-09-24 12:11
Marking as a duplicate of https://github.com/google/ExoPlayer/issues/3251.

**Closed as completed by ojw28** 2017-09-24 12:11 UTC
Labels: duplicate, enhancement

**Comment by lulululbj** [comment] 2017-09-27 03:04
I chage `false` to `true` , then I can seek the progressbar. The flv video was recorded by myself.

**Comment by ojw28** [comment] 2017-09-27 08:05
You might be able to drag the bar, but I'm pretty sure that regardless of where you release it, playback will restart from the beginning.

**Comment by lulululbj** [comment] 2017-09-27 08:45
It will not restart from the beginning, but the position I seek to. At least when I play the video recorded by myself it's ok. I had uploaded my test flv video on my github , this is the [download link](https://github.com/lulululbj/LeetCode/blob/master/src/main/resources/1506501121874.mp4) . You can download it and have a try.

**Comment by andrewlewis** [comment] 2017-09-27 08:57
After the change to make `isSeekable` return true, when you seek the extractor it is still loading data from the beginning but the player discards data up to the playback position. Seeking to timestamps that aren't close to the beginning of a longer video is going to be unusably slow and wasteful. Try with the Big Buck Bunny (FLV Video) sample in the demo app to see this.

**Comment by lulululbj** [comment] 2017-09-28 00:54
Thank you for your answer very much . My test video is only 15 seconds , so I think it's ok to change `isSeekable` return true. It is indeed not a good idea to make it return true in `FlvExtractor.java`.
