### ISSUE TITLE
TrackSelectionDialog shows all tracks as disabled when trying to download the clearkey protected content in demo app

### ISSUE THREAD

**Issue by Sahil333** [google/ExoPlayer#6144] opened 2019-07-09 00:23 UTC
### [REQUIRED] Searched documentation and issues
I looked [here](https://exoplayer.dev/downloading-media.html) and followed this [issue](https://github.com/google/ExoPlayer/issues/2643) as well. In the issue someone [mentioned ](https://github.com/google/ExoPlayer/issues/2643#issuecomment-392518392) that he was able to download the content but I can't get it how.

### [REQUIRED] Question
I have been trying to add a download feature in my app. My content is protected by clearkeys. I have been trying to download the content using DownloadService and manage keys download by myself as OfflineLicenseHelper doesn't support clearkey content (It gives unsupported format error).  

The demo app doesn't support download of protected content, so i tried to bypass it by changing the relevant lines [here](https://github.com/google/ExoPlayer/blob/1ab402cf27ab3c52d671ef15b25a1cdde1fe84c8/demos/main/src/main/java/com/google/android/exoplayer2/demo/SampleChooserActivity.java#L193). After doing this, the track selection dialog appears but all tracks are disabled as in the fig. I tried to use addTrackSelection() directly without showing trackselectiondialog with default parameters but no track is being added.
![Screenshot_2019-07-09-05-28-14-84](https://user-images.githubusercontent.com/14136740/60850461-114c5300-a20d-11e9-8b70-f054d7bef9e0.png)

**Comment by tonihei** [comment] 2019-07-09 08:04
That's more or less a duplicate of #6129. You need to provide a DrmSessionManager to the DownloadHelper to be able to select protected formats.

**Closed as completed** 2019-07-09 08:04 UTC
Labels: duplicate

**Comment by Sahil333** [comment] 2019-07-09 11:33
@tonihei Thanks for the quick reply. It worked for me :D.
