### ISSUE TITLE
The exoplayer was created using the child thread looper, and verifyCurrentThread() reported an error when receiving the callback onSurfaceChanged()

### ISSUE THREAD

**Issue by strivexiong** [google/ExoPlayer#11346] opened 2023-11-21 02:05 UTC
I encountered an issue with the creation of exoplayer using a custom child thread looper, and the verifyCurrentThread() failed to report an error when the exoplayer bound surface received the callback onSurfaceChanged(). The thread corresponding to exoplayer is a child thread, but the thread that calls back to onSurfaceChanged() is the main thread. How can I solve this problem

**The exoplayer creation code is as follows:**
```
new ExoPlayer.Builder(mContext)
    .setLooper(subHandler.getLooper())
    .setPlaybackLooper(subHandler.getLooper())
    .build();
```

**The error log is as follows:**
2023-11-21 09:55:31.025 24829-24829 SurfaceView xxx E Exception configuring surface
java.lang.IllegalStateException
at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:92)
at com.google.android.exoplayer2.util.ListenerSet.verifyCurrentThread(ListenerSet.java:312)
at com.google.android.exoplayer2.util.ListenerSet.queueEvent(ListenerSet.java:221)
at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:262)
at com.google.android.exoplayer2.ExoPlayerImpl.maybeNotifySurfaceSizeChanged(ExoPlayerImpl.java:2714)
at com.google.android.exoplayer2.ExoPlayerImpl.access$1800(ExoPlayerImpl.java:120)
at com.google.android.exoplayer2.ExoPlayerImpl$ComponentListener.surfaceChanged(ExoPlayerImpl.java:3074)
at android.view.SurfaceView.updateSurface(SurfaceView.java:1036)
at android.view.SurfaceView.setFrame(SurfaceView.java:450)
at android.view.View.layout(View.java:23851)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23854)
at android.view.ViewGroup.layout(ViewGroup.java:6439)
at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
at android.view.View.layout(View.java:23854)
at android.view.ViewGroup.layout(ViewGroup.java:6439)
at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
at android.view.View.layout(View.java:23854)
at android.view.ViewGroup.layout(ViewGroup.java:6439)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23854)
at android.view.ViewGroup.layout(ViewGroup.java:6439)
at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:536)
at android.view.View.layout(View.java:23854)
at android.view.ViewGroup.layout(ViewGroup.java:6439)

**Comment by tianyif** [comment] 2023-11-21 16:55
Hi @strivexiong,

Please checkout the [note on threading](https://developer.android.com/guide/topics/media/exoplayer/hello-world#a-note-on-threading) where we recommend to use the ExoPlayer on application's main thread: 

"ExoPlayer instances must be accessed from a single application thread. For the vast majority of cases, this should be the application's main thread."

Is there any reason that you avoid accessing ExoPlayer from main thread?

**Comment by icbaker** [comment] 2023-11-21 17:33
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/10333

**Closed as completed by icbaker** 2023-11-21 17:33 UTC
Labels: duplicate

**Comment by marcbaechinger** [comment] 2023-11-21 17:39
Just checking this is not the root of the issue:

```
    .setLooper(subHandler.getLooper())
    .setPlaybackLooper(subHandler.getLooper())
```

I think you should not use the same looper as the playback thread looper and the application looper. I don't think this is documented somewhere and I haven't thought about it in detail, but I think this shouldn't be done.

If I'm right and this shouldn't be done, the `ExoPlayer.Builder` could also verify this and throw with an explanation.

**Comment by strivexiong** [comment] 2023-11-28 07:13
Thank you all for your responses.

I found a solution. When the player is bound to the surface, if the setVideoSurfaceView() interface is called, exo will listen to the life cycle state of the view. The view life cycle callback is on the main thread, and the above exception occurs if the exo is created in a child thread. 

However, if you call **setVideoSurface**() directly to bind the surface, in this method, _componentListener_ is not registered, and the view lifecycle callback is not called. So if you call setVideoSurface() directly, you will not receive an exception even if you create exo in the child thread.
