### ISSUE TITLE
How to Locally build after commit "Move common gradle setup to a setting file"?

### ISSUE THREAD

**Issue by fgl27** [google/ExoPlayer#7554] opened 2020-06-27 12:50 UTC
After https://github.com/google/ExoPlayer/commit/4138e28d626be428f5d84b77138f90006b233c08 can't do local builds

To build locally I use https://github.com/google/ExoPlayer/tree/dev-v2#locally

And worked for a long time, after above commit I get a studio error `Could not read script '/home/fgl27/workspace/ExoPlayer/ExoPlayer/common_library_config.gradle' as it does not exist.`

That happens to all file, if I fix one single file by setting the correct path manually it happens to another and another so on so on.

As one can see the word `ExoPlayer` is getting duplicated somehow and no is not my local files fault, I already check there is no duplicated info on my local [settings.gradle](https://github.com/fgl27/SmartTwitchTV/blob/master/apk/settings.gradle) after all it worked prior this change.

So what to do here?

**Comment by fgl27** [comment] 2020-06-27 12:56
So the problem is because I'm using this
`gradle.ext.exoplayerRoot = '../../ExoPlayer'`
that worked before but now needs to be modified
to 
`gradle.ext.exoplayerRoot = "$rootDir/../../ExoPlayer"`

**Comment by ojw28** [comment] 2020-06-27 14:16
I think we should keep it so that relative paths work as well.

**Comment by tonihei** [comment] 2020-07-03 07:48
The issue should be fixed by the commit above, please let us know if it still occurs. Thanks!

**Closed as completed by tonihei** 2020-07-03 07:48 UTC
Labels: bug

**Comment by christianfrank84** [comment] 2020-08-31 12:37
For me the issue is still occuring. 

It keeps looking for the `Exoplayer/common_library_config.gradle` within my project folder. Even tho Exoplayer is not located within my project root, but instead one folder above. 

This is how I am referencing Exoplayer in my project. 
`gradle.ext.exoplayerRoot = '../Exoplayer'
gradle.ext.exoplayerModulePrefix = 'exoplayer-'
apply from: new File(
        gradle.ext.exoplayerRoot, 'core_settings.gradle')
`

following this medium article https://medium.com/google-exoplayer/howto-2-depend-on-a-local-checkout-of-exoplayer-bcd7f8531720

**Comment by tonihei** [comment] 2020-09-07 13:12
@christianfrank84  I just verified the steps again and can't see a problem. Here is what I did:

1. Checked out ExoPlayer and changed to dev-v2 branch:
```
git clone https://github.com/google/ExoPlayer.git
cd ExoPlayer
git checkout dev-v2
```
2. Created a new empty Android Studio project in `../Project`. The directory structure now looks like this (among others):
```
root/ExoPlayer/common_library_config.gradle
root/ExoPlayer/core_settings.gradle
root/Project/setting.gradle
```
3. Modified `setting.gradle` to end with the following lines:
```
gradle.ext.exoplayerRoot = '../ExoPlayer'
gradle.ext.exoplayerModulePrefix = 'exoplayer-'
apply from: new File(gradle.ext.exoplayerRoot, 'core_settings.gradle')
```
4. Ran gradle sync and now have all exoplayer modules as source.
