### ISSUE TITLE
`Play` Action from MediaSession not handled correctly after a `Pause` action

### ISSUE THREAD

**Issue by georgi-neykov-hub** [google/ExoPlayer#6121] opened 2019-07-02 16:32 UTC
### [REQUIRED] Issue description
MediaSessionConnector does not properly handle `play` commands from a MediaSession after a `pause` command has been handled.
If one looks at the `MediaSessionCompat.Callback.onPlay()` implementation inside `MediaSessionConnector`at [this line](https://github.com/google/ExoPlayer/blob/r2.10.2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L1061) it will notice that if the `Player` instance's playback state is `Player.STATE_READY` the player will not be isntructed to start playing again via `controlDispatcher.dispatchSetPlayWhenReady()` and the media session command will just do nothing. 

### [REQUIRED] Reproduction steps
The Exoplayer demo app does not post media notifications (at least I did not found a way to do it) so no direct way to reproduce it from there. Any application/code using `MediaSessionConnector` will suffice. 
The steps are:
* Initialize a `MediaSessionCompat` and make it active.
* Initialize a `ExoPlayer` instance, give it some `DataSource` that will load something to be played.
* Initialize a `MediaSesionConnector` instance with the initialized session instance.
* By using a `TransportControls` instance (can be obtained via MediaSession.getController().getTransportControls()) make an `play`action. After the playback starts, make a `pause` action.
* Try again to execute a `play` action, eventually the code form the link in the bug description will execute, and the player will be in `Player.STATE_READY` state, which will skip all if-else blocks and ignore the command.

### [REQUIRED] Link to test content
Any playable content will suffice, the bug is not about the media type, but how playback commands are handled.

### [REQUIRED] A full bug report captured from the device
No reason to post a bug report, there aren't any crashes.

### [REQUIRED] Version of ExoPlayer being used
2.10.2

### [REQUIRED] Device(s) and version(s) of Android being used
The bug involves code in a callback inside `MediaSessionConnector`, no `MediaCodec`s, no HALs or anything involved, the Android version or device is irrelevant.

**Comment by ojw28** [comment] 2019-07-02 16:33
Duplicate of https://github.com/google/ExoPlayer/issues/6093

**Closed as completed by ojw28** 2019-07-02 16:33 UTC
Labels: duplicate
