### ISSUE TITLE
UDP Stream is not working in Exoplayer

### ISSUE THREAD

**Issue by msilucifer** [google/ExoPlayer#7668] opened 2020-07-24 15:23 UTC
Hello.

### Question
How to implement UDP stream using Exoplayer?

I am trying to test UDP stream using Exoplayer while VLC mediaplayer is streaming a video file.
But I am not able to open UDP stream in exoplayer and I can get only bugs.
It will be great help if someone can guide me and share the code for playing UDP stream in ExoPlayer.

Here is the code I used and the bug report that occurred.

### Code
    ...
    DataSource.Factory factory = () -> new UdpDataSource(3000, 100000);
    ExtractorsFactory tsExtractorFactory = () -> new TsExtractor[]{new TsExtractor(TsExtractor.MODE_SINGLE_PMT,
        new TimestampAdjuster(0), new DefaultTsPayloadReaderFactory())};
    MediaSource mediaSource = new ExtractorMediaSource(Uri.parse("udp://@IP:PORT"), factory, 
    tsExtractorFactory,null,null);
    player = new SimpleExoPlayer.Builder(getApplicationContext()).build();
    player.prepare(mediaSource);
    ...

### A full bug report captured from the device
     E/EventLogger: internalError [eventTime=1.06, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.upstream.UdpDataSource$UdpDataSourceException: java.net.BindException: bind failed: EADDRNOTAVAIL (Cannot assign requested address)
        at com.google.android.exoplayer2.upstream.UdpDataSource.open(UdpDataSource.java:108)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.BindException: bind failed: EADDRNOTAVAIL (Cannot assign requested address)
        at libcore.io.IoBridge.bind(IoBridge.java:99)
        at java.net.PlainDatagramSocketImpl.bind(PlainDatagramSocketImpl.java:60)
        at java.net.DatagramSocket.bind(DatagramSocket.java:484)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:428)
        at com.google.android.exoplayer2.upstream.UdpDataSource.open(UdpDataSource.java:105)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: android.system.ErrnoException: bind failed: EADDRNOTAVAIL (Cannot assign requested address)
        at libcore.io.Posix.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
        at libcore.io.IoBridge.bind(IoBridge.java:97)
        at java.net.PlainDatagramSocketImpl.bind(PlainDatagramSocketImpl.java:60) 
        at java.net.DatagramSocket.bind(DatagramSocket.java:484) 
        at java.net.DatagramSocket.<init>(DatagramSocket.java:428) 
        at com.google.android.exoplayer2.upstream.UdpDataSource.open(UdpDataSource.java:105) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
    ]

**Comment by krocard** [comment] 2020-07-27 09:56
@marcbaechinger I'm assigning to you according to the triage guide, but @ojw28 might be able to help as he was the reviewer of the implementation in [Internal ref: cl/98668385].

My analysis:

First, from the stacktrace, this is an UDP address (not multicast).

Looking at [UdpDataSource.open(DataSpec)](https://github.com/google/ExoPlayer/blob/r2.11.7/library/core/src/main/java/com/google/android/exoplayer2/upstream/UdpDataSource.java#L92) (comments added by me):
~~~ java
  public long open(DataSpec dataSpec) throws UdpDataSourceException {
    uri = dataSpec.uri;                  // This is the uri of the server sending the media
    String host = uri.getHost();         // _remote_ host sending the media
    int port = uri.getPort();            // _remote_ port of the _remote_ host sending the media 
    address = InetAddress.getByName(host);
    socketAddress = new InetSocketAddress(address, port); // _remote_ socket sending the media
    socket = new DatagramSocket(socketAddress);
...
~~~
The [documentation of DatagramSocket](https://docs.oracle.com/javase/7/docs/api/java/net/DatagramSocket.html#DatagramSocket(java.net.SocketAddress)) says:
> Creates a datagram socket, bound to the specified local socket address.

And looking at the code, I can confirm, it calls `bind` to bind with the provided (remote!) socket.

As is does not make sense to bind to a remote address, it throws EADDRNOTAVAIL.

In fact I can not see how `UdpDataSource` can ever work except maybe if the sender and the receiver are using the same interface and `SO_REUSEADDR`.
I think the code should be:
~~~ java
    socket = new DatagramSocket(); // let it bind to any local address & available port
    socket.connect(socketAddress); // Connect it to the remote socket
~~~

Similarly for the multicast, the `MultiCastSocket` is binded to the remote address which does not make sense to me.

I'm very confused at how the current implementation can work, but it must given that this code has not changed since 2015.

**Comment by ojw28** [comment] 2020-08-03 19:30
It looks like the implementation changes were made in response to [this comment](https://github.com/google/ExoPlayer/commit/709fc7735b9038ab8ea8399b4e2308587d98bd80#r11338612) by @tresvecesseis . Looking back, I'm not sure that comment is really correct.

@tresvecesseis - Could you clarify exactly what this means:

> This could be a problem if you have multiple multicast groups with the same port active in the the LAN (as we have in our multiroom configuration), it would be better if you bound the multicast socket to the local address.

What specifically could be a problem? For `MulticastSocket`, if you just specify the port through the constructor, then I think a wildcard address is used. It's unclear how multiple multicast groups would cause a problem, since the code connects to the specific group that it wants to connect to by calling `multicastSocket.joinGroup(address)`.

Secondly, are you sure this line of code in your suggestion was correct:

> socket = new DatagramSocket(sockAddr);

I agree with @krocard that this looks wrong, and that the suggested code snippet above is probably the correct one. Did you ever have this working end-to-end?

**Comment by milan-fabian** [comment] 2021-01-06 14:51
Hi,

I have been playing a little bit with UDP streams in Exoplayer and I would like to add some insights from the testing, which will maybe help with this issue.

The current implementation with `socket = new DatagramSocket(socketAddress);` actually works in following case:

- Streaming from computer (IP 192.168.1.10): `ffmpeg -re -i "video.mp4" -c copy -f mpegts "udp://192.168.1.11:1234"`
- Receiving on an Android device (IP 192.168.1.11): Exoplayer with address `udp://192.168.1.11:1234`

So basically I am "pushing" packets to the IP address of an Android device and Exoplayer is listening on the local address and waiting for the packets. Exoplayer plays the video, quite smoothly on one Android device, really laggy on another, but that is probably a different problem.

I tried the other way around, streaming from computer to local address and using `new DatagramSocket().connect(socketAddress)` to play the stream, but all I got was a timeout. I am not sure if you could actually "request" UDP video stream from another device (that's what `new DatagramSocket().connect(socketAddress)` should do), but I don't have anything to back up my theory.

So the current implementation is correct for one case, the question is whether it is even possible to do it other way round.

**Comment by krocard** [comment] 2021-01-12 10:57
Thanks for your explanation and testing @milan-fabian, I understand how it works now.
So the `DataSpec` passed to `UdpDataSource.open` is _not_ the uri of the server streaming the media, it is instead the local port and interface that should be opened to receive the data.
Additionally, no UDP filtering occurs, meaning that any udp packet sent to the device port will be played, regardless of it source.

To answer @msilucifer question, in the current code, you need to have the `IP` in your code `Uri.parse("udp://@IP:PORT")` set to`localhost` and `PORT` as the local port of your device you are streaming to from vlc (usually 1234). The remote IP and port should not be used.

In the future, we might want to change `UdpDataSource` so that the URI provided to open is that of the remote server.  
 1) Either by passing passing to the `UdpDataSource` constructor the local ip and port and passing the remote ip and port in the `DataSpec` passed to open, allowing to `connect` to it (aka filter out any packet not from this source).
 2) Or, if if understand correctly the [udp uri scheme specification](https://www.iana.org/assignments/uri-schemes/prov/udp) which sets the syntax as `udp://[<localaddress>@]<destination|multicastgroup>[:<port>]`. The local address should be retrieved from the `user data` section. If <localadress> is left unspecified, it seems the socket should be bound to all local interfaces. The problem is that only one port is specified, when 2 are needed: the local port to know where to bind to and the remote on to connect to. From the examples I could find around the web it seems very clear that the `<port>` in the URI is that of the local socket. No idea where the remote port is to be find, but I don't think a connect is possible without the remote port.
@AquilesCanta I think this UDP stream specification is a subset of MPEG-TS, are you aware of it?

This UDP data source behaviour is very similar to the upcoming RTP data source. @lcf87 do you have a recommendation on how/if the `UdpDataSource` should be updated to allow incoming source filter and if it is even needed in practice? We could alternatively use `recvfrom` on each received packet to check the source ip similarly to what the kernel does after a `connect`.

On a practical side, I think we have a couple of options:
 1) do nothing and ask all clients to use `udp://localhost:<their local port>` as an UDP URI. (even though this is incompatible with standard `udp://` uris)
 2) get the host we are binding to from the `user data`. Aka replace `String host = uri.getHost()` by `String host = uri.getUserData()` [here](https://github.com/google/ExoPlayer/blob/r2.11.7/library/core/src/main/java/com/google/android/exoplayer2/upstream/UdpDataSource.java#L94) and ignore the URI's `host`.
 3) Something else?

I think option 1 probably makes the most sense given that few user use this class, though @lcf87 I would be very interested in your opinion.

**Comment by krocard** [comment] 2021-01-12 14:48
@msilucifer To be clair, you should use `localhost` as the IP in your `udp://@IP:PORT` URI. It should fix the `Exception: bind failed: EADDRNOTAVAIL (Cannot assign requested address)` BindException. Please report if this does not fixes your issue.

I'm keeping this issue open to have a discussion with @milan-fabian,  @lcf87 and @AquilesCanta about `UdpDataSource`'s current `udp://` URI semantic parsing as it seems incorrect according to the spec.

**Comment by msilucifer** [comment] 2021-01-12 15:15
Thanks for your guide.
But I don't want to use localhost as the IP.
For instance, if "192.168.1.10" is my target address, how should I set the ip addresss?

**Comment by krocard** [comment] 2021-01-12 17:51
> But I don't want to use localhost as the IP.

Contrary to the other `DataSource`, IP and PORT in the URI passed to `UdpDataSource.open` are that of the _local_ socket to open to receive the stream.

Though you are right that `localhost` might restrict you to the loopback interface. I did not think of that in my previous comment.
Instead a wildcard address should be used. `0.0.0.0` for ipv4, `::` on ipv6.

> For instance, if "192.168.1.10" is my target address, how should I set the ip address?

When you setup the stream on the server (eg. vlc), you must specify the address and port of the Android device, so here "192.168.1.10" and port 1234.  
As UDP is not a connected protocol, it does not need to know IP of the emitter to receive the stream. On your android device, set the URI passed to `UdpDataSource` to `udp://@0.0.0.0:1234`.

**Comment by krocard** [comment] 2021-01-12 18:23
From [my earlier comment](https://github.com/google/ExoPlayer/issues/7668#issuecomment-758577643)
> Or, if if understand correctly the udp uri scheme specification ... `udp://[<localaddress>@]<destination|multicastgroup>[:<port>]`

I had _not_ understood correctly the specification. The destination address is the address of the current device. So the code is currently correct!

The only thing I would change is to interpret a missing URI host as the wildcard address as VLC does. This would allow to specify the URI as `udp://@:1234` and would allow to specify the URI independently of ipv4 or ipv6. What do you think @lcf87?

**Comment by krocard** [comment] 2021-01-12 18:25
@msilucifer to summarize use `udp://0.0.0.0:1234` as URI.

**Comment by krocard** [comment] 2021-01-12 19:07
While digging a bit deeper to make a change making the host optional, I discovered that on Linux (and thus Android), binding to `::` binds to _both_ ipv6 and ipv4. But this is a configurable option and while currently enabled on my Pixel 4, might not be something we want to rely on.

**Comment by krocard** [comment] 2021-01-13 12:47
Closing this as the solution was found (using `udp://0.0.0.0:1234` or `udp://:::1234` as URI).

**Closed as completed by krocard** 2021-01-13 12:47 UTC
Labels: question
