### ISSUE TITLE
ExoPlayer Widevine Drm Need Help

### ISSUE THREAD

**Issue by SystemRestored** [google/ExoPlayer#4067] opened 2018-04-01 05:36 UTC
0
down vote
favorite
Hello I am developing an application where I will be available to play dash stream with widevine drm protection. I have read the sample of exoplayer but my need is different, I will on my website, and when click the dash url it will start playing the stream in exoplayer. I have succeeded in doing first part for opening the exoplayer activity, however I dont know how I can run the drm protected stream on exoplayer.

I know the stream and drm licence url.

A simple code I am working on is attached below. Kindly help me with additional code for drmsessionmanager and etc. To run stream

here is my code which only supports mpd without drm:

`    public class exoplayer2 extends AppCompatActivity { // Variables
     private static final String VIDEO_URI = "http://url.mpd";

    private SimpleExoPlayer player;
    private SimpleExoPlayerView simpleExoPlayerView;
    private Handler mainHandler;
    private TrackSelection.Factory videoTrackSelectionFactory;
    private TrackSelector trackSelector;
    private LoadControl loadControl;
    private DataSource.Factory dataSourceFactory;
    private MediaSource videoSource;
    private Uri uri;
    private String userAgent;
    private static final DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();

    // Activity onCreate
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        super.onCreate(savedInstanceState);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.activity_exoplayer);
        simpleExoPlayerView = (SimpleExoPlayerView)findViewById(R.id.player_view);
        userAgent = Util.getUserAgent(this,"SimpleDashExoPlayer");
        createPlayer();
        attachPlayerView();
        preparePlayer();
    }

    // Create TrackSelection Factory, Track Selector, Handler, Load Control, and ExoPlayer Instance
    public void createPlayer(){
        mainHandler = new Handler();
        videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        loadControl = new DefaultLoadControl();
        player = ExoPlayerFactory.newSimpleInstance(this,trackSelector,loadControl);
    }

    // Set player to SimpleExoPlayerView
    public void attachPlayerView(){
        simpleExoPlayerView.setPlayer(player);
    }

    // Build Data Source Factory, Dash Media Source, and Prepare player using videoSource
    public void preparePlayer(){
        uriParse();
        dataSourceFactory = buildDataSourceFactory(bandwidthMeter);
        videoSource = new DashMediaSource(uri,buildDataSourceFactory(null),new DefaultDashChunkSource.Factory(dataSourceFactory),mainHandler,null);
        player.prepare(videoSource);
    }

    // Parse VIDEO_URI and Save at uri variable
    public void uriParse(){
        uri = Uri.parse(VIDEO_URI);
    }

    // Build Data Source Factory using DefaultBandwidthMeter and HttpDataSource.Factory
    private DataSource.Factory buildDataSourceFactory(DefaultBandwidthMeter bandwidthMeter){
        return new DefaultDataSourceFactory(this, bandwidthMeter, buildHttpDataSourceFactory(bandwidthMeter));
    }

    // Build Http Data Source Factory using DefaultBandwidthMeter
    private HttpDataSource.Factory buildHttpDataSourceFactory(DefaultBandwidthMeter bandwidthMeter){
        return new DefaultHttpDataSourceFactory(userAgent, bandwidthMeter);
    }

    // Activity onStop, player must be release because of memory saving
    @Override
    public void onStop(){
        super.onStop();
        player.release();
    }
}

}`

**Comment by linhai326** [comment] 2018-04-02 22:00
you can find the sample code from the exoplayer demo's playActivity.java. Basically all you need to do is:
- create the drmSessionManager using the get license url.
- pass drmSessionManager to ExoPlayerFactory.newSimpleInstance
- and the rest will be handled by exoplayer.

**Comment by SystemRestored** [comment] 2018-04-03 02:28
@linhai326  thanks for your kind reply. I am a noob in this. Kindly help me. I have read the demo, and tried to do so.. I can use the demo application, however when I am copying the demo code in my application, some errors are coming like could not find ParcelableArray and etc. Can you give me additional code needed with the code shared above. I will be very helpful to you. Sorry for my english..

**Comment by tonihei** [comment] 2018-04-03 08:55
As @linhai326 already pointed out, you need to setup a DrmSessionManager which is passed to the player. The demo app is a good point to get started. Not that the demo app parses the drm scheme from the intent, that's why it tries to read from a ParcelableArray. No need to do this in your app.

**Comment by SystemRestored** [comment] 2018-04-03 16:29
I have already tried that and got one part in stuck: buildDrmSessionManagerV18( drmSchemeUuid, drmLicenseUrl, keyRequestPropertiesArray, multiSession); I get error that buildDrmSessionManagerV18 the method cannot be resolved my license url and drm scheme is same so I dont need and intent, can you help me with the additional code to the above needed

**Comment by tonihei** [comment] 2018-05-04 16:42
If you like us to look further, please provide concrete reproduction steps and sample media.

**Comment by tonihei** [comment] 2018-05-17 08:14
Closing due to lack of information.

**Closed as completed by tonihei** 2018-05-17 08:14 UTC
Labels: question, need more info
