### ISSUE TITLE
Pause and resume Ad will cut off ads

### ISSUE THREAD

**Issue by maxTanquerel** [google/ExoPlayer#6030] opened 2019-06-13 16:31 UTC
### [REQUIRED] Issue description
When an ad is paused, then resumed, we can see the "Learn more" disappear, then the countdown will jump, second ad will not be playing entirely (sometime entire ad is skip to third one)

Video of issue : https://drive.google.com/open?id=1mvmjUpsvU57IXo4Duht4NHOLYhkjo0QF

### [REQUIRED] Reproduction steps
I am able to reproduce this issue in the exoplayer - demo ima project, branch release-v2. The only thing I changed is ad and content url + line 351 of PlayerView.java `boolean controllerHideDuringAds = true;` to `boolean controllerHideDuringAds = false;`

### [REQUIRED] Link to test content
adTag = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator="

content = "https://www.rmp-streaming.com/media/bbb-360p.mp4"

### [REQUIRED] A full bug report captured from the device
[Logs.txt]
(https://github.com/google/ExoPlayer/files/3287131/Ads.Paused.error.Logs.txt)

### [REQUIRED] Version of ExoPlayer being used
exoplayer : release-v2 branch, latest commit : https://github.com/google/ExoPlayer/commit/ecb7b8758cd6a700b72275a56d22b3dc56959764
ima : 3.11.2

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 2

**Comment by maxTanquerel** [comment] 2019-07-12 20:09
Any news on this ?

**Comment by andrewlewis** [comment] 2020-03-13 16:19
Given "AdError 402: VAST media file loading reached a timeout of 8 seconds.", I think this might be a duplicate of #4140. We are in the process of upgrading to new ads manager implements that should fix this problem.

**Comment by andrewlewis** [comment] 2020-05-18 15:35
I've verified this is fixed by migrating to the new IMA SDK preloading APIs (fa7d26dd9f94f52c412ff7d6490630dd73f187a6), and that change should be in a release soon.

**Closed as completed by andrewlewis** 2020-05-18 15:35 UTC
Labels: bug: in dependency
