### ISSUE TITLE
Progress bar customization in live HLS data

### ISSUE THREAD

**Issue by ahmetberkinc** [google/ExoPlayer#7862] opened 2020-09-07 12:33 UTC
I want to play live stream with HLS data on Exoplayer. I can access live stream data, but the timebar buffer range is limited to a certain time. In addition, when I stop the player, the live broadcast data continues to come in, so time moves towards negative after a while.
Could a method (similar to youtube live streaming feature) be provided with Exoplayer, such as starting or limiting the buffer range from the beginning of the program in live broadcast data?
![Screenshot_47](https://user-images.githubusercontent.com/40149789/92387415-26c55180-f11e-11ea-81af-85fda9d5cb70.png)
As can be seen in the picture, the live broadcast streaming occurs uninterruptedly, but access to the buffer is available at a certain interval (about 10 minutes).
![Screenshot_49](https://user-images.githubusercontent.com/40149789/92387836-ed411600-f11e-11ea-9f54-a6a5a2555237.png)
When the user stops streaming, time starts to move backwards and after a while it becomes negative.

**Comment by AquilesCanta** [comment] 2020-09-08 15:29
Can you explain exactly what the suggested change is? Please specific observed and expected behavior. The reason I ask is that I'm not clear on whether the required change is in the Player interface, in the ExoPlayer UI module, or both.

**Comment by ahmetberkinc** [comment] 2020-09-09 06:39
The structure I want to apply is that the duration on the playerview is dynamically updated while the live stream is in progress and the time flows forward (not remaining constant). In addition, when the user stops the live stream, the current time on the player does not flow backwards. So I think the change must be in the Exoplayer UI and buffer features.
![Screenshot_51](https://user-images.githubusercontent.com/40149789/92563164-d108ba80-f27f-11ea-86ed-c8579e66370e.png)

**Comment by ojw28** [comment] 2020-09-11 17:22
This is a duplicate of https://github.com/google/ExoPlayer/issues/2213. For now, I'm afraid the recommendation is to implement your own player UI if you require this kind of functionality.

**Closed as completed by ojw28** 2020-09-11 17:22 UTC
Labels: duplicate, question
