### ISSUE TITLE
Getting IllegalStateException on specific stream

### ISSUE THREAD

**Issue by lpv-1902** [google/ExoPlayer#9965] opened 2022-02-10 11:52 UTC
I am getting an IllegalStateException on this stream: https://serve-first.folxplay.tv/folx/ch-6/1080-X9PRFHOWUW.m3u8. The stream works fine on safari and Google Chrome with M3U8 player extensions.

```
[ExoPlayerImplInternal] Source error
[ExoPlayerImplInternal]   com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:442)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[ExoPlayerImplInternal]       at com.google.an02-10 11:50:29.298 E/ExoPlayerImplInternal( 3618):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[ExoPlayerImplInternal]       at java.lang.Thread.run(Thread.java:914)
[ExoPlayerImplInternal]   Caused by: java.lang.IllegalStateException
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.util.TimestampAdjuster.setFirstSampleTimestampUs(TimestampAdjuster.java:60)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:341)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:314)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
```

**Comment by ojw28** [comment] 2022-02-10 15:56
The media is malformed. If the stream provider intends these streams to be playable by applications that they don't control, then I would suggest you contact the stream provider and ask them to fix it. This is a duplicate of https://github.com/google/ExoPlayer/issues/9843.

**Closed as completed by ojw28** 2022-02-10 15:56 UTC
Labels: duplicate, bad media
