### ISSUE TITLE
Slow zapping - Exoplayer 2.12.1

### ISSUE THREAD

**Issue by hot1sp** [google/ExoPlayer#8703] opened 2021-03-11 16:52 UTC
Hi We experiencing a delay between 5 to 10 seconds on normal Live channel zapping, Analysis of the call to stream URL shows that actual call to get DASH manifest occurring between 5 to 10 seconds after setting stream URL and starting the prepare functionality on the player, calling to drm is after getting the manifest file . We had tried it also on the Exoplayer 2.13.1 version and result is the same Is there any specific customization we should make on the player to be compatible on working with high speed fiber network ?To emphasize that connecting Exoplayer to the Docs is network this issue does not occurring

here is the log file 
[logs](https://www.dropbox.com/s/1nz9k913bnfiuws/exoplayer_logs.txt?dl=0)
- ExoPlayer version number : 2.12.1
- Android version : 10
- Android device : sdmc

**Comment by tonihei** [comment] 2021-03-12 15:16
I can't see anything very unusual in the provided logs. The first video load takes about 6 seconds, the subsequent ones are all much faster. But all videos are seemingly immediately released once they become ready:

```
[First video start requested, manifest starts loading]
2021-03-11 18:19:06.993 16755-16755/il.net.hot.hott I/ExoPlayerImpl: Init ca37569 [ExoPlayerLib/2.12.1] [DV8555-KIH, HOT Streamer, SDMC, 29]
2021-03-11 18:19:07.001 16755-16755/il.net.hot.hott E/delayTest: onPlaybackStateChanged
2021-03-11 18:19:07.002 16755-16755/il.net.hot.hott E/delayTest: state buffering
...
[First video starts playing after loading manifest and DRM keys, 6 seconds in total]
2021-03-11 18:19:13.010 16755-16755/il.net.hot.hott E/delayTest: onPlaybackStateChanged
2021-03-11 18:19:13.011 16755-16755/il.net.hot.hott E/delayTest: state ready
...
[then player is released immediately]
2021-03-11 18:19:16.061 16755-16755/il.net.hot.hott I/ExoPlayerImpl: Release ca37569 [ExoPlayerLib/2.12.1] [DV8555-KIH, HOT Streamer, SDMC, 29] [goog.exo.core, goog.exo.ui, goog.exo.dash]

[Second video starts very quickly]
2021-03-11 18:19:17.512 16755-16755/il.net.hot.hott I/ExoPlayerImpl: Init 4da2867 [ExoPlayerLib/2.12.1] [DV8555-KIH, HOT Streamer, SDMC, 29]
2021-03-11 18:19:17.520 16755-16755/il.net.hot.hott E/delayTest: onPlaybackStateChanged
2021-03-11 18:19:17.521 16755-16755/il.net.hot.hott E/delayTest: state buffering
...
[Becomes ready and buffers again in 1 second]
2021-03-11 18:19:18.319 16755-16755/il.net.hot.hott E/delayTest: onPlaybackStateChanged
2021-03-11 18:19:18.319 16755-16755/il.net.hot.hott E/delayTest: state ready
2021-03-11 18:19:18.325 16755-16755/il.net.hot.hott E/delayTest: onPlaybackStateChanged
2021-03-11 18:19:18.326 16755-16755/il.net.hot.hott E/delayTest: state buffering
...
[player released after a further second]
2021-03-11 18:19:23.875 16755-16755/il.net.hot.hott I/ExoPlayerImpl: Release 4da2867 [ExoPlayerLib/2.12.1] [DV8555-KIH, HOT Streamer, SDMC, 29] [goog.exo.core, goog.exo.ui, goog.exo.dash]
...
[and so on]
```

It's hard to tell whether there is something wrong with your integration, with ExoPlayer, the device, or whether everything is actually working as intended. Could you provide more details for what your app is doing exactly with ExoPlayer, what you expect to happen, and if you think a certain stream is loaded much slower than expected, please also provide the stream itself.

**Comment by hot1sp** [comment] 2021-03-13 20:33
Thank you for quickly responding.
We are making a live streaming app with the help of the ExoPlayer.
We are releasing the player after every zap and re-create it again.
The regular behavior is about 1-1.5 sec loading between zapping and sometimes we got 6 sec delay as you notice in the log, 
It's happen in different channels also on channels that has been already loaded quickly. 
this is our implementation 
```
defaultHttpDataSourceFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent(context, context.getString(R.string.app_name)), bandwidthMeter);
        if (bandwidthMeter == null)
            bandwidthMeter = new DefaultBandwidthMeter.Builder(context).build();
        callback = new MyHttpMediaDrmCallback(context, TvConstants.getLicenseUrl(isCdn), true, defaultHttpDataSourceFactory, asset);
        frameworkMediaCryptoDefaultDrmSessionManager = new DefaultDrmSessionManager.Builder().build(callback);
        factory = new DefaultRenderersFactory(context);

        defaultTrackSelector = new DefaultTrackSelector(context);
        defaultTrackSelector.setParameters(defaultTrackSelector.buildUponParameters().setPreferredAudioLanguage("eng").build());

        mediaDataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, context.getResources().getString(R.string.app_name)), bandwidthMeter);
        bufferConfigurationInteractor.loadConfigurationFromSharedPreferences(context);
        DefaultLoadControl defaultLoadControl = new DefaultLoadControl.Builder().
                setBufferDurationsMs(bufferConfigurationInteractor.getMinBufferMS(),bufferConfigurationInteractor.getMaxBufferMS()
                        ,bufferConfigurationInteractor.getBufferPlaybackMS(),bufferConfigurationInteractor.getBufferPlaybackAfterRebufferMS()).build();
        player = new SimpleExoPlayer.Builder(context, factory).setLoadControl(defaultLoadControl).setTrackSelector(defaultTrackSelector).build();
        player.setSeekParameters(PREVIOUS_SYNC);
        player.setMediaSource(getCorrectMediaSource(streamType, url));
        playerView.setPlayer(player);
        playerView.setKeepContentOnPlayerReset(true);
        player.prepare();


private MediaSource getCorrectMediaSource(String streamType, String url) {
        switch (streamType.toLowerCase()) {
            default:
            case TvConstants.DASH:
                return new DashMediaSource.Factory(mediaDataSourceFactory)
                        .setDrmSessionManager(frameworkMediaCryptoDefaultDrmSessionManager)
                        .createMediaSource(MediaItem.fromUri(url));
            case TvConstants.MP3:
                return new ProgressiveMediaSource.Factory(mediaDataSourceFactory).createMediaSource(MediaItem.fromUri(url));
            case TvConstants.HLS:
                return new HlsMediaSource.Factory(mediaDataSourceFactory).createMediaSource(MediaItem.fromUri(url));
        }
    }
```

**Comment by tonihei** [comment] 2021-03-15 11:07
It still seems likely everything is working as intended. Whenever you start a new stream, there are a number of preperation steps before actual playback starts:
- Loading manifest. This adds at least one network round trip time.
- Loading DRM keys. Again, this requires one network round trip.
- Buffering sufficient media. This requires to buffer and extract at least X seconds worth of media for playback to start (2.5 seconds by default)
- Decoding media: A decoder needs to be initialized and media needs to be decoded just before playback to be shown on the screen.

Each of these steps adds a delay and depending on the server you are contacting, your network, etc., it may just take a couple of seconds to start.

However, there may be things you can do to speed this up:
 - Decoding media: You can keep the already initialized decoder if you don't release the player and create a new one. Instead, you can set a new source on the same player with `setMediaSource` to switch media.
 - Buffering sufficient media: If fast start-up is really important for your app, you could try to change the parameters of `DefaultLoadControl`. In particular try setting `bufferForPlaybackMs` to a lower value. Usually, it's also a good idea to download some initial seconds of media already to ensure a fast startup, but this doesn't work for live streams.
 - Loading manifest: You can force the player to preload the manifest of all available streams already, by adding all streams to the playlist (for example with `player.addMediaSources`) AND setting `SimpleExoPlayer.Builder.setUseLazyPreparation(false)`. Instead of setting a new source, you can then switch media by calling `player.seekToDefaultPosition(playlistIndex)`. Note that this causes the player to load all manifest of the items you set in the beginning. So if you have too many streams available, you can also only add some items to the playlist depending on which manifests you like to preload at any given time.
 - Loading DRM keys: It's possible to pre-acquire DRM sessions, but this is likely more complicated as you need to read the key information from the manifest (once available), trigger the pre-acquisition and make sure to release it after usage. There is also the problem that the number of available DRM sessions is limited on a device, so you can't preload all of them at once if there are many streams in the playlist.

**Comment by hot1sp** [comment] 2021-03-16 15:50
Thanks for the detailed information.
We are familiar with some of the points that you mention.
We will try some new techniques and update what's worked for us.

**Comment by tonihei** [comment] 2021-05-20 10:32
Closing because the question was answered.

**Closed as completed by tonihei** 2021-05-20 10:32 UTC
Labels: question
