### ISSUE TITLE
ExoPlayer 2.3.1 stays in downloading media segments phase -> missing onLoadCompleted()

### ISSUE THREAD

**Issue by m35w** [google/ExoPlayer#2847] opened 2017-05-19 10:39 UTC
### Issue description
Sometimes it happens that playback of HLS stream freezes because ExoPlayers starts fetching new media segments (onLoadStarted() is being called),
but it stays in that state i.e. onLoadCompleted() method's not executed.
During that period (e.g. 30minutes) there's no onLoadCompleted() or onLoadCancelled(), no errors (onPlayerError(), onLoadError()) but still every ~12sec ExoPlayers fetches m3u8 file (so there's no connection issue).
Also if I switch to other stream after that period, then onLoadCancelled() is being called to that missing media segment.

So there's the following scenario:

1) onLoadStarted()
2) then periodically ~12sec onLoadCompleted() related to m3u8 playlist
3) if I switch to other stream e.g. 30minutes later, then onLoadCancelled() comes related to media data from point 1).

Is it some known issue?
I expected that in such a situation some error would come.

### Reproduction steps
Unfortunately I'm not able to reproduce this by myself (I tried to downgrade the bandwidth, or disconnect the network just after onLoadStarted() is called, but all the time I received onLoadError()).
It only happens (sometimes) when I leave my application with HLS playback running for many hours (it's a stream which has a m3u8 updated periodically). 

### Version of ExoPlayer being used
2.3.1

### Device(s) and version(s) of Android being used
Xiaomi MIBOX3 with AndroidTV (version 6.0.1)

### A full bug report captured from the device
No errors visible

**Comment by ojw28** [comment] 2017-05-22 15:57
@AquilesCanta - This might be fixed by https://github.com/google/ExoPlayer/commit/002dd72e702929a33d8940cfbaa758459e0067c6? Or alternatively, it might be a stuck playlist case?

**Comment by AquilesCanta** [comment] 2017-05-22 16:31
This is most likely the second. Otherwise, the errors would be propagated via `AdaptiveMediaSourceEventListener#onLoadError`.

@m35w can you please try to reproduce by

>It only happens (sometimes) when I leave my application with HLS playback running for many hours (it's a stream which has a m3u8 updated periodically).

Once this happens, you could confirm the "playlist is stuck" by loading the playlist repeatedly. The expected behavior is that the media sequence increases with an interval at most as long as the target duration. If it doesn't, it means that the server got stuck, and ExoPlayer is waiting for new segments to be added to the playlist, which is not happening.

Once you confirm, we'll use this issue to track this enhancement.

**Comment by m35w** [comment] 2017-05-23 10:34
Hi,
thanks for the feedback.

I'm not sure what the following means:
> you could confirm the "playlist is stuck" by loading the playlist repeatedly"

could you please clarify it?

I general when the problematic issue occurs the following happens:

- onLoadCompleted() comes for some .ts let's say N.ts
- onLoadStarted() is fired for N+1.ts chunk
- lack of onLoadCompleted() for N+1.ts, also none of the following comes:
     onLoadError, onPlayerError, onLoadCancelled;
	 -> during that state only onLoadCompleted comes every ~12sec related to m3u8*;
	 -> nothing changes until e.g. I switch to other stream, in that case onLoadCancelled is being  
             called for N+1.ts
	    (but it can be e.g. 1 hour after onLoadStarted() was called for N+1.ts)
		
*it's a HLS live stream with dynamic window, so subsequent .ts chunks are added to m3u8 periodically.

**Comment by AquilesCanta** [comment] 2017-05-23 10:37
Ok, this is something I have not seen before, as far as I recall. Please provide a stream that reproduces this to dev.exoplayer@gmail.com. I will have a look as soon as I have time.

**Comment by AquilesCanta** [comment] 2017-05-23 10:39
I suspect this might be a server side issue. Although I would expect a timeout to happen.

**Comment by m35w** [comment] 2017-05-23 13:50
Well I don't have this exact stream chunk, as the content of streams changes dynamically so the media segments are replaced by the new ones on the streaming server.
I would need to be at my desk at the time when the issue appears (but usually it happens during a night hours).
If I manage to capture the stream I'll send it.

In a free time I will try to find a way to reproduce this scenario
(for the time being I tried to trim the network bandwidth, or disconnect the network, but is such situations onLoadError() was always fired)

**Comment by AquilesCanta** [comment] 2017-11-02 10:55
Hello @m35w, were you able to diagnose the issue? If I understand correctly, the problem here is that the Loader starts loading but no callback method is called (onLoadCompleted, onLoadCanceled, onLoadError). This could (very rarely) happen due to a number of reasons, but we will need to be able to reproduce to actually decide it's caused by ExoPlayer. Right now, I am inclined to think it is a server side issue. Please, if possible, provide any information that might help us debug this, and we will reopen the issue. It might be worth capturing a Loadable in this state and checking what's going on; and whether any data is being consumed. A specific combination of states might cause HlsMediaChunk to loop infinitely, but I wouldn't know how. Anyway, please add any useful information below and we will reopen.

**Closed as completed by AquilesCanta** 2017-11-02 10:55 UTC
Labels: bug
