### ISSUE TITLE
 v2: HLS live streaming getCurrentPosition can not get correct time position

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#2115] opened 2016-11-29 03:06 UTC
HLS live streaming getCurrentPosition can not get correct time position
ExoPlayer dev-v2 latest code
demo have same problem
dev-v1 work well

**Comment by ojw28** [comment] 2016-11-29 08:35
Closing because it ignores the issue template. The issue template provides a *very* clear list of six bullet points indicating what you should include to allow us to efficiently investigate your issue. This issue addresses two of the six bullet points only. It's just not an effective use of our time to try and guess what you mean and fill in all the gaps. If you want us to investigate an issue, please fill out the issue template properly. Thanks!

**Closed as completed by ojw28** 2016-11-29 08:35 UTC

**Comment by ojw28** [comment] 2016-11-29 08:38
As a general notes:

- We don't know what "correct" means because we don't know what behavior you're expecting.
- We don't know how the behavior you observe differs from the expected behavior because you haven't told us, hence we cannot easily tell if we're reproducing the issue or not.
- We don't know what content to use to try and reproduce the issue because you haven't included it in your description.
- Please include a bug report as requested in the issue template.

Please stop filing issues that do not contain sufficient information.
