### ISSUE TITLE
Adaptive track selection

### ISSUE THREAD

**Issue by pstambrecht** [google/ExoPlayer#4443] opened 2018-06-27 17:23 UTC
In class **DefaultTrackSelector** is method:

```
private static boolean isSupportedAdaptiveVideoTrack(
      Format format,
      @Nullable String mimeType,
      int formatSupport,
      int requiredAdaptiveSupport,
      int maxVideoWidth,
      int maxVideoHeight,
      int maxVideoBitrate) {
    return isSupported(formatSupport, false) && ((formatSupport & requiredAdaptiveSupport) != 0)
        && (mimeType == null || Util.areEqual(format.sampleMimeType, mimeType))
        && (format.width == Format.NO_VALUE || format.width <= maxVideoWidth)
        && (format.height == Format.NO_VALUE || format.height <= maxVideoHeight)
        && (format.bitrate == Format.NO_VALUE || format.bitrate <= maxVideoBitrate);
  }
```

Why there is ` isSupported(formatSupport, false)` with _false_ ? It does not respect params settings.

**Comment by ojw28** [comment] 2018-06-27 17:31
Is this in relation to `setExceedRendererCapabilitiesIfNecessary`? The purpose of that parameter is not to completely disable capabilities checks. It's to enable trying to play _something_ in the case all available options are deemed to exceed capabilities, where that _something_ is the lowest quality stream that exceeds capabilities. That does not happen as part of trying to make an adaptive selection, and hence passing `false` when trying to make the adaptive selection is the right thing to do.

I guess we could provide an option to completely disable capabilities checks, if that's what you're after. To be enabled at your own risk ;).

**Comment by pstambrecht** [comment] 2018-06-27 18:07
@ojw28 Yes, it is in relation to `setExceedRendererCapabilitiesIfNecessary` So am I right that it's a protection not to play unsupported streams? But when I change it to `true` it works fine. So this protection does not work properly.

**Comment by ojw28** [comment] 2018-06-27 18:15
The default is `exceedRendererCapabilitiesIfNecessary = true`, so changing it to true wont do anything. The parameter only has an effect if _all_ streams exceed renderer capabilities. In this case, if `exceedRendererCapabilitiesIfNecessary = true`, we'll try and play the lowest quality stream (i.e. the one that exceeds the capabilities by the least amount), in case the device has under-reported what it's actually capable of and can actually play the stream. If `exceedRendererCapabilitiesIfNecessary = false` then we wont try and play any stream.

The reason we default to `true` is that in practice we do see devices under-reporting capabilities (it's also not possible for a device to always get this exactly right ahead of seeing the bit-stream anyway), and the worst that normally happens is that playback fails, which isn't really any worse from the user's perspective compared to not trying in the first place. If you change the value to `false` then we'll not try and do this.

I think we need to improve the Javadoc here (and in particular more clearly surface what all the defaults are). It's still an open question whether there's actually a feature request here. Is there something you want to do that's not currently possible, or were you just clarifying what the API is for?

**Comment by pstambrecht** [comment] 2018-06-27 18:20
Ok, I understand this. But my question was why there is hardcoded `false`. Without any chance to change it.

**Comment by pstambrecht** [comment] 2018-06-27 18:22
@ojw28 I think javadoc is fine. Maybe it's my fault :)

**Comment by ojw28** [comment] 2018-06-27 18:39
It could be better ;). I think I've answered the question (i.e. it's working as intended, the flag is used elsewhere). So will close this but endeavor to improve the Javadoc regardless.

**Closed as completed by ojw28** 2018-06-27 18:39 UTC
Labels: question
