### ISSUE TITLE
OutOfMemoryError in DefaultAudioSink

### ISSUE THREAD

**Issue by saschpe** [google/ExoPlayer#3654] opened 2017-12-31 11:16 UTC
Happened on: Sony BRAVIA 4K 2015 (SVP-DTV15), 2560MB RAM, Android 6.0
Can likely be reproduced with the UniversalMediaPlayer example using ExoPlayer. Not sure if it's the device's fault or the lib since there is a native call involved and it's hard to debug what happens there.

```
java.lang.OutOfMemoryError: 
  at android.media.AudioTrack.getTimestamp (AudioTrack.java:1230)
  at com.google.android.exoplayer2.audio.DefaultAudioSink$AudioTrackUtilV19.updateTimestamp (DefaultAudioSink.java:1503)
  at com.google.android.exoplayer2.audio.DefaultAudioSink.maybeSampleSyncParams (DefaultAudioSink.java:1048)
  at com.google.android.exoplayer2.audio.DefaultAudioSink.getCurrentPositionUs (DefaultAudioSink.java:301)
  at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.getPositionUs (MediaCodecAudioRenderer.java:384)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePlaybackPositions (ExoPlayerImplInternal.java:524)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork (ExoPlayerImplInternal.java:551)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage (ExoPlayerImplInternal.java:306)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at android.os.Looper.loop (Looper.java:148)
  at android.os.HandlerThread.run (HandlerThread.java:61)
```

**Comment by tonihei** [comment] 2018-01-02 09:24
Could you add some reproduction steps for us to have a look?  If at all possible, please also include a full bug report to see what may have caused this issue.

**Comment by tonihei** [comment] 2018-01-23 11:12
Closing for now, because none of the required information was provided. If you have more information, feel free to reopen issue.

**Closed as completed by tonihei** 2018-01-23 11:12 UTC
Labels: need more info
