### ISSUE TITLE
Skippable ads throwing error in Mi Android Tv Box 

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#7037] opened 2020-03-02 05:36 UTC
Issue description
Skippable ads are not getting played in Mi android TV Box.I am currently using a forked version of exoplayer.Ads with out skip are getting played.The same ad is playing in my emulator where as when i run the ad in Mi tv box it is throwing the following exception.  AdError [errorType: PLAY, errorCode: AdErrorCode [name: UNKNOWN_ERROR, number: 900], message: The provided ad type: skippablevideo is not supported.].I am using the ima plugin from exoplayer

Reproduction steps
Try playing an skippable ad in Mi android tv

Version of ExoPlayer being used
Forked from version 2.9.0,Ima sdk version-com.google.ads.interactivemedia.v3:interactivemedia:3.10.2

Device(s) and version(s) of Android being used
Andorid 8.1.0,Mi android tv box

**Comment by andrewlewis** [comment] 2020-03-02 09:16
Please could you set `ImaAdsLoader.DEBUG` to true, reproduce the issue and attach a bug report (`adb bugreport`) or logging (or email it to `dev.exoplayer@gmail.com`)?

Based on your description it sounds like a device-specific issue. It would be helpful to know whether you can reproduce it on any other devices apart from the TV box.

**Comment by meenukrishnamurthy** [comment] 2020-03-02 13:54
@andrewlewis I have mailed you the bug report.This issue is showing up only in Mi android tv box.I have checked with two other devices.Amazon firestick and android tv with version 8.0.It working in both the devices.Please check and let me know.

**Comment by andrewlewis** [comment] 2020-03-02 14:23
The email only has the stack trace, but IMA may output useful diagnostic info to logcat before the actual error occurs. Please follow the instructions from my previous comment to enable the DEBUG flag and get a full bug report.

**Comment by meenukrishnamurthy** [comment] 2020-03-05 05:06
@andrewlewis I have mailed the bug report as instructed by you.Please check and revert

**Comment by andrewlewis** [comment] 2020-03-13 16:38
The relevant error is `03-05 14:52:54.864 10100 15098 15098 W SDK_LOG:ima.common.ErrorUtils: Error play dispatched: AdError 200: The provided ad type: skippablevideo is not supported.`.

Currently the official guidance is that skippable ads just aren't supported on this device, so this is working as intended.

I'm following up with the IMA SDK team on [Internal: b/147342932] to find out more about the reason for the limitation and will follow up here if possible.

**Comment by krackjack234** [comment] 2020-04-28 11:02
@andrewlewis  we also landed up with the same issue. However in this case we expected CONTENT_RESUME_REQUESTED to be called after LOG event which didnt happen. We are using IMA sdk v3.16.5. Is this the expected behavior?


Logs from IMA SDK
```
2020-04-28 16:02:45.632 7523-7523/com.tv.example D/IMASDK: Sending js message: adsLoader [contentComplete]
2020-04-28 16:02:47.111 7523-7523/com.tv.example D/IMASDK: Sending js message: adsLoader [requestAds]
2020-04-28 16:02:48.508 7523-7523/com.tv.example D/IMASDK: Received js message: webViewLoaded [initialized]
2020-04-28 16:02:48.509 7523-7523/com.tv.example D/IMASDK: Sending js message: webViewLoaded [csi]
2020-04-28 16:02:48.666 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:48.672 7523-7523/com.tv.example D/IMASDK: Received js message: omid [omidReady]
2020-04-28 16:02:48.758 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:48.759 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  0.338s] [ima.loader.AdsLoaderImpl] Requesting ads using new ads loader. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:48.760 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  0.344s] [ima.loader.AdsLoaderImpl] requestAds, processing external request. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:48.761 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  0.345s] [ima.loader.SequentialAdsLoader] Enqueued new request. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:48.761 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  0.346s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:48.891 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:48.911 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:48.923 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:49.463 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:49.464 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.028s] [ima.loader.AdXmlFetcher] Creating AdsRequestsMap. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:49.465 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.056s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:49.503 7523-7523/com.tv.example D/IMASDK: Received js message: adsLoader [adsLoaded]
2020-04-28 16:02:49.533 7523-7523/com.tv.example D/IMASDK: Sending js message: adsManager [init]
2020-04-28 16:02:49.550 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:49.618 7523-7523/com.tv.example W/IMASDK: Invalid internal message, ignoring. Please make sure the Google IMA SDK library is up to date. Message: gmsg://afma.google.com/activityMonitor?type=getPageSignals&sid=090bbdef-9952-4373-ae4e-1c260d68e822&dt=1588069969562
2020-04-28 16:02:49.619 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.203s] [ima.loader.AdsLoaderImpl] requestAds, processing internal request. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:49.620 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.204s] [ima.loader.SequentialAdsLoader] Enqueued new request. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:49.620 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.204s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:49.631 7523-7523/com.tv.example D/IMASDK: Received js message: adsManager [adMetadata]
2020-04-28 16:02:49.640 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:49.649 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:49.659 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.099 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(0)] "A cookie associated with a resource at http://doubleclick.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.", source: https://imasdk.googleapis.com/native/sdkloader/native_sdk_v3_debug.html?sdk_version=a.3.16.5&hl=en&omv=1.3.1-google_20200121&app=com.tv.example (0)
2020-04-28 16:02:50.258 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.260 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.871s] [ima.loader.AdSourceFactory] Creating WaterfallAdSource. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.260 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.878s] [VastAdSource] hasMoreAds, this.ads.length: 1 , this.currentAdIndex: -1 , this.numAdsSent: 0 ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.261 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.879s] [VastAdSource] getNextAd, this.currentAdSource: null ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.261 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.879s] [VastAdSource] hasMoreAds, this.ads.length: 1 , this.currentAdIndex: -1 , this.numAdsSent: 0 ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.262 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.881s] [VastAdSource] processNextAd_, currentAdIndex: 0, ads.length: 1 ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.262 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.882s] [VastAdSource] Setting fallback index to session context: 0 ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.264 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.887s] [VastAdSource] processInlineAd, successCallback with 1 ads ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.265 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.888s] [VastAdSource] hasMoreAds, this.ads.length: 1 , this.currentAdIndex: 0 , this.numAdsSent: 1 ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.266 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.889s] [ima.loader.AdsLoaderImpl] dispatchAdsLoadedSdkEvent_, ads.length: 1 ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.333 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.956s] [ima.admanager.VideoAdManager] Playback error: [object Object] AdError 200: The provided ad type: skippablevideo is not supported. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.348 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.970s] [UrlReporter] Reporting urls for event : error ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.352 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.974s] [UrlMacrosReplacer] No macro definition found for: VIEWABILITY ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.373 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  1.995s] [ima.common.ErrorUtils] Error play dispatched: AdError 200: The provided ad type: skippablevideo is not supported. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.389 7523-7523/com.tv.example I/chromium: [INFO:CONSOLE(981)] " [  2.012s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.211.1/native_bridge_debug__en.js (981)
2020-04-28 16:02:50.403 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.413 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.420 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.427 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.433 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.439 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.446 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.452 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.458 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.464 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.470 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.477 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.483 7523-7523/com.tv.example D/IMASDK: Received js message: log [log]
2020-04-28 16:02:50.493 7523-7523/com.tv.example D/IMASDK: Received js message: adsManager [log]
2020-04-28 16:02:50.503 7523-7523/com.tv.example D/IMASDK: Received js message: displayContainer [hide]
```

**Comment by ojw28** [comment] 2020-06-09 09:02
@andrewlewis - Should trying to play the "Single skippable inline" sample in the demo app be sufficient to test this? It's working fine on the MiBox3 and MiBoxS devices I have, so if so I think you can mark this as fixed.

**Closed as completed** 2020-06-10 09:53 UTC
Labels: wont fix: intended behavior

**Comment by ojw28** [comment] 2020-06-10 14:13
@meenukrishnamurthy @krackjack234 - We believe this is fixed, but please let us know if you see otherwise, and we can reopen the issue. Thanks!
