### ISSUE TITLE
Green screen after changing device rotation 

### ISSUE THREAD

**Issue by TuanGiang** [google/ExoPlayer#9361] opened 2021-08-31 11:37 UTC
Device: Chromecast with Google TV
Android OS:  Android TV 10.
Issue: widevine video turn to green after changing device rotation to portrait (landscape is OK)
Exoplayer version: 2.14.1
App: Exoplay-demo
Media: widevine secure media in media.exolist.json. Example:
 {
        "name": "HD (cenc)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/hevc/tears/tears.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
}

Step reproduce:
1.  Device in landscape rotation (USER_ROTATION =  Surface.ROTATION_0)
2.  Play widevine video --> Video play OK
3.  Changing device rotation to portrait (USER_ROTATION =  Surface.ROTATION_90)
4.  Player screen turn to green color. 
![processed](https://user-images.githubusercontent.com/3911399/131494469-3b32cb52-2342-4eaa-9a60-bb97928fe6b6.jpeg)

Step to update rotation:
1. In Manifest.xml , add permission: uses-permission android:name="android.permission.WRITE_SETTINGS"
2.  Open Setting > Apps > Special app access > Modify system settings > Allow 
3. Update rotation: rotation = Surface.ROTATION_0 (landscape) or Surface.ROTATION_90 (portrait).
Settings.System.putInt(contentResolver,Settings.System.USER_ROTATION, rotation )

**Comment by kim-vde** [comment] 2021-08-31 17:44
I tried to reproduce on a TV with a Chromecast using our [cast demo app](https://github.com/google/ExoPlayer/tree/r2.15.0/demos/cast) but I couldn't. The video plays for me (it is not rotated though). I have tried other videos and observed the same behaviour.

Can you try to reproduce with our demo app and, if you manage to do so, explain how you did exactly (for example, where to put line `Settings.System.putInt(contentResolver,Settings.System.USER_ROTATION, rotation )`).

Could you also provide more information on what you are trying to do? Are you trying to play a video on a vertically mounted TV? Does it work for other videos? For the video for which it fails, are the other components of the screen rotated (control buttons, text, ...)?

**Comment by TuanGiang** [comment] 2021-09-01 01:14
>I tried to reproduce on a TV with a Chromecast using our cast demo app but I couldn't. The video plays for me (it is not rotated >though). I have tried other videos and observed the same behaviour.

--> cast demo app has error on my Chromecast TV. Here is error message: Failed to get Cast context, Try updating Google play services and restart the app. So I use demo-app (https://github.com/google/ExoPlayer/tree/r2.15.0/demos/main).

>Can you try to reproduce with our demo app and, if you manage to do so, explain how you did exactly (for example, where to >put line Settings.System.putInt(contentResolver,Settings.System.USER_ROTATION, rotation )).

--> I add source code and apk for rotation feature (only rotation). Apk file name: rotation-debug.apk
[TvRotation.zip](https://github.com/google/ExoPlayer/files/7087335/TvRotation.zip)
You must Open Setting > Apps > Special app access > Modify system settings > Allow TVRotation app ro granted WRITE_SETTING permission. 

>Could you also provide more information on what you are trying to do? Are you trying to play a video on a vertically mounted >TV? Does it work for other videos? For the video for which it fails, are the other components of the screen rotated (control >buttons, text, ...)?

--> I trying to to play a video on both vertically/horizontal mounted. My videos are DRM video and must using SurfaceView to show the video. It impossible (or very difficult) to rotate SurfaceView it self, I have solution for rotate SurfaceView is set Rotation  for Android TV device, but the issue occur.  

Video  | Vertical | Horizontal
------------| -------------| -------------
Secure video (HEVC, VP9 + Widewine) | Green screen | Play OK
Normal video | Play OK | Play OK

--> I add video for the issue: https://user-images.githubusercontent.com/3911399/131595752-07d51f97-8b9d-4c47-ab3e-d927fa42e290.mp4. Or better video resolution: https://drive.google.com/file/d/1pR4ySNjfEq4YPllS6_cyNll0s06IpO-W/view?usp=sharing

Thanks.

**Comment by kim-vde** [comment] 2021-09-02 16:22
Thank you for the extra information. I tried to reproduce on multiple devices but still couldn't:
- TV emulator (running Android 10): no green screen, rotation applied
- Chromecast/Pixel/Samsung phone (running Android 10): no green screen, no rotation applied.

Are you seeing this issue only on your Google TV, or on other devices as well (e.g. other TVs, phones, emulators ...)? Can you give us more info regarding the model of the devices you are using?

From what I know of the issue, I suspect it is related to the Android Framework or that it is device specific.

**Comment by icbaker** [comment] 2021-09-02 17:23
I can reproduce the issue on a Chromecast with Google TV by modifying the demo app and enabling the permission as described in the in the original comment. I put this at the top of `PlayerActivity#onCreate()`:
```
Settings.System.putInt(
    getContentResolver(),
    Settings.System.USER_ROTATION,
    Surface.ROTATION_90);
```

Clear content plays sideways successfully, widevine encrypted content shows a green screen.

**Comment by icbaker** [comment] 2021-09-02 17:31
A simpler way to repro is just to install the unmodified demo app and run the following in a terminal with adb connection to the chromecast:
```
$ adb shell settings put system user_rotation 1
```

Screen goes green

```
$ adb shell settings put system user_rotation 0
```

Video comes back

Screen is also green with 2 (upside down) and 3 (sideways the other way)

**Comment by kim-vde** [comment] 2021-09-03 11:09
I have reported the issue to the Sabrina team (internal ref: b/198749708). We will keep you updated when they get back to us.

**Comment by TuanGiang** [comment] 2021-09-05 02:30
@kim-vde, @icbaker thanks you.

**Comment by icbaker** [comment] 2022-08-16 07:38
Feedback from the internal bug: Device rotation is not supported on Android TV (there's no UI controls for it). So I'm closing this as intended behaviour.

**Closed as completed by icbaker** 2022-08-16 07:38 UTC
Labels: wont fix: intended behavior
