### ISSUE TITLE
com.google.android.exoplayer2.source.ads.AdPlaybackState.getAdGroup ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ldd386** [google/ExoPlayer#11313] opened 2023-10-18 10:42 UTC
### Bug

After upgrading the exoplayer to the latest version (2.19.1) we started seeing these errors in the production app:

java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
    at com.google.android.exoplayer2.source.ads.AdPlaybackState.getAdGroup(AdPlaybackState.java:625)
    at com.google.android.exoplayer2.Timeline$Period.getAdGroupTimeUs(Timeline.java:735)
    at com.google.android.exoplayer2.analytics.PlaybackStatsListener.findBestEventTime(PlaybackStatsListener.java:328)
    at com.google.android.exoplayer2.analytics.PlaybackStatsListener.onEvents(PlaybackStatsListener.java:253)
    at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector.lambda$setPlayer$1$com-google-android-exoplayer2-analytics-DefaultAnalyticsCollector(DefaultAnalyticsCollector.java:140)
    at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector$$ExternalSyntheticLambda19.invoke
    at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:353)
    at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet.java:297)
    at com.google.android.exoplayer2.util.ListenerSet.$r8$lambda$eEvjP-IE0x3J2lRvKfFbbjRFRvc
    at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.handleMessage
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by tonihei** [comment] 2023-10-19 11:55
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues

This is also a duplicate of https://github.com/google/ExoPlayer/issues/10817

**Closed as completed by tonihei** 2023-10-19 11:55 UTC
Labels: duplicate
