### ISSUE TITLE
How to add http request header into MediaItem?

### ISSUE THREAD

**Issue by thucngv** [google/ExoPlayer#10626] opened 2022-09-16 05:19 UTC
I tried to play url through ExoPlayer.setMediaItem  method.
I don't find an option to add request header to MediaItem.Builder.

**Comment by rohitjoins** [comment] 2022-09-16 09:13
Duplicate of https://github.com/google/ExoPlayer/issues/6166

**Closed as completed by rohitjoins** 2022-09-16 09:13 UTC
Labels: duplicate
