### ISSUE TITLE
How to add full screen mode button to ExoPlayer, by clicking it should enable full screen mode(change orientation like YouTube)

### ISSUE THREAD

**Issue by QuaQuaAndroid** [google/ExoPlayer#6131] opened 2019-07-04 13:38 UTC
How to add full screen mode button to ExoPlayer, by clicking it should enable full screen mode(change orientation like YouTube).
Portrait to Landscape and Vice-versa.

**Comment by tonihei** [comment] 2019-07-04 16:14
Duplicate of #1845.  There unfortunately no easy way to implement such a button for all Android devices.

**Closed as completed by tonihei** 2019-07-04 16:14 UTC
Labels: duplicate

**Comment by tiendatit92** [comment] 2019-09-26 03:40
This is my project. You can follow in there
https://github.com/tiendatit92/ExoplayerFullscreenLandcapse
