### ISSUE TITLE
Crash in `TextRenderer` when rendering stream with single subtitle

### ISSUE THREAD

**Issue by baconz** [google/ExoPlayer#8017] opened 2020-09-29 22:58 UTC
### [REQUIRED] Issue description
We get an NPE in 2.12.0 when the `TextRenderer` tries to render a stream with a single subtitle:

```
     Caused by: java.lang.NullPointerException: throw with null exception
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
        at com.google.android.exoplayer2.text.TextRenderer.getNextEventTime(TextRenderer.java:328)
        at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:201)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```
I think this was introduced with the null checks added here: https://github.com/google/ExoPlayer/commit/0efec5f6c12a5d583f24c122fbcbc1b1eebbabc3#diff-2a869b1d2a8dabec5def4e6e02d2bd18

It is possible to call `getNextEventTime()` on the first `render()` if `nextSubtitle.isEndOfStream()`.

### [REQUIRED] Reproduction steps
It is difficult for us to share a stream in the clear that reproduces this.

### [REQUIRED] Link to test content
See above.

### [REQUIRED] A full bug report captured from the device
Happy to do this upon request.

### [REQUIRED] Version of ExoPlayer being used
2.12.0

### [REQUIRED] Device(s) and version(s) of Android being used
Any

**Comment by icbaker** [comment] 2020-09-30 15:46
I'm not able to reproduce this crash.

I tried with the following WebVTT file:
```
WEBVTT

00:00.000 --> 00:01.234
This is the first subtitle.
```

And played it in the demo app at 2.12.0 using this JSON snippet:
```
{
  "name": "go/exoghi/8017",
  "uri": "https://storage.googleapis.com/exoplayer-test-media-1/gen-3/screens/dash-vod-single-segment/video-avc-baseline-480.mp4",
  "subtitle_uri": "file:///sdcard/Download/webvtt.vtt",
  "subtitle_mime_type": "text/vtt",
  "subtitle_language": "en"
}
```

The video played fine and displayed the subtitle as expected on the screen. I didn't see any suspicious stack traces in logcat.

Are you able to reproduce the behaviour you see in the ExoPlayer demo app?

Can you provide more info about your setup to help us reproduce and investigate?

**Comment by baconz** [comment] 2020-10-01 05:38
Indeed I can't repro with the VTT example you posted. I suspect it is because the VTT input buffer does not set `BUFFER_FLAG_END_OF_STREAM` on the first pass.

I am able to reproduce reliably with the CEA-608 subtitles in the example below. Here, the very first time the decoder grabs captions, the input buffer has `BUFFER_FLAG_END_OF_STREAM` set, and thus it triggers the NPE code path.

```
      {
        "name": "bad cea-608 dash",
        "uri": "https://static-us-east-2-fastly-a.www.philo.com/storage/dev/seth/exo_cc_npe/manifest.mpd"
      },
```

**Comment by icbaker** [comment] 2020-10-01 09:00
Thanks, I can repro with that media.

(side note, I had to tweak the URL slightly, think it should be `https://static-us-east-2-fastly-a.www.philo.com/storage/dev/seth/exo_cc_npe/manifest.mpd` - I've edited your comment to help anyone else trying to repro)

**Comment by icbaker** [comment] 2020-10-01 09:35
I've sent a fix for this - thanks for reporting

**Closed as completed** 2020-10-06 17:16 UTC
Labels: bug

**Comment by saurabhkpatel** [comment] 2020-10-15 20:56
Any updates, when this is going to be released? We're stuck on this crash now.

**Comment by icbaker** [comment] 2020-10-16 10:10
@ojw28 is putting together 2.12.1 which will include this fix - no eta I'm afraid.
