### ISSUE TITLE
How cookies are sent by Exoplayer in player network calls

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#7431] opened 2020-05-27 15:22 UTC
### [REQUIRED] 
Searched documentation and issues

### [REQUIRED] Question
We are playing akamai urls using a custom player based on exoplayer. We do not set any cookies explicitly but do set a custom header that needs to be passed in every player network calls (manifest & ts segments)

What we are observing is sometimes Exoplayer is sending the long token as cookies in request header and sometimes the cookie is not set at all, for the same playback domain. The issue is happening quite randomly.

![Screen Shot 2020-05-27 at 8 48 41 PM](https://user-images.githubusercontent.com/50735078/83039413-c5d8a880-a05b-11ea-8907-1ca46e3ffacb.png)

![Screen Shot 2020-05-27 at 8 50 25 PM](https://user-images.githubusercontent.com/50735078/83039417-c83b0280-a05b-11ea-8db9-480a814e5656.png)

![Screen Shot 2020-05-27 at 11 46 12 PM](https://user-images.githubusercontent.com/50735078/83057269-54f1ba80-a074-11ea-9209-c4cbde8c256a.png)

We wanted to know if this is the expected behavior and if not what we need to do to set the cookies for every player network call.

Thanks in advance.

**Comment by marcbaechinger** [comment] 2020-05-27 20:55
I think ExoPlayer does nothing special with cookies. It also depends on what data source you are using. When using `DefaultHttpDataSource` an `HttpUrlConnection` is used which manages cookies according to the [CookieManager](https://developer.android.com/reference/java/net/CookieManager.html).

AFAIK a cookie is sent only when requested from the server with a 'Set-Cookie' response header. This Set-Cookie response header defines the scope of the cookie like to which host it should be sent and the like. The hdntl cookie is requested by the Akamai server.

> Exoplayer is sending the long token as cookies in request header and sometimes 
> the cookie is not set at all, 

I don't understand what you mean with 'long token' I'm afraid. Can you be more specific in what the issue actual is you are seeing and what the expected behaviour would be? Are requests failing and do you have some error messages from the Akamai server?

In the above inspection tool it seems to me that it differs for http and https. I think this because it shows that the TLS handshake is empty in one case and it is 1.33KB in the other case. ALso for one request there is a query string and the other doesn't have a query string.

**Comment by krackjack234** [comment] 2020-05-28 05:53
@marcbaechinger  The query string (called as long token) is actually getting passed as cookies in subsequent calls by exoplayer, though we are not sure how it's happening. In the successful case (3rd screenshot), you can see the query string is passed as cookie. However in the unsuccessful case, no query string is passed. Since Akamai is expecting the query string to be passed as cookies, it returns an access denied when its missing.

**Comment by krackjack234** [comment] 2020-06-01 05:36
hi @marcbaechinger  we tried the below code in app and we could not see the problem occuring. Please advise if this is correct to use


```
 private static final CookieManager DEFAULT_COOKIE_MANAGER;
    static {
        DEFAULT_COOKIE_MANAGER = new CookieManager();
        DEFAULT_COOKIE_MANAGER.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
    }

 if (java.net.CookieHandler.getDefault() != DEFAULT_COOKIE_MANAGER) {
            java.net.CookieHandler.setDefault(DEFAULT_COOKIE_MANAGER);
  }

```

**Comment by ojw28** [comment] 2020-06-02 21:48
I think that setting a cookie manager is the right thing to do to solve this. The ExoPlayer demo app also does this, [here](https://github.com/google/ExoPlayer/blob/r2.11.4/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L136). I don't know what cookie policy you need. It might be that `ACCEPT_ORIGINAL_SERVER` is sufficient, as is being used in the demo app.

In any case, it seems like you're on the right track, so I think we can go ahead and close this issue. Marking with the documentation candidate label since this is something that would be good to cover in our developer guide.

**Closed as completed by ojw28** 2020-06-02 21:48 UTC
Labels: question

**Comment by krackjack234** [comment] 2020-06-04 18:37
hi @ojw28  if this code is impacting the way Exoplayer is handing cookies, should we not have this as part of Exoplayer code itself?

**Comment by ojw28** [comment] 2020-06-04 20:38
ExoPlayer doesn't handle cookies at all, and it's not really its job to do so. It's the application's job to configure the network stack to handle cookies in the correct way for the services that it's interacting with.

As justification for this, consider all of the other non-media network requests that your application is making. It's not ExoPlayer's job to handle cookies for those requests, and if cookie handling is required the application is going to have to do some configuration to make that work. The network requests that ExoPlayer makes to the underlying network stack are really no different.

**Comment by krackjack234** [comment] 2020-06-05 12:58
@ojw28  got it. Is there any way we can apply this setting only for the exoplayer network calls instead of applying it globally? 

Also as part of the original problem, we are still not able to understand why Exoplayer in some cases are not passing the cookies if we do not set the cookie handler. The problem is this issue is intermitted without this change, so it will be great to know why sometimes exo is not passing the cookies.

**Comment by ojw28** [comment] 2020-06-05 14:30
> Also as part of the original problem, we are still not able to understand why Exoplayer in some cases are not passing the cookies if we do not set the cookie handler. The problem is this issue is intermitted without this change, so it will be great to know why sometimes exo is not passing the cookies.

To re-iterate, ExoPlayer does not "pass the cookies". It's the network stack that passes the cookies. In order for the network stack to have a cookie to pass in the first place, it must have been given to the network stack somehow. Probably a previous request for which the server response included a `Set-Cookie` response header, as outlined by @marcbaechinger above. The cookie manager probably also has to be set before whatever it is that sets the cookie happens. In the case where you're not setting the cookie handler, perhaps something else in your application is (perhaps some code buried in one of your dependencies is doing it). This might explain why you sometimes see it work even when you don't explicitly set it yourself.

> Is there any way we can apply this setting only for the exoplayer network calls instead of applying it globally?

I don't know about the default network stack, but if you're using the ExoPlayer OkHttp extension you can create an `OkHttpClient` just for use by ExoPlayer, and set a cookie handler just on the client rather than globally. See [this stackoverflow post](https://stackoverflow.com/questions/34881775/automatic-cookie-handling-with-okhttp-3) for an example.

**Comment by krackjack234** [comment] 2020-06-10 18:55
@ojw28  thanks for the detailed explanation. This is quite helpful
