### ISSUE TITLE
Player gets stuck at the last second of the Ad and content video doesn't play.

### ISSUE THREAD

**Issue by victorraft** [google/ExoPlayer#3305] opened 2017-09-27 18:56 UTC
### Issue description
I'm having an issue with the IMA Extension on 2.5.3 where the preroll plays, but then it gets stuck at the last second, and the player stays on the buffering state forever. It doesn't fail or anything, so the content video never starts. 
It seems to be happening only with some AdTags. Reproducible on the Demo app.

Not sure if related, but the onAdError function in ImaAdsLoader stops being called after around the time it received MIDPOINT or so. If I close the Activity while the player is stuck then onAdError finally gets called with CONTENT_RESUME_REQUESTED and ALL_ADS_COMPLETED.

### Reproduction steps
In the ExoPlayer demo app, assign the following value to the adTagUriString variable (line 336 of PlayerActivity):
`//pubads.g.doubleclick.net/gampad/ads?sz=3x3&iu=/36117602/htv-kcci.app/news/national_news/vuz&impl=s&gdfp_req=1&env=vp&output=xml_vast2&unviewed_position_start=1&url=http%3A%2F%2Fwww.wjcl.com%2Farticle%2Fletter-leads-to-man-tracking-down-family-in-romania%2F12453607&description_url=http%3A%2F%2Fwww.wjcl.com%2Farticle%2Fletter-leads-to-man-tracking-down-family-in-romania%2F12453607&correlator=[timestamp]&cust_params=tool%3Dvideo%26coid%3D12453607%26pos%3Dpreroll%26page%3Dvuz`

### Link to test content
Reproducible in the demo app.

### Version of ExoPlayer being used
2.5.3

### Device(s) and version(s) of Android being used
It happens everytime on the Android Studio Emulator (tested on API 25 and 26) and sometimes on my Galaxy S7 with API 25.

### A full bug report captured from the device
N/A

**Comment by ojw28** [comment] 2017-09-28 10:23
This is most likely a duplicate of https://github.com/google/ExoPlayer/issues/1874, but I'll double check. If so, we should prioritize putting at least a workaround in place, since the IMA extension expands the use cases that might hit the problem.

**Comment by ojw28** [comment] 2017-09-28 14:20
Confirmed + marking as duplicate. We'll push a fix for this in the next few days.

**Closed as completed by ojw28** 2017-09-28 14:20 UTC
Labels: duplicate
