### ISSUE TITLE
ExoPlayer 2.5.0 request partial segment request for encrypted dash audio content

### ISSUE THREAD

**Issue by dhanapal20** [google/ExoPlayer#3409] opened 2017-10-31 09:40 UTC
[sample.zip](https://github.com/google/ExoPlayer/files/1430179/sample.zip)

#Issue description
We have a sample VOD HEVC Encrypted dash content and We are trying to play it using Exo Plyer 2.5.0. Upon doing so , the content plays for one second and then stops and player displays 'retry' due to repeated 206 partial audio segment request .  
The exo player first requests for an audio segment and gets a 200 OK response back from the server. Then again it requests 3x times for 206 byte range for the same audio segment and then freezes
But the same VOD content plays well in clear format and problematic audio segments also played well without and any partial segment request

#Reproduction steps
Play our sample encrypted content using exoplayer 2.5.0.

# Version of ExoPlayer being used 2.5.0
# Device(s) and version(s) of Android being used :  Android 7.0 
We have attached the following for further analysis 
  - Manifest
  - audio segment with encrypted and clear format
  - wireshark capture during the problematic case

Decryption Key  :"d4d3243adb14c27b0fb649ba54c34bd9"

Could you check in exoplayer code level and provide us the reason for this 206 request

**Comment by ojw28** [comment] 2017-11-01 18:17
* The attachments don't seem to have been attached. Could you attach them?
* Please provide a full bug report captured shortly after encountering the issue (ideally using the ExoPlayer demo app), as is requested in the issue template.
* The issue description doesn't actually describe what the issue is. The player making a range request isn't a reason for the player failing, so there must be something else going on. This will likely be visible in the bug report, if one can be provided. Thanks!

**Comment by ojw28** [comment] 2017-11-01 18:20
Ignore my comment about the attachments; I found them at the top :). The manifest seems to be omitted though.

**Comment by shreyasreedhar** [comment] 2017-11-10 01:45
@ojw28  , we would like to know why does the exo player request for partial segment request when it has already gotten a complete 200 OK for the audio segment. 
It keeps repeating the partial request and then stops pLAYING. Is there any clue on this as to why this could happen ?

 ** The exo player first requests for an audio segment and gets a 200 OK response back from the server. Then again it requests 3x times for 206 byte range for the same audio segment and then freezes ***

**Comment by ojw28** [comment] 2017-11-13 00:06
Without a way for us to reproduce the problem, it's not really possible for us to say. If you want further guidance please provide concrete reproduction steps, and also complete information as is requested both in the issue template and above. A bug report in particular would tell us a lot about what's going on, but one has not been provided.

One possible cause is that the server is setting the Content-Length header incorrectly in the response, or something like that, but as above we really can't tell without a way to test the issue for ourselves.

Closing for now since the requested information has not been provided. If you're able to provide complete information and reproduction steps, please reply here and we'll re-open for investigation.

**Closed as completed by ojw28** 2017-11-13 00:06 UTC
Labels: need more info

**Comment by shreyasreedhar** [comment] 2017-11-13 08:25
@ojw28 I am attaching the segment for which the exo player got a 200 response and then again requested for 206 of the same segment during playback of a live channel 


[seg_audio34_0_t15102006487528222.mp4.mpeg.zip](https://github.com/google/ExoPlayer/files/1465570/seg_audio34_0_t15102006487528222.mp4.mpeg.zip)

![image](https://user-images.githubusercontent.com/27345798/32709479-af7bd60e-c86b-11e7-9df5-28e8a94d4092.png)

**Comment by ojw28** [comment] 2017-11-13 10:50
This does not help us reproduce or diagnose the issue unfortunately. It seems quite likely to be a serving issue, in which case it would only reproduce when the segment is actually requested from the server you're using. We also still don't have a copy of the manifest that shows how the segment was advertised to the client, or a bug report that would show us what the actual errors are leading up to playback failure. We just can't help you without more information.

If you're unable to provide us with an actual way to reproduce the problem, then you'll probably have to diagnose the issue yourself.
