### ISSUE TITLE
Getting Issue while selecting Lower Bitrate after updating the player to 2.17.1

### ISSUE THREAD

**Issue by narasimharao11** [google/ExoPlayer#10112] opened 2022-03-25 14:18 UTC
Hi Team,
We have recently updated the exoplayer version from 2.11.2 to 2.17.1. After updating the player we are facing issue with lower bitrate streams in track selection. We reproduced the issue in the demo app and attached the logs and complete bug report to it. 

Steps to reproduce:
1. Open the demo application.
2. Select any hls content. 
3. click on lowest bitrate available.

**Logs:**
```
playerFailed [eventTime=20.03, mediaPos=4.45, window=0, period=0, errorCode=ERROR_CODE_IO_BAD_HTTP_STATUS
      x0.p: Source error
        at x0.m1.G(Unknown Source:16)
        at x0.m1.handleMessage(Unknown Source:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: g3.b0$e: Response code: 403
        at f1.b.b(Unknown Source:265)
        at g3.u.b(Unknown Source:140)
        at h3.c.H(Unknown Source:278)
        at h3.c.b(Unknown Source:126)
        at g3.n0.b(Unknown Source:12)
        at g3.o.a(Unknown Source:8)
        at g3.o.b(Unknown Source:0)
        at g3.h0.a(Unknown Source:14)
        at g3.f0$d.run(Unknown Source:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    ]
```

- ExoPlayer version number - 2.17.1
- Android version - 11,12
- Android device - Oneplus 8T, IQOO Z3 5G

[bugreport-OnePlus8T_IND-RP1A.201005.001-Exoplayer.zip](https://github.com/google/ExoPlayer/files/8351265/bugreport-OnePlus8T_IND-RP1A.201005.001-Exoplayer.zip)

**Comment by marcbaechinger** [comment] 2022-03-28 09:56
The stack trace tells that there is a HTTP 403, so the player does not have access to this resource.

If you test out without obfuscation then you can find out yourself whether this is caused when loading media or playlist and talk to the system administrator of the server whether they can help you identify the failing resources.  

I'm closing this issue as from the player perspective a 403 can not be fixed and the error message is correctly saying what is happing. Please re-open if you think this is caused by a bug in the library.

**Closed as completed by marcbaechinger** 2022-03-28 09:56 UTC
Labels: wont fix: intended behavior
