### ISSUE TITLE
Prevent Audio Capture not wokring on xiaomi devices

### ISSUE THREAD

**Issue by SudoDios** [google/ExoPlayer#9759] opened 2021-12-04 18:16 UTC
Hi again.
I am using `android:allowAudioPlaybackCapture=false` &
```koltin
val audioAttributes: AudioAttributes =
        AudioAttributes.Builder()
                .setAllowedCapturePolicy(ALLOW_CAPTURE_BY_NONE)
                .setUsage(C.USAGE_MEDIA)
                .setContentType(C.CONTENT_TYPE_MOVIE)
                .build()
exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl)
exoPlayer.audioAttributes = audioAttributes
```
and wokring it.
#9743 
But in screen recorder on xiaomi devices **not work**. (tested on Xiaomi Poco x3 pro, System screen recorder)
You have a solution ?

**Comment by SudoDios** [comment] 2021-12-04 18:16
#9743

**Comment by ojw28** [comment] 2021-12-06 11:12
Duplicate of #9743. Please don't file duplicate issues.

**Closed as completed by ojw28** 2021-12-06 11:12 UTC
Labels: duplicate
