### ISSUE TITLE
HLS with multiaudio "PesReader: Unexpected start code prefix"

### ISSUE THREAD

**Issue by sdex** [google/ExoPlayer#2175] opened 2016-12-09 13:18 UTC
Hello. 

I cannot play HLS video with multi audiotracks (release-v2, dev-v2 branches) in the demo app.
I see only black screen and warnings in logcat: "PesReader: Unexpected start code prefix"

Possible related issues: #1978, #2163 (but I don't see first chunk or corrupted video).

Reproduces in all devices that I tried (samsung galaxy s6, lg g4, xiaomi redmi note 3).

The link to video was sent via email. 

[bugreport_samsung_galaxy_s6_android_6.zip](https://github.com/google/ExoPlayer/files/642226/bugreport_samsung_galaxy_s6_android_6.zip)

**Comment by AquilesCanta** [comment] 2016-12-11 15:02
Keep in mind #2014 . I'll have a look at the stream.

**Comment by AquilesCanta** [comment] 2016-12-12 14:48
I haven't been able to get the manifest (or play the stream, as a consequence). I keep getting timeouts and 503's. If you can root the cause and fix it, let me know. Please make sure the cause of your issue is not the same as for the referenced issues in the thread. If that's the case, we are going to workaround it, and you can track #2172, and close this one.

**Comment by AquilesCanta** [comment] 2017-01-09 14:36
Closing due to lack of required info. Assuming it is indeed a duplicate.

**Closed as completed by AquilesCanta** 2017-01-09 14:36 UTC
Labels: need more info
