### ISSUE TITLE
emsg box does not work.

### ISSUE THREAD

**Issue by wasabeef** [google/ExoPlayer#2437] opened 2017-02-10 10:11 UTC
It's not working on `release-v2` and `dev-v2-emsg-experimental`.
Is it unsupported?

DASH Sample
http://se-mashup.fokus.fraunhofer.de:8080/dash/assets/adinsertion-samples/events/inband/dash.mpd

**Comment by ojw28** [comment] 2017-02-12 10:33
Duplicate of #2176.

**Closed as completed by ojw28** 2017-02-12 10:33 UTC
Labels: duplicate
