### ISSUE TITLE
Skip 64kb of junk at the beginning of mp3 files

### ISSUE THREAD

**Issue by halaei** [google/ExoPlayer#7187] opened 2020-04-04 09:37 UTC
### [REQUIRED] Issue description
Most players and tools, like ffmpeg, skip more junk bytes that what exoplayer does. Hence there are files that are OK regarding those players and tools, but cannot be played with exoplayer.
Here is a link to a commit in ffmpeg. The code as well as description are informative:

https://github.com/FFmpeg/FFmpeg/commit/2b3e9bbfb529e6bde238aeb511b55ebe461664c8

### [REQUIRED] Reproduction steps
Play the following file, which starts with 20kb of junk after id3. It doesn't work althoug other players, like YouTube Misic, Mx Player, and Google Play Music support it:
http://s12.ws-static.com/titan/music/R/Reza%20Pishro/[one]/Moarefie%20Nabegheha%20[WikiSeda].mp3

### [REQUIRED] Link to test content
Play this file: http://s12.ws-static.com/titan/music/R/Reza%20Pishro/[one]/Moarefie%20Nabegheha%20[WikiSeda].mp3
Other files are also reported in related issues linked in the next section.

### [REQUIRED] A full bug report captured from the device
None of the available extractors (e, g, j, e, j, f, g0, c, d, z, b, b, h, d) could read the stream.
It is also provided in other bug reports:
https://github.com/google/ExoPlayer/issues/2359
https://github.com/google/ExoPlayer/issues/2404

### [REQUIRED] Version of ExoPlayer being used
2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Samsung Galaxy S8, and SM-A105F (Android 9). Probably any android device.

**Comment by halaei** [comment] 2020-04-04 09:38
Maybe a duplicate of https://github.com/google/ExoPlayer/issues/5718. I didn't find it at first. I hope it provides extra information.

**Comment by andrewlewis** [comment] 2020-04-06 07:06
Thanks for the report and extra information on #5718! I will mark this as a duplicate for now.

**Comment by andrewlewis** [comment] 2020-04-06 07:06
Duplicate of #5718

**Closed as completed by andrewlewis** 2020-04-06 07:06 UTC
Labels: duplicate
