### ISSUE TITLE
Why exoplayer cannot stream PLS type streaming link?

### ISSUE THREAD

**Issue by bhaskarraj** [google/ExoPlayer#7875] opened 2020-09-09 16:24 UTC
I have PLS streaming link which plays fine in other players. But exoplayer is not able to play such link. Test link:
[http://shoutcast.radyogrup.com:1020/listen.pls](url)

Does exoplayer not support of PLS type streaming? I am able to stream .m3u8 and other links except for that.

**Comment by kim-vde** [comment] 2020-09-10 11:00
Duplicate of #1947.

**Closed as completed** 2020-09-10 11:00 UTC
Labels: duplicate, question
