### ISSUE TITLE
ANR on clear the player of PlayerView 

### ISSUE THREAD

**Issue by nooooooooooob** [google/ExoPlayer#5078] opened 2018-11-08 11:11 UTC
here is ANR log
————————————————————————————————————————
"main" prio=5 tid=1 WAIT
  | group="main" sCount=1 dsCount=0 obj=0x41e3ae58 self=0x41e29850
  | sysTid=7095 nice=0 sched=0/0 cgrp=apps handle=1074819412
  | state=S schedstat=( 92592230727 45469543736 288528 ) utm=7999 stm=1260 core=0
  at java.lang.Object.wait(Native Method)
  - waiting on <0x42ebeaf8> (a com.google.android.exoplayer2.PlayerMessage)
  at java.lang.Object.wait(Object.java:364)
  at com.google.android.exoplayer2.PlayerMessage.blockUntilDelivered(PlayerMessage.java:282)
  at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurfaceInternal(SimpleExoPlayer.java:962)
  at com.google.android.exoplayer2.SimpleExoPlayer.setVideoTextureView(SimpleExoPlayer.java:285)
  at com.google.android.exoplayer2.SimpleExoPlayer.clearVideoTextureView(SimpleExoPlayer.java:300)
————————————————————————————————————————

here is my code which cause the ANR
————————————————————————————————————————
mPlayerView.setPlayer(null);
————————————————————————————————————————
 
exoplayer version:2.8.2
AndroidVersion 4.4.4

it happens when I release the player while the player is buffering

**Comment by AquilesCanta** [comment] 2018-11-08 16:06
Can you please provide a bugreport?

See the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by nooooooooooob** [comment] 2018-11-09 01:47
bugreport is sent by email

**Comment by AquilesCanta** [comment] 2018-11-09 09:42
The provided file is not a bugreport. You can obtain one by running `adb bugreport` right after reproducing the issue on the device.

**Comment by AquilesCanta** [comment] 2018-11-13 10:49
We need to identify the device to do anything about it. I will be closing the issue until the missing information is provided.

**Closed as completed by AquilesCanta** 2018-11-13 10:49 UTC
Labels: need more info

**Comment by yannqiu** [comment] 2019-03-21 09:32
I meet the same issue.
here is ANR log:
Build fingerprint: 'Xiaomi/kenzo/kenzo:6.0.1/MMB29M/V8.2.1.0.MHOCNDL:user/release-keys'
ABI: 'arm'
RedMi Note3

**"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x73e746e8 self=0xf4805400
  | sysTid=25736 nice=-4 cgrp=default sched=0/0 handle=0xf74d6534
  | state=S schedstat=( 59422277189 14082905779 121050 ) utm=5097 stm=844 core=5 HZ=100
  | stack=0xff3d1000-0xff3d3000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x03031489> (a com.google.android.exoplayer2.PlayerMessage)
  at com.google.android.exoplayer2.PlayerMessage.blockUntilDelivered(PlayerMessage.java:282)
  at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurfaceInternal(SimpleExoPlayer.java:1216)
  at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurfaceHolder(SimpleExoPlayer.java:317)
  at com.google.android.exoplayer2.SimpleExoPlayer.clearVideoSurfaceHolder(SimpleExoPlayer.java:337)
  at com.google.android.exoplayer2.SimpleExoPlayer.clearVideoSurfaceView(SimpleExoPlayer.java:348)
  at com.google.android.exoplayer2.ui.PlayerView.setPlayer(PlayerView.java:524)**

hope you reply

**Comment by bjitivo** [comment] 2019-04-09 19:41
We have experienced this also.

anr bugreport attached

For what it's worth, as far as I can tell, this ANR is due to the synchronous waiting for a Message of type C.MSG_SET_SURFACE by the main android Looper thread via a call to SimpleExoPlayer.setVideoSurfaceInternal, which itself is called because of a clearVideoSurface() call on the player.

The Message itself must be processed by the MediaCodecVideoRenderer instance, but it is blocking in a call to MediaCodecRenderer.initCodec(), which itself appears to be blocked trying to create an instance of the codec in the stagefright library.

Can you please re-open and reconsider this bug?  Thanks!

[bugreport-eSTREAM4K-180712-2019-04-09-12-31-03.zip](https://github.com/google/ExoPlayer/files/3060711/bugreport-eSTREAM4K-180712-2019-04-09-12-31-03.zip)
