### ISSUE TITLE
Video can not be play normally before 4s, and the audio is normal.

### ISSUE THREAD

**Issue by tuesda** [google/ExoPlayer#5189] opened 2018-12-04 03:51 UTC
Version: 2.9.2
device: Samsung note 9

This video's picture is blocked until 4s, and the audio is play normally.

video:
[lnl2iM0zEZBBNgCOGSIGJWatulMf.mp4.zip](https://github.com/google/ExoPlayer/files/2642324/lnl2iM0zEZBBNgCOGSIGJWatulMf.mp4.zip)

**Comment by erdemguven** [comment] 2018-12-04 17:08
This is reproducible on the demo app. Looks like video starts with the frame at about 4s and doesn't progress until 4s. It plays fine on VLC.

@ojw28 could you looks at this?

**Comment by ojw28** [comment] 2018-12-04 17:11
I'm going to guess this is edit list related.

**Comment by andrewlewis** [comment] 2018-12-04 18:01
This looks like a duplicate of #1659.

**Closed as completed** 2018-12-04 18:01 UTC
Labels: duplicate
