### ISSUE TITLE
Video distorted when playing on Galaxy Note 10.1

### ISSUE THREAD

**Issue by thomasvsundert** [google/ExoPlayer#369] opened 2015-03-25 18:27 UTC
We're seeing that on some devices m3u8 video playback is distorted (see screenshot). 
This has been seen on Samsung Galaxy Note 10.1, Model GT-N8010, Android version 4.4.2, Kernel version 3.0.31-2098840
Mp4 playback seems to work just fine on the same device.

![unnamed-3](https://cloud.githubusercontent.com/assets/294815/6832099/8f259582-d324-11e4-9c4c-0455b78735f7.jpg)

**Comment by ojw28** [comment] 2015-03-25 20:47
Are you using TextureView, or SurfaceView? Also, do you have a test stream that reproduces the issue (or, if it reproduces with the samples in the demo app, that would be useful to know)?

**Comment by vdesmet93** [comment] 2015-03-27 11:59
I'm a colleague of Thomas and will provide some more details.

We're using a SurfaceView with a HlsRendererBuilderfrom the demo application to render the HLS video. The HLS video from the demo app works fine. The stream we're using is behind a login and direct links will expire within an hour or so, so we can't provide a direct URL. 

The onRenderersError() and onPlayerError() callbacks don't return any errors during the playback issues.

**Comment by ojw28** [comment] 2015-04-07 14:28
You'll probably need to make an equivalent public stream (e.g. of cycling test content) available to get any help with debugging this issue. We can't debug something that we have no way of reproducing.

**Comment by ojw28** [comment] 2015-10-11 19:57
Closing due to lack of test stream.

**Closed by ojw28** 2015-10-11 19:57 UTC
