### ISSUE TITLE
java.lang.NoClassDefFoundError: com.google.android.exoplayer2.ExoPlayer$Builder$$ExternalSyntheticLambda2

### ISSUE THREAD

**Issue by KamiNoYuki** [google/ExoPlayer#11137] opened 2023-04-26 08:51 UTC
### NoClassDefFoundError

>I got an error that only occurs on Android versions 6.0 and 5.0. It looks like an anonymous inner class was not found. 
How can i solve this problem, please?
Running device version: 6.0.
Gradle version: 7.1.2.
Android studio version: flamingo(2022.2.1).
ExoPlayer version: 2.18.1.

```
java.lang.NoClassDefFoundError: com.google.android.exoplayer2.ExoPlayer$Builder$$ExternalSyntheticLambda2
at com.google.android.exoplayer2.ExoPlayer$Builder.<init>(ExoPlayer.java:528)
at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer$1.run(IjkExo2MediaPlayer.java:396)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by rohitjoins** [comment] 2023-04-27 16:12
Duplicate of #10602.

**Closed as completed by rohitjoins** 2023-04-27 16:12 UTC
Labels: duplicate
