### ISSUE TITLE
Downloader blocking on Cache

### ISSUE THREAD

**Issue by aasitnikov** [google/ExoPlayer#9132] opened 2021-06-29 12:28 UTC
In my app I have two components. First is "player", which accepts `MediaSources` with `CacheDataSource` in it. When this player is asked to play some new media, it fetches data via `HttpDataSource` and puts it in a `Cache`. Second is "downloader", which uses `Downloaders` like `ProgressiveDownloader` or `HlsDownloader`, which use `CacheDataSource.Factory` to cache media. Both components share the same `Cache` instance - "downloader" can pre-cache the next track, so that "player" could play this track from cache. 

The problem is when "player" and "downloader" try to operate on the same media. For example, imagine player's `ProgressiveMediaSource` open `CacheDataSource` and buffer first 50s of media, as defined by `LoadControl`. But if `Player` is paused, then it keeps `CacheDataSource` open forever, holding `Cache`'s `CacheSpan`. In that case `Downloader` will be stuck and won't be able to download any media, because all `Downloader`s call `CacheDataSource.Factory.createDataSourceForDownloading()`, which force sets `FLAG_BLOCK_ON_CACHE` and prevents `Downloader` to proceed. 

I found no legal way to unset this flag for `Downloader` - all of `CacheDataSource.Factory`, `CacheDataSource` and `Downloader` implementations are final. The least invasive way I found is to create a `Cache` implementation, that returns null from non-nullable `startReadWrite()` - in that case [current `CacheDataSource` implementation](https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSource.java#L687-L696) won't block on cache. But it still looks hacky, and might not work in future versions.

Is there any other way to work around this issue?

**Comment by marcbaechinger** [comment] 2021-07-05 15:00
I think you need to use two different caches, one for downloading and one for on-the-fly caching. I think currently this is a restriction. You have already found issue #8645 which is marked as an enhancement. I don't think I can add much more about this problem than in the other issue.  

I apologize for not having properly answered your comment in the other issue. You did the right thing in adding your comment there. Thanks you for doing that. I will mark this issue as duplicate of the other issue and close this issue. If you think it is different from the other issue please re-open.

**Closed as completed by marcbaechinger** 2021-07-05 15:00 UTC
Labels: duplicate, question
