### ISSUE TITLE
Support downloading live content

### ISSUE THREAD

**Issue by comdigi** [google/ExoPlayer#9940] opened 2022-02-05 02:05 UTC
Hi!
I downloaded live content(m3u8) but got an error message saying "This demo app does not support downloading live content"
Is it impossible to download live content?

Thanks

**Comment by marcbaechinger** [comment] 2022-02-06 20:12
The library does not support downloading live content out-of-the-box. There are no plans to provide this in the near future I'm afraid.

There is a tracking bug about this feature. Closing as a duplicate of #3877

**Closed as completed by marcbaechinger** 2022-02-06 20:12 UTC
Labels: duplicate, question

**Comment by comdigi** [comment] 2022-02-10 08:40
Thanks!
