### ISSUE TITLE
Unable to play HLS Video in exoplayer in Nexus 4

### ISSUE THREAD

**Issue by sachinbhanot** [google/ExoPlayer#453] opened 2015-05-13 06:03 UTC
Hi,

I am trying to play the video in nexus 4 using latest exoplayer version. but its showing me the exception.

Here is log error

   com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 304, 1.0, -1, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.a(SourceFile:333)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.k(SourceFile:320)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.a(SourceFile:350)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.a(SourceFile:331)
            at com.google.android.exoplayer.ExoPlayerImplInternal.a(SourceFile:540)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:219)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 304, 1.0, -1, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.k(SourceFile:320)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.a(SourceFile:350)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.a(SourceFile:331)
            at com.google.android.exoplayer.ExoPlayerImplInternal.a(SourceFile:540)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:219)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)
     Caused by: android.media.MediaCodec$CodecException: start failed
            at android.media.MediaCodec.native_start(Native Method)
            at android.media.MediaCodec.start(MediaCodec.java:612)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.k(SourceFile:316)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.a(SourceFile:350)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.a(SourceFile:331)
            at com.google.android.exoplayer.ExoPlayerImplInternal.a(SourceFile:540)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:219)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)
05-11 19:21:56.605     190-3354/? E/OMX-VDEC-1080P? Error in ioctl read next msg
05-11 19:21:56.619    3188-3188/? E/Play Video? Play video error->com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 640, 304, 1.0, -1, -1, -1, -1, 1920, 1080)
05-11 19:21:56.630      190-629/? E/? Destroy C2D instance
05-11 19:21:56.630      190-629/? E/? Destroy C2D instance
05-11 19:21:56.632    3188-3332/? E/ExoPlayerImplInternal? Stop failed.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_stop(Native Method)
            at android.media.MediaCodec.stop(MediaCodec.java:628)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.n(SourceFile:380)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.j(SourceFile:353)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.j(SourceFile:325)
            at com.google.android.exoplayer.TrackRenderer.u(SourceFile:212)
            at com.google.android.exoplayer.ExoPlayerImplInternal.b(SourceFile:512)
            at com.google.android.exoplayer.ExoPlayerImplInternal.m(SourceFile:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.k(SourceFile:479)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:232)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)

**Comment by sachinbhanot** [comment] 2015-05-13 06:25
even If i am trying to play in Micromax a77 its showing the error

05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): Internal runtime error.
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): java.lang.IllegalStateException
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:731)
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:446)
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): 	at android.os.Handler.dispatchMessage(Handler.java:103)
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): 	at android.os.Looper.loop(Looper.java:194)
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): 	at android.os.HandlerThread.run(HandlerThread.java:60)
05-13 11:53:58.925: E/ExoPlayerImplInternal(2421): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by sachinbhanot** [comment] 2015-05-13 07:20
I checkout the previous branch
Commit: ccac9fad4e61eae184b329b93e9ae2501cf79eb6 [ccac9fa]
Parents: 876fa41b43, b0a3c30a90
Author: ojw28 <olly@google.com>
Date: 09 February 2015 22:59:44
Labels: HEAD


and its working for this branch . I am not sure what changes are done after that. so can you please help me out from this issue? there are many device in which exoplayer is not working?

**Comment by ojw28** [comment] 2015-05-13 07:59
The two errors are completely different. The Nexus 4 is probably in a bad state (possibly due to another app misbehaving and not properly releasing the decoder).

**Comment by sachinbhanot** [comment] 2015-05-13 08:17
yes , i tried on standard exo player demo code. its not working for many micormax devices

**Comment by ojw28** [comment] 2015-05-13 08:19
What about the Nexus 4 after power cycling? Can you please provide more details of the devices. What version of Android are they running?

**Comment by sachinbhanot** [comment] 2015-05-13 08:22
sry , I am not aware that , what is power cycling with the device ?
Android L 5.0

**Comment by ojw28** [comment] 2015-05-13 08:51
Sorry, bad language. Try turning it off and on again. This will help determine whether the issue is actually another application behaving badly (e.g. not releasing the decoder).

**Comment by ojw28** [comment] 2015-05-13 08:51
Ah, I see you did that. I'll try and reproduce. Thanks.

**Comment by ojw28** [comment] 2015-05-13 09:35
On the Nexus 4, what's the exact Android build? Go to Settings -> About phone, and copy everything from "Build number".

**Comment by ojw28** [comment] 2015-05-13 10:04
Hm. I tried Nexus 4 running Android 5.0 (LRX21T) and a MicroMax Canvas 4, and experienced no issues playing any of the HLS demo videos in the demo app.

**Comment by sachinbhanot** [comment] 2015-06-02 06:01
Hi,

This is a test stream url , 
http://54.243.144.35:1935/vod/_definst_/smil:tmp/0_9xum6cv2.smil/playlist.m3u8
Can you please test this url in demo app?

**Comment by ojw28** [comment] 2015-06-04 17:17
Works fine on my Nexus 4 in the demo app. What's the exact Android build? Go to Settings -> About phone, and copy everything from "Build number".

**Comment by sachinbhanot** [comment] 2015-07-16 08:26
Hi Build no is LMY47V

**Comment by lhtuan** [comment] 2015-10-13 04:07
have you released your exoplayer? I had a same problem when i forgot to release the exoplayer.

**Comment by ojw28** [comment] 2016-11-25 20:34
I think we need to put this down to the test device being in a bad state. Closing as obsolete because realistically we're not going to be able to dedicate any more time to looking at this issue.

**Closed by ojw28** 2016-11-25 20:34 UTC
Labels: need more info
