### ISSUE TITLE
DASH Live stream stops playing multiperiod manifest

### ISSUE THREAD

**Issue by bhjortsberg** [google/ExoPlayer#4492] opened 2018-07-10 10:22 UTC
### Issue description
Playing a DASH Live stream with multiperiods. 
The player is stuck and stops playing when there is a new period. Sometimes the player continues after 30-60s and eventually the player also crashes with 

```
07-10 11:52:25.114  9551  9551 D AndroidRuntime: Shutting down VM
07-10 11:52:25.133  9551  9551 E AndroidRuntime: FATAL EXCEPTION: main
07-10 11:52:25.133  9551  9551 E AndroidRuntime: Process: ---------, PID: 9551
07-10 11:52:25.133  9551  9551 E AndroidRuntime: java.lang.IndexOutOfBoundsException
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.util.Assertions.checkIndex(Assertions.java:68)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.source.dash.DashMediaSource$DashTimeline.getPeriod(DashMediaSource.java:1054)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector$MediaPeriodQueueTracker.updateMediaPeriodToNewTimeline(AnalyticsCollector.java:778)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector$MediaPeriodQueueTracker.onTimelineChanged(AnalyticsCollector.java:727)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java:424)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java:746)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:681)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:622)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:567)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:109)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-10 11:52:25.133  9551  9551 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

Using an older version of ExoPlayer works fine (2.6.1).

### Reproduction steps
See the provided DASH media presentation

### Link to test content
Unfortunately no link but the manifest file that cases the issue:
[manifest_period.mpd.txt](https://github.com/google/ExoPlayer/files/2179855/manifest_period.mpd.txt)

### Version of ExoPlayer being used
Non-working version: 2.8.2 
Working fine in: 2.6.1

### Device(s) and version(s) of Android being used
Emulator Android 7.1.1 and OnePlus3T Android 8.0

### Link
The following issue seem to be similar use case:
https://github.com/google/ExoPlayer/issues/3431

**Comment by ojw28** [comment] 2018-07-12 19:04
@tonihei - The crash looks like a bug in `MediaPeriodQueueTracker`. I didn't get as far as reproducing, but my hypothesis is that:

1. There's an active period in the timeline.
1. The timeline updates and the period is removed. `updateMediaPeriodToNewTimeline` is called. `newPeriodIndex` is `INDEX_UNSET` for the removed period, and so the period entry is returned without being updated. Importantly, this means there may now be an entry in `activeMediaPeriods` with an invalid period index.
1. The timeline updates again. `updateMediaPeriodToNewTimeline` is called, and tries to use the invalid period index to access the timeline.

I think you'd normally expect `onMediaPeriodReleased` to happen between (2) and (3), which would avoid the problem, but I doubt that's guaranteed and it seems flaky to rely on it. 

@bhjortsberg - For the playback getting stuck, this may be a result of invalid changes being made to the manifest. Unfortunately we can't determine whether this is the case just from a snapshot of the manifest. We'd need a working test stream ideally, or alternatively a sequence of manifest files showing how it changes over time.

**Comment by bhjortsberg** [comment] 2018-07-13 09:46
It's possible that it can be something with the manifest, I can't see anything myself though. Attaching a sequence of manifest when the player get stuck. I think it's hard to get a working stream, but I can do a network capture if that would help. 

I'm not sure if it get stuck when the old period (id: p_3_382868305) disappears from the manifest or when the new (id: p_3_382868325) is created. 
Also in manifest_11.mpd there are 2 new segments compared to manifest_10.mpd, but that should not be a problem? 

[manifest_player_stop_08.mpd.txt](https://github.com/google/ExoPlayer/files/2192117/manifest_player_stop_08.mpd.txt)
[manifest_player_stop_09.mpd.txt](https://github.com/google/ExoPlayer/files/2192118/manifest_player_stop_09.mpd.txt)
[manifest_player_stop_10.mpd.txt](https://github.com/google/ExoPlayer/files/2192119/manifest_player_stop_10.mpd.txt)
[manifest_player_stop_11.mpd.txt](https://github.com/google/ExoPlayer/files/2192120/manifest_player_stop_11.mpd.txt)
[manifest_player_stop_12.mpd.txt](https://github.com/google/ExoPlayer/files/2192121/manifest_player_stop_12.mpd.txt)
[manifest_player_stop_13.mpd.txt](https://github.com/google/ExoPlayer/files/2192122/manifest_player_stop_13.mpd.txt)

**Comment by ojw28** [comment] 2018-07-23 14:53
The actual crash should be fixed now. Please could you try `dev-v2` to see if your live stream still gets stuck (i.e. there's something else wrong), or whether the issue is now resolved?

**Comment by bhjortsberg** [comment] 2018-07-27 11:22
Hi, yes the crash is fixed! However, the stream still gets stuck.

**Comment by ojw28** [comment] 2018-07-27 11:24
Ok. I'm not sure we can do much about that without a live test stream, given we're unable to reproduce with other streams we have. I couldn't see anything obviously wrong from the manifests provided.

**Comment by bhjortsberg** [comment] 2018-07-27 11:40
Ok, I'll see if I can come arrange something.

**Comment by bhjortsberg** [comment] 2018-08-01 19:37
Hi, I have now created a live stream.
Available here: 
*removed*
Conditions are not ideal but I'll try to keep the stream alive.

**Comment by ojw28** [comment] 2018-08-01 19:57
Using the latest `dev-v2` branch, I'm not able reproduce a permanent freeze. I do see a freeze for a few seconds at the end of the green/white striped part at 29:27, but it always recovers after a few seconds. I haven't worked out whether that's due to the content or not yet.

Could you describe exactly what you're seeing when you try and play this stream?

**Comment by bhjortsberg** [comment] 2018-08-02 07:52
There is a new period when switching to and from the green/white stripe part. This stream works better and I can see what you are seeing that it freezes at 29:27, the period ends at 30:00. This freeze does not happen on 2.6.1 or in shaka-player.

**Comment by bhjortsberg** [comment] 2018-08-02 09:20
Sometimes it also freezes at 09:27 just before  green/white stripe preiod should start, sometimes you can see just millisecond stall. And sometimes it just works without problem. A timing issue?

**Comment by ojw28** [comment] 2018-08-02 12:06
I tried reproducing again with some additional logging this morning. Playback worked flawlessly for about half an hour. Now I'm seeing very frequent socket timeouts, which is making it difficult to test. Could you take a look and see if there's a problem?

For what it's worth, my suspicion is that there's something subtly wrong with the stream. The logging I've added is to look at the sample timestamps being extracted (after adjustment by presentation offset) from each period. I'm interested in checking they align properly with what the manifest indicates is there (i.e. they start at t~=0 and go up to t~=period_duration). When the stream was working flawlessly they looking absolutely fine, but that doesn't really tell us much :).

**Comment by ojw28** [comment] 2018-08-02 12:30
In addition to checking the socket timeout problem, is it possible for you to increase the size of the live window for the stream? It's quite frustrating getting to the point where the issue reproduces, and not being able to rewind to go over that point again because it's dropped off the back of the live window.

**Comment by bhjortsberg** [comment] 2018-08-02 12:53
Yes, I can increase the live window. And I will try to make the connection more stable.

**Comment by bhjortsberg** [comment] 2018-08-02 13:09
You should have 20min live window now (at least when it has been running for 20min). Segments will be available for 60min.

**Comment by ojw28** [comment] 2018-08-03 15:37
I think this issue occurs only when the DASH manifest is both multi-period and contains `EventStream` elements. We'll push a fix shortly, and would be grateful if you could verify on your end. Thanks!

**Comment by ojw28** [comment] 2018-08-03 16:05
In addition, I'm fairly confident that the `Event.presentationTime` values are incorrect in the test stream. As per the DASH spec they should be relative to the start of the period, however they appear to be absolute (i.e. relative to the start of the live stream). This may cause an eventual hang, even after the fix we'll be pushing. I'm not too sure about this though.

**Comment by bhjortsberg** [comment] 2018-08-03 16:12
Nice! Yes, I'll be able to verify the fix.
You are probably right about the `Event.presentationTime`, thanks for pointing that out. I'll fix that on our side.

**Comment by bhjortsberg** [comment] 2018-08-05 21:29
If I remove the `EventStream` element everything works fine.

**Comment by ojw28** [comment] 2018-08-06 11:03
The ExoPlayer part of this issue is addressed by the change ref'd above. I'm not certain, but you may still encounter eventual freezing for as long as the presentation timestamps in the `EventStream` are incorrect. You should fix that on your side.

Thanks for the test stream; very helpful!

**Closed as completed by ojw28** 2018-08-06 11:03 UTC
Labels: need more info

**Comment by bhjortsberg** [comment] 2018-08-06 13:01
I've verified the fix and it works! Thanks a lot!
Will this go into verion 2.8.3?

**Comment by ojw28** [comment] 2018-08-06 13:06
Yes, it has been cherry picked already: https://github.com/google/ExoPlayer/commit/e92d65533f8720793d186b81c4c50aedb7411395

**Comment by nicusorflorin** [comment] 2018-11-28 16:03
@ojw28 the crash is happening once more on 2.9.0, and it looks like the code for the crash fix is missing from the source codes, any updates to why it wasn't merged? was it generating another issue?

**Comment by ojw28** [comment] 2018-11-28 16:39
It looks like the changes are there to me. Can you be more specific.

**Comment by nicusorflorin** [comment] 2018-11-28 16:44
@ojw28 this commit https://github.com/google/ExoPlayer/commit/7d4ac516e72233ebee63bc57fa4529c8b76c54d1 which as i understand from the previous comments, should fix the actual crash, on v2.9.0 this piece of code is missing

**Comment by ojw28** [comment] 2018-11-28 17:00
It looks like it was removed in a subsequent change. Looking at the subsequent change, this appears to have been deliberate, because it should no longer be necessary.

Whatever the crash is you're seeing, it's not the same as the one at the top of this issue, because the method that was crashing no longer exists. Please can you provide more complete information (i.e. the actual crash, and a manifest to reproduce the issue). I'd suggest filing it as a new issue, since it's unclear whether it's really that related to this one.

**Comment by nicusorflorin** [comment] 2018-11-28 17:18
@ojw28 I changed the licenseUrl, i'm not allowed to actually give access to the video, sorry about that
```    
java.lang.IndexOutOfBoundsException
        at com.google.android.exoplayer2.util.Assertions.checkIndex(Assertions.java:68)
        at com.google.android.exoplayer2.source.dash.DashMediaSource$DashTimeline.getPeriod(DashMediaSource.java:1153)
        at com.google.android.exoplayer2.Timeline.getPeriodByUid(Timeline.java:757)
        at com.google.android.exoplayer2.ExoPlayerImpl.getCurrentWindowIndex(ExoPlayerImpl.java:492)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:632)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generatePlayingMediaPeriodEventTime(AnalyticsCollector.java:650)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java:442)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java:839)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:776)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:713)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:658)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:129)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```


[manifestCrash.txt](https://github.com/google/ExoPlayer/files/2625925/manifestCrash.txt)

**Comment by ojw28** [comment] 2018-11-29 00:04
I don't think it's the same issue. Please file a new issue, filling out the template as much as is feasible (e.g., but not limited to, details of exactly how to reproduce the problem).
