### ISSUE TITLE
 ChunkSampleSource can become stuck in isPendingReset state when switching the audio track

### ISSUE THREAD

**Issue by bartsidee** [google/ExoPlayer#1438] opened 2016-04-12 17:32 UTC
We are seeing some random stalls of the player when swithing audio tracks with MS Smoothstream content.

After some research into the logic it seems that the issue is related to the "isPendingReset" state which is kept in a true state after an audio track switch:
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/chunk/ChunkSampleSource.java#L596

I've been able to track the below order of events within ChunkSampleSource when a track is switched:
1. [enable](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/chunk/ChunkSampleSource.java#L182) method is called to enable to new track which triggers restartFrom
2. [restartFrom](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/chunk/ChunkSampleSource.java#L307) method is called which sets the pendingResetPositionUs value and triggers updateLoadControl
3. [updateLoadControl](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/chunk/ChunkSampleSource.java#L423) is called which should trigger [maybeStartLoading](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/chunk/ChunkSampleSource.java#L460) to correctly continue playback

the problem is that on our failure cases **maybeStartLoading** is not called, the reason is that [nextLoader](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/chunk/ChunkSampleSource.java#L448) is returning false, the logs seem to indicate that player is at that moment still fetching/finishing a fragment from the previous track

Now the problem is that if the player fails to call "maybeStartLoading" the player is stuck in an endless loop as the pendingResetPositionUs is not correctly reset. 

Could it be that the player is missing a fallback mechanism for this scenario?

Utilising exoplayer 1.5.7

Below some logs:

**Unsuccessful track switch**
04-12 18:30:24.100 6529-7208/com.mmm.sbx D/SampleSourceTrackRender: enabledSourceTrackIndex: 1
04-12 18:30:24.100 6529-7208/com.mmm.sbx D/ChunkSampleSource: enable: 1, 7526227
04-12 18:30:24.100 6529-7208/com.mmm.sbx D/SSChunkSource: enable track:1
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: enable: bufferSizeContribution 3538944
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: restartFrom: 7526227
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: loader.isLoading()false
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: clearCurrentLoadable
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl doChunkOperation state3
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: doChunkOperation
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl chunksDiscardedfalse
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl currentLoadableHolder.chunk == nullfalse
**04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()false, nextLoader:false**
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ExoPlayerImplInternal: enableRenderer 1
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ExoPlayerImplInternal: enableRenderer 2 mediaClock != null
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()false, nextLoader:false
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:0, 7526227
04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: isPendingReset:false
**04-12 18:30:24.105 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:0, SAMPLE_READ**
04-12 18:30:24.110 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()false, nextLoader:false
**04-12 18:30:24.110 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:1, 7526227**
**04-12 18:30:24.110 6529-7208/com.mmm.sbx D/ChunkSampleSource: isPendingReset:true**
**04-12 18:30:24.110 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:1, NOTHING_READ**
04-12 18:30:24.110 6529-6529/com.mmm.sbx D/VideoFragment_VIDEO: s = 1 buffering
04-12 18:30:24.110 6529-6529/com.mmm.sbx D/VideoFragment_VIDEO: s = 1
04-12 18:30:24.110 6529-6529/com.mmm.sbx I/VideoPlayerPlugin: javascript: window.videoplayer.raiseEvent('VideoPlayerStateChange', ['1'])
04-12 18:30:24.115 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()false, nextLoader:false
04-12 18:30:24.115 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()false, nextLoader:false
04-12 18:30:24.115 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:1, 7526227
04-12 18:30:24.115 6529-7208/com.mmm.sbx D/ChunkSampleSource: isPendingReset:true
04-12 18:30:24.115 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:1, NOTHING_READ
04-12 18:30:24.125 6529-6820/com.mmm.sbx D/VideoPlayerPlugin: execute allAudioTracks args: []
04-12 18:30:24.125 6529-6820/com.mmm.sbx D/VideoFragment_VIDEO: allAudioTracks - [{"language":"deu","description":"deu, 2ch, 44100Hz, 0.09Mbit,  (0)","index":0},{"language":"eng","description":"eng, 2ch, 44100Hz, 0.09Mbit,  (0)","index":1}]
04-12 18:30:24.125 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()false, nextLoader:false
04-12 18:30:24.130 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()false, nextLoader:false
04-12 18:30:24.130 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:1, 7526227
04-12 18:30:24.130 6529-7208/com.mmm.sbx D/ChunkSampleSource: isPendingReset:true
04-12 18:30:24.130 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:1, NOTHING_READ

**Successful track switch**
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/SampleSourceTrackRender: enabledSourceTrackIndex: 0
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: enable: 0, 751000
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/SSChunkSource: enable track:0
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: enable: bufferSizeContribution 3538944
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: restartFrom: 751000
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: loader.isLoading()false
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: clearCurrentLoadable
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl doChunkOperation state3
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: doChunkOperation
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl chunksDiscardedfalse
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl currentLoadableHolder.chunk == nullfalse
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()false, nextLoader:true
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl maybeStartLoading
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: maybeStartLoading 1
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: maybeStartLoading 2
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: maybeStartLoading 3 - pendingResetPositionUs reset
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: notifyLoadStarted
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: loader.startLoading
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ExoPlayerImplInternal: enableRenderer 1
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ExoPlayerImplInternal: enableRenderer 2 mediaClock != null
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()true, nextLoader:false
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:0, 751000
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: isPendingReset:false
04-12 18:30:15.625 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:0, FORMAT_READ
04-12 18:30:15.640 6529-6529/com.mmm.sbx D/VideoFragment_VIDEO: s = 1 buffering
04-12 18:30:15.640 6529-6529/com.mmm.sbx D/VideoFragment_VIDEO: s = 1
04-12 18:30:15.640 6529-6529/com.mmm.sbx I/VideoPlayerPlugin: javascript: window.videoplayer.raiseEvent('VideoPlayerStateChange', ['1'])
04-12 18:30:15.640 6529-6529/com.mmm.sbx D/DebugTextViewHelper: videoFormat [0.25, 2, 1]
04-12 18:30:15.765 6529-6529/com.mmm.sbx D/DebugTextViewHelper: bandwidth [0.38, 290635, 0.10, 23725306]
04-12 18:30:15.765 6529-6529/com.mmm.sbx D/DebugTextViewHelper: bandwidth [0.38, 1299, 0.00, 23725306]
04-12 18:30:15.830 6529-7208/com.mmm.sbx D/MediaCodec: OMX.MTK.VIDEO.DECODER.AVC.secure needRmClient (289)
04-12 18:30:15.830 6529-7208/com.mmm.sbx D/MediaCodec: OMX.MTK.VIDEO.DECODER.AVC.secure needVdpImgrz (295)
04-12 18:30:15.840 6529-7224/com.mmm.sbx I/OMXClient: Using client-side OMX mux.
04-12 18:30:15.885 6529-6537/com.mmm.sbx W/art: Suspending all threads took: 10.836ms
04-12 18:30:15.895 6529-7223/com.mmm.sbx D/MediaCodec: secure path, set mOutputPath = OUTPUT_VIDEO_MAIN
04-12 18:30:15.895 6529-7223/com.mmm.sbx D/MediaCodec: set mOutputPath = 256
04-12 18:30:15.900 6529-7224/com.mmm.sbx E/binder.hwcomposer: [enable_vdp:59][channel=0 ,enable=1] 
04-12 18:30:15.905 6529-7224/com.mmm.sbx E/ACodec: [OMX.MTK.VIDEO.DECODER.AVC.secure] storeMetaDataInBuffers failed w/ err -1010
**04-12 18:30:15.965 6529-7208/com.mmm.sbx D/ChunkSampleSource: updateLoadControl loader.isLoading()true, nextLoader:true**
04-12 18:30:15.965 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:0, 751000
04-12 18:30:15.965 6529-7208/com.mmm.sbx D/ChunkSampleSource: isPendingReset:false
04-12 18:30:15.965 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:0, FORMAT_READ
04-12 18:30:15.965 6529-7230/com.mmm.sbx I/OMXClient: Using client-side OMX mux.
04-12 18:30:15.970 6529-6529/com.mmm.sbx D/DebugTextViewHelper: decoderInitialized [0.58, OMX.MTK.VIDEO.DECODER.AVC.secure]
04-12 18:30:15.970 6529-6529/com.mmm.sbx D/DebugTextViewHelper: audioFormat [0.58, 0, 2]
04-12 18:30:15.980 6529-7230/com.mmm.sbx D/MediaCodec: set mOutputPath = 1024 L(1531)
04-12 18:30:16.015 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:0, 751000
04-12 18:30:16.015 6529-7208/com.mmm.sbx D/ChunkSampleSource: isPendingReset:false
04-12 18:30:16.015 6529-7208/com.mmm.sbx D/ChunkSampleSource: readData track:0, SAMPLE_READ
04-12 18:30:16.015 6529-7208/com.mmm.sbx D/ChunkSampleSource: notifyLoadCompleted

**Comment by bartsidee** [comment] 2016-04-13 09:10
Some additional info:, 
the reason that nextLoader boolean is _false_ is that the **currentbuffer** size value is still larger or equal compared to the **targetBufferSize** value in [DefaultLoadControl](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/DefaultLoadControl.java#L190)

It could have a relation with the fragment from track 0 which is still read after track 1 is enabled, I expect the cause to be some sort of synchronization issue but was unable to pinpoint it yet.

**Comment by ojw28** [comment] 2016-04-13 11:30
Hmm. Are you passing non-default values when constructing the `DefaultLoadControl`, or are you just using the constructor that only takes an `Allocator`? Have you tweaked any other values, such as the buffer segment size that's being used?

**Comment by ojw28** [comment] 2016-04-13 11:31
If possible, please let us know how we can reproduce this in the ExoPlayer demo app.

**Comment by bartsidee** [comment] 2016-04-13 16:08
I'm using the exoplayer demoplayer with default configuration on an AndroidTv device.

let me review if we have a url which we can share.

**Comment by kubotron** [comment] 2016-05-04 10:29
It seems this is the case also with DASH streams, we're working on creating a sample stream we could share, where we can reliably reproduce the issue

**Comment by ojw28** [comment] 2016-08-23 19:52
Closing due to lack of a sample that reproduces the issue.

**Closed by ojw28** 2016-08-23 19:52 UTC
Labels: need more info
