### ISSUE TITLE
Exception in ParsableByteArray while parsing FMP4 segment

### ISSUE THREAD

**Issue by DayanandaMadappa** [google/ExoPlayer#792] opened 2015-09-14 11:59 UTC
Hi,

While playing dash profile stream,content is not playing till total duration.while playback below exception is continously seen in FragmentedMp4Extractor and at some point of time it exited from the playback.
Please help me in resolving this issue.

```
09-08 11:50:32.974 E/LoadTask(28728): java.lang.IllegalStateException: Top bit not zero: -1
09-08 11:50:32.974 E/LoadTask(28728): 	at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:240)
09-08 11:50:32.974 E/LoadTask(28728): 	at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:628)
09-08 11:50:32.974 E/LoadTask(28728): 	at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:162)
09-08 11:50:32.974 E/LoadTask(28728): 	at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
09-08 11:50:32.974 E/LoadTask(28728): 	at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
09-08 11:50:32.974 E/LoadTask(28728): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
09-08 11:50:32.974 E/LoadTask(28728): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
09-08 11:50:32.974 E/LoadTask(28728): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-08 11:50:32.974 E/LoadTask(28728): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-08 11:50:32.974 E/LoadTask(28728): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
```

Regards
Daya

**Comment by ojw28** [comment] 2015-09-14 12:35
Sounds a bit like bad media to me, or at least unusual media. You'll need to provide a sample stream for us to debug.

**Comment by ojw28** [comment] 2015-09-14 12:37
You may also like to try upgrading to the latest release, just in case that resolves the issue. I think you're on 1.4.1 currently.

**Comment by dnutcracker** [comment] 2015-09-17 16:31
Probably related - 
I got this using the latest dev branch with device LG LS665 on Android 5.1.1 when trying to play a local mp4 file:
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -1355457943
       at com.google.android.exoplayer.SampleSourceTrackRenderer.handlesTrack(SampleSourceTrackRenderer.java:146)
       at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:133)
       at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:207)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -1355457943
       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: Top bit not zero: -1355457943
       at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:240)
       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:328)
       at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:122)
       at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:745)
       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Any ideas?

**Comment by ojw28** [comment] 2016-02-21 20:58
Closing due to lack of information.

**Closed by ojw28** 2016-02-21 20:58 UTC
Labels: need more info
