### ISSUE TITLE
Unable to (1) add okhttp as a gradle dependency to the demo application, and (2) build exoplayer modules locally in r2.7.2

### ISSUE THREAD

**Issue by griygagns** [google/ExoPlayer#4059] opened 2018-03-30 08:12 UTC
(1) Unlike r2.7.0, I am not allowed to import any okhttp3 classes in the demo application after adding `implementation project(modulePrefix + 'extension-okhttp')` to demo's build.gradle. Then, I proceed to directly add `implementation 'com.squareup.okhttp3:okhttp:3.10.0'` instead. Unfortunately, I am still unable to build the apk in the release mode successfully even though the proguard options suggested in https://github.com/square/okhttp#proguard are added to demo's proguard-rules.txt.

(2) I also tried to build exoplayer modules locally according to https://github.com/google/ExoPlayer#locally. However, Android Studio warned that javadoc_util.gradle does not exist. To overcome this problem, I have to copy it to the root folder of my project.

Note that I didn't encounter the above problems before r2.7.0.

**Comment by ojw28** [comment] 2018-04-02 15:30
The correct thing to add to the demo app's build file would be:
```
implementation project(modulePrefix + 'extension-okhttp')
implementation('com.squareup.okhttp3:okhttp:3.9.0') {
  exclude group: 'org.json'
}
```
Which works fine for me. Having said that:
* We should consider using `api` rather than `implementation` for the dependency our OkHttp extension has on the OkHttp library, given using the extension requires application code using OkHttp library classes directly.
* The `javadoc_util.gradle` thing is an oversight, and is something we should fix.

**Comment by griygagns** [comment] 2018-04-02 16:32
Thank you for your reply. It is true that everything works fine if using "debug" build type. However, I still fail to generate signed APK when the build type is chosen as "release" (i.e. both shrinkResources and minifyEnabled in demo's build.gradle are true). For details, please see the error messages below:

![untitled](https://user-images.githubusercontent.com/37923459/38204380-5321c070-36d5-11e8-8fe5-644708695258.png)

**Comment by griygagns** [comment] 2018-04-02 16:36
Apart from the above build issue, I also wonder why the issue of okhttp dependency is not found before r2.7.0. 

EDITED: I understand the difference between api and implementation now. My problem remaining is the  build failure issue mentioned above. Thank you.

**Comment by ojw28** [comment] 2018-04-02 18:35
* The dependency change is a result of https://github.com/google/ExoPlayer/commit/f91e6349fdd464db6902e66a672667a601abe797#diff-c6b1b36d417beffe802401b73f6b0bf0. We should probably use `api` rather than `implementation` for OkHttp, as noted above, which will undo this change of behavior.

* Adding consumer proguard rules directly to the okhttp extension, rather than to the demo app, resolves the warnings. This is something else we should do.

* After fixing the warnings I'm still hitting another proguard failure, which seems independent of okhttp ("The output jar is empty. Did you specify the proper '-keep' options?"). I've not been able to figure out how to fix that yet. There are some related issues on StackOverflow, but it's unclear whether they're relevant to this case. Do you also hit that failure, or are you able to build successfully?

**Comment by griygagns** [comment] 2018-04-03 07:34
I got the same error.

By the way, there is a minor issue in demo app [(here)](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L553), where " - 1" should be removed after [4828f27](https://github.com/google/ExoPlayer/commit/4828f275c7177a486fa1518b6242ac962741cb87). That's why after r2.7.0 the "video" button is always shown as the last button.

**Comment by ojw28** [comment] 2018-04-03 07:41
Are you using "Build > Generate Signed APK" in Android Studio? It looks to me like it might be broken (i.e. not an ExoPlayer issue). I see the error when using that feature, but if I instead make a release configuration, that works fine.

**Comment by ojw28** [comment] 2018-04-03 07:51
It's interesting that when configuring signing for a release configuration, Android Studio goes and removes nearly all of the dependencies from the app's `build.gradle` file, which then need to be re-added manually. I suspect "Build > Generate Signed APK" makes this transformation every time, which is why it doesn't end up working.

**Comment by griygagns** [comment] 2018-04-03 08:57
Yes. I am used to using "Build > Generate Signed APK" in Android Studio. 

However, now it is very strange that I am suffering from the same "empty output jar" error permanently even if I only try to generate signed apk from a new project that uses a clean ExoPlayer-r2.7.2.zip. I am wondering if Android Studio has some previous project caches that prevent me from generating signed apk sucessfully. Do you know how to solve this annoying problem?

**Comment by ojw28** [comment] 2018-04-03 09:30
Yes, the issue is unrelated to any changes you may have made. I'll open a couple of issues against Android Studio to get their input on the problem. Until the underlying issue is fixed, I think you just need to generate the apk some other way. Hopefully command line tools are not affected.

**Comment by ojw28** [comment] 2018-04-03 10:01
Bugs filed on Android Studio:
- https://issuetracker.google.com/issues/77507254
- https://issuetracker.google.com/issues/77509617

**Comment by griygagns** [comment] 2018-04-03 10:54
Thanks. Hopefully, android studio can fix the issue asap. 

I can confirm that when shrinkResources and minifyEnabled are set to true, "Build > Generate Signed APK" also works fine with local ExoPlayer modules, including okhttp extension with appropriate modifications as discussed above .

**Comment by ojw28** [comment] 2018-04-03 14:48
Fixes on ExoPlayer side are merged into `dev-v2` (see above), and will be included in the next release. Closing this, since the remaining issue is to the best of our knowledge an Android Studio problem.

**Closed as completed by ojw28** 2018-04-03 14:48 UTC
Labels: bug
