### ISSUE TITLE
Dead Thread Crash Appears When Restarting App.

### ISSUE THREAD

**Issue by grndvl1** [google/ExoPlayer#9093] opened 2021-06-21 14:50 UTC
Handler (android.os.Handler) {7e02fd9} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {7e02fd9} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.sendMessage(Handler.java:519)
        at android.os.Message.sendToTarget(Message.java:416)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.addMediaSources(ExoPlayerImplInternal.java:342)
        at com.google.android.exoplayer2.ExoPlayerImpl.addMediaSources(ExoPlayerImpl.java:431)
        at com.google.android.exoplayer2.ExoPlayerImpl.addMediaItems(ExoPlayerImpl.java:400)
        at com.google.android.exoplayer2.ExoPlayerImpl.addMediaItems(ExoPlayerImpl.java:395)
        at com.google.android.exoplayer2.BasePlayer.addMediaItem(BasePlayer.java:65)
        at com.google.android.exoplayer2.SimpleExoPlayer.addMediaItem(SimpleExoPlayer.java:1531)
        at ai.bright.ifit.tv.gate.ui.GateFragment$onResume$1.invokeSuspend(GateFragment.kt:95)

Using Exoplayer 2.12.0
Running on Google TV and FireTv (for a TV app, runs on phone and get same crash)
Seen this error in previous versions and people said it was fixed in 2.x.  Do I need to update 2.12 to higher to fix?

**Comment by icbaker** [comment] 2021-06-21 15:40
Are you sure this is a crash? I believe that message is logged as a warning and shouldn't cause a crash: 
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/os/MessageQueue.java;l=562;drc=5d123b67756dffcfdebdb936ab2de2b29c799321

See the discussion in https://github.com/google/ExoPlayer/issues/426 for the same warning triggered by a different call-site (which it sounds like you might have already read, based on your 2.x comment? The label on that issue 'fixed in 2.x' indicates the changes were made in ExoPlayer v2 before 2.0.0 was released, and so they're included in 2.12.0).

Based on the specific stack trace you've pasted it looks like `SimpleExoPlayerImpl.release()` has completed (quitting `ExoPlayerImplInternal.internalPlaybackThread`) before you call `SimpleExoPlayer.addMediaItem`. `Player#release` is [documented](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#release()) as follows:
> The player must not be used after calling this method.

From the information provided it looks like the root cause of these logs is an application problem (interacting with a Player instance after it's been released). If this doesn't sound right, and you believe it's a bug in the library, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by grndvl1** [comment] 2021-06-21 16:13
Sorry yeah it doesn't crash but nothing plays.  We are using a video for the start screen and this error occurs and nothing plays.  If I finish the app by hitting backbutton it will play properly on next restart.  But I think I have the solution and that is to not hang onto player but saved in the oncreateview() using the SimpleExoPlayer.Builder().build.  Instead in onResume() call and save it here instead.  That seems to fix the issues and video plays all the time.  Probably not the best way to do this but it works

**Comment by icbaker** [comment] 2021-06-22 10:45
Glad you resolved the problem!

**Closed as completed by icbaker** 2021-06-22 10:45 UTC
Labels: question
