### ISSUE TITLE
Stuck media playback with VPAID ads

### ISSUE THREAD

**Issue by chladto1** [google/ExoPlayer#7832] opened 2020-08-31 18:11 UTC
### [REQUIRED] Issue description
VPAID ads are not supported by IMA, but it look like, IMA is correctly sending event _CONTENT_RESUME_REQUESTED_, but the media playback is stuck anyway. Could you please fix it?

### [REQUIRED] Reproduction steps
Use the following VMAP as adTagUri.

### [REQUIRED] Link to test content
[https://devs.origin.cdn.cra.cz/ima/vpaidvmap.xml](https://devs.origin.cdn.cra.cz/ima/vpaidvmap.xml)

### [REQUIRED] A full bug report captured from the device
[log.txt](https://github.com/google/ExoPlayer/files/5151844/log.txt)

### [REQUIRED] Version of ExoPlayer being used
2.11.8

### [REQUIRED] Device(s) and version(s) of Android being used
Device or Android version independent.

**Comment by christosts** [comment] 2020-09-01 11:53
@andrewlewis can you please take a look?

**Comment by andrewlewis** [comment] 2020-09-01 13:07
Thanks for the report and for including the ad tag. A fix (to resume content immediately) is in review.

**Comment by chladto1** [comment] 2020-10-18 17:07
Unfortunately, here you are another test content that leads into stuck media playback. Can you please take a look?

VPAID in preroll, 3 ad breaks and postroll
Test content: [https://devs.origin.cdn.cra.cz/ima/vpaidvmap2.xml](https://devs.origin.cdn.cra.cz/ima/vpaidvmap2.xml)
Log: [vpaidvmap2.txt](https://github.com/google/ExoPlayer/files/5397850/vpaidvmap2.txt)

Preroll with ad and VPAID
Test content: [https://devs.origin.cdn.cra.cz/ima/vmap2adswithvpaid.xml](https://devs.origin.cdn.cra.cz/ima/vmap2adswithvpaid.xml)
Log: [vmap2adswithvpaid.txt](https://github.com/google/ExoPlayer/files/5397867/vmap2adswithvpaid.txt)

ExoPlayer version 2.12.0

**Comment by andrewlewis** [comment] 2020-10-26 17:22
For the first ad tag, I have a change in review that makes the previous the fix referenced above more general, which avoids playback getting stuck. This issue will be updated if/when that's merged.

For the second ad tag, something strange is going on where we are reporting an ad position to the IMA SDK, but the IMA SDK is not updating the ad overlay view, nor notifying us when the ad finishes. I couldn't reach any conclusions about the cause of this I'm afraid. Given that VPAID ads are officially listed as unsupported [here](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/compatibility#video-features-and-sdk-versions), I don't think we should spend a lot of time diagnosing what's going on with the second tag and finding a way to make it fail gracefully. I think the best way to address this is to configure your ad server not to serve VPAID ads to Android clients.

**Comment by BucherTomas** [comment] 2020-10-27 12:55
@andrewlewis Thank you for looking into it.

I agree that VPAID ads should not be even served to mobile devices in ideal world. However, ad servers often utilize their own rules serving ads and even though ad campaigns on these servers are managed by people owning applications that use ExoPlayer, they might not have the means to affect the ad server logic and filter out VPAID ads from ad pool targeted at mobile devices.

That is why the purpose of this ticket is to make ExoPlayer + IMA combo as robust as possible when handling VPAID ads since player stalling as a result of failure is fairly bad UX.

If you believe that IMA is doing something wrong, would you be so kind and forward it to them together with your findings? Thank you.

**Comment by andrewlewis** [comment] 2021-01-21 10:09
I need to revert this workaround as it caused the regression reported in #8428 but I plan to replace it with a different workaround that allows loading the VPAID ad to time out.

**Closed as completed** 2021-02-01 18:20 UTC
Labels: bug
