### ISSUE TITLE
Mp3Extractor.readSample crash with ArrayIndexOutOfBoundsException with broken mp3 streams

### ISSUE THREAD

**Issue by softlion** [google/ExoPlayer#2559] opened 2017-03-15 11:06 UTC
### Issue description
Using ExoPlayerFactory with a MediaCodecAudioRenderer having the default MediaCodecSelector, and the DefaultTrackSelector, and an ExtractorMediaSource 
Reading an mp3 live stream using a custom data source.

The data from the datasource may have discontinuities.
When a discontinuity happens, exoplayer crashes.

### Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app.

### Link to test content
http://cdn.nrjaudio.fm/adwz1/fr/30405/aac_64.mp3

### Version of ExoPlayer being used
r2.2.0

### Device(s) and version(s) of Android being used
Android 5.1 emulator
All

### A full bug report captured from the device
```
E/LoadTask( 2855): Unexpected exception loading stream
E/LoadTask( 2855): java.lang.ArrayIndexOutOfBoundsException: src.length=8192 srcPos=0 dst.length=65536 dstPos=65784 length=-248
E/LoadTask( 2855):      at java.lang.System.arraycopy(Native Method)
E/LoadTask( 2855):      at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromPeekBuffer(DefaultExtractorInput.java:208)
E/LoadTask( 2855):      at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:54)
E/LoadTask( 2855):      at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:485)
E/LoadTask( 2855):      at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readSample(Mp3Extractor.java:184)
E/LoadTask( 2855):      at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:156)
E/LoadTask( 2855):      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:635)
E/LoadTask( 2855):      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
E/LoadTask( 2855):      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/LoadTask( 2855):      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/LoadTask( 2855):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/LoadTask( 2855):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/LoadTask( 2855):      at java.lang.Thread.run(Thread.java:818)
```

**Comment by ojw28** [comment] 2017-03-15 12:22
I'm quite confused by this issue. I don't think the player does crash, since the exception is immediately caught and handled? What is the exact behavior you're seeing, and what is the behavior you expect?

**Comment by ojw28** [comment] 2017-03-15 13:53
Closing as working as intended. There's no evidence here that there's actually a crash (only that an exception was logged prior to being handled). It's not valid to insert arbitrary discontinuities into an mp3 stream, and this is not something we support or intend to support. Correct behavior is that the player will fail (without crashing the process), which I think is what already happens.

**Closed as completed by ojw28** 2017-03-15 13:53 UTC
Labels: need more info

**Comment by softlion** [comment] 2017-03-15 13:58
Well the player does fail and loose its buffer.

iOS native player does support discontinuities, as this happens frequently in live streams with poor network conditions.

readFromPeekBuffer should not try to copy an array with a negative length ...

**Comment by ojw28** [comment] 2017-03-15 14:03
If poor network conditions cause a break in connectivity and a discontinuity is introduced as a result, then that's a valid case that we already handle correctly. It's different to the stream just containing arbitrary discontinuities, because we're aware that it's happened.

I'm not sure the negative length comment is particularly relevant. Sure, we could add a large number of checks everywhere through all of our extractors for invalid data, all of which would just throw some other exception instead. The end result is the same, the code is messier and the checks consume additional CPU time, which is why we just let it fail and catch the exception at the top level.

**Comment by softlion** [comment] 2017-03-15 14:04
Ok
