### ISSUE TITLE
Callback for `dispatchFastForward`, `dispatchRewind` and `dispatchSeekTo` 

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#10212] opened 2022-04-22 08:13 UTC
Since ControlDispatcher and DefaultControlDispatcher have been removed from **[v2.16.0](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2160-2021-11-04)** 

How do we get the call back fast forward, rewind button press, and also user seek to a different position?

**Comment by marcbaechinger** [comment] 2022-04-25 10:58
You can use a `ForwardingPlayer` as mentioned in the [release notes you are referring to](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2160-2021-11-04):

```
Remove ControlDispatcher and DefaultControlDispatcher. Operations can be customized by 
using a `ForwardingPlayer`, or when configuring the player (for example by using
`ExoPlayer.Builder.setSeekBackIncrementMs)`.
```

It  depends on what you want to do which isn't clear from the information you provided. Assuming you are using the `ControlDispatcher` for the `StyledPlayerView` you may want to do something like this:

```
ForwardingPlayer forwardingPlayer = new ForwardingPlayer(player) {
  @Override
  public void seekForward() {
    if (iNeedCustomBehaviour) {
      // Do what you need to do.
    } else {
      super.seekForward();
    }
 }
};
playerView.setPlayer(forwardingPlayer);
```

I'm going to close this as a duplicate of #9756.

If you need further assistance please try to search the issue tracker for [`ControlDispatcher`](https://github.com/google/ExoPlayer/issues?q=is%3Aissue++ControlDispatcher+). If this does not help please ad some more detailed information about your use case here and reopen the issue.

**Comment by drayan85** [comment] 2022-05-04 06:39
Basically, we are trying to detect when users seek forward and backward to trigger analytics events

**Comment by marcbaechinger** [comment] 2022-05-04 15:24
I think in this case my comment above should be sufficient.  You can either intercept the seek command as demonstrated with the code snippet. You can alternatively just use `AnalyticsListener` to get `onPositionDiscontinuity` that reports when the player processed a seek.

I'm closing this issue. If you add more info or have other questions, please reopen.

**Closed as completed by marcbaechinger** 2022-05-04 15:24 UTC
Labels: duplicate, question
