### ISSUE TITLE
Failed to play stream with error log "Error -22 initializing AudioTrack"

### ISSUE THREAD

**Issue by weizhaoj** [google/ExoPlayer#3627] opened 2017-12-22 00:01 UTC
**Version of ExoPlayer being used**
dev-v2-r2.6.0

**Issue description:**
when I go to play the below stream:
https://test.playready.microsoft.com/media/dash/APPLEENC_CBCS_BBB_1080p/clear/bbb_sunflower_1080p_60fps_normal.mp4

It will report below log:
```
12-21 15:12:41.673   210   595 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
12-21 15:12:41.674   210   595 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
12-21 15:12:41.675   210   472 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
12-21 15:12:41.676   210   472 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
12-21 15:12:41.680   242  2758 I chatty  : uid=1046(mediacodec) omx@1.0-service expire 3 lines
12-21 15:12:41.683   227   966 W APM_AudioPolicyManager: getOutput() could not find output for stream 3, samplingRate 48000,format 150994944, channels 3f, flags 1
12-21 15:12:41.683  2613  2714 E AudioTrack: Could not get audio output for session 17, stream type -1, usage 1, sample rate 48000, format 0x9000000, channel mask 0x3f, flags 0x1
12-21 15:12:41.683  2613  2714 E AudioTrack-JNI: Error -22 initializing AudioTrack
12-21 15:12:41.683  2613  2714 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: Renderer error.
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:439)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:998)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:573)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:325)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:101)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:164)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 20480)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1181)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:487)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:544)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:433)
12-21 15:12:41.687  2613  2714 E ExoPlayerImplInternal: 	... 7 more
12-21 15:12:41.688   242   665 I chatty  : uid=1046(mediacodec) HwBinder:242_4 expire 45 lines
12-21 15:12:41.723  2613  2746 D SurfaceUtils: disconnecting from surface 0xcf874008, reason disconnectFromSurface
12-21 15:12:41.730   242   314 I chatty  : uid=1046(mediacodec) HwBinder:242_2 expire 28 lines
12-21 15:12:41.733  2613  2613 D EventLogger: videoDisabled [1.40]
12-21 15:12:41.737  2613  2613 D EventLogger: audioDisabled [1.41]
12-21 15:12:41.757  2613  2613 E EventLogger: playerFailed [1.42]
12-21 15:12:41.757  2613  2613 E EventLogger: com.google.android.exoplayer2.ExoPlaybackException
12-21 15:12:41.757  2613  2613 E EventLogger: 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:439)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:998)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:573)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:325)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at android.os.Handler.dispatchMessage(Handler.java:101)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at android.os.Looper.loop(Looper.java:164)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-21 15:12:41.757  2613  2613 E EventLogger: Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 20480)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1181)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:487)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:544)
12-21 15:12:41.757  2613  2613 E EventLogger: 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:433)
12-21 15:12:41.757  2613  2613 E EventLogger: 	... 7 more
12-21 15:12:41.757  2613  2613 D EventLogger: loading [false]
12-21 15:12:41.768  2613  2613 D EventLogger: state [1.44, true, I]
12-21 15:12:41.977   458   474 I ActivityManager: Waited long enough for: ServiceRecord{328eafe u0 com.android.tv.settings/.users.UserSwitchListenerService}
12-21 15:12:42.979   458   474 I ActivityManager: Waited long enough for: ServiceRecord{ed8cd40 u0 com.google.android.apps.mediashell/.MediaShellCastReceiverService}
12-21 15:12:43.338  1184  2769 D EpgDataCleanupService: Received intent: Intent { act=com.android.providers.tv.intent.CLEAN_UP_EPG_DATA flg=0x4 cmp=com.android.providers.tv/.EpgDataCleanupService (has extras) }
12-21 15:12:43.347  1765  1765 D cr_RecommendationsService: [RecommendationsService.java:109] onReceive: Intent { act=com.google.android.apps.mediashell.ACTION_RECOMMEND flg=0x14 (has extras) }
12-21 15:12:43.635   458   565 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
12-21 15:12:44.445  1765  1765 E chromium: [1765:1765:ERROR:client_auth_signer.cc(295)] Cast certificate is not valid.
12-21 15:12:44.445  1765  1765 I chatty  : uid=10008(u0_a8) com.google.android.apps.mediashell identical 12 lines
12-21 15:12:45.204   203   203 I chatty  : uid=1000(system) memtrack@1.0-se expire 12 lines
12-21 15:12:45.284   930  2773 V NativeCrypto: SSL handshake aborted: ssl=0xc720a3c8: I/O error during system call, Connection reset by peer
12-21 15:12:45.297   458   469 D ConnectivityService: reportNetworkConnectivity(100, false) by 10003
```

**Comment by andrewlewis** [comment] 2017-12-22 08:44
Please provide a full bug report captured with `adb bugreport` just after reproducing the error.

**Comment by weizhaoj** [comment] 2017-12-22 17:40
Please check attached log file, please let me any other info you need.
[bugreport.txt](https://github.com/google/ExoPlayer/files/1583130/bugreport.txt)

**Comment by andrewlewis** [comment] 2018-01-02 08:42
The linked bug report doesn't include `DUMP OF SERVICE media.audio_flinger` or full logcat, which would be useful for diagnosing this. Please could you try capturing it again?

**Comment by weizhaoj** [comment] 2018-01-04 01:22
After switch to another version of Exoplayer, clear stream can play well, but got crash when play encrypted stream(AES CENC CBCS).
So, close this one....

**Comment by tonihei** [comment] 2018-01-05 10:20
Re-opening because it's not solved yet (see #3662). Full bug report still missing for further investigation.

**Comment by weizhaoj** [comment] 2018-01-05 18:58
[bugreport.txt](https://github.com/google/ExoPlayer/files/1607588/bugreport.txt)
[logcat.txt](https://github.com/google/ExoPlayer/files/1607589/logcat.txt)

Please cehck attached log which incldue "media.audio_flinger"
--------- 0.003s was the duration of dumpsys ** media.audio_flinger**
-------------------------------------------------------------------------------
DUMP OF SERVICE media.audio_policy:
AudioPolicyManager: 0xf26c5200
Command Thread: 0xf26af140
Tones Thread: 0xf26af020
AudioCommandThread 0xf26af140 Dump
- Commands:
   Command Time        Wait pParam
  Last Command
   04      001747.172  0    0xf1e95030
AudioCommandThread 0xf26af020 Dump
- Commands:
   Command Time        Wait pParam
  Last Command
     none

AudioPolicyManager Dump: 0xf26c5200
 Primary Output: 13
 Phone state: AUDIO_MODE_NORMAL
 Force use for communications 0
 Force use for media 0
 Force use for record 0
 Force use for dock 8
 Force use for system 0
 Force use for hdmi system audio 0
 Force use for encoded surround output 0
 TTS output not available
 Master mono: off
- Available output devices:
  Device 1:
  - id:  5
  - tag name: HDMI
  - type: AUDIO_DEVICE_OUT_AUX_DIGITAL                    
  - Profiles:
      Profile 0:[dynamic format][dynamic channels][dynamic rates]
      Profile 1:
          - format: AUDIO_FORMAT_PCM_16_BIT
          - sampling rates:48000
          - channel masks:0x0003
      Profile 2:[dynamic format]
          - format: AUDIO_FORMAT_PCM_16_BIT
          - sampling rates:8000, 11025, 16000, 22050, 24000, 32000, 44100, 48000
          - channel masks:0x0001, 0x0003
      Profile 3:
          - format: AUDIO_FORMAT_PCM_16_BIT
          - sampling rates:8000, 16000, 24000, 32000, 44100, 48000
          - channel masks:0x0003
      Profile 4:
          - format: AUDIO_FORMAT_PCM_16_BIT
          - sampling rates:8000, 16000, 22050, 24000, 32000, 44100, 48000
          - channel masks:0x0001, 0x0003
      Profile 5:[dynamic format]
          - format: AUDIO_FORMAT_PCM_8_24_BIT
          - sampling rates:8000, 11025, 16000, 22050, 24000, 32000, 44100, 48000
          - channel masks:0x0001, 0x0003
      Profile 6:[dynamic format]
          - format: AUDIO_FORMAT_IEC61937
          - sampling rates:8000, 11025, 16000, 22050, 24000, 32000, 44100, 48000
          - channel masks:0x0001, 0x0003
      Profile 7:[dynamic format]
          - format: AUDIO_FORMAT_AC3
          - sampling rates:8000, 11025, 16000, 22050, 24000, 32000, 44100, 48000
          - channel masks:0x0001, 0x0003

**Comment by andrewlewis** [comment] 2018-01-08 08:50
Configuring the AudioTrack for 6 channel AC-3 passthrough is failing. Is there an audio receiver connected via HDMI that is capable of decoding this? I wonder whether the problem is that the current configuration supports passthrough of only stereo AC-3 not 5.1.

**Comment by weizhaoj** [comment] 2018-01-08 19:25
I install Exoplayer APK on an Android box(our platform), to decode Audio/Video and output to a TV via HDMI. The passthrough path should be working via SPDIF, not HDMI.
I think the device I connect should have no problem, because it can play well with another version --
 "ExoPlayer-release-v2".

**Comment by andrewlewis** [comment] 2018-01-09 09:23
AC-3 passthrough works fine for me in the demo app for stereo and 5.1 sources (and the link you posted above), in `dev-v2-r2.6.0`, `dev-v2-r2.6.1` and `release-v2`, testing on a Sony Bravia Android TV.

Please could you confirm on which ExoPlayer version this is broken? Are you able to reproduce the same issue on any other Android devices?

**Comment by weizhaoj** [comment] 2018-01-09 23:34
Thanks for your test. 
Based on your info, I switch to dev-v2-r2.6.1 and change my TV(HDMI receiver). The clear stream can play well.

**Comment by andrewlewis** [comment] 2018-01-10 09:11
Thanks for the update. It sounds like this is resolved so I'll close the issue. If there is a remaining problem related to initializing the AudioTrack please describe it and I'll reopen the issue.

**Closed as completed by andrewlewis** 2018-01-10 09:11 UTC
Labels: question
