### ISSUE TITLE
Upgrade to V2.9.0 causes my apk to crash 

### ISSUE THREAD

**Issue by harini113** [google/ExoPlayer#5026] opened 2018-10-30 20:51 UTC
**"Error is: java.lang.RuntimeException: Constructor thew an exception. Class: com.qualcomm.aptmm_exoplayer.VideoTest
10-26 08:28:19.205  5161  5161 D AndroidRuntime: Shutting down VM
--------- beginning of crash
10-26 08:28:19.207  5161  5161 E AndroidRuntime: FATAL EXCEPTION: main
10-26 08:28:19.207  5161  5161 E AndroidRuntime: Process: com.qualcomm.aptmm_exoplayer, PID: 5161
10-26 08:28:19.207  5161  5161 E AndroidRuntime: java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo"**

When I try to use my apk based of V2.9.0 library, it crashes right away with the above error. The v2.8.4 does not have this issue.

Expected behavior: is my video file plays and completes.
Actual behavior: is the apk crashes right away with above error in the logcat. The adb output for my apk is as follows
**"INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0"**

Version of apk: Dev 2.9.0

**Comment by iamkurtgoz** [comment] 2018-10-31 00:04
as CommonsWare mentioned, for reference add this inside the android {...} closure in the build.gradle for your app module to resolve issue:

android {
...
  compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
...
}

**Comment by tonihei** [comment] 2018-10-31 08:44
Did that solve your issue? It's probably a duplicate of #4907 if so.

**Closed as completed** 2018-10-31 08:44 UTC
Labels: duplicate

**Comment by ojw28** [comment] 2018-10-31 10:12
@tonihei - Can we update our documentation (e.g. dev guide / readme) to specify the need for the Java 8 compile options? Last I asked it didn't sound like it would be enabled by default any time soon.

**Comment by harini113** [comment] 2018-11-01 16:24
Thanks Ojw28 and tonihei, The compile options did fix my issue. If you can
add it by default or add it to some documentation that would definitely
help.

Thanks

Sri

**Comment by tonihei** [comment] 2018-11-01 16:52
We did both, see the commits referenced above.
