### ISSUE TITLE
DefaultDrmSessionManager accessed before setPlayer(), possibly on the wrong thread.

### ISSUE THREAD

**Issue by Kolyall** [google/ExoPlayer#11149] opened 2023-05-04 10:30 UTC
### Bug

Version: 2.18.6

Sometimes in Log I see the trace, but cant determinate problem in my code:
```
DefaultDrmSessionManager accessed before setPlayer(), possibly on the wrong thread.
                                   java.lang.IllegalStateException
                                       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.verifyPlaybackThread(DefaultDrmSessionManager.java:824)
                                       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.prepare(DefaultDrmSessionManager.java:471)
                                       at com.google.android.exoplayer2.source.dash.DashMediaSource.prepareSourceInternal(DashMediaSource.java:450)
                                       at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:221)
                                       at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:120)
                                       at com.google.android.exoplayer2.source.WrappingMediaSource.prepareChildSource(WrappingMediaSource.java:212)
                                       at com.google.android.exoplayer2.source.MaskingMediaSource.createPeriod(MaskingMediaSource.java:108)
                                       at com.google.android.exoplayer2.MediaSourceList.createPeriod(MediaSourceList.java:315)
                                       at com.google.android.exoplayer2.MediaPeriodHolder.createMediaPeriod(MediaPeriodHolder.java:433)
                                       at com.google.android.exoplayer2.MediaPeriodHolder.<init>(MediaPeriodHolder.java:108)
                                       at com.google.android.exoplayer2.MediaPeriodQueue.enqueueNextMediaPeriodHolder(MediaPeriodQueue.java:190)
                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1999)
                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1986)
                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:974)
                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
                                       at android.os.Handler.dispatchMessage(Handler.java:103)
                                       at android.os.Looper.loop(Looper.java:237)
                                       at android.os.HandlerThread.run(HandlerThread.java:67)
```

Android Studio:
```
Flamingo | 2022.2.1 Patch 1
Build #AI-222.4459.24.2221.9971841, built on April 19, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-148-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins:
    idea.plugin.protoeditor (222.4459.16)
    com.intellij.marketplace (222.4459.28)
    com.intellij.javafx (1.0.4)
    co.anbora.labs.kse (1.4.0)
    JUnit4-Parallel-Runner (1.5)
    com.atlassian.bitbucket.references (2022.1.224)
    com.thoughtworks.gauge (222.4459.16)
    com.developerphil.adbidea (1.6.9)

Current Desktop: ubuntu:GNOME
```

**Comment by Kolyall** [comment] 2023-05-04 10:54
Maybe it is due to this lines are in incorrect positions in com.google.android.exoplayer2.source.dash.DashMediaSource#prepareSourceInternal? 
![2023-05-04_13-53](https://user-images.githubusercontent.com/3495165/236184299-119acfb5-a32d-4509-8135-cdfbc99e88e6.png)

**Comment by marcbaechinger** [comment] 2023-05-04 12:53
Thanks for reporting. 
This is a duplicate of https://github.com/androidx/media/issues/350

It was fixed with https://github.com/google/ExoPlayer/commit/aa4e0080147fe76a6c0cca40b7eccdf45eb58028

**Closed as completed by marcbaechinger** 2023-05-04 12:53 UTC
Labels: duplicate

**Comment by Kolyall** [comment] 2023-05-04 13:47
@marcbaechinger But when the issue will be fixed in the library `com.google.android.exoplayer:exoplayer-dash` https://github.com/google/ExoPlayer/blob/cf49175f790dc4bbee85bb195c021ea40765d84b/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/DashMediaSource.java#L450 ?

**Comment by icbaker** [comment] 2023-05-04 14:06
@Kolyall It's already fixed on the `dev-v2` branch by the commit Marc linked above:

https://github.com/google/ExoPlayer/blob/5dbbff49ddac62c16a5eda1a40f104248cffc426/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/DashMediaSource.java#L450-L451

**Comment by Kolyall** [comment] 2023-05-04 14:55
@icbaker and when new release will be published with the fix?
