### ISSUE TITLE
setPreferredVideoMimeType does not work with HLS content.

### ISSUE THREAD

**Issue by HyowonHwang** [google/ExoPlayer#9841] opened 2022-01-06 00:53 UTC
Hi, I've tried to set preferred video mime type  like below and Test sample are consist of avc and hevc variants.

```
  trackSelectionParameters =
          new DefaultTrackSelector.ParametersBuilder(/* context= */ this)
              .setPreferredVideoMimeType(MimeTypes.VIDEO_H265)
              .build();

```
But it doesn't seem to work. I've got logs by `EventLogger`

```
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger: tracks [eventTime=3.57, mediaPos=0.00, window=0, period=0
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:   MediaCodecVideoRenderer [
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=YES_NOT_SEAMLESS [
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:0, id=0, mimeType=video/avc, bitrate=1015727, codecs=avc1.640028, res=1920x1080, trick-play-track, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:1, id=1, mimeType=video/avc, bitrate=760174, codecs=avc1.64001f, res=1280x720, trick-play-track, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:2, id=2, mimeType=video/avc, bitrate=520162, codecs=avc1.64001f, res=960x540, trick-play-track, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:3, id=3, mimeType=video/avc, bitrate=186651, codecs=avc1.64001f, res=640x360, trick-play-track, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:4, id=4, mimeType=video/avc, bitrate=95410, codecs=avc1.64001f, res=480x270, trick-play-track, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:5, id=5, mimeType=video/avc, bitrate=2523597, codecs=avc1.640020, res=960x540, fps=60.0, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:6, id=6, mimeType=video/avc, bitrate=9873268, codecs=avc1.64002a, res=1920x1080, fps=60.0, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:7, id=7, mimeType=video/avc, bitrate=7318337, codecs=avc1.64002a, res=1920x1080, fps=60.0, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:8, id=8, mimeType=video/avc, bitrate=5421720, codecs=avc1.64002a, res=1920x1080, fps=60.0, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:9, id=9, mimeType=video/avc, bitrate=3611257, codecs=avc1.640020, res=1280x720, fps=60.0, supported=YES
2022-01-06 09:51:02.423 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:10, id=10, mimeType=video/avc, bitrate=1475903, codecs=avc1.64001f, res=768x432, fps=30.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:11, id=11, mimeType=video/avc, bitrate=1017705, codecs=avc1.64001f, res=640x360, fps=30.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:12, id=12, mimeType=video/avc, bitrate=582820, codecs=avc1.64001f, res=480x270, fps=30.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:13, id=13, mimeType=video/avc, bitrate=339404, codecs=avc1.64001f, res=416x234, fps=30.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:14, id=32, mimeType=video/hevc, bitrate=328352, codecs=hvc1.2.4.L123.B0, res=1920x1080, trick-play-track, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:15, id=33, mimeType=video/hevc, bitrate=226274, codecs=hvc1.2.4.L123.B0, res=1280x720, trick-play-track, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:16, id=34, mimeType=video/hevc, bitrate=159037, codecs=hvc1.2.4.L123.B0, res=960x540, trick-play-track, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:17, id=35, mimeType=video/hevc, bitrate=92800, codecs=hvc1.2.4.L123.B0, res=640x360, trick-play-track, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:18, id=36, mimeType=video/hevc, bitrate=51760, codecs=hvc1.2.4.L123.B0, res=480x270, trick-play-track, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:19, id=37, mimeType=video/hevc, bitrate=2164328, codecs=hvc1.2.4.L123.B0, res=960x540, fps=60.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:20, id=38, mimeType=video/hevc, bitrate=6664228, codecs=hvc1.2.4.L123.B0, res=1920x1080, fps=60.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:21, id=39, mimeType=video/hevc, bitrate=5427899, codecs=hvc1.2.4.L123.B0, res=1920x1080, fps=60.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:22, id=40, mimeType=video/hevc, bitrate=4079770, codecs=hvc1.2.4.L123.B0, res=1920x1080, fps=60.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:23, id=41, mimeType=video/hevc, bitrate=2764701, codecs=hvc1.2.4.L123.B0, res=1280x720, fps=60.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:24, id=42, mimeType=video/hevc, bitrate=1226255, codecs=hvc1.2.4.L123.B0, res=768x432, fps=30.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:25, id=43, mimeType=video/hevc, bitrate=901770, codecs=hvc1.2.4.L123.B0, res=640x360, fps=30.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:26, id=44, mimeType=video/hevc, bitrate=548927, codecs=hvc1.2.4.L123.B0, res=480x270, fps=30.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:27, id=45, mimeType=video/hevc, bitrate=340713, codecs=hvc1.2.4.L123.B0, res=416x234, fps=30.0, supported=YES
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:     ]
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:     Metadata [
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:       HlsTrackMetadataEntry
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:     ]
2022-01-06 09:51:02.424 19388-19388/com.google.android.exoplayer2.demo D/EventLogger:   ]

```

Is there any point that I should try or bug? 

- URI to test content for reproduction
  https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8

- ExoPlayer version number
  r2.16.1

**Comment by ojw28** [comment] 2022-01-06 10:35
Duplicate of https://github.com/google/ExoPlayer/issues/9519

**Closed as completed by ojw28** 2022-01-06 10:35 UTC
Labels: bug
