### ISSUE TITLE
 Why automatic handling of audio focus is only available for USAGE_MEDIA and USAGE_GAM

### ISSUE THREAD

**Issue by Raynor999** [google/ExoPlayer#7399] opened 2020-05-20 07:59 UTC
some case, automatic ducking is expected behavior for music and video playback apps,
so i need requests focus with AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK  to let other apps duck and restore the volume .  but, automatic handling of audio focus is only available for USAGE_MEDIA and USAGE_GAM

**Comment by nic0lette** [comment] 2020-05-28 15:36
Hi @Raynor999 -- can you explain more about your use case?

I was the person who originally added the automatic handling of audio focus, and the reason I added it only for `USAGE_MEDIA` and `USAGE_GAME` is because, in my mind, one used ExoPlayer for playing long bits of content, such as songs, background tracks, or movies.

By contrast, `AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK` is intended for instances where an app wants to play something "short", such as a notification sound. It's also ill suited if the content includes any spoken words, because the user could end up in a situation where song lyrics + spoken content were being played together, and that can make it difficult to understand.

**Comment by ojw28** [comment] 2020-06-11 18:47
I think the immediate question here has been answered.  In terms of the enhancement request, I've generalized https://github.com/google/ExoPlayer/issues/7317 to track this, and therefore will close this issue as a duplicate of that one.

**Closed as completed by ojw28** 2020-06-11 18:47 UTC
Labels: duplicate, question
