### ISSUE TITLE
E/MediaCodecVideoRenderer: Video codec error

### ISSUE THREAD

**Issue by KostyaLyapochkin** [google/ExoPlayer#9476] opened 2021-09-23 14:13 UTC
Hello. I've stuck with this error. Full description:

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(4, null, null, video/avc, avc1.64002A, 18320008, null, [1920, 856, 24.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:558)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec.secure, Format(4, null, null, video/avc, avc1.64002A, 18320008, null, [1920, 856, 24.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1034)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:585)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:2142)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.processEndOfStream(MediaCodecRenderer.java:2017)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1848)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:823)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalArgumentException: The surface has been released
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1882)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:50)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1121)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1027)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:585) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:2142) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.processEndOfStream(MediaCodecRenderer.java:2017) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1848) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:823) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```
Shortly speaking, A VideoService holds my player inside to support background playing that is when an application is in the background. When the application goes to the background mode ad must play. When player intents to change source in the background mode I have this error. I think that it can be similar with this issue https://github.com/google/ExoPlayer/issues/8776 which had been fixed.

https://github.com/KostyaLyapochkin/ExoPlayerErrorExample - I've pushed new commit with tag #9476.
Please, Take a look.

**Comment by icbaker** [comment] 2021-09-23 14:47
Thanks for the repro project. I tried it on a Pixel 5 and backgrounded the app a few times during both ad and content playback and didn't see any failures.

Are there more specific repro steps I should be taking?

What device(s) do you see this problem on?

Could you capture an `adb bugreport` immediately after reproducing and either upload it here or send to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by KostyaLyapochkin** [comment] 2021-09-23 15:07
@icbaker Oh, sorry I've forgotten to specify list of devices. Pixels and Android Emulators work perfectly as usual but I have this issue on  Pixel 2 XL( Android 10), Xiaomi Redmi note 7 Pro 10 (Android 10), Galaxy Tab S2 SM-T810 (Android 7), Galaxy S8 (Android 9).

[bugreport-2021-09-23-18-05-08.zip](https://github.com/google/ExoPlayer/files/7218769/bugreport-2021-09-23-18-05-08.zip)

I can record a video if you need.

**Comment by icbaker** [comment] 2021-09-23 15:27
> I can record a video if you need.

That would be really helpful, just so i can understand exactly when the failure happens.

Thanks!

**Comment by KostyaLyapochkin** [comment] 2021-09-24 06:27
https://user-images.githubusercontent.com/36475116/134628258-0c849107-54b2-45f0-93c5-8474f0af1dc6.mp4

**Comment by icbaker** [comment] 2021-09-28 13:11
Thanks for the video, I didn't realise you were waiting for the ads to fully play out while the app was in the background. I'm now able to reproduce a failure on both a Pixel 5 and a OnePlus AC2003 by:
1. Opening the app, the ad starts playing
2. Background the app, the ad audio is still audible
3. Wait for the ad audio to stop playing (and the error appears in the logcat here)
4. Re-foreground the app and the content doesn't play.

Turns out there's another bug in `MediaCodecVideoRenderer` - similar to #8776 as you say. Basically the fix for that issue missed a possible combination of events:
* If we're currently using the dummy surface (e.g. because the app is in the background) then `this.dummySurface == this.surface`. 
* And then if we realise we need a new `DummySurface` because we're switching to secure content
   * Then the fix for 8776 nulls out `dummySurface` and releases it
   * But `this.surface` is still pointing to the old, released surface instance. 
* The fix is to null out `surface` as well if `surface == dummySurface`.

I've sent a fix for this, it should be linked below shortly.

As a workaround I was able to make things work on a Pixel 5 by calling [`MediaItem.Builder#setDrmSessionForClearPeriods(true)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.Builder.html#setDrmSessionForClearPeriods(boolean)). This works because the dummy surface is configured to be secure from the beginning, so we never need to reinstantiate it. However it resulted in a different error on the OnePlus - the same as #8696:

```
2021-09-27 12:28:50.156 10764-14693/com.example.exoplayererrorcodecsample D/SurfaceUtils: connecting to surface 0xb400007c989b6d00, reason connectToSurface
2021-09-27 12:28:50.156 10764-14693/com.example.exoplayererrorcodecsample E/BufferQueueProducer: [SurfaceTexture-1-10764-0](id:2a0c00000000,api:3,p:10764,c:10764) connect: already connected (cur=3 req=3)
2021-09-27 12:28:50.156 10764-14693/com.example.exoplayererrorcodecsample E/SurfaceUtils: Failed to connect to surface 0xb400007c989b6d00, err -22
2021-09-27 12:28:50.156 10764-14693/com.example.exoplayererrorcodecsample E/MediaCodec: nativeWindowConnect returned an error: Invalid argument (-22)
2021-09-27 12:28:50.156 10764-14503/com.example.exoplayererrorcodecsample E/MediaCodec: configure failed with err 0xffffffea, resetting...
2021-09-27 12:28:50.163 10764-14694/com.example.exoplayererrorcodecsample I/OMXClient: IOmx service obtained
2021-09-27 12:28:50.179 10764-14628/com.example.exoplayererrorcodecsample D/SurfaceUtils: disconnecting from surface 0xb400007c989b28e0, reason pushBlankBuffersToNativeWindow
2021-09-27 12:28:50.185 10764-14503/com.example.exoplayererrorcodecsample W/MediaCodecRenderer: Failed to initialize decoder: OMX.qcom.video.decoder.avc.secure
      java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2128)
        at android.media.MediaCodec.configure(MediaCodec.java:2044)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:50)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1121)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1027)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:585)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:2142)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.processEndOfStream(MediaCodecRenderer.java:2017)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1848)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:823)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:245)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Closed as completed** 2021-09-30 09:21 UTC
Labels: bug

**Comment by KostyaLyapochkin** [comment] 2021-10-18 14:20
@icbaker Hi. setDrmSessionForClearPeriods(true) - workaround has helped me, on the one hand it's pretty restricted solution because when VAST contains webm format, so IMA SDK can return this format for playing, for instance, Samsung devices do not select secure decoder for playing webm format (OMX.Exynos.vp8.dec) as a result I am stuck with the same error. On the other hand Sony F3112 Android 7 uses OMX.MTK.VIDEO.DECODER.AVC with mp4 it means that setDrmSessionForClearPeriods does not help at all.
