### ISSUE TITLE
Partially fragmented FMP4 file does not play correctly

### ISSUE THREAD

**Issue by Abu-Abdullah** [google/ExoPlayer#7308] opened 2020-04-29 07:29 UTC
Hi,

the following file is working with native MediaPlayer but not Exoplayer:
http://maknoon.com/001.m4a

**Comment by christosts** [comment] 2020-05-01 17:10
Assigning to @andrewlewis who is more experienced with media formats:

@andrewlewis this what I see:
- The first sample (buffer) that reaches the MediaCodecAudioRenderer is marked end-of-stream
- Looks like this is caused because the first call to FragmentedMp4Extractor.read() returns RESULT_END_OF_INPUT

**Comment by ojw28** [comment] 2020-05-01 18:37
@kim-vde - I think this will probably be fixed as part of [Internal ref: b/130115709].

The problem is that we think the file is FMP4 because it has an `mvex` atom in the `moov` box, but it actually declares all of the samples in the `moov` atom as well, and does not contain any `moof` atoms. It's therefore an extreme example of a "partially fragmented" MP4 files, where it claims to be fragmented but is in fact not fragmented at all.

**Comment by kim-vde** [comment] 2020-05-04 08:03
@ojw28 Ok. I'll try to fix this when working on [Internal ref: b/130115709]. Thanks for investigating.

@Abu-Abdullah We plan to fix the bug mentioned by Olly in the following months. Thanks for reporting your issue.

**Closed as completed** 2020-07-08 10:01 UTC
Labels: bug, content not playing
