### ISSUE TITLE
Streaming video it drops frame with overlay animated .webp file

### ISSUE THREAD

**Issue by bhavikjethava** [google/ExoPlayer#9597] opened 2021-10-23 18:36 UTC
I have implemented Exoplayer for my android tv app. When I stream 4k video it drops some frame and lag video. I have displayed a full-screen video with an overlay of an animated webp file.

Playing 24fps video work perfectly
Playing 30fps video it's lagging 
I am testing on Google tv(Google Chromecast).

Exoplayer version 2.15.1
implementation 'com.google.android.exoplayer:exoplayer:2.15.1'
implementation 'com.google.android.exoplayer:extension-leanback:2.15.1'

I used VLC Player to play the same video, they were playing fine, but I  want to use exo-player for my android tv application
VLc player version 3.3.13
implementation 'org.videolan.android:libvlc-all:3.3.13'

**Comment by icbaker** [comment] 2021-11-01 11:11
Does the problem occur when playing the video **without** the animated overlay?

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by bhavikjethava** [comment] 2021-11-19 05:08
When I played without animated overlay it run perfectly.
Also, I have send demo app to dev.exoplayer@gmail.com

**Comment by icbaker** [comment] 2021-11-19 16:31
I don't have access to the link provided over email - please make it publicly accessible.

**Comment by bhavikjethava** [comment] 2021-11-19 17:11
Please check

**Comment by icbaker** [comment] 2021-11-22 11:53
Thanks for the demo application.

I ran it on a Pixel 5 (API 30) and saw a smooth-playing video behind an empty banner with a sun logo on the right hand side.

I ran it on a Chromecast with Google TV and saw the same empty banner but the video behind is playing choppily. i.e. I'm able to reproduce the problem you're seeing.

Given the overlay that causes the problem seems to be coming from the Fresco library, and without the overlay ExoPlayer is able to play the video without a problem, I don't think this is a problem with the ExoPlayer library. I suggest you report this issue to the Fresco developers: https://frescolib.org/support.html

**Comment by bhavikjethava** [comment] 2021-11-22 13:38
Thanks for the quick replay.

I have tried to change the overlay to lottie but hard luck. I think any animated overlay isn't compatible with exoplayer, I just checked the same with vlc player and it worked like a charm. so I have sent out a mail with another example please have a look.

Thanks in advance.

**Comment by icbaker** [comment] 2021-11-22 17:56
The latest email seems to contain the ExoPlayer project, I think it was forked from the dev-v2 branch at some point between 2.15.1 and 2.16.0. If you've made modifications to this it's pretty hard to find them (because I don't know what commit I should be comparing against). It's great to use the demo app to reproduce problems, but would it be possible to either share your modified version as a GitHub project (since that will pin-point the commit you forked from) or let me know what commit it's based on and roughly what changes you made?

**Comment by bhavikjethava** [comment] 2021-11-29 08:31
Thanks for the quick replay.

I have attached 2 demos named

1. ExoPlayer.zip (in this demo I'm using the latest version of Exoplayer 2.16.1)
2. ExoPlayer-release-v2.zip (In this example I have used a demo app from https://github.com/google/ExoPlayer added a video and animated overlay. The same problem occurred.

Thanks in advance.

**Comment by icbaker** [comment] 2021-11-29 17:21
I looked at the latest `ExoPlayer.zip` you sent, it seems to contain exactly the same files as the previous `ExoPlayer.zip` that you sent (i.e. based on an unknown commit on the dev-v2 branch between 2.15.1 and 2.16.0).

I also looked at `ExoPlayer-release-v2.zip`. It seems to have no changes when compared to r2.16.1 of ExoPlayer (i.e. the latest version).

I'm closing this because, as above, it seems unlikely there's anything we can do to fix the problem in the ExoPlayer library. If you get further debugging the problem on your own and have specific feedback about a way we can fix it, then please re-open this issue, file a new issue, or (ideally!) send us a PR with the fix.

**Closed as completed by icbaker** 2021-11-29 17:21 UTC
Labels: question
