### ISSUE TITLE
Tracking the "loop" event in ExoPlayer, can this be included in the documentation?

### ISSUE THREAD

**Issue by greyski** [google/ExoPlayer#6157] opened 2019-07-10 00:06 UTC
### [REQUIRED] Searched documentation and issues
I did not see any implementation of this check in the demo apps.

I noticed a previous question attempts to answer this: https://github.com/google/ExoPlayer/issues/3096

A more concrete question answers it here as well: https://github.com/google/ExoPlayer/issues/4802

### [REQUIRED] Question
Could we add documentation about the `DISCONTINUITY_REASON_PERIOD_TRANSITION` and it's usage? Or maybe add a "loop counter" in one of the demo apps?

Although after some google-fu and searching **I** was able to find these links, it took quite some time before I understood the process of tracking the "loop" event and figure this would benefit other developers attempting to replicate this logic (although I personally believe there should be a "loop-specific" callback sent to listeners).

Apologies if this is a "Feature Request", I wasn't sure where documentation suggestions could be made.

### A full bug report captured from the device
n/a

### Link to test content
n/a

**Comment by tonihei** [comment] 2019-07-10 09:18
That's a duplicate of #4898.  Please have a look at this post specifically: https://github.com/google/ExoPlayer/issues/4898#issuecomment-427008090. The main trick is to check if the `player.getCurrentWindowIndex` is still the same as before. 

Agree that can be documented in a better way, so marking as "documentation candidate".

**Closed as completed by tonihei** 2019-07-10 09:18 UTC
Labels: duplicate
