### ISSUE TITLE
Bug with counting time Exoplayer 2.17.1

### ISSUE THREAD

**Issue by Stinger2198** [google/ExoPlayer#10202] opened 2022-04-19 18:46 UTC
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Android device - Amazon Fire tv stick (all version)

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Video plays longer than its duratio
[log_exoplayer.txt](https://github.com/google/ExoPlayer/files/8515640/log_exoplayer.txt)
n

### Expected result

The media plays successfully

### Actual result

Timer continues to count the time, the video on the screen is frozen
![158827506-5c08a2ff-b6ac-4805-a4ae-a2f4ab265842](https://user-images.githubusercontent.com/30195609/164072336-b3755b3e-e944-4053-a5d6-c3b929ff7ae5.jpg)

### Media

[app-release.zip](https://github.com/google/ExoPlayer/files/8515727/app-release.zip)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ojw28** [comment] 2022-04-19 23:57
Duplicate of #10083. Please don't file multiple issues about the same thing. Thanks!

**Closed as completed by ojw28** 2022-04-19 23:57 UTC
Labels: duplicate
