### ISSUE TITLE
Improve movie loading!

### ISSUE THREAD

**Issue by admobwebmaster** [google/ExoPlayer#4985] opened 2018-10-19 16:29 UTC
My exoplayer loads the videos very slow, all the time stopping to load the video.

how do I improve buffering and upload videos without too many uploads.

thank you

**Comment by ojw28** [comment] 2018-10-19 17:35
This kind of bug report is completely unactionable by us, because it doesn't provide any useful information to help us reproduce the problem. Or even to determine whether the issue is client side or server side. Closing. If you want to file a new issue, please fill out the issue template properly.

**Closed as completed by ojw28** 2018-10-19 17:35 UTC
Labels: question
