### ISSUE TITLE
Momentary freeze in camera-fed-GL-texture when loading clip in ExoPlayer

### ISSUE THREAD

**Issue by rcvangemert** [google/ExoPlayer#762] opened 2015-09-06 10:50 UTC
I have a exoplayer and a camera being rendered to a gl texture. When I load a clip while the camera is visible I get a momentry freeze. Is there some way to lower the thread priority while the next clip is loading?

**Comment by ojw28** [comment] 2015-09-07 13:11
I doubt this is anything to do with thread priority. It's probably some unfortunate locking in the underlying media server when the decoder makes its memory allocation, or something like that.

Have you managed to infer anything about what could be causing the momentary freeze?

**Comment by rcvangemert** [comment] 2015-09-07 21:26
>Have you managed to infer anything about what could be causing the momentary freeze?  
I commented out each step in the initialization the freeze occured when I enabled the prepare statment.
player.prepare(videoRenderer, audioRenderer);
My initialization sequence is-
     player = ExoPlayer.Factory.newInstance(RENDERER_COUNT);
     player.addListener(this);
     Mp4Extractor extractor = new Mp4Extractor();
     Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
     DataSource dataSource = new DefaultUriDataSource(context, null, "videoAssist");
     ExtractorSampleSource extractorSampleSource = new ExtractorSampleSource(
         uri, dataSource, allocator, BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE, extractor);
     videoRenderer = new MediaCodecVideoTrackRenderer(extractorSampleSource,
                                                            MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT,
                                                             0,
                                                             handler,
                                                             this,
                                                             0);
       audioRenderer = new AudioTrackRenderer(extractorSampleSource, audioMixer, profile);
            
       player.prepare(videoRenderer, audioRenderer);
            
       surfaceTexture = createSurfaceTexture();
       surface = new Surface(surfaceTexture);
       player.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surface);
On 07/09/2015 11:11 PM, ojw28 <notifications@github.com> wrote:I doubt this is anything to do with thread priority. It's probably some unfortunate locking in the underlying media server when the decoder makes its memory allocation, or something like that.

Have you managed to infer anything about what could be causing the momentary freeze?

**Comment by rcvangemert** [comment] 2015-09-08 04:41
I actualy have 2  exoplayers, camera and graphics pane. All use a opengl texture. when the camera is the primary source and a clip is loaded I get a camera freeze. When a exoplayer is the primary source and a clip is loaded on second exoplayer I get a exoplayer freeze. I know this is pushing things... but its so close to working well. In my case the secondary exoplayer instance can take its time to load a clip as other sources are being recorded.

**Comment by ojw28** [comment] 2015-09-09 10:28
You'll probably need to narrow it down further (i.e. which call within ExoPlayer's code, within prepare). My hunch would be that it occurs when the video decoder allocates the memory that it needs. This may lock something in the underlying media server, causing the camera to freeze.

I'm just speculating, although if that is the issue then there's not much we can do about it.

**Comment by rcvangemert** [comment] 2015-09-09 10:39
Thanks.

**Comment by ojw28** [comment] 2015-10-11 19:19
I don't think there's anything actionable for us to do here, so closing. Please update if you managed to root cause the underlying issue. Thanks!

**Closed by ojw28** 2015-10-11 19:19 UTC
Labels: question
