### ISSUE TITLE
NullPointerException when playing source of HLS in R2.0.4

### ISSUE THREAD

**Issue by newandroidboy88** [google/ExoPlayer#2491] opened 2017-02-23 14:03 UTC
When playing akamihd hls live video  in Exoplayer 2.0.4 
Internal runtime error.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.exoplayer2.source.CompositeSequenceableLoader.getNextLoadPositionUs()' on a null object reference at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.getNextLoadPositionUs(HlsMediaPeriod.java:216) at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1080) at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1076) at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:289) at android.os.Handler.dispatchMessage(Handler.java:98)  at android.os.Looper.loop(Looper.java:148)at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1080)
                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1076)
                                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:289)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                   at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by AquilesCanta** [comment] 2017-02-23 14:10
Please, read the issue template and provide all the required information.

**Comment by AquilesCanta** [comment] 2017-02-23 15:06
I am going to assume this is a duplicate of #2493. If not, please file a new issue including all the information requested in the issue template.

**Closed as completed by AquilesCanta** 2017-02-23 15:06 UTC
