### ISSUE TITLE
Random failure while signing for an APK

### ISSUE THREAD

**Issue by LloydBlv** [google/ExoPlayer#10418] opened 2022-07-07 14:35 UTC
While the tasks for signing the APK are going on a specific task fails with the following feedback:

```
* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, position: Lcom/google/android/exoplayer2/source/dash/manifest/DashManifestParser;parseMediaPresentationDescription(Lorg/xmlpull/v1/XmlPullParser;Landroid/net/Uri;)Lcom/google/android/exoplayer2/source/dash/manifest/DashManifest;, origin: /Users/sa/.gradle/caches/transforms-3/5b877f18430bbf29b75cb7d9cd8a8daa/transformed/exoplayer-dash-2.17.1-runtime.jar:com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.class


```

Tried to bump to recent exo, etc, but still it fails, the wrapper version used is "7.5-rc-2" and the gradle version is : "7.4.0-alpha07"

Can someone please pointout what is going on?

**Comment by yuroyami** [comment] 2022-07-07 21:30
- Have you tried including the classes in question to proguard rules ?

Also, are you using ExoPlayer all-around dependency or declaring each part of ExoPlayer independently ? This may perhaps happen due to a conflict of versions between ExoPlayer parts.

**Comment by LloydBlv** [comment] 2022-07-11 06:33
The mentioned classes are added to the proguard rules file. A unified version is being used for all the exo dependencies actually 2.17.1. Also tried to use recent version, 2.18.0 and still same issue.

**Comment by marcbaechinger** [comment] 2022-07-11 10:32
Thanks for reporting! I can repro this with a new project in Android Studio that plays a DASH sample. I can't repros with the demo app. Marking as bug. We need to investigate this.

```
com.android.tools.r8.internal.f20: Unused argument with users in com.google.android.exoplayer2.source.dash.manifest.DashManifest com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseMediaPresentationDescription(org.xmlpull.v1.XmlPullParser, android.net.Uri)
```

**Comment by LloydBlv** [comment] 2022-07-11 10:58
Testing on the new media3 dependencies produces the same result, fails on :app:minifyReleaseWithR8 task

**Comment by marcbaechinger** [comment] 2022-07-11 11:21
Looks like a bug in the tooling to me - probably in the Android Gradle Plugin. 

When downgrading for instance to `7.2.1` (Android Gradle Plugin version) it works for me with Gradle version `7.3.3` and `7.4`. With an Android Gradle Plugin above `7.2.1` it fails for me. Can you confirm this?

**Comment by LloydBlv** [comment] 2022-07-11 12:28
I can confirm that 7.2.1 worked fine but any version above fails

**Comment by ArcherEmiya05** [comment] 2022-07-21 02:34
Any other update on this or downgrading is the only way to fix this?

**Comment by marcbaechinger** [comment] 2022-07-26 16:40
I don't think that is a library issue that we can fix on the library side. Fixing this would probably need a fix in R8/plugin or you need to work around that the minimizer wants to do it's work. I think downgrading to a Gradle Plugin that does not exhibit the problem is currently the easiest fix. 

I would guess when this is fixed it would need to upgrade to a Gradle Plugin that is not affected, but this is guesswork on my side. I have reported the problem with internal bugref: b/240282988 and will update this issue as soon as I hear something.

**Comment by marcbaechinger** [comment] 2022-08-18 23:18
This has been [fixed in R8](https://r8.googlesource.com/r8/+/92e9516cbe1aed9698d8f02075a2ad4f7b8199ae) and is contained in R8 3.3.75. 

Using the Android Gradle Plugin `7.2.2` fixed the problem for me with Android Studio Dolphin, and Android Gradle Plugin `7.4.0-alpha09` with Android Studio Electric Eel | 2022.1.1 Canary 9.

Can you please verify and re-open the issue if you are still having problems when using the AGP versions above.

**Closed as completed by marcbaechinger** 2022-08-18 23:18 UTC
Labels: bug: in dependency

**Comment by hungntv** [comment] 2022-10-04 08:12
@marcbaechinger thanks. You're my life saver!

=================================
Need to downgrade to 7.2.2??

`classpath 'com.android.tools.build:gradle:7.3.0'`

`Unused argument with users in com.google.android.exoplayer2.source.dash.manifest.DashManifest com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseMediaPresentationDescription(org.xmlpull.v1.XmlPullParser, android.net.Uri)`
