### ISSUE TITLE
How to get response header from Lincence url request?

### ISSUE THREAD

**Issue by karathb** [google/ExoPlayer#5740] opened 2019-04-08 07:05 UTC
Hi all!

I know that the response headers of the last load are available through the onLoadStarted() callback (as part of LoadEventInfo). 

However I would need to parse the headers of the licence url request and as I see that is not passed there. Am I missing something? Should I somehow be able to read the response headers of the licence url request?

Thanks in advance,
Balázs

**Comment by erdemguven** [comment] 2019-04-08 14:59
Response headers on onLoadStarted() callback are always empty perhaps you can use onLoadCompleted().

**Comment by karathb** [comment] 2019-04-08 15:09
Okay, I will test tomorrow and let you know. Though so far I did not even see loadEventInfo.uri == licenseUrl in the onLoadStarted event. Should that also come there? (with the License url)

**Comment by karathb** [comment] 2019-04-09 12:32
Yeah, I am able to see the response headers of the playback urls. For each chunk it is there in onLoadCompleted(). But the issue still exists regarding the license request. For that the response header is not exposed in those callbacks. 

Is there any way of grabbing the reponse header of the licence request?

**Comment by AquilesCanta** [comment] 2019-04-09 12:51
Assuming you are using [DefaultDrmSessionManager](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.html), all license requests are done through [MediaDrmCallback](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/drm/MediaDrmCallback.html) so you can look into it to intercept the response headers. 

When you create an [HttpMediaDrmCallback](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/drm/HttpMediaDrmCallback.html) to pass to the DefaultDrmSessionManager, you can either pass a custom [HttpDataSource.Factory](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/HttpDataSource.Factory.html) or use instead a custom MediaDrmCallback that obtains the response headers through [DataSource#getResponseHeaders](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/DataSource.html#getResponseHeaders--). Hope this helps.

**Comment by karathb** [comment] 2019-04-10 12:59
Okay, so when the player does the license request, it should go through either of the two methods of MediaDrmCallback interface, right? Trying to add a custom callback to intercept the response headers.

**Comment by tonihei** [comment] 2019-04-10 13:08
In the long term, we should ensure these load events are reported through the normal `MediaSourceEventListener` callbacks if possible. We can use this issue for tracking. Note that this needs some further internal refactoring such that the license load events can be associated to a MediaSource or MediaPeriod.

**Comment by karathb** [comment] 2019-04-11 15:36
Side note: for now using a custom MediaDrmCallback seems to be the easiest solution, and works perfectly fine. Thanks for all the help so far, and waiting for the deeper integration :)

**Comment by ojw28** [comment] 2019-05-06 01:02
I think this is probably a duplicate of https://github.com/google/ExoPlayer/issues/5399. @tonihei - Can we duplicate one to the other, and edit the title of the one that we keep to accurately reflect the request? Thanks!

**Comment by tonihei** [comment] 2019-05-07 09:25
Yes, sounds like a duplicate. Using the other one for tracking and closing this one.

**Closed as completed by tonihei** 2019-05-07 09:25 UTC
Labels: duplicate, enhancement
