### ISSUE TITLE
Crash happening on 2.13.0: ArrayIndexOutOfBoundsException in maybeUpdateAdMediaSources

### ISSUE THREAD

**Issue by priscila225** [google/ExoPlayer#8693] opened 2021-03-09 14:32 UTC
I want to report a crash using exoplayer v2.13.0 and googleIMA 3.22.0. It's a TV app in which we have a DAI video and other VOD videos with prerolls/midrolls. Not sure if it's crashing on live video (DAI) or VOD.
Since we updated Exoplayer to 2.13.0 this crash started happening:
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
length=0; index=1
com.google.android.exoplayer2.source.ads.AdsMediaSource.maybeUpdateAdMediaSources (AdsMediaSource.java:316)
com.google.android.exoplayer2.source.ads.AdsMediaSource.onAdPlaybackState (AdsMediaSource.java:295)
com.google.android.exoplayer2.source.ads.AdsMediaSource.access$100 (AdsMediaSource.java:58)
com.google.android.exoplayer2.source.ads.AdsMediaSource$ComponentListener.lambda$onAdPlaybackState$0 (AdsMediaSource.java:385)
com.google.android.exoplayer2.source.ads.AdsMediaSource$ComponentListener.lambda$onAdPlaybackState$0$AdsMediaSource$ComponentListener (AdsMediaSource.java:7)
com.google.android.exoplayer2.source.ads.-$$Lambda$AdsMediaSource$ComponentListener$0n-PEDqeEt9IJPXJ3J126o4e0MQ.run (-.java:7)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.os.HandlerThread.run (HandlerThread.java:61)
```
I believe this might be a crash in the Exo SDK itself since we're not seeing any reference to our code in the stack trace, but even if it's not could you provide me any information on what could be causing this, as well as any tips to fix it?
- ExoPlayer version 2.13.0
- IMA version  3.22.0
- Android 7 47% of crashes
- Android 5 45% of crashes
- Android 9 8% of crashes
- Android device: Amazon AFTT/AFTTM

**Comment by tonihei** [comment] 2021-03-09 14:41
Andrew, could you take a look?

**Comment by cadalt** [comment] 2021-03-10 14:42
we are seeing this crash pretty frequently since upgrading to 2.13.0 as well! so fixing it would be much appreciated!

**Comment by cadalt** [comment] 2021-03-10 18:21
this crash is still happening on 2.13.2

**Comment by priscila225** [comment] 2021-03-10 18:22
^ Yes I can confirm this is occurring on the Exo latest version 2.13.2 version with ima 3.22.2 latest version too

**Comment by victorraft** [comment] 2021-03-10 19:44
@andrewlewis do you think maybe this can be happening because the if statement in line 315-318 is missing an array size check before accessing `adPlaybackState.adGroups[adGroupIndex]`?

**Comment by andrewlewis** [comment] 2021-03-11 08:26
I'm planning to look into this today. Yes, there may is probably a size check missing, but I want to find the code path that's causing the size to be out of synch just to make sure this isn't a symptom of another bug.

**Comment by andrewlewis** [comment] 2021-03-11 14:28
For anyone seeing this crash, is there a code path in your app where `ImaAdsLoader.release()` is called before `Player.release()`? I am working on the assumption that the problem is caused by the way `ImaAdsLoader` updates the ad playback state to have 0 ads when it's released, but if the error is reproducible in an app that doesn't do that then the assumption isn't correct.

**Comment by victorraft** [comment] 2021-03-11 14:34
@andrewlewis Yes, our code has this function:

```    
override fun playItemAtPlaylistIndex(index: Int) {
        releaseAdsLoader()
        releasePlayer()
```

And according to some logs we got this function was the last one that was executed before the crash stacktrace, so I think you migh be onto something here!

Do you think inverting the order of these calls might help? We're looking for a solution that doesn't involve waiting for the next Exo release, so if you could suggest some workaround that's good enough that would be much appreciated! 
Thank you!

**Comment by andrewlewis** [comment] 2021-03-11 14:40
Yes! When the ads loader is released, it removes all cue points from the `AdPlaybackState` and that causes a crash because `AdsMediaSource` tries to access information about cue points that have disappeared. (There could be another cause but I haven't found it yet.)

**Comment by cadalt** [comment] 2021-03-11 14:45
for the record, this must be something new caused by 2.13.0 though, right?
just clarifying because this code where ImaAdsLoader.release() is called before Player.release() has been there for a long time

**Comment by andrewlewis** [comment] 2021-03-11 14:47
> for the record, this must be something new caused by 2.13.0 though, right?

Yes. This probably stopped working in 69dad31b67157ac87679bc6ae24846323f1c18fa, which went into 2.13.0.

**Comment by andrewlewis** [comment] 2021-03-11 14:49
To clarify, I'm planning to fix the bug anyway (at which either ordering should work again), but if you need a quick fix without waiting for an ExoPlayer release or patch then swapping the order of the calls should do it.

**Comment by cadalt** [comment] 2021-03-11 14:50
got it! thank you @andrewlewis !!!

**Comment by victorraft** [comment] 2021-03-11 15:23
@andrewlewis there is another place that we call `releaseAdsLoader` and I just wanted to run it by you and see if this case could also cause issues. 
We call `releaseAdsLoader` when we're going to start a new video and the new one has a different preroll tag than the previous one:
```
    private suspend fun wrapMediaSourceWithAds(context: Context, mediaSource: MediaSource, _prerollTag: String?): MediaSource {
        val adTagUri = Uri.parse(_prerollTag.orEmpty())

        if (adTagUri != loadedAdTagUri) {
            /** HERE! Could this call cause a crash too? **/ 
            releaseAdsLoader()
            loadedAdTagUri = adTagUri
        }
 
        val formattedAdTag = processAdTag(_prerollTag) 

        if (adsLoader == null) {
            adsLoader = createAdsLoader(context)
        }

        val adsLoaderInstance = adsLoader ?: return mediaSource
        adsLoaderInstance.setPlayer(player)

        // Compose the content media source into a new AdsMediaSource with both ads and content.
        val dataSpec = DataSpec(formattedAdTag.asUri())
        val adsMediaSource = AdsMediaSource(mediaSource, dataSpec, dataSpec.uri, this, adsLoaderInstance, adViewProvider)
        adsMediaSource.addEventListener(mainHandler, this)
        return adsMediaSource
    }
```

releasePlayer() is not called in this case, but I just want to be on the safe side.

**Comment by andrewlewis** [comment] 2021-03-12 09:40
@victorraft If the player is prepared with an `AdsMediaSource` already at the moment when this function runs then yes, I would expect it to hit the same issue. The problem is that `AdsMediaSource` doesn't accept the update to the ad playback state called by the `AdsLoader.release()` if any ad groups previously loaded, and the way to work around that is to make sure there is no `AdsMediaSource` at the time of the call. (It's slightly inefficient to release the player as resources will need to be reacquired (unless you are using foreground mode) but I suspect that's okay as a temporary workaround!)

**Comment by ojw28** [comment] 2021-03-30 15:29
@andrewlewis - Is this bug fixed by the commit referenced above? If so, can we mark it as fixed? Thanks!

**Closed as completed** 2021-03-30 15:32 UTC
Labels: bug
