### ISSUE TITLE
Exoplayer is throwing MediaCodecVideoRenderer error on DRM protected DASH content with codec avc1.4d400c

### ISSUE THREAD

**Issue by abhishekpatil26** [google/ExoPlayer#9526] opened 2021-10-04 06:16 UTC
While playing Wide-vine DRM protected DASH content with codec avc1.4d400c, exoplayer is throwing MediaCodecVideoRenderer error and playback fails.

This issue is mostly occurring on particular bit-rates, not on all.

**Error Log :** 

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.4d400c, 100000, null, [320, 180, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc.secure
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:872)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2821)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:75)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1416)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:859)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-09-28 17:02:02.622 com.jio.media.ondemand E/SurfaceUtils: native window cannot handle protected buffers: the consumer should either be a hardware composer or support hardware protection
2021-09-28 17:02:02.724 com.jio.media.ondemand E/PlaybackLogs: playerFailed [eventTime=49.45, mediaPos=45.61, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.4d400c, 100000, null, [320, 180, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc.secure
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:872)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2821)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:75)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1416)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:859)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

What is the cause of the MediaCodec$CodecException:Error? and how it can be resolved?
Please let us know if anything else is required.

- Exoplayer version - 2.12.2 
- OS - Android 11
- Device - LG G8X

**Comment by andrewlewis** [comment] 2021-10-04 09:06
@abhishekpatil26 Please capture a bug report via `adb bugreport` just after reproducing the issue. You can attach it here or email it to dev.exoplayer@gmail.com with subject "Issue #9526" (and update this issue to indicate you've done this).

> `2021-09-28 17:02:02.622 com.jio.media.ondemand E/SurfaceUtils: native window cannot handle protected buffers: the consumer should either be a hardware composer or support hardware protection`

This looks suspicious -- are you outputting to a `SurfaceView`? Can you reproduce this problem in the ExoPlayer demo app?

@icbaker Please could you take a look? Thanks.

**Comment by abhishekpatil26** [comment] 2021-10-07 11:12
Hi @icbaker & @andrewlewis,
Have already sent a mail with complete bugreport, please check and let us know if you need anything else.

**Comment by icbaker** [comment] 2021-10-08 17:05
This looks like a problem coming from the device's widevine implementation (not sure if the top two lines are relevant, but I've included them just in case):
```
10-05 20:17:33.866  1000  8965  8965 E HidlServiceManagement: Service vendor.qti.hardware.seccam@1.0::ISecCam/default must be in VINTF manifest in order to register/get.
10-05 20:17:33.866  1000  8965  8965 E vendor.qti.hardware.seccam@1.0-service-qti: Cannot register ISecCam HAL service
10-05 20:17:33.912 media   846   846 E QCOM-OEMCrypto: Error at trusted_app_decrypt_cenc : 2563
10-05 20:17:33.912 media   846   846 E QCOM-OEMCrypto: TA Result : 1 OEMCryptoResult : 25
10-05 20:17:33.913 media   846   846 I QCOM-OEMCrypto: -----------------------------------------------------------------
10-05 20:17:33.913 media   846   846 I QCOM-OEMCrypto: Error stack trace[7] for TA version 1:75
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: 	 cipher_set_data_input : 314
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: 	 decrypt_blocks : 378
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: 	 decrypt_ctr_block_offset : 875
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: 	 decrypt_ctr : 919
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: 	 decrypt_subsample : 1365
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: 	 process_subsample : 1404
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: 	 i_widevine_session_decrypt_cenc : 1739
10-05 20:17:33.913 media   846   846 I QCOM-OEMCrypto: -----------------------------------------------------------------
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: Error at decrypt_data : 1874
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: Error at _oecc48 : 2320
10-05 20:17:33.913 media   846   846 E QCOM-OEMCrypto: Error at _oecc105 : 3118
10-05 20:17:33.914 media   846   846 E WVCdm   : [crypto_session.cpp(1541):Decrypt] OEMCrypto_DecryptCENC failed: status = 25
10-05 20:17:33.914 media   846   846 E WVCdm   : Decrypt error in session sid25 during a sample with protected data: 1
10-05 20:17:33.914 10613  5470  8511 W MediaCodec: Log queueSecureInputBuffer error: -2147483648
```

@rrfrias could you take a look?

**Comment by abhishekpatil26** [comment] 2021-10-13 08:32
@rrfrias @icbaker any update on the above mentioned issue?
also let me know if you need anything else.

**Comment by rrfrias** [comment] 2021-10-14 06:30
@abhishekpatil26 I would like your permission to share the bugreport with Qualcomm to investigate furthur.

**Comment by abhishekpatil26** [comment] 2021-10-14 13:14
@rrfrias yes, please go ahead and share with them, also do let me know if they require anything else.

**Comment by rrfrias** [comment] 2021-10-15 02:04
Thanks. We are following up with Qualcomm (Internal ref#: 203154116)

**Comment by rrfrias** [comment] 2021-10-16 18:50
Unfortunately this is a known issue with TA version 1.75 and was fixed in 1.79. This should be addressed in an OEM update. There is no suitable way for an app to query the trustzone version to figure what it is running. I can check with LG for an android version/update that it was fixed in. As an alternative it might be better to key off this exception and avoid certain bitrates/encodings. Let us know if you need more information from LG otherwise i will close this in a week.

**Comment by abhishekpatil26** [comment] 2021-10-22 05:51
@rrfrias The issue is not just with the LG devices, there are other manufacturers too, I'll be sharing a list of OEM's and devices with high no. of occurrences here.

**Comment by abhishekpatil26** [comment] 2021-10-22 09:38
@rrfrias 

Here are some more details about the error occurring on our application with list of OEM's and devices, this data is of past 7 days.

**-Decoder failed: OMX.MTK.VIDEO.DECODER.AVC**

Xiaomi Redmi Note 8 Pro
Xiaomi M2003J15SC
vivo vivo 1904
vivo vivo 1901
realme RMX2151
realme RMX2001
OPPO CPH2001
Realme RMX1825
OPPO CPH2179
samsung SM-A315F
samsung SM-A125F
Realme RMX1827
OnePlus DN2101

Total Error Session	176,557
Total Users		47,213
	
**-Decoder failed: OMX.qcom.video.decoder.avc**

Xiaomi	Redmi Note 7 Pro
Xiaomi	Redmi Note 9 Pro
samsung SM-M115F
OnePlus AC2001
OPPO CPH2127
vivo V2029
Realme RMX1851
vivo vivo 1906
OPPO CPH2095
realme RMX1971
realme RMX1921
samsung SM-J810G
OnePlus ONEPLUS A6010
Realme RMX1901

Total Error Session	174,486
Total Users		48,812

**-Decoder failed: OMX.qcom.video.decoder.avc.secure**

Xiaomi	M2101K7AI
Xiaomi	M2101K6P
vivo vivo 1951

Total Error Session	24,605	
Total Users		4,151

**-Decoder failed: OMX.Exynos.avc.dec**

samsung SM-M315F
samsung SM-M215F

Total Error Session	60,515
Total Users		16,215

**-Decoder failed: OMX.sprd.h264.decoder**

realme	RMX3231

Total Error Session	2,636
Total Users		751

**-Decoder failed: OMX.hisi.video.decoder.avc**	

HUAWEI	JSN-L42
HUAWEI	HRY-AL00

Total Error Session	1,670
Total Users		387

**-Decoder failed: c2.android.aac.decoder**

realme	RMX2185
Xiaomi	M2006C3LI

Total Error Session	437
Total Users		388

**Comment by rrfrias** [comment] 2021-10-22 21:07
Can you get us one bugreport each when using mtk and exynos decoders? Do you know if this always reproducible on a given device?

**Comment by abhishekpatil26** [comment] 2021-10-25 06:48
Hi @rrfrias, I got the above data from Firebase Crashlytics portal of our product, so I won't be able to get a complete bugreport for those devices, let me check if I can get a device with MediaTek or Exynos processor. If I got, will share the bugreport on mail or here.

**Comment by abhishekpatil26** [comment] 2021-12-06 12:33
Hi @rrfrias  @icbaker @andrewlewis,

Any update on above mentioned issue?

**Comment by rrfrias** [comment] 2022-01-11 19:18
Hi @abhishekpatil26, the failure cause for a Qualcomm based device will differ from MediaTek or Exynos based devices. The bugreport you shared on October 5th helped us root cause the Qualcomm failure. MediaTek and Samsung will need similar information to investigate and root cause. If analytics captures stack traces of the failure, can you share that with  dev.exoplayer@gmail.com . Add "Issue 9526" to the title. We have added more information in android S, so information from newer device will be more useful.

**Closed as completed** 2022-02-09 02:04 UTC
Labels: bug: in platform drm, closed-by-bot
