### ISSUE TITLE
DefaultBandwidthMeter never unregisters, which can lead to a crash with looped calls.

### ISSUE THREAD

**Issue by MichealReed** [google/ExoPlayer#8625] opened 2021-02-23 18:53 UTC
After continuously looping start/stops for reconnection when a stream goes down or connection is lost, I found a crash. It seems nothing ever unregisters the receiver registered in the code below, which eventually causes exoplayer to fill the android limit of 1,000. It may be worth taking another pass at the other DASH related stuff to ensure receivers are being unregistered.

https://github.com/google/ExoPlayer/blob/8a0d52be4b5402af0987fc7d009bc49977c72b67/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultBandwidthMeter.java#L474

**Comment by Samrobbo** [comment] 2021-02-25 17:59
@tonihei, You've worked on DefaultBandwidthMeter, can you have a look into this?

**Comment by tonihei** [comment] 2021-02-26 09:13
This line is only called once in a static context, so it can't fill any limit up to 1000 as far as I can see. Do you have any signs that this particular receiver is registered more than once?

**Comment by MichealReed** [comment] 2021-02-26 15:34
The issue is with repetitive calls to something in the DASH/streaming feature. If you continually attempt to restart the media in an environment where timeouts are prevalent this will eventually cause a crash as I cannot find anywhere this is formally being unregistered outside of the app being restarted.

**Comment by tonihei** [comment] 2021-02-26 16:37
That doesn't really explain how this can happen. The registration happens once statically, so even if you restart many playbacks in your app, there will never be more than one instance registered. 
If you think there is a bug, please provide us with reproduction steps that show the problem.

**Comment by MichealReed** [comment] 2021-02-26 17:00
Although I am using exoplayer as a part of a flutter plugin, reproduction there should be the same. Start a dash stream (like https://cmafref.akamaized.net/cmaf/live-ull/2006350/akambr/out.mpd), have a loop in the background that monitors buffer status and stops/reloads the stream when nothing new is being added to the buffer. Stopping on connection lost, attempting to reload the source, then attempting to play. Eventually if connection is not regained you will see:

```
Fatal Exception: java.lang.IllegalStateException: Too many receivers, total of 1000,
```

As mentioned originally it may not be DefaultBandwidthMeter, I simply connected the dots to DASH streaming from this. Something is indeed not being unregistered somewhere though.

**Comment by tonihei** [comment] 2021-02-26 17:05
> Although I am using exoplayer as a part of a flutter plugin, reproduction there should be the same.

Given we never received such a report before, it may as well come from the flutter plugin. To investigate this, it would be best if you could try to reproduce in the ExoPlayer demo app. 

> have a loop in the background that monitors buffer status and stops/reloads the stream when nothing new is being added to the buffer. Stopping on connection lost, attempting to reload the source, then attempting to play.

Could you also provide the actual method calls or callbacks for this? Otherwise it's unclear whether trying this out will result the same behavior you are seeing.

**Comment by MichealReed** [comment] 2021-02-26 17:08
Per here -- https://stackoverflow.com/questions/10876015/broadcast-receiver-register-in-manifest-vs-activity am I incorrect to think that even if it is statically registered it should still be unregistered? It seems that once a call is made to register the broadcast receiver it stays intact for the lifecycle of the object or the application and further calls to register will create an additional registration. I am confident that this is not a flutter related crash. In-between development states that will allow further reproduction there, will include a call stack when I get to the point of reproduction again.

edit: and here -- https://stackoverflow.com/questions/23241931/dynamic-registration-vs-static-registration-of-broadcastreceiver

**Comment by MichealReed** [comment] 2021-02-26 17:27
Another possible layer here is that I am using Cronet. OKHttp may be far to slow to ever reproduce this with common usage.

**Comment by tonihei** [comment] 2021-03-01 10:15
I'm afraid we can't really act on a high-level suspicion that *something* in ExoPlayer (or a related library in your app) *somewhere* registers too many receivers. We'd really need a concrete sign (e.g. evidence of repeated registration) that something is wrong in a particular place (e.g. a concrete class) to investigate further. Alternatively, if you want us to investigate ourselves, please provide steps that allow us to reproduce the problem too. This could be updates to the demo app, or a minimal project somewhere else to illustrate your usage pattern and that reproduces the problem.

**Comment by MichealReed** [comment] 2021-03-01 16:20
I pointed you to exactly where in the code there is a registration and not a matching unregistration. My app in this case literally only has an audio player, there is nothing else in my codebase it could be outside of exoplayer. All other receiver registrations seem to clean up after themselves except this one. Blame it on usage or whatever, but it really seems like you're just trying to push this one off at this point.

**Comment by tonihei** [comment] 2021-03-01 17:53
As already mentioned above, the registration you linked is only executed once during the lifetime of the app, because it's assigned to a static variable. So I don't see how you could ever get more than one registration from this line. You should be able to verify this by adding a log line right after the registration and checking in your app whether you can see the log line more than once.

**Comment by ojw28** [comment] 2021-03-02 17:13
> Per here -- https://stackoverflow.com/questions/10876015/broadcast-receiver-register-in-manifest-vs-activity am I incorrect to think that even if it is statically registered it should still be unregistered?

To answer this explicitly: There's no need for us to unregister. It's by design that the code you link to registers a receiver once and keeps it registered until the application process is killed. Doing this should not cause the problem you're seeing.

It seems you have (a) an error indicating that something in your app registers 1000 receivers, and (b) a line of code in ExoPlayer that demonstrably doesn't do this. Removing the bug label because it's likely the problematic registrations are coming from somewhere else.

**Closed as completed** 2021-03-30 01:04 UTC
Labels: closed-by-bot
