### ISSUE TITLE
ExoPlayer cannot handle video/audio track switching on the fly in TS files.

### ISSUE THREAD

**Issue by octopuscard** [google/ExoPlayer#2534] opened 2017-03-06 17:52 UTC
We play our video content in TS files using ExoPlayer.  Every so often we insert commercial ad content (also in TS files) into the stream.  When the track order of our video content and commercial ad content have the same track order, there is no transition problem at all.  However, if the track order is different, we encountered many different problems such as stalling or skipping content.  For example, if video track in track 1 and audio track is in track 2 for our content, the transition to commercial ad is fine if the ad's video track is in track 1 and audio track is in track 2.  If the ad's video track is in track 2 and audio track is in track 1, then the transition is messed up.  It seems that ExoPlayer is expecting track order to be the same once content starts playing.  Is there a work around for this?

**Comment by AquilesCanta** [comment] 2017-03-07 10:54
Please, before going on, read the issue template. 


I will need clarification about what the issue is:

1. Which Exoplayer version are you using?
2. Try to provide the exact steps to reproduce the issue. **We depend on this to help you**. Assuming you are using version 2, are you creating a new media source per TS file? Are you using dinamically altering the files without changing the MediaSource?
3. What does "track order" mean? Are the first packets of each elementary streams arriving in different order? Is the PID order changing? Is the PMT declaration order changing?

Remember that if you don't want to post something publicly, you can send it to dev.exoplayer@gmail.com.

**Comment by octopuscard** [comment] 2017-03-09 00:32
1. We're using ExoPlayer version 1.5.7
2.  Please see (3) below.
3. For track order, I mean the PID order.  For example:
   (a) In one TS file, I have the following:
    Stream #0:0[0x6e]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x6f]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 222 kb/s

  (b) In another TS file, I have 👍 
    Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 177 kb/s
    Stream #0:1[0x101]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc

In the first TS file, the PID is 0x6e and 0x6f for video and audio respectively when the next ts file with PID 0x100 and 0x101 for audio and video respectively.  I don't think it matters what PID values they are, but the order of the PID.  If I play the first TS following by the second TS, ExoPlayer doesn't see the switch of video and audio track.

**Comment by AquilesCanta** [comment] 2017-03-09 10:48
> If the ad's video track is in track 2 and audio track is in track 1, **then the transition is messed up**.

What does this mean?

> ExoPlayer doesn't see the switch of video and audio track

What does this mean?

> many different problems such as stalling or skipping content

Stalling as in buffering? preparing? ready but frozen video? Skipping content is skipping frames or the whole file? This could happen if the first frame is not a key frame in the second file, for example. If the second file plays, at all, then the issue is not related to PIDs. 

Please, try updating to the player to the latest v1 version. Also, there has been a lot of work done on concatenating, ad insertion and playlists in V2. Consider migrating, and you will find proper explicit support for what you are doing.

What I suggest is that you provide enough information to reproduce ourselves. A description of the media is not enough. The code you use for transitioning between one file and the other is also important. You have not provided a bug report either.

**Comment by octopuscard** [comment] 2017-03-09 22:05
We're not able to upgrade to V2 yet.  I will try to explain it again below.

Here I gave an example of using 2 TS files
1. TS-1 : with video in track 1 and audio in track 2
2. TS-2 : with audio in track 1 and video in track 1

After ExoPlayer plays TS-1 and transition to TS-2, ExoPlayer fails to play TS-2. If TS-2 has video and audio in the same order as TS-1, there is no problem in playing TS-2.

The problem seems to be in the readData() method in one of the sample source file e.g. HLSSampleSource.java. The following code is from the method.  When ExoPlayer is transitioned from TS-1 to TS-2, ExoPlayer thinks that the video track has new media format because now we have audio as track 1 and ExoPlayer tries to use the audio format as video format causing a problem in playback.

    MediaFormat mediaFormat = extractor.getMediaFormat(extractorTrack);
    if (mediaFormat != null) {
      if (!mediaFormat.equals(downstreamMediaFormats[track])) {
        formatHolder.format = mediaFormat;
        downstreamMediaFormats[track] = mediaFormat;
        return FORMAT_READ;
      }
      // If mediaFormat and downstreamMediaFormat[track] are equal but different objects then the
      // equality check above will have been expensive, comparing the fields in each format. We
      // update downstreamMediaFormat here so that referential equality can be cheaply established
      // during subsequent calls.
      downstreamMediaFormats[track] = mediaFormat;
    }

**Comment by AquilesCanta** [comment] 2017-03-10 10:13
Before I start looking into this, please provide the media you are playing to dev.exoplayer@gmail.com.

**Comment by octopuscard** [comment] 2017-03-10 21:09
Media files have been sent.

**Comment by AquilesCanta** [comment] 2017-03-13 10:16
You have quoted a snippet from the HLS code. Are these files part of an HLS stream? If yes, I will need a link to the manifest. If not, please provide the code you use to transition from one file to the other.

**Comment by octopuscard** [comment] 2017-03-16 16:41
I'm still waiting for more details of duplicating this bug and will update here once I get more info.

**Comment by ojw28** [comment] 2017-04-27 10:03
Closing due to lack of information.

**Closed as completed by ojw28** 2017-04-27 10:03 UTC
Labels: need more info
