### ISSUE TITLE
Seeking with AesCipherDataSource throws "Searched too many bytes" ParserException

### ISSUE THREAD

**Issue by Mithrandir21** [google/ExoPlayer#3012] opened 2017-07-02 14:24 UTC
**The setup**:
App attempting to open encrypted MP3 audio file from the web for playback without storing full file to disk.

```java
// 1. The DataSource that does the fetching of the (encrypted) mp3 from web
DataSource encryptedStream = new OkHttpDataSource(new OkHttpClient(), getUserAgent(), null);

// 2. The Key and the Cache
final byte[] secretKey = "secretkey";
SimpleCache cache = new SimpleCache(new File(context.getCacheDir() + "/cache"), new NoOpCacheEvictor());
DataSource cacheDataSource = new CacheDataSource(cache, encryptedStream);

// 3. Decrypting DataSource - Uses the key to decrypt the mp3 from cache
DataSource decryptedDataSource = new AesCipherDataSource(secretKey, cacheDataSource);

// 4. Extractor for parsing the decrypted media data.
Extractor[] mp3Extractor = {new Mp3Extractor()};

// 5. This is the MediaSource representing the media to be played.
return new ExtractorMediaSource(trackUri, () -> decryptedDataSource, () -> mp3Extractor, null, null);        

```

**Issue**:
Seeking to a point far away from current position leads to a `ParserException("Searched too many bytes.");` from the Mp3Extractor.

**Explanation**:
If playing unencrypted URI (not using the `AesCipherDataSource`) play and seeking work flawlessly.
**However, when attempting to seek** to a position far away with encrypted mp3, new content does not seem to be read from the upstream (okHttp -> cache -> aescipher -> mp3Extractor), which causes the exception being thrown.

 
Note:
If the same encrypted mp3 file is download directly to the phone and then attempted played with the exact same datasources, both PLAY and SEEKING work as expected.

**Comment by ojw28** [comment] 2017-07-03 10:08
For the note at the bottom, are the data sources really exactly the same in the local case? Specifically, do you still have an `OkHttpDataSource` in the chain, rather than a `FileDataSource` or similar?

If the only difference between it working and not working is having the mp3 hosted on the server, then the most likely reason for failure is that the server just isn't serving the correct data in response to range requests. Can you try hosting the file on a different cloud provider, or similar, to see if the issue reproduces in that case too?

**Comment by Mithrandir21** [comment] 2017-07-03 16:23
@ojw28 Thank you for the quick reply. I was originally using `DefaultUriDataSource`, which gave me a shorter seeking span than with OkHttpDataSource. So for the purposes of fixing the seeking issue, I switched to OkHttpDataSource. When using `DefaultUriDataSource` I could use the same exact code for both web hosted encrypted mp3 and local encrypted mp3.

I will try the hosting the mp3 somewhere else for testing purposes, any suggestion?

I have made some observation regarding what the CacheDataSource does when attempting to seek unencrypted mp3 and encrypted mp3. I will update those observations in a little while.

**Comment by Mithrandir21** [comment] 2017-07-04 10:19
I have attempted the hosting the file somewhere else and I got the same results, seeking not possible.
But the observation I have made about the what the CacheDataSource does might be useful in understanding the issue.

The following steps happen when I seek to a far away point in the encrypted mp3:
1. The `AesCipherDataSource` asks it's upstream DataSource, `CacheDataSource`, for a CacheSpan.
2. `CacheDataSource` checks if it's cache, `SimpleCache`, has the a CacheSpan for that readPosition.
3. Since the `SimpleCache` does not have the content, the `CacheDataSource` asks it's upstream DataSource, the `OkHttpDataSource` to fetch the it.
4. The `OkHttpDataSource` then fetches the range, hands it over to the `SimpleCache`, which then writes it to the its cache.
5. `CacheDataSource` than again runs `read` and when it now asks the `SimpleCache` for a CacheSpan with the data, the `SimpleCache` provides the retrieved cache data. (See line 290 in `CacheDataSource`.)

Until this point, things seem very clear and understandable. But what happens after this that makes seeking not actually happen, that I am unsure of. Because it seems even if though the `openNextSource` of the `CacheDataSource` finds the cached Span and returns true, it repeats the `openNextSource` 2 more times, again finding the cached Span, before giving up the whole endeavour. And at this point, playback stops completely.

**Comment by ojw28** [comment] 2017-07-04 10:30
The "giving up" part is highly likely because the data being read through the chain isn't valid mp3 media (i.e. something's going wrong that causes the data read to be malformed). I think at this point we'll need a link to sample content + the secretKey required to configure an `AesCipherDataSource` to help debug this. Without this information we have no way to reproduce.

**Comment by Mithrandir21** [comment] 2017-07-04 16:02
Here is sample content. The two urls link to the exact the same file, the first unencrypted and the second encrypted.

Unencrypted mp3:
http://streamerv3.nmusic.sapo.pt/6fddb7d788ddcdcca746c5f90d1eda4e/20560166/stream

Encrypted mp3 - Key: 43559861C07D2252
http://streamerv3.nmusic.sapo.pt/f8d75520ae7e9d361acb6d80c14b67bb/20560166/stream

**Comment by ojw28** [comment] 2017-07-04 16:16
I see the same issue as you do. However if I download the stream and host it on cloud.google.com, it works fine in that case. Which implies something is wrong on the serving side.

Note: The cache existing in the chain or not doesn't make any difference to whether this issue reproduces.

**Comment by ojw28** [comment] 2017-07-04 16:32
You can see the problem using curl. Requesting the first 32 bytes:

```
curl -r 0-31 http://streamerv3.nmusic.sapo.pt/f8d75520ae7e9d361acb6d80c14b67bb/20560166/stream | hexdump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    32  100    32    0     0    412      0 --:--:-- --:--:-- --:--:--   415
0000000 30f4 99ed 26c4 bcb8 6a4c d972 c29d 09cd
0000010 e603 e200 0b13 2501 59aa 3946 8a54 d9e2
```

Requesting 16 bytes starting 16 bytes in:

```
curl -r 16-31 http://streamerv3.nmusic.sapo.pt/f8d75520ae7e9d361acb6d80c14b67bb/20560166/stream | hexdump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    16  100    16    0     0    209      0 --:--:-- --:--:-- --:--:--   210
0000000 56bd 9dde 75c4 d1cd 7437 f549 f3b4 5ced
```

If I download the stream and upload it to cloud storage, and then make the same request to that server:

```
curl -r 16-31 https://storage.googleapis.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxx | hexdump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    16  100    16    0     0     77      0 --:--:-- --:--:-- --:--:--    77
0000000 e603 e200 0b13 2501 59aa 3946 8a54 d9e2
```

For things to work correctly, the bytes returned in the "16 bytes starting 16 bytes in" case should match the second half of the "32 bytes starting 0 bytes in" case. This is true when hosted on cloud storage, but apparently not when hosted on streamerv3.

Is it possible that the streamerv3 server is encrypting on-the-fly, and is not correctly accounting for the requested range offset when it does this? Closing in any case, since this is a server-side issue.

**Closed as completed by ojw28** 2017-07-04 16:32 UTC
Labels: wont fix: infeasible

**Comment by Mithrandir21** [comment] 2017-07-04 17:41
@ojw28 Thank you for such a quick and thorough assessment of the issue. I agree with your conclusion and hope that this post will help anyone having similar issues in the future.
