### ISSUE TITLE
attempting to play stream fails

### ISSUE THREAD

**Issue by kartajan** [google/ExoPlayer#1309] opened 2016-02-24 21:41 UTC
I have been attempting to play a live stream into a "Live Channels" setup, but exoplayer is not playing the stream. I need to know why it doesn't play/ what I can do to fix it.
I have attached a 10 second dump of the stream captured via VLC
[dump.zip](https://github.com/google/ExoPlayer/files/145459/dump.zip)

**Comment by ojw28** [comment] 2016-02-25 10:27
The dump plays fine for me using the latest release (1.5.6). Closing because I cannot reproduce, and because you haven't provided sufficient information as requested in the issue template. Please file an issue containing all of the requested information.

**Closed by ojw28** 2016-02-25 10:27 UTC
