### ISSUE TITLE
Crash when changing audio track on high bitrate video streams

### ISSUE THREAD

**Issue by ProtoScott** [google/ExoPlayer#9223] opened 2021-07-23 16:41 UTC
- Search existing issues, including issues that are closed:
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
**Done**
- Consult our developer website: https://exoplayer.dev/
 **Done**
- Check the supported formats: https://exoplayer.dev/supported-formats.html
**Done**
- Try playing problematic media in the demo app:
  http://exoplayer.dev/demo-application.html
**Done**

Issue:
When switching audio streams when playing a high bitrate video stream the app throws the exception:

Steps to reproduce:
1. Play video content at >24mbps with multiple audio
2. Switch between audios (you may need to switch more than once)
3. Observe Exception: Playback stuck buffering and not loading

Stacktrace:
```
07-15 14:16:06.935 10195 10882 W DefaultLoadControl: Target buffer size reached with less than 500ms of buffered media data.
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal: Playback error
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:587)
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:193)
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:65)
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1013)
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
07-15 14:16:06.939 10195 10882 E ExoPlayerImplInternal:       ... 3 more
```

- ExoPlayer version: 2.12+
- Android version: 10
- Bravia VH2 (2021 Sony TV)

When ran tests the same tests on 2.11.8 and below and could not reproduce the issue.

"Workaround"
Switch from 40mbps -> 4mbps, change audio, switch back up to 40mbps.

We have content available for testing but it's DRM protected, if anyone wants to investigate the issue I can supply a link on request (they are time limited links).

**Comment by christosts** [comment] 2021-07-26 16:07
The warning log right above the stack-trace basically says the buffer is full and cannot fill with anymore data although less than 500ms of data (I assume audio) have been buffered which is to little to start playback, therefore the player detects it is stuck (as expected? let's see). By default, the player's buffer is around ~12MB~ 120MB (see ~[DEFAULT_MIN_BUFFER_SIZE](https://github.com/google/ExoPlayer/blob/80332f7f1be7f0ea59440b4888560d228f405789/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L95)~ [DEFAULT_VIDEO_BUFFER_SIZE](https://github.com/google/ExoPlayer/blob/80332f7f1be7f0ea59440b4888560d228f405789/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L73)). Let's do two things.

First, can you send us a link to the content via email at dev.exoplayer@gmail.com with the subject "Issue #9223"? I'd like to test and repro to see if there's any bug in the player, or it just happens that the player's default buffer values are too small to handle this content's high bit rates. 

Second, how to address this with the existing APIs. I am assuming you are using the player with its default load control, therefore can you try to customize the player's load control? Create the player with a custom `DefaultLoadControl` that either has a buffer with size bigger that the default, or it has the `prioritizeTimeOverSizeThresholds` flag enabled. Here's a snippet that does both

```
SimpleExoPlayer player = new SimpleExoPlayer.Builder(context)
              .setLoadControl(new DefaultLoadControl.Builder()
                  .setTargetBufferBytes(xxx)
                  .setPrioritizeTimeOverSizeThresholds(true)                  
                  .build())
              .build();
```

Calling `setPrioritizeTimeOverSizeThresholds(true)` will make the player to continue buffering until the minimum amount of data is buffered, measured is duration (default is 50s). This will ignore any size constraints. There is a risk that this might make the player's buffer grow too much, especially high bit rate content (and if it turns our there is a bug). Calling `setTargetBufferBytes()` will increase the buffer max size. ~If the video stream is encoded at 40Mbps, I can see how 12MB can be filled with only ~3 seconds of video.  I guess you can safely increase that to 100MB.~

(**Edited**: fixed incorrect references to default buffer size)

**Comment by ProtoScott** [comment] 2021-07-26 16:39
So that sounds about right based on what you've said.

We have already changed `setPrioritizeTimeOverSizeThresholds` to true, this then gave us the "out of memory" exceptions, we lowered the available buffer from 50 seconds to 25 seconds which overcame that problem.

I'll try see what happens if we set `setTargetBufferBytes` and get back to you.

**Comment by ProtoScott** [comment] 2021-07-26 20:48
Setting setPrioritizeTimeOverSizeThresholds to true, and lowering the stored buffer to 25s instead of 50s works (not ideal but it works).

Setting the targetBufferBytes to 100MB still causes the `Playback stuck buffering and not loading`

**Comment by christosts** [comment] 2021-07-27 14:07
I have received the test content (thanks!) but I think the license expired already, so I have not reproduced with your content yet.

I did notice that the content has tracks that go up to 80mbps. To be able to buffer 50s (50s picked up because it's the default duration) of video encoded at 80mbps, the buffer should be at least 500MB. I'm assuming that, since you're attempting to play such high content (you mentioned you're testing with 40mbps), the TV should have enough RAM so that you can increase the ~target buffer beyond 100MB.~ default target buffer.

I intend to debug to see if video is leaving no space for audio, however, I think at the moment you need to tune the load control's buffer duration and target size accordingly. You have already lower the buffer duration, but you'd beed to increase the size too, depending on the highest bitrate track of your content. If the device hardware cannot accommodate buffers of this size (I mentioned above 500MB), you might have to also consider dropping these high bit rate tracks and restrict playback to lower bitrates. By that, I mean adding some logic to cap the maximum bitrate - please the [related documentation](https://exoplayer.dev/track-selection.html).

(**Edited**: corrected reference to target buffer, since by default it's 120MB)

**Comment by christosts** [comment] 2021-07-29 15:19
Correction: I made mistake in my [first response](https://github.com/google/ExoPlayer/issues/9223#issuecomment-886833907) that by default the buffer size is 12MB, the correct is 120MB. For 40mbits video, 120MB should accommodate ~24 seconds of video. The rest of my responses remain: please try to increase the target byte buffer to 200-300MB and/or reduce the target duration.

**Closed as completed** 2021-08-27 01:04 UTC
Labels: closed-by-bot
