### ISSUE TITLE
Forward and Rewind not working for flv format videos.

### ISSUE THREAD

**Issue by HaiderSaleem** [google/ExoPlayer#6190] opened 2019-07-16 14:20 UTC
I have videos uploaded on server and passing the link to exoplayer to play, its playing videos but i'm not able to forward or rewind it or seek to a specific time tho its working perfectly with other formats.
Attached url of source video.

[https://media.mec.edu.om/Folders/Digital%20Logic%20Design/Logic%20Gate.flv](url)

**Comment by ojw28** [comment] 2019-07-16 14:22
Duplicate of https://github.com/google/ExoPlayer/issues/3251

**Closed as completed by ojw28** 2019-07-16 14:22 UTC
Labels: duplicate

**Comment by HaiderSaleem** [comment] 2019-07-16 14:31
It was asked in 2017 and now its 2019, isnt there any implementation made till yet?
That server doesn't support .mp4, so we now converting .wmv to .flv and now this issue has come.
any suggestion?

**Comment by HaiderSaleem** [comment] 2019-07-16 14:34
> I have videos uploaded on server and passing the link to exoplayer to play, its playing videos but i'm not able to forward or rewind it or seek to a specific time tho its working perfectly with other formats.
> Attached url of source video.
> 
> [https://media.mec.edu.om/Folders/Digital%20Logic%20Design/Logic%20Gate.flv](url)

It was asked in 2017 and now its 2019, isnt there any implementation made till yet?
That server doesn't support .mp4, so we now converting .wmv to .flv and now this issue has come.
any suggestion?

**Comment by ojw28** [comment] 2019-07-16 14:40
Pretty much any web server will support mp4, so I'm unclear what it means for a server to not support it. My suggestion would be to use mp4. Also, it's explained on the duplicate issue why this is a low priority issue for us, and that if support is added it'll likely be in the form of an external contribution.

**Comment by HaiderSaleem** [comment] 2019-07-16 14:44
You mentioned there via rtmp but its from http.

**Comment by ojw28** [comment] 2019-07-16 14:48
Most of the comment in that issue relates to what the issue is tracking. I.e. "Support seeking in FLV (including if delivered using rtmp)". I've adjusted the comment there to start a new paragraph to make it clearer.

If you could explain what it means for an http server to not support mp4, that would be helpful to understand. An mp4 file is just a regular file. If a web server can serve any file, then I don't see why it wouldn't be able to serve an mp4 file.

**Comment by HaiderSaleem** [comment] 2019-07-16 15:10
idk why, but client has tested by uploading .mp4 and later hitting the url, found 404.

**Comment by ojw28** [comment] 2019-07-16 15:16
I think they're most likely just doing something wrong, and you or they should figure out how to fix that. I don't think there's anything special about hosting an mp4 file vs any other type of file.

**Comment by HaiderSaleem** [comment] 2019-07-17 15:35
> I think they're most likely just doing something wrong, and you or they should figure out how to fix that. I don't think there's anything special about hosting an mp4 file vs any other type of file.

yeah, we have fixes it by allowing .mp4 files on their server, thanks.
