### ISSUE TITLE
mp4 video with audio stream type mp3 is played without sound

### ISSUE THREAD

**Issue by metalurgus** [google/ExoPlayer#1694] opened 2016-07-23 16:23 UTC
the video info, retrived using `ffprobe`:

```
[STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=High
codec_type=video
codec_time_base=1/50
codec_tag_string=avc1
codec_tag=0x31637661
width=704
height=544
coded_width=704
coded_height=544
has_b_frames=2
sample_aspect_ratio=34:33
display_aspect_ratio=4:3
pix_fmt=yuv420p
level=30
color_range=N/A
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
timecode=N/A
refs=1
is_avc=true
nal_length_size=4
id=N/A
r_frame_rate=25/1
avg_frame_rate=25/1
time_base=1/12800
start_pts=0
start_time=0.000000
duration_ts=37680128
duration=2943.760000
bit_rate=1713055
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=73594
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=eng
TAG:handler_name=DataHandler
TAG:encoder=libx264
[/STREAM]
[STREAM]
index=1
codec_name=mp3
codec_long_name=MP3 (MPEG audio layer 3)
profile=unknown
codec_type=audio
codec_time_base=1/48000
codec_tag_string=.mp3
codec_tag=0x33706d2e
sample_fmt=s16p
sample_rate=48000
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/48000
start_pts=0
start_time=0.000000
duration_ts=141282432
duration=2943.384000
bit_rate=192000
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=122641
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=eng
TAG:handler_name=DataHandler
[/STREAM]
[FORMAT]
filename=C:\Users\Vlad\Downloads\╨Т╨╕╨┤╨╡╨╛\5f387ac8b35310be0b24ac276ca821b7.mp4
nb_streams=2
nb_programs=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0.000000
duration=2943.760000
size=703042708
bit_rate=1910597
probe_score=100
TAG:major_brand=qt
TAG:minor_version=512
TAG:compatible_brands=qt
TAG:encoder=Lavf55.19.104
[/FORMAT]
```

Here is the video info of the file with AAC sound stream, which works OK:

```
[STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=High
codec_type=video
codec_time_base=1001/48000
codec_tag_string=avc1
codec_tag=0x31637661
width=1280
height=718
coded_width=1280
coded_height=718
has_b_frames=2
sample_aspect_ratio=1:1
display_aspect_ratio=640:359
pix_fmt=yuv420p
level=31
color_range=N/A
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
timecode=N/A
refs=1
is_avc=true
nal_length_size=4
id=N/A
r_frame_rate=24000/1001
avg_frame_rate=24000/1001
time_base=1/24000
start_pts=0
start_time=0.000000
duration_ts=62087025
duration=2586.959375
bit_rate=1760057
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=62025
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=eng
TAG:handler_name=DataHandler
TAG:encoder=libx264
[/STREAM]
[STREAM]
index=1
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_time_base=1/48000
codec_tag_string=mp4a
codec_tag=0x6134706d
sample_fmt=fltp
sample_rate=48000
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/48000
start_pts=0
start_time=0.000000
duration_ts=124174336
duration=2586.965333
bit_rate=165399
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=121264
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=rus
TAG:handler_name=DataHandler
[/STREAM]
[FORMAT]
filename=C:\Users\Vlad\Downloads\╨Т╨╕╨┤╨╡╨╛\08f4d03dd55dfbeb62aa2a7a51a2f63c.mp4
nb_streams=2
nb_programs=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0.000000
duration=2586.966000
size=624371238
bit_rate=1930821
probe_score=100
TAG:major_brand=qt
TAG:minor_version=512
TAG:compatible_brands=qt
TAG:encoder=Lavf55.19.104
[/FORMAT]
```

Here is the [link to my question](http://stackoverflow.com/questions/38543780/exoplayer-no-sound-on-video-with-mp3-sound-stream) on StackOverflow

**Comment by ojw28** [comment] 2016-07-24 23:14
We'd be happy to take a look at this if you provide a test stream for us to reproduce the issue with. Please provide one if you wish for us to do so (either here or by email to dev.exoplayer@gmail.com)

**Comment by ojw28** [comment] 2016-07-28 19:52
Are you able to provide test content, or shall we close this? Thanks!

**Comment by metalurgus** [comment] 2016-07-28 20:40
Sorry for the delay, I wull provide a sample video com w morning my time (in 10 hours aprox)

**Comment by ojw28** [comment] 2016-08-02 15:48
Closing due to lack of sample.

**Closed as completed by ojw28** 2016-08-02 15:48 UTC
Labels: need more info
