### ISSUE TITLE
DefaultDrmSessionManager and OfflineLicenseHelper does a DRM leak

### ISSUE THREAD

**Issue by sharish** [google/ExoPlayer#6140] opened 2019-07-08 11:59 UTC
This is more of a code review than an issue where `FrameworkMediaDrm` getting initialized through static factory methods  does not have a way to release the MediaDrm. 

https://github.com/google/ExoPlayer/blob/1ab402cf27ab3c52d671ef15b25a1cdde1fe84c8/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.java#L161

https://github.com/google/ExoPlayer/blob/1ab402cf27ab3c52d671ef15b25a1cdde1fe84c8/library/core/src/main/java/com/google/android/exoplayer2/drm/OfflineLicenseHelper.java#L104

Initializing too many `DefaultSessionManager|OfflineLicenseHelper`  this way end up throwing the following exception. Once this failure happen, any media from any application dependent on DRM fails to play the video. It's hard to figure out which application caused this DRM leak as well. 

```
android.media.MediaCodec$CodecException: Error 0x80000000
at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2752)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1427)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:654)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:209)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by ojw28** [comment] 2019-07-08 12:01
Duplicate of https://github.com/google/ExoPlayer/issues/4721

**Closed as completed by ojw28** 2019-07-08 12:01 UTC
Labels: duplicate
