### ISSUE TITLE
Next button in notification not visible even adding the setUseNextAction true

### ISSUE THREAD

**Issue by YogeshSinghPathania** [google/ExoPlayer#10938] opened 2023-01-20 16:04 UTC
### ExoPlayer Version

2.14.2

### Devices that reproduce the issue

 Hi im facing the issue in Exoplayer Notification.  Right Button is not showing. I also enable the property true for right button but its not working. Please let me know if this is version issue or anything else.
 
Device-  Pixel 5 Api 30

### Devices that do not reproduce the issue

Device-  Pixel 5 Api 30

### Reproducible in the demo app?

Yes

### Reproduction steps

Play the song and than lock the device and than you will see right button is not showing

### Expected result

Right Button have to visible

### Actual result

Right button not visible

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment] 2023-01-20 21:19
Maybe similar to #9268

**Comment by YogeshSinghPathania** [comment] 2023-01-22 06:50
I already checked #9268 but i did not find any solution and also this issue is Closed due to inactivity.

.

**Comment by marcbaechinger** [comment] 2023-01-30 19:01
Closing as duplicate of #10952. Please see my comment regarding behaviour changes in Android 13 there.

**Closed as completed by marcbaechinger** 2023-01-30 19:01 UTC
Labels: question
