### ISSUE TITLE
Live DASH video track selection broken since 2.13.0

### ISSUE THREAD

**Issue by cdongieux** [google/ExoPlayer#8847] opened 2021-04-21 17:10 UTC
I'm currently updating my app from ExoPlayer 2.12.1 to 2.13.3, I notice the video track selection on Live DASH streams seems broken since 2.13.0.

Here are available video tracks:
```
MediaCodecVideoRenderer [
  Group:0, adaptive_supported=YES_NOT_SEAMLESS [
    [X] Track:0, id=379, mimeType=video/avc, bitrate=400000, codecs=avc1.64000d, res=384x216, fps=25.0, supported=YES
    [X] Track:1, id=380, mimeType=video/avc, bitrate=800000, codecs=avc1.64001e, res=640x360, fps=25.0, supported=YES
    [X] Track:2, id=381, mimeType=video/avc, bitrate=1600000, codecs=avc1.64001f, res=896x504, fps=25.0, supported=YES
    [X] Track:3, id=3517, mimeType=video/hevc, bitrate=1600000, codecs=hvc1.1.2.L93, res=896x504, fps=50.0, supported=YES
    [X] Track:4, id=382, mimeType=video/avc, bitrate=3000000, codecs=avc1.64001f, res=1280x720, fps=25.0, supported=YES
    [X] Track:5, id=3518, mimeType=video/hevc, bitrate=4800000, codecs=hvc1.1.2.L123, res=1920x1080, fps=50.0, supported=YES
    [X] Track:6, id=3519, mimeType=video/hevc, bitrate=14800000, codecs=hvc1.1.2.L123, res=1920x1080, fps=50.0, supported=YES
  ]
]
```

Here is what was ExoPlayer behavior in 2.12.1 and what it's now:

**2.12.1:**
1. track 896x504 (1600000bps, video/avc) is selected
2. track 1920x1080 (14800000bps, video/hevc) is selected
=> that's the expected behavior

**2.13.3:**
1. track 896x504 (1600000bps, video/avc) is selected
2. track 1920x1080 (14800000bps, video/hevc) is selected
3. track 384x216 (400000bps, video/avc) is selected
=> this behavior is not expected

In 2.13.3, few seconds after step 2. the bandwidth estimation drops and the lowest bitrate track is selected, a higher quality seems to never be selected.

As stream URL and DRM info are sensitive, I'll provide you by email a sample code hosted on a private GitHub repository to help you reproduce the issue. Please let me know if you need anything else.

**Comment by tonihei** [comment] 2021-04-23 13:20
There are two separate issues here that cause the behavior you are seeing:

1. The manifest defines media segments with a `SegmentTimeline`. The last defined segment ends in the future relative the current time retrieved from the `UTCTiming` element. The manifest itself looks consistent (e.g. if you calculate the last segment end time, it's slightly less than the `publishTime`), but the problem seems the be that the `publishTime` itself (and thus the last defined segment) is always ~10 seconds in the future. The player is using the `UTCTiming` element to get the server time and thus thinks the last segment ends in the future.
    - The relevance of all this is that ExoPlayer 2.13 added support for low-latency streaming and segments ending in the future are by definition not fully available yet and can't be used for bandwidth estimation. That's why the `BandwidthMeter` is ignoring all media segments loads for bandwidth estimation. 
    - In theory, the player should ignore such segments in `SegmentTimeline` if they are not explicitly marked as low-latency segments (with `availabilityTimeOffset`), but so far no one used `SegmentTimelines` to deliberately publish future segments [internal ref: b/172894901]. Given the `publishTime` discrepancy it also looks more like a media issue in this case.

2. The second issue is a code setup issue. By default, ExoPlayer is only using actual media segments for bandwidth estimation to ignore smaller independent loads like DRM key requests or manifests as they tend to produce largely underestimated bandwidth estimates. So while the problem described in (1) exists, no new measurements should happen at all (as they are all ignored) and the player should at least stay at its current format selection. 
     - However, your code passes in the global singleton `BandwidthMeter` as a `TransferListener` to your `DataSource`. This means the `BandwidthMeter` suddenly measures bandwidth for all loads, including DRM key requests and manifest refreshes. These smaller transfers largely underestimate the bandwidth and cause the estimate to drop down. Thus the player started selecting lower quality formats. Note that this is only an issue because the much larger media segment loads are ignored at the same time for the reason described above.
     - So you should just make sure to not add the `BandwidthMeter` as a `TransferLister` to your `DataSources`.

Solving the second issue prevented the issue already as no new measurements happened and the player just stayed on the previously selected format. However, I think you should also look into issue 1 to make sure the player doesn't treat these segment as low-latency segments.

**Comment by cdongieux** [comment] 2021-04-23 15:40
Thank you Toni for your feedback.

Removing BandwidthMeter from my DataSources did the trick, thank you.
But in the case where the network bandwidth fluctuates I guess track
selection will not be fully effective (or not at all) until point 1 is
fixed because bandwidth measurements don't happen ; am I correct?

**Comment by tonihei** [comment] 2021-04-23 15:51
>  I guess track selection will not be fully effective (or not at all) until point 1 is fixed because bandwidth measurements don't happen ; am I correct?

That's correct, yes.  If you discover that you actually need the player to ignore segments that end in the future, we could re-purpose this issue as a feature request. But given the time difference between the actual manifest request time and the `publishTime` value it seems more likely the problem is related to the manifest creation.

**Comment by cdongieux** [comment] 2021-04-30 13:38
Hi Toni,

Sorry for the late reply.
I reported what you said to our streams production team, according to them
this wrong publishTime value is caused by the source stream clock slowly
drifting, so fixing this bug on our side does not seem that simple.
In the meantime, as ExoPlayer behavior changed between version 2.12.X and
2.13.X with the same DASH manifest "profile" (meaning with this manifest
publishTime bug), I would like to re-purpose this issue as a feature
request.

I dig a little bit in ExoPlayer sources and I'm ready to submit a patch to
tackle this issue. So how do you want me to proceed? Do you prefer I give
you this patch directly for you to have a look at it and tell me if I'm on
the right way? Or do you prefer I submit a PR on GitHub?

Best regards,
Christophe

**Comment by tonihei** [comment] 2021-05-04 12:45
Thanks for going ahead and creating #8894. I just had a quick look and I think it may solve your issue but isn't really the right thing to do. The primary time source for the player is the `UTCTiming` element and we shouldn't just override it by the `publishTime` in this one location. So whatever counts as "current time" needs to come from the `UTCTiming` element only. Note that the underlying problem is not only the wrong `publishTime` (I only used this as an easily observable signal), but mainly that the segments defined in the `SegmentTimeline` also stretch into the future. So a player shouldn't treat them as available (and they might actually not be available in reality). 

The proper fix to this problem would be to update `MultiSegmentBase.getAvailableSegmentCount/getNextSegmentAvailableTimeUs` and similar methods to not treat segments in the future as being available. In addition, there are other places that need to be updated (like `DashMediaSource` to actually check these methods) because right now we use the `DashSegmentIndex.isExplicit` flag as an indicator whether some segment may be unavailable. That's why it's at least a medium-size change that isn't trivial. 

Another short-term fix that would also address your problem is to disable the check for `isSegmentAvailableAtFullNetworkSpeed` when we assume that all segments should always be available (i.e. right now, when `isExplicit` is false, because we don't support this part of the spec). So when we get around to do the proper fix, this is just one more place that needs to be updated to remove this check again. Does that make sense? Maybe you can update your PR accordingly?

**Comment by cdongieux** [comment] 2021-05-06 14:35
> Note that the underlying problem is not only the wrong publishTime [...], but mainly that the segments defined in the SegmentTimeline also stretch into the future. So a player shouldn't treat them as available.

In my specific case the clock used to both define `publishTime` and segments timestamps is inaccurate and is slightly drifting, this is why it's about 10 seconds in the future. **But in facts all segments are indeed available**. This why in my PR `isSegmentAvailableAtFullNetworkSpeed` is checking if `segmentEndTimeUs <= manifestPublishTimeUs` which is always true, so a segment is always available at full network speed. By saying this check "isn't really the right thing to do" do you mean this is incorrect?

I try to figure out the tweaks you're proposing about `isExplicit` for both the proper fix and the short-term fix but I don't see how this would help in my specific case. In my understanding declaring the last segment as unavailable to avoid calling `isSegmentAvailableAtFullNetworkSpeed` would be wrong because the segment is actually available, and I'm not sure setting the last segment index 's `isExplicit` to `false` would be correct either.

**Comment by tonihei** [comment] 2021-05-06 15:02
The fix I was proposing is to do something like this (pseudo-code):
```
isSegmentAvailableAtFullNetworkSpeed() {
  if (index.isExplicit()) {
    // We don't support segment availability for explicit indices. So also assume they are available at full speed in all cases.
    return true;
  }
  ...
}
```

> By saying this check "isn't really the right thing to do" do you mean this is incorrect?

Yes, because the DASH specification clearly says that all segments whose end time are in the future should not be treated as available (see https://dashif-documents.azurewebsites.net/Guidelines-TimingModel/master/Guidelines-TimingModel.html#timing-availability). The fact that your specific segments are indeed available doesn't really matter because we can't be sure this is the case for all manifests.

**Comment by cdongieux** [comment] 2021-05-06 17:16
Alright, thanks a lot for the clarification. I updated the PR accordingly :)

**Comment by tonihei** [comment] 2021-05-20 10:34
PR was merged, and the slightly malformed stream here plays fine again. So closing this issue.

**Closed as completed by tonihei** 2021-05-20 10:34 UTC
Labels: wont fix: app issue
