### ISSUE TITLE
Ad frame removal 

### ISSUE THREAD

**Issue by jayachandrak** [google/ExoPlayer#3221] opened 2017-08-30 11:02 UTC
![image](https://user-images.githubusercontent.com/1639425/29869321-242cb6e6-8da0-11e7-9acc-8dd403d5f208.png)

Ad frame is still visible even after ad completion and content is in loading state so i would like to show either black screen or artwork in background 

Please suggest what can be done this also applicable for both pre roll and mid roll 

Thanks

**Comment by jayachandrak** [comment] 2017-09-05 07:45
@andrewlewis You want me to write down reproducible steps. i am waiting for your suggestion on the same

**Comment by andrewlewis** [comment] 2017-09-05 08:10
Yes, please provide steps to reproduce in the demo app, including the media and ad tag URIs.

**Comment by jayachandrak** [comment] 2017-09-08 04:27
### Reproduction steps
Create ImaMediasource with below data and check after finishing of ad we can still see the ad frame 

### Link to test content
sample ad tag:
missing url after comment use any of ad url
content url:
http://www.sample-videos.com/video/mp4/720/big_buck_bunny_72p_1mb.mp4

### Version of ExoPlayer being used
2.5.1

### Device(s) and version(s) of Android being used
nexus 9 android 7.0

**Comment by ojw28** [comment] 2017-09-12 16:19
Does this issue only occur if there's buffering between the ad and the content? Which is not normally what happens, since we start to pre-buffer the content prior to the ad finishing. I think it's working as intended that the last frame of the ad remains visible in this case.

**Comment by ojw28** [comment] 2017-09-18 17:46
Closing because I think this is working as intended, as because no further information has been provided.

**Closed as completed** 2017-09-18 17:45 UTC
Labels: need more info
