### ISSUE TITLE
Exoplayer version 2.18.3 got error mix androidx and old support

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#11023] opened 2023-02-27 09:15 UTC
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

Hi when i do complaining i got this error : exoplayer-ui-2.18.3.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

How to fix it?

### Devices that do not reproduce the issue

Android tv emulator

### Reproducible in the demo app?

Yes

### Reproduction steps

install with latest version then do run install. You will see error in the log gradlew install.

### Expected result

-The error should be remove like in 2.18.2 no problem

### Actual result

Error come like about.

### Media

You can see the error log give above for you reference

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment] 2023-02-27 13:53
Thank you for reporting. Can you please share with us a [minimal reproducible project](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem? I can't reproduce it locally, so there's could be something that we missed.

**Comment by icbaker** [comment] 2023-02-28 09:51
Duplicate of https://github.com/google/ExoPlayer/issues/8580

**Closed as completed by icbaker** 2023-02-28 09:51 UTC
Labels: duplicate
