### ISSUE TITLE
Random UnrecognizedInputFormatException

### ISSUE THREAD

**Issue by dorinsimina** [google/ExoPlayer#3484] opened 2017-11-20 18:59 UTC
By using the http://listen.untold.com stream url from time to time I get the below response:

> 11-20 20:41:37.154 8016-8144/org.y20k.transistor E/ExoPlayerImplInternal: Source error.
                                                                          com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:776)
                                                                              at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:699)
                                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)
11-20 20:41:37.154 8016-8016/org.y20k.transistor E/PlayerService: An error occurred. Type SOURCE: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.

There does not seem to be a clear scenario to reproduce the issue. Does anyone know what might cause it? Is the URL bad formatted?

After successive trying to play/pause eventually it starts working and the issue disappears.

**Comment by andrewlewis** [comment] 2017-11-21 08:26
This is an MP3 live stream. It looks like the format of media received from the URL does not match the structure that `Mp3Extractor` expects, occasionally. To diagnose this, we'd ideally need a sample of media that consistently reproduces the issue.

Please could you give a bit more detail about how easy to reproduce this is? For example, do you see the error if you repeatedly start playing the URL for two minutes? Thanks.

**Comment by ojw28** [comment] 2017-12-04 18:31
Closing due to lack of information.

**Closed as completed by ojw28** 2017-12-04 18:31 UTC
Labels: need more info
