### ISSUE TITLE
Manual range request for Fast forward: An exception occurred

### ISSUE THREAD

**Issue by Sidnio** [google/ExoPlayer#11150] opened 2023-05-04 12:18 UTC
`dataSource.setRequestProperty("Range", "bytes=26-110915379")`

```
Playback error
com.google.android.exoplayer2.ExoPlaybackException: Source error
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:614)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Invalid NAL length
    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:641)
    at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:259)
    at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
    at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
```

![image](https://user-images.githubusercontent.com/33193340/236200017-b3d6d472-6817-4057-8b8e-e7fccef081ae.png)

![image](https://user-images.githubusercontent.com/33193340/236200240-2afa4e53-ba9c-42f7-b1d5-698843b43f4e.png)

**Comment by marcbaechinger** [comment] 2023-05-04 12:44
I understand you are doing a range request and it seems that the extractor isn't aware of that. Generally I'd think that the player is doing the range requests internally. From what I understand I'd say an app shouldn't set range requests for fast forwarding but instead use `player.seekTo(positionMs)` to achieve this.

Can you add a question to the issue or change it to a bug? If you do latter, can you elaborate a bit on what you are trying to achieve and what the expected behavior would be?

**Comment by Sidnio** [comment] 2023-05-04 14:20
I am custom format mp4 array is at the beginning of type index 26

**Comment by marcbaechinger** [comment] 2023-05-04 14:41
Then you would need to have an `MP4Extractor` that is understanding this custom format and request the data accordingly I think. I don't think you can fix this by silently requesting data starting from a different byte.

**Comment by Sidnio** [comment] 2023-05-04 14:49
What I wrote above, it's playable, but there's no way to fast forward

**Comment by Sidnio** [comment] 2023-05-04 14:53
In the request header, the bytes specified in the request can be played, but an exception occurs when the request is fast-forwarded

**Comment by icbaker** [comment] 2023-05-04 15:40
I suspect the reason you see a problem when seeking forward is that when you say "seek to Xms in the stream" the `Mp4Extractor` works out that needs to be a byte offset of Y **in the MP4 file**, and asks the `DataSource` to re-open starting at Y - but in your stream it actually needs to be Y+26. Then the `Mp4Extractor` gets upset because it doesn't read the data it's expecting.

You can probably use `ResolvingDataSource` to always increase the `DataSpec.position` by 26 (or set it to 26 if it's not set). This means when the stream is initially opened the read will start at byte 26. Then when the `Mp4Extractor` asks to read byte Y of the MP4 file the `DataSource` will open the underlying stream at Y+26. See more info about `ResolvingDataSource` here: https://developer.android.com/guide/topics/media/exoplayer/customization#customizing_server_interactions

**Comment by Sidnio** [comment] 2023-05-05 00:51
> 



> I suspect the reason you see a problem when seeking forward is that when you say "seek to Xms in the stream" the `Mp4Extractor` works out that needs to be a byte offset of Y **in the MP4 file**, and asks the `DataSource` to re-open starting at Y - but in your stream it actually needs to be Y+26. Then the `Mp4Extractor` gets upset because it doesn't read the data it's expecting.
> 
> You can probably use `ResolvingDataSource` to always increase the `DataSpec.position` by 26 (or set it to 26 if it's not set). This means when the stream is initially opened the read will start at byte 26. Then when the `Mp4Extractor` asks to read byte Y of the MP4 file the `DataSource` will open the underlying stream at Y+26. See more info about `ResolvingDataSource` here: https://developer.android.com/guide/topics/media/exoplayer/customization#customizing_server_interactions



I don't know how you said it should be done

**Comment by icbaker** [comment] 2023-06-09 10:04
Closing because a solution has been provided.

**Closed as completed by icbaker** 2023-06-09 10:04 UTC
Labels: question
