### ISSUE TITLE
Exo Player event listner callback issue

### ISSUE THREAD

**Issue by kuldiep** [google/ExoPlayer#3666] opened 2018-01-04 09:25 UTC
### Issue description
in onPause() of activity i am passing false to player.setPlayerWhenReady(), i press home button of phone so onPause() of activity got called but i keep app in background, i am not removing from stack, after around 20 mins i re open the app so onStart() of activity got called where initialize exoplayer again and i pass valid video url, then i pass player.setPlayerWhenReady(true),but exo player directly calls onPlayerError() in its callback.. but when i close the app from stack and again open the app exo player works fine...please help to resolve this issue.

### Reproduction steps
-start a video streaming using exo player
-click on home button of phone
-don't remove app from background stack
-re open the app..it will call onPlayerError() 

### Version of ExoPlayer being used
2.5.1

### Device(s) and version(s) of Android being used
Motorola G3, and version is 6.0.1

**Comment by tonihei** [comment] 2018-01-04 09:36
Could you provide us with the information requested in the issue template [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE)? In particular, we need details about the reported error for further investigation.

**Comment by kuldiep** [comment] 2018-01-04 09:53
@tonihei  thanks for looking into the question .. i have edited my issue as per given template.

**Comment by tonihei** [comment] 2018-01-04 10:18
I added 
```
if (player != null) {
  player.setPlayWhenReady(false);
}
```
to the `onPause` method of our demo app and I wasn't able to reproduce the error. I didn't wait 20 min though. Does that make a difference whether you wait for 20 minutes or just a short time?

Also, could you please give us the stack trace of the error or even better a full bugreport? And just for clarification - did you get this error in our demo app or your own app? It would be really helpful to tell us what exactly we need to change in our demo to reproduce the problem.

**Comment by kuldiep** [comment] 2018-01-04 11:43
@tonihei i am not using demo app, in short time like 2 mins or 5 mins player works perfectly..i tried 

if (player != null) {
  player.setPlayWhenReady(false);
}

and in onStart() i do

 player.setPlayWhenReady(true);

but player calls onPlayerError() directly, it should play the video instead.
in bug reports

```
01-04 17:11:18.132 31868-31868/com.lxltech.sc.participant D/LOG: onPlayerError: 
                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
01-04 17:11:18.133 31868-31868/com.lxltech.sc.participant D/LOG: onPlayerError: exception 
                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:389)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
```
 i got this exceptions

**Comment by tonihei** [comment] 2018-01-04 12:51
Still can't reproduce your problem.

However, it's a bit odd that you try to set playWhenReady to true in onStart(). 
The demo app initializes and releases the player in either onStart/onStop or onResume/onPause depending on the API version. When you're running Android 6.0.1 you API version should be 23 and thus your player should be released in onPause() and still be null in onStart(). Can you check when your player is released and initialized? It sounds as if the difference between 2 min and 20 min waiting is that onStop is called only in the latter case.

**Comment by ojw28** [comment] 2018-01-04 13:26
[HTTP 403](https://en.wikipedia.org/wiki/HTTP_403) is a server error indicating the client is forbidden access to the stream. Most likely the URLs you're trying to play require authentication, and whatever authentication you're using expires before the app is brought back into the foreground. This is an application and/or server configuration issue. The player is functioning correctly in failing when the 403 is received.

**Comment by kuldiep** [comment] 2018-01-05 05:00
@tonihei @ojw28 thanks for supporting guys, issue was coming because of authentication problem.

**Comment by tonihei** [comment] 2018-01-05 09:54
Closing the issue then as the problem seems to be solved.

**Closed as completed by tonihei** 2018-01-05 09:54 UTC
Labels: question
