### ISSUE TITLE
Exception on device Running Android 11

### ISSUE THREAD

**Issue by theboubougne** [google/ExoPlayer#7878] opened 2020-09-09 17:45 UTC
Android 11 was released yesterday.
Some of my users who switched to Android 11 are experiencing exception when trying to stream audio content.
Switching to MediaPlayer framework allows them to play the files without any issue

Device Pixel 4XL on the official release of Android 11
Audio file:  https://dts.podtrac.com/redirect.mp3/dovetail.prxu.org/memory/9d4152c8-f5a4-4ea6-94c9-651ecf0babe3/thememorypalace.mp3
ExoPlayer: 2.11.7

Stack trace:
```
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0], [2, 44100]), rendererSupport=YES
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$ConfigurationException: com.google.android.exoplayer2.audio.AudioProcessor$UnhandledAudioFormatException: Unhandled format: AudioFormat[sampleRate=-1, channelCount=-1, encoding=-1]
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onOutputFormatChanged(MediaCodecAudioRenderer.java:603)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.processOutputFormat(MediaCodecRenderer.java:1631)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1525)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.audio.AudioSink$ConfigurationException: com.google.android.exoplayer2.audio.AudioProcessor$UnhandledAudioFormatException: Unhandled format: AudioFormat[sampleRate=-1, channelCount=-1, encoding=-1]
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:455)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onOutputFormatChanged(MediaCodecAudioRenderer.java:593)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       ... 8 more
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.audio.AudioProcessor$UnhandledAudioFormatException: Unhandled format: AudioFormat[sampleRate=-1, channelCount=-1, encoding=-1]
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.SilenceSkippingAudioProcessor.onConfigure(SilenceSkippingAudioProcessor.java:145)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.BaseAudioProcessor.configure(BaseAudioProcessor.java:53)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:450)
09-09 13:27:03.925  8196 16092 E ExoPlayerImplInternal:       ... 9 more





09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.analytics.AnalyticsCollector.onPlayerError(AnalyticsCollector.java:488)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$2$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:812)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$fI_Ao37C4zouOtNaX7xHdRfgmVc.invokeListener(Unknown Source:2)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:812)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at android.os.Looper.loop(Looper.java:223)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at java.lang.reflect.Method.invoke(Native Method)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-09 13:27:03.932  8196  8196 E PA_PlayerTask: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by kim-vde** [comment] 2020-09-10 13:32
I tried to play the file with a Pixel 2 XL (with Android 11 and ExoPlayer 2.11.7) but I couldn't reproduce the error.

From the stacktrack, the error is thrown in line 145 of `SilenceSkippingAudioProcessor` because the encoding is equal to `Format.NO_VALUE` (which is equal to -1). But when I play the file on my device, the encoding is `ENCODING_PCM_16BIT`.

I will assign the issue to @andrewlewis to see if he can find something.

In the mean time, what you could try to do to understand what is happening is:

- Play the file on our [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main) to see if it works.
- Debug ExoPlayer to see why the encoding, channel count and sample rate are unset.

**Comment by andrewlewis** [comment] 2020-09-10 13:37
I wasn't able to reproduce this either, testing on Pixel 4 XL running RP1A.200720.009 (the official Android 11 build listed [here](https://source.android.com/setup/start/build-numbers)) using the ExoPlayer demo version 2.11.7. (I also tried enabling speed adjustment and silence skipping but that didn't make a difference.)

Do you have any custom components in your application, or can you think of anything else that might be different in your setup? Thanks.

**Comment by theboubougne** [comment] 2020-09-10 18:40
I cannot reproduce it either but I got at least 20 users reporting this issue. They cannot play ANY file with this version of EXOPlayer while this works fine on my device. Switching to Mediaplayer framework fixes the issue for them.
The app has been using EXOPlayer for a couple of years without any issue playing millions of files every day. This just started on the day of the official Android release.
Nobody experienced this while using earlier Beta of Android 11

**Comment by theboubougne** [comment] 2020-09-10 20:31
I finally managed to reproduce the issue
If I enable a custom renderer like this

```
      rendererFactory = new CustomRenderersFactory(context, new AudioProcessor[] { downMixAudioProcessor });
      loadControl = new DefaultLoadControl.Builder().setAllocator(allocator)
                    .setBufferDurationsMs(minBufferMs, maxBufferMs, bufferForPlaybackMs, bufferForPlaybackAfterRebufferMs)
                    .setTargetBufferBytes(C.LENGTH_UNSET)
                    .setPrioritizeTimeOverSizeThresholds(true).createDefaultLoadControl();
      this.player = new SimpleExoPlayer.Builder(context, rendererFactory).setLoadControl(loadControl).setTrackSelector(new DefaultTrackSelector(context)).build();
```

The AudioProcessor downMixAudioProcessor::onConfigure() method is properly called and channels, samplerate, ... are properly set.

so I don't understand what's causing this

**Comment by andrewlewis** [comment] 2020-09-11 10:50
Could you clarify how you reproduced the issue in more detail, so I can replicate the same setup here? What is `downMixAudioProcessor`? If that's required to reproduce it please share the source code for it.

**Comment by theboubougne** [comment] 2020-09-11 14:26
Any Audio processor you add that way will cause the issue on Android 11. You just need to add a custom renderer to reproduce the issue. You can create a copy of the existing SilenceSkippingAudioProcessor class and use it instead of my downMixAudioProcessor  and you will get the issue

**Comment by andrewlewis** [comment] 2020-09-11 15:04
I modified the demo app on `dev-v2` to add a silence skipping audio processor with `MediaCodecAudioRenderer`, using the following snippet in place of the `PlayerActivity` code to get a default renderers factory and it worked as expected (side note: the silence skipping audio processor needs to be used in an `AudioProcessorChain` to have the player position advance correctly but that isn't relevant to this failure):
```
SilenceSkippingAudioProcessor audioProcessor = new SilenceSkippingAudioProcessor();
audioProcessor.setEnabled(true);
RenderersFactory renderersFactory = new DefaultRenderersFactory(/* context= */ this) {
  protected AudioSink buildAudioSink(Context context, boolean enableFloatOutput, boolean enableAudioTrackPlaybackParams, boolean enableOffload) {
    return new DefaultAudioSink(AudioCapabilities.DEFAULT_AUDIO_CAPABILITIES, new AudioProcessor[] {audioProcessor});
  }
};
```

Are you using `MediaCodecAudioRenderer`? What does `CustomRenderersFactory` do?

**Comment by theboubougne** [comment] 2020-09-11 15:24
I used CustomRenderersFactory to add a new audioProcessor to the add audio Processor to the playback

public class CustomRenderersFactory extends DefaultRenderersFactory {

```
    private final AudioProcessor[] audioProcessors;
    public CustomRenderersFactory(Context context, AudioProcessor[] audioProcessors) {
        super(context);
        this.audioProcessors = audioProcessors;
    }

    @Override
    protected AudioProcessor[] buildAudioProcessors() {
        return this.audioProcessors;
    }

}


```


For some reasons it stopped working since Android 11. Your sample code works fine. Thanks
I know this isn't related to the main question but can you provide more details about what you mean by 'the silence skipping audio processor needs to be used in an AudioProcessorChain'?
What is the correct way to add custom audio Processor to the AudioProcessorChain?

Thanks

**Comment by theboubougne** [comment] 2020-09-11 15:30
Your sample fixes the crash BUT, my audio processor is ignored. Audio isn't processed anymore...

**Comment by andrewlewis** [comment] 2020-09-11 15:33
I'll try on 2.11.7 in case it's just a difference in the branches.

**Comment by theboubougne** [comment] 2020-09-11 15:37
I know this isn't related to the main question but can you provide more details about what you mean by 'the silence skipping audio processor needs to be used in an AudioProcessorChain'?

**Comment by andrewlewis** [comment] 2020-09-11 16:51
> Your sample fixes the crash BUT, my audio processor is ignored. Audio isn't processed anymore...

That snippet is a no-op on 2.11.7 as `buildAudioSink` wasn't released there (it should work on the `dev-v2` branch though). Sorry for the confusion.

With your code on 2.11.7 the added `SilenceSkippingAudioProcessor` does work for me on an Android 11 build. It's strange you are seeing different behavior when we have the same setup. Could you provide the output of `adb shell getprop ro.build.fingerprint`, and also share a minimal patch you've applied to the demo app to reproduce this, just in case there is something else that is different?

> Any Audio processor you add that way will cause the issue on Android 11.

This doesn't seem to be the case for me. It may not be relevant, but I should note that a custom `AudioProcessor` that doesn't return its configured format is one explanation for what you are seeing, I think.

> I know this isn't related to the main question but can you provide more details about what you mean by 'the silence skipping audio processor needs to be used in an AudioProcessorChain'?
> What is the correct way to add custom audio Processor to the AudioProcessorChain?

`SilenceSkippingAudioProcessor` skips audio frames so if you want the player position to be accurate (for example, to show a seek bar or show video frames in synchronization with audio) `DefaultAudioSink` needs to know how many frames were skipped. Please take a look at [`DefaultAudioSink.DefaultAudioProcessorChain`](https://cs.opensource.google/exoplayer/ExoPlayer/+/release-v2:library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java;l=115;drc=ad1dffcae8e3ff73a32716a47d0b837c7d4ffe59) to see how this works. If your custom audio processors don't skip audio or change the speed of audio, you don't need to inject and custom audio processor chain.

**Comment by theboubougne** [comment] 2020-09-11 17:25
This is the code of my AudioProcessor class. It returns the configuration and worked for a couple of years without any issue until Android 11


`public class DownMixAudioProcessor extends BaseAudioProcessor {
    private final static String TAG = LogHelper.makeLogTag("DownMixAudioProcessor");
    private int sampleRateHz;
    private int channelCount;
    private @C.PcmEncoding int encoding;
    private ByteBuffer buffer;
    private boolean enabled;

    public DownMixAudioProcessor() {
        sampleRateHz = Format.NO_VALUE;
        channelCount = Format.NO_VALUE;
        encoding = C.ENCODING_INVALID;
        buffer = EMPTY_BUFFER;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
        flush();
    }

    @Override
    public AudioFormat onConfigure(AudioFormat inputAudioFormat) throws UnhandledAudioFormatException {
        if (inputAudioFormat == null || (inputAudioFormat.encoding != C.ENCODING_PCM_8BIT && inputAudioFormat.encoding != C.ENCODING_PCM_16BIT
                && inputAudioFormat.encoding != C.ENCODING_PCM_24BIT && inputAudioFormat.encoding != C.ENCODING_PCM_32BIT)) {
            throw new UnhandledAudioFormatException(inputAudioFormat);
        }
        if (this.sampleRateHz == inputAudioFormat.sampleRate && this.channelCount == inputAudioFormat.channelCount
                && this.encoding == inputAudioFormat.encoding) {
            return AudioFormat.NOT_SET;
        }
        this.sampleRateHz = inputAudioFormat.sampleRate;
        this.channelCount = inputAudioFormat.channelCount;
        this.encoding = inputAudioFormat.encoding;
        return inputAudioFormat;
    }

    @Override
    public boolean isActive() {
        return encoding != C.ENCODING_INVALID && enabled && this.channelCount == 2;
    }

    @Override
    public void queueInput(ByteBuffer inputBuffer) {
        if (!this.enabled) {
            output(inputBuffer);
        } else {
            try {
                // Prepare the output buffer.
                int position = inputBuffer.position();
                int limit = inputBuffer.limit();
                int size = limit - position;
                int resampledSize;
                switch (encoding) {
                    case C.ENCODING_PCM_8BIT:
                        resampledSize = size * 2;
                        break;
                    case C.ENCODING_PCM_24BIT:
                        resampledSize = (size / 3) * 2;
                        break;
                    case C.ENCODING_PCM_32BIT:
                        resampledSize = size / 2;
                        break;
                    case C.ENCODING_PCM_16BIT:
                        resampledSize = size;
                        break;
                    case C.ENCODING_PCM_FLOAT:
                    case C.ENCODING_INVALID:
                    case Format.NO_VALUE:
                    default:
                        throw new IllegalStateException();
                }
                if (buffer.capacity() < resampledSize) {
                    buffer = ByteBuffer.allocateDirect(resampledSize).order(ByteOrder.nativeOrder());
                } else {
                    buffer.clear();
                }

                // Resample the little endian input and update the input/output buffers.
                switch (encoding) {
                    case C.ENCODING_PCM_8BIT:
                        // 8->16 bit resampling. Shift each byte from [0, 256) to [-128, 128) and scale up.
                        for (int i = position; i < limit; i++) {
                            buffer.put((byte) 0);
                            buffer.put((byte) ((inputBuffer.get(i) & 0xFF) - 128));
                        }
                        break;
                    case C.ENCODING_PCM_24BIT:
                        // 24->16 bit resampling. Drop the least significant byte.
                        for (int i = position; i < limit; i += 3) {
                            buffer.put(inputBuffer.get(i + 1));
                            buffer.put(inputBuffer.get(i + 2));
                        }
                        break;
                    case C.ENCODING_PCM_32BIT:
                        // 32->16 bit resampling. Drop the two least significant bytes.
                        for (int i = position; i < limit; i += 4) {
                            buffer.put(inputBuffer.get(i + 2));
                            buffer.put(inputBuffer.get(i + 3));
                        }
                        break;
                    case C.ENCODING_PCM_16BIT:
                        for (int i = position; i < limit; ++i) {
                            buffer.put(inputBuffer.get(i));
                        }
                        break;
                    case C.ENCODING_PCM_FLOAT:
                    case C.ENCODING_INVALID:
                    case Format.NO_VALUE:
                    default:
                        // Never happens.
                        throw new IllegalStateException();
                }
                inputBuffer.position(inputBuffer.limit());
                buffer.flip();
				
				// PROCESS sound here
				// downmix()
                
                output(buffer);
            } catch (final Throwable t) {
                ExceptionHelper.fullLogging(t, TAG);
                // temporarily disable the audio effect
                this.enabled = false;
            }
        }
    }

    private void output(ByteBuffer data) {
        int length = data.remaining();
        if (length > 0) {
            replaceOutputBuffer(length).put(data).flip();
        }
    }

    @Override
    public void onReset() {
        LogHelper.d(TAG, "onReset()");
        sampleRateHz = Format.NO_VALUE;
        channelCount = Format.NO_VALUE;
        encoding = C.ENCODING_INVALID;
        buffer = EMPTY_BUFFER;
    }`

**Comment by andrewlewis** [comment] 2020-09-12 15:51
`DownMixAudioProcessor` is overriding `BaseAudioProcessor.isActive`, and if you are returning true there it is necessary that the preceding `onConfigure` call returned a valid format (not `AudioFormat.NOT_SET`). It looks like the implementation doesn't follow that contract, so the next audio processor, `SilenceSkippingAudioProcessor` if this is the only custom one, can get an invalid format as input. That would explain the original error. (It would affect all API versions though. For what it's worth, from cursory inspection of the code, I think the bug can happen when reconfiguring the audio processor with the same format, so I wonder whether that is more likely to happen on Android 11 because of a difference in what is being played.)

Side note: the resampling code in `queueInput` can be removed, because custom audio processors only need to handle 16-bit PCM audio (`DefaultAudioSink` puts a `ResamplingAudioProcessor` before custom audio processors so you only need to handle 16-bit PCM).

I'd suggest simplifying the code to remove resampling and make the implementation of `onConfigure`/`isActive` closer to what's in `SilenceSkippingAudioProcessor` as a first step. If the problem persists, or if you can help reproduce the issue on Android 11 using a non-custom AudioProcessor, please provide more details.

**Comment by theboubougne** [comment] 2020-09-12 17:38
Thanks a lot for this information.
This fixes the error on Android 11 however the audio effect is still not applied after I stopped overriding isActive. It still works fine on previous version of Android.
When debugging I can see that isActive is returning TRUE, until player state playWhenReady is changed to true.
After that onConfigure is called  with valid information and yet BaseAudioProcessor.isActive() keeps returning false for some reasons. Again this is only for Android 11
On older Android version onConfigure is only called once at the beginning so something different is definitely going on on Android 11

**Comment by theboubougne** [comment] 2020-09-13 16:19
BTW I switeched to v2.12 and the new and started using this:

SilenceSkippingAudioProcessor audioProcessor = new SilenceSkippingAudioProcessor();
audioProcessor.setEnabled(true);
RenderersFactory renderersFactory = new DefaultRenderersFactory(/* context= */ this) {
  protected AudioSink buildAudioSink(Context context, boolean enableFloatOutput, boolean enableAudioTrackPlaybackParams, boolean enableOffload) {
    return new DefaultAudioSink(AudioCapabilities.DEFAULT_AUDIO_CAPABILITIES, new AudioProcessor[] {audioProcessor});
  }
};

This works fine for older Android version, but on Android 11, the audio processor is still being ignored. You can check my previous message for more details

**Comment by andrewlewis** [comment] 2020-09-14 08:55
> When debugging I can see that isActive is returning TRUE, until player state playWhenReady is changed to true.
> After that onConfigure is called with valid information and yet BaseAudioProcessor.isActive() keeps returning false for some reasons. Again this is only for Android 11
> On older Android version onConfigure is only called once at the beginning so something different is definitely going on on Android 11

Please paste your updated `onConfigure` and `isActive` implementations here.  In the code you provided above, `onConfigure` is going to return `AudioFormat.NOT_SET` if the audio processor is configured twice with the same format, which I think is a bug:

```
    if (this.sampleRateHz == inputAudioFormat.sampleRate && this.channelCount == inputAudioFormat.channelCount
            && this.encoding == inputAudioFormat.encoding) {
        return AudioFormat.NOT_SET;
    }
```

**Comment by theboubougne** [comment] 2020-09-15 00:50
Thanks a lot. This fixes my issue.
The difference is that Android 11 calls onConfigure multiple times compared to older version of android. If this normal then you can close this ticket, otherwise this might be worth investigating
Thanks!

**Comment by andrewlewis** [comment] 2020-09-25 16:55
> The difference is that Android 11 calls onConfigure multiple times compared to older version of android. If this normal then you can close this ticket, otherwise this might be worth investigating

This isn't expected (I don't think anything relevant changed in Android 11), but I don't see the behavior you're describing. In the demo app if I breakpoint in `onConfigure` for one of the audio processors it's hit only once when starting playback. For now I'll close this but if you can provide steps to see this behavior in the demo app I'll take a look. Thanks.

**Closed as completed by andrewlewis** 2020-09-25 16:55 UTC
Labels: bug
