### ISSUE TITLE
Widevine Modular with HDCP playback fails with CryptoException

### ISSUE THREAD

**Issue by zegnus** [google/ExoPlayer#2776] opened 2017-05-05 09:25 UTC
### Issue description
When playing WideVine modular content with HDCP required, certain devices are unable to reproduce the video beyond the mark of 10 seconds throwing a CryptoException in the logs. Alll mentioned devices play fine with WV:HDCP: None (not required).

### Reproduction steps
1. Clone the ExoPlayer repository git@github.com:google/ExoPlayer.git
2. Deploy the `demo` application
3. Play any of the following links:
   - WV: HDCP: 1.0 required
   - WV: HDCP: 2.0 required
   - WV: HDCP: 2.1 required
   - WV: HDCP: 2.2 required
   - WV: HDCP: No digital output
4. The content will play for 12s
5. The content will stop playing and it will throw the following exception in the logs (WV: HDCP: 1.0 required example):
```
05-04 10:50:57.869 16079-17784/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
                                                                                           com.google.android.exoplayer2.ExoPlaybackException
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:708)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:168)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                            Caused by: android.media.MediaCodec$CryptoException: Unknown Error
                                                                                               at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                               at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                               at android.os.Looper.loop(Looper.java:168) 
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
05-04 10:50:57.875 16079-16079/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [13.04]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:708)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:168)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  Caused by: android.media.MediaCodec$CryptoException: Unknown Error
                                                                                     at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                     at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:168) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
```

### Version of ExoPlayer being used
ExoPlayer Demo version 1.5.14

### Devices we had been able to reproduce this issue
- Nexus 5 >= Android M with security patches "2016-05-01", "2016-08-05", "2016-09-06", "2016-10-05"
- HtcOneM8 >= Android 6.0.0
- OnePlus2 ONE A2003 OxygenOS 3.5.8 >= Android 6.0.1
- Samsung Galaxy S6 edge SM-G925F >= Android 6.0.1
- Samsung Galaxy S6 SM-G920F >= Android 6.0.1
- Samsung Galaxy A3 SM-A300FU >= Android 6.0.1
- Samsung SM-T315 >= Android 4.4.2
- Samsung GT-I9195 >= Android 4.4.2
- Samsung Galaxy S7 SM-G930F >= Android 7.0 (could also be from 6.0.1)
- KindleFireHdx8 KFAPWI >= Android 4.4.2
- KindleFireHdx8 KFSAWI >= Android 4.4.2

### Devices reported by our users but we do not posses such devices
- KindleFireHdx7Generation3 KFTHWI >= Android 4.4.2
- Kindle2013Generation3 KFSOWI >= Android 4.4.2
- SamsungT320 >= Android 4.4.2
- SamsungT520 >= Android 4.4.2

### A full bug report captured from the device
- [KindleFireHdx8 KFAPWI](https://drive.google.com/open?id=0BxmlNrFUS44jUXZDXzdXNTU2bFU)
- [KindleFireHdx8 KFSAWI](https://drive.google.com/open?id=0BxmlNrFUS44jNFM2eHZkd1ZkOW8)
- [HtcOneM8](https://drive.google.com/open?id=0BxmlNrFUS44jOThmckpOaVVNaU0)
- [Nexus 5](https://drive.google.com/open?id=0BxmlNrFUS44jZ2tZOHU4SUtvd0k)
- [Samsung GT-I9195](https://drive.google.com/open?id=0BxmlNrFUS44jT0xaQ3FfRWh3Mnc)
- [Samsung Galaxy A3 SM-A300FU](https://drive.google.com/open?id=0BxmlNrFUS44jWlk2TFVGUzNRZHc)
- [Samsung Galaxy S6 SM-G920F](https://drive.google.com/open?id=0BxmlNrFUS44jRUctd1FEVTBkc3c)
- [Samsung Galaxy S6 edge SM-G925F](https://drive.google.com/open?id=0BxmlNrFUS44jaVFiNjdCb2pTTlE)
- [Samsung Galaxy S7 SM-G930F](https://drive.google.com/open?id=0BxmlNrFUS44jM25qdzk0SDBGQjA)
- [Samsung SM-T315](https://drive.google.com/open?id=0BxmlNrFUS44jd0pEQmtDbHVrWHM)

**Comment by MizzleDK** [comment] 2017-05-05 09:54
This looks very similar to my issue:
https://github.com/google/ExoPlayer/issues/2770

**Comment by ojw28** [comment] 2017-05-05 09:58
I suspect this is an issue with the license configuration for our test content (and that it happens on all devices as a result). I see the following error when I try, which suggests the license response doesn't include the correct keys:

```
MediaCodec$CryptoException: Crypto key not available
```

@wvpaf - This is Widevine test content. Has something changed about the way the content or the licenses are configured? It appears the license response doesn't contain the correct keys to play the content. Example:

https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd
https://proxy.uat.widevine.com/proxy?video_id=HDCP_V1&provider=widevine_test

@MizzleDK - It's unlikely the two issues are related.

**Comment by MizzleDK** [comment] 2017-05-05 09:59
@ojw28 All right, no problem.

**Comment by zegnus** [comment] 2017-05-05 10:10
@ojw28 It does not happen on all devices, for example in the Nexus 5 with a security patch lower than the mentioned ones the content plays fine. Also plays fine with a Nexus 5X, Nexus 9, HTC 10...

**Comment by ojw28** [comment] 2017-05-08 01:51
Right, on further investigation this isn't a configuration issue. Widevine have been taking a look at the reports, and it appears there are multiple things going on:

1. The following devices are thought to have L3 Widevine only (i.e. no L1). Failure is expected when using L3 Widevine if the license policy requires an HDCP level:

- Samsung Galaxy A3 SM-A300FU
- Samsung SM-T315 (Unconfirmed L3)
- Samsung GT-I9195
- KindleFireHdx8 KFAPWI (Unconfirmed L3)

2. Nexus 5 is a known device specific issue. The HTC M8 report looks the same, also.

3. The others will need further investigation.

Do you need to be requiring an HDCP level in your license configuration?

**Comment by zegnus** [comment] 2017-05-08 09:07
@ojw28 Unfortunately yes, we are required to have HDCP by contract with our providers. The list provided is only an example, we are seeing reported more devices and sometimes affects only a specific variation of a specific device. One of our main suspicious is that a security patch on Android 6.0.1 introduced this bug across multiple devices.

**Comment by ojw28** [comment] 2017-05-08 14:24
It's somewhat unclear to me why HDCP is relevant for devices where the display is integrated (i.e. all phones and tablets), and it seems this requirement would prevent you from ever providing content to devices that only have L3 Widevine. I'm also surprised there's no provision for such devices; for example the possibility of streaming up to 480p without L1/HDCP.

**Comment by zegnus** [comment] 2017-05-08 15:02
@ojw28 I'm going to explore your second point on streaming 480p content; an alternative is to fall back to Widevine Classic.

Regarding HDCP on phones/tablets, as far as I understood, is it required if he device can be plugged in to an external TV through HDMI. Is that right?

**Comment by ojw28** [comment] 2017-05-08 15:12
That's correct, but I *think* (please don't take this as a guarantee) that just requiring a secure output path is sufficient to guarantee HDCP in that case. My understanding was that you only have to start specifying HDCP requirements in the license policy if you care about the actual version.

**Comment by wvpaf** [comment] 2017-05-09 22:09
Hi @ojw28 is there anything actionable at this point?

**Comment by ojw28** [comment] 2017-05-09 22:40
@wvpaf - I think WV need to do some investigation into the other devices (e.g. the Exynos devices) as per our internal thread.

**Comment by zegnus** [comment] 2017-05-31 15:22
@ojw28 do we have any feedback so far?

**Comment by RRethy** [comment] 2017-06-20 16:55
Bump

**Comment by zegnus** [comment] 2017-06-20 17:43
@wvpaf can you please feed back if there has been any update in this issue? Thank you

**Comment by wvpaf** [comment] 2017-06-20 22:38
Hi,
Digging through the provided logs looks like ;
Samsung Galaxy S6 SM-G920F & Samsung Galaxy S6 edge SM-G925F - are indeed failing HDCP. the policy on the asset is HDCP v2 and the device supports HDCPv1 : see in the log, 

<6>[782705.805478]  [2:mc_log: 3066] MobiCore mcd: d01|[Error]:tlwvdrm:: Fail to decrypt for insufficient HDCP version
<6>[782705.805502]  [2:         mc_log: 3066] MobiCore mcd: d01|[Error]:tlwvdrm:: current HDCP version is 1
<6>[782705.805517]  [2:         mc_log: 3066] MobiCore mcd: d01|[Error]:tlwvdrm:: key control block HDCP version is 2

This would be valid if there is an external device connected to the reported devices, which in this case there isnt. 
This is a bug in the OEM's implementation that was addressed in more recent versions of the devices. 
We will attempt to engage the OEM and ask if they have any plans to address.

**Comment by wvpaf** [comment] 2017-07-18 22:32
Suggestion, if you set the HDCP version to 1 playback should work on some of the mentioned devices.

**Closed as completed by wvpaf** 2017-07-18 22:32 UTC
Labels: bug, bug: device specific, bug: in platform drm

**Comment by zegnus** [comment] 2017-07-19 15:44
Hi @wvpaf thank you for the feedback.

Do you know if the Nexus 5 is going to be fixed?

Thanks
