### ISSUE TITLE
How to add Youtube like FullScreen Mode

### ISSUE THREAD

**Issue by YounMario** [google/ExoPlayer#2308] opened 2017-01-09 11:50 UTC
I want add fullscreen mode like that Youtube did . 
here is my step:
1.definded FragmentLayout as a PlayerView's (TextureView)  Container.
2.when click fullScreen button . remove PlayerView's parent. and add it to fullScreen Layout
3.add fullScreenLayout to root window

here is my fullscreen mode code: 
` private void changeToFullScreenMode() {
        ViewGroup windowView = (ViewGroup) ContextUtil.scanForActivity(mContext)
                .findViewById(Window.ID_ANDROID_CONTENT);

        View view = windowView.findViewById(R.id.full_screen_view);
        if (view != null) {
            windowView.removeView(view);
        }

        View fullScreenView = View.inflate(mContext, R.layout.layout_full_screen_player, null);
        View videoView = mPlayerView.getPlayerView();
        removeParent(videoView);
        ViewGroup fullScreenViewContainer = (ViewGroup) fullScreenView.findViewById(R.id.play_view_container);
        fullScreenViewContainer.addView(videoView);
        windowView.addView(fullScreenView, new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
    }`

Then i found after change to fullscreen mode . there is some frame get dirty .
it's will run  onSurfaceTextureDestroyed first then run onSurfaceTextureAvailable method.
I set player surface when  onSurfaceTextureAvailable . so I want know how to change to fullScreen mode smoothly.

**Comment by ojw28** [comment] 2017-01-25 15:16
Duplicate of #1845.

**Closed as completed by ojw28** 2017-01-25 15:16 UTC
Labels: duplicate
