### ISSUE TITLE
Support for playing mts, m2ts format video

### ISSUE THREAD

**Issue by ooyellow58** [google/ExoPlayer#9300] opened 2021-08-15 20:32 UTC
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] Use case description
Describe the use case or problem you are trying to solve in detail. If there are
any standards or specifications involved, please provide the relevant details.

### Proposed solution
A clear and concise description of your proposed solution, if you have one.

### Alternatives considered
A clear and concise description of any alternative solutions you considered,
if applicable.

**Comment by ojw28** [comment] 2021-08-16 16:28
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/1488. Closing as such. If this is not a duplicate, please clarify below by providing additional information. Thanks!

**Closed as completed by ojw28** 2021-08-16 16:28 UTC
Labels: duplicate
