### ISSUE TITLE
How to play video media on child process

### ISSUE THREAD

**Issue by sunhb** [google/ExoPlayer#9949] opened 2022-02-08 09:48 UTC
I have a player service on a child process named ":player", and the UI components is in main process.
I want to know how to render video from child process to VideoView in main process.
Thanks!

**Comment by ojw28** [comment] 2022-02-12 17:50
There's no need to file duplicate issues across the `media3` and `ExoPlayer` issue trackers. I'll close this as a duplicate of https://github.com/androidx/media/issues/37, and we'll address your question there.

**Closed as completed by ojw28** 2022-02-12 17:50 UTC
Labels: duplicate
