### ISSUE TITLE
Support dynamic start and end positions in ClippingMediaSource

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#7498] opened 2020-06-14 12:20 UTC
### Question

I want to ask if it is possible to have/create a MediaSource that allow custom start/end position like the ClippingMediaSource, but those start/end position can be modified after constructing the MediaSource?

An imagined scenario is an App for video editing and user can set and edit trimming positions and can preview the video at the same time.

**Comment by AquilesCanta** [comment] 2020-06-15 16:24
@tonihei mind taking a look at this? I couldn't find any existing issues, so marking as enhancement.

**Comment by tonihei** [comment] 2020-06-16 08:17
That's a duplicate of #3163.

**Closed as completed by tonihei** 2020-06-16 08:17 UTC
Labels: duplicate
