### ISSUE TITLE
Multiple audio tracks aren't displayed for HLS streams

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#6614] opened 2019-11-02 20:18 UTC
**Issue description**

Multiple audio tracks are not seen on ExoPlayer 2.10.6 for some HLS streams. TS streams are working fine.
The issue is tested on the demo project.

**Reproduction steps**

- Paste the link to the Demo project manifest to media.exolist.json;
- Play the media stream.

**Link to test content**

Link to the media e-mailed to ExoPlayer development team.

**Version of ExoPlayer being used**

2.10.6

**Device(s) and version(s) of Android being used**

Tested on Android Emulators, versions: 8.0, 9.0.
Samsung Galaxy Note 4, Android 6.0.1

HLS media stream has 2 audio tracks (English & Russian), but only one is available for selection.

<img width="504" alt="Screenshot 2019-11-02 at 22 16 24" src="https://user-images.githubusercontent.com/45258003/68076543-952eda00-fdbe-11e9-87dd-de548ab15731.png">

**Comment by ojw28** [comment] 2019-11-11 04:10
Duplicate of https://github.com/google/ExoPlayer/issues/2014.

**Closed as completed by ojw28** 2019-11-11 04:10 UTC
Labels: duplicate
