### ISSUE TITLE
The cache encryption method doesn't seem to work!

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4744] opened 2018-08-29 11:02 UTC
Before filing an issue:
-----------------------
version:2.8.4

I want to use SimpleCache() to encrypt the cached file, which sets the password through the parameter "secretKey."

But cached files can still be played by other players.

**Comment by qeadsw** [comment] 2018-08-29 11:07
I don't know if this question meets the template, please point out thank you.

**Comment by qeadsw** [comment] 2018-08-29 11:08
@ojw28 Please give advice or comments！

**Comment by AquilesCanta** [comment] 2018-08-30 13:40
Closing as duplicate of #4742.

**Closed as completed by AquilesCanta** 2018-08-30 13:40 UTC
Labels: duplicate
