### ISSUE TITLE
Update to 2.10.0 : Audio discontinuity detected ?

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#5853] opened 2019-05-08 13:48 UTC
Hi,
i've update to the last version 2.10.0 and problems start to occur
when i play a stream radio , the sound glitches and i have this **Audio discontinuity detected** in my logcat. so i switched back to 2.9.6 and everything is back to normal .
is there any change i need to make ?
Regards

**Comment by marcbaechinger** [comment] 2019-05-09 16:08
Can you please provide some more information according to the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md)?

**Comment by satyres** [comment] 2019-05-10 22:53
Hi , thanks for your reply.
i'm using Android 5.1 , i've tried on many streams here is one : http://89.34.24.40:9950/
running on Android Studio 3.4.
the problem is the sound glitches and there is Audio discontinuity detected in my logcat.
By the way why should i move to Android X ?
many problem happen when i switched to 2.10.0 and i've been struggling the make it work 
but finally i moved back to 2.9.6 which is more stable
 
Thanks for your time

**Comment by andrewlewis** [comment] 2019-05-11 18:34
Focusing on the audio discontinuity issue: I wasn't able to reproduce this after playing the stream for about 15 minutes. Do you see audio discontinuities when playing the stream in the demo app? If so, please provide a bug report captured with `adb bugreport` just after seeing the problem and attach it here or email it to `exoplayer.dev@gmail.com` with subject 'Issue #5853'.

**Comment by satyres** [comment] 2019-05-12 00:42
Thanks for your reply.
i'm using this app to listen to radio streams https://github.com/segler-alex/RadioDroid
i wanted to update to 2.10.0 ,i've made all possible changes
with HLS streams it works fine , but with the new ProgressiveMediaSource something has changed and the sound start to glitches and i've got  Audio discontinuity detected in my logcat.
please if you don't mind give it  a try ,and change the version to 2.10.0 because with the 2.9.6 it works just fine, this is really odd.
Best regards

**Comment by ojw28** [comment] 2019-05-15 12:10
As above, we already tried to reproduce with the stream provided, and did not encounter any issues. Please try playing the stream in the ExoPlayer demo app. If you can reproduce the problem there then please capture a full bug report with `adb bugreport` shortly after the glitches start to occur, and provide it to us. Thanks!

**Comment by ojw28** [comment] 2019-06-21 18:00
According to https://github.com/segler-alex/RadioDroid/issues/482 the issue doesn't reproduce in the ExoPlayer demo app. Closing, since there's nothing actionable for us to do here.

**Closed as completed by ojw28** 2019-06-21 18:00 UTC
Labels: wont fix: app issue

**Comment by tipoc123** [comment] 2019-08-14 14:11
I have the same issue. Exoplayer 2.9.6 plays HLS video fine, but Exoplayer 2.10.* shows multiple errors (and video hangs at that points) :
```
E AudioTrack: Discontinuity detected [expected 99124410, got 100959077]
```
Sorry, no publicly available link.
In both cases the same device:
Android 6.0.1 STB GIEC MP1113 (chip Amlogic s905x)

ADB Bugreport (ExoPlayer 2.10.0):
[bugreport.txt](https://github.com/google/ExoPlayer/files/3501734/bugreport.txt)

**Comment by tipoc123** [comment] 2019-09-23 13:10
Do you plan to fix this issue?

**Comment by satyres** [comment] 2019-09-23 16:28
Hi?
I hope futur version will fix it.
please if you have time , please give it a try here is a link for [RadioDroid](https://github.com/segler-alex/RadioDroid)
 , just change in the gradle the last version of Exoplayer
i don't know really what happened in the exoplayer core .
but i hope they will be able to fix , to get the last version
Regards

**Comment by satyres** [comment] 2019-09-23 16:30
I do have the same issue even in the last version of Exoplayer
when [RadioDroid](https://github.com/segler-alex/RadioDroid)
i wonder what did happen from the 2.9.6
please fix it
regards
