### ISSUE TITLE
Does ExoPlayer use presentationTimeOffset to calculate start times for segmented text tracks?

### ISSUE THREAD

**Issue by chrisfillmore** [google/ExoPlayer#4132] opened 2018-04-16 17:32 UTC
Hello,

I'm troubleshooting an issue with Shaka player in which segmented WebVTT subtitles aren't showing:
https://github.com/google/shaka-player/issues/1405

I believe the problem is that the cue start times are relative to the segment, and Shaka applies `presentationTimeOffset`, as explained here: https://github.com/google/shaka-player/issues/1405#issuecomment-380622695, so as a result, the segments can't be found by the player.

Here is the content I'm troubleshooting. Unfortunately it's protected so you can't play it, but you can inspect the manifest:
https://dfwlive-sponsored.secure.footprint.net/Content/DASH.abre/Live/channel(FBNHD-1381.dfw.720.mobile)/manifest.mpd

For comparison, here is content which plays just fine in both Shaka and Exo (note: PTO of zero):
https://dfwlive-sponsored.secure.footprint.net/Content/DASH.abre/Live/channel(CNNHD-8249.dfw.1080)/manifest_mobile.mpd

The problematic content displays subtitles just fine in ExoPlayer v2.6.1. I'm not familiar with the Exo code base or any extant issues related to text tracks or PTO. So my question is: does Exo use `presentationTimeOffset` to calculate start times for segmented text tracks? Does it have any special behaviour if this calculation puts the subtitles in the past?

**Comment by ojw28** [comment] 2018-04-16 18:03
I'm reasonably confident that we apply `presentationTimeOffset` correctly. If your WebVTT subtitles are packaged in FMP4 as per ISO/IEC 14496-30, then I think our application of `presentationTimeOffset` is the same as for audio, video etc.

I think we'd need a working test stream to get a clean understanding of exactly what your streams do. I can't even access the manifest links provided (I get: "Access is forbidden"). It doesn't matter too much if audio and video are protected, since we can disable those tracks and still see what's happening with the subtitles.

**Comment by chrisfillmore** [comment] 2018-04-16 18:13
Thanks @ojw28. Are you outside the U.S.? Content will be geo-blocked if so, but if you could access a U.S. VPN, it should work.

There is another developer on my team who may be able to assist with getting a working stream, let me see if I can bring him in.

**Comment by ojw28** [comment] 2018-04-16 18:19
I'm in the UK. I did try proxying into the US, but it didn't resolve my issue (perhaps you make some efforts to detect and block well known proxy services?).

**Comment by chrisfillmore** [comment] 2018-04-16 18:22
Hmm, as far as I know we don't because we regularly require support from international industry partners (I am also not based in US).

I just remembered that the segments are not packaged in fmp4 -- they are plain text WebVTT files. Does that change anything?

**Comment by ojw28** [comment] 2018-04-16 19:00
It looks like [DASH IF IOP](http://dashif.org/wp-content/uploads/2016/12/DASH-IF-IOP-v4.0-clean.pdf) 6.4.5 clarifies expected behavior for the plain WebVTT files:

> Only one file for the full period is permitted, practically limiting this use case to non-live content. Such external files are assumed to have a timeline aligned with the Period, so that TTML time 00:00:00.000 corresponds to the start of the Period. The presentation time offset is expected to be not presented, and if present, expected to be ignored by the DASH client. The same applies to side-loaded WebVTT files. In that case, the mimeType is text/vtt. If segmented subtitles are needed, such as for live sources, ISOBMFF-packaged TTML or WebVTT segments shall be used with timing according to [29]. In particular, this means that the TTML timing inside the segments is with respect to the media timeline.

So according to DASH IF IOP:

* You shouldn't be using plain WebVTT, since your content is (I'm assuming) live.
* For on-demand cases `presentationTimeOffset` is not expected to be present. If it is present it's expected that clients will ignore it. Looking at ExoPlayer code, it looks like we ignore it.
* Whether timestamps in plain WebVTT segments should be relative to the start of the segment or the start of the period is left undefined by DASH IF IOP, since it instead states that you need to use ISOBMFF packaged segments for this case. I _think_ ExoPlayer assumes that the timestamps are relative to the start of the segment, which is consistent with what you're seeing. However, unless you can find this defined as a rule in a spec somewhere, then I don't think you can rely on different players making the same assumption.

So I think the likely conclusion is, if you want your content to work properly across players, you probably need to look at moving to ISOBMFF packaged segments.

**Comment by chrisfillmore** [comment] 2018-04-16 19:25
@ojw28 Thank you for that analysis; I appreciate the help!

**Closed as completed** 2018-04-16 19:44 UTC
Labels: question

**Comment by ojw28** [comment] 2018-04-16 19:53
By the way, if this were ever clarified, I think the most likely clarification would be that timestamps should be as in the ISOBMFF packaged case. It doesn't seem sensible to define them differently. I think that would mean (a) absolute timestamps (i.e. not relative to the start of the segment), and (b) `presentationTimeOffset` being applied. ExoPlayer currently does the opposite in both cases :)...
