### ISSUE TITLE
Issue with Subtitles

### ISSUE THREAD

**Issue by Hari-414** [google/ExoPlayer#10718] opened 2022-10-25 05:38 UTC
HI Team,

   We have recently updated the Exoplayer version to 2.18.1 from 2.14.0. We are unable to show subtitles on the player. The subtitle configurations is attached to the mediaitem and then to player but the subtitles are missing on the player while the content is playing. The same content is showing subtitles on the player in version 2.14.0. Can you please look into this issue and also mention if any additional information is required.

Thanks and Regards,
Hari Teja.

**Comment by rohitjoins** [comment] 2022-10-25 08:55
Hi! Please provide the test content which can be used to reproduce this issue.
If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by Hari-414** [comment] 2022-10-25 09:16
Hi!, We have shared the test content to dev.exoplayer@gmail.com. Please look into this issue as early as possible as the stream url expires within one hour.

**Comment by rohitjoins** [comment] 2022-10-25 10:21
On playing the test content in our demo app, I could see the subtitle when configured correctly. You can find information about using subtitles files: https://exoplayer.dev/media-items.html#sideloading-subtitle-tracks

Please try using just the MediaItem API and see if that works.

Note that the subtitle track will not be selected by default, unless you've customised the [track selection behaviour of the player](https://exoplayer.dev/track-selection.html). If you want this subtitle track to always be selected, you could pass C.SELECTION_FLAG_DEFAULT to SubtitleConfiguration.Builder#setSelectionFlags.

May be you are not using `DefaultMediaSourceFactory`? The subtitle fields of MediaItem are only supported by DefaultMediaSourceFactory, so please use that if not already done. More details [here](https://github.com/google/ExoPlayer/issues/9885#issuecomment-1019171341).

**Comment by Hari-414** [comment] 2022-10-26 10:50
Even after doing the changes you have mentioned. We are unable to show the subtitles on the player.

**Comment by rohitjoins** [comment] 2022-10-26 11:08
@Hari-414 You can try playing the content in our demo app by editing the `media.exolist.json` and replacing one of the urls with your content's parameters. You can see subtitle being enabled in playback when configured correctly. 

This looks like an app specific integration issue. Unfortunately we can't give 1:1 support for solving app specific
issues. We'll leave this issue open for ~2 weeks in case anyone wishes to answer it here. If you think
this is a problem with ExoPlayer, please narrow down your issue to describe the ExoPlayer behaviour
that doesn't match your expectations.

**Comment by yuroyami** [comment] 2022-10-26 15:17
If you need assistance solving the issue, you can email me the contents at: `evongintoki@gmail.com` and I will look into it. Also, attaching a snippet of ExoPlayer initialization code and track loading would be preferable too

EDIT: Who marked this as spam lol ?

**Comment by Hari-414** [comment] 2022-10-31 04:34
Thanks @rohitjoins , after configuring the player is now showing subtitles as well. We have a query about version 2.14.0. Does the version 2.14.0 support the subtitles of file type vtt. Because we are updating the player only because of this issue.

**Comment by rohitjoins** [comment] 2022-10-31 11:55
@Hari-414 Yes, 2.14.0 supports subtitles of file type VTT. Based on the [release notes](https://github.com/google/ExoPlayer/releases/tag/r2.17.0), we have added support for VTT for MKV container in later release i.e. 2.17.0.

We generally try to keep issues focused on one topic. Please [open a new issue](https://github.com/google/ExoPlayer/issues/new/choose). This way we can assign someone that can provide support specifically for your question. Thanks!

**Closed as completed by rohitjoins** 2022-10-31 11:55 UTC
Labels: question, needs triage
