### ISSUE TITLE
Live audio streams stop suddenly (player stuck in buffering state)

### ISSUE THREAD

**Issue by atul14** [google/ExoPlayer#1285] opened 2016-02-19 06:18 UTC
Hi,

Am trying to play audio streams using ExoPlayer(sample application). Have observed an issue that the streams suddenly stop playing after some time, and in the logcat I can see the logs like this - 

E/AudioTrack: Discontinuity detected [expected 158217189, got 157209116]

Few more observations to help pin point the diagnosis - 

1. Mostly happening with Samsung Devices
2. Checked with two devices
    a. Samsung Galaxy J2, Android Version 5.1.1
    b. Samsung Galaxy S4, Android Version 5.0.1
3. Happens with most of the streams. One sample stream tried is
    a. http://67.212.165.106:8191
4. When the issue occurs, the player states show "Buffering"
5. At some rare times, the stream recovers, but most of the times, it doesn't recover and just stops.

Please help with the issue resolution.

**Comment by atul14** [comment] 2016-02-22 07:15
Can anybody help with this issue?

**Comment by isidoroDigio** [comment] 2016-02-22 10:02
Hi,

I'm experiencing this issue also with Samsung Galaxy S6, but I didn't post any result because I don't have access to the device yet. But @ojw28 the issue that you are referencing is for Android 4.1.2 and the issue happen in 5.1.1 so the patch will not correct the error, don't you?

**Comment by ojw28** [comment] 2016-02-22 10:06
I'm not referencing that issue. I referenced this issue from that issue (i.e. the other way around ;)). @atul14 - Things would be less confusing if you didn't cross-post the same thing in multiple places. Thanks!

Regarding this issue - We'll take a look when we have a chance, although any additional debugging work you can do to resolve the issue directly would be much appreciated.

**Comment by isidoroDigio** [comment] 2016-02-22 10:08
Hahaha my bad!

**Comment by atul14** [comment] 2016-02-22 10:38
@ojw28 Thanks for your revert on the issue. Will follow this thread only. I will try to find out some additional info as much is possible. Meanwhile, in case you need any other info from Logcat etc, will be glad to provide. Thanks..

Meanwhile, @isidoroDigio also got reports on this issue from Samsung Galaxy S6, S6 Edge and Edge +

So, primarily with Samsung devices.

**Comment by ojw28** [comment] 2016-02-22 12:18
I could reproduce the issue on a Nexus 5X. I'm not convinced this isn't a serving issue. The stream provided above quite often returns a 400 response code rather than a valid response, so the server seems pretty flaky. How certain are you that this isn't simply a connectivity issue (hence transitioning into the buffering state whilst the client attempts to recover the connection)?

**Comment by atul14** [comment] 2016-02-22 14:12
Hi @ojw28 Thanks for the observation

Here is one more stream showing the same behavior - http://192.69.212.61:8020/live. 

Just to rule out serving/network issue, I attempted to play the same stream at the same time(on the same Network) - one on the Samsung phone and other on the other player on my desktop(VLC)

The phone showed again the same behavior(almost after 15 minutes stream stopped), while VLC continued to work fine.
Again saw the error E/AudioTrack: Discontinuity detected [expected 693454648, got 692586486] and stream abruptly stopped.

**Comment by atul14** [comment] 2016-02-24 07:37
Hello @ojw28 Did you get a chance to look into this? Will be glad to provide any more details that could help investigation.

**Comment by atul14** [comment] 2016-02-25 09:29
Hi @ojw28 I saw your comment on #398 , Although couldn't reproduce the issue with the link mentioned, I could do that with the other link that I have. Also captured the adb bugreport. Here is the dropbox link for that
https://www.dropbox.com/s/pakhy7kym0tr7fe/bugreport.txt.zip?dl=0

1. Stream played is http://192.69.212.61:8020/live with latest ExoPlayer v1.5.6
2. Device used is Samsung Galaxy J2, Android Version 5.1.1. Hope this could help in the investigation
3. One observation(could just be a shot in the dark) - issue seems more with streams on a lower bitrate as compared to ones with higher bitrate. May be something do with buffering etc.

**Comment by ojw28** [comment] 2016-02-25 11:52
I don't think the "Discontinuity Detected" log messages are relevant to this issue. Instead, I think the issue occurs when the client's connection to the server is broken. ExoPlayer tries to recover, and one of two things happens:

- ExoPlayer fails to re-establish a connection, an error is propagated and the state transitions to idle. This is working as intended.
- ExoPlayer succeeds in re-establishing a connection, but the player gets stuck in a buffering state. There's an issue with how we're recovering the connection where the player incorrectly gauges how much media is buffered, causing it to get stuck thinking there's not sufficient media for playback to resume.

I think the second possibility is what you're seeing. If it is, you can work around the issue by ensuring that you always pass 0 as the third argument to `ExoPlayer.Factory.newInstance`. Please could you test this and verify that it fixes the issue for you? We can investigate a proper fix in due course, but it might take a while.

**Comment by ojw28** [comment] 2016-02-25 11:58
By the way, the issue isn't device specific. It can be reproduced across all devices fairly easily as follows:

1. Play the stream for ~5 minutes.
2. Quickly toggle WiFi off and on again using the pull-down drawer. This will force a connection break.

**Comment by atul14** [comment] 2016-02-25 12:00
Thanks @ojw28, will test the suggested solution and confirm

**Comment by atul14** [comment] 2016-02-26 06:29
Hi @ojw28 tried the recommended solution, works well. Now the stream recovers automatically, though I experience a minor slutter of 2-3 seconds. Here is what I see in logcat now(and the audio restarts) - 

02-26 06:12:56.718 30776-32211/com.test E/AudioTrack: Discontinuity detected [expected 347432789, got 346489886]
02-26 06:12:57.219 30776-32211/com.test W/AudioTrack: releaseBuffer() track 0xaf8c1580 disabled due to previous underrun, restarting
02-26 06:12:59.591 30776-32211/com.test W/AudioTrack: releaseBuffer() track 0xaf8c1580 disabled due to previous underrun, restarting

I guess, for now it's good to go. Thanks for that !! Do keep us posted on progress if there's a better fix !

Just a side note, don't know I was experiencing this issue more with Samsung devices, rather than other ones I tried(Lenovo, Nexus etc)

Thanks again.

**Comment by atul14** [comment] 2016-03-03 10:49
HI @ojw28 After applying the fix and update, we are still getting reports regarding the issue from our live users in the Play Store.

Basically the issue seems to be related to buffering and recovery in case of low bandwidth networks or poor streams. The audio continuously slutters at times

Is there a plan soon to prioritize a fix for this?

Thanks

**Comment by ojw28** [comment] 2016-03-06 21:01
Continuous stuttering will occur with the workaround in place specifically when there is insufficient bandwidth between the server and device. This is because the workaround is to set `minRebufferMs=0`. This is the duration of media that needs to be re-buffered for playback to resume after buffering. When it's set to 0 toggling between buffering and playing can occur rapidly if media is being fetched but at insufficient rate.

Once a "proper" fix is in place it will no longer be necessary to set `minRebufferMs=0`. The default value of `5000` will cause less frequent toggling between buffering and playing. Note however that playback will not be smooth. If there's insufficient bandwidth then there's not much we can do.

**Comment by ChernyshovYuriy** [comment] 2016-03-29 17:36
There is one of the cause that can lead to the buffering state freeze and I described it in https://github.com/google/ExoPlayer/issues/1395
Could be helpful for others.

**Comment by wajidp** [comment] 2016-05-26 03:32
Discontinuity detected [expected 12613060, got 12189160] 
Am getting this buffering problem frequently . Is this resolved in latest build ? Sometimes it recovers but most of the times doesn't.  Am using 1.5.8.

**Comment by wajidp** [comment] 2016-05-26 09:07
@ojw28 kindly look into this

**Comment by wajidp** [comment] 2016-06-01 11:40
No response :(

**Comment by ojw28** [comment] 2016-08-31 21:36
This issue is fixed properly in the `dev-v2` branch.

**Closed by ojw28** 2016-08-31 21:36 UTC
Labels: bug, fixed in 2.x
