### ISSUE TITLE
SimpleExoPlayerView blinks with a black screen when videos are changed

### ISSUE THREAD

**Issue by yozh1que** [google/ExoPlayer#2945] opened 2017-06-13 13:19 UTC
### Issue description
SimpleExoPlayerView blinks with a black screen when videos are changed. Standard VideoView does not. Is there a way to achieve the same behavior as with VideoView (by maybe telling the player not to erase view's content while preparing the next video)?

### Reproduction steps
Whenever the play method is called, the screen becomes black for a fraction of a second.

```java
private void initPlayer() {
    if (player == null) {
        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter());
        TrackSelector trackSelector =
                new DefaultTrackSelector(videoTrackSelectionFactory);

        LoadControl loadControl = new DefaultLoadControl();

        player = ExoPlayerFactory.newSimpleInstance(activity, trackSelector, loadControl);
        player.setPlayWhenReady(true);
        eventListener = new EventListener();
        player.addListener(eventListener);
        playerView.setPlayer(player);
    }
}

public void play(Uri uri, long playbackProgress) {
    initPlayer();

    DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(
            activity,
            Util.getUserAgent(activity, activity.getString(R.string.app_name)),
            new DefaultBandwidthMeter());
    ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

    MediaSource videoSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, null, null);
    player.prepare(videoSource);
    player.seekTo(playbackProgress);
}
```

### Version of ExoPlayer being used
r2.4.0

### Device(s) and version(s) of Android being used
Lenovo TAB 2 A10-70L 16Gb

**Comment by ojw28** [comment] 2017-06-13 13:21
Dupe of https://github.com/google/ExoPlayer/issues/2843.

**Closed as completed by ojw28** 2017-06-13 13:21 UTC
Labels: duplicate
