### ISSUE TITLE
Playback issues with Dash H265 streams on some devices

### ISSUE THREAD

**Issue by islor** [google/ExoPlayer#4765] opened 2018-09-03 09:31 UTC
### Issue description
We have tested two H265 streams on a some set top boxes and mobile devices. Both streams are sent to dev.exoplayer@gmail.com along with the logs.

Stream 1 seems to be playing well on Sony mobile phone, but on our set top box visual playback seems to be jerking but the sound runs with no issues. At first we suspected that it might be a device issue, but when tested with a H265 stream from the Exoplayer sample app there doesnt seem to be any issue.
Are you guys able to shed some light on where the issues is? 

The second stream is failing to play at all. There's a "Top bit not zero" error, what could this issue be?

### Reproduction steps
Use sample app, insert provided links. Device used Vodafone UIW4030VHA box.

### Version of ExoPlayer being used
2.8.3

**Comment by tonihei** [comment] 2018-09-05 13:22
I can reproduce both issues.

For the second stream: The fragmented MP4 extractor can read all headers correctly (the values look plausible). But then starts reading the samples by getting the length of the NAL unit. This value doesn't seem to make sense at all (is either too large or negative). Could it be that the stream is faulty? Is it just this one stream or do you see the error in other cases too?

For the first stream: I can reproduce on a Nexus 6P and it looks like an encryption issue. @paf-wv Can you take a look at the first stream?

**Comment by tonihei** [comment] 2018-09-05 14:42
To add to my previous answer: 
It may be that the second stream encrypts the NAL unit headers which it shouldn't do. The NAL header needs to be cleartext to be able to parse the stream. Which encryption tool are you using?

**Comment by islor** [comment] 2018-09-06 02:49
@tonihei i see, let me check with the content team on the encryption. Is there anyway I can see and identify these in the logs myself?

**Comment by tonihei** [comment] 2018-09-06 08:08
The "Top bit not zero" error is a good indication that the NAL unit header can't be read properly. Might be something else, it's just our best guess so far that these headers are encrypted as well and thus the value doesn't seem to make sense.

**Comment by islor** [comment] 2018-09-18 06:48
@tonihei @paf-wv  Hi guys, any ideas on the first stream so far?

**Comment by islor** [comment] 2018-09-18 06:56
For stream 2 we've fixed the NAL issue, but there looks to be another problem. Playback stops after seek is done, tested on the same device too. Sending you guys the new link in email. Is this still a stream issue?

**Comment by ojw28** [comment] 2018-09-18 11:16
It seems highly likely to be an issue with the way you've implemented sample encryption. Have you managed to play the stream successfully using any other player, or any other platform?

**Comment by paf-wv** [comment] 2018-10-09 21:41
@islor, any luck getting an answer for @ojw28?
thanks

**Comment by paf-wv** [comment] 2018-10-23 19:06
@islor, assume the content was the issue and will close this case.
Please reopen if the issue reoccurs .

**Closed as completed by paf-wv** 2018-10-23 19:06 UTC
Labels: bug: in platform drm
