### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ummerakbar45** [google/ExoPlayer#4939] opened 2018-10-12 05:35 UTC
### Issue description
App crashes
### Reproduction steps
While testing we didn't get any such crash, but now app is live and on playstore crashes are related exoplayer

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
samsung, mi, moto etc 
version 6+

### A full bug report captured from the device

java.lang.IndexOutOfBoundsException: 
  at com.google.android.exoplayer2.util.Assertions.checkIndex (Assertions.java:68)
  at com.google.android.exoplayer2.source.SinglePeriodTimeline.getWindow (SinglePeriodTimeline.java:151)
  at com.google.android.exoplayer2.source.ForwardingTimeline.getWindow (ForwardingTimeline.java:62)
  at com.google.android.exoplayer2.source.AbstractConcatenatedTimeline.getWindow (AbstractConcatenatedTimeline.java:195)
  at com.google.android.exoplayer2.Timeline.getWindow (Timeline.java:638)
  at com.google.android.exoplayer2.Timeline.getWindow (Timeline.java:625)
  at com.google.android.exoplayer2.ui.PlayerControlView.updateNavigation (PlayerControlView.java:634)
  at com.google.android.exoplayer2.ui.PlayerControlView.access$1000 (PlayerControlView.java:164)
  at com.google.android.exoplayer2.ui.PlayerControlView$ComponentListener.onTimelineChanged (PlayerControlView.java:1088)
  at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners (ExoPlayerImpl.java:839)
  at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo (ExoPlayerImpl.java:776)
  at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo (ExoPlayerImpl.java:713)
  at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent (ExoPlayerImpl.java:658)
  at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:129)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6983)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:441)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1408)

**Comment by tonihei** [comment] 2018-10-12 10:08
This is most likely because of parallel access to the player. Do you see warnings about that in the log?

**Comment by ummerakbar45** [comment] 2018-10-12 16:29
No I haven't check logs yet, I don't think it is called in parallelly.
Is there any method by which I can check if ExoPlayer is occupied .

**Comment by tonihei** [comment] 2018-10-15 08:55
You should see a warning which starts with "Player is accessed on the wrong thread". If you want to check in code which thread should be used, you can call `player.getApplicationLooper()` which returns the Looper of the thread on which all player calls must happen.

If you can't find this warning and all player access is happening on the correct thread, please try to provide further context of what is happening. For example a full bugreport with event logger output and/or reproduction steps.

**Comment by tonihei** [comment] 2018-10-30 11:18
Closing as we didn't receive any further input.

**Closed as completed by tonihei** 2018-10-30 11:18 UTC
Labels: need more info
