### ISSUE TITLE
AudioTrack: Discontinuity detected and Video Freezes, audio and subtitle works fine

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#5323] opened 2018-12-28 15:25 UTC
Hi, 

I have a really strange issue.

### Configuration I am using:
ExoPlayer + DRM content + IMA + Video Length 45-50 minutes

### Issue:

All works good. 
Only time issue occurs is when when user is playing a content with more than two AdBreaks (let say video has a mid-roll) and presses fastForward button.
When user presses FF button, and  if it hits the AdBreak. Ad plays as expected no issue there. But when user rewinds after the Ad, ExoPlayer is unable to play content before the AdBreak.
Audio and subtitles are there but video is frozen all the time till it hits the AdBreak, after that it works fine.

After the AdBreak, FF and RW buttons are working as expected but after if the user presses FF again and hit the Ad and it it tries to rewind the content before the Ad, same issue repeats.

On the top of that, from the log it shows this error message when user tries to forward and rewind in the frozen part of video.

E/AudioTrack: Discontinuity detected [expected 23219, got -51958000]
E/AudioTrack: Discontinuity detected [expected 23219, got -29759000]
E/AudioTrack: Discontinuity detected [expected 23219, got -6145000]

I am really not sure what's going on.

**Comment by ojw28** [comment] 2019-01-02 12:12
Can you provide better reproduction steps, to allow us to see what you're seeing? In particular some sample content and an ad tag. I tried playback of content with more than two ad breaks, and it worked fine for me.

**Comment by nishantkp** [comment] 2019-01-02 18:33
Hi @ojw28,

My apologies for not being clear,

ExoPlayer is used for TV and **FF** and **RW** action is achieved through listening to remote control events, `KeyEvent.KEYCODE_MEDIA_FAST_FORWARD` and `KeyEvent.KEYCODE_MEDIA_REWIND`

```java
public boolean dispatchKeyEvent(KeyEvent event) {
        if (event.getKeyCode() == KeyEvent.KEYCODE_MEDIA_FAST_FORWARD &&
                event.getAction() == KeyEvent.ACTION_DOWN) {
            fastForward();
            return true;
        }
        if (event.getKeyCode() == KeyEvent.KEYCODE_MEDIA_FAST_FORWARD &&
                event.getAction() == KeyEvent.ACTION_DOWN) {
            rewind();
            return true;
        }
        ...
        ...
        ...
        super.dispatchKeyEvent(event);
    }
```

**Steps to reproduce,**
1. Use **seekTo()** for the fast-forward and rewind, like

_Fast Forward_
```java
long mForwardRewindPosition = 0L;
void fastForward() {
        mForwardRewindPosition = exoPlayer.getCurrentPosition() + (exoPlayer.getDuration() / 100);
        mForwardRewindPosition = Math.min(mForwardRewindPosition, exoPlayer.getDuration());
        exoPlayer.seekTo(exoPlayer.getCurrentWindowIndex(), mForwardRewindPosition);
    }
```

_Rewind_
```java
void rewind() {
        mForwardRewindPosition = exoPlayer.getCurrentPosition() - (exoPlayer.getDuration() / 100);
        mForwardRewindPosition = Math.max(mForwardRewindPosition, 0);
        exoPlayer.seekTo(exoPlayer.getCurrentWindowIndex(), mForwardRewindPosition);
    }
```

2. Press DPAD-Fast Forward till the seek hits to AdBreak. 

3. Let the Ad play.

4. After Ad is done, hit DPAD-Rewind button to play the content before the Ad. 

**Actual Result** 

Audio and subtitles are working as expected but video is frozen all the time even you can see the progress.
Video will continue to resume playback automatically once the progress hit the ad break (the one we just played).

And at the same time if you check the log, you will find this error lines,
```java
E/AudioTrack: Discontinuity detected [expected 23219, got -51958000]
E/AudioTrack: Discontinuity detected [expected 23219, got -29759000]
E/AudioTrack: Discontinuity detected [expected 23219, got -6145000]
```

Hope it will reproduce the issue.

**Comment by ojw28** [comment] 2019-01-02 18:50
> Can you provide better reproduction steps, to allow us to see what you're seeing? **In particular some sample content and an ad tag**.

**Comment by nishantkp** [comment] 2019-01-02 21:31
Hi,

sample video URL is, 

```
http://www.bok.net/dash/tears_of_steel/cleartext/stream.mpd
```

and AdTag is,

```
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=
```

**Comment by ojw28** [comment] 2019-03-06 18:58
I can't reproduce this in the demo app, even using 2.9.2 specifically. Could you try again to see if the issue is resolved (it's theoretically possible a change in IMA on the server side fixed this)?

If it still reproduces for you, could you provide a bit more information. In particular, a full bug report, and if possible a video showing the issue reproducing in our demo app, so that we can make sure we're doing exactly the same thing. Thanks!

**Comment by tonihei** [comment] 2019-05-07 13:44
Closing because no further information was provided.

**Closed as completed by tonihei** 2019-05-07 13:44 UTC
Labels: duplicate

**Comment by nishantkp** [comment] 2019-06-13 18:40
Hi @ojw28,

It's been quite a while.

**ExoPlayer Version : 2.10.1**

I have proper reproduction steps now,

I am able to reproduce it with demo-app too.

**Steps to reproduce,**

Use AndroidTV or something which can be controlled via remote control.
I am also able to produce the same thing in phones/tablets as well.

1. Install the app
2. Open the demo app
3. Go to **IMA sample ad tags**
4. Play VMAP pre-, mid and post-rolls, single ads
5. Let it play the pre-roll, after that select the progress-bar and start scrubbing after the mid-roll. Mid-roll will play just fine.
6. Now scrub to the left before mid-roll, content will frizz, but you can still see the progress indicator and timings go forward even audio will play just fine.
7. Video will play just fine after it hits the mid-roll.

Please find this drop-box link for better clarity,

https://www.dropbox.com/s/scbsm4kbr5gin1m/Video%202019-06-13%2C%202%2044%2001%20PM.mov?dl=0

**Comment by tonihei** [comment] 2019-06-14 08:26
Thanks for the extra information and reproduction steps! It's now pretty clear that it's a duplicate of #6009 and it will be fixed soon.

**Comment by nishantkp** [comment] 2019-06-14 13:11
@tonihei Thanks 👍
