### ISSUE TITLE
"player control" component behaves differently between TalkBack (Accessibility) on and off

### ISSUE THREAD

**Issue by ryxryx** [google/ExoPlayer#8627] opened 2021-02-24 02:49 UTC
Steps to reproduce
- Enable "TalkBack" on your Android device
- Run exoplayer demo app
- Go to play any video
- Tap on player area -> TalkBack says "show player controls"
- Activate it (by double tap or however you set up accessibility on your device) -> Player controls are shown
- While player controls are still shown, activate again -> video is paused
- While player controls are still shown, activate again -> video is played

This is different behaviour compared with when Talkback is off:
- While video is play, tap player area -> Player controls are shown
- While player controls are still shown, tap player area -> Player controls are hidden

This is causing confusion to our users who use TalkBack. When player controls are shown and TalkBack focus is still on the player, and then users activate, what should happen is player controls get hidden. The key thing here is that TalkBack focus is still on the player, so the action should not apply onto the play/pause button. User with accessibility might not see why this is happening.

- ExoPlayer version number: using demo app
- Android version: Android 10
- Android device: Samsung Tab A
- Also tested on older version 2.11.3 on Android 7 on Nexus 9

**Comment by Samrobbo** [comment] 2021-07-19 10:57
This issue slipped through the cracks, sorry about that.

I can confirm this exact issue is happening on my device. 

@ojw28 is this something you can look into? I'm conscious there seems to be a few other Talkback related issues, such as it repeatedly 'saying' the current progress time? Is that expected behaviour?

It could be worth a full dive into the UI talkback situation?

**Comment by ojw28** [comment] 2021-07-19 11:13
I did take a look at this a while back, and was able to reproduce the issue. I wasn't able to figure out the root cause though. It felt like it was more likely to be a problem with talkback itself than a problem with ExoPlayer's UI components. It seems quite likely there exists a way we could work around whatever the underlying problem is. We'll need to carve out some more time to try and figure out how to do that.

**Comment by halilozel1903** [comment] 2022-02-21 09:44
Can't it be done by naming the buttons? 

Like this `android:contentDescription="volume button"`

**Comment by ojw28** [comment] 2022-03-07 09:52
This seems to be related to `StyledPlayerView` overriding `onTouchEvent`. It may be possible to fix it whilst fixing https://github.com/google/ExoPlayer/issues/9605 and https://github.com/google/ExoPlayer/issues/9861.

**Comment by ojw28** [comment] 2022-03-15 00:54
Fixed in `dev-v2`. The fix will be included in 2.18.

**Closed as completed by ojw28** 2022-03-15 00:54 UTC
Labels: bug
