### ISSUE TITLE
End of voice is clipped in Samsung Phone

### ISSUE THREAD

**Issue by MegatronKing** [google/ExoPlayer#3386] opened 2017-10-23 09:36 UTC
### Issue description
 End of voice is clipped in Galaxy devices

### Reproduction steps
1. I played an voice such as "Hello, Jack", but just hear "Hello, Ja", in other mobiles, it works well.
2. I have tested the URI like raw/assets/file/http, every of them is not well.
3. I set a repeat mode, it works well too, "Hello Jack Hello Jack Hello Jack...".
4. I tried the MediaPlayer in system, it has no problem, too.

### Version of ExoPlayer being used
r2.5.1

### Device(s) and version(s) of Android being used
Devices with problem :
- Samsung Galaxy S7 Edge SM-G9350, Android 7.0
- Samsung Galaxy S7 SM-G930FD, Android 7.0
- Samsung Galaxy S7 SM-G930V, Android 7.0
- Samsung Galaxy S4 GT-I9508, Android 5.0.1

Devices without problem :

- Samsung Galaxy S6 SM-G920A Android 5.1.1
- Samsung Galaxy Note5 SM-N9200, Android 5.1.1
- Samsung Galaxy S8 SM-G950U, Android 7.0

### Link to test content
https://drive.google.com/file/d/0B6j8PP1DO7zmNG9TVkhCcmM4RDg/view

### A full bug report captured from the device
https://drive.google.com/file/d/0B6j8PP1DO7zmalhyMkxiMnpOMVU/view?usp=sharing

**Comment by MegatronKing** [comment] 2017-10-24 06:51
Update this issue. I found seekTo is also not work in the phone.

**Comment by ojw28** [comment] 2017-11-01 15:16
Please can you provide a sample audio file that clearly reproduces the issue? Thanks.

**Comment by MegatronKing** [comment] 2017-11-02 02:06
Thanks for the reply.
Audio link : https://drive.google.com/file/d/0B6j8PP1DO7zmNG9TVkhCcmM4RDg/view
But I think it is not the audio's problem because I have tried some formats like ogg and mp3.

**Comment by ojw28** [comment] 2017-11-06 08:55
Please also provide a full bug report shortly after encountering the issue (as requested in our issue template).

**Comment by MegatronKing** [comment] 2017-11-06 09:37
I have updated the issue and bug report has attached as a link.

**Comment by ojw28** [comment] 2017-11-06 16:38
This seems to be a device specific issue. We've asked Samsung to take a look [Internal ref: 68935307]

**Comment by MegatronKing** [comment] 2017-11-15 10:29
I have added more Samsung devices with problem and some without problem.

**Comment by ojw28** [comment] 2018-01-02 17:04
Samsung have indicated this will be fixed in future device software updates. Closing, since it's not an ExoPlayer issue and I don't think we have a sensible workaround that we can apply on those devices currently affected (unfortunately).

**Closed as completed by ojw28** 2018-01-02 17:04 UTC
Labels: bug: device specific
