### ISSUE TITLE
Subtitle does not appear when App comes to Foreground in paused state

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#8787] opened 2021-04-02 09:13 UTC
I am checking on ExoPlayer Demo 'release-v2' branch.

Steps:

1. Go to 'Subtitles'
2. Select 'TTML Japanese Features'
3. Let the media start
4. Pause the player when the subtitle is visible on the screen
5. Go to BG and come to FG

Video: https://drive.google.com/file/d/1eQdVFGuRuDOYxeFS_cjeXf3TadiOXDFO/view?usp=sharing
Result: With video frame, last visible subtitle is not being shown
Expected Result: With video frame, last visible subtitle should be visible

Is this the intended behaviour ?

PS: There is a callback of `onCues(List<Cue> var1)` from TextOutput which gives us the cues for the content. I see `onCues(List<Cue> var1)` comes with var1 with 0 values when i go to BG and come to FG event thought there was a subtitle before going to BG.

**Comment by ojw28** [comment] 2021-04-06 15:41
Closing as a duplicate of https://github.com/google/ExoPlayer/issues/3480.

**Closed as completed by ojw28** 2021-04-06 15:41 UTC
Labels: duplicate
