### ISSUE TITLE
Internal track renderer error.

### ISSUE THREAD

**Issue by AnwerMatterXD** [google/ExoPlayer#1598] opened 2016-06-15 12:36 UTC
Ihave This Error When run app in kitkat ??????

  com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://live.mp3quran.net:9990/;
                                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://live.mp3quran.net:9990/;
                                                                                        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:202)
                                                                                        at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                                        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:824)
                                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                        at java.lang.Thread.run(Thread.java:841)
                                                                                     Caused by: java.net.ProtocolException: Unexpected status line: ICY 200 OK
                                                                                        at com.android.okhttp.internal.http.RawHeaders.setStatusLine(RawHeaders.java:108)
                                                                                        at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
                                                                                        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
                                                                                        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
                                                                                        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                                                        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                                        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
                                                                                        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:199)
                                                                                        at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135) 
                                                                                        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:824) 
                                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                        at java.lang.Thread.run(Thread.java:841)

**Comment by andrewlewis** [comment] 2016-06-15 12:55
This looks like a duplicate of #890 and #1211. Try using the [okhttp extension](https://github.com/google/ExoPlayer/tree/master/extensions/okhttp).

**Closed as completed by andrewlewis** 2016-06-15 12:55 UTC
Labels: duplicate

**Comment by AnwerMatterXD** [comment] 2016-06-15 14:49
sooory im not understand the soulation !!!!!!
