### ISSUE TITLE
IllegalStateException when playing specific HLS

### ISSUE THREAD

**Issue by eshkoliGilad** [google/ExoPlayer#1683] opened 2016-07-19 12:57 UTC
Testing it on ExoPlayer 1.5.9 version on Sony Xperia Z4 using Android M.

I'm trying to play this url: "http://31.154.18.73:55525/shls/LIVE%24NVR/5.m3u8?start=LIVE&end=END&device=HLS" which does seem to work natively on Android and also works with hls.js demo site in android browser.

But I'm keep getting this error (Stack trace):

"07-19 15:51:45.101 8778-8778/com.xxx.app D/LivePlayer: preparePlayer called with: http://31.154.18.73:55525/shls/LIVE%24NVR/5.m3u8?start=LIVE&end=END&device=HLS
07-19 15:51:45.106 8778-8778/com.xxx.app I/ExoPlayerImpl: Init 1.5.9
07-19 15:51:45.111 8778-8778/com.xxx.app D/LivePlayer: STATE_PREPARING
07-19 15:51:45.119 8778-8778/com.xxx.app D/LivePlayer: STATE_PREPARING
07-19 15:51:45.128 8778-8778/com.xxx.app D/LivePlayer: onSurfaceTextureAvailable
07-19 15:51:45.222 8778-9438/com.xxx.app W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
07-19 15:51:45.234 8778-9438/com.xxx.app W/AudioCapabilities: Unsupported mime audio/alac
07-19 15:51:45.235 8778-9438/com.xxx.app W/AudioCapabilities: Unsupported mime audio/dsd
07-19 15:51:45.246 8778-9438/com.xxx.app W/VideoCapabilities: Unsupported mime video/divx
07-19 15:51:45.248 8778-9438/com.xxx.app W/VideoCapabilities: Unsupported mime video/divx311
07-19 15:51:45.250 8778-9438/com.xxx.app W/VideoCapabilities: Unsupported mime video/divx4
07-19 15:51:45.261 8778-9438/com.xxx.app W/VideoCapabilities: Unsupported mime video/mp4v-esdp
07-19 15:51:45.281 8778-9438/com.xxx.app I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
07-19 15:51:45.370 8778-9438/com.xxx.app E/ExoPlayerImplInternal: Internal runtime error.
                                                                       java.lang.IllegalStateException
                                                                           at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.enableRenderer(ExoPlayerImplInternal.java:347)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:314)
                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:224)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
07-19 15:51:45.388 8778-8778/com.xxx.app D/GoogleAnalytics: track(Live,Error,com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException url:http://31.154.18.73:55525/shls/LIVE%24NVR/5.m3u8?start=LIVE&end=END&device=HLS)
07-19 15:51:45.388 8778-8778/com.xxx.app D/LivePlayer: STATE_IDLE"

On the contrary, I'm do able to play some other streams (Example: "http://video4.earthcam.com/fecnetwork/hotelvictoria2.flv/playlist.m3u8"), so HLS does seem to work properly for most cases.

So may it be the encoded TS are using a profile ExoPlayer can't handle ?
May it be the something related to audio streaming which is improper ?

Also, which HLS version does ExoPlayer support ?

**Comment by eshkoliGilad** [comment] 2016-07-20 10:07
It looks as if it is related to rendererMediaClock is not null but I can't find who is assigning it and I don't know what it is or what it is related to.

I would be more than happy to be clarified about that issue.

**Comment by ojw28** [comment] 2016-07-20 10:25
This error doesn't occur if I add the stream to the ExoPlayer demo app, so it's likely something you've done in your integration. Are you injecting two audio renderers or custom renderers of some kind into the player?

Please provide reproduction steps if you're able to cause the failure inside the ExoPlayer demo app. Else we'll have to close this as an issue with your integration. Thanks!

**Comment by eshkoliGilad** [comment] 2016-07-20 10:36
Hi, @ojw28 .
Thanks for the quick response.

It looks as you were right.

I use this [gist](https://gist.github.com/jmgirven/4e0ba2c7d584c8695549) in order to try and FF a video. Removing this was the soultion. But any idea why I can't use this with the current gist ?

**Comment by ojw28** [comment] 2016-07-20 10:45
A `MediaClock` is a component that drives the playback position. In regular ExoPlayer use, `MediaCodecAudioTrackRenderer` is the `MediaClock` and drives the playback position. Other `TrackRenderer`s ensure that they render in sync with the `MediaClock`. In the case that there's no audio, `ExoPlayerImplInternal` has a component that can act as the `MediaClock` instead.

In your case you have two active `MediaClock`s at once, because you're using `MediaClockAudioTrackRenderer` and you're also using the custom renderer, which implements `MediaClock`. You cannot have two active `MediaClock`s at once, because that implies there could be two different playback positions simultaneously, which makes no sense. Hence we fail the playback.

If you're not interested in audio, one solution is to not inject an audio renderer. Note that we're unable to assist with any issues specific to the custom renderer, if you still have issues after doing this.

**Closed as completed by ojw28** 2016-07-20 10:45 UTC
Labels: question, wont fix: infeasible
