### ISSUE TITLE
App crashes from `java.lang.IllegalArgumentException` on `CastPlayer.setMediaItems()` when passing large playlist

### ISSUE THREAD

**Issue by blvckcoded** [google/ExoPlayer#10404] opened 2022-07-04 23:13 UTC
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

* Pixel 5 running Android 12

### Reproducible in the demo app?

No

### Reproduction steps

1. Create a "playlist" of around 100-150 media items
2. Attempt to play playlist of media items with ExoPlayer and notice you will have no issues
3. Now switch to CastPlayer and notice a crash will occur from cast framework when calling CastPlayer.setMediaItem(...) with large list

Note - I saw this existing issue from 2 years ago but has limited info on it. https://github.com/google/ExoPlayer/issues/8280

This existing issue is related.

### Expected result

The playlist is casted and played successfully

### Actual result

Playback crashes with stack trace:
```
java.lang.IllegalArgumentException: Message exceeds maximum size524288
        at com.google.android.gms.cast.zzbp.zzh(com.google.android.gms:play-services-cast@@20.1.0:6)
        at com.google.android.gms.cast.framework.media.zzbg.zzb(com.google.android.gms:play-services-cast-framework@@20.1.0:2)
        at com.google.android.gms.cast.internal.zzp.zzg(com.google.android.gms:play-services-cast@@20.1.0:2)
        at com.google.android.gms.cast.internal.zzap.zzx(com.google.android.gms:play-services-cast@@20.1.0:18)
        at com.google.android.gms.cast.framework.media.zzag.zza(com.google.android.gms:play-services-cast-framework@@20.1.0:2)
        at com.google.android.gms.cast.framework.media.zzbl.zzc(com.google.android.gms:play-services-cast-framework@@20.1.0:5)
        at com.google.android.gms.cast.framework.media.RemoteMediaClient.zzt(com.google.android.gms:play-services-cast-framework@@20.1.0:1)
        at com.google.android.gms.cast.framework.media.RemoteMediaClient.queueLoad(com.google.android.gms:play-services-cast-framework@@20.1.0:3)
        at com.google.android.exoplayer2.ext.cast.CastPlayer.setMediaItemsInternal(CastPlayer.java:1039)
        at com.google.android.exoplayer2.ext.cast.CastPlayer.setMediaItems(CastPlayer.java:284)
```

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment] 2022-07-05 10:09
Duplicate of #8280

**Closed as completed by marcbaechinger** 2022-07-05 10:09 UTC
Labels: enhancement
