### ISSUE TITLE
How to listen buffering percent before video can play ?

### ISSUE THREAD

**Issue by mdtuyen** [google/ExoPlayer#2902] opened 2017-06-04 06:05 UTC
I want to get percent buffering before stream video link, I used getbufferedPercentage but see that it not correct (some time < 0 or not increate)

Please give be a solution (With exoplayer2) ( I make it work fine with vitamio)

**Comment by ojw28** [comment] 2017-06-04 12:15
`getBufferedPercentage` is the correct thing to be using. We should make sure the value doesn't go negative. Beyond that you'll need to provide proper reproduction steps if you want us to investigate, and fill out the issue template correctly.

**Comment by ojw28** [comment] 2017-06-06 15:53
The returned value is now constrained to be in the range [0,100]. Closing due to lack of information beyond that.

**Closed as completed by ojw28** 2017-06-06 15:53 UTC
Labels: bug, need more info
