### ISSUE TITLE
Concatenating media source as a single media item

### ISSUE THREAD

**Issue by ayeshq** [google/ExoPlayer#9566] opened 2021-10-15 02:18 UTC
I'm working on a simple audio player, which plays audio stories, every story is divided into multiple media items as a playlist, I'm using the `ConcatenatingMediaSource` with no issues at all as follows:
```
private fun createMediaSource(
        tracks: List<Track>
    ): MediaSource = ConcatenatingMediaSource().apply {
        tracks.forEach { track ->
            val mediaSource = ProgressiveMediaSource
                .Factory(DefaultDataSourceFactory(context))
                .createMediaSource(MediaItem.fromUri(track.getFullUri()))
            addMediaSource(mediaSource)
        }
    }
```
However the required playback behavior for the app is to play all tracks sequentially as a single audio file, so if the user uses the seek bar the player would seamlessly know if it should stay on the same track, the previous or the next track, and the length that's visible to the user on the seek bar is the sum of all lengths of all the tracks.

My question is, is there a different media source I can use that can do this, should I create a custom media source, or should I completely build this logic in custom UI and completely avoid using the `com.google.android.exoplayer2.ui.PlayerView` ?

**Comment by tonihei** [comment] 2021-10-15 08:00
This is a duplicate of #4868. The goal is to have a `MediaSource` that fully combines all individual items to one single `MediaItem` with the combined duration.

**Closed as completed** 2021-10-15 08:00 UTC
Labels: duplicate
