### ISSUE TITLE
Custom PlaybackControlView not update without exo_position and exo_duration

### ISSUE THREAD

**Issue by baitouwei** [google/ExoPlayer#2927] opened 2017-06-09 09:19 UTC
### Issue description
Custom PlaybackControlView whitout position text and duration text then progress will not update.

### Reproduction steps
```java
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.google.android.exoplayer2.ui.DefaultTimeBar
        android:id="@id/exo_progress"
        android:layout_width="match_parent"
        android:layout_height="20dp">
    </com.google.android.exoplayer2.ui.DefaultTimeBar>
</FrameLayout>
```
1.Use above xml to custom PlaybackControlView
2.PlaybackControlView progress will not update

### Version of ExoPlayer being used
r2.4.1

### Device(s) and version(s) of Android being used
Geneymotion Nexus 5 6.0.0 API 23

**Comment by ojw28** [comment] 2017-06-09 09:27
Duplicate of https://github.com/google/ExoPlayer/issues/2871. This will be fixed in the next release.

**Closed as completed by ojw28** 2017-06-09 09:27 UTC
Labels: duplicate
