### ISSUE TITLE
How to clear playerNotification without using StopForground(true), 

### ISSUE THREAD

**Issue by zedxer** [google/ExoPlayer#5912] opened 2019-05-20 07:44 UTC
How to clear playerNotification without using StopForground(true), 
-----------------------
I needed to clear notification when player is paused or stopped but the problem is that I was unable to do this without using [this](https://github.com/google/ExoPlayer/issues/4256#issuecomment-388936681)
but this cause my app to crash leaving this Fatal exception. 

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1837)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6665)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
```
Here is the notification listener.
```
playerNotificationManager?.setNotificationListener(object : PlayerNotificationManager.NotificationListener {
            override fun onNotificationCancelled(notificationId: Int) {
                stopSelf()
            }

            override fun onNotificationStarted(notificationId: Int, notification: Notification?) {
                startForeground(notificationId, notification)
            }
        })
```
Here is my code for adding listener
```
player?.addListener(object : Player.DefaultEventListener() {
            override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
                playerNotificationManager?.setOngoing(false)
                if (!playWhenReady)
                    stopForeground(true)

            }
```
In the Activity I am starting the Service from here
 ```
 override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.player_layout)
    intent.putStringArrayListExtra("URLs", arrayofURLs)
        startForegroundService(this, intent)
    }

    private fun startForegroundService(context: Context, intent: Intent): ComponentName? {
        return if (Util.SDK_INT >= 26) {
            bindService(intent, connection, Context.BIND_AUTO_CREATE)
            context.startForegroundService(intent)
        } else {
            bindService(intent, connection, Context.BIND_AUTO_CREATE)
            context.startService(intent)
        }
    }
```

**Comment by marcbaechinger** [comment] 2019-05-20 09:01
I'm not sure how the code snippet is related to the stack trace.

The stack trace of the exception seems to be caused by a call to 'startForegroundService()' which then is not followed by a call to 'Service.startForeground()'. From the code above I don't understand how the snippet which calls `stopForeground()` triggers this. I'd watch out for some code which is triggering calling `startForegroundService` again. This may be the case when playWhenReady is set to true again, but the service does not call `startForeground`. It's worth reviewing the code to make sure this does not happen.

In general, if you have a foreground service you need to have a notification. If you want to remove the notification you need to remove your service from the foreground by calling `stopForeground(true)`, which also remove the notification. If now `playWhenReady` is set to true again and the player in the service resumes playback, you need to call `startForeground()` again and pass the notification id and the notification. 

Apart from this, the `PlayerNotificationManager` removes the notification when `playerNotificationManager.setPlayer(null)` is called.

**Comment by zedxer** [comment] 2019-05-20 09:57
Apologies for not posting complete code.  I have update the question now, And thanks this resolves my problem.

**Comment by marcbaechinger** [comment] 2019-05-21 09:07
Cool! I understand this is resolved, so I close this issue. Please re-open in case I misunderstood.

**Closed as completed by marcbaechinger** 2019-05-21 09:07 UTC
Labels: question
