### ISSUE TITLE
HLS livestream video indefinitely stuck at buffering state, but works when I seek the video to some other timestamp

### ISSUE THREAD

**Issue by MohitGupta913** [google/ExoPlayer#10892] opened 2022-12-30 16:00 UTC
#### Issue
I am trying to play an HLS live stream video in our main codebase but it is stuck in buffering state at timestamp 0 and not playing. But when I seek the video to some other timestamp, it works fine.

HLS video I am using: [Link](https://2gud-live-cdn.akamaized.net/media/fk-p-user-2gudsocial072022/social-multimedia/video/publish/112288_E57A7D49690199E252FEEBB8AC81455E/master.m3u8)

<img width="200" alt="image" src="https://user-images.githubusercontent.com/23074857/210089298-e979de5c-78bf-48d9-b20d-6c06ab7478dd.png">

#### Context
I went through the code and figured out that `playBackState` never changes from `buffering` state to `ready` state and the player never plays the video. It is not throwing any errors either.

Checked the network logs. It is only requesting initial segments but not making subsequent network calls to get video chunks. Please check the network log screenshots.
<img width="400" alt="1" src="https://user-images.githubusercontent.com/23074857/210087890-56699a96-11e7-42eb-be09-552c2c961a08.png"><img width="400" alt="2" src="https://user-images.githubusercontent.com/23074857/210087901-74140bbb-f129-4d2c-b5e6-23cb947ce2c4.png">

I got the following log through a custom Analytics Event listener. It was put inside `onPlayerStateChanged` callback.
```
2023-01-01 21:39:51.706 31400-31400/com.flipkart.android D/FkVideoAnalyticsListener: [main]  onPlayerStateChanged currentPlaybackPositionMs: 0 totalBufferedDurationMs: 0 playWhenReady:true playbackState:2
```
That means buffering itself is stuck!
#### Ask
Is there a way to check what the exoplayer is waiting for complete the buffer? Please suggest ways to debug this further.
#### Additional information
Checked another similar issue https://github.com/google/ExoPlayer/issues/4659, but the suggested solution didn't work.

Also, I have another demo video player. **This player is able to play the video properly. So, I am guessing that there is no issue with the media and issue lies with the implementation.**
#### Versions
ExoPlayer 2.9.6
#### Device
Redmi Note 8 Pro (Physical device), Android 11

**Comment by tonihei** [comment] 2023-01-05 09:34
The stream plays without issues on the latest ExoPlayer version 2.18.2 using a Pixel 5. 

Could you try the latest version yourself to see if it's working? If it does, then we likely fixed an issue since the version you are using.

**Comment by MohitGupta913** [comment] 2023-01-06 09:27
Thanks for reverting @tonihei !

**Some more info**:
So, we have a library to play video on android (`android-video-player`) which uses exoplayer internally (`v2.9.6`). We also have a demo app (a demo player to test videos) and a main production app. Both of them use this `android-video-player` lib to play the video.

Now, the demo app is able to play the video but the main app doesn't. That probably means the media is good and also, there are no issues with this version of the exoplayer.

We are not able to point out the difference on the high level as the code mentioned above is a little old and the folks have left the company. We were trying to backtrack from the exoplayer code where it is stuck, maybe some config is incorrect.

Found one more similar issue: https://github.com/google/ExoPlayer/issues/1027

**Debugging done so far**:
On digging into the exoplayer code, we figured `MSG_PERIOD_PREPARED` event is not happening inside `ExoPlayerImplInternal.java` which means that period has not been prepared. On backtracking, we found out that the below function (inside `HlsMediaPeriod.java`) which triggers this event is not getting called:
```
  @Override
  public void onPrepared() {
    if (--pendingPrepareCount > 0) {
      return;
    }

    int totalTrackGroupCount = 0;
    for (HlsSampleStreamWrapper sampleStreamWrapper : sampleStreamWrappers) {
      totalTrackGroupCount += sampleStreamWrapper.getTrackGroups().length;
    }
    TrackGroup[] trackGroupArray = new TrackGroup[totalTrackGroupCount];
    int trackGroupIndex = 0;
    for (HlsSampleStreamWrapper sampleStreamWrapper : sampleStreamWrappers) {
      int wrapperTrackGroupCount = sampleStreamWrapper.getTrackGroups().length;
      for (int j = 0; j < wrapperTrackGroupCount; j++) {
        trackGroupArray[trackGroupIndex++] = sampleStreamWrapper.getTrackGroups().get(j);
      }
    }
    trackGroups = new TrackGroupArray(trackGroupArray);
    callback.onPrepared(this);  // <-- this line triggers the `MSG_PERIOD_PREPARED` event
  }
```

Here, `pendingPrepareCount` started with 2 but the function only got called once and its value never became 0. Hence, the code below the `if` check didn't execute! This didn't get called twice because `onMoovContainerAtomRead()` method (inside `FragmentedMp4Extractor.java`) didn't call `extractorOutput.endTracks()` which eventually calls `onPrepared()`.


What could be the reasons for such different behavior between the two wrapper code implementations (demo & main app) which use the same exoplayer library under the hood? What are the possible scenarios for period not getting prepared and how can we debug that?

**Comment by tonihei** [comment] 2023-01-09 09:24
Just guessing based on the code pointers, I assume that the player is told about multiple formats/tracks inside the streams, but then fails to find any samples for them. 

A potential difference between ExoPlayer's demo app and your app is that is uses chunkless preparation, a more efficient mode of preparation that just uses the multivariant playlist and doesn't need to read any of the actual chunks to know which tracks exist. 

In any case, if stream plays perfectly fine on the latest ExoPlayer demo app, then we probably can't help you in detail to find out where the difference to your app is. If you think something is wrong and you can reproduce it by making changes to the ExoPlayer demo app, then please let us know and we can have a look again.

**Comment by MohitGupta913** [comment] 2023-01-09 19:23
Is the chunkless preparation feature available in v2.9.6?

Also, I will use the demo app that exoplayer ships and see if it works with the latest version, although it would be challenging for us to migrate the whole code to use the new exoplayer.

**Comment by MohitGupta913** [comment] 2023-01-09 21:03
@tonihei you are a lifesaver! Thank you.
I used the chunkless preparation feature (which was introduced in v2.7) in the main app and now I am able to play the HLS video.
```
    protected HlsMediaSource.Factory getHlsFactory() {
        if (hlsFactory == null) {
            DataSource.Factory factory = cacheManager != null ? cacheManager.getReadCacheDataSourceFactory() : dataSourceFactory;
            hlsFactory = new HlsMediaSource.Factory(factory).setAllowChunklessPreparation(true);  // this line enables chunkless preparation
        }
        return hlsFactory;
    }
```
Referred: [Customizing playback](https://exoplayer.dev/hls.html#disabling-chunkless-preparation) & [Faster HLS preparation](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6)

**Fyi**: Both our demo app and main app **were not using the chunkless preparation** feature. Still, HLS streaming works in our demo app.

**Comment by tonihei** [comment] 2023-01-26 14:41
Closing the issue as the question was resolved and ExoPlayer supports the stream by default in the latest versions.

**Closed as completed by tonihei** 2023-01-26 14:41 UTC
Labels: question
