### ISSUE TITLE
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.

### ISSUE THREAD

**Issue by ramkailash-mob-incedo** [google/ExoPlayer#4407] opened 2018-06-22 09:39 UTC
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:148)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:48)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)

**Comment by ojw28** [comment] 2018-06-22 10:15
There are multiple existing issues for this ([see here](https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aissue+%22Input+does+not+start+with+the+%23EXTM3U+header%22+)).

Hard to say for sure without any of the information requested in the issue template, but closing on the assumption this is a duplicate of https://github.com/google/ExoPlayer/issues/4066.

**Closed as completed by ojw28** 2018-06-22 10:15 UTC
Labels: duplicate
