### ISSUE TITLE
E/ExoPlayerImplInternal: Internal track renderer error.

### ISSUE THREAD

**Issue by Naguchennai** [google/ExoPlayer#4007] opened 2018-03-20 09:03 UTC
Some time Exoplayer stop playing and showing this error play audio only its happend  exoplayer all vertion after IMA added vertions

     	E/AudioTrack: AudioFlinger could not create track, status: -12
	E/AudioTrack-JNI: Error -12 initializing AudioTrack
	E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
	E/ExoPlayerImplInternal: Playback error.
	com.google.android.exoplayer2.ExoPlaybackException
		at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:467)
		at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1068)
		at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:567)
		at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
		at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
		at android.os.Handler.dispatchMessage(Handler.java:98)
		at android.os.Looper.loop(Looper.java:163)
		at android.os.HandlerThread.run(HandlerThread.java:61)
	 Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(22050, 12, 28352)
		at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1220)
		at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:517)
		at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:574)
		at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:461)
		at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1068) 
		at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:567) 
		at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522) 
		at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305) 
		at android.os.Handler.dispatchMessage(Handler.java:98) 
		at android.os.Looper.loop(Looper.java:163) 
		at android.os.HandlerThread.run(HandlerThread.java:61) 

My Audio player code is 

     streamUri = Uri.parse(url);

		DefaultBandwidthMeter defaultBandWidthMeter = new DefaultBandwidthMeter();
		DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, defaultBandWidthMeter,
				new OkHttpDataSourceFactory(okHttpClient, Util.getUserAgent(this, "exoplayer2example"), defaultBandWidthMeter));
		ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
		TrackSelection.Factory videoTrackSelectionFactory =
				new AdaptiveTrackSelection.Factory(defaultBandWidthMeter);
		TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
		player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);

		if( url.contains("m3u8") ) {
			MediaSource videoSource = new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(streamUri);
			loopingSource = new LoopingMediaSource(videoSource);
			player.prepare(loopingSource);
		}else{

			MediaSource videoSource = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(streamUri);
			loopingSource = new LoopingMediaSource(videoSource);
			player.prepare(loopingSource);
		}

**Comment by andrewlewis** [comment] 2018-03-20 09:11
Please provide the information requested in the [new issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

In particular, it would be useful to have a bug report captured with `adb bugreport` as this will give an indication as to whether audio tracks are leaking. Are you releasing the player?

**Comment by Naguchennai** [comment] 2018-03-20 09:16
yes in service when service start and also onDestroy()

    if (player != null) {
			player.stop();
			player.release();
			player = null;
		}

**Comment by Naguchennai** [comment] 2018-03-20 10:24
ok install this app and click next station continuesly ( click next next next  in player page ..fast click)

...Deleted...

or give me you email id i will share source

**Comment by andrewlewis** [comment] 2018-03-20 10:37
Looking through a significant amount of code is going to be too time consuming and we can't really install your app and debug it.

Please provide the output of `adb bugreport`, as requested above, and we can go from there. If you can also provide minimal steps to reproduce based on the ExoPlayer demo app that would also be useful.

**Comment by Naguchennai** [comment] 2018-03-20 10:45
I already posted adb report .. i also attached zip with full bug report
[bugreport-NRD90M-2018-03-20-16-12-31.zip](https://github.com/google/ExoPlayer/files/1828928/bugreport-NRD90M-2018-03-20-16-12-31.zip)


Note: once have this error player stoped completely .. i need close completely and need remove app cache for play again. after that only it work .. close app using finish() it not work .. need clean app cache..

**Comment by andrewlewis** [comment] 2018-03-20 11:33
Did you force stop the app at about 03-20 16:11? If you take a look at the `DUMP OF SERVICE media.resource_manager:` in the bug report there are a whole load of platform resources released at that time, and the resources are associated with your process ID. If you look at the logcat, there are several players created/released with errors before that time, but without errors after it.

It looks like you're correctly creating/releasing your own ExoPlayer instance, based on the logcat. If you disable playback of ads so you're only playing your own content does the problem go away? Could you provide some details about how you're inserting and playing ads? Are you doing all cleanup required by the ad SDK you're using?

**Comment by Naguchennai** [comment] 2018-03-23 10:39
so you cant find out where is problem is ?

**Comment by Naguchennai** [comment] 2018-03-23 10:40
you already closed so many same error with out fixing???? lol

https://www.google.co.in/search?client=opera&hs=IB2&ei=u9i0Wu6fD4fcvgTs7oqICg&q=Internal+track+renderer+error&oq=Internal+track+renderer+error&gs_l=psy-ab.3..0.188969.188969.0.189648.1.1.0.0.0.0.67.67.1.1.0....0...1c.1.64.psy-ab..0.1.67....0.UrGDTjlLwSI

**Comment by andrewlewis** [comment] 2018-03-23 10:43
That error encompasses several different possible failure modes.

If you could answer the questions in my previous comment then we might be able to make some progress on this.

**Comment by Naguchennai** [comment] 2018-03-23 10:46
itd working fine now after removing google skd
compile 'com.google.android.gms:play-services-ads:11.8.0'

i remove all googl ads then its working fine...
can you tell me where is problem is?

**Comment by andrewlewis** [comment] 2018-03-23 10:47
Could you provide some details about how you're inserting and playing ads? Are you doing all cleanup required by the ad SDK you're using?

**Comment by Naguchennai** [comment] 2018-03-23 10:50
i just insert admob banner in my layout only .....

your library crashing with admob ads sdk... take a look i dont know where

**Comment by Naguchennai** [comment] 2018-03-23 11:01
After removing google admob interstitial ads its fixed .. i dont know why.... if you want close this thread close it.. thank you

**Comment by andrewlewis** [comment] 2018-03-23 11:02
Both the AdMob SDK and ExoPlayer rely on the Android media framework. If there's a mistake in your use of the AdMob SDK or a bug in the AdMob SDK that causes a resource leak, that could manifest itself in an error while using ExoPlayer, but obviously isn't necessarily indicative of an ExoPlayer bug.

This issue tracker is only for ExoPlayer issues. As removing the AdMob SDK code resolves the issue, I don't think we have enough evidence that this is an ExoPlayer bug to spend time investigating further at this point.

I suggest double checking that your code follows the contract of the AdMob SDK especially with regard to releasing resources, and, if you can't see anything wrong in your code, post details about the problem on their [help forum](https://groups.google.com/forum/?fromgroups#!categories/google-admob-ads-sdk/android).

If you find evidence that this is likely to be an ExoPlayer bug, please provide it and I'll reopen the issue.

**Closed as completed by andrewlewis** 2018-03-23 11:02 UTC
Labels: need more info
