### ISSUE TITLE
ArrayIndexOutOfBoundsException in HlsSampleStreamWrapper.finishedReadingChunk

### ISSUE THREAD

**Issue by dmitryLukNs** [google/ExoPlayer#2381] opened 2017-01-27 13:05 UTC
UPD
Hi guys. Updated issues in accordance with template.
Until recently, all was well.
Perhaps something has changed on the server and player started to give following error.
I have a link on HLS live stream, if I try to start video at this link, the player throws the error.
I use exoplayer v2.1.1.
Device Nexus 5, Android API 23(6.0.1)
This stream without any problems being played back on the IcePlayer on the desktop.
If you run the query at this link, we get the index file, which contains six links to other index files.
I think the problem is in the first link from that list, because it uses the audio format mp4a.40.5 (HE-AAC)

`REQUEST BY LINK

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=500000,RESOLUTION=480x270,CODECS="avc1.77.30, mp4a.40.5"
http://some_stsream
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=500000,RESOLUTION=480x270,CODECS="avc1.77.30, mp4a.40.2"
http://some_stsream
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1500000,RESOLUTION=848x480,CODECS="avc1.77.30, mp4a.40.2"
http://some_stsream
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1500000,RESOLUTION=848x480,CODECS="avc1.77.30, mp4a.40.2"
http://some_stsream
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2500000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://some_stsream
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2500000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://some_stsream

ERROR

E/ExoPlayerImplInternal: Internal runtime error.
                                            java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
                                                at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.finishedReadingChunk(HlsSampleStreamWrapper.java:325)
                                                at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.readData(HlsSampleStreamWrapper.java:302)
                                                at com.google.android.exoplayer2.source.hls.HlsSampleStream.readData(HlsSampleStream.java:49)
                                                at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:263)
                                                at com.google.android.exoplayer2.metadata.MetadataRenderer.render(MetadataRenderer.java:96)
                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                at android.os.Looper.loop(Looper.java:148)
                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)`

Thanks.

**Comment by AquilesCanta** [comment] 2017-01-27 13:40
As requested in the issue template, please send the stream to dev.exoplayer@gmail.com. I suspect that the stream is dynamically adding a new track in the TS(you can easily notice this), though it is quite strange that the iOS player fails in this case. Please give the last release version a try, as there have been many changes. If my theory is correct, it should still fail, but it minimizes the risk of running into an already fixed bug.

It is really hard for us to evaluate the failure with this amount of information. Please read the issue template. Providing a way for us to reproduce the issue usually answers most questions.

**Comment by AquilesCanta** [comment] 2017-01-27 14:04
If the new track happens to be SCTE 35 Splicing information, the bug will be fixed in the last release version.

**Comment by dmitryLukNs** [comment] 2017-01-30 06:54
I sent url on mail, but I think the life time it has already expired.
That's all I can provide
Because now with the video everything is OK the first link comes with audio format mp4a.40.2

**Comment by ojw28** [comment] 2017-01-30 19:02
I don't think it's likely to be SCTE-35 given: `length=3; index=3`. This indicates the number of sample queues has changed from 3 to 4. I think I'm right to say that we'd expect 4 queues for this media (audio, video, cea608, id3). Of these id3 is generated up front, video and cea608 are generated together when video is found, and audio is generated when audio is found. So I think the only consistent explanation is that the first segment(s) do not contain or declare any audio. They should do so, even if it's silence.

If the above theory is correct then this issue is the same as https://github.com/google/ExoPlayer/issues/2234.

**Comment by ojw28** [comment] 2017-01-30 19:04
Closing on the assumption the theory is correct, since working test content has not been provided.

**Closed as completed by ojw28** 2017-01-30 19:04 UTC
Labels: wont fix: infeasible, bad media
