### ISSUE TITLE
Pixel reboot when playing "Clear -> Enc -> Clear -> Enc -> Enc" playlist in demo app

### ISSUE THREAD

**Issue by yqritc** [google/ExoPlayer#2935] opened 2017-06-12 08:59 UTC
### Issue description
When switching content in playlist from "Enc" to "Clear", player turns to green screen and pixel reboot without any logs.

### Reproduction steps
1. Launch ExoPlayer demo app
2. Select the following playlist in demo app
https://github.com/google/ExoPlayer/blob/r2.4.1/demo/src/main/assets/media.exolist.json#L433
3.  When changing content from enc(widevine) to clear(no-drm), Pixel always reboots its device

### Link to test content
The following demo app playlist
https://github.com/google/ExoPlayer/blob/release-v2/demo/src/main/assets/media.exolist.json#L433

### Version of ExoPlayer being used
release-v2
r2.4.1

### Device(s) and version(s) of Android being used
Model: Pixel
Android version: 7.1.2
Build number: NJH47B

*The following devices does not reboot
Nexus 5X (OS ver: O, Build no: OPP1.170223.012）
Nexus 5(Os ver: 6.0.1, Build no: M4B30X)

### A full bug report captured from the device
No bug report is captured

**Comment by ojw28** [comment] 2017-06-12 09:05
Yes, this is a known issue unfortunately. My understanding is that it'll be fixed in O. The fix hasn't landed yet, so there's no point in you trying to flash O at this point in time. [Internal bug ref: 36511863]

**Comment by yqritc** [comment] 2017-06-12 10:10
thanks for the quick response.
It'll be nice if you can leave the comment here when fixing this issue in O.

**Comment by ojw28** [comment] 2017-06-12 10:51
Please follow #2587 if you're interested in receiving an update when the issue is fixed (they will be fixed at the same time).

**Comment by yqritc** [comment] 2017-06-12 10:55
ok. I'll follow #2587, thanks!

**Comment by ojw28** [comment] 2017-06-23 15:08
Re-opening this because they turned out to be separate issues.

**Comment by yqritc** [comment] 2017-06-25 08:46
@ojw28 
Is this still planning to be fixed in O release?

**Comment by ojw28** [comment] 2017-06-25 13:13
I believe so.

**Comment by yqritc** [comment] 2017-07-04 13:39
As same as #2924, forcing usage of the secure decoder for playback of both the clear and protected content works around the issue.

**Comment by ojw28** [comment] 2017-09-10 20:19
Fixed in Pixel Oreo update.

**Closed as completed by ojw28** 2017-09-10 20:19 UTC
Labels: bug: device specific
