### ISSUE TITLE
Rtmp url not playing in sample of exoplayer

### ISSUE THREAD

**Issue by aktjkt** [google/ExoPlayer#4325] opened 2018-05-30 08:20 UTC
### Issue description
I wanted to create a rtmp player using ExoPlayer Demo application when i trying to play through wowza server its working fine but when trying to play through flash server its getting following error 
E/ExoPlayerImplInternal: Source error.
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

### Reproduction steps
Just given any rtmp url which supports flash media server 

### Version of ExoPlayer being used
I am using 
    implementation 'com.google.android.exoplayer:exoplayer:2.7.3'
    implementation 'com.google.android.exoplayer:extension-rtmp:2.7.3'

### Device(s) and version(s) of Android being used
I am using Redmi mi a1 device having version Android 8 

### A full bug report captured from the device
E/ExoPlayerImplInternal: Source error.
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by ojw28** [comment] 2018-05-30 13:47
Duplicate of https://github.com/google/ExoPlayer/issues/4200

**Closed as completed by ojw28** 2018-05-30 13:47 UTC
Labels: duplicate

**Comment by ojw28** [comment] 2018-05-30 14:08
Please can you provide some sample RTMP streams that reproduce this issue?
