### ISSUE TITLE
Frame advance in exoplayer (What does rendering in exoplayer depend on?)

### ISSUE THREAD

**Issue by Swathi-Thirunarayanan** [google/ExoPlayer#7240] opened 2020-04-15 18:25 UTC
### Related Issue:
[1]  (https://github.com/google/ExoPlayer/issues/7025) 

### What does rendering in exoplayer depend on?
I am trying to achieve frame-advance in exoplayer on key-press. I am forcing the exoplayer to stop rendering after it renders one frame after a key-press by calling stopRenderers() at ExoPlayerImplInternal.java; But the issue is, exoplayer is not rendering the immediate next frame after each key-press. I made sure that during frame-advance it ignores dropOutputBuffer(). But still i wasnt seeing successive frame rendered after key press. Looking into renderOutputBufferV21(), I got to know that, after function call codec.releaseOutputBuffer(index, releaseTimeNs); the frame is rendered on the screen. The function just uses index and releaseTimeNs as its parameter to render onto the screen. So i changed the code such that, after each key-press, releaseTimeNs increments by 1ms. Also i found that index is incrementing by 1 after each key press. But still i wasn't seeing the consecutive frame being rendered. 

1. What all parameters does rendering depend on? 

2. Does PTS and system time has something to do with rendering? 

3. What other parameters do I have to change in-order to render immediate next frame?

4. How does exoplayer pick next frame to render?

**Comment by andrewlewis** [comment] 2020-06-04 09:28
This is probably being (at least partly) addressed in the discussions on #7382 and #7454 so I will mark this as a duplicate to avoid repeated effort.

**Comment by andrewlewis** [comment] 2020-06-04 09:29
Duplicate of #7382

**Comment by andrewlewis** [comment] 2020-06-04 09:29
Duplicate of #7454

**Closed as completed by andrewlewis** 2020-06-04 09:29 UTC
Labels: duplicate
