### ISSUE TITLE
How to preload a part of the video into the memory before the video start play.

### ISSUE THREAD

**Issue by developerzjy** [google/ExoPlayer#8409] opened 2020-12-29 12:43 UTC
When playing a video in the video list, if I want to play the next video, how to play the next video immediately(play immediately instead of loading->player). I know this requires a preload method, but I can not find a suitable method in ExoPlayer.I have found some ways to use CacheUtil, but it is Deprecated in the latest EXO version.On the other hand, CacheUtil is cached to the disk, I think it is unnecessary, because I just want to start play faster, so that caching to the memory is enough.
I ran the exo source demo, but I didn't find a method to preload video into the memory. I tried ConcatenatingMediaSource, it does not implement preloading.
Can anyone share some relating documents or demo code.

[This is my demo.](https://github.com/developerzjy/ExoDemo.git) When I switch videos, how do I play directly without loading?

**Comment by marcbaechinger** [comment] 2020-12-29 14:02
You are right you could do that with caching. A cache that is saving data to the disk is part of the library. See issue #7887 for some more details. You could choose to write your `Cache` implementation that does only store data in memory instead of disk, but I'm not sure what the performance gain would be and if it's worth doing your own implementation.

The solution you are actually looking for is that the player automatically buffers the start of the next item by default. This is a known feature request as per #3327. I'm closing this issue. 

Duplicate of #3327.

Please follow up in one or the other issue mentioned.

**Closed as completed by marcbaechinger** 2020-12-29 14:02 UTC
Labels: duplicate, question
