### ISSUE TITLE
Restrict All Background Data

### ISSUE THREAD

**Issue by gte619n** [google/ExoPlayer#1746] opened 2016-08-16 12:46 UTC
Hello,

I have developed a music application that uses ExoPlayer for HLS streaming (in a service). Up until around ~June it was going great. We had great reviews and our customers were subscribing at good rates. All of a sudden, cancellations doubled, people left nasty comments and we had reports of the player "suddenly stopping."

After a TON of troubleshooting, updating ExoPlayer, working on some other pieces of the app, improving just about everything possible, we finally captured an error: ECONNREFUSED.

After much more server-side trouble shooting, I fired up ADB, proxied through my desktop and started watching the traffic. Everything was working perfect until the application went into the background. MADEUREKA:

![2016-08-15](https://cloud.githubusercontent.com/assets/223900/17699252/b13f7688-638d-11e6-9e0a-4d1f28dcb0cd.png)

It appears that this is now enabled by default on SOME Samsung phones. Hence the explosion of angry users. Is there a way to handle this within Exo? I've not had any luck tracking down much information about this new setting works or how people are handling the scenario. 

Any advice is much appreciated. Honestly, I'm a bit shell shocked that this was the issue after all this time spent debugging!

**Comment by ojw28** [comment] 2016-08-16 12:49
On what information are you basing your assertion that this is enabled by default on some Samsung phones? Can you point to a source?

**Comment by gte619n** [comment] 2016-08-16 12:51
When I started getting desperate, I went and bought an S7. That's when I could reproduce the issue; however, I had to wait for the buffer to run out to see the behavior. Probably why it only affects a subset of power users, as the buffer is very large (~40 minutes).

**Comment by ojw28** [comment] 2016-08-16 12:57
So you're saying it's defaulting to true across a significant number of devices, but also there are no discussions about the subject on the internet? That doesn't feel like it's particularly plausible to me. Nor would I expect a sudden burst of complaints if this were the root cause.

That aside, I think as long as you're a foreground service you probably aren't subject to background data restrictions. You should be a foreground service regardless, otherwise your process might be killed (which is a more likely cause of playback stopping). Is your service a foreground service? If not, make it so. See [here](https://developer.android.com/guide/components/services.html#Foreground).

**Comment by gte619n** [comment] 2016-08-16 13:51
I agree that this all sounds preposterous. To clarify, the service is started by an activity using context.startService( serviceIntent ). The service then begins playing with a startForeground call and the notification is put in the status bar. I can see the notification at all times.

I have attached a [stacktrace](https://github.com/google/ExoPlayer/files/420378/Connection.Error.Stacktrace.zip) of the behavior I'm seeing. The calls to the EventBus are happening in the service itself. The ECONNREFUSED exceptions are happening in the player which is held in the service. I know the service is still running or the EventBus messages wouldn't appear. You can see where the service runs out of buffer and then continues to play while attempting to get more data.

[Connection Error Stacktrace.zip](https://github.com/google/ExoPlayer/files/420378/Connection.Error.Stacktrace.zip)

When I run through a wireshark proxy, I can see the traffic start and stop by toggling the Restrict All Background Data setting. I can replicate it every time. This really does seem to be an issue with this specific setting.

Could the player be holding a thread reference that is not considered foreground somehow? Is there anything else I can test to troubleshoot this issue? I am really really perplexed, to say the least!

**Comment by ojw28** [comment] 2016-08-16 14:10
I don't think you have sufficient evidence to blame the background data restriction. I could be wrong about all of the following, but I think you'd need to confirm that I am before you could justify the claim:
- I don't think foreground services count as "background" for data restriction purposes.
- There is no evidence this setting is enabled by default on a significant number of devices. Lack of evidence suggests that this isn't the case.
- It's unclear that ECONNREFUSED is the result of background data restriction. The fact that it takes 8000ms to hit the failure (according to the logs) kind of suggests that it's not, since if the failure is due to a local constraint there's no reason why it couldn't occur immediately; short of it being implemented in a pretty strange way.
- How have you validated that the server isn't refusing the connection?

**Comment by gte619n** [comment] 2016-08-16 21:16
Went back and did some more testing. I have the buffer sized to about ~3 minutes of playback time. I have tested using a T-Mobile Galaxy S6 and a Nexus 5. I have implemented a wireshark proxy on my development machine and have the application pointing at the proxy, so I can monitor the traffic. The devices are connected over wifi.

The following happens on both devices:
- Disable Background Data Restriction (BDR). Playback works fine on both devices in all scenarios over a ~12 minutes timeframe. Wireshark shows the expected traffic.
- Enable BRD. Start playback with the application in the foreground. Keep the application in the foreground by touching the screen. Playback works over a ~12 minute timeframe. Wireshark shows the expected traffic.
- Enable BRD. Start playback with the application in the foreground, but then immediately switch to the home screen. Playback continues, but the network traffics stops. After ~3 minutes, playback stops, but the foreground notification is still present.
- Enable BRD. Start playback with the application in the foreground, but then immediately switch to the home screen. Playback continues, but the network traffics stops. Immediately bring the application activity to the foreground, network traffic immediately resumes.
- Enable BRD. Start playback, go to home screen. Wireshark traffic stops. Disable BRD. Wireshark traffic starts. Playback continues past the 3 minute mark.

When I say "traffic stops", I mean that no request even hits the proxy server. Somehow, it just never gets off the phone at all.

So, at this point, I'm 100% sure that the setting is stopping the network traffic of the music player while the application activity is not in the foreground. The service has the notification in the status bar the entire time.

What other sorts of things could I check?

**Comment by gte619n** [comment] 2016-08-16 21:28
One other odd sort of traffic pattern I'm seeing is that the application does not reach out for new chunks in a continuous fashion; rather, it seems to be filling the buffer, waiting to exhaust the buffer, then reaching out to refill the buffer when the buffer is nearly exhausted. This pattern is consistent when the network is available, regardless of application state. I would expect the application to pull chunks as the application plays?

**Comment by ojw28** [comment] 2016-08-16 21:55
Interesting. I did find these posts suggesting similar issues:

http://forums.androidcentral.com/samsung-galaxy-s7/655691-music-streaming-stops-pauses-galaxy-s7.html
https://community.spotify.com/t5/Android/Stops-playing-on-Samsung-Galaxy-S7-Edge/td-p/1311156

It surprises me that a foreground service counts as being in the background for data restriction purposes, but your results suggest this is the case, on some devices and/or OS combinations at least :(. The posts above suggest that it's not specific to ExoPlayer or your app. You could try experimenting with explicitly holding [WiFi locks](https://developer.android.com/reference/android/net/wifi/WifiManager.WifiLock.html) and [Wake locks](https://developer.android.com/reference/android/os/PowerManager.WakeLock.html), to see if that makes a difference, but I doubt it. If the system setting is indeed restricting data to the app then I doubt there's a lot you can do. If it were possible for apps to simply ignore a system setting, it would kind of defeat its purpose.

The fill/drain behavior you note in your second post is intentional. In theory batching requests in this way is nicer for network providers, although I don't really know how much truth there is to that statement these days. You can tweak this behavior by passing non-default values to LoadControl.

**Comment by ojw28** [comment] 2016-08-23 18:41
Closing as answered; although if you have further insights we'd be interested to learn of them!

**Closed as completed by ojw28** 2016-08-23 18:41 UTC
Labels: question

**Comment by gte619n** [comment] 2016-08-23 18:49
Will do. Our team is working on it this week.

**Comment by dhaag23** [comment] 2016-08-25 17:52
I'm not sure if this bug fix applies, since it doze related and this doesn't quite seem like doze, but Google has fixed a bug around keeping foreground services alive: https://code.google.com/p/android/issues/detail?id=193802

**Comment by donnfelker** [comment] 2016-10-15 16:08
@gte619n Did you and your team find a resolution to this?

**Comment by gte619n** [comment] 2016-10-17 12:50
Sadly, we didn't find a good solution. We changed the error handling of the player around to look for the active connection when it throws ERR_CONNECTION_REFUSED. If it detects that it's the background data restriction causing it, we gracefully pause the player and throw up an error message with instructions about how to turn it off.

It's not great, but it was the best we could figure out. It seems like a bug in the implementation of the background restriction.
