### ISSUE TITLE
Exoplayer IMA Extension Memory Leaks and SDK Issue

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#5626] opened 2019-03-13 08:30 UTC
### [REQUIRED] Issue description
Memory leaks and SDK version issue in v2.9.6 

### [REQUIRED] Reproduction steps
I just started to implement the IMA extension in my application that has a video streaming feature using Exoplayer and everything works fine until a memory leaks appears when closing the app after this implementation even after calling `adsLoader.setPlayer(null)` in `onStop()` and `adsLoader.relase()` in `onDestroy()`. I am currently using a Single Skippable Inline: 
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=
From the documentation page here: 
https://developers.google.com/interactive-media-ads/docs/sdks/android/tags

Another thing is it seems like the SDK version is outdated, this is what I saw in a stacktrace whenever I play some video.
`Invalid internal message, ignoring. Please make sure the Google IMA SDK library is up to date.`

### [REQUIRED] Link to test content
N/A

### [REQUIRED] A full bug report captured from the device
Here is my full [stacktrace.txt](https://github.com/google/ExoPlayer/files/2960437/stacktrace.txt)

### [REQUIRED] Version of ExoPlayer being used
Exoplayer dependency v2.9.6 

### [REQUIRED] Device(s) and version(s) of Android being used
LG K10 K430dsy Android M 6.0.0

**Comment by andrewlewis** [comment] 2019-03-13 09:09
Do you see the memory leak even after `imaAdsLoader.release()` has been called? (Are you sure `onDestroy` is getting called?)

**Comment by ArcherEmiya05** [comment] 2019-03-13 09:12
Yes `onDestroy()` is getting called and even after calling `imaAdsLoader.release()` still the memory leaks kicks in after closing the app. This memory leaks only occurs after implementing IMA Extension.

**Comment by andrewlewis** [comment] 2019-03-13 09:20
From the logcat attached, `Activity [...] has leaked ServiceConnection com.google.android.gms.common.a@67f33ac that was originally bound here` referring to Play Services `com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo` looks suspicious. Are you able to reproduce this on other devices that have Play Services installed?

**Comment by ArcherEmiya05** [comment] 2019-03-13 09:22
Okay I'll try it on another device, btw I update my report with the links regarding Single Skippable Inline.

**Comment by ArcherEmiya05** [comment] 2019-03-13 09:23
I am currently using 
```
Android Studio 3.5 Canary 7
Build #AI-183.5429.30.35.5346365, built on March 2, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
```

**Comment by ArcherEmiya05** [comment] 2019-03-13 10:19
AllCall W1 Android Smartwatch Alps W1 Android L 5.1.1
Still showing `Invalid internal message, ignoring. Please make sure the Google IMA SDK library is up to date.` but no memory leaks.
Here is the logcat: [stacktrace.txt](https://github.com/google/ExoPlayer/files/2960917/stacktrace.txt)

**Comment by andrewlewis** [comment] 2019-04-07 21:48
The `Invalid internal message` logging is expected in certain situations, and I don't think it indicates a problem here.

This looks like a Play Services issue to me. Is the device up to date in terms of system updates and updates on the Play Store? Were you able to try out any other devices (apart from the smart watch), and if so did you see the memory leak and `Activity [...] has leaked ServiceConnection` on any of those?

**Comment by ArcherEmiya05** [comment] 2019-04-08 14:02
My Google Play Services is in the latest but the device system patch is not, but I do not think it would and should be a problem. Anyway I'll try another device and will immediately post here again.

**Comment by ArcherEmiya05** [comment] 2019-04-24 15:59
Cherry Mobile Flare J5s Android Oreo Go Edition
No memory leaks.
[stacktrace.txt](https://github.com/google/ExoPlayer/files/3113167/stacktrace.txt)

**Comment by maxTanquerel** [comment] 2019-05-24 15:07
I am also detecting a leak, using leak canary. It seems to be the webview present in adsViewGroup that is not released correctly. Like @ArcherEmiya05, I can confirm that `imaAdsLoader.setPlayer(null)` and `imaAdsLoader.release()` are correctly called.

I am also using exoplayer 2.9.6 with IMA 3.11.2
![Screenshot_20190524-110153](https://user-images.githubusercontent.com/17617426/58337539-00d64980-7e14-11e9-9f9c-faf49f280986.png)

**Comment by maxTanquerel** [comment] 2019-05-29 13:38
@andrewlewis : It seems that the leak occurred only when the adsLoader is release when playing an ad. No leak detected when the content is playing. 

I tried to :
- Change the context used to create the adsLoader from AppContext to ActivityContext
- Call stopAds from ImaAdsLoader
- Call contentComplete from AdsLoader in IMA library.

Nothing release the WebView properly. Do you know what can I test ?

**Comment by andrewlewis** [comment] 2019-06-24 16:26
Please disregard the above bot comment. Trying to reproduce this is on my list.

**Comment by ArcherEmiya05** [comment] 2019-07-02 05:17
I will test it again with the same device LG K10 K430dsy since memory leaks happens on this device after implementing ads sdk.

**Comment by andrewlewis** [comment] 2020-05-07 10:48
There is an issue with the ad overlay view leaking, which I've filed #7344 to track. I think this bug may be the same but it's a bit unclear, and the first part of this issue seems to relate to Play Services. I will close this one for now so please follow #7344 instead, or file a new issue if you are confident you are seeing something different.

**Closed as completed by andrewlewis** 2020-05-07 10:48 UTC
Labels: bug: in dependency
