### ISSUE TITLE
How can I use SPDIF Passthrough in exoplayer

### ISSUE THREAD

**Issue by JiannaiJ** [google/ExoPlayer#6586] opened 2019-10-26 03:30 UTC
I read the issues #2148,  but I can't create this feature exactly.  My Android Projector support SPDIF Passthrough to amplifier, use Kodi player to verify this function. I need to force audio to pass through the SPDIF to the amplifier, not the HDMI.

  I've tried many ways, but I can't always achieve this function, and there is little information on the Internet.I hope someone can tell me how to implement this function. Because I don't know much about audio and video development. So it's better to attach reference code. Thank you.

**Comment by tonihei** [comment] 2019-10-31 14:39
I'm not sure I fully understand what kind of feature you are trying to implement here. Could you describe that in more details? 

Assigning to @andrewlewis as he is likely to know more about this.

**Comment by andrewlewis** [comment] 2019-11-11 06:00
Assuming the S/PDIF device appears as a separate output audio device in `AudioDeviceInfo`, this may be a duplicate of enhancement #1993.

**Closed as completed** 2019-11-26 08:56 UTC
Labels: question
