### ISSUE TITLE
Exoplayer2 cannot load the VTT subtitles from HLS  after SeekProcessed

### ISSUE THREAD

**Issue by paavalan** [google/ExoPlayer#4456] opened 2018-06-30 19:37 UTC
I am using Demo exoplayer app from Github . I am trying to play hls video from internet it has vvt subtitles. Video is getting played subtitles showing, but when i forward video then it is not displaying any subtitles.

Version of ExoPlayer being used
2.8.2

**Comment by ojw28** [comment] 2018-07-02 08:44
Most likely the content is not correctly prepared. We can't do anything to help without having a link to the content that reproduces the issue.

**Comment by davidaronpf** [comment] 2018-07-06 19:06
Hello, I have the exact same issue. 
The player loads the video and vtt subtitles from the m3u8 list linked in the hls. If I let the video play from the start, all vtt subtitle files are loaded correctly and presented in the video, but if I foward the video or skip some scenes, the subs don't load for that scene, neither for the entire rest of the video.
I too think that my content is not correctly prepared, but I haven't detected the error in my files, can someone please take a look?

Here is a link to one of my m3u8 subtitles list: http://mpix.tmwpix.com:8080/filmes/itacoisa/legendas/por.m3u8

Here is the link to one of the vtt files in that list:
http://mpix.tmwpix.com:8080/filmes/itacoisa/legendas/por0.vtt

I don't know much about Exoplayer, sorry. Any help is very appreciated.

**Comment by ojw28** [comment] 2018-07-06 20:25
@davidaronpf -  The EXTINF values in your `por.m3u8` are not correct. In particular it specifies that the first segment is `81.221000` seconds long. Which looks like a stray 8, but even after you delete it I think the durations values are just off generally.

**Comment by davidaronpf** [comment] 2018-07-06 21:18
Hmm, I see. So EXTINF is supposed to just be the duration of the segment in seconds right? 
First segment starts at 01:19.177 and ends at 01:21.221. The difference between that is 2.004, so that should be the EXTINF value for it?

Sorry if my questions are dumb, and thanks for the reply.

Edit:
I see that the segment is defined as 81 seconds long because that's the seconds from the start of the movie until the end of the subtitle por0.vtt, even though the actual line from the .vtt is just two seconds long. So is the 81 really wrong?

**Comment by ojw28** [comment] 2018-07-06 21:29
The summed total of all EXTINF values up to the start of a segment must equal the playback position at that segment. Note this mean the durations must include any gaps in which no subtitle is visible. I'd suggest you consult the [HLS RFC](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-02), look at [Apple's sample streams](https://developer.apple.com/streaming/examples/), and [other resources](http://hlsbook.net/how-to-add-subtitles-to-a-live-hls-stream/), since helping with media preparation is beyond the scope of this issue tracker.

**Comment by davidaronpf** [comment] 2018-07-06 21:49
Now I understand. I'll try to fix the EXTINF then to something easier to deal, by splitting better the vtt parts (like 10 second chunks).
Thank you very much for all your help.

**Comment by davidaronpf** [comment] 2018-07-13 13:32
Hi again! I fixed the EXTINF and it worked. When I forward the video, the subtitles still show, which is great!

There's one problem though, that I don't know if it's not related: All subtitles play a second or more before they should, so they also end before they should too. For example, a subtitle that is supposed to play at 01:19 and end at 01:22, instead plays at 01:17 and ends at 01:20.
Do you know what might be the cause?

Thanks in advance for any help.

**Comment by ojw28** [comment] 2018-07-13 13:37
You probably need to add a `X-TIMESTAMP-MAP` metadata header to each VTT file, as described in the [HLS RFC](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-02#section-3.5). Either that or your timing is just incorrect.

I'm going to close this. It's not an ExoPlayer issue, and we don't generally have enough cycles to help debug content. The Apple sample streams have correctly sync'd captions, so I'm pretty sure there's no issue with the player.

**Closed as completed by ojw28** 2018-07-13 13:37 UTC
Labels: question
