### ISSUE TITLE
Live multi-audio H.265 HLS audio out-of-sync with video when the audio track is switched

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#1554] opened 2016-05-26 13:02 UTC
With live multi-audio H.265 HLS streams where audio and video data use different sequence numbers, audio gets out-of-sync with video whenever the audio track is switched and it never recovers. Video also freezes for a while soon after the audio track switch.
This can be synchronized using the first processed sequence number as reference.
The issue can be reproduced with the following steps, in the ExoPlayer dev branch of 25/05/2016 (1.5.8) demo app:
- Start playback of the content
- Switch the audio track

I will provide more information about the how to access the related content by email.
This was detected in an LG Nexus 5 / Android 6.0.1

**Comment by moacir69** [comment] 2016-05-26 13:02
[bugReport.txt](https://github.com/google/ExoPlayer/files/284390/bugReport.txt)

**Comment by moacir69** [comment] 2016-06-09 11:24
Good afternoon,
Do you have any update regarding this issue?
Kind regards,

Moacir

**Comment by ojw28** [comment] 2017-01-13 18:24
This is most likely fixed in the latest V2 release, since we've made some fixes for AV sync that apply to the multi-audio HLS case. If the issue remains, please provide test content so that we can reproduce.

**Closed by ojw28** 2017-01-13 18:24 UTC

**Comment by AquilesCanta** [comment] 2017-01-16 09:33
I didn't know there was an issue related to this, otherwise I would have added a reference. Do try the latest version and let us know if the issue persists. Unfortunately, this fix is not available in V1.
