### ISSUE TITLE
onPlayerStateChanged return playbackState error when i stop audio for long time

### ISSUE THREAD

**Issue by haochen12** [google/ExoPlayer#5548] opened 2019-02-21 00:59 UTC
### Issue description
i play audio ,stop it for long time,i play this audio again ,retrun playbackstate is Player.STATE_ENDED,it lead to i can not finish playing audio.

### Reproduction steps
stop audio for long time and play it again ,try some times.

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #1234".

### Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".

my code:
```java
SimpleExoPlayerView playerView = new SimpleExoPlayerView(IFlyTMApplication.getInstance());
        playerView.setPlayer(player);

        Uri mp3Uri = Uri.parse(audioPath);
        DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(
                IFlyTMApplication.getInstance(), Util.getUserAgent(IFlyTMApplication.getInstance(), "smartbook"));
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        mediaSource = new ExtractorMediaSource(
                mp3Uri, dataSourceFactory, extractorsFactory, null, null);
        player.prepare(mediaSource);
        player.setPlayWhenReady(true);
        player.addListener(new PlayerEventListener());
```
### Device(s) and version(s) of Android being used
android 5.1 exoplayer 2.5.4

**Comment by haochen12** [comment] 2019-02-21 01:01
when i play audio ,stop it for long time,repeat it some time return Player.STATE_ENDED,but audio is not finished,please tell me how to solve it ,thanks in advance .

**Comment by andrewlewis** [comment] 2019-02-21 09:39
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

In particular we need a full bug report and information on what device(s) you've tested on.

**Comment by haochen12** [comment] 2019-02-21 11:28
I play an audio,stop for two minutes,and i continue playing the audio, playbackstate become Player.STATE_ENDED, should be Player.STATE_BUFFERING. @andrewlewis

**Comment by haochen12** [comment] 2019-02-26 08:01
how to know the audio  play completely. @andrewlewis

**Comment by andrewlewis** [comment] 2019-02-26 10:14
@haochen12 Please try to reproduce the error in the demo app and provide the output of `adb bugreport`, provide a link to the media and let us know what device(s) you are testing on.

**Comment by ojw28** [comment] 2019-04-05 20:22
Closing due to lack of requested information.

**Closed as completed by ojw28** 2019-04-05 20:22 UTC
Labels: need more info
