### ISSUE TITLE
ExoPlayer remains in buffering state infinitely after sometime (100 % reproducible )

### ISSUE THREAD

**Issue by itsAmud** [google/ExoPlayer#2521] opened 2017-03-02 07:59 UTC
- ExoPlayer remains in buffering state infinitely after sometime for some videos even if the video     buffered percentage is 100% and video buffer position is equal to max duration of video. Same video  was working fine with Exoplayer release-1.
- Tried to play video url with ExoPlayer sample application.
  Demo video url : https://img0.ropose.com/video/yrIBmLa/Be46_1487445358869_5b477613_a260.webm
https://img0.ropose.com/video/yrIBmLa/Be46_1487445358869_5b477613_a260.mp4
- Facing issue in Exoplayer-2. (Same was working with Exoplayer-1) 
- Tested on Moto E2 (Android 6.0) , One plus one (Android 6.0.1) (Reproducible for almost every device)

**Comment by AquilesCanta** [comment] 2017-03-02 11:03
Both videos work well on both V1 and V2 (latest versions). Please make sure you are using an updated version. If that solves your problem, please close the issue. When you say:

> Reproducible for almost every device

you mean the issue or the media? I didn't have any inconveniences with nexus 5x.

**Comment by itsAmud** [comment] 2017-03-02 11:31
I have tried playing this video in sample app by pulling branch : release-v2
Please note : Video length is approx 10s. Video plays fine in starting but went in infinite buffering state after 6s.

**Comment by itsAmud** [comment] 2017-03-05 13:07
@AquilesCanta : please let me know whether you were able to reproduce the issue.
Thanks.

**Comment by AquilesCanta** [comment] 2017-03-06 14:05
I have just tried and not been able to reproduce the issue on release-v2. Please be concrete about:

> Reproducible for almost every device

It does not reproduce on 5X, Galaxy S6 or Android One.

**Comment by slezadav** [comment] 2017-03-10 09:02
Very similar issue happening to me on huawei p8-lite , with r2.2.0 of the exoplayer

**Comment by yahim91** [comment] 2017-03-18 09:05
Hi,
I also encounter this issue when playing a video recorded with camera2 and using LoopingMediaSource. The video is played from the external storage. The player stays in STATE_BUFFERING and does not reach the end of the video. Also the loop does not work. I modified the demo app to use my video and I also encountered the bug.
The video url is https://drive.google.com/file/d/0B2BhYxjwNC7ecFVuSUN5d3dYYjg/view?usp=sharing.
But as I said, I encounter this issue when loading the file from external storage, I didn't tested with remote urls. I use Nexus 5X with Android 7.1.1.
You should also take a look at video metadata, maybe camera2 video recording is the problem.

**Comment by AquilesCanta** [comment] 2017-03-20 10:54
@yahim91 The file plays well for me in the DemoApp using my Nexus5x running 7.1.1. @yahim91  and @slezadav , please file a new issue including all the information requested in the issue template if your issues persist.

I am closing this issue due to inactivity in the scope of the original report.

**Closed as completed by AquilesCanta** 2017-03-20 10:54 UTC
Labels: need more info
