### ISSUE TITLE
Pine A64 - Portrait video renders incorrectly

### ISSUE THREAD

**Issue by ejbp** [google/ExoPlayer#1800] opened 2016-09-06 08:09 UTC
- A description of the issue.
  MOV files 1920x1080 plays duplicated in same window. I tested exoplayer demo app and all videos goes well, including others that I've added (.mp4 files) except .mov files that doesn't play well and, by the way, any video from "wide vine Dash: mp4,h265" tab only plays audio with a black screen (no video at all). This last one, it's another issue, though.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer
  demo app.
  
  I'm playing a local file placed in /sdcard/Movies folder
- A link to content that reproduces the issue. 

![img_2639](https://cloud.githubusercontent.com/assets/2060105/18265779/4ce04ee6-740f-11e6-8c0e-68e665c0c429.JPG)
![img_2638](https://cloud.githubusercontent.com/assets/2060105/18265781/5228f402-740f-11e6-8f40-82407b9712a8.JPG)
- The version of ExoPlayer being used.
  package="com.google.android.exoplayer.demo"
  android:versionCode="1510"
  android:versionName="1.5.10"
- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.

Model number: Pine A64
Processor type: QuadCore-A64
Android version: 5.1.1
Firmware version: v1.2.6
Kernel version: 3.10.65 light@Chiphd #64 (Thu Jul 7 11:20:25 CST 2016)
here is the download link: http://files.pine64.org/os/android/android-ver5.1.1-20160711-pine64-64GB.zip 
- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". 

[bug-report.txt](https://github.com/google/ExoPlayer/files/456218/bug-report.txt)

**Comment by andrewlewis** [comment] 2016-09-07 16:19
Is this reproducible on any other devices? If not, it is probably a device-specific bug with how the video is being rendered, so please check if there are any system updates available for the device. 

To investigate further we need a link to a stream that doesn't play correctly.

If I understand correctly, streams using MP4 containers play fine but playing streams in MOV containers are broken as in the screenshot. Is there anything else that is different in the streams that are broken besides the container format, e.g. the video codec or resolution? For what it's worth, there are some native crashes earlier in the bug report (which seem to be from VLC) and appear to relate to the video dimensions, like `DEBUG   : Abort message: 'frameworks/av/media/libstagefright/ACodec.cpp:3664 CHECK_LE( rect.nTop + rect.nHeight - 1,videoDef->nFrameHeight) failed: 1087 vs. 1080'`. I guess it's possible that this is related if you were trying to play the same stream in VLC.

**Comment by ejbp** [comment] 2016-09-14 05:51
[Apologize my late answer but I didn't have another android device with me]

**"Is this reproducible on any other devices? If not, it is probably a device-specific bug with how the video is being rendered, so please check if there are any system updates available for the device."**

I've tried in an android smartphone with one movie that was giving this issue in the pine64 and it doesn't happen meaning the video plays well.

**"To investigate further we need a link to a stream that doesn't play correctly:"** 

A movie that doesn't play well running Exoplayer in pine64 (captured with iPhone 6 ):
[IMG_2665.MOV.zip](https://github.com/google/ExoPlayer/files/471320/IMG_2665.MOV.zip)

You can check the behaviour with this video in this link:
[result_.mov.zip](https://github.com/google/ExoPlayer/files/471323/result_.mov.zip)
note: when it's buffering (when the video is stopped) the image appears well but immediately after starts to play the issue appears.

I've made some additional tests too [running Exoplayer in pine64]:

1)
I've converted the IMG_2665.MOV with quicktime to
1080x1920 (same resolution but in the player log shows as 1080x1920 not as 1920x1080)
720p
480p
and all videos plays well.

2)
I've figured out that if I capture the movie in Landscape it plays well (captured with iPhone 6):
Link: [https://drive.google.com/file/d/0Bx62BNfVLJZDSG0wVWcxSjFQN1U/view?usp=sharing](https://drive.google.com/file/d/0Bx62BNfVLJZDSG0wVWcxSjFQN1U/view?usp=sharing)

Though, if I do it in portrait the issue happens. Here is another movie that is giving problems (captured with iPhone 6):
Link:  [https://drive.google.com/file/d/0Bx62BNfVLJZDUW1oZThFR05iamc/view?usp=sharing](https://drive.google.com/file/d/0Bx62BNfVLJZDSG0wVWcxSjFQN1U/view?usp=sharing)

**"If I understand correctly, streams using MP4 containers play fine but playing streams in MOV containers are broken as in the screenshot."**
All plays well except the ones (.MOV) that I capture in portrait (tested only capturing them with iPhone6). You can also check by the movie that I've sent regarding the behaviour of the video that when it's buffering (when the video is stopped) the image appears well.

**"Is there anything else that is different in the streams that are broken besides the container format, e.g. the video codec or resolution?"**
No. The rest is great.

Regarding your last note, including the libVLC is a mess in mobile and I quit from libVLC as I was having problems with most of videos (including mp4). Probably missing codecs but hey, Exoplayer exists, so why to spend more time with libvlc?! 

#pine64 #exoplayer #android

**Comment by ojw28** [comment] 2016-09-15 14:31
This looks like a pine64 specific issue with the H264 video decoder. My best guess it that the decoder fails to handle rotation metadata correctly. Portrait videos are typically encoded as landscape videos with a piece of metadata indicating that the content should be rotated for playback. This rotation value is provided to the decoder at playback by ExoPlayer. It appears that the decoder on this specific device is not able to perform the rotation correctly.

Please report the issue directly to the device manufacturer and see what they make of it. Thanks!

**Comment by ojw28** [comment] 2017-01-13 18:40
Closing since this issue isn't something we can fix in ExoPlayer; it would be up to the device manufacturer to provide a fix via a platform software update.

**Closed as completed by ojw28** 2017-01-13 18:40 UTC
Labels: bug: device specific
