### ISSUE TITLE
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)

### ISSUE THREAD

**Issue by GluTbl** [google/ExoPlayer#5382] opened 2019-01-15 04:03 UTC
Hello sometime my player streaming dash manifest face some problem.
i dont know why this issue is there.
sometime it works...sometime it dont work... 

```
2019-01-15 09:27:23.425 12203-14314/? E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001000)
2019-01-15 09:27:23.425 12203-14314/? E/ACodec: signalError(omxError 0x80001000, internalError -2147483648)
2019-01-15 09:27:23.425 12203-14313/? E/MediaCodec: Codec reported err 0x80001000, actionCode 0, while in state 6
2019-01-15 09:27:23.429 12203-14273/? E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2570)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2019-01-15 09:27:23.435 12203-14314/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f79be2440
2019-01-15 09:27:23.435 12203-14314/? W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 14 to native window
2019-01-15 09:27:23.436 12203-14314/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f79be24a0
```

**Comment by erdemguven** [comment] 2019-01-17 22:23
Duplicate of #5173

**Closed as completed** 2019-01-17 22:23 UTC
Labels: duplicate
