### ISSUE TITLE
Variable LoadControl 

### ISSUE THREAD

**Issue by komissarovdenis** [google/ExoPlayer#2804] opened 2017-05-10 15:44 UTC
Would you mind to make LoadControl more flexible to get opportunity to change buffering timeline during the playback?

It maybe useful for such cases like that: you have a list with videos and a few seconds buffer ahead for traffic economy and quick start. But if user like to choose some video from this list to watching (in fullscreen mode without reinit the player, just seamless transition) it's necessary to change LoadControl values to have a more buffered date ahead for comfortable watching

Thank you guys for a great lib!

**Comment by ojw28** [comment] 2017-05-10 16:02
I'm not sure what "more flexible" means in concrete terms. Please could you specify exactly what you'd like to see changed?

Note that you can implement and inject your own `LoadControl` implementation if you want a custom buffering policy, so unless the interface itself isn't flexible enough then I think it's already possible for you to do what you're trying to do.

**Comment by komissarovdenis** [comment] 2017-05-10 16:16
I mean you can change the parameters of the LoadControl impl during the player lifecycle without side effects during playback.

I tried some time ago on version 2.2.0 to make my own impl on this interface but changing the values of buffers brakes the player (I used HLS source and tuned the buffer from 5 up to 60 seconds). It's freezes on the last buffered frame but playback continues with the sound. Sometimes seeking helps to fix it. I decided that it is not supported to change those params but maybe it's a bug.

**Comment by ojw28** [comment] 2017-05-10 16:20
I don't see any reason why you shouldn't be able to make your own implementation that allows changing of the values (as long as you take care to do it in a thread safe way). I wouldn't expect a custom `LoadControl` to cause the issues you describe. If you're able to provide a simple patch to the demo app that lets us reproduce what you've done and the issue you're seeing, then we'd take a look at that for you.

**Comment by komissarovdenis** [comment] 2017-05-10 16:22
Yes, sure. I will provide demo soon. Thank you.

**Comment by komissarovdenis** [comment] 2017-05-10 18:46
So, there's test commit https://github.com/komissarovdenis/ExoPlayer/commit/f6bd0cd9333d6a31c4953ef6349ba60bc828582d#diff-84acd8dd0150dbbf53399c749c4bcaf4R639

The main question is what I have to do to update ```allocator``` when timings changed?
```
    public void changeBufferMs(int minBufferMs, int maxBufferMs) {
      minBufferUs = minBufferMs * 1000L;
      maxBufferUs = maxBufferMs * 1000L;
      // call something for update
    }
```
In that case player will stuck, of course

**Comment by ojw28** [comment] 2017-05-11 00:35
I'm not able to reproduce the issue with the patch you've provided. I see playback just get stuck buffering (both audio and video stop), but that's working as intended because the patch sets the buffer to an unusably low duration when the button is pressed. The patch doesn't appear to be an accurate reflection of what you're actually trying to do, since it makes the buffer smaller* rather than bigger.

To investigate issues like this we need clear reproduction steps. For example a patch to the demo app that actually does what you're trying to do, and can be used to reproduce the issue you're seeing following clearly defined steps. Closing this issue for now, since I don't think we have that. If you're able to provide this then please let us know.

\* Note that LoadControl only determines whether more media is buffered, and so when specifying a smaller buffer the way this works is that the buffer naturally drains down to the new reduced limits as playback continues. It is not the case that LoadControl can proactively cause already buffered media to be removed from the buffer for this case.

**Closed as completed by ojw28** 2017-05-11 00:35 UTC
Labels: need more info
