### ISSUE TITLE
DecoderInitializationException after returning from AdMob interstitial ad

### ISSUE THREAD

**Issue by emerging-coders** [google/ExoPlayer#5856] opened 2019-05-09 05:16 UTC
I am playing video with ExoPlayer and showing Google AdMob interstitial ad.
After ad has been gone there was trouble to play video and show error like:

```
Playback error.
   com.google.android.exoplayer2.ExoPlaybackException
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:441)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
    Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [720, 420, -1.0], [-1, -1])
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920) 
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:193) 
       at android.os.HandlerThread.run(HandlerThread.java:65) 
```

I am using these libraries:

```
implementation 'com.google.android.exoplayer:exoplayer:2.8.1'
implementation 'com.google.android.exoplayer:exoplayer-ui:2.8.1'
```

**Comment by marcbaechinger** [comment] 2019-05-09 16:05
It seems that initialisation of the codec fails after the ad has been played. It's likely that the codec has not been released and you want to initialize again.

Is the interstitial ad a video ad as well?

If so and you are using a second player instance to play the add it is likely that the ad player did not properly release the codec before the content player tries to initialise the codec again.  So you need to properly release the player.

**Comment by emerging-coders** [comment] 2019-05-11 04:56
Yes! obviously I am using video interstitial ad of google admob. This error causes when after ad has been gone and Exoplayer is stop working.

**Comment by andrewlewis** [comment] 2019-05-11 13:42
This looks similar to #5582. Where do you initialize the player after returning from the interstitial ad? If you're initializing the player in a lifecycle callback, could you try posting a runnable that initializes the player instead, as suggested in that issue, and let us know if that makes a difference? Thanks.

**Comment by ojw28** [comment] 2019-06-21 18:13
Can this be closed as a duplicate of #5582?

**Closed as completed** 2019-07-01 10:16 UTC
Labels: duplicate

**Comment by AntonAndev** [comment] 2019-08-03 15:51
today I got many complains, since 1st August Admob started to show some ads, may be more video ads, exoplayer crashes more often, I can't reproduce this on my devices. This is crazy situation. I can't disable ads because I need to pay for video hosting.

**Comment by andrewlewis** [comment] 2019-08-05 07:51
@Andevity do the crashes have similar stack traces to the original post on this issue? If not, could you provide some more details and I'll follow up with the AdMob team. Thanks.

**Comment by emerging-coders** [comment] 2019-09-09 12:40
Here what actually error occurs in Admob's Interstitial Ad:
```
ExoPlayerImplInternal: Renderer error.
    com.google.android.gms.internal.ads.zzgd
        at com.google.android.gms.internal.ads.zzkl.zza(com.google.android.gms:play-services-ads@@18.2.0:100)
        at com.google.android.gms.internal.ads.zzkl.zzgo(com.google.android.gms:play-services-ads@@18.2.0:92)
        at com.google.android.gms.internal.ads.zzkl.zzd(com.google.android.gms:play-services-ads@@18.2.0:382)
        at com.google.android.gms.internal.ads.zzoq.zzd(com.google.android.gms:play-services-ads@@18.2.0:236)
        at com.google.android.gms.internal.ads.zzkl.zzb(com.google.android.gms:play-services-ads@@18.2.0:231)
        at com.google.android.gms.internal.ads.zzgl.handleMessage(com.google.android.gms:play-services-ads@@18.2.0:243)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.gms.internal.ads.zzko: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [1280, 720, -1.0], [-1, -1])
        at com.google.android.gms.internal.ads.zzkl.zzgo(com.google.android.gms:play-services-ads@@18.2.0:92) 
        at com.google.android.gms.internal.ads.zzkl.zzd(com.google.android.gms:play-services-ads@@18.2.0:382) 
        at com.google.android.gms.internal.ads.zzoq.zzd(com.google.android.gms:play-services-ads@@18.2.0:236) 
        at com.google.android.gms.internal.ads.zzkl.zzb(com.google.android.gms:play-services-ads@@18.2.0:231) 
        at com.google.android.gms.internal.ads.zzgl.handleMessage(com.google.android.gms:play-services-ads@@18.2.0:243) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1778)
        at com.google.android.gms.internal.ads.zzoq.zza(com.google.android.gms:play-services-ads@@18.2.0:218)
        at com.google.android.gms.internal.ads.zzkl.zzgo(com.google.android.gms:play-services-ads@@18.2.0:81)
        at com.google.android.gms.internal.ads.zzkl.zzd(com.google.android.gms:play-services-ads@@18.2.0:382) 
        at com.google.android.gms.internal.ads.zzoq.zzd(com.google.android.gms:play-services-ads@@18.2.0:236) 
        at com.google.android.gms.internal.ads.zzkl.zzb(com.google.android.gms:play-services-ads@@18.2.0:231) 
        at com.google.android.gms.internal.ads.zzgl.handleMessage(com.google.android.gms:play-services-ads@@18.2.0:243) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```
This error continuously occurs in Interstitial ad and that's causes `Decoder init failed`. So, after that our app's ExoPlayer also being throw `Decoder init failed`. Without video ad ExoPlayer works smoothly and play videos as it is.

**Comment by andrewlewis** [comment] 2019-09-09 13:00
@emerging-coders Does your app keep an initialized player while it shows the interstitial ad? It looks like there aren't enough resources to play the ad.

**Comment by emerging-coders** [comment] 2019-09-10 05:56
We know that in devices there is limited decoder capabilities. But what we can do for release ExoPlayer of an Interstitial ad? There is nothing to do with Interstitial ad to release resources! But Facebook Audience Network Interstitial ad provides `interstitialAd.destroy();` method to release resources!! Why Admob's Ad not provides!!

**Comment by andrewlewis** [comment] 2019-09-22 22:24
@emerging-coders We can't really provide support on AdMob here, but as far as I know it does actually provide a destroy method (see [this page](https://developers.google.com/admob/android/rewarded-video)).
