### ISSUE TITLE
SubtitleView custom layout measurement

### ISSUE THREAD

**Issue by komissarovdenis** [google/ExoPlayer#4788] opened 2018-09-07 12:46 UTC
When you have a `SubtitleView` with custom layout measurement (Parent view has match_parent for both dims and `SubtitleView` has smaller size and positioned in center) `SubtitlePainter` will draw cues somewhere outside of `SubtitleView`'s viewport and you'll see nothing.

Bug is probably located in `SubtitlePainter ` in method `setupTextLayout()` on the line 346
`textTop = parentBottom - textHeight - (int) (parentHeight * bottomPaddingFraction);`
it's necessary to decrement `parentTop` as well.
Should be: `textTop = parentBottom - parentTop - textHeight - (int) (parentHeight * bottomPaddingFraction);`

Version 2.8.4
Thanks

**Comment by tonihei** [comment] 2018-09-07 12:58
Not sure this is correct. The text is positioned relative to the bottom edge of the parent. Thus we subtract the height of the text and the padding from the bottom edge to get the top of the text. This is independent of the top of the parent and it may mean that the position "overflows" the top. 

Could it be that your SubtitleView is just too small to fit the text? Try changing the bottom padding fraction (`subtitleView.setBottomPaddingFraction`) and/or the text size (`subtitleView.setFractionalTextSize` or `subtitleView.setFixedTextSize`).

**Comment by komissarovdenis** [comment] 2018-09-07 13:18
Let me try to explain how views actually look:
1. Video Texture fits all the screen, but actually rendering may not cover all it's area (for example: screen 1080x2220 and typical video 16:9 is rendering like 1080x608 and other area is just black). It's necessary to have such a big texture to be able make animated transitions/scales/crops/etc from one screen to another.
2. If SubtitleView measured like 1080x2220 then we have a huge size of text and it's not I'am expect.
    If it is measured to video frame size 1080x608 and located in screen center over video then there's a bug when cues rendered somewhere bottom outside subtitle's view.

**Comment by tonihei** [comment] 2018-09-07 13:35
I think I understand your problem. Please try to change the padding or text size as suggested above. 
If you think this doesn't help, please try to explain your problem some other way.

**Comment by komissarovdenis** [comment] 2018-09-11 08:47
I tried to manipulate with paddings, fractions and text sizes - there's no difference at all.

So, I prepared a small test (based on your demo) to show in practice:
https://github.com/komissarovdenis/ExoPlayer/commit/0bea7972c8008c1be15f8c58b5c0eb2473d7d337

1. I added an HLS link to content with subtitles
2. Moved out subtitles view from ratio container to emulate case when subtitle view has different proportions comparing with surface
You can try to compile code without decrementing `parentTop` and check "visibility" of cues.
More over: this fix make no changes (shifts) for default use like a child of ratio layout.

**Comment by tonihei** [comment] 2018-10-02 16:57
Thanks for demo (and sorry for the delay!). I now understand the issue and it seems indeed to be a bug in our code. We'll provide a fix for that soon.

**Comment by tonihei** [comment] 2018-10-11 15:22
Closing because the issue is fixed by the commit above.

**Closed as completed by tonihei** 2018-10-11 15:22 UTC
Labels: bug
