### ISSUE TITLE
HLS seek stops VOD

### ISSUE THREAD

**Issue by malwoong** [google/ExoPlayer#1444] opened 2016-04-14 11:47 UTC
I'm currently trying to replace VideoPlayer by ExoPlayer in our app, which displays VoD and live content, via HLS streams.

I made reference to demo ver rl.5.7. Contents type is Util.TYPE_OTHER and using urls("https://... .mp4") to stream.

When I try to seek forward or backwards(seekTo), the stream stops playing.

It just stays at ExoPlayer.STATE_IDLE.

Any help would be appreciated.

Our VOD stream links : 
https://player.vimeo.com/external/162328830.hd.mp4?s=84715da70a4f4399b681feab48a514b9879f6072&profile_id=174

https://player.vimeo.com/external/162795289.hd.mp4?s=da224cf9562fe2b6fc05e0634fe8eeb00d2dbd72&profile_id=174

https://player.vimeo.com/external/162795284.hd.mp4?s=2151e0a46e2667deb2193234ea97a8c75c17adcf&profile_id=174

**Comment by ojw28** [comment] 2016-04-14 12:24
If I take the demo app and enter these smaples in `Samples.java` then they play back fine, seeking included. Please describe exactly how to reproduce the issue in ExoPlayer's demo app, and provide a full bug report as requested in the issue template, or we will be unable to investigate further.

**Comment by ojw28** [comment] 2016-04-21 17:22
Closing due to insufficient information.

**Closed** 2016-04-21 17:22 UTC
Labels: need more info

**Comment by maven-y** [comment] 2017-06-05 07:25
I tried with this link https://player.vimeo.com/external/162328830.hd.mp4?s=84715da70a4f4399b681feab48a514b9879f6072&profile_id=174

I never plays vimeo vidoes.


>06-05 12:51:02.517 18502-18502/? E/Zygote: v2
06-05 12:51:02.527 18502-18502/? W/SELinux: Function: selinux_compare_spd_ram, index[1], priority [2], priority version is VE=SEPF_SECMOBILE_6.0.1_0013
06-05 12:51:02.527 18502-18502/? W/SELinux: SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.google.android.exoplayer2.demo 
06-05 12:51:02.747 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:02.837 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:02.937 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_1_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_1_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:03.047 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:03.137 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:03.227 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:03.317 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:03.407 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:03.497 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:03.597 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:03.687 18502-18502/com.google.android.exoplayer2.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/app/com.google.android.exoplayer2.demo-1/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.android.exoplayer2.demo-1@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
06-05 12:51:03.797 18502-18502/com.google.android.exoplayer2.demo E/MotionRecognitionManager: mSContextService = null
06-05 12:51:03.797 18502-18502/com.google.android.exoplayer2.demo E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@3d30af3
06-05 12:52:06.917 18502-18502/com.google.android.exoplayer2.demo E/EventLogger: internalError [29.02, loadError]
                                                                                 com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: timeout
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:269)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:128)
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:70)
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:79)
                                                                                     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:252)
                                                                                     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:147)
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:643)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.net.SocketTimeoutException: timeout
                                                                                     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:216)
                                                                                     at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                                                     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                                     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:60)
                                                                                     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:466)
                                                                                     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:374)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:571)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:267)
                                                                                     at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:128) 
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257) 
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:70) 
                                                                                     at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:79) 
                                                                                     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:252) 
                                                                                     at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:147) 
                                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:643) 
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
06-05 12:52:20.657 18502-18689/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/mpeg-L1
06-05 12:52:20.657 18502-18689/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/mpeg-L2
06-05 12:52:20.657 18502-18689/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/x-ms-wma
06-05 12:52:20.657 18502-18689/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/x-ima
06-05 12:52:20.657 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
06-05 12:52:20.667 18502-18689/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/evrc
06-05 12:52:20.667 18502-18689/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/qcelp
06-05 12:52:20.667 18502-18689/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/qcelp
06-05 12:52:20.667 18502-18689/com.google.android.exoplayer2.demo W/AudioCapabilities: Unsupported mime audio/evrc
06-05 12:52:20.677 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/wvc1
06-05 12:52:20.677 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
06-05 12:52:20.687 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
06-05 12:52:20.687 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/wvc1
06-05 12:52:20.687 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
06-05 12:52:20.697 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
06-05 12:52:20.697 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
06-05 12:52:20.697 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/mp43
06-05 12:52:20.727 18502-18689/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/sorenson
06-05 12:52:37.687 18502-18502/com.google.android.exoplayer2.demo W/ExoPlayerImplInternal: Ignoring messages sent after release.


Pls share how they will work.

**Comment by AquilesCanta** [comment] 2017-06-05 09:45
@malvin91, the link you include plays well in the demo app. 

Add your link to the demo app and go from there. If you need to report an issue, please don't use a closed issue. And please don't forget to include all the information requested in the issue template. Otherwise it will probably be closed automatically.

**Comment by maven-y** [comment] 2017-06-05 09:51
OK thanks for reply. Should I report a new issue to it ?

**Comment by AquilesCanta** [comment] 2017-06-05 09:53
Please try it in the demo app, first. It plays well for me.
