### ISSUE TITLE
Failed to open session: General DRM error 

### ISSUE THREAD

**Issue by ram992** [google/ExoPlayer#4674] opened 2018-08-17 09:19 UTC
Hello @ojw28, this is a question basically,

I am getting this error on almost all major devices and the cause of it is a bit confusing to me.

I use Modular DRM content and pass a drmSessionManager as shown in the demo app.
and also create a MediaDRM object like this 
`mediaDrm = new MediaDrm(C.WIDEVINE_UUID);`
`securityLevel = mediaDrm.getPropertyString("securityLevel");`
to get the securityLevel of the device so that I can be sure that the device plays DRM content. 

The content plays fine but suddenly this error 
`drm license failed android.media.MediaDrm$MediaDrmState Exception: Failed to open session: General DRM error` 
gets logged by the ExoPlayer and the content stops playing. I have observed that the issue goes away when I restart my Device.
So, my question is what is causing the issue, 
Is it the DRM session that the player opens but fails to close cause of my code issue or is it this
`mediaDrm = new MediaDrm(C.WIDEVINE_UUID);` that causes the issue, as I do not call a close/ end session kind of thing for this.
Also I have referred this issue, #1178. and I think I have the same issue but mine is not content specific as it happens with all the content.
Can you suggest me a solution for this

**Comment by ojw28** [comment] 2018-08-19 18:41
Please can you provide complete details of the problem, as requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). We'll then route the issue to Widevine for diagnosis.

**Comment by ojw28** [comment] 2018-08-19 18:45
> Also I have referred this issue, #1178. and I think I have the same issue but mine is not content specific as it happens with all the content.

If you're encoding/transcoding all of your content using the same pipeline, and if that pipeline is doing something wrong, then you'd probably expect all of your content to be affected. A good test might be to see whether you can reproduce the problem using the DRM protected sample content in the demo app. If not, but if you can reproduce with your content, that might suggest your content has an encoding/transcoding issue.

**Comment by ram992** [comment] 2018-08-20 05:02
Hello @ojw28 thanks for the reply. As I told you, the issue got fixed as soon as I restarted the device. I will try to reproduce it but would require few days, and give you the Log.
What I want to know is, whether creating the **MediaDrm Object** for what ever purposes, will create a DRM session ? Or Is it that only the ExoPlayer Code where I ask it to create a **drmSessionManager** will create one.

**Comment by ojw28** [comment] 2018-08-20 06:36
As far as I know, calling `MediaDrm.openSession` is what opens a session. I don't think just creating a `MediaDrm` instance will open a session.

**Comment by ram992** [comment] 2018-08-20 06:49
Well, I am not calling that one, then can it be caused by improper handling of releasePlayer(). And can I check in Logs when will ExoPlayer calls openSession and closeSession, so that I may know it the issue is with my code.

**Comment by ojw28** [comment] 2018-08-20 09:22
* You must remember to release the player (by calling `release` on it).
* You should also remember to call `release` on the `MediaDrm` object, although I don't think that I'd expect anything too bad to happen if this is forgotten.
* Note that `PlayerActivity` in our demo app does both of these things, so take a look if you want some sample code.

As long as you're releasing these two things correctly, then I think your code is probably fine.

**Comment by ram992** [comment] 2018-08-21 03:31
Thank @ojw28 I am release the player, but not calling the release on MediaDrm. Will reproduce once without it and then will try again by putting that part. 
Will share the ADB report shortly

**Comment by ram992** [comment] 2018-08-22 08:28
Hello @ojw28 I am getting this error in Nokia Devices that are updated to the Android P preview Build
`com.google.android.exoplayer2.drm.UnsupportedDrmException: android.media.UnsupportedSchemeException: Failed to instantiate drm object.
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.newInstance(FrameworkMediaDrm.java:57)`

Is there a fix for it. Also I will be sharing the bug report to your mail ID.

**Comment by ojw28** [comment] 2018-08-22 15:55
You should report the issue to Nokia (or whoever is distributing the preview build that you're using).

**Comment by ram992** [comment] 2018-08-23 03:56
I've sent a Mail to them explaining the situation. And will be sharing the ADB for Moto Z issue in few days

**Comment by ojw28** [comment] 2018-09-12 15:45
Closing because we never received a bug report for Moto Z (as far as I can see). For the Nokia preview build, it seems most likely that they haven't included Widevine in the preview build.

**Closed as completed by ojw28** 2018-09-12 15:45 UTC
Labels: need more info
