### ISSUE TITLE
Question about Smooth Streaming and TTML subtitles

### ISSUE THREAD

**Issue by alfonsoramosa** [google/ExoPlayer#2540] opened 2017-03-08 12:09 UTC
Exoplayer 2.2.0
Device: Nexus player
Android 7.1.1

Hi,

I'm having an issue when playing Smooth Streaming with TTML subtitles.

Examining the mp4 header of the subtitles chunks, it seems that the field with the length of the sample (an xml with the subtitles) is wrong (the value is slightly lower than it should be), then, the xml parsing is failing with an XmlPullParserException and the player is not playing video, audio nor subtitles.

As far as I know, that's what ExoPlayer is doing:

1. It's getting the length of the sample from **tfhb (Track Fragment Header Box)**, field Default sample size.
2. It extracts the sample (xml) from the chunk using this lenght.
3. Parses the xml (**TtmlDecoder.java**), method **decode()**.

As the readed length is wrong, Exoplayer is not getting the full xml from the sample and the parser is throwing an XmlPullParserException.
Before the exception, all the relevant information has been already parsed, as only a few bytes are missing at the end of the xml.

Questions:

- The size in tfhb.default_sample_size is in bytes?
- I have seen other "alternative" field, just before **mdat** (4 bytes). The value of this field is the correct length +8, but I have not been able to find documentation about this field. It seems that this field is used by software like "Mp4 Explorer", instead of tfhb.default_sample_size to extract the sample content.  Which one should be used?
- It's possible to make more robust the parsing process to use the already parsed information if there is an error in the xml and it throws and XmlPullParserException, and continue with the playback?

Attached is one of this chunks, with the following values:
- tfhb.default_sample_size = 00 00 05 3B
- The other alternative, just before mdat: 00 00 05 44
- The correct length of the sample is 05 3C

![fragments textstream_swe 0000000000](https://cloud.githubusercontent.com/assets/15816325/23703383/f73b3952-03ff-11e7-99bf-40ed4cd28f54.png)
Thanks
[Fragments(textstream_swe=0000000000).zip](https://github.com/google/ExoPlayer/files/827494/Fragments.textstream_swe.0000000000.zip)

**Comment by ojw28** [comment] 2017-03-08 14:50
> The size in tfhb.default_sample_size is in bytes?

I think so, yes. Note that it's possible for data in the `trun` box to override the size depending on the atom flags (see `FragmentedMp4Extractor.parseTrun`), but this feature is not typically used for TTML segments in SmoothStreaming.

> I have seen other "alternative" field, just before mdat (4 bytes). The value of this field is the correct length +8, but I have not been able to find documentation about this field. It seems that this field is used by software like "Mp4 Explorer", instead of tfhb.default_sample_size to extract the sample content. Which one should be used?

I'm unsure what that is. We have SmoothStreaming content including TTML subtitles that has been provided to us by streaming providers previously, all of which appears to specify the sample size correctly in the field we currently use. Which suggests that usage is correct and that the media attached to this issue has an off-by-one error.

> It's possible to make more robust the parsing process to use the already parsed information if there is an error in the xml and it throws and XmlPullParserException, and continue with the playback?

It's not ideal to arbitrarily suppress errors as it makes it harder to discover when something is broken. If this were a widespread issue we'd consider it, but as of now we don't have evidence suggesting this is the case. Streaming providers have been using ExoPlayer for SmoothStreaming for 2-3 years now without this issue having been reported previously. If the issue is limited to a single content provider or piece of content, whoever is responsible for that content should correct their media.

**Comment by alfonsoramosa** [comment] 2017-03-10 13:13
Thank you ojw28,

This issue is limited to a single content provider. It seems that they are filling tfhb.default_sample_size with the number of characters, not with the number of bytes of the sample xml.

Anyway, these SS subtitles are working fine in other 10 different players and platforms, so I guess these other players are extracting the sample from the chunk in a different way.
As I told before, there is an offset to the end of the sample, in the 4 bytes just before "mdat" that can also be used.
In fact, testing that with "Mp4 explorer", a mp4 analyzer, it is not using at all the field tfhb.default_sample_size when extracting the sample. No matters the value I put on that field, "Mp4 explorer" extracts always the full sample.
It seems to be used more like an "informative" field than the one used to extract the sample.
But if I modify the offset, that affects how "Mp4 explorer" extracts the sample.

So, it seems that many other players and software are not actually using tfhb.default_sample_size directly to extract the sample.

**Comment by ojw28** [comment] 2017-03-10 13:45
Oh right, I've figured out what the 4 bytes you refer to are. That's just the size of the `mdat` box. Every box starts with its length (4 bytes) followed by its type (4 bytes), as defined by the `Box` class in 14496-12.

It's not correct to use the size of the `mdat` box as the size of the sample, as you suggest other players may be doing. An `mdat` box normally contains multiple samples, so if you were to take the whole of content of the `mdat` box you'd need to manually scan it to work out where the individual sample boundaries are.

Even the scanning approach as described above is not valid, because an `mdat` box is permitted to also include arbitrary non-sample binary data in addition to sample data (normally at the end of the box, but it's also possible for it to be at the start). Hence it's required for a player to use the sample sizes provided by the `trun` (or default size), together with the offset to the first sample in order to guarantee correct operation for valid media.

Closing, since it seems we're doing the right thing and using the `mdat` box size is definitely not a correct approach. You should ask the content provider to fix their media.

**Closed as completed by ojw28** 2017-03-10 13:45 UTC
Labels: wont fix: infeasible, bad media

**Comment by alfonsoramosa** [comment] 2017-03-14 13:44
Ok, I agree. That's a content problem and the content provider should fix it.
And it's a good practice not to play something if there is an error in the stream, for example in this contents subtitles.
But perhaps the player should at least play audio and video. It should be enough not displaying subtitles to show that there is a problem with the subtitles.
