### ISSUE TITLE
Exoplayer2 keep trying to load stream when getting error

### ISSUE THREAD

**Issue by jiafei1986** [google/ExoPlayer#3020] opened 2017-07-04 01:44 UTC
I am now developing the video app by dash stream,  I found the exoplayer2 keep trying to load the data when getting error, it still trying to load even close the player,   below is the exception.    is there a way stop the load thread?
` com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                                   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                                   at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                   at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                                   at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
                                                                                   at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
                                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                   at java.lang.Thread.run(Thread.java:761)`

**Comment by andrewlewis** [comment] 2017-07-04 07:03
What do you mean by "close the player"? Are you seeing this loading error repeatedly even after calling `ExoPlayer.release()`?

**Comment by jiafei1986** [comment] 2017-07-04 23:34
@andrewlewis  I just run the demo app, and click the back button to quit the player Acvitiy.

**Comment by ojw28** [comment] 2017-07-05 10:53
I cannot reproduce this. The player makes a couple of attempts (in rapid succession) and then gives up retrying. Even if I configure the source manually to retry forever, retries stop as expected when quitting the player activity.

Please provide proper reproduction steps and all of the information requested in the issue template, else there's nothing actionable here and we will close the issue. Thanks!

**Comment by ojw28** [comment] 2017-07-19 20:18
Closing due to lack of information and being unable to reproduce.

**Closed as completed by ojw28** 2017-07-19 20:18 UTC
Labels: need more info
