### ISSUE TITLE
Download media playlist would crash

### ISSUE THREAD

**Issue by RicardoJiang** [google/ExoPlayer#4400] opened 2018-06-21 08:47 UTC
### Issue description
when download hls media playlist videos in demo it will crash
FATAL EXCEPTION: main
                                                                                    Process: com.google.android.exoplayer2.demo, PID: 11416
                                                                                    java.lang.NullPointerException
                                                                                        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:110)
                                                                                        at com.google.android.exoplayer2.source.hls.offline.HlsDownloadHelper.getDownloadAction(HlsDownloadHelper.java:100)
                                                                                        at com.google.android.exoplayer2.source.hls.offline.HlsDownloadHelper.getDownloadAction(HlsDownloadHelper.java:41)
                                                                                        at com.google.android.exoplayer2.demo.DownloadTracker$StartDownloadDialogHelper.onClick(DownloadTracker.java:298)
                                                                                        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:150)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

### Reproduction steps
just download media playlist video in demo
for example
"name": "Apple TS media playlist",
        "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8"

### Version of ExoPlayer being used
latest

**Comment by tonihei** [comment] 2018-06-21 08:48
Duplicate of #4396. And already fixed.

**Closed as completed by tonihei** 2018-06-21 08:48 UTC
Labels: duplicate
