### ISSUE TITLE
Connection re-use for DASH/HLS/SmoothStreaming

### ISSUE THREAD

**Issue by michaelstrigy** [google/ExoPlayer#2555] opened 2017-03-14 13:38 UTC
Hi,

I am trying to find the reasons for some latency in videos over dash that we are playing.
I can see on runtime that httpdatasource is always closing and opening connections, although the implementation uses okhttp.
when checking with wireshark i actually see many 'fin ack' and 'syn - ack - syn' along the playback time.
anyway to avoid this? i would like to use 1 connection which i thought okhttp should use and seem to be the used module but it seems to still work like i described.

thanks.

**Comment by michaelstrigy** [comment] 2017-03-14 13:52
Correction: ok http wasn't used, demo used defaultHttpDatasource i replaced it with OkHttpDatasource but still multiple syns..

**Comment by ojw28** [comment] 2017-03-14 13:57
Even DefaultHttpDataSource uses OkHttp under the hood on most recent versions of Android (because OkHttp is used in the platform as the default network stack). If I remember correctly the underlying network stack will try and hold connections open so they can be re-used for some period of time. Most likely the server you're requesting chunks from is closing the connections, in which case I think a change in server configuration would be required to allow them to be re-used.

**Comment by michaelstrigy** [comment] 2017-03-14 14:01
thats the thing, when capturing network data, the fin is localy sent to the server and not sent by the server, meaning its initiated by exoplayer http module.

**Comment by ojw28** [comment] 2017-03-14 14:07
I'm not an expert on TCP, but I think both sides need to send FIN when the connection terminates. Are you sure the client isn't sending FIN+ACK because it received a FIN from the server?

**Comment by michaelstrigy** [comment] 2017-03-14 14:14
it does seem we are sending fin ack to close a connection, the server then replies with a fin ack as well.
I agree this is strange especially since the http version is 1.1 which should be persistent with 1 connection.. seems very strange, i will try to investigate further, if anyone has information, please share, thanks!

**Comment by ojw28** [comment] 2017-06-24 13:52
We did look at this (quite a long time prior to this issue being filed) and convinced ourselves that connections were being re-used correctly. I don't think we have solid enough evidence to warrant us spending time checking again at this point, although if you get to the point where you're convinced it's no longer working, please let us know.

It would also be a good idea to try with some of the test content in the demo app (i.e. not hosted on your servers) to help rule out the possibility this is caused by server-side behavior, which still feels like the most likely possibility to me at this point.

Closing for now. Thanks!

**Closed as completed by ojw28** 2017-06-24 13:52 UTC
Labels: question
