### ISSUE TITLE
Exoplayer leaks surfacetexture switching movies

### ISSUE THREAD

**Issue by AndrewDickerson** [google/ExoPlayer#1236] opened 2016-02-05 05:49 UTC
Exoplayer leaks a Surfacetexture when switching movies because I can't seem to free the oes texture between movies.

**Comment by AquilesCanta** [comment] 2016-02-05 13:23
Can you provide some more information? I would like to reproduce the leakage. Are you releasing the player between runs? You are instantiating a new surface per stream, I guess?

**Comment by ojw28** [comment] 2016-02-08 18:59
Agreed; this issue is unclear. ExoPlayer doesn't own the surface (or SurfaceTexture). The surface is injected into the player by the application, which can also clear the surface. Please clarify.

**Comment by ojw28** [comment] 2016-02-10 10:29
Closing due to lack of information.

**Closed by ojw28** 2016-02-10 10:29 UTC
Labels: need more info
