### ISSUE TITLE
How to get metadata information like artist, genre, etc?

### ISSUE THREAD

**Issue by Informatheus** [google/ExoPlayer#7946] opened 2020-09-18 17:57 UTC
I analyzed the references but was only able to find the **title** and **url** in the Metadata object. In my project I need more info like genre and artist. There isnt a way to get more information? Thanks in advance.

**Comment by marcbaechinger** [comment] 2020-09-19 11:46
The `MediaItem` needs to be built by yourself with a builder. There is currently no support to automatically include the metadata of the media in the media item. We released a [`MetadataRetriever`](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/MetadataRetriever.java) with 2.12 which allows to read metadata from a given media item stream/file. 

I close this issue as a duplicate of https://github.com/google/ExoPlayer/issues/3609. Please join the conversation there.

**Comment by ChernyshovYuriy** [comment] 2020-09-29 15:20
> The `MediaItem` needs to be built by yourself with a builder. There is currently no support to automatically include the metadata of the media in the media item. We released a [`MetadataRetriever`](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/MetadataRetriever.java) with 2.12 which allows to read metadata from a given media item stream/file.
> 
> I close this issue as a duplicate of #3609. Please join the conversation there.

Thanks Marc!
Any suggestion how to use it in case of media is represented by bytes array. Can't get uri or path to it, just a pure bytes array.
Thanks in advance.

**Comment by marcbaechinger** [comment] 2020-10-01 19:51
Sorry Yuriy! I didn't see your comment because it's closed Aside: You can reopen an issue if you think it makes sense (it makes sense in this case:). If an issue is closed it's not really visible anymore.

You can pass your own implementation of `MediaSourceFactory` to [one of the static methods](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/MetadataRetriever.java#L68). The [media item will then be passed](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/MetadataRetriever.java#L119) to the `createMediaSource` method of the factory. Your factory then just uses a `ProgressiveMediaSourceFactory` to create the source and you can inject a `ByteArrayDataSource` which reads from your byte array. 

Please look whether that works for you. Happy to help out some more if needed.

EDIT: (or actually you can probably create a `ProgressiveMediaSourceFactory` directly and pass that `ByteArrayDataSource` to the constructor of it. No need for a composition)

**Comment by ChernyshovYuriy** [comment] 2020-10-01 19:55
Hey Marc,
Thanks a lot for advice. I will take a look. Meanwhile, I used MediaMetadataRetriever and it works as I need. I provided my own imp of MediaDataSource which reads bytes as needed.

**Comment by marcbaechinger** [comment] 2020-10-01 20:02
Ha! Great! You don't even need me! :D

**Closed as completed** 2020-10-02 17:39 UTC
Labels: duplicate, question
