### ISSUE TITLE
PIFF AAC-LC playback failure

### ISSUE THREAD

**Issue by weizhaoj** [google/ExoPlayer#4968] opened 2018-10-17 01:48 UTC
Exoplayer Version: 2.7.0 Release.

Audio Encoding Settings : AAC-LC
Encryption Settings : PIFF Encryption AES128-CTR

looks Exoplayer get failed on "null object reference". Below is the full log.

```
10-08 17:00:44.106   231  1922 D PlayReadyDrmFactory: isCryptoSchemeSupported >> isSupported = true
10-08 17:00:44.106   231  1922 D PlayReadyDrmFactory: PlayReadyDrmFactory::CreatePluging appPackageName = com.google.android.exoplayer2.demo
10-08 17:00:44.106   231  1922 D PlayReadyDrmFactory: isCryptoSchemeSupported >> isSupported = true
10-08 17:00:44.106   231  3486 D PlayReadyDrmFactory: isCryptoSchemeSupported >> isSupported = true
10-08 17:00:44.107   231  1922 D PlayReadyDrmFactory: PlayReadyDrmFactory::CreatePluging appPackageName = com.google.android.exoplayer2.demo
10-08 17:00:44.107   231  1922 D PlayReadyDrmFactory: isCryptoSchemeSupported >> isSupported = true
10-08 17:00:44.112  1976  1976 I ExoPlayerImpl: Init ExoPlayerLib/2.4.0 [sequoia, sequoia, synaptics, 28]
10-08 17:00:44.115  1976  1976 D EventLogger: state [0.00, true, I]
10-08 17:00:44.169  1976  1976 D EventLogger: state [0.06, true, B]
10-08 17:00:44.170  1976  1976 D EventLogger: sourceInfo [periodCount=1, windowCount=1
10-08 17:00:44.170  1976  1976 D EventLogger:   period [?]
10-08 17:00:44.170  1976  1976 D EventLogger:   window [?, false, false]
10-08 17:00:44.170  1976  1976 D EventLogger: ]
10-08 17:00:44.171  1976  1976 D EventLogger: loading [true]
10-08 17:00:44.197   484   516 I ActivityManager: Displayed com.google.android.exoplayer2.demo/.PlayerActivity: +169ms
10-08 17:00:44.419  1976  1976 D EventLogger: sourceInfo [periodCount=1, windowCount=1
10-08 17:00:44.419  1976  1976 D EventLogger:   period [144.17]
10-08 17:00:44.420  1976  1976 D EventLogger:   window [144.17, false, false]
10-08 17:00:44.420  1976  1976 D EventLogger: ]
10-08 17:00:44.427  1976  4786 I OMXClient: IOmx service obtained
10-08 17:00:44.427   286  3819 I OMXMaster: makeComponentInstance(OMX.google.aac.decoder) in omx@1.0-service process
10-08 17:00:44.429  1976  1976 D EventLogger: Tracks [
10-08 17:00:44.429  1976  1976 D EventLogger:   Renderer:1 [
10-08 17:00:44.429  1976  1976 D EventLogger:     Group:0, adaptive_supported=N/A [
10-08 17:00:44.429  1976  1976 D EventLogger:       [X] Track:0, id=1, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=```, supported=YES
10-08 17:00:44.429  1976  1976 D EventLogger:     ]
10-08 17:00:44.430  1976  1976 D EventLogger:   ]
10-08 17:00:44.430  1976  1976 D EventLogger: ]
10-08 17:00:44.431  1976  1976 D EventLogger: audioEnabled [0.32]
10-08 17:00:44.434   286   851 E OMXNodeInstance: getConfig(0xec1a42a0:google.aac.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
10-08 17:00:44.439   224   224 W AshmemAllocator: ashmem_create_region(8192) returning hidl_memory(0xf4218180, 8192)
10-08 17:00:44.441   224   224 I chatty  : uid=1000(system) allocator@1.0-s identical 2 lines
10-08 17:00:44.441   224   224 W AshmemAllocator: ashmem_create_region(8192) returning hidl_memory(0xf4218180, 8192)
10-08 17:00:44.445   224   224 W AshmemAllocator: ashmem_create_region(32768) returning hidl_memory(0xf4218180, 32768)
10-08 17:00:44.446   224   224 I chatty  : uid=1000(system) allocator@1.0-s identical 2 lines
10-08 17:00:44.449   224   224 W AshmemAllocator: ashmem_create_region(32768) returning hidl_memory(0xf4218180, 32768)
10-08 17:00:44.470  1976  1976 D EventLogger: audioDecoderInitialized [0.36, OMX.google.aac.decoder]
10-08 17:00:44.472  1976  1976 D EventLogger: audioFormatChanged [0.36, id=1, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=```]
10-08 17:00:44.520  1976  4784 E LoadTask: Unexpected exception loading stream
10-08 17:00:44.520  1976  4784 E LoadTask: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:44.520  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:44.520  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:44.520  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:44.520  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:44.520  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:44.520  1976  4784 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:44.520  1976  4784 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:44.520  1976  4784 E LoadTask: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:44.521  1976  1976 E EventLogger: internalError [0.41, loadError]
10-08 17:00:44.521  1976  1976 E EventLogger: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:44.521  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
10-08 17:00:44.521  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:44.521  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:44.521  1976  1976 E EventLogger: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:44.521  1976  1976 E EventLogger: Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:44.521  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:44.521  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:44.521  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:44.521  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:44.521  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:44.521  1976  1976 E EventLogger: 	... 3 more
10-08 17:00:45.092  1976  4784 E LoadTask: Unexpected exception loading stream
10-08 17:00:45.092  1976  4784 E LoadTask: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:45.092  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:45.092  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:45.092  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:45.092  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:45.092  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:45.092  1976  4784 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:45.092  1976  4784 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:45.092  1976  4784 E LoadTask: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:45.095  1976  1976 E EventLogger: internalError [0.98, loadError]
10-08 17:00:45.095  1976  1976 E EventLogger: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:45.095  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
10-08 17:00:45.095  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:45.095  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:45.095  1976  1976 E EventLogger: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:45.095  1976  1976 E EventLogger: Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:45.095  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:45.095  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:45.095  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:45.095  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:45.095  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:45.095  1976  1976 E EventLogger: 	... 3 more
10-08 17:00:46.678  1976  4784 E LoadTask: Unexpected exception loading stream
10-08 17:00:46.678  1976  4784 E LoadTask: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:46.678  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:46.678  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:46.678  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:46.678  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:46.678  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:46.678  1976  4784 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:46.678  1976  4784 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:46.678  1976  4784 E LoadTask: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:46.683  1976  1976 E EventLogger: internalError [2.57, loadError]
10-08 17:00:46.683  1976  1976 E EventLogger: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:46.683  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
10-08 17:00:46.683  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:46.683  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:46.683  1976  1976 E EventLogger: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:46.683  1976  1976 E EventLogger: Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:46.683  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:46.683  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:46.683  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:46.683  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:46.683  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:46.683  1976  1976 E EventLogger: 	... 3 more
10-08 17:00:47.593   484   606 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
10-08 17:00:48.579  1719  3349 I chromium: [1719:3349:INFO:ssdp_device.c(101)] SSDP packets sent for 30 seconds = 83
10-08 17:00:49.226  1976  4784 E LoadTask: Unexpected exception loading stream
10-08 17:00:49.226  1976  4784 E LoadTask: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:49.226  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:49.226  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:49.226  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:49.226  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:49.226  1976  4784 E LoadTask: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:49.226  1976  4784 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:49.226  1976  4784 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:49.226  1976  4784 E LoadTask: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: Source error.
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:49.235  1976  4783 E ExoPlayerImplInternal: 	... 3 more
10-08 17:00:49.239  1976  1976 E EventLogger: internalError [5.12, loadError]
10-08 17:00:49.239  1976  1976 E EventLogger: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:49.239  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
10-08 17:00:49.239  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:49.239  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:49.239  1976  1976 E EventLogger: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:49.239  1976  1976 E EventLogger: Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:49.239  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:49.239  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:49.239  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:49.239  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:49.239  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:49.239  1976  1976 E EventLogger: 	... 3 more
10-08 17:00:49.250  1976  1976 E EventLogger: playerFailed [5.14]
10-08 17:00:49.250  1976  1976 E EventLogger: com.google.android.exoplayer2.ExoPlaybackException
10-08 17:00:49.250  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at android.os.Looper.loop(Looper.java:193)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at android.os.HandlerThread.run(HandlerThread.java:65)
10-08 17:00:49.250  1976  1976 E EventLogger: Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:49.250  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at java.lang.Thread.run(Thread.java:764)
10-08 17:00:49.250  1976  1976 E EventLogger: Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.initializationVectorSize' on a null object reference
10-08 17:00:49.250  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.appendSampleEncryptionData(FragmentedMp4Extractor.java:1198)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1050)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
10-08 17:00:49.250  1976  1976 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-08 17:00:49.250  1976  1976 E EventLogger: 	... 3 more
10-08 17:00:49.272  1976  1976 D EventLogger: audioDisabled [5.16]
10-08 17:00:49.272  1976  1976 D EventLogger: loading [false]
10-08 17:00:49.274  1976  1976 D EventLogger: state [5.16, true, I]
10-08 17:00:53.368   179   389 W [ 4704.820] [33;1mAmp2@@[MODULE_DISPSRV:disp_output_info():364]:[0m : [Output] = 4Kx2KP30 YCbCr422 10Bit, HDMI HDCP2.2(1) => Connected
10-08 17:00:53.368   179   389 W [ 4704.820] [33;1mAmp2@@[MODULE_DISPSRV:disp_plane_info():336]:[0m : [MAIN plane]=(0,0,720,480)->(0,0,720,480)/Buildin
10-08 17:00:53.368   179   389 W [ 4704.820] [33;1mAmp2@@[MODULE_DISPSRV:disp_frame_info():284]:[0m : [MAIN frame]=(0,0,720,480)->(0,0,720,480)@YUV420SP/8bits/Pp:0/Fs:1/hdr type:0
10-08 17:00:53.368   179   389 W [ 4704.820] [33;1mAmp2@@[MODULE_DISPSRV:disp_frame_info():284]:[0m : [PIP frame]=(0,0,0,0)->(0,0,0,0)@YUV422/0bits/Pp:0/Fs:0/hdr type:0
10-08 17:00:53.368   179   389 W [ 4704.820] [33;1mAmp2@@[MODULE_DISPSRV:disp_plane_info():336]:[0m : [GFX0 plane]=(0,0,1920,1080)->(0,0,3840,2160)/FrameScale/1.29fps[43]
10-08 17:00:53.368   179   389 W [ 4704.821] [33;1mAmp2@@[MODULE_DISPSRV:disp_frame_info():284]:[0m : [GFX0 frame]=(0,0,1920,1080)->(0,0,1920,1080)@ARGB32_PM/8bits/Pp:0/Fs:0/hdr type:0
10-08 17:00:55.162   236   236 E IMGMemtrackHAL: GetGLMemtrackRecords: Subtracting per-pid stats from global stats would wrap. Clamping global stats to zero.
10-08 17:00:55.162   236   236 I chatty  : uid=1000(system) memtrack@1.0-se identical 6 lines
10-08 17:00:55.162   236   236 E IMGMemtrackHAL: GetGLMemtrackRecords: Subtracting per-pid stats from global stats would wrap. Clamping global stats to zero.
10-08 17:00:55.163   236   236 E IMGMemtrackHAL: IonHeapBufferToRecords: Saw only garbage when skipping 'Table header' when parsing system-ion
10-08 17:00:56.748  1601  1636 I Finsky  : [136] com.google.android.finsky.br.ac.run(5): Stats for Executor: BlockingExecutor com.google.android.finsky.br.ad@fd2e64f[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
10-08 17:00:56.748  1601  1636 I Finsky  : [136] com.google.android.finsky.br.ac.run(5): Stats for Executor: LightweightExecutor com.google.android.finsky.br.ad@f1251dc[Running, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 8]
10-08 17:00:58.533  1719  1719 I chromium: [1719:1719:INFO:metrics_recorder.cc(89)] Metrics stat: total=2
10-08 17:00:58.533  1719  1719 I chromium: CastV2.Transport.Ping.In=394
10-08 17:00:58.533  1719  1719 I chromium: CastV2.Transport.Pong.Out=394
10-08 17:00:59.240   484   495 I system_server: Background concurrent copying GC freed 176106(5MB) AllocSpace objects, 4(208KB) LOS objects, 42% free, 7MB/13MB, paused 224us total 131.790ms
10-08 17:00:59.337  1719  1910 I chromium: [1719:1910:INFO:wifi_proximity.cc(209)] Request scan.
10-08 17:01:05.751  2557  2580 I Finsky  : [199] com.google.android.finsky.br.ac.run(5): Stats for Executor: BlockingExecutor com.google.android.finsky.br.ad@1148f56[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
10-08 17:01:05.751  2557  2580 I Finsky  : [199] com.google.android.finsky.br.ac.run(5): Stats for Executor: LightweightExecutor com.google.android.finsky.br.ad@bf16bd7[Running, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 7]
10-08 17:01:06.778   484   509 D AutofillManagerService: onBackKeyPressed()
10-08 17:01:07.328   484   484 W HDMI    : [2]:Unhandled cec command:<User Control Release> src: 0, dst: 4
10-08 17:01:10.337   484   606 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
```

**Comment by ojw28** [comment] 2018-10-17 18:53
Please provide the information requested in the issue template. Specifically in this case a sample stream that we can reproduce the issue with.

**Comment by srguduru** [comment] 2018-10-17 19:18
I have the same issue.
Here is the test stream details:
 
Link for the content:
https://playreadydata.blob.core.windows.net/asset-33c2dbff-5f5e-475b-904e-b13f1d5f7186/Taxi3_AACLC_154k.isma?sv=2012-02-12&sr=c&si=d46b2dd3-e9f6-40e9-8a57-f31dfff51bfa&sig=p740biwUqRSljucOrlqBwl0YSMJTE6%2FYCFD6UobCc5k%3D&se=2026-07-13T16%3A51%3A58Z
 
Encryption: PIFF Encryption AES128-CTR

**Comment by ojw28** [comment] 2018-10-17 19:50
The NullPointerException issue doesn't occur on 2.9.0. Playback still doesn't work, presumably because we're not decrypting the samples?

Please also see https://github.com/google/ExoPlayer/issues/1529#issuecomment-219322776.

**Comment by tonihei** [comment] 2019-05-07 14:41
Closing due to lack of further information.

**Closed as completed by tonihei** 2019-05-07 14:41 UTC
Labels: need more info
