### ISSUE TITLE
Internal runtime error, IllegalStateException

### ISSUE THREAD

**Issue by s3xy4ngyc** [google/ExoPlayer#951] opened 2015-11-12 10:54 UTC
## Error Report and Stacktrace
On Some Devices I do get a Internal runtime Error with an IllegalStateException:

```
11-12 11:39:29.139 6550-10618/com.google.android.exoplayer.demo E/ACodec: [OMX.SEC.avc.dec] ERROR(0x90000004)
11-12 11:39:29.139 6550-10618/com.google.android.exoplayer.demo E/MediaCodec: Codec reported an error. (omx error 0x90000004, internalError -2147483648)
11-12 11:39:29.144 6550-10603/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                         java.lang.IllegalStateException
                                                                                             at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:802)
                                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:458)
                                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                             at android.os.Looper.loop(Looper.java:176)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-12 11:39:29.144 6550-6550/com.google.android.exoplayer.demo E/EventLogger: playerFailed [1.10]
                                                                              com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:176)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                               Caused by: java.lang.IllegalStateException
                                                                                  at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:802)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:458)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                  at android.os.Looper.loop(Looper.java:176) 
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

This Issue was already raised in #337 

I was able to reproduce this behavior with the Sample App:

## Steps to reproduce

Used Device: Samsung Galaxy S3 (Android 4.3)

1. Put Phone into Landscape Mode (unclear if really needed)
2. Select Content, I've used the "Google Play" Sample (Youtube DASH)
3. While it Initially Loads, Instantly Seek To another Position.
4. watch it burn. (Check the Logs)

It might need a few tries to See The Result, since it seems to occur randomly. However it seems like it is a problem with seeking while in some loading process.

On Larger Content with higher quality (e.G. Movies) this occurs more frequently.

I was not able to reproduce it on my Nexus 5 running Android 6

**Comment by AtHeaven** [comment] 2015-12-01 10:43
The same behavior on Nexus 4 (5.1.1) and GenyMotion Sony Tablet emulator (4.1.1). Tried to play different HLS streams.

**Comment by ojw28** [comment] 2016-01-06 15:58
- I can easily reproduce the problem on the Samsung Galaxy S3, as per the original report. It's also trivial to cause a failure at any point during playback in the demo app on this device, by holding and dragging the seek bar. Occasionally this causes a native crash rather than the error reported in this issue.
- I cannot reproduce this on Nexus 4 running 5.1.1 (LMY48T). Please provide a full bug report (the output of `adb bugreport`) if you want us to try further.

For the S3, it looks like there's an issue with the flush implementation of the video decoder. It's quite easy to work around, but I'm not entirely sure exactly what we should be targeting the workaround to. As you can see [here](https://en.wikipedia.org/wiki/Samsung_Galaxy_S_III#Model_variants), there were quite a lot of variants of the S3, and it's likely that the issue doesn't occur on all of them.

**Comment by ojw28** [comment] 2016-01-06 17:45
This should be fixed for the S3. I cannot reproduce on Nexus 4. We're not officially supporting GenyMotion emulator; it's likely an issue with their implementation.

**Closed by ojw28** 2016-01-06 17:45 UTC
Labels: bug, device specific issue

**Comment by tiger1990** [comment] 2016-03-14 13:43
Scenario ::: Exception Getting on device when seeking player at random position
I am getting an exception on Model (GT-N8000)
I have also implemented this workaround 

 private static boolean codecNeedsFlushWorkaround(String name)
    {
        return Util.SDK_INT < 18
                || (Util.SDK_INT == 18
                && ("OMX.SEC.avc.dec".equals(name) || "OMX.SEC.avc.dec.secure".equals(name)))
                || (Util.SDK_INT == 19 && Util.MODEL.startsWith("SM-G800")
                && ("OMX.Exynos.avc.dec".equals(name) || "OMX.Exynos.avc.dec.secure".equals(name))) || "OMX.SEC.aac.dec".equals(name) && Util.MODEL.startsWith("GT-N8000");
    }

Exception Detail:::

 E/MFC_DEC_APP: SsbSipMfcDecInit] IOCTL_MFC_DEC_INIT failed
03-14 19:02:37.370 1901-4873/? E/SEC_H264_DEC: SsbSipMfcDecInit() failed!
03-14 19:02:37.370 25499-4867/com.jio.media.jod E/ACodec: [OMX.SEC.avc.dec] ERROR(0x90000004)
03-14 19:02:37.370 25499-4866/com.jio.media.jod E/MediaCodec: Codec reported an error. (omx error 0x90000004, internalError -2147483648)
03-14 19:02:38.425 25499-25499/com.jio.media.jod E/EventLogger: playerFailed [3.16]
                                                                com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at android.os.Looper.loop(Looper.java:146)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                 Caused by: java.lang.IllegalStateException
                                                                    at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:998)
                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:546)
                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
