### ISSUE TITLE
Decoder reuse from high to low bit depth audio

### ISSUE THREAD

**Issue by kgrevehagen** [google/ExoPlayer#6608] opened 2019-11-01 09:35 UTC
### [REQUIRED] Issue description
When going from a track with high bit depth(e.g. 24 bit) to a track with lower bit depth(e.g. 16 bit), the decoder reuse logic actually reuses the codec, whereas I think it should not. I have noticed two different behaviors when doing this:
- It wont play the 16 bit track. I wasn't able to recreate these files for sharing here.
- Plays the 16 bit track, but sound has a lot of noise/artifacts added. Happens with the provided test files.

Returning `KEEP_CODEC_RESULT_NO` in `MediaCodecAudioRenderer.canKeepCodec()` makes it behave correct in both cases mentioned above.

Playing the same content with DRM works, which is as expected, because decoder reuse is not implemented for that, as I've understood.

### [REQUIRED] Reproduction steps
1. Enable FLAC playback via the extension.
2. Play the playlist below, it will start with the 24 bit track.
3. Skip next to the 16 bit track.

### [REQUIRED] Link to test content
```
      {
        "name": "FLAC 24 bit -> 16 bit",
        "playlist": [
          {
            "uri": "https://quc-test-source.s3.amazonaws.com/flac_16_v_24/ranum_24bits.flac"
          },
          {
            "uri": "https://quc-test-source.s3.amazonaws.com/flac_16_v_24/ranum_16bits.flac"
          }
        ]
      }
```

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
2.10.5

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 3, Android 10, 100% reproducible

**Comment by tomislavturcic** [comment] 2019-11-04 11:55
Same issue as the one reported here: https://github.com/google/ExoPlayer/issues/6601

**Comment by andrewlewis** [comment] 2019-11-05 14:27
Duplicate of #6601

**Closed as completed by andrewlewis** 2019-11-05 14:27 UTC
Labels: duplicate

**Comment by kgrevehagen** [comment] 2019-11-13 10:19
@andrewlewis #6601 has three issues inside the task, and the one you are still investigating seems to be related to this issue, might actually be the exact one. But I believe I have found the cause of the problem and a potential fix. So maybe you can use this issue to track this exact issue?

A potential fix for this is to check for `codecMaxInputSize` inequality, not just bigger than.

In `MediaCodecAudioRenderer.java`, in the method `canKeepCodec(...)` we can change from 
`if (getCodecMaxInputSize(codecInfo, newFormat) > codecMaxInputSize`
to
`if (getCodecMaxInputSize(codecInfo, newFormat) != codecMaxInputSize`

This seems to fix the issue, and is also logically correct in my mind. Question is if this gives any side effects that I'm not aware of.

**Comment by andrewlewis** [comment] 2019-11-13 12:14
I think the issue is probably that the audio sink is not reconfigured despite the PCM bit depth changing. When I was fixing this I uncovered another issue with draining audio processors which I'm looking into at the moment (this additional issue prevents this working even with a fix not to keep the codec).
