### ISSUE TITLE
DynamicConcatenatingMediaSource and RepeatMode off

### ISSUE THREAD

**Issue by edwinzap** [google/ExoPlayer#3831] opened 2018-02-12 10:28 UTC
### Issue description
With a DynamicConcatenatingMediaSource, the RepeatMode = off doesn't work. After the last Window, it comes back to the first (next but its the same for previous)

### Reproduction steps
1) Create a DynamiConcatenatingMediaSource object
2) Add MediaSources
3) Set the player RepeatMode = OFF
4) Use a SimpleExoplayerView
5) Press the next button on the Playback Controller until it reach the last item of the playlist
6) Press the next button once again

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
On every devices.

Thanks !

**Comment by tonihei** [comment] 2018-02-12 14:32
Tried to replicate what you describe here in the demo app, but it works perfectly fine for me. 
- Especially point 6 is not possible to do because SimpleExoPlayerView disables the next button at the last item if repeat mode is off.

Could you please provide more details on what is not working and how to reproduce in the demo app?

**Comment by ojw28** [comment] 2018-02-26 17:50
Closing due to lack of information.

**Closed as completed by ojw28** 2018-02-26 17:50 UTC
Labels: need more info
