### ISSUE TITLE
local m3u8 play error

### ISSUE THREAD

**Issue by jiyewushen** [google/ExoPlayer#8330] opened 2020-12-08 12:47 UTC
version 2.12.2

when m3u8 file include absolutely path , but it may be added  `content://media/` (not `file://`)

```kotlin
        //uri: content://media/external/file/1206383
        val mediaItem=MediaItem.Builder().setUri(uri).setMimeType(MimeTypes.APPLICATION_M3U8).build()
        val player = SimpleExoPlayer.Builder(this).build()
        player.addMediaItem(mediaItem)
        binding.playerView.player = player
        player.prepare()
        player.play()
```
m3u8 file
```text
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.063378,
/storage/emulated/0/Quark/Download/a0
#EXTINF:10.040167,
/storage/emulated/0/Quark/Download/a1
********
*******
*****
```

Error
```java
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.ContentDataSource$ContentDataSourceException: java.io.FileNotFoundException: Missing cursor for content://media/storage/emulated/0/Quark/Download/a0
        at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:110)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:418)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:400)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:375)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:342)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.FileNotFoundException: Missing cursor for content://media/storage/emulated/0/Quark/Download/a1
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1120)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:958)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:881)
        at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:70)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:418) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:400) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:375) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:342) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by krocard** [comment] 2020-12-09 17:19
@christosts (or @AquilesCanta) do you know if we support HLS manifest referencing local files?

**Comment by AquilesCanta** [comment] 2020-12-09 17:44
It should just work, assuming the URIs are correct and the DataSource factory which the MediaSource is using supports the URIs' scheme. In this case, I'm inclined to think the URIs are not correct (as per the exception) but it's possible I'm missing something about content:// URLs which I haven't seen much of.

**Comment by ojw28** [comment] 2020-12-14 14:03
Agree that the URIs are probably not correct (as per the exception). If you're sure it's an ExoPlayer issue then I think we'd need concrete reproduction steps, in the form of a small sample project you can share on GitHub and detailed instructions for how to reproduce the issue with it.

**Comment by jiyewushen** [comment] 2020-12-15 05:59
everything do well, but why add "content://media/" at dataSpec , next  ContentDataSource open it , crash. Why "content://media"? not "File://"? 
<img width="851" alt="135439" src="https://user-images.githubusercontent.com/16441451/102176795-1ec73b80-3edd-11eb-846b-7da905daa19e.png">

<img width="800" alt="134919" src="https://user-images.githubusercontent.com/16441451/102176614-be37fe80-3edc-11eb-9bc1-cd5b33990be5.png">

**Comment by jiyewushen** [comment] 2020-12-15 06:36
@ojw28 @krocard  @AquilesCanta 
Fortunately, I finally found issue. it crash due to create  a wrong dataSpec.
<img width="800" alt="134919" src="https://user-images.githubusercontent.om/16441451/102179359-f130c100-3ee1-11eb-8359-c470b8c5c6ed.png">
<img width="851" alt="135439" src="https://user-images.githubusercontent.com/16441451/102179368-f5f57500-3ee1-11eb-901f-b6b41dcb0391.png">


`UriUtil.resolveToUri` add error scheme when create uri at `HlsMediaChunk.createInstance`(note:mediaPlaylist.baseUri is MediaStore uri and mediaSegment.url is file path).
I ues `Uri.fromFile` test it , it do well.
```java
  public static HlsMediaChunk createInstance(
      HlsExtractorFactory extractorFactory,
      DataSource dataSource,
      Format format,
      long startOfPlaylistInPeriodUs,
      HlsMediaPlaylist mediaPlaylist,
      int segmentIndexInPlaylist,
      Uri playlistUrl,
      @Nullable List<Format> muxedCaptionFormats,
      int trackSelectionReason,
      @Nullable Object trackSelectionData,
      boolean isMasterTimestampSource,
      TimestampAdjusterProvider timestampAdjusterProvider,
      @Nullable HlsMediaChunk previousChunk,
      @Nullable byte[] mediaSegmentKey,
      @Nullable byte[] initSegmentKey) {
    // Media segment.
    HlsMediaPlaylist.Segment mediaSegment = mediaPlaylist.segments.get(segmentIndexInPlaylist);
    //test
    File file=new File(mediaSegment.url);
    Uri uri=Uri.fromFile(file);
//    Uri uri=UriUtil.resolveToUri(mediaPlaylist.baseUri, mediaSegment.url);
    DataSpec dataSpec =
        new DataSpec(
            uri,
            mediaSegment.byteRangeOffset,
            mediaSegment.byteRangeLength);
    boolean mediaSegmentEncrypted = mediaSegmentKey != null;
    @Nullable
    byte[] mediaSegmentIv =
        mediaSegmentEncrypted
            ? getEncryptionIvArray(Assertions.checkNotNull(mediaSegment.encryptionIV))
            : null;
    DataSource mediaDataSource = buildDataSource(dataSource, mediaSegmentKey, mediaSegmentIv);

    // Init segment.
    HlsMediaPlaylist.Segment initSegment = mediaSegment.initializationSegment;
    DataSpec initDataSpec = null;
    boolean initSegmentEncrypted = false;
    @Nullable DataSource initDataSource = null;
    if (initSegment != null) {
      initSegmentEncrypted = initSegmentKey != null;
      @Nullable
      byte[] initSegmentIv =
          initSegmentEncrypted
              ? getEncryptionIvArray(Assertions.checkNotNull(initSegment.encryptionIV))
              : null;
      Uri initSegmentUri = UriUtil.resolveToUri(mediaPlaylist.baseUri, initSegment.url);
      initDataSpec =
          new DataSpec(initSegmentUri, initSegment.byteRangeOffset, initSegment.byteRangeLength);
      initDataSource = buildDataSource(dataSource, initSegmentKey, initSegmentIv);
    }

    long segmentStartTimeInPeriodUs = startOfPlaylistInPeriodUs + mediaSegment.relativeStartTimeUs;
    long segmentEndTimeInPeriodUs = segmentStartTimeInPeriodUs + mediaSegment.durationUs;
    int discontinuitySequenceNumber =
        mediaPlaylist.discontinuitySequence + mediaSegment.relativeDiscontinuitySequence;

    @Nullable HlsMediaChunkExtractor previousExtractor = null;
    Id3Decoder id3Decoder;
    ParsableByteArray scratchId3Data;
    boolean shouldSpliceIn;
    if (previousChunk != null) {
      boolean isFollowingChunk =
          playlistUrl.equals(previousChunk.playlistUrl) && previousChunk.loadCompleted;
      id3Decoder = previousChunk.id3Decoder;
      scratchId3Data = previousChunk.scratchId3Data;
      boolean canContinueWithoutSplice =
          isFollowingChunk
              || (mediaPlaylist.hasIndependentSegments
                  && segmentStartTimeInPeriodUs >= previousChunk.endTimeUs);
      shouldSpliceIn = !canContinueWithoutSplice;
      previousExtractor =
          isFollowingChunk
                  && !previousChunk.extractorInvalidated
                  && previousChunk.discontinuitySequenceNumber == discontinuitySequenceNumber
              ? previousChunk.extractor
              : null;
    } else {
      id3Decoder = new Id3Decoder();
      scratchId3Data = new ParsableByteArray(Id3Decoder.ID3_HEADER_LENGTH);
      shouldSpliceIn = false;
    }

    return new HlsMediaChunk(
        extractorFactory,
        mediaDataSource,
        dataSpec,
        format,
        mediaSegmentEncrypted,
        initDataSource,
        initDataSpec,
        initSegmentEncrypted,
        playlistUrl,
        muxedCaptionFormats,
        trackSelectionReason,
        trackSelectionData,
        segmentStartTimeInPeriodUs,
        segmentEndTimeInPeriodUs,
        /* chunkMediaSequence= */ mediaPlaylist.mediaSequence + segmentIndexInPlaylist,
        discontinuitySequenceNumber,
        mediaSegment.hasGapTag,
        isMasterTimestampSource,
        /* timestampAdjuster= */ timestampAdjusterProvider.getAdjuster(discontinuitySequenceNumber),
        mediaSegment.drmInitData,
        previousExtractor,
        id3Decoder,
        scratchId3Data,
        shouldSpliceIn);
  }
```

**Comment by ojw28** [comment] 2020-12-21 11:13
I think the way that ExoPlayer is resolving the URI is correct. There's no way that the player can know that `/storage/emulated/0/Quark/Download/a0` is a file path, as opposed to a path relative to the base URI. Assuming it's relative to the base URI is correct and standard practice, as far as I'm aware.

If you want to specify file URIs in your m3u8 file then you should use absolute URIs like `file:///storage/emulated/0/Quark/Download/a0` rather than `/storage/emulated/0/Quark/Download/a0`. If you do this then player will know that it's a file URI and to not resolve it relative to the base URI, and playback will succeed.

Closing this, since it looks like the player is doing the right thing. Thanks!

**Closed as completed by ojw28** 2020-12-21 11:13 UTC
Labels: question, bad media
