### ISSUE TITLE
Full screen button inside custom controls

### ISSUE THREAD

**Issue by halibegic** [google/ExoPlayer#2346] opened 2017-01-18 15:49 UTC
Hi,

After setting **app:controller_layout_id="@layout/custom_controls"** attribute and using standard UI components (e.g. play, pause) I need to add full screen button. However I just can't seem to figure it out how to implement this with SimpleExoPlayerView, any help would be great.

**Comment by ojw28** [comment] 2017-01-18 15:51
Duplicate of #1845

**Closed as completed by ojw28** 2017-01-18 15:51 UTC
Labels: duplicate
