### ISSUE TITLE
Document most common ExoPlaybackException causes

### ISSUE THREAD

**Issue by laurafuente** [google/ExoPlayer#1611] opened 2016-06-21 06:45 UTC
My request is to set a more intelligent error management instead of always launching a ExoPlaybackException. This makes very difficult to shown information to the user about the player error.
The ideal solution was to return different error codes for different errors to know the cause of the error

**Comment by andrewlewis** [comment] 2016-06-21 07:14
Does the cause returned by `e.getCause()` contain the information you need? (See the [javadoc for ExoPlaybackException](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ExoPlaybackException.html).)

**Comment by laurafuente** [comment] 2016-06-21 07:35
Hi Andrew, with the cause I can get some information in some cases surfing the code. But probably it's more user friendly to have a list with the different kinds of errors I can get from the player.

**Comment by andrewlewis** [comment] 2016-06-21 08:55
As per #1552, it's not possible to provide a complete list of errors, but I agree it would be useful to have documentation listing the most common/important exceptions. I'll use this issue to track adding the documentation. Thanks!

**Comment by laurafuente** [comment] 2016-06-21 09:09
Hi,
Let me know when that documentation is available, please
Thanks Andrew

**Comment by anki1427** [comment] 2016-09-26 06:56
Hi I am facing this issue while playing video in MI phones ,there is a ExoPlayBackException...

 Unhandled error event
                                                                com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                 Caused by: java.lang.IllegalStateException
                                                                    at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                    at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:983)
                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:573)
                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:514)
                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 

What is the issue i am not able to debug it.

**Comment by andrewlewis** [comment] 2018-06-06 15:30
It's been a while, but one way to address this finally would be to implement a more comprehensive `ErrorMessageProvider`, like the [one in the demo app](https://github.com/google/ExoPlayer/blob/b9aaf1e/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L705).

**Comment by ojw28** [comment] 2021-08-09 15:20
This will be addressed by `PlaybackException.errorCode` in 2.15.

**Closed as completed by ojw28** 2021-08-09 15:20 UTC
Labels: enhancement
