### ISSUE TITLE
Memory leak on SampleQueue AllocationNode

### ISSUE THREAD

**Issue by songcream** [google/ExoPlayer#5151] opened 2018-11-27 04:27 UTC
I use exoPlayer to play local mp4 file in my app,and add about 10+ video files with looping mode ,but it crash after running 5 hours long. I made a heap dump in studio,it shows that SampleQueue$AllocationNode takes a lot memory,and it will increase more when app run longer
![360 17060221398853](https://user-images.githubusercontent.com/40887133/49058581-97e48f00-f23f-11e8-8ef3-e3fef83ec87d.png)

**Comment by songcream** [comment] 2018-11-27 08:33
In addition,this happens on android 5.1,but work right on andorid 7.1

**Comment by andrewlewis** [comment] 2018-11-28 11:52
Is the screenshot showing ~ 35 MB of allocations in the sample queue? That doesn't seem excessive.

Can you reproduce this in the latest version of the ExoPlayer demo app by enabling looping mode and playing the 10 video file concatenation? If so please provide the streams you're trying to play and let us know what device(s) you see the crash on and we'll take a look. Thanks.

**Comment by ojw28** [comment] 2018-12-18 20:11
Closing due to lack of follow-up. As above, 35MB does not seem excessive for a media buffer. There is no evidence in this issue that usage does actually increase the longer the app runs. It seems most likely that something else in your app is leaking memory.

If you can reproduce with the ExoPlayer demo app, that would be good evidence that it is indeed an ExoPlayer issue. Please respond here if it does reproduce there.

**Closed as completed by ojw28** 2018-12-18 20:11 UTC
Labels: question, need more info
