### ISSUE TITLE
MediaCodecRenderer will never return isEnded=true if the stream is not marked final

### ISSUE THREAD

**Issue by extorn** [google/ExoPlayer#5818] opened 2019-04-30 08:21 UTC
### [REQUIRED] Issue description
The MediaCodecRenderer does not signal it has been ended when it encounters the end of stream marker along with some data.
The buffer has the data added, the buffer is marked to signal the stream has ended, but because if the stream isn't marked as final, the SampleStream returns RESULT_NOTHING_READ, feedInputBuffer in MediaCodecRenderer returns immediately with false. Since the inputStreamEnded is never set, isEnded will never return true. The renderer will as a result, continue trying to render data (checking for, not finding and returning). This makes the player renderer loop in ExoPlayerInternal infinite.

To fix this, I've wrapped the SampleStream like this:
```
 @Override
    protected void onStreamChanged(Format[] formats, long offsetUs) throws ExoPlaybackException {
        SampleStream stream = getStream();
        if(!(stream instanceof SampleStreamWrapper)) {
            replaceStream(formats, new SampleStreamWrapper(stream), offsetUs);
        }
    }
```

My SampleStreamWrapper makes the following change, but otherwise just delegates directly to the SampleStream.

```
@Override
    public int readData(FormatHolder formatHolder, DecoderInputBuffer buffer, boolean formatRequired) {
        int readResult = wrapped.readData(formatHolder, buffer, formatRequired);
        if(buffer.isEndOfStream()) {
            // force buffer read else the bytes just get lost and the buffer isn't cleared
            // It's just important this is neither RESULT_NOTHING_READ nor RESULT_BUFFER_READ
            return RESULT_END_OF_INPUT;
        }
        return readResult;
    }
```
A better fix would be to perhaps wrap this block (line 687-699) in MediaCodecRenderer with an if:
 ```
if(!buffer.isEndOfStream()) {
```
```
   if (result == C.RESULT_NOTHING_READ) {
      return false;
    }
    if (result == C.RESULT_FORMAT_READ) {
      if (codecReconfigurationState == RECONFIGURATION_STATE_QUEUE_PENDING) {
        // We received two formats in a row. Clear the current buffer of any reconfiguration data
        // associated with the first format.
        buffer.clear();
        codecReconfigurationState = RECONFIGURATION_STATE_WRITE_PENDING;
      }
      onInputFormatChanged(formatHolder.format);
      return true;
    }
```
 ```
}
```

### [REQUIRED] Reproduction steps
Place an optional debug breakpoint in line 684 of MediaCodecRenderer set to break if result == C.RESULT_NOTHING_READ.
here's the line - result = readSource(formatHolder, buffer, false);

### [REQUIRED] Link to test content
It was a random 6 second mp4 file I generated on my phone using its camera. I don't think this is specific to the content. Here's a small one.
[VID_20190430_093729.mp4.zip](https://github.com/google/ExoPlayer/files/3130485/VID_20190430_093729.mp4.zip)

### [REQUIRED] A full bug report captured from the device
Nothing to see in my logs. I discovered this because I've been writing a custom extension to the renderer.

### [REQUIRED] Version of ExoPlayer being used
exoplayer:2.8.2

### [REQUIRED] Device(s) and version(s) of Android being used
Nexus 6 - Android 7.1.1

**Comment by tonihei** [comment] 2019-04-30 08:25
Can you please provide example content? It's indeed highly likely that the content is causing this behaviour somehow.

**Comment by extorn** [comment] 2019-04-30 08:29
I should have said, I am using a custom RenderererFactory that only provides this audio renderer - a  video renderer is not provided. That may have a bearing. I'll create and upload a more generic source media file to demo it in a minute.

**Comment by extorn** [comment] 2019-04-30 08:38
[VID_20190430_093729.mp4.zip](https://github.com/google/ExoPlayer/files/3130485/VID_20190430_093729.mp4.zip)

**Comment by extorn** [comment] 2019-04-30 08:39
I've created and tested with a series of 5 different videos - the issue occurs with all.

**Comment by extorn** [comment] 2019-04-30 08:40
It could be the real issue is that the stream is not being marked as final, but I've not looked into the area of ExoPlayer that does this to establish why it isn't happening.

**Comment by extorn** [comment] 2019-04-30 08:44
Sorry. I think this is my issue - I'm trying to reuse your exo player classes rather than copy and paste them so I've essentially removed the audioSink from the logic and, as a result, when isEnded is called, audioSink is always returning false when audioSink.isEnded is called!

**Comment by extorn** [comment] 2019-04-30 08:51
Sorry. I spoke too soon - actually the bug remains - the call to isEnded() in MediaCodecRenderer returns false always since the outputStreamEnded field has not been set to true.

**Comment by tonihei** [comment] 2019-04-30 11:51
The provided test stream plays (and ends) perfectly fine in the current code version. Can you try updating to the latest version (2.10-alpha) to check whether the problem still occurs?

**Comment by extorn** [comment] 2019-04-30 11:54
thanks. It plays fine in exoplayer:2.8.2 too. I'll check if it ends correctly and get back to you.

**Comment by tonihei** [comment] 2019-05-08 08:31
Closing, because the issue is not reproducible on newer versions of ExoPlayer.

**Closed as completed by tonihei** 2019-05-08 08:31 UTC
Labels: wont fix: not reproducible
