### ISSUE TITLE
VLC streaming UDP play Caton

### ISSUE THREAD

**Issue by cl-geniatech** [google/ExoPlayer#6226] opened 2019-07-26 07:32 UTC
Download the link code stream https://mega.nz/#!p2ZQCaIT!8e4GdXgv0Hd3mplvjeB9v4wBcYknh-f8W3i-RKYjfOg, streaming UDP through VLC string, EXOPlayer playing Caton

**Comment by marcbaechinger** [comment] 2019-07-31 08:56
Can you please provide some more info about what the issue is and what your expectations are?

You can find the issue description here: https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md

**Comment by cl-geniatech** [comment] 2019-08-01 03:02
Hi Marc:

Thanks for the inquiry, the main problem is to play Caton, which is expected to play smoothly. At present, the support for UDP is not good yet.
My test is through VLC streaming UDP, tested on Android7.1 STB, please know

chenlei@geniatech.com

**Comment by marcbaechinger** [comment] 2019-11-13 12:06
Closing due to lack of information and activity.

**Closed as completed by marcbaechinger** 2019-11-13 12:06 UTC
Labels: content not playing
