### ISSUE TITLE
A subset of Samsung devices crashes when changing between streams. 

### ISSUE THREAD

**Issue by marcinOz** [google/ExoPlayer#4162] opened 2018-04-20 13:06 UTC
### Issue description
We add our streams and swipe to change functionality to ExoPlayer demo app. 
A subset of Samsung devices crashes when changing between those streams. 

### Reproduction steps
1. Open our version of ExoPlayer demo app (provided by mail).
2. Start any stream
3. Start swiping left and right through streams 
4. after a long period of time ~ 10 min app crashes

### Link to test content
by email to dev.exoplayer@gmail.com using a subject "Issue #4162".

### Version of ExoPlayer being used
2.7.3

### Device(s) and version(s) of Android being used
== Exynos 7 Octo (7870) ==

Samsung Galaxy J7 (2017) - Android 7.0
Samsung Galaxy J5 (2017) - Android 7.0
Samsung Galaxy A3 (2017) - Android 7.0
Samsung Galaxy J7 (2016)

== Exynos 7 Quad (7570) ==

Samsung Galaxy J3 (2017)
Samsung Galaxy Xcover 4

### A full bug report captured from the device

[channel_list_click.txt](https://github.com/google/ExoPlayer/files/1931815/channel_list_click.txt)

![screen shot 2018-04-05 at 10 44 58](https://user-images.githubusercontent.com/6572599/39047166-2683dc20-4499-11e8-919e-1e03767f1f48.png)
![screen shot 2018-04-05 at 11 06 48](https://user-images.githubusercontent.com/6572599/39047189-43c79740-4499-11e8-98d9-1676d64f9061.png)

**Comment by botaydotcom** [comment] 2018-04-20 13:10
Duplicate of #4161.

**Comment by botaydotcom** [comment] 2018-04-20 13:11
I will close the other duplicated issue instead.

**Comment by giladna** [comment] 2018-04-22 06:26
@botaydotcom 

I think it is related to this issue
https://issuetracker.google.com/issues/77891433

We also have J7 device that restarts in change when switching between sources with protected content

**Comment by ojw28** [comment] 2018-12-19 16:09
Agree this is tracked by the issue ref'd in the post above. I don't think there's much we can do about it at our layer; it likely needs to be fixed in the platform.

**Comment by ojw28** [comment] 2019-04-05 22:19
Closing this. The issue is tracked by https://issuetracker.google.com/issues/77891433.

**Closed as completed by ojw28** 2019-04-05 22:19 UTC
Labels: bug: device specific
