### ISSUE TITLE
ArrayIndexOutOfBoundsException when player is closed while playing ad

### ISSUE THREAD

**Issue by oguzhaneksi** [google/ExoPlayer#8796] opened 2021-04-05 20:14 UTC
**Issue Description**

I get this exception when finished the player activity while playing an ad.

> java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.maybeUpdateAdMediaSources(AdsMediaSource.java:316)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.onAdPlaybackState(AdsMediaSource.java:295)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.access$100(AdsMediaSource.java:58)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource$ComponentListener.lambda$onAdPlaybackState$0$AdsMediaSource$ComponentListener(AdsMediaSource.java:405)
        at com.google.android.exoplayer2.source.ads.-$$Lambda$AdsMediaSource$ComponentListener$EnOXLA4Xyh_hsc2De4jHB6dR5vU.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

Do you have any idea that why this exception occurs?

**Reproduction steps**
Can't.

**Link to test content**
Not available.

**Version of ExoPlayer being used**
2.13.2

**Device(s) and version(s) of Android being used**
Variety devices.
Variety os versions.

**Comment by andrewlewis** [comment] 2021-04-06 08:54
Please see #8693 -- I think this is probably a duplicate of that.

**Comment by andrewlewis** [comment] 2021-04-06 08:54
Duplicate of #8693

**Closed as completed by andrewlewis** 2021-04-06 08:54 UTC
Labels: duplicate
