### ISSUE TITLE
Bug: cannot work together with Android-x ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4484] opened 2018-07-08 11:22 UTC
Suppose you take a completely new project on Android Studio canary/beta, that has Android-X instead of the support library.

And you add just these 2 lines of ExoPlayer:

    implementation 'com.google.android.exoplayer:exoplayer-core:2.8.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.8.1'

Then you get an error message as I've reported here:
https://issuetracker.google.com/issues/111205657

If you wish to try it out, take the project I've uploaded there. Strip it away from anything related to Exoplayer, see that it builds fine, and then add these 2 lines and try to build.

**Comment by botaydotcom** [comment] 2018-07-09 09:54
I think this is probably a duplicate of #4387. At the moment, the workaround seems to be avoid using the new AndroidX libraries if you need to use ExoPlayer. We will try to migrate to use AndroidX, but I have no idea about the timeline.

**Closed as completed by botaydotcom** 2018-07-09 09:54 UTC
Labels: question

**Comment by AndroidDeveloperLB** [comment] 2018-07-09 10:13
That's too bad.
Can you please keep this issue open till it gets fixed, then?
Maybe provide 2 branches for now? One for Android-X and one for support library?

**Comment by ojw28** [comment] 2018-07-09 19:56
I tried to reproduce this using Android Studio 3.3 Canary 2, with everything up to date, and I was not able to reproduce. You should have the following in your `gradle.properties` file, which will automatically convert any libraries you're using that still use the old support library to use `androidx` instead, hence avoiding the compatibility problem:
```
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
```
There should also be the following in the same file:
```
android.useAndroidX=true
```
Do you see both of those? And are you definitely using the latest Android Studio Canary?

**Comment by AndroidDeveloperLB** [comment] 2018-07-09 21:07
Those 2 lines weren't there for some reason.
How come?
Adding them has made it possible to use this sample project I've made.

**Comment by ojw28** [comment] 2018-07-09 21:14
I think some kinks were (or are) still being ironed out with Android Studio Beta/Canary (they're Beta/Canary for a reason, I guess!). So most likely the lines should have been added, but weren't.

Anyway, it's good to know it works (and to figure out how to deal with this!).

**Comment by AndroidDeveloperLB** [comment] 2018-07-10 06:49
I suggest to put it in the main page or FAQ, or something.

**Comment by ojw28** [comment] 2018-07-10 07:16
Unless this ever becomes a problem with a stable version of Android Studio, I'm not sure that's necessary. We'll keep an eye on it though.

**Comment by xellDart** [comment] 2018-09-02 20:21
same her, i get error on compilation

**Comment by cckroets** [comment] 2018-10-11 18:39
Eventually every active library should be on androidx. Forcing apps to use jetifier should not be a long term solution. Can we leave this issue open until there is a release that uses androidx?

**Comment by ojw28** [comment] 2018-10-11 19:01
Feel free to file a new tracking issue if you feel one should exist (this one is quite noisy, and is only tangentially related). Note that the existence of a tracking issue isn't in itself going to make any difference to when we make the switch. I don't think we're aware of any reason to hurry, so unless we hear otherwise we'll probably switch naturally when we need a feature that didn't make it into the last feature release of the support library (28.0.0).
