### ISSUE TITLE
Playing TS file problem

### ISSUE THREAD

**Issue by cuiwei78** [google/ExoPlayer#6439] opened 2019-09-18 06:46 UTC
Before filing a content issue:
------------------------------
- Search existing issues, including issues that are closed:
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
- Consult our supported formats page, which can be found at
  https://exoplayer.dev/supported-formats.html.
- Learn how to create useful log output by using the EventLogger:
  https://exoplayer.dev/listening-to-player-events.html#using-eventlogger
- Try playing your content in the ExoPlayer demo app. Information about the
  ExoPlayer demo app can be found here:
  http://exoplayer.dev/demo-application.html.

When reporting a content issue:
-----------------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Content description
A karaoke video file in TS format which contains two audio tracks.

### [REQUIRED] Link to test content
http://211.103.208.76:8089/d_song/386278.ts

### [REQUIRED] Version of ExoPlayer being used
latest

### [REQUIRED] Device(s) and version(s) of Android being used
Huawei Android Phone, Android 8.0.

### [REQUIRED] A full bug report captured from the device
Only video is displayed but no sound.

I have problem using latest ExoPlayer to play a TS file.
I put the TS file on my server and make it as Http url: 
http://211.103.208.76:8089/d_song/386278.ts 

My code to play it is below:
========================================
exoPlayer = ExoPlayerFactory.newSimpleInstance(this);
exoPlayer.setVideoSurfaceView(videoView);
final DataSource.Factory factory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "myExo"));
MediaSource mediaSource1 = new ProgressiveMediaSource.Factory(factory).createMediaSource(Uri.parse(test));
exoPlayer.setAudioAttributes(new AudioAttributes.Builder().setContentType(C.CONTENT_TYPE_MUSIC).build());
exoPlayer.prepare(mediaSource1);
exoPlayer.setPlayWhenReady(true);
exoPlayer.setRepeatMode(Player.REPEAT_MODE_ALL);
=========================================
But the result is, video can play but no audio sound.
Could you please help fine what is the problem?

**Comment by cuiwei78** [comment] 2019-09-18 08:16
More info, the audio inside TS is mp2, does not ExoPlayer support mp2 audio?

**Comment by AquilesCanta** [comment] 2019-09-19 15:53
Next time you file an issue, please provide everything requested in the issue template. You are missing a bugreport.

ExoPlayer supports any codecs available in the device. Seems to me this is a duplicate of #3076. You might want to consider using the [ffmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) to support missing audio codecs.

**Closed as completed by AquilesCanta** 2019-09-19 15:53 UTC
Labels: wont fix: intended behavior
