### ISSUE TITLE
HLS: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by Jedashford** [google/ExoPlayer#1056] opened 2015-12-14 06:44 UTC
I'm testing our streams with the newest player (not sure if we're also getting this on the old player).

Randomly throughout the movie the player just dies. I get the below errors. Its always the same. It looks like a segment is failing, or is failing to download within a timeout period.

My question is: how can I see the segments that are being downloaded and how can I get http codes and other network information? Specifically, how can I get better debug information related to networking in exoplayer?

Thanks for what you're doing. HLS is our only option for what we do and without exoplayer, we'd be limited to few platforms.

```
12-13 23:02:15.012 19152-19152/com.vidangel E/EventLogger: internalError [34.21, loadError]
                                                           com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: Read timed out
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70)
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99)
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
                                                               at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101)
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82)
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                                                               at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)
                                                            Caused by: java.net.SocketTimeoutException: Read timed out
                                                               at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
                                                               at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
                                                               at com.android.okio.Okio$2.read(Okio.java:113)
                                                               at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                               at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
                                                               at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70) 
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99) 
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155) 
                                                               at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101) 
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82) 
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114) 
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                                                               at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108) 
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:818) 
12-13 23:02:24.488 19152-19152/com.vidangel E/EventLogger: internalError [43.69, loadError]
                                                           com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: Read timed out
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70)
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99)
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
                                                               at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101)
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82)
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                                                               at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)
                                                            Caused by: java.net.SocketTimeoutException: Read timed out
                                                               at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
                                                               at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
                                                               at com.android.okio.Okio$2.read(Okio.java:113)
                                                               at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                               at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
                                                               at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70) 
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99) 
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155) 
                                                               at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101) 
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82) 
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114) 
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                                                               at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108) 
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:818) 
12-13 23:02:24.967 612-1127/? W/ActivityManager: getRunningAppProcesses: caller 10053 does not hold REAL_GET_TASKS; limiting output
12-13 23:02:26.881 1984-2069/? W/bt-att: gatt_ind_ack_timeout send ack now
12-13 23:02:26.937 1984-2069/? E/bt-btif: indication/notif for unknown device, ignore
12-13 23:02:26.937 1984-2069/? E/bt-btif: indication/notif for unknown device, ignore
12-13 23:02:28.284 19152-19152/com.vidangel E/EventLogger: internalError [47.49, loadError]
                                                           com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70)
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99)
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
                                                               at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101)
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82)
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                                                               at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)
                                                            Caused by: java.net.ProtocolException: unexpected end of stream
                                                               at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
                                                               at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70) 
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99) 
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155) 
                                                               at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101) 
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82) 
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114) 
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                                                               at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108) 
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:818) 
12-13 23:02:28.294 19152-2545/com.vidangel E/ExoPlayerImplInternal: Internal track renderer error.
                                                                    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:141)
                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                                                                        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                                        at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                                        at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77)
                                                                        at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70)
                                                                        at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99)
                                                                        at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
                                                                        at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101)
                                                                        at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82)
                                                                        at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
                                                                        at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                                                                        at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                     Caused by: java.net.ProtocolException: unexpected end of stream
                                                                        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
                                                                        at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                                        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                                        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                                        at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                                        at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77) 
                                                                        at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70) 
                                                                        at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99) 
                                                                        at javax.crypto.CipherInputStream.read(CipherInputStream.java:155) 
                                                                        at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101) 
                                                                        at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82) 
                                                                        at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114) 
                                                                        at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                                                                        at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108) 
                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                        at java.lang.Thread.run(Thread.java:818) 
12-13 23:02:28.306 13943-2592/? D/NvOsDebugPrintf: TVMR: TVMRFrameDelivery: 5180: Closing TVMR Frame Delivery Thread -------------
12-13 23:02:28.307 19152-19152/com.vidangel E/EventLogger: playerFailed [47.51]
                                                           com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                                                               at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
                                                               at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:141)
                                                               at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
                                                               at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                               at android.os.Handler.dispatchMessage(Handler.java:100)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                               at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                            Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:260)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77)
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70)
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99)
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
                                                               at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101)
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82)
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114)
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
                                                               at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)
                                                            Caused by: java.net.ProtocolException: unexpected end of stream
                                                               at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
                                                               at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:552)
                                                               at com.google.android.exoplayer.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:258)
                                                               at com.google.android.exoplayer.upstream.DefaultUriDataSource.read(DefaultUriDataSource.java:141) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:77) 
                                                               at com.google.android.exoplayer.upstream.DataSourceInputStream.read(DataSourceInputStream.java:70) 
                                                               at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:99) 
                                                               at javax.crypto.CipherInputStream.read(CipherInputStream.java:155) 
                                                               at com.google.android.exoplayer.hls.Aes128DataSource.read(Aes128DataSource.java:101) 
                                                               at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:82) 
                                                               at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:114) 
                                                               at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240) 
                                                               at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108) 
                                                               at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:818) 
12-13 23:02:28.313 13943-2593/? D/NvOsDebugPrintf: TVMR: TVMRVPRFloorSizeSettingThread: 5147: Closing TVMRVPRFloorSizeSettingThread -------------
12-13 23:02:28.318 13943-2588/? D/NvOsDebugPrintf: TVMR: NvMMLiteTVMRDecBlockClose: 6871: Done 
```

**Comment by ojw28** [comment] 2015-12-15 23:50
`HttpDataSourceException` contains a `dataSpec` field that tells you what data was requested. So look at that. In this case the status code will have been in the 2XX range. If the status code is outside of this range then you'd get an `InvalidResponseCodeException`, which has a `responseCode` field that tells you what the status code was.

**Comment by Jedashford** [comment] 2015-12-16 01:55
@ojw28 Thank you. We'll go through further testing and see if we can track down the problem. We've been using this in all of our VidAngel apps and think this one has been giving us trouble for a while. We're following the apple spec on HLS, but deviate on clip length. Due to the way we allow customers to customize streams, we have clip lengths from .2 sec through 9 sec. Could be the problem, but we've found success on all other platforms (iOS, desktop, Roku, etc.)

**Comment by ojw28** [comment] 2015-12-16 18:27
It's unlikely to be an issue with clip length. The root causes are all quite far down in the networking layer, below any layers in which media specific things are happening. I would guess there's a server-side issue. This part of the log is of particular interest:

```
Caused by: java.net.ProtocolException: unexpected end of stream
  at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
  at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
```

I think this is indicative of a server providing a `Content-Length` value in a response header that does not match the length of the response body (the body turns out to be shorter). If my understand is correct, that kind of behavior is invalid from the server.

**Comment by ojw28** [comment] 2016-01-04 15:19
Closing as a probable server error.

**Closed by ojw28** 2016-01-04 15:19 UTC
Labels: question

**Comment by Jedashford** [comment] 2016-02-01 02:31
@ojw28 still attempting to track this one down. Our Android customer base is growing any many get video stalls multiple times in a video session. How would you suggest I get access to HTTP logs. Specifically how can I see each network response and its headers? This is for HLS and all segments we're requesting. I don't see anything on the event logger that would give me that info. Any help here would be grateful.
