### ISSUE TITLE
How can I convert the main video to another named video in the same group?(multiple angle)

### ISSUE THREAD

**Issue by opgj123** [google/ExoPlayer#8360] opened 2020-12-17 09:14 UTC
```
if (mainPlayer == null) {
            trackMainSelector = new DefaultTrackSelector(this);
            trackMainSelector.setParameters(
                    trackMainSelector.buildUponParameters().setMaxVideoSizeSd());
            mainPlayer = new SimpleExoPlayer.Builder(this)
                    .setTrackSelector(trackMainSelector)
                    .build();
        }
        playerMainView.setPlayer(mainPlayer);
        MediaItem mediaItem = new MediaItem.Builder()
                .setUri(getString(R.string.live_url))
                .setMimeType(MimeTypes.APPLICATION_M3U8)
                .build();
        mainPlayer.setMediaItem(mediaItem);
        mainPlayer.setPlayWhenReady(playWhenReady);
        mainPlayer.seekTo(currentWindow, playbackPosition);
        mainPlayer.prepare();
```
Set as above to play the video.

example m3u8 file
`#EXTM3U`
`#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="200kbs",NAME="Angle1",AUTOSELECT=YES,DEFAULT=YES`
`#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="200kbs",NAME="Angle2",AUTOSELECT=YES,DEFAULT=NO, URI="Angle2/200kbs/prog_index.m3u8"`
`#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="500kbs",NAME="Angle1",AUTOSELECT=YES,DEFAULT=YES`
`#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="500kbs",NAME="Angle2",AUTOSELECT=YES,DEFAULT=NO, URI="Angle2/500kbs/prog_index.m3u8"`
```
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="English",AUTOSELECT=YES, DEFAULT=YES,URI="eng/prog_index.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=300000,CODECS="mp4a.40.2,avc1.4d401e", VIDEO="200kbs",AUDIO="aac"
Angle1/200kbs/prog_index.m3u
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=754857,CODECS="mp4a.40.2,avc1.4d401e", VIDEO="500kbs",AUDIO="aac"
Angle1/500kbs/prog_index.m3u8
```
The setSelectionOverride method switches tracks, but cannot play other videos in the same group.
```
if (trackType == C.TRACK_TYPE_VIDEO){
builder.setRendererDisabled(rendererIndex, false);
int groupIndex = 0; 
DefaultTrackSelector.SelectionOverride override = new DefaultTrackSelector.SelectionOverride(groupIndex, 0);
builder.setSelectionOverride(rendererIndex, mappedTrackInfo.getTrackGroups(rendererIndex), override);
}
trackMainSelector.setParameters(builder);
```

Angle1/200kbs/prog_index.m3u -> Angle1/500kbs/prog_index.m3u8 (o)

Angle1/200kbs/prog_index.m3u -> Angle2/200kbs/prog_index.m3u8 (x)
How can I switch the angle?

**Comment by ojw28** [comment] 2020-12-17 12:36
Duplicate of https://github.com/google/ExoPlayer/issues/2600

**Closed as completed by ojw28** 2020-12-17 12:36 UTC
Labels: duplicate, question

**Comment by opgj123** [comment] 2020-12-18 01:34
Is the work in progress?
