### ISSUE TITLE
samsung GT-P5100 API 17 error

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#228] opened 2015-01-07 08:51 UTC
```
java.lang.IllegalArgumentException
        at android.media.MediaCodecList.getCodecCapabilities(MediaCodecList.java:-2)
        at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:211)
        at com.google.android.exoplayer.MediaCodecUtil.a(Unknown:-1)
        at com.google.android.exoplayer.MediaCodecUtil.b(Unknown:-1)
        at com.google.android.exoplayer.MediaCodecUtil.a(Unknown:-1)
```

**Comment by ojw28** [comment] 2015-01-07 12:44
https://github.com/google/ExoPlayer/pull/53 would fix this, but it's still a little unclear whether we should do that. It depends a bit on whether these failure modes are permanent or temporary (the latter may occur if the mediaserver dies underneath us, I think).

Please clarify:

- What were you trying to play when you observed this? If possible, please provide the mime type being checked when the crash occurs.
- Was it 100% reproducible, or did it just happen once?

**Comment by crossle** [comment] 2015-01-08 01:16
Sorry, I have no GT-P5100, so not reproduce, but I sure playback hls,  Video: h264 (Main) Audio: aac (LC)

**Comment by ojw28** [comment] 2015-01-08 01:28
Where did the stack trace come from? If you have a released application and you got the report from logging/feedback reports, then some idea of the number of reports relative to the number of playbacks on these devices would give a good idea of how serious the problem is.

I suspect that it's a problem that occurs when mediaserver happens to die just at the point where the codecs are being queried, in which case it should occur very infrequently.

**Comment by edisonw** [comment] 2015-01-10 05:16
gonna give my 2 cents on "whether these failure modes are permanent or temporary" (not specific to my PR, but just in general), ExoPlayer is great and it is deployed on 10s of millions of Vine users, and I think the greatest benefit of having it not be part of the framework code but instead an open source project IS that we can have monkey patches for specific devices and get rid of monkey patches when they get fixed. I totally understand the argument of not having device specific things merged in as the list can get large, but then I feel like we are not taking advantage of the "crowd sourced" nature of being open source.

**Comment by ojw28** [comment] 2015-01-10 09:43
Thanks for the input. I think there are two distinct problems here:

- MediaCodecUtil calls methods in the framework that make cross-process calls, I think into mediaserver. There is a very low but non-zero probability of sporadic failure (e.g. if mediaserver crashes), across a wide range of devices.
- A small range of older devices always fail when queried, due to incorrect configuration. You observed this for the GT-I9100. I got hold of one of these and confirmed that the issue is 100% repeatable.

Both of these currently manifest themselves as runtime exceptions which application developers are unlikely to catch, meaning their applications will end up crashing when either issue occurs.

- I think the correct fix for the first problem is to have MediaCodecUtil throw a checked exception. This forces an application developer handle the case, meaning they wont ship an application that will crash when the problem does occur (assuming they handle it in a sensible way). It's analogous to IPC in Java throwing RemoteException.
- For the second problem, I think we should be doing as you say and crowd-sourcing any fixes for specific bad configurations. For these particular cases we want MediaCodecUtil to hide the exception and carry on looking for a suitable decoder. We need to target these fixes quite precisely (e.g. specific device/decoder combinations), so that we don't end up hiding any instances of the first problem.

I'll submit a change to throw a checked exception, and then we can follow up on the second problem and figure out exactly how specific the targeting should be.

**Comment by edisonw** [comment] 2015-01-10 19:45
Thanks for the reply. Yea, this sounds like the correct path to solution to me as well. I think you guys are doing a great job and to me sounds like how new quality new components on Android can be produced in the future (as we both know how manufacturers gaming Android CTS to get products out faster). :)

**Comment by ojw28** [comment] 2015-01-12 17:46
Sporadic failures are now indicated with a checked exception.

The remaining work here is to add special cases for any known cases where 100% failure occurs. In these cases we should skip/ignore/fill-in as appropriate, to replicate what the underlying platform would have done were it configured correctly.

**Comment by ojw28** [comment] 2015-01-12 17:49
Closing this. We'll use #53 to track the incorrect configuration problem.

**Closed by ojw28** 2015-01-12 17:49 UTC
