### ISSUE TITLE
Missing audio when playing back MP4 file

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#731] opened 2015-08-21 08:52 UTC
Sample: http://demo-uhd3d.com/files/uhd4k/Samsung_UHD_Soccer_Barcelona_Atletico_Madrid.ts

When playing back this file which has an AAC Stereo track, only visible plays.

```
General
Complete name : /Users/Ian/Movies/HEVC/Samsung_UHD_Soccer_Barcelona_Atletico_Madrid.ts
Format : MPEG-4
Format profile : Base Media
Codec ID : iso4
File size : 1.24 GiB
Duration : 3mn 52s
Overall bit rate mode : Variable
Overall bit rate : 45.8 Mbps
Encoded date : UTC 2014-06-03 22:43:24
Tagged date : UTC 2014-06-03 22:43:24

Video
ID : 1
Format : HEVC
Format/Info : High Efficiency Video Coding
Format profile : Main@L5.1@High
Codec ID : hvc1
Codec ID/Info : High Efficiency Video Coding
Duration : 3mn 51s
Bit rate : 45.7 Mbps
Maximum bit rate : 116 Mbps
Width : 3 840 pixels
Height : 2 160 pixels
Display aspect ratio : 16:9
Frame rate mode : Constant
Frame rate : 50.000 fps
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Bits/(Pixel*Frame) : 0.110
Stream size : 1.23 GiB (100%)
Title : Encoded with IFME v3.2.1.0
Encoded date : UTC 2014-06-03 22:43:24
Tagged date : UTC 2014-06-03 22:43:32

Audio
ID : 2
Format : AAC
Format/Info : Advanced Audio Codec
Format profile : LC
Codec ID : 67
Duration : 3mn 52s
Bit rate mode : Variable
Bit rate : 118 Kbps
Maximum bit rate : 143 Kbps
Channel(s) : 2 channels
Channel positions : Front: L R
Sampling rate : 48.0 KHz
Compression mode : Lossy
Stream size : 3.26 MiB (0%)
Title : Track 1
Encoded date : UTC 2014-06-03 22:43:31
Tagged date : UTC 2014-06-03 22:43:32
```

**Comment by ojw28** [comment] 2015-08-21 16:32
This is an MP4 file (despite the naming of the url). The root cause is a failure to determine the mime type in AtomParsers.

**Comment by ojw28** [comment] 2015-08-21 18:30
We'll merge a fix for this next week.

**Comment by IanDBird** [comment] 2015-08-31 08:46
@ojw28 - Sorry, but any update on when this fix might become available? Thanks

**Closed** 2015-09-01 13:10 UTC
Labels: bug
