### ISSUE TITLE
black screen when waiting load ads

### ISSUE THREAD

**Issue by mancuk** [google/ExoPlayer#10697] opened 2022-10-18 07:59 UTC
for the first time playing the first video, the ad is shown successfully. but when i try to play the second video, the ad loading runs for a long time and just a black screen

**Comment by ahmedaa6122** [comment] 2022-10-18 08:12
Can i contact with you in telegram or whattsapp please

**Comment by mancuk** [comment] 2022-10-18 08:24
> Can i contact with you in telegram or whattsapp please

did you experience the same?

**Comment by ahmedaa6122** [comment] 2022-10-18 10:57
I can help you send me WhatsApp or telegram

**Comment by tonihei** [comment] 2022-10-19 12:30
Please provide more detailed reproduction steps and explanations of what's happening. Otherwise we can't really address the issue if we can't understand what you are seeing and how it occurs.

**Comment by mancuk** [comment] 2022-10-20 06:35
> Please provide more detailed reproduction steps and explanations of what's happening. Otherwise we can't really address the issue if we can't understand what you are seeing and how it occurs.

first,
when about to start the video, an ad appears.
but when we play another video the ad doesn't appear.
the ad only appears once when we open the app and play the video. but after that the ad no longer appears when playing another video. only black screen appears

**Comment by tonihei** [comment] 2022-10-20 09:52
This doesn't really help I'm afraid. Please provide specific steps we need to take to reproduce the problem (e.g. describing changes to the demo app )

**Comment by mancuk** [comment] 2022-10-21 06:51
> This doesn't really help I'm afraid. Please provide specific steps we need to take to reproduce the problem (e.g. describing changes to the demo app )

I have 2 videos: Video A and Video B
when i start video A an ad appears before the video,
but when I start video B the ad doesn't appear at all and the video doesn't exist, there's only a black screen

**Comment by mancuk** [comment] 2022-10-21 06:52
> > This doesn't really help I'm afraid. Please provide specific steps we need to take to reproduce the problem (e.g. describing changes to the demo app )
> 
> I have 2 videos: Video A and Video B when i start video A an ad appears before the video, but when I start video B the ad doesn't appear at all and the video doesn't exist, there's only a black screen

private fun initializePlayer() {

        val mediaSourceFactory: MediaSource.Factory = DefaultMediaSourceFactory( /* context= */this)
            .setLocalAdInsertionComponents(
                 { adtags: MediaItem.AdsConfiguration? -> clientSideAdsLoader },  /* adViewProvider= */
                playerView!!
            )

        playerView.let {
//            it!!.requestFocus()
            player = ExoPlayer.Builder(this)
                .setMediaSourceFactory(mediaSourceFactory)
                .setSeekForwardIncrementMs(10000)
                .setSeekBackIncrementMs(10000)
                .build()
            it!!.player = player
            clientSideAdsLoader!!.setPlayer(player)
            binding.ytOverlay.player(player!!)

            debugViewHelper = DebugTextViewHelper(player!!, binding.debugTextView)
            debugViewHelper!!.start()

            val haveResumePosition = mResumeWindow != C.INDEX_UNSET

            if (haveResumePosition) {
                Log.i("DEBUG", " haveResumePosition ")
                player!!.seekTo(mResumeWindow, mResumePosition)
            }

            val mediaItem  = MediaItem.Builder()
                .setUri(urlHls)
                .setMimeType(MimeTypes.APPLICATION_M3U8)
                .setAdsConfiguration(
                    MediaItem
                        .AdsConfiguration
                        .Builder(
                            Uri.parse(TAG_ADS))
                        .build()
                )
                .build()


            player!!.addListener(PlayerEventListener())
            player!!.setMediaItem(mediaItem)
            player!!.prepare()
            updateButtonVisibility()

        }

**Comment by tonihei** [comment] 2022-11-01 10:29
It's expected that the same Ad tag doesn't play again if it was already played. I tried this scenario with an HLS stream in our demo app and everything works as expected. If you think something doesn't work as expected, please make sure to provide steps someone can follow to reproduce the problem.

**Comment by mancuk** [comment] 2022-11-01 10:43
> It's expected that the same Ad tag doesn't play again if it was already played. I tried this scenario with an HLS stream in our demo app and everything works as expected. If you think something doesn't work as expected, please make sure to provide steps someone can follow to reproduce the problem.

**Comment by mancuk** [comment] 2022-11-01 10:49
> > It's expected that the same Ad tag doesn't play again if it was already played. I tried this scenario with an HLS stream in our demo app and everything works as expected. If you think something doesn't work as expected, please make sure to provide steps someone can follow to reproduce the problem.


I will try again with existing documents, if there are still errors I will record

**Comment by tonihei** [comment] 2022-11-14 13:43
Closing again, because there is nothing actionable for us at the moment. If you can reproduce a problem and think there is something we need to change, please reopen or file a new issue.

**Closed as completed by tonihei** 2022-11-14 13:43 UTC
Labels: question, needs triage
