### ISSUE TITLE
Is it possible to skip an element inside a ConcatenatingMediaSource if the source is not availiable?

### ISSUE THREAD

**Issue by cle-bo** [google/ExoPlayer#6757] opened 2019-12-12 13:28 UTC
Hello and thanks for your support.
I want to execute the following code:

![image](https://user-images.githubusercontent.com/50229987/70716928-9cb29e80-1ced-11ea-9445-65a5c9a230ad.png)

- three filepaths with one filepath leading to a file that doesnt exist (DOESNOTEXIST.mp4)
- create a ConcatenatingMediaSource with three ProgressiveMediaSources representing those three filepaths (pms1, pms2 and pms3)

What I want to achieve:
- prepare the playlist starting with psm1-playback
- after psm1 ended and psm2 can't be found ("Source error") the playback of psm3 starts

What actually happens:
- playback starts with psm1 (so far so good) but then
- playback stops with the last frame of psm1 and the following error occurs:
`2019-12-12 14:22:20.548 21560-21660/com.airtango.lpsplayer E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/9C33-6BBD/Android/media/DOESNOTEXIST.mp4: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.io.FileNotFoundException: /storage/9C33-6BBD/Android/media/DOESNOTEXIST.mp4: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:455)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
        at libcore.io.IoBridge.open(IoBridge.java:441)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128) 
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) `

So the question is: How can I interfere with the ProgressiveMediaSource-implementation and handle the Source error in a different way by skipping the element and continue with the next element of the playlist?

I read about [LoadErrorHandling in exoplayer at medium.com](https://medium.com/google-exoplayer/load-error-handling-in-exoplayer-488ab6908137) but it seems as this is only possible with adaptive media sources such as HLS, DASH, and SmoothStreaming and is not possible with a ProgressiveMediaSource in my case, right? Can I somehow inject a different Loader for my PMS?

Maybe somewhere around here?!?!
com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)

Thanks :-)

**Comment by christosts** [comment] 2019-12-16 13:10
Hi @cle-bo,

unfortunately this is not possible at the moment.  [This comment](https://github.com/google/ExoPlayer/issues/4343#issuecomment-394273056) from issue #4343 provides a workaround.

**Comment by ojw28** [comment] 2019-12-17 16:53
Closing this as a duplicate of https://github.com/google/ExoPlayer/issues/4343.

**Closed as completed by ojw28** 2019-12-17 16:53 UTC
Labels: duplicate
