### ISSUE TITLE
Some of the frames missing from the output of the decoder

### ISSUE THREAD

**Issue by cyriac83** [google/ExoPlayer#4739] opened 2018-08-28 16:35 UTC
Hello,

I am trying to extend the Exoplayer (running on Samsung Galaxy J3,  Android 7.0 Nougat) to save decoded frames of a video as a file for objective video quality analysis. For this, I have made changes to MediaCodecVideoRenderer class, and is able to save frames which are spitted out by the decoder. I am using Google's software decoder (again, by modifying Exoplayer to choose the software decoder since by default phone's hardware decoder is chosen) as frames are not accessible if hardware decoder is used.

Now, the issue I am facing is that some of the frames are missing in the saved video file (which is in yuv420 format by the way). For example, for a video (176*144 and 30 fps) of 300 frames, about 30 frames are missing! Is this possible? Could the decoder drop some frames by any chance? I have verified that all 300 frames are given as input the decoder, and don't notice any issues when the video is being played out on the screen.

Any help/insight is greatly appreciated.

Thank you!

**Comment by ojw28** [comment] 2018-08-28 16:39
The decoder should always output all frames (i.e. not drop any internally). ExoPlayer may drop frames after they're output from the decoder, so you need to make sure your logic to grab the decoded frames happens before that. If you're confident that you're doing this correctly, you'll need to file an issue with proper reproduction steps if you want us to investigate further.

**Comment by cyriac83** [comment] 2018-08-28 16:52
Thanks for the quick response!

Ok, I will go over my logic once again to see if I have done any mistake while capturing and writing frames to a file. BTW, could you please clarify whether the place "ExoPlayer may drop frames after they're output from the decoder" is in MediaCodecVideoRenderer class or somewhere else? I have seen the code snippet in MediaCodecVideoRenderer class where Exoplayer may drop a frame if it is too late for display (30ms -- Exoplayer 2.4.2) and doesn't pass it to the renderer. This would help me to investigate any logical error on my side better.

Thank you!

**Comment by ojw28** [comment] 2018-08-28 16:59
Yes, I'm referring to the code in `MediaCodecVideoRenderer` that drops the frame if it's too late for display.

By the way, we did used to observe that some decoders would drop a small number of frames internally in the specific case of adapting between different resolution streams in adaptive playback. I don't think this is relevant to your case, but one thing we did when we observed this was to put tests in place to check that video decoders satisfied a "number of frames in == number of frames out" rule. The Google software decoder passes these tests (unless you're running on a pretty old device; certainly it would have passed for Nougat). So unless there's something different about your input video that's causing the decoder to encounter a problem, I suspect it's more likely that the issue is in your code.

**Comment by cyriac83** [comment] 2018-08-28 17:03
Ok, great! Thanks for the clarification. I would get back you if the issue is not fixed. You may close this thread if you wish so.

Thanks again, much appreciated!

**Comment by ojw28** [comment] 2018-08-28 18:07
Closing for now, but please feel free to respond here if you want to follow up (there's no need to open a new issue, unless sufficient time has elapsed for this one to have been locked). Thanks!

**Closed as completed by ojw28** 2018-08-28 18:07 UTC
Labels: need more info

**Comment by cyriac83** [comment] 2018-08-29 20:09
Hi again!

You were right. Some of the frames are categorized as late and are being dropped , and that accounted for the missing frames. 

I am trying to see why these frames are categorized as late in the first place by the Exoplayer. Because of my experiment requirements, at least some frames of a video segment are likely to be out of order, and it is this out of order stream of frames that are downloaded (e.g., consider that UDP is used for streaming) by the Exoplayer and passed on to the decoder. 

Does Exoplayer timestamp each frame before passing it to the decoder (or in other words does Exoplayer assumes all frames in a segment to be in order)? If so, then I am wondering whether this time-stamping is causing some of the frames to be classified as "late". My understanding is that the decoder could take care of this out of ordering of frames based on Picture Order Count (POC).

Could you please shed some light on any time-stamping that is done by the Exoplayer before the encoded frames are passed on to the decoder?

**Comment by ojw28** [comment] 2018-08-31 14:28
> Because of my experiment requirements, at least some frames of a video segment are likely to be out of order, and it is this out of order stream of frames that are downloaded (e.g., consider that UDP is used for streaming) by the Exoplayer and passed on to the decoder.

I don't really understand this. Video decoders typically rely on frames being provided in a particular order (the decode order). Unless the stream consists only of key frames.

> Does Exoplayer timestamp each frame before passing it to the decoder (or in other words does Exoplayer assumes all frames in a segment to be in order)? If so, then I am wondering whether this time-stamping is causing some of the frames to be classified as "late". My understanding is that the decoder could take care of this out of ordering of frames based on Picture Order Count (POC).

The frame presentation timestamps are typically specified within the media itself, and those just get passed through the decoder. Note that decode order and presentation order are often different, meaning it's normal to see frames being queued to the decode with slightly out of order presentation timestamps, but being dequeued with in order presentation timestamps.

Isn't the most likely reason that frames are being classified as being late because they're actually late? Possibly because whatever you're doing to save the frames being output from the decoder is not fast enough to run in real time on your test device? If you don't have a real time requirement then just modify the code to never classify a frame as late, and the problem will probably just go away.

**Comment by cyriac83** [comment] 2018-08-31 16:03
"Video decoders typically rely on frames being provided in a particular order (the decode order)"

I am not sure if decoders could assume that frames would be always in a particular order, especially if frames are transmitted over a communication network that may change the decoder order (also known as transmission order). But, yes, as you have mentioned, decoders could reorder the frames no matter what order these frames eventually reach the decoder (same as how decoders convert from decoder to presentation order).

It is possible that my logic of writing frames is introducing the delay. I would definitely look over it. Before that, I just wanted to check whether Exoplayer does any time-stamping on each frame as soon as it is received from the network. Anyways, that part is now clear since you have clarified that decoders are using the frame presentation timestamps specified within the media itself. 

If you don't mind, could you also please clarify one more thing. Does Exoplayer sets decoder input queue/buffer size? If so, where in the code (class names) should I look in case I need to make any changes?

**Comment by ojw28** [comment] 2018-08-31 16:13
> I am not sure if decoders could assume that frames would be always in a particular order, especially if frames are transmitted over a communication network that may change the decoder order (also known as transmission order).

There are lots of layers between packets-received-over-the-network and feeding-the-decoder. By the time you get up to the layer where the decoder is being fed, I'm pretty certain samples need to be in correct decode order.

> Does Exoplayer sets decoder input queue/buffer size?

I'm not sure what this means exactly, but the decoder itself determines how many input and output buffers it provides.

**Comment by cyriac83** [comment] 2018-08-31 16:16
Ok, thanks for the clarifications! Those are really useful for me to investigate further. 

Thank you!
