### ISSUE TITLE
Normally you don't need to use CachedContentIndex directly. It is used by SimpleCache. Nothing happens if you don't use it directly :)

### ISSUE THREAD

**Issue by NgWaiKong** [google/ExoPlayer#5171] opened 2018-11-29 11:36 UTC
_Originally posted by @erdemguven in https://github.com/google/ExoPlayer/issues/5168#issuecomment-442757296_

Excuse me, is this CacheContentIndex for performance optimization? I see that I will store a copy of the file "cached_content_index.exi", which seems to be optimized for performance.

**Comment by andrewlewis** [comment] 2018-11-29 11:42
Please use the original issue for the continued discussion. I'll close this one as a duplicate of #5168.

**Closed as completed by andrewlewis** 2018-11-29 11:42 UTC
Labels: duplicate
