### ISSUE TITLE
Exoplayer Not Able to Show Embedded Video Subtitle for Some HLS(M3U8) Stream.

### ISSUE THREAD

**Issue by ajayhack** [google/ExoPlayer#10767] opened 2022-11-10 11:45 UTC
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Issue Reproduce on:-
1.Samsung Galaxy F62 (Android Version 12)

### Reproducible in the demo app?

Yes

### Reproduction steps

Issue HLS Stream shared on mail:- dev.exoplayer@gmail.com

### Expected result

ExoPlayer should able to show Embedded Subtitle.

### Actual result

ExoPlayer not able to show Embedded Subtitle of HLS Stream which is shared on dev.exoplayer@gmail.com

### Media

Issue HLS Stream shared on dev.exoplayer@gmail.com

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-11-10 13:39
We didn't receive the email mentioned above, please ensure you used the subject `Issue #10767` and try re-sending it.

**Comment by ajayhack** [comment] 2022-11-10 13:44
@icbaker , Please check again We have send again on dev.exoplayer@gmail.com.

**Comment by icbaker** [comment] 2022-11-10 16:06
The provided link returns me an HTTP 403 error when trying to play it from my device and also from `curl`.

Please let me know how to access the stream (is it geo-blocked?).

**Comment by ajayhack** [comment] 2022-11-10 17:31
@icbaker , Please check the same mail thread , We have replied on it and shared API Url , Request to get the latest Stream Url as it is session based expired so if previous one expired then please use the API Url , Request to get the latest Live HLS Stream Url.

**Comment by icbaker** [comment] 2022-11-10 17:37
I requested a new URL as described and played it immediately (within 2 mins). It also returned me a 403 error.

**Comment by ajayhack** [comment] 2022-11-10 17:40
@icbaker , Can you please let me know your location from where you requested I will check whether this stream is GEO-Blocked for that location.

**Comment by icbaker** [comment] 2022-11-10 17:43
I'd rather not share that information. If the stream is geo-blocked (which presumably you know?) I can try VPNing to an allowed geo. Otherwise if you'd like me to investigate please make a stream globally available that reproduces the problem.

**Comment by ajayhack** [comment] 2022-11-10 17:47
Yes Please if you can use VPN for INDIA Location and then get the stream from API, that would be great.

**Comment by icbaker** [comment] 2022-11-10 17:55
Requested a new URL, VPN'd to India from my device and played the new URL: 403 error again.

**Comment by ajayhack** [comment] 2022-11-10 17:58
Maybe you can try first connect to VPN INDIA then request url and then try to play and all the time VPN should be connected to INDIA location.

**Comment by icbaker** [comment] 2022-11-10 18:00
I'm afraid it's not easy to do that under my current VPN setup, and chasing your auth problems is unfortunately not a good use of my time. I'll look into this issue when a globally available stream is provided that reproduces the problem.

**Comment by ajayhack** [comment] 2022-11-11 05:38
@icbaker , Please check the same email thread , we have shared a video please reference it and get the stream url same way and then try to use it in browsers to check (Safari , Brave , Chrome).

Note:- Stream is Globally Available Now.

**Comment by ajayhack** [comment] 2022-11-21 11:33
@icbaker , Can you please provide update on this , please let me know if you required any more stuff from our end.
Please let me know as this is most priority for us.

**Comment by icbaker** [comment] 2022-11-21 14:46
I'm able to play the stream in hlsplayer.net on Chrome on MacOS, but not from my device running the demo app (where I still get a 403). Are you able to play these streams using the ExoPlayer demo app on your device?

**Comment by ajayhack** [comment] 2022-11-22 06:01
@icbaker , Yes we have tested our Live Stream on ExoPlayer Demo App on real device also and it's been playing.
Please check the mail , We have shared a video on playing our stream in exoplayer demo app on real device.

**Comment by icbaker** [comment] 2022-11-22 10:59
I'm able to play the stream now. I can see that subtitles are not visible. I tried disabling HLS chunkless preparation as suggested in https://github.com/google/ExoPlayer/issues/10352 and I can now enable subtitles and they show up.

Marking as a duplicate of https://github.com/google/ExoPlayer/issues/10352

**Closed as completed by icbaker** 2022-11-22 10:59 UTC
Labels: duplicate, bad media

**Comment by icbaker** [comment] 2022-11-22 11:11
I also notice that the stream provided here doesn't meets the [HLS authoring guidelines](https://developer.apple.com/documentation/http_live_streaming/http_live_streaming_hls_authoring_specification_for_apple_devices) regarding subtitles:

> 4.4. The presence of closed captions MUST be declared via an EXT-X-MEDIA tag that contains a LANGUAGE attribute.

I can't see an EXT-X-MEDIA tag in the manifest.

The stream provided originally in #10352 does include this info, so it's not clear if adding this would be enough to make subtitles show up, but you might like to try it.

**Comment by ajayhack** [comment] 2022-11-23 13:42
@icbaker , We are not using HLSMediaSource.Fatory we are using DefaultMediaSourceFactory and in this We did not have option to disable chunkless prepration through code , Can you suggest how can we disable chunkless prepration through code while using DefaultMediaSourceFactory.

For Reference Code Snippet we are ussing:-
MediaSource.Factory mediaSourceFactory =
                    new DefaultMediaSourceFactory(dataSourceFactory)
                            .setAdsLoaderProvider(this::getAdsLoader)
                            .setAdViewProvider(simpleExoPlayerView);

**Comment by icbaker** [comment] 2022-11-23 16:19
Currently it's quite tricky to customise the `HlsMediaSource.Factory` used inside `DefaultMediaSourceFactory` - and I see you're using ad playback config, so even if you only want to play HLS streams you can't use `HlsMediaSource.Factory` directly because it doesn't implement the ads integration. Moving things like ads integration into 'leaf' `MediaSource.Factory` implementations is tracked by https://github.com/androidx/media/issues/185.

We also have some thoughts about making `DefaultMediaSourceFactory` more flexible to allow tweaks like this, but they're not implemented yet (and we have no current plans to work on them).

For now you probably have two options:
1. Fork `DefaultMediaSourceFactory` and change the way it instantiates an `HlsMediaSource.Factory` to set chunkless to `false`.
2. [Depend on ExoPlayer locally](https://github.com/google/ExoPlayer#locally) and change the default value inside `HlsMediaSource.Factory` to `false`.

(2) is probably the easier option to maintain, since you only need to change one line - and future changes to the library should apply relatively cleanly on top of this patch (and you can always revert it, pull in a new version of the library, then re-apply it).
