### ISSUE TITLE
HLS freezing on certain videos

### ISSUE THREAD

**Issue by davidleu** [google/ExoPlayer#695] opened 2015-08-06 23:28 UTC
The Exoplayer works for most of the videos that I'm trying to play, but there's a few random videos that seem to drop all the frames consistently after about a second.  The audio seems to keep going but the video just freezes.  Occasionally, it'll play for 1s, freeze for 15s, play a few seconds, and then start dropping all the frames again but the majority of the time is the freezing forever after 2s.

URLs of non-working video: http://content.jwplatform.com/manifests/ZG0sqhaT.m3u8 http://content.jwplatform.com/manifests/8mhjqIya.m3u8 and more

I tried the exact same videos in a very simple sandbox app using just the MediaPlayer and that seemed to play those videos just fine with no freezing so I don't think it's a provider/network issue.  There are other videos from the same provider that play great (e.g. http://content.jwplatform.com/manifests/xjm4gf2b.m3u8), so I'm not sure if there's anything special about the videos that aren't working.

Same behavior on both Samsung Galaxy S4, Nexus 7, with both at 4.4.4.  Using the latest 1.4.2 from August 4.  Power cycling the devices didn't seem to help either.

Any insights?  Thanks.

Logcat below for non-working video:
```
08-06 10:51:46.170  15231-15231/com.google.android.exoplayer.demo D/ProgressBar﹕ setProgressDrawable drawableHeight = 48
08-06 10:51:46.180  15231-15231/com.google.android.exoplayer.demo D/AbsSeekBar﹕ AbsSeekBar Constructor: mAllowedSeeBarAnimation = true
08-06 10:51:46.180  15231-15231/com.google.android.exoplayer.demo D/Activity﹕ #1 setTransGradationModeColor false
08-06 10:51:46.180  15231-15231/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.4.2
08-06 10:51:46.190  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
08-06 10:51:46.190  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
08-06 10:51:46.190  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, true, P]
08-06 10:51:47.531  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ state [1.34, true, B]
08-06 10:51:47.531  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ videoFormat [1.35, 0, 0]
08-06 10:51:47.541  15231-22557/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
08-06 10:51:47.591  15231-22557/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
08-06 10:51:47.871  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ decoderInitialized [1.68, OMX.qcom.video.decoder.avc]
08-06 10:51:47.871  15231-22579/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
08-06 10:51:48.001  15231-22542/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 715K, 24% free 30951K/40216K, paused 28ms, total 28ms
08-06 10:51:48.041  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ videoSizeChanged [1920, 1080, 1.0]
08-06 10:51:48.071  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ state [1.88, true, R]
08-06 10:51:49.193  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [3.00, 50]
08-06 10:51:50.133  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [3.94, 50]
08-06 10:51:51.064  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [4.88, 50]
08-06 10:51:51.295  15231-22542/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 11538K, 41% free 23937K/40216K, paused 33ms, total 33ms
08-06 10:51:52.025  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [5.83, 50]
08-06 10:51:52.766  15231-22542/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 235K, 36% free 26041K/40216K, paused 27ms, total 28ms
08-06 10:51:52.966  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [6.78, 50]
08-06 10:51:53.897  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [7.71, 50]
08-06 10:51:54.197  15231-22542/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 132K, 29% free 28881K/40216K, paused 28ms, total 28ms
08-06 10:51:54.818  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [8.64, 50]
08-06 10:51:55.719  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [9.54, 50]
08-06 10:51:56.049  15231-22542/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 119K, 19% free 32724K/40216K, paused 27ms, total 28ms
08-06 10:51:56.650  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [10.47, 50]
08-06 10:51:57.581  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [11.39, 50]
08-06 10:51:58.492  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [12.30, 50]
08-06 10:51:59.443  15231-15231/com.google.android.exoplayer.demo D/EventLogger﹕ droppedFrames [13.25, 50]
```

Logcat of working video:
```
08-06 10:59:14.667  27406-27406/com.google.android.exoplayer.demo D/ProgressBar﹕ setProgressDrawable drawableHeight = 48
08-06 10:59:14.677  27406-27406/com.google.android.exoplayer.demo D/AbsSeekBar﹕ AbsSeekBar Constructor: mAllowedSeeBarAnimation = true
08-06 10:59:14.677  27406-27406/com.google.android.exoplayer.demo D/Activity﹕ #1 setTransGradationModeColor false
08-06 10:59:14.677  27406-27406/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.4.2
08-06 10:59:14.677  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
08-06 10:59:14.677  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
08-06 10:59:14.677  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, true, P]
08-06 10:59:15.088  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.42, true, B]
08-06 10:59:15.088  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ videoFormat [0.42, 0, 0]
08-06 10:59:15.088  27406-27829/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
08-06 10:59:15.138  27406-27829/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
08-06 10:59:15.308  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ decoderInitialized [0.64, OMX.qcom.video.decoder.avc]
08-06 10:59:15.308  27406-27837/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
08-06 10:59:15.478  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ videoSizeChanged [1920, 1080, 1.0]
08-06 10:59:15.558  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.88, true, R]
08-06 10:59:15.648  27406-27827/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 5974K, 30% free 19611K/27960K, paused 30ms, total 30ms
08-06 10:59:22.735  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ videoFormat [8.06, 1, 0]
08-06 10:59:22.775  27406-27827/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 674K, 25% free 20984K/27960K, paused 38ms, total 39ms
08-06 10:59:23.486  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ videoSizeChanged [1280, 720, 1.0]
08-06 10:59:29.111  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ state [14.44, true, B]
08-06 10:59:29.702  27406-27406/com.google.android.exoplayer.demo D/EventLogger﹕ end [15.02]
```

**Comment by ojw28** [comment] 2015-08-07 19:24
Both samples play fine on my Nexus 5. Is your Nexus 7 the first generation one, or the second? I'll try and reproduce on one of the devices you say is affected next week.

The log line below looks suspect, but I'm not sure whether it's the root cause or not:

08-06 10:51:47.591  15231-22557/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648

**Comment by davidleu** [comment] 2015-08-07 20:05
It's the 2013 Nexus 7.  Also just tried it on a Nexus 10 and a Nexus 6.  Both of those don't seem to be working either for the same videos.

As for the "storeMetaDataInBuffers failed w/ err -2147483648", I saw it in the working video too and wasn't sure what to make of that failure.

I will try another off-site location to try to remove network connection as a factor but many of the other videos do work and it's the same certain subset of videos that consistently freeze.

**Comment by b95505017** [comment] 2015-08-17 15:24
Same issue here.
I try to play 1080p HLS from Twitch using ExoPlayer on Nexus 7 but freeze, only audio still alive.

Mark these line then video start rendering:
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.java#L433
````java
    if (earlyUs < -30000) {
      // We're more than 30ms late rendering the frame.
      dropOutputBuffer(codec, bufferIndex);
      return true;
    }
````

I think that it is related to video decode rate is far slower that audio, also I saw lots of ````INFO_TRY_AGAIN_LATER```` when call to ````dequeueOutputBuffer````. The fact is that the ````earlyUs```` is decreasing so fast that all buffer is dropped.

How do we solve these problem? Or maybe we need a better A/V sync algorithm?

Thanks.

**Comment by ojw28** [comment] 2015-08-19 08:26
The most recent update from @b95505017 sounds like attempting to play a 60fps video on a device that's not capable of supporting 60fps. I don't think it's the same as the original issue.

**Comment by b95505017** [comment] 2015-08-19 14:50
@ojw28 Nope, I tried 1080p 30fps HLS and got the same issue. :(

**Comment by richk** [comment] 2015-12-16 23:11
Any update on this?
Getting reports of similar issue from users using our app with Exoplayer integrated. Was working fine before.

**Comment by hookr** [comment] 2016-04-15 03:22
I also have  this issue. only can play http-flv,but can not play hls. It occur only on my tv-box base on android 4.4.My english not good!

**Comment by bluemix** [comment] 2016-07-25 13:15
the same here, on an Android set-top box (STB),
certain videos freeze on the same time

**Comment by ojw28** [comment] 2016-08-23 20:03
@b95505017 - We handle variable frame-rates, provided the peak/average rates aren't too high for the device. There is no way to downgrade the frame-rate. There isn't really a good way to "downgrade" the frame-rate. Specifically, it's not possible to decode every other frame (or similar) because decoding one frame typically requires decoding the previous one, because video is encoded to make use of the fact that adjacent frames are similar to one another.

There are keyframes (typically every 2 to 10 seconds) that can be decoded independently, and we could display those and skip the rest. We may consider this for 2.x, but it wont give a good quality experience. You should really deliver content to the device that it's able to play.

We have merged assorted fixes since the original issue was filed. There's not much actionable here, so I'm going to close the issue. Please file a fresh issue is this is still a problem on 1.5.10 or later, including _all_ of the information requested in the issue template. Thanks!

**Closed by ojw28** 2016-08-23 20:03 UTC

**Comment by b95505017** [comment] 2016-08-23 20:26
@ojw28 I've notice that on Nexus 7, YouTube will try to skip 1080p60. Wondering how to achieve this.

**Comment by ojw28** [comment] 2016-08-23 20:30
I believe they skip to keyframes as per my comment above, using a custom modification that they've made to ExoPlayer. Note that mileage of such an approach is quite dependent on how frequent keyframes are in the source media, which is outside of the control of the player. If you own both the serving and consuming sides, as in the YouTube case, then it's a little different. Note also that it's really much better just to play 30fps content if the device can't hack 60fps. What's the point in downloading twice as many frames just so you can throw most of them away?

We're considering adding skipping-to-keyframe support into 2.x, as per my comment above, to deliver a better experience where the source content is high frame-rate and alternatives don't exist.
