### ISSUE TITLE
Support playlists of offline DRM protected content 

### ISSUE THREAD

**Issue by vinayjoglekar** [google/ExoPlayer#5211] opened 2018-12-07 06:22 UTC
**Issue description**
Does exoplayer have support to play offline DRM content using ConcatenatingMediaSource? Currently I am able to play single media offline which is DRM protected using : 
`drmSessionManager?.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, license.keySetIdBytes)`

**Version of ExoPlayer being used**
2.9.1

**Comment by ojw28** [comment] 2018-12-09 19:11
I don't think we have a great solution for this currently. As you note, you can only restore one `keySetId` into the `DrmSessionManager`.

**Comment by vinay-altbalaji** [comment] 2018-12-12 12:52
Thanks, @ojw28 . Is it going be to a part of any of the upcoming releases?

**Comment by avecost** [comment] 2019-07-31 07:40
Hello @vinayjoglekar can you share on how you implemented the Offline Playback that is protected content.

TIA

**Comment by vinayjoglekar** [comment] 2019-07-31 10:23
@avecost you need to cache license key(s) of the content at when you download the actual content. At the time of playback of this offline content instead of using MediaDrmCallback, use that license like this
`drmSessionManager?.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, license.keySetIdBytes)`

**Comment by ojw28** [comment] 2019-08-02 15:46
Marking as a duplicate of #2394, since what's being done for that issue will also solve this one.

**Closed as completed by ojw28** 2019-08-02 15:46 UTC
Labels: duplicate
