### ISSUE TITLE
Opus File no longer plays

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/ExoPlayer#7046] opened 2020-03-05 05:49 UTC
With 2.11.3 opus files that played before don't play any longer.

The issue was originally reported here:
https://github.com/PaulWoitaschek/Voice/issues/948

The issue contains an example file.
When trying to play it, the following error happens:

```
2020-03-05 06:44:39.395 13664-13728/? E/opus_jni: Failed to set Opus header gain; status=invalid argument
2020-03-05 06:44:39.395 13664-13728/? E/ExoPlayerImplInternal: Renderer error: index=0, type=audio, format=Format(null, null, null, audio/opus, null, -1, null, [-1, -1, -1.0], [2, 48000]), rendererSupport=YES
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.ext.opus.OpusDecoderException: Failed to initialize decoder
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.maybeInitDecoder(SimpleDecoderAudioRenderer.java:655)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.onInputFormatChanged(SimpleDecoderAudioRenderer.java:701)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:280)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.ext.opus.OpusDecoderException: Failed to initialize decoder
        at com.google.android.exoplayer2.ext.opus.OpusDecoder.<init>(OpusDecoder.java:134)
        at com.google.android.exoplayer2.ext.opus.LibopusAudioRenderer.createDecoder(LibopusAudioRenderer.java:111)
        at com.google.android.exoplayer2.ext.opus.LibopusAudioRenderer.createDecoder(LibopusAudioRenderer.java:31)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.maybeInitDecoder(SimpleDecoderAudioRenderer.java:648)
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.onInputFormatChanged(SimpleDecoderAudioRenderer.java:701) 
        at com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.render(SimpleDecoderAudioRenderer.java:280) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by krocard** [comment] 2020-03-11 14:57
I can not reproduce the failure on :
```
git checkout r2.11.3
./gradlew demo:installNoExtensionsDebug
adb push ok.opus not_ok.opus /sdcard/
adb shell am start -a com.google.android.exoplayer.demo.action.VIEW     -d file:/sdcard/ok.opus
adb shell am start -a com.google.android.exoplayer.demo.action.VIEW     -d file:/sdcard/not_ok.opus
```

Both playback played without error on both my device (Pixel 3 and Nvidia shield).

**Comment by krocard** [comment] 2020-03-11 15:01
Actually, from the log, the Opus extension seems to be used: https://github.com/google/ExoPlayer/blob/r2.11.3/extensions/opus/src/main/jni/opus_jni.cc#L82

**Comment by PaulWoitaschek** [comment] 2020-03-11 15:08
That's opus 1.3.1.
This is the repo for opus:

```
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    implementation "com.github.PaulWoitaschek.ExoPlayer-Extensions:extension-opus:2.11.3" {
        transitive = false
    }
}
```

The library is set to `EXTENSION_RENDERER_MODE_PREFER`.

https://github.com/PaulWoitaschek/Voice/blob/97f06a38834fc55fec39379b4a5545851527d632/app/src/main/java/de/ph1b/audiobook/playback/OnlyAudioRenderersFactory.kt#L23

**Comment by krocard** [comment] 2020-03-11 15:39
Thanks for your opus version, I'll try again with the extension this time.

**Comment by ojw28** [comment] 2020-03-27 16:02
It looks like we parse gain as an unsigned value, when it should be interpreted as a signed value. It's not a regression though; the problem has been there ever since the `OpusDecoder` was first written in 2016.

**Comment by ojw28** [comment] 2020-03-27 23:37
Fixed in `dev-v2`.

**Closed as completed by ojw28** 2020-03-27 23:37 UTC
Labels: bug
