### ISSUE TITLE
HLS stream doesn't work with exoplayer demo app

### ISSUE THREAD

**Issue by darkokostic** [google/ExoPlayer#3709] opened 2018-01-15 19:32 UTC
Hi there,

I have a lot of links for streams that I have to play in my app, some of them are working just fine. 

Anyway, some of that HLS streams doesn't play audio, and some of that HLS streams doesn't play at all (either audio and video).

I tested on ExoPlayer demo app both.
  - The link that works in my app, works in demo app too.
  - The link that doesn't play in my app, and always trying to send http request over and over, doesn't work in demo app too. **It throws com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to {{link}}**

Also to be sure that this link works, I tested it with another players from Google Play Store and the stream is playing just fine. (Perfect Player app).

Version of ExoPlayer that I am using is 2.6.1.

Reproduction steps: You can set the url that I will send by email to HLS stream in demo app.

If anyone can help, I will be very thankful.

Best regards,
Darko

**Comment by AquilesCanta** [comment] 2018-01-16 10:54
I cannot reproduce: both links work well. I will close the issue under the suspicion that something server-side has been fixed. If you still encounter the issue, please provide reply to this issue including the missing [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) items.

**Closed as completed by AquilesCanta** 2018-01-16 10:54 UTC
Labels: need more info

**Comment by darkokostic** [comment] 2018-01-16 15:41
Hi there, 
On my device, it seems to be the same issue still. So I am writing a report again.

### Issue description
The main issue on my device is that some of the links doesn't play (some of them play only audio, and some of them are sending http request in loop over and over). I am testing on ExoPlayer demo app.

### Reproduction steps
To reproduce this issue, put the links that I will send in email in "HLS" JSON samples in ExoPlayer Demo App.

### Link to test content
I sent an email with links

### Version of ExoPlayer being used
I am using ExoPlayer version 2.6.1 or ExoPlayer v2 demo app downloaded from this git repository.

### Device(s) and version(s) of Android being used
My Android device is Sony Xperia M5 and Android version is 6.0.

### A full bug report captured from the device
I sent my bug reports from my app, and exoplayer demo app.

I was first thinking that it is my app issue, but it works same on ExoPlayer Demo app.

**Comment by darkokostic** [comment] 2018-01-18 15:31
Can anyone help? Still the stream doesn't work with demo app.

**Comment by AquilesCanta** [comment] 2018-01-19 16:25
#1967 explains the cause. You need to inject FLAG_ALLOW_NON_IDR_KEYFRAMES by implementing your own `HlsExtractorFactory`. You can use `DefaultHlsExtractorFactory` as starting point.

**Comment by darkokostic** [comment] 2018-01-19 23:20
I did it, and it resolved my problem on Android 6.0, now all my streams work.

But still on Android 7.0, some of the streams doesn't have audio, it shows Unsupported on demo app, but on Android 6.0 device it works. 

Also this flag that resolved me the issue for streams on Android 6.0, on Android 7.0 same streams doesn't play still.

**Comment by darkokostic** [comment] 2018-01-20 00:00
Also I added ffmpeg extension, and still I am getting same results.

**Comment by darkokostic** [comment] 2018-01-20 12:25
I think that I am not using properly ffmpeg extension, I added it as a module like you described here: https://github.com/google/ExoPlayer/blob/release-v2/README.md and I can use ffmpeg classes, but I didn't configure any of this build instructions: https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg. Do I have to do this build instructions? I don't know how to do it, because it is not documented well here.

Maybe this will resolve my issue about audio, because I figure out that audio is .mp2 that doesn't work on Android Nougat. Also about video that doesn't play, the issue is maybe frame rate, but I don't know what to do about that.

If anyone can help?
Best regards.

**Comment by darkokostic** [comment] 2018-01-20 20:01
Hello there,

I implemented ffmpeg extension, everything works perfect on Android 6.0, but still some streams doesn't play either video and audio on Android 7.0.

It is the same on Android 5.0.

I am sure that I implemented ffmpeg extension properly because I am getting in log that it loading FFmpeg extension class on every stream that device doesn't support.

After message that app loaded ffmpeg extension I am getting this:

W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/VideoCapabilities: Unsupported mime video/divx
W/VideoCapabilities: Unsupported mime video/xvid
W/VideoCapabilities: Unsupported mime video/flv1
W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es

Any help?
Best regards.

**Comment by ojw28** [comment] 2018-01-21 19:00
> But still on Android 7.0, some of the streams doesn't have audio, it shows Unsupported on demo app, but on Android 6.0 device it works.

This is working as intended, and means that the device does not support the audio format you're trying to play. Please see the Sample Formats section of our [Supported Formats](https://google.github.io/ExoPlayer/supported-formats.html) page, and the [Android supported format](https://developer.android.com/guide/topics/media/media-formats.html#core) page that it links to.

> I implemented ffmpeg extension, everything works perfect on Android 6.0, but still some streams doesn't play either video and audio on Android 7.0.

There is not sufficient information provided for us to further debug this issue. For example, we have not received sufficient information for us to even know what type of audio format the streams that are still problematic contain. Are you sure you compiled FFmpeg in a way that supports the required format(s)?
