### ISSUE TITLE
Geting Multiple instances of ClippingMediaSource to work

### ISSUE THREAD

**Issue by skreenr** [google/ExoPlayer#8023] opened 2020-10-01 00:43 UTC
### [REQUIRED] Searched documentation and issues
https://exoplayer.dev, StackOverflow, Google

### [REQUIRED] Question
My app, a background service, needs to be able to play a number of short video clips w/o delay when event listeners fire. 
Instead if playing back from individual files, I decided to concatenate clips in one mmother-clip and set individual ClippingMediaSource's to use in the app with idea it will cut on media prebuffering time. 

In my code I switch my player' MediaSource between those ClippingMediaSource to accomplish instant playback. 
Instead, I found only first segment plays, then it gets stuck.  Am wondering if the player needs to be released , then re-prepared which likely will add a delay

					Simple_player = new SimpleExoPlayer.Builder(getBaseContext()).build();
					Simple_player.setVolume(0.0f);
					Uri uri = RawResourceDataSource.buildRawResourceUri(R.raw.motherClip);

					DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getBaseContext(), "com.domain.app");
					videoSource = new ExtractorMediaSource.Factory( dataSourceFactory ).createMediaSource(uri);
 					Src_Clip1  = new ClippingMediaSource( videoSource, 0,  200000);
					Src_Clip2  = new ClippingMediaSource( videoSource, 200000, 2670000);
					Src_Clip3  = new ClippingMediaSource( videoSource, 2670000,  2870000);
					Src_Clip4  = new ClippingMediaSource( videoSource, 5570000,  5770000);

	 				Simple_player.setRepeatMode(Player.REPEAT_MODE_OFF);
					Simple_player.setVideoSurfaceHolder(holder);

					 Simple_player.prepare( Src_Clip1  );
	 				 Simple_player.setPlayWhenReady(true);

						......................

 	 				Simple_player.prepareSrc_Clip2  )
	 				Simple_player.setPlayWhenReady(true); 
						......................

	 				Simple_player.prepareSrc_Clip3  );
	 				Simple_player.setPlayWhenReady(true); 
						......................
	 				Simple_player.prepareSrc_Clip4  );
	 				Simple_player.setPlayWhenReady(true); 

	 				 

### A full bug report captured from the device
I observe only first video segment actually plays, then it gets stuck on last frame

### Link to test content
In case your question is related to a piece of media, which you are trying to
play, please provide a JSON snippet for the demo app’s media.exolist.json file,
or a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where
"#1234" should be replaced with your issue number. Provide all the metadata we'd
need to play the content like drm license urls or similar. If the content is
accessible only in certain countries or regions, please say so.

**Comment by marcbaechinger** [comment] 2020-10-02 14:19
I think I do not understand what you are trying to achieve with clipping, when there are no gaps or other sources in between the clips. It's basically the same as a single source with no clipping.

> with idea it will cut on media prebuffering time

If you call `prepare()` each time in between, it always will discard all the data that is already buffered and start over. I think that's not what you want to achieve.

To make sure there is no misunderstanding: ExoPlayer does not prebuffer the start of each item in the timeline. ExoPlayer does buffer a certain duration in time starting from the current position. So if the buffer is configured to be 50 seconds and you are at position 180_000, then 30 seconds of the second clips is buffered. But if you are at position 100_000 in the first clip, the next clip is not in the buffer yet. 

If I understand correctly you can just 

```
player.setMediaSources(videoSource);
player.prepare();

// later

player.seekTo(200_000);
player.seekTo(2_670_000);
player.seekTo(5_570_000);

```

If you still want the clipping approach I would do that like below:

```
List<MediaSource> sources = new ArrayList();
sources.add(new ClippingMediaSource( videoSource, 0,  200000));
sources.add(new ClippingMediaSource( videoSource, 200000, 2670000));
sources.add(new ClippingMediaSource( videoSource, 2670000,  2870000));
sources.add(new ClippingMediaSource( videoSource, 5570000,  5770000));

player.setMediaSources(sources);
player.prepare();

// later

player.seekTo(1, C.TIME_UNSET);
player.seekTo(2, C.TIME_UNSET);
player.seekTo(3, C.TIME_UNSET);
```

> I found only first segment plays, then it gets stuck.
> Uri uri = RawResourceDataSource.buildRawResourceUri(R.raw.motherClip);

I wonder whether you tried that with a uri as well and if this gives you the same results. I'm asking because I have not much experience with this I'm afraid. If we can rule out it's because of the raw source that would be fine. Is this what you are going to to do in production as well or is this just for testing?

However, I would recommend doing the approach in the first code snippet in this comment. If you try that it probably removes the problem of getting stuck.

Aside: `ProgressiveMediaSource` is a drop-in replacement of the `ExtractorMediaSource` which is deprecated. It may remove some warnings if you use `ProgressiveMediaSource`. If you don't see `ExtractorMediaSoruce` being deprecated, I'd recommend upgrading to the latest ExoPlayer version 2.12.

**Comment by skreenr** [comment] 2020-10-03 23:02
Looking at your code snippet, a question:  _How do you stop Exoplayer at a specific time? _and_ then re-start_
My idea was to play short clips of predetermined positions out of a "mother" clip, which is  <10M file size
The thinking was it may provide a more responsive = instantaneous UX as compared to just opening/preparing individual clips.
Perhaps I am wrong, would love to hear about better way to get it


That said, a **_new concern with Exoplayer_** is –  I observe the video **_FPS  appear to be lower  with my videos compared to what I was getting with MediaPlayer_**, which delivered smooth playback at 30fps. Exoplayer playback looks less smooth, maybe a little jerky
 My videos are 720x1520 resolution at 30 fps,  and I tested playback using this project https://github.com/AlynxZhou/alynx-live-wallpaper/blob/master/app/src/main/java/xyz/alynx/livewallpaper/GLWallpaperService.java 
replacing the original video with my own, specs per above

Please advise if in fact Exoplayer has this problem and can't match MediaPlayer in quality

Now you may ask me Why not stik with MediaPlayer then? 
Two things:  Hardware compatibility and Cropping video feature;
- there are number of phones, mostly seem to come  out of China, which fail executing standard MediaPlayer code
- Exoplayer ability to do a Cropping scale mode is really a gem of a feature

**Comment by marcbaechinger** [comment] 2020-10-04 13:44
Can you please open another issue with the fps problem and test this with the demo app of ExoPlayer instead with another app? You can start your sample uri by [adding it to the json in source code](https://exoplayer.dev/demo-application.html#1-editing-assetsmediaexolistjson) or [by firing an intent](https://exoplayer.dev/demo-application.html#3-firing-an-intent). After you've run the video in the demo app with the fps problem, please [take a bug report](https://developer.android.com/studio/debug/bug-report) and upload it in the new issue. If you still see the fps problem please also include a uri to the content.

The app above does something with GL which may be the problem of the frame rate? I'm totally not sure, that's why it's best to use the demo app so we know. 

If you do not want to share in public, you can send bugreport and content uri to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your new issue number

> How do you stop Exoplayer at a specific time? 

If you just add a single stream (first suggestion above), you can [execute an event at a given playback position](https://exoplayer.dev/listening-to-player-events.html#playback-position) and then pause the player in the code executed by the message.

If you are using clipped pieces to have multiple media items in the playlist you can set `SimpleExoPlayer.setPauseAtEndOfMediaItems(/* pauseAtEndOfMediaItems= */ true)`. 

> and then re-start?

What is the condition at which to restart?

**Comment by fumundecheeze** [comment] 2020-10-04 13:53
Thank you can you tell me how to set up SAS open source the easiest way..

**Comment by marcbaechinger** [comment] 2020-10-04 14:27
@fumundecheeze This is the ExoPlayer issue tracker. If you think this is the right issue tracker for your question, please open a new issue and ask your question. Else someone from SAS can probably help you in the most efficient way.

**Comment by skreenr** [comment] 2020-10-05 03:03
@marcbaechinger  - **Which of the Demo apps** you want me to try? There are a bunch of them in the Zip of Exoplayer project.  
I opened each and looked inside, none had an actual Video file in them. Perhaps they are for streaming use cases, which won't be my case.

What I did was just grabbed this Alynx walpaper project, which builds fine and uses video file, replaced their video with mine of 30fps 720x1520 pixel resolution spec, and can see it's not silky smooth like MediaPlayer does when it works, not exactly jagged but I would say flickering. My immediate thought was, it's about hardware codec performance vs software codec in Exo, an uneducated guess.


**Your comment on GL used in Alynx project**: they use GL renderer because it is required to get the video CROPPING_MODE for scaling, right?  I tried assigning the mode directly to Exoplayer e w/o using GL in my code and A-Studio won't let me do that, requires a renderer

EDIT: I seem didn't get it right: I was trying to insert  _Simple_player.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)_
which showed Error with a prompt about Render, but after I replaced C with Renderer it accepted it like that:
_Simple_player.setVideoScalingMode(Renderer.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);_


The Demo in Main folder quite possibly not using the CROPPING_MODE though, so it won't be a relevant comparison, e.g. Apples to Oranges case. 
To restate, **ability to crop Videos is of importance to my project**

Also. the Demo probably is not running video full-screen, so , again, Apples to Oranges

Two questions on your Code tips:

-  _Execute Event at a playback position_
I looked at your examples https://github.com/google/ExoPlayer/issues/6550   and https://github.com/google/ExoPlayer/issues/5515 and don't quite get What I need to put in the Payload and How/Where the processing part of it goes: Like another Override or what? that does the Pausing 

- _What is the condition at which to restart?_
The restarting is to be fired by listeners in my service (my app is a service = LWP)
Do I need to call Prepare() or just playWhenReady(true) then?

**Comment by marcbaechinger** [comment] 2020-10-05 11:58
Yes, we should compare the same thing. What I'm saying (guessing to be fair) is that the jitter may be caused by GL tranformations or the code of the app which we probably can not review very closely. ExoPlayer uses the same hw decoder like media player in case an app does not force software encoding with ExoPlayer explicitly. Please open another issue for the GL question so we can keep things separated for us and later readers. Hope that's ok for you. Sorry for any inconvenience. 

I would first try with the main demo app to rule out your suggestion that ExoPlayer jitters in general. If you trust in this there is also a GL app. I don't dare to give you instruction for the GL thing as my experience there is around very low. :) 

*Execute Event at a playback position*

I think you just don't need a payload in your case. When executing a message at a playback position you can pass any app specific `payload` object which then will passed to your message when executed at a given position. ExoPlayer does nothing else with that then passing it to the lambda function.

```
player.createMessage(
    (messageType, payload) -> player.pause())
  .setPosition(200_000)
  .setHandler(new Handler())
  .send();
```

In the sample snippet above you pause the player in the lambda function which has a reference to the player and calls `pause()`. You set the position to the positions at which you want the lambda to be executed. The sample uses the start of the second clip of your example above. You also need to set a `Handler` to make sure that the lambda is executed in the thread that created the handler. The sample above assumes you are doing this in the main thread. Your call to `player.pause()` needs to be called in the same thread on which you created the player which is most likely the main thread.

*What is the condition at which to restart?*

Yes, you are correct. When your listener is called, you can just call `player.setPlayWhenReady(true)` or `player.play()` which is exactly the same. The player then resumes from where it is currently paused.

**Comment by skreenr** [comment] 2020-10-06 00:49
Getting this **ERROR: _plugin with id 'com.android.application' not found_** when I try building the Main Demo**
Any advise?

**Comment by marcbaechinger** [comment] 2020-10-06 12:00
I just tried and that works fine for me. I cloned the project from GitHub with 

```
git clone https://github.com/google/ExoPlayer.git
```

Then I imported the project with Android Studio and run the demo app which deployed in the emulator.

How do you build and do you have some more log output?

**Comment by marcbaechinger** [comment] 2020-10-06 12:05
When I google the error message above it brings me to a [StackOverFlow article](https://stackoverflow.com/questions/24795079/error1-0-plugin-with-id-com-android-application-not-found).

You probably need to update the gradle version.

What do you get when you run the following from the root of the ExoPlayer project?

```
./gradlew -v
```

**Comment by skreenr** [comment] 2020-10-06 23:40
I dwnload'ed Zip of the project instead of cloning.  Usually this works fine

The advise is good in that SoF article, and I copied Build.gradle file from another project that builds and placed into Main package. Now it syncs however not a APK but as a module, because I guess the file structure is wrong (missing app folder for one)
Here is snapshot 

Let me know if it's an easy fix

**Comment by marcbaechinger** [comment] 2020-10-07 09:30
There shouldn't be a need to copy another gradle file into the project. I downloaded the project ZIP file from [https://github.com/google/ExoPlayer/archive/release-v2.zip](https://github.com/google/ExoPlayer/archive/release-v2.zip). Then start Android Studio and import the project with `New - Import project` and select the root folder of the ZIP file that has been extracted to for instance `/home/username/Downloads/ExoPlayer-release-v2`. With this the project opens and I can deploy the demo app to a device or emulator.

From the screenshot it seem that the module has been opened by selecting the `ExoPlayer-release-v2/demos/main` folder instead of the root of the project. Can you try to import the project from the root of the ZIP file instead of directly pointing to the demo app? The project will then have all the demo apps as app modules which can be deployed side by side.

**Comment by skreenr** [comment] 2020-10-08 03:36
I have done that and it appears it's looking for Gradlever 4.0.0 while mine is 3.6.3
How do I change the version? couldn't find a way to change it myself
Have to add that Google demos tend to be tricky to build; I have never actually managed to build any and when I need to learn something I typically would find some tutorial and code on Github that "just builds" rather than givingsome extra work

With that, Why not we find a wallpaper coded you feel comfortable using as a test bed?
remember we need a full screen playback, and wallpaper is a right kind of app for that

**Comment by krocard** [comment] 2020-10-08 07:24
> I have done that and it appears it's looking for Gradlever 4.0.0 while mine is 3.6.3

You probably need to update Android Studio.

If you can't build the demo with Android Studio, you can try directly with gradle:
Assuming you have the android SDK installed at `~/Android/Sdk` and you are using a linux/mac terminal.
```
git clone https://github.com/google/ExoPlayer.git --branch 2.12.0 && cd ExoPlayer // Or cd where you uncompressed the ExoPlayer zip archive
ANDROID_SDK_ROOT=~/Android/Sdk ./gradlew demo:installNoDecoderExtensionsDebug
adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d URI_OF_YOUR_MEDIA
```

**Comment by skreenr** [comment] 2020-10-10 03:54
There should be way to change Gradle level in project config, just How?
Using Demos to make people upgrade is not proper way, leave it to marketing, Thanks

**Comment by marcbaechinger** [comment] 2020-10-10 17:24
I'm closing this now. You can ask why if you don't know already.

**Closed as completed** 2020-10-10 17:23 UTC
Labels: question

**Comment by skreenr** [comment] 2020-10-16 06:34
OK I build a very basic LWP, two of them: one using MediaPlayer and another Exoplayer, to play a video clip of ~7sec in a loop.  Looking at the result it seems to me like Exoplayer's playback is just a bit slower, maybe few FPS. Another observation is that when activating the LWP in Settings, in Preview the video plays with delay a little more pronounced than with MediaPlayer, just fraction of a sec. Not a show stopper, but something I see.
Can send over projects' code and media
