### ISSUE TITLE
java.io.EOFException when playing DRM protected content

### ISSUE THREAD

**Issue by almoghzn** [google/ExoPlayer#1370] opened 2016-03-14 16:49 UTC
- We're trying to play DRM protected content using Exo Player.
- Our license provider is EZDRM.
- In general we seems to play protected content successfully.
- Playing protected content is non-issue, we are able to get the license key from the license provider (ezdrm) and start to play the content.
- Other contents are also play without any problem at all.
- Specific content can not be played from start to end.
- It's starts successfully and plays until specific pts (min' 1:31:25) and then Exo Player fails and gives the following error:

```
03-14 18:31:04.398    2735-2755/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [684.97, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:73)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:85)
            at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:386)
            at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:245)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:114)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:131)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:644)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:164)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:243)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
03-14 18:31:04.399    2735-2760/com.google.android.exoplayer.demo D/DataSource﹕ data source : http://10.0.0.11:8080/video/night-30mbps-EZDRM/video/1/seg-550.m4f
03-14 18:31:04.404    2735-2755/com.google.android.exoplayer.demo D/EventLogger﹕ bandwidth [684.98, 15617, 0.00, 72424600]
03-14 18:31:04.405    2735-2755/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [684.98, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:73)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:85)
            at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:386)
            at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:245)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:114)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:131)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:644)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:164)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:243)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
03-14 18:31:04.740    2735-2750/com.google.android.exoplayer.demo D/ExoRemoteControlServer﹕ handleRpcCall [getPerformanceCounters]: null
03-14 18:31:05.404    2735-2760/com.google.android.exoplayer.demo D/DataSource﹕ data source : http://10.0.0.11:8080/video/night-30mbps-EZDRM/video/1/seg-550.m4f
03-14 18:31:05.411    2735-2755/com.google.android.exoplayer.demo D/EventLogger﹕ bandwidth [685.98, 15617, 0.00, 72424600]
03-14 18:31:05.412    2735-2755/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [685.98, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:73)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:85)
            at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:386)
            at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:245)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:114)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:131)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:644)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:164)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:243)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
03-14 18:31:05.991    2735-2750/com.google.android.exoplayer.demo D/ExoRemoteControlServer﹕ handleRpcCall [getPerformanceCounters]: null
03-14 18:31:07.242    2735-2750/com.google.android.exoplayer.demo D/ExoRemoteControlServer﹕ handleRpcCall [getPerformanceCounters]: null
03-14 18:31:07.411    2735-2760/com.google.android.exoplayer.demo D/DataSource﹕ data source : http://10.0.0.11:8080/video/night-30mbps-EZDRM/video/1/seg-550.m4f
03-14 18:31:07.420    2735-2755/com.google.android.exoplayer.demo D/EventLogger﹕ bandwidth [687.99, 15617, 0.00, 72424600]
03-14 18:31:07.420    2735-2755/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [687.99, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:73)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:85)
            at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:386)
            at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:245)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:114)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:131)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:644)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:164)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:243)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
03-14 18:31:08.493    2735-2750/com.google.android.exoplayer.demo D/ExoRemoteControlServer﹕ handleRpcCall [getPerformanceCounters]: null
03-14 18:31:09.077    2735-2742/com.google.android.exoplayer.demo W/art﹕ Suspending all threads took: 61.557ms
03-14 18:31:09.746    2735-2750/com.google.android.exoplayer.demo D/ExoRemoteControlServer﹕ handleRpcCall [getPerformanceCounters]: null
03-14 18:31:10.026    2735-2742/com.google.android.exoplayer.demo W/art﹕ Suspending all threads took: 7.689ms
03-14 18:31:10.419    2735-2760/com.google.android.exoplayer.demo D/DataSource﹕ data source : http://10.0.0.11:8080/video/night-30mbps-EZDRM/video/1/seg-550.m4f
03-14 18:31:10.426    2735-2755/com.google.android.exoplayer.demo D/EventLogger﹕ bandwidth [691.00, 15617, 0.00, 72424600]
03-14 18:31:10.426    2735-2755/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [691.00, loadError]
    java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:73)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:85)
            at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:386)
            at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:245)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:114)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:131)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:644)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:164)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:243)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
03-14 18:31:10.998    2735-2750/com.google.android.exoplayer.demo D/ExoRemoteControlServer﹕ handleRpcCall [getPerformanceCounters]: null
03-14 18:31:12.248    2735-2750/com.google.android.exoplayer.demo D/ExoRemoteControlServer﹕ handleRpcCall [getPerformanceCounters]: null
03-14 18:31:12.373    2735-2756/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:606)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:427)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:204)
            at android.os.Handler.dispatchMessage(Handler.java:100)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:51)
     Caused by: java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:73)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:85)
            at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:386)
            at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:245)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:114)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:131)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:644)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:164)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:243)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
03-14 18:31:12.374    2735-2755/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [692.95]
    com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:606)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:427)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:204)
            at android.os.Handler.dispatchMessage(Handler.java:100)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:51)
     Caused by: java.io.EOFException
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:73)
            at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:85)
            at com.google.android.exoplayer.extractor.RollingSampleBuffer.appendData(RollingSampleBuffer.java:386)
            at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:245)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.sampleData(ContainerMediaChunk.java:114)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.sampleData(ChunkExtractorWrapper.java:131)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:644)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:164)
            at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
            at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:243)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
```

- It's easy to reproduce - all we need to do is just to play this specific media and by minutes 1:31:25 it will stop.
- The content is about ~20GB, I can send the specific segment if it can help (you can see in the log as well that this is segment #550
- We are using custom version of Exo Player that based on previous version
- This has been tested on two devices:
1. NVIDIA SHIELD - Android v.6.0
2. Vestel S7252 - Android v.5.1.1
- Bugreport is attached, logcat as well.
[bugreport.txt](https://github.com/google/ExoPlayer/files/172417/bugreport.txt)
[EOFException-seg550.txt](https://github.com/google/ExoPlayer/files/172420/EOFException-seg550.txt)

**Comment by ojw28** [comment] 2016-03-16 00:29
It sounds very much like the media is broken to me. You'll need to provide us with an easy way to reproduce the issue if you want us to take a look.

**Comment by ojw28** [comment] 2016-04-04 10:50
Closing due to insufficient information.

**Closed** 2016-04-04 10:50 UTC
Labels: question

**Comment by AlaeddineOuerteni** [comment] 2016-07-12 08:26
Hello @ojw28,
I'm getting the same error when I try to play a DRM content not yet full downloaded but it's ready to be played (Some chunks have already been downloaded).
