### ISSUE TITLE
show only a part of video in simpleExoPlayerView

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#3458] opened 2017-11-14 12:41 UTC
show only a part of video in simpleExoPlayerView

not show whole video 
video width is 960  and height is 540

I want to show that part staring from left -350 to right 500
and from tom 200-bottom 450

my xml code is 

```
<com.google.android.exoplayer2.ui.SimpleExoPlayerView
        android:id="@+id/player_view"
        android:focusable="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:use_controller="false"
        app:resize_mode="fit"
        app:surface_type="texture_view"
        android:rotation="90"
        android:layout_above="@+id/PlaybackControlViewa"
        android:layout_marginTop="10dp" />



```

how can this be done

**Comment by ojw28** [comment] 2017-11-14 12:47
Duplicate of #3432.

**Closed as completed by ojw28** 2017-11-14 12:47 UTC
Labels: duplicate, question

**Comment by pawaom** [comment] 2017-11-14 12:48
yes it may be duplicate , but this question is in regards to simpleexoplayer, how can we set 

how can  
      Matrix matrix = new Matrix();
        matrix.setScale(172, 400, 343, 637);
        simpleexoplayer.setTransform(matrix); be done

simpleexoplayer.settransfrom()  doesnot work

**Comment by ojw28** [comment] 2017-11-14 12:52
Please don't file new issues for the same question. Just append your additional comment onto the existing one. Thanks.
