### ISSUE TITLE
Possible DeadLock when releasing SimpleExoPlayer

### ISSUE THREAD

**Issue by perracodex** [google/ExoPlayer#5575] opened 2019-02-27 14:42 UTC
### Issue description
In version 2.9.6 I started to experience randomly what seems to be a DeadLock when releasing the player. 
The way I release the player is very straightforward,  just a call to the SimpleExoPlayer’s release method in the activity onStop().
When the application freezes, by pausing all threads I can see that the main thread is waiting in the wait() call within ExoPlayerImplInternal.release()

```
ExoPlayerImplInternal
{
	public synchronized void release() {
	  if (released) {
		return;
	  }
	  handler.sendEmptyMessage(MSG_RELEASE);
	  boolean wasInterrupted = false;
	  while (!released) {
		try {
		  wait(); // <- line at which the main thread is locked
		} catch (InterruptedException e) {
		  wasInterrupted = true;
		}
	  }
	  if (wasInterrupted) {
		// Restore the interrupted status.
		Thread.currentThread().interrupt();
	  }
	}
}
```

### Reproduction steps
Is hard to reproduce, it happens randomly. The only requirement is that the video has played at least a few seconds.

### Version of ExoPlayer being used
2.9.6 

### Device(s) and version(s) of Android being used
Nexus 6, Android OS 7.1.1

**Comment by perracodex** [comment] 2019-02-27 15:35
**Update:**
After further testing it seems that the issue only happens with a specific type of recording.
Find attached a video sample. Don't expect any image, the video is black and without sound. Is just for testing purposes. Is a video recorded using the android MediaRecorder with a time-lapse Camcorder profile, setting the recording rate at 30fps and capture rate at 90fps:

[test video.zip](https://github.com/google/ExoPlayer/files/2910953/test.video.zip)

The only way to reproduce it is by placing the SimpleExoPlayer.release() call in an activity onStop, play the video, and while is playing press the back button to exit the activity. Repeat a few times until at one point the application freezes. It may happen the first time time or after a few plays, there is no pattern.

I can only reproduce it in a Nexus 6 - 7.1.1.
No problems at all in Nexus 5X - 8.1.0

I've also tested versions 2.9.5, 2.9.4 and 2.9.3 and the issue happens also in all of them. I guess probably will happen in most of the previous versions.

**Comment by AquilesCanta** [comment] 2019-02-28 14:16
Have you seen #4352? I'll close under the assumption that this is a duplicate of that issue.

If you don't think it's a duplicate of this issue then please provide an explanation and I'll reopen.

**Closed as completed by AquilesCanta** 2019-02-28 14:16 UTC
Labels: duplicate

**Comment by perracodex** [comment] 2019-02-28 14:24
It seems to be same issue. Though I would like to point out in case it helps, that with the sample recording I've attached in my the last comment I'm able to get the ANR very regularly, just after a few plays, though only in a Nexus 6 API 7.1.1.
I get no problems at all when using instead a regular video or the attached sample in a Nexus 5X 8.1.0.

Thanks
