### ISSUE TITLE
Exo Player in notification using playerNotificationManager not showing rewind & fast forward in locked screen

### ISSUE THREAD

**Issue by ravisaini1990** [google/ExoPlayer#7742] opened 2020-08-12 12:33 UTC
For locked screen, I need following -
1) Rewind  2) Play/pause 3) Fast-forward

and for expanded notification -
1) Rewind  2) Play/pause 3) Fast-forward 4) Progress seekbar

I am using following flags -
```
 playerNotifManager?.setUseNavigationActions(false)
        playerNotifManager?.setFastForwardIncrementMs(1)
        playerNotifManager?.setRewindIncrementMs(1)
        playerNotifManager?.setUsePlayPauseActions(true)
        playerNotifManager?.setPriority(NotificationCompat.PRIORITY_MAX)
        playerNotifManager?.setUseNavigationActionsInCompactView(true)


```

**Comment by marcbaechinger** [comment] 2020-08-12 13:31
I'm not sure why you are opening a different issue for the thing we just discussed quite closely in #7733 I appreciate that `PlayerNotificationManager` is not doing exactly what you want, and marked issue #7733 as enhancement accordingly. If you think you get another engineer to act differently I doubt it. 

Closing as duplicate of #7733

**Closed as completed by marcbaechinger** 2020-08-12 13:31 UTC
Labels: question
