### ISSUE TITLE
Calling transportControls.setPlaybackSpeed doesn't change the speed 

### ISSUE THREAD

**Issue by samardzija** [google/ExoPlayer#9509] opened 2021-09-29 14:59 UTC
I'm developing an android app for reproducing audio files. I'm trying to change the playback speed and I'm calling serviceConnection.transportControls.setPlaybackSpeed, but nothing happens, it doesn't change the speed. I've been using other methods like skipToPrevious(), skipToNext(), seekTo() etc and all of them just work fine. I tried to find answers in documentation, but I couldn't. Can you help me out with this?

- ExoPlayer version number: 2.15.1
- Android version: 30
- Android device: Samsung S20

**Comment by krocard** [comment] 2021-09-29 17:40
It's hard to help you without a way to reproduce or more debugging from your part and understanding the architecture (for example why are you not calling the player directly and going through serviceConnection).

One possibility is that the MediaSession has disabled the action `ACTION_SET_PLAYBACK_SPEED`. Also which version of mediaSession are you using?

Another possibility is that the media doesn't support speed adjustments. I can suggest calling ExoPlayer's `Player.setPlaybackSpeed` directly (for example in the code building it) to check if the media does support it.

**Comment by samardzija** [comment] 2021-09-30 08:40
@krocard For all exo player libraries, I'm using 2.15.1, that goes for com.google.android.exoplayer:extension-mediasession. 
I've added ACTION_SET_PLAYBACK_SPEED for getSupportedPrepareActions() in PlaybackPreparer. 

When I call directly in the service player.setPlaybackSpeed(speed), then it is working fine. Thanks for the suggestion. 
So, only when calling through  serviceConnection class, it doesn't work. Really strange. :-/

**Comment by krocard** [comment] 2021-09-30 10:01
In your UI code, make sure the action is supported, check that `(mediaController.getPlaybackState().getActions() & ACTION_SET_PLAYBACK_SPEED) != 0`.
Then confirm that `mediaController.getTransportControls().setPlaybackSpeed(int)` is actually called (with a positive speed) by your UI code.
Finally if your UI code is behaving as expected, trying put a breakpoint in `MediaSessionConnector.onSetPlaybackSpeed` to check that the action is received by ExoPlayer's extension:
https://github.com/google/ExoPlayer/blob/2a88f0fb295ff5b56e6fbcbe7e91bdf922cbae13/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L1310-L1315.

That should allow us to know if the issue comes from MediaSession/controller configuration, your ui code, or our extension.

**Comment by samardzija** [comment] 2021-09-30 10:39
That was really helpful, I found it! 
I've added `mediaSessionConnector.setEnabledPlaybackActions(ALL_PLAYBACK_ACTIONS)` 
and now it works. 

I sow in code that DEFAULT_PLAYBACK_ACTIONS are without PlaybackStateCompat.ACTION_SET_PLAYBACK_SPEED. 
Don't know why is that, but I assume you had a good reason for doing that.

**Comment by krocard** [comment] 2021-09-30 10:50
Thanks for reporting the solution. Will close as your issue is now fixed.

@marcbaechinger do you recall why ACTION_SET_PLAYBACK_SPEED is not part of the default when you implemented #8229?

https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L141-L144

**Comment by krocard** [comment] 2021-09-30 10:51
Closing because the issue has been fixed.

**Closed as completed by krocard** 2021-09-30 10:51 UTC
Labels: bug
