### ISSUE TITLE
Regrading an IMADAI sample asset fix

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#8984] opened 2021-05-25 10:01 UTC
Couple of months back, I reported an [issue](https://groups.google.com/g/ima-sdk/c/-Q2jekaVWdA/m/mC3CJ97bAQAJ ) to IMA team about an asset which was not working once I seek to the mid-roll.

Now, they are saying that this is fixed now and fix was in ExoPlayer v2.13.3. Because for this DAI asset, i did not see any log which tell me about the issue. 
Can you please tell me what was the root cause of it ?

**Comment by marcbaechinger** [comment] 2021-05-25 22:30
The thread in the IMA SDK group thread is referring to #8890 which is marked as a duplicate of #8937. The fix for this was this commit: https://github.com/google/ExoPlayer/commit/8ded11753ee4df9452aa8f483111b5fe8b7bb73e

As far as I understand this was not related to the IMA SDK but a problem in the HLS implementation of ExoPlayer that is used by the IMA asset.

**Comment by ojw28** [comment] 2021-05-26 09:19
Whilst I agree that the chain of messages and issues leads to 8ded117, that commit only landed in 2.14.0, so if the issue was really fixed in 2.13.3 then that commit can't be the relevant one.

That said, the chain of communication regarding this issue is quite confused and hard to untangle, so I don't think it's a good use of time to try and figure out whatever the real root cause was. If finding this out is very important to you and if you're able to reproduce the issue, then I'd suggest you perform a bisection of the commits in 2.13.3 to locate the one that fixed the issue.

**Closed as completed by ojw28** 2021-05-26 09:19 UTC
Labels: question
