### ISSUE TITLE
Incompatibility with http:// mjpeg stream + url auth is not possible gives error

### ISSUE THREAD

**Issue by Anioz** [google/ExoPlayer#10999] opened 2023-02-18 08:23 UTC
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

Android Note8 Android 10
S7E Android 10

### Reproducible in the demo app?

Yes

### Reproduction steps

Prep: Hook up your favorite webcam to snap motioneye raspberry pi and make the http:// stream
Set the Android manifest with all the necessary internet permissions
 android:usesCleartextTraffic="true" android:networkSecurityConfig="@xml/network_security_config" && perm internet

1. Create control
2. Set its source to an auth (http://user:pswd@13.3.2.21:8085) URL that youve tested in your local browser to know if its working (mjpeg format)
3. See the errors in the debug output window

### Expected result

Just plays stream like a browser

Propositions:
Allow forcing the AUTH containing url instead of filtering it for credentials and trying to handle that behind the scene which currently somehow breaks (might force the general url auth problem)

Add a codec that can handle mjpeg streams like a webview (which currently works) scale to fit without any extra bells and whistles just to offer a way out of this madness

### Actual result

1st test without the AUTH in the http:// url
Fails to play stream with error:
[ExoPlayerImplInternal] Playback error
[ExoPlayerImplInternal]   com.google.android.exoplayer2.ExoPlaybackException: Source error
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:607)
[ExoPlayerImplInternal]       at android.os.Handler.dispatchMessage(Handler.java:103)
[ExoPlayerImplInternal]       at android.os.Looper.loop(Looper.java:237)
[ExoPlayerImplInternal]       at android.os.HandlerThread.run(HandlerThread.java:67)
[ExoPlayerImplInternal]   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[ExoPlayerImplInternal]       at java.lang.Thread.run(Thread.java:919)

2nd test with AUTH in the url:
[ExoPlayerImplInternal] Playback error
[ExoPlayerImplInternal]   com.google.android.exoplayer2.ExoPlaybackException: Source error
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:609)
[ExoPlayerImplInternal]       at android.os.Handler.dispatchMessage(Handler.java:103)
[ExoPlayerImplInternal]       at android.os.Looper.loop(Looper.java:237)
[ExoPlayerImplInternal]       at android.os.HandlerThread.run(HandlerThread.java:67)
[ExoPlayerImplInternal]   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 401
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:413)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:262)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
[ExoPlayerImplInternal]       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[ExoPlayerImplInternal]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[ExoPlayerImplInternal]       at java.lang.Thread.run(Thread.java:919)

### Media

MJPEG stream http stream with AUTH or without AUTH

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2023-02-20 16:59
ExoPlayer doesn't support the mjpg format, support is tracked by https://github.com/google/ExoPlayer/issues/7312

Note that mjpeg is (confusingly) not the same as JPEG Motion Photo (which is a short MP4 video bundled alongside an image). We do support playing the video from inside a JPEG Motion Photo: https://exoplayer.dev/supported-formats.html

It's unclear to me whether you're seeing additional auth issues, or just the lack of support for your chosen video format. I'm going to close this as a duplicate of #7312, please open a new issue if you can reproduce the auth issues with a supported media format.

**Closed as completed by icbaker** 2023-02-20 16:59 UTC
Labels: duplicate
