### ISSUE TITLE
 HLS AES is not playable in 2.7.3 but working on 2.6.0

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#4135] opened 2018-04-16 19:11 UTC
Hi,
Sending in mail url that is not playable in 2.7.3 but working on 2.6.0

this is HLS AES media where we receive the following exception in the Demo App
"Cannot find sync byte. Most likely not a Transport Stream"
This stream (sending in mail) working fine on 2.6.0

Please look int to the regression.
Using VPN to india required  you can connect via expressVpn app to Mumbai (it is 30days free)  

 04-16 22:08:27.827 199-797/? D/audio_hw_primary: disable_snd_device: snd_device(2: speaker)
04-16 22:08:28.465 24042-24042/com.google.android.exoplayer2.demo E/EventLogger: internalError [3.78, loadError]
                                                                                 com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
                                                                                     at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:256)
                                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:285)
                                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
04-16 22:08:28.474 24042-24205/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
                                                                                           com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
                                                                                               at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:256)
                                                                                               at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:285)
                                                                                               at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219)
                                                                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                               at java.lang.Thread.run(Thread.java:818)
04-16 22:08:28.476 24042-24042/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [3.79]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:353)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
                                                                                     at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:256)
                                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:285)
                                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)

PS.

Pretty sure this is issue is side affect by fix done for: 
https://github.com/google/ExoPlayer/issues/3632
 
10x
Gilad.

**Comment by AquilesCanta** [comment] 2018-04-17 15:34
Could you provide a bugreport, please?

**Comment by giladna** [comment] 2018-04-17 16:39
@AquilesCanta 

Sending now link to drive with issue#4135

contains logs from Nexus 6p 8.1  and nexus 5 - 6.0

**Comment by ojw28** [comment] 2018-06-05 22:41
@AquilesCanta - Did you have a chance to look at this?

**Comment by AquilesCanta** [comment] 2018-06-08 13:50
Hi @giladna, I am getting a 403 after trying several proxies in India (including Mumbai). Could you donwload and send to us the master playlist, one of the media playlists and a few segments from that playlist, along with the key? That would make debugging much easier. You could put it in a Google drive and send it to dev.exoplayer@gmail.com for us to see. Many thanks.

**Comment by AquilesCanta** [comment] 2018-06-21 09:06
Hi @giladna, any updates? Could you please provide a drive link containing a minimal reproducing playlist with segments? A playlist with a few segments should be enough.

**Comment by ojw28** [comment] 2018-09-17 19:42
Closing due to lack of required information.

**Closed as completed by ojw28** 2018-09-17 19:42 UTC
