### ISSUE TITLE
Player is unable to parse an embedded TTML.

### ISSUE THREAD

**Issue by ozguroktem** [google/ExoPlayer#10931] opened 2023-01-17 15:35 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Samsung Galaxy A22 running Android 13
Xiaomi Redmi Note 7 running Android 11
Huawei Mate 20 Lite running Android 10

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play the media in question.
2. Select any subtitle.

### Expected result

The player continues to play the media and shows the subtitle after selecting one.

### Actual result

The player immediately stops after selecting any subtitle and playback crashes with the following stack trace:

`Playback error
                                                       com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:621)
                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                           at android.os.Looper.loop(Looper.java:223)
                                                           at android.os.HandlerThread.run(HandlerThread.java:67)
                                                       Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                           at com.google.android.exoplayer2.text.ttml.TtmlSubtitle.getEventTime(TtmlSubtitle.java:62)
                                                           at com.google.android.exoplayer2.text.SubtitleOutputBuffer.getEventTime(SubtitleOutputBuffer.java:53)
                                                           at com.google.android.exoplayer2.text.TextRenderer.getCurrentEventTimeUs(TextRenderer.java:426)
                                                           at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:259)
                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
                                                           at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)`

### Media

Sent it through email.

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2023-01-17 16:25
Duplicate of #10867

**Closed as completed by icbaker** 2023-01-17 16:25 UTC
Labels: duplicate
