### ISSUE TITLE
Exoplayer can not play http://hbsh.chinashadt.com:2036/live/8.stream/chunklist_w693062733.m3u8

### ISSUE THREAD

**Issue by lsgfly** [google/ExoPlayer#6079] opened 2019-06-22 06:05 UTC
[REQUIRED] Issue description
I use the Exoplayer to play the url　　　http://hbsh.chinashadt.com:2036/live/8.stream/chunklist_w693062733.m3u8 .
It can not be played successful, but no error occured.
But when I get the ts from m3u8 file, It can be played successful.
other m3u8 can be played successful.

[REQUIRED] Reproduction steps
play the url http://hbsh.chinashadt.com:2036/live/8.stream/chunklist_w693062733.m3u8 .

[REQUIRED] A full bug report captured from the device

[REQUIRED] Version of ExoPlayer being used
2.8.2

[REQUIRED] Device(s) and version(s) of Android being used
android 9.0 vivo X27 . many devices can not play successful

**Comment by ojw28** [comment] 2019-06-22 11:04
Isn't this the same root cause as https://github.com/google/ExoPlayer/issues/6077? Closing on the assumption this is a duplicate.

**Closed as completed by ojw28** 2019-06-22 11:04 UTC
Labels: duplicate
