### ISSUE TITLE
Player ignores LoadControl and buffering continues after pausing AAC Stream

### ISSUE THREAD

**Issue by izpakla** [google/ExoPlayer#7043] opened 2020-03-04 13:59 UTC
### Issue description
ExoPlayer instantiation and values used for DefaultLoadControl:
```
private val dataSourceFactory: DefaultDataSourceFactory by lazy {
    DefaultDataSourceFactory(this, Util.getUserAgent(this, "user-agent-test"), null)
}

private val audioAttributes = AudioAttributes.Builder()
    .setContentType(C.CONTENT_TYPE_MUSIC)
    .setUsage(C.USAGE_MEDIA)
    .build()

private val exoPlayer: ExoPlayer by lazy {
    val loadControl = DefaultLoadControl.Builder()
        .setBufferDurationsMs(
            1000,
            2000,
            500,
            500
        )
        .setPrioritizeTimeOverSizeThresholds(true)
        .createDefaultLoadControl()

    ExoPlayerFactory.newSimpleInstance(this, DefaultTrackSelector(), loadControl).apply {
        setAudioAttributes(this@MainActivity.audioAttributes, true)
    }
}
```

Buffering does not stop when setting
`exoPlayer.playWhenReady = false`

Android Studio Profiler shows the same network activity when `playWhenReady` is true.
Network activity actually stops after ~3 minutes.

Second scenario:
When network connection is disabled (stream was playing) there were around 30 to 80 (in some cases) seconds of audio available before it actually stopped.

### Version of ExoPlayer being used
2.11.3

**Comment by krocard** [comment] 2020-03-09 18:03
Toni, is this working as expected?

**Comment by tonihei** [comment] 2020-03-12 12:37
> Buffering does not stop when setting
exoPlayer.playWhenReady = false

This part is definitely working as intended. If the player is paused, we still fill the buffer so that playback can resume as quickly as possible.

> Second scenario:
When network connection is disabled (stream was playing) there were around 30 to 80 (in some cases) seconds of audio available before it actually stopped.

The data of progressive streams is loaded in small chunks of 1 MB (by default) before checking whether more data needs to be loaded. 1 MB for a 128kbps AAC stream is about 65 seconds, so yes, this is working as expected too.

If you want the progressive stream loader to check more often, you can override the default value for this in the `ProgressiveMediaSource.Factory` by calling `setContinueLoadingCheckIntervalBytes` with your desired value.

**Comment by tonihei** [comment] 2020-04-17 17:29
Assuming the question was answered and closing the issue. If not, please reopen.

**Closed as completed by tonihei** 2020-04-17 17:29 UTC
Labels: question
