### ISSUE TITLE
How to distinguish between i-frame and video tracks in HLS streams.

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#8405] opened 2020-12-28 05:31 UTC
In new version of exoplayer we are getting i-frame list in Format under video track. We don't have any way differentiate between actual video tracks and i-frame tracks.

This will help us in resolving right track for download.

**Comment by AquilesCanta** [comment] 2020-12-29 13:28
Duplicate of #8313.

**Closed as completed by AquilesCanta** 2020-12-29 13:28 UTC
Labels: duplicate, question
