### ISSUE TITLE
CodecException occurs during playback

### ISSUE THREAD

**Issue by ogawa-ma** [google/ExoPlayer#10621] opened 2022-09-14 12:02 UTC
■ Question
We have published an application that uses ExoPlayer, but some users are experiencing CodecException during streaming playback.
Since the error is occurring in MediaCodec, it seems like there is a problem with the video file, but I can't figure out the cause.
Can you find the cause from the logs or video files?

■ ExoPlayer version used
* 2.16.1

■ Some of the devices that are occurring
* Galaxy A32 5G(OS version 12)
* Galaxy A41(OS version 10)
* HUAWEI MediaPad T5(OS version 8)

■ Android version in which this is occurring
* 5~12

■ Playback Video Format
* Widevine DASH (H.264)

```
Caused by android.media.MediaCodec$CodecException: start failed
       at android.media.MediaCodec.native_start(MediaCodec.java)
       at android.media.MediaCodec.start(MediaCodec.java:2235)
       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:69)
       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:124)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1063)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:982)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:540)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1395)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:764)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:936)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:765)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:246)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```
![crash](https://user-images.githubusercontent.com/54785318/190147743-75cc861b-1927-4172-907a-58f7a8f42125.png)

I have sent the media file URL and the license server URL to dev.exoplayer@gmail.com.

**Comment by rohitjoins** [comment] 2022-09-14 17:23
@ogawa-ma I tried playing the media file sent via email and was able to play it successfully on the mentioned OS version and device. 

Without being able to reproduce I'm afraid there's not much more help we can offer.

**Comment by rohitjoins** [comment] 2022-09-20 19:18
Duplicate of #10620

**Closed as completed by rohitjoins** 2022-09-20 19:18 UTC
Labels: question
