### ISSUE TITLE
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error

### ISSUE THREAD

**Issue by adamheinrich-oke** [google/ExoPlayer#10519] opened 2022-08-12 10:21 UTC
On certain devices the playback fails with MediaCodecVideoRenderer error. Error seems to relate to the fullHD rendition which is included in manifest file. So far we excluded the 1080p quality profile and playback works. Typically one can start the first playback, and when it tries to upscale, the player crashes. Following attempts to start another playback directly fail.

I attach the logs from  JNY-LX1 Huawei.
[Huawei BP stream issue Android studio log_2.txt](https://github.com/google/ExoPlayer/files/9315479/Huawei.BP.stream.issue.Android.studio.log_2.txt)
 
Temporary fix was to set the maxbitrate to 4.2 mb
```
2022-08-08 12:43:30.220 29029-30690/nl.streamgroup.skylinkcz E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video=4714400, null, null, video/avc, avc1.640029, 4714400, null, [1920, 1080, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2699)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:149)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1345)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:219) 
```

 If needed I'll send via email .mpd manifest file as well.

Not working list of devices is: Redmi Note 6 Pro, Redmi 5 Plus, Redmi K20 Pro/Mi 9T Pro, Honor 9, Redmi Note 7/Z717VL, Huawei mate 20 lite,JNY-LX1 and more.

**Comment by icbaker** [comment] 2022-08-15 16:16
The attached Huawei log file looks like a different error:

```
2022-08-08 12:43:31.513 29029-29029/nl.streamgroup.skylinkcz E/EventLogger: playerFailed [15.03]
    com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video=4714400, null, null, video/avc, avc1.640029, 4714400, null, [1920, 1080, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2699)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:149)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1345)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

----

Can you clarify what your question is?

**Comment by adamheinrich-oke** [comment] 2022-08-16 09:24
I edited the question. I do not own any of these devices so emulator was used for reproduction purposes. We never had any issues with playing drm protected content on emulator as well. Before the edit I attached logs from emulated device with  UnsupportedSchemeException/UnsupportedDrmException thrown.

**Comment by m-scheepers** [comment] 2022-08-24 10:01
@icbaker to clarify this further, the HD profile is Widevine L1. For devices which do not support Widevine L1 I would expect the client plays the L3 renditions which are available within the manifest.

**Comment by icbaker** [comment] 2022-08-24 10:20
> For devices which do not support Widevine L1 I would expect the client plays the L3 renditions which are available within the manifest.

ExoPlayer currently does not check key status before adapting to a rendition, this is tracked by https://github.com/google/ExoPlayer/issues/4825.

The current recommendation is to ensure on your side that you don't try and play an unplayable stream: https://github.com/google/ExoPlayer/issues/4825#issuecomment-422116376

It sounds like this should probably be closed as a duplicate of https://github.com/google/ExoPlayer/issues/4825.

**Comment by icbaker** [comment] 2022-09-08 16:26
Duplicate of https://github.com/google/ExoPlayer/issues/4825.

**Closed as completed by icbaker** 2022-09-08 16:26 UTC
Labels: duplicate
