### ISSUE TITLE
VideoRenderer Freezes when playing a 60 fps stream

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#10019] opened 2022-03-03 09:39 UTC
Hello,

I am asking you following a freeze and macro block problem following the reading of a 60 fps stream under ExoPlayer.
The stream is in ExoPlayer Demo:

      {
        "name": "HD (MP4, H264, Widevine cenc)",
        "uri": "https://storage.googleapis.com/exoplayer-test-media-1/60fps/bbb-wv-1080/manifest.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
      }

Report :

In the processOutputBuffer function under MediaCodecVideoRenderer:
long earlyUs = (long) ((bufferPresentationTimeUs - positionUs) / playbackSpeed);
I noticed that the earlyUs value is negative during freezes (it can happen up to -250 ms). Which indicates that we are late
relative to the rendering of the image.

If earlyUs < -30 ms ExoPlayer either ignores the buffer or discards frames. (in isBufferLate)

So, if we change the test in isBufferLate to prevent frames from being discarded, the situation improves less from the freeze.

Is there a way in ExoPlayer  that will allow us this problem of freezes ?

BR,

**Comment by ojw28** [comment] 2022-03-07 19:59
The device you're testing on may just not be performant enough to play HD 60fps Widevine protected content. If the device can't keep up, then video frames will be dropped. The stream works without any frame drops on a Galaxy S20, so it does seem that it depends on the performance of the device.

If the device is obviously too low-end to support this type of content (including if the device is an emulator), then I think this is working as intended, and that a production app would need to provide such a device with lower quality content.

Alternatively, you could try enabling asynchronous queuing as per https://github.com/google/ExoPlayer/issues/6348#issuecomment-934292402. @christosts - Is there a post that explains how to enable it now that it's no longer experimental?

**Comment by christosts** [comment] 2022-03-08 11:15
> Alternatively, you could try enabling asynchronous queuing as per [#6348 (comment)](https://github.com/google/ExoPlayer/issues/6348#issuecomment-934292402). @christosts - Is there a post that explains how to enable it now that it's no longer experimental?

We don't have a post, but this [comment on #9894](https://github.com/google/ExoPlayer/issues/9894#issuecomment-1034726822) has a code snippet how to enable the feature.

**Comment by christosts** [comment] 2022-03-25 16:08
We added documentation how to enable asynchronous buffer queueing on the customization pages of the player's website (will appear on the next release). Closing this issue.

**Closed as completed by christosts** 2022-03-25 16:08 UTC
Labels: question
