### ISSUE TITLE
Is there any step by step tutorial to implement FFMPEG extension to play MPEGA audio in HLS?

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4363] opened 2018-06-09 11:23 UTC
I want to play ac3 audio in HLS streaming in exoplayer. The sound is not coming. Does exoplayer support ac3 audio in HLS and is there any step by step tutorial to implement ffmpeg in exoplayer

**Comment by AquilesCanta** [comment] 2018-06-09 18:59
Duplicate of #4357.

**Closed as completed by AquilesCanta** 2018-06-09 18:59 UTC
Labels: duplicate
