### ISSUE TITLE
Random AVSync issues with exoplayer version 2.11.4 and above

### ISSUE THREAD

**Issue by biswarupdasgupta** [google/ExoPlayer#7607] opened 2020-07-08 14:45 UTC
### [REQUIRED] Reproduction steps
Start player from a position > 0 (e.g startPosition as 10mins)
The issue is quite random and happens suddenly if player is started from a non-zero position. Once avsync is lost, player does not recover at all.

Here is a code snippet on how we are initialising player

 ```
       playerView.setPlayer(player);
        playerView.setPlaybackPreparer(playbackPreparer);
        if(startPosition > 0){
            this.startPosition = startPosition;
        }
        boolean haveStartPosition = startPosition != C.TIME_UNSET;
        if (haveStartPosition) {
            player.seekTo(startPosition);
        }
        player.prepare(mediaSource, !haveStartPosition, false);
```

### [REQUIRED] Link to test content
Checking with client if we can share a test stream

### [REQUIRED] A full bug report captured from the device
https://drive.google.com/drive/folders/1-EoqpWCvLDMuEid7-SrpLGuaZ38wicvp?usp=sharing

### [REQUIRED] Version of ExoPlayer being used
2.11.4 and 2.11.6

In 2.11.6 the issue is more prominent

### [REQUIRED] Device(s) and version(s) of Android being used
Android Xiaomi, OnePlus and Huawei devices

**Comment by tonihei** [comment] 2020-07-13 08:36
The bug report unfortunately doesn't contain anything useful to say what happened. I'll mark the issue with "need more info" to wait for a test stream. Otherwise it's hard to say what the issue might be and if we can do something about it.

**Comment by krackjack234** [comment] 2020-07-29 11:53
Hi @tonihei  We could not share the test stream because of license issues, so sharing some screenshots and information about the issue.

Here are the screenshot of the player and device information when the issue happens. Please note the dk and mcdb values.

https://drive.google.com/drive/folders/1xepcZwAaAwe8BsXiQo5JxvpeZHBwMT80?usp=sharing

Hope it helps

**Comment by tonihei** [comment] 2020-07-31 09:23
Thanks for sharing the screenshot. It looks as if your playback experienced a lot of dropped frames and had problem keeping up.

Could you answer these questions to understand your problem a little bit better and to see if there is something we can do.
 1. "Random AV sync issues" - what does that mean exactly? Is audio playback smooth? Is video playback choppy and has problem keeping up with the audio? Or is it just dropping frames? What happens when you pause playback and then resume? 
2. "Start player from a position > 0 (e.g startPosition as 10mins)".  Is this step important? Or does it also happen if you let the stream play from the beginning until it reaches this position?
3. "with exoplayer version 2.11.4+"  Did you verify the same setup works with 2.11.3, but not with 2.11.4? If not, could you give that a try or clarify which versions you tested.
4. "We could not share the test stream because of license issues". You are welcome to share via dev.exoplayer@gmail.com mentioning "Issue #7607" in the subject line. If that's not possible, you could check if the problem reproduces with other media as well? Or only with this one stream?

Thanks!

**Comment by krackjack234** [comment] 2020-07-31 09:50
Hi @tonihei , please find my reply below

1. Issue happens if user does quick seek on certain positions of the stream. AV sync issue is not seen if user plays the stream without seeking. When the issue happens we can see the video getting stuck for some time and then it recovers but with out of sync audio
 
2. No this is no longer important step. We found that this issue happens even if we start the stream from 0 and do fast seek operations.

For 3 and 4 I will come back.

**Comment by krackjack234** [comment] 2020-08-04 07:37
@tonihei  For 3) issue is seen even with exo version 2.9.6
For 4), the test stream, sample apk and device logs are now shared over email. Issue is happening with specific media streams on seek. 

Do let us know if any other information will help in analysing the issue.

**Comment by tonihei** [comment] 2020-08-04 11:49
Thanks for providing all the detailed information! I tried playing the stream on a Pixel 4 and a Nexus 6P, but both work fine with your APK and stream (and seeking around), no dropped frames at all.

Could you tell us a list of devices on which you observed the issue (as specific as possible: brand, model, OS version). If we have one of the devices in the office, I'll try to obtain one to test the issue again.

**Comment by krackjack234** [comment] 2020-08-04 17:28
hi @tonihei  we are able to reproduce this issue with OnePlus7. The device details and adb bugreport are available in the same link

**Comment by christosts** [comment] 2020-08-07 13:05
I have a OnePlus 3T and gave it a try but wasn't able to reproduce the issue.

One thing to note, it may not be related but I'm tracking it just in case: the content is geo-protected but initially I was able to get playback working without additional setup on my device (geo-protection wasn't fully working at that point?) For about 20 minutes, I was streaming content and there were issues with dropped frames. Very frequently video was freezing and audio kept going, sometimes up to 5-10 seconds. This was happening with or without a seek, and also on a Pixel 4. I could see a lot of error logs coming from the AudioTrack about audio discontinuities, for example

```
E/AudioTrack: Discontinuity detected [expected 144042666, got 216042000]
```

However, at some point all HTTP requests started returning 403 and I configured my device(s) accordingly. At that point I also got slightly different content, e.g. the logo on the top right was not appearing before, which is when I realised I may have been receiving an invalid stream until that point. After I configured my devices, I have been streaming the content without any issues for about 1 hour.

I wasn't able to figure out why the discontinuities occurred in the first place.

**Comment by krackjack234** [comment] 2020-08-12 18:14
hi @christosts when you saw the video, was it the same stream as the one seen in the video recordings we shared?
We found that the issue is seen more when user is connected to mobile data and not wifi.

**Comment by christosts** [comment] 2020-08-25 10:51
In playbacks that worked fine, the test stream was the same with the video recordings you have shared.

During the short period of time that the playback was not working (due to incorrect device geo-location setup), the content was slightly different: the logo pop-up of the service in the beginning of the stream did not appear and the video jumped directly to the main content. Also the logo wasn't visible on the top-right corner, so I guess the video content was different.

I attempted to repro again but the stream returns an HTTP 403. Can you please check if the stream is still available for us to test?

**Comment by tonihei** [comment] 2020-10-09 17:36
Thanks for providing stream access. I can play the stream again and tested on a OnePlus 7 with ExoPlayer 2.11.4. I seeked quickly to various positions, but could never reproduce the issue as visible in your video. 

Is there anything else I could try? Any specific stream positions / seek sequences? And how often do you have to seek to see the issue?

**Comment by biswarupdasgupta** [comment] 2020-10-14 15:09
Issue was seen more on mobile networks. So if possible, can you please
throttle the speed and check?

Thanks

**Comment by tonihei** [comment] 2020-10-28 12:02
I also tried again with a throttled connection, but I still couldn't observe the problem. Not sure if there is anything else I can do here if it's not possible to reproduce despite using the same device (OnePlus 7), the same video (provided via email), the same ExoPlayer version (2.11.4), a slow (throttled) connection and performing multiple seeks.

I think I'll close this issue as not reproducible, but if you have another idea or other steps that let you reproduce the issue reliable, please feel free to reopen or file a new issue.

**Closed as completed by tonihei** 2020-10-28 12:02 UTC
Labels: wont fix: not reproducible
