### ISSUE TITLE
ExoPlayer hls stream freezes after a few minutes of playing

### ISSUE THREAD

**Issue by lazarvgd** [google/ExoPlayer#2476] opened 2017-02-20 12:26 UTC
Hi,

I have an issue with ExoPlayer. I can play HLS stream for a few minutes, but after a few minutes it freezes, no output warnings in logcat, no errors.
The only message I got is this `E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010` , but player is able to play the stream.

Also I am able to "refresh" the player by recreating the player with the same url. This is happening for various HLS stream soruces.

EDIT:
I have tried this on real device and got the same issue.

Here is the screenshot of the player:
![freez](https://cloud.githubusercontent.com/assets/11629801/23124991/11b6547a-f770-11e6-90e3-63d3d51bc38c.png)

Can you please advice me about this issue?
Thanks

**Comment by AquilesCanta** [comment] 2017-02-20 12:37
Have you managed to reproduce with a physical device?

**Comment by AquilesCanta** [comment] 2017-02-20 12:37
Please provide all the information in the issue template, as well.

**Comment by lazarvgd** [comment] 2017-02-20 12:42
Please tell me if I need to provide source code?
Thanks

**Comment by AquilesCanta** [comment] 2017-02-20 13:05
No, assuming you can reproduce this using the DemoApp, please send a link to the stream, as requested in the issue template.

**Comment by lazarvgd** [comment] 2017-02-20 13:38
Unfortunately I am not able to provide you stream URLs because there are network restrictions - I am accessing these streams over VPN. Any other suggestions?

**Comment by AquilesCanta** [comment] 2017-02-20 14:11
There is not enough information for me to know what the issue is. For starters, I will need the media sample you are using. Try reproducing with a few concatenated chunks instead of an HLS manifest. If it reproduces, send me the chunks. Also send the bugreport from the physical device, please.

**Comment by mcart666** [comment] 2017-03-15 10:51
Hi,

Possibly I have the same issue. Playback of live HLS stream freezes, player enters "BUFFERING" state, no useful information provided by logcat. ExoPlayer for some reason just stops downloading the subsequent media segments, but still tries to get m3u8 playlists.

Device: Xiaomi Mibox
ExoPlayer v2.2.0

I can provide the stream that gives 100% reproduction rate (also on demo application), but please let me know how to do that - it's about 150 MB. Size of files that can be attached here is limited to 10 MB.

**Comment by AquilesCanta** [comment] 2017-03-15 11:17
I am closing this issue due to lack of required info.

 @mcart666, please open a new issue including all information required in the issue template.

**Closed as completed by AquilesCanta** 2017-03-15 11:17 UTC
Labels: need more info
