### ISSUE TITLE
Issues with cast extension and live HLS streams

### ISSUE THREAD

**Issue by guy244** [google/ExoPlayer#5226] opened 2018-12-10 00:36 UTC
Hey, I'm trying the implement cast support to my app, when I use normal non live links such as MP4 and even HLS non live stream it works perfectly but, when I use live stream the stream just won't play at the chromecast.

This is how I create my MediaInfo:
```
       MediaMetadata movieMetadata = new MediaMetadata(MediaMetadata.MEDIA_TYPE_MOVIE);
        movieMetadata.putString(MediaMetadata.KEY_TITLE, "Test");
        
MediaInfo mediaInfo = new MediaInfo.Builder("HLS link")
                .setStreamType(MediaInfo.STREAM_TYPE_LIVE).setContentType(MimeTypes.APPLICATION_M3U8)
                .setMetadata(movieMetadata).build();

```
This is how I load the items:
`                castPlayer.loadItem(new MediaQueueItem.Builder(setCastMedia()).build(), 0);
`

This is the logcat I get:
` W/MediaControlChannel: received unexpected error: Invalid Request.
 W/MediaQueue: Error fetching queue item ids, statusCode=2100, statusMessage=null
`

Any ideas what I'm doing wrong?
Happens the same with TS type streams...

**Comment by guy244** [comment] 2019-01-02 19:34
anything?

**Comment by AquilesCanta** [comment] 2019-01-03 16:25
Hi, we are currently putting our efforts in implementing a custom receiver app so we have full control of the delivered experience. We are working to release this as soon as we can, but we still have some more work to do. Thanks for your patience!

**Comment by AquilesCanta** [comment] 2019-01-03 16:27
Also, please don't skip items in the issue template when reporting stuff. There is not much I can do with the provided information. The provided logcat line may not even be related to the issue, that's why we ask for a full bugreport. Plus, a sample media link is necessary for us to reproduce and investigate further.

**Comment by tonihei** [comment] 2019-05-07 14:31
Closing because the requested information was not provided.

**Closed as completed by tonihei** 2019-05-07 14:31 UTC
