### ISSUE TITLE
M3u8 Not Playing after first ts segment.

### ISSUE THREAD

**Issue by Akash1034** [google/ExoPlayer#4399] opened 2018-06-21 06:37 UTC
**### Issue Description**:
I have been trying to play a m3u8 file(audio) with segments having byte ranges. The file works smoothly till end if no action is performed(pause/play). But when pausing and playing the file, it doesn't play or even when you seek the audio, it doesn't resumes. This is happening only in case of audio which is m3u8 format.

### **Reproduction steps**:
The issue can be reproduced by playing the file for more than 10 secs(each segment is 10 secs), and then pause/play the file. The issue can also be reproduced by seeking the file as well.

When debugged, found that when the first segment is playing(around first 10 secs), any action(pause/play) can be done it works fine, but when the second segment is loaded after that no actions can be done as the exoplayer stuck and never recovers. The Exoplayer stays in STATE_BUFFERING state and doesn't recovers to STATE_READY state after first segment is over and any action is performed after it(After first segment).

Please find the pseudo code through which we are trying to play the audio:

To initiate the player:
private void initPlayer() {

    trackSelector = new DefaultTrackSelector();
    renders=renderer();
    exoPlayer = ExoPlayerFactory.newInstance(renders, trackSelector, new CustomLoadControl(new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE), 50000,50000,5000,10000,10000, true));
    exoPlayer.addListener(mlistener);
}
To prepare the player:

public void prepare() {
exoPlayer.prepare(buildMediaSource(Uri.parse(mUrl),""),true,true);
}

To pause the audio:
public void pause(long posMs) {
exoPlayer.setPlayWhenReady(false);
Logger.d("Constant", posMs);
}

To play the audio:
public void play(String url,long posMs,int peerId) {
mUrl = url;
command= SpConstants.ACTION_PLAY;
_peerId=peerId;
exoPlayer.setPlayWhenReady(false);
prepare();
exoPlayer.seekTo(posMs);
}

### **Version of exoplayer used**:
Tried with 2.2.0, 2.6, 2.8.1.

**Comment by tonihei** [comment] 2018-06-21 08:20
Duplicate of #4390. Please don't open new issues for the same problematic content.

**Closed as completed** 2018-06-21 08:40 UTC
Labels: duplicate

**Comment by AquilesCanta** [comment] 2018-06-21 08:44
Also, someone commented this was no longer an issue. Please update the referred issue if not the case. Having a look at the code now, I don't see that setPlayWhenReady(true) is being called. In any case, please close the other issue if this has been solved.
