### ISSUE TITLE
When changing video tracks in Live +  Dash + DRM Widevine + HEVC Media the first 2 seconds frame are pixled

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#9094] opened 2021-06-21 19:07 UTC
I am playing live dash drm hevc media on the demo app
with the following bitrates: 
 384000, 560000, 920000, 2200000, 4520000

when track selection is done manually I can see that the first frames are not fluent and pixels are shown 

when I run this media on Android TV I do not see this issue on tracks selection but on mobile device it is happening.

when I perform track selection using the dialog for example to 920000 i can see in the logs the following:
I  am not sure whether it is the decoders of the hevc/ stream encoding/  drm  or the player  please advice.

`Buffer can't be freed`

```
2021-06-21 21:46:08.467 3911-3911/com.google.android.exoplayer2.demo D/EventLogger: ]
2021-06-21 21:46:08.526 7370-7370/? D/io_stats: !@   8,0 r 792441 33311320 w 833211 25950896 d 82212 109294680 f 251192 364721 iot 750080 583182 th 102400 102400 65496 pt 560 inp 0 0 159525.421
2021-06-21 21:46:08.576 3911-3911/com.google.android.exoplayer2.demo D/EventLogger: downstreamFormat [eventTime=18.81, mediaPos=7189.84, window=0, period=0, id=3, mimeType=video/hevc, bitrate=920000, codecs=hev1.1.6.L93.B0, res=1024x576, fps=25.0]
2021-06-21 21:46:08.576 3911-3911/com.google.android.exoplayer2.demo D/EventLogger: videoInputFormat [eventTime=18.81, mediaPos=7189.84, window=0, period=0, id=3, mimeType=video/hevc, bitrate=920000, codecs=hev1.1.6.L93.B0, res=1024x576, fps=25.0]
2021-06-21 21:46:09.151 3911-3911/com.google.android.exoplayer2.demo D/EventLogger: videoSize [eventTime=19.38, mediaPos=7189.84, window=0, period=0, 1280, 720]
2021-06-21 21:46:09.152 3911-3911/com.google.android.exoplayer2.demo D/EventLogger: renderedFirstFrame [eventTime=19.38, mediaPos=7189.84, window=0, period=0, Surface(name=null)/@0xea63667]
2021-06-21 21:46:09.152 7430-7430/? W/adbd: timeout expired while flushing socket, closing
2021-06-21 21:46:09.166 5508-4065/? I/EXYNOS_BASE_PORT: [0xe6745c00][Exynos_OMX_PortDisableProcess] Before disabling output port, do flush
2021-06-21 21:46:09.166 5508-3574/? E/EXYNOS_VIDEO_DECCONTROL: [0xe6745c00][Exynos_OMX_FreeBuffer] Buffer can't be freed because this(0xe67b3820) is already in component
2021-06-21 21:46:09.166 5508-3574/? E/EXYNOS_VIDEO_DECCONTROL: [0xe6745c00][Exynos_OMX_FreeBuffer] output port : invalid state : comp state(0x3), port state(0x2), enabled(0x1)
2021-06-21 21:46:09.166 5508-4073/? W/libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
2021-06-21 21:46:09.167 5508-4065/? I/EXYNOS_BASE_PORT: [0xe6745c00][Exynos_OMX_PortDisableProcess] Disable output Port
2021-06-21 21:46:09.167 3911-4063/com.google.android.exoplayer2.demo I/ACodec: [OMX.Exynos.hevc.dec] Now handling output port settings change
2021-06-21 21:46:09.463 3911-3911/com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=19.70, mediaPos=7183.84, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2021-06-21 21:46:09.463 3911-3911/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
2021-06-21 21:46:09.463 3911-3911/com.google.android.exoplayer2.demo D/EventLogger:   window [7200.00, seekable=true, dynamic=true]
2021-06-21 21:46:09.464 3911-3911/com.google.android.exoplayer2.demo D/EventLogger: ]
```

- ExoPlayer version number - 2.14.1
- Android version - android 10
- Android device - galaxy s10e

on pixel 3 android 12 i get this log but there the playback is totally broken:

```
1-06-21 19:26:49.372 1112-20752/? E/QC2Comp: [hevcD_20] Codec returned output for non-existant input-index(12)!
2021-06-21 19:26:49.819 1112-20752/? E/QC2Comp: [hevcD_20] Codec returned output for non-existant input-index(16)!
2021-06-21 19:26:49.901 1112-20752/? E/QC2Comp: [hevcD_20] Codec returned output for non-existant input-index(20)!
2021-06-21 19:26:49.984 1112-20752/? E/QC2Comp: [hevcD_20] Codec returned output for non-existant input-index(22)!
2021-06-21 19:26:50.066 1112-20752/? E/QC2Comp: [hevcD_20] Codec returned output for non-existant input-index(24)!
```
I am Sending the configuration I was using in the Demo app to the dev mail.

![Image](https://user-images.githubusercontent.com/16818804/122813415-99817100-d2db-11eb-89cb-beb21dd319ae.png)

**Comment by icbaker** [comment] 2021-06-22 09:05
Thanks for providing the content over email, unfortunately I get a HTTP 403 when trying to play the stream. Is the stream geo-blocked? If so, please make it globally accessible.

```
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:588)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:203)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:86)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:176)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:411)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    ]
```

**Comment by giladna** [comment] 2021-06-22 13:46
@icbaker will UK will work for you?

vpn to Israel or India should also be working

10x

**Comment by icbaker** [comment] 2021-06-22 15:52
Thanks, I got it working by VPNing to Israel.

I see the same decoder artefacts as in your screenshot when manually switching tracks - I'll take a closer look to understand what's going on.

**Comment by giladna** [comment] 2021-06-22 17:35
@icbaker 
I was sniffing the network and I have observation which I am not sure is related 
I can see that by the time the track is switched then the time to download the chunk is > 1 sec and chunk size is bigger then the regular chunks 
could this  affect on the live buffers which are not ready yet till chunk is fully downloaded?

**Comment by icbaker** [comment] 2021-06-23 08:27
I haven't root caused the source of the artefacts yet, but I have noticed that the content doesn't seem to be DRM protected? I found I can still play it (with the same artefacts) with this JSON snippet in the demo app:

```json
{
    "name": "Live hevc (no DRM config)",
    "uri": "MPD URL from email"
},
```

**Comment by giladna** [comment] 2021-06-23 10:27
@icbaker  seems that you are right i do not see content protection in the manifest and it plays to me as well without the license

do you think it is related? 

we see in the logs an issue with the Buffer can't be freed when switching it

how do you suggest to continue I think it is more related to HEVC behaviour?

**Comment by giladna** [comment] 2021-06-23 16:19
@icbaker  

I have shared another stream with DRM

I have compared 2.14.0 vs 2.14.1  and in 2.14.1 when switching between video tracks there is no black screen as it used to be till today and artefacts is seen
so i guess that behaviour in DRM in 2.14.0 is not observed while in 2.14.1 is observed.

hope this helps

**Comment by giladna** [comment] 2021-06-25 11:41
@icbaker 
Any update for that?

**Comment by GAYANJ95** [comment] 2021-06-30 07:28
@icbaker Any update on this issue?

**Comment by GAYANJ95** [comment] 2021-07-05 19:29
Hi @icbaker did to able to check on this?

**Comment by giladna** [comment] 2021-07-05 20:30
@icbaker @ojw28 

I have investigated this issue some more 
I can tell that this issue behaviour was not there on v2.9.6 and first observed on v2.10.0

I think this information is a good starting point for understanding the root cause.

this behavior is in production and we would be happy if this can be prioritized by the team

10x

Gilad.

**Comment by GAYANJ95** [comment] 2021-07-08 03:29
@icbaker @ojw28 any update in this please. 🙂

**Comment by icbaker** [comment] 2021-07-12 14:57
I tried to reproduce this problem today and the links provided over email don't seem to be working. The first one seems to either return 404 or data that immediately crashes MediaCodec (screen only shows green, no video at all) and the second one (with DRM) seems to consistently return a 403 (tried VPNing to both India & Israel).

-----

> I have compared 2.14.0 vs 2.14.1 and in 2.14.1 when switching between video tracks there is no black screen as it used to be till today and artefacts is seen
> so i guess that behaviour in DRM in 2.14.0 is not observed while in 2.14.1 is observed.

I suspect (though this is a guess) that this is related to https://github.com/google/ExoPlayer/commit/58e307c6b00d95280fd6f2d7310ae3532f6b39e8 - since in 2.14.0 the secure decoder is probably fully released when switching tracks while in 2.14.1 it isn't.

This might also explain the difference you see between 2.9.6 and 2.10.0. From the 2.10.0 release notes:
> Improve decoder re-use between playbacks (#2826). Read [this blog post](https://medium.com/google-exoplayer/improved-decoder-reuse-in-exoplayer-ef4c6d99591d) for more details.

**Comment by giladna** [comment] 2021-07-13 05:41
@icbaker thanks 
I will share soon a new Live clear HEVC media the url that was shared is broken already :(
same vpn will be required

From the post I cannot see how apps can control if they have to disable this feature due to such behaviour

as we can see that for this  HEVC media we face that issue in between track switching and not between media changes

I could not see the issue on the first time media is loaded only after the bitrate change manually or by the ABR mechanised

 Please update if you can tell why in HEVC this issue occurs.

PS. I could also tell that in Pixel 3 android 12 the same media  when it was working was totally not playable only green screen was shown this should be investigated as well

10x

Gilad

**Comment by giladna** [comment] 2021-07-13 05:44
@icbaker 

I have rechecked and the url I gave is  actually working - sending it again 

which device did you try it on maybe this is what I saw on the Pixel?

I am using Samsung Galaxy S10e

Gilad


![pixel3-AN-12](https://user-images.githubusercontent.com/16818804/125399035-b2e87b00-e3b8-11eb-80ee-d4d119da01da.png)
![galaxy-s10e-AN-10](https://user-images.githubusercontent.com/16818804/125399044-b54ad500-e3b8-11eb-8d92-84690cf6d0b4.png)

**Comment by icbaker** [comment] 2021-07-14 09:56
*Edited on 2021-08-27 to strike out the incorrect evidence about i-frames. See https://github.com/google/ExoPlayer/issues/9094#issuecomment-907157354*

My previous comment was perhaps a bit terse - I'll try and explain in more detail what I think is happening.

Apologies if any of this is obvious - I'll try and lay out my reasoning clearly.

I see the following symptoms when playing on a OnePlus AC2003 using decoder `OMX.qcom.video.decoder.hevc`:
* When starting playback there's often lots of green before the picture emerges.
* When switching tracks (either manually at any time, or automatically at a segment boundary) there's often decoder artefacts (which you're calling pixellation).

**Investigation/interpretation:**
* The symptoms (green blocks when starting playback, and pixellation when switching tracks - both manually in the middle of a segment and automatically on segment boundaries) suggests that data is being incorrectly fed into the decoder.
   * ~Specifically: When encountering a 'discontinuity' the decoder expects to first receive an [I-frame (or key frame)](https://en.wikipedia.org/wiki/Video_compression_picture_types#Intra-coded_(I)_frames/slices_(key_frames)) for the new content. If it instead receives a P-frame or B-frame, it will try and apply this on top of the last I-frame from before the discontinuity - resulting in pixellation, because it doesn't apply correctly.~
   * ~When starting playback there's no previous I-frame, so the B-frames or P-frames are applied to an 'empty' frame, which is where all the green comes from.~
* ~ExoPlayer knows these requirements, so it deliberately feeds an I-frame to the decoder directly after a discontinuity.~

~**Hypothesis:**~
* ~ExoPlayer is incorrectly identifying P or B frames as I-frames and feeding them to the decoder at the start of playback or after a discontinuity.~
   * ~This is either because the frames are incorrectly identified in the media, or due to a bug in ExoPlayer's parsing of the media.~

~**Evidence:**~
* ~I logged the size of each sample being output by `FragmentedMp4Extractor`, as well as whether it thinks it's a key frame or not.~
* ~I-frames will generally be much larger than P or B frames because they contain a whole image (rather than just delta from the previous frame)~
* ~When playing only the 384kbps video track I found that most of the I-frames identified by ExoPlayer were implausibly small (400 - 600 bytes) and occasionally there was one of believable size (9,000 - 30,000 bytes).~
* ~Compared to a known-good piece of media, where all keyframes identified were 'large' (>5kB).~
* ~This supports the hypothesis - but doesn't show if the problem is with the media or with ExoPlayer.~

~**Further investigation:**
* ~In order to see if the media is incorrectly tagging the frames, or if ExoPlayer is incorrectly reading the media, I tried playing the media with VLC on MacOS and it didn't play at all.~

The fact this media doesn't play at all on VLC and has playback problems on ExoPlayer strongly suggests to me that the problem is with the media, not with ExoPlayer.

We're not media encoding experts - and unfortunately don't have the capacity to provide detailed debugging of every piece of problematic media.

~I suggest you investigate the encoding process used to create this media, and look at whether the keyframe tagging is correct.~

~If you want to look at the logic ExoPlayer uses to determine a sample is a keyframe you can follow it back from here:~
https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/FragmentedMp4Extractor.java#L1659-L1662

----
> From the post I cannot see how apps can control if they have to disable this feature due to such behaviour

This behaviour can't be easily disabled. With correctly parsed media it shouldn't cause problems - the reason it seems to cause problems in this case is because the media is being incorrectly parsed. That's what should be fixed imo (by fixing the media).

**Comment by giladna** [comment] 2021-07-14 11:08
@icbaker thank you for your time for the investigation and for your detailed answer.

I believe I will have to read it one more time to follow all you investigation process.

I have 2 questions tough,

Say it is bad media, why in Exo version v2.9.6  it was working?

Why does it behave differently over different android devices with Exo 2.14.1


Anyway I am taking your comments with our customer to double check the encoding

10x
Gilad.

**Comment by icbaker** [comment] 2021-07-14 11:19
> Say it is bad media, why in Exo version v2.9.6 it was working?
> 
> Why does it behave differently over different android devices with Exo 2.14.1

I think these have the same root cause(s):
* I suspect (but haven't verified) that before 2.10.0 ExoPlayer would release and recreate the MediaCodec instance when switching tracks manually (because there's a discontinuity).
* Before 2.14.1 ExoPlayer would release and recreate the MediaCodec when encountering a discontinuity in **DRM protected playbacks only** - including when switching tracks manually. 

I also suspect that different decoders will behave differently when fed with P and B frames before an I frame straight after decoder creation compared to in the 'middle' of a decoder's life. This is why releasing + recreating the decoder might behave differently to keeping the same decoder instance and feeding new frames to it. Since in all these cases the data being fed to the decoder is invalid, this is [undefined behaviour](https://en.wikipedia.org/wiki/Undefined_behavior) so decoder implementations are pretty free to behave as they please, from crashing (as you see on Pixel 3) to trying to play but with artefacts (as we see on other devices).

Something worth clarifying: Just because a piece of media works on a particular version of a player doesn't mean it's valid media. The validity of a piece of media is relative to the spec defining the media - not the behaviour of any particular implementation of that spec.

**Comment by ojw28** [comment] 2021-07-21 19:09
It's not necessarily the case, but I wonder if this is related to https://github.com/google/ExoPlayer/issues/9168.

**Comment by icbaker** [comment] 2021-08-09 15:13
Closing due to inactivity

**Comment by giladna** [comment] 2021-08-22 18:24
@icbaker 

Actually we got the customer comment last Friday as per their diagnose the stream is served correctly

I will share the information in direct mail to the team and the urls as well

hence there VPN to ISRAEL has to be used.

I have tested the stream again on exo v2.15.0 and I can see the same behaviour.

please take a look and see maybe there is a point that has to be considered

PS.
the stream is also playing in VLC

BR 

Gilad.

**Comment by giladna** [comment] 2021-08-22 21:04
@ojw28 

when changing the code on exo demo app 

with the code you gave for dash media

```
//      player =
//          new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
//              .setMediaSourceFactory(mediaSourceFactory)
//              .setTrackSelector(trackSelector)
//              .build();
      player =
              new SimpleExoPlayer.Builder(/* context= */ this)
                      .setMediaSourceFactory(
                              new ProgressiveMediaSource.Factory(
                                      new DefaultDataSourceFactory(/* context= */ this),
                                      new DefaultExtractorsFactory().setMp4ExtractorFlags(
                                              Mp4Extractor.FLAG_WORKAROUND_IGNORE_EDIT_LISTS)))
                      .setTrackSelector(trackSelector)
                      .build();
```

we get the following exception


```
2021-08-23 00:00:03.295 12486-13032/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:594)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1025)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

```

What is the suggested code for DASH?

**Comment by janakasud** [comment] 2021-08-26 08:12
@giladna,

can't we add the FLAG like this?

```
          MediaSourceFactory mediaSourceFactory =
          new DefaultMediaSourceFactory(
              dataSourceFactory,
              new DefaultExtractorsFactory().setMp4ExtractorFlags(
                  Mp4Extractor.FLAG_WORKAROUND_IGNORE_EDIT_LISTS))
              .setAdsLoaderProvider(this::getAdsLoader)
              .setAdViewProvider(playerView);
              
 ```
 
 Just by editing the _DefaultMediaSourceFactory_ in the Demo app instead of replacing with _ProgressiveMediaSource.Factory_.

**Comment by giladna** [comment] 2021-08-26 08:25
@janakasud 

thanks for your tip

I could reproduce the exact issue with the same media and with the following code 
so seems it is not the root cause

```
      MediaSourceFactory defaultMediaSourceFactory =
              new DefaultMediaSourceFactory(
                      dataSourceFactory,
                      new DefaultExtractorsFactory().setMp4ExtractorFlags(
                              Mp4Extractor.FLAG_WORKAROUND_IGNORE_EDIT_LISTS))
                      .setAdsLoaderProvider(this::getAdsLoader)
                      .setAdViewProvider(playerView);

      player =
              new SimpleExoPlayer.Builder(/* context= */ this)
                      .setMediaSourceFactory(defaultMediaSourceFactory)
                      .setTrackSelector(trackSelector)
                      .build();
```

I got this error in logcat

```
2021-08-26 11:21:19.477 5732-5732/com.google.android.exoplayer2.demo D/EventLogger: videoSize [eventTime=31.34, mediaPos=7183.68, window=0, period=0, 768, 432]
2021-08-26 11:21:19.477 5732-5732/com.google.android.exoplayer2.demo D/EventLogger: renderedFirstFrame [eventTime=31.34, mediaPos=7183.68, window=0, period=0, Surface(name=null)/@0x3c8e4bb]
2021-08-26 11:21:19.491 5505-6427/? I/EXYNOS_BASE_PORT: [0xeaaa5800][Exynos_OMX_PortDisableProcess] Before disabling output port, do flush
2021-08-26 11:21:19.491 5505-8333/? E/EXYNOS_VIDEO_DECCONTROL: [0xeaaa5800][Exynos_OMX_FreeBuffer] Buffer can't be freed because this(0xeaa36f40) is already in component
2021-08-26 11:21:19.491 5505-8333/? E/EXYNOS_VIDEO_DECCONTROL: [0xeaaa5800][Exynos_OMX_FreeBuffer] output port : invalid state : comp state(0x3), port state(0x2), enabled(0x1)
2021-08-26 11:21:19.491 5505-8333/? E/EXYNOS_VIDEO_DECCONTROL: [0xeaaa5800][Exynos_OMX_FreeBuffer] Buffer can't be freed because this(0xeaa36f40) is already in component
2021-08-26 11:21:19.491 5505-8333/? E/EXYNOS_VIDEO_DECCONTROL: [0xeaaa5800][Exynos_OMX_FreeBuffer] output port : invalid state : comp state(0x3), port state(0x2), enabled(0x1)
2021-08-26 11:21:19.491 5505-8333/? E/EXYNOS_VIDEO_DECCONTROL: [0xeaaa5800][Exynos_OMX_FreeBuffer] Buffer can't be freed because this(0xeaa36680) is already in component
2021-08-26 11:21:19.491 5505-8333/? E/EXYNOS_VIDEO_DECCONTROL: [0xeaaa5800][Exynos_OMX_FreeBuffer] output port : invalid state : comp state(0x3), port state(0x2), enabled(0x1)
2021-08-26 11:21:19.491 5505-8333/? E/EXYNOS_VIDEO_DECCONTROL: [0xeaaa5800][Exynos_OMX_FreeBuffer] Buffer can't be freed because this(0xeaa36680) is already in component
2021-08-26 11:21:19.491 5505-8333/? E/EXYNOS_VIDEO_DECCONTROL: [0xeaaa5800][Exynos_OMX_FreeBuffer] output port : invalid state : comp state(0x3), port state(0x2), enabled(0x1)
2021-08-26 11:21:19.492 5732-6426/com.google.android.exoplayer2.demo I/ACodec: [OMX.Exynos.hevc.dec] Now handling output port settings change
2021-08-26 11:21:19.493 5505-6439/? W/libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
2021-08-26 11:21:19.493 5505-6427/? I/EXYNOS_BASE_PORT: [0xeaaa5800][Exynos_OMX_PortDisableProcess] Disable output Port
```

**Comment by janakasud** [comment] 2021-08-26 09:20
how can we "logged the size of each sample being output by FragmentedMp4Extractor, as well as whether it thinks it's a key frame or not." ?

**Comment by icbaker** [comment] 2021-08-26 09:35
> how can we "logged the size of each sample being output by FragmentedMp4Extractor, as well as whether it thinks it's a key frame or not." ?

The size & flags for each sample are available here:
https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/FragmentedMp4Extractor.java#L1417

A sample is a key frame if `flags & C.BUFFER_FLAG_KEY_FRAME != 0`.

**Comment by icbaker** [comment] 2021-08-27 12:13
Thanks for the new content over email. I see the same symptoms as before with both the DASH and HLS streams provided:
* On a OnePlus AC2003 using `OMX.qcom.video.decoder.hevc`: Decoder artefacts when joining the livestream and also when switching tracks 
* On a Pixel 5 using `c2.qti.hevc.decoder` playback fails with decoder errors.
  * Hacking the demo app to ignore this decoder forces it to use `c2.android.hevc.decoder` and then it seems playback succeeds but pixelation is still observed when switching tracks (but afaict, not when joining the livestream).

Looking at this again I realised I made a big mistake when adding the [logging described above](https://github.com/google/ExoPlayer/issues/9094#issuecomment-879758915) to look at the size of a sample and whether it's a key frame. I added the logging to `FragmentedMp4Extractor` but I **didn't** filter by track type, so the logs ended up being a random interleaving of audio and video samples. And audio samples are small and also all key frames, which led me down the wrong path. Fixing this to only log video samples matches up with what you said in the email (key frames are inserted every 50 frames).

I think this part of what I said is still true & useful:
> The symptoms (green blocks when starting playback, and pixellation when switching tracks - both manually in the middle of a segment and automatically on segment boundaries) suggests that data is being incorrectly fed into the decoder.

But I've not found any evidence to suggest that this invalid data is due to ExoPlayer identifying samples as I-frames that aren't.

**Comment by icbaker** [comment] 2021-08-27 12:52
When using the `c2.android.hevc.decoder` I see the following logging when switching tracks sometimes. It may be relevant, but doesn't seem to always appear, and doesn't always correlate with pixelation (sometimes the logging appears with no pixelation, sometimes neither, sometimes both):

```
08-27 13:32:55.553  1046  1374 30158 D C2SoftHevcDec: error in getVuiParams: 0x3df
08-27 13:32:55.553  1046  1374 30158 D C2SoftHevcDec: error in getVuiParams: 0x3df
08-27 13:32:55.553  1046  1374 30158 D C2SoftHevcDec: Bytes consumed is zero. Ignoring remaining bytes
```

I think `0x3df` resolves to `IHEVCD_VUI_PARAMS_NOT_FOUND`: 
* https://cs.android.com/android/platform/superproject/+/master:frameworks/av/media/codec2/components/hevc/C2SoftHevcDec.cpp;l=585;drc=f01aba98613df50aaf0005582510dfd61993793c
* https://cs.android.com/android/platform/superproject/+/master:external/libhevc/decoder/ihevcd_error.h;l=124;drc=master

**Comment by icbaker** [comment] 2021-08-27 14:12
FWIW I don't see the same `error in getVuiParams` when playing a known-good HEVC DASH stream with `c2.android.hevc.decoder` (Demo app's "Clear DASH -> HD (MP4, H265)").

**Comment by icbaker** [comment] 2021-08-27 15:06
I remain fairly convinced that the source of these decoder artefacts is related to your media. We haven't received similar reports from any other content providers - so it's either that your media is configured in a valid, but esoteric, way that's incompatible with ExoPlayer or your media is invalid.

If you want to dig further into this I suggest you compare what info is being passed to SampleQueue (the format(), sampleData() and sampleMetadata() methods) when switching tracks both while playing the problematic media and the known-good Demo app's "Clear DASH -> HD (MP4, H265)" sample.

If you find that the media is valid please provide full details of specifically what ExoPlayer is unable to handle (simply saying "it plays in VLC and is therefore valid" is, as explained above, not enough).

**Comment by giladna** [comment] 2021-08-30 05:00
@icbaker  Thanks for taking the time for investigating and explaining your findings.

I will take your suggestion and will try to do the comparison you have suggested.

10x

Gilad.

**Comment by giladna** [comment] 2021-08-31 11:29
@icbaker 

Regarding the  c2.android.* decoder.

Could you tell why this is happening there and how to workaround this without hacking the code? should we open issue for Android Platform?

If I apply the below code then I have the playback working (though audio is not playing the c2.android audio decoder seems  not to be working on my Pixel1/android 10 and there is only one decoder coming from MediaCodecUtil  for "audio/mp4a-latm" on this device

```
renderersFactory.setMediaCodecSelector((mimeType, requiresSecureDecoder, requiresTunnelingDecoder) -> {
            List<MediaCodecInfo> codecsList =  new ArrayList<>(MediaCodecUtil.getDecoderInfos(mimeType, requiresSecureDecoder, requiresTunnelingDecoder));
            ListIterator<MediaCodecInfo> iter = codecsList.listIterator();
            while(iter.hasNext()){
                String name = iter.next().name;
                if(name.startsWith("OMX.google") || name.startsWith("c2.android")) {
                    iter.remove();
                }
            }
            return  codecsList;
        });
```

**Comment by icbaker** [comment] 2021-09-01 16:26
I've done a bit more digging - I think the sample at the start of each of your segments (which contains an IDR frame) is missing the VPS/SPS/PPS NAL units. This data must either prefix **every** IDR frame (in the same sample) or be provided as initialization data (e.g. in an MP4 `hvcC` box). Your stream doesn't seem to provide this data in an initialization box, so we're expecting to see it prefix each IDR frame. It does seem to prefix the other two IDR frames in each segment.

This means that when a track switch happens on a segment boundary the first IDR frame of the new stream is passed to the decoder **without** the appropriate VPS/SPS/PPS data, and therefore the decoder either crashes or I would guess tries to re-use the 'old' VPS/SPS/PPS from the previous stream, which isn't compatible (leading to artefacts). This explains why steady-state playback (with no track switches) doesn't produce artefacts, because even though the VPS/SPS/PPS data is missing on every 3rd IDR frame, if the decoder is re-using the data from the previous IDR frame it's still 'correct'.

Concretely, I observed the following NAL unit types with each of the 3 key frames in each segment (VPS is 32, SPS is 33 and PPS is 34). Every segment had the same pattern, this is just from one chosen arbitrarily:

| Timestamp  | NAL units |
| ------------- | ------------- |
| 23766040000  | 35, 39, 20  |
| 23768040000  | 35, 32, 33, 34, 39, 39, 20  |
| 23770040000 | 35, 32, 33, 34, 39, 39, 20 |

**Closed as completed** 2021-10-18 11:13 UTC
Labels: bad media
