### ISSUE TITLE
Problems Side Loading Subtitles in ExoPlayer v2.0.1

### ISSUE THREAD

**Issue by mnarmar** [google/ExoPlayer#1882] opened 2016-09-30 21:54 UTC
We use SmoothStreaming / Playready and depend on Side Loading independent TTML Subtitles.

Found two problems trying to Side Load TTML Subtitles using MergingMediaSource containing SingleSampleMediaSource and SsMediaSource:

1-
DefaultTrackSelector.selectTextTrack correctly receives the TTML track, but it never gets it selected.
Hint : adjusting the score check in a DefaultTrackSelector subclass to be  {if (trackScore >= selectedTrackScore) ... } , Solved it and got it selected.

2 -
Received crash:
    Caused by: java.lang.NullPointerException: Attempt to get length of null array
    at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:272)

Examining this NullPointerException crash , we found that it is checking length of SourceLoadable.sampleData before it ever gets initialized or assigned.

**Comment by ojw28** [comment] 2016-10-03 11:53
1 - It's working as intended that the track isn't selected by default. If you want this behaviour, you should specify `C.SELECTION_FLAG_DEFAULT` as the `selectionFlags` argument when creating the format for the text track. `DefaultTrackSelector` also exposes methods for selecting the track.

2 - This is a bug. We'll push a fix shortly.

**Comment by mnarmar** [comment] 2016-10-03 15:40
1 - Thanks providing what is missed
2 - Waiting for the fix

**Comment by ojw28** [comment] 2016-10-03 16:45
A fix has been pushed to `dev-v2`. Thanks!

**Closed as completed by ojw28** 2016-10-03 16:45 UTC
Labels: bug
