### ISSUE TITLE
NullPointerException in TextRenderer

### ISSUE THREAD

**Issue by jonfhancock** [google/ExoPlayer#2081] opened 2016-11-17 17:44 UTC
We are getting an NPE on an HLS video with 608 captions. 

The stack trace is: 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.text.SubtitleOutputBuffer.getEventTimeCount()' on a null object reference
at com.google.android.exoplayer2.text.TextRenderer.getNextEventTime(TextRenderer.java:252)
at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:165)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

The method `getNextEventTime()` should have a null check on subtitle before attempting to call `getEventTimeCount()`.  I am not sure what it should return if subtitle is null.  Perhaps `C.INDEX_UNSET`?

**Comment by ojw28** [comment] 2016-11-17 18:50
Thanks for the report. I think the problem is more that `nextSubtitleEventIndex` needs resetting to `INDEX_UNSET` in a few places.

**Comment by ojw28** [comment] 2016-11-18 12:58
This is fixed in `dev-v2`.

**Closed as completed by ojw28** 2016-11-18 12:58 UTC
Labels: bug
