### ISSUE TITLE
Some nonlinear ads causing the player to stall

### ISSUE THREAD

**Issue by BucherTomas** [google/ExoPlayer#8352] opened 2020-12-15 15:31 UTC
While we are aware that mobile IMA SDK does not support nonlinear ads, we are experiencing issues with playback, if an ad server returns such ads. Observed with ExoPlayer 2.11.8 both in ExoPlayer demo app and our own app.

These steps can be used to reproduce the issue:
_1. Load the following VMAP https://devs.origin.cdn.cra.cz/ima/stuck/vmap.xml.
2. Skip the preroll or let it finish and seek immediately after the first midroll adbreak.
3. Now, most likely the skip button will not count down to 0 (keeps displaying 5) and the player becomes stuck at the end of the midroll, the last event is onAdEvent: AD_BUFFERING. This happens every time on multiple devices, so should be easy to reproduce and to get your own fresh log._

It works fine, if these nonlinear adbreaks are omitted from the VMAP, but this simulated test ad suite is structurally almost an exact copy of what our player receives in production environment from third party ad services of our customers and the content these services provide is out of our hands.

Please, take a look, but might be primarily an issue with IMA SDK itself judging by the skip button behavior in midroll.

**Comment by krocard** [comment] 2020-12-16 10:02
This might be a duplicate of #8349.

**Comment by BucherTomas** [comment] 2020-12-17 09:53
That ticket states that it was caused by regression in 2.12.0, but we are still using 2.11.8. Also the same scenario works fine, if I remove those nonlinear adbreaks from the VMAP, so our issue does not seem to be tied exclusively to seeking. This is  supported by the fact that if I don't seek and the player reaches the first midroll normally, it stalls anyway,

Therefore it appears that some further examination might be needed.

**Comment by tonihei** [comment] 2020-12-17 16:51
@andrewlewis  Could you take a look at this? Sounds like we should handle this more gracefully.

**Comment by andrewlewis** [comment] 2021-01-05 10:31
As you've already noted, non-linear ads aren't supported. I agree it would be good to handle this more gracefully. The difficulty is that there doesn't seem to be a positive signal from the IMA SDK that the cue points for these non-linear ads won't load. I have filed a feature request to be able to omit non-linear ad cue points [internal: b/176789309].

On `dev-v2` it's possible that ad loading will time out making this failure mode slightly better. I will close this for now given that the use case is officially not supported. Hopefully the ad server provides a way to configure the ad tag not to include non-linear ads, but failing that it may be possible to do a workaround where you load the ad tag yourself, parse it and remove the non-linear ads before passing the ads response directly.

**Closed as completed by andrewlewis** 2021-01-05 10:31 UTC
Labels: wont fix: infeasible
