### ISSUE TITLE
Subtitle Tracks in mp4 files not Rendering in ExoPlayer Demo

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#635] opened 2015-07-19 22:05 UTC
I am creating mp4 with soft-subtitles like this:

```
ffmpeg -i dizzy.mp4 -sub_charenc CP1252 -i subtitle.srt -map 0:v -map 0:a -c copy -map 1 -c:s:0 mov_text -metadata:s:s:0 language=ger output.mp4
```

In VLC Player i can just show the subtitle Track "Track 1 - [GER]" but in Exoplayer no Subtitles are showing up. What do i have to do in the demo-player to see the Subtitles?

**Comment by ened** [comment] 2015-07-21 03:14
Maybe because https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java does not include the SubripParser?

**Comment by Schizo** [comment] 2015-07-21 03:43
Isn't the Trackrenderer handling it? How can i add it?

**Comment by ened** [comment] 2015-07-21 08:39
Could you try instantiating a new SubripParser in here: 

```
    TrackRenderer textRenderer = new TextTrackRenderer(sampleSource, player,
        player.getMainHandler().getLooper(), new Tx3gParser());
```

(right now its Tx3g).

**Comment by ojw28** [comment] 2015-07-21 16:23
When you use ffmpeg like that, what's the format of the subtitle in the generated output file?

**Comment by Schizo** [comment] 2015-07-22 04:11
Source:https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/subtitle_options
for **MKV** containers: copy, ass, srt, ssa
for **MP4** containers: copy, mov_text
for **MOV** containers: copy, mov_text

So yes, actually the format is changed to MOV

**Comment by ojw28** [comment] 2015-07-22 08:11
mov_text is tx3g apparently, which should work. Please provide a sample file that displays captions in VLC and not in ExoPlayer's demo app. Thanks.

**Comment by Schizo** [comment] 2015-07-22 16:21
File attached and the srt file as well.

[output.mp4 | uploaded via ZenHub](https://files.zenhub.io/55afc2ec0757ff951b9aa831)

[subtitle.srt | uploaded via ZenHub](https://files.zenhub.io/55afc3050757ff951b9aa833)

**Comment by ojw28** [comment] 2015-07-22 18:52
Thanks! There are multiple small fixes needed to get this working. I'll try and merge them tomorrow.

Note that once the changes are merged, the player will report a duration of 2:22 for the test video linked above, despite the fact that audio and video only last for around 0:24. Playback will continue beyond 0:24, and the subtitle at 2:20 will be rendered correctly before the player transitions to the ended state. This is working as intended, and occurs because you've merged a subtitle track that's longer than the video. In a real sample I would expect the subtitle track to be more or the same duration as the video, and so this wouldn't occur.

**Comment by Schizo** [comment] 2015-07-22 21:48
Thanks for looking into that so quickly! 
Yes  it makes sense that the file is 2:22, as it is considered as a Track like audio/video in ffmpeg as well.

**Comment by ojw28** [comment] 2015-07-23 12:48
This is fixed now. Note that once you enable the text track, it wont display any text that would have been displayed prior to the track being enabled (and should still be visible). You'll need to seek or wait for the next piece of text to appear. In practice this isn't a real problem, since each caption is normally only visible for a short period.

**Closed by ojw28** 2015-07-23 12:48 UTC
Labels: need more info
