### ISSUE TITLE
Please publish to MavenCentral or maven.google.com

### ISSUE THREAD

**Issue by ZacSweers** [google/ExoPlayer#8382] opened 2020-12-20 23:24 UTC
(Couldn't comment on #28)

JCenter has a long history of artifact integrity issues and we try to avoid it at all costs. I recognize that maven central's publishing process is sometimes considered more tedious, but this signing/verification process is part of why it's preferred.

https://blog.autsoft.hu/a-confusing-dependency/
https://twitter.com/jakewharton/status/1073102730443526144?lang=en

**Comment by ZacSweers** [comment] 2020-12-20 23:25
Alternatively, publish to maven.google.com

**Comment by ojw28** [comment] 2020-12-20 23:32
Duplicate of https://github.com/google/ExoPlayer/issues/5246

**Closed as completed by ojw28** 2020-12-20 23:32 UTC
Labels: enhancement
