### ISSUE TITLE
Some stream returns error (HLS)

### ISSUE THREAD

**Issue by ppamorim** [google/ExoPlayer#708] opened 2015-08-12 20:10 UTC
Hi Exo team.
I'm developing an streaming app and some streams returns IllegalStateException, like this:

    08-12 17:06:55.981  12502-16493/com.doge_hides_the_name E/ACodec﹕ [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
    08-12 17:06:56.141  12502-16493/com.doge_hides_the_name E/ACodec﹕ [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
    08-12 17:06:56.141  12502-16492/com.doge_hides_the_name E/MediaCodec﹕ Codec reported an error. (omx error 0x80001009, internalError -2147483648)
    08-12 17:06:56.151  12502-16483/com.doge_hides_the_name E/ExoPlayerImplInternal﹕ Internal runtime error.
       java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:832)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:499)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:146)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

I handled this error at my source, can you fix it?

**Comment by crossle** [comment] 2015-08-15 10:13
same problem.
```
              OMXClient  I  Using client-side OMX mux.
                         I  Using client-side OMX mux.
            EventLogger  D  decoderInitialized [3, OMX.TI.DUCATI1.VIDEO.DECODER]
                         D  decoderInitialized [3, OMX.google.aac.decoder]
               SoftAAC2  I  Reconfiguring decoder: 0->44100 Hz, 0->2 channels
                 ACodec  E  [OMX.TI.DUCATI1.VIDEO.DECODER] ERROR(0x80001020)
             MediaCodec  E  Codec reported an error. (omx error 0x80001020, internalError -2147483648)
  ExoPlayerImplInternal  E  Internal runtime error.
                         E  java.lang.IllegalStateException
                         E      at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                         E      at com.google.android.exoplayer.MediaCodecTrackRenderer.b(MediaCodecTrackRenderer.java:772)
                         E      at com.google.android.exoplayer.MediaCodecTrackRenderer.a(MediaCodecTrackRenderer.java:450)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.j(ExoPlayerImplInternal.java:425)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:207)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:137)
                         E      at android.os.HandlerThread.run(HandlerThread.java:61)
                         E      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    VideoPlayerFragment  E  VideoPlayerFragment
                         E  com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:240)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:137)
                         E      at android.os.HandlerThread.run(HandlerThread.java:61)
                         E      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                         E  Caused by: java.lang.IllegalStateException
                         E      at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                         E      at com.google.android.exoplayer.MediaCodecTrackRenderer.b(MediaCodecTrackRenderer.java:772)
                         E      at com.google.android.exoplayer.MediaCodecTrackRenderer.a(MediaCodecTrackRenderer.java:450)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.j(ExoPlayerImplInternal.java:425)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:207)
                         E      ... 4 more
            EventLogger  E  playerFailed [3]
                         E  com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:240)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:137)
                         E      at android.os.HandlerThread.run(HandlerThread.java:61)
                         E      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                         E  Caused by: java.lang.IllegalStateException
                         E      at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                         E      at com.google.android.exoplayer.MediaCodecTrackRenderer.b(MediaCodecTrackRenderer.java:772)
                         E      at com.google.android.exoplayer.MediaCodecTrackRenderer.a(MediaCodecTrackRenderer.java:450)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.j(ExoPlayerImplInternal.java:425)
                         E      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:207)
                         E      ... 4 more
```

**Comment by crossle** [comment] 2015-08-16 06:55
https://github.com/google/ExoPlayer/issues/709

**Comment by Arqu** [comment] 2015-08-16 19:44
I don't know if this applies to you guts, but this issue often happens if you have more than one player (or anything else) trying to access the codec at once. See if you use another media app or multiple instances of exo or maybe you just don't release/prepare the player correctly.

**Comment by ppamorim** [comment] 2015-08-19 11:20
@Arqu It's not a problem with the player state...

**Comment by ojw28** [comment] 2015-08-19 19:38
Please could you provide a link to an affected stream?

**Comment by ojw28** [comment] 2015-09-01 13:42
Not enough information. Closing.

**Closed by ojw28** 2015-09-01 13:42 UTC
Labels: need more info

**Comment by ppamorim** [comment] 2015-09-01 20:05
Well done! ¬¬

**Comment by ojw28** [comment] 2015-09-01 20:22
There's a request for a link to an effected stream 13 days ago above with no response. We can't debug issues that we cannot reproduce.

**Comment by ppamorim** [comment] 2015-09-03 13:13
@ojw28, would you test my app to see what's happening?

https://play.google.com/store/apps/details?id=com.camerite

**Comment by ojw28** [comment] 2015-09-03 14:00
It's not feasible for us to debug an application for which we do not have source code. Even if we do have source code, it is not an efficient use of time for us to debug third party applications, because it makes it difficult to separate out issues in application code v.s. issues in ExoPlayer.

If HLS playback is broken in ExoPlayer, it should be trivial for you to provide a link to a stream that is broken. If your streams are authenticated, it should be possible for you to expose a non-authenticated test stream that reproduces the issue. If the problem doesn't occur in the demo app, then it's a problem with your application code.

**Comment by sough** [comment] 2017-03-28 08:11
hello, i have link on mp4 file with same error, but this link lives only 24 hour, if you are interested, i can provide one
