### ISSUE TITLE
Exoplayer plays new Playlist from the beginning instead of provided position

### ISSUE THREAD

**Issue by mathemandy** [google/ExoPlayer#4375] opened 2018-06-13 17:51 UTC
### Issue description
I Implemented DynamicConcatenatingMediaSource in my project and have reached a bug where in the method ```exoPlayer.prepare(source);``` the songs starts  to play at the beginning of the playlist before ```   exoPlayer.seekTo(currentPosition, C.TIME_UNSET);``` is callled. 
So this causes a UI bug on my app.  

For ac already cached song, a user can hear the first song playing before moving to the next song.
### I Play a song from here and compare if its a new list, i reinitialise exoplayer.

      private BroadcastReceiver playNewAudio = new BroadcastReceiver() {
        @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
        @Override
        public void onReceive(Context context, Intent intent) {

            if (exoPlayer != null) {
                try {
                    if (!exoPlayer.getPlayWhenReady()) {
                        resumeMedia();
                        sendBroadcast(Dispatcher.Broadcast.NEW_TRACK_PLAYING, "");
                        return;
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            //Get the new media index form SharedPreferences
            if (songManager.currentPosition != -1 && songManager.currentPosition < songManager.getCurrentPlayList().size()) {
                //index is in a valid range
                songManager.activeTrack = songManager.getCurrentPlayList().get(songManager.currentPosition);
				//sendBroadcast(Dispatcher.Broadcast.NEW_TRACK_PLAYING,"");
                if (songManager.getPreviousPlaylist().equals(songManager.currentPlayList))

                    seekToCurrent(songManager.currentPosition);

                else
                    initExo();
            } else {
                stopSelf();
            }

            /*stopMedia();*/
            if (exoPlayer != null) {
                try {
                    exoPlayer.setPlayWhenReady(shouldAutoPlay);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                initExo();
            }
            /*initMediaPlayer();*/
            updateMetaData();
            buildNotification(PlaybackStatus.PLAYING);

        }
    };

### Here is where i initialise Exo

      private void initExo() {
        songManager = SongManager.getInstance();
        int currentPosition = songManager.getCurrentPosition();
        window = new Timeline.Window();
        defaultBandwidthMeter = new DefaultBandwidthMeter();
        LoadControl loadControl = new DefaultLoadControl();

        trackSelectionFactory = new AdaptiveTrackSelection.Factory(defaultBandwidthMeter);

        trackSelector = new DefaultTrackSelector(trackSelectionFactory);

        boolean newExo = exoPlayer == null;

        if (newExo)
            exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);

        exoPlayer.addListener(this);
        source = initMediaSource();
        exoPlayer.prepare(source);
        exoPlayer.seekTo(currentPosition, C.TIME_UNSET);
        exoPlayer.setPlayWhenReady(true);

    }

### Then the call to initMediaSource

        private DynamicConcatenatingMediaSource initMediaSource() {
        clearSource();
        DynamicConcatenatingMediaSource mediaSource = new DynamicConcatenatingMediaSource();
        for (Track track : songManager.getCurrentPlayList()) {
            if (track != null && !track.getSource().isEmpty()) {
                HlsMediaSource source = new
                        HlsMediaSource(Uri.parse(track.getSource()), cacheDataSourceFactory(), 5,   null, null);
                mediaSource.addMediaSource(source);
            } else {
                Log.e("Bad_Track", track.toString());
            }
        }
        songManager.setPreviousPlaylist(songManager.currentPlayList);
        return mediaSource;
    }

This works fine in the same Playlist. 
I was able to find this issue as i added Breakpoints on that line and notices the music started playing as soon as i left the ```onPrepared``` method.

### Link to test content
http://res.cloudinary.com/mathemandy/image/upload/v1528912175/videotogif_2018.06.13_18.24.51_jcazq8.gif.

### Version of ExoPlayer being used
 implementation 'com.google.android.exoplayer:exoplayer:2.7.2'

### Device(s) and version(s) of Android being used
Nougat 7.0 Infinix Zero 45 Plus

**Comment by AquilesCanta** [comment] 2018-06-13 18:13
Have you tried calling `seekTo` before calling `prepare`?

**Comment by mathemandy** [comment] 2018-06-13 20:49
I just did that - The inverse is the result.
It seeks to the selected song and returns immediately to the first song on the list after ```prepare```

**Comment by ojw28** [comment] 2018-06-14 04:10
I think the problem is with `initExo()`. In particular, if you have an existing player instance that's currently playing, then the call to `exoPlayer.prepare` will cause playback of the new source from `time=0`. This may happen so quickly that you hear the audio play for a brief period before the subsequent `exoPlayer.seekTo` call is processed to seek to the desired position.

I think you can fix it by modifying your `initExo()` method to call `setPlayWhenReady(false)` before preparing the player with the new source, as shown below. This will prevent playback until after the `exoPlayer.seekTo` call is processed:

```
source = initMediaSource();
exoPlayer.setPlayWhenReady(false);      // <-- Newly inserted line
exoPlayer.prepare(source);
exoPlayer.seekTo(currentPosition, C.TIME_UNSET);
exoPlayer.setPlayWhenReady(true);
```

**Comment by mathemandy** [comment] 2018-06-14 08:29
@ojw28  The initial Problem still persists  after trying your fix

**Comment by ojw28** [comment] 2018-06-14 22:55
In that case I think we need clearer reproduction steps. In particular, rather than providing snippets of code (which aren't that helpful, since it's unclear when each piece of code is invoked), please provide the sequence of calls made on the ExoPlayer instance that reproduce the problem.

I can't really see how this would happen unless you have a bug in your code that's causing `playWhenReady` to be true between when you prepare the player, and when you seek to the desired position.

**Comment by ojw28** [comment] 2018-07-06 21:14
Closing due to lack of clear reproduction steps.

**Closed as completed** 2018-07-06 21:14 UTC
Labels: question, need more info

**Comment by OfekRegev** [comment] 2018-09-11 12:19
I've been experiencing the same issue. When I'm preparing a DynamicConcatenatingMediaSource using player.prepare(concatenatingMediaSource) and then calling player.seekTo(index,0) the initial index set always to 0 and only then skipping to the provided index. Since my media source is performing some validations to the stream link the first media source always start validating and only after it finishes the seeked media source starts to validate.

**Comment by ojw28** [comment] 2018-09-11 12:21
We cannot look at this issue without proper reproduction steps. Please provide some (preferably in the form of a simple demo project) if you want the issue to be reopened.
