### ISSUE TITLE
Add track exclusion logic to exclude tracks from multi-key manifest based on DRM level in case of issue

### ISSUE THREAD

**Issue by laruedavid** [google/ExoPlayer#10641] opened 2022-09-21 15:51 UTC
### Use case description 
Multi-key DRM manifest are used to apply a different level of DRM protection depending on the quality level of the representation.
In my tests I have 240p and 540p tracks with L3 (software) DRM level and a 720p and 1080p tracks with L1 (hardware) DRM level.
On some devices I encounter an issue when the device switch to a track protected with L1 DRM Level.
The device starts with low quality tracks due to ABR rules and the video works fine, but after a few seconds of video playback the buffer increase and the device try to play a track with higher quality and ExoPlayer throw a ExoPlaybackException.

I able to reproduce this issue with an HTC M8. The Widevine L1 is not revoked and I managed to get the license, but when the license has an HDCP restriction, the device cannot play the content even though it says it supports HDCP 2.2.

There are a lot of issues with DRM and we could expect to improve the user experience overall.

### Proposed solution
Add track exclusion logic to exclude tracks that the player cannot play.

### Alternatives considered
It's possible to implement a fallback behavior to play a fully protected L3 asset on DRM error, but exclusion logic on main assets could be more transparent and easier to implement.

**Comment by icbaker** [comment] 2022-09-21 15:59
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/4825

**Closed as completed** 2022-09-21 15:59 UTC
Labels: enhancement

**Comment by laruedavid** [comment] 2022-09-21 16:31
@icbaker it looks this is not excatly the same issue. In their case they tried to play a manifest with multi-key receiving only the first key.
In my case I have both SW and HW keys and my device has a L1 HDCP 2.2 configuration.
I'm not able to filter tracks regarding the licence  requierements because the device match all these requierements but I encounter an issue during playback may be caused by an internal error.

**Comment by icbaker** [comment] 2022-09-21 16:40
Does `OnKeyStatusChangeListener` report that the device is able to play the stream that subsequently fails? I would expect that to be aware the stream is unplayable due to HDCP restrictions, and therefore the track would not be selected for playback if #4825 were implemented - so I think it would solve your use-case too?

**Comment by laruedavid** [comment] 2022-09-22 06:40
@icbaker I added a OnKeyStatusChangeListener on the ExoMediaDrm and we had the following result

E/setOnKeyStatusChangeListener: onKeyStatusChange
E/setOnKeyStatusChangeListener: statusCode 0 -> STATUS_USABLE
E/setOnKeyStatusChangeListener: statusCode 0 -> STATUS_USABLE
E/setOnKeyStatusChangeListener: hasNewUsableKey true

Regarding this result it looks like both keys should work but this is not the case for the second one
