### ISSUE TITLE
Is there way to disable .m3u8 hls video track completely to save bandwidth and listen only audio track ?

### ISSUE THREAD

**Issue by lemontmoon** [google/ExoPlayer#10374] opened 2022-06-23 13:40 UTC
Hi,

I am looking for solution , how to disable VIDEO TRACK completely,, simply set it to null to disable video track data downloading.

I just need to listen only audio to save bandwidth when I am on my bike ride. I was trying to setrendererdisabled but bandwidth doesnt change, its same as with rendererenabled. 

Is there any solution for that for m3u8 hls playback ?

Thanks !!! :)

**Comment by icbaker** [comment] 2022-06-23 17:48
This is a duplicate of https://github.com/google/ExoPlayer/issues/9282 (it's specific to HLS, if you disable the video track in a DASH stream the player won't download video segments).

**Closed as completed** 2022-06-23 17:48 UTC
Labels: duplicate

**Comment by lemontmoon** [comment] 2022-06-23 17:51
disable videotrack, do you mean setrenderer disabled ? or do i need set
null track somehow ? thx

**Comment by icbaker** [comment] 2022-06-23 18:09
You can disable all video tracks by calling [`TrackSelectionParameters.Builder#setTrackTypeDisabled(C.TRACK_TYPE_VIDEO, true)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/TrackSelectionParameters.Builder.html#setTrackTypeDisabled(@com.google.android.exoplayer2.C.TrackTypeint,boolean)).

Disabling the video renderer using [`DefaultTrackSelector.Parameters.Builder#setRendererDisabled(int, boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.Parameters.Builder.html#setRendererDisabled(int,boolean)) will have roughly the same effect: video segments will still be downloaded in HLS, but not in DASH.

**Comment by lemontmoon** [comment] 2022-06-23 18:31
thanks,, its clear for me now,, we have been disabling hls tracks
previously using flussonic by adding trackselection parameter to url,,
maybe they are coverting this from dash source
