### ISSUE TITLE
Crash: NPE in HlsChunkSource.onPlaylistError

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#8323] opened 2020-12-07 20:57 UTC
I'm seeing small amount of crashes with callstack:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.Uri.equals(java.lang.Object)' on a null object reference
       at com.google.android.exoplayer2.source.hls.HlsChunkSource.onPlaylistError(HlsChunkSource.java:406)
       at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onPlaylistError(HlsSampleStreamWrapper.java:536)
       at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.onPlaylistError(HlsMediaPeriod.java:455)
       at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.notifyPlaylistError(DefaultHlsPlaylistTracker.java:387)
       at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.access$800(DefaultHlsPlaylistTracker.java:46)
       at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadError(DefaultHlsPlaylistTracker.java:600)
       at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadError(DefaultHlsPlaylistTracker.java:462)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:492)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

It does not look like issue with stream itself, since all the time when this crash happens stream is being played quite a long time:
```
12:54:30 GMT+0300 main|D] EventLogger: timeline [eventTime=5.49, mediaPos=6.01, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:54:30 GMT+0300 main|D] EventLogger:   period [?]
12:54:30 GMT+0300 main|D] EventLogger:   window [24.02, true, true]
12:54:30 GMT+0300 main|D] EventLogger: ]
12:54:31 GMT+0300 main|D] EventLogger: videoEnabled [eventTime=6.72, mediaPos=6.01, window=0, period=0]
12:54:31 GMT+0300 main|D] EventLogger: audioEnabled [eventTime=6.73, mediaPos=6.01, window=0, period=0]
12:54:31 GMT+0300 main|D] EventLogger: tracks [eventTime=6.73, mediaPos=6.01, window=0, period=0
12:54:31 GMT+0300 main|D] EventLogger:   MediaCodecVideoRenderer [
12:54:31 GMT+0300 main|D] EventLogger:     Group:0, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=6310000, codecs=avc1.4D402A, res=1920x1080, fps=59.94, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Metadata [
12:54:31 GMT+0300 main|D] EventLogger:       HlsTrackMetadataEntry
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:   ]
12:54:31 GMT+0300 main|D] EventLogger:   MediaCodecAudioRenderer [
12:54:31 GMT+0300 main|D] EventLogger:     Group:0, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=24000, language=en, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:   ]
12:54:31 GMT+0300 main|D] EventLogger:   FfmpegAudioRenderer []
12:54:31 GMT+0300 main|D] EventLogger:   TextRenderer [
12:54:31 GMT+0300 main|D] EventLogger:     Group:0, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Group:1, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [ ] Track:0, id=subs:und t1, mimeType=text/vtt, language=und, label=und t1, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Group:2, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [ ] Track:0, id=subs:und t2, mimeType=text/vtt, language=und, label=und t2, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Group:3, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [ ] Track:0, id=subs:und t3, mimeType=text/vtt, language=und, label=und t3, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Group:4, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [ ] Track:0, id=subs:und t4, mimeType=text/vtt, language=und, label=und t4, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:   ]
12:54:31 GMT+0300 main|D] EventLogger:   MetadataRenderer [
12:54:31 GMT+0300 main|D] EventLogger:     Group:0, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [X] Track:0, id=null, mimeType=application/id3, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:   ]
12:54:31 GMT+0300 main|D] EventLogger:   CameraMotionRenderer []
12:54:31 GMT+0300 main|D] EventLogger: ]
12:54:31 GMT+0300 main|D] EventLogger: downstreamFormat [eventTime=6.80, mediaPos=6.01, window=0, period=0, id=0, mimeType=null, bitrate=6310000, codecs=avc1.4d002a,mp4a.40.2, res=1920x1080, fps=59.94]
12:54:31 GMT+0300 main|D] EventLogger: videoDecoderInitialized [eventTime=6.88, mediaPos=6.01, window=0, period=0, OMX.MTK.VIDEO.DECODER.AVC]
12:54:31 GMT+0300 main|D] EventLogger: videoInputFormat [eventTime=6.88, mediaPos=6.01, window=0, period=0, id=0, mimeType=video/avc, bitrate=6310000, codecs=avc1.4D402A, res=1920x1080, fps=59.94]
12:54:31 GMT+0300 main|D] EventLogger: audioDecoderInitialized [eventTime=6.94, mediaPos=6.01, window=0, period=0, OMX.google.aac.decoder]
12:54:31 GMT+0300 main|D] EventLogger: audioInputFormat [eventTime=6.94, mediaPos=6.01, window=0, period=0, id=1/15, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=24000, language=en]
12:54:31 GMT+0300 main|D] EventLogger: tracks [eventTime=6.97, mediaPos=6.01, window=0, period=0
12:54:31 GMT+0300 main|D] EventLogger:   MediaCodecVideoRenderer [
12:54:31 GMT+0300 main|D] EventLogger:     Group:0, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=6310000, codecs=avc1.4D402A, res=1920x1080, fps=59.94, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Metadata [
12:54:31 GMT+0300 main|D] EventLogger:       HlsTrackMetadataEntry
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:   ]
12:54:31 GMT+0300 main|D] EventLogger:   MediaCodecAudioRenderer [
12:54:31 GMT+0300 main|D] EventLogger:     Group:0, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=24000, language=en, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:   ]
12:54:31 GMT+0300 main|D] EventLogger:   FfmpegAudioRenderer []
12:54:31 GMT+0300 main|D] EventLogger:   TextRenderer [
12:54:31 GMT+0300 main|D] EventLogger:     Group:0, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [X] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Group:1, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [ ] Track:0, id=subs:und t1, mimeType=text/vtt, language=und, label=und t1, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Group:2, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [ ] Track:0, id=subs:und t2, mimeType=text/vtt, language=und, label=und t2, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Group:3, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [ ] Track:0, id=subs:und t3, mimeType=text/vtt, language=und, label=und t3, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:     Group:4, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [ ] Track:0, id=subs:und t4, mimeType=text/vtt, language=und, label=und t4, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:   ]
12:54:31 GMT+0300 main|D] EventLogger:   MetadataRenderer [
12:54:31 GMT+0300 main|D] EventLogger:     Group:0, adaptive_supported=N/A [
12:54:31 GMT+0300 main|D] EventLogger:       [X] Track:0, id=null, mimeType=application/id3, supported=YES
12:54:31 GMT+0300 main|D] EventLogger:     ]
12:54:31 GMT+0300 main|D] EventLogger:   ]
12:54:31 GMT+0300 main|D] EventLogger:   CameraMotionRenderer []
12:54:31 GMT+0300 main|D] EventLogger: ]
12:54:31 GMT+0300 main|D] EventLogger: audioSessionId [eventTime=7.03, mediaPos=6.01, window=0, period=0, 105]
12:54:31 GMT+0300 main|D] EventLogger: videoSize [eventTime=7.11, mediaPos=6.01, window=0, period=0, 1920, 1080]
12:54:31 GMT+0300 main|D] EventLogger: renderedFirstFrame [eventTime=7.18, mediaPos=6.01, window=0, period=0, Surface(name=null)/@0x4a09d55]
12:54:31 GMT+0300 main|D] EventLogger: state [eventTime=7.18, mediaPos=6.05, window=0, period=0, READY]
12:54:31 GMT+0300 main|D] EventLogger: isPlaying [eventTime=7.19, mediaPos=6.05, window=0, period=0, true]
12:54:31 GMT+0300 main|D] EventLogger: volume [eventTime=7.20, mediaPos=6.05, window=0, period=0, 0.0]
12:54:31 GMT+0300 main|D] EventLogger: volume [eventTime=7.32, mediaPos=6.15, window=0, period=0, 1.0]
12:54:37 GMT+0300 main|D] EventLogger: timeline [eventTime=12.87, mediaPos=-0.30, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:54:37 GMT+0300 main|D] EventLogger:   period [?]
12:54:37 GMT+0300 main|D] EventLogger:   window [24.46, true, true]
12:54:37 GMT+0300 main|D] EventLogger: ]
12:54:44 GMT+0300 main|D] EventLogger: timeline [eventTime=20.11, mediaPos=0.94, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:54:44 GMT+0300 main|D] EventLogger:   period [?]
12:54:44 GMT+0300 main|D] EventLogger:   window [24.02, true, true]
12:54:44 GMT+0300 main|D] EventLogger: ]
12:54:51 GMT+0300 main|D] EventLogger: timeline [eventTime=27.35, mediaPos=2.18, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:54:51 GMT+0300 main|D] EventLogger:   period [?]
12:54:51 GMT+0300 main|D] EventLogger:   window [24.02, true, true]
12:54:51 GMT+0300 main|D] EventLogger: ]
12:54:59 GMT+0300 main|D] EventLogger: timeline [eventTime=34.57, mediaPos=3.41, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:54:59 GMT+0300 main|D] EventLogger:   period [?]
12:54:59 GMT+0300 main|D] EventLogger:   window [24.02, true, true]
12:54:59 GMT+0300 main|D] EventLogger: ]
...
12:57:45 GMT+0300 main|D] EventLogger: timeline [eventTime=201.05, mediaPos=1.89, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
12:57:45 GMT+0300 main|D] EventLogger:   period [?]
12:57:45 GMT+0300 main|D] EventLogger:   window [23.89, true, true]
12:57:45 GMT+0300 main|D] EventLogger: ]
...
13:01:36 GMT+0300 main|D] EventLogger: timeline [eventTime=432.24, mediaPos=2.08, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
13:01:36 GMT+0300 main|D] EventLogger:   period [?]
13:01:36 GMT+0300 main|D] EventLogger:   window [24.02, true, true]
13:01:36 GMT+0300 main|D] EventLogger: ]
...
13:05:28 GMT+0300 main|D] EventLogger: timeline [eventTime=663.81, mediaPos=-0.35, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
13:05:28 GMT+0300 main|D] EventLogger:   period [?]
13:05:28 GMT+0300 main|D] EventLogger:   window [24.02, true, true]
13:05:28 GMT+0300 main|D] EventLogger: ]
13:05:35 GMT+0300 main|D] EventLogger: timeline [eventTime=671.04, mediaPos=0.88, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
13:05:35 GMT+0300 main|D] EventLogger:   period [?]
13:05:35 GMT+0300 main|D] EventLogger:   window [24.02, true, true]
13:05:35 GMT+0300 main|D] EventLogger: ]
13:05:52 GMT+0300 r:Playback|E] UncaughtExceptionHandler: Uncaught exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.Uri.equals(java.lang.Object)' on a null object reference 	at d.e.a.b.x1.t0.o.e(HlsMediaPeriod.java:4) 	at d.e.a.b.x1.t0.u.c.a(DefaultHlsPlaylistTracker.java:2) 	at d.e.a.b.x1.t0.u.c$a.p(DefaultHlsPlaylistTracker.java:14) 	at com.google.android.exoplayer2.upstream.Loader$d.handleMessage(Loader.java:21) 	at android.os.Handler.dispatchMessage(Handler.java:102) 	at android.os.Looper.loop(Looper.java:154) 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

I do not have exact steps or stream itself. According to logs it happens out of the blue.
It looks like some race condition and 

- ExoPlayer: 2.12.1
- Android version: 7,8,9
- Android devices: Amazon AFTMM, Xiaomi Mi TV Stick

**Comment by krocard** [comment] 2020-12-09 13:25
It seems one of the playlistUrl was null.
https://github.com/google/ExoPlayer/blob/be13805ce4e22231ae728d2710a2b8751ee5ad7c/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsChunkSource.java#L403-L409

@christosts @AquilesCanta any idea where this could come from? Additionally, in order for the exception to be raised early, maybe `HlsChunkSource` should check that all url are non null and make a defensive copy of the array.

**Comment by christosts** [comment] 2020-12-15 17:36
We inspected the code and saw there is a case where this may happen: if the playlist has a subtitles track but it does not include a URI for the subtitles. This would be in violation of the HLS spec, but the player at the moment does not raise an exception immediately. As a result, a null value may be inserted in the `playlistUrls`  array. We are going to fix this and it will be available to the dev-v2 branch in the coming days. The fix would make the player fail fast and make this error more obvious. 

Our hypothesis of what is probably happening: the playlist does not have a URI for subtitles but the player does not raise a parse exception, therefore it contains the null element in the array. This is not causing an error immediately because subtitles are not displayed, then later a possibly unrelated error triggers the onLoadError() event (HTTP 404 maybe?) which eventually raises the NPE.

We should try to verify this is indeed the case causing the error at hand. @stari4ek is it possible provide any playlist samples that have caused this? You did mention that it's not possible, but I'm asking in case something has changed since the issue was filed. Or, in case you have found reproduction steps in your app, will you be able to test locally on your app after we commit the fix?

**Comment by stari4ek** [comment] 2020-12-16 10:44
Yeah, it could be provoked by network/loader error. Some of reports have
```
r:Playback|D] TvirlLoadErrorHandlingPolicy: Got HttpDataSourceException (java.net.SocketTimeoutException: timeout) (count: 1, load duration: 11671ms). Delay reconnect to: 0ms
```
right before it,
some of them have network down/up nearby.

I do not have access to streams but I will try to reach users.
But this error happens with the same service, so it's very possible that this is media issue.

While pro-active reaction to HLS spec violation sounds as proper implementation, it makes ExoPlayer less steady and friendly to media already floating around (especially comparing to non-ExoPlayer based players). Any chances to ignore invalid tracks? Mark them unsupported?
From user perspective since it's subtitles track - loosing playback for such media is bigger harm than loosing track itself.

**Comment by christosts** [comment] 2020-12-17 11:51
Hi, commit [8da4eaa](https://github.com/google/ExoPlayer/commit/8da4eaa377e0c529c92aa9781480ed48f35006af) ignores subtitles that do not have a URI, but does not raise an exception in order to maintain playback. This is in the dev-v2 branch at the moment and will be available on a next release. 

Closing the issue, feel free to re-open if the fix did not address the issue, or there are any other questions.

**Closed as completed by christosts** 2020-12-17 11:51 UTC
Labels: bug
