### ISSUE TITLE
OkHttp extension on Maven?

### ISSUE THREAD

**Issue by aletorrado** [google/ExoPlayer#1889] opened 2016-10-04 03:19 UTC
Is this extension available on Maven? I couldn't find any clear instructions on how to integrate it.

**Comment by ojw28** [comment] 2016-10-04 10:18
I've created https://bintray.com/google/exoplayer/extension-okhttp. Bintray need to approve its addition to jCenter, I think. Hopefully this should happen pretty soon.

**Comment by ojw28** [comment] 2016-10-05 09:36
This is a dupe of https://github.com/google/ExoPlayer/issues/1157, so closing this.

**Closed as completed by ojw28** 2016-10-05 09:36 UTC
Labels: enhancement
