### ISSUE TITLE
Issue with EMSG delivery as per latest dashif.org specifications

### ISSUE THREAD

**Issue by tibor-leo-safar-accedo** [google/ExoPlayer#9335] opened 2021-08-25 14:33 UTC
Actual situation:
-------------------------
There is a DASH stream packager where the delivery of EMSG (EIT) messages is implemented as per latest defined by dashif.org documentation. (Page 13 -> 6.2)
https://dashif.org/docs/EventTimedMetadataProcessing-v1.0.2.pdf
These messages are not dispatched/delivered to the message listeners.

Longer explanation:
-------------------------
23009-1 5th edition - timing compliant EMSG handling

The handling of DASH events embedded in ISOBMFF emsg boxes is different between 23009-1 4th edition and 23009-1 5th edition.

In 23009-1 4th edition there is a restriction on the presentation of events that says: "presentation_time: provides the Media Presentation time of the event measured on the Movie timeline, in the timescale provided in the timescale field; the value shall not be less than the earliest presentation time of the carrying Segment." This means that the start time of an event should always be higher than the EPT of the segment carrying the event.

This restriction will be removed in the 5th edition of the ISO spec. _Some packagers have already implemented this change._

In order to be compliant to that, the player implementation shall consider the duration of an event. From the DASH-IF event spec:

"on-start Dispatch Mode: Dispatching exactly at ST, which is the start/presentation time of the event/metadata sample. The DASH player shall dispatch the event to the application at the presentation time of the corresponding media sample, or in the case of the start of playback after that moment and during the event duration, at the earliest time within the event duration. In this mode, since the Applications receive the event/sample at its start/presentation time, it may need to act on the received data immediately."

In order to fulfil this requirement players need to consider the duration of an event to determine if an event is to be dispatched or not. To our best knowledge the Exoplayer is currently ignoring the duration of an event when deciding whether to dispatch an event.

More detailed explanation with timing example of **emsg**'s in a live stream:
---
 - there is a program starting at 13:00 It lasts 60 minutes, so next EMSG is going to be delivered at 14:00
 - the playback of the stream is initiated at 13:10 - whatever time between 13 and 14h - the related **emsg** is present in the stream, but due to the logic mentioned above from _SampleQueue.java_ and _SimpleMetadataDecoder.java_ the message _will not be delivered to the player listeners_.
 - the first delivered **emsg** will be the one from 14h, what means that at the time we have joined the stream no message will be dispatched (**This is the issue**). The first delivered message will be only at the next event boundary at 14:00.
 - Expectation is to have the emsg dispatched to listeners by joining time (while the **emsg** duration lasts). Actually all **emsg** messages could be delivered, and the client/player implementation can decide what to do with them, 

Issue:
-------------------------
The current version of ExoPlayer (2.12.2 - in our project) does not delivers EMSG messages if they are packed according to the latest definitions.
It needs a tweak of player for these message to get delivered.

_SampleQueue.java_
`private synchronized int readSampleMetadata(`
`...`
`    if (buffer.timeUs < startTimeUs) {`
`      buffer.addFlag(C.BUFFER_FLAG_DECODE_ONLY);`
`    }`
`...`

The issue here is that BUFFER_FLAG_DECODE_ONLY is set, however the buffer time is a valid value what needs to be delivered, according to new standards. (even if timeUs is smaller than startTimeUs.)

Temporary solution:
-------------------
Because was not sure what are the long term plans with BUFFER_FLAG_DECODE_ONLY flags, the code in _SampleQueue.java_ was left untouched, but a small change was applied to the _SimpleMetadataDecoder.java_ The change is to deliver all the messages regardless of the `isDecodeOnly()` flag of the message buffer:
    `return inputBuffer.isDecodeOnly() ? null : decode(inputBuffer, buffer);`
was simply changed to
    `return decode(inputBuffer, buffer);`
Resulting in all the messages being delivered, so the client application can receive them and act upon its needs.

Questions:
-------------------
 - Was this already spotted/reported and/or maybe fixed in any of the newer versions (haven't seen any related remark in release notes so far)
 - Is tis planned to be addressed in the short future?
 - Is the current temporary solution, presented above, feasible or you think something more sophisticated is needed here? (What would be your suggestion?)

Note: 
More details with example stream is going to be sent by e-mail.

- ExoPlayer version number: **2.12.2**
- Android version: **all**
- Android device: **any**

**Comment by icbaker** [comment] 2021-08-25 16:23
I think this is a duplicate of #9241

**Closed as completed by icbaker** 2021-08-25 16:23 UTC
Labels: duplicate
