### ISSUE TITLE
HLS MaxAudioBitrate limit not working

### ISSUE THREAD

**Issue by jakoss** [google/ExoPlayer#6006] opened 2019-06-07 08:25 UTC
### Content description
I'm trying to stream audio only files (AAC and MP3, both codecs have the same issue). I generated 3 different bitrates playlists (256k, 192k and 128k) and then master playlist.
I need to be able to limit max bitrate (if users want to limit their data usage) to set values. So i have code:
```kotlin
private val exoPlayer: SimpleExoPlayer by lazy {
        val adaptiveTrackSelection = AdaptiveTrackSelection.Factory()
        val trackSelector = DefaultTrackSelector(adaptiveTrackSelection)
        trackSelector.setParameters(DefaultTrackSelector.ParametersBuilder()
// here i'm trying to force lowest bitrate for testing purposes
            .setMaxAudioBitrate(128_000)
            .setExceedAudioConstraintsIfNecessary(false)
            .setForceLowestBitrate(true))

        ExoPlayerFactory.newSimpleInstance(this, trackSelector).apply {
            setAudioAttributes(uAmpAudioAttributes, true)
            addAnalyticsListener(EventLogger(trackSelector))
            val debugViewHelper = DebugTextViewHelper(this, debug_text_view)
            debugViewHelper.start()
        }
    }
```
And i setup hls media source like that (just static test streams):
```kotlin
private fun createMediaSource(): MediaSource {
        val dataSourceFactory = DefaultDataSourceFactory(this, "ExoPlayer")
        val hlsMediaSourceFactory = HlsMediaSource.Factory(dataSourceFactory)
            .setAllowChunklessPreparation(true)
        val track1 = hlsMediaSourceFactory.createMediaSource(Uri.parse("http://10.0.2.2:5000/streams/despacito/master.m3u8"))
        val track2 = hlsMediaSourceFactory.createMediaSource(Uri.parse("http://10.0.2.2:5000/streams/duality/master.m3u8"))
        val track3 = hlsMediaSourceFactory.createMediaSource(Uri.parse("http://10.0.2.2:5000/streams/blackorwhite/master.m3u8"))

        return ConcatenatingMediaSource(track1, track2, track3)
    }
```
It's playing very well, no issues here, but unfortunetely, with this setup, exoplayer always chooses track with highest bitrate. Logs:
```
D/EventLogger: tracksChanged [26.35, 0.00, window=1, period=1, 
      Renderer:1 [
        Group:0, adaptive_supported=YES_NOT_SEAMLESS [
          [ ] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=281600, codecs=mp4a.40.2, supported=YES
          [ ] Track:1, id=1, mimeType=audio/mp4a-latm, bitrate=211200, codecs=mp4a.40.2, supported=YES
          [ ] Track:2, id=2, mimeType=audio/mp4a-latm, bitrate=140800, codecs=mp4a.40.2, supported=YES
        ]
      ]
      Renderer:3 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=ID3, mimeType=application/id3, supported=YES
        ]
      ]
    ]
```

I found configuring `adaptive streaming` very confusing, since internet is full of samples with old api versions and i wasn't able to find some official documentation about that.

### Link to test content
Whole streamed content: [files.zip](https://github.com/google/ExoPlayer/files/3264954/files.zip)

### Version of ExoPlayer being used
2.10.1

### Device(s) and version(s) of Android being used
Mutiple versions of android on Android Emulator and on physical device (Nokia 8)

**Comment by jakoss** [comment] 2019-06-07 10:28
Strange thing (but maybe not related) - every time i call player.currentManifest i got null. Same with onTimelineChanged event - i get 3 events (as expected), but manifest is null in all of them

**Comment by jakoss** [comment] 2019-06-18 05:43
Further information. I had to change HttpDataSource to OkHttp like that:
```
val httpClient = getUnsafeOkHttpClient()
val dataSourceFactory = OkHttpDataSourceFactory(httpClient, "ExoPlayer")
val hlsMediaSourceFactory = HlsMediaSource.Factory(dataSourceFactory)
        .setAllowChunklessPreparation(true)
```
to bypass SSL problems with our internal certs. It seems like on OkHttp the exact same code is working fine, just after playback start i get log `downstreamFormatChanged [0.38, 0.00, window=0, period=0, id=2, mimeType=null, bitrate=140800, codecs=mp4a.40.34]` and player does take right quality. So the problem seems to be with `DefaultDataSource`

**Comment by AquilesCanta** [comment] 2019-06-18 09:17
Hi, sorry for the delay on this. I got confused thinking it was a duplicate of a different issue in the current HLS implementation. I'll have a look soon and reach back.

**Comment by jakoss** [comment] 2019-06-18 09:43
No worries. Let me know if i can help you more

**Comment by AquilesCanta** [comment] 2019-06-18 09:54
There is a bug in the default track selector, due to which it ignores the maximum audio bitrate when creating the adaptive audio group. A fix for this will be referred in this issue soon.

As a side note, you should not select both a maximum bitrate and `forceLowestBitrate`, since the latter overrides the former. From what I understand about your usecase, you should stick to `maxAudioBitrate`.

Final note. I don't know how you got this in the logs:

```
Renderer:1 [
        Group:0, adaptive_supported=YES_NOT_SEAMLESS [
          [ ] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=281600, codecs=mp4a.40.2, supported=YES
          [ ] Track:1, id=1, mimeType=audio/mp4a-latm, bitrate=211200, codecs=mp4a.40.2, supported=YES
          [ ] Track:2, id=2, mimeType=audio/mp4a-latm, bitrate=140800, codecs=mp4a.40.2, supported=YES
        ]
      ]
```

as this would mean that the player has not selected any audio tracks. However, you also mention 

> It's playing very well,

so I assume there was some confusion here.

**Comment by jakoss** [comment] 2019-06-18 10:05
I was experimenting with `forceLowestBitrate` just to check what it does in this issue. 

As of the logs - `It's playing very well` was just about music. It was playing.

Now, when using OkHttpDataSource, Renderer ` gets right track selected, so no problem here :)

**Comment by AquilesCanta** [comment] 2019-06-19 14:36
This should be fixed in the dev branch. Please give `maxAudioBitrate` a try and let me know if you run into any issues.

**Closed as completed by AquilesCanta** 2019-06-19 14:37 UTC
Labels: bug

**Comment by jakoss** [comment] 2019-06-25 07:05
Version 2.10.2 seems to be working fine. Thanks
