### ISSUE TITLE
Automated building of extensions

### ISSUE THREAD

**Issue by peacechen** [google/ExoPlayer#4079] opened 2018-04-03 18:17 UTC
### Issue description
`react-native-video` uses ExoPlayer for the Android implementation.  Video format support is all over the place (e.g. some files play on the Nexus 5 / Android 6, but not Nexus 6 / Android 7).  I believe that this may be resolved by using the software extension decoders.

The docs for the extensions have a [manual build requirement](https://google.github.io/ExoPlayer/demo-application.html#including-extension-decoders) that doesn't play nice when ExoPlayer is used as a dependency.
`Build each of the extensions that you want to include. Note that this is a manual process.`

What is a good way to programmatically build the extensions when using ExoPlayer as a dependency?

### Reproduction steps
Use ExoPlayer demo app.

### Link to test content
This video doesn't play on a Nexus 6 / Android 7 using ExoPlayer without extensions:
https://github.com/mediaelement/mediaelement-files/blob/master/big_buck_bunny.mp4

### Version of ExoPlayer being used
2.7.2

### Device(s) and version(s) of Android being used
Nexus 5 / Android 6.0.1
Nexus 6 / Android 7.1.2

### A full bug report captured from the device
N/A

**Comment by andrewlewis** [comment] 2018-04-04 07:31
#1434 tracks distributing some extensions via jCenter.

I can't think of any particularly useful guidance regarding programmatically building the extensions. The extension READMEs include instructions that could be used as reference for writing some build scripts. Perhaps someone else who has experience with this can offer some suggestions.

The linked stream has H.264/AVC video and AAC audio. Does including extensions actually make a difference to whether it's playable?

**Comment by peacechen** [comment] 2018-04-04 14:28
I haven't had time to test it with the extensions.  In the meantime, would anyone with a working build of ExoPlayer + extensions try the video link?  The issue could be Android 7 (or the Nexus 6 hardware, but unlikely since the video plays in Chrome on the Nexus 6).

**Comment by ojw28** [comment] 2018-11-23 23:30
As above, #1434 tracks distributing some extensions via jCenter.

I'm confused by the rest of this issue. Nexus 6 never received Android 7.1.2. Updates stopped at 7.1.1 according to https://developers.google.com/android/images#shamu. The linked video plays fine on a Nexus 6 I have running 7.1.1. There is no bug report provided, which would indicate both the build on the device and most likely the cause of playback failure. It's unclear what "does not play" really means.

Closing for the above reasons.

**Closed as completed by ojw28** 2018-11-23 23:30 UTC
Labels: need more info
