### ISSUE TITLE
Live Stream playback failure on PTS rollover

### ISSUE THREAD

**Issue by ssenanayake** [google/ExoPlayer#10330] opened 2022-06-10 14:48 UTC
### ExoPlayer Version

2.16.1

### Devices that reproduce the issue

Android Devices and FireOS Devices

### Devices that do not reproduce the issue

Other platforms like Apple, Roku does not exhibit this issue

### Reproducible in the demo app?

Yes

### Reproduction steps

1) Play the non-DRM Live content
2) Let it play for around 12 hrs so that a PTS rollover occurs.

In the Live stream HLS manifest, we use VTT captions and when the PTS rollover occurs, the X-TIMESTAMP-MAP enty's MPEGTS becomes negative and that is when the content playback freeze occurs and never recovers.

We have remove the Live VTT captions entry and the stream plays without issue.

### Expected result

Stream plays without issue

### Actual result

In the Live stream HLS manifest, we use VTT captions and when the PTS rollover occurs, the X-TIMESTAMP-MAP enty's MPEGTS becomes negative and that is when the content playback freeze occurs and never recovers.

### Media

Media is obtained through a call to Google DAI. 

The DAI ID can be provided through email. Also a url can be provided from Google DAI, but please note that the Url expires after a certain time.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-06-10 15:17
This looks like it's in the same bit of the world as https://github.com/google/ExoPlayer/issues/7462.

Can you confirm that the stream includes a `.vtt` file with an `X-TIMESTAMP-MAP` with a negative `MPEGTS` value, i.e. something like:
```
X-TIMESTAMP-MAP=LOCAL:01:02:03.040,MPEGTS:-567000
```

My (possibly incorrect) interpretation of the HLS spec discussing the wrapping of 33-bit PES timestamps is that it treats the PES timestamp as an unsigned integer and therefore expects the value to wrap from `2^33 - 1` down to `0`. Given you're discussing negative numbers, does that mean you're treating the PES timestamp as a signed 33-bit integer and wrapping it from `2^32 - 1` down to `-2^32`?

It would be helpful to provide a stream we can use to reproduce the problem.

**Comment by ssenanayake** [comment] 2022-06-10 15:38
Yes, the MPEGTS value is negative as in

WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:-5202976


I have emailed the adb Bugreport along with the Google DAI ID for the stream for testing.



Here's the master manifest as of right now....

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="eng",URI="https://dai.google.com/linear/hls/pa/event/9Lq0ERvoSR-z9AwvFS-xYA/stream/42ae32e7-3e03-4632-b2ba-d48ed6d93566:DLS/variant/e943d374d8ffe9086defc6918d5473fe/bandwidth/000.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=391534,AVERAGE-BANDWIDTH=380600,CODECS="avc1.64000d,mp4a.40.2",RESOLUTION=400x224,SUBTITLES="subs",FRAME-RATE=29.970
https://dai.google.com/linear/hls/pa/event/9Lq0ERvoSR-z9AwvFS-xYA/stream/42ae32e7-3e03-4632-b2ba-d48ed6d93566:DLS/variant/33ed89282c4502db4e5f09a4a16c17ad/bandwidth/391534.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=677468,AVERAGE-BANDWIDTH=655600,CODECS="avc1.640015,mp4a.40.2",RESOLUTION=512x288,SUBTITLES="subs",FRAME-RATE=29.970
https://dai.google.com/linear/hls/pa/event/9Lq0ERvoSR-z9AwvFS-xYA/stream/42ae32e7-3e03-4632-b2ba-d48ed6d93566:DLS/variant/b0630584e763cfc011905cf4106a0626/bandwidth/677468.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1055788,AVERAGE-BANDWIDTH=1020800,CODECS="avc1.64001e,mp4a.40.2",RESOLUTION=640x360,SUBTITLES="subs",FRAME-RATE=29.970
https://dai.google.com/linear/hls/pa/event/9Lq0ERvoSR-z9AwvFS-xYA/stream/42ae32e7-3e03-4632-b2ba-d48ed6d93566:DLS/variant/f3f3a7f3426dd9153708165fc2d7feb2/bandwidth/1055788.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1513283,AVERAGE-BANDWIDTH=1460800,CODECS="avc1.64001e,mp4a.40.2",RESOLUTION=768x432,SUBTITLES="subs",FRAME-RATE=29.970
https://dai.google.com/linear/hls/pa/event/9Lq0ERvoSR-z9AwvFS-xYA/stream/42ae32e7-3e03-4632-b2ba-d48ed6d93566:DLS/variant/8d491c64934e873291989bbbc150e508/bandwidth/1513283.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=2199524,AVERAGE-BANDWIDTH=2120800,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=960x540,SUBTITLES="subs",FRAME-RATE=29.970
https://dai.google.com/linear/hls/pa/event/9Lq0ERvoSR-z9AwvFS-xYA/stream/42ae32e7-3e03-4632-b2ba-d48ed6d93566:DLS/variant/d064ccdcdc5337370ea268ff8e389280/bandwidth/2199524.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4143876,AVERAGE-BANDWIDTH=3990800,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=1280x720,SUBTITLES="subs",FRAME-RATE=29.970
https://dai.google.com/linear/hls/pa/event/9Lq0ERvoSR-z9AwvFS-xYA/stream/42ae32e7-3e03-4632-b2ba-d48ed6d93566:DLS/variant/23cdc4d7f0845231cf2b256fa7e96718/bandwidth/4143876.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=5859480,AVERAGE-BANDWIDTH=5640800,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080,SUBTITLES="subs",FRAME-RATE=29.970
https://dai.google.com/linear/hls/pa/event/9Lq0ERvoSR-z9AwvFS-xYA/stream/42ae32e7-3e03-4632-b2ba-d48ed6d93566:DLS/variant/e9fb5818977104098eceaa0a7fe15f91/bandwidth/5859480.m3u8
```


and 

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="English",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="eng",URI="https://dai.google.com/linear/hls/pa/event/9Lq0ERvoSR-z9AwvFS-xYA/stream/42ae32e7-3e03-4632-b2ba-d48ed6d93566:DLS/variant/e943d374d8ffe9086defc6918d5473fe/bandwidth/000.m3u8"

is the Live VTT caption file.


At present, since it's not in a rollover the file is as follows...

```
WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:4681720928

00:00:00.000 --> 00:00:02.150
matchup was much better for them

00:00:02.350 --> 00:00:04.150
but you don't just put turner on

00:00:04.450 --> 00:00:05.850
you pitch around at turner
```


Unfortunately it takes many hours to reach this condition in the live stream. I let it run overnite in the Exo Demo app for 2.16.1 (Because we use the Amazon port of Exo and that's the latest), and the same "Playback failed" error occured.

**Comment by icbaker** [comment] 2022-06-13 14:45
We added support for negative `MPEGTS` values in the `X-TIMESTAMP-MAP` header in https://github.com/google/ExoPlayer/pull/7098. In the comment thread of that PR @ojw28 and @matamegger tentatively concluded that only positive values are really allowed under the spec (since MPEG-2 PES timestamps are unsigned) but they also agreed that handling negative timestamps wouldn't make handling positive timestamps any worse.

As I said above when we added wrapping support in https://github.com/google/ExoPlayer/issues/7462 we assumed that the `MPEGTS` value would wrap back to 0 (i.e. is an unsigned representation, the same as the MPEG-2 spec).

What media preparation tool are you using where the `MPEGTS` timestamp wraps to a negative value?

Since it seems the HLS spec probably (?) didn't intend this value to be negative, I'm tempted to mark this 'bad media' rather than try and make our wrapping-handling logic even more complicated by considering the possibility of also wrapping back from `2^32 - 1` to `-2^32`.

**Comment by ssenanayake** [comment] 2022-06-15 02:24
@icbaker For the VTT captions during live we use a custom solution. But that uses each TS chunk and a Google Service to extract the captions and create the VTT on the fly for Live content. That custom solution is what is created the negative MPEGTS value. 

We are exploring alternatives/fixes.

**Comment by icbaker** [comment] 2022-06-15 11:14
If your custom code is generating the `X-TIMESTAMP-MAP` header, then can you try changing it to always write positive `MPEGTS` values? Either by parsing the original binary 33-bit MPEG timestamp representation in an unsigned way (so the number is never negative in your system), or if you don't control the parsing you can transform a signed, negative representation of a 33-bit number to the bit-equivalent unsigned, positive representation by adding `2^33` - so you could try doing that to all negative values just before writing the `X-TIMESTAMP-MAP` header.

**Comment by athithamarnathcbs** [comment] 2022-06-15 19:04
1. 33-bit MPEG timestamp representation is not an unsigned integer and this timestamp representation is dictated by the encoder's PCR. 

2. adding `2^33` to the webVTT for s segment that has negative PTS values after the rollover will thereby stop the captions playback. 

Just like PTS rollover handled in the stream decoder, this adding `2^33` logic needs to be handled in the webVTT parser in the stream decoder.

**Comment by icbaker** [comment] 2022-06-27 09:28
> 33-bit MPEG timestamp representation is not an unsigned integer and this timestamp representation is dictated by the encoder's PCR.

In ISO 13818-12007 Table 2-6 the `program_clock_reference_base` is described as 33-bits with mnemonic `uimsbf`.

In section 2.2.6 of the same document, the `uimsbf` mnemonic is defined as:
> Unsigned integer, most significant bit first

----

I'm closing this issue because I don't believe it makes sense for ExoPlayer to change any logic here - the problem will be solved if your subtitle encoding system consistently treats mpeg timestamps as unsigned integers that wrap from `2^33 - 1` back to `0`.

**Closed as completed by icbaker** 2022-06-27 09:28 UTC
Labels: question

**Comment by ssenanayake** [comment] 2022-07-18 19:15
Just wanted to provide an update....

We changed the RegEx in "WebvttExtractor" in Exo.

From:

  private static final Pattern MEDIA_TIMESTAMP = Pattern.compile("MPEGTS:(\\d+)");


To:

  private static final Pattern MEDIA_TIMESTAMP = Pattern.compile("MPEGTS:(-?\\d+)");


And did thorough testing with Google DAI Live streams with PTS rollover resulting in vtt captions having a negative MPEGTS value. All worked well after the change to support negative in RegEx. No other issues observed.

Also we reached out to Roger Pantos on negative values for MPEGTS and he confirmed that they can be negative.

Thanks!!!

**Comment by icbaker** [comment] 2022-07-19 16:21
> We changed the RegEx in "WebvttExtractor" in Exo.
> 
> From:
> 
> private static final Pattern MEDIA_TIMESTAMP = Pattern.compile("MPEGTS:(\d+)");
> 
> To:
> 
> private static final Pattern MEDIA_TIMESTAMP = Pattern.compile("MPEGTS:(-?\d+)");

Just to clarify (for anyone else reading this thread), ExoPlayer has had the second of these regexes (with the optional `-`) since https://github.com/google/ExoPlayer/commit/dd4a732303dafc9b5fb8a3bb3e6c67bd6a6b403b (as mentioned above in https://github.com/google/ExoPlayer/issues/10330#issuecomment-1154015503) which has been present since version 2.11.4 of the library. So the change described here only makes sense on versions of ExoPlayer before 2.11.4, and in those cases is essentially a back-port of the commit.

The original issue tracked by this new thread was not about matching the negative value (since the version reported was 2.16.1 which already matches the negative value), but about something else going wrong with handling the rollover. If all that was required to fix the originally reported issue is to change the regex, then I think the original issue report must have indicated the wrong version of ExoPlayer being used? Or there's something else more confusing going on...

I'm going to leave the issue closed since it sounds like you've resolved the problem.
