### ISSUE TITLE
nVidia Shield - DRM_E_OUTOFMEMORY when playing PlayReady protected content

### ISSUE THREAD

**Issue by MizzleDK** [google/ExoPlayer#2265] opened 2016-12-27 21:04 UTC
I'm running the demo app in the release-v2 (2.1.1) branch on my Nvidia Shield TV. When attempting to play the SmoothStreaming demo with PlayReady DRM, I sometimes get the following error log:

```
12-27 21:58:49.127 11743-12140/com.google.android.exoplayer2.demo E/MediaDrm-JNI: Illegal state exception: Failed to get key request (-2147483648)
12-27 21:58:49.128 11743-12140/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
                                                                                           com.google.android.exoplayer2.ExoPlaybackException
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:298)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:754)
                                                                                               at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:214)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:496)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:479)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                               at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                            Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
                                                                                               at android.media.MediaDrm.getKeyRequest(Native Method)
                                                                                               at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:84)
                                                                                               at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.postKeyRequest(StreamingDrmSessionManager.java:376)
                                                                                               at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.openInternal(StreamingDrmSessionManager.java:328)
                                                                                               at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.acquireSession(StreamingDrmSessionManager.java:266)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:732)
                                                                                               at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:214) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:496) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:479) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                               at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
12-27 21:58:49.130 11743-11743/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.88]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:298)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:754)
                                                                                     at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:214)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:496)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:479)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
                                                                                     at android.media.MediaDrm.getKeyRequest(Native Method)
                                                                                     at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:84)
                                                                                     at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.postKeyRequest(StreamingDrmSessionManager.java:376)
                                                                                     at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.openInternal(StreamingDrmSessionManager.java:328)
                                                                                     at com.google.android.exoplayer2.drm.StreamingDrmSessionManager.acquireSession(StreamingDrmSessionManager.java:266)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:732)
                                                                                     at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:214) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:496) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:479) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:315) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

I'm not yet sure what causes the issue to appear, but once it has appeared, it's impossible to start video playback until the device is rebooted.

The Nvidia Shield TV device is running Android (TV) 6.0 with build version 3.3(24.18.78.174).

Note: This also happened on ExoPlayer 1.5.3.

**Comment by MizzleDK** [comment] 2017-01-02 22:17
Here's the unfiltered system logs:

```
01-02 23:14:50.195 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x02000009) at external/DxDrm/PlayReady/Server/DxPrdyProvisioning.cpp(112)
01-02 23:14:50.195 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x02000009) at external/DxDrm/PlayReady/OEM/common/oeminfo_common.c(188)
01-02 23:14:50.195 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_OUTOFMEMORY (0x80000002), Insufficient resources exist to complete the request at external/DxDrm/PlayReady/BlackBox/dx_stub/blackbox_hwa_stub_impl.c(2728)
01-02 23:14:50.195 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_OUTOFMEMORY (0x80000002), Insufficient resources exist to complete the request at external/DxDrm/PlayReady/BlackBox/dx_stub/blackbox_hwa_stub.c(276)
01-02 23:14:50.195 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_OUTOFMEMORY (0x80000002), Insufficient resources exist to complete the request at external/DxDrm/PlayReady/ServerSDK/../Device_PK_1.2/Source/drmmanager/drmmanager.c(759)
01-02 23:14:50.195 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_INVALIDARG (0x80070057), The parameter is incorrect at external/DxDrm/PlayReady/ServerSDK/../Device_PK_1.2/Source/noncestore/drmnoncestore.c(118)
01-02 23:14:50.195 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_INVALIDARG (0x80070057), The parameter is incorrect at external/DxDrm/PlayReady/ServerSDK/../Device_PK_1.2/Source/core/drmdatastore.c(96)
01-02 23:14:50.195 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_INVALIDARG (0x80070057), The parameter is incorrect at external/DxDrm/PlayReady/ServerSDK/../Device_PK_1.2/Source/core/drmdatastore.c(96)
01-02 23:14:50.195 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x80000002) at external/DxDrm/PlayReady/Server/DxPrdyServerSdkApi.cpp(164)
01-02 23:14:50.195 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x80000002) at external/DxDrm/PlayReady/Client/IDxPrdyBaseContext.cpp(65)
01-02 23:14:50.195 247-731/? E/DxModule_0x80000000: Returning Error Code: 0x80000002 at external/DxDrm/PlayReady/Client/IDxPrdyBaseContext.cpp(78)
01-02 23:14:50.195 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x80000002) at external/DxDrm/PlayReady/Client/IDxPrdyBaseStream.cpp(290)
01-02 23:14:50.195 247-731/? E/DxModule_0x80000000: Returning Error Code: DX_ERROR_GENERAL_FAILURE (0x00000009) at external/DxDrm/MultiScheme/Client/DxAPITools.cpp(41)
01-02 23:14:50.201 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x02000009) at external/DxDrm/PlayReady/Server/DxPrdyProvisioning.cpp(112)
01-02 23:14:50.201 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x02000009) at external/DxDrm/PlayReady/OEM/common/oeminfo_common.c(188)
01-02 23:14:50.201 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_OUTOFMEMORY (0x80000002), Insufficient resources exist to complete the request at external/DxDrm/PlayReady/BlackBox/dx_stub/blackbox_hwa_stub_impl.c(2728)
01-02 23:14:50.201 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_OUTOFMEMORY (0x80000002), Insufficient resources exist to complete the request at external/DxDrm/PlayReady/BlackBox/dx_stub/blackbox_hwa_stub.c(276)
01-02 23:14:50.201 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_OUTOFMEMORY (0x80000002), Insufficient resources exist to complete the request at external/DxDrm/PlayReady/ServerSDK/../Device_PK_1.2/Source/drmmanager/drmmanager.c(759)
01-02 23:14:50.201 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_INVALIDARG (0x80070057), The parameter is incorrect at external/DxDrm/PlayReady/ServerSDK/../Device_PK_1.2/Source/noncestore/drmnoncestore.c(118)
01-02 23:14:50.201 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_INVALIDARG (0x80070057), The parameter is incorrect at external/DxDrm/PlayReady/ServerSDK/../Device_PK_1.2/Source/core/drmdatastore.c(96)
01-02 23:14:50.201 247-731/? E/DxModule_0x10: PlayReady error: DRM_E_INVALIDARG (0x80070057), The parameter is incorrect at external/DxDrm/PlayReady/ServerSDK/../Device_PK_1.2/Source/core/drmdatastore.c(96)
01-02 23:14:50.201 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x80000002) at external/DxDrm/PlayReady/Server/DxPrdyServerSdkApi.cpp(164)
01-02 23:14:50.202 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x80000002) at external/DxDrm/PlayReady/Client/IDxPrdyBaseContext.cpp(65)
01-02 23:14:50.202 247-731/? E/DxModule_0x80000000: Returning Error Code: 0x80000002 at external/DxDrm/PlayReady/Client/IDxPrdyBaseContext.cpp(78)
01-02 23:14:50.202 247-731/? E/DxModule_0x80000000: Returning Error Code: (0x80000002) at external/DxDrm/PlayReady/Client/IDxPrdyBaseStream.cpp(290)
01-02 23:14:50.202 247-731/? E/DxModule_0x80000000: Returning Error Code: DX_ERROR_GENERAL_FAILURE (0x00000009) at external/DxDrm/MultiScheme/Client/DxAPITools.cpp(41)
01-02 23:14:50.202 247-731/? E/DxDrmModularPlugin: getKeyRequest : DxDrmStream_GetLicenseChallenge failed, result = 9
01-02 23:14:50.202 29163-29200/dk.yousee.ott.leanback E/MediaDrm-JNI: Illegal state exception: Failed to get key request (-2147483648)
```

**Comment by ojw28** [comment] 2017-01-03 12:45
It looks like the Shield's PlayReady module can't allocate the memory it needs. I'm following up with nVidia.

**Comment by MizzleDK** [comment] 2017-01-03 13:58
Thank you.

**Comment by ojw28** [comment] 2017-01-04 15:05
This is a memory leak issue that nVidia have already identified and fixed. I believe the fix will be included in their next software update for Shield. Thanks!

**Closed as completed** 2017-01-04 22:49 UTC
Labels: wont fix: infeasible, bug: device specific

**Comment by MizzleDK** [comment] 2017-01-05 08:39
Awesome! Thanks a lot.

**Comment by aleian84** [comment] 2017-01-30 17:02
Hi guys, 
have you an update on this defect? When it will be released by nVidia?

Thanks!

**Comment by ojw28** [comment] 2017-01-30 17:07
We're not able to comment on the schedules of device manufacturers. Although according to the internet, the [answer is now](http://www.anandtech.com/show/11080/nvidia-releases-android-70-update-for-2015-shield-tv-adds-amazon-video-app).

**Comment by MizzleDK** [comment] 2017-01-31 09:47
I can confirm that it's fixed with the Android TV 7.0 update.

**Comment by aleian84** [comment] 2017-01-31 16:25
Thank you guys. 

I use exoplayer r1.5.14 and I have the following exception when I try to play any encrypted playready content :   

01-31 17:16:43.720 4037-6217/it.infinity_atv E/MediaDrm-JNI: Illegal state exception: Failed to get key request (-2147483648)
01-31 17:16:43.721 4037-6217/it.infinity_atv E/ExoPlayerImplInternal: Internal track renderer error.
                                                                      com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
                                                                          at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:364)
                                                                          at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800)
                                                                          at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
                                                                          at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540)
                                                                          at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523)
                                                                          at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                          at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                          at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                          at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                       Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
                                                                          at android.media.MediaDrm.getKeyRequest(Native Method)
                                                                          at com.google.android.exoplayer.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:67)
                                                                          at com.google.android.exoplayer.drm.StreamingDrmSessionManager.postKeyRequest(StreamingDrmSessionManager.java:415)
                                                                          at com.google.android.exoplayer.drm.StreamingDrmSessionManager.openInternal(StreamingDrmSessionManager.java:367)
                                                                          at com.google.android.exoplayer.drm.StreamingDrmSessionManager.open(StreamingDrmSessionManager.java:337)
                                                                          at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:359)
                                                                          at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800) 
                                                                          at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
                                                                          at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540) 
                                                                          at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523) 
                                                                          at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128) 
                                                                          at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432) 
                                                                          at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                          at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
01-31 17:16:43.735 4037-4037/it.infinity_atv E/EventLogger: internalError [1.48, drmSessionManagerError]
                                                            android.media.MediaDrm$MediaDrmStateException: Failed to get key request
                                                                at android.media.MediaDrm.getKeyRequest(Native Method)
                                                                at com.google.android.exoplayer.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:67)
                                                                at com.google.android.exoplayer.drm.StreamingDrmSessionManager.postKeyRequest(StreamingDrmSessionManager.java:415)
                                                                at com.google.android.exoplayer.drm.StreamingDrmSessionManager.openInternal(StreamingDrmSessionManager.java:367)
                                                                at com.google.android.exoplayer.drm.StreamingDrmSessionManager.open(StreamingDrmSessionManager.java:337)
                                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:359)
                                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800)
                                                                at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
                                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540)
                                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523)
                                                                at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by aleian84** [comment] 2017-02-01 09:22
Hi guys,
only to give an update to you.

My problem is in the manifest. Now I have produced a new manifest an all work correctly.

Thank you for the support.
