### ISSUE TITLE
Samsung Galaxy S7, S7 Edge (Nougat) Playback issue on r1.5.6

### ISSUE THREAD

**Issue by uyjulius** [google/ExoPlayer#2583] opened 2017-03-21 08:44 UTC
### Issue description
We are seeing a pattern of our users who are reporting that DASH playback has stopped working as soon as they updated their Galaxy S7 and S7 Edge to Nougat. They are seeing no video but are hearing sound. This does not happen in Marshmallow. Were there any similar reports?

### Reproduction steps
Simply play an mpd video on an S7 or S7 Edge running Nougat.

### Link to test content
Happens on every mpd video.

### Version of ExoPlayer being used
1.5.6

### Device(s) and version(s) of Android being used
Samsung Galaxy S7 and Samsung Galaxy S7 Edge running Android Nougat

Affected device models: 
S7: SM-G930P, SM-G930A, SM-G930T, SM-G930V
S7 Edge: SM-G935P, SM-G935A, SM-G935T, SM-G935V

### A full bug report captured from the device
We are currently unable to get a logcat as Nougat hasn't rolled out on the S7 devices in our country yet. Will follow up as soon as Nougat rolls out.

**Comment by ojw28** [comment] 2017-03-21 10:04
We've not heard any reports of this. It's pretty unlikely this is happening with Google/YouTube services, else I suspect we'd have heard about it.  It's unlikely to be anything at the level of the DASH manifest or the container either, since that's all handled by ExoPlayer code. That leaves the device decoders. Is there something special/unusual about the codecs / resolutions / content of your streams?

**Comment by uyjulius** [comment] 2017-03-22 01:24
Hi,

I talked to our media team and they said that there is nothing unique that we put in our streams. We're following the regular standards. It could be decoder related since this did not happen pre nougat on S7 and S7 edge. We'll update again as soon as we get a Nougat update on our S7. By then we'll be able to fill in more details. 

Not sure if this is incidental too but the reports come from S7 and S7 Edges from US carriers (AT&T, Sprint, T-Mobile and Verizon) We have yet to receive reports from other S7/S7 Edge variants.

**Comment by ojw28** [comment] 2017-03-22 12:43
Do you know if YouTube is working correctly on these devices? I've not heard anything to suggest otherwise. Wikipedia suggests that China and US variants use a Qualcomm SoC vs an Exynos SoC for other markets, which could be relevant. It could also be that the roll-out of Nougat hasn't reached any non-US devices yet.

**Comment by uyjulius** [comment] 2017-03-23 01:28
Hi ojw28,

Thanks for looking into this! Will check with our users. They typically take time to respond. I'll update this thread as soon as we get any information from them. 

On the sidenote, does YouTube have some form of fallback mechanism to a regular MP4 stream if the phones can't support DASH? We had issues with low end devices unable to play DASH streams yet MP4 works just fine. We think it's likely due to the processor unable to handle the activities in the ExoPlayer. Asking this question in the assumption that YouTube may have a mechanism to turn off DASH streams for phones which runs into problems in streaming it and thus defaults to a regular MP4. So we may actually have reports coming back to us saying that YouTube ran just fine.

**Comment by ojw28** [comment] 2017-03-23 12:25
They definitely have the ability to deliver regular MP4 streams, but as far as I know they don't have a dynamic fallback that will transparently fall back from DASH to regular MP4 on a given device. I think it's more of a back-end configuration thing where certain devices can be blacklisted for DASH streams. So if YouTube DASH playbacks are failing on S7, I'd expect users to notice.

**Comment by teshiburu** [comment] 2017-03-27 16:17
I've been having an issue that I imagine is being caused by this bug, I use plex and am unable to direct play media using their version of exo, on an s7 edge IF the media is in the 10 bit color space, i can supply logs if they will help or even media samples but so far ive only seen the issue on x264 10bit files

http://forums.plex.tv/discussion/comment/1401724

**Comment by ojw28** [comment] 2017-03-27 16:19
I don't think that's related. 10 bit color scheme definitely falls into the "special case" category. 10 bit color depth is unsupported on Android except for some HDR Android TV devices with tunneled mode enabled.

**Comment by uyjulius** [comment] 2017-03-29 08:53
Hi ojw28,

Some of our users got back to us saying that YouTube plays just fine on their end. We also received a fresh report from S7 Active (SM-G891A) reporting the same behavior, right after updating to Android 7.0. 

We contacted Samsung on this issue. Will keep you in the loop if anything comes up. The same might occur on the new S8 devices.

**Comment by xdestiny110** [comment] 2017-04-27 03:56
Is this bug fixed? I got the same problem when I update OS from 6.0.1 to 7.0. My device model is SM-G9350. I can hear voice but image is stuck. It drop all buffer in MediaCodecVideoTrackRenderer because of timeout.

**Comment by uyjulius** [comment] 2017-04-28 01:19
Thanks for sharing this. We tested this thinking that this might be a Samsung OS issue but the S8, which runs Android 7.0 as well does not exhibit this issue. We have yet to get our hands on an S7 running 7.0.

**Comment by uyjulius** [comment] 2017-05-08 01:12
We have just received an update for our S7 device SM-G930FD to Android 7.0. Exoplayer DASH playback runs just fine. The same issue does not manifest on an S8 as well.

**Comment by hare989** [comment] 2017-05-31 09:51
I'm also having playback issues with ExoPlayer 1.5.4 on devices: Samsung Galaxy S7 Edge SM-G935T (working fine with SM-G935F with kernel version 3.18.14), Samsung Galaxy S3 Tab, Lenovo P2. But I also noticed that these devices have same kernel version 3.18.31. Unfortunately, I don't have any of these devices with such kernel version to test. I hope that you could provide me any clue regarding this issue.

**Comment by ojw28** [comment] 2017-08-04 17:58
What's the current status of this issue? Have Samsung fixed it via a software update?

**Comment by uyjulius** [comment] 2017-08-07 02:16
Hi ojw28,

We didn't check further with them. We simply fell back to native on phones which have shown evidences of not being able to support ExoPlayer.

**Comment by uyjulius** [comment] 2017-08-07 02:22
Just a follow up,

Sony Bravia updated to Android 7.0.0 have started exhibiting the same behavior so we disabled DASH playback on them as well. We haven't checked if 2.x releases work.

**Comment by ojw28** [comment] 2017-08-07 08:42
This is pretty strange. There must be _something_ different about the affected streams, given major providers (YouTube, Play Movies, Facebook, Netflix etc) appear to be unaffected. To the best of my knowledge in any case; I'm pretty sure we'd have heard from these providers if there were problems on the S7. Have you managed to reproduce the issue locally yet? If so, could you please provide a full bug report?

**Comment by uyjulius** [comment] 2017-08-07 09:15
No unfortunately. In Singapore where I live, the S7 Android 7.0 variant works just fine and the Sony Bravia Android 7.0 update is not yet available. In our logs, only the US variants of the S7 are running into this issue. I believe these companies should have a mechanism to fall back to MP4 if DASH streams don't work. 

Also, the test comes from r1.5 version of ExoPlayer. We haven't been able to test with S7 running Exoplayer r2.x. It is likely that these companies already have the 2.x ExoPlayer which would have probably resolved the issue. From the reports of others, it does seem like only 1.5.x are affected.

**Comment by ojw28** [comment] 2017-10-02 00:20
YouTube (and until very recently Play Movies) still use V1 ExoPlayer, and have not been affected by the issue described. On what reports are you basing the assertion that it appears only V1 is affected?

I think we'll need to close this unless someone provides some actionable information, like clear reproduction steps in the ExoPlayer demo app, a full bug report etc. There's just nothing we can actually do given the amount of information currently provided here.

**Comment by uyjulius** [comment] 2017-10-02 02:34
We've made a workaround for this on our side so it is no longer a pain point on our side. Unfortunately, we weren't able to get our hands on those devices exhibiting this issue. We can close this.

**Closed as completed** 2017-10-02 02:36 UTC
Labels: need more info
