### ISSUE TITLE
Dolby Vision - Decoder init failed:  

### ISSUE THREAD

**Issue by SalvinStephen** [google/ExoPlayer#3788] opened 2018-02-02 11:17 UTC
### Issue description
The exoplayer throws decoder initialization error.

### Reproduction steps
Try to stream video on exoplayer in any Dolby Vision supported device.
### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com including the issue number in the subject line.

### Version of ExoPlayer being used
Exoplayer version:'com.google.android.exoplayer:exoplayer:r2.5.1'

### Device(s) and version(s) of Android being used
Android 7.0 or above supported device

### A full bug report captured from the device
```
01-11 00:21:04.534: W/Binder:3036_1(3135): type=1400 audit(0.0:1715): avc: denied { sys_ptrace } for capability=19 scontext=u:r:system_control:s0 tcontext=u:r:system_control:s0 tclass=capability permissive=0
01-11 00:21:04.534: W/Binder:3036_1(3135): type=1400 audit(0.0:1716): avc: denied { read } for name="dolby_vision_enable" dev="sysfs" ino=4057 scontext=u:r:system_control:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): Renderer error.
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): com.google.android.exoplayer2.ExoPlaybackException
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:395)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at android.os.Looper.loop(Looper.java:154)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1/27, null, video/avc, -1, null, [960, 540, -1.0], [-1, -1])
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	... 9 more
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): Caused by: java.lang.IllegalArgumentException
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at android.media.MediaCodec.native_configure(Native Method)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at android.media.MediaCodec.configure(MediaCodec.java:1898)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:403)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:371)
01-11 00:21:04.557: E/ExoPlayerImplInternal(13072): 	... 8 more
01-11 00:21:04.560: E/EventLogger(13072): playerFailed [2.80]
01-11 00:21:04.560: E/EventLogger(13072): com.google.android.exoplayer2.ExoPlaybackException
01-11 00:21:04.560: E/EventLogger(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:395)
01-11 00:21:04.560: E/EventLogger(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)
01-11 00:21:04.560: E/EventLogger(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)
01-11 00:21:04.560: E/EventLogger(13072): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432)
01-11 00:21:04.560: E/EventLogger(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
01-11 00:21:04.560: E/EventLogger(13072): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)
01-11 00:21:04.560: E/EventLogger(13072): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
01-11 00:21:04.560: E/EventLogger(13072): 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-11 00:21:04.560: E/EventLogger(13072): 	at android.os.Looper.loop(Looper.java:154)
01-11 00:21:04.560: E/EventLogger(13072): 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-11 00:21:04.560: E/EventLogger(13072): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1/27, null, video/avc, -1, null, [960, 540, -1.0], [-1, -1])
01-11 00:21:04.560: E/EventLogger(13072): 	... 9 more
01-11 00:21:04.560: E/EventLogger(13072): Caused by: java.lang.IllegalArgumentException
01-11 00:21:04.560: E/EventLogger(13072): 	at android.media.MediaCodec.native_configure(Native Method)
01-11 00:21:04.560: E/EventLogger(13072): 	at android.media.MediaCodec.configure(MediaCodec.java:1898)
01-11 00:21:04.560: E/EventLogger(13072): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:403)
01-11 00:21:04.560: E/EventLogger(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:371)
01-11 00:21:04.560: E/EventLogger(13072): 	... 8 more
01-11 00:21:04.562: D/OmxComponentManagerImpl(3117): DecreaseEntryNumByName pEntry->mNum=2, pEntry->mMaxNum:4,componentName:OMX.amlogic.avc.decoder.awesome
01-11 00:21:04.562: I/omx_core(3117): OMX_freeHandle_num_= 1
01-11 00:21:04.563: D/AmlogicVideoDecoderAwesome(3117): ~AmlogicVideoDecoderAwesome
01-11 00:21:04.572: E/PlayerActivity(13072): playerFailed: 
01-11 00:21:04.572: E/PlayerActivity(13072): com.google.android.exoplayer2.ExoPlaybackException
01-11 00:21:04.572: E/PlayerActivity(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:395)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at android.os.Looper.loop(Looper.java:154)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-11 00:21:04.572: E/PlayerActivity(13072): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1/27, null, video/avc, -1, null, [960, 540, -1.0], [-1, -1])
01-11 00:21:04.572: E/PlayerActivity(13072): 	... 9 more
01-11 00:21:04.572: E/PlayerActivity(13072): Caused by: java.lang.IllegalArgumentException
01-11 00:21:04.572: E/PlayerActivity(13072): 	at android.media.MediaCodec.native_configure(Native Method)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at android.media.MediaCodec.configure(MediaCodec.java:1898)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:403)
01-11 00:21:04.572: E/PlayerActivity(13072): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:371)
01-11 00:21:04.572: E/PlayerActivity(13072): 	... 8 more
01-11 00:21:04.572: V/dj(13072): onError() & canProcess val= true
01-11 00:21:04.573: I/ExoPlayerImpl(13072): Release de6dbc3 [ExoPlayerLib/2.5.1] [needle, AFTN, Amazon, 25] [goog.exo.core, goog.exo.hls]
01-11 00:21:04.576: D/EventLogger(13072): videoDisabled [2.82]
01-11 00:21:04.576: D/EventLogger(13072): audioDisabled [2.82]
```

**Comment by ojw28** [comment] 2018-02-02 13:06
Can you provide details of a specific device running Android (not FireOS) that has this issue? Please also provide media that we can use to reproduce the issue. If this issue is occurring on FireOS devices only, you need to report it to Amazon.

**Comment by ojw28** [comment] 2018-02-26 19:33
Closing due to lack of further information.

**Closed as completed by ojw28** 2018-02-26 19:33 UTC
Labels: need more info
