### ISSUE TITLE
NPE in ExtractorMediaSource

### ISSUE THREAD

**Issue by ethanblake4** [google/ExoPlayer#3796] opened 2018-02-05 06:17 UTC
Stack trace: 
```java
java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.source.MediaSource$Listener.onSourceInfoRefreshed(com.google.android.exoplayer2.source.MediaSource, com.google.android.exoplayer2.Timeline, java.lang.Object)' on a null object reference
        at com.google.android.exoplayer2.source.ExtractorMediaSource.notifySourceInfoRefreshed(ExtractorMediaSource.java:380)
        at com.google.android.exoplayer2.source.ExtractorMediaSource.onSourceInfoRefreshed(ExtractorMediaSource.java:372)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod.maybeFinishPrepare(ExtractorMediaPeriod.java:555)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod.access$000(ExtractorMediaPeriod.java:51)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$1.run(ExtractorMediaPeriod.java:153)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
This happened randomly when playing a new queue in my music player app. I wasn't doing anything different than usual, but here is the relevant code, slightly edited for clarity, that was executing at the time: 
```kotlin
val i = 0; while (i < dynamicSource.size) {
     dynamicSource.removeMediaSource(i)
}
val sources = MutableList(tracks.size, { z -> sourceFromTrack(tracks[z]).second})
dynamicSource.addMediaSources(sources)
```

`dynamicSource` is a `DynamicConcatenatingMediaSource`.

`sourceFromTrack` returns an `ExtractorMediaSource` based on a `MediaSource` that tails from a `RandomAccessFile`.

This was tested on a Pixel 2 XL running 8.0.1 with ExoPlayer 2.6.1. I've tested the app hundreds of times and never seen this issue before so I cannot reproduce it. It appears that this is the same as #1914 but that issue is closed.

**Comment by tonihei** [comment] 2018-02-05 11:48
Thanks for reporting. This is a bug caused by removing a currently playing or loading child `MediaSource` from the `DynamicConcatenatingMediaSource`. It seems this bug has been in the code all the time, but only recent changes in version 2.6.1 made the `ExtractorMediaSource` throw this NPE because of this bug.

We already have a fix which will be pushed to the dev-branch soon.

**Comment by tonihei** [comment] 2018-02-09 13:53
Closing because issue is fixed on the dev branch.

**Closed as completed by tonihei** 2018-02-09 13:53 UTC
Labels: bug
