### ISSUE TITLE
no such column: title exception

### ISSUE THREAD

**Issue by noman87** [google/ExoPlayer#8420] opened 2021-01-01 12:07 UTC
Firebase crashlytics  showing crashes on different users devices, however it is not reproducing during development 

Version:**com.google.android.exoplayer:exoplayer-core:2.12.0**

**Exception:** 
```
Caused by android.database.sqlite.SQLiteException: no such column: title (code 1 SQLITE_ERROR)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:942)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:155)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:142)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
       at com.google.android.exoplayer2.offline.DefaultDownloadIndex.loadDownloadsFromVersion2(DefaultDownloadIndex.java:360)
       at com.google.android.exoplayer2.offline.DefaultDownloadIndex.ensureInitialized(DefaultDownloadIndex.java:289)
       at com.google.android.exoplayer2.offline.DefaultDownloadIndex.getDownload(DefaultDownloadIndex.java:176)
```

**Comment by andrewlewis** [comment] 2021-01-05 11:36
@marcbaechinger @ojw28 Please could you take a look?

**Comment by ojw28** [comment] 2021-01-05 13:18
I think @christosts might have implemented the relevant changes, so is probably the best person to take a look.

**Comment by noman87** [comment] 2021-01-05 13:35
i m getting continues crashes on firebase

**Comment by christosts** [comment] 2021-01-05 17:01
In ExoPlayer version 2.12.0, there's a change in the downloads database table schema. The codepath indicated by the stack trace is executed when the player is upgrading the database to the latest version ([TABLE_VERSION = 3](https://github.com/google/ExoPlayer/blob/r2.12.0/library/core/src/main/java/com/google/android/exoplayer2/offline/DefaultDownloadIndex.java#L42)). The upgrade is executed only if the previous downloads database version is `2` and the table exists. The exception message indicates that column `title` is not found on the old table, but this column had to be present in the table in version 2 anyway.

May I ask:
- Did you update the ExoPlayer version recently to v2.12? If yes, from what version? 
- Is your app using any custom components for downloads, e.g. a custom DownloadIndex, or have you modified the database directly?
- Is your app using downloads from multiple threads? 
- Is the app creating multiple instances of `DownloadManager` and/or `DownloadService`?

**Comment by noman87** [comment] 2021-01-06 14:02
**Question**
 Did you update the ExoPlayer version recently to v2.12? If yes, from what version?

**Answer** 
yes, from 2.10.4 to 2.12.0

**Question** 
Is your app using any custom components for downloads, e.g. a custom DownloadIndex, or have you modified the database directly?

**Answer**  
i check the download status before making the download request like this and this is the line where i am facing crash 
`val download = audioDownloadManager.getDownloadManager().downloadIndex.getDownload(url)`

I m not modifying database directly nor i call any exoplayer database functionality directly, however i m using this for delete the downloaded items 
`DownloadService.sendRemoveDownload(context, MyDownloadService::class.java, it, false)`  

**Question** 
Is your app using downloads from multiple threads?

**Answer**  

I made download request on main thread, there is a list of mp3 files which i need to download, i made request  like this  if file not status is STATE_COMPLETED in for loop
`DownloadService.sendAddDownload(context,MyDownloadService::class.java,downloadRequest,true)`

**Question**
Is the app creating multiple instances of DownloadManager and/or DownloadService?

**Answer**
NO, i made single instance of `DownloadManager` and use it in whole application, i made `MyDownloadService` which extend `DownloadService` which is use to make download request like this 
`DownloadService.sendAddDownload(context,MyDownloadService::class.java,downloadRequest,true)`

**Comment by christosts** [comment] 2021-01-06 19:32
Please ensure that your app creates a single instance of `DownloadManager`, it is something that has come up again in the past, sometimes there are bugs in the app configuration (for example [issue 6516](https://github.com/google/ExoPlayer/issues/6516#issuecomment-648663819)).

The database upgrade is kicked-off by the constructor of the `DownloadManager` but it is executed in the `DownloadManager`'s background thread. One hypothesis could be that while the database is upgraded, the call to `getDownloadManager().downloadIndex.getDownload(url)` is introducing a race condition that is not properly handled.

Can you check if the call to `getDownloadManager().downloadIndex.getDownload(url)` happens before the `DownloadManager` is initialized? You can check if the `DownloadManager` is initialized with two ways: a direct call to [DownloadManager.isInitialized()](https://github.com/google/ExoPlayer/blob/r2.12.0/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadManager.java#L295) or adding a [DownloadManager.Listener](https://github.com/google/ExoPlayer/blob/r2.12.0/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadManager.java#L74) to the `DownloadManager` and overriding the [onInitialized](https://github.com/google/ExoPlayer/blob/r2.12.0/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadManager.java#L81) callback.

For debugging this, consider the following scenario: use your previous application version (the one using ExoPlayer r2.10.4) and download media (you may want to keep a back up of the database to repeat this test quickly, the database name is `exoplayer_internal.db`). Then update ExoPlayer to r.2.12.2 and start you application. When the app creates the `DownloadManager` instance, that should kick-off the database upgrade. At that point, please check whether calls to `getDownloadManager().downloadIndex.getDownload(url)` are happening before the `DownloadManager` is initialized, and if yes, try to wait until `DownloadManager` it is initialized before accessing the database with the `DownloadIndex`. 

In the meantime, I will try to replicate a similar scenario to see if the synchronisation around the database upgrade has any loop holes and needs further safeguarding.

**Comment by christosts** [comment] 2021-01-07 14:38
Update: I can verify there is a race condition triggered if the app tries to access the database through `DownloadManager.downloadIndex` while the `DownloadManager` is still initialising. This should happen on first time the app updates from a version prior to 2.12 to a version after 2.12 and ExoPlayer had downloads in its database already. If the race condition is triggered, the player crashes with the same exception details. We will submit a fix and I will update the issue when the fix is commited and also available for use.

In the meantime, assuming your app is crashing because of this bug, please ensure that accessing to the database through the DownloadIndex happens after the `DownloadManager` is initialized (I listed a couple of ways onl the comment above).

**Comment by noman-noor** [comment] 2021-01-07 14:44
Thank you so much for your quick support and assistance, i m trying to handle initialization issue, approx how much time it will take to fix from your side?

**Comment by christosts** [comment] 2021-01-07 14:52
The commit should be in the dev-v2 branch within the week and we plan a minor release (2.12.3) within January.

**Comment by christosts** [comment] 2021-01-08 15:55
Just an update that the a fix has been pushed to the dev-v2 branch. I will update this issue again when the commit is part of a released version.

**Comment by noman-noor** [comment] 2021-01-08 15:57
Thank you so much @christosts let me implement it and update you

**Comment by noman-noor** [comment] 2021-01-09 06:40
@christosts  do i need to handle initialize check now or library handling it internally ? 
does dependency works like this `com.google.android.exoplayer:exoplayer-core:dev-v2` ?

**Comment by christosts** [comment] 2021-01-11 11:20
> @christosts do i need to handle initialize check now or library handling it internally ?

The library will synchronize initialization internally and you should not have to wait for the DownloadManager to be initlaized. However, depending on how you are structuring your app, it might be better to wait for DownloadManager to be initiliazed anyway. If you access the database through `DownloadManager.downloadIndex` while the DownloadManager is still initliazing, this will block your thread until the manager is initialized. You might want to avoid having the thread blocked anyway.

> does dependency works like this `com.google.android.exoplayer:exoplayer-core:dev-v2` ?

Issue #3859 describes how to depend on the snapshot version of exoplayer, which however seems to not be working at the moment. If you want to test with the dev-v2 branch, you need to clone the repo source code and build it to your project locally. You may want to follow #3859 for updates when the issue is fixed (note: using the snapshot is recommended only for testing fixes, applications should depend on stable releases of ExoPlayer).  Alternatively, you may wait for a few days, we plan to release 2.12.3 soon.

**Comment by icbaker** [comment] 2021-01-11 11:27
> If you want to test with the dev-v2 branch, you need to clone the repo source code and build it to your project locally.

FYI there's instructions for that here:
https://github.com/google/ExoPlayer/blob/release-v2/README.md#locally

**Comment by christosts** [comment] 2021-01-13 14:40
ExoPlayer release 2.12.3 is out, including the fix for synchronizing the database initialization. I'm closing this issu, feel free to re-open if the problem persists.

**Closed as completed by christosts** 2021-01-13 14:40 UTC
Labels: bug, need more info
