### ISSUE TITLE
Exoplayer in recycler view

### ISSUE THREAD

**Issue by djmalkar** [google/ExoPlayer#2455] opened 2017-02-15 05:57 UTC
I have integrated exoplayer in my recycler view. So far i am able to integrate it successfully. Now i want to increase its performance. How to reuse SimpleEXoPlayer when use click other video in list item of recycler view. When new video is about to be played how to pass new video url and hot to efficiently implement simpleExoPlayer. Right now i am creating new instance when new list video item is played

**Comment by ojw28** [comment] 2017-03-16 12:31
Duplicate of #867.

**Closed as completed by ojw28** 2017-03-16 12:31 UTC
Labels: duplicate
