### ISSUE TITLE
JDK 11 Compilation issue

### ISSUE THREAD

**Issue by zhangnin** [google/ExoPlayer#10030] opened 2022-03-07 09:02 UTC
Environment：
JDK 11
Studio  7.1.2
Gradle  gradle-7.2-bin.zip

This is a warning (这是一个警告：)
[Processor] Library 'C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.google.android.exoplayer\exoplayer-ui\2.14.1\ba7feb79d652fc0593865e906e7a9a6d7d8d9442\exoplayer-ui-2.14.1.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

**Comment by ojw28** [comment] 2022-03-07 19:50
Is this warning actually causing a real problem? I think it can be safely ignored.

**Comment by icbaker** [comment] 2022-03-07 20:01
I think this is a duplicate of https://github.com/google/ExoPlayer/issues/8580

**Comment by ojw28** [comment] 2022-03-07 20:04
Yes, that's the reason why the warning is output. Closing as duplicate because it looks like we've already confirmed that it's harmless and expected. Thanks!

**Closed as completed by ojw28** 2022-03-07 20:04 UTC
Labels: duplicate
