### ISSUE TITLE
ExtractorSampleSource crashed at the place maybeStartLoading

### ISSUE THREAD

**Issue by kxun** [google/ExoPlayer#584] opened 2015-06-26 19:53 UTC
0		com.google.android.exoplayer.util.Assertions.b(Assertions.java:66)
1		com.google.android.exoplayer.extractor.ExtractorSampleSource.f(ExtractorSampleSource.java:455)
2		com.google.android.exoplayer.extractor.ExtractorSampleSource.d(ExtractorSampleSource.java:401)
3		com.google.android.exoplayer.extractor.ExtractorSampleSource.d(ExtractorSampleSource.java:337)
4		com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:272)
5		android.os.Handler.dispatchMessage(Handler.java:102)
6		android.os.Looper.loop(Looper.java:211)
7		android.os.HandlerThread.run(HandlerThread.java:61)
8		com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

Any known issue on this and what might be the cause?

**Comment by ojw28** [comment] 2015-06-29 20:02
Can you get a stack trace that hasn't been pro-guarded? Also, does this still reproduce on the dev branch, and if so what steps are required to reproduce? We fixed a potential crash that could be related a few weeks ago (the player would fail if you disabled all renderers whilst paused, and then re-enabled one of them).

**Comment by ojw28** [comment] 2015-07-14 11:18
Closing due to lack of information.

**Closed by ojw28** 2015-07-14 11:18 UTC
Labels: need more info
