### ISSUE TITLE
Exoplayer doesn't run on Pixel Android 10 on emulator

### ISSUE THREAD

**Issue by rlissner** [google/ExoPlayer#6566] opened 2019-10-19 19:44 UTC
Before filing a bug:
-----------------------

When reporting a bug:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Issue description
Exoplayer downloaded yesterday.  Compiled Exoplayer-release-2 demo.  Runs fine compiled with Android 29 on an Android 25 device on emulator on Mac.  Same compile, but on a Pixel 29 device on emulator says (more or less) "there are video tracks on this file, but this device can't play them."

### [REQUIRED] Reproduction steps
Easy.  Download fresh demo.  Change build.gradle to 29.  Compile.  Run demo (main) on a Mac with Android Studio, emulator device is Pixel XL running 29.

### [REQUIRED] Link to test content
DOn't need.  It's your demo.

### [REQUIRED] A full bug report captured from the device
There is no bug report.  It just won't play the video.  I got here because I was having similar problems with JWPlayer, which is based on Exoplayer.

### [REQUIRED] Version of ExoPlayer being used
Sorry.  It was downloaded 10/18/2019

### [REQUIRED] Device(s) and version(s) of Android being used
Up to date Android Studio.  Compiled and max support is 29.

**Comment by ojw28** [comment] 2019-10-21 10:53
This does not reproduce for me. I suspect that you've somehow got an old (e.g. pre-release) version of the emulator system image.

Please attach a bug report as requested in the issue template, which, among other things, would allow us to confirm exactly which version of the emulator system image you're using. It's not correct to state that there's no bug report, since you can capture one whenever you want. Shortly after you reproduce the problem, please run `adb bugreport` in the terminal, which will generate a bug report for you to send us.

**Comment by rlissner** [comment] 2019-10-21 22:13
Thank you for the very quick response.  I don't have adb installed, but
will do so tonight unless I hear from JWPlayer which is also not working.
It's not an old copy of the emulator.

Later I did hear from JWPlayer, they gave me a bunch of suggestions.

Whatever works, I will pass on.

Robert Lissner
4790 Caughlin Parkway PMB 519, Reno NV 89519
775-750-5537 call or text

**Comment by ojw28** [comment] 2019-10-22 09:39
If you have a working version of Android Studio then by I'm pretty sure you do have adb installed. As far as I know Android Studio requires you to have an Android SDK installed (at least to do anything useful). And adb is part of the Android SDK (it should be under the `platform-tools` sub-directory).

**Comment by rlissner** [comment] 2019-11-06 04:12
Well I haven't been able to run adb, so I can only tell you this:
Exoplayer runs nicely on a Pixel 3
It only plays the audio portion of a video file on the 29.2.1 emulator on a
Pixel 3 XL.  There is no new emulator, and my Android Studio is completely
up to date.
Your documentation says that some 3rd party emulators might not work.  The
Pixel code if, of course, definitely Google and part of the SDK.


I've resolved my JWPlayer issue, so this is just FYI if you care.
Robert Lissner
4790 Caughlin Parkway PMB 519, Reno NV 89519
775-750-5537 call or text

**Comment by ojw28** [comment] 2019-11-06 11:17
We do care :). However there's currently nothing actionable for us to do here, since the issue doesn't reproduce for us and we don't have an `adb bugreport` to provide further information. Closing for now. Please provide the required information if you're able to do so in the future, and we can re-open it. Thanks!

**Closed as completed by ojw28** 2019-11-06 11:17 UTC
Labels: question
