### ISSUE TITLE
Dash Is not Live Playing in ExoPlayer 2.5.4 on Android M Platform 

### ISSUE THREAD

**Issue by rakesharyais** [google/ExoPlayer#3469] opened 2017-11-16 04:46 UTC
### Issue description
Dash Live Is not  Playing in ExoPlayer 2.5.4 on Android M Platform 

### Reproduction steps
I used this url to play Dash LIve in ExoPlayer 2.5.4
http://vm2.dashif.org/livesim/testpic_2s/Manifest.mpd which is not playing on Android M.
Where as it plays properly in Android N and O

Note: Tried to play the same url in Exoplayer Sample App and even here it does not play 

### Version of ExoPlayer being used
ExoPlayer 2.5.4

### Device(s) and version(s) of Android being used
Device :Samsung galaxy S6 Android M

### A full bug report captured from the device

```
11-16 09:51:45.759 12286 12552 W ChunkedTrackBlacklist: Blacklisting failed (cannot blacklist last enabled track): responseCode=404, format=Format(V300, video/mp4, video/avc, 300000, null, [640, 360, 30.0], [-1, -1])

11-16 09:51:45.759 12286 12552 W ChunkedTrackBlacklist: Blacklisting failed (cannot blacklist last enabled track): responseCode=404, format=Format(A48, audio/mp4, audio/mp4a-latm, 48000, eng, [-1, -1, -1.0], [2, 48000])

11-16 09:51:45.759 12286 12565 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

11-16 09:51:45.759 12286 12565 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

11-16 09:51:45.759 12286 12286 E EventLogger: internalError [2.03, loadError]

11-16 09:51:45.759 12286 12286 E EventLogger: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

11-16 09:51:45.759 12286 12286 E EventLogger: 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(Unknown Source)

11-16 09:51:45.759 12286 12286 E EventLogger: 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(Unknown Source)

11-16 09:51:45.759 12286 12286 E EventLogger: 	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(Unknown Source)

11-16 09:51:45.759 12286 12286 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Unknown Source)

11-16 09:51:45.759 12286 12286 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

11-16 09:51:45.759 12286 12286 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

11-16 09:51:45.759 12286 12286 E EventLogger: 	at java.lang.Thread.run(Thread.java:818)

11-16 09:51:45.759 12286 12564 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

11-16 09:51:45.769 12286 12564 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

11-16 09:51:45.769 12286 12286 E EventLogger: internalError [2.03, loadError]

11-16 09:51:45.769 12286 12286 E EventLogger: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

11-16 09:51:45.769 12286 12286 E EventLogger: 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(Unknown Source)

11-16 09:51:45.769 12286 12286 E EventLogger: 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(Unknown Source)

11-16 09:51:45.769 12286 12286 E EventLogger: 	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(Unknown Source)

11-16 09:51:45.769 12286 12286 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Unknown Source)

11-16 09:51:45.769 12286 12286 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

11-16 09:51:45.769 12286 12286 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

11-16 09:51:45.769 12286 12286 E EventLogger: 	at java.lang.Thread.run(Thread.java:818)

11-16 09:51:45.779 12286 12564 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

11-16 09:51:45.779 12286 12565 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

11-16 09:51:45.779 12286 12564 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

11-16 09:51:45.779 12286 12565 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

11-16 09:51:46.579 12286 12552 W ChunkedTrackBlacklist: Blacklisting failed (cannot blacklist last enabled track): responseCode=404, format=Format(V300, video/mp4, video/avc, 300000, null, [640, 360, 30.0], [-1, -1])

11-16 09:51:46.579 12286 12552 W ChunkedTrackBlacklist: Blacklisting failed (cannot blacklist last enabled track): responseCode=404, format=Format(A48, audio/mp4, audio/mp4a-latm, 48000, eng, [-1, -1, -1.0], [2, 48000])

11-16 09:51:46.579 12286 12286 E EventLogger: internalError [2.85, loadError]
```

**Comment by AquilesCanta** [comment] 2017-11-16 10:53
It is possible that the issue is related to the clock of the device/timezone configuration. We will run a few experiments and let you know. @ojw28 can provide advice about how to generate the media to prevent this.

**Comment by ojw28** [comment] 2017-11-16 11:49
As @AquilesCanta says, an inaccurate device clock could cause this problem for the type of DASH manifest linked, particularly if the device clock is even slightly fast (a slow clock is less likely to be a problem).

In general, DASH manifests that rely on the client knowing the current time, as is the case in this example, should include a `UTCTiming` element to allow the client to resolve the current time rather than relying on the device clock. Otherwise you will inevitably run into this type of problem; you can't rely on device clocks being set accurately.

**Comment by AquilesCanta** [comment] 2017-11-16 18:19
@rakesharyais, could you please make sure the device's clock and timezone are correct when you start playing the media, and contact us back once you do? 

If you do control the media, please try the UTCTiming tag that @ojw28 suggested. If it works there is not much we can do about it, but we should definitely discard any other possibility before assuming there is an error in ExoPlayer, as it seems to reproduce fine in normal cases. Thanks!

**Comment by rakesharyais** [comment] 2017-11-17 05:55
@AquilesCanta We are not controlling the media .
we are just using the url  (http://vm2.dashif.org/livesim/testpic_2s/Manifest.mpd) to play

**Comment by AquilesCanta** [comment] 2017-11-17 10:06
> @rakesharyais, could you please make sure the device's clock and timezone are correct when you start playing the media, and contact us back once you do?

**Comment by ojw28** [comment] 2017-11-17 19:25
@rakesharyais - Manifests in the style of the one you link to really should contain a `UTCTiming` element to help avoid playback failure if the device clock is incorrect. This is the most likely problem here. I suspect this is just a test stream that's not indicative of what anyone would actually deploy in production (if they're sensible ;)).

**Comment by ojw28** [comment] 2017-11-17 19:25
Closing on the assumption that the device clock was slightly fast. Please re-open if you can validate this is not the case.

**Closed as completed by ojw28** 2017-11-17 19:25 UTC
Labels: question
