### ISSUE TITLE
Consider allowing non-idr frames as keyframes in TsExtractor.

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#982] opened 2015-11-24 08:03 UTC
H264Reader fails identify format if created with *idrKeyframesOnly=true*, which is **default** for *TsExtractor*.
Is it expected behavior?

Condition (in my case):
* multicast (UdpDataSource) stream with MPEG-2 TS
* video is h264
* no extractor provided or default one (*TsExtractor()*)

In this situation, player never leaves *preparing* state, cause *ExtractorSampleSource* never gets format for h264 track (*haveFormatsForAllTracks*)

Problemmatic part (*H264Reader*):
```java
// c-tor
ifrParserBuffer = (idrKeyframesOnly) ? null : new IfrParserBuffer();

// consume(...)
// ...
if (ifrParserBuffer != null && ifrParserBuffer.isCompleted()) {
  int sliceType = ifrParserBuffer.getSliceType();
  isKeyframe |= (sliceType == FRAME_TYPE_I || sliceType == FRAME_TYPE_ALL_I);
}

// ...
if (isKeyframe && !hasOutputFormat && sps.isCompleted() && pps.isCompleted()) {
  output.format(parseMediaFormat(sps, pps));
  hasOutputFormat = true;
}
```
*isKeyframe* is detected **only** if *idrKeyframesOnly=false*. So even if we've got sps/pps - we won't identify it.

**Comment by ojw28** [comment] 2015-11-26 12:28
I believe this is expected behavior. You're free to set idrKeyframesOnly=true in your app, so this isn't an issue as such. It's more a question of whether the default should be true rather than false. I believe it's correct that it's set to false, since we expect most streams to contain IDR frames and I seem to remember we saw some temporary corruption on the visual output when setting it to false in some cases.

**Comment by stari4ek** [comment] 2015-11-26 19:30
but it can identify format in both cases why limit it only to *idrKeyframesOnly=false*?
```java
if ((isKeyframe || ifrParserBuffer == null) &&
   && !hasOutputFormat && sps.isCompleted() && pps.isCompleted()) {
```
otherwise it looks like inconsistence with different state behavior (with *idrKeyframesOnly=true* it will stay in "waiting for sps/pps" infinitely)

**Comment by ojw28** [comment] 2015-11-27 10:57
As per above: I seem to remember we saw some temporary corruption on the visual output when setting it to false in some cases. I think this is because the non-IDR frames that can contain this information can also have decoding dependencies on prior frames, depending on the way in which the content is encoded. If they do, they are not valid points from which you can start feeding the decoder.

It might be possible to do something more advanced to figure out whether a frame has decoding dependencies in prior frames. I'll leave this issue open to figure that out, but it's pretty low priority for us.

**Comment by ojw28** [comment] 2016-02-21 16:10
We have no current plans to do "something more advanced" as described above, so closing this.

**Closed by ojw28** 2016-02-21 16:10 UTC
Labels: enhancement
