### ISSUE TITLE
Settings PopUp dialog isn't displayed properly when using setDecorFitsSystemWindows(false) 

### ISSUE THREAD

**Issue by davidtrpchevski** [google/ExoPlayer#10879] opened 2022-12-21 00:22 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

NOTE: This happens only on 2.17.2 and up. On 2.17.1, this cannot be reproduced, there's no bug.

Pixel 4 Emulator running Android 12
Xiaomi Poco F3 running Android 12
Xiaomi Redmi 8 running Android 9

### Reproducible in the demo app?

Yes

### Reproduction steps

NOTE: This happens only on 1.0.0-beta01 and up. On 1.0.0-alpha03, this cannot be reproduced, there's no bug.

Try to hide the SystemUI (Status bar and Navigation bar) by using setDecorFitsSystemWindows(false)

Full code: 

```
fun Activity.hideSystemUI() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
        window.setDecorFitsSystemWindows(false)
        window.insetsController?.let {
            it.systemBarsBehavior = WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
            it.hide(WindowInsetsCompat.Type.systemBars())
        }
    } else {
        WindowCompat.setDecorFitsSystemWindows(window, false)
        WindowCompat.getInsetsController(window, window.decorView).apply {
            systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
            hide(WindowInsetsCompat.Type.systemBars())
        }
    }

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
        window?.attributes?.layoutInDisplayCutoutMode =
            WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
    }
}
```

### Expected result

NOTE: This happens only on 2.17.2 and up. On 2.17.1, this cannot be reproduced, there's no bug.

Version 1.0.0-alpha03

<img width="451" alt="image" src="https://user-images.githubusercontent.com/13114412/208789866-def179d5-b022-4865-8f2c-8208a24a58fd.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/13114412/208789884-71a09ba5-a111-43a9-bc65-29d028204cde.png">

### Actual result

NOTE: This happens only on 1.0.0-beta01 and up. On 1.0.0-alpha03, this cannot be reproduced, there's no bug.

Version 1.0.0-beta03

<img width="420" alt="image" src="https://user-images.githubusercontent.com/13114412/208789504-8e409d29-18b5-448d-8182-06e915505c89.png">
<img width="435" alt="image" src="https://user-images.githubusercontent.com/13114412/208790824-9f09c3d6-1215-47c6-b0aa-cc4e90270a21.png">

### Media

https://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=51AF5F39AB0CEC3E5497CD9C900EBFEAECCCB5C7.8506521BFC350652163895D4C26DEE124209AA9E&key=ik0

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-12-21 10:22
Thanks for reporting with super clear screenshots! I'm going to close this as a duplicate of https://github.com/androidx/media/issues/234 and continue the conversation there. The code is shared between this repo and the androidx/media repo - so any fixes made there will automatically land here too.

**Closed as completed by icbaker** 2022-12-21 10:22 UTC
Labels: duplicate
