### ISSUE TITLE
Set setPlayWhenReady  to false and then true removes the text track exoplayer  Issue

### ISSUE THREAD

**Issue by TarifHatoum** [google/ExoPlayer#3952] opened 2018-03-07 08:09 UTC
Issue description
setPlayWhenReady  to false and then true makes the text track exoplayer disappear and the text track is still checked

Steps to replicate the issue:
-Select a text track.
-Pause the player. 
-Keep it paused around 10 minutes.
-Press resume the caption disappeared and it is still selected.  

Version of ExoPlayer being used
ExoPlayer version used: 2.3.1

Device(s) and version(s) of Android being used
Tested with Google Pixel with Android 7.1

**Comment by ojw28** [comment] 2018-03-07 10:42
* Is the activity being recreated between pausing and resuming? If so, how is this issue different to https://github.com/google/ExoPlayer/issues/3915?
* Are these instructions for the main ExoPlayer demo app? If not, please provide reproduction steps for that app (if it doesn't reproduce there then that suggests the issue is in your own code). Please can you also be specific about what piece of media you're playing, so we can replicate exactly what you're doing.

**Comment by ojw28** [comment] 2018-03-20 20:25
Closing due to lack of follow up.

**Closed as completed by ojw28** 2018-03-20 20:25 UTC
Labels: need more info
