### ISSUE TITLE
Subtitle multiline window spacing

### ISSUE THREAD

**Issue by Gvex95** [google/ExoPlayer#9266] opened 2021-08-06 11:20 UTC
Hi, i am wondering is it possible to separate lines when there are more than one line drawn on screen.

Let me explain with example:

![example](https://user-images.githubusercontent.com/26479259/128502831-6f719cc9-ed35-4b72-9fde-eba2cb78f12a.jpg)

What i mean, is it possible to add spacing after first line like in picture?
What property is responding for handling this, if this is even possible.

Thanks in advice

**Comment by andrewlewis** [comment] 2021-08-06 11:35
@Gvex95 What subtitle format are you using (e.g., TTML)?

@icbaker Please could you take a look? I was wondering if this might be a duplicate of #7632 but I guess it depends what the format is.

**Comment by Gvex95** [comment] 2021-08-06 11:42
> @Gvex95 What subtitle format are you using (e.g., TTML)?
> 

Ttml and mp4 fragmented webvtt. But i was wondering if this is even possible to do, for all supported formats? 
I am willing to except any little tricks and hacks you suggest if currently there is no proper way of doing this (for example exposing some method like `setMultiLineSpacing(float px)`

**Comment by nigelmegitt** [comment] 2021-08-06 12:49
In TTML, set `tts:lineHeight` on a style applied to the `<p>` element to a larger number. It's very close to the CSS `line-height` property.

**Comment by Gvex95** [comment] 2021-08-09 07:40
> In TTML, set `tts:lineHeight` on a style applied to the `<p>` element to a larger number. It's very close to the CSS `line-height` property.

Yes, but if i don't have control over my subtitles, is there any hack i can do to make this happen?
Like i saw for https://github.com/google/ExoPlayer/issues/7516

If it is not possible, i think it would be nice feature to add, if u agree.

Thanks guys :)

**Comment by icbaker** [comment] 2021-08-09 08:06
#7632 tracks implementing support for TTML's `tts:lineHeight` property. I suspect that implementing that will require modifying `Cue` to add some sort of `lineHeight` field, and then implementing support for it in [`WebViewSubtitleOutput`](https://github.com/google/ExoPlayer/blob/r2.14.2/library/ui/src/main/java/com/google/android/exoplayer2/ui/WebViewSubtitleOutput.java) and [`CanvasSubtitleOutput`](https://github.com/google/ExoPlayer/blob/r2.14.2/library/ui/src/main/java/com/google/android/exoplayer2/ui/CanvasSubtitleOutput.java) (as well as writing the code to parse the property out of the TTML file of course).

Once `Cue` has this property then you'll be able to 'hackily' set it for every cue, even if you don't control the subtitle data (and regardless of the original subtitle format), by mutating the `List<Cue>` as it flows from the player to the screen. One place to do this is by subclassing `StyledPlayerView` and overriding `onCues`.

So I'm going to close this as a duplicate of #7632 - because once that's implemented this will be possible.

**Closed as completed by icbaker** 2021-08-09 08:06 UTC
Labels: duplicate

**Comment by Gvex95** [comment] 2021-08-09 08:28
> #7632 tracks implementing support for TTML's `tts:lineHeight` property. I suspect that implementing that will require modifying `Cue` to add some sort of `lineHeight` field, and then implementing support for it in [`WebViewSubtitleOutput`](https://github.com/google/ExoPlayer/blob/r2.14.2/library/ui/src/main/java/com/google/android/exoplayer2/ui/WebViewSubtitleOutput.java) and [`CanvasSubtitleOutput`](https://github.com/google/ExoPlayer/blob/r2.14.2/library/ui/src/main/java/com/google/android/exoplayer2/ui/CanvasSubtitleOutput.java) (as well as writing the code to parse the property out of the TTML file of course).
> 
> Once `Cue` has this property then you'll be able to 'hackily' set it for every cue, even if you don't control the subtitle data (and regardless of the original subtitle format), by mutating the `List<Cue>` as it flows from the player to the screen. One place to do this is by subclassing `StyledPlayerView` and overriding `onCues`.
> 
> So I'm going to close this as a duplicate of #7632 - because once that's implemented this will be possible.

Thanks @icbaker for such a detailed explanation. Have a great day :)
