### ISSUE TITLE
How to use IMA extension without autoplay?

### ISSUE THREAD

**Issue by Anton111111** [google/ExoPlayer#4300] opened 2018-05-25 13:09 UTC
Hi!
I want to show ads without autoplay enabled. For example if i remove     `player.setPlayWhenReady(true);` in the example:
https://github.com/google/ExoPlayer/blob/2b55c91af0afd1f50f689adb1046f1cf78c887f6/demos/ima/src/main/java/com/google/android/exoplayer2/imademo/PlayerManager.java#L98

I don't see ad. 
How to start show ad only when user click on play button ?

**Comment by Anton111111** [comment] 2018-05-25 13:40
Simple start demo from branch 
https://github.com/Anton111111/ExoPlayer/blob/autoplay/demos/ima/src/main/java/com/google/android/exoplayer2/imademo/PlayerManager.java
to reproduce this problem.

**Comment by Anton111111** [comment] 2018-05-25 15:18
Also if i set player.setPlayWhenReady(false);  how in example above i see in log the following Error:

```
05-25 18:15:02.683 16994-16994/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdError
    AdError [errorType: PLAY, errorCode: AdErrorCode [name: VIDEO_PLAY_ERROR, number: 400], message: There was an error playing the video ad.]
        at com.google.obf.ir.a(IMASDK:102)
        at com.google.obf.ij.a(IMASDK:73)
        at com.google.obf.jd.f(IMASDK:213)
        at com.google.obf.jd.a(IMASDK:44)
        at com.google.obf.je.b(IMASDK:39)
        at com.google.obf.je$1.shouldOverrideUrlLoading(IMASDK:4)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:339)
        at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:168)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:256)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
05-25 18:15:02.691 16994-16994/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: CONTENT_RESUME_REQUESTED
    Unexpected CONTENT_RESUME_REQUESTED without stopAd
05-25 18:15:02.696 16994-16994/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: ALL_ADS_COMPLETED
```

**Comment by Anton111111** [comment] 2018-05-30 05:17
I think this issue is not question. I think status must be changed to bug.

**Comment by andrewlewis** [comment] 2018-05-30 08:12
#3764 may be related.

**Comment by andrewlewis** [comment] 2018-05-30 09:06
This is the same failure mode as #3764: we pause the ad immediately but IMA raises an error and forces us to start playing the content. Marking this as a duplicate of that issue. I've asked the IMA SDK team to take a look and will update that issue when I hear back. Thanks!

**Closed as completed by andrewlewis** 2018-05-30 09:06 UTC
Labels: duplicate
