### ISSUE TITLE
can't play mp4 with exoplayer 2.7.0

### ISSUE THREAD

**Issue by imfondof** [google/ExoPlayer#6536] opened 2019-10-12 03:52 UTC
**Issue description：**
can't play mp4 with exoplayer 2.7.0

**Reproduction steps：**
here is my code :  https://github.com/Imfondof/exospecialdemo
(the mp4 url is http://filesystem1.bbtree.com/2019/10/11/cms/5673cc33-eeb8-440d-aeae-f30900b7b0fe.mp4)

**A full bug report captured from the device**
error:
E/LoadTask: Unexpected exception loading stream
java.lang.IllegalArgumentException
at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:264)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:408)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:364)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:355)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:186)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

**Version of ExoPlayer being used：**
2.7.0

**Device(s) and version(s) of Android being used：**
android8、android9

**Comment by Samrobbo** [comment] 2019-10-14 10:54
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

In particular, a full bug report, and the exact reproduction steps.

**Comment by imfondof** [comment] 2019-10-15 05:04
> Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
> 
> In particular, a full bug report, and the exact reproduction steps.

**Issue description：**
can't play mp4 with exoplayer 2.7.0

**Reproduction steps：**
here is my code :  https://github.com/Imfondof/exospecialdemo
(the mp4 url is http://filesystem1.bbtree.com/2019/10/11/cms/5673cc33-eeb8-440d-aeae-f30900b7b0fe.mp4)

**A full bug report captured from the device**
error:
E/LoadTask: Unexpected exception loading stream
java.lang.IllegalArgumentException
at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:264)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:408)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:364)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:355)
at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:186)
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

**Version of ExoPlayer being used：**
2.7.0

**Device(s) and version(s) of Android being used：**
android8、android9

**Comment by Samrobbo** [comment] 2019-10-18 11:32
Hi,

I've tested this in the current version, and it appears to be working as expected.

I advise you update your app to a newer version of ExoPlayer, as each update contains bug fixes and improvements. 

In particular, it appears a possible fix for this was added in 2.9.3.

**Comment by imfondof** [comment] 2019-10-21 01:14
> ise you update your app to a n

thank you very much!
and it appears a possible fix for this was added in 2.9.2, in a word , thanks!

but the current problem is that my old project can't play with exoplayer above 2.7.0.
I will try to update my project.

thanks!

**Comment by Samrobbo** [comment] 2019-10-21 08:32
Closing because this seems to be resolved.

**Closed as completed by Samrobbo** 2019-10-21 08:32 UTC
Labels: bug
