### ISSUE TITLE
seekToDefaultPosition() not executed when LoopingMediaSource

### ISSUE THREAD

**Issue by fathallah1990** [google/ExoPlayer#5589] opened 2019-03-02 16:56 UTC
ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource();
        for (int i = 0; i <= suraLength; i++) {
            MediaSource mediaSource = buildMediaSource("url");
            LoopingMediaSource loopingMediaSource = new LoopingMediaSource(mediaSource, 4);
            concatenatingMediaSource.addMediaSource(loopingMediaSource);
        }
mp.seekToDefaultPosition(3);

seekToDefaultPosition() not executed when use  LoopingMediaSource

**Comment by tonihei** [comment] 2019-03-04 11:17
That's indirectly caused by #5155 and not easily fixed until #5155 is resolved. A simple workaround is to not use `LoopingMediaSource`, but rather add the sources directly to the `ConcatenatingMediaSource` like that:
```
ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource();
MediaSource mediaSource = buildMediaSource("url");
concatenatingMediaSource.addMediaSources(Collections.nCopies(4, mediaSource));
mp.seekToDefaultPosition(3);
```

**Comment by tonihei** [comment] 2019-03-04 11:19
I'll close the issue as duplicate because it will be auto-fixed when #5155 is resolved and there is an easy workaround for this specific case.

**Closed as completed by tonihei** 2019-03-04 11:19 UTC
Labels: bug, duplicate
