### ISSUE TITLE
ExoPlayer set up with Rtmp extension leaks memory when closing the activity with playerView

### ISSUE THREAD

**Issue by AdamGrzybkowski** [google/ExoPlayer#4249] opened 2018-05-14 06:41 UTC
### Issue description
LeakCanary detects a leak when closing activity with PlayerView.

I'm using the ExoPlayer with Rtmp extensions to display the live stream. When the url is invalid (there is no live stream there) the leak occurs. 

This is how the releasePlayer method looks like
```
private fun releasePlayer() {
        player?.release()
        player = null
        playerView.player = null
        mediaSource = null
        trackSelector = null
}
```

![screenshot_20180514-081829](https://user-images.githubusercontent.com/12660801/39981425-d7a85e26-5750-11e8-8459-e509f8e63483.jpg)

### Version of ExoPlayer being used
2.8.0

**Comment by ojw28** [comment] 2018-05-30 14:19
There are two parts to this issue:

1. The leak occurs because `RtmpClient.open` blocks forever when an attempt is made to connect to an invalid address, rather than failing. This is what stops the thread right at the top of the chain from exiting, and is the root cause. This is a bug in LibRtmp rather than ExoPlayer, which I've reported here: https://github.com/ant-media/LibRtmp-Client-for-Android/issues/67.
1. We could mitigate the leak by nulling `ExtractorMediaPeriod.callback` when `ExtractorMediaPeriod.release()` is called. It's probably a good idea to do this for all other `MediaPeriod` implementations as well, particularly given that loader threads may not exit immediately even when they're working correctly (e.g. whilst LibRtmp shouldn't block forever, it's not unreasonable that it might end up blocking until some timeout is reached).

**Comment by ojw28** [comment] 2018-06-05 13:59
We've made some changes to ExoPlayer that will mitigate the leak. The `MediaPeriod` will still leak, which is unavoidable until the root cause is fixed in LibRtmp. However we now explicitly null references from that point, to allow GC of `ExoPlayerImplInternal`, the `Activity` and so on. This is a good thing to do from a robustness point of view, and may allow faster GC for some other use cases too.

Leaving the issue open to track picking up a newer version of LibRtmp when the root cause is addressed.

**Comment by AdamGrzybkowski** [comment] 2018-06-05 16:51
Great @ojw28  thanks :)

**Closed as completed** 2019-09-01 22:26 UTC
Labels: bug: in dependency
