### ISSUE TITLE
Missing gzip decompression from subtitle parser

### ISSUE THREAD

**Issue by devnullpointer** [google/ExoPlayer#8504] opened 2021-01-25 14:34 UTC
When using OpenSubtitles as a provider for subtitles, they provide srt files in gzip format, unfortunately due to #8503 downloading and uncompressing them for local usage is not available and onlyt http:// based subtitles are only working. 

Ideally checking the headers and using a GZIPInputStream to decompress the file would solve the issue.

The end result is as follows:
```
W/SubripDecoder: Skipping invalid index: �������������}Ɏ�h��=�xJ�@F�Ш�r�TT熒��<�����p'=I�<=����s�C?м��g��F�*� K%��ۿپ������Eџ�_FQ<<�%�qFev�v��nj��p��8�.�9�`36�.8�c{��������sۿ�l�n>���0>�kn�w�w��.K�*��tYfIt���1x���x���`;\�G���e������w�/UxuXe����a�to��}��18\�
    Skipping invalid index: ��]�}���2���J���
    Skipping invalid index: ���0�v?��
    Skipping invalid index: 6�s��f�ˇ!�w��z��98z��B��(�b��(	Ө����/i�tS7���O�_0����^Qi�xp��о�h�S��m�c����zz2��㑏%8�,�T���
    Skipping invalid index: �8
    Skipping invalid index: ��V�N��.��-��׹餛��J��y�v]q1M�n�҉b�n
    Skipping invalid index: v�t=��r��7Z���W+�*,�̀KҰN�B��ӡ����v�;��}a�{C�[��`j[@8��<,���K�0�����؏̊0�
    Skipping invalid index: 32��4����Ƙ8<��V55�m;N2�P�03(�9��:O��=�aN;�#R�9���	��C˓0O,��Y���{ގm��Vl�º�O6�tp&�r	=�$27s�p���hi�8��p���~ۼ�SH$=vә��L"uB�)6
    Skipping invalid index: z���x��t��3$Qn�L	[����N�#]鯗���w ����\�mK@p$�c�}!Z���V�R(\�˼�p�0O	鞰�0x��!�h�8��v����kR*�"̣��ª�����!�-�k;�����@���<߈u����y�~*2&��"��eZ2>�l_�o�N'�N�È�U����[��`�6��SKt4;�ێȼ��Yx(CK"���YQ[heX����S��ib?
    Skipping invalid index: ������o�8O�-�ۮmF��$V�eX&u�:�K�yCkx
    Skipping invalid index: �5w�Ba`a0�a'�$R����%�G���0���w�y�`Ztlr�I�@bb�����{:���ڍ�<��ͳ��8��ѽf�>:����ҒL�a��H*{).�u#J��1�Gw���E�?���f
W/SubripDecoder: Skipping invalid index: �����r����D��whh]{���<�DQě�">��"{i��w��ꇽtP4�Ua��aes@����͉nkۜ�a��hgb�};aO���!���f{ct|�|3Q���ҒUJ�Hx�DSt��@��q5�LGĀYf�I[�^��|h�2�3f1	C�m�ϙ��`��tƹ�	--Y�H����K��0r���0���'ܧ%�3���TI�F��j�%��MH|�zwn�Cs&�rRMQ����=�e]JM#�-5�1ܒ�����]K�8`�ܐ�������9���
W/SubripDecoder: Skipping invalid index: T7��Jk�X[Z�NT�o'�ק���7�ã-@�n�c�E�<.P��HnE��Q9�%���D�V$��A)*g[m�n>��>O�X�þC:\w��?ߟN"T�$E0*�q�Zy�1P�{d����A����-�N�]��h�AF�\	Њ��(3��{�#+I�2��H:��r[�I���.XN���>x!��������@��Y];e���{���0^�?4�e$E�&�q�
    Skipping invalid index: R@S��d!\r�.�����ux�Ul��x T�؆���AqD
    Skipping invalid index: ��,��u���0w��HV�d���V��M��f��0�@���8N,��~�����rW�QjQ�4�&�����
    Skipping invalid index: P�q]�$2�ۏ��Eb*N�$%��
W/SubripDecoder: Skipping invalid index: �m�gRz�Z"�e�"�FQb=����(��qd1���
    Skipping invalid index: ҖP��� �\���}+l$��ndCF!�3"L� ���b�+�bY����cB�ŜR,�7���IN,��]Bvt'f�<~���<�̚i ��0�-�
    Skipping invalid index: ����n�^z��p^.��5'�3-�4@my��csey@v/��k����t�p3c�W"���t�NP�96'h�Y5{�R�� zd�)@����b��ķ���b�*�`և��،ݎ��g�)�H�<W�d�\�\9k��B�aYۥ!Ɛ��r��r�V웼�`�"�@u%��[2Dn�X(-4:���.LBny�h@]$fP��v<�2�4N�' �;�6�@��(�*�k�����Hƅ.`�a�A����c'�,퉄�vR\/"<IV�t*��������-��8��+6��
    Skipping invalid index: m���q�е�$��@W�"�Ɋ�N3;]0L�6��I�'|���D�4�&7_S�(�:�VxF:f�ǋ��L|JX6f85�ع�.�iP�ťYX�{Q����~KF2����g�CF��F��Ƞ�u�
    Skipping invalid index: �4�>˺�}C�bC���������y��0���X���2���OJK�YDHg�7x��=��	Ix�\`�+�p�a
    Skipping invalid index: sӍ��n����d��l��-4%�Q�������2Z`��YЁ�'3;�&�_i'�h\�_�6	۬S�������f����JK��QY�9,b���?��+�éD`E"w��Cc3�<���H��3�}j����D�s#s�'^V��A���^^�y��]׾m�S�Zh�����&Q��$=�c�)a���bU���.ۗ�Y8�ߋ�����X�|������9���\�����<�)3���]�/¤�@����!�lM��.�ۅ(.�w���\a� 4b+�R���/��7��������A��~;�� KYx�(�R���NY����٫�W�::!���h�'�Jo1�8�8P<C���
    Skipping invalid index: -���$?-�= �R��/�EA�K���TAF��g�Y+
```

- ExoPlayer 2.12.3
- Android 7.1.1

**Comment by icbaker** [comment] 2021-01-25 14:49
gzip compression should be handled fairly transparently either by the [Android platform](https://developer.android.com/reference/java/net/HttpURLConnection#performance) and/or by [DefaultHttpDataSource](https://github.com/google/ExoPlayer/blob/03263db378392385e290c40505d80e990c85a5cb/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L364-L384).

Can you provide a link to a hosted subtitle file that reproduces the issue in the demo app so I can understand what's happening in this case? 
Please either link it here or send it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number). Please also update this issue to indicate you’ve done this.

**Comment by devnullpointer** [comment] 2021-01-25 14:54
I logged into opensubtitles site and grabbed the link I just emailed, hardcoded it and got the following in the debug log:

```
D/EventLogger: loading [true]
D/EGL_emulation: eglMakeCurrent: 0xa80853c0: ver 3 0 (tinfo 0xa8083850)
D/EventLogger: loading [false]
W/SubripDecoder: Skipping invalid index: �������������}َ���}���ݰ��c�zUyz�%[�Kf&��]�d�d*��4s{��\��y��
    Skipping invalid index: _���r�8@[�����b�����������(
    Skipping invalid index: �ȃ8	�2�������/�������v8��~7��럃�q�������p
    Skipping invalid index: �Ǭ����?��~>8��������/�t�����?k��U��Y�:̒�f=<o���o�vl�������z���4|�G�@�]�G�K^VYb��i�4�[Z���،��2m�~��n�2�����C^�yA�x�c�������9�v������;@�~��98z��B��(�b��(	Ө����Oi�ߺ��W���OX�@z/���k<��{h�L4�y��1xn��wO==�N�����I�R*DP�b��II+}'�����\��܌t�������P�<L���
    Skipping invalid index: ��&y7\�D��C7��f���z9��-���\�Qf�%iX't!_ނ�Ќ@�����}i��pyC��O�Lm+G^��exi�U�ߞw�Y�QaFfU��t?�Sx�u�aUSsٶ�$�'
    Skipping invalid index: �
    Skipping invalid index: 3����8��X����<^�s�9���	��C˓0O,��Y���{ގm�f��*``K֍|�q���0ɖ�H�Y'1����݀��]�@KSwā�#�����楝����MgZz3��H�5�f�}���x��t��3$Qn�L	[rp�v:�J�~i�߈~������K�m�dsl�/D��}��V
    Skipping invalid index: �Kt��n�)!�6�:��-�����ð{|�@JR�y�X UXUt5��1$��q�?�Ǧ��;z{:�7b�{n�fF��ʃ�	��Ȁ$��V��#��ۻ�I�S�0�{Uj���%�֟&0��
    Skipping invalid index: ������#2o6Å�ϰkn-�ZfEm��a��~_O�KO���4�q ܁�7D��˖�m�6#�c+�2,�:q�%�5<͉��;݂
    Skipping invalid index: �00�0��zL)�hg���#�ɏC�C��;�@0-:69�$U 1�e�V	΋��=�Ѓ}���
    Skipping invalid index: x��Yhi�����3��X�lfaiI��0��}$I��ĺ%��ꣻ��G��ȟ��N3�XORe�9g�{p"Y�;4���0>��Eo���"��E�	�߽��{-�h�7�����
W/SubripDecoder: Skipping invalid index: ��
    Skipping invalid index: #&�ś�ֶ97�=Þ���Ĩ�v�2�O�iCl�������f�4���%��B��|�����.�'�j����?���7��w��zQgT�	��Θ�$D!��?gg����y�'�0�d"U��RRL,]g8�ȱ�k�dJ2�p��4��3�R%!�W�E��+�6!�mZ��ݹ͙��I5E<��u)5�,�ԔG�pK>��/�w-aXt?�sC2�?�H��6#+Pݬ��*�bmi
    Skipping invalid index: :QAS��_��,����	D�m��F(�@U
    Skipping invalid index: #�e�G�F�t��lZ�d�����m�]��X��<�bq�n�pݭN��p:=�P��h�ƑBh�E�@i0��vi@Ls�n(�`:�v٦�=Uy�Bp%@+^k�̜����t$	ʨ�#進�m�gA&"�`9efO��y���ۓB�o[{�N@git��!$�C@Z�e
    Skipping invalid index: 6�|x���̗����ƑB(HM-⒅p�ͧn�L<�!��D�~x�ë��b;���Zp�6�eȠ��#R��e�ĭ#���4���Hu@�b�� #
    Skipping invalid index: $�B�n�6�
    Skipping invalid index: \��EX����P�qbx �+�\8&_d��2�R����0!��|h�LT�:��� ����~h�.Sqb/ )�To�l<����.���6�{0D�$��F1�~�#�)��V����������}�[�`#i�t#�adS.��b��D����n��CV��$�E3A1���ͼ�t�K�h���É�(����|�#�f�F"�̗�X6%�B7d/��L�z8/��Ț�y��<t�ñ��< ;�qD�Ox�o:w��1w�+���{:R'���4Ϭ��b�0�Y��$[)^-� �IK|K��i ��Bf}�~����H�~����0���s�L�O�Z�5ȕ�!{+t@��]
    Skipping invalid index: bi(/_�-wjž�K?
    Skipping invalid index: �!�TW�Ⱦ#C����B��jI��$�W
    Skipping invalid index: �ԥ�@b��n��/H�4|"н�m#
    Skipping invalid index: t^+�2�2�v訹،d`\�v���0���vr,�Ě�=����N��E�'�J��@����\��qG�rE�&���<�V�D�@�ኝT�:Y�if'�k��iA���1i��7�Ȝ�����k*[��
W/SubripDecoder: Skipping invalid index: �Hǌ�x�0��O	���f;wم�?
```

**Comment by icbaker** [comment] 2021-01-25 15:15
Thanks for the link.

This file isn't being gzipped at the HTTP layer, so the HTTP response [1] doesn't contain a `Content-Encoding: gzip` header. This makes sense since the file is stored already gzipped, so its compressed before it reaches the HTTP serving layer, the server doesn't attempt to double-compress it (and even if it did, Android/ExoPlayer would only unzip one of the layers).

There's no way for ExoPlayer to know this file is gzipped. I assume you put something like this in the JSON?

```
      {
        "name": "test",
        "uri": "https://html5demos.com/assets/dizzy.mp4",
        "subtitle_uri": "https://dl.opensubtitles.org/en/download/src-api/vrf-19c50c57/sid-dImipHnCRU,QoQu9,aIqIohipS8/filead/1957066282.gz",
        "subtitle_mime_type": "application/x-subrip",
        "subtitle_language": "en"
      },
```

This snippet is wrong, because the URI doesn't point to a subrip file, it points to a gzipped subrip file.

So I don't think this suggestion makes sense (afaict there are no headers to check for):
> Ideally checking the headers and using a GZIPInputStream to decompress the file would solve the issue.

To make this work you'll need to do the unzipping yourself, probably by writing a `DataSource` implementation that wraps another `DataSource` and unzips during `read()` calls. It might end up looking similar to the existing [`AesCipherDataSource`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/crypto/AesCipherDataSource.java). You'll need to make sure this unzipping is only applied to files that are zipped - determining how to identify these files could be tricky. You might be able to just look at the file extension of the URI, or you could use `DataSpec.customData` to identify these files.

This challenge of reliably identifying which URIs need to be unzipped and which don't makes it very unlikely that we'd add this functionality to the library. So I'm going to close this.

[1]
```
$ curl -i -H "Accept-Encoding: gzip,identity" -D - --output /dev/null https://dl.opensubtitles.org/en/download/src-api/vrf-19c50c57/sid-dImipHnCRU,QoQu9,aIqIohipS8/filead/1957066282.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/2 200
date: Mon, 25 Jan 2021 15:04:16 GMT
content-type: application/force-download
content-length: 12581
set-cookie: __cfduid=ddcfd54c1b82c79a2700b00616fe81ffa1611587056; expires=Wed, 24-Feb-21 15:04:16 GMT; path=/; domain=.opensubtitles.org; HttpOnly; SameSite=Lax
set-cookie: PHPSESSID=dImipHnCRU%2CQoQu9%2CaIqIohipS8; expires=Mon, 25-Jan-2021 21:04:16 GMT; Max-Age=21600; path=/; domain=.opensubtitles.org; HttpOnly
set-cookie: OAID=c1da70ff71ed9bba46504ab426b637cc; expires=Tue, 25-Jan-2022 15:04:16 GMT; Max-Age=31536000; path=/
set-cookie: OAID=c1da70ff71ed9bba46504ab426b637cc; expires=Tue, 25-Jan-2022 15:04:16 GMT; Max-Age=31536000; path=/
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept
access-control-allow-origin: *
x-robots-tag: noindex, nofollow
p3p: CP="CUR ADM OUR NOR STA NID"
content-disposition: attachment; filename="WandaVision.S01E01.Episode.1.720p.DSNP.WEB-DL.DDP5.1.H.264-TOMMY.srt.gz"
pragma: no-cache
expires: Mon, 1 Apr 2006 01:23:45 GMT
content-transfer-encoding: Binary
cache-control: private, must-revalidate, post-check=0, pre-check=0, no-store, max-age=0, max-stale=0
content-md5: 2a48bdb2ea45e6f2653005840a367897
download-quota: 199
x-cache-backend: web4
age: 0
x-var-cache: MISS
x-ratelimit-remaining: 40
x-via: fw2
accept-ranges: bytes
cf-cache-status: DYNAMIC
cf-request-id: 07dbac0afc00002cfbba09d000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=t60%2B%2FBhPhndRfcq%2BHA61bTTvrAG6imPUZqPjgaQPZp%2BxzMpWtZiAOzM5tStr91JqfROsEXWuSdbcFAUPpwNvfFwHpHB%2BWXLcZHoj4jnYtljC%2Bp%2FbZTBzRc5n2nLkcjXj7w%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"max_age":604800,"report_to":"cf-nel"}
server: cloudflare
cf-ray: 6172e2be5d242cfb-LHR
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400

100 12581  100 12581    0     0  91832      0 --:--:-- --:--:-- --:--:-- 91832
```

**Closed as completed by icbaker** 2021-01-25 15:15 UTC
Labels: question

**Comment by devnullpointer** [comment] 2021-01-25 15:19
Thanks for the info, and I completely and fully understand the position taken. I will try to implement a datasource as you suggested to see if that helps, ideally if I could guarantee all the opensubtitles subrips are gzip'd that would make things a lot easier.

Thanks @icbaker

**Comment by devnullpointer** [comment] 2021-01-26 13:34
@icbaker thanks for the input, I wrote a custom DataSource Factory implementing OkHttpDataSource and wrote a GzipInterceptor for it. Works like a charm.
