### ISSUE TITLE
Exoplayer gets stuck after some time of streaming RTSP content from VLC

### ISSUE THREAD

**Issue by vinayaksoni** [google/ExoPlayer#9263] opened 2021-08-05 18:27 UTC
Hi,

Device: Raspberry Pi 4
Android version: 11

I downloaded the tip of dev-v2 branch of Exoplayer to get the RTSP support. I created a demo app with it for playing RTSP content from VLC:

```
public class MainActivity extends Activity {
    final static String RTSP_URL = "rtsp://192.168.1.214:8554/abc";
    PlayerView playerView;
    SimpleExoPlayer player;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // Create an RTSP media source pointing to an RTSP uri.
        MediaSource mediaSource =
                new RtspMediaSource.Factory().createMediaSource(MediaItem.fromUri(RTSP_URL));
        playerView = findViewById(R.id.pv_main);
        player = new SimpleExoPlayer.Builder(MainActivity.this).build();
        // Bind the player to the view.
        playerView.setPlayer(player);

// Set the media item to be played.
        player.setMediaSource(mediaSource);
// Prepare the player.
        player.prepare();
// Start the playback.
        player.play();

    }
    @Override
    protected void onDestroy() {
        super.onDestroy();
        playerView.onPause();
        player.release();
    }
}
```

The RTSP stream plays fine for a minute but then stops with the following trace in the logcat:

```
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer: Video codec error
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:   java.lang.IllegalStateException
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:98)
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1199)
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:825)
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at android.os.Looper.loop(Looper.java:223)
08-05 18:00:19.433  3969  3997 E MediaCodecVideoRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal: Playback error
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(null, null, null, video/avc, avc1.42c015, -1, null, [480, 360, -1.0], [-1, -1]), format_supported=YES
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:558)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:978)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:482)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       ... 3 more
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:98)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1199)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:825)
08-05 18:00:19.436  3969  3997 E ExoPlayerImplInternal:       ... 5 more
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal: Disable failed.
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:   java.lang.IllegalStateException
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2298)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:165)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:895)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:888)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:741)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:483)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:178)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1642)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1384)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1347)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:574)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
08-05 18:00:19.441  3969  3997 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
```

Posting an issue for the first time so please let me know if any other info is needed.

**Comment by andrewlewis** [comment] 2021-08-06 08:12
To look into codec failures like this we really need a full bug report captured via `adb bugreport` just after seeing the error, as that may include useful diagnostic information that may help track down the cause (and also tells us exact device and build). If there's something you don't want to post publicly please email the bug report to dev.exoplayer@gmail.com using a subject in the format "Issue #9263".

**Comment by e-sonic** [comment] 2021-08-06 20:42
I have emailed it to you.

**Comment by andrewlewis** [comment] 2021-08-09 08:44
The logging about exceeding the timeout looks like [internal: b/173106189] and #9256:

```
08-05 13:00:33.811  1046   302  2419 W C2BqBuffer: last successful dequeue was 7323724 us ago, 0 consecutive failures
08-05 13:00:40.331 1010138  2376  2415 W CCodec  : previous call to queue exceeded timeout
08-05 13:00:40.334 1010138  2376  2413 E MediaCodec: Codec reported err 0x80000000, actionCode 0, while in state 6
```

I didn't spot anything else that looked related in the bug report.

**Comment by vinayaksoni** [comment] 2021-08-09 21:01
Couple of more observations: 
-  When I play the big buck bunny rtsp stream (rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov), it plays fine but when it ends, it throws the same error logs.

- I am able to play the same vlc rtsp stream of local webcam via VideoView but not via exoplayer. I understand they might different underneath the hood but thought of letting you know.

With Best Regards,

Vinayak Soni

On Aug 9, 2021, at 14:14, Andrew Lewis ***@***.***> wrote:

﻿
The logging about exceeding the timeout looks like [internal: b/173106189] and #9256:

08-05 13:00:33.811  1046   302  2419 W C2BqBuffer: last successful dequeue was 7323724 us ago, 0 consecutive failures
08-05 13:00:40.331 1010138  2376  2415 W CCodec  : previous call to queue exceeded timeout
08-05 13:00:40.334 1010138  2376  2413 E MediaCodec: Codec reported err 0x80000000, actionCode 0, while in state 6
I didn't spot anything else that looked related in the bug report.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by andrewlewis** [comment] 2021-08-10 09:58
>  When I play the big buck bunny rtsp stream (rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov), it plays fine but when it ends, it throws the same error logs.

This indeed seems similar to #9256 -- it seems that under some circumstances the decoder throws if there is no interaction with it for a few seconds, and I understand that this can happen with RTSP streams because we detect end of stream via timing out (because there is no explicit signal).

> I am able to play the same vlc rtsp stream of local webcam via VideoView but not via exoplayer. I understand they might different underneath the hood but thought of letting you know.

@claincly Please could you look into this as part of documenting the feature gap compared to MediaPlayer's RTSP support?

**Comment by vinayaksoni** [comment] 2021-08-12 07:01
> > When I play the big buck bunny rtsp stream (rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov), it plays fine but when it ends, it throws the same error logs.
> 
> This indeed seems similar to #9256 -- it seems that under some circumstances the decoder throws if there is no interaction with it for a few seconds, and I understand that this can happen with RTSP streams because we detect end of stream via timing out (because there is no explicit signal).

So for this bug, we should wait until #9256 is resolved?

> 
> > I am able to play the same vlc rtsp stream of local webcam via VideoView but not via exoplayer. I understand they might different underneath the hood but thought of letting you know.
> 
> @claincly Please could you look into this as part of documenting the feature gap compared to MediaPlayer's RTSP support?

Please provide a link to this feature gap document whenever available.

**Comment by e-sonic** [comment] 2021-08-18 14:43
Any update?

**Comment by vinayaksoni** [comment] 2021-08-18 14:45
Any update on this?

**Comment by andrewlewis** [comment] 2021-08-18 18:14
> > > When I play the big buck bunny rtsp stream (rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov), it plays fine but when it ends, it throws the same error logs.
> > 
> > 
> > This indeed seems similar to #9256 -- it seems that under some circumstances the decoder throws if there is no interaction with it for a few seconds, and I understand that this can happen with RTSP streams because we detect end of stream via timing out (because there is no explicit signal).
> 
> So for this bug, we should wait until #9256 is resolved?

Yes, although the cause of that bug seems to be that an incomplete access unit is queued to the codec, so it could be explained by the stream being invalid or a bug in how access units are being parsed in ExoPlayer. It will take more investigation to figure that out.

> > > I am able to play the same vlc rtsp stream of local webcam via VideoView but not via exoplayer. I understand they might different underneath the hood but thought of letting you know.
> > 
> > 
> > @claincly Please could you look into this as part of documenting the feature gap compared to MediaPlayer's RTSP support?
> 
> Please provide a link to this feature gap document whenever available.

This is work in progress and internal-only at the moment I'm afraid.

**Comment by vinayaksoni** [comment] 2021-08-19 14:22
> > > > When I play the big buck bunny rtsp stream (rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov), it plays fine but when it ends, it throws the same error logs.
> > > 
> > > 
> > > This indeed seems similar to #9256 -- it seems that under some circumstances the decoder throws if there is no interaction with it for a few seconds, and I understand that this can happen with RTSP streams because we detect end of stream via timing out (because there is no explicit signal).
> > 
> > 
> > So for this bug, we should wait until #9256 is resolved?
> 
> Yes, although the cause of that bug seems to be that an incomplete access unit is queued to the codec, so it could be explained by the stream being invalid or a bug in how access units are being parsed in ExoPlayer. It will take more investigation to figure that out.

Any further information is needed for debugging?

> 
> > > > I am able to play the same vlc rtsp stream of local webcam via VideoView but not via exoplayer. I understand they might different underneath the hood but thought of letting you know.
> > > 
> > > 
> > > @claincly Please could you look into this as part of documenting the feature gap compared to MediaPlayer's RTSP support?
> > 
> > 
> > Please provide a link to this feature gap document whenever available.
> 
> This is work in progress and internal-only at the moment I'm afraid.

Ah ok.

**Comment by andrewlewis** [comment] 2021-09-06 13:36
I'm going to mark this as a duplicate for now as I don't think any more action is needed until that other bug is fixed (at which point we can confirm that this is addressed).

**Comment by andrewlewis** [comment] 2021-09-06 13:36
Duplicate of #9256

**Closed as completed by andrewlewis** 2021-09-06 13:36 UTC
Labels: duplicate
