### ISSUE TITLE
Device reboots while recording video

### ISSUE THREAD

**Issue by bhavna-nga** [google/ExoPlayer#4427] opened 2018-06-26 05:14 UTC
### Issue description
I have used Exoplayer for recording videos. This is working fine for almost all the devices, but for a few of them (Samsung Galaxy S9+ being one of them) is experiencing reboot issue while the video is recorded. The device automatically restarts on its own. Since this is not an app-crash, this cannot be even recorded on Crashlytics. Had anyone faced the same issue - Any solution for this or any way to debug the exact issue using logs or any other medium??

### Reproduction steps
Start recording video using S9 or S9+. Wait for sometime and the device restarts on its own. Sometimes stopping the recording reboots the device.

### Link to test content
No such link for now

### Version of ExoPlayer being used
2.8.0

### Device(s) and version(s) of Android being used
Samsung S9 and S9+ (Oreo)

### A full bug report captured from the device
Since the device reboots on a production build, I can't report a log. Please suggest how can the log can be captured.

**Comment by andrewlewis** [comment] 2018-06-26 07:17
Could you clarify what you mean by "recording videos"? ExoPlayer doesn't support recording videos (only playback). If you are able to capture a bug report after the devices reboots that may have useful information. I suggest reporting this to Samsung directly.

I'll close this for now but if you find that the issue is related to ExoPlayer then please provide more information and I'll reopen it.

**Closed as completed by andrewlewis** 2018-06-26 07:17 UTC
Labels: question
