### ISSUE TITLE
ffmpeg extension support for exoplayer

### ISSUE THREAD

**Issue by zhangabvc** [google/ExoPlayer#5252] opened 2018-12-13 01:59 UTC
Exoplayer successfully loaded ffmpeg, but the audio format mpega still has no sound.

My implementation steps are as follows

 I developed it on this this original . ExoPlayer demo app（2.9）. I move  extensions\ffmpeg  to libarary/core/src.
Then modify the code

![image](https://user-images.githubusercontent.com/44994911/49713520-071ca300-fc84-11e8-8ab8-70b784fb787e.png)

After modification
![image](https://user-images.githubusercontent.com/44994911/49713551-2ca9ac80-fc84-11e8-9b25-7f0e4358ab82.png)

The result appears to be successfully loaded ffmpeg, the log shows "DefaultRenderersFactory: Loaded FfmpegAudioRenderer"

Is it my method is wrong?

**Comment by ojw28** [comment] 2018-12-13 10:50
Duplicate of #5204

**Closed as completed by ojw28** 2018-12-13 10:50 UTC
Labels: duplicate
