### ISSUE TITLE
Unable to instantiate decoder OMX.qcom.video.decoder.avc

### ISSUE THREAD

**Issue by OmarBasem** [google/ExoPlayer#6167] opened 2019-07-11 09:26 UTC
### [REQUIRED] Issue description
Video fails to play giving that error:
errorException: "com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
errorString: "Unable to instantiate decoder OMX.qcom.video.decoder.avc"

If there is one video on the screen, it works fine, but if there is more than one video, usually it fails to load and play. This happens for both remote and local videos.

### [REQUIRED] Reproduction steps
A scroll view with few videos. Sometimes they will load, but usually they won't work. I am unable to provide a demo app because I am using ExoPlayer as part of a react-native package (react-native-video), but this is a zip file for the Java code used in the package:

[exoplayer.zip](https://github.com/google/ExoPlayer/files/3381221/exoplayer.zip)

### [REQUIRED] Link to test content
https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

### [REQUIRED] A full bug report captured from the device
[bugreport-jasmine-PKQ1.180904.001-2019-07-11-13-19-25.zip](https://github.com/google/ExoPlayer/files/3381245/bugreport-jasmine-PKQ1.180904.001-2019-07-11-13-19-25.zip)

### [REQUIRED] Version of ExoPlayer being used
ExoPlayer 2.9.0

### [REQUIRED] Device(s) and version(s) of Android being used
Device: xiaomi mi a2
Android version: 9

**Comment by ojw28** [comment] 2019-07-11 17:52
Duplicate of #6168

**Closed as completed by ojw28** 2019-07-11 17:52 UTC
Labels: bug
