### ISSUE TITLE
Please help to fix this case issue with IMA extension.

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#3235] opened 2017-09-03 14:22 UTC
Hello all !

We use Exoplayer 2.5.1 with IMA extension in demo app, play live streaming m3u8, Everything works properly, but sometime we see two issue:
- Ads counter show wrong, it show 30-29-28-27 then repeat 30-29-28-27....
- If buffering occurent in video ads playing, then when exoplayer ready, video ads bypass. player continue with main streaming.

@foreach repear counter ads we only see log :
09-03 12:40:15.136 3735-3772/? E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 1Kb duration : 3ms lastUpdatedAfter : 60127 ms mFlush_time_threasold : 2000 mCurrentSize : 612
09-03 12:40:21.496 2378-18808/? E/OMXNodeInstance: getConfig(d5c:Exynos.avc.dec, ConfigCommonOutputCrop(0x700000f)) ERROR: NotReady(0x80001010)
						
09-03 12:41:15.296 3735-3772/? E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 1Kb duration : 1ms lastUpdatedAfter : 60161 ms mFlush_time_threasold : 2000 mCurrentSize : 612
09-03 12:41:16.056 2378-4096/? E/OMXNodeInstance: getConfig(d5f:Exynos.avc.dec, ConfigCommonOutputCrop(0x700000f)) ERROR: NotReady(0x80001010)

Anybody has this case, please help.

Thanks.

**Comment by andrewlewis** [comment] 2017-09-04 13:41
Please could you provide links to the media and ad tag you're playing so we can reproduce the issue? If you don't want to share them on GitHub please email them to dev.exoplayer@gmail.com.

**Comment by kinhdang** [comment] 2017-09-05 02:49
Thanks, and we had provided links in email.

**Comment by ojw28** [comment] 2017-09-06 11:01
The repeating ad counter and the ad possibly ending prematurely are due to the same issue as https://github.com/google/ExoPlayer/issues/3180, and will be fixed shortly. I think this will most likely fully resolve your problem, so marking as a duplicate. Thanks!

**Closed as completed by ojw28** 2017-09-06 11:01 UTC
Labels: duplicate
