### ISSUE TITLE
Merging of Exoplayer layout

### ISSUE THREAD

**Issue by Crabgore** [google/ExoPlayer#7068] opened 2020-03-10 15:53 UTC
If i use 2 or 3 fragments with Exoplayer  and RESIZE_MODE_ZOOM in one screen, they merge into one video. Its same on every type of device (phone, tablet, TV, box). From version 2.8 to 2.11.3, nothing changed.
will it ever be fixed?

**Comment by tonihei** [comment] 2020-03-12 13:24
This doesn't really describe what the problem is. Could you please fill out the issue template including reproduction steps, expected behaviour etc. so that we can understand your issue? Thanks!

**Comment by Crabgore** [comment] 2020-03-12 13:38
You can create a LinearLayot and put two exoplayer2 Playerviews with weight 1 each. Set surface_view surface type and RESIZE_MODE_ZOOM resizeMode to each of this views and start a video in each.
Displayed only one video filling whole screen, not two.
with other resize modes or using texture_view all works correctly - displayed two videos.

sorry for my english

![Screenshot_1](https://user-images.githubusercontent.com/48756344/76528003-ce680c80-6478-11ea-9422-984543d324c8.png) - expecting behavior
![Screenshot_2](https://user-images.githubusercontent.com/48756344/76528024-d627b100-6478-11ea-8d59-b363046a9823.png) - really behavior

**Comment by tonihei** [comment] 2020-03-12 16:02
That might be the same problem as reported in #6955. This issue will likely be fixed in a future Android version. As noted in #6955. it's probably not really an ExoPlayer issue because ExoPlayer just renders to any surface it is provided with and the rest is handled by the Android framework.

**Comment by tonihei** [comment] 2020-03-12 16:03
Closing it under the assumption that this is a duplicate.

**Closed as completed by tonihei** 2020-03-12 16:03 UTC
Labels: duplicate, bug: in platform
