### ISSUE TITLE
Some manifests crashed the player

### ISSUE THREAD

**Issue by peyoh** [google/ExoPlayer#1675] opened 2016-07-13 11:54 UTC
Hello, 
some live profile MPD files  throws IndexOutOfBoundsException in the player. 
They are generated from shaka packager ( edash packager) project 
https://github.com/google/shaka-packager.
I've sent links to the dev email. 
I'm new in the player's code and I'm still unable to track this issue.

**Comment by peyoh** [comment] 2016-07-13 13:26
Hello, 
I've opened a question in shacka packager [#122](https://github.com/google/shaka-packager/issues/122), because I see something strange in the manifest files.

**Comment by ojw28** [comment] 2016-07-13 13:50
I think the manifest is most likely valid according to the DASH spec. The segments aren't aligned, but the `AdaptationSet` doesn't indicate that they are aligned (i.e. `segmentAlignment=true` is not set on the `AdaptationSet`).

ExoPlayer requires segment alignment, which is why you're seeing the failure. I believe DASH-IF IOP also has this same requirement, which in turn implies shaka-packager should be aligning the segments. I've updated the issue you filed on shaka-packager to indicate this. On the ExoPlayer side, we have no plans to support non-aligned segments in DASH. Issue https://github.com/google/ExoPlayer/issues/1049 is tracking failing in a more graceful/obvious way when we encounter non-aligned segments.

Please update this issue if the shaka-packager folks disagree with the above, since I probably wont see updates to that issue without being prompted. If I hear nothing, I'll mark this as a duplicate of https://github.com/google/ExoPlayer/issues/1049 in a few weeks.

Thanks!

**Comment by peyoh** [comment] 2016-07-14 13:50
Hi, 
I' think this is a duplicate issue of [#1049](https://github.com/google/ExoPlayer/issues/1049)

**Closed as completed** 2016-07-14 14:27 UTC
Labels: duplicate
