### ISSUE TITLE
Demo for audio playback and using Google design guidelines.

### ISSUE THREAD

**Issue by fourofspades** [google/ExoPlayer#8979] opened 2021-05-23 18:38 UTC
The demo apps are all very video playback centric, and all demonstrate very similar concepts.  Trying to use this library for audio playback is really hard if you want to do it correctly.  There is no demo of an background Audio service.  There is no demo of how to integrate with Android mediasessions/media2, or how to use PlayerNotificationManager correctly to create an Android guidelines compliant media player.

I got most of these things working, but it was really a case of trawling githib code from other projects, and I noticed so many bugs in other apps (and mine) as a result of no samples to guide developers.  If Google care about app quality, then good demo apps should be a priority.

My last problem, I simply gave up on, I was tearing so much hair out.  Trying to handle the PendingIntent from PlayerNotificationManager createCurrentContentIntent override, that just caused me too many issues, I literally found 10 or more projects on Github, and not one of them worked correctly, and most developers commented out their botched attempts and  just set it to null, and turn off the ability to click the notification to take you back to your fragment (via activity).  it makes for sucky apps, but it's the unfortunate path of least resistance.

Please, a good Audioplayer sample, using a background service, and properly connecting with Android media notifications and audio channels.

**Comment by ojw28** [comment] 2021-05-24 10:03
This is fair feedback, and is a gap that we're aware of. It's a duplicate of part of https://github.com/google/ExoPlayer/issues/5854, so closing as a duplicate of that issue. Thanks!

**Closed as completed by ojw28** 2021-05-24 10:03 UTC
Labels: duplicate

**Comment by fourofspades** [comment] 2021-05-24 10:39
I would like to see this as Java, not Kotlin, which doesn't really have much traction yet.
