### ISSUE TITLE
Black Screen on changing the bitrate in demo app 

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#8196] opened 2020-11-10 09:15 UTC
### [REQUIRED] Question
In ExoPlayer demo app, if I change the Video bit rate then i see a blackscreen then video frame appears. It is only happening in Dash DRM content; which i can see. For HLS and Clear Dash, when i change the bit rate, video frame is visible and resumes the content after the track update.

### A full bug report captured from the device
Not required.

### Link to test content
In Demo app. Widevine DASH H264 (MP4) -> Secure (cenc)

**PS:** We can show a loader on bitrate switching OR may show an overlay but want to ask that is this a known and intended behaviour ? From UX viewpoint, I felt that it is not good.

**Comment by kim-vde** [comment] 2020-11-10 17:08
Thanks for reporting this. Could you clarify how you change the bitrate?

**Comment by GouravSna** [comment] 2020-11-10 17:10
I am changing it manually from the 'Select Tracks' button from PlayerScreen then under 'Video' selecting bitrate.

**Comment by kim-vde** [comment] 2020-11-11 10:36
I can indeed observe this behaviour with Widevine secure content but not with Widevine clear content. I can see some DRM errors in the strack trace when changing the track but I am not sure whether they are linked. This issue was already present in ExoPlayer 11.7.

Assigning to @AquilesCanta for further investigation.

**Comment by GouravSna** [comment] 2020-12-03 05:06
Hi @kim-vde @AquilesCanta , Please let us know if we have any update on it.

**Comment by ojw28** [comment] 2020-12-03 18:32
Note: This only happens with manual track selection. It doesn't happen on adaptive track selections performed by the player during playback.

What you're seeing is the result of a platform limitation related to how secure video playback is implemented. In short, the implementation clears the `Surface` when the decoder is released. It doesn't appear to happen on a Pixel 4 XL running Android 11. I'm unsure whether this means that the limitation has been removed completely in Android 11, or whether the exact behaviour varies by the system-on-chip in the device. I have a Galaxy S20 that currently does reproduce the issue running Android 10, and is expected to receive Android 11 soon [according to Samsung](https://news.samsung.com/us/samsung-one-ui-3-android11-enhanced-user-experience/). So a good test will be whether the issue is still present on this device after it receives the update.

There is also a [TODO in ExoPlayer to do a better job of re-using the decoder in this case](https://github.com/google/ExoPlayer/blob/r2.12.2/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L770), which would help with some cases, but is unlikely to fully solve the problem because we will still need to release and recreate the decoder in some cases.

I will leave this issue open until I can report back on what the Galaxy S20 does after it receives its update. Once that's done I will close this issue because it's a limitation of the underlying platform. We have no plan to look at the TODO mentioned above any time soon, because it's quite a complicated piece of work for quite a minor improvement, and because it would also not resolve the issue in all cases.

**Comment by GouravSna** [comment] 2020-12-04 01:33
Thanks a lot @ojw28 😀

**Comment by ojw28** [comment] 2020-12-04 12:13
The S20 I have was upgraded to Android 11, and still has the same behaviour unfortunately. Closing regardless as a platform limitation, as described above.

**Closed as completed by ojw28** 2020-12-04 12:13 UTC
Labels: question, bug: in platform
