### ISSUE TITLE
Problem with ExoPlayer set/getPlaybackParameters

### ISSUE THREAD

**Issue by AndroVid** [google/ExoPlayer#3380] opened 2017-10-20 07:32 UTC
Hi, we use SimpleExoPlayer. We change the playback speed successfully by using setPlaybackParameters function, but after calling setPlaybackParameters we expect to  get same values with getPlaybackParameters function. But it always returns the Default value. When we checked the code, inside setPlaybackParameters "internalplayer" is modified but inside getPlaybackParameters, non-modifed Default value is returned.

**Comment by tonihei** [comment] 2017-10-20 08:24
Can you tell us which version you use where you think this is the case? The [current release version definitely returns the current playback parameters](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L256). 

However, please note that setting the playback parameters is an asynchronous process. You can listen to Player.EventListener.onPlaybackParametersChanged to know when the parameters actually changed. This also means that calling player.getPlaybackParameters() immediately after player.setPlaybackParameters() still returns the original, default parameter set. We know that this is confusing and we are currently working on improving this to make it less error-prone. Marking this as enhancement to track this and keep you updated.

**Comment by AndroVid** [comment] 2017-10-20 09:14
Version is 2.5.3 and we didnt call getPlaybackParameters just after calling the setPlaybackParameters. After calling set, we see that Player plays at the new speed, after seeing this ( maybe after 10 secs) we call the get.  Also we tried getting the value from onPlaybackParametersChanged callback but it was never called. We see other Player calbacks are called like "onPlayerStateChanged"

**Comment by tonihei** [comment] 2017-10-20 11:10
Unfortunately, I can't reproduce your problem in our demo app. Have you tested if this problem is in any way device or media specific? Or does it always happen? 
I currently can't see a way the player actually plays at the new speed  and does not call the eventListener.onPlaybackParametersChanged. To further investigate this problem, it would be nice if you could reproduce it in our demo app to allow us to look closer.

**Comment by ojw28** [comment] 2017-11-01 14:34
Closing due to lack of further information. I cannot reproduce the issue either.

**Closed as completed by ojw28** 2017-11-01 14:34 UTC
Labels: enhancement, need more info
