### ISSUE TITLE
Pause progressive stream

### ISSUE THREAD

**Issue by ilpelatodijavascript** [google/ExoPlayer#6991] opened 2020-02-18 18:15 UTC
Hello, I'm pausing a Progressive Media Source like this:
```
simpleExoPlayer.setPlayWhenReady(false);
```
and it works as it should untill the stream buffers and instead of playing from the right position it jumps back to the live feed.
Is there any way to fix this?

**Comment by fgl27** [comment] 2020-02-18 21:00
how much time you paused for? maybe it helps also the media link that causes the issue (if you can share the link if not there is a way to private send links but is not for me, only if the project maintainers ask they let you know how to)...

there is a **maxBufferMs** with the default values is [DEFAULT_MAX_BUFFER_MS](https://exoplayer.dev/doc/reference/constant-values.html#com.google.android.exoplayer2.DefaultLoadControl.DEFAULT_MAX_BUFFER_MS) from [setBufferDurationsMs](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.Builder.html#setBufferDurationsMs-int-int-int-int-), maybe it is the cause, it can be overwintered to a higher value...

I have a similar issue but is with hls live streams that I leave it paused for a time that is bigger than **playlist.durationUs**.

It doesn't loading new segments after the buffer size became current buffer (before pause buffer) + **playlist.durationUs** or something like that in my case the before buffet is 5 to 10s and the playlist.duration is 28 to 32s, the buffer stops incrementing at around 35 to 45s of buffer size, none new segments are buffered because the playlist is not updated after that during a pause on live streams, even if **DEFAULT_MAX_BUFFER_MS** is "not yet full".

The result is, that after I press play it plays for **buffer size**, until the buffer is empty, then like yours issue creates a discontinuity because it "jumps back to the live feed" (after a new buffer moment) without ever trying to get the missing segment's...

This is probably a "how is design for hls" thing, maybe not I would like to see **DEFAULT_MAX_BUFFER_MS** to get full on pause for all live stream, even if **playlist.durationUs** and the visible segments from before I click pause are less then **DEFAULT_MAX_BUFFER_MS** after all for a live stream they keep be generated...

**Comment by marcbaechinger** [comment] 2020-02-19 17:42
I think the two cases are different. The initial issue seems to be about a non-seekable `ProgressiveMediaSource` which actually is a live stream. The second is about an actual HLS live stream for which the manifest is reloaded frequently and the live window changes (I'd expect a `BehindLiveWindowException` after a while).

I'll look into the initial case. @fgl27 Can you please open another issue if you think it's required? You can also [search for BehindLiveWindowException here in the issue tracker](https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=is%3Aissue+BehindLiveWindowException) to get more info about this case.

@ilpelatodijavascript: Basically the answer of fgl27 points into the right direction. When you pause the player, it keeps downloading data until the buffer is full. Lets assume that the buffer is now filled until timestamp N. The player now stops reading from the network connection because no more data can be stored in the buffer. When the player is started again and the buffer is going to play out, data is read from the network connection again, but there is a discontinuity because the server advanced in the meantime and does deliver a timestamp which leaves a gap since timestamp N which result in a discontinuity (what you describe as 'jumps to the live feed again').

The short answer is probably that such a progressive live stream can not be paused properly. You can try to increase the maxBufferMs parameter but this just delays the problem to some time later in the stream.

If you send me a url to the stream I can look if my guess from above is correct. Although I don't think I'll be able to provide a much better answer I'm afraid.

**Comment by fmatosqg** [comment] 2020-02-19 23:21
@fgl27 @marcbaechinger I can confirm that while pausing my HLS live stream it's a big hassle to get back on track.

I wish many things in exoplayer were simple:

- I need to listen to all errors, crawl through it and check if its type is BehindLiveWindowException
- once that happens I have to propagate it as a new state so some other class that listens to all state changes will check if the new state is BehindLiveWindowException
- then I increment a counter and issue a new play command with the previously stored url
- if the counter reaches a MAX value I quit. If at any time the new state is Playing I reset the counter.

**Comment by marcbaechinger** [comment] 2020-02-20 11:57
@fmatosqg What would be your suggestion the player should do to handle the situation of falling behind the live window?

The current solution does play out as much as it can and then signals that it run into an exceptional state from which it is not clear how to recover. You are right that in throwing, the player leaves it to the app how to deal with this situation. Silently restarting at the default position (close to the live edge) is an option which can be initiated by the app upon the exception. In any case I think that the app needs to be informed about this clearly which is the case by throwing.

If you want, you can find the information about the live stream in the window in the timeline. It would probably allow you to calculate how long you can pause without falling behind the live window. In doing so you could tell your user and act up that situation before the player throws. In anticipating this case, you could for instance seek back to the default position before the exception is thrown or just resume playback. I don't know whether this is more or less complicated than the approach you described above. It feels to me that the `PlayerActivity` of the demo app can handle this case in a less complicated way. I appreciate though that your app may need to fulfill more complicated requirements than the demo app.

Some API properties around live stream:

window.durationUs -> duration of the live window
window.defaultPosition -> position within the live window to start playback from 
player.getCurrentLiveOffset() -> Returns the offset of the current playback position from the live edge in milliseconds,

player.getCurrentPosition() -> the position at which the player is paused. 
player.getBufferedPosition() -> position until which data is buffered

**Comment by fgl27** [comment] 2020-02-21 17:29
@marcbaechinger @fmatosqg thanks for the help

I open a separated issue to see if we can improve the pause behavior.

https://github.com/google/ExoPlayer/issues/7006

**Comment by fmatosqg** [comment] 2020-02-25 05:33
@marcbaechinger I wrote some comments here https://github.com/google/ExoPlayer/issues/7006#issuecomment-590590051

**Comment by ojw28** [comment] 2020-02-28 19:28
I've marked most of the responses above as off topic, since there are two issues being discussed here. Here's the part of response from @marcbaechinger that is relevant to the original issue:

> @ilpelatodijavascript: When you pause the player, it keeps downloading data until the buffer is full. Lets assume that the buffer is now filled until timestamp N. The player now stops reading from the network connection because no more data can be stored in the buffer. When the player is started again and the buffer is going to play out, data is read from the network connection again, but there is a discontinuity because the server advanced in the meantime and delivers a timestamp which leaves a gap since timestamp N which result in a discontinuity (what you describe as 'jumps to the live feed again'). The short answer is probably that such a progressive live stream can not be paused properly. You can try to increase the maxBufferMs parameter but this just delays the problem to some time later in the stream.

As Marc mentions, for progressive live streams it's not possible the player to request the media data from a particular position from the server. So the only way to support pause/resume for such streams is for the player to continue buffering the media indefinitely whilst the playback is paused. Supporting this is already tracked by https://github.com/google/ExoPlayer/issues/6562, so we can close this as a duplicate of that issue. We're unlikely to add support any time soon though.

**Closed as completed by ojw28** 2020-02-28 19:28 UTC
Labels: duplicate, question
