### ISSUE TITLE
HLS playback fails when load control uses  loadControl.setPrioritizeTimeOverSizeThresholds(false);

### ISSUE THREAD

**Issue by neuro79** [google/ExoPlayer#7622] opened 2020-07-13 17:00 UTC
We have been able to reproduce a possible bug in Exoplayer implementation. We are able to reproduce the problem using Exoplayer Demo app. The first time we see this problem was an HLS playlist where the first video resolution was failing (404) but the other resolutions was available (testing HLS fallback) 

Playback fails to play HLS when the first track in the playlist reports an error, track selector is not able to switch to other track. 

We are able to reproduce this issue using the media.exolist.json file provided in Exoplayer demo, the element that fails is : "Apple 16x9 basic stream"

To reproduce the problem add this code to the PlayerActivity.
```
 DefaultLoadControl createPlayerLoadControl() 
{
    DefaultLoadControl.Builder loadControl = new DefaultLoadControl.Builder();
    //Buffer size in time has priority over size.
    loadControl.setPrioritizeTimeOverSizeThresholds(false);
    return loadControl.createDefaultLoadControl();
  }
```

```
 player =
          new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
              .setTrackSelector(trackSelector)
              .setLoadControl(createPlayerLoadControl())
              .build();
```

Changing `loadControl.setPrioritizeTimeOverSizeThresholds(true);` playback works properly. 

We have have tested one modification of DefaultLoadControl, when the reset function is called instead of force targetBufferSize to 0 we force a value different from 0.

```
  private void reset(boolean resetAllocator) {
    targetBufferSize = prioritizeTimeOverSizeThresholds ? 0 : 1000000;
    isBuffering = false;
    if (resetAllocator) {
      allocator.reset();
    }
  }
```

Later Load control will calculate the proper targetBufferSize but this solution doesn't seems to be the most appropriated.

**Comment by fgl27** [comment] 2020-07-13 17:33
`player = new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory) .setTrackSelector(trackSelector) .setLoadControl(createPlayerLoadControl()) .build();`

should be 

`player = new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory) .setTrackSelector(trackSelector) .setLoadControl(createPlayerLoadControl().build());`

just make yours `createPlayerLoadControl()` return the already build control, you don' need to build only when using

**Comment by AquilesCanta** [comment] 2020-07-16 11:54
Could you share with me a bugreport captured shortly after reproducing the issue? There are instructions about this in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). Aside, the Apple 16x9 basic stream URL in the demo app doesn't return 404 for the first media playlist. Are you introducing some form of modification in the library to cause this behavior?

**Comment by neuro79** [comment] 2020-07-16 15:20
[bugReport.log](https://github.com/google/ExoPlayer/files/4932383/bugReport.log)
We was able to reproduce the same issue using an HLS playlist where the first video track was failing, in Apple 16x9 as you said there is not any 404 response but the behaviour of the player is the same, player keep buffering at 0% and playback never begins.
I have realise right now that if I use fast forward then playback begins but autoplay is not working due to as we said the buffer remains at 0%

**Comment by AquilesCanta** [comment] 2020-07-16 15:53
I think you got a dumpstate instead of a bugreport as requested. Please capture a bugreport by running `adb bugreport` shortly after reproducing the issue.

**Comment by neuro79** [comment] 2020-07-17 05:43
Please find attached a new bugreport. We called adb bugreport just after the issue has been reproduced. Player is not reporting any error, just keeping buffer at 0%.
[adbBugreport.log](https://github.com/google/ExoPlayer/files/4935931/adbBugreport.log)

**Comment by AquilesCanta** [comment] 2020-07-17 10:26
I'm not clear about something: In the problem description you mentioned that one of the conditions to reproduce this issue is that the first resolution returns 404. However, in the bugreport I cannot see any instance of InvalidResponseCodeException. Can you clarify this?

In general, in order to accelerate this process I would advise you provide a list of very precise steps I can take (parting from an unmodified demo app) in order to reproduce this issue.

[Internal reference: b/144538905 seems related but I'm not 100% sure since the reporter's repro steps do not seem similar enough].

**Comment by neuro79** [comment] 2020-07-17 11:06
**Steps to reproduce the issue:**

[PlayerActivity.zip](https://github.com/google/ExoPlayer/files/4937376/PlayerActivity.zip)

- Download Exoplayer v2.11.7  from https://github.com/google/ExoPlayer/tree/release-v2
- Unzip and copy PlayerActivity.java to demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java
- Launch demo application.
- Choose HLS -> Apple 16x9 basic stream.

**Result:**
Device is not playing the content.
**Expected:**
Device begins Apple 16x9 playback.

**Comments**
Inside this PlayerActivity file you will see the changes we did in demo app to reproduce the problem, basically enable setPrioritizeTimeOverSizeThresholds.

Please let me know if you are able to reproduce using this way.

**Comment by AquilesCanta** [comment] 2020-07-17 15:04
I think your issue may already be fixed in the dev branch. Could you please try reproducing there?

**Comment by neuro79** [comment] 2020-07-17 15:31
Hi,

Yeah, it works properly in dev-v2. Looks like the commit that solve the issue is:
d48dc4c15933dd8354cbcc6260c48565bb850e15
Please proceed to close the ticket.

**Comment by AquilesCanta** [comment] 2020-07-17 17:32
Cool! Thanks for reaching out.

**Closed as completed by AquilesCanta** 2020-07-17 17:32 UTC
Labels: bug
