### ISSUE TITLE
Player is dropping frame when playing Highest profiles (DASH+widevine) on Samsung S6

### ISSUE THREAD

**Issue by Sky35** [google/ExoPlayer#1690] opened 2016-07-21 09:07 UTC
Hello, 
when using the player on Samsung S6 and activating widevine encryption, we are seeing that the player is not able to decode all the frames and it is like it is dropping some of them. What it is strange is the fact that it is only when encryption is activated, one the higher video profiles (1.6Mbps or higher) and also only for Samsung S6 Android device
Player version used: 1.5.7 and 1.5.9

**Comment by Sky35** [comment] 2016-07-25 12:18
By making more test, I have observed that if we change the manner how the stream is encoding, the issue went gone: when frames are encoded through 1 slice instead of 4, the player is able to decode it correctly.
Is it a restriction for the player?

**Comment by andrewlewis** [comment] 2016-07-25 12:53
Playback of streams that use more than one slice per frame should work I think. Could you provide a test stream so we can reproduce the issue (either here or by email to dev.exoplayer@gmail.com)? Thanks!

**Comment by Sky35** [comment] 2016-07-25 13:05
Thank you for your feedback.

I have got an example where there is 2 or 4 Slices per Frame (depending of the resolution):

http://189.28.24.25/sdash/eng_test_15/manifest_03.mpd

For the protected content, you may need the LA URL: https://widevine-proxy.appspot.com/proxy


Thanks
Arnaud

**Comment by wvpaf** [comment] 2016-08-09 20:34
An ADB Bugreport might be helpful as well.

**Comment by wvpaf** [comment] 2016-08-16 21:10
@Sky35, any updates?

**Comment by gvidda** [comment] 2016-09-12 12:15
We have this issue also, but different behaviour on different devices.
On a Nexus 6 there's dropped frames (like a framerate at 4-5 instead of 30) and on a Samsung Galaxy Tab S2 (SM-T810) there are visible artifacts in the video.
Version used 1.5.9.

**Comment by wvpaf** [comment] 2016-09-13 20:23
@gvidda, Since the devices are exhibiting different issues it would be best to create separate cases with supporting information like ADB bugreports and links to content to reproduce. 
Thanks.

**Comment by mlondon1** [comment] 2016-09-20 13:03
This is the exact issue I have for encrypted content.  I created a ticket for it, but it sounds like a dupe

https://github.com/google/ExoPlayer/issues/1813

**Comment by ojw28** [comment] 2017-01-13 17:22
Closing because no bug reports have been provided.

**Closed as completed by ojw28** 2017-01-13 17:22 UTC
Labels: need more info
