### ISSUE TITLE
ResolvingDataSource w/QueryString injection for video segments

### ISSUE THREAD

**Issue by cobookman** [google/ExoPlayer#6391] opened 2019-09-05 06:48 UTC
Would the following be how to use ResolvingDataSource for injecting QueryStrings to video segments? Particularily on adding token auth Query Strings without needing to generate a per-user manifest file.

Ref: https://github.com/google/ExoPlayer/issues/5779

```
public class MainActivity extends AppCompatActivity {
  @Override
  protected void onCreate ( Bundle savedInstanceState ) {
    Context context = getApplicationContext();

    // URL pointing to the DASH Manifest
    Uri dashManifest = Uri.parse("https://myservice.com/manifest.mpd");

    // query string to inject for HTTP calls to resources listed in the manifest (cough video, audio, subtitle)
    String queryStringInjection = "?someQuery=string&with=values";


    // Create a data source factory.
    DataSource.Factory upstreamDataSource = new DefaultHttpDataSourceFactory(Util.getUserAgent(context, "app-name"));

    // Code which determines how to resolve network resources
    ResolvingDataSource.Resolver resolver = new Resolver() {
      // Not modifing dataSpec.
      DataSpec resolveDataSpec(DataSpec dataSpec) throws IOException {
        return dataSpec;
      }

      /**
       * Injects Signed URL Query String
       * The ResolvingDataSource first grabs a Network Request generated
       * by an upstreamDataSource. Then resolvReportedUri(uri) is called for 
       * getUri(..) calls. 
       */
      default Uri resolveReportedUri(Uri uri) {
        return uri + queryStringInjection;
      }
    };

    DataSource.Factory dataSourceFactory = new ResolvingDataSource.Factory(upstreamDataSource, resolver);


    // Create a DASH media source pointing to a DASH manifest uri.
    MediaSource mediaSource = new DashMediaSource.Factory(dataSourceFactory).createMediaSource(dashManifest);

    // Create a player instance.
    SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(context);

    // Prepare the player with the DASH media source.
    player.prepare(mediaSource);
  }
}
```

**Comment by ojw28** [comment] 2019-09-05 12:24
Duplicate of https://github.com/google/ExoPlayer/issues/6065, which I've re-opened.

**Closed as completed by ojw28** 2019-09-05 12:24 UTC
Labels: duplicate, question
