### ISSUE TITLE
TtmlRegion reported without origin or extent

### ISSUE THREAD

**Issue by xirac** [google/ExoPlayer#7061] opened 2020-03-09 10:48 UTC
Following my first PR #6860, a deeper analysis has been done on the Ttml chunks that are not being displayed.

Here are 3 consecutive TTML chunks where the 2nd is not displayed.
1620467150624629.ttml is the first appearance of the subtitle:
 * It is correctly displayed by ExoPlayer
 * It is in the cue with ID "p_0001",
   * referencing region with ID "speaker_2",
   * ending at "45012:58:37.063" (the end of the fragment).

[1620467150624629.txt](https://github.com/google/ExoPlayer/files/4306069/1620467150624629.txt)

1620467170636759.ttml is the continuation of the subtitle:
 * It is not displayed by ExoPlayer
 * It is in the cue with ID "p_0000"
   * referencing region with ID "speaker",
   * begining at "45012:58:37.063" (begining of the fragment, direct continuation of previous cue),
   * ending at "45012:58:39.022" (end of the fragment).
 * region with ID "speaker" is strictly equivalent to previous fragment's region "speaker_2"
 * region "speaker_2" is not present in this fragment as it is not used

[1620467170636759.txt](https://github.com/google/ExoPlayer/files/4306070/1620467170636759.txt)

1620467190227559.ttml is the end of this line:
 * It is brievly displayed by ExoPlayer, before being replaced by the next line
 * It is in the cue with ID "p_0000",
   * referencing region with ID "speaker_1",
   * begining at "45012:58:39.022" (begining of the fragment, direct continuation of previous cue),
   * ending at "45012:58:40.339" (begining of the next cue).
 * region "speaker_1" is strictly equivalent to previous fragment's region "speaker"
 * region "speaker_2" exists in this fragment as it is used by the next cue

[1620467190227559.txt](https://github.com/google/ExoPlayer/files/4306071/1620467190227559.txt)

As far as I can see, the 2nd chunk declares origin and extent in styling's style whereas the first and third one declare origin and extent in layout's region.

Is #6978 somehow related to that declaration outside of a region ?
Should I update parseNode or parseStyleAttributes to read properly origin and extent values?

Thanks for your help!

**Comment by tonihei** [comment] 2020-03-09 11:06
@icbaker Assigning to you as you looked into the previous PR already.

**Comment by icbaker** [comment] 2020-03-10 09:25
I agree this looks similar to #6978 but i think it's actually not the same. I think this is the same root cause as #2953 (referential styling).

In your second example you have a `region` which uses a **referential** `style="speakerStyle"` attribute. I believe this is what doesn't currently work in ExoPlayer. This commit on #2953 looks like it could be related too: https://github.com/google/ExoPlayer/commit/c7948f2f7a9b9bee91b116fbcc61e727443453cf

#6978 would be relevant if your `div` directly specified `tts:origin` or `tts:extent` attributes instead of going via `region`.

I briefly started to look at adding referential styling support a while ago, but didn't get very far. I'll try and find some time to take another look soon.

**Comment by icbaker** [comment] 2020-03-10 09:25
Duplicate of #2953.

**Closed as completed by icbaker** 2020-03-10 09:25 UTC
Labels: duplicate, question
