### ISSUE TITLE
CryptoException occurs when playing Widevine DASH on a specific device

### ISSUE THREAD

**Issue by ogawa-ma** [google/ExoPlayer#7080] opened 2020-03-13 07:06 UTC
### [REQUIRED] Searched documentation and issues
・ExoPlayer Javadoc.
・ExoPlayer Issues

### [REQUIRED] Question
CryptoException occurs when playing Widevine DASH on Android OS7.
Why does it happen?

```
com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:333)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1343)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:814)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:818)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2505)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:63)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1334)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:814) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:818) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

Version of ExoPlayer being used: 2.10.6

Device information that occurred
Device name: HUAWEI P9 lite
Model Number: HUAWEI VNS-L22
Android version: 7.0

Device name: Android Studio emulator
Model Number:-
Android version: 7.1.1

**Comment by tonihei** [comment] 2020-03-13 13:17
Could you check your ExoPlayer version again? You mentioned 2.10.6, but the stack trace clearly shows a class (SynchronousMediaCodecAdapter) that is not yet in any release, so it looks more like you are using the dev-branch? 

If you can reproduce, please also provide a bugreport (ideally with adding an `EventListener` first) and the media file. You can send both to dev.exoplayer@gmail.com with subject "Issue #7080"

**Comment by ogawa-ma** [comment] 2020-03-16 09:12
sorry. It was a log on the dev-v2 branch.

Also occurs in 2.10.6.
```
    com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1126)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:658)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2505)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1117)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:658) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

Occurs on videos with a long license expiration date (after January 19, 2038).
If the expiration date is set before January 18, 2038, it will not occur.

bugreport sent to dev.exoplayer@gmail.com.
If you need a media file for your investigation, let me know so I'll prepare it.

**Comment by ogawa-ma** [comment] 2020-03-24 04:08
What is the progress on this issue?

**Comment by tonihei** [comment] 2020-04-17 17:48
Sorry for the delayed answer. The bugreport unfortunately doesn't contain anything useful maybe except this log line: "WVCdm   : Decrypt error result in session sid2 during encrypted block: 5"

If the problem can be triggered only by changing the expiration date, then it sounds as if we are running into the [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem). My guess would be that some part of Huawei's Widevine module is using int instead of long for the the timestamps and thus run into this issue. 

@paf-wv Is that something that can only be fixed by Huawei, or is there a potential bug in the Android code as well? 

@ogawa-ma If it's easy to provide a test stream, please share with dev.exoplayer@gmail.com so that we can debug if needed. Could you also confirm that by the problem can be fixed by only changing the expiration date and nothing else? Thanks.

**Comment by ogawa-ma** [comment] 2020-04-20 03:44
@tonihei 
Thank you for your response.

Regarding the information provided, we plan to provide the following information.
・ Media file (.mpd) URL
・ URL of the license server

Is there any other information I need?

**Comment by tonihei** [comment] 2020-04-20 07:48
That's probably enough information, unless your stream needs special request headers or similar.

**Comment by ogawa-ma** [comment] 2020-04-21 03:20
I have sent the media file URL and the license server URL to dev.exoplayer@gmail.com.

**Comment by jt64** [comment] 2020-04-21 21:45
If this is a 2038 issue it is likely in the Widevine implementation, not in Huawei since the license durations are handled in widevine code, not OEM code. A bug has been opened for Widevine to follow up. As Android N devices probably won't be getting an update, you will likely need to work around this by limiting your license expiration times to before 2038. Widevine will check if this is still an issue on current releases where it can be fixed.

**Comment by jt64** [comment] 2020-05-05 22:25
After looking into this it is a known issue, and was resolved in Android O. A test was added to our test suite to confirm that the bug is fixed on Android O and newer devices, so it is likely this device was not recent enough to be verified by the test.  The problem only happens on devices that do not have hardware backed widevine implementations, that is why you may only see it on some devices. The workaround would be to avoid using license durations far into the future.

**Closed as completed by jt64** 2020-05-05 22:25 UTC
Labels: bug: in platform drm
