### ISSUE TITLE
Player slows down, eventually stops after many loops

### ISSUE THREAD

**Issue by derlucas** [google/ExoPlayer#4869] opened 2018-09-26 06:51 UTC
### Issue description
I made a simple test app. The App only adds two h265 videos to a List and play them in a loop. I've tested URI to a remote server via http, and a version with downloading the files locally and playing them from there. Makes no difference.
After 300-400 track changes, the Player stops looping and the End of the second Video is show as still Image. After 200-300 track changes the playback speed is getting slower and stutters sometimes.

I added a workaround which reloads the Playlist after N loops. This seems to be working fine. But i'd rather know the source of this problem and maybe get this fixed if this is indeed a valid bug.

### Reproduction steps
Use this app: https://github.com/derlucas/exoplayerlooptest and my two videos, play it back over night and see the stopped player. After a couple of hours the problem occurs.

### Link to test content
I cannot share the videos in public, so i will send the Links via Email.

### Version of ExoPlayer being used
ExoPlayer 2.8.4

### Device(s) and version(s) of Android being used
The Device is a Shuttle NS02_Series with Android 5.1.1, Security Patch 2016-04-01, Kernel 3.10.0, FW Version 20180810.202204

### A full bug report captured from the device
I will send the complete bug report via Email, too.

**Comment by tonihei** [comment] 2018-09-26 07:35
That is most likely a duplicate of #4559. Can you check if the problem is fixed with our dev branch? Or wait for the upcoming 2.9.0 release and check there.

Closing the issue for now. If the problem is still occuring even after the update to 2.9.0 or when using the dev branch, please feel free to reopen.

**Closed as completed by tonihei** 2018-09-26 07:35 UTC
Labels: duplicate

**Comment by derlucas** [comment] 2018-09-26 08:52
Thanks for the quick reply. I'm a little embarrassed i did not find the other Issues. I'll try FLAG_WORKAROUND_IGNORE_EDIT_LISTS and wait for the 2.9.0 release. Thanks!
