### ISSUE TITLE
Slow HLS stream download

### ISSUE THREAD

**Issue by semirzahirovic** [google/ExoPlayer#4828] opened 2018-09-17 12:09 UTC
### Issue description
We have tested the downloading of HLS streams in our app. Although it works fine, time to download stream is huge. Is there an easy way to **reduce** download time?

On the server-side, everything is hosted on a Google Storage Bucket, served through Google Cloud CDN using HTTP/2 so the hosting should not be the bottleneck.
When doing a quick benchmark on desktop, the first download (before being cached by the CDN) takes 11 minutes, while the second one (after being cached at the nearest edge-location) takes only 3 minutes.
However, when downloading the same file in our app using ExoPlayer, the download takes *22 minutes* on the first try and *18 minutes* after caching.

We have also tried creating bigger segments and in that case download is much faster, but problem is that seeking when streaming takes more time, so that solution is not optimal at all.

We are also using OkHttpDataSourceFactory with v3.11.0 of OkHttp.

### Link to test content
Here is the link where the issue can be reproduced: https://storage.googleapis.com/strillo-demo/hls-test/oldfashioned_girl_1808_librivox.m3u8.

### Version of ExoPlayer being used
Exo player v2.8.3.

### Device(s) and version(s) of Android being used
Any supported device/version.

**Comment by andrewlewis** [comment] 2018-09-17 13:43
#4253 may be related.

**Comment by semirzahirovic** [comment] 2018-09-17 13:57
@andrewlewis thanks for suggestion. Not sure if it correlates to the issue you linked as this is reproducible by having the Cache folder empty and downloading only one stream.

**Comment by andrewlewis** [comment] 2018-09-17 15:30
I wonder whether the mobile device is relatively slow because the chunk downloads are serialized. #4273 is a feature requests for parallel chunk downloads. I guess one way to investigate this hypothesis would be to start multiple downloads concurrently and look at the total throughput.

**Comment by ojw28** [comment] 2018-09-17 18:00
* Can you be more specific about what device(s) you've tested this on?
* Are you writing to internal storage or an SD card, and does this make any difference? If the latter, have you tried with a different SD card? If I remember correctly, we've seen some other cases where it's turned out that the SD card is just incredibly slow to write to, so it would be helpful if you could check this.

If it's not the SD card then I agree it's probably a dupe of #4273.

**Comment by semirzahirovic** [comment] 2018-09-18 08:25
@ojw28 Yeah, it is a dupe of #4273. We tried downloading in internal storage and SD card. Since there is a lot of segments, the download is slow. Tested on S7, S9, S9 plus, Pixel 2...

We are hoping that the parallel segment download feature will be implemented soon.

**Comment by ojw28** [comment] 2018-09-18 11:00
Closing as duplicate.

**Closed as completed by ojw28** 2018-09-18 11:00 UTC
Labels: question
