### ISSUE TITLE
Set request header does not work when uses Cronet

### ISSUE THREAD

**Issue by hnv248** [google/ExoPlayer#9419] opened 2021-09-13 02:42 UTC
I set 'Referer' header for httpDataSourceFactory which uses CronetDataSource but It does not work.
When I set 'Referer' header for httpDataSourceFactory which uses DefaultHttpDataSource, it works.

**Comment by ojw28** [comment] 2021-09-13 09:56
Duplicate of https://github.com/google/ExoPlayer/issues/8292.

**Closed as completed by ojw28** 2021-09-13 09:56 UTC
Labels: duplicate
