### ISSUE TITLE
Error initializing AudioTrack

### ISSUE THREAD

**Issue by Brianvdb** [google/ExoPlayer#880] opened 2015-10-19 15:24 UTC
I have an Activity that is declared the following way
     
    <activity
		 android:name=".MyActivity"
		  android:label="@string/app_name"
          android:launchMode="standard"
	    android:configChanges="orientation|screenSize">

I need to handle configuration/orientation changes myself. Everytime the device is rotating I release the player and re-init everything in the `onConfigurationChanged(Configuration)` method.

Now after like 5~8 orientates I get the following error on all of my devices

```
10-19 17:07:44.760  15501-13123/com.someapp.debug I/SoftAAC2﹕ Reconfiguring decoder: 0->44100 Hz, 0->2 channels
10-19 17:07:44.790  15501-13019/com.someapp.debug E/AudioTrack﹕ AudioFlinger could not create track, status: -12
10-19 17:07:44.790  15501-13019/com.someapp.debug E/AudioTrack-JNI﹕ Error initializing AudioTrack
10-19 17:07:44.790  15501-13019/com.someapp.debug E/android.media.AudioTrack﹕ Error code -20 when initializing AudioTrack.
10-19 17:07:44.790  15501-13019/com.someapp.debug E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 67584)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:335)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:828)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:458)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 67584)
            at com.google.android.exoplayer.audio.AudioTrack.checkAudioTrackInitialized(AudioTrack.java:791)
            at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:340)
            at com.google.android.exoplayer.audio.AudioTrack.initialize(AudioTrack.java:314)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:330)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:828)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:458)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

After I get this exception I need to restart my whole app for any video to load again, otherwise it will throw the same exception everytime I load a video.
I am playing mp4 videos only.

Am I doing something wrong?

**Comment by ojw28** [comment] 2016-09-09 20:55
Closing as duplicate of https://github.com/google/ExoPlayer/issues/954.

**Closed by ojw28** 2016-09-09 20:55 UTC
