### ISSUE TITLE
ffmpeg extension support  for exoplayer.

### ISSUE THREAD

**Issue by zhangabvc** [google/ExoPlayer#5176] opened 2018-11-30 07:39 UTC
xoplayer cannot play Audio-mpg2 format.So add ffmpeg to support some audio format.
To perform according to this url https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg
But cannot use ffmpeg.
do as follows:
COMMON_OPTIONS="
--target-os=android 
--disable-static 
--enable-shared 
--disable-doc 
--disable-programs 
--disable-everything 
--disable-avdevice 
--disable-avformat 
--disable-swscale 
--disable-postproc 
--disable-avfilter 
--disable-symver 
--disable-swresample 
--enable-avresample 
--enable-decoder=vorbis 
--enable-decoder=opus 
--enable-decoder=ffmpeg 
--enable-decoder=flac 
" && 
cd "${FFMPEG_EXT_PATH}/jni" && 
(git -C ffmpeg pull || git clone git://source.ffmpeg.org/ffmpeg ffmpeg) && 
cd ffmpeg && git checkout release/4.0 && 
./configure 
--libdir=android-libs/armeabi-v7a 
--arch=arm 
--cpu=armv7-a 
--cross-prefix="${NDK_PATH}/toolchains/arm-linux-androideabi-4.9/prebuilt/${HOST_PLATFORM}/bin/arm-linux-androideabi-" 
--sysroot="${NDK_PATH}/platforms/android-9/arch-arm/" 
--extra-cflags="-march=armv7-a -mfloat-abi=softfp" 
--extra-ldflags="-Wl,--fix-cortex-a8" 
--extra-ldexeflags=-pie 
${COMMON_OPTIONS} 
&& 
make -j4 && make install-libs && 
make clean && ./configure 
--libdir=android-libs/arm64-v8a 
--arch=aarch64 
--cpu=armv8-a 
--cross-prefix="${NDK_PATH}/toolchains/aarch64-linux-android-4.9/prebuilt/${HOST_PLATFORM}/bin/aarch64-linux-android-" 
--sysroot="${NDK_PATH}/platforms/android-21/arch-arm64/" 
--extra-ldexeflags=-pie 
${COMMON_OPTIONS} 
&& 
make -j4 && make install-libs && 
make clean && ./configure 
--libdir=android-libs/x86 
--arch=x86 
--cpu=i686 
--cross-prefix="${NDK_PATH}/toolchains/x86-4.9/prebuilt/${HOST_PLATFORM}/bin/i686-linux-android-" 
--sysroot="${NDK_PATH}/platforms/android-9/arch-x86/" 
--extra-ldexeflags=-pie 
--disable-asm 
${COMMON_OPTIONS} 
&& 
make -j4 && make install-libs

cd "${FFMPEG_EXT_PATH}"/jni && 
${NDK_PATH}/ndk-build APP_ABI="armeabi-v7a arm64-v8a" -j4

Finally generated like this libavcodec.so libavresample.so libavutil.so libffmpeg.so for arm64v8.

Modify code on DefaultRenderersFactory.java
@deprecated
public DefaultRenderersFactory(
Context context,
@nullable DrmSessionManager drmSessionManager,
@ExtensionRendererMode int extensionRendererMode,
long allowedVideoJoiningTimeMs) {
this.context = context;
this.extensionRendererMode = EXTENSION_RENDERER_MODE_PREFER ; //Modified
//this.extensionRendererMode = extensionRendererMode; //old
this.allowedVideoJoiningTimeMs = allowedVideoJoiningTimeMs;
this.drmSessionManager = drmSessionManager;
}

![1](https://user-images.githubusercontent.com/44994911/49273492-16dffe80-f4b0-11e8-81b9-fb7d29f78975.jpg)
![2](https://user-images.githubusercontent.com/44994911/49273494-16dffe80-f4b0-11e8-8005-67d4b61ba692.jpg)
![3](https://user-images.githubusercontent.com/44994911/49273495-17789500-f4b0-11e8-99f2-69d97d421a6e.jpg)

but this log 'Loaded FfmpegAudioRenderer.' does not appear.

**Comment by andrewlewis** [comment] 2018-11-30 08:16
Duplicate of #5154.

**Closed as completed by andrewlewis** 2018-11-30 08:16 UTC

**Comment by zhangabvc** [comment] 2018-11-30 08:24
> Duplicate of #5154.
yes. 

Can help me solve it?
