### ISSUE TITLE
Some Podcasts are not playing due to d: Error code: 262206

### ISSUE THREAD

**Issue by geeta4** [google/ExoPlayer#6915] opened 2020-01-27 11:53 UTC
Some podcasts are not playing on google podcast  and throwing error

```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.ae: Unable to connect to https://play.hubhopper.com/2e3222d384ef9a0c9c4f15ab3e0f184f.mp3?s=hh-rss-feed
        at com.google.android.apps.gsa.staticplugins.p.x.a(SourceFile:50)
        at com.google.android.exoplayer2.upstream.aw.a(SourceFile:11)
        at com.google.android.exoplayer2.source.bc.b(SourceFile:10)
        at com.google.android.exoplayer2.upstream.am.run(SourceFile:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.google.android.apps.gsa.shared.o.d: Error code: 262206
        at com.google.android.libraries.gsa.f.a.bw.a(SourceFile:17)
        at com.google.android.libraries.gsa.f.a.bw.a(SourceFile:25)
        at com.google.common.u.a.f.a(SourceFile:3)
        at com.google.common.u.a.h.run(SourceFile:23)
        at com.google.common.u.a.aw.execute(SourceFile:3)
        at com.google.common.u.a.d.b(SourceFile:74)
        at com.google.common.u.a.d.a(SourceFile:73)
        at com.google.common.u.a.d.a(SourceFile:177)
        at com.google.common.u.a.f.a(SourceFile:6)
        at com.google.common.u.a.h.run(SourceFile:15)
        at com.google.common.u.a.aw.execute(SourceFile:3)
        at com.google.common.u.a.d.b(SourceFile:74)
        at com.google.common.u.a.d.a(SourceFile:73)
        at com.google.common.u.a.d.a(SourceFile:177)
        at com.google.common.u.a.f.a(SourceFile:6)
        at com.google.common.u.a.h.run(SourceFile:15)
        at com.google.common.u.a.aw.execute(SourceFile:3)
        at com.google.common.u.a.d.b(SourceFile:74)
        at com.google.common.u.a.d.a(SourceFile:73)
        at com.google.common.u.a.d.a(SourceFile:177)
        at com.google.common.u.a.f.a(SourceFile:6)
        at com.google.common.u.a.h.run(SourceFile:15)
        at com.google.common.u.a.aw.execute(SourceFile:3)
        at com.google.common.u.a.d.b(SourceFile:74)
        at com.google.common.u.a.d.a(SourceFile:73)
        at com.google.common.u.a.d.b(SourceFile:167)
        at com.google.android.libraries.gsa.f.a.d.a(SourceFile:5)
        at com.google.android.libraries.gsa.f.a.d.a(SourceFile:11)
        at com.google.common.u.a.bq.run(SourceFile:9)
        at com.google.common.u.a.aw.execute(SourceFile:3)
        at com.google.common.u.a.d.b(SourceFile:74)
        at com.google.common.u.a.d.a(SourceFile:73)
        at com.google.common.u.a.d.b(SourceFile:167)
        at com.google.android.libraries.gsa.f.a.br.onRedirectReceived(SourceFile:45)
        at org.chromium.net.impl.w.run(SourceFile:7)
        at com.google.android.libraries.gsa.f.a.ao.run(SourceFile)
        at com.google.android.libraries.gsa.n.a.k.run(SourceFile:2)
        at com.google.android.apps.gsa.shared.util.c.a.cc.a(SourceFile:3)
        at com.google.android.apps.gsa.shared.util.c.a.cf.run(SourceFile:2)
        at com.google.apps.tiktok.concurrent.ar.run(SourceFile:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at com.google.apps.tiktok.concurrent.b.run(SourceFile:4)
        at java.lang.Thread.run(Thread.java:818) 
01-27 17:19:23.979 24157-24157/? E/APWDelegate: onPlayerError
```

**Comment by ojw28** [comment] 2020-01-27 13:14
This isn't really an ExoPlayer issue. The referenced `https` URL redirects to a `http` URL, which redirects back to an `https` URL again:

```
> curl -sLD - https://play.hubhopper.com/2e3222d384ef9a0c9c4f15ab3e0f184f.mp3?s=hh-rss-feed

HTTP/2 302 
content-type: text/html; charset=UTF-8
location: http://www.ivoox.com/misterios-madrid-juan-miguel-marsella-23_mf_46808510_feed_1.mp3
date: Mon, 27 Jan 2020 13:11:30 GMT
server: nginx/1.12.2
x-powered-by: PHP/7.2.21
x-cache: Miss from cloudfront
via: 1.1 c149c6b8a4d6f497cac6f2d9e9e6be41.cloudfront.net (CloudFront)
x-amz-cf-pop: AMS54-C1
x-amz-cf-id: qcQG1jgVnytYLWJlR1XOz9hzKieFZsyB6NBxbwjhgQuKN10WPgOF5Q==

HTTP/1.1 302 Found
Server: nginx
Date: Mon, 27 Jan 2020 13:11:30 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Set-Cookie: countAudios=1
Location: https://podcastcdn-23.ivoox.com/audio/0/1/5/8/misteriosmadridjuanmiguelmarsella23-misteriosnegro-ivoox46808510.mp3?secure=vssP9OYv55eE8A3jdJPaKg==,1580137890

HTTP/2 200 
date: Mon, 27 Jan 2020 13:11:30 GMT
content-type: audio/mpeg
content-length: 5053768
last-modified: Tue, 21 Jan 2020 22:12:13 GMT
etag: "5e27773d-4d1d48"
access-control-allow-origin: *
server: CDN77-Turbo
x-edge-ip: 185.152.65.119
x-edge-location: pragueCZ
x-cache: HIT
x-age: 470732
accept-ranges: bytes
```

Google Podcasts is most likely failing because it's configured to disallow http entirely (meaning it can't follow the rediret), or because it's configured to disallow following https to http redirects. I'll close this issue, since it's not an ExoPlayer problem, but I'll also raise an internal issue with the Google Podcasts team because it's unclear whether the current behavior is intentional, and even if it is the failure mode should probably be clearer.

**Closed as completed by ojw28** 2020-01-27 13:14 UTC
Labels: question

**Comment by geeta4** [comment] 2020-01-28 10:54
but it is playing https://play.hubhopper.com/79ca341bb30bd5bce43d54f7282d0ce0.mp3?s=hh-rss-feed

**Comment by ojw28** [comment] 2020-01-28 11:11
The Podcast team have confirmed that https to http redirects don't work, and that they'll look at fixing it [Internal ref: 148371236]. I'm not sure how the second link works, since that also contains an https to http redirect when I try using curl. It's possible that the redirect is different depending on the UserAgent, etc.

**Comment by geeta4** [comment] 2020-01-28 11:21
non working:
1. Meditacion Online y Mindfulness
2. Economia Falada
3. Misterios en Negro

working:
The Tollywood project

how if working is also redirecting and for cross protocol as well?
