### ISSUE TITLE
c2.android.vp8.decoder doesn't play videos with odd resolutions (e.g., height=405px)

### ISSUE THREAD

**Issue by Pentaphon** [google/ExoPlayer#9103] opened 2021-06-23 17:29 UTC
Here's the problematic file which results in the following error: 

![Screenshot_20210623-102205](https://user-images.githubusercontent.com/49374058/123141615-6d660d00-d40d-11eb-9121-cd2a8898ca7a.png)

https://gofile.io/d/pOEXA2

1) Download the file from the filehost link and play with Exoplayer 2.14.1
2) Observe the error message you can see above; playback fails
3) Tried another player aka https://github.com/mpv-android/mpv-android and it plays the file without issue.

- Exoplayer 2.14.1 (using this Exoplayer-based player found here: https://github.com/moneytoo/Player/releases/tag/v0.38)
- Android version 10
- Android device Motorola G Play (2021)

**Comment by icbaker** [comment] 2021-06-24 13:21
The provided file plays fine for me in the 2.14.1 demo app on a Pixel 3a XL. This selected the `c2.qti.vp8.decoder` codec.

It sounds like this might be device-specific and unfortunately I don't have access to a Motorola G Play (2021) to test with. 

Do you observe this on any other devices?

Does it fail 100% of the time or is it only occasional? (the linked issue suggests the failure is occasional)

Can you provide a bugreport (`adb bugreport`) taken after reproducing the failure in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html)? It might contain some useful information. 

> Tried another player aka https://github.com/mpv-android/mpv-android and it plays the file without issue.

I suspect (but don't know) that this player isn't using the platform decoder (which ExoPlayer does) and bundles a software decoder instead. i.e. the fact it plays OK there doesn't pin-point this as an ExoPlayer issue, because the underlying decoders are also different.

**Comment by icbaker** [comment] 2021-06-24 13:45
I've managed to reproduce on my Pixel 3a XL by forcing the demo app not to use the `c2.qti.vp8.decoder` decoder so that it picks the `c2.android.vp8.decoder` decoder instead.

The codec name suggests it's coming from AOSP - I will raise this issue with the team that maintains those.

One thing that looks unusual is that the height of the video is an odd number of pixels (405), it might be that this causes problems here (the third parameter is `step`, i.e. this checks if the value is both within the specified range **and** even):
https://cs.android.com/android/platform/superproject/+/master:frameworks/av/media/codec2/components/vpx/C2SoftVpxDec.cpp;l=72;drc=f6c0c3c515a363113573bcf08aeee56a8d99c64f

It seems that if this is the problem, the codec shouldn't claim it can play the file when queried (rather the current behaviour of claiming support and then crashing when playback is attempted).

**Comment by icbaker** [comment] 2021-06-24 15:10
> It seems that if this is the problem, the codec shouldn't claim it can play the file when queried (rather the current behaviour of claiming support and then crashing when playback is attempted).

Actually this sentence isn't fair, because we round the height up to an even number before querying the platform:
https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecInfo.java#L657-L660

If I remove those lines then playback still fails, but at least it's clear that the file isn't supported by the codec so the failure is somewhat expected (the `format_supported=NO_EXCEEDS_CAPABILITIES` bit):
```
2021-06-24 15:52:22.918 8704-8748/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/x-vnd.on2.vp8, null, -1, und, [720, 405, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

@ojw28 Do you think the benefits of the workaround for https://github.com/google/ExoPlayer/issues/6551 outweigh the costs/confusion of reporting a decoder exception with `format_supported=YES` when in fact the decoder would tell us it doesn't support the video (because the height is odd). Given the result in both cases here is the same exception, it does seem like the workaround (which enables playback of content that otherwise doesn't play) is probably preferable.

**Comment by Pentaphon** [comment] 2021-06-24 19:16
>Does it fail 100% of the time or is it only occasional? (the linked issue suggests the failure is occasional)

Absolutely 100% of the time. I've tried it again just now to be sure. It never plays. 

> Do you observe this on any other devices?

I have a Snapdragon 632 device and an Exynos tablet that do not show this error, oddly enough. Those devices are a bit more mature than my current Snapdragon 460 device (the Moto G Play 2021) that shows the error. 

I've seen this error on another user's bug report (with log) on another Exoplayer-based app, an interestingly enough, his problematic file is 1280x720. That user got an output of: 

`Decoder init failed: OMX.Exynos.vp8.dec, Format(1, null, null, video/x-vnd.on2.vp8, null, -1, und, [1280, 720, -1.0], [-1, -1])`

You can find that bug report here. 

https://github.com/K1rakishou/Kuroba-Experimental/issues/454

> One thing that looks unusual is that the height of the video is an odd number of pixels (405), it might be that this causes problems here

I suspected that as well but I'm not sure anymore.

**Comment by Pentaphon** [comment] 2021-07-02 00:32
Here's a screenshot from a report by another user of the Exoplayer-based app I linked in the previous post.

That user's video is 1920x1080 yet they get `Decoder failed: OMX.qcom.video.decoder.vp8`

https://i.imgur.com/R1qodeh.png

**Comment by icbaker** [comment] 2021-07-02 17:02
> `Decoder init failed: OMX.Exynos.vp8.dec, Format(1, null, null, video/x-vnd.on2.vp8, null, -1, und, [1280, 720, -1.0], [-1, -1])`
> 
> You can find that bug report here.
> 
> [K1rakishou/Kuroba-Experimental#454](https://github.com/K1rakishou/Kuroba-Experimental/issues/454)

This is a different decoder, so it may well be a different problem.

There's not really enough info in the logcat snippet linked to pinpoint what's going wrong. A full `adb bugreport` might provide more info. Without that or the being able to reproduce the problem there's very little we can do to help.

However this log line looks suspicious:
> ```
>D/(21:38:54.241) KurobaEx | ExoPlayerWrapper: getOrCreateExoPlayer() creating a new player, total players count: 4
> ```

It seems like there are multiple players instantiated. Is it possible the device has run out of VP8 decoders? This is a risk when using multiple players.

-----

Regarding the 'problem' this issue was originally about: The odd height video failing despite saying `format_supported=YES`, I filed https://github.com/google/ExoPlayer/issues/9142 to change this to say `format_supported=NO_EXCEEDS_CAPABILITIES`. Given that playback fails in both cases, it doesn't seem like very high priority.

**Comment by K1rakishou** [comment] 2021-07-03 07:14
>It seems like there are multiple players instantiated. Is it possible the device has run out of VP8 decoders? This is a risk when using multiple players.

Is this actually a thing that can happen? The exoplayer in this particular case is used inside a ViewPager with 3-4 pages always being in memory. To avoid constantly creating and releasing players I'm using a pool of players (because I found out that on some devices calling release() may block the app for quite some time). So is using multiple players not recommended?

**Comment by icbaker** [comment] 2021-07-05 11:28
If the decoder is in hardware then there's a limited number of decoders on the device (the exact number varies per codec & per device), so if you try and initialize more than that it will fail.

There's more details about safely instantiating multiple players:
* https://github.com/google/ExoPlayer/issues/1286#issuecomment-200854838
* https://github.com/google/ExoPlayer/issues/273 (linked from comment above)

**Comment by icbaker** [comment] 2021-07-22 16:10
Closing due to inactivity.

**Comment by Pentaphon** [comment] 2021-08-25 20:09
> The codec name suggests it's coming from AOSP - I will raise this issue with the team that maintains those.

Have you done this?  A lot of people are coming to the Exoplayer issues page and blaming Exoplayer, which should be reason enough to raise the issue with them ASAP, I think?

**Comment by icbaker** [comment] 2021-08-26 10:17
> > The codec name suggests it's coming from AOSP - I will raise this issue with the team that maintains those.
> 
> Have you done this? A lot of people are coming to the Exoplayer issues page and blaming Exoplayer, which should be reason enough to raise the issue with them ASAP, I think?

This is tracked by [internal b/197831521]. I'll leave this open while I wait for a response.

**Comment by icbaker** [comment] 2021-09-01 11:46
You could try using our VP9 extension to play these files. It won't work out of the box, as it's configured to only support VP9, but the underlying VPX library is capable of decoding VP8. I haven't tried this, and it may not work, but if you'd like to give it a go then I suggest you try roughly the following:
1. Modify `generate_libvpx_android_configs.sh` to remove `--disable-vp8` from this line: https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/extensions/vp9/src/main/jni/generate_libvpx_android_configs.sh#L30
2. Follow the instructions to build the extension: https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9#readme
3. Modify `LibvpxVideoRenderer.java` to advertise support for the VP8 MIME type as well as VP9: https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/extensions/vp9/src/main/java/com/google/android/exoplayer2/ext/vp9/LibvpxVideoRenderer.java#L129
4. Configure the extension to be preferred over `MediaCodec`: https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9#using-the-extension

**Comment by Pentaphon** [comment] 2021-09-01 11:54
> You could try using our VP9 extension to play these files. It won't work out of the box, as it's configured to only support VP9, but the underlying VPX library is capable of decoding VP8. I haven't tried this, and it may not work, but if you'd like to give it a go

I've notified the developer of an app whose users have been seeing this issue very often. Perhaps your suggestion will bear fruit on his end if he decides to give it a go.

**Comment by icbaker** [comment] 2021-10-28 11:51
The team have responded regarding [internal b/197831521]. There's no immediate plan to change `c2.android.vp8.decoder` to support odd-dimensioned videos, but they may look at this in future. Of course any future change would only affect devices that pick up whatever OS update it ends up in.

They pointed out that Android doesn't generally promise to support odd-dimensioned videos in any format. The CDD only requires a device to support specific resolutions of VP8 (all of which are even): https://source.android.com/compatibility/12/android-12-cdd#536_vp8

Some devices obviously do support odd-dimensioned videos, but if you want your content to work flawlessly across all devices I would recommend you stick media encodings that match the requirements enforced by the CDD and the details on this page: https://developer.android.com/guide/topics/media/media-formats

I'm going to close this because there's no further action possible from the ExoPlayer team here.

**Closed as completed by icbaker** 2021-10-28 11:51 UTC
Labels: question
