### ISSUE TITLE
Allow applications to modify subtitle offsets during playback

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#854] opened 2015-10-09 09:21 UTC
Depending on where a subtitle was sourced from (e.g. if a user provided one), could result in it having incorrect timings with the content. Applications generally workaround this by having subtitle controls during playback that allows the user to tweak the timings of when they are displayed (e.g. +/- N).

At the moment, there is no easy way to apply (and modify) subtitle offsets. The `SubtitleParserHelper` does apply a `subtitleOffsetUs` but this is an offset taken from the `MediaFormat` and not modifiable.

**Comment by IanDBird** [comment] 2015-10-09 13:18
BTW, I should have said that i'm more than happy to make the relevant changes myself and submit a pull request. That said, it would be useful if you had any thoughts/opinions on how you'd like to see it implemented to make it easier to be accepted later to the library.

**Comment by ojw28** [comment] 2015-10-12 13:40
Doing this for chunked subtitles is problematic, because deciding when to load chunks is based on their start times. That said, I assume this request is exclusively about non-chunked subtitles. It doesn't really make a huge amount of sense to consider a chunked case where the timestamps are incorrect, but it does make sense for the sideloaded non-chunked case.

Would it be enough to simply pass a sampleTimeUs parameter into SingleSampleSource, which is probably where you'd be loading subtitles from for this case. Currently this class hardcodes the single sample timestamp as 0. Setting to non-zero should have the desired effect of offsetting all of the timestamps contained within the subtitle.

**Comment by IanDBird** [comment] 2015-10-12 13:51
I agree, it really only makes sense for the non-chunked case.

I think that the problem with your suggestion is that ideally you'd be able to continue playback but also allow the user to change/tweak the settings until they are happy. Generally the scenario in which the user requires this is:
 - The user plays a video, for which they've defined the sidecar subtitle to use
 - The user notices that the timing is off
 - During playback, the user opens the subtitle options within the player
 - The user manually changes the subtitle offset (+/-)
 - The user assesses whether they are now happy, if not, repeat

Correct me if i'm wrong, but your suggestion would require us to recreate the SampleSource upon every user modification and therefore interrupt playback? If so, that would make user adjustments like the one i've described pretty difficult for users.

**Comment by ojw28** [comment] 2015-10-12 14:02
We could let `SingleSampleChunkSource` implement `ExoPlayerComponent`, and allow passing of a message to change the offset without having to recreate the `SampleSource`. Changing the offset would look like:

```
int captionTrackIndex = player.getSelectedTrack(captionRendererIndex);
player.setSelectedTrack(captionRendererIndex, TRACK_DISABLED);
player.sendMessage(singleSampleSource, MSG_SET_SAMPLE_TIME, offset);
player.setSelectedTrack(captionRendererIndex, captionTrackIndex);
```

Where disabling and re-enabling are necessary to ensure that the sample gets reloaded from the source. 

I know it's a bit convoluted, but making changes anywhere near the actual text renderer means that they'd be on the code path for the chunked case as well, and so we'd end up having a setting there that only works for a subset of use cases. In practice, I think the approach above would work well for your needs. Thoughts?

**Comment by IanDBird** [comment] 2015-10-12 14:09
This sounds good although, although for my own use case, we would probably require it on the `ExtractorSampleSource` as well. The reason for this is that:
 - Some users might find external SRTs which they remux into an MP4 or MKV (I know it sounds crazy, but people do)
 - For unsupported subtitle formats (e.g. ASS), our software will convert it on the fly to a MKV container that "just" contains a single subtitle stream, in SRT.

**Comment by IanDBird** [comment] 2016-01-07 14:53
@ojw28 - I was looking into this issue again, with the hope that I could submit a PR. I just wanted to check that you were still happy with your suggested solution, and for me to make the relevant changes to both `SingleSampleSource` (i'm assuming non-chunked) as well as the `ExtractorSampleSource`.

I'm assuming that the reason it would be preferable to do it in the `SampleSource`s over the actual renderer is that the offset could be applied differently to each unique source?

The other thing I don't yet fully understand is how modifying the `SampleHolder`s `timeUs` by the offset (that's what I interpreted your suggestion to mean) will affect the timing of the subtitle. The subtitle parser will use the sample source to parse the text. The time codes are extracted by the original subtitle. How/where do the source's time affect what is parsed? (sorry if this is a dumb question)

**Comment by ojw28** [comment] 2016-01-08 16:49
I don't have concerns around the `SingleSampleSource` case. I'm not sure how easy it is to implement shifting "properly" in `ExtractorSampleSource` though, or how compatible any such change would be with future plans around having `ExtractorSampleSource` use `LoadControl`. It doesn't sound like a particularly great path to be going down to me, although I haven't given it much thought.

In general, it's not our priority to play whatever random-broken-stuff an application throws at us.

**Comment by Proxwian** [comment] 2019-09-03 18:12
We really need that feature in exoplayer :c

**Comment by warren-bank** [comment] 2020-03-15 17:05
fwiw, I recently took a look throught the [r2.11.3](https://github.com/google/ExoPlayer/tree/r2.11.3) code for any hook that I could use to implement this feature.. and found a fairly simple solution that works well (under most reasonable conditions).

the new classes are [here](https://github.com/warren-bank/Android-ExoPlayer-AirPlay-Receiver/tree/v02/android-studio-project/ExoPlayer-AirPlay-Receiver/src/main/java/com/github/warren_bank/exoplayer_airplay_receiver/exoplayer2/customizations).. and [this code](https://github.com/warren-bank/Android-ExoPlayer-AirPlay-Receiver/blob/v02/android-studio-project/ExoPlayer-AirPlay-Receiver/src/main/java/com/github/warren_bank/exoplayer_airplay_receiver/exoplayer2/PlayerManager.java#L95-L96) shows how they are used when constructing a new instance of `SimpleExoPlayer`.

PS: the class [`NonFinalTextRenderer`](https://github.com/warren-bank/Android-ExoPlayer-AirPlay-Receiver/blob/v02/android-studio-project/ExoPlayer-AirPlay-Receiver/src/main/java/com/github/warren_bank/exoplayer_airplay_receiver/exoplayer2/customizations/NonFinalTextRenderer.java) is only needed because [`TextRenderer`](https://github.com/google/ExoPlayer/blob/r2.11.3/library/core/src/main/java/com/google/android/exoplayer2/text/TextRenderer.java#L46) is marked `final`; it's a verbatim copy that isn't marked `final`. A non-final version of this class is needed because [`MyTextRenderer`](https://github.com/warren-bank/Android-ExoPlayer-AirPlay-Receiver/blob/v02/android-studio-project/ExoPlayer-AirPlay-Receiver/src/main/java/com/github/warren_bank/exoplayer_airplay_receiver/exoplayer2/customizations/MyTextRenderer.java#L9) must extend it.

**Comment by icbaker** [comment] 2020-03-18 16:55
@warren-bank That approach (of modifying the time inside the Renderer) works in most of the common cases that you'd want this feature (where the subtitles are likely coming from a standalone SRT file), but it doesn't work in a completely general case with general offsets.

The main problems:

* If you offset backwards a long way, there's no way for the Renderer to 'rewind' its data - so you'd either have to handle that in some manual way or just show no subtitles until you 'caught up'.
* If the subtitles are being streamed from a server, you also can't offset too far into the future, because the renderer has no way to request the media source to 'read ahead'.

As @ojw28 mentions above in https://github.com/google/ExoPlayer/issues/854#issuecomment-147407768 - it's problematic to put logic into the Renderer that only works in a limited set of cases.

So for these reasons we wouldn't accept a PR for the approach of modifying the timestamp inside the text renderer (you're obviously completely welcome to maintain the patch yourself, and share it with others that find it a good solution for their problem).

If you'd like to send a PR to fix this, and you're sideloading subtitle files using a `SingleSampleMediaSource`, I think the best approach would be to implement @ojw28's  suggestion from https://github.com/google/ExoPlayer/issues/854#issuecomment-147407768. Note that `ExoPlayerComponent` has since been renamed to `PlayerMessage.Target`. If this is an approach you (or anyone else) would like to take I'd be happy to answer any questions or help get you started.

**Comment by warren-bank** [comment] 2020-03-18 17:22
@icbaker Yep, I totally get that it isn't a perfect solution.. because for streamed captions, it wouldn't trigger any additional downloading for data that doesn't already exist in the buffer. That having been said, I'm very content with this methodology as a temporary solution.. at least until something 100% robust is included in the core library. I've only tested it lazily.. not exhaustively, but it's worked very well for every single use-case that I've tried so far.. even cases when I would expect that it wouldn't. So.. idk? Afaic, it's good enough for me. Figured I'd share my not-quite-perfect implementation.. because it turned out to be super easy to do.

**Comment by warren-bank** [comment] 2020-03-18 17:45
Dumb follow-up question..

Since text captions take up next-to-no storage.. consisting of a sequential set of tiny text files.. which combined amount to approx 100kB total per track per video; what do you think of a strategy to force the downloading of all chunks for every text track and store the entire thing in a separate buffer?

At a high level, it should behave exactly the same as though the text tracks had been specified as external files and sideloaded with the video stream.

If that were possible, then a text renderer _could_ freely seek within this separate buffer, and it would work well for any VOD video stream with one or more text tracks.

Thoughts?

**Comment by icbaker** [comment] 2020-03-19 17:04
A movie with a lot of dialogue can end up with quite large subtitle files, especially if they 'animate' the subtitles by making individual characters appear in subsequent cues.

Also some subtitles are image-based, and so obviously much larger.

It's another awkward "doesn't really work in the general case" I'm afraid - because we wouldn't want the default library behaviour to be something that could surprisingly use up a lot of bandwidth.

**Comment by warren-bank** [comment] 2020-03-19 18:50
Point well taken..

I appreciate your well-informed feedback; I don't know the ExoPlayer internals very well.. so anything I propose is to be taken at a high level.

So far as negatively impacting default behavior, I was actually thinking of this kind of behavior as being disabled by default.. and optionally enabled through (let say..) the [`PlaybackParameters`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/PlaybackParameters.html). Also.. since most text tracks are never used (either off altogether, or set to the user's native language).. it seems like the proposed downloading could be handled lazily.. only triggered when a new (not-as-yet-buffered) text track is made active.

Just food for thought.

**Comment by vrayv** [comment] 2020-12-31 15:25
Links are down for this example. Can you repost the changed classes and the example?

**Comment by warren-bank** [comment] 2020-12-31 18:41
Hi @vrayv . Links are now fixed. Sorry for that; project directories must've been reorganized at some point.

**Comment by icbaker** [comment] 2024-12-16 10:18
Closing this as a duplicate of https://github.com/androidx/media/issues/1976 on the media3 issue tracker.

**Closed by icbaker** 2024-12-16 10:18 UTC
Labels: enhancement, low priority
