### ISSUE TITLE
SimpleExoPlayerView grainy/distorted when setting player

### ISSUE THREAD

**Issue by sheaam30** [google/ExoPlayer#2305] opened 2017-01-08 15:22 UTC
I'm attempting to seamlessly switch video from 1 SimpleExoPlayerView to another.

In the first I am playing an HLS video:
```
BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
LoadControl loadControl = new DefaultLoadControl();
exoPlayer = ExoPlayerFactory.newSimpleInstance(textureVideoView.getContext(), trackSelector, loadControl);

Handler mainHandler = new Handler();
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(App.getApp(),                Util.getUserAgent(App.getApp(), "Agent"));
MediaSource hlsSource = new HlsMediaSource(sourceUri, dataSourceFactory, mainHandler, null);
return new LoopingMediaSource(hlsSource);

exoPlayer.prepare(new LoopingMediaSource(hlsSource));
exoPlayer.setPlayWhenReady(true);
```
I'm trying to keep the video in it's current state and swap the view that the player is using by calling `simpleExoPlayerView.setPlayer(exoPlayer)`. The video switches to play in the second view but it shows up as black/grainy initially and after a few seconds clears up.

- Using ExoPlayer version 2.1
- Seeing this on Pixel XL 7.1.1

![grainy](https://cloud.githubusercontent.com/assets/6750107/21750823/56b082e2-d58a-11e6-9238-d0e5be549e3d.png)

**Comment by ojw28** [comment] 2017-01-08 21:34
This is a duplicate of https://github.com/google/ExoPlayer/issues/2093.

**Closed as completed by ojw28** 2017-01-08 21:34 UTC
Labels: duplicate
