### ISSUE TITLE
 Loading an external exolist.json file not work with emulator Google TV SDK 31 but it works with Android TV SDK 28

### ISSUE THREAD

**Issue by NimaTajfar** [google/ExoPlayer#9441] opened 2021-09-17 03:01 UTC
Hi,
I use demo app within Exoplayer version 2.15.0 (latest release).  Loading an external exolist.json file with deep links is not work with Google TV SDK 31 (at least with Emulator and but when i do same process and switch to Android TV SDK 28 it works please note local assets folder works in both versions (even Google TV SDK 31) . if i need to do make any other changes in Android.Manifest file in order to support Google TV SDK 31 loading an external please let me know ( using adb please let me know) 

Step of produce:
1. very simple run the demo on Google TV SDK 31 emulator
2. adb shell am start -a android.intent.action.VIEW \
    -d your.domain/exolist.json

Result : it DOESNT load and there is a toast (message) ""you don't have an app that can do this"

1. run the demo on Android TV SDK 28 emulator
2. adb shell am start -a android.intent.action.VIEW \
    -d your.domain/exolist.json
Result : it loads

Thanks

**Comment by ojw28** [comment] 2021-09-17 09:30
Duplicate of https://github.com/google/ExoPlayer/issues/9437. Please don't file new issues to continue an existing discussion. Thanks.

**Closed as completed by ojw28** 2021-09-17 09:30 UTC
Labels: question

**Comment by NimaTajfar** [comment] 2021-09-17 15:29
@ojw28  This is not duplicate issue #9437. I achieve to run external server now with Android TV SDK 28 , i am reporting there is a problem with EXoplayer and Google TV SDK 31 NOT work with external server and emulator at least,

**Comment by ojw28** [comment] 2021-09-17 15:34
It's so closely related that it's basically part of the same discussion. If you create a new issue then it may be routed to a completely different person, which is not efficient if the new issue is about loading an external exolist.json file, and you're already talking to someone about loading an external exolist.json file.
