### ISSUE TITLE
Roboelectric 4.5-SNAPSHOT does not exist (anymore?)

### ISSUE THREAD

**Issue by MartB** [google/ExoPlayer#8332] opened 2020-12-08 17:59 UTC
https://github.com/google/ExoPlayer/blob/2980354510000406b71250368e54e4ab7d1cda1d/constants.gradle#L27

Should be 4.5-alpha-3 im not sure what happened to 4.5-SNAPSHOT but this breaks the build at the moment.

**Comment by icbaker** [comment] 2020-12-08 18:29
`4.5-SNAPSHOT` is still the documented way to depend on bleeding-edge Robolectric:
https://github.com/robolectric/robolectric#using-snapshots 

It still seems to be hosted here:
https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/4.5-SNAPSHOT/

It seems to still resolve for me - I tried restarting Android Studio and clearing caches, and everything still builds.

Can you provide more info on the exact error details you see, and how you reproduced?

There are other issues (#7932) reported with resolving Robolectric snapshots, but we've never been able to reproduce reliably so it would be helpful if you could provide as much info as possible.

FWIW we (ExoPlayer team) build the project with gradle every day on the tip of dev-v2 and haven't seen any issues.

**Comment by MartB** [comment] 2020-12-08 18:36
I did not add the sonatype repo into my app build.gradle file, is this required?

I get `Failed to resolve: org.robolectric:robolectric:4.5-SNAPSHOT` while switching the build variant.
This is the error i get while building after switching the build variant to `release`.

### Additional details
Android studio version is: 4.1.1
Gradle (wrapper) is: 6.6.1

**Build log**
```
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':exoplayer-library-core:debugUnitTestRuntimeClasspath'.
   > Could not find org.robolectric:robolectric:4.5-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/robolectric/robolectric/4.5-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/org/robolectric/robolectric/4.5-SNAPSHOT/robolectric-4.5-SNAPSHOT.pom
       - https://dl.google.com/dl/android/maven2/org/robolectric/robolectric/4.5-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/org/robolectric/robolectric/4.5-SNAPSHOT/robolectric-4.5-SNAPSHOT.pom
     Required by:
         project :exoplayer-library-core
         project :exoplayer-library-core > project :exoplayer-robolectricutils

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by icbaker** [comment] 2020-12-08 18:46
> I did not add the sonatype repo into my app build.gradle file, is this required?

I don't know actually - is it easy to try that and see if it resolves the problem?

I assume you're depending on `dev-v2` because `release-v2` currently depends on Robolectric 4.4 (non-snapshot):
https://github.com/google/ExoPlayer/blob/107fed9b2afc1e1edce95eee4a1fbc952377efd2/constants.gradle#L27

And so I'm also assuming you're depending on ExoPlayer-as-source. 

Can you try building the demo app and see if it can resolve the Robolectric dep? You can open it in Android Studio: https://exoplayer.dev/demo-application.html

How does your app pull in your local version of ExoPlayer via Gradle? It might be helpful to share as much of your app's gradle config as you can (if you can't post it publicly you can send it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this).

**Comment by MartB** [comment] 2020-12-08 18:54
Your assumptions are correct thats why i linked to the dev-2 branch commit.

For integrating exoplayer locally i used https://github.com/google/ExoPlayer/blob/dev-v2/README.md#locally

**Project build.gradle**
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
    }
}

allprojects {
    repositories {
        jcenter()
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Stripped down app build.gradle**
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    defaultConfig {
        applicationId 'de.martb.exotest'
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        dataBinding = true
    }
    productFlavors {
    }

    lintOptions {
        abortOnError false
    }

    ndkVersion '21.3.6528147'
    buildToolsVersion '30.0.2'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation project(':exoplayer-library-core')
    implementation project(path: ':exoplayer-extension-ffmpeg')
    implementation project(path: ':exoplayer-extension-okhttp')
}

repositories {
    mavenCentral()
}
```

**settings.gradle**
```
include ':app'

gradle.ext.exoplayerRoot = 'ExoPlayer'
gradle.ext.exoplayerModulePrefix = 'exoplayer-'
apply from: new File(gradle.ext.exoplayerRoot, 'core_settings.gradle')
```

### Demo compile test
Worked without any problems from within the exoplayer source repo.
Slightly puzzled here, why would it give me troubles when it works on the demo.


### Android Studio 4.2 beta 1
Same behavior luckily so not related to android studio version.

P.S: Android Studio 4.2 beta 1 requires an adjustment for `gradle.ext.exoplayerRoot` see https://github.com/google/ExoPlayer/issues/7554#issuecomment-650557898 that helped me.

### Adding the repository manually **FIXED**
After adding the repository manually to my **project** `build.gradle` everything worked fine.
It was not sufficient to add it to the app level `build.gradle` file.

Which leads us to an important thing, the exoplayer project contains the line https://github.com/google/ExoPlayer/blob/2980354510000406b71250368e54e4ab7d1cda1d/build.gradle#L29 but it does not seem to be respected when building from another app in-source.

The documentation for https://github.com/google/ExoPlayer/blob/dev-v2/README.md#locally should probably be adjusted to contain the line, as im not sure if its possible to add the repository to each library project that requires roboelectric.

**Edit: added demo test results**
**Edit 2: after switching to AS 4.2 beta 1**
**Edit 3: after manually adding it to the project build.gradle**

**Comment by MartB** [comment] 2020-12-08 19:32
@icbaker edit mania from above is done. (I promise lol)
See my paragraph about manually adding the repository for my thoughts on the way to fix this "issue".

**Comment by icbaker** [comment] 2020-12-14 10:32
Thanks for all the detailed investigation and findings! 

I was able to reproduce by depending on a local ExoPlayer from an external gradle project (the demo case is different because it's in the same overall project).

I've made a change to our gradle config that I think should avoid apps needing to edit their own gradle configs. It worked in my local testing - would appreciate if you could also see if it works for you.

**Closed as completed by icbaker** 2020-12-14 10:32 UTC
Labels: question
