### ISSUE TITLE
怎么设置播放没有音频的视频流

### ISSUE THREAD

**Issue by yanshanshu** [google/ExoPlayer#7686] opened 2020-07-28 07:54 UTC
我的视频流没有音频，怎么禁止音频，只播放画面。

**Comment by ojw28** [comment] 2020-07-28 08:57
I think this is a duplicate of https://github.com/google/ExoPlayer/issues/7675. Please don't file duplicate issues. Thanks!

**Closed as completed by ojw28** 2020-07-28 08:57 UTC
Labels: question
