### ISSUE TITLE
Galaxy Tab S2 - Drm protetected video does not work properly after seeking

### ISSUE THREAD

**Issue by gimbutas** [google/ExoPlayer#3063] opened 2017-07-14 06:54 UTC
### Issue description
If long protected video (longer than 1 hour) has video tracks with resolution higher than device resolution (for example 4K), then after starting playback and seeking, the video playback does not resume correctly. Video seems to continue playing (audio keeps playing and elapsed time counter at the bottom left corner of the screen is also updated properly) but screen itself is black. From debug information (information box at the top left corner of the screen) I can see that video track is updated to a resolution that is higher than device resolution.

### Reproduction steps
Issue can be reproduced using the ExoPlayer demo app (ExoPlayer version 2.4.3) by following these steps:
1. Starting video playback (Video requirements are described in "Issue description" chapter. Video itself is provided under "Link to test content" chapter).
2. Skip video ahead a few minutes. Wait for playback to resume.
3. In case video playback continues normally then repeat step 2 until issue is encountered. Issue is not hard to reproduce so it should usually take only a few seeks to encounter it.

### Link to test content
Link to test content manifest:
https://media.axprod.net/DASH/TwoHourVideo4K/Encrypted/Manifest.mpd

In order to play that video in ExoPlayer demo app, assets/media.exolist.json file should be edited by adding following sample to it:
{
        "name": "TwoHourVideo4K encrypted",
        "uri": "https://media.axprod.net/DASH/TwoHourVideo4K/Encrypted/Manifest.mpd",
        "extension": "mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://drm-widevine-licensing.axtest.net/AcquireLicense",
        "drm_key_request_properties": {
          "X-AxDRM-Message": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiNjllNTQwODgtZTllMC00NTMwLThjMWEtMWViNmRjZDBkMTRlIiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImtleXMiOlt7ImlkIjoiZmQ1NGZiYWUtMTU4NC00MWY2LWIwZmItNTVmOTRkYjg3NTlkIn1dfX0.h-V5_8r0Mvx_Pj95uUDkghQB6LAaUTkngNJUwBm09zQ"
        }
}

### Version of ExoPlayer being used
ExoPlayer version 2.4.3.

### Device(s) and version(s) of Android being used
Device name: Samsung Galaxy Tab S2
Model number: SM-T815
Android version: 7.0 (API level 24)

Issue reproduces quite easily (sometimes even from first seeking).

### A full bug report captured from the device
Full bug report captured from the device is sent via email.

**Comment by ojw28** [comment] 2017-07-14 13:17
A few follow-up questions:

- Are you only seeing this issue on Galaxy Tab S2? Does it reproduce on e.g. Pixel, or one of the recent Galaxy S devices? I cannot reproduce on a Galaxy S8.
- Is the video being long relevant? I somewhat doubt it. Does the issue reproduce with the shorter Widevine protected content in the demo app?

Thanks!

**Comment by gimbutas** [comment] 2017-07-14 14:36
Thank you for the reply.

1. Yes, I am seeing the issue only on Galaxy Tab S2. I tried it also on Galaxy S5 (Android version 6.0.1) and Nexus 9 (Android version 7.0) and just noticed that selection of higher video tracks are disabled (2560x1440 and 3840x2160) on these devices. On Galaxy Tab S2 these video tracks are available and I see same issue when selecting one of them manually.

2. I must have tried reproducing the issue with unprotected short video before because I just managed to reproduce the issue with shorter Widevine protected video:
{
        "name": "DASH GPMFv6 H264 Encrypted",
        "uri": "http://media.axprod.net/DASH/GPMFv6/H264/Encrypted/Manifest.mpd",
        "extension": "mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://drm-widevine-licensing.axtest.net/AcquireLicense",
        "drm_key_request_properties": {
          "X-AxDRM-Message": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiNjllNTQwODgtZTllMC00NTMwLThjMWEtMWViNmRjZDBkMTRlIiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImtleXMiOlt7ImlkIjoiN2YzYzE0NTUtOWE0ZS00ODc4LTgyZDEtYWQ3YjYyYTYxMDZjIn1dfX0.Qgt0I2HzmntyFQ9tk3p2u2s1PruyGb12RsB3g6EBBLQ"
        }
}

I did not find any default demo app videos to match requirements (protected video that would have several video tracks, one of which would need to be higher than device resolution). Therefore I could not reproduce the issue with default demo videos.

**Comment by ojw28** [comment] 2017-07-14 15:24
Would it be possible for you to try forcing `codecNeedsFlushWorkaround` to return `true` on this device, here:

https://github.com/google/ExoPlayer/blob/r2.4.3/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L1069

If the issue goes away, we probably just need to enable that workaround on this device. If you are able to try this, please do so by getting the 2.4.3 release (`git checkout r2.4.3`) and adding the change to that, rather than `dev-v2`, as there's a separate known issue on `dev-v2` right now that probably means your test stream doesn't play!

**Comment by gimbutas** [comment] 2017-07-17 07:23
I tried the solution you suggested (forcing `codecNeedsFlushWorkaround` to return `true`) but unfortunately it did not work.

**Comment by ojw28** [comment] 2019-04-05 22:31
Closing as part of a scrub of old device specific issues.

**Closed as completed by ojw28** 2019-04-05 22:31 UTC
Labels: bug: device specific
