### ISSUE TITLE
Custom HTTP headers for the stream in a MediaItem

### ISSUE THREAD

**Issue by cdongieux** [google/ExoPlayer#10163] opened 2022-04-07 15:30 UTC
Is there any way to set custom HTTP headers for the stream in a `MediaItem`?

When building a `MediaItem` we can set a URI, we can also set headers for the license request, but I don't see any method on `MediaItem.Builder` to set custom HTTP headers for the manifest/stream itself.

My usecase is to play a media with this kind of generic URL https://foobar.com/npvr.mpd, and I have to perform the request with a HTTP header `Npvr-Token: <NPVR_TOKEN>` to be able to receive the right MPD.

I see a workaround where I can set headers like this:
```
    data class Media(
        val streamUrl: String,
        val streamRequestHeaders: Map<String, String> = emptyMap()
    )

    private val httpDataSourceFactory = OkHttpDataSource.Factory(okHttpClient)
    ...
    private fun buildMediaItem(
        media: Media
    ): MediaItem {
        httpDataSourceFactory.setDefaultRequestProperties(media.streamRequestHeaders)
        return MediaItem.fromUri(media.streamUrl)
            ...
            .build()
    }
```
But this is not optimal.

**Comment by ojw28** [comment] 2022-04-19 22:02
Closing this as a duplicate of #6166

**Closed as completed by ojw28** 2022-04-19 22:02 UTC
Labels: duplicate
