### ISSUE TITLE
Mid-roll ad playback fails with Video codec error

### ISSUE THREAD

**Issue by kishan-js** [google/ExoPlayer#9923] opened 2022-02-02 10:02 UTC
We are trying to play mid-roll ads with ExoPlayer ima extension, but it's failing with Video codec error. Mostly it's happening for DRM enabled content. In this case content is playing properly, but when mid-roll ads coming it's failing. pre-roll ads are playing properly.
Shared bug report via email.

- ExoPlayer version: 2.15.1
- IMA SDK version: 3.24.0
- Android version: 11
- Android device: Oppo Reno 5 Pro 5G

**Comment by icbaker** [comment] 2022-02-02 10:13
Thanks for the bug report. From these log lines this looks like a duplicate of #8696:
```
02-02 09:51:19.026 10337 16257 20440 E SurfaceUtils: Failed to connect to surface 0xb400007410656010, err -22
02-02 09:51:19.026 10337 16257 20440 E MediaCodec: nativeWindowConnect returned an error: Invalid argument (-22)
02-02 09:51:19.026 10337 16257 20093 E MediaCodec: configure failed with err 0xffffffea, resetting...
```

**Closed as completed by icbaker** 2022-02-02 10:13 UTC
Labels: duplicate
