### ISSUE TITLE
v2.1.1 Switch media source and retain position

### ISSUE THREAD

**Issue by veritas1** [google/ExoPlayer#2248] opened 2016-12-22 10:57 UTC
Our app allows users to switch from video to audio only media source (of same content).

We had been using `ExoPlayer.prepare(MediaSource mediaSource, boolean resetPosition)` but that seems to have been dropped in favour of `ExoPlayer.prepare(MediaSource mediaSource, boolean resetPosition, boolean resetState)` in v2.1.1.

Now the resetPosition param is being ignored, as media always starts from the beginning.

Tested on Google Pixel XL (7.1.1) and Moto X 2nd Gen (6.0).

**Comment by ojw28** [comment] 2016-12-22 21:17
That parameter is working fine for me. Please provide detailed reproduction steps, if possible using the demo app. Thanks.

**Comment by ojw28** [comment] 2017-01-04 23:33
Closing due to lack of information.

**Closed as completed by ojw28** 2017-01-04 23:33 UTC
Labels: need more info
