### ISSUE TITLE
Provide more fine grade download failure reasons than REASON_UNKNOWN

### ISSUE THREAD

**Issue by rs146** [google/ExoPlayer#7438] opened 2020-05-28 12:40 UTC
### [REQUIRED] Searched documentation and issues
We have had a look at GitHub issues and StackOverflow but we have not been able to find any further information.

### [REQUIRED] Question
At the moment, when there is an error in a `Download`, ExoPlayer does not define the error in the `Download` object. It only uses a generic [FAILURE_REASON_UNKNOWN](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/offline/Download.html#FAILURE_REASON_UNKNOWN). _Is there a way in which we can have more fine-grained download failure states attached to the `Download` object?_ Some errors we could think of are: HTTP/Network error; Manifest issues; DRM failure.

### A full bug report captured from the device
No bug report.

### Link to test content
No link to test content for this.

**Comment by marcbaechinger** [comment] 2020-05-28 16:00
We have currently the intDef which restricts the failure reason to the unspecific FAILURE_REASON_UNKNOWN. I marked this as an improvement so we can consider adding more fine grade reasons here.

I can't say whether and when we have a chance to look into this yet.

**Comment by ojw28** [comment] 2020-06-02 21:50
Duplicate of https://github.com/google/ExoPlayer/issues/5914.

**Closed as completed by ojw28** 2020-06-02 21:50 UTC
Labels: duplicate, enhancement
