### ISSUE TITLE
can i use Ffmpeg as my video renderer ?

### ISSUE THREAD

**Issue by AhmedHumk** [google/ExoPlayer#10926] opened 2023-01-15 16:26 UTC
Hello, I am using ffmpeg as my audio renderer can videorenderer be supported as well ?

**Comment by AhmedHumk** [comment] 2023-01-15 18:25
Currently any mpeg-2 video doesnt render only audi is playing, that's why i search for a renderer that can play those type of formats i checked the ffmpeg extension it has only audio renderer not a video

**Comment by AhmedHumk** [comment] 2023-01-16 11:08
i guess that you can just use this
https://github.com/AhmedHumk/ffmpegVideoDecoder

**Comment by rohitjoins** [comment] 2023-01-17 12:14
Adding video support to our [ffmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) is tracked by #2159. Closing this as a duplicate of #2159.

**Closed as completed by rohitjoins** 2023-01-17 12:14 UTC
Labels: duplicate
