### ISSUE TITLE
Possible NPE in new ExoPlayer.isTunnelingEnabled method

### ISSUE THREAD

**Issue by TheBeastLT** [google/ExoPlayer#10997] opened 2023-02-17 15:53 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Any

### Reproducible in the demo app?

Yes

### Reproduction steps

https://github.com/google/ExoPlayer/blob/f72ca8338399c9e3c19e73fc0779f24baff14d35/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L1717

Here a NPE can happen when you have alternative renderers in the factory, ie. having a FfmpegRenderer. In this case, when it's not selected by any track `rendererConfigurations` array will have a null entry in it.

### Expected result

A null check should be added to avoid NPE.

### Actual result

A NPE is thrown when invoking this method with FfmpegRenderer present.

### Media

None

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by microkatz** [comment] 2023-02-20 11:28
Duplicate of https://github.com/google/ExoPlayer/issues/10977.

Fixed in https://github.com/google/ExoPlayer/commit/5e3cd7a3c3f2cd590d77ccd318c5ba4824f414b8

**Closed as completed by microkatz** 2023-02-20 11:28 UTC
Labels: bug, duplicate
