### ISSUE TITLE
4k Udp Streaming  is stuttering,

### ISSUE THREAD

**Issue by mouemen-haress** [google/ExoPlayer#8748] opened 2021-03-23 11:20 UTC
I use Exoplayer To catch udp streaming , in All video it is work well , but when i try with 4k stream   is stuttering,

**Comment by andrewlewis** [comment] 2021-03-23 12:31
There isn't enough information here for us to help you. It sounds a bit similar to #8091 so you might want to read through that issue to see if that helps. Otherwise I'd suggest doing some debugging on your side and reporting a specific issue if you can find one, or providing detailed instructions so we can reproduce the problem here.

**Comment by mouemen-haress** [comment] 2021-03-23 12:43
thank you for your answear , I am using vlc to broadcast UDP in the internal network  . And I am trying to play it in an android application using the exoplayer. All the videos work fine, but when I  try to play   4K video ,  in order for the video to start, then after a few  of seconds it stops and then returns this state over and over again .

**Comment by andrewlewis** [comment] 2021-04-01 16:24
#8770 looks the same. As noted on that issue too, we can't help much with such limited information. Please avoid filing duplicate issues in future.

**Comment by andrewlewis** [comment] 2021-04-01 16:24
Duplicate of #8770

**Closed as completed by andrewlewis** 2021-04-01 16:24 UTC
Labels: duplicate
