### ISSUE TITLE
change exoplayer speed for certain duration of video in Android

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#5218] opened 2018-12-08 07:03 UTC
o change exoplayer speed we use player.setPlaybackParameters

this changes speed , but how can we set speed only for certain duration

the code that I have used is

```
playerTimer.setCallback(new PlayerTimer.Callback() {
            @Override
            public void onTick(long timeMillis) {
                if (player != null) {
                    long position = player.getCurrentPosition();
                    long duration = player.getDuration();
                    speeder(position);

                }
            }
        });
```
and

```
public void speeder(long pos) {


        if (player.getCurrentWindowIndex() == 1) {
            if (pos >= 100000) &&
            pos <= 200000){
                PlaybackParameters playbackParameters = new PlaybackParameters(
                        2.0f, 1.0f);
                player.setPlaybackParameters(playbackParameters);
            }
                    else if (pos <= 100000) &&
            pos >= 200000)
            {
                PlaybackParameters playbackParameters1 = new PlaybackParameters(
                        1.0f, 1.0f);
                player.setPlaybackParameters(playbackParameters1);
            }
        }
    }
```
but the speed doesnot change when its between 100000 and 200000

**Comment by ojw28** [comment] 2018-12-09 18:52
Calling `setPlaybackParameters` is the right thing to be doing. If you call it when you want playback to change speed, then that should work. So I'm guessing your code just doesn't do that correctly. I don't know what `PlayerTimer` is. I don't think it's part of the ExoPlayer codebase. One thing I would note is that I suspect it repeatedly calls `setPlaybackParameters` on every tick (whatever a tick is). You should probably just call it once each time you want a change in speed.

Closing, since it seems the issue is with your application code, rather than there being any issue with the ExoPlayer library.

**Closed as completed by ojw28** 2018-12-09 18:52 UTC
Labels: question

**Comment by tonihei** [comment] 2018-12-10 09:40
You can also use something like this to let ExoPlayer handle the timing for you:
```
Handler handler = new Handler();
player.createMessage(
    (a,b,c) -> player.setPlaybackParameters(2.0f, 1.0f))
  .setPosition(1, 100000).setHandler(handler).send();
player.createMessage(
    (a,b,c) -> player.setPlaybackParameters(1.0f, 1.0f))
  .setPosition(1, 200000).setHandler(handler).send();
```
