### ISSUE TITLE
How are Bandwidth Estimates averaged?

### ISSUE THREAD

**Issue by stevemayhew** [google/ExoPlayer#7392] opened 2020-05-18 23:07 UTC
I have a question about the code in the SlidingWindow as well.  I see it was partially answered in this issue, https://github.com/google/ExoPlayer/issues/6805.

The weighting makes sense, but I don't see how the mean is calculated over the set of weighted samples?

This description implies such an mean calculation takes place (from the [Bandwidth Analysis](https://docs.google.com/document/d/1e3jVkZ6nxNWgCqTNibqV8uJcKo8d597XVl3nJkY7P8c/edit#) doc:
> Each transfer end results in a new measurement based on the time since the first transfer started or the last measurement, and the bytes transferred since. The final estimate is updated using a "sliding median" which keeps a list of recent measurements, and then takes the weighted[*] median of all these samples. In addition, we don't publish an actual estimate until we loaded at least a minimum number of bytes (512KB) and took at least a minimum total time to load (2000ms).

Perhaps I'm missing something, it looks like the code here in [SlidingPercentile.java](https://github.com/google/ExoPlayer/blob/0de9c007afcbc0fb6c753794afc902eb4aaa47b4/library/core/src/main/java/com/google/android/exoplayer2/util/SlidingPercentile.java#L123
)  indicates picks the first from the list (lowest bandwidth, list is sorted low to high) depending on the weighting you pick it might picker a higher value, but it is still only one value from the list of saved values.

Here's some results from actual playback (1/2 hour from a live playlist).  The raw data (input values to the algorithm in Mbps)

```
Sum       44713.5574593001
Number    2513
Mean      17.7928999042181
Median    13.409257
Mode      6.739077  
NModes    4
Min       0.13804652
Max       134.688
Range     134.54995348
Variance  159.687584345879
Std_Dev   12.636755293424
SEM       0.252080546272307
95% Conf  17.2988220335244 to 18.2869777749118
          (for a normal distribution - see skew)
Skew      1.07033347848766
          (skew is 0 for a symmetric dist)
Std_Skew  21.9048220214407
Kurtosis  2.34584296477789
          (K=3 for a normal dist)
```

The 10Mps stream plays perfectly with no stalls if level is fixed to highest.  It level shifts between the top two variants over 50 times though with ABR.

This works ok for VOD because the `DEFAULT_MAX_DURATION_FOR_QUALITY_DECREASE_MS` (25s)  is so much less then the buffer target (`DEFAULT_MIN_BUFFER_MS`, 50s) that the condition for the track change are seldom if ever met.

For live, with an implicit "max buffer size" of 18 seconds (with 6 second segments), you are always under the `DEFAULT_MAX_DURATION_FOR_QUALITY_DECREASE_MS`

**Comment by tonihei** [comment] 2020-05-19 07:56
> Perhaps I'm missing something, it looks like the code here in SlidingPercentile.java indicates picks the first from the list (lowest bandwidth, list is sorted low to high) depending on the weighting you pick it might picker a higher value, but it is still only one value from the list of saved values.

It picks the "weighted" median of the samples. "Weighted" means that the weights are taken into account when finding the element in the middle, but we don't "weight" the two elements either side of the middle to form an average. 

Example [value, weight]:  
  [1, 5]
  [2, 10]
  [3, 2]
  [4, 15]
The total weight is 32, so the midpoint is where the weight sum reaches 16.  Our algorithm then returns the first samples that exceeds this weight. In the example this would be 3.

If all your samples are close together, this doesn't really matter because the difference between choosing one sample over the other is likely to be small. However, if your measurements are noisier, then it's likely that the estimate is jumping around slightly. Please have a look at [this section](https://docs.google.com/document/d/1e3jVkZ6nxNWgCqTNibqV8uJcKo8d597XVl3nJkY7P8c/edit#heading=h.abgue47v2gpt) in the bandwidth analysis doc that addresses this problem. (And it has a nice graph showing what you describe).

 > The 10Mps stream plays perfectly with no stalls if level is fixed to highest. It level shifts between the top two variants over 50 times though with ABR. For live, with an implicit "max buffer size" of 18 seconds (with 6 second segments), you are always under the DEFAULT_MAX_DURATION_FOR_QUALITY_DECREASE_MS

That's probably working as intended, isn't it? If you forget about the bandwidth estimation inaccuracies and take the provided estimate for granted, then it makes sense for the ABR algorithm to switch down if the current network speed isn't sufficient and the buffer is relatively low.

Having said that, you can keep the higher quality for longer, but increase your risk of running into rebuffers, by reducing this value to something more suitable for live streams. Our default was chosen with VOD playback in mind and live ABR makes things considerably more difficult as we never have a long buffer by design. 

For your particular example, the best value depends on the desired offset to live head. If your desired offset is 12 seconds (2 segments), then everything close to 12 seconds indicates stable streaming with no reason to switch down. Only if the available buffer falls below let's say 9 seconds, you should consider switching down. So 9 seconds could be a good choice for `maxDurationForQualityIncrease`.

**Comment by stevemayhew** [comment] 2020-05-19 17:50
Thanks so much @tonihei, of course my mistake I read "median" and thought "average".   Thanks for the reminder how median is calculated, now it makes perfect sense.

So the `maxWeight` setting basically sets the number of samples included in the median calculation.  The median is statistically much better to use the average, if the data set includes lots of outliers.  Note, the depth of data set is limited by `MAX_RECYCLED_SAMPLES`, as this limits the sample size to 5 no matter what the `maxWeight` is set to (a bug?)

The data set above is from an set-top box connected via WiFi, the drops in throughput occur because errors on the WiFi trigger the CWND algorithm in Cubic, even though there is no congestion issues.  It is hard for the algorithm to smooth these out, as they are likely a small portion of the 40 or so RTT's that would make up an entire segment load and the algorithm only measures transfer at the segment level (I realize this is a problem with access to the socket level statistics from Android)

I talk about this in my comment here:  https://docs.google.com/document/d/1e3jVkZ6nxNWgCqTNibqV8uJcKo8d597XVl3nJkY7P8c/edit?disco=AAAADp-rSWI

We have a pretty large deployment now of STB's, multiple origin server vendors and would be happy to help benchmarking solutions or supplying data sets.  Let me know

**Comment by stevemayhew** [comment] 2020-05-19 17:51
PS,  where is the best place for me to continue this discussion?   Comments on the design doc?

**Comment by tonihei** [comment] 2020-05-20 07:42
> Note, the depth of data set is limited by MAX_RECYCLED_SAMPLES, as this limits the sample size to 5 no matter what the maxWeight is set to (a bug?)

The samples are saved in an unbounded list. The recycled samples array is only used to prevent recreation of the Sample object by reusing up to 5 of them. This is probably a premature optimization that makes the code more complicated than needed.

> We have a pretty large deployment now of STB's, multiple origin server vendors and would be happy to help benchmarking solutions or supplying data sets. Let me know

Sounds helpful, I'll get in touch.

> PS, where is the best place for me to continue this discussion? Comments on the design doc?

Yes, please. If it directly related to the things in there, comments are most helpful. If it's more like a separate issue not covered in the doc, feel free to open a new GH issue instead (similar to this one).

**Comment by stevemayhew** [comment] 2020-05-20 18:14
> The samples are saved in an unbounded list. The recycled samples array is only used to prevent recreation of the Sample object by reusing up to 5 of them. This is probably a premature optimization that makes the code more complicated than needed.

Ah, yes I see that now.   So the `maxWeight` bounds the size of the list (a very good thing, given our use case should be able to play live "tv" for multiple hour sessions)

**Comment by tonihei** [comment] 2020-07-06 09:25
Closing, because the question was answered.

**Closed as completed by tonihei** 2020-07-06 09:25 UTC
Labels: question
