### ISSUE TITLE
freeze frames on playing LIVE DASH ABR streams with the ExoPlayer

### ISSUE THREAD

**Issue by hezie100** [google/ExoPlayer#4558] opened 2018-07-23 15:22 UTC
I'd like to have more details on the ExoPlayer specifications, especially on LIVE (channels) DASH ABR streaming.
what's the supported video codec and audio codec ?
what's the required amount of Levels/ bit rates in manifest ?
what's the required chunk size for the segments ?
do I need to set any sliding window for the player to be able to seek in time or not ?
what's the setup required in order to gain the maximum video quality on LIVE DASH with the ExoPlayer and what could be the reason for frequent freeze frames while playing LIVE DASH stream ?
waiting your response
thank you,

Hezi.

**Comment by ojw28** [comment] 2018-07-23 15:33
If you have a DASH live stream that's freezing, the best thing you can do is to properly full out our issue template, providing the stream, so that we can take a look.

We do not have any hard requirements on most of the specific questions that you pose.

**Comment by hezie100** [comment] 2018-07-23 16:24
Hi
providing to you some downloaded chunk files of live stream and their related MPD manifest file will help to analyze, or do you need a LIVE URL to watch it on real time ?
thx

Hezi.

**Comment by ojw28** [comment] 2018-07-23 17:53
We need a way to reproduce the issue. So unless we can reproduce the issue with the files (seems unlikely), we'll need a live URL.

**Comment by hezie100** [comment] 2018-07-23 18:15
I need to pass to you a LINK to play LIVE DASH Stream but personally from one source IP to test.
the source IP of yours from which you'll test it will be opened on our Firewall and you'll get a one-time-URL
please provide to me your public source IP for which I need to enable HTTPS access to that link to test
Thx,

Hezi.

**Comment by ojw28** [comment] 2018-07-23 19:28
Please could you setup a non-restricted test stream. You can share a stream to `dev.exoplayer@gmail.com` if you don't want the URL to be visible here. If you're really concerned about protected your content beyond that, then it should be possible for you to feed your video pipeline is with a freely available video, such as [Big Buck Bunny](https://peach.blender.org/). We don't generally jump through hoops to help debugging content specific problems.

**Comment by hezie100** [comment] 2018-07-24 09:39
Hi
the stream itself is not restricted, only the access into it
so I can provide a clear stream that only yours source IP can access it - could you please provide to me your source IP and I'll provide to you the Link to the stream and token to put on the call ?
please update
thanks.

**Comment by ojw28** [comment] 2018-07-24 09:40
Providing specific IPs isn't practical for us, sorry.

**Comment by hezie100** [comment] 2018-07-24 09:59
ok
who owns please this email account ? dev.exoplayer@gmail.com
thanks.

**Comment by hezie100** [comment] 2018-07-24 10:14
hi
any answer ?
thanks.

**Comment by ojw28** [comment] 2018-07-24 14:00
Google owns it.

**Comment by hezie100** [comment] 2018-07-25 14:37
Hi
since we noticed some freeze frames, which parameters on ExoPlayer are related to the player buffer management ?
about the actual quality of video, the player has some video filters we can adjust ?
could you please share with a link to the video & audio set of parameters managed by the ExoPlayer ?
thx

Hezi.

**Comment by ojw28** [comment] 2018-07-25 15:03
Your problem is unlikely to be related to parameter configuration. It's more likely that your content doesn't correctly implement the DASH spec, for example.

We cannot help in an efficient way without a non-restricted test stream. The URL can be shared privately to `dev.exoplayer@gmail.com`, or publicly here. Unless we receive such a stream we'll have to close this, since there's nothing actionable for us to do. Thanks.

**Comment by hezie100** [comment] 2018-07-26 09:44
Hi,
I had just sent to your email: dev.exoplayer@gmail.com, a DASH LIVE test stream
please confirm that you had received that email and that LIVE stream is accessible for you.
main issues detected:
issue with lips sync - video and audio are not in sync
freeze frames during playout
quality of video is poor 

please update
thanks.

**Comment by hezie100** [comment] 2018-07-26 10:27
HI

any update ??
thanks.

**Comment by hezie100** [comment] 2018-07-26 10:52
the stream sent is accessible for you ?

**Comment by hezie100** [comment] 2018-07-26 13:09
Hello
could someone give me an update please on that ?

**Comment by ojw28** [comment] 2018-07-26 15:15
We do have other work to do alongside this issue. We'll update the issue when we take a look. Thanks.

**Comment by hezie100** [comment] 2018-07-26 15:50
hi, thanks
But issue I have noticed is that the ExoPlayer is getting the DASH manifest, start from the lower level of bit rate configured but stay on that level, meaning that it is not tuned into the higher levels of bit rates listed on the DASH manifest.
what could be the reason that player is not moving between different levels of bit rate (listed on DASH manifest) and always stays on the same lower level ?
thanks for your clarification.

**Comment by ojw28** [comment] 2018-07-26 17:24
I was able to access the test stream.

> issue with lips sync - video and audio are not in sync

It does appear to be a little out of sync. I'm pretty confident this is an issue with the content itself, not with ExoPlayer. You will probably have to debug this on the content side.

> But issue I have noticed is that the ExoPlayer is getting the DASH manifest, start from the lower level of bit rate configured but stay on that level, meaning that it is not tuned into the higher levels of bit rates listed on the DASH manifest.

I cannot reproduce this using our demo app. Playback starts in the lower quality and switches up to the higher quality after a short period of time.

Please try using the ExoPlayer demo app without modifications, other than adding your test stream. If this works then the issue is in your application code. Most likely you're not passing the same `BandwidthMeter` instance to the `DefaultTrackSelector`/`AdaptiveTrackSelection.Factory` and `DataSource.Factory`. As an aside, we're simplifying plumbing of the `BandwidthMeter` in an upcoming release, since this is a common source of error.

> freeze frames during playout

I am unable to reproduce this issue.

**Comment by hezie100** [comment] 2018-07-30 08:34
Hi,
after the suggested adjustments, we can see now that ExoPlayer on our app code is playing the ABR profiles as expected, moving from one level of bit rate into another one - so it's OK - Thanks !
**now we still have an issue with the "freeze frames" while playing the VOD asset and the LIVE Stream** over Mpeg DASH - could you please advise which parameter settings we might being adjust on Player code side in order to solve that issue ?
on server side, increasing the fragment length from 5 sec into 10 sec, does not solve that freeze frame issue.
please advise. thanks

**Comment by hezie100** [comment] 2018-07-30 10:06
Hi
do you have an update for me please on that remaining issue ?
thanks.

**Comment by hezie100** [comment] 2018-07-30 13:26
hi

any update please ??
thanks.

**Comment by hezie100** [comment] 2018-07-30 15:48
Hi
could you please update on that matter ?
it's really urgent for us
thanks.

**Comment by hezie100** [comment] 2018-07-31 09:17
hi
**we're still facing freeze frames while playing video, DASH vod and DASH Live**
it seems like the flow motions are corrupted
could you please advise what could be the reason for that and how should we fix that ?
thanks.

**Comment by ojw28** [comment] 2018-07-31 09:20
Please note that repeatedly spamming this issue does not lead to us looking at it more quickly. We will look at it when we have time to do so. Thanks.

**Comment by hezie100** [comment] 2018-07-31 09:29
OK
I understand - thank you.
if you need further tests on our DASH LIVE Stream test, please tell me and I'll activate it immediately.
thanks.

**Comment by ojw28** [comment] 2018-07-31 14:53
As per my comment [all the way up at the top of this issue](https://github.com/google/ExoPlayer/issues/4558#issuecomment-407100309), we need you to fully complete the issue template.

I was unable to reproduce the freezing issue locally using the test stream provided. This suggests it may be a device specific issue (the issue template requests specific device information - which would help us debug this), or sporadic (the issue template requests a full bug report - which would help us try and figure out what's happening even if we can't reproduce due to the sporadic nature, from the logs the bug report contains).

Please do not provide just the specific points I've mentioned, but instead complete the full issue template, which you can find a copy of [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). Please reproduce the issue using the ExoPlayer demo app, so that we capture the demo app's logging in any bug report. Please also provide a fresh test stream if the previous one is no longer working (if the previous one is still active, that's fine).

**Comment by hezie100** [comment] 2018-07-31 17:34
Hi,
thanks for your feedback
I have just sent to: dev.exoplayer@gmail.com,  both Test DASH links for you to reproduce the issue and an Issue template report.
please check and update
thanks again.

**Comment by hezie100** [comment] 2018-08-01 09:00
Dear dev. ExoPlayer team,
could you please confirm reception of issue template and Clear DASH test links I had shared with dev.exoplayer@gmail.com ?
thanks a lot.

**Comment by andrewlewis** [comment] 2018-08-01 09:24
We've received the email. It looks like it's missing a full bug report, so please provide that as requested above.

We'll update here when we get round to investigating further.

**Comment by ojw28** [comment] 2018-08-02 12:33
Also, is the issue device specific, or not? Can you reproduce it on other devices (e.g. a Pixel device, or a recent Samsung S device)?

**Comment by ojw28** [comment] 2018-08-14 15:02
A full bug report was not provided. Closing due to lack of required information. Please reply here if/when you've provided one, and we'll take a look.

**Closed as completed by ojw28** 2018-08-14 15:02 UTC
Labels: need more info
