### ISSUE TITLE
NullPointerException: wrapped.getHeaderField(key) must not be null

### ISSUE THREAD

**Issue by Kolyall** [google/ExoPlayer#10000] opened 2022-02-23 15:15 UTC
"com.google.android.exoplayer:extension-okhttp:2.16.1"
```
val client = OkHttpClient.Builder().build()

val okhttpDataSourceFactory = OkHttpDataSource.Factory(okHttpClient)

val okHttpDataSource = okhttpDataSourceFactory.createDataSource()`

val dashManifest = DashUtil.loadManifest(
                formatDataSource,
                dashManifestFileUrl
            )

val drmInitData = DashUtil.loadFormatWithDrmInitData(okHttpDataSource, dashManifest.getPeriod(0))
```

When I load mpd files with RxWorker all works fine.
But when I use CoroutineWorker
Error is:
```
2022-02-23 18:10:25.379 32257-32341/viplay.moodby.play.dev E/DownloadManager: Task failed: application/dash+xml:6197495697119a0012d9c023:61f92262dd0ad849a6a66c48:61b06838e6a0d106b8ae101f, false
      java.util.concurrent.ExecutionException: java.lang.NullPointerException: wrapped.getHeaderField(key) must not be null
        at com.google.android.exoplayer2.util.RunnableFutureTask.getResult(RunnableFutureTask.java:170)
        at com.google.android.exoplayer2.util.RunnableFutureTask.get(RunnableFutureTask.java:68)
        at com.google.android.exoplayer2.offline.SegmentDownloader.execute(SegmentDownloader.java:355)
        at com.google.android.exoplayer2.offline.SegmentDownloader.getManifest(SegmentDownloader.java:309)
        at com.google.android.exoplayer2.offline.SegmentDownloader.download(SegmentDownloader.java:136)
        at com.google.android.exoplayer2.offline.DownloadManager$Task.run(DownloadManager.java:1348)
     Caused by: java.lang.NullPointerException: wrapped.getHeaderField(key) must not be null
        at com.android.tools.appinspection.network.httpurl.TrackedHttpURLConnection.getHeaderField(TrackedHttpURLConnection.kt:317)
        at com.android.tools.appinspection.network.httpurl.HttpsURLConnectionWrapper.getHeaderField(HttpsURLConnectionWrapper.kt:182)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.isCompressed(DefaultHttpDataSource.java:829)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:413)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:84)
        at com.google.android.exoplayer2.offline.SegmentDownloader$1.doWork(SegmentDownloader.java:313)
        at com.google.android.exoplayer2.offline.SegmentDownloader$1.doWork(SegmentDownloader.java:310)
        at com.google.android.exoplayer2.util.RunnableFutureTask.run(RunnableFutureTask.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by icbaker** [comment] 2022-02-23 15:20
This is a duplicate of #9979 (which you've seen).

As explained there, this is a [bug in the implementation of `TrackedHttpURLConnection`](https://issuetracker.google.com/219572925). This class is provided by Android Studio - possibly when doing some sort of network profiling? Not sure - I assume it shouldn't be included in production apps (though I'm not sure). Regardless, it's not a bug in ExoPlayer: we are obeying the `HttpURLConnection` contract, the Android Studio implementation is violating it and causing this exception to be thrown.

**Closed as completed by icbaker** 2022-02-23 15:20 UTC
Labels: duplicate
