### ISSUE TITLE
aspect ratio issue for 21:9 widescreen movie on v1.5.8

### ISSUE THREAD

**Issue by kunalbhatia** [google/ExoPlayer#2004] opened 2016-10-27 10:00 UTC
Hi Team,

We're trying to play a 21:9 wide screen aspect ratio movie on a 16:9 tv.

**TV Details are:**
Tv Manufacturer: Philips
Android Version: 4.4.2

Usually the desired behavior is, that we see black patch bars on both top and bottom, but it doesn't comes in that way, instead black patch bar comes on all four sides for this particular tv. 

I'll provide you a snapshot of the tv screen, but I can't provide you video url, as it is a paid content

I've attached two images showing abnormal behavior in exoplayer and one image in where we can see the desired behavior in a spuul android app.

**exoplayer images are:** 

![exoplayer_img_2](https://cloud.githubusercontent.com/assets/973321/19762976/ce0efe6e-9c59-11e6-9eca-84806687b665.jpg)

![exoplayer_img_1](https://cloud.githubusercontent.com/assets/973321/19762975/cdf28838-9c59-11e6-8a26-ce5e0ba3a5ac.jpg)

**spuul tv app image:**
![usual_behaviour_spuul_app](https://cloud.githubusercontent.com/assets/973321/19762977/ce11d936-9c59-11e6-81fa-ad7c0437f23f.jpg)

Please suggest us a solution to get the desired output on a 16:9 tv.

**Comment by ojw28** [comment] 2016-10-27 10:52
Are you certain the black bars on the left and right aren't "burnt in" to the video stream itself? If so then this is working as intended, and the black bars need to be removed from the video stream to fix the issue.

**Comment by kunalbhatia** [comment] 2016-10-27 11:14
@ojw28 
ok to clarify, I'll upload a snapshot of same stream in some different 16:9 tv.
Here Tv manufacturer is LG and we've fire tv stick with android os 5.2
below is the snap:
![img_20161027_163628284](https://cloud.githubusercontent.com/assets/973321/19765099/39520478-9c64-11e6-8521-10f39f51f6fb.jpg)

**Comment by ojw28** [comment] 2016-10-27 11:19
In that case it sounds very much like a Philips specific issue. Have you reported it to Philips? If not, you should probably do so. If you provide a full bug report from the device then we can try and route the issue internally as well.

**Comment by kunalbhatia** [comment] 2016-10-27 12:28
but spuul tv app is working fine for movies with aspect ratio 21:9.

Also, as per our observation, TVs with width less than 720, this issue arises where as TVs with width more than 720 it works fine, but on both TVs may it be 720 or less than that, spuul app is working fine.

**Comment by ojw28** [comment] 2016-11-16 22:36
How do you know the issue affects TVs where the width is less than 720 if you've only seen the issue on one TV? If you've seen the issue on multiple devices, please provide full details in all cases. We really need full bug reports from the affected devices as well, if you want us to investigate this issue further.

**Comment by kunalbhatia** [comment] 2016-11-17 02:42
Yes I'm certain, as the same stream works fine on other TVs, I guess this
issue is device specific, I've tried others players also, but still the
output remains same for that specific TV.

**Comment by ojw28** [comment] 2016-11-17 11:13
Please see my latest comment above (the one you just replied to was ~21 days ago; I'd suggest opening this issue on the GitHub website in case email is messing things up).

**Comment by ojw28** [comment] 2017-01-13 15:32
Closing because a bug report was not provided.

**Closed as completed by ojw28** 2017-01-13 15:32 UTC
Labels: need more info, bug: device specific
