### ISSUE TITLE
MediaDrmCallback override method not called.

### ISSUE THREAD

**Issue by mitab86** [google/ExoPlayer#6465] opened 2019-09-24 06:18 UTC
I am using DefaultDrmSessionManager and passing a MediaDrmCallback to its parameter. The Drm content is playing fine in API 24 but could not play on API 28. Also after logging the override methods, I found out that `executeProvisionRequest` was not called on API 24 and `executeKeyRequest`  was not called on API 28. Due to which I was not able to fetch `License Url `  which depends upon payload inside `executeKeyRequest` method on API 28.

Here is my code

 ```
MediaDrmCallback mediaDrmCallback = new MediaDrmCallback() {
        @Override
        public byte[] executeProvisionRequest(UUID uuid, ExoMediaDrm.ProvisionRequest request) throws Exception {
            String url = request.getDefaultUrl() + "&signedRequest=" + new String(request.getData());
            LogCS.e("executeProvision", "executeProvsion");
            return executePost(dataSourceFactory, url, null, null);

        }

        @Override
        public byte[] executeKeyRequest(UUID uuid, ExoMediaDrm.KeyRequest request) throws Exception {
            LogCS.e("executeKeyRequest", "executeKeyRequest");

            try {
                String payload = Base64.encodeToString(request.getData(), Base64.DEFAULT);

                LogCS.e("payload", payload.trim().replaceAll("\n", ""));

                DRMLicensePresenterImpl drmLicensePresenter = new DRMLicensePresenterImpl(ExoplayerActivity.this, ExoplayerActivity.this, payload.trim().replaceAll("\n", ""), ticketToStream);
                drmLicensePresenter.getDRMLicenseDetail(UrlUtil.getAltBalajiUrl(ExoplayerActivity.this, UrlUtil.DRM_LICENSE));

            } catch (Exception e) {
                e.printStackTrace();
            }
            LogCS.e("license is" + count++ + "----", license);

            // get license
            return Base64.decode(license, Base64.DEFAULT);

        }
    };

    private static byte[] executePost(HttpDataSource.Factory dataSourceFactory, String url,
                                      byte[] data, Map<String, String> requestProperties) throws IOException {
        HttpDataSource dataSource = dataSourceFactory.createDataSource();
        if (requestProperties != null) {
            for (Map.Entry<String, String> requestProperty : requestProperties.entrySet()) {
                dataSource.setRequestProperty(requestProperty.getKey(), requestProperty.getValue());
            }
        }
        DataSpec dataSpec = new DataSpec(Uri.parse(url), data, 0, 0, C.LENGTH_UNSET, null,
                DataSpec.FLAG_ALLOW_GZIP);
        DataSourceInputStream inputStream = new DataSourceInputStream(dataSource, dataSpec);
        try {
            return Util.toByteArray(inputStream);
        } finally {
            Util.closeQuietly(inputStream);
        }
    }
```
` drmSessionManager = new DefaultDrmSessionManager<>(C.WIDEVINE_UUID, FrameworkMediaDrm.newInstance(C.WIDEVINE_UUID), mediaDrmCallback, null, false);`

**Comment by mitab86** [comment] 2019-09-26 09:51
@AquilesCanta @willnorris @xian @kiall @talklittle @icbaker @tonihei  any help please

**Comment by ojw28** [comment] 2019-10-02 12:33
* I don't think it's particularly relevant whether `executeProvisionRequest` is called, unless provisioning is actually failing on the problematic devices.
* It's unclear why you're not using `HttpMediaDrmCallback`. Is there a reason you're providing your own?
* It's not clear what the actual issue is. Does playback fail, and if so, what's the actual playback failure? Please can you provide proper reproduction steps, a bug report etc, as requested in the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=).

p.s. It's not really appropriate to spam everyone you can think of because your issue is unanswered for two days. Please bear in mind we deal with a lot of issues.

**Comment by mitab86** [comment] 2019-10-03 02:22
- We are using our own `mediaDrmCallBack` because `DrmLicense` can only be requested from `executeKeyRequest` according to the third party service provider guide. We do not get DrmLicense before.

```
@Override
        public byte[] executeKeyRequest(UUID uuid, ExoMediaDrm.KeyRequest request) throws Exception {
            try {
                String payload = Base64.encodeToString(request.getData(), Base64.DEFAULT)
                DRMLicensePresenterImpl drmLicensePresenter = new DRMLicensePresenterImpl(ExoplayerActivity.this, ExoplayerActivity.this, payload.trim().replaceAll("\n", ""), ticketToStream);
                drmLicensePresenter.getDRMLicenseDetail(UrlUtil.getAltBalajiUrl(ExoplayerActivity.this, UrlUtil.DRM_LICENSE));

            } catch (Exception e) {
                e.printStackTrace();
            }
            LogCS.e("license is" + count++ + "----", license);

            // get license
            return Base64.decode(license, Base64.DEFAULT);

        }
```

- The player stops without playing any content but the seek bar shows the duration of the video and video does not start on Android pie but plays on marshmallow. I have checked on multiple devices and does not seem to be a device-specific issue. Here is the error that I am getting due to failure in calling the LicenseUrl 

```
2019-09-26 10:12:41.392 6495-7310/com.osolutions.poc E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:739)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:422)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionError(DefaultDrmSession.java:211)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onProvisionError(DefaultDrmSessionManager.java:602)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionResponse(DefaultDrmSession.java:281)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$000(DefaultDrmSession.java:41)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:469)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:128)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity.executePost(ExoplayerActivity.java:453)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity.access$200(ExoplayerActivity.java:118)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity$4.executeProvisionRequest(ExoplayerActivity.java:414)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:500)
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by AquilesCanta** [comment] 2019-10-03 09:37
You need  to fix the server or the key request parameters so that you get the keys to play the content. Perhaps you are missing an HTTP header or using the wrong URL?

We can draw two conclusion from the provided stack trace:
- The device is provisioned (no need for provisioning, as @ojw28 points out above). Otherwise, there would be no key request at all.
- The server is just returning a 404 when you are requesting the keys which explains why you cannot play the content.

The duration of the content is known without having the keys. Let me know if I'm misreading something here. Otherwise, feel free to close the issue.

**Comment by mitab86** [comment] 2019-10-03 15:58
Does that mean we need to ask the third party to change the flow of requesting of the Licence URL and use HttpMediaDrmCallback instead of custom mediaDrmCallback? 
Yes, the seek bar shows the length of the video (duration) but does not play the video on android pie but plays the same video in marshmallow device.

**Comment by AquilesCanta** [comment] 2019-10-03 18:43
> Does that mean we need to ask the third party to change the flow of requesting of the Licence URL and use HttpMediaDrmCallback instead of custom mediaDrmCallback?

No.

> does not play the video on android pie but plays the same video in marshmallow

The same code works in M but not in P? If so, please provide the bugreport and content reproduce the issue, as requested in the issue template. We cannot help otherwise.

**Comment by mitab86** [comment] 2019-10-05 14:48
Here is the log report I got after using `EventLogger`. Sorry if something is wrong with Debugging 
```
2019-10-05 20:29:29.364 9560-9560/com.osolutions.otv I/ExoPlayerImpl: Init 1eb37af [ExoPlayerLib/2.8.2] [HWBLA, BLA-AL00, HUAWEI, 28]
2019-10-05 20:29:29.402 9560-9560/com.osolutions.otv D/EventLogger: state [0.02, 0.00, window=0, false, BUFFERING]
2019-10-05 20:29:29.405 9560-9560/com.osolutions.otv D/EventLogger: state [0.02, 0.00, window=0, true, BUFFERING]
2019-10-05 20:29:29.663 9560-9560/com.osolutions.otv D/EventLogger: timelineChanged [0.28, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
2019-10-05 20:29:29.663 9560-9560/com.osolutions.otv D/EventLogger:   period [1091.95]
2019-10-05 20:29:29.664 9560-9560/com.osolutions.otv D/EventLogger:   window [1091.95, true, false]
2019-10-05 20:29:29.664 9560-9560/com.osolutions.otv D/EventLogger: ]
2019-10-05 20:29:29.689 9560-9560/com.osolutions.otv D/EventLogger: mediaPeriodCreated [0.31, 0.00, window=0, period=0]
2019-10-05 20:29:29.691 9560-9560/com.osolutions.otv D/EventLogger: loading [0.31, 0.00, window=0, period=0, true]
2019-10-05 20:29:29.734 9560-9560/com.osolutions.otv D/EventLogger: decoderEnabled [0.35, 0.00, window=0, period=0, video]
2019-10-05 20:29:29.735 9560-9560/com.osolutions.otv D/EventLogger: decoderEnabled [0.35, 0.00, window=0, period=0, audio]
2019-10-05 20:29:29.738 9560-9560/com.osolutions.otv D/EventLogger: tracksChanged [0.36, 0.00, window=0, period=0, 
2019-10-05 20:29:29.738 9560-9560/com.osolutions.otv D/EventLogger:   Renderer:0 [
2019-10-05 20:29:29.739 9560-9560/com.osolutions.otv D/EventLogger:     Group:0, adaptive_supported=YES [
2019-10-05 20:29:29.739 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=153681, res=320x180, fps=25.0, supported=YES
2019-10-05 20:29:29.739 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:1, id=2, mimeType=video/avc, bitrate=400508, res=480x270, fps=25.0, supported=YES
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:2, id=4, mimeType=video/avc, bitrate=598218, res=640x360, fps=25.0, supported=YES
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:3, id=6, mimeType=video/avc, bitrate=845201, res=640x360, fps=25.0, supported=YES
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:4, id=8, mimeType=video/avc, bitrate=1192408, res=1024x576, fps=25.0, supported=YES
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:5, id=9, mimeType=video/avc, bitrate=2380125, res=1280x720, fps=25.0, supported=YES
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:6, id=12, mimeType=video/avc, bitrate=3272406, res=1280x720, fps=25.0, supported=YES
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:7, id=14, mimeType=video/avc, bitrate=4464071, res=1920x1080, fps=25.0, supported=YES
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:8, id=15, mimeType=video/avc, bitrate=1785967, res=1024x576, fps=25.0, supported=YES
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:     ]
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:   ]
2019-10-05 20:29:29.740 9560-9560/com.osolutions.otv D/EventLogger:   Renderer:1 [
2019-10-05 20:29:29.741 9560-9560/com.osolutions.otv D/EventLogger:     Group:0, adaptive_supported=YES_NOT_SEAMLESS [
2019-10-05 20:29:29.741 9560-9560/com.osolutions.otv D/EventLogger:       [ ] Track:0, id=1, mimeType=audio/mp4a-latm, bitrate=69615, channels=2, sample_rate=44100, language=en, supported=YES
2019-10-05 20:29:29.741 9560-9560/com.osolutions.otv D/EventLogger:       [ ] Track:1, id=3, mimeType=audio/mp4a-latm, bitrate=69615, channels=2, sample_rate=44100, language=en, supported=YES
2019-10-05 20:29:29.741 9560-9560/com.osolutions.otv D/EventLogger:       [ ] Track:2, id=5, mimeType=audio/mp4a-latm, bitrate=69615, channels=2, sample_rate=44100, language=en, supported=YES
2019-10-05 20:29:29.741 9560-9560/com.osolutions.otv D/EventLogger:       [ ] Track:3, id=7, mimeType=audio/mp4a-latm, bitrate=69615, channels=2, sample_rate=44100, language=en, supported=YES
2019-10-05 20:29:29.741 9560-9560/com.osolutions.otv D/EventLogger:       [ ] Track:4, id=10, mimeType=audio/mp4a-latm, bitrate=69615, channels=2, sample_rate=44100, language=en, supported=YES
2019-10-05 20:29:29.741 9560-9560/com.osolutions.otv D/EventLogger:       [X] Track:5, id=11, mimeType=audio/mp4a-latm, bitrate=101616, channels=2, sample_rate=44100, language=en, supported=YES
2019-10-05 20:29:29.741 9560-9560/com.osolutions.otv D/EventLogger:       [ ] Track:6, id=13, mimeType=audio/mp4a-latm, bitrate=101616, channels=2, sample_rate=44100, language=en, supported=YES
2019-10-05 20:29:29.741 9560-9560/com.osolutions.otv D/EventLogger:       [ ] Track:7, id=16, mimeType=audio/mp4a-latm, bitrate=69615, channels=2, sample_rate=44100, language=en, supported=YES
2019-10-05 20:29:29.742 9560-9560/com.osolutions.otv D/EventLogger:       [ ] Track:8, id=17, mimeType=audio/mp4a-latm, bitrate=101616, channels=2, sample_rate=44100, language=en, supported=YES
2019-10-05 20:29:29.742 9560-9560/com.osolutions.otv D/EventLogger:     ]
2019-10-05 20:29:29.742 9560-9560/com.osolutions.otv D/EventLogger:   ]
2019-10-05 20:29:29.742 9560-9560/com.osolutions.otv D/EventLogger: ]
2019-10-05 20:29:29.745 9560-9560/com.osolutions.otv D/EventLogger: mediaPeriodReadingStarted [0.36, 0.00, window=0, period=0]
2019-10-05 20:29:30.705 9560-9560/com.osolutions.otv I/MediaDrm: Drm event (1,0)
2019-10-05 20:29:31.019 9560-10049/com.osolutions.otv E/executeProvision: executeProvsion
2019-10-05 20:29:31.020 9560-9560/com.osolutions.otv D/EventLogger: decoderInputFormatChanged [1.64, 0.00, window=0, period=0, audio, id=11, mimeType=audio/mp4a-latm, bitrate=101616, channels=2, sample_rate=44100, language=eng]
2019-10-05 20:29:31.021 9560-9560/com.osolutions.otv D/EventLogger: decoderInputFormatChanged [1.64, 0.00, window=0, period=0, video, id=4, mimeType=video/avc, bitrate=598218, res=640x360, fps=25.0]
2019-10-05 20:29:31.022 9560-9560/com.osolutions.otv D/EventLogger: state [1.64, 0.00, window=0, period=0, true, READY]
2019-10-05 20:29:31.635 9560-10049/com.osolutions.otv E/executeProvision: executeProvsion
2019-10-05 20:29:32.203 9560-9680/com.osolutions.otv W/OneSignal: Location permission exists but GoogleApiClient timed out. Maybe related to mismatch google-play aar versions.
2019-10-05 20:29:32.341 9560-9577/com.osolutions.otv W/System: A resource failed to call end. 
2019-10-05 20:29:33.262 9560-10049/com.osolutions.otv E/executeProvision: executeProvsion
2019-10-05 20:29:35.713 9560-10049/com.osolutions.otv E/executeProvision: executeProvsion
2019-10-05 20:29:36.206 9560-10061/com.osolutions.otv I/OMXClient: IOmx service obtained
2019-10-05 20:29:36.211 9560-10061/com.osolutions.otv I/ACodec: In onAllocateComponent create compenent, codec name: OMX.hisi.video.decoder.avc
2019-10-05 20:29:36.218 9560-10060/com.osolutions.otv D/SurfaceUtils: connecting to surface 0x7de96d0010, reason connectToSurface
2019-10-05 20:29:36.219 9560-10060/com.osolutions.otv I/MediaCodec: [OMX.hisi.video.decoder.avc] setting surface generation to 9789441
2019-10-05 20:29:36.219 9560-10060/com.osolutions.otv D/SurfaceUtils: disconnecting from surface 0x7de96d0010, reason connectToSurface(reconnect)
2019-10-05 20:29:36.219 9560-10060/com.osolutions.otv D/SurfaceUtils: connecting to surface 0x7de96d0010, reason connectToSurface(reconnect)
2019-10-05 20:29:36.222 9560-10061/com.osolutions.otv E/ACodec: [OMX.hisi.video.decoder.avc] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
2019-10-05 20:29:36.224 9560-10061/com.osolutions.otv E/libc: Access denied finding property "ro.kirin.product.platform"
2019-10-05 20:29:36.224 9560-10061/com.osolutions.otv E/HwExtendedCodec: mime: video/avc matching compontent failed!
2019-10-05 20:29:36.225 9560-10061/com.osolutions.otv I/HwExtendedCodec: mime is [video/avc] at setVideoFormat
2019-10-05 20:29:36.228 9560-10061/com.osolutions.otv I/ACodec: codec does not support config priority (err -22)
2019-10-05 20:29:36.229 9560-10061/com.osolutions.otv I/ACodec: [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
2019-10-05 20:29:36.229 9560-10061/com.osolutions.otv I/ACodec: [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
2019-10-05 20:29:36.229 9560-10061/com.osolutions.otv I/ACodec: [OMX.hisi.video.decoder.avc] using color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) and dataspace 0x103
2019-10-05 20:29:36.236 9560-10061/com.osolutions.otv I/ACodec: onStart
2019-10-05 20:29:36.287 9560-10061/com.osolutions.otv D/SurfaceUtils: disconnecting from surface 0x7de96d0010, reason setNativeWindowSizeFormatAndUsage
2019-10-05 20:29:36.287 9560-10061/com.osolutions.otv D/SurfaceUtils: connecting to surface 0x7de96d0010, reason setNativeWindowSizeFormatAndUsage
2019-10-05 20:29:36.288 9560-10061/com.osolutions.otv D/SurfaceUtils: set up nativeWindow 0x7de96d0010 for 640x360, color 0x30d, rotation 0, usage 0x20002900
2019-10-05 20:29:36.322 9560-9560/com.osolutions.otv D/EventLogger: decoderInitialized [6.94, 0.00, window=0, period=0, video, OMX.hisi.video.decoder.avc]
2019-10-05 20:29:36.324 9560-9560/com.osolutions.otv D/EventLogger: downstreamFormatChanged [6.94, 0.00, window=0, period=0, id=4, mimeType=video/avc, bitrate=598218, res=640x360, fps=25.0]
2019-10-05 20:29:36.326 9560-10045/com.osolutions.otv E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:739)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:422)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionError(DefaultDrmSession.java:211)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onProvisionError(DefaultDrmSessionManager.java:602)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionResponse(DefaultDrmSession.java:281)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$000(DefaultDrmSession.java:41)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:469)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:128)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity.executePost(ExoplayerActivity.java:456)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity.access$200(ExoplayerActivity.java:120)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity$4.executeProvisionRequest(ExoplayerActivity.java:417)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:500)
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2019-10-05 20:29:36.327 9560-10061/com.osolutions.otv I/ACodec: [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
2019-10-05 20:29:36.327 9560-10061/com.osolutions.otv I/ACodec: [OMX.hisi.video.decoder.avc] got color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) err=0(NO_ERROR)
2019-10-05 20:29:36.327 9560-10061/com.osolutions.otv I/ACodec: [OMX.hisi.video.decoder.avc] using color aspects (R:2(Limited), P:4(BT601_6_525), M:3(BT601_6), T:3(SMPTE170M)) and dataspace 0x103
2019-10-05 20:29:36.327 9560-10061/com.osolutions.otv W/ACodec: forcing OMX state to Idle when received shutdown in ExecutingState
2019-10-05 20:29:36.358 9560-10060/com.osolutions.otv D/SurfaceUtils: disconnecting from surface 0x7de96d0010, reason disconnectFromSurface
2019-10-05 20:29:36.384 9560-9560/com.osolutions.otv D/EventLogger: decoderDisabled [7.00, 0.00, window=0, period=0, video]
2019-10-05 20:29:36.385 9560-9560/com.osolutions.otv D/EventLogger: decoderDisabled [7.00, 0.00, window=0, period=0, audio]
2019-10-05 20:29:36.389 9560-9560/com.osolutions.otv D/EventLogger: mediaPeriodReleased [7.01, 0.00, window=0, period=0]
2019-10-05 20:29:36.393 9560-9560/com.osolutions.otv E/EventLogger: playerFailed [7.01, 0.00, window=0]
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.shouldWaitForKeys(MediaCodecRenderer.java:842)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:739)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:422)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionError(DefaultDrmSession.java:211)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onProvisionError(DefaultDrmSessionManager.java:602)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.onProvisionResponse(DefaultDrmSession.java:281)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.access$000(DefaultDrmSession.java:41)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostResponseHandler.handleMessage(DefaultDrmSession.java:469)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:128)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity.executePost(ExoplayerActivity.java:456)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity.access$200(ExoplayerActivity.java:120)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity$4.executeProvisionRequest(ExoplayerActivity.java:417)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:500)
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2019-10-05 20:29:36.393 9560-9560/com.osolutions.otv E/ExoplayerActivity: TYPE_RENDERER: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
2019-10-05 20:29:36.395 9560-9560/com.osolutions.otv D/EventLogger: loading [7.01, 0.00, window=0, false]
2019-10-05 20:29:36.395 9560-9560/com.osolutions.otv D/EventLogger: state [7.01, 0.00, window=0, true, IDLE]
```

**Comment by ojw28** [comment] 2019-10-08 15:17
To correct an earlier point, I don't think the device is provisioned. It's provisioning that's failing with a 404 response code here:

```
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
        at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:128)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity.executePost(ExoplayerActivity.java:456)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity.access$200(ExoplayerActivity.java:120)
        at com.osolutions.otv.movie.exoplayer.ExoplayerActivity$4.executeProvisionRequest(ExoplayerActivity.java:417)
        at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:500)
```

I would suggest that you:

1. Make sure your `executeProvisionRequest` behaves exactly like the `HttpMediaDrmCallback` implementation (just copy and paste from `HttpMediaDrmCallback` into your custom callback implementation). You can keep your custom implementation of `executeKeyRequest`. See whether that fixes it.
1. If it's still failing, please could you provide a sample URL calculated in `executeProvisionRequest`. Please also provide details of what device this happens on. To ensure we get sufficient information, please provide the output of `adb shell getprop ro.build.version.release` when the device is attached via USB. If the device happens to be located in China, that would also be relevant information.

**Comment by mitab86** [comment] 2019-10-10 13:49
Thank you @ojw28 that did solve my problem. Have a good day.

**Closed as completed** 2019-10-16 12:49 UTC
Labels: question
