### ISSUE TITLE
  Fatal Exception: android.view.InflateException Binary XML file line #28: Binary XML file line #28: Error inflating class com.google.android.exoplayer2.ui.StyledPlayerView

### ISSUE THREAD

**Issue by kyh8496** [google/ExoPlayer#11128] opened 2023-04-19 02:23 UTC
### Bug

Fatal Exception: android.view.InflateException
Binary XML file line #28: Binary XML file line #28: Error inflating class com.google.android.exoplayer2.ui.StyledPlayerView

release version crash!!

What proguard settings do you need?

Caused by android.content.res.Resources$NotFoundException
Font resource ID #0x7f090000 could not be retrieved.

playerview is ok!
but crash in StyledPlayerView

**Comment by icbaker** [comment] 2023-04-19 09:08
Duplicate of https://github.com/google/ExoPlayer/issues/10409

**Closed as completed by icbaker** 2023-04-19 09:08 UTC
Labels: duplicate
