### ISSUE TITLE
DrmSessionException when downloading offline license on a specific device

### ISSUE THREAD

**Issue by ogawa-ma** [google/ExoPlayer#7720] opened 2020-08-06 08:17 UTC
### [REQUIRED] Searched documentation and issues
・ExoPlayer Javadoc.
・ExoPlayer Issues

### [REQUIRED] Question
Hi.

I get a DrmSessionException when I try to download an offline license.

■ error message
```
 com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error
```

■ Offline license download process
```

val dataSourceFactory = LocalDefaultHttpDataSourceFactory(
    Util.getUserAgent(context, context.getString(R.string.app_name))
)
val offlineLicenseHelper =
    OfflineLicenseHelper.newWidevineInstance(
        licenseUrl,
        dataSourceFactory,
        MediaSourceEventDispatcher()
    )
val datasource = dataSourceFactory.createDataSource()
val context = (MgsApplication.appContext as MgsApplication)
val dashManifest = DashUtil.loadManifest(datasource, Uri.parse(manifest))
val drmInitData = DashUtil.loadDrmInitData(datasource, dashManifest.getPeriod(0))
if (drmInitData != null) {
    val offlineLicenseKeySetId = offlineLicenseHelper.downloadLicense(drmInitData)
}

```

When I check the license server's issuance history, the license is issued successfully.

This error occurs in SC-02H, but there are SC-02H where an error occurs and SC-02H where an error does not occur.
I don't know why some devices occur in the same SC-02H and some do not.

A terminal with an error always throws a DrmSessionException no matter how many times I try to download it.
On the contrary, the offline license can be successfully downloaded even if the device that does not generate the error is downloaded many times.

What can cause this?
Also, have you seen a similar phenomenon?

ExoPlayer version used: 2.11.3

Device information that occurred
Device Name:Galaxy S7 edge
Model Number: SC-02H
Android Version: 8.0.0

### A full bug report captured from the device
sorry. 
This error is caused by a user who is using the app we are releasing, so we cannot get the bug report.
However, since you can put logs in the application, if you have any necessary logs, please let me know. 
put the logs in the app get the logs.

**Comment by rrfrias** [comment] 2020-08-11 20:50
@ogawa-ma , there is not enough information for us to determine the root cause of this problem. The DrmSessionException in this case is a MediaDrmStateException. If you can cast and log [MediaStateException#getDiagnosticInfo](https://developer.android.com/reference/android/media/MediaDrm.MediaDrmStateException#getDiagnosticInfo()) that will narrow down the problem. The most useful logs are in the framework, so a bugreport would greatly help if that is at all possible.

**Comment by ogawa-ma** [comment] 2020-08-12 11:41
@rrfrias 
Thank you for your reply.
This was the value I got from the MediaStateException＃getDiagnosticInfo
`android.media.MediaDrm.error_neg_2000 `

**Comment by jt64** [comment] 2020-08-25 22:23
@ogawa-ma Thank you for getting the diagnostic info. unfortunately there isn't enough detail in it to help us narrow down the problem further. Would it be possible to ask the user to capture a bugreport after the failure occurs by following [these instructions](https://developer.android.com/studio/debug/bug-report)?

**Comment by ogawa-ma** [comment] 2020-09-04 02:02
sorry. You can't ask users to capture a bug report.

**Comment by rrfrias** [comment] 2020-09-08 22:32
It is difficult to investigate this issue without logs from the OS which will are included in a bugreport. Without knowing more about the specific failure, some options are falling back to L3 (security level) or a factory reset. There might be some changes in newer releases that might help, but this device is unlikely to get an update given it is still running android 8.0.0.

**Comment by rrfrias** [comment] 2020-09-26 07:05
Closing as we do not have sufficient information to make progress. We are working to improve error reporting through exceptions in future releases. If you get a bugreport or a logcat, please reopen.

**Closed as completed by rrfrias** 2020-09-26 07:05 UTC
Labels: bug: in platform drm
