### ISSUE TITLE
Is there a flag to bypass the Shoutcast Metadata?

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#7825] opened 2020-08-28 19:08 UTC
Hi
i've found the script you wrote to find the metadata is very slow and there are better way 
i'm using a radio player, their script is very fast and reliable, after upgrading to the new Exoplayer they are forced to use your script which is  very slow and takes more than 10s to get the new metadata.
so i'm asking is their a way to bypass your script so i can use the older script of the radio player.
Thanks

**Comment by ojw28** [comment] 2020-08-28 20:13
Sorry, but it's impossible to understand what this means from the information provided. If there's a problem where ExoPlayer is slow to report Shoutcast metadata, please structure this issue as a bug report where you clearly describe what the problem is and how to reproduce it. Reproduction steps should be provided for the ExoPlayer demo app or some other publicly available code that we can look at, including links to any sample content that reproduces the issue.

If you're reporting an issue with a closed source radio application, you should report the issue to the developer of that application, since there is no way for us to determine whether the issue is with ExoPlayer or with their application code. It's also quite unlikely that we're forcing anyone to use any particular block of code. ExoPlayer is designed to be extensible and customizable, and as such it's quite likely possible to disable a code block if it's problematic. In the worst case it's always possible to do this by editing the source code directly.

**Comment by satyres** [comment] 2020-08-28 20:23
Hi
it's not a bug .
starting from the version 2.10.X you have added the shoutcast support which is very good by the way.
i was using an app called RadioDroid , this app has a very good script to find the shoutcast metadata and as soon as the song change it get's the new metadata.
but lately they have been forced to use the new Exploayer 2.10.X and they used your script to get the new metadata , but it's not so fast as their script.
i was wondering if there is a way to turn off the default script of Exoplayer and use the script of RadioDroid so i can record without having glitches because of the metadata.
Thanks and sorry if i bother you.

**Comment by ojw28** [comment] 2020-08-28 20:57
> it's not a bug .

If it's taking 10 seconds to get metadata that it should be possible to get immediately, then it probably is a bug.

> but lately they have been forced to use the new Exploayer 2.10.X and they used your script to get the new metadata , but it's not so fast as their script.

In what way have they been "forced" to do this, and how do you know that ExoPlayer 2.10 is the root cause of whatever the problem is that has caused metadata retrieval to be slower than it used to be? It sounds like you should report the issue to the application developer, rather than here. If there is a bug in ExoPlayer that's causing this, it should be reported as a bug with proper reproduction steps using the ExoPlayer demo app, as mentioned above.

**Comment by satyres** [comment] 2020-08-28 21:18
Thank you for your answer.
i'm sure it's not a bug it's working fine for Exoplayer , 
well i need to make more test to find out the problem can you tell me if there is a flag to turn off the metadata shoutcast in Exoplayer or how to override it  in order to find out the problem.
Thanks for your awesome work , really appreciate it 
regards

**Comment by ojw28** [comment] 2020-08-28 21:53
If it's working fine in ExoPlayer then it's probably a bug in RadioDroid, so you should report the issue there.

There are a few different ways of disabling ICY metadata handling. For example, you can write a custom `DataSource` that rewrites each request to remove the `Icy-MetaData` request header. This will stop the server from sending ICY metadata back to the player. You can also edit `ProgressiveMediaPeriod` directly to remove the ICY metadata handling logic that was added there.

Closing for now, since this seems like an application issue that's not under our control.

**Closed as completed by ojw28** 2020-08-28 21:53 UTC
Labels: wont fix: app issue
