### ISSUE TITLE
CEA-608 with multiple tracks

### ISSUE THREAD

**Issue by emveepee** [google/ExoPlayer#10666] opened 2022-10-03 14:56 UTC
I have been able to force  CEA608 subtitles on mpegts streams and it is working as expected, but I have not found a way to force anything but the first  CC.  In the US there is often a Spanish stream and VLC is reporting these on CC-3 but I have tried setAccessibilityChannel(3) but there no subtitles, forcing  "sp" etc without success.

CCExtractor finds them with field 2 caption one which should be 3.

Is there any working example dealing with multiple set of captions?

**Comment by emveepee** [comment] 2022-10-03 23:41
I have been using the code with the debugger and it turns out the data is there when I force it but it isn't being displayed correctly.  It seems there is a conflict with the xds handling also on field 2, so this is more an issue then question.

I can get it almost working by not ignoring the xds data with

      if (!isCaptionValid  && isInCaptionService ) {

here https://github.com/google/ExoPlayer/blob/release-v2/library/extractor/src/main/java/com/google/android/exoplayer2/text/cea/Cea608Decoder.java#L500

**Comment by emveepee** [comment] 2022-10-05 00:17
I found another issue in the code on the test for the control byte https://github.com/google/ExoPlayer/blob/ab4d37f499ba49bb3cac7938eb03ebf7133ccfe6/library/extractor/src/main/java/com/google/android/exoplayer2/text/cea/Cea608Decoder.java#L876 doesn't meet spec.  On field 2 the control byte is 0x15

**Comment by tonihei** [comment] 2022-10-06 13:11
Thanks for investigating this. As you noted, the different accessibility channels should be supported, but it sounds like there might be bug. Can you share the stream you are using with us? Otherwise it's hard to reproduce and to fix. You can also send a link to dev.exoplayer@gmail.com with "Issue #10666" in the subject if you don't want to post here.

**Comment by emveepee** [comment] 2022-10-06 13:57
@tonihei I sent the link.  This file has CC's in field 1 and field2 also with xds data.   Here is the spec

```
When closed captioning is used on line 21, field 2, it shall conform to all of the applicable specifications
and recommended practices as defined for field 1 services with the following differences:

a) The non-printing character of the miscellaneous control-character pairs that fall in the range of 0x14,
0x20 to 0x14, 0x2F in field 1, shall be replaced with 0x15, 0x20 to 0x15, 0x2F when used in field 2.

b) The non-printing character of the miscellaneous control-character pairs that fall in the range of 0x1C,
0x20 to 0x1C, 0x2F in field 1, shall be replaced with 0x1D, 0x20 to 0x1D, 0x2F when used in field 2.

c) When any of the control codes from 0x01 to 0x0F is used to begin a control-character pair it indicates
the beginning of XDS Data. This XDS data should be considered part of a different data channel and
can be used to interrupt the captioning data according to the FCC rules for other data channels
```

**Comment by icbaker** [comment] 2022-10-07 17:25
Thanks for the test media and all the pointers - I've looked into this and think I've found two different issues:

1. As you pointed out, we're too strict in `isServiceSwitchCommand()`. I've fixed this by relaxing the check a little by ANDing with `0xF6` instead of `0xF7` so it works for both `0x14` and `0x15`. You can see this is already done in `isMiscCode` above.
2. Some of the packets in the file you provided seem to have invalid parity. The code currently measures the 'invalidity' of a packet in two ways:
   * The validity bit in the packet header
   * The parity check of the `cc1` and `cc2` bytes
   
   In both cases it assumes that an 'invalid' packet should **clear all existing subtitle data**. This causing the subtitles of your spanish track to be cleared before they were shown. There's a comment in the code which says `The encoder has flipped the validity bit to indicate captions are being turned off`. Based on that wording I experimentally changed it so the clearing only happens based on the header bit (which is the only one the encoder should be setting). If a packet fails parity then it's skipped, but previous data is not cleared.

These changes together result in the subtitles in your file being shown.

I think (1) is uncontroversial and I'll send it for internal review shortly.

(2) (the parity change) is a bigger deal. Reading through the discussion on #5086 (where this clear-on-invalid-parity logic was first added), it looks like it was queried at the time but was needed for sarnoff compliance. I need to have more of a think about this. It's possible that we can keep the general check, but re-order the statements slightly - I need to dig into exactly what packet(s) in your stream were failing the parity check.

**Comment by emveepee** [comment] 2022-10-07 17:33
> Thanks for the test media and all the pointers - I've looked into this and think I've found two different issues:
> 

I agree that is why I made the two comments, the first got most of the subtitles with errors, the second and the CC-3 subtitles were cleaned up.

>        In both cases it assumes that an 'invalid' packet should **clear all existing subtitle data**. This causing the subtitles of your spanish track to be cleared before they were shown. There's a comment in the code which says `The encoder has flipped the validity bit to indicate captions are being turned off`. Based on that wording I experimentally changed it so the clearing only 

That comment wouldn't apply to xds pseudo channels though so if it isn't writing cc's then perhaps it is not a valid generalization for a "clear".  When it isn't xds data there is not different.  Certainly it works well with the change.

**Comment by icbaker** [comment] 2022-10-07 17:45
It seems that every packet with invalid parity is the same, it's always `[0x8F, 0xD8]`. After we remove the parity bit, that's `[0x0F, 0x58]`. I think `0x0F` indicates this is a checksum packet (from CEA-608-E section 8.6.2):
> For all packet classes and types, there is a single control code (0x0F) to identify the end of the packet. This code shall be followed by a single Checksum Data Byte to complete the pair.

It seems a) wrong that the sum would always be `0x58` (?) and b) wrong that this byte always has incorrect parity. Where did you get this file from? It seems like maybe the encoder is just putting a placeholder checksum in that doesn't have the correct parity? In that case it seems to me that the stream is invalid.

**Comment by icbaker** [comment] 2022-10-07 17:50
I added a more targeted workaround for this particular problem (checksum with invalid parity) and the file now shows subtitles. This is less risky than the larger parity change. I will send it for review internally and see what the team says.

The change adds this block before the `isCaptionValid` assignment near the top of `decode()`:

```java
if (isCtrlCode(ccData1) && ccData1 == 0x0F && !ODD_PARITY_BYTE_TABLE[ccByte2]) {
  // The checksum has invalid parity, so we just ignore it (but don't clear the existing
  // subtitle data).
  continue;
}
```

**Comment by emveepee** [comment] 2022-10-07 18:06
I got the file from a user in the US, it would be CableCard cable data.  I know when I ran the file through CCExtractor all the checksums validated.  I will see if I can pinpoint the difference, it might be related to situations where two xds buffers are being used.  In the meantime I will change to your code to see what the users think.

**Comment by emveepee** [comment] 2022-10-08 17:03
> ```java
> if (isCtrlCode(ccData1) && ccData1 == 0x0F && ODD_PARITY_BYTE_TABLE[ccByte2]) {
>   // The checksum has invalid parity, so we just ignore it (but don't clear the existing
>   // subtitle data).
>   continue;
> }
> ```

I tried this  change and it doesn't clear the screen on silence the way it should.

**Comment by icbaker** [comment] 2022-10-14 17:30
Ah - my suggestion has a typo, sorry! It should have a `!` here (edited):

```
&& !ODD_PARITY_BYTE_TABLE[ccByte2]
```

However, even with that change I still see the same behaviour you describe - the subtitles aren't cleared correctly.

Looking more closely at the stream it seems to have 4 checksum packets sent at the end of each subtitle line. The checksum is always 15. The first two packets have valid parity bits, the third one doesn't, and the fourth one does.

I tried reshuffling the code to ignore XDS packets (including all checksums) earlier (by moving this block above the validity check):
```
maybeUpdateIsInCaptionService(ccData1, ccData2);
if (!isInCaptionService) {
  // Only the Captioning service is supported. Drop all other bytes.
  continue;
}
```

It has the same symptoms for me with the stream you provided: The subtitles are not cleared when the person stops talking. I need to work out what the 'clear subtitles' signal is meant to be with this stream, and why we end up ignoring it (or maybe it's not present?).

**Comment by icbaker** [comment] 2022-10-19 16:59
> I need to work out what the 'clear subtitles' signal is meant to be with this stream, and why we end up ignoring it (or maybe it's not present?).

I looked into this further. It seems when selecting field 1 with the provided stream we receive many more 'erase displayed memory' commands (`0x2C`) compared to when field 2 is selected. With field 2 selected this erase command only arrives immediately before the next subtitle is due to be shown, hence the screen is not cleared. At this point, I suspect this is a problem with this stream, and I don't plan to spend any more time looking into it. I plan to send a fix for the `0x14` vs `0x15` problem (discussed above), but nothing else discussed in this thread.

**Comment by icbaker** [comment] 2022-11-01 17:09
I'm closing this beause, as above, i believe the remaining issues here are related to this stream. If you have some more insights about other concrete bugs in exoplayer please comment here and I can re-open it, or file a new issue.

**Closed as completed by icbaker** 2022-11-01 17:09 UTC
Labels: bug
