### ISSUE TITLE
Setting a start and end range dynamically 

### ISSUE THREAD

**Issue by sergexte** [google/ExoPlayer#5538] opened 2019-02-20 04:00 UTC
I have a UI that has two sliders which represent the start and end time of a segment of a video. The start and end time are set so that the video loops over the selected segment. 
To implement this I tried doing making a Clipping source wrapped in a LoopingMediaSource. It works well when loaded the first time but the sliders on the UI are meant to be changed to loop the video in a dynamically set range. I have a callback every time the start or end times change where I stop the player, build the media source giving a ClippingMediaSource the new start and end times and wrap it in a LoopingMediaSource and then calling player.prepare() with the new source. However I can't make the experience be smooth since the callback is called as the slider is being moved. Each time I am stopping the player and calling prepare on it.  Is there any recommended way of doing this?

**Comment by tonihei** [comment] 2019-02-26 11:38
Duplicate of #3163

**Comment by tonihei** [comment] 2019-02-26 11:39
We are working on supporting this feature and it should be part of the upcoming 2.10 release.

**Closed as completed by tonihei** 2019-02-26 11:38 UTC
Labels: duplicate
