### ISSUE TITLE
Failed to resolve: com.google.android.exoplayer:exoplayer-core:2.6.0

### ISSUE THREAD

**Issue by kambizira** [google/ExoPlayer#5227] opened 2018-12-10 04:20 UTC
Hello. when i want to add this library to my project , these messages are shown:
```
Failed to resolve: com.google.android.exoplayer:exoplayer-core:2.6.0
Install Repository and sync project
Open File
Show in Project Structure dialog


Failed to resolve: com.google.android.exoplayer:exoplayer-dash:2.6.0
Install Repository and sync project
Open File
Show in Project Structure dialog
```
I use this line to add ExoPlayer to my project:

`implementation 'com.google.android.exoplayer:exoplayer:2.6.0'`

why these errors are shown? I am not able to sync my project. Thanks.

**Comment by vinayagasundar** [comment] 2018-12-10 04:25
Duplicate of #5225
@kambizira Please check it there

**Comment by sharoonck** [comment] 2018-12-10 05:31
in build.gradle  (project:projectname)
add this


allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://google.bintray.com/exoplayer/'
        }
    }
}


this solv my problem

**Comment by ojw28** [comment] 2018-12-10 08:47
Duplicate of #5225

**Closed as completed by ojw28** 2018-12-10 08:47 UTC
