### ISSUE TITLE
TtmlSubtitle\SubtitleOutputBuffer throws ArrayIndexOutOfBoundsException when trying to play video with subtitles

### ISSUE THREAD

**Issue by DzmitrySlutskiy** [google/ExoPlayer#10934] opened 2023-01-19 12:20 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Samsung SM-T970 (but this issue is not device specific and testing team was able to reproduce it with various devices)

### Reproducible in the demo app?

No

### Reproduction steps

Start playback with enabled subtitles - in some cases player falls to error with errorCode = 1000
This issue is not reproducible with ExoPlayer 2.18.1 and looks like it was introduced in this commit https://github.com/google/ExoPlayer/commit/1bc316dee121502ac5d5e33994cd796fa2427256

### Expected result

Playback with subs is ok 

### Actual result

ExoPlayer reports issue ExoPlaybackException with ERROR_CODE_UNSPECIFIED = 1000 (from EventLogger):

playerFailed [eventTime=2.28, mediaPos=46.00, window=0, period=0, errorCode=ERROR_CODE_UNSPECIFIED
          com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:621)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.os.HandlerThread.run(HandlerThread.java:67)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
    at com.google.android.exoplayer2.text.ttml.TtmlSubtitle.getEventTime(TtmlSubtitle.java:62)
    at com.google.android.exoplayer2.text.SubtitleOutputBuffer.getEventTime(SubtitleOutputBuffer.java:53)
    at com.google.android.exoplayer2.text.TextRenderer.getCurrentEventTimeUs(TextRenderer.java:426)
    at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:259)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
    at android.os.Handler.dispatchMessage(Handler.java:102) #
    at android.os.Looper.loopOnce(Looper.java:226) 
    at android.os.Looper.loop(Looper.java:313) 
    at android.os.HandlerThread.run(HandlerThread.java:67)

### Media

Unfortunately I'm not able to provide media as well as bugreport from customer devices because of DRM protection and it is strongly forbidden to share it.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2023-01-19 14:08
Duplicate of https://github.com/google/ExoPlayer/issues/10867

**Closed as completed by icbaker** 2023-01-19 14:08 UTC
Labels: duplicate
