### ISSUE TITLE
Most of the time ima ad first frame show and skip to content.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#3684] opened 2018-01-09 07:46 UTC
I am using Exoplayer version 2.6.1.
i noticed most of the time ima ad show first frame and then it skip to the content.

**Comment by andrewlewis** [comment] 2018-01-09 08:07
Please provide steps to reproduce the issue, especially the ad tag you're trying to play. Thanks.

**Comment by giladna** [comment] 2018-01-09 10:30
@ZohaibGhafoor 
did you run it on different device?
verify it also with different vendor and see if reproduced.
From what I know IMA SDK has issue with playing ad breaks which located in same offset (like preroll+ bumber)
it might behave differently from device/OS version

**Comment by ZohaibGhafoor** [comment] 2018-01-09 10:37
@giladna 
I am using it on Samsung s8, and using preroll adTag from dfp, didn't test any other device for now. even sometimes ad also miss and content run.

**Comment by ZohaibGhafoor** [comment] 2018-01-09 10:40
in VideoPlayerActivity where i can catch Ad Exception if there is any Ad Exception ?

**Comment by ojw28** [comment] 2018-02-26 17:53
Closing because the issue does not contain any clear reproduction steps, which means there's nothing actionable that we can do here. If you're able to provide such steps then please do so here, and we'll reopen the issue. Also note that 2.7.0 included a whole bunch of fixes for ExoPlayer's IMA integration, so it's worth trying to upgrade to see if the issue is fixed.

**Closed as completed by ojw28** 2018-02-26 17:53 UTC
Labels: need more info
