### ISSUE TITLE
How to combine dash segments(.m4s) to form a playable .mp4 video chunk? Which class/methods are responsible? Any examples

### ISSUE THREAD

**Issue by GaureeshA** [google/ExoPlayer#5940] opened 2019-05-24 09:51 UTC
### [REQUIRED] Searched documentation and issues
Looked up online both in GitHub/exoplayer issues and other articles. But no clear information is provided?

### [REQUIRED] Question
Where exactly do I get access to dash segments(.m4s)? It is even alright if we can access the .mp4 video chunks which are got by combining .m4s segments with init.mp4

**Comment by erdemguven** [comment] 2019-05-28 19:38
ExoPlayer doesn't support this.

**Comment by GaureeshA** [comment] 2019-05-29 10:51
On my last question @ojw28 had replied the following, 
"Depending on whether "super resolution" is performed on compressed or decompressed samples, you should take a look at the the components under DashMediaPeriod or MediaCodecVideoRenderer respectively."
Can you please explain what he means by compressed or decompressed samples?

**Comment by ojw28** [comment] 2019-05-29 15:36
If you want to ask a question about a comment on a particular issue, please could you ask it on the same issue rather than somewhere unrelated? Thanks.

**Comment by GaureeshA** [comment] 2019-05-29 17:24
Sure @ojw28, but the last issue was closed immediately. So could not reply there.
Anyway, your reply about compressed vs decompressed was very helpful. Thanks a lot.

**Comment by ojw28** [comment] 2019-05-29 17:29
There is nothing stopping you from replying on a closed issue (unless it's been subsequently locked, but we don't tend to do that unless an issue has been untouched for a relatively long period of time)

**Comment by GaureeshA** [comment] 2019-05-31 09:32
We are most probably looking for the compressed samples(i.e. along with container). As you mentioned about "DashMediaPeriod", where can I find the bytes of the compressed sample so that I can save it locally and make some changes to it. I can find the class called "Chunk", but how do I access the bytes? Thanks again.

**Comment by ojw28** [comment] 2019-06-03 09:37
Duplicate of https://github.com/google/ExoPlayer/issues/5913

**Closed as completed** 2019-06-03 09:36 UTC
Labels: duplicate, question
