### ISSUE TITLE
Minix Neo U1: SampleQueue$AllocationNode Memory Leak

### ISSUE THREAD

**Issue by mareiski** [google/ExoPlayer#7461] opened 2020-06-03 13:58 UTC
### [REQUIRED] Issue description
We want to loop a video file for at least 2 months. Everything works fine, but after 1 to 10 hours the video is frozen and we get an out of memory error. This is just happening on android 5.1, on android 6.0 it works fine. We are using a 4k video file, but its also not working with normal videos (but it takes more time till the error occures). I also made a heap dump which shows that SampleQueue$AllocationNode takes a lot memory. This is also increasing till the app gets killed.

![memoryLeak](https://user-images.githubusercontent.com/37186788/83643938-f74bf980-a5b0-11ea-87fc-d853656ca09c.PNG)

### [REQUIRED] Reproduction steps
Play a 4k video file with LoopingMediaSource for 1 to 10 hours long on android 5.1.

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
We are using the android tv box minix neo u1 with android 5.1

**Comment by andrewlewis** [comment] 2020-06-04 10:03
Unfortunately I don't have access to a device running Android 5.1 at the moment so can't try to reproduce this. Without access to the stream you are trying to play I can't check if it's playable on the emulator. Before we investigate further, please try to reproduce this using the ExoPlayer demo app (modified to loop indefinitely) using the latest release.

If there is a bug in ExoPlayer causing a memory leak, it seems strange it doesn't reproduce on Android 6.

**Comment by mareiski** [comment] 2020-06-05 12:38
Ok installed the demo app successfully and set the repeat mode to all. I will let write you if something happens.

I also don't know why it's working on android 6. The apps are the exactly the same.

**Comment by mareiski** [comment] 2020-06-07 11:57
It happened again with the demo app. But just with our own video. I will send it to if this is ok. The time on the timeline is still ticking but the video is frozen. According to the timeline i played the track for about 15 hours. I will try to reproduce the bug with your demo videos.

**Comment by andrewlewis** [comment] 2020-06-08 09:21
Marking as needs more info for testing with a sample in the demo app.

**Comment by mareiski** [comment] 2020-06-08 10:16
In the demo app, i set the repeat mode to all. After this I added our video to the media-exolist. I downloaded the video in the app and started it. After 15 hours of playing the video was frozen (it is not playing anymore). But the timer in the left bottom corner of the timeline is still ticking and showed 15 hours. Usually it resets when the video is finished and starts again. 
I hope this helps to reproduce the error.

**Comment by andrewlewis** [comment] 2020-06-08 10:51
The provided stream won't play on the emulator I have (at API version 22) unfortunately. Do you see the same problem looping one of the provided sample streams in the demo app? Does it occur if you don't download the video but instead just stream it (by tapping the sample name, not the down arrow)?

**Comment by andrewlewis** [comment] 2020-06-08 11:23
Please could you also share a link to the captured heap dump screenshotted in the original post?

**Comment by mareiski** [comment] 2020-06-08 11:32
No there is no problem with the samples, but is any of these streams a 4k video?
Yes it occurs even if i stream it. I sent you a mail with the hprof file.

**Comment by mareiski** [comment] 2020-06-10 12:10
Have you received the heap dump? Is there any update?

**Comment by ojw28** [comment] 2020-06-12 12:02
Hi @mareiski - I have an Android 5.1 device, so I can try and reproduce this. That said, if it's specific to the individual device, it might not be possible. I do have a couple of questions:

1. We don't see any evidence of a memory leak in the heap dump. When did you capture it? Note that it would be necessary to capture it as the playback gets close to running out of memory in order to capture the leak.
1. Could you also try and capture a bug report (with `adb bugreport`) shortly after reproducing the problem in the demo app, so that we can see the logging around where the failure occurs. From the information provided it's somewhat unclear where the memory leak is coming from. I have another theory that this issue could actually be related to running out of file descriptors, but we'd need a bug report to be able to determine this.

**Comment by ojw28** [comment] 2020-06-14 11:53
I left my device running the video on loop for over 2 days and there's no sign of a memory leak. I think we need the additional information requested above to investigate this further.

**Comment by mareiski** [comment] 2020-06-14 13:12
I captured the heap dump after the video was frozen. I also tried to capture it closer to the out of memory exception but there was an error that there is not enough memory on the device available to capture the heap dump.
I will send you the bug report as soon as possible.

**Comment by mareiski** [comment] 2020-06-16 16:36
Ok it happened again, but I couldn't take a bug report because of this exception:
Failed to get bugreportz version: 'bugreportz -v' returned '/system/bin/sh: bugreportz: not found' (code 0).
If the device does not run Android 7.0 or above, try 'adb bugreport' instead.

I only got a piece of the report in plain text. Any idea how to get the whole report?

**Comment by ojw28** [comment] 2020-06-16 16:58
What command are you using to try and capture the bug report? The suggestion to use `adb bugreport` is interesting, because that's what I'd suggest using to start with. Which suggests you're maybe using some other command?

**Comment by mareiski** [comment] 2020-06-16 18:07
I tried adb bugreport but after this I get the exception above and then the whole report is printed into the terminal. If I use adb bugreport C:\Users\USERNAME\Documents I get the same exception and nothing else happens. I also checked that there is just one device.

**Comment by ojw28** [comment] 2020-06-16 18:10
I think it's normal that the report can be printed to the terminal on older devices. You can just redirect the output into a file (e.g., `adb bugreport > bugreport.txt`).

**Comment by mareiski** [comment] 2020-06-16 18:14
I also tried this, it's the same exception, and no textfile is created

**Comment by ojw28** [comment] 2020-06-16 18:15
If the whole report is printed into the terminal then it must be possible to redirect that into a file one way or another?

**Comment by mareiski** [comment] 2020-06-16 18:16
Unfortunately the output is only printed into the terminal if i use just adb bugreport. If i use adb bugreport > bugreport.txt it doesn't print the report.

**Comment by ojw28** [comment] 2020-06-16 18:19
Hmm. If the output isn't appearing in `bugreport.txt` when you do that, that sounds like a problem with the terminal you're using, doesn't it? Does `command > output-file.txt` output redirection work in general in your terminal? It seems like this is something you'll need to figure out on your side somehow, in order to provide the report.

**Comment by mareiski** [comment] 2020-06-16 18:28
Ah sorry, I found the file. I will take the report if the error occures again

**Comment by mareiski** [comment] 2020-06-19 12:10
Did you receive the report?

**Comment by ojw28** [comment] 2020-06-19 12:48
Yes. I can't really see anything useful in it though, unfortunately.

Can you reproduce this problem on any other device? It's somewhat hard to justify spending a lot of time looking at this, if it's likely to be a device specific problem.

**Comment by mareiski** [comment] 2020-06-19 13:25
Hmm ok no i could not reproduce it yet, but I will check it out again

**Comment by ojw28** [comment] 2020-09-08 21:32
Closing because there's nothing really actionable for us to do here.

**Closed as completed by ojw28** 2020-09-08 21:32 UTC
Labels: bug: device specific
