### ISSUE TITLE
When will video soft decoder be supported

### ISSUE THREAD

**Issue by arlimm318** [google/ExoPlayer#9645] opened 2021-11-03 09:26 UTC
When will video soft decoder  be supported？
for example，soft decoder of H264 。
Is there a plan to support it？

**Comment by icbaker** [comment] 2021-11-03 10:06
I'm not sure I understand what you mean by a 'soft decoder'. If you mean a software decoder, as opposed to a hardware one, then these are already supported in ExoPlayer, either via MediaCodec (which ExoPlayer will use by default, and will select software or hardware decoders depending on what's available on the device) or by bundling software decoder implementations into your app (more info: https://exoplayer.dev/supported-formats.html#sample-formats).

If that doesn't answer your question please can you add more info and context about exactly what you're asking?

**Comment by icbaker** [comment] 2021-11-03 10:37
For video decoders bundled with your application we already support the following extensions:
* VP9: https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9
* AV1: https://github.com/google/ExoPlayer/tree/release-v2/extensions/av1

Other formats will also be supported by adding video support to our [ffmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg), which is tracked by https://github.com/google/ExoPlayer/issues/2159. I believe that should answer your question, so I'm going to close this as a duplicate of #2159.

**Closed as completed by icbaker** 2021-11-03 10:37 UTC
Labels: duplicate
