### ISSUE TITLE
Decoder failed: OMX.amlogic.avc.decoder.awesome2

### ISSUE THREAD

**Issue by nikola5ra** [google/ExoPlayer#8334] opened 2020-12-09 15:00 UTC
We are facing an issue with live stream playback on Google Chromecast device running on Android 10.
On other devices we used for testing everything is working as expected.

- ExoPlayer version number: 2.12.1
- Android version: 10
- Android device: Google Chromecast, Kernel version 4.9.180

A full bug report captured from the device
-------------------------

```
MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640028, 1856404, null, [1920, 1080, 29.97], [-1, -1]), format_supported=YES
Decoder failed: OMX.amlogic.avc.decoder.awesome2
    com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.amlogic.avc.decoder.awesome2
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:872)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2790)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:58)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1774)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:857)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by krocard** [comment] 2020-12-09 17:52
It is hard to help you without more information, most importantly the media being played and a bug report.

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by karamgharam** [comment] 2020-12-10 07:06
i have same issue and this full report this case i think when open too mush video in day  but on Huawei devices

**Comment by nikola5ra** [comment] 2020-12-10 09:03
@krocard I have sent a full bug report on dev.exoplayer@gmail.com and the URL you can use for testing. Thanks!

**Comment by nikola5ra** [comment] 2020-12-10 09:05
@karamgharam In my case, it is happening after the power cycle of the device. Once playback failed if you try to restart playback everything is working fine.

**Comment by karamgharam** [comment] 2020-12-10 09:13
@nikola5ra how can i restart playback ?

**Comment by nikola5ra** [comment] 2020-12-10 10:07
@karamgharam by restart I was meaning to start playback again.

**Comment by nikola5ra** [comment] 2021-06-30 08:59
@krocard any update on this ticket? Thanks.

**Comment by krocard** [comment] 2021-06-30 11:38
The following error is logged before the exception is received by ExoPlayer:
```
12-10 09:31:15.035  1046  3732  3801 E OMXNodeInstance: fillBuffer::storeFenceInMeta(0xf2b7d6c4:amlogic.avc.decoder.awesome2, 0x4 [3110400@0xf2ba2e00 fc=19]) ERROR: ??(0xffffffc2)
12-10 09:31:15.035  1046  3732  3801 W         : Unrecognized status value: -62
12-10 09:31:15.035 10081  6519  6882 W         : Unrecognized status value: -62
12-10 09:31:15.035 10081  6519  6882 E ACodec  : signalError(omxError 0x80001001, internalError -62)
12-10 09:31:15.036 10081  6519  6881 E MediaCodec: Codec reported err 0xffffffc2, actionCode 0, while in state 6
12-10 09:31:15.039 10081  6519  6881 D SurfaceUtils: disconnecting from surface 0xbd47f808, reason disconnectFromSurface
12-10 09:31:15.047 10081  6519  6715 E ExoPlayerImplInternal: Playback error
```

I tried to reproduce on a Pixel 3 XL, but the server returns a 400 error.

This is the same error message as #8557, and can be found on a few other internal bugs.

@christosts could you take a look as this might be a duplicate of #8557 and is an HLS stream.

**Comment by rohitsingh2410** [comment] 2022-01-27 13:30
Any update on this?
`{
error: {
errorException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome2, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1]), 
errorString: Unable to instantiate decoder OMX.amlogic.avc.decoder.awesome2
}
}`

**Comment by christosts** [comment] 2022-01-31 11:09
@rohitsingh2410 these errors are usually specific to the device & content combination and we need more information than just the error itself. I suggest you file a new issue with the information requested on the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) so we can look at it separately.

**Closed as completed** 2022-01-31 11:09 UTC
Labels: bug, bug: device specific
