### ISSUE TITLE
Display video player in textureView

### ISSUE THREAD

**Issue by ttm-hoangcm** [google/ExoPlayer#4712] opened 2018-08-23 04:54 UTC
I'm using ExoPlayer to display a stream video like that:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/mixer_display"
    tools:context=".MainActivity">

    <TextureView
        android:id="@+id/texture_view"
        android:layout_width="298dp"
        android:layout_height="205dp"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:layout_marginStart="37dp"
        android:layout_marginTop="31dp"
        android:focusable="true"
        app:resize_mode="fill"/>

    
        
        
        
        
        
        
        
        

    <TextureView
        android:id="@+id/angle_view1"
        android:layout_width="66dp"
        android:layout_height="48dp"
        android:layout_alignParentStart="true"
        android:layout_alignTop="@+id/angle_view4"
        android:layout_marginStart="24dp"
        android:focusable="true" />

    <TextureView
        android:id="@+id/angle_view2"
        android:layout_width="66dp"
        android:layout_height="48dp"
        android:layout_alignParentStart="true"
        android:layout_alignTop="@+id/angle_view1"
        android:layout_marginStart="110dp"
        android:focusable="true" />

    <TextureView
        android:id="@+id/angle_view3"
        android:layout_width="66dp"
        android:layout_height="48dp"
        android:layout_alignParentStart="true"
        android:layout_alignTop="@+id/angle_view1"
        android:layout_marginStart="196dp"
        android:focusable="true" />

    <TextureView
        android:id="@+id/angle_view4"
        android:layout_width="66dp"
        android:layout_height="48dp"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        android:layout_marginBottom="13dp"
        android:layout_marginEnd="244dp"
        android:focusable="true" />

</RelativeLayout>
MainActivity:

```
public class MainActivity extends AppCompatActivity {

    private static final String TAG = "MainActivity";
    private TextureView simpleExoPlayerView;
    private SimpleExoPlayer player;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

// 1. Create a default TrackSelector
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

// 2. Create a default LoadControl
        LoadControl loadControl = new DefaultLoadControl();

// 3. Create the player
            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
            simpleExoPlayerView = new TextureView(this);
            simpleExoPlayerView = (TextureView) findViewById(R.id.texture_view);

//Set media controller

// Bind the player to the view.
            player.setVideoTextureView(simpleExoPlayerView);
            Uri mp4VideoUri = Uri.parse("http://mediaserver01.heartscreation.co.jp/Dash2/John_Test/John_Test.mpd");
//            simpleExoPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FILL);
            player.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT);

//VIDEO FROM SD CARD: (2 steps. set up file and path, then change videoSource to get the file)
//        String urimp4 = "path/FileName.mp4"; //upload file to device and add path/name.mp4
//        Uri mp4VideoUri = Uri.parse(Environment.getExternalStorageDirectory().getAbsolutePath()+urimp4);

//Measures bandwidth during playback. Can be null if not required.
            DefaultBandwidthMeter bandwidthMeterA = new DefaultBandwidthMeter();
//Produces DataSource instances through which media data is loaded.
            DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "exoplayer2example"), bandwidthMeterA);
            DashChunkSource.Factory dashChunkSourceFactory =
                    new DefaultDashChunkSource.Factory(dataSourceFactory);
//Produces Extractor instances for parsing the media data.
            ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

            MediaSource videoSource = new DashMediaSource(mp4VideoUri, dataSourceFactory, dashChunkSourceFactory, null, null);
            final LoopingMediaSource loopingSource = new LoopingMediaSource(videoSource);

// Prepare the player with the source.
            player.prepare(loopingSource);
            player.addListener(new Player.EventListener() {
//            @Override
//            public void onTimelineChanged(Timeline timeline, Object manifest) {
//                Log.v(TAG, "Listener-onTimelineChanged...");
//            }

                @Override
                public void onTimelineChanged(Timeline timeline, @Nullable Object manifest, int reason) {

                }

                @Override
                public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
                    Log.v(TAG, "Listener-onTracksChanged...");
                }

                @Override
                public void onLoadingChanged(boolean isLoading) {
                    Log.v(TAG, "Listener-onLoadingChanged...isLoading:" + isLoading);
                }

                @Override
                public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                    Log.v(TAG, "Listener-onPlayerStateChanged..." + playbackState);
                }

                @Override
                public void onRepeatModeChanged(int repeatMode) {
                    Log.v(TAG, "Listener-onRepeatModeChanged...");
                }

                @Override
                public void onShuffleModeEnabledChanged(boolean shuffleModeEnabled) {

                }

                @Override
                public void onPlayerError(ExoPlaybackException error) {
                    Log.v(TAG, "Listener-onPlayerError...");
                    player.stop();
                    player.prepare(loopingSource);
                    player.setPlayWhenReady(true);
                }

                @Override
                public void onPositionDiscontinuity(int reason) {

                }
//
//            @Override
//            public void onPositionDiscontinuity() {
//                Log.v(TAG, "Listener-onPositionDiscontinuity...");
//            }

                @Override
                public void onPlaybackParametersChanged(PlaybackParameters playbackParameters) {
                    Log.v(TAG, "Listener-onPlaybackParametersChanged...");
                }

                @Override
                public void onSeekProcessed() {

                }
            });

            player.setPlayWhenReady(true); //run file/link when ready to play.
//        player.setVideoDebugListener(this); //for listening to resolution change and  outputing the resolution
//        }
    }//End of onCreate
```
But when I run app, the video is deviated, it's not fill correct in the view. How to fix it?

**Comment by ojw28** [comment] 2018-08-23 07:13
It's unclear what you expected go happen, and what did happen. Please can you also provide easy to use reproduction steps? In this case probably in the form of a complete project on GitHub that we can just checkout in order to see what you're seeing? We don't have cycles to recreate your app in order to help debug the issue.

**Comment by ttm-hoangcm** [comment] 2018-08-23 07:41
I have a TextureView :
```
<TextureView
        android:id="@+id/texture_view"
        android:layout_width="298dp"
        android:layout_height="205dp"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:layout_marginStart="37dp"
        android:layout_marginTop="31dp"
        android:focusable="true"
        app:resize_mode="fill"/>
```
Then I create ExoPlayer for a stream video and set it into my TextureView :
```
private static final String TAG = "MainActivity";
    private TextureView simpleExoPlayerView;
    private SimpleExoPlayer player;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

// 1. Create a default TrackSelector
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

// 2. Create a default LoadControl
        LoadControl loadControl = new DefaultLoadControl();

// 3. Create the player
            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
            simpleExoPlayerView = new TextureView(this);
            simpleExoPlayerView = (TextureView) findViewById(R.id.texture_view);

//Set media controller

// Bind the player to the view.
            player.setVideoTextureView(simpleExoPlayerView);
            Uri mp4VideoUri = Uri.parse("http://mediaserver01.heartscreation.co.jp/Dash2/John_Test/John_Test.mpd");

//Measures bandwidth during playback. Can be null if not required.
            DefaultBandwidthMeter bandwidthMeterA = new DefaultBandwidthMeter();
//Produces DataSource instances through which media data is loaded.
            DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "exoplayer2example"), bandwidthMeterA);
            DashChunkSource.Factory dashChunkSourceFactory =
                    new DefaultDashChunkSource.Factory(dataSourceFactory);
//Produces Extractor instances for parsing the media data.
            ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

            MediaSource videoSource = new DashMediaSource(mp4VideoUri, dataSourceFactory, dashChunkSourceFactory, null, null);
            final LoopingMediaSource loopingSource = new LoopingMediaSource(videoSource);

// Prepare the player with the source.
            player.prepare(loopingSource);
            player.setPlayWhenReady(true);
```
I expected it will display in TextureView ok, but it's not, here is my result :
[https://ibb.co/dpUWCe](url)
Where I was wrong, and how to fix it? Thanks a lot

**Comment by ojw28** [comment] 2018-08-23 07:46
It's really not possible for us to debug this kind of issue without clearer reproduction steps. For example, I have no idea what's wrong with that screenshot, because I don't know what it's supposed to look like. Even once I understand what's wrong with it, I have no way to easily debug what might be wrong, because I don't have full access to the code and a working project to reproduce the problem.

Please provide a sample GitHub project that reproduces the issue, else we will close this issue. Thanks.

**Closed as completed** 2018-10-15 08:16 UTC
Labels: need more info
