### ISSUE TITLE
How to add Blur effect to ExoPlayer?

### ISSUE THREAD

**Issue by esam00** [google/ExoPlayer#9271] opened 2021-08-09 09:58 UTC
Referring to this [question](https://github.com/google/ExoPlayer/issues/3286) I was wondering if this still the case that ExoPlayer doesn't support such effect? 
Is there any way to achieve this behavior with Exployer ? 
<img width="415" alt="Screen Shot 2021-08-09 at 11 36 01 AM" src="https://user-images.githubusercontent.com/17669557/128688559-99f63cac-8049-4a6e-bfc0-039e96b45700.png">

**Comment by claincly** [comment] 2021-08-09 10:23
I don't think the situation has changed.

**Comment by ojw28** [comment] 2021-08-09 10:38
Closing as a duplicate of https://github.com/google/ExoPlayer/issues/3286 because the advice there is still correct.

**Closed as completed by ojw28** 2021-08-09 10:38 UTC
Labels: duplicate
