### ISSUE TITLE
Unable to start looping playback of videos with shorter audio tracks

### ISSUE THREAD

**Issue by ForgottenUmbrella** [google/ExoPlayer#6909] opened 2020-01-23 15:45 UTC
### Issue description
The start of videos with significantly shorter audio tracks (e.g. 0.13 seconds of audio for a 30 second video) does not play when looping is enabled (`repeatMode` set to `REPEAT_MODE_ONE`), but seeking beyond some point enables playback of the rest of the video. When looping or the audio track are disabled, the entire video plays.
As stated in #1874, this issue is supposed to have already been resolved; it is expected that such a broken video should still start and loop seamlessly, with silence to pad out the short audio track. (Aside: although called "broken", `ffmpeg` reports no errors.)

### Reproduction steps
1. In ExoPlayer demo app PlayerActivity, set the `player_view`'s `repeat_toggle_modes` flag to `none|one`. Install this modified app to your Android device.
1. Download and fire an intent to play the test content.
1. Enable repeat mode and seek to the start of the video to observe observe that the video is in playing state but does not play.
1. Seek forward a bit and observe that rest of video plays fine.
1. Disable repeat mode and seek to start to observe that the video begins playback.
1. Re-enable repeat mode, disable audio track, and seek back to beginning to observe that video plays fine without audio track.

### Link to test content
[First 30 seconds of Big Buck Bunny](https://drive.google.com/file/d/1P_OH8Iby86HQX-Zv-mnd0jmtT_uP_A3l/view?usp=sharing) with audio track replaced with a much shorter one from another broken video (copyright 2008, Blender Foundation / www.bigbuckbunny.org)

### A full bug report captured from the device
[bugreport-crosshatch-QQ1A.200105.002-2020-01-23-22-02-42.zip](https://github.com/google/ExoPlayer/files/4103809/bugreport-crosshatch-QQ1A.200105.002-2020-01-23-22-02-42.zip)

### Version of ExoPlayer being used
2.11.1

### Device(s) and version(s) of Android being used
Google Pixel 3 XL on Android 10
The provided file will always exhibit the behaviour of not starting when `repeatMode` is enabled in an app that uses ExoPlayer (e.g. Google Photos? At least, it can be reproduced in that app regardless of whether or not it uses ExoPlayer).

**Comment by icbaker** [comment] 2020-01-23 16:13
Thanks for the report and test content, I can repro locally.

I don't think this is related to #1874 because that was about getting stuck in `BUFFERING` state whereas the logs I see suggest we're stuck in READY. The last `state` line I see is:
`2020-01-23 16:11:08.988 32519-32519/com.google.android.exoplayer2.demo D/EventLogger: state [eventTime=4.02, mediaPos=0.01, window=0, period=0, true, READY]`

Still looking into the exact cause.

**Comment by icbaker** [comment] 2020-01-23 16:38
This looks like a duplicate of #6459

**Closed as completed by icbaker** 2020-01-23 16:38 UTC
Labels: bug, duplicate

**Comment by ForgottenUmbrella** [comment] 2020-01-25 07:25
Thanks for pointing me in the right direction, and apologies for the duplicate. 
As a workaround, I'd like to programmatically disable the audio track if it is significantly short (<0.15s) by checking its duration, keeping in mind that the video duration is not the same. I see that the `Track` class has a `durationUs` field, but I do not know how to obtain an instance of the appropriate Track. The closest I can get is `mPlayer.getCurrentTrackSelections().get(C.TRACK_TYPE_AUDIO)` but I don't know how to go from `TrackSelection` to `Track`. Any clues?

**Comment by icbaker** [comment] 2020-01-27 11:10
Generally the way to programmatically enable/disable tracks is through a custom `TrackSelector` - either by implementing the interface from scratch or customising a `DefaultTrackSelector` instance.

Unfortunately ExoPlayer has an assumption that all the tracks in the media are the same duration, so the duration of individual tracks isn't exposed to a `TrackSelector` implementation. It's therefore not really possible to enable/disable tracks based on their duration I'm afraid.
