### ISSUE TITLE
throwExceptionIfDeadLineIsReached

### ISSUE THREAD

**Issue by Cvetacar** [google/ExoPlayer#11085] opened 2023-03-27 06:24 UTC
Hello, we have recently updated our application to Exoplayer 2.18.4 and since then, our apps have started crashing with the following exception:

```
java.lang.VerifyError: kotlin/UInt$$ExternalSyntheticBackport0
        at com.google.android.exoplayer2.audio.DefaultAudioSink$PendingExceptionHolder.throwExceptionIfDeadlineIsReached(DefaultAudioSink.java:2259)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:933)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:706)        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1905)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)
```

We ran into this error while doing monkey tests, and I can't seem to replicate this issue by hand, so I am not entirely sure when exactly it occurs. I don't understand why this happens. Do you have any ideas on why this exception occurs and offer any potential fixes? The frequency of these crashes makes them hard to ignore. Thanks in advance.

**Comment by icbaker** [comment] 2023-03-27 08:09
Duplicate of https://github.com/androidx/media/issues/280.

**Closed as completed by icbaker** 2023-03-27 08:09 UTC
Labels: duplicate
