### ISSUE TITLE
UHD is broken in Android phones

### ISSUE THREAD

**Issue by FabriceLor** [google/ExoPlayer#1491] opened 2016-05-01 02:51 UTC
The exoplayer is not working in UHD -- even the demos from the exoplayer themselvesare not working.
UHD feeds dont work in H264 and HEVC. Audio works but video doesnt show up at all.

Tested on a few phones including a Samsung S7 with Android 6.01

The same feeds work in  DashJS or in Microsoft Edge's browser player.

Also having issues with some HD video at 29,97fps that work fine if we make them 25fps.

Tested using video streams in DASH with HEVC or H264, hosted on Akamai with certified workflow...

Note: the same worked 2 months ago using Exoplayer. Conflict with newer Android updates?

**Comment by andrewlewis** [comment] 2016-05-03 07:53
Please provide the information requested in the issue template. We need a link to a specific stream that fails to play. Did you find that none of the sample streams in the demo app played on a Samsung Galaxy S7 running Android 6.0.1?

**Comment by ojw28** [comment] 2016-05-04 14:44
Most likely the devices don't advertise support for the format/resolution/frame-rate combination that you're trying to use, in which case this is working as intended. If you're using DASH you should definitely not be only providing 4K representations. There should be SD and HD representations as well in the same adaptation set. This allows playback to proceed successfully using the subset of representations that are supported by the device.

Note that the UHD samples in the demo app do only include 4K representations, but these are test streams; not an example of what you should actually ship in production to end users.

If you believe there's something else going on, then as above we'll need a link to a specific stream. This is also true if you believe that the device is capable of playing the streams, in which case it's probably a device specific issue where it's under-reporting its own capabilities.

**Comment by ojw28** [comment] 2016-05-04 16:03
For what it's worth, I tried the demo app on an S7 running 6.0.1 and all of the clear UHD samples work fine for me. There's a subtle caching problem that can cause these samples to break if you try and and play the secure UHD samples before the clear ones, which will be fixed shortly, but it's unclear whether that's the problem you're running into.

**Comment by ojw28** [comment] 2016-05-04 17:11
The subtle caching problem was actually fixed already in dev, by 5f016c9df9631838ffb38e959299346870b517cb.

**Comment by ojw28** [comment] 2016-05-12 13:38
Closing because insufficient information was provided. We've fixed one subtle issue related to this, as described above.

**Closed** 2016-05-12 13:37 UTC
Labels: need more info

**Comment by sapanda** [comment] 2016-05-20 19:47
Sorry about the delay on getting you guys the desired info. Been a little swamped off late. 

We were doing a live stream that weekend and the issues @FabriceLor mentioned cropped up. Everything had worked fine 2 weekends prior with the exact same setup. UHD playback wasn't working in both 1.5.4 or 1.5.7. But at least in 1.5.4, we'd get some stuttered frames. In the end we determined that the issue was only occurring on the Samsung Galaxy devices (Note 5, S6, S7) on latest versions of Android 5 and 6. We tried the live streams on a Nexus 6p and things were fine.

I just ran a few more tests on the following devices:
1) Samsung Galaxy S6 w/ Android 6.0.1
2) Huawei Nexus 6p w/ Android 6.0.1

I tried the following sample videos in both ExoPlayer 1.5.7 and 1.5.8. I'm facing issues with the UHD. The HD versions work just fine:

"WV: Clear UHD (MP4,H265)"
- S6: Only audio, No video
- 6p: Doesn't play

"WV: Secure UHD (MP4,H265)"
- S6: Only audio, No video
- 6p: Doesn't play

"WV: Secure UHD (MP4,H264)"
- S6 & 6p: Only audio, No video

"WV: Clear UHD (MP4,H264)"
- S6 plays video fine
- 6p: Only audio, No video

We've generally never had problems with UHD DASH on these devices with ExoPlayer. So I suspect something in the latest version of either the Android OS or ExoPlayer is incompatible with these devices?

Hope that helps!
