### ISSUE TITLE
Drm session Error. Response code: 500

### ISSUE THREAD

**Issue by andreyburmistrov** [google/ExoPlayer#10948] opened 2023-01-27 12:37 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

STB rockchip 3229 running Android 5.1

### Devices that do not reproduce the issue

STB s905w2 running Android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

Hello! STB rockchip 3229 running Android 5.1 has Widevine L3.
Drm info app show me the following information:

CleakKey CDM
Vendor: Google
Version: 1.0

Widevine CDM

Vendor: Google
Version: 1.0
Max HDCP Level Supported: Unprotected
Current HDCP Level: Unprotected
System ID: 4445
Security Level: L3

I want to play protected dash video:

```json
{
"license_server":"https://api.amediateka.tech/drm-wrapper/proxy/wv/?pX=CF83A2",
"src":"https://s91084.cdn.ngenix.net/streamer/ver2/dash/widevine/df60ae0c-4b61-44ab-8a9f-561d801d2e34/x264/auto/aac-all/manifest.mpd?t=1674821406&h=ma%2F0EvolPExEYw%2Fpza+w0A==
}
```

with next code:

```java
MediaItem.Builder mediaItemBuilder = new MediaItem.Builder( );
mediaItemBuilder.setUri( Uri.parse( src ) );
mediaItemBuilder.setDrmLicenseUri( Uri.parse( licenseServer ) );
mediaItemBuilder.setDrmUuid( Util.getDrmUuid( "widevine" ) );
exoplayer.setMediaItem( mediaItemBuilder.build( ) );
```
but playback crashes.

In exoplayer demo app same error, but other test dash video works correctly.

On other STB device s905w2 Android 11 video plays correctly.

Drm Info:
ClearKey CDM

Vendor: Google
Version: 1.2
Max DHCP Level Supported: No digital output
Current HDCP Level: None

Widevine CDM

Vendor: Google
Version: 16.0.0
Max HDCP Level Supported: None
Current HDCP Level: None
System ID: 8158
Security Level: L3
Max Number of Sessions: 15
OEM Crypto Api Version 15

### Expected result

The media plays succesfully

### Actual result

Playback crashes with the following stacktrace:
```
I/WVCdm   (  178): CdmEngine::OpenSession
I/WVCdm   (  178): Level3 Library Dec 11 2014 16:13:16
W/WVCdm   (  178): Could not read /data/mediadrm/IDM1000/ay64.dat2: No such file or directory
W/WVCdm   (  178): Could not load liboemcrypto.so. Falling Back to L3.  dlopen failed: library "liboemcrypto.so" not found
I/WVCdm   (  178): CdmEngine::QueryKeyControlInfo
W/WVCdm   (  178): BufferReader::Read<T> : Failure during parse: Not enough bytes (4)
W/WVCdm   (  178): CdmEngine::ExtractWidevinePssh: Unable to read PSSH atom size
W/WVCdm   (  178): BufferReader::Read<T> : Failure during parse: Not enough bytes (4)
W/WVCdm   (  178): CdmEngine::ExtractWidevinePssh: Unable to read PSSH atom size
I/WVCdm   (  178): CdmEngine::GenerateKeyRequest
D/WVCdm   (  178): PrepareKeyRequest: nonce=387651927
```

```
E/DefaultDrmSession( 3676): DRM session error
E/DefaultDrmSession( 3676):   com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:200)
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:159)
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:623)
E/DefaultDrmSession( 3676):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/DefaultDrmSession( 3676):       at android.os.Looper.loop(Looper.java:135)
E/DefaultDrmSession( 3676):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/DefaultDrmSession( 3676):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:404)
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:79)
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:73)
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:183)
E/DefaultDrmSession( 3676):       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:183)
E/DefaultDrmSession( 3676):       ... 5 more
E/ExoPlayerImplInternal( 3676): Playback error
E/ExoPlayerImplInternal( 3676):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:586)
E/ExoPlayerImplInternal( 3676):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 3676):       at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal( 3676):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 3676):   Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:544)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:534)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:497)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:61)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:584)
E/ExoPlayerImplInternal( 3676):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 3676):       ... 2 more
E/ExoPlayerImplInternal( 3676):   Caused by: com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:200)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:159)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.drm.DefaultDrmSession$RequestHandler.handleMessage(DefaultDrmSession.java:623)
E/ExoPlayerImplInternal( 3676):       ... 3 more
E/ExoPlayerImplInternal( 3676):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:404)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:79)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:73)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:183)
E/ExoPlayerImplInternal( 3676):       at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:183)
E/ExoPlayerImplInternal( 3676):       ... 5 more
```

### Media

```
{
"license_server":"https://api.amediateka.tech/drm-wrapper/proxy/wv/?pX=CF83A2",
"src":"https://s91084.cdn.ngenix.net/streamer/ver2/dash/widevine/df60ae0c-4b61-44ab-8a9f-561d801d2e34/x264/auto/aac-all/manifest.mpd?t=1674821406&h=ma%2F0EvolPExEYw%2Fpza+w0A==
}
```

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment] 2023-01-27 15:47
That's an HTTP 500 which is hard to fix on the client side. Seems like the player tries to get the license but then the server isn't happy about it?

When I include your media in the demo app and I try to play, I get an HTTP 403 as I'm for some reason not authorized. However, it looks that needs fixing on the server side or something with URIs isn't right.

I don't think we are able to help you with this. With the information available it doesn't look like a problem with the library.

**Comment by andreyburmistrov** [comment] 2023-02-03 10:26
Thank's marcbaechinger! I have another question.. I think, ```HttpMediaDrmCallback::executePost``` uses method result ```ExoMediaDrm::getKeyRequest``` to set ```httpBody```. Is it correct to say that the native part of implementation of the method ```ExoMediaDrm::getKeyRequest``` is hidden inside vendor widevine libraries? And is it possible that the problem is that incorrect / incomplete information about the device is sent to the license server? This idea arose because on another device the license server returns 200 and request differs just in ```httpBody```..

**Comment by marcbaechinger** [comment] 2023-02-03 10:34
I'm assigning to @icbaker who is the best person to answer this.

**Comment by icbaker** [comment] 2023-02-03 15:44
> Is it correct to say that the native part of implementation of the method `ExoMediaDrm::getKeyRequest` is hidden inside vendor widevine libraries?

To be precise: `FrameworkMediaDrm` (the default implementation of `ExoMediaDrm` which will be used if you haven't customised this) calls the framework [`MediaDrm.getKeyRequest`](https://developer.android.com/reference/android/media/MediaDrm#getKeyRequest(byte[],%20byte[],%20java.lang.String,%20int,%20java.util.HashMap%3Cjava.lang.String,%20java.lang.String%3E)) method. The actual implementation below that is not really known to ExoPlayer - but yes it likely goes into Widevine code. 

> And is it possible that the problem is that incorrect / incomplete information about the device is sent to the license server?

@marcbaechinger is correct in the initial comment: In order to know why you're getting HTTP 500 errors you need to talk to the owners of the license server. The key request could be valid, but the server could have any arbitrary logic (e.g.  not giving keys out to a particular family of devices for certain content) such that it's basically impossible for us to usefully speculate about the cause of the 500 error. Or the key request could be invalid as you say.

The key request bytes are intended to be opaque, I wouldn't spend much effort trying to decode or validate them yourself - find out from the license server exactly why it's rejecting these requests.

**Comment by icbaker** [comment] 2023-04-24 17:04
Closing due to inactivity

**Closed as completed by icbaker** 2023-04-24 17:04 UTC
Labels: question
