### ISSUE TITLE
How to change the quality gradually?

### ISSUE THREAD

**Issue by opgj123** [google/ExoPlayer#10250] opened 2022-05-10 04:31 UTC
I implemented a method of manually changing the track by referring to the demo app.
However, if you change the track, it will pause and play again after the quality has changed.
I want it to change gradually when I change the quality like YouTube.
This is the code I applied.

```
val trackSelector = simpleExoPlayer.trackSelector
                val mappedTrackInfo = (trackSelector as MappingTrackSelector).currentMappedTrackInfo
                val parameters = (trackSelector as DefaultTrackSelector).parameters
                val builder = parameters.buildUpon()
                if (mappedTrackInfo != null) {
                    for (rendererIndex in 0 until mappedTrackInfo.rendererCount) {
                        val trackType = mappedTrackInfo.getRendererType(rendererIndex)
                        if (trackType == C.TRACK_TYPE_VIDEO) {
                            builder.clearSelectionOverrides(rendererIndex).setRendererDisabled(rendererIndex, false)
                            val trackGroupArray = mappedTrackInfo.getTrackGroups(rendererIndex)
                            val tracks = intArrayOf(trackGroupArray.get(0).length - 1)
                            val override = DefaultTrackSelector.SelectionOverride(0, tracks, 0)
                            builder.setSelectionOverride(rendererIndex, mappedTrackInfo.getTrackGroups(rendererIndex), override)
                        }
                    }
                    trackSelector.setParameters(builder)
                }
```

using another method
A quick transition was made using the canSelectFormat method, but the Player goes to the buffering -> ready state, pauses for a while, and then plays.
when the track is changed I wish the picture quality would change naturally without stopping like on YouTube.

**Comment by tonihei** [comment] 2022-05-13 15:21
This is a duplicate of the enhancement tracked by https://github.com/google/ExoPlayer/issues/2250. 

You can work around this yourself by overriding `AdaptiveTrackSelection` to load your designated format next (see https://github.com/google/ExoPlayer/issues/6630#issuecomment-1023007702 for an example). Note that this means the format change only happens after everything that is already buffered in the old format has been played out. if you wish to speed this up, you also need to modify the logic in `AdaptiveTrackSelection.evaluateQueueSize` to drop already buffered data if required.

**Closed as completed by tonihei** 2022-05-13 15:21 UTC
Labels: duplicate
