### ISSUE TITLE
Detect STATE_ENDED for each track that are in ConcatenatingMediaSource

### ISSUE THREAD

**Issue by mtariquekhan** [google/ExoPlayer#5920] opened 2019-05-21 06:48 UTC
I have created a list of tracks using ConcatenatingMediaSource. The track list is playing perfectly but whenever one track gets finished I am not able to get STATE_END event. Although It gets called when all tracks that are in the list gets played completely.
Is it intended behavior? If yes then what is the alternative to listen to the end state whenever each track gets played completely.

**Comment by tonihei** [comment] 2019-05-21 11:58
That's basically a duplicate of #4728 or #4898.

If you try to detect STATE_ENDED for each track for analytics purposes, please note that we'll also provide a helper class in one of our next releases which allows you to track the state of each playlist item in a playlist independent of the other items. For example, each playlist item will get it's own ENDED state to simplify analytics tasks. I'll keep this issue open as an an enhancement until that's fully implemented.

**Comment by prakashblaster** [comment] 2019-09-06 05:51
Can you show me the code for playlist creation please.. mtariquekhan

**Comment by tonihei** [comment] 2019-09-20 10:30
`PlaybackStatsListener` will be part of the next major release to track analytics events for all playlist items separately.

**Closed as completed by tonihei** 2019-09-20 10:30 UTC
Labels: enhancement
