### ISSUE TITLE
Green bar in top of the video in a Galaxy S3

### ISSUE THREAD

**Issue by ssaguiar** [google/ExoPlayer#1507] opened 2016-05-06 20:04 UTC
I am developing an application for iptv and am using vlc sdk to play videos.
I am starting to change vlc to exoplayer because it's lighter and play content better in low end phones.

I am playing with the exoplayer demo application, so I can study it, before porting it to my app.

The problem I am facing is because when I play a stream, in the upper side of the video there is a small green bar, the size of the width of the video.
The video plays fine.

This seems to be caused by the hardware acceleration (we had this problem before, with other player, and it was solved disabling hardware acceleration for some devices).

Another problem is that the subtitles are not recognized (are allways 'unknown' for all streams that have subtitles).

Can you help with some clues about some solution for these problems, if possible?

Thank you very much.

Sergio

**Comment by ssaguiar** [comment] 2016-05-09 13:25
Just to complement my question, my phone is a Samsung Galaxy S3 9GT-I9300, Android 4.3 original from Samsung.

This is the picture of what is happening:

![hard](https://cloud.githubusercontent.com/assets/5515284/15114424/4e866192-15d0-11e6-85d0-7744402ee258.png)

**Comment by ojw28** [comment] 2016-05-17 16:04
Without providing test content that reproduces this issue, we can't debug it. Please link to test content here, or email it to `dev.exoplayer@gmail.com`. Thanks.

**Comment by ojw28** [comment] 2016-08-10 19:26
Closing due to lack of required information.

**Closed by ojw28** 2016-08-10 19:26 UTC
Labels: need more info
