### ISSUE TITLE
ArrayIndexOutOfBoundsException on playback of a HLS stream

### ISSUE THREAD

**Issue by rini-m** [google/ExoPlayer#1695] opened 2016-07-25 11:42 UTC
```
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-2
    at java.util.ArrayList.get(ArrayList.java:310)
    at java.util.Collections$UnmodifiableList.get(Collections.java:1054)
    at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:441)
    at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:712)
    at com.google.android.exoplayer.hls.HlsSampleSource.onLoadCompleted(HlsSampleSource.java:438)
    at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.os.HandlerThread.run(HandlerThread.java:61)
    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Exoplayer version used- r1.5.8. 
Playback starts, buffer for few seconds and then app crashes with this error. This is 100% reproducible in all available devices, trying to play same content.

**Comment by AquilesCanta** [comment] 2016-07-25 16:19
As stated in the ISSUE_TEMPLATE, please provide a link to the media that causes the error. Otherwise it is practically impossible for us to know the cause. You can send it to dev.exoplayer@gmail.com, if you would rather not post it here. Don't forget to include the issue number.

**Comment by AquilesCanta** [comment] 2016-08-11 16:39
Closing due to lack of requested information.

**Comment by londhenamdev** [comment] 2016-08-24 07:16
Hello AquilesCanta,
I have the same issue as above.  I am trying to play this media (http://origin.tcmsdemo.com/94BF6635-FEF4-4702-8800-C3830A353949.m3u8) using exoplayer in android. It plays for 2 seconds and then app is crasing with same error as above.

**Comment by AquilesCanta** [comment] 2016-08-25 15:59
@londhenamdev What version are you using? Is it possible that you are using an old one? I cannot reproduce it and I am inclined to think the issue is the lack of alignment of the segments (which is not a problem in version 1.5.10, I think). Please, try updating exoplayer and if the problem persists, open a new bug, providing all the information required in the issue template.

**Closed as completed by AquilesCanta** 2016-08-25 15:59 UTC
Labels: need more info
