### ISSUE TITLE
Error when playing H.264 video

### ISSUE THREAD

**Issue by ogawa-ma** [google/ExoPlayer#10610] opened 2022-09-13 06:24 UTC
■ Question
I'm publishing an app that uses ExoPlayer, but some users are experiencing errors and cannot play videos.
Format is H.264, The playback method is Widevine DASH streaming playback.
Can you tell the cause from the logs?

ExoPlayer version used：2.16.1
Device：Google Pixel4XL, Google Pixel5
Android version：13

![スクリーンショット 2022-09-13 15 11 53](https://user-images.githubusercontent.com/54785318/189823888-3fd350db-aa3f-48a5-a548-9dbd7b3fb46e.png)

**Comment by rohitjoins** [comment] 2022-09-14 17:21
Duplicate of #10621

**Closed as not planned by rohitjoins** 2022-09-14 17:21 UTC
Labels: duplicate
