### ISSUE TITLE
Setting BackBuffer to LoadControl as 10 minutes, breaks buffering.  "Playback stuck buffering and not loading" is thrown

### ISSUE THREAD

**Issue by AlienAsRoger** [google/ExoPlayer#8378] opened 2020-12-19 16:09 UTC
## Steps to reproduce

1. Modify ExoPlayer Demo project for `PlayerActivity`
```
      int minBufferMs = (int) TimeUnit.SECONDS.toMillis(900);
      int maxBufferMs = (int) TimeUnit.SECONDS.toMillis(1000);
      int bufferForPlaybackMs = DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS;
      int bufferAfterResumeMs = DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS;

      DefaultLoadControl loadControl = new DefaultLoadControl.Builder()
          .setBufferDurationsMs(minBufferMs, maxBufferMs, bufferForPlaybackMs, bufferAfterResumeMs)
          .setBackBuffer((int) TimeUnit.MINUTES.toMillis(10), false) // I tried with true flag, but it's the same
          .build();

      player =
          new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
              .setMediaSourceFactory(mediaSourceFactory)
              .setLoadControl(loadControl)
              .setTrackSelector(trackSelector)
              .build();
```

2. Add podcast mp3 files:
```
      {
        "name": "TuneIn Today explained podcast, MP3",
        "uri": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/chtbl.com/track/524GE/traffic.megaphone.fm/VMP7089786295.mp3"
      },
      {
        "name": "TuneIn Today explained podcast, MP3",
        "uri": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/chtbl.com/track/524GE/traffic.megaphone.fm/VMP1541465457.mp3"
      },
```

I think any podcast would be reproducible, but this is what we've used.

3. Start playback of those files and notice how buffering proceeds. Buffering stops at about half of the podcast and when player reaches this time it not longer proceed
4. Note: Also check with variable speed, like x 2.0

![device-2020-12-19-075726](https://user-images.githubusercontent.com/465875/102693673-2e8e9a80-41d1-11eb-858c-f4d011327672.png)

In our app we are also getting this exception `Playback stuck buffering and not loading`

additional logs from our application:
```
2020-12-14 07:17:26.273 11401-11401/tunein.player D/ExoAnalyticsListener: onMetadata() called with: eventTime = [com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime@811344ef], metadata = [entries=[ICY: title="Randy Granger - The Dog Star", url="null", rawMetadata.length="43"]]
2020-12-14 07:20:40.449 11401-11401/tunein.player D/ExoAnalyticsListener: onIsLoadingChanged() called with: eventTime = [com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime@669fb32f], isLoading = [false]
2020-12-14 07:21:01.985 11401-22267/tunein.player I/chatty: uid=10632(tunein.player) ExoPlayer:Playb identical 5 lines
2020-12-14 07:21:02.025 11401-22267/tunein.player I/chatty: uid=10632(tunein.player) ExoPlayer:Playb identical 1 line
2020-12-14 07:21:02.078 11401-22267/tunein.player E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:956)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2020-12-14 07:21:02.094 11401-11401/tunein.player D/ExoMediaSourceEventListener: onLoadCanceled() called with: windowIndex = [0], mediaPeriodId = [com.google.android.exoplayer2.source.MediaSource$MediaPeriodId@17a8e5f4], loadEventInfo = [com.google.android.exoplayer2.source.LoadEventInfo@9884317], mediaLoadData = [com.google.android.exoplayer2.source.MediaLoadData@e3fc304]
2020-12-14 07:21:02.094 11401-11401/tunein.player D/ExoMediaSourceEventListener: onLoadCanceled() called with: windowIndex = [0], mediaPeriodId = [com.google.android.exoplayer2.source.MediaSource$MediaPeriodId@17a8e5f4], loadEventInfo = [com.google.android.exoplayer2.source.LoadEventInfo@9884317], mediaLoadData = [com.google.android.exoplayer2.source.MediaLoadData@e3fc304]
2020-12-14 07:21:02.095 11401-11401/tunein.player D/ExoAnalyticsListener: onLoadCanceled() called with: eventTime = [com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime@138922cc], loadEventInfo = [com.google.android.exoplayer2.source.LoadEventInfo@9884317], mediaLoadData = [com.google.android.exoplayer2.source.MediaLoadData@e3fc304]
2020-12-14 07:21:02.101 11401-11401/tunein.player D/ExoAnalyticsListener: onBandwidthEstimate() called with: eventTime = [com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime@c18b3aa5], totalLoadTimeMs = [568952], totalBytesLoaded = [13636239], bitrateEstimate = [191738]
2020-12-14 07:21:02.110 11401-11401/tunein.player D/ExoAnalyticsListener: onPlayerError() called with: eventTime = [com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime@5820337d], error = [com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error]
2020-12-14 07:21:02.112 11401-11401/tunein.player D/ExoPlayerStateListener: onPlayerError() call error onError Unknown message = Playback stuck buffering and not loading
2020-12-14 07:21:02.115 1003-1008/? E/statsd: Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->10632[I] (10)0x30000->ExoPlayer:WakeLockManager[S] 
2020-12-14 07:21:02.159 11401-11401/tunein.player I/ExoPlayerImpl: Release b3f95d3 [ExoPlayerLib/2.12.2] [blueline, Pixel 3, Google, 30] [goog.exo.core, goog.exo.okhttp, goog.exo.ui, goog.exo.ima]
2020-12-14 07:21:02.217 11401-11401/tunein.player D/ExoAnalyticsListener: onTimelineChanged() called with: eventTime = [com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime@c60b9014], reason = [0]
2020-12-14 07:21:02.217 11401-11401/tunein.player D/ExoAnalyticsListener: onTracksChanged() called with: eventTime = [com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime@c60b9014], trackGroups = [com.google.android.exoplayer2.source.TrackGroupArray@1], trackSelections = [com.google.android.exoplayer2.trackselection.TrackSelectionArray@1b4daae]
```

- ExoPlayer version number = 2.12.2
- previous ExoPlayer version = 2.11.8
- Android version = 11
- Android device = Pixel 3

## Current workaround

do not set back buffer

**Comment by tonihei** [comment] 2020-12-21 09:29
This is mostly working as intended. The reason is that a 10min back buffer will require large amounts of memory and the `DefaultLoadControl` stops loading further media once an upper memory limit is reached. That's why your playback is stuck and the error is thrown.

There are multiple ways to work around this problem for your particular case:
 - Reduce/Remove the back buffer and replace it by a `CacheDataSource`. This writes the data to disk and thus doesn't use up memory during playback.
 - Increase the allowed memory limit in `DefaultLoadControl` by calling `Builder.setTargetBufferBytes` or by overwriting the `calculateTargetBufferBytes` method if you want to have more flexibility to set the limit based on the selected tracks.
 - Set `DefaultLoadControl.Builder.setPrioritizeTimeOverSizeThresholds(true)` to prioritize time constraints over memory constraints. This essentially means that the configured `minBufferMs` takes priority over the memory limit and the player will always buffer to `minBufferMs` even if the memory limit is already reached. Note that this method may allow arbitrarily large memory usage if the `minBufferMs` is large and you configure a back buffer of 10 min. This may not be a problem if you control the media and you know the maximum possible bitrate.

**Comment by tonihei** [comment] 2021-01-04 11:48
Closing as I assume the question was answered.

**Closed as completed by tonihei** 2021-01-04 11:48 UTC
Labels: wont fix: intended behavior
