### ISSUE TITLE
Video content not playing

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#5848] opened 2019-05-08 06:02 UTC
I am getting the following error when play content from a provided url.

```
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(1/4, null, null, audio/mpeg-L2, null, -1, null, [-1, -1, -1.0], [2, 48000])
```

I am using a forked version of the exoplayer library version 2.9.0.

I have seen a issues related to this that we can solve this using ffmpeg extension of exoplayer.Can pls guide me through this

Can u provide me an email so that i can provide you an url.Cannot post it publicly due to privacy issues

**Comment by marcbaechinger** [comment] 2019-05-08 16:52
Please email the link to dev.exoplayer@gmail.com using a subject in the format "Issue #5848".

Regarding the 'forked version of ExoPlayer 2.9.0' I'd recommend to first try playing the content with the demo app of the most recent version which is currently 2.10 to make sure the issue is not caused by the fork.

**Comment by ojw28** [comment] 2019-05-14 11:44
Closing due to lack of required information.

**Closed as completed by ojw28** 2019-05-14 11:44 UTC
Labels: need more info
