### ISSUE TITLE
java.io.FileNotFoundException: /jacoco.exec when starting demo app

### ISSUE THREAD

**Issue by dpolyakova** [google/ExoPlayer#7696] opened 2020-07-29 20:05 UTC
### [REQUIRED] Searched documentation and issues
No documentation mentioning jacoco.

### [REQUIRED] Question
After compileSdkVersion was switched to 29 we started seeing jacocoInit exception when running debug flavor of any demo application. 
```
07-29 12:50:21.792 23937 23937 W System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
07-29 12:50:21.794 23937 23937 W System.err:    at java.io.FileOutputStream.open0(Native Method)
07-29 12:50:21.795 23937 23937 W System.err:    at java.io.FileOutputStream.open(FileOutputStream.java:308)
07-29 12:50:21.795 23937 23937 W System.err:    at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
07-29 12:50:21.796 23937 23937 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
07-29 12:50:21.796 23937 23937 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
07-29 12:50:21.796 23937 23937 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
07-29 12:50:21.797 23937 23937 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
07-29 12:50:21.797 23937 23937 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
07-29 12:50:21.797 23937 23937 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.Offline.getProbes(Offline.java:51)
07-29 12:50:21.797 23937 23937 W System.err:    at com.google.android.exoplayer2.offline.DefaultDownloadIndex.$jacocoInit(Unknown Source:13)
07-29 12:50:21.798 23937 23937 W System.err:    at com.google.android.exoplayer2.offline.DefaultDownloadIndex.<clinit>(Unknown Source:0)
07-29 12:50:21.798 23937 23937 W System.err:    at com.google.android.exoplayer2.demo.DemoUtil.ensureDownloadManagerInitialized(DemoUtil.java:138)
07-29 12:50:21.798 23937 23937 W System.err:    at com.google.android.exoplayer2.demo.DemoUtil.getDownloadTracker(DemoUtil.java:121)
07-29 12:50:21.799 23937 23937 W System.err:    at com.google.android.exoplayer2.demo.SampleChooserActivity.onCreate(SampleChooserActivity.java:117)
07-29 12:50:21.800 23937 23937 W System.err:    at android.app.Activity.performCreate(Activity.java:7144)
07-29 12:50:21.800 23937 23937 W System.err:    at android.app.Activity.performCreate(Activity.java:7135)
07-29 12:50:21.800 23937 23937 W System.err:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
07-29 12:50:21.801 23937 23937 W System.err:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
07-29 12:50:21.801 23937 23937 W System.err:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
07-29 12:50:21.801 23937 23937 W System.err:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
07-29 12:50:21.801 23937 23937 W System.err:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
07-29 12:50:21.801 23937 23937 W System.err:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
07-29 12:50:21.802  3203 21578 I WVCdm   : [cdm_engine.cpp(484):QueryStatus] CdmEngine::QueryStatus
07-29 12:50:21.802 23937 23937 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
07-29 12:50:21.803  3203 21578 I WVCdm   : [cdm_engine.cpp(484):QueryStatus] CdmEngine::QueryStatus
07-29 12:50:21.804 23937 23937 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
07-29 12:50:21.804 23937 23937 W System.err:    at android.os.Looper.loop(Looper.java:193)
07-29 12:50:21.804 23937 23937 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6718)
07-29 12:50:21.805 23937 23937 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-29 12:50:21.805 23937 23937 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-29 12:50:21.806 23937 23937 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
 ```

The issue and solution is already documented here: https://github.com/jacoco/jacoco/issues/968 
I've checked that placing jacoco-agent.properties file in library-core fixes the problem. Can we get this fix, please?

Reproduced in version: dev-v2 commit 1ed5d8b

**Comment by tonihei** [comment] 2020-07-31 14:24
I haven't seen this problem before with our demo app builds on the dev-v2 branch. Is there anything special about your build setup that is needed to reproduce the problem? Or are you building and running the ExoPlayer demo app as it is? It would also be good to know if it's related to Android Studio/build tools version and the like.

**Comment by dpolyakova** [comment] 2020-07-31 22:33
In this particular case I built the demo using gradle command on Linux workstation:
` ./gradlew demo:assembleNoDecoderExtensions`
The SDK installed on that machine is:
```
~/Android/Sdk/tools/bin$ ./sdkmanager --version
26.1.1
```
But I also see same exception with other demos built in IntelliJ Idea on Windows. And other engineers in our team see same issue as well.

The platform I'm reproducing this on is Evolution Digital/Amino Android TV box running Android P.
```
[ro.com.google.gmsversion]: [Android_9_Pie]
[ro.build.version.min_supported_target_sdk]: [17]
[ro.build.version.sdk]: [28]
```

**Comment by tonihei** [comment] 2020-08-03 11:19
I tried the steps below, but everything works fine.

On a Linux workstation:
 1. `git clone https://github.com/google/ExoPlayer.git` + `git checkout dev-v2`
 2. Install Android Studio 4.0 and download Android SDK 29 and open project once so that `local.properties` file is generated
 3. `cd ExoPlayer` and `./gradlew demo:assembleNoDecoderExtensions`
 4. `cd demos/main/buildout/outputs/apk/noDecoderExtensions/debug` and `adb install demo-noDecoderExtensions-debug.apk`
 5. Open app on phone (Pixel 4, Android R beta build) and try to play a sample.

If you can reproduce the problem, could you provide similar steps that would allow us to reproduce what is happening too?  Ideally, we would not need to add some configuration file for an unrelated library and it seems preferable to understand where the problem is coming from.

**Comment by dpolyakova** [comment] 2020-08-04 04:41
I tried running same demo app on my GalaxyS10 which is Android O, SDK 29 and I don't see jacoco exception there. So the difference must be in the Java runtime environment between the O and P. Our streamer devices are all Android P, and 32 bit only - armeabi-v7a .

**Comment by tonihei** [comment] 2020-08-04 08:48
> I tried running same demo app on my GalaxyS10 which is Android O, SDK 29 and I don't see jacoco exception there. So the difference must be in the Java runtime environment between the O and P. Our streamer devices are all Android P, and 32 bit only - armeabi-v7a .

I think something got messed up in this comment. Android O is SDK 26, Android P is SDK 28 and Android 10 is SDK 29. 
Could you provide the reproduction steps in the same style as above so that we can reproduce the problem? For this kind of build setup issue, it's best to start from scratch so that no previous config or customization can influence the result.

**Comment by menscikov** [comment] 2020-08-04 09:11
I have the same warning (W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)) for about 1 year on any physical or virtual device.

It's appearing only once after application start. To repeat this warning i have to close the app and start again.

**Comment by tonihei** [comment] 2020-08-04 09:20
@menscikov So this is just a warning without any influence on the app behaviour?

**Comment by menscikov** [comment] 2020-08-04 09:30
> @menscikov So this is just a warning without any influence on the app behaviour?

For me, yes. I also tried to fix this warning in the same way as written in 1 post, but it didn't work.
Would be great, if it will be fixed sometime.

**Comment by tonihei** [comment] 2020-08-04 09:39
If I understand jacoco/jacoco#968 correctly, this issue is working as intended from Jacoco side and they would advise the Android Gradle plugin maintainers to fix their setup. This is tracked by https://issuetracker.google.com/151471144 already. 

Nothing of this actually relates to ExoPlayer as far as I can see and the warning doesn't influence app behaviour and I would consider it to be log spam that hopefully gets fixed by the Android Gradle plugin in a future version. Given that, I'll close this issue because there is nothing actionable for us.

**Closed as completed by tonihei** 2020-08-04 09:39 UTC
Labels: wont fix: infeasible
