### ISSUE TITLE
IndexOutOfBoundsException while doing com.google.android.exoplayer2.source.SampleDataQueue.readData(SampleDataQueue.java:309)

### ISSUE THREAD

**Issue by dwc18** [google/ExoPlayer#7580] opened 2020-07-02 18:42 UTC
### [REQUIRED] Issue description

During testing of the code which discards samples in HLS streams when upshifting to a higher resolution stream, I've been able to reliably reproduce the following crash:

2020-06-24 11:48:18.931 22859-22859/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=1324.15, mediaPos=557.73, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:493)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.IndexOutOfBoundsException: off=-1129, len=7157 out of bounds (size=65536)
        at java.nio.Buffer.checkBounds(Buffer.java:587)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:285)
        at com.google.android.exoplayer2.source.SampleDataQueue.readData(SampleDataQueue.java:309)
        at com.google.android.exoplayer2.source.SampleDataQueue.readToBuffer(SampleDataQueue.java:147)
        at com.google.android.exoplayer2.source.SampleQueue.read(SampleQueue.java:345)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.readData(HlsSampleStreamWrapper.java:563)
        at com.google.android.exoplayer2.source.hls.HlsSampleStream.readData(HlsSampleStream.java:79)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:354)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1286)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:835)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:815)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:404)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

This appears to be the same crash which was encountered and mentioned by smayhew in the pull request which pulled the code in:  https://github.com/google/ExoPlayer/pull/7244 

smayhew's comment: https://github.com/google/ExoPlayer/pull/7244#issuecomment-620119891

I will include more detailed information on the reproduction in the reproduction steps, but in short this is reproduced using the demo app with one slight modification and running against a live stream.  

### [REQUIRED] Reproduction steps

Environment:
  - client device: TiVo Stream 4k 
  - wireless connection is intentionally set to be close to the threshold for the stream.  In this particular case, the stream (a live stream) has 6Mbps, 4Mbps and 2Mbps variants and the access point is limiting the connection to 10Mbps
  - CODE CHANGE:  in part because this stream uses the same resolution, and also because we'd like to eventually have the discard be evaluated for every shift to a higher bitrate (not just higher resolution) I disabled the checks for resolution and only evaluate bitrate when determining whether to discard samples.  i.e., in AdaptiveTrackSelection.java:

    // If the chunks contain video, discard from the first SD chunk beyond
    // minDurationToRetainAfterDiscardUs whose resolution and bitrate are both lower than the ideal
    // track.
    for (int i = 0; i < queueSize; i++) {
      MediaChunk chunk = queue.get(i);
      Format format = chunk.trackFormat;
      long mediaDurationBeforeThisChunkUs = chunk.startTimeUs - playbackPositionUs;
      long playoutDurationBeforeThisChunkUs =
          Util.getPlayoutDurationForMediaDuration(mediaDurationBeforeThisChunkUs, playbackSpeed);
      if (playoutDurationBeforeThisChunkUs >= minDurationToRetainAfterDiscardUs
          && format.bitrate < idealFormat.bitrate
         /* && format.height != Format.NO_VALUE && format.height < 720
          && format.width != Format.NO_VALUE && format.width < 1280
          && format.height < idealFormat.height*/) {

With the above setup, I typically encounter the error within 5-10 minutes.

### [REQUIRED] Link to test content
At the moment we are unable to make our video feed public.  We are working on ways to address this.

### [REQUIRED] A full bug report captured from the device
I will capture the bug report and email it.

### [REQUIRED] Version of ExoPlayer being used
branch of dev-v2 at: commit dac3dde7bb8d79e785f65b0c0c7b7425f41dffa6 (dev-v2)

### [REQUIRED] Device(s) and version(s) of Android being used
Primary device used for reproduction and testing is a Tivo Stream 4K running android: 
dwc$ adb shell getprop ro.build.version.release 
9
dwc$ adb shell getprop ro.build.version.sdk
28

I've also reproduced on an RCN device, but it is more difficult because it's ethernet-only and it's more difficult for me to bandwidth limit for this device.

As mentioned in the reproduction section, with the setup specified I can reproduce the problem within 5-10 minutes when playing at the live point.

**Comment by tonihei** [comment] 2020-07-03 07:47
Thanks for the detailed report. I believe this essentially a duplicate of #7549 and the problem was caused by a bug in #7244 that is already fixed on the dev-v2 branch by https://github.com/google/ExoPlayer/commit/7bc5fa855f774ce198e23a455fec751b7743486f.

**Closed as completed by tonihei** 2020-07-03 07:47 UTC
Labels: bug, duplicate
