### ISSUE TITLE
Implementation of midroll ads

### ISSUE THREAD

**Issue by vinayjoglekar** [google/ExoPlayer#3694] opened 2018-01-11 11:25 UTC
Hello Team, is there any example/tutorial available to implement mid roll ads using exoplayer IMA extension? I have successfully added preroll ads. Here is my code: 

```
contentMediaSource = new ExtractorMediaSource.Factory(mediaDataSourceFactory).createMediaSource(Uri.parse(contentUrl), null, null);
mediaSourceWithAds = new AdsMediaSource(contentMediaSource,this,adsLoader,simpleExoPlayerView.getOverlayFrameLayout(),null,null);
player.seekTo(contentPosition);
player.prepare(mediaSourceWithAds);
player.setPlayWhenReady(true);
```
Thanks!

**Comment by andrewlewis** [comment] 2018-01-11 12:17
Midrolls should be played automatically (exactly like prerolls) if you provide a VMAP ad tag that has midrolls to your `adsLoader`.

**Comment by vinayjoglekar** [comment] 2018-01-11 13:37
Thanks for the answer @andrewlewis . Appreciate it! Does it work in similar way in case of VAST template?

**Comment by andrewlewis** [comment] 2018-01-11 13:57
VAST ad tags don't specify a location for the ad, and currently we always play them as prerolls. I can mark this as an enhancement if you are interested in having the ability to specify where a VAST ad plays in the content, but we don't currently plan to implement this soon.

**Comment by giladna** [comment] 2018-01-11 19:58
@andrewlewis 

this can be done in the current ExoPlayer via this format:
in case you have a vast you want to use in midroll just build such VAMP

      String vmap = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
              "<vmap:VMAP xmlns:vmap=\"http://www.iab.net/videosuite/vmap\" version=\"1.0\">\n" +
              " <vmap:AdBreak timeOffset=\"00:00:15.000\" breakType=\"linear\" breakId=\"midroll-1\">\n" +
              "  <vmap:AdSource id=\"midroll-1-ad-1\" allowMultipleAds=\"false\" followRedirects=\"true\">\n" +
              "   <vmap:AdTagURI templateType=\"vast3\"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>\n" +
              "  </vmap:AdSource>\n" +
              " </vmap:AdBreak>\n" +
              "</vmap:VMAP>";

    ImaAdsLoader.Builder builder = new ImaAdsLoader.Builder(context);
    adsLoader = builder.setImaSdkSettings(new ImaSdkSettings()).buildForAdsResponse(vmap);

Gilad

**Comment by giladna** [comment] 2018-01-11 20:58
@andrewlewis 

Another thing I have noticed that should be taken with the IMA SDK team is that for some reason IMA error is not accurate enough I get Error that node in `vmap:AdSource` is not acceptable in IMA parser 
the issue here is that the the AdTagURI is not  having prefix of vmap:AdTagURI

```
  String vmap = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
          "<vmap:VMAP xmlns:vmap=\"http://www.iab.net/videosuite/vmap\" version=\"1.0\">\n" +
          " <vmap:AdBreak timeOffset=\"00:00:15.000\" breakType=\"linear\" breakId=\"midroll-1\">\n" +
          "  <vmap:AdSource id=\"midroll-1-ad-1\" allowMultipleAds=\"false\" followRedirects=\"true\">\n" +
          "   <AdTagURI templateType=\"vast3\"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6256&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&url=&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></AdTagURI>\n" +
          "  </vmap:AdSource>\n" +
          " </vmap:AdBreak>\n" +
          "</vmap:VMAP>";
 

See Exception: 
Caused by: AdError [errorType: LOAD, errorCode: AdErrorCode [name: UNKNOWN_AD_RESPONSE, number: 1010], message: VMAP unsupported node in <vmap:AdBreak>: vmap:AdSource]

01-11 23:03:12.083 30500-30508/com.google.android.exoplayer2.imademo I/zygote64: Increasing code cache capacity to 256KB
01-11 23:03:12.141 30500-30500/com.google.android.exoplayer2.imademo W/chromium: [WARNING:render_frame_host_impl.cc(2646)] OnDidStopLoading was called twice.
01-11 23:03:12.151 30500-30574/com.google.android.exoplayer2.imademo W/AdsMediaSource: Ad load error
                                                                                       java.io.IOException: Ad error: com.google.obf.gk@fcc1726
                                                                                           at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.maybeNotifyAdError(ImaAdsLoader.java:795)
                                                                                           at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.onAdError(ImaAdsLoader.java:532)
                                                                                           at com.google.obf.he.a(IMASDK:8)
                                                                                           at com.google.obf.gp$1.a(IMASDK:28)
                                                                                           at com.google.obf.hj.d(IMASDK:143)
                                                                                           at com.google.obf.hj.a(IMASDK:47)
                                                                                           at com.google.obf.hk.b(IMASDK:39)
                                                                                           at com.google.obf.hk$1.shouldOverrideUrlLoading(IMASDK:4)
                                                                                           at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
                                                                                           at com.android.webview.chromium.Ap.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:74)
                                                                                           at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15)
                                                                                           at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160)
                                                                                           at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                                           at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                        Caused by: AdError [errorType: LOAD, errorCode: AdErrorCode [name: UNKNOWN_AD_RESPONSE, number: 1010], message: VMAP unsupported node in <vmap:AdBreak>: vmap:AdSource]
                                                                                           at com.google.obf.gp$1.a(IMASDK:27)
                                                                                           at com.google.obf.hj.d(IMASDK:143) 
                                                                                           at com.google.obf.hj.a(IMASDK:47) 
                                                                                           at com.google.obf.hk.b(IMASDK:39) 
                                                                                           at com.google.obf.hk$1.shouldOverrideUrlLoading(IMASDK:4) 
                                                                                           at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77) 
                                                                                           at com.android.webview.chromium.Ap.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:74) 
                                                                                           at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15) 
                                                                                           at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160) 
                                                                                           at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method) 
                                                                                           at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                           at android.os.Looper.loop(Looper.java:164) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
01-11 23:03:12.153 30500-30500/com.google.android.exoplayer2.imademo W/chromium: [WARNING:render_frame_host_impl.cc(2646)] OnDidStopLoading was called twice.
01-11 23:03:12.321 22919-17913/? I/Icing: Indexing 12FB00B293EA29FC0B0030812D82935604985490 from com.google.android.gms


Gilad.

**Comment by andrewlewis** [comment] 2018-02-14 14:42
@giladna For this kind of suggestion it's best to ask in the IMA forum: https://groups.google.com/forum/#!forum/ima-sdk. Thanks!

Closing for now as there doesn't appear to be much demand for setting the position for VAST ads, and there's a workaround above.

**Closed as completed by andrewlewis** 2018-02-14 14:42 UTC
Labels: question
