### ISSUE TITLE
IMA shouldOverrideUrlLoading NPEs

### ISSUE THREAD

**Issue by dbrain** [google/ExoPlayer#8447] opened 2021-01-12 00:43 UTC
## Issue description

We are seeing a lot of NullPointerException's in Firebase coming from IMA in our latest release, containing ExoPlayer 2.12.0 and IMA 3.21.4 (Note: ExoPlayer specifies 3.21.0, so we've bumped it slightly).

GIven it's IMA and obfuscated it's hard to work out exactly what is going wrong from our perspective. It seems like at some point the WebView is triggering a URL load, which is causing IMA to call into components it thinks should not be null, but are at that point.

I'm guessing it's some kind of lifecycle thing, maybe ExoPlayer has detached when this event occurs or hasn't attached yet. Hoping someone who has worked with the IMA code could shed some light / point me in the right direction.

## Reproduction steps
I have been so far unable to reproduce this, or find a specific flow making it happen.

## Link to test content
Not content specific.

## Stacktraces
Note, the actual crashes have repeats of this due to the way WebViews are implemented across devices.

### Crash 1
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.google.ads.interactivemedia.v3.api.StreamRequest.getUserRequestContext()' on a null object reference
       at com.google.ads.interactivemedia.v3.internal.amr.c(IMASDK:3)
       at com.google.ads.interactivemedia.v3.internal.aog.d(IMASDK:66)
       at com.google.ads.interactivemedia.v3.internal.aom.d(IMASDK:5)
       at com.google.ads.interactivemedia.v3.internal.aoj.shouldOverrideUrlLoading(IMASDK:2)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-428010123:17)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:165)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

### Crash 2
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.ads.interactivemedia.v3.internal.and.g()' on a null object reference
       at com.google.ads.interactivemedia.v3.internal.amr.a(IMASDK:2)
       at com.google.ads.interactivemedia.v3.internal.aog.d(IMASDK:71)
       at com.google.ads.interactivemedia.v3.internal.aom.d(IMASDK:5)
       at com.google.ads.interactivemedia.v3.internal.aoj.shouldOverrideUrlLoading(IMASDK:2)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-428014120:17)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:183)
       at android.app.ActivityThread.main(ActivityThread.java:7258)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

## Version of ExoPlayer being used
2.12.0 with IMA 3.21.4

## Device(s) and version(s) of Android being used
Device and OS independent

**Comment by andrewlewis** [comment] 2021-01-12 09:03
The mention of `StreamRequest.getUserRequestContext()` suggests that the use case is server-side ad insertion/DAI. Could you confirm whether that's expected?

If so I think this needs to be investigated by the IMA SDK team, so you could post a description of the problem [here](https://groups.google.com/g/ima-sdk).

**Comment by dbrain** [comment] 2021-01-12 09:09
@andrewlewis Sorry, I should have clarified in the description. We do not use DAI, just plain old IMA via VAST/VMAP.

Given the IMA SDK is trying to hit a null `StreamRequest`, maybe it's some backup flow? Hard to tell with the obfuscated IMA code.

**Comment by andrewlewis** [comment] 2021-01-12 09:19
I've asked the IMA SDK team to take a look in [internal: b/177294971] and will plan to keep this issue updated if we learn more. Thanks.

**Comment by andrewlewis** [comment] 2021-01-13 09:26
There's a fix for the `NullPointerException` which will hopefully go into the next IMA SDK release (I'd guess this will be 3.22.1 as it just missed the 3.22.0 release -- here's [the repository](https://maven.google.com/web/index.html?q=interactive#com.google.ads.interactivemedia.v3:interactivemedia)). Although this will fix the NPE, without details about how the error was triggered, it's hard to say what the root cause could be. With the fix, it's possible that a more informative error will be propagated to allow diagnosing what's going on.

**Comment by dbrain** [comment] 2021-01-13 22:49
Great, thanks @andrewlewis. I will update this issue when we've had a chance to roll out after the next IMA release.

**Comment by dbrain** [comment] 2021-01-13 23:55
Sorry, @andrewlewis, one thing I forgot to ask. Will it be safe to update IMA without waiting for an ExoPlayer release? Specially will ExoPlayer 2.12.2 support 3.22.0 (and 3.22.1, assuming minor fixes) without changes?

**Comment by andrewlewis** [comment] 2021-01-14 10:54
Forcing the later version should be fine (I think there won't be any API incompatibilities, so it should only require the gradle change). I'd probably do a bit of manual testing anyway just to be safe.

**Comment by fpitters** [comment] 2021-03-02 09:34
@andrewlewis do you know if this was included into 3.22.2?

I can't see anything on the changelog (https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/history)

**Comment by andrewlewis** [comment] 2021-03-09 19:01
Sorry for the delay. The fix for the stack trace with `getUserRequestContext` is in 2.22 ("Fixes the error message when AdsLoader would receive an error without a valid session ID.").

Looking at the internal issue, I don't think the second crash has been diagnosed yet. I also added a note there about the crash reported in https://groups.google.com/g/ima-sdk/c/BvHHkeXvhL4, which appears to have a similar cause (missing session ID).

**Comment by andrewlewis** [comment] 2021-03-10 11:03
For crash 2, please could you provide an updated stack trace from a client using IMA SDK version 2.22? Thanks for the help tracking this down.

**Comment by fpitters** [comment] 2021-03-10 12:08
Thank you for keeping track of this.

This is a report from Firebase using 3.22.2 with latest Exo 2.13.2.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'com.google.ads.interactivemedia.v3.api.player.ContentProgressProvider com.google.ads.interactivemedia.v3.api.AdsRequest.getContentProgressProvider()' on a null object reference
       at com.google.ads.interactivemedia.v3.internal.cw.a(cw.java:2)
       at com.google.ads.interactivemedia.v3.internal.em.e(em.java:71)
       at com.google.ads.interactivemedia.v3.internal.es.d(es.java:5)
       at com.google.ads.interactivemedia.v3.internal.ep.shouldOverrideUrlLoading(ep.java:2)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:15)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:181)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by andrewlewis** [comment] 2021-03-15 10:46
A fix has been submitted for this. I'll look out for the next IMA SDK update and hopefully we can get that into the next minor release.

**Comment by priscila225** [comment] 2021-03-15 14:42
Nice @andrewlewis because I'm seeing this a lot on the latest crashlytics reports which are bad for the company I work for

**Comment by AlienAsRoger** [comment] 2021-03-17 18:25
@fpitters looks like IMA SDK team has release a fix for the NPE crash https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/history 
We will try to see if it's fixes our issue in production which is identical to your report.

**Comment by AlienAsRoger** [comment] 2021-03-19 00:19
That update did not resolve the issue, we are still seeing this crash:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at com.google.ads.interactivemedia.v3.internal.ea.a(ea:3)
        at com.google.ads.interactivemedia.v3.internal.dy.doInBackground(dy:2)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by andrewlewis** [comment] 2021-03-19 12:11
@AlienAsRoger This crash looks like it has a different cause to the others based on the stack trace. Did you see an increase in this recently, or was it present on older versions too? The cause appears to be that [BitmapFactory.decodeStream](https://developer.android.com/reference/android/graphics/BitmapFactory#decodeStream(java.io.InputStream)) is returning `null` for the companion ad URL.

**Comment by AlienAsRoger** [comment] 2021-03-22 23:17
> @AlienAsRoger Did you see an increase in this recently, or was it present on older versions too? 

It was present in the old version. I was thinking that they might have fixed 2 issues at once :)

**Closed as completed** 2021-04-01 16:26 UTC
Labels: bug: in dependency

**Comment by atrope** [comment] 2021-05-06 15:22
This is still happening with latest version

```

java.lang.NullPointerException: 
  at com.google.ads.interactivemedia.v3.internal.amy.a (Unknown Source:16)
  at com.google.ads.interactivemedia.v3.internal.aon.d (Unknown Source:1494)
  at com.google.ads.interactivemedia.v3.internal.aot.d (Unknown Source:57)
  at com.google.ads.interactivemedia.v3.internal.aoq.shouldOverrideUrlLoading (Unknown Source:12)
  at android.webkit.WebViewClient.shouldOverrideUrlLoading (WebViewClient.java:77)
  at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading (chromium-Monochrome.aab-stable-443009123:14)
  at android.os.MessageQueue.nativePollOnce (Native Method)
  at android.os.MessageQueue.next (MessageQueue.java:326)
  at android.os.Looper.loop (Looper.java:181)
  at android.app.ActivityThread.main (ActivityThread.java:7091)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)

```

**Comment by tonihei** [comment] 2021-05-11 13:02
@atrope  Which version of ExoPlayer (or other related components like IMA extension) are you using?

**Comment by atrope** [comment] 2021-05-11 13:42
@tonihei we are using ExoPlayer 2.13.3
