### ISSUE TITLE
Green circle on bottom of 360 videos on Xiaomi Phones

### ISSUE THREAD

**Issue by MateusZitelli** [google/ExoPlayer#4872] opened 2018-09-27 00:52 UTC
### Issue description

A green circle is showed on the bottom of **some** 360 videos samples in Xiaomi phones. The problem happens both in the ExoPlayer sample app and my custom 360 video player implementation. However, in the ExoPlayer demo app, if the video is played in the non-360 mode there is no artifacts. I also received multiple reports from users experiencing the same issue.

![device-2018-09-26-174054](https://user-images.githubusercontent.com/201472/46117179-b0d7b200-c1b4-11e8-85fd-556238b1b460.png)

### Reproduction steps
Just play the sample using the 

### Link to test content
https://drive.google.com/file/d/14eyCSSj9sNAM8zGDP-hFaarg8uPB3p-Q/view?usp=sharing

### Version of ExoPlayer being used
v2.8.2 and dev-v2.9.0

### Device(s) and version(s) of Android being used
Redmi Note 4 - Android 7.0
Xiaomi Mi Max - Android 7.0

### A full bug report captured from the device
```
2018-09-26 17:49:37.863 736-14755/? E/OMX-VDEC-1080P: Does not handle dataspace request
2018-09-26 17:49:37.863 736-14755/? E/OMXNodeInstance: getConfig(2e00192:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
2018-09-26 17:49:37.905 10944-10944/com.google.android.exoplayer2.demo D/EventLogger: videoSizeChanged [0.33, 0.18, window=0, period=0, 1920, 960]
2018-09-26 17:49:37.908 10944-10944/com.google.android.exoplayer2.demo D/EventLogger: renderedFirstFrame [0.34, 0.18, window=0, period=0, Surface(name=android.graphics.SurfaceTexture@e7e8f58)/@0x1a008b1]
2018-09-26 17:49:37.946 1506-1672/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{46e49fc u0 com.google.android.exoplayer2.demo/.PlayerActivity t1601} time:10052106
2018-09-26 17:49:37.946 1506-1623/? D/ActivityTrigger: ActivityTrigger activityStopTrigger 
2018-09-26 17:49:37.946 1882-1882/? D/EventBus: [1882, u0] send(AppTransitionFinishedEvent)
2018-09-26 17:49:37.947 1882-1882/? D/EventBus: [1882, u0]  -> ForcedResizableInfoActivityController [0x4fb4a2e, P1] onBusEvent(AppTransitionFinishedEvent)
2018-09-26 17:49:37.947 1882-1882/? D/EventBus: [1882, u0] onBusEvent(AppTransitionFinishedEvent) duration: 26 microseconds, avg: 601
2018-09-26 17:49:37.972 1506-1672/? I/WindowManager: Destroying surface Surface(name=com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.SampleChooserActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2043 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:895 com.android.server.wm.WindowState.destroyOrSaveSurface:2116 com.android.server.wm.AppWindowToken.destroySurfaces:366 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:445 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:178 com.android.server.wm.WindowAnimator.animateLocked:687 
2018-09-26 17:49:37.975 1882-1882/? D/EventBus: [1882, u0] send(AppTransitionFinishedEvent)
2018-09-26 17:49:37.975 1882-1882/? D/EventBus: [1882, u0]  -> ForcedResizableInfoActivityController [0x4fb4a2e, P1] onBusEvent(AppTransitionFinishedEvent)
2018-09-26 17:49:37.975 1882-1882/? D/EventBus: [1882, u0] onBusEvent(AppTransitionFinishedEvent) duration: 26 microseconds, avg: 601
2018-09-26 17:49:37.977 1506-1672/? I/Timeline: Timeline: App_transition_stopped time:10052138
2018-09-26 17:49:37.988 561-561/? W/SurfaceFlinger: couldn't log to binary event log: overflow.
2018-09-26 17:49:38.064 1881-1881/? D/wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
2018-09-26 17:49:38.082 1881-1881/? D/wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=229376 outq=0 send_len=49
2018-09-26 17:49:38.289 747-747/? I/cnss-daemon: RTM_NEWNEIGH message received: 28
2018-09-26 17:49:38.290 747-747/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
```

**Comment by erdemguven** [comment] 2018-09-27 15:33
I couldn't reproduce the issue on a Redmi 5 plus with Android 7.1.2. I'll try to find a Redmi Note 4 or Xiaomi Mi Max.

I wonder if a similar issue occurs in non-360 mode if you set the surface_type to texture_view.

**Comment by MateusZitelli** [comment] 2018-09-27 18:12
The equirectangular video does not present any artifacts when played with surface_type set to texture_view.

**Comment by MateusZitelli** [comment] 2018-10-02 17:56
Checking old users reports the issue was happening as far as ExoPlayer version r2.2.0, therefore it was not introduced recently.

**Comment by MateusZitelli** [comment] 2018-10-08 18:44
The bug is also happening with:
- Moto G (5S) Plus - Android 7.1.1

**Comment by MateusZitelli** [comment] 2018-10-16 23:51
Protruly B10S - The issue happens with Gear 360 videos - Android 7.1.1

**Comment by ojw28** [comment] 2019-10-11 14:29
@MateusZitelli - Is this still an issue for you? If you have a device on which this problem reproduces, I'd suggest you try the following (one by one, not at the same time) in the demo app:

1. Try commenting out [this line](https://github.com/google/ExoPlayer/blob/r2.10.5/library/ui/src/main/java/com/google/android/exoplayer2/ui/spherical/SceneRenderer.java#L131). Please verify that the (now visible) background is grey, not green.
1. Try changing [GlUtil.createExternalTexture](https://github.com/google/ExoPlayer/blob/r2.10.5/library/core/src/main/java/com/google/android/exoplayer2/util/GlUtil.java#L120) to use `GL_NEAREST` instead of `GL_LINEAR` (there are two lines to change). Does that make any difference?

If there are any software updates for the affected device, it would be interesting to see whether they fix the problem.

**Comment by ojw28** [comment] 2021-01-13 10:57
Closing because this sounds like a device specific issue, and it's unlikely we'll be able to dedicate further investigation to it at this stage.

**Closed as completed by ojw28** 2021-01-13 10:57 UTC
Labels: bug: device specific
