### ISSUE TITLE
TTML: Support for styling reference in subtitles file

### ISSUE THREAD

**Issue by masensio** [google/ExoPlayer#7960] opened 2020-09-21 17:04 UTC
**Use case description**
We have a media app which is using Exoplayer as player. It is used to reproduce some streaming videos with subtitles. 
The media chunks are receiving with the `tts:origin` field in `styling` or in `region` region.
We have observed that sometimes the subtitles are shown correctly but other times they disappear.
We were researching about that curious behaviour of the subtitles and discovered Exoplayer doesn´t support styling reference for subtitles. 
However in the the [TTML standard](https://www.w3.org/TR/ttml1/#semantics-style-association-referential) there is no limitation to have the `tts:origin` outside of the `region`.

<img width="1660" alt="subtitles" src="https://user-images.githubusercontent.com/3862330/93797491-9f5b0080-fc3c-11ea-8a7a-960cc3fc0275.png">

We are using `Exoplayer 2.11.7`

I´ve seen you have another issue related with that: https://github.com/google/ExoPlayer/issues/2953. 
Is there any plan follow TTML standard?

**Proposed solution**
Supporting TTML standard in Exoplayer.

**Comment by icbaker** [comment] 2020-09-22 09:16
You're right we don't fully support referential styling - that's tracked in #2953 as you've found.

We don't currently have any plans to work on this, but we'd accept high quality pull requests improving our TTML support. If someone looks at working on this they might need to make some architectural changes to `TtmlDecoder` - I'd be happy to discuss proposals before implementation if that would be helpful.

I'll mark this as a duplicate of #2953.

**Closed as completed by icbaker** 2020-09-22 09:16 UTC
Labels: duplicate
