### ISSUE TITLE
Click event on SimpleExoPlayerView gets propagated trough [Chromebook]

### ISSUE THREAD

**Issue by zarkooroz** [google/ExoPlayer#4091] opened 2018-04-06 11:46 UTC
We are using ExoPlayer in Android app and it works as expected. The issue occurs when app is installed on Chromebook. 
When clicking on video, event is propagated and in our case new video is started. Expected behaviour would be to show video controls as on standard Android devices.

SimpleExoPlayerView holder also has clickable parameter but that does not help either.
Did anyone had similar experience or have some suggestion on how to fix this?

**Comment by ojw28** [comment] 2018-12-18 20:18
Does this still reproduce? It sounds like a bug in ChromeOS support for Android apps, rather than an ExoPlayer bug. It's possible that they've fixed it by now. If not, I think it should probably be reported to the ChromeOS team?

**Comment by ojw28** [comment] 2019-01-23 23:17
Closing due to lack of update. As above, if this still reproduces then I think you should probably report the issue to the ChromeOS team.

**Closed as completed by ojw28** 2019-01-23 23:17 UTC
Labels: question, need more info
