### ISSUE TITLE
The player sometimes gets stuck on buffering state and doesn't return to ready state

### ISSUE THREAD

**Issue by Zo2m4bie** [google/ExoPlayer#1446] opened 2016-04-15 09:01 UTC
Hi. I faced of with issues when the player goes to buffer state and it doesn't go back to ready state again(and I didn't receive any error). I play hls stream and sometimes it just happens, first time I reproduced after playing  0.5h, second time player's working more that 2 hours before going in "forever" buffer state, third time I received  "forever" buffer state after around 5 hours, last time I received it after around 15 mintes watching channel). 
Here some data from lib:
I looked at HlsSampleSource [maybeStartLoading method](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L682), when the player stucks I always return in 

`if (loader.isLoading() || !nextLoader) {
      return;
    }`

because nextLoader always = false
and it's because I received 
currentBufferSize = 20250624
targetBufferSize = 16777216
and [here](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/DefaultLoadControl.java#L190)  it always return false because currentBufferSize was bigger than  targetBufferSize.

Also in HlsSampleSource [readData](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L294) return NOTHING_READ [here](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L348)

I tried it in v.: 1.5.0 and I tried it in v.: 1.5.7 it reproduces here too. I cannot provide link right now, but perheps you can tell me why it may heppen.

**Comment by AquilesCanta** [comment] 2016-04-15 09:10
You can provide the link through dev.exoplayer@gmail.com. After that, let us know here so that we can go look for it.

**Comment by Zo2m4bie** [comment] 2016-04-15 09:59
@AquilesCanta sent

**Comment by AquilesCanta** [comment] 2016-04-15 10:07
I will keep you posted. It may take me some time to work this out, but feel free to ping me if it seems I forgot about it.

**Comment by Zo2m4bie** [comment] 2016-04-15 10:23
@AquilesCanta ok, but 
Is it ok if I will add throwing error(for me to know that I have to restart stream)  [here](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/DefaultLoadControl.java#L190) when currentBufferSize >= targetBufferSize? Because I figured out(maybe it's only for this stream) that when currentBufferSize become >= targetBufferSize I always receive this infinity buffer state(Of course it can be aftermath of real problem)

**Comment by AquilesCanta** [comment] 2016-04-18 11:30
I still haven't been able to reproduce the issue. If you want to work around it, perhaps [#911](https://github.com/google/ExoPlayer/issues/911) will provide some aid, just in case. I will try to reproduce again this week, but if I don't manage to, I will have to close this thread. If you have any extra information that may aid, please provide.

**Comment by AquilesCanta** [comment] 2016-04-20 09:01
I haven't been able to reproduce the issue even after 12+ hours playbacks. Unfortunately, I will have to close this. If you manage to limit the scope of the issue to a certain device or certain circumstances, file a new one. Perhaps the issue was related to some connection/server side problem, but if you say that it does not manage to recover, I can't think of any good diagnosis.

**Closed by AquilesCanta** 2016-04-20 09:01 UTC

**Comment by Zo2m4bie** [comment] 2016-04-22 11:45
@AquilesCanta so far I found that this bug is device specific . This device have many issues with exo player and some of them are very strange like [this](https://github.com/google/ExoPlayer/issues/1411) 
Also if someone faced with the same issue, for me helped restarting player when [currentBufferSize >= targetBufferSize](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/DefaultLoadControl.java#L190)

**Comment by AquilesCanta** [comment] 2016-04-22 11:51
It is a good hint for anyone who encounters the same issue in that device. Unfortunately is not a workaround we can add to the library, considering the specificity of the circumstances under which the problem occurs and that the workaround is not targeting the cause of the problem itself, but rather a symptom. It is unlucky that I do not count with a testing device right now. If you dig up some more information about what the cause is, let me know. Cheers.

**Comment by djdawson3** [comment] 2016-08-10 21:49
Hi,

I'm not sure if this is the correct place to put this, but I've scoured the issues for this project and this seems relevant. Anyways, I've had a similar problem as OP: Sometimes videos aboslutely refuse to play and they get stuck buffering forever. 

I looked at the videos that were having this problem and I noticed that they were all very unoptimized and had a very high bitrate (15mb/s). When this happens, the buffer fills up completely and then it appears to get stuck. I can get this unstuck by increasing the size of our buffer, but that seems less than ideal (I'm currently using the defaults provided in the examples). 

I tried finding this in the code, but I wasn't able to. Can someone either tell me or point me to where I can find how ExoPlayer determines when it has buffered enough to start playing the video? All of these videos are below 30 seconds and they refuse to play unless I've pretty much buffered the entire thing. 

I should note that this doesn't happen with just HLS; in my case, it's happening using just the MediaCodecVideoTrackRenderer

EDIT: After further research, I've found this thread: https://github.com/google/ExoPlayer/issues/1405

Turns out that the issue was with the audio interleaving.
