### ISSUE TITLE
OOM crash while video is looped using LoopingMediaSource

### ISSUE THREAD

**Issue by konaire** [google/ExoPlayer#4517] opened 2018-07-16 08:32 UTC
### Issue description
Experiencing a OOM crash in multiple devices when `MediaSource` is wrapped with `LoopingMediaSource`. Sometimes I got this exception even without looping the video. Application consumes a lot of memory after specific moment while playing the video. Then it crashes with OutOfMemoryException. I was able to reproduce this only with one video file. Maybe this video is corrupted in some way?

### Reproduction steps
Apply following changes to json file in the demo app:
```
{
  "name": "Loop file",
  "uri": "/sdcard/MP-CD1_loop(1).mp4",
  "extension": "mp4"
}
```

And wrap media source with LoopingMediaSource. It will produce exception faster.

**PlayerActivity (lines 410-411)**
```
mediaSource = mediaSources.length == 1 ? new LoopingMediaSource(mediaSources[0]) : new ConcatenatingMediaSource(mediaSources);
```
App works perfectly before 2:14. After this time app starts to consume a lot of memory and will crash with OutOfMemoryException after some delay.

### Link to test content
https://drive.google.com/file/d/1QUD0e1qfDLYVBuLWiHL1VnLCNuoMJBW3/view?usp=sharing

### Version of ExoPlayer being used
v2.8.2

### Device(s) and version(s) of Android being used
Sony Xperia XA1, Android 8.0
Wileyfox Swift, Android 7.1.2

### A full bug report captured from the device
[bugreport-N2G48B-2018-07-16-10-54-50.zip](https://github.com/google/ExoPlayer/files/2196843/bugreport-N2G48B-2018-07-16-10-54-50.zip)

**Comment by tonihei** [comment] 2018-07-23 14:52
I tested you example file and also got an extremely high memory usage, especially around the 2:30 mark.

However, after looking deeper into your file, I'd conclude this is working as intended because this section has very large media samples and the player needs to buffer them according to its buffering policy. The effective bitrate of some of these samples is over 500 Mbps.

Note that the `DefaultLoadControl` has two types of constrains: memory size and buffer length. By default the load control continues to buffer until it reaches a minimum buffer length independent of the used memory. You can set the flag `prioritizeTimeOverSizeThresholds` in the `DefaultLoadControl.Builder` to `false`  to tell the player that it should stop loading as soon as it reaches the maximum buffer size even if the minimum buffer duration is not yet reached.

**Comment by konaire** [comment] 2018-07-24 09:51
Thank you for information. Now my app doesn't crash after changing `DefaultLoadControl`. But video still lags somewhere between 2:26 and 2:34 because of such high bitrate. So I will reconvert the video to fix this behavior.

**Comment by tonihei** [comment] 2018-08-20 10:51
Closing because the question seems to answered. Please reopen if you feel this is not the case.

**Closed as completed by tonihei** 2018-08-20 10:51 UTC
Labels: wont fix: infeasible
