### ISSUE TITLE
Extracting EMSG tags from audio fMP4 HLS segments 

### ISSUE THREAD

**Issue by sruditsky** [google/ExoPlayer#10168] opened 2022-04-09 14:03 UTC
Let's assume we have an HLS stream which has separate streams of video and audio fMP4 segments,
I.e. it has a 
```
#EXT-X-MEDIA:TYPE=AUDIO,URI=
```
with audio media playlist URI 
and
```
#EXT-X-STREAM-INF:
```
with video media playlist URI.

If I understand the code in https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/DefaultHlsExtractorFactory.java#L230
then for such a case there will be two FragmentedMp4Extractor-s created one for video and one for audio.
However, only the video FragmentedMp4Extractor will have FLAG_ENABLE_EMSG_TRACK set.

_The question is how then the EMSG tags present only in the audio segments (e.g. ID3 tags) are getting processed?_

**Comment by icbaker** [comment] 2022-04-11 13:44
Can you please provide a stream we can use to reproduce the issue?

Please either upload it here or send to dev.exoplayer@gmail.com using the subject `Issue #10168`. Please also update this issue to indicate you’ve done this.

**Comment by sruditsky** [comment] 2022-04-11 20:26
@icbaker @christosts 
I provided a sample stream through the specified email.

**Comment by christosts** [comment] 2022-04-12 09:46
Thank you for sending us the sample stream via email. When I try to access it, it returns an HTTP 403 (tried a few different clients). Do I need a specific configuration to access the stream, e.g. specify certain headers or is the URL geo-restricted?

**Comment by sruditsky** [comment] 2022-04-12 17:47
@christosts 
Are you outside US? Then this URL might be not accessible.

I sent another e-mail which contains (attached) a small portion of a steam.
I did verify that this portion of the stream (hosted locally) is playable on the ExoPlayer demo app.
I also verified that audio segments contain ID3 tags, but FragmentedMp4Extractor never gets these tags because audio FragmentedMp4Extractor is constructed without FragmentedMp4Extractor.FLAG_ENABLE_EMSG_TRACK

**Comment by sruditsky** [comment] 2022-04-21 15:10
@christosts 
Is there any progress with this?

**Comment by sruditsky** [comment] 2022-04-23 06:46
@icbaker @christosts 
So, as I mention in the original description the problem is that ExoPlayer creates the audio FragmentedMp4Extractor for HLS without FLAG_ENABLE_EMSG_TRACK flag set. And my understanding of the reason for why this is done this way is that would we create both (audio and video) FragmentedMp4Extractor-s with this flag we would have 2 SampleQueue-s with metadata and would need 2 MetadataRenderer-s to handle them.

We are testing a workaround which does exactly that.
I.e. it
a) modifies https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/DefaultHlsExtractorFactory.java#L233 to always pass FLAG_ENABLE_EMSG_TRACK flag to FragmentedMp4Extractor constructor 
and
b) duplicates this line https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L569 to create the second MetadataRenderer.

This seems to fix this issue.
_Assuming that we only have HLS content do you see any issue with this approach?_

**Comment by icbaker** [comment] 2022-04-25 08:31
Yes this should work - the reason it's very hard for ExoPlayer to do this automatically is that we don't know how many emsg tracks we're going to find in each stream before preparation, and by the time we're preparing we've already constructed all the renderers.

If you always know you're going to have two emsg tracks then constructing two MetadataRenderers to handle them and ensuring they're both selected sounds like a reasonable workaround.

**Comment by sruditsky** [comment] 2022-04-25 14:55
@icbaker 
Thanks for confirmation.

**Comment by christosts** [comment] 2023-02-07 17:45
I'm closing this issue as it seems the initial issue is fixed and we don't have plans to address this in the code.

**Closed as completed by christosts** 2023-02-07 17:45 UTC
Labels: question
