### ISSUE TITLE
Possible memory leak in SampleQueue

### ISSUE THREAD

**Issue by nani0490** [google/ExoPlayer#7870] opened 2020-09-09 00:56 UTC
Hello

We have been using Exoplayer v2.6.1 on an Android 7.1.1 device.
The MediaSource we use is nothing but HLS and when left the stream to play (from customized third party UI) for more than 4 hours or so, the (3rd party) application crashes and sometimes the device runs into OutOfMemomy.

I did refer the previous bugs like  #1855, #1908, #1943, #5151, #6511, #6553, and none of them have solved this.

Like I said, after a few hours, I get OOM and the (3rd party) application eventually crashes.
![image](https://user-images.githubusercontent.com/11717511/92541491-34322700-f257-11ea-8b0a-15e47c1f3a2f.png)

When profiling the application, the "Retained Memory" of the "SampleQueue" object seems to be pretty high (~250MB) as you can see.
![image](https://user-images.githubusercontent.com/11717511/92541648-ae62ab80-f257-11ea-97e9-a3bab1a2c902.png)

It need not be 4 hours every time, sometimes it can be even less, and sometimes it is even more.

Coming to the server setup, the media HLSv4 protocol is used and the server is configured to provide 3 segments of 4-second chunks.

The LoadControl is not over-ridden and uses the default values.

If further information is needed and can be shared, I oblige to do so.

**Comment by AquilesCanta** [comment] 2020-09-09 01:01
Is this a v2.6.1 issue? If so, please try reproducing on a newer version of ExoPlayer. We have fixed some leaks in the past, and 2.6.1 is pretty old.

**Comment by nani0490** [comment] 2020-09-09 06:17
Hello
Thanks for the update.
A lot of things were tied up and so we cannot update to the latest version.
Would it be possible to provide a list of commits or a patch that impacts HLS?

**Comment by AquilesCanta** [comment] 2020-09-09 16:14
Unfortunately it's impossible for us to come up with a comprehensive list for you to try. You could take at the [release notes](https://github.com/google/ExoPlayer/blob/dev-v2/RELEASENOTES.md) in case you find anything that could impact your app.

My advise is that you try to reproduce the leakage using the dev branch and latest release using the demo app plus minimal changes to make it work. If the issue does not reproduce then the underlying cause could be either an old bug or an issue in the app (specially if the player is being heavily customized).

I'll close the issue since there is not much we can do on our side until we can clearly determine this is an existing exoplayer issue. 2.6.1 is almost 3 years old.

**Closed as completed by AquilesCanta** 2020-09-09 16:14 UTC
Labels: wont fix: infeasible
