### ISSUE TITLE
NullPointerException when playing a particular HLS source in r1.3.2

### ISSUE THREAD

**Issue by mingfai** [google/ExoPlayer#481] opened 2015-05-21 23:48 UTC
When playing a HLS that use a URL(with a authentication token in url), RollingSampleBuffer.allocator is null that caused NPE. Not 100% sure but I think that URL did work in r1.2.x / dev stream in the past. 
(edited: i meant to say it DID work)
```
java.lang.NullPointerException: Attempt to invoke interface method 'int com.google.android.exoplayer.upstream.Allocator.getIndividualAllocationLength()' on a null object reference [main]com.google.android.exoplayer.ExoPlaybackException: java.lang.NullPointerException: Attempt to invoke interface method 'int com.google.android.exoplayer.upstream.Allocator.getIndividualAllocationLength()' on a null object reference
 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236) ~[na:0.0]
 	at android.os.Handler.dispatchMessage(Handler.java:98) ~[na:0.0]
 	at android.os.Looper.loop(Looper.java:211) ~[na:0.0]
 	at android.os.HandlerThread.run(HandlerThread.java:61) ~[na:0.0]
 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) ~[na:0.0]
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int com.google.android.exoplayer.upstream.Allocator.getIndividualAllocationLength()' on a null object reference
 	at com.google.android.exoplayer.extractor.RollingSampleBuffer.<init>(RollingSampleBuffer.java:58) ~[na:0.0]
 	at com.google.android.exoplayer.extractor.DefaultTrackOutput.<init>(DefaultTrackOutput.java:48) ~[na:0.0]
 	at com.google.android.exoplayer.hls.HlsExtractorWrapper.track(HlsExtractorWrapper.java:223) ~[na:0.0]
 	at com.google.android.exoplayer.extractor.ts.AdtsExtractor.init(AdtsExtractor.java:54) ~[na:0.0]
 	at com.google.android.exoplayer.hls.HlsExtractorWrapper.<init>(HlsExtractorWrapper.java:64) ~[na:0.0]
 	at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:345) ~[na:0.0]
 	at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:488) ~[na:0.0]
 	at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:160) ~[na:0.0]
 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:248) ~[na:0.0]
 	at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:116) ~[na:0.0]
 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267) ~[na:0.0]
 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195) ~[na:0.0]
 	... 4 common frames omitted

```

**Comment by mingfai** [comment] 2015-05-22 00:26
The line number are incorrect. No idea why. But you may trace from RollingSampleBuffer to the root. I run in debug mode and the allocator is actually null in runtime.

**Comment by srikieonline** [comment] 2015-05-22 00:53
+1. I saw that this URL was working on 1.2.3, and is now broken on 1.3.2

com.google.android.exoplayer.ExoPlaybackException: java.lang.NullPointerException
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.NullPointerException
            at com.google.android.exoplayer.extractor.RollingSampleBuffer.<init>(RollingSampleBuffer.java:58)
            at com.google.android.exoplayer.extractor.DefaultTrackOutput.<init>(DefaultTrackOutput.java:48)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.track(HlsExtractorWrapper.java:223)
            at com.google.android.exoplayer.extractor.ts.AdtsExtractor.init(AdtsExtractor.java:54)
            at com.google.android.exoplayer.hls.HlsExtractorWrapper.<init>(HlsExtractorWrapper.java:64)
            at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:345)
            at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:488)
            at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:160)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:254)
            at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:116)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment] 2015-05-22 09:57
This will be fixed by #483, I think.

**Comment by ojw28** [comment] 2015-05-22 09:58
Note - This only affects audio-only HLS, as far as I'm aware. Please correct me if I'm wrong. We're working on putting better regression testing mechanisms in place to stop this kind of thing from happening; apologies!

**Closed** 2015-05-22 19:41 UTC
Labels: bug

**Comment by mingfai** [comment] 2015-05-22 21:04
thx. I updated to r1.3.3 and the URL works again
