### ISSUE TITLE
Up to Android 5: bad quality with m3u8 with missing height/width

### ISSUE THREAD

**Issue by toby78** [google/ExoPlayer#4505] opened 2018-07-12 09:50 UTC
### Issue description
Track selection with .m3u8 files fails on Android 5.0.2 and 6.0.1 devices, the lowest quality is shown independent of available bandwidth.

This is an ExoPlayer issue as the same streams works in Google Chrome browser on the same device.

Additional Info: Debugging DefaultTrackSelector shows height and width set to -1 for all Android Versions (both Android Versions with this issue or without this issue) - whereas the stream that does work contains this info when Debugging DefaultTrackSelector.

### Reproduction steps
Play the provided sample stream on any ExoPlayer Version on Android 5.2 or Android 6.0.1
Observe the video quality. Compare with playing the same stream in Google Chrome browser on the same device.

### Link to test content
Sent via email on 12.07.2018 - 12:07

### Version of ExoPlayer being used
ExoPlayer 2.8.2 

### Device(s) and version(s) of Android being used
Android 5.0.2 and Android 6.0.1. Android 6.0 however works.

### A full bug report captured from the device
sent via email

**Comment by AquilesCanta** [comment] 2018-07-12 09:56
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

NOTE: Format information should definitely not change between Android versions.

**Comment by toby78** [comment] 2018-07-12 10:09
Please re-open. Sample streams sent just now.

**Comment by AquilesCanta** [comment] 2018-07-12 10:10
We need all the information requested in the issue template.

**Comment by toby78** [comment] 2018-07-12 10:29
Done

**Comment by AquilesCanta** [comment] 2018-07-20 10:00
No bugreport has been provided (the issue template explains how to obtain one). Also, a single one may not be enough. Try to provide a clear explanation of each run (one that works and one that doesn't **for the same stream**), with its corresponding bugreport.

However, I suspect this issue is more related to codec capabilities advertising than width and height.

If you think width and height are relevant, you could try serving two identical playlists to the same device with one catch: one playlist includes width and height, and the other doesn't. If this affects playback, then your diagnose may be accurate.

In the logcat, you can look for lines like these:

```
Renderer:0 [
  Group:0, adaptive_supported=YES [
    [X] Track:0, id=133, mimeType=video/avc, bitrate=261112, codecs=avc1.4d4015, res=426x240, fps=30.0, supported=YES
    [X] Track:1, id=134, mimeType=video/avc, bitrate=671331, codecs=avc1.4d401e, res=640x360, fps=30.0, supported=YES
    [X] Track:2, id=135, mimeType=video/avc, bitrate=1204535, codecs=avc1.4d401f, res=854x480, fps=30.0, supported=YES
    [X] Track:3, id=160, mimeType=video/avc, bitrate=112329, codecs=avc1.4d400c, res=256x144, fps=30.0, supported=YES
    [X] Track:4, id=136, mimeType=video/avc, bitrate=2400538, codecs=avc1.4d401f, res=1280x720, fps=30.0, supported=YES
  ]
]
Renderer:2 [
  Group:0, adaptive_supported=YES_NOT_SEAMLESS [
    [ ] Track:0, id=139, mimeType=audio/mp4a-latm, bitrate=48582, codecs=mp4a.40.5, channels=2, sample_rate=22050, supported=YES
    [X] Track:1, id=140, mimeType=audio/mp4a-latm, bitrate=127868, codecs=mp4a.40.2, channels=2, sample_rate=44100, supported=YES
  ]
]
```

These lines will probably contain the most relevant information here. My theory is that they will contain the string NO_EXCEEDS_CAPABILITIES, and that the `DefaultTrackSelector` is picking the lowest quality because `exceedRendererCapabilitiesIfNecessary` is true by default. 

You can check this by yourself to save some waiting time. If the device is under-reporting capabilities, there is not much we can do about it, specially if it's fixed in later versions of Android. Please check whether the above information is true, and provide bugreports if not. Do not forget to clearly explain which stream is running each bugreport.

**Comment by ojw28** [comment] 2018-11-23 22:31
Closing due to lack of clear reproduction steps / complete bug reports / follow up.

**Closed as completed by ojw28** 2018-11-23 22:31 UTC
Labels: need more info
