### ISSUE TITLE
Current buffer size is underestimated on BufferSizeAdaptiveTrackSelection.

### ISSUE THREAD

**Issue by TakuSemba** [google/ExoPlayer#7809] opened 2020-08-27 03:20 UTC
### [REQUIRED] Issue description

I'm currently working on applying Buffer Based ABR on some contents using `BufferSizeAdaptiveTrackSelection`.
While doing so, I found the issue that it never goes to steady-state.

`BufferSizeAdaptiveTrackSelection` goes into steady-state phase when the player has enough buffer to play a track at `selectedIndex`which has selected at start-up phase (which is based on the network bandwidth).

This issue happens because that, at `TraskSelection#updateSelectedTrack()`, `BufferSizeAdaptiveTrackSelection` receives `bufferedDurationUs` to determine which track should be selected based on the buffer size algorithm, but `bufferedDurationUs` is underestimated due to this adjustment below. 

https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsChunkSource.java#L249

As a result, `BufferSizeAdaptiveTrackSelection` never selects the highest bitrate and it never satisfies the condition of moving into steady-state phase.

Also, I found that Buffer Based ABR implementation is deleted on `dev-v2` brach (not release-v2 branch) stating that it had not produced the better result, but I'm wondering it might have been caused by the issue above.

If it's the case, would it be possible to get it back and make it available to us again until we are sure that it really does not work well?

### [REQUIRED] Reproduction steps

1. set `TrackSelection.Factory` and `LoadControl` created by `BufferSizeAdaptationBuilder`.
2. play one of the content in `demo` app. (I tried `Apple 4x3 basic stream`, but I think it happens on another content too.)
3. you will see that `BufferSizeAdaptiveTrackSelection` never goes into steady-phase.

**Comment by AquilesCanta** [comment] 2020-08-27 10:52
Assigning @tonihei who experimented with `BufferSizeAdaptiveTrackSelection`.

**Comment by tonihei** [comment] 2020-08-27 15:18
Thanks for reporting and experimenting with new algorithms!

I can see the issue as well and you already identified the root cause in the `HlsChunkSource`. Note that the problem only occurs if ALL of the following conditions are true:
 1. HLS stream with non-independent segments
 2. The bandwidth is sufficient to play the highest available bitrate.
 3. The `hysteresisBuffer` parameter is less than the chunk duration of the HLS stream (5 < 10 seconds in the `Apple 4x3 basic stream` for example).

When we ran experiments with this algorithm, we used DASH streams, so this problem likely did not influence our results. Given that we deleted the class, I can't really solve anything in our current code then. You are welcome to keep using the `BufferSizeAdaptiveTrackSelection` class in your project of course, and you can easily prevent this issue by making one of the conditions above `false`, for example use DASH or HLS with independent segments, test on a slower network, or set the `hysterisBuffer` value in the builder to something that is at least the chunk duration. Note that changing this parameters also influences the behaviour of the algorithm in other places (it makes it more stable and less reactive).

[Closing because there is nothing we are going to do.]

**Closed as completed by tonihei** 2020-08-27 15:18 UTC
Labels: bug, wont fix: infeasible

**Comment by tonihei** [comment] 2020-08-27 15:37
> or set the hysterisBuffer value in the builder to something that is at least the chunk duration. Note that changing this parameters also influences the behaviour of the algorithm in other places (it makes it more stable and less reactive).

Since you have to fork the code anyway, you can also introduce a new parameter `hlsChunkDuration` or similar and make sure to use `Math.max(hysteresisBuffer, hlsChunkDuration)` instead of `hysteresisBuffer `on the following line. This prevents unwanted side effects. You can then set the `hlsChunkDuration` to whatever value you need for your streams.
https://github.com/google/ExoPlayer/blob/e822196336b64208ba7caa557e4c6ee02b03335e/library/core/src/main/java/com/google/android/exoplayer2/trackselection/BufferSizeAdaptationBuilder.java#L336

**Comment by TakuSemba** [comment] 2020-08-28 01:38
Thank you for the replay. I'll think about what we can do.

**Comment by AquilesCanta** [comment] 2020-09-02 12:17
My two cents: HLS media playlist define a [target duration](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.3.1) which you can use to 

> set the hysterisBuffer value in the builder to something that is at least the chunk duration
