### ISSUE TITLE
internalError [211.13, audioTrackUnderrun [60416, 342, 2466]]   Video has been stuck since this error occurred.

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#3787] opened 2018-02-02 09:52 UTC
## This is a detailed log. This problem has been difficult for me for a long time. I hope it can help me solve it.

- Exoplayer 2.6.1 
- Android 6.0
- Memory size：2G 
- play video :  DRM , mpd file

```
02-02 09:39:06.205 20957-20957/com.qcode.mrenderer D/EventLogger: droppedFrames [15.23, 2]
02-02 09:39:06.205 20957-20957/com.qcode.mrenderer D/EventLogger: videoDisabled [15.24]
02-02 09:39:06.206 20957-20957/com.qcode.mrenderer D/EventLogger: audioDisabled [15.24]
02-02 09:39:06.232 20957-20957/com.qcode.mrenderer D/EventLogger: state [0.00, true, I]
02-02 09:39:06.238 20957-20957/com.qcode.mrenderer D/EventLogger: ========   onLoadStarted  ========    
02-02 09:39:06.238 20957-20957/com.qcode.mrenderer D/EventLogger: state [0.01, true, B]
02-02 09:39:06.394 20957-20957/com.qcode.mrenderer D/EventLogger: sourceInfo [periodCount=1, windowCount=1
02-02 09:39:06.394 20957-20957/com.qcode.mrenderer D/EventLogger:   period [4821.79]
02-02 09:39:06.395 20957-20957/com.qcode.mrenderer D/EventLogger:   window [4821.79, true, false]
02-02 09:39:06.395 20957-20957/com.qcode.mrenderer D/EventLogger: ]
02-02 09:39:06.400 20957-20957/com.qcode.mrenderer D/EventLogger: loading [true]
02-02 09:39:06.404 20957-20957/com.qcode.mrenderer D/EventLogger: Tracks [
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:   Renderer:0 [
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:     Group:0, adaptive_supported=N/A [
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:       [X] Track:0, id=1, mimeType=video/hevc, bitrate=10009546, res=3840x1608, fps=24.416666, supported=YES
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:     ]
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:   ]
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:   Renderer:1 [
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:     Group:0, adaptive_supported=N/A [
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:       [X] Track:0, id=2, mimeType=audio/mp4a-latm, bitrate=133920, channels=2, sample_rate=44100, language=und, supported=YES
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:     ]
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger:   ]
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger: ]
02-02 09:39:06.405 20957-20957/com.qcode.mrenderer D/EventLogger: videoEnabled [0.18]
02-02 09:39:06.419 20957-20957/com.qcode.mrenderer D/EventLogger: audioEnabled [0.19]
02-02 09:39:06.420 20957-20957/com.qcode.mrenderer D/EventLogger: ========   onLoadStarted  ========    
02-02 09:39:06.420 20957-20957/com.qcode.mrenderer D/EventLogger: ========   onLoadStarted  ========    
02-02 09:39:06.420 20957-20957/com.qcode.mrenderer D/EventLogger: ========   onLoadStarted  ========    
02-02 09:39:06.420 20957-20957/com.qcode.mrenderer D/EventLogger: ========   onLoadStarted  ========    
02-02 09:39:06.474 20957-20957/com.qcode.mrenderer D/EventLogger: audioDecoderInitialized [0.25, OMX.google.aac.decoder]
02-02 09:39:06.474 20957-20957/com.qcode.mrenderer D/EventLogger: audioFormatChanged [0.25, id=2, mimeType=audio/mp4a-latm, bitrate=133920, channels=2, sample_rate=44100, language=und]
02-02 09:39:06.562 20957-20957/com.qcode.mrenderer D/EventLogger: videoDecoderInitialized [0.33, OMX.amlogic.hevc.decoder.awesome]
02-02 09:39:06.562 20957-20957/com.qcode.mrenderer D/EventLogger: videoFormatChanged [0.33, id=1, mimeType=video/hevc, bitrate=10009546, res=3840x1608, fps=24.416666]
02-02 09:39:06.658 20957-20957/com.qcode.mrenderer D/EventLogger: drmKeysLoaded [0.43]
02-02 09:39:06.928 20957-20957/com.qcode.mrenderer D/EventLogger: audioSessionId [27]
02-02 09:39:06.953 20957-20957/com.qcode.mrenderer D/EventLogger: renderedFirstFrame [Surface(name=null)/@0xe01b6db]
02-02 09:39:07.312 20957-20957/com.qcode.mrenderer D/EventLogger: state [1.08, true, R]
02-02 09:39:08.314 20957-20957/com.qcode.mrenderer D/EventLogger: loading [false]
02-02 09:39:20.730 20957-21189/com.qcode.mrenderer D/EventLogger: positionDiscontinuity
02-02 09:39:20.735 20957-20957/com.qcode.mrenderer D/EventLogger: droppedFrames [14.51, 2]
02-02 09:39:20.736 20957-20957/com.qcode.mrenderer D/EventLogger: state [14.51, true, B]
02-02 09:39:20.929 20957-20957/com.qcode.mrenderer D/EventLogger: loading [true]
   
02-02 09:39:22.889 20957-20957/com.qcode.mrenderer D/EventLogger: loading [false]
02-02 09:39:23.711 20957-21189/com.qcode.mrenderer D/EventLogger: positionDiscontinuity
02-02 09:39:23.907 20957-20957/com.qcode.mrenderer D/EventLogger: loading [true]
02-02 09:39:23.907 20957-20957/com.qcode.mrenderer D/EventLogger: ========   onLoadStarted  ========    
02-02 09:39:23.910 20957-20957/com.qcode.mrenderer D/EventLogger: ========   onLoadStarted  ========    
02-02 09:39:26.289 20957-20957/com.qcode.mrenderer D/EventLogger: loading [false]
02-02 09:39:44.587 20957-20957/com.qcode.mrenderer D/EventLogger: renderedFirstFrame [Surface(name=null)/@0xe01b6db]
02-02 09:39:44.607 20957-20957/com.qcode.mrenderer D/EventLogger: state [38.38, true, R]
02-02 09:42:33.549 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [207.32, audioTrackUnderrun [60416, 342, 818]]
02-02 09:42:34.022 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [207.79, audioTrackUnderrun [60416, 342, 466]]
02-02 09:42:34.232 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [208.00, audioTrackUnderrun [60416, 342, 134]]
02-02 09:42:34.763 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [208.54, audioTrackUnderrun [60416, 342, 511]]
02-02 09:42:37.355 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [211.13, audioTrackUnderrun [60416, 342, 2466]]
02-02 09:42:43.489 20957-20957/com.qcode.mrenderer D/EventLogger: state [217.26, true, B]
02-02 09:42:43.490 20957-20957/com.qcode.mrenderer D/EventLogger: droppedFrames [217.26, 13]
```
## The core logs are below.

**02-02 09:42:33.549 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [207.32, audioTrackUnderrun [60416, 342, 818]]
02-02 09:42:34.022 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [207.79, audioTrackUnderrun [60416, 342, 466]]
02-02 09:42:34.232 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [208.00, audioTrackUnderrun [60416, 342, 134]]
02-02 09:42:34.763 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [208.54, audioTrackUnderrun [60416, 342, 511]]
02-02 09:42:37.355 20957-20957/com.qcode.mrenderer E/EventLogger: internalError [211.13, audioTrackUnderrun [60416, 342, 2466]]**

**Comment by ojw28** [comment] 2018-02-02 11:07
There isn't anything we can do to help with this type of issue unless you provide all of the information in the issue template, including proper reproduction steps, test media that that reproduces the issue, and a full bug report captured with `adb bugreport`. Please provide this information. Thanks!

**Comment by ojw28** [comment] 2018-05-09 23:28
Closing due to lack of information.

**Closed as completed by ojw28** 2018-05-09 23:28 UTC
Labels: need more info
