### ISSUE TITLE
HLS - Unexpected exception loading stream / Internal track renderer error

### ISSUE THREAD

**Issue by zsoltconax** [google/ExoPlayer#1065] opened 2015-12-16 07:56 UTC
Screen is blank and get exceptions logged when I try to open the following stream:
https://www.dropbox.com/s/0cl4zpqt7pqk9dr/play_tv2ip_0-62.ts?dl=0
https://www.dropbox.com/s/9rxfs4fg5o76f5r/play_tv2ip_1.m3u8?dl=0

I guess it has something to do with TsExtractor, but I couldn't pinpoint the issue yet.

```
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask: java.lang.IllegalArgumentException
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.SeiReader.consume(SeiReader.java:65)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.H264Reader.feedNalUnitTargetEnd(H264Reader.java:193)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.H264Reader.consume(H264Reader.java:146)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:433)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:147)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 08:41:51.240 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.lang.Thread.run(Thread.java:818)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask: java.lang.IllegalArgumentException
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.SeiReader.consume(SeiReader.java:65)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.H264Reader.feedNalUnitTargetEnd(H264Reader.java:193)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.H264Reader.consume(H264Reader.java:146)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:433)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:147)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 08:41:51.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.lang.Thread.run(Thread.java:818)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger: internalError [0.88, loadError]
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.lang.Thread.run(Thread.java:818)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:  Caused by: java.lang.IllegalArgumentException
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.SeiReader.consume(SeiReader.java:65)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.H264Reader.feedNalUnitTargetEnd(H264Reader.java:193)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.H264Reader.consume(H264Reader.java:146)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:433)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:147)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.lang.Thread.run(Thread.java:818) 
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger: internalError [0.88, loadError]
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.lang.Thread.run(Thread.java:818)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:  Caused by: java.lang.IllegalArgumentException
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.SeiReader.consume(SeiReader.java:65)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.H264Reader.feedNalUnitTargetEnd(H264Reader.java:193)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.H264Reader.consume(H264Reader.java:146)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:433)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:147)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
12-16 08:41:51.270 2338-2338/com.google.android.exoplayer.demo E/EventLogger:     at java.lang.Thread.run(Thread.java:818) 
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask: java.lang.IllegalArgumentException
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.SeiReader.consume(SeiReader.java:65)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.H264Reader.feedNalUnitTargetEnd(H264Reader.java:193)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.H264Reader.consume(H264Reader.java:146)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:433)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:147)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 08:41:52.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.lang.Thread.run(Thread.java:818)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask: Unexpected exception loading stream
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask: java.lang.IllegalArgumentException
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.SeiReader.consume(SeiReader.java:65)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.H264Reader.feedNalUnitTargetEnd(H264Reader.java:193)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.H264Reader.consume(H264Reader.java:146)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:433)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:147)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 08:41:54.250 2338-5232/com.google.android.exoplayer.demo E/LoadTask:     at java.lang.Thread.run(Thread.java:818)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:135)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:  Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.lang.Thread.run(Thread.java:818)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:  Caused by: java.lang.IllegalArgumentException
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:116)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:127)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ts.SeiReader.consume(SeiReader.java:65)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ts.H264Reader.feedNalUnitTargetEnd(H264Reader.java:193)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ts.H264Reader.consume(H264Reader.java:146)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:433)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:147)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
12-16 08:41:54.270 2338-5218/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.lang.Thread.run(Thread.java:818) 
```

**Comment by ojw28** [comment] 2015-12-16 11:32
The media is malformed. Specifically, the SEI data in the H264 streams appears to be incorrectly truncated. If I play the TS segment in VLC on desktop I see related errors spammed into the logs (although playback doesn't fail):

```
[h264 @ 0x7efdc8c95280] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c97840] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c95280] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c97840] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c95280] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c97840] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c95280] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c97840] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c95280] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c97840] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c95280] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c97840] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c95280] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c97840] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c95280] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c97840] SEI type 49 truncated at 103
[h264 @ 0x7efdc8c95280] SEI type 49 truncated at 103
```

**Comment by ojw28** [comment] 2015-12-16 11:35
Even if we were to fix the player to be robust against the incorrect truncation, it looks like there's something else wrong with the stream that causes the video to flash green about 1 second into the playback on my test device.

The correct fix here is to correctly encode the media. Whilst we could make the player robust against the incorrect truncation, such fixes make the player less efficient for everyone using correctly encoded media. We only make such fixes if the issue is widespread in existing media. Since we only have a single sample currently, we wont be fixing this.

**Closed by ojw28** 2015-12-16 11:35 UTC
