### ISSUE TITLE
Worse video quality on some devices in comparison with MediaPlayer

### ISSUE THREAD

**Issue by okycelt** [google/ExoPlayer#5022] opened 2018-10-30 09:52 UTC
### Issue description
We're using ExoPlayer to play UDP multicast streams and we've noticed that on some devices the video quality is 'worse' in comparison with MediaPlayer. It is noticeable especially when observing text. When playing the same stream using MediaPlayer the text seems sharper than using ExoPlayer.

From our tests, it seems ExoPlayer could only have this problem on boxes with 30Hz output. If we play the same content on a box with 60Hz output the text is sharp.

Also, we think the problem could be related to the 'tbr' parameter in ffmpeg/ffprobe. In the first stream (with tbr 59.94), we observe issues. But in the second stream (same source re-encoded with tbr 30), the text is sharp. Please see the two snippets of ffprobe output below.

`Stream #0:0[0x410]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(top first), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 59.94 tbr, 90k tbn, 59.94 tbc`

`Stream #0:2[0x102]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc`

I'm sending a link to both streams via email.

### Reproduction steps
1. Play enclosed .ts file to a multicast address e.g. using tsplay.
2. Use UdpDataSource.Factory and ExtractorMediaSource.Factory to create MediaSource with Uri pointing to a multicast address from step 1

### Link to test content
Sent by email.

### Version of ExoPlayer being used
2.8.4, 2.9.0

### Device(s) and version(s) of Android being used
Amlogic stb with Android 6.0.1 (30Hz output)
Amlogic stb with Android 7.1.2 (25Hz output)

### A full bug report captured from the device
Sent by email.

**Comment by ojw28** [comment] 2018-10-30 13:34
Duplicate of #5003

**Closed as completed by ojw28** 2018-10-30 13:34 UTC
Labels: duplicate
