### ISSUE TITLE
onBackPressed() not being called

### ISSUE THREAD

**Issue by arushijain45** [google/ExoPlayer#799] opened 2015-09-16 10:00 UTC
In the PlayerActivity once the player starts if I press back button neither onBackPressed(), nor onDestoy(), nor onStop() is called. I have to do some operations in onBackPressed() which I am not able to do. Also I have to press back button twice to come out of the PlayerActivity.

**Comment by ojw28** [comment] 2015-09-16 10:54
If you're able to come out of the player activity by pressing the back button, then onBackPressed() must be getting called. This is because the base implementation of onBackPressed is what actually causes the activity to finish when the back button is pressed in the first place. In the unmodified demo app the player controls do swallow one back press if they're visible, which could explain why you need to press it twice. The first press will hide the controls, the second will be delivered to the activity. This is working as intended.

onStop and onDestroy definitely get called for me, and given we've had no other reports of this and the code has been unchanged for some time, I very much suspect it's something wrong with modifications you've made to the code / some strange device you may be using.

**Comment by arushijain45** [comment] 2015-09-16 11:13
I was using HTC Desire 616, but when i switch to Nexus 5 it started showing onStop(), onDestroy(). What might be the reason?

**Comment by ojw28** [comment] 2015-09-16 11:33
The application's thread must be getting blocked at some point (possibly in onPause where it calls releasePlayer). You'd need to capture a full bug report and upload it somewhere for us to take a look. See:

http://stackoverflow.com/questions/26789107/how-to-write-an-android-bug-report-to-a-file-via-adb

**Comment by arushijain45** [comment] 2015-09-17 05:58
@ojw28 The bug report is attached here.
https://www.dropbox.com/s/tgsrxrtghitx2p8/bugreport.txt?dl=0

**Comment by ojw28** [comment] 2015-09-18 17:33
I don't see anything obvious in that report. When exactly did you capture the bug report? You should start playback, then press back a whole bunch of time (observing that it doesn't work), and then capture the bug report whilst still in that state. If that's not what you did, could you capture and share another one? If you did that already, I'm not really sure. Thanks!

**Comment by ojw28** [comment] 2015-10-11 19:15
There's nothing actionable here given the information we have. Closing for now.

**Closed by ojw28** 2015-10-11 19:15 UTC
Labels: need more info

**Comment by jorgemreis** [comment] 2015-10-22 09:42
Hi! Following the thread's subject, how can I hide the upper buttons on the exoplayer demo at the same time of the player controls, when the back button is pressed? I didn't figure out where this behaviour is called.
Thanks in advance!

**Comment by pvllnspk** [comment] 2016-07-15 10:09
Faced the same problem on my Nexus 5 while showing an ad video, seems like the problem with losing focus
