### ISSUE TITLE
Support PNG subtitles in SMPTE-TT

### ISSUE THREAD

**Issue by fguinet** [google/ExoPlayer#1583] opened 2016-06-08 08:10 UTC
Currently the ExoPlayer code assumes subtitles/text-tracks are always receive in text format (TTML).
The metadata stream of the transport stream may contain SMPTE-TT data, an extension of TTML that extends TTML with binary blobs, encoded in base64. 
The base64 data are part of the TTML xml structure and may for example contain bitmap subtitles or be used to tunnel other formats.
Is it plan to implements SMPTE-TT + PNG support including  the display of the base64-decoded bitmap subtitles in the player ?

**Comment by rvergara1** [comment] 2016-06-08 08:50
Same issue [https://github.com/google/ExoPlayer/issues/179](https://github.com/google/ExoPlayer/issues/179)

**Comment by AquilesCanta** [comment] 2016-06-08 10:32
As stated above, this is a duplicate of [#179](https://github.com/google/ExoPlayer/issues/179). Thanks, @rvergara1.

**Comment by ojw28** [comment] 2017-04-19 14:39
Re-opening specifically to track support for bitmaps inside of SMPTE-TT. Marking as an enhancement. Realistically, I don't think we'll be looking at this any time soon, so if someone wants to work on a pull request please feel free. It's probably not too hard to add support now that plumbing of bitmaps through Cue and SubtitlePainter is in place.

**Comment by ghost** [comment] 2017-04-19 14:51
Hi @ojw28 

Just to weigh in on the use-cases here.

Many of the source channels for live TV ONLY deliver subtitles in image based DVB-SUB format. 
 
Since we don't have the luxury of being able to deliver a text based format on many channels and it cannot be be guaranteed that there will be capability in the head end to provide OCR based conversion from image rendering to text - thus SMPTE-TT  is considered a 'must have' for OTT/MPEG-DASH delivery of live TV in Scandinavia and Eastern Europe.


In saying that, If we were to have a go at implementing this, I guess we would need to add extraction /decoding of TTML metadata to TtmlDecoder?  Any other gotchas in there?

**Comment by ojw28** [comment] 2017-04-19 15:15
Yes, I think it's just a case of adding support in TtmlDecoder (and related classes in the text/ttml package). I don't think there are any gotchas, and you shouldn't need to change anything outside of that package.

**Comment by nigelmegitt** [comment] 2017-04-19 15:25
> SMPTE-TT is considered a 'must have' for OTT/MPEG-DASH delivery of live TV in Scandinavia and Eastern Europe

A valid and possibly more current alternative would be [IMSC](https://www.w3.org/TR/ttml-imsc1/)'s Image Profile, which is similarly a variant of TTML and includes some SMPTE-TT concepts. It is also under consideration for CMAF.

**Comment by rossinior** [comment] 2017-05-05 15:33
Sorry for this dumb question...
I have MKVs (HVEC Video, AC3 and/or DTS Audio, with VOBSUB subtitle tracks embedded (coming to this thread from #1781).
How does ExoPlayer 2 handle These?

**Comment by JerCodeWhisperer** [comment] 2017-08-29 20:49
Hi, we are looking to use this feature.  At the present time is it being worked on or is it planned?

**Comment by szaboa** [comment] 2018-10-19 15:07
@ojw28 @AquilesCanta

I intend to work on this, is it all right for you? 

What I see after quickly checking the code that the image attribute from the header needs to be parsed, then I need to create a bitmap from the base64 string and just pass forward to the cue. 

Am I missing something perhaps?

**Comment by ojw28** [comment] 2018-10-22 12:29
@szaboa - Feel free to give this a go!

Re your question, I'm not sure as we haven't had time to properly investigate, but what you describe sounds plausible! The main thing I'm not sure on is how the implementation will fit into the existing TTML code, which is relatively complex (e.g. `TtmlNode`). Figuring that out is probably the main challenge.

**Comment by szaboa** [comment] 2018-10-24 20:30
I think I am on the right track, the sub is already displayed. But need to research a bit the TTML specs, because I am not sure if image based subs can have regions, and also I would like to extend the TTML decoder unit test cases.

**Comment by nicusorflorin** [comment] 2018-11-15 07:29
Will this allow IMSC subs to be rendered as well?

**Comment by ojw28** [comment] 2018-12-14 15:45
@szaboa has implemented support for this (thanks!), which is now available in the `dev-v2` branch. @szaboa - Can this issue be closed, or is there more work still to be done?

**Comment by szaboa** [comment] 2018-12-14 16:22
@ojw28 
Np, looking forward to contribute more.

From my side this issue can be closed. If there is a demand for IMSC image subs then I can do it under another issue in the future.

**Closed** 2018-12-14 16:35 UTC
Labels: enhancement
