### ISSUE TITLE
Why not doing the renderer.render() parallelly in different threads?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#6075] opened 2019-06-21 09:11 UTC
Described like the title, I found other players，the audio renderer and video renderer always work in different threads,  what's the advantages of this design? 

1. In the `render()`, the audio decoder and video decoder init serially, it may wastes more time  to start the first frame. 

2. If the audio need to transform(e.g. resample, modify channel count), the processors may cost more time, which may blocking the next video renderer to work, may drop frames.

**Comment by ojw28** [comment] 2019-06-21 09:46
Marking as a duplicate of https://github.com/google/ExoPlayer/issues/5796.

**Closed as completed by ojw28** 2019-06-21 09:46 UTC
Labels: duplicate
