### ISSUE TITLE
Unable to play HLS encoded m3u8 url's

### ISSUE THREAD

**Issue by maven-y** [google/ExoPlayer#4753] opened 2018-08-30 11:27 UTC
### Issue description
Playing my HLS url in the demo app, always do not load live streaming also progress shown minus value

### Reproduction steps
1. Run the demo
2. Expand HLS
3. Click on stream
4. Link to test content

### Link to test content
Content : http://node1.twisted-symmetry.space:2000/HLS/capribb/capribb.m3u8

### Version of ExoPlayer being used
2.8.2

### Device(s) and version(s) of Android being used

- Pixel 2 XL Android 9 - OS 8.1
- Samsung Galaxy S9 Android 8.0

### A full bug report captured from the device
08-30 16:39:43.019 8150-8150/? I/exoplayersampl: Late-enabling -Xcheck:jni
08-30 16:39:43.081 8150-8150/com.yusufcakmak.exoplayersample I/exoplayersampl: The ClassLoaderContext is a special shared library.
08-30 16:39:43.192 8150-8166/com.yusufcakmak.exoplayersample D/libEGL: loaded /vendor/lib64/egl/libEGL_adreno.so
08-30 16:39:43.198 8150-8166/com.yusufcakmak.exoplayersample D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
08-30 16:39:43.211 8150-8166/com.yusufcakmak.exoplayersample D/libEGL: loaded /vendor/lib64/egl/libGLESv2_adreno.so
08-30 16:39:43.280 8150-8150/com.yusufcakmak.exoplayersample W/exoplayersampl: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
08-30 16:39:43.281 8150-8150/com.yusufcakmak.exoplayersample W/exoplayersampl: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
08-30 16:39:43.311 8150-8150/com.yusufcakmak.exoplayersample D/OpenGLRenderer: Skia GL Pipeline
08-30 16:39:43.343 8150-8167/com.yusufcakmak.exoplayersample I/Adreno: QUALCOMM build : 7bf2852, Ie32bfa6f6f
Build Date : 06/03/18
OpenGL ES Shader Compiler Version: EV031.24.00.00
Local Branch : googdrp
Remote Branch : 
Remote Branch : 
Reconstruct Branch : 
Build Config : S L 4.0.10 AArch64
08-30 16:39:43.350 8150-8167/com.yusufcakmak.exoplayersample I/Adreno: PFP: 0x005ff110, ME: 0x005ff066
08-30 16:39:43.354 8150-8167/com.yusufcakmak.exoplayersample I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-30 16:39:43.355 8150-8167/com.yusufcakmak.exoplayersample I/OpenGLRenderer: Initialized EGL, version 1.4
08-30 16:39:43.355 8150-8167/com.yusufcakmak.exoplayersample D/OpenGLRenderer: Swap behavior 1
08-30 16:39:45.940 8150-8150/com.yusufcakmak.exoplayersample W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@adea1
08-30 16:39:46.014 8150-8150/com.yusufcakmak.exoplayersample W/exoplayersampl: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
08-30 16:39:46.018 8150-8150/com.yusufcakmak.exoplayersample I/ExoPlayerImpl: Init 6246050 [ExoPlayerLib/2.8.2] [taimen, Pixel 2 XL, Google, 28]
08-30 16:39:46.040 8150-8172/com.yusufcakmak.exoplayersample D/NetworkSecurityConfig: No Network Security Config specified, using platform default
08-30 16:39:58.154 8150-8171/com.yusufcakmak.exoplayersample E/ExoPlayerImplInternal: Source error.
com.google.android.exoplayer2.source.BehindLiveWindowException
at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:290)
at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:538)
at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCompleted(HlsSampleStreamWrapper.java:584)
at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCompleted(HlsSampleStreamWrapper.java:56)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:389)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by AquilesCanta** [comment] 2018-08-30 17:37
This is a duplicate of #4659. Please try playing using FLAG_IGNORE_AAC_STREAM.

**Closed as completed by AquilesCanta** 2018-08-30 17:37 UTC
Labels: bad media
