### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by h3clikejava** [google/ExoPlayer#4295] opened 2018-05-24 12:43 UTC
at com.google.android.exoplayer2.source.ExtractorMediaSource.notifySourceInfoRefreshed (ExtractorMediaSource.java:381)
  at com.google.android.exoplayer2.source.ExtractorMediaSource.onSourceInfoRefreshed (ExtractorMediaSource.java:372)
  at com.google.android.exoplayer2.source.ExtractorMediaPeriod.maybeFinishPrepare (ExtractorMediaPeriod.java:625)
  at com.google.android.exoplayer2.source.ExtractorMediaPeriod.access$000 (ExtractorMediaPeriod.java:53)
  at com.google.android.exoplayer2.source.ExtractorMediaPeriod$1.run (ExtractorMediaPeriod.java:157)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.os.HandlerThread.run (HandlerThread.java:65)

bug report from Google Play Console, It's a old bug, maybe you need try catch it, don't let it crash!
BTW, I used version is 2.7.3

**Comment by botaydotcom** [comment] 2018-05-29 10:46
I think this is probably a duplicate of #3968. In that issue (it seems it's from you as well), @ojw28 suggested that the cause for this was probably because your app was re-using `MediaSource` instances. This is not supported until 2.8.0. Therefore, one possible solution for you in this case is to try to upgrade your app to use ExoPlayer 2.8.0 and above.

**Closed as completed by botaydotcom** 2018-05-29 10:46 UTC
Labels: duplicate
