### ISSUE TITLE
How to make the notification dismissable when using a foreground service

### ISSUE THREAD

**Issue by hobsRKM** [google/ExoPlayer#7896] opened 2020-09-12 12:10 UTC
I have implemented a foreground service which exoplayer supports and started it.
In playerState listner i used stopForeground(false)  after setplayerWhenReady(false).
No matter what I do I cannot dismiss the notification.

Tested on device ONE PLUS6T Android 10

**Here is the code for service:**
```

public class MusicPlayerInitExo extends Service {

................

public voice Oncreate(){
...................
               switch(playbackState) {
                    case Player.STATE_READY:
                        if (playWhenReady) {
                            //play event

                            playerState="play";
                            playerState();



                        } else  {
                            //pause event

                            playerState="pause";
                            playerState();


                            stopForeground(false);

                        }
                        break;
}
```
Here is how I am starting the foreground service

```
 Intent intent = new Intent(context,MusicPlayerInitExo.class);
        Util.startForegroundService(context,intent);
```

Here is the notification listener:

```
.......
 new PlayerNotificationManager.NotificationListener() {
                    @Override
                    public void onNotificationPosted(int notificationId, Notification notification, boolean ongoing) {
                        startForeground(notificationId, notification); ;

                    }
                    @Override
                    public void onNotificationCancelled(int notificationId, boolean dismissedByUser) {
                        if (dismissedByUser) {
                            // Do what the app wants to do when dismissed by the user.
                            player.release();
                            playerNotificationManager.setPlayer(null);
                            stopSelf();
                           
                        }
                    }
                });
```

**Comment by marcbaechinger** [comment] 2020-09-12 14:48
It's the intended behaviour that a user can not remove the notification as long as the notification is attached to a foreground service. You need to stop the service being in foreground when the player is paused. That allows the user to swipe away the notification. If the player is started again you put the service into foreground again.

Please refer to #7276 which explains how you can do that. Please see my comment with the code sample [here](https://github.com/google/ExoPlayer/issues/7276#issuecomment-617747297).

Sometimes the quickest way to get help, is searching for existing issues. Also include closed issues in your search. If you find your question is already answered, this saves you from writing down your question and you don't need to wait for the answer. That's very efficient.

I found, for instance, the following issues about foreground service and notification:

#7276 - PlayerNotificationManager event onNotificationCanceled is never called 
#7781 - Where to call Util.startForegroundService in PlayerActivity?
#7446 - How to remove player notification when running a foreground service
#5954 - Allow to dismiss notification with stopforeground(false) destroying service 
#7443 - onMetadataChanged callback not getting updated properly

**Comment by marcbaechinger** [comment] 2020-09-12 15:24
Closing this issue for now. Please reopen if you think the question is not covered by other issues.

**Closed as completed by marcbaechinger** 2020-09-12 15:24 UTC
Labels: duplicate, question
