### ISSUE TITLE
Widevine: No video visible when playing live content (Pixel 2 XL)

### ISSUE THREAD

**Issue by DevDroid01** [google/ExoPlayer#3596] opened 2017-12-15 21:26 UTC
### Issue description
When playing live encrypted dash content on Pixel 2 XL, audio plays but the video is not visible. The content plays fine on other devices including Pixel 1 with Android O.

### Reproduction steps
See email for sample app built using Exoplayer demo. Click the button "Click Here" on sample chooser activity to repro the issue.

### Link to test content
See email sent to dev.exoplayer@gmail.com for content

### Version of ExoPlayer being used
2.6.0 & 2.5.3

### Device(s) and version(s) of Android being used
Pixel 2 XL
Repro rate: 100%
Cannot repro on other devices

### A full bug report captured from the device
See email for bug report

**Comment by andrewlewis** [comment] 2017-12-19 11:15
Please could you try updating the device to `OPM2.171019.012` and see if this is still reproducible?

I couldn't see any obvious unexpected error logging in the bug report. @wvpaf please could you take a look at the emailed bug report and see if there's anything DRM-specific? Thanks!

**Comment by astinus-1** [comment] 2018-01-05 22:54
Not seeing anything DRM related. The keys are added correctly, and then no errors that I can distinguish that would indicate anything has happened.

**Comment by ojw28** [comment] 2018-01-08 13:25
@DevDroid01 - Please can you also include the stream details so that we can add the stream to our own version of the demo app? I pre-compiled apk isn't as useful for debugging.

**Comment by DevDroid01** [comment] 2018-01-08 16:44
@ojw28, Thanks for looking into this. Are you able to stream the content using the sample APK provided? Since the content is production content, I am not able to provide the DRM keys and our license server utilizes a different method to provide the license. So it's difficult to utilize our license server. Hence the sample APK I provided. 

Do you have any suggestions on anything else I can provide that would help you move forward in your investation?

Thanks

**Comment by ojw28** [comment] 2018-01-08 18:19
I am able to reproduce on Pixel 2 (the smaller variant, so it seems to affect both) running `OPM2.171019.012`. I cannot reproduce on Galaxy S8.

@wvpaf / @astinus-1 / @jefftinker - Could you try reproducing locally and root causing what's going wrong here? Something seems to be broken. From ExoPlayer's point of view it looks like we believe buffers really are being drawn into the surface, but that doesn't appear to be happening.

**Comment by fredgc** [comment] 2018-01-16 23:37
This has been reproduced internally, and we are investigating root cause.

**Comment by hare989** [comment] 2018-01-23 12:21
Have similar issue on Nokia 5 (Android 7.1.2)

**Comment by oleksandr-yefremov** [comment] 2018-01-25 13:59
We face the same issue on Pixel 2XL (`OPM1.171019.013`). DRM livestream with Widevine plays audio but the screen is black. Same as with OP, livestream is in production, so unfortunately we are not able to share it. Some errors are shown in logcat, maybe they are of any relevance:
```
01-08 17:41:51.588 609-609/? E/qdgralloc: Unknown Color Space = 5
01-08 17:41:51.622 609-632/? E/SurfaceFlinger: Failed to find layer (SurfaceView - testapp/testapp.navigation.NavigationActivity#0) in layer parent (no-parent).
01-08 17:41:51.625 609-631/? E/SurfaceFlinger: Failed to find layer (Background for - SurfaceView - testapp/testapp.navigation.NavigationActivity#0) in layer parent (no-parent).
01-08 17:41:52.776 988-376/? E/OMX-VDEC-1080P: OMX_QcomIndexParamVideoMetaBufferMode not supported for port: 0
01-08 17:41:52.776 988-376/? E/OMX-VDEC-1080P: set_parameter: Error: 0x80001019, setting param 0x7f00001c
01-08 17:41:52.776 988-376/? E/OMXNodeInstance: setParameter(0xf2a2bb04:qcom.decoder.avc.secure, OMX.google.android.index.storeMetaDataInBuffers(0x7f00001c): Input:0 en=0 type=1) ERROR: UnsupportedSetting(0x80001019)
01-08 17:41:52.776 988-376/? E/OMX-VDEC-1080P: Enable/Disable android-native-buffers allowed only on output port!
01-08 17:41:52.776 988-376/? E/OMX-VDEC-1080P: set_parameter: Error: 0x80001019, setting param 0x7f000017
01-08 17:41:52.776 988-376/? E/OMXNodeInstance: setParameter(0xf2a2bb04:qcom.decoder.avc.secure, OMX.google.android.index.enableAndroidNativeBuffers(0x7f000017): Input:0 en=0) ERROR: UnsupportedSetting(0x80001019)
01-08 17:41:52.776 988-376/? E/OMX-VDEC-1080P: Enable/Disable allocate-native-handle allowed only on input port!
01-08 17:41:52.776 988-376/? E/OMX-VDEC-1080P: set_parameter: Error: 0x80001019, setting param 0x7f00005d
01-08 17:41:52.776 988-376/? E/OMXNodeInstance: setParameter(0xf2a2bb04:qcom.decoder.avc.secure, OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
01-08 17:41:52.787 988-376/? E/OMXNodeInstance: getConfig(0xf2a2bb04:qcom.decoder.avc.secure, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
01-08 17:41:52.838 988-934/? E/OMXNodeInstance: getConfig(0xf4123680:google.aac.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
01-08 17:41:53.230 988-134/? E/OMXNodeInstance: getConfig(0xf2a2bb04:qcom.decoder.avc.secure, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
01-08 17:41:53.249 988-510/? E/OMXNodeInstance: getConfig(0xf2a2bb04:qcom.decoder.avc.secure, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
01-08 17:41:53.250 988-376/? E/OMXNodeInstance: getConfig(0xf2a2bb04:qcom.decoder.avc.secure, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
```

**Comment by wvpaf** [comment] 2018-01-30 23:08
Might be a surface connection issue, reassigning to @ojw28

**Comment by ojw28** [comment] 2018-01-31 12:34
Internal ref b/70981593

**Comment by bwalter** [comment] 2018-03-13 12:03
We currently have the same issue and get many complaints from Pixel 2 users. Do you have any further information? Any help would be very much appreciated. I would be extremely happy to know if there is a possible workaround to make the DRM/Widevine livestream work on that device.

**Comment by oleksandr-yefremov** [comment] 2018-04-11 09:37
Our streaming team found out that we can work around this issue by changing color schemes and matrix.

Stream with following config did not work (`bt470bg` scheme, DRM):
```
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Bits/(Pixel*Frame) : 0.241
Stream size : 1.82 MiB (94%)
Color range : Limited
Color primaries : BT.601 PAL
Transfer characteristics : BT.470 System B, BT.470 System G
Matrix coefficients : BT.470 System B, BT.470 System G
```

Same stream but with scheme `bt709` works without issues (DRM)
```
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Stream size : 1.29 MiB (95%)
Color range : Limited
Color primaries : BT.709
Transfer characteristics : BT.709
Matrix coefficients : BT.709
```

We are transferring all our streams now, hopefully this change will not break on other devices.
Since there is no information about limitations on color scheme in [dev guide](https://google.github.io/ExoPlayer/supported-formats.html) or anywhere else, I assume this is a bug on Pixel 2 specifically. Hence the question, **is this smth that can be "fixed" on OS build or ExoPlayer side?**

**Comment by croedel** [comment] 2018-05-07 09:06
Just adding some points to stress the high business relevance of this ticket:

The non working color schema BT.601 PAL is the **standard color schema for SD Live streams**. This means, that this bug causes all SD Live streams with Widevine DRM encryption to fail on Pixel2.
The workaround (i.e. changing the color schema) for Live streams unfortunately is **not** a simple setting within the transcoder. It would mean a major HW invest (upscaling to HD, color schema converter, ...) and permanent cost increase for all SD channels. 

Therefor we would really be grateful if this issue could get fixed on OS / ExoPlayer / Widevine side, soon.

**Comment by ojw28** [comment] 2018-05-07 15:00
@jefftinker - My understanding is this is fixed for Pixel in P. Could you confirm this is correct? Thanks.

**Comment by naseer** [comment] 2018-05-07 15:08
If the transfer for such clips can somehow be spoofed to `Recommendation ITU-R BT.470-2 System M | gamma 2.2`, that should also help resolve this problem until a proper fix is available to you.

**Comment by jt64** [comment] 2018-05-22 22:20
Yes this issue has been fixed in P.

**Comment by jt64** [comment] 2018-05-22 22:21
@ojw28 can you close this?

**Closed as completed** 2018-05-23 07:58 UTC
Labels: bug: device specific, bug: in platform drm
