### ISSUE TITLE
Streaming playback related loading and buffering issues response questions

### ISSUE THREAD

**Issue by yyms3275** [google/ExoPlayer#9546] opened 2021-10-08 10:40 UTC
◈ Symptoms ◈

I'm making a sample that plays a YouTube URL based on the ExoPlayer library. However, some specific videos require a lot of loading time during playback. If you play it once and then play it again, sometimes it loads quickly, but many videos require a long loading time such as buffering when starting for the first time.

The ProgressiveMediaSource method and the MergingMediaSource function were used to play the video.
Buffering loading occurs when only video is played, and buffering loading does not occur when only audio is played.

Buffering does not exist in any case when loading from a Shinhange webview. However, buffering occurs only in the sample app I made.
Is it a problem with the decoder of the codec? Or is it a problem with the buffering tuning settings? Or is it a bug in ExoPlayer itself?

I prepared a sample APK and source code to clearly show the symptoms I am talking about. I hope you can solve my problem through the APK or source code below. Also, the saved log is attached when there is buffering loading.

* If you look at the log in the case of normal and buffered loading, there is a difference between the following lines.

I/Codec2Client: Available Codec2 services: "default" "software"
E/ion: ioctl c0044901 failed with code -1: Inappropriate ioctl for device
I/ACodec: [OMX.qcom.video.decoder.avc] OMX_EventPortSettingsChanged 0x7f000062

◈ Reference YouTube URL ◈

* https://youtu.be/zx5Rpv7WmU4
* https://youtu.be/kF0SHa-lWqc
* https://youtu.be/rkiu8IGjG5Q
* https://youtu.be/cAmiuLeSlEU
* https://youtu.be/7wVXO3Z7q2k

◈ Log / APK / Source code ◈

* Download Logcat : [logcat.txt](https://github.com/google/ExoPlayer/files/7310548/logcat.txt)
* Download sample apk(.apk) : https://mega.nz/file/RnYnAKLI#gljX7WRsVRexgTY1Ag-F5htG3BGgJiui8JV-y-dQVfk
* Download sample source code(.zip) : https://mega.nz/file/BiQRlaDA#yUm6hDLLJBxhyuG7aYsd1bOq4Z4KOAFCMMn6yx-1nUY
* Symptom preview : https://user-images.githubusercontent.com/41143436/136542404-8bd36b06-7119-4c8b-89f7-5b9a2b6c972f.mp4

https://user-images.githubusercontent.com/41143436/136548913-c5afefa0-6591-44a8-b342-6daa759425f9.mp4

◈ Testing other apps ◈

* I tested playing the video by changing the internal URL through other apps or open sources listed below. However, except for the webview method, all of them showed the same loading symptoms such as buffering.

<Normal operation>

* Adityakumar-Y/VideoPlayerApp : How to play webview
https://github.com/Adityakumar-Y/VideoPlayerApp

<Buffering symptoms>

* YMusic

* imamit29/ExoPlayer-With-Vimeo-Youtube
https://github.com/imamit29/ExoPlayer-With-Vimeo-Youtube

* faisalmahmudxiii/Youtube_like
https://github.com/faisalmahmudxiii/Youtube_like

* mitchtabian/Video-Player-RecyclerView
https://github.com/mitchtabian/Video-Player-RecyclerVi

**Comment by icbaker** [comment] 2021-10-08 11:48
This looks like a duplicate of #9531. Please don't open additional issues for the same question.

Also note that ExoPlayer does not support playing YouTube videos: https://exoplayer.dev/troubleshooting.html#can-i-play-youtube-videos-directly-with-exoplayer

**Comment by andrewlewis** [comment] 2021-10-08 14:27
I don't think it's going to be productive for us to spend time looking into this as it seems likely these streams are not intended to be loaded in this way. As @icbaker indicates, we don't support playback of YouTube videos and instead you should be using the [proper API](https://developers.google.com/youtube/android/player/) for doing that.

**Closed as completed by andrewlewis** 2021-10-08 14:27 UTC
Labels: question
