### ISSUE TITLE
Close caption: Text are not match with the audio its going Two second advanced

### ISSUE THREAD

**Issue by mohanrajsambath** [google/ExoPlayer#3998] opened 2018-03-16 09:32 UTC
### Issue description
Close caption: Text are not matching with the audio it's going Two seconds advanced,  I'm using HLS streaming  URL. The URL is coming from the Amazon with transcription made by my team. I'm trying on Android as my part. This issue occurs only on my side. How do I handle this issue?

### Reproduction steps
Parse HLS URL with transcription enabled to exoplayer

### Version of ExoPlayer being used
Exoplayer version 2.6.0

### Device(s) and version(s) of Android being used
Device: Samsung Galaxy S6,
OS: Android 5.0.2.

**Comment by botaydotcom** [comment] 2018-03-16 10:02
Hi @mohanrajsambath ,
Please provide us with the URL/ content that you are testing with? If you don't want to put the link here, you can send us an email to dev.exoplayer@gmail.com, and we will look into it. Thank you very much.

**Comment by mohanrajsambath** [comment] 2018-03-16 10:33
I'm unable to share the URL because we are setting a cookie. Do have any other idea.

**Comment by AquilesCanta** [comment] 2018-03-16 10:44
Please send instructions to reproduce the issue to dev.exoplayer@gmail.com if you don´t want to share them publicly (would the URL and the cookie be enough?). However, this is not something we have seen in the past, so we cannot provide assistance without being able to actually reproduce it, unfortunately.

**Comment by mohanrajsambath** [comment] 2018-03-16 11:27
Thankyou, I will do by mail.

**Comment by mohanrajsambath** [comment] 2018-03-16 12:25
If I send public URL here is it possible to test on your side, depend on your reply, I will request to my team to make public URL. Thank you.

**Comment by AquilesCanta** [comment] 2018-03-16 12:28
It'd be great to avoid any cookie usage requirements, if that's what you mean. But it doesn't have to publicly accessible, if that's the question. Any links sent to dev.exoplayer will remain visible only to the exoplayer development team.

**Comment by mohanrajsambath** [comment] 2018-03-19 14:12
Sorry for your Inconvenience, My Team is Making on it.  Thank you for prompting reply.

**Comment by mohanrajsambath** [comment] 2018-03-23 09:23
I have this public url, can you please help me to fix this issue, 
[https://s3-eu-west-1.amazonaws.com/cyrano-temp/test-audio/aa10a5e5-0d88-dac7-400f-f20a7dce6841.m3u8](Close Caption url), thank you.

**Comment by AquilesCanta** [comment] 2018-03-27 16:00
This works correctly for me. The rendered subtitles match the embedded webvtt file and are roughly in sync with the sound. Could you clarify the unexpected behavior you are observing?

**Comment by ojw28** [comment] 2018-06-05 21:12
Closing due to lack of updates (and the subtitles appearing to work correctly when we tried to reproduce).

**Closed as completed by ojw28** 2018-06-05 21:12 UTC
Labels: need more info
