### ISSUE TITLE
how to get getCurrentPosition with   playbackControlView.setShowMultiWindowTimeBar(true); of the next video

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#8375] opened 2020-12-19 05:51 UTC
how can we get the current position of the second, third video with ConcatenatingMediaSource

I had a look at playerview, where the current position text is updated, I want to have a custom implementation of the seekbar and to display the current position text in a similar way. 
```
if (!timeline.isEmpty()) {
                        int currentWindowIndex = player.getCurrentWindowIndex();
                        int firstWindowIndex = multiWindowTimeBar ? 0 : currentWindowIndex;
                        int lastWindowIndex = multiWindowTimeBar ? timeline.getWindowCount() - 1 : currentWindowIndex;
                        for (int i = firstWindowIndex; i <= lastWindowIndex; i++) {
                            if (i == currentWindowIndex) {
                                currentWindowOffset = C.usToMs(durationUs);
                            }

```

an easier option would be to get currentWindowOffset directly, is it possible.

**Comment by marcbaechinger** [comment] 2020-12-29 17:01
I think I understand you want to get the duration of each item in the `ConcatenatingMediaSource`. With this you can calculate the total position of the start of any media source in the playlist to display the current position in the entire playlist. If this is what you are trying to achieve, and if you are using progressive media, please refer to #4727. 

The duration of progressive media items is available only when the player starts to buffer the media item, not before. This is a known limitation. 

Duplicate of #4727.

Please re-open if I misunderstood your issue.

**Closed as completed by marcbaechinger** 2020-12-29 17:01 UTC
Labels: duplicate, question
