### ISSUE TITLE
Offline DASH `StreamKey` mismatch between `DownloadHelper` and `DashMediaSource`

### ISSUE THREAD

**Issue by benlancaster** [google/ExoPlayer#9284] opened 2021-08-11 08:47 UTC
I've noticed that there is a mismatch between the track groups advertised by `DownloadHelper`, and those advertised by `DashMediaSource`.

Consider a single-period DASH VOD stream with the following tracks, as advertised by `DownloadHelper`:

- Period 0
  - TrackGroup 0: video tracks (6 representations)
  - TrackGroup 1: `application/cea-708` (embedded)
  - TrackGroup 2: `audio/eac3` (1 representation)
  - TrackGroup 3: `audio/mp4-latm` (1 representation)
  - TrackGroup 4: `text/vtt` (1 representation)
  - TrackGroup 5: `application/x-emsg` (embedded) 

Track groups at index 1 and 5 are embedded in the video segments.

In this example, let's suppose we would like to download:

- the highest bitrate video track (`StreamKey(0,0,1)`)
- the MP4 audio track (`StreamKey(0,3,0)`)

When ExoPlayer re-parses the manifest to get the segments to download, it is unaware of the embedded CEA-708 and SCTE track groups, so the `DashMediaSource` looks like this:

- Period 0
  - TrackGroup 0: video tracks (6 representations)
  - TrackGroup 1: `audio/eac3` (1 representation)
  - TrackGroup 2: `audio/mp4-latm` (1 representation)
  - TrackGroup 3: `text/vtt` (1 representation)

...so the copied manifest (persisting only provided `StreamKeys`) contains the wrong tracks, in this example, using our previously selected StreamKeys, the WebVTT track _not_ MP4 Audio track will be downloaded, resulting in a silent playback (but at least you get subtitles I guess!).

**Comment by claincly** [comment] 2021-08-12 08:46
Before I assign this issue, can you provide a link to the media? 

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by jeffwconaway** [comment] 2021-08-16 16:15
I attached a bug report and sent that to dev.exoplayer@gmail.com. Hopefully this will help.

**Comment by claincly** [comment] 2021-09-01 16:00
Hello @jeffwconaway, I cannot see the email you sent, please maybe check if the address is correct? 

And also please add the "needs triage" label after you send it, thanks!

**Comment by ojw28** [comment] 2021-09-07 09:12
> In this example, let's suppose we would like to download:
>
> the highest bitrate video track (`StreamKey(0,0,1)`)
> the MP4 audio track (`StreamKey(0,3,0`)

This is assuming that `StreamKey.groupIndex` and `StreamKey.trackIndex` are the same as the index of the `TrackGroup` and the index of the track within it. This is not always the case, because a `StreamKey` identifies a stream rather than a track. The distinction is more obvious when you have muxed audio/video streams in HLS. In this case there are two tracks contained within a single stream, so the indexing clearly can't be the same in both cases. The same is true here, albeit more subtly, where the caption and video tracks are muxed into a single stream.

The intended use of `DownloadHelper` is that you use its methods for track selection to select which tracks you want, as documented in [the Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/offline/DownloadHelper.html) (step 3). Calling `getDownloadRequest` (step 4) will then generate a `DownloadRequest` that's supposed to contain the correct `StreamKeys` for the selected tracks. Internally, it does this by calling `MediaPeriod.getStreamKeys`, which looks like it correctly accounts for embedded tracks.

I suspect what's happening here is that you're not following the intended use of `DownloadHelper`, and are creating `StreamKeys` directly in application code, making the incorrect assumption described above when doing so. If that's the case, I think this is an application issue that you can fix by using `DownloadHelper` in the intended way instead.

Alternatively, if you are using `DownloadHelper` in the intended way and it's generating the incorrect `StreamKeys` for you, please let us know and we'll take another look. `DashMediaPeriod.getStreamKeys` likely has a bug in it if this is the case.

**Comment by benlancaster** [comment] 2021-09-07 15:12
> I suspect what's happening here is that you're not following the intended use of `DownloadHelper`, and are creating `StreamKeys` directly in application code, making the incorrect assumption described above when doing so. If that's the case, I think this is an application issue that you can fix by using `DownloadHelper` in the intended way instead.

Interesting, we'll investigate and report back. If that's the case, I'll go ahead and close this issue. Thanks loads for taking the time to explain it so well, @ojw28.

**Comment by ojw28** [comment] 2021-09-09 17:41
Closing this on the assumption it's an app issue as described, but please let us know if not. Doing so here is fine as long as the issue isn't locked (it doesn't matter that it's closed; we can re-open it if needed).

We updated the `StreamKey` documentation to try and make it a little clearer in the commit referenced above.

**Closed as completed by ojw28** 2021-09-09 17:41 UTC
Labels: wont fix: app issue

**Comment by jeffwconaway** [comment] 2021-09-27 21:20
@ojw28 Thanks for your help on this issue.

I'm looking into changing out implementation to what you recommended.  I think changing the way we were using `DownloadHelper` fixed the issue we were having with `StreamKeys`.  In our previous implementation, we were able to download tracks that were in  `MappingTrackSelector.MappedTrackInfo.unmappedTrackGroups` by generating our own `StreamKeys` and `DownloadRequests`. 

I don't see a way to download a track that ends up in `MappingTrackSelector.MappedTrackInfo.unmappedTrackGroups` via `DownloadHelper.addTrackSelection()` using  `SelectionOverrides`.  When the `DownloadRequest` is created, only `SelectionOverrides` are read from the mapped renderers.  

Is there another way to allow tracks from `MappingTrackSelector.MappedTrackInfo.unmappedTrackGroups` to be downloaded?

**Comment by ojw28** [comment] 2021-09-27 21:30
> Is there another way to allow tracks from MappingTrackSelector.MappedTrackInfo.unmappedTrackGroups to be downloaded?

If the track ends up in `unmappedTrackGroups` then that implies that it's not playable, assuming you're using equivalent `RenderersFactory`s for downloading and playback, which we'd expect to be the case. So I think my question would be: Why would you want to do this :)? I suspect that you may have a somewhat unusual use case.

**Comment by benlancaster** [comment] 2021-10-07 08:27
> > Is there another way to allow tracks from MappingTrackSelector.MappedTrackInfo.unmappedTrackGroups to be downloaded?
> 
> If the track ends up in `unmappedTrackGroups` then that implies that it's not playable, assuming you're using equivalent `RenderersFactory`s for downloading and playback, which we'd expect to be the case. So I think my question would be: Why would you want to do this :)? I suspect that you may have a somewhat unusual use case.

Thumbnails (for thumbnail scrubbing)
