### ISSUE TITLE
with HLS, onVideoInputFormatChanged is called automatically and initializes format

### ISSUE THREAD

**Issue by jy617lee** [google/ExoPlayer#5373] opened 2019-01-14 06:40 UTC
I'm using exoplayer 2.9.1v, and trying to change bitrate, width, height of player. 
Like demo app, I'm trying to set these parameters using `DefaultTrackSelector`. 
But when to start player, `onVideoInputFormatChanged` is called and this initializes format (width, height, etc). 

below is my code which set format parameters via DefaultTrackSelector.
```            
           TrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory();
            DefaultTrackSelector trackSelector = new DefaultTrackSelector(trackSelectionFactory);
            trackSelector.setParameters(
                    trackSelector
                            .buildUponParameters()
                            .setMaxVideoSizeSd()
                            .setMaxVideoBitrate(quality)
                            .setMaxVideoSize(videoW, videoH)
            );

            player = ExoPlayerFactory.newSimpleInstance(context, trackSelector);
            dataSourceFactory = new DefaultDataSourceFactory(context,
                    Util.getUserAgent(context, "yourApplicationName"));
            videoSource = new HlsMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(Uri.parse(mVideoItem.getVideo()));
            player.addAnalyticsListener(this);
            player.prepare(videoSource);
```

**Comment by tonihei** [comment] 2019-01-14 09:24
What you describe sounds as if everything is working as intended. Can you please elaborate a bit more what your actual problem is?

**Comment by jy617lee** [comment] 2019-01-14 09:41
Thank you for reply, @tonihei . 

For example, I set videosize with `setMaxVideoSize(360, 180)` and call player.prepare. 

But when player starts, `onVideoInputFormatChanged(Format format)` is called and `format.width` is 1280 and `format.height` is 720 which is diffrent from what I set with setMaxVideoSize()

**Comment by tonihei** [comment] 2019-01-14 09:45
Can you provide more details of your stream (either share it, or attach an `EventLogger` and paste the outputs here)? Might be that you don't have a format which is below this max video size or that the HLS formats don't contain the video size.

**Comment by tonihei** [comment] 2019-02-08 14:48
Closing as we haven't received further input.

**Closed as completed by tonihei** 2019-02-08 14:48 UTC
Labels: question
