### ISSUE TITLE
Matroska file has to download completely before playing

### ISSUE THREAD

**Issue by steelersfan7** [google/ExoPlayer#8935] opened 2021-05-13 05:25 UTC
I pass a  URL to exoplayer and it can't play the underlying mkv file that the URL is pointing to. The file is H264 video and AAC audio.

This is when I try to initially open the URL. Note the period and window are just question marks.

```
2021-05-11 15:53:10.941 29571-29571/org.client.android D/EventLogger: timeline [eventTime=0.97, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
2021-05-11 15:53:10.941 29571-29571/org.client.android D/EventLogger:   period [?]
2021-05-11 15:53:10.942 29571-29571/org.client.android D/EventLogger:   window [?, seekable=false, dynamic=true]
2021-05-11 15:53:10.942 29571-29571/org.client.android D/EventLogger: ]
```

This is 8 minutes later when the video has downloaded fully. Now, the period and window are filled in and the item starts to play.

The expected behavior is to play while the video is still downloading.
```
2021-05-11 16:01:02.721 29571-29571/org.client.android D/EventLogger: timeline [eventTime=472.75, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2021-05-11 16:01:02.722 29571-29571/org.client.android D/EventLogger:   period [4290.35]
2021-05-11 16:01:02.722 29571-29571/org.client.android D/EventLogger:   window [4290.35, seekable=true, dynamic=false]
2021-05-11 16:01:02.722 29571-29571/org.jellyfin.client.android D/EventLogger: ]
```
- ExoPlayer version number is `2.13.2`
- Android version is `11`
- Android device is `note 20`

**Comment by Samrobbo** [comment] 2021-05-13 12:50
Is this using the ExoPlayer demo app? Or have you got adjustments and customisations within your own app? 

If possible, can we get a link to the test media, so that we can try to reproduce the problem and see what the issue is? 

The best way to get meaningful and usable responses is to fill in the issue template, which can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ojw28** [comment] 2021-05-14 11:49
This is probably because the `Cues` element has been written at the very end of the file. ExoPlayer needs this element before it can start playback. As per the [Matroska documentation](https://www.matroska.org/technical/ordering.html), writing the `Cues` element further forward in the file has some advantages (including allowing ExoPlayer to start playback when it only has a partial download).

**Comment by steelersfan7** [comment] 2021-05-14 17:24
I am still assembling some logs and data as requested. This seems to be only a problem related to exoplayer. MX,libvlc, vlc, mpv, and any one of the app store players take the URL's in and start playing. I am also confirming soon if the issue is related to mkv, by testing an mp4. Thanks for the quick reply.

**Comment by ojw28** [comment] 2021-06-04 11:54
Closing because I don't think there's anything actionable for us. As above, this can likely be avoided by locating the `Cues` element toward the beginning of the file. It is _possible_ for a player to support playback without the `Cues` element, albeit with inefficient or no seeking support. This is not something we're looking to support though.

**Closed as completed by ojw28** 2021-06-04 11:54 UTC
Labels: question
