### ISSUE TITLE
The surface show nothing after  mSimpleExoPlayer.setVideoListener(mVideoListener);

### ISSUE THREAD

**Issue by songwenju** [google/ExoPlayer#2800] opened 2017-05-10 09:26 UTC
when I use the simpExoPlayer to setVideoListener(videoListener),like this :
```
mExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.exoView);
mExoPlayerView.setPlayer(mSimpleExoPlayer);
mSimpleExoPlayer.setVideoListener(mVideoListener);
mSimpleExoPlayer.addListener(eventListener);
mSimpleExoPlayer.setPlayWhenReady(true);

//the videoLister
 private SimpleExoPlayer.VideoListener mVideoListener = new SimpleExoPlayer.VideoListener() {
        @Override
        public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio) {
            LogUtil.i(this,"MainActivity.onVideoSizeChanged.width:"+width+", height:"+height);

        }

        @Override
        public void onRenderedFirstFrame() {
                LogUtil.i(this,"MainActivity.onRenderedFirstFrame.");
        }
    };
```
the surface is black ,but audio is play.

**Comment by AquilesCanta** [comment] 2017-05-10 09:40
Is there a shutter involved? If so, are you making it invisible? If there is a SimpleExoPlayerView involved, maybe you should also add `mExoPlayerView.onRenderedFirstFrame();`. Like in:

```
@Override
public void onRenderedFirstFrame() {
    mExoPlayerView.onRenderedFirstFrame();
    LogUtil.i(this,"MainActivity.onRenderedFirstFrame.");
}
```

**Comment by ojw28** [comment] 2017-05-10 14:30
The problem is that `SimpleExoPlayerView` sets itself as the video listener (in its `setPlayer` method), and relies on being the registered listener. By calling `setVideoListener` yourself you're replacing the listener with your own. `SimpleExoPlayerView` then doesn't get the events that it needs.

We could change `setVideoListener` to `addVideoListener`/`removeViewListener` if you have a legitimate use case for needing to listen to the events. Normally, though, I'd only expect the player view to need these events.

**Comment by ojw28** [comment] 2017-05-10 14:30
Marking as needs-more-info to clarify what the use case is for needing these events.

**Comment by songwenju** [comment] 2017-05-11 03:23
@AquilesCanta 
```
mExoPlayerView.onRenderedFirstFrame();
```
The object can not use the method.

**Comment by AquilesCanta** [comment] 2017-05-11 09:33
Yes, looking into it into detail I noticed the class that actually implements `VideoListener` is an internal class, not actually `SimpleExoPlayerView` so the approach I presented won't work. Please reply @ojw28's comment above, so we might think about multiple listeners support.

**Comment by songwenju** [comment] 2017-05-12 01:57
@ojw28 Sometimes I need to monitor the changes in the listener, such as in the TIF, TvInputService want to get the size of the player changes, and then notify the corresponding surface to make the appropriate changes.

**Comment by ojw28** [comment] 2017-05-12 02:01
Using `setVideoListener` is appropriate for that use case. But in that use case it doesn't make sense for you to also be using `SimpleExoPlayerView`. Either the output is `SimpleExoPlayerView` (in which case it's the registered video listener) or you're outputting to some other Surface (in which case you're the registered video listener). So I don't think your use case requires the ability to have multiple video listeners simultaneously on the player...

**Comment by marcbaechinger** [comment] 2017-05-14 23:03
> We could change setVideoListener to addVideoListener/removeViewListener if you have a legitimate use case for needing to listen to the events.

@ojw28 I think a legitimate use case could be performance monitoring. While the SimpleExoPlayerView needs the onRenderedFirstFrame to remove the shutter, a performance monitoring listener wants to know the time it takes until the first frame is rendered and report that time.

On the other hand there is also simpleExoPlayer.setVideoDebugListener which allows to set a VideoRendererEventListener which has a onRenderedFirstFrame(Surface surface) callback which is quite the same thing.

**Comment by ojw28** [comment] 2017-05-15 01:13
Right, the debug listener is suitable for that case. Closing this for now.

**Closed as completed by ojw28** 2017-05-15 01:13 UTC
Labels: need more info
