### ISSUE TITLE
Bug: when `onPlayerStateChanged` is called , saying the video has started, it shows a black content first

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4731] opened 2018-08-27 12:53 UTC
It's for a very very short time, but you can notice it in some content.

In my sample POC, I've made a ViewAnimator that has an ImageView and PlayerView. When the player says it's completely ready and starts playing, I switch to the PlayerView:

        player!!.addListener(object : PlayerEventListener() {
            override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
                super.onPlayerStateChanged(playWhenReady, playbackState)
                if (playbackState == Player.STATE_READY && playWhenReady) {
                    Log.d("appLog", "onPlayerStateChanged STATE_READY")
                    if (viewSwitcher.currentView != playerView)
                        viewSwitcher.showNext()
                }
            }
        })

However, in this very first step, I can see a black content first.

Attached sample project and video. To see the issue, play the video in super slow motion to notice, or change the content it shows compared to the surrounding (example: white background around the view, and red video to play).

[ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/2323891/ExoPlayerTest.zip)

Tested on Pixel 2 with Android P.

Currently the only workaround for this that I've found, is to avoid using ViewAnimator , and instead use Framelayout, where the ImageView is on top, and ignore `onPlayerStateChanged`, and instead, 
when the `onRenderedFirstFrame` is called, only then I show the video.

**Comment by AndroidDeveloperLB** [comment] 2018-08-27 12:58
BTW, the sample shows opening a file from external storage, but the same issue occurs with the res/raw resource file too.

**Comment by AquilesCanta** [comment] 2018-08-30 13:30
Note: I cannot reproduce the described problem in the provided app. I do see a bit of stuttering the first time the file is played, but I am not sure it's the described issue. Not in the subsequent repeats. A few questions:

- Is this content specific? Does it work correctly with other media files?
- Can you reproduce in the demo app?
- Does it play correctly using MediaPlayer?

One thing I can point out is that you should keep the video surface visible, and use the image view on top (as pointed out in the original post), in line with what we do with the shutter view in the player view. Also, if you plan to animate the player view somehow, it's probably a good idea to use a texture view, instead of a surface view.

**Comment by tonihei** [comment] 2018-08-30 14:02
To add to what has already been said:
The `onPlayerStateChanged` event with the change to `STATE_READY` means the whole renderer pipeline is ready to proceed with the playback. That doesn't necessarily mean the first frame has already been rendered. For example (among other reasons), if the surface being rendered into is not attached yet or tunneling is enabled.
As you already pointed out, the `onRendererFirstFrame` callback is the only one which gives you direct feedback on whether the screen is still black or the first frame has been rendered.

**Comment by AndroidDeveloperLB** [comment] 2018-08-30 20:13
@AquilesCanta Have you watched the attached video? Between the time you see the image and the time the video plays, there is a black content, which doesn't exist in the input video file.

As I wrote, you need to either look very well, or record what you see and play in slow motion.
Check the video here, after I've played what I've send in slow motion. It is for a very short time, as I wrote. If you chose a different content to show on the image and video, you might notice it better.

[2018-08-30_19-38-33.zip](https://github.com/google/ExoPlayer/files/2337039/2018-08-30_19-38-33.zip)

If you say you can't see it, please take a video of what you see (choose whichever video and image you wish, as long as they are quite different) , and I will show you it has a black content before showing the video.

- Is this content specific? Does it work correctly with other media files?

No. Same issue. Tried videos from here too:
https://www.videoblocks.com/video/colorful-abstract-energy-lines-background-loop-tamyptx

- Can you reproduce in the demo app?
Demo app doesn't have this case of ViewAnimator with ImageView and ExoPlayer as its child views. How can I check it there?

- Does it play correctly using MediaPlayer?
What would be the equivalent ? setOnPreparedListener 

"One thing I can point out is that you should keep the video surface visible, and use the image view on top (as pointed out in the original post), in line with what we do with the shutter view in the player view."

Doesn't help. Already tried it. 

I suggest having a new state for onPlayerStateChanged , that says that the player is now playing, which means it actually shows content and it's safe to switch to it.

**Comment by AndroidDeveloperLB** [comment] 2018-08-30 20:17
@tonihei  Why should they be separated? Why not have a state that says that the player is playing?

We have STATE_IDLE , STATE_BUFFERING , STATE_READY , STATE_ENDED . Why don't we have STATE_PLAYING ? The most important state is missing if this is not working this way.

Also, the docs say this about "STATE_READY" :

"The player is able to immediately play from its current position. The player will be playing if
 {@link #getPlayWhenReady()} is true, and paused otherwise.
"

And I had `getPlayWhenReady` set to be true, meaning it should have been playing there, and not just "ready" to play.

**Comment by AndroidDeveloperLB** [comment] 2018-08-30 20:37
BTW, I've tested the sample of this repository, of "demo-ima". It has the same issue. After the ad is shown, there is a black content between the ad and the video.
Check attached video.

[2018-08-30_23-33-32.zip](https://github.com/google/ExoPlayer/files/2337830/2018-08-30_23-33-32.zip)

Then again, maybe it's not implemented well. Maybe it doesn't cache the content video while playing the ad. I haven't looked at the code.

**Comment by tonihei** [comment] 2019-05-07 15:03
I think the question has been answered above, so closing the issue.

**Closed as completed by tonihei** 2019-05-07 15:03 UTC
Labels: need more info
