### ISSUE TITLE
Exoplayer UI and Service disconnections.

### ISSUE THREAD

**Issue by fourofspades** [google/ExoPlayer#9206] opened 2021-07-20 12:01 UTC
I'm having some issues with my app, where Android kills my background service after a while.   When the user presses the play button in the ExoPlayer UI, it doesn't do anything anymore, as the service has been killed by the OS.

What should I be doing here?  It doesn't help that there isn't a good example of how to do an audio-only player with a background service.

**Comment by marcbaechinger** [comment] 2021-07-20 13:34
You need to run your service as a Foreground service and attach a notification to it to make it visible for the user. When running in the foreground, the system does not kill the service. Detailed documentation about running a foreground service can be found in the [guide](https://developer.android.com/guide/components/foreground-services) on developer.android.com.

**Comment by fourofspades** [comment] 2021-07-20 15:02
In my audio service, I am using a PlayerNotificationManager.Builder and calling the following on it:

```
.setNotificationListener( new PlayerNotificationManager.NotificationListener()
		{
			@Override
			public void onNotificationPosted( int notificationId, Notification notification, boolean ongoing )
			{
				startForeground( notificationId, notification );
			}
			@Override
			public void onNotificationCancelled( int notificationId, boolean dismissedByUser )
			{
				stopForeground( true );
				stopSelf();
			}
		} );
```
I also have <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>  in my manifest.

Is this not enough?

**Comment by marcbaechinger** [comment] 2021-07-20 15:26
That look about right to me. You also need to start the service accordingly. There is `Util.startForegroundService()): 

```
@Nullable
  public static ComponentName startForegroundService(Context context, Intent intent) {
    if (Util.SDK_INT >= 26) {
      return context.startForegroundService(intent);
    } else {
      return context.startService(intent);
    }
  }
```

You can use the method above or do what the method is doing yourself. Please also verify the `onNotificationPosted()` is called immediately when the service is started. This requires that the player is prepared when you start the service.

**Comment by fourofspades** [comment] 2021-07-21 13:14
I am doing all the above things mentioned (and always have been), but still getting disconnects.   I think I have a related question.   I am using audio live streaming, and the service gets killed, I believe, only when the player is in the paused state, in the background.   

**So my possibly related question:**
When a live audio stream is paused, is the buffering consuming memory?  (I guess it has to go somewhere?) if so will Android eventually kill the service when the buffer gets too big and it's consuming too much memory.

**Comment by marcbaechinger** [comment] 2021-07-21 13:59
When a live stream is paused data is buffered up to the limit defined by the `DefaultLoadControl`. By default this is 50 seconds of media I think. It does not indefinitely keep buffering.

When you say it is killed when paused I'm a bit surprised, because you ignore the ongoing flag in your code. It would ideally be like so:

```
@Override
public void onNotificationPosted( int notificationId, Notification notification, boolean ongoing ) {
  if (ongoing) {
     startForeground( notificationId, notification );
 } else {
     stopForeground(/* removeNotification= */ false);
 }   
}
```

then you leave the foreground state when ongoing == false (eg. when paused) which is the right thing to do.

Generally, the problem you have to solve is how to make sure the service is alive as long your UI in the Activity is alive. You can't get around that by making your service life forever. You need to solve that in a way that your UI is aware whether the service is running or not.

One approach is that you [bind to the service](https://developer.android.com/guide/components/bound-services) directly just to make sure the service is not killed while you're bound to it, or you need to make sure to start the service again. When your UI unbinds, then the service is free to be killed by the rules of a foreground service again.

Another approach would be to use a `MediaSession` that you start in your service. Then you can get a `MediaControllerCompat` to it and use it for sending playback commands. When the service is killed you destroy the media session which sends a `onSessionDestroyed()` event to the `MediaControllerCompat.Callback` that you chave registered with mediaController.registerCallback()). If that happened you know you need to start the service again and get a new controller.

I can't give you support into more details of this I'm afraid. I would look into one of these options I explained above/

**Comment by fourofspades** [comment] 2021-07-21 14:11
Many thanks, that is plenty of detail for me to look at.

**Comment by marcbaechinger** [comment] 2021-07-23 14:34
Just checking because it came to mind: can you confirm that with "ExoPlayer UI" you are referring to the `PlayerView` or `StyedPlayerView` and not the notification? If so the above guidance is valid. :)

**Comment by fourofspades** [comment] 2021-07-23 14:39
Using PlayerControlView in a fragment here, and the controls go dead if left paused in the background too long.   The notification has also been destroyed, so it's all related I guess.

**Comment by fourofspades** [comment] 2021-08-06 20:31
Still struggling with this, I believe I am following all the items suggested so far.   One thing I have noticed, on Android 10 (and perhaps earlier), it's possible to swipe away the notification.   Thinking this might indicate a problem....  Edit, false alarm, notification was still there in the extended notification area below it 

I think I'm going to have to throw in the towel on this, and hope that exoplayer team eventually get around to creating a audio demo app that shows how to integrate exoplayer, foreground audio service, mediasesion and notification.  Or someone can find something on GitHub that does it all correctly using recent exoplayer version. (I did a search and came up empty handed)

**Comment by fourofspades** [comment] 2021-08-28 12:59
@marcbaechinger  Still hugely struggling with this, going round and round in circles.   The best place I got to, was this:

source of audio foreground service:

https://pastebin.com/rV2QcGeH

It's not ideal, I can't retain a notification when the player is paused, which means users can't play/pause from the notification, but it does at least fix the unresponsive play button.

It's also weird that my notifications are swipe-able (on Android 12).  It's been mentioned that they shouldn't be, if the service is bound to the notification manager.

**Comment by ojw28** [comment] 2021-09-06 22:04
For what it's worth, I'm not convinced that your base assumptions are valid. In particular:

> Android kills my background service after a while. When the user presses the play button in the ExoPlayer UI, it doesn't do anything anymore, as the service has been killed by the OS.

I don't think this is how Android works. If Android kills anything, it kills your entire process (which, unless you've done something special, includes both your service and your UI).

**Comment by fourofspades** [comment] 2021-09-07 06:31
It's kind of hard to work out what was actually going on. Android 12 allowed me to swipe away the media notifications (but same code on older Android z they are persistent).

In the end, I didn't use the UI control, I changed to a imageview where I change the icons manually, all my problems have disappeared.

This one probably now falls into the "no audio player sample code" issue, where we can see how it's supposed to be wired up.  #8979 #5854

**Comment by ojw28** [comment] 2021-09-09 13:04
Ok. Let's close this as a duplicate of #5854. We do understand that creating audio apps is proving troublesome for developers, in absence of a sample.

**Closed as completed by ojw28** 2021-09-09 13:04 UTC
Labels: duplicate, question
