### ISSUE TITLE
ClippingMediaSource not working

### ISSUE THREAD

**Issue by amrkhalil22** [google/ExoPlayer#2839] opened 2017-05-17 21:40 UTC
I want to play video from external storage and play specific range ( from-> to ).
I'm trying to use "ClippingMediaSource", but a black screen is shown always.

here is my code 
`String videoLocation = "/storage/emulated/0/WhatsApp/Media/WhatsApp Video/VID-20170506-WA0047.mp4";

MediaSource mediaSource = new ExtractorMediaSource(Uri.fromFile(new File(videoLocation)),
                buildDataSourceFactory(), new DefaultExtractorsFactory(), null, null);
        Long normailzedStartTime = 0L;
        Long normailzedEndTime = 3L;

        ClippingMediaSource clip = new ClippingMediaSource(mediaSource, normailzedStartTime, normailzedEndTime);
        exoPlayer = ExoPlayerFactory.newSimpleInstance(getContext(), new DefaultTrackSelector(null));
        exoPlayer.prepare(clip);
        exoPlayer.setPlayWhenReady(false);
`

exoplayer version : r2.4.0
Device : Nexus 5
Android vesion : M

**Comment by andrewlewis** [comment] 2017-05-17 21:48
The end time looks too small -- the unit for the start/end position parameters is microseconds (as documented). For example, to play the first three seconds you'd pass 0 and 3000000 as the start and end positions

**Comment by amrkhalil22** [comment] 2017-05-17 22:00
@andrewlewis Thanks you for the quick answer.
I have changed values to be:
from 0L
to 3000000L 
but the same issue occurs.

**Comment by andrewlewis** [comment] 2017-05-17 22:01
To investigate further we'd need the information requested in the issue template, especially a link to the media you're trying to play.

**Comment by amrkhalil22** [comment] 2017-05-17 22:06
@andrewlewis Sorry, I don't know where can I find the issue template ?
link media that I'm trying to play is from external storage 
like this for example:
"String videoLocation = "/storage/emulated/0/WhatsApp/Media/WhatsApp Video/VID-20170506-WA0047.mp4"
MediaSource mediaSource = new ExtractorMediaSource(Uri.fromFile(new File(videoLocation)),

**Comment by amrkhalil22** [comment] 2017-05-17 22:12
@andrewlewis I noticed now the sound of video is playing but video screen still black.

**Comment by andrewlewis** [comment] 2017-05-17 22:13
[Here's the issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). It's useful to be able to reproduce the error, so we need a link to the actual file you're trying to play. Please either attach it here, or email it to dev.exoplayer@gmail.com.

**Comment by amrkhalil22** [comment] 2017-05-17 22:52
**Issue description**

Want to play video from external storage and play specific range ( from-> to ).
I'm trying to use "ClippingMediaSource", the sound is working but a black screen is shown always.

**Reproduction steps**

Simply play any video from external storage and use ClippingMediaSource.

**Link to test content**

Happens on every video from external storage.

**Version of ExoPlayer being used**

r2.4.0

**Device(s) and version(s) of Android being used**

Nexus 5 
Android version: M

**A full bug report captured from the device**
05-18 00:50:14.189   820   820 W Binder_4: type=1400 audit(0.0:2967633): avc: denied { ioctl } for path="socket:[5504682]" dev="sockfs" ino=5504682 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
05-18 00:50:14.189   820   820 W Binder_4: type=1400 audit(0.0:2967634): avc: denied { ioctl } for path="socket:[5504682]" dev="sockfs" ino=5504682 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
05-18 00:50:14.261 29705 29705 I ExoPlayerImpl: Init ExoPlayerLib/2.4.0 [hammerhead, Nexus 5, LGE, 23]
05-18 00:50:14.462 29705 29705 D CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
05-18 00:50:14.612 29705 30081 W VideoCapabilities: Unrecognized profile 2130706433 for video/avc
05-18 00:50:14.660 29705 30081 I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
05-18 00:50:14.686 29705 30095 I OMXClient: Using client-side OMX mux.
05-18 00:50:14.733 29705 29705 D CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
05-18 00:50:14.924 29705 30095 E OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
05-18 00:50:14.949 29705 29705 D CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
05-18 00:50:15.022 29705 29705 D CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
05-18 00:50:15.106 29705 30115 I SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
05-18 00:50:15.146 29705 29705 I Choreographer: Skipped 50 frames!  The application may be doing too much work on its main thread.
05-18 00:50:15.152   201   799 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=4
05-18 00:50:15.162   201   799 D audio_hw_primary: select_devices: out_snd_device(5: headphones) in_snd_device(0: none)
05-18 00:50:15.162   201   799 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(5) acdb_id(10)
05-18 00:50:15.162   201   799 D audio_hw_primary: enable_snd_device: snd_device(5: headphones)
05-18 00:50:15.172   201   799 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
05-18 00:50:15.229  1795  1795 W Binder_8: type=1400 audit(0.0:2967635): avc: denied { ioctl } for path="socket:[5501890]" dev="sockfs" ino=5501890 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
05-18 00:50:15.229  1795  1795 W Binder_8: type=1400 audit(0.0:2967636): avc: denied { ioctl } for path="socket:[5501890]" dev="sockfs" ino=5501890 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
05-18 00:50:15.246   779   809 I ActivityManager: Displayed /.presentation.ui.activities.MainActivity: +2s505ms
05-18 00:50:16.447  2673  2673 E WorkerRegistryImpl: getWorker() is called after WorkerRegistry disposal.
05-18 00:50:16.448  2673  2673 E WorkerRegistryImpl: getWorker() is called after WorkerRegistry disposal.
05-18 00:50:16.664  6503  6624 D ClClient: Not sending keepalive.  Current connection state=STOPPED
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967637): avc: denied { getattr } for path="/proc/1" dev="proc" ino=5477812 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:init:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967638): avc: denied { search } for name="1" dev="proc" ino=5477812 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:init:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967639): avc: denied { search } for name="1" dev="proc" ino=5477812 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:init:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967640): avc: denied { getattr } for path="/proc/2" dev="proc" ino=5477813 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967641): avc: denied { search } for name="2" dev="proc" ino=5477813 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967642): avc: denied { search } for name="2" dev="proc" ino=5477813 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967643): avc: denied { getattr } for path="/proc/3" dev="proc" ino=5477814 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967644): avc: denied { search } for name="3" dev="proc" ino=5477814 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967645): avc: denied { search } for name="3" dev="proc" ino=5477814 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967646): avc: denied { getattr } for path="/proc/7" dev="proc" ino=5477815 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967647): avc: denied { search } for name="7" dev="proc" ino=5477815 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967648): avc: denied { search } for name="7" dev="proc" ino=5477815 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967649): avc: denied { getattr } for path="/proc/8" dev="proc" ino=5477816 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967650): avc: denied { search } for name="8" dev="proc" ino=5477816 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967651): avc: denied { search } for name="8" dev="proc" ino=5477816 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967652): avc: denied { getattr } for path="/proc/13" dev="proc" ino=5477817 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967653): avc: denied { search } for name="13" dev="proc" ino=5477817 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967654): avc: denied { search } for name="13" dev="proc" ino=5477817 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967655): avc: denied { getattr } for path="/proc/14" dev="proc" ino=5477818 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967656): avc: denied { search } for name="14" dev="proc" ino=5477818 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967657): avc: denied { search } for name="14" dev="proc" ino=5477818 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967658): avc: denied { getattr } for path="/proc/18" dev="proc" ino=5477819 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967659): avc: denied { search } for name="18" dev="proc" ino=5477819 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967660): avc: denied { search } for name="18" dev="proc" ino=5477819 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967661): avc: denied { getattr } for path="/proc/19" dev="proc" ino=5477820 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967662): avc: denied { search } for name="19" dev="proc" ino=5477820 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967663): avc: denied { search } for name="19" dev="proc" ino=5477820 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967664): avc: denied { getattr } for path="/proc/20" dev="proc" ino=5477821 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967665): avc: denied { search } for name="20" dev="proc" ino=5477821 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967666): avc: denied { search } for name="20" dev="proc" ino=5477821 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967667): avc: denied { getattr } for path="/proc/22" dev="proc" ino=5477822 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967668): avc: denied { search } for name="22" dev="proc" ino=5477822 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967669): avc: denied { search } for name="22" dev="proc" ino=5477822 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967670): avc: denied { getattr } for path="/proc/23" dev="proc" ino=5477823 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967671): avc: denied { search } for name="23" dev="proc" ino=5477823 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967672): avc: denied { search } for name="23" dev="proc" ino=5477823 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967673): avc: denied { getattr } for path="/proc/24" dev="proc" ino=5477824 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:17.689 30208 30208 W ps      : type=1400 audit(0.0:2967674): avc: denied { search } for name="24" dev="proc" ino=5477824 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
05-18 00:50:18.025   779   788 I art     : Background partial concurrent mark sweep GC freed 109090(8MB) AllocSpace objects, 3(60KB) LOS objects, 23% free, 52MB/68MB, paused 2.099ms total 214.955ms
05-18 00:50:18.590 29705 29826 V FA      : Inactivity, disconnecting from the service

**Comment by andrewlewis** [comment] 2017-05-17 23:23
We also need the MP4 you're trying to play (attached here or emailed).

**Comment by amrkhalil22** [comment] 2017-05-18 20:11
@andrewlewis I have sent video to dev.exoplayer@gmail.com.

**Comment by AliAbozaid** [comment] 2017-05-18 23:23
Hello @andrewlewis I face the same problem do you have any suggestions!

**Comment by amrkhalil22** [comment] 2017-05-19 02:31
@andrewlewis I have tried the code with the Demo app and its working, but same code is not working in my project!
Is there any difference between Exoplayer in Demo app and version "r2.4.0" which I'm using?

**Comment by amrkhalil22** [comment] 2017-05-19 19:16
@andrewlewis I found when I use my code in Activity the video is working well, but the same code is not working with Fragment! 
Only video's sound is working with Fragment and black screen is shown.
Do you have any idea?

**Comment by andrewlewis** [comment] 2017-05-20 17:22
If the issue isn't reproducible in the demo app, there isn't much we can do to help. It sounds like there might be an issue with how you're passing the surface to the player but it's difficult to say.

Closing for now as this doesn't seem to be a problem with ClippingMediaSource.

**Closed as completed by andrewlewis** 2017-05-20 17:22 UTC
Labels: question

**Comment by amrkhalil22** [comment] 2017-05-20 17:27
@andrewlewis Did you try ClippingMediaSource with Fragments ?
It's working with Activity but not working with Fragment.

**Comment by andrewlewis** [comment] 2017-05-20 17:59
I haven't, but I'm having trouble coming up with any reason this would be affected by using a Fragment vs an Activity, unless your app is doing something different with how it handles Surfaces in the two cases.

Are you using SimpleExoPlayerView? If so, maybe set a breakpoint in `onRenderedFirstFrame` to verify that it's getting called to hide the `shutterView`. Could you make a small patch to the demo app that puts the SimpleExoPlayerView in a Fragment to demonstrate the issue?

Do you see video if you don't use ClippingMediaSource but just play the unclipped MediaSource?

**Comment by amrkhalil22** [comment] 2017-05-22 19:50
@andrewlewis I'm very sorry! 
I have tried to play with MediaSource and it didn't work also, then I noticed that 
`simpleExoPlayerView.setPlayer(exoPlayer)`
was forgotten!
Sorry again.

**Comment by andrewlewis** [comment] 2017-05-23 08:53
@AmrMohammed89 Glad to hear it's fixed.

@AliAbozaid Please file a new issue if you still have the same problem.
