### ISSUE TITLE
No tracks info received for TS in non-HLS mode

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#4666] opened 2018-08-15 22:25 UTC
This issue was introduced with changes made in commit: 4f57c46560006f188d6c8cf64aa3d7ffc003368c

Rolling back that changes on top of 8854aa415fbc39def3dfbd9c97d3a25812305999 fixes the problem.

I can reproduce the problem using next setup:
* https://play.google.com/store/apps/details?id=org.acestream.media.atv (provides local server which re-streams p2p content via http). Sorry for 3rd party app, but it's a bit difficult to grab it's stream from device itself
* http://localhost:6878/ace/getstream?url=http%3A%2F%2Fcontent.asplaylist.net%2Fcdn%2F334_all.acelive
* NVidia Shield

In 90% of attempts to play stream using Demo Player I do not get tracks info and no playback started.
Logs from successful and failed attempts:

```
2018-08-15 23:30:34.344 12396-12396 I/ExoPlayerImpl: Init 7f1d4ce [ExoPlayerLib/2.8.3] [foster, SHIELD Android TV, NVIDIA, 26]
2018-08-15 23:30:34.348 12396-12396 D/EventLogger: state [0.00, 0.00, window=0, true, BUFFERING]
2018-08-15 23:30:34.358 12396-12396 D/EventLogger: timelineChanged [0.01, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
2018-08-15 23:30:34.358 12396-12396 D/EventLogger:   period [?]
2018-08-15 23:30:34.358 12396-12396 D/EventLogger:   window [?, false, false]
2018-08-15 23:30:34.358 12396-12396 D/EventLogger: ]
2018-08-15 23:30:34.359 12396-12396 D/EventLogger: mediaPeriodCreated [0.01, 0.00, window=0, period=0]
2018-08-15 23:30:34.360 12396-12396 D/EventLogger: loading [0.01, 0.00, window=0, period=0, true]
2018-08-15 23:30:34.392 12396-12396 D/EventLogger: surfaceSizeChanged [0.05, 0.00, window=0, period=0, 1920, 1080]
2018-08-15 23:30:34.430 12396-12439 D/OpenGLRenderer: endAllActiveAnimators on 0x2e1b63bc00 (ExpandableListView) with handle 0x2e0d1f7200
2018-08-15 23:30:35.404 12396-12396 D/EventLogger: decoderEnabled [1.06, 0.00, window=0, period=0, video]
2018-08-15 23:30:35.405 12396-12396 D/EventLogger: decoderEnabled [1.06, 0.00, window=0, period=0, audio]
2018-08-15 23:30:35.406 12396-12396 D/EventLogger: tracksChanged [1.06, 0.00, window=0, period=0, 
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:   Renderer:0 [
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:     Group:0, adaptive_supported=N/A [
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:       [X] Track:0, id=1/256, mimeType=video/avc, codecs=avc1.64001E, res=720x576, supported=YES
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:     ]
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:   ]
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:   Renderer:2 [
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:     Group:0, adaptive_supported=N/A [
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:       [X] Track:0, id=1/257, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=eng, supported=YES
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:     ]
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:   ]
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:   Renderer:6 [
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:     Group:0, adaptive_supported=N/A [
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:       [ ] Track:0, id=1/8448, mimeType=application/cea-608, supported=YES
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:     ]
2018-08-15 23:30:35.406 12396-12396 D/EventLogger:   ]
2018-08-15 23:30:35.406 12396-12396 D/EventLogger: ]
2018-08-15 23:30:35.421 12396-12396 D/EventLogger: mediaPeriodReadingStarted [1.08, 0.00, window=0, period=0]
```

```
2018-08-15 23:30:46.688 12396-12396 I/ExoPlayerImpl: Init 7342d48 [ExoPlayerLib/2.8.3] [foster, SHIELD Android TV, NVIDIA, 26]
2018-08-15 23:30:46.692 12396-12396 D/EventLogger: state [0.00, 0.00, window=0, true, BUFFERING]
2018-08-15 23:30:46.739 12396-12396 D/EventLogger: surfaceSizeChanged [0.05, 0.00, window=0, 1920, 1080]
2018-08-15 23:30:46.740 12396-12396 D/EventLogger: timelineChanged [0.05, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
2018-08-15 23:30:46.741 12396-12396 D/EventLogger:   period [?]
2018-08-15 23:30:46.741 12396-12396 D/EventLogger:   window [?, false, false]
2018-08-15 23:30:46.741 12396-12396 D/EventLogger: ]
2018-08-15 23:30:46.742 12396-12396 D/EventLogger: mediaPeriodCreated [0.05, 0.00, window=0, period=0]
2018-08-15 23:30:46.743 12396-12396 D/EventLogger: loading [0.05, 0.00, window=0, period=0, true]
2018-08-15 23:30:46.899 12396-12396 D/EventLogger: timelineChanged [0.21, 0.00, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
2018-08-15 23:30:46.899 12396-12396 D/EventLogger:   period [0.00]
2018-08-15 23:30:46.900 12396-12396 D/EventLogger:   window [0.00, false, false]
2018-08-15 23:30:46.900 12396-12396 D/EventLogger: ]
```

**Comment by AquilesCanta** [comment] 2018-08-20 19:46
I have started looking at this and can reproduce. If you manage to capture a stream that reproduces consistently, please don't hesitate to share it with me. It would save lots of time.

**Comment by AquilesCanta** [comment] 2018-08-21 14:17
The issue seems to be actually caused by an sporadic server error which seems to be accentuated by opening connections in quick succession. A mitigation fix for this will be pushed soon, but this does do anything to work around faulty server behavior.

**Closed as completed** 2018-08-28 11:07 UTC
Labels: bug

**Comment by AquilesCanta** [comment] 2018-08-28 11:08
Please give it a try and let us know whether this fixes your issue.

**Comment by stari4ek** [comment] 2018-09-25 19:25
Checked with current HEAD.
Works well. Thank you
