### ISSUE TITLE
IMA extension doesn't play correctly VAST with 2 and more ads

### ISSUE THREAD

**Issue by nsyedin** [google/ExoPlayer#7281] opened 2020-04-23 09:16 UTC
IMA extension doesn't play correctly VAST with 2+ ads. Second ad is skipped on pause/resume.
Steps to reproduce:
1. Get any VAST with 2 or more ads, for ex https://raw.githubusercontent.com/nsyedin/adtest/master/bug.xml (3 ads)
2. Finish 1st ad(skip or complete)
3. Ensure 2nd ad is loaded and displayed
3. Move application to background with Home button(or pause video)
4. Restore application(or resume video)

Observed result: 2nd ad is completed, 3rd ad is started
Expected result: 2nd ad continues from the same position

The same result is observed on the latest IMA SDK BasicExample with ExoPlayer components v2.11.1. IMA SDK AdvancedExample works as expected, 2nd ad continues from the same position.
ExoPlayer branch: release-v2
ExoPlayer commit: 7d3f54a375fac04a746ca76a8f2e1ad32c8b45b2(Wed Apr 8 22:48:19 2020) - latest
[ExoPlayer-demo.log](https://github.com/google/ExoPlayer/files/4521379/ExoPlayer-demo.log)
[ExoPLayer-demo.patch](https://raw.githubusercontent.com/nsyedin/adtest/master/bugrep/ExoPLayer-demo.patch)
[ExoPlayer-demo.mp4](https://github.com/nsyedin/adtest/blob/master/bugrep/ExoPlayer-demo.mp4)
[BasicExample.mp4](https://github.com/nsyedin/adtest/blob/master/bugrep/BasicExample.mp4)
[AdvancedExample.mp4](https://github.com/nsyedin/adtest/blob/master/bugrep/AdvancedExample.mp4)

**Comment by andrewlewis** [comment] 2020-04-27 07:38
I think this is a bug with preloading in the IMA SDK (already tracked by #4140) that will be fixed as part of upgrading to use new preloading APIs (that is tracked by #6429). I will mark this as a duplicate of #4140 for now.

**Comment by andrewlewis** [comment] 2020-04-27 07:38
Duplicate of #4140

**Closed as completed by andrewlewis** 2020-04-27 07:38 UTC
Labels: duplicate
