### ISSUE TITLE
How to store video cache index using ExoDatabaseProvider? and retrieve it later?

### ISSUE THREAD

**Issue by nirazv** [google/ExoPlayer#7918] opened 2020-09-15 15:29 UTC
Using CacheWriter.cache method i created video cache but How do i can store the current completed cache index in ExoDatabaseProvider and 

How to retrieve it to play video in ExoPlayer? 
please share some codes..

My Code for Creating/Downloading video and storing it in cache using [CacheWriter](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/cache/CacheWriter) class

> 
```
ExoDatabaseProvider exoDatabaseProvider = new ExoDatabaseProvider(context);
DataSpec dataSpec = new DataSpec(Uri.parse(videoUrl));
SimpleCache simpleCache = new SimpleCache(getCacheDir(),leastRecentlyUsedCacheEvictor,exoDatabaseProvider);
CacheDataSource cacheDataSource = new CacheDataSource(simpleCache, new DefaultHttpDataSource());
CacheWriter cacheWriter = new CacheWriter(cacheDataSource,dataSpec,false,null,this);
cacheWriter.cache();
```
>

**Comment by icbaker** [comment] 2020-09-15 15:44
You can't store anything in `ExoDatabaseProvider`. It's an implementation of [SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper) - i.e. it provides/helps you open a DB.

It's not clear from your code what you're trying to do.

You probably don't want to call `CacheWriter#cache()` directly - it's generally called by a `Downloader` implementation.

Are you trying to download videos, or just cache them for a single playback?

You might want to read through https://exoplayer.dev/downloading-media.html if you haven't already.

**Comment by icbaker** [comment] 2020-09-15 16:20
This issue looks like a duplicate of a question over here where @marcbaechinger was already helping you: https://github.com/google/ExoPlayer/issues/7887#issuecomment-692622184

I'll close this and let them help you out since they already have context of what you're trying to do.

**Closed as completed by icbaker** 2020-09-15 16:20 UTC
Labels: duplicate
