### ISSUE TITLE
Artifacts on video

### ISSUE THREAD

**Issue by AntonAndev** [google/ExoPlayer#1921] opened 2016-10-10 12:12 UTC
Hello, I use SimpleExoPlayer and SimpleExoPlayerView to display a video. I see artifacts on video on different streams. I made a following test: in the web admin panel of media server opened a stream in the JWPlayer, opened the same stream in my Android app using r.2.0.2 on device Sony Z3 Compact (Android 6) and using r.2.0.1 on device LG Spirit (Android 6) and in my app for iOS on iPad (AVPlayer). Problem with artifacts occurs only on Android app with both versions of SimpleExoplayer and doesn't occur on Web JWPlayer and iOS app with AVPlayer at the same time of the same stream. Problem occurs randomly.

**Comment by AntonAndev** [comment] 2016-10-15 19:29
Hello, were you able to reproduce a problem on example streams?

**Comment by marcbaechinger** [comment] 2016-10-17 14:52
Hi. Thanks for you report. 
Can you please check this post about what information we need to handle an issue? Many thanks: https://medium.com/google-exoplayer/howto-1-reporting-an-issue-56a3ed73a5

**Comment by AntonAndev** [comment] 2016-10-20 12:45
Hello, I made some tests, these artifacts occur when playing with ExoPlayer HLS streams from Nimble media server, and doesn't occur when playing with ExoPlayer DASH streams from the same Nimble media server. I sent this info to developers of Nimble. Strange thing is why other players play Nimble's HLS without artifacts.

**Comment by AntonAndev** [comment] 2016-10-24 10:22
Hello, I sent new links now to your email, these links - recorded video (dvr) in m3u8, so it is easy to see artifacts now.

**Comment by AquilesCanta** [comment] 2016-10-24 10:32
Have you checked that this is not related to #1978?

**Comment by AquilesCanta** [comment] 2016-10-24 10:34
Also, can you reproduce the issue in V1?

**Comment by AntonAndev** [comment] 2016-10-24 13:47
Hello, similar to #1978 but I reproduced it in V1 demo app.

**Comment by AntonAndev** [comment] 2016-10-25 18:56
Workaround: add "hls_reset_video_audio_cc = false" in nimble.conf and restart nimble service. Now video without artifacts in ExoPlayer.

**Comment by AquilesCanta** [comment] 2016-12-07 10:37
Closing as this is most likely a duplicate of #1978 and no update has been made.

**Closed as completed by AquilesCanta** 2016-12-07 10:37 UTC
Labels: need more info
