### ISSUE TITLE
Slower playback with widevine on dash stream

### ISSUE THREAD

**Issue by SteUK** [google/ExoPlayer#1983] opened 2016-10-21 17:53 UTC
Hi,

I am seeing playback of an h265 2880x1920 15mbit dash stream not make 30fps on a Samsung s7 when I widevine encrypt it. Is this to be expected in exo player due to the nature of drm?

This is with ExoPlayer2 release-v2. And it is the video decode rate that is dropping below the 30fps of the source...app holds near enough 60 and above. Averaging over every second, I am seeing decode rates of 26fps on occasion, but mainly it is just dipping below the 30 to 28 or so. Another stream I have tried has been as low as 22fps.

Streams are encoded with nvidia hevc using the slow preset and goo of 60 frames. Segmenting for dash at 4 second intervals.

Thanks!

**Comment by ojw28** [comment] 2017-01-30 21:02
I think this is a duplicate of #1764 (and should be fixed by the latest Samsung platform update).

**Closed as completed by ojw28** 2017-01-30 21:02 UTC
Labels: duplicate, bug: device specific
