### ISSUE TITLE
Failed to query underlying media codecs

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#1577] opened 2016-06-07 12:02 UTC
Hi,
We are getting the following exception while playing HLS.

Android Version : 4.2.2
Exoplayer Version : 1.5.8

The same HLS live stream is playing with Android Media Player. But in exoplayer it gives the following error.
```
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
E/EventLogger( 8408): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
E/EventLogger( 8408): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
E/EventLogger( 8408): 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
E/EventLogger( 8408): 	at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:264)
E/EventLogger( 8408): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
E/EventLogger( 8408): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/EventLogger( 8408): 	at android.os.Looper.loop(Looper.java:137)
E/EventLogger( 8408): 	at android.os.HandlerThread.run(HandlerThread.java:60)
E/EventLogger( 8408): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/EventLogger( 8408): Caused by: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
E/EventLogger( 8408): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:165)
E/EventLogger( 8408): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:115)
E/EventLogger( 8408): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:76)
E/EventLogger( 8408): 	at com.google.android.exoplayer.MediaCodecUtil.maxH264DecodableFrameSize(MediaCodecUtil.java:298)
E/EventLogger( 8408): 	at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.isFormatPlayable(VideoFormatSelectorUtil.java:168)
E/EventLogger( 8408): 	at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormats(VideoFormatSelectorUtil.java:102)
E/EventLogger( 8408): 	at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormatsForDefaultDisplay(VideoFormatSelectorUtil.java:60)
E/EventLogger( 8408): 	at com.google.android.exoplayer.hls.DefaultHlsTrackSelector.selectTracks(DefaultHlsTrackSelector.java:87)
E/EventLogger( 8408): 	at com.google.android.exoplayer.hls.HlsChunkSource.prepare(HlsChunkSource.java:253)
E/EventLogger( 8408): 	at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:149)
E/EventLogger( 8408): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:54)
E/EventLogger( 8408): 	at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110)
E/EventLogger( 8408): 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:273)
E/EventLogger( 8408): 	... 6 more
E/EventLogger( 8408): Caused by: java.lang.IllegalArgumentException
E/EventLogger( 8408): 	at android.media.MediaCodecList.getCodecCapabilities(Native Method)
E/EventLogger( 8408): 	at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:211)
E/EventLogger( 8408): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:147)
```
Do we need to add this codec manually? But as native player is playing the same stream, there shouldn't be a issue with hardware codec supports right?

Please advice,
Regards,
Randeep

**Comment by ojw28** [comment] 2016-06-07 12:08
Please can your try with the current dev branch? This was probably fixed by https://github.com/google/ExoPlayer/commit/82ef94e30b7daa1825b7f88aa48680e7257df5a9. Thanks!

**Comment by randeeppr** [comment] 2016-06-09 08:32
Hi @ojw28 
We tried with the dev branch. Still we are getting the same.

```
E/ExoPlayerImplInternal( 4670): Internal track renderer error.
E/ExoPlayerImplInternal( 4670): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:275)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:264)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
E/ExoPlayerImplInternal( 4670): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/ExoPlayerImplInternal( 4670): 	at android.os.Looper.loop(Looper.java:137)
E/ExoPlayerImplInternal( 4670): 	at android.os.HandlerThread.run(HandlerThread.java:60)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal( 4670): Caused by: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:186)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:129)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:106)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.MediaCodecUtil.maxH264DecodableFrameSize(MediaCodecUtil.java:325)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.isFormatPlayable(VideoFormatSelectorUtil.java:168)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormats(VideoFormatSelectorUtil.java:102)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormatsForDefaultDisplay(VideoFormatSelectorUtil.java:60)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.hls.DefaultHlsTrackSelector.selectTracks(DefaultHlsTrackSelector.java:87)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.hls.HlsChunkSource.prepare(HlsChunkSource.java:253)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:149)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:54)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:273)
E/ExoPlayerImplInternal( 4670): 	... 6 more
E/ExoPlayerImplInternal( 4670): Caused by: java.lang.IllegalArgumentException
E/ExoPlayerImplInternal( 4670): 	at android.media.MediaCodecList.getCodecCapabilities(Native Method)
E/ExoPlayerImplInternal( 4670): 	at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:211)
E/ExoPlayerImplInternal( 4670): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:160)
E/ExoPlayerImplInternal( 4670): 	... 18 more
```
Also most of our videos are HD. 

Regards,
Randeep

**Comment by ojw28** [comment] 2016-06-09 08:38
You'll need to provide a full bug report (captured with `adb bugreport` for us to look at this further).

**Comment by randeeppr** [comment] 2016-06-12 10:18
@ojw28 
bug report sent to dev.exoplayer@gmail.com
Please check.

**Comment by ojw28** [comment] 2016-06-13 10:39
I think it's a device specific issue. The device doesn't appear to have passed Android's compatibility test suite (https://source.android.com/compatibility/cts/) and also appears to be running a fairly strange looking eng build. You should report the issue to the device manufacturer.

In addition, we'll see if we can come up with a workaround for the issue, and will add additional logging to determine exactly which decoder is causing the issue.

**Comment by randeeppr** [comment] 2016-06-14 07:32
@ojw28 Its an Android set up box. Can you please let us know what exactly is happening? is it because its 4.2.2? Exoplayer works in 4.2.2 right? Please let me know if more logs are enabled. Then I can try it with the new build.

**Comment by ojw28** [comment] 2016-06-14 08:57
The underlying device/platform is broken. You should report the issue to the device manufacturer. It should be pretty straightforward for them to work out what's going on. This error occurs in platform code, and should not happen:

```
E/ExoPlayerImplInternal( 4670): Caused by: java.lang.IllegalArgumentException
E/ExoPlayerImplInternal( 4670):     at android.media.MediaCodecList.getCodecCapabilities(Native Method)
E/ExoPlayerImplInternal( 4670):     at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:211)
```

**Comment by nimukup** [comment] 2016-06-14 10:31
@ojw28  , This is Randeep's Colleague , I have checked the Code below framework to understand the flow , It seems API everything is fine. Also I attached media_codecs.conf file in the device /etc/media_codec.xml. This is board from Broadcom and they uses thier own Nexus middleware to play. It will be difficult now to get support from them. Could you please give me a work around to this from the player or more specific where I need to check in android source ?

[media_codecs.txt](https://github.com/google/ExoPlayer/files/313692/media_codecs.txt)

**Comment by ojw28** [comment] 2016-06-14 11:36
The code underneath the platform is throwing an `IllegalArgumentException` as shown above, which seems to be at odds with your statement that it's fine. Please clarify. Is it possible for you to root cause exactly why this exception is being thrown?

**Comment by ojw28** [comment] 2016-06-14 18:17
Some extra logging was added in https://github.com/google/ExoPlayer/commit/a68d5243828289568977c1dc91fd9baf20336682 that will print the name of the decoder for which the query fails. It would be good to know what this is, so if you could attach another bug report that would be great.

**Comment by nimukup** [comment] 2016-06-15 03:11
@ojw28 

with extra loggings , we have the exact bug 
frameworks/av/media/libstagefright/MediaCodecList.cpp
CodecCapabilities caps;
    err = QueryCodec(
            client.interface(),
            info.mName.c_str(), type, info.mIsEncoder, &caps);
Here it failed. 
Seems like in libstagefright , broadcom is not implemented any OMX plugin instead they have written NexusPlayer.cpp ,which is like AwesomePlayer.cpp. And they are calling this NexusPlayer from media/libmediaplayerservice/StagefrightPlayer.cpp . 
This is the reason exoplayer failed to get the codec information, Is there any way we can make it make work ? Please let us know.

**Comment by ojw28** [comment] 2016-06-15 07:19
Sorry, but this is something you need to talk to Broadcom about. If the underlying support just isn't there in the platform, then ExoPlayer isn't going to work.

**Closed by ojw28** 2016-06-15 07:19 UTC
Labels: device specific issue, need more info
