### ISSUE TITLE
DRM download example required.

### ISSUE THREAD

**Issue by gowthamkrishnabj** [google/ExoPlayer#8416] opened 2020-12-31 05:17 UTC
Required some information/sample project regarding DRM download, with offline playback. The current demo project download feature doesn't support a download of  DRM content.

**Comment by ojw28** [comment] 2021-01-03 18:56
Duplicate of https://github.com/google/ExoPlayer/issues/7347. Please search for existing issues before filing new ones; Thanks!

**Closed as completed by ojw28** 2021-01-03 18:56 UTC
Labels: duplicate
