### ISSUE TITLE
vp8 decode error

### ISSUE THREAD

**Issue by kuailedeadai** [google/ExoPlayer#7343] opened 2020-05-07 09:36 UTC
Hello, may I ask if I added the adaptation of vp8 in the vp9 extension, added vp8 decoding in generate_libvpx_android_configs.sh, the compilation shows that it passed, and the vp8 module has been integrated, but when running, the vp8 decoding error Decode error: Bitstream not supported by this decoder

**Comment by andrewlewis** [comment] 2020-05-07 10:02
It's difficult to know the cause based on the information you've provided, but one thing to note is that in `vpx_jni.cc` in the VP9 extension you will need to initialize the right codec in the call to `vpx_codec_dec_init` (you can use `get_vpx_decoder_by_name` to get the right codec interface to pass into that method). Caveat: last time I did this was in 2016 so the APIs may have changed!

As this is not something we support at the moment, and it seems unlikely we would add support given it hasn't been requested and the codec has been superseded, I will close this for now.

**Closed as completed by andrewlewis** 2020-05-07 10:02 UTC
Labels: question

**Comment by kuailedeadai** [comment] 2020-05-07 11:45
Thanks, your suggestion has solved my problem
