### ISSUE TITLE
Cache dataSource implementation

### ISSUE THREAD

**Issue by harikautilya** [google/ExoPlayer#3075] opened 2017-07-17 15:53 UTC
Hey here is an example which i implemented for cache datasource . I searched a lot for examples but couldn't find any . Figured it out-Some-How. Please test it and integrate if it correct. 

```
private LoopingMediaSource getCacheMediaSource() {
        final Uri thumbailUri = Uri.parse(videoThumbUrl);

        final DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(itemView.getContext(),
                Util.getUserAgent(itemView.getContext(), "application"));
        Cache cache = new SimpleCache(itemView.getContext().getCacheDir(), new LeastRecentlyUsedCacheEvictor(1024 * 1024 * 10));
        CacheDataSourceFactory cacheDataSourceFactory = new CacheDataSourceFactory(cache, dataSourceFactory, CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR);

        final MediaSource mediaSource = ExoPlayerHelper.buildMediaSource(itemView.getContext(),
                thumbailUri,
                cacheDataSourceFactory,
                itemView.getHandler(), null);
        return new LoopingMediaSource(mediaSource, Integer.MAX_VALUE - 1);
    }
```

**Comment by ojw28** [comment] 2017-07-17 16:55
This is neither an issue or a question. Closing as duplicate of https://github.com/google/ExoPlayer/issues/2808.

**Closed as completed by ojw28** 2017-07-17 16:55 UTC
Labels: duplicate
