### ISSUE TITLE
Mp4 Video not played

### ISSUE THREAD

**Issue by arcgate-git** [google/ExoPlayer#5996] opened 2019-06-05 09:00 UTC
I am using Exoplayer version 2.10.1 and i have trimmed the video using mp4 parser. Particular trimmed videos play well on device using other players. But in exoplayer I am facing the issue below:

com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.

**Comment by ojw28** [comment] 2019-06-05 09:15
Duplicate of https://github.com/google/ExoPlayer/issues/5988

**Closed as completed by ojw28** 2019-06-05 09:15 UTC
Labels: duplicate
