### ISSUE TITLE
data/mediadrm/IDM1013/L1/cert.bin does not exist

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#8003] opened 2020-09-28 12:38 UTC
### [REQUIRED] Searched documentation and issues
I searched through the existing issues but I could not find any issue similar to this.

### [REQUIRED] Question
I have a DASH Widevine L3 Content that is working on all devices but there is one particular device Nexus Tab | OS 7.1.1 that is having Security Level L1 and HDCP disconnected.  I am getting the error as L1 decoder is not present even though the device itself is L1 Supported. 

Here is the logs
”09-24 23:39:43.855   265   265 W WVCdm   : DeviceFiles::RetrieveHashedFile: /data/mediadrm/IDM1013/L1/cert.bin does not exist”

**The same content gets played if Enforce L3 as Security Level.** 

### A full bug report captured from the device
I have a full adb logs report that was reproduced on the Sample App of Exo Player. Please let me know if you require the bug report as well. I have sent this on email : dev.exoplayer@gmail.com

### Link to test content
Content is private.

**Comment by AquilesCanta** [comment] 2020-09-28 14:38
Please provide the bugreport, as requested in the issue template. Aside, have you tried on any other device with the same model? I wonder if this issue could be specific to the physical device you are using (as opposed to an issue with the device model).

**Comment by Taranlayal10** [comment] 2020-09-29 05:13
Thanks for your prompt response, I have sent the bug report on the email. Unfortunately we do not have the other same device model.

**Comment by Taranlayal10** [comment] 2020-09-30 15:19
Hi @AquilesCanta 

Hope you have received the bug report. Any updates on this?

**Comment by AquilesCanta** [comment] 2020-09-30 15:42
Was this bugreport captured after playing the content in the ExoPlayer demo app? Can you clarifiy which ExoPlayer version it's using? I cannot find a playback exception or some of the usually present demo app log lines.

**Comment by Taranlayal10** [comment] 2020-10-01 11:13
Hello @AquilesCanta 

Bug report was from my application. I have again sent the bug report after reproducing this issue on Sample Exo Player. Please check.

**Comment by Taranlayal10** [comment] 2020-10-05 04:11
Appreciate your response on this.

**Comment by Taranlayal10** [comment] 2020-10-08 07:20
Any updates? This is blocking our release. Please help understanding this issue as this might come in other devices

**Comment by AquilesCanta** [comment] 2020-10-09 15:14
This looks like a duplicate of #7986. The device and observed behavior (HTTP 400) are the same. Unfortunately there's not much we can do on the ExoPlayer side. From #7986:

> If you need more details about Widevine properties and are a Widevine licensee please contact Widevine support at https://www.widevine.com/contact.

Regarding

> Please help understanding this issue as this might come in other devices

We haven't seen this issue in other devices. I did some research on whether widevine has made any announcements about withdrawing support for Nexus 7, but I haven't found any material. I will post below if I learn anything.

I will be closing this under the assumption that there's no actionable items for the ExoPlayer team.

**Note**: Next time you file an issue, please follow all instructions from the issue template in order to (a) reduce the amount of back and forth and (b) encourage us to look into the issue quickly.

**Closed as completed by AquilesCanta** 2020-10-09 15:14 UTC
Labels: duplicate, bug: in platform drm

**Comment by AquilesCanta** [comment] 2020-10-09 17:08
I have just confirmed: Widevine has revoked licensing for some devices, including Nexus 7. There's nothing we can do to help with this, unfortunately. [Internal ref: b/167219582].

**Comment by objectiveCarlo** [comment] 2020-10-10 01:04
hello how to find this list  of devices online? thanks/

**Comment by rrfrias** [comment] 2020-10-11 18:11
@objectiveCarlo, if your company is a Google/Widevine partner, you should contact https://www.widevine.com/contact for more information.
