### ISSUE TITLE
ANR related to Exoplayer and WebView

### ISSUE THREAD

**Issue by waseefakhtar** [google/ExoPlayer#9917] opened 2022-02-01 15:14 UTC
I notice plenty of the following ANRs occurring on plenty of devices and I wonder if you have any idea why that could be and how we can solve it:

```
main (waiting): tid=1 systid=27947
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.google.android.gms.ads.exoplayer3.n.d(n.java:2)
       at com.google.android.gms.ads.internal.video.exoplayer3.ab.ax(ab.java:3)
       at com.google.android.gms.ads.internal.video.gmsg.exoplayer3.e.f(e.java)
       at com.google.android.gms.ads.internal.webview.ac.aS(ac.java)
       at com.google.android.gms.ads.internal.webview.ac.destroy(ac.java:7)
       at com.google.android.gms.ads.internal.webview.y.destroy(y.java:5)
       at com.google.android.gms.ads.internal.webview.q.f(q.java:2)
       at com.google.android.gms.ads.internal.gmsg.y.a(y.java:4)
       at com.google.android.gms.ads.internal.webview.q.i(q.java:3)
       at com.google.android.gms.ads.internal.webview.q.e(q.java:8)
       at com.google.android.gms.ads.internal.webview.ai.run(ai.java:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at auj.a(auj.java)
       at com.google.android.gms.ads.internal.util.f.a(f.java:1)
       at auj.dispatchMessage(auj.java)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8246)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

- ExoPlayer version number: 2.12.0, 2.13.0
- Android version: Android 11, Android 12
- Android device: OPPO, Realme, Xiaomi, OnePlus, etc.

<img src="https://user-images.githubusercontent.com/4093820/151995006-60541637-430a-48a0-8980-b8f25749c0d1.png" width="700"/>

**Comment by tonihei** [comment] 2022-02-01 16:44
This looks the same as an internal reported bug (internal ref: b/211641759). We don't directly control this code as it's part of a Play Services fork of ExoPlayer (note the "exoplayer3" in the stack trace). But most likely, this is caused by ANRs caused when switching surfaces or releasing a player, which may happen in some cases if the underlying MediaCodec is stuck in a faulty state. ExoPlayer added workarounds for this (by failing the player after a timeout instead of letting the app go into the ANR state), but this is not released in this ExoPlayer fork yet (as part of Play Services).

**Closed as completed** 2022-05-10 14:49 UTC
Labels: bug: in platform
