### ISSUE TITLE
TsExtractor bug

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#278] opened 2015-02-04 08:27 UTC
Device android 4.4, Test [link]( https://dn-hls-233-tv-cn-bj-01.qbox.me/54d10b6e695a325d2fa90000/54d11617695a321622c00000/source/index.m3u8), about 3~4 second, the logcat print many below line, frequently gc, and  result in the UI get stuck,(you can add progressbar on the top of surfaceview)
```
 D/dalvikvm( 5562): GC_FOR_ALLOC freed 4962K, 19% free 81591K/100428K, paused 74ms, total 74ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 4971K, 19% free 81592K/100428K, paused 73ms, total 73ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 4979K, 19% free 81593K/100428K, paused 72ms, total 72ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 4988K, 19% free 81594K/100428K, paused 58ms, total 58ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 4997K, 19% free 81596K/100428K, paused 56ms, total 56ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5006K, 19% free 81597K/100428K, paused 58ms, total 58ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5015K, 19% free 81598K/100428K, paused 61ms, total 61ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5023K, 19% free 81599K/100428K, paused 67ms, total 67ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5032K, 19% free 81601K/100428K, paused 62ms, total 62ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5041K, 19% free 81602K/100428K, paused 61ms, total 61ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5051K, 19% free 81604K/100428K, paused 62ms, total 62ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5059K, 19% free 81605K/100428K, paused 59ms, total 59ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5068K, 19% free 81606K/100428K, paused 61ms, total 61ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5076K, 19% free 81607K/100428K, paused 63ms, total 63ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5085K, 19% free 81608K/100428K, paused 59ms, total 59ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5094K, 19% free 81609K/100428K, paused 57ms, total 57ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5103K, 19% free 81611K/100428K, paused 58ms, total 58ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5111K, 19% free 81612K/100428K, paused 62ms, total 62ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5120K, 19% free 81613K/100428K, paused 59ms, total 59ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5129K, 19% free 81615K/100428K, paused 59ms, total 59ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5139K, 19% free 81616K/100428K, paused 71ms, total 71ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5147K, 19% free 81617K/100428K, paused 61ms, total 61ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5155K, 19% free 81619K/100428K, paused 58ms, total 58ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5164K, 19% free 81620K/100428K, paused 58ms, total 58ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5173K, 19% free 81621K/100428K, paused 57ms, total 57ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5182K, 19% free 81622K/100428K, paused 57ms, total 57ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5191K, 19% free 81624K/100428K, paused 55ms, total 55ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5200K, 19% free 81625K/100428K, paused 57ms, total 57ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5208K, 19% free 81626K/100428K, paused 59ms, total 59ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5217K, 19% free 81627K/100428K, paused 58ms, total 58ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5226K, 19% free 81629K/100428K, paused 58ms, total 58ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5235K, 19% free 81630K/100428K, paused 56ms, total 56ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5244K, 19% free 81631K/100428K, paused 56ms, total 56ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5252K, 19% free 81632K/100428K, paused 62ms, total 62ms
D/dalvikvm( 5562): GC_FOR_ALLOC freed 5261K, 19% free 81634K/100428K, paused 72ms, total 72ms
```
if the link no valid for u, you can download from [dropbox](https://www.dropbox.com/sh/p744vis5lv5kkh1/AADVSRb64J1EFNnrUtvptNL2a?dl=0), and use local http server test.

**Comment by mine260309** [comment] 2015-02-04 08:47
It is probably caused by TsExtractor that reads the HTTP data very fast and holds the samples in memory.
You can control the behavior by modify the SampleSource who uses TxExtractor and keep the available samples in a threshold, that limits the memory usage of TsExtractor.

**Comment by crossle** [comment] 2015-02-04 10:04
@mine260309 read HTTP data very fast? why other ts stream normal.

**Comment by mine260309** [comment] 2015-02-04 11:43
Depend on the ts stream (and codec info), TsExtract may discard samples or hold the samples to be rendered.
In my experience, if a chunk of HLS is large (e.g. 100MiB), TsExtract will read as many samples as HTTP downloads, and thus consume too much memory. But in my case there's no such GC logs.

Your case could be different, but you may analyze the heap usage to find which object consume too much memory.

**Comment by johanlindquist** [comment] 2015-02-04 19:48
I would agree with @mine260309 that it is most likely caused by TsExtractor reading too many samples "ahead" in the TS segment.  Occurs especially at high bitrates.  

There is also an issue where there are too many Samples being pooled (in the SamplePool) - this is marked as "We need to fix this"

**Comment by crossle** [comment] 2015-02-05 01:47
@johanlindquist agree.  I trace the GC, found alway allocate `Sample.expand`, result in GC.

**Comment by crossle** [comment] 2015-02-05 14:35
@andudo  How to fix this?

**Comment by Guro** [comment] 2015-02-06 16:54
any easy fix for this? 
i have same problem

**Comment by johanlindquist** [comment] 2015-02-09 16:38
Also, the TsExtractor$Sample will use a lot of byte arrays, which, if pooled correctly, can reduce GC.  

This is especially noticeable when the bitrate (and thus) samples are larger - the samples are all expanded at bitrate switching time.  

Not sure what the ideal situation here is as pooling too many bytes will have a big impact on memory footprint.  But, considering they are being used at quite a fast rate, maybe that is ok?

**Comment by ojw28** [comment] 2015-02-09 16:47
Sample objects are already pooled. The ideal solution would probably be to keep data in TsPacket sized buffers right up until the samples are actually read from the extractor. Rather than copying sample data out of TsPacket buffers into intermediate Sample objects, we'd instead only parse out the information we need, such as where the sample data boundaries are within these buffers. We'd then copy directly from TsPacket buffers into SampleHolders on demand.

This is a pretty big change, and may be pretty complicated to pull off. But it would solve the issue.

**Comment by Guro** [comment] 2015-02-09 17:40
@ojw28
Currently because of this bug Exo Player for HLS is almost unusable, especially when bitrate is high.

do you have any approx time when this bug will be fixed?
or we should try it doing ourselves?

**Comment by ojw28** [comment] 2015-02-09 17:42
FWIW it's only unusable for lower powered devices running pre-L versions of Android. L does much better due to Art being the default VM. I plan to start looking at it this week. How soon the fix will arrive will depend on how difficult it is to fix.

**Comment by Guro** [comment] 2015-02-09 18:10
yep, we have 4.4 devices and for testing purpose now have switched from Dalvik to Art and result is much better.
but as you know there are lot of devices with Dalvik, please give us updates when you will look at the issue and will know approximate time of fixing.

Thanks.

**Comment by crossle** [comment] 2015-02-10 00:27
Yep, I use Nexus 5 Android 5.0 test, it work well. Waiting for Dalvik work well.

**Comment by ojw28** [comment] 2015-02-10 22:15
I started looking at this today. I've made good progress, and hope to have something ready by the end of the week.

**Comment by Guro** [comment] 2015-02-10 23:05
Happy to hear that :) thanks

**Comment by ojw28** [comment] 2015-02-10 23:27
I'm not quite sure how good performance will end up being. It should be noted that HLS, specifically its use of MPEG-TS as a container format, is horrendously inefficient, both for bandwidth and in terms of computational cost for the client. If you have a 1MB keyframe in your stream, it ends up being fragmented into over 5000 pieces, which the client then has to merge back together again before it can feed it to the decoder.

You should really consider switching to DASH or SmoothStreaming using the FMP4 container format if you have any control at all over what format you're using, where a 1MB keyframe will be in exactly one piece, and can simply be copied directly into the decoder.

**Comment by Guro** [comment] 2015-02-11 08:30
@ojw28 thanks for advice, we will check if its possible to switch to DASH, the problem is that iOS supports only HLS.

will wait for you fix and check performance.

**Comment by ojw28** [comment] 2015-02-13 19:34
Hi. Could you test this again using the latest dev branch? Thanks!

**Comment by ojw28** [comment] 2015-02-13 19:35
Note: If you were previously using the dev-hls branch, you should now be using dev (dev-hls has been merged to dev).

**Comment by Guro** [comment] 2015-02-13 20:01
Tested for a little bit and as it seems issue is fixed! 
Big Thanks!

**Closed** 2015-02-13 20:36 UTC
Labels: bug
