### ISSUE TITLE
unexpected end of stream

### ISSUE THREAD

**Issue by marcochin** [google/ExoPlayer#4455] opened 2018-06-29 20:04 UTC
### Issue description
Getting an unexpected end of stream exception and not sure what the cause is. Have read from a different issue that this is 

> indicative of a server providing a Content-Length value in a response header that does not match the length of the response body

However, the stack trace is different. Any help would be appreciated! 

```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:269)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:152)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:135)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:116)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:126)
        at com.google.android.exoplayer2.extractor.mkv.Sniffer.sniff(Sniffer.java:50)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.sniff(MatroskaExtractor.java:404)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:912)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:846)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.ProtocolException: unexpected end of stream
        at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:396)
        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
        at com.android.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:779)
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:571)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:267)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:152) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:135) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:116) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:126) 
        at com.google.android.exoplayer2.extractor.mkv.Sniffer.sniff(Sniffer.java:50) 
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.sniff(MatroskaExtractor.java:404) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:912) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:846) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)
```

### Version of ExoPlayer being used
Exoplayer 2.7.1

### Device(s) and version(s) of Android being used
Android TV Nexus Player 8.0
Android Google Pixel 8.1

**Comment by andrewlewis** [comment] 2018-07-02 08:51
It looks like the end of the stream is being encountered right at the start of the file. Please could you provide a link to the stream you're trying to play?

**Comment by ojw28** [comment] 2018-07-06 21:02
I think this issue probably is

> indicative of a server providing a Content-Length value in a response header that does not match the length of the response body

An easy way to check would be to try playing the file locally, or from a different server. In any case, closing due to lack of follow-up information. If you're able to provide a stream that reproduces the issue, please respond here and we'll re-open it.

**Closed as completed by ojw28** 2018-07-06 21:02 UTC
Labels: need more info
