### ISSUE TITLE
UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.

### ISSUE THREAD

**Issue by anasAJ** [google/ExoPlayer#4150] opened 2018-04-18 14:47 UTC
I have a probleme while trying to open an existing and tested .m3u8 link with HLSMediaSource here is my code :
PS:i'm on Android Tv App Activity
    public class PlaybackVideoFragment extends VideoSupportFragment{

    PlayerView playerView;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        final Movie movie =(Movie) getActivity().getIntent().getSerializableExtra(DetailsActivity.MOVIE);
        super.onCreate(savedInstanceState);
        Handler mainHandler = new Handler();
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(getActivity(), trackSelector);
        playerView =new PlayerView(getActivity());
        playerView.setPlayer(player);
        DefaultBandwidthMeter defbandwidthMeter = new DefaultBandwidthMeter();
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getActivity(), Util.getUserAgent(getActivity(), "ipision"), defbandwidthMeter);
        Uri myUri = Uri.parse(movie.getVideoUrl());//getVideoUrl() returns this : http://live.streamlife.co:8080/live/1493.m3u8(tested)
        MediaSource videoSource = new HlsMediaSource(myUri,dataSourceFactory,mainHandler, new MediaSourceEventListener() {
            @Override
            public void onLoadStarted(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs) {

            }

            @Override
            public void onLoadCompleted(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

            }

            @Override
            public void onLoadCanceled(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

            }

            @Override
            public void onLoadError(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded, IOException error, boolean wasCanceled) {

            }

            @Override
            public void onUpstreamDiscarded(int trackType, long mediaStartTimeMs, long mediaEndTimeMs) {

            }

            @Override
            public void onDownstreamFormatChanged(int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaTimeMs) {

            }
        });
        // Prepare the player with the source.
        player.prepare(videoSource);
        player.setPlayWhenReady(true);
    }
And here is the error:

    E/ExoPlayerImplInternal: Source error.
                 com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
                     at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:148)
                     at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:48)
                     at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                     at java.lang.Thread.run(Thread.java:818)

Crash begins when i try to get into player fragment.

**Comment by AquilesCanta** [comment] 2018-04-18 16:16
@anasAJ, I cannot resolve the provided URL:

```
$ curl http://live.streamlife.co:8080/live/1493.m3u8
curl: (6) Could not resolve host: live.streamlife.co
```

Is it possible that the DNS resolution for the domain is geo-restricted?

**Comment by anasAJ** [comment] 2018-04-18 16:25
here is a correcte one:
http://xtrastv.pointto.us:8000/live/greek/eglS9qxjAg/1493.m3u8
i've been doing som tests and i've found that the problem was from the m3u files syntax so i provide to URI a list link that contains only this :

    #EXTM3U
    #EXT-X-PLAYLIST-TYPE:VOD
    #EXT-X-TARGETDURATION:-1
    #EXT-X-VERSION:3
    #EXT-X-MEDIA-SEQUENCE:0
    #EXTINF:-1,TV5 MONDE
    http://xtrastv.pointto.us:8000/live/greek/eglS9qxjAg/1493.m3u8

But now i'm getting a reg expression error that says #EXT-X-TARGETDURATION: "need somethimg like ([\d\.]+)\b " instead of "-1" and also for #EXTINF.

**Comment by AquilesCanta** [comment] 2018-04-18 16:32
Please see #3722 and #4066.

http://xtrastv.pointto.us:8000/live/greek/eglS9qxjAg/1493.m3u8

is giving me an empty response.

**Comment by ojw28** [comment] 2018-04-21 08:07
Agree this is a duplicate of #4066.

**Closed as completed by ojw28** 2018-04-21 08:07 UTC
Labels: duplicate
