### ISSUE TITLE
2.9.x have compile issue with Java

### ISSUE THREAD

**Issue by zishanj** [google/ExoPlayer#5419] opened 2019-01-21 19:33 UTC
I have to step down to 2.8.4 just because 2.9.x have some compile issues with Java. The doc although mentioned about adding some compileoptions like
```
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
```
But these are already set in my Java based Gradle settings but still it throws error similar to #5276 . In that issue there is a suggestion for Kotlin based settings:

```
kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
```

Does this 2.9.x is based on Kotlin and my Java app needs to be configure for Kotlin support?

**Comment by ojw28** [comment] 2019-01-22 10:19
In pretty much all of cases where people are seeing this type of issue, it's because they've not made the changes to their gradle files correctly. Does the ExoPlayer demo app compile and run fine for you? If so, try and figure out what the difference is between that project and yours, in terms of how the gradle files are setup. If you're still stuck, I think you'll need to provide a small demo project that reproduces the problem. Without this there's not much we can do to help.

**Comment by zishanj** [comment] 2019-01-22 10:51
As I mentioned it may require Kotlin compiler settings but I just wonder why this Kotlin is not required for ver 2.8.4.

**Comment by ojw28** [comment] 2019-01-22 10:53
If you're using Kotlin in your application code then you might need to configure Java 8 for Kotlin. ExoPlayer itself doesn't contain any Kotlin code (in any version).

**Comment by zishanj** [comment] 2019-01-22 16:12
I don't use Kotlin but this 2.9.x version is forcing me to configure for Kotlin, otherwise 2.8.4 is working fine.

**Comment by ojw28** [comment] 2019-01-22 16:13
In what way is it forcing you? ExoPlayer doesn't use Kotlin. If you don't use Kotlin either, you shouldn't need to configure anything related to Kotlin.

**Comment by ojw28** [comment] 2019-01-23 23:28
Closing for now. If you still have an issue, you'll need to provide a small demo project that reproduces the problem.

**Closed as completed by ojw28** 2019-01-23 23:28 UTC
Labels: need more info
