### ISSUE TITLE
MediaCodec$CryptoException when play UHD

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2706] opened 2017-04-19 16:35 UTC
Dear colleagues,
It maybe odd report to some degree, however, it leads to more scenarios to fail playback.
Requirements:
- Use Sample App v. 2.3.1 to play WV/DASH (MP4, H264) UHD content on a device that supports this content partially, for instance, NO_EXCEEDS_CAPABILITIES for Video
- Observe playback with Audio only (which is expected), however, after some time there is ExoPlaybackException caused by MediaCodec$CryptoException.

Stack trace:
```
04-19 12:18:21.657 E: Renderer error.
                      com.google.android.exoplayer2.ExoPlaybackException
                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:739)
                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:525)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                          at android.os.Handler.dispatchMessage(Handler.java:98)
                          at android.os.Looper.loop(Looper.java:148)
                          at android.os.HandlerThread.run(HandlerThread.java:61)
                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                       Caused by: android.media.MediaCodec$CryptoException: Unknown Error
                          at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                          at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2305)
                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:725)
                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:525) 
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464) 
                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                          at android.os.Looper.loop(Looper.java:148) 
                          at android.os.HandlerThread.run(HandlerThread.java:61) 
                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

While I am agree that this is expected, however, just curious whether it is possible to avoid playback error and just play audio?

More input for the same issue. If try to play clear content with the same parameters, despite the fact that video variant reports NO_EXCEEDS_CAPABILITIES, video itself plays well.

Now, different devices behave differently. I tested on LG-D852 device (Android 6.0 API 23), but, testing on FireTV for instance (yes I know that it is Fire OS which is unsupported by you guys) causing next behaviour: video frame freezes and only audio plays, video variant keep sloading on and on until:
```
04-19 11:37:08.091 E/LoadTask(22580): java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 62363 free bytes and 60KB until OOM
04-19 11:37:08.091 E/LoadTask(22580): 	at com.quickplay.google.android.exoplayer.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
04-19 11:37:08.091 E/LoadTask(22580): 	at com.quickplay.google.android.exoplayer.extractor.DefaultTrackOutput.prepareForAppend(DefaultTrackOutput.java:585)
04-19 11:37:08.091 E/LoadTask(22580): 	at com.quickplay.google.android.exoplayer.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:489)
04-19 11:37:08.091 E/LoadTask(22580): 	at com.quickplay.google.android.exoplayer.source.chunk.ChunkExtractorWrapper$BindingTrackOutput.sampleData(ChunkExtractorWrapper.java:179)
04-19 11:37:08.091 E/LoadTask(22580): 	at com.quickplay.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1111)
04-19 11:37:08.091 E/LoadTask(22580): 	at com.quickplay.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
04-19 11:37:08.091 E/LoadTask(22580): 	at com.quickplay.google.android.exoplayer.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:112)
04-19 11:37:08.091 E/LoadTask(22580): 	at com.quickplay.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:295)
04-19 11:37:08.091 E/LoadTask(22580): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-19 11:37:08.091 E/LoadTask(22580): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-19 11:37:08.091 E/LoadTask(22580): 	at java.lang.Thread.run(Thread.java:818)
```
So, the question is - is this something that can be done from ExoPlayer side to avoid playback exception / video loading of unsupported variant / etc ... ? I understand that this is somehow client side responsibility, but still, even though variant not supported, ExoPlayer should not fail when client stays on it.

**Comment by ojw28** [comment] 2017-04-23 21:42
I'm not sure I follow the first part of this question. What do you think is happening when the CryptoException occurs, and why do you think it's expected? If only audio is being played, that suggests to me that the CryptoException is being thrown from the audio renderer, and I don't think it is expected. Please clarify; thanks!

The second part of the question looks unrelated, and is on an unsupported device. So let's focus on the first part.

**Comment by ChernyshovYuriy** [comment] 2017-04-23 23:46
If CryptoException is from audio renderer then it is unexpected, of course. I was on the opinion that this exception is from video one, this is why I though it is expected.
My question is - despite the fact that there is unsupported video renderer, should playback fail on audio variant?

**Comment by ojw28** [comment] 2017-04-24 10:30
If no video tracks are selected (as is the case if the tracks are all unsupported), then playback should work in the same way as if there were no video tracks in the media to start with. We wont be obtaining a video decoder or feeding it buffers, which is why I think the failure is in the audio renderer. Please could you take a look and verify this is indeed the case?

We would not expect failure in this case. Is the issue device specific, or is it occurring on all devices that don't support UHD? Does playback of the SD/HD samples succeed? Are you sure the issue is even specific to the UHD case? Thanks.

**Comment by ghost** [comment] 2017-05-02 18:32
I am seeing this same issue using the latest sample app from version 2.4 on an nvidia shield running 7.0. Selecting Widevine DASH: MP4,H265 and then try playing WV:Secure UHD (MP4,H265). Playback starts and the video goes on for about 5 seconds and then freezes. Ive attached a complete log as a text file.

[exoplayer-sample-uhd-wv-h265-failed.txt](https://github.com/google/ExoPlayer/files/971619/exoplayer-sample-uhd-wv-h265-failed.txt)

I forgot to add some other details. We see this same issue on our hd h264 wv dash content. Playing any hd h264 wv dash content that has been marked as widevine level 1 causes this issue on the nvidia shield running 7.0 and also a mibox running 6.1. Turning the security level from widevine level 1 to widevine level 3 causes the issue to go away on both devices. Hand manipulating the manifests to only have the video tracks makes the issue go away. When we hand manipulated the manifest to have audio tracks only the issue remains. Turning the wv level back to 3 from 1 on the audio only tracks made the issue go away.

It seems to be audio related.

**Comment by ojw28** [comment] 2017-05-02 22:14
@JamieAndresakis - If you're seeing video at all then that's not the same issue. This issue is specifically for the case where video tracks aren't selected.
@ChernyshovYuriy - Unless you're able to answer the questions above I'll go ahead and close this, since there's nothing obviously actionable.

**Comment by ghost** [comment] 2017-05-02 22:58
@ojw28  in your sample app your own sample content starts and then dies after 5 seconds. Our own internal content fails immediately with the same error without ever playing anything. If you think I should open a separate issue please advise.

**Comment by ojw28** [comment] 2017-05-02 23:33
It's definitely a different issue. The error isn't actually the same. You're seeing "Error decrypting data: insufficient output protection" and in the original post the error was "Unknown Error".

The "insufficient output detection" error is indicative of the device refusing to decrypt the content because the protection level of the video output path isn't sufficient to protect the content. Is it possible you're plugging the Shield into an unusual display? I'd class anything that's not HDMI into a normal TV as unusual. It's possible that the Shield and the display haven't been able to negotiate HDCP if so. Alternatively, have you made any modifications to the demo app?

**Comment by ghost** [comment] 2017-05-03 00:18
I apologize for not looking closer at the issue from the original poster but thank you for indulging my question any way 👍  

I was running the shield on a newish dell monitor straight hdmi. Not sure if its HDCP compatible. When I get the shield back tomorrow I will test it on a tv so thank you for that.

I have not made any modifications to the application other than adding my own urls to media.exolist.json.

I should add that all your other sample content seemed to play but not the uhd wv dash h265 when I ran it on any device plugged into that same monitor.

If you would like I can collect more data and start a separate issue.

**Comment by ChernyshovYuriy** [comment] 2017-05-03 00:40
Sorry guys, I am no longer with the company I am originally reported issue at.
I would be happy to go on conversation and found root cause of my issue but I can not go on.
For this reason, you guys decide whether to close it or investigate alongside.
Sorry.

**Comment by ghost** [comment] 2017-05-03 00:43
I just checked the sample app on a sony bravia tv running 6.0.1. Everything seems to work so the issue with the sample content mustve been related to the hdcp stuff on the monitor. My content is still not working so it must be widevine related.

**Comment by ojw28** [comment] 2017-05-03 09:00
@JamieAndresakis - No worries! I'd assume it's related to HDCP in that case. Plugging into a computer monitor isn't really a common use case. We've found that support can be quite variable (and all bets are off if you're using any kind of non-standard cable). At the platform level it's likely that the right thing is happening. I'm unsure why the license policy of the UHD sample content is different (if that is the case). In any case, let's assume everything is working as intended for now. If you encounter further issues please feel free to open a new issue.

@ChernyshovYuriy - If this means the end of your work with ExoPlayer, then best of luck in your future endeavors!

I'll close this for now, since it doesn't look like we have anything actionable at this point in time.

**Closed as completed by ojw28** 2017-05-03 09:00 UTC
Labels: need more info

**Comment by ChernyshovYuriy** [comment] 2017-05-04 00:36
@ojw28 it doesn't mean that I stopped use ExoPlayer at all.
I just no more with the AT&T (QuickPlay Media), however, I do use ExoPlayer in my personal project as a Player to play radio stream. Search "Open Radio" in Google Play, this application (means ExoPlayer as well) also used in the vehicles because it is Google Auto compatible :-)

**Comment by ojw28** [comment] 2017-05-04 10:29
Cool :).
