### ISSUE TITLE
NPE in method `HlsMediaPeriod#maybeThrowPrepareError()`

### ISSUE THREAD

**Issue by Khang-NT** [google/ExoPlayer#3599] opened 2017-12-16 14:46 UTC
### Issue description
Crash log:
```
ExoPlayerImplInternal: Internal runtime error.
            java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.maybeThrowPrepareError()' on a null object reference
            at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.maybeThrowPrepareError(HlsMediaPeriod.java:98)
            at com.google.android.exoplayer2.source.DynamicConcatenatingMediaSource$DeferredMediaPeriod.maybeThrowPrepareError(DynamicConcatenatingMediaSource.java:808)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeThrowPeriodPrepareError(ExoPlayerImplInternal.java:970)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:544)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:154)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

I don't understand much the code base, but it shouldn't cause NPE in method `maybeThrowPrepareError` with any reason.

### Reproduction steps
It happens randomly when I play HLS media source.

### Version of ExoPlayer being used
I use version `2.6.0`.

**Comment by ojw28** [comment] 2017-12-18 00:44
Please can you provide a full bug report captured with `adb bugreport`, proper reproduction steps, and test content that can be used to reproduce this issue. All of this information is requested in the issue template.

Looking at the code for `HlsMediaPeriod`, it's hard to see how a null entry can end up in `sampleStreamWrappers`, unless there's some failure that happens before this one. If there is some previous failure, that's the root cause we need to be fixing. I'd expect such a failure to be visible in the full bug report, once provided. If there isn't, can you see how a null entry could happen?

**Comment by ojw28** [comment] 2018-01-02 18:35
@AquilesCanta - Can you see any way this can occur? If not (and unless new information is provided), then I think it's OK to go ahead and close this issue.

**Comment by AquilesCanta** [comment] 2018-01-10 11:56
> Can you see any way this can occur?

Not really. As far as I can tell, the only thing that could cause something like the issue described is having HlsMediaPeriod#prepare() and HlsMediaPeriod#maybeThrowPrepareError() being invoked on different threads, but that should never happen (both are expected to be invoked on the ExoPlayerImplInternal handler thread). This condition propagates to DynamicConcatenatingMediaSource.

In order to debug this we should discard all possible app specific behavior. 

- Is this issue reproducible in the DemoApp?
- Is the issue reproducible only for specific media?
- Can you still reproduce the issue? Could you make sure the issue repruduces with the correct invocation thread for prepare and maybeThrowPrepareError?

I will close the issue for now and will reopen once the requested information is provided. Please, don't forget to include the information requested by @ojw28 above.

**Closed as completed by AquilesCanta** 2018-01-10 11:56 UTC
Labels: need more info
