### ISSUE TITLE
Last word/syllable of mp3 files are cut on certain devices

### ISSUE THREAD

**Issue by abelhamilton** [google/ExoPlayer#3449] opened 2017-11-11 15:59 UTC
### Issue description
I'm trying to implement Exoplayer to play background music in loop and speech sounds at the same time that are played on click events.
I can't add silence at the end of the file because I play them in raw to make a sentence like : 
file one : "select" 
file two : "a category"
That's why I can't have a silence gap between 2 files and there are about 1500 files in the app so I do that to save space.

At first I was with MediaPlayer but figured out that on certain phone (One plus A0001 ) I can't have 2 Mediaplayers working at the same time so I decided to go with Exoplayer.
The 2 players are running in a service. 

Background music are ogg files in the raw folder and works great.

I couldn't manage to play mp3 speech file from raw folder so i put them in asset folder and I manage to play them.
The problem I am facing now is that at the end of every mp3 files is cut on some of my devices. The length of the cut depends of the device.

Did I made something wrong ?

Thanks in advance

This is my code for the soundPlayer

```
DefaultRenderersFactory renderersFactorySound = new DefaultRenderersFactory(this,null, DefaultRenderersFactory.EXTENSION_RENDERER_MODE_OFF);
exoPlayerSound = ExoPlayerFactory.newSimpleInstance(renderersFactorySound, new DefaultTrackSelector(), new DefaultLoadControl());
exoPlayerSound.addListener(playerSoundEventListener);
exoPlayerSound.setVolume(1.0f);
exoPlayerSound.setRepeatMode(Player.REPEAT_MODE_OFF);

final AssetDataSource dataSource = new AssetDataSource(this);
DataSpec dataSpec = new DataSpec(Uri.parse("asset:///sounds/" + soundsToPlay.get(0) + ".mp3"));
try {
     dataSource.open(dataSpec);
} catch (AssetDataSource.AssetDataSourceException e) {
     e.printStackTrace();
}

DataSource.Factory factoryMusic = new DataSource.Factory() {
      @Override
      public DataSource createDataSource() {
              return dataSource;
      }
};
MediaSource audioSource = new ExtractorMediaSource(Uri.parse("asset:///sounds/" + soundsToPlay.get(0) + ".mp3"), factoryMusic, Mp3Extractor.FACTORY, null, null);
exoPlayerSound.prepare(audioSource);
exoPlayerSound.setPlayWhenReady(true);

```

This is my code for the musicPlayer
```
DefaultRenderersFactory renderersFactoryMusic = new DefaultRenderersFactory(this, null, DefaultRenderersFactory.EXTENSION_RENDERER_MODE_OFF);
playerMusic = ExoPlayerFactory.newSimpleInstance(renderersFactoryMusic, new DefaultTrackSelector(), new DefaultLoadControl());
playerMusic.setVolume(0.4f);
playerMusic.setRepeatMode(Player.REPEAT_MODE_ONE);
DataSpec dataSpecMusic = new DataSpec(RawResourceDataSource.buildRawResourceUri(songId));
            final RawResourceDataSource rawResourceDataSourceMusic = new RawResourceDataSource(this);
            try {
                rawResourceDataSourceMusic.open(dataSpecMusic);
            } catch (RawResourceDataSource.RawResourceDataSourceException e) {
                e.printStackTrace();
            }

DataSource.Factory factoryMusic = new DataSource.Factory() {
     @Override
     public DataSource createDataSource() {
           return rawResourceDataSourceMusic;
     }
};

MediaSource audioSourceMusic = new ExtractorMediaSource(rawResourceDataSourceMusic.getUri(), factoryMusic, OggExtractor.FACTORY, null, null);
playerMusic.prepare(audioSourceMusic);
playerMusic.setPlayWhenReady(true);
```

### Version of ExoPlayer being used
    compile 'com.google.android.exoplayer:exoplayer-core:r2.5.4'

### Device(s) and version(s) of Android being used
Devices with problem :  
- Samung Galaxy note 3 SM-N9005 - Android v5.0
- Acer Iconia B1-710 - Android v4.1.2

Device without problem :
- One plus A0001 - Android v6.0.1
- Samung Galaxy note 1 GT-N7000 - Android v4.1.2

**Comment by andrewlewis** [comment] 2017-11-13 16:15
This looks similar to #3386.

**Comment by otanmukhanov** [comment] 2018-01-30 08:41
I have same problem.
Device Lenovo A536.
My app has 3000 short mp3 files. And 20 percent of they has same problem - mp3 files are cut. And many users of my app are saying about it problem.
It is actual problem of exoplayer for many type of devices. Why are you closing such issues?

**Comment by andrewlewis** [comment] 2018-02-07 15:52
@abelhamilton Please could you check whether this is still reproducible using a more recent ExoPlayer release like 2.6.1, and provide an example file where you hear the clipping problem? We now implement gapless trimming of audio ourselves rather than relying on the platform codec to do this, which might possibly fix the issue.

@otanmukhanov Please provide the same information and we can investigate further.

If this is a device specific issue with gapless trimming, it may be fixed in recent releases of ExoPlayer. Or, more likely, if it's caused by platform decoders not outputting to the end of the input stream, we should find out how widespread the bug is by compiling a list of affected devices, and decide whether to try to work around it.

**Comment by satyasivaprasad** [comment] 2018-05-07 07:27
The issue has still existed in the latest version(2.7.3)
I am using HTC M9, when I play the audio file from the RAW folder using exoplayer the last word is chopped.

This happens only when I change audio manager mode to "MODE_IN_COMMUNICATION"
audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
And other modes like MODE_IN_CALL or MODE_NORMAL audio is playing fine(means without cut)

**Comment by andrewlewis** [comment] 2018-11-05 17:31
Closing as I think the originally reported issue is fixed.

If you still see problems with output audio being truncated please file a separate issue and include all the information requested in the issue template.

**Closed as completed by andrewlewis** 2018-11-05 17:31 UTC
Labels: bug: device specific
