### ISSUE TITLE
Extreme pixelation on HD HLS streams

### ISSUE THREAD

**Issue by jedashford** [google/ExoPlayer#2172] opened 2016-12-09 05:09 UTC
**- A description of the issue.**
![vidangel_exoplayer](https://cloud.githubusercontent.com/assets/4111055/21038373/5c268902-bd92-11e6-8ec7-6bdd742f4d8b.png)
We get random (but reproducible every time) extreme pixelation of the picture on Exoplayer 2.x with HD streams. This did not happen on <= 1.5 . 

**- Steps describing how the issue can be reproduced, ideally in the ExoPlayer demo app.**
At the bottom of this report, there are files ready to go and you just need to add the code to the media.exolist.json in the demo app. As you can see, the "VidAngel Stream Prod 4mbs Pixelation Issue" pixelates when the video plays. This was tested on nvidia shield and the nexus player. 

The "VidAngel Stream Prod 720p No Issues" is a 720p stream that does not exhibit the same behavior. 

"VidAngel Stream New Endcoding 4mbs Pixelation Fast Recovery" is a new encoding params for the same stream and as you can see, the pixelation occurs, but quickly corrects itself. 

We have never had an issue like this with Android in the past. These same streams work smoothly on 1.5, Roku, Apple, Chromcast, Xbox, and Samsung Smart TVs. 

**- A link to content that reproduces the issue. If you don't wish to post it
  publicly, please submit the issue, then email the link to
  dev.exoplayer@gmail.com including the issue number in the subject line.**
Provided it in the code below
**- The version of ExoPlayer being used.**
2.0.4
**- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.**
We can reproduce it every time. See streams mentioned below.

**- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.**
See Attached
[bugreport.txt](https://github.com/google/ExoPlayer/files/641285/bugreport.txt)

Code added to the demo app (media.exolist.json) to reproduce:

      {
        "name": "VidAngel Stream Prod 4mbs Pixelation Issue",
        "uri": "https://s3.amazonaws.com/processing.vidangel.com/playlist-all-1480546906-hd-aac.m3u8"
      },
      {
        "name": "VidAngel Stream New Endcoding 4mbs Pixelation Fast Recovery",
        "uri": "https://s3.amazonaws.com/processing.vidangel.com/playlist-all-1480959853-hdx-aac.m3u8"
      },
      {
        "name": "VidAngel Stream Prod 720p No Issues ",
        "uri": "https://s3.amazonaws.com/processing.vidangel.com/playlist-all-1480546906-hds-aac.m3u8"
      },
      {
        "name": "VidAngel Stream New Endcoding 720p No Issues",
        "uri": "https://s3.amazonaws.com/processing.vidangel.com/playlist-all-1480546752-hdm-aac.m3u8"
      },

**Comment by AquilesCanta** [comment] 2016-12-09 10:21
This is a duplicate of #1978, #1921 and #2163.

**Comment by jedashford** [comment] 2016-12-09 22:26
@AquilesCanta This problem has never happened on Exoplayer 1.5, doesn't happen on any other player across all of our platforms player's (iOS, tvOS, Roku (both scene graph and roVideoScreen), XBox, Samsung TV (Tizen) and Chromecast. 

We're inspecting the media elements, but even if it is the media, everyone (including apple) is handling it gracefully, but ExoPlayer isn't. I'd suggest a bug fix no matter if it is the media or not. I'll follow up either way.

Thank you for the response and what you are doing. Without your work, we'd be stuck on Android.

**Comment by ojw28** [comment] 2016-12-11 23:04
@AquilesCanta Pretty sure you're right that the streams are in violation of the spec. I wonder though: Am I right in thinking that we started looking at continuity counter as part of the work to handle "noisy input" properly? Is there any other reason to look at them? If not, maybe we should disable the continuity counter checks for HLS via (another :/) flag, given they appear to be causing problems. Handling "noisy input" doesn't seem necessary for HLS because HTTP/TCP is used.

**Comment by ojw28** [comment] 2016-12-11 23:06
Note: If we do this, it will need to be V1 and V2, since I continuity counter checks have been added to V1 as well.

**Closed as completed** 2016-12-14 16:23 UTC
Labels: bug

**Comment by jedashford** [comment] 2016-12-14 21:00
@ojw28 @AquilesCanta We've tested these changes and the stream is completely solid. Thank you for your efforts: from the VIdAngel team and customers !
