### ISSUE TITLE
Mimicking the behavior of REPEAT_MODE_ALL without overhead

### ISSUE THREAD

**Issue by yuroyami** [google/ExoPlayer#11002] opened 2023-02-20 10:34 UTC
When repeat mode is set to `REPEAT_MODE_ALL`, the player will **_instantly_** repeat the media without any delay overhead. So, I am trying to mimic this behavior by listening to when the player finishes playback of a media item, then seek to 0ms again.

However, this comes with some overhead, whereas `REPEAT_MODE_ALL` literally instantly replays it without any preloading or buffering. 

I tried inspecting the source code but I couldn't put my finger on where the interface for repeat mode is implemented, could you redirect me in the right way ? I want to repeat the media item at will while only using `REPEAT_MODE_OFF`

**Comment by tonihei** [comment] 2023-02-20 17:24
> I want to repeat the media item at will while only using REPEAT_MODE_OFF

Could you explain in a bit more detail what this means? Then we can hopefully direct you to a potential solution. I suspect you'd need a way to preload items items in a playlist for fast skipping/seeking (see #3327), just that you want to preload the current item instead of the next one.

> where the interface for repeat mode is implemented

Repeating works in the same way as a regular playlist. ExoPlayer will preload and predecode samples from the next item in the playlist as soon as the current one finished loading/decoding. This way the transition can be completely seamless. When repeating items, the "next item in the playlist" is basically another copy of the current one.

**Comment by yuroyami** [comment] 2023-02-21 00:11
@tonihei
What I meant by 'repeating media item at will', is that my repeat mode is set to `REPEAT_MODE_OFF` like this:

```kotlin
player.repeatMode = Player.REPEAT_MODE_OFF
```
But, there is a button that replays the playback from the beginning, so I do it manually like this:

```kotlin
player.seekTo(0L)
```

The code line above does the job but with huge overhead. I know that seeking comes with a cost, but even with the lowest buffering values, it takes like 200-300 ms to repeat from the beginning. However, when repeat mode is `REPEAT_MODE_ALL`, it basically repeats whatever is playing instantly without any delay.

Note that I am not using any playlist functionality so there is basically one media item to replay at all times. 

Thank you in advance!

**Comment by tonihei** [comment] 2023-02-21 10:27
Thanks for confirming!

> Note that I am not using any playlist functionality

As explained above, ExoPlayer's repeat modes are implemented in top of the same logic that makes playlist transitions seamless, that's why it's the same type of feature.

> But, there is a button that replays the playback from the beginning

This is the skipping/seeking feature (#3327) I mentioned above, which isn't supported yet. We are likely to work on this in the near future though and it should make this case almost as fast as the repeat mode transition you mentioned. The only optimizations you can do for now is to make sure your data is available locally on disk (e.g. using ExoPlayer's cache if needed: https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network)

I'll close this issue as a duplicate of #3327.

**Closed as completed by tonihei** 2023-02-21 10:27 UTC
Labels: duplicate
