### ISSUE TITLE
How do I access the current MediaSource from the DRM session?

### ISSUE THREAD

**Issue by francois-cabrol** [google/ExoPlayer#6361] opened 2019-08-30 04:04 UTC
I am trying to implement Widevine DRM management in my ExoPlayer-based application. In the solution I use (based on DASH), each movie has its unique ID and the request I send to the license server has to contain the ID of the movie that I am trying to play.

I would then need the ID corresponding to my movie in the **DrmCallback.** Is there a way in **DrmCallback**, **DrmSession** or **DrmSessionManager** to access information about the **MediaSource** currently playing?

Thank you very much.

**Comment by kgrevehagen** [comment] 2019-08-30 07:51
This is exactly what I proposed here: https://github.com/google/ExoPlayer/issues/6342

As far as I've understood, this will be fixed in 2.11.0, but only if you know the ID at the time of creating the `MediaSource`, since from version 2.11.0 you can send in the `DrmSessionManager` in the MediaSource(and then send in the same ID to a custom `MediaDrmCallback`).

Right now I have used a hacky workaround to save the latest ID to a shared object that both the 
`MediaSource` and `MediaDrmCallback` is using.

**Comment by AquilesCanta** [comment] 2019-08-30 11:05
Marking as a duplicate of #6342.

**Closed as completed by AquilesCanta** 2019-08-30 11:05 UTC
Labels: duplicate
