### ISSUE TITLE
Fragmented mp4 files not always sniffed correctly

### ISSUE THREAD

**Issue by replystreaming** [google/ExoPlayer#1523] opened 2016-05-12 10:39 UTC
Hi all,
we are trying to reproduce a protected (widevine) mp4 file stored on the device, implementing the offline drm playback.
We've already done a research and we've found out that we can split the problem in two step:
1. we have to retrieve the key from our server and store it somewhere;
2. we have to provide that key when the exoplayer starts the streaming of the protected file.

We know that we have to define our custom DrmSessionManager, in order to: 
1. save the downloaded key (with KEY_TYPE_OFFLINE type) to the MediaDrm class (using the provideKeyResponse method) during the key acquisition step.
2. provide the downloaded key to the ExoPlayer, during the streaming step.

At this moment, we are trying to implement the second step: our goal is to analyse the offline drm acquisition flow associated to a local file streaming.
We have provided the custom DrmSessionManager

new MediaCodecVideoTrackRenderer(context, sampleSource, MediaCodecSelector.DEFAULT, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 5000, ourCustomDrmSessionManager, true, mainHandler, player, 50);
DataSource dataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
Uri videoUri = Uri.parse(mLocalVideoItem.getVideoLocalUri());
ExtractorSampleSource sampleSource = new ExtractorSampleSource(videoUri, dataSource, allocator,BUFFER_SEGMENT_SIZE * BUFFER_SEGMENT_COUNT, mainHandler, player, 0);    

but the ExoPlayer is not using it: no method of that class - open(drmInitData), getMediaCrypto() ... - is called.

How can we force the drm license acquisition during an offline streaming?
Is there anything wrong in our approach?

Thanks in advance

**Comment by ojw28** [comment] 2016-05-12 13:36
Do you have DRM protected playbacks working in streaming mode for the same content? If not, you should get that working first. If so, how is the DRM initialization data transferred during playback? If you're not seeing `open` called on your `DrmSessionManager` then that indicates that there is no DRM initialization data (e.g. a pssh box for FMP4) present in the media.

**Comment by replystreaming** [comment] 2016-05-13 12:42
Hi all,
yes we can share DRM protected playbacks working fine in streaming mode  (https://www.dropbox.com/sh/nqzhqz6ouvoocz9/AAD7agLhLPWLD1Genk6cTsMma?dl=0). It's the same content with the issue in the offline mode.
Can you check if there is something wrong with it?
Can you tell us how we can force the Exoplayer to use DRM keys?

Thanks in advance

**Comment by ojw28** [comment] 2016-05-13 14:10
As stated in the message above, I think the problem is that there's no DRM initialization data (e.g. a pssh box) in the media. When you're streaming this isn't a problem because the pssh box is being delivered out-of-band in the DASH manifest's ContentProtection elements. There are multiple possible solutions:

1. Use DASH for offline playbacks too. Since your manifest appears to use relative URLs only, this is probably as simple as downloading the DASH manifest alongside the files and then using the exact same code as you do for the streaming case, but pointing to the offline manifest using a `file://` uri. This is probably going to be the simplest approach. This approach also lets you use the same code for both streaming and offline, rather than having an alternative code path requiring `ExtractorSampleSource` for the offline case.
1. Embed the pssh boxes inside the media instead of or in addition to the ones provided in the manifest. This would work fine, although embedded the pssh boxes in the media reduces the ease with which they can be modified/changed.
1. We could allow sideloading of `DrmInitData` into an `ExtractorSampleSource`. You would have to offline the data from the ContentProtection elements of the manifest, then at playback time build a `DrmInitData` from the data and sideload it into the source.

I'd suggest you try the first option to start with and see how you get on.

**Comment by replystreaming** [comment] 2016-05-13 16:25
Hi all,
as you can see in the attached image, pssh boxes are in mp4.

Thanks

![screen](https://cloud.githubusercontent.com/assets/19324839/15254546/9b34260e-1937-11e6-8044-9e92762a714d.jpg)

**Comment by ojw28** [comment] 2016-05-13 16:30
Interesting. I'll take a look.

**Comment by ojw28** [comment] 2016-05-13 16:32
Aside: Regardless of what we discover, it's probably still going to be easier for you to use DASH for offline playbacks. Having one code path is going to be easier to maintain and test than having too ;).

**Comment by ojw28** [comment] 2016-05-13 17:05
@andrewlewis - Our mp4 sniffer is failing to detect the video file as fragmented. The condition we're using is that there's a `moof` atom in the first ~4K of the stream, but in this case the first `moof` is quite a bit further than that at ~12K (see capture above). The sniffer's logic for detecting unfragmented mp4 also looks a bit suspicious. Ideally we'd want it to return false for fragmented mp4, but given it's only looking at the first 128 bytes I'm not sure that it'll do that (which means we effectively rely on the extractors being tried in a particular order).

Is there some way we can be more sure when sniffing, to determine for certain whether a file is fragmented or not? Just increasing the sniffing length would "fix" the problem for this media, but doesn't seem like a good solution in general.

@replystreaming - This is a general media type detection issue. When the media is correctly handled as fragmented mp4 we call into the DrmSessionManager as you'd expect.

**Comment by replystreaming** [comment] 2016-05-16 17:00
Hi,

increasing the sniffing length "fixes" actually the problem for this media; as you said, since does not seem to be a good solution, we would prefer to go with the final one. Do you have an idea when this could be fixed? In the mean time we will use your work-around.

**Comment by ojw28** [comment] 2016-05-16 17:07
@andrewlewis has a fix already that also looks for the `mvex` atom. We'll push it to the dev branch this week.

**Comment by replystreaming** [comment] 2016-05-16 17:18
Great. Would you mind to keep us posted?
Your help is really appreciated. 
Many Thanks

**Comment by ojw28** [comment] 2016-05-17 15:56
This is fixed in dev.

**Closed by ojw28** 2016-05-17 15:56 UTC
Labels: bug
