### ISSUE TITLE
How to make webm in exoplayer like chrome support transparent

### ISSUE THREAD

**Issue by Witype** [google/ExoPlayer#2544] opened 2017-03-09 15:02 UTC
When I playback the webm in chrome like this:
![image](https://cloud.githubusercontent.com/assets/6899329/23755725/479365a6-051c-11e7-8f05-e4ec2160ba94.png)
but int the exoplayer is not support transparent :the background is black
![image](https://cloud.githubusercontent.com/assets/6899329/23755811/8b208a60-051c-11e7-95e4-db1186532ef9.png)

How can I do this?
thanks!!!

**Comment by andrewlewis** [comment] 2017-03-09 15:28
Duplicate of #2509.

**Closed as completed by andrewlewis** 2017-03-09 15:28 UTC
Labels: duplicate
