### ISSUE TITLE
HLS Live Stream: artifacts of playback after adaptive track selection

### ISSUE THREAD

**Issue by DashaBadanina** [google/ExoPlayer#8526] opened 2021-02-01 13:32 UTC
How to reproduce:
-------------------------

Issue can be reproduced, using the ExoPlayer demo app:

1. Play hls live stream playlist with interlaced and progressive tracks, like this
<img width="929" alt="Снимок экрана 2021-02-01 в 18 28 22" src="https://user-images.githubusercontent.com/14832039/106465247-87816c00-64bb-11eb-84fb-20d58cc8e1aa.png">

2. Waiting for adaptive selection track with highest bitrate (interlaced track)
3. Cut the internet speed down to 10 Mbps 
4. Waiting for adaptive selection track with lower bitrate (progressive track)

**Actual result:**
After tracks switching (from interlaced to progressive!) for a couple of seconds you will see artifacts of playback like fast playback or frames freezing. 

I recorded a sample.
 After track switching:
![logs](https://user-images.githubusercontent.com/14832039/106463889-c4e4fa00-64b9-11eb-8e31-38fd1e8b27b3.jpeg)

I see this: 
https://user-images.githubusercontent.com/14832039/106463534-628bf980-64b9-11eb-9da4-015d701c79c8.mp4

**Expected result:**
Track switching is smoothing and invisible to the user (like in the case of track switching from progressive to interlaced).

Environment:
-------------------------
- ExoPlayer demo app v 2.12.3
- Android 9
- STB SEI Robotics

**Comment by icbaker** [comment] 2021-02-02 09:12
Please can you provide a stream we can use to try and reproduce this issue?

Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by DashaBadanina** [comment] 2021-02-02 14:04
I have sent the stream to dev.exoplayer@gmail.com. Please don't forget to use the user agent to receive all tracks, like this
<img width="1185" alt="Снимок экрана 2021-02-02 в 18 43 38" src="https://user-images.githubusercontent.com/14832039/106610877-1ad4a300-6589-11eb-9a56-3884a9052f8c.png">
By the way, as I know, ExoPlayer can't play interlace track by default. So we had to fix our firmware and set special parameters via setprop.
But how will you play my interlaced track? Do you have your own way?

**Comment by icbaker** [comment] 2021-02-05 17:23
ExoPlayer doesn't do any special handling for interlaced content (and as you've said, lots of devices don't support it). We just pass the video samples down into MediaCodec.

If you're seeing glitches during adaptive switching between progressive and interlaced content, it may be due to the implementation of MediaCodec on your device - which is something you need to report to the device manufacturer.

I don't think there's anything extra ExoPlayer could be doing here, so I'm going to close this.

**Closed as completed by icbaker** 2021-02-05 17:23 UTC
Labels: question

**Comment by skogl** [comment] 2021-03-29 11:59
I have seen this issue when playing a mpeg-ts stream as well so it's not related to adaptive streams. My device handles interlaced streams well, but it seems to have trouble handling this transition between non-interlaced and interlaced frames. 

Is this also something that needs to be implemented in the device?
