### ISSUE TITLE
Does Exoplayer V2 supports DRM for HLS?

### ISSUE THREAD

**Issue by RadhikaBalla** [google/ExoPlayer#3595] opened 2017-12-15 06:40 UTC
Hello guys,

     I am using Exoplayer-v2 for playing DRM encrypted Mpeg Dash videos. Does this exoplayer supports DRM for HLS also?? 

If it does not support, is there any other way to play DRM encrypted HLS videos?

**Comment by erdemguven** [comment] 2017-12-15 09:39
Duplicate of #1442

**Closed as completed by erdemguven** 2017-12-15 09:39 UTC
Labels: duplicate, question

**Comment by andrewlewis** [comment] 2017-12-15 09:45
Please see also https://google.github.io/ExoPlayer/supported-formats.html -- we now support cenc/cbcs Widevine on certain API levels.

**Comment by RadhikaBalla** [comment] 2017-12-15 12:44
Hello,

Thanks for the information. when I try to play HLS stream with DRM from
Demo app, getting following error.

Error:

```
com.google.android.exoplayer2.demo E/EventLogger: internalError [1.63,
loadError]
 com.google.android.exoplayer2.ParserException: Couldn't match
METHOD=(NONE|AES-128) in #EXT-X-KEY:METHOD=SAMPLE-AES,U
RI="skd://3d80d6d4458b30f0b5806aed183160c2?wowzasessionid=
480449731",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
     at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylis
tParser.parseStringAttr(HlsPlaylistParser.java:436)
     at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylis
tParser.parseMediaPlaylist(HlsPlaylistParser.java:357)
     at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylis
tParser.parse(HlsPlaylistParser.java:138)
     at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylis
tParser.parse(HlsPlaylistParser.java:43)
     at com.google.android.exoplayer2.upstream.ParsingLoadable.load(
ParsingLoadable.java:115)
     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(L
oader.java:315)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPool
Executor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoo
lExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
12-15 17:47:54.381 754-1104/com.google.android.exoplayer2.demo
E/ExoPlayerImplInternal: Source error.
```

And This is the code that I have added in media.exolist.json.

```
"name": "HLS",
"uri": "http://183.82.107.32:1935/DRMCBS/mp4:sample.mp4/playlist.m3u8",
"drm_scheme": "widevine",
"drm_license_url": "https://wv-keyos.licensekeyserver.com"
```

sdK min version in current version is 12. And when I try to change
minsdkversion to 19 in constants.gradle it is giving manifest merger
exception. Apart from constants.gradle file is there any other file to
change min version?

**Comment by erdemguven** [comment] 2017-12-15 13:13
Please file a new issue and include the information requested in the issue template. This is issue is closed.

**Comment by RadhikaBalla** [comment] 2017-12-18 05:23
Hello,

Please look into this issue.

-- 
Thanks&Regards,
Radhika Balla

**Comment by ojw28** [comment] 2017-12-18 12:31
Are you sure the content even supports Widevine decryption? 

@AquilesCanta is the expert in this area, but `METHOD=SAMPLE-AES` in the media playlist suggests to me that it's not. `SAMPLE-AES` is explicitly not supported on our [supported formats](https://google.github.io/ExoPlayer/supported-formats.html) page.

**Comment by RadhikaBalla** [comment] 2017-12-19 10:50
Hello guys,


 I am using exoplayer-v2. I need to extract media metadata from hls and
mpeg-dash streams. I have raised a ticker for that, please look into it.

-- 
Thanks&Regards,
Radhika Balla

**Comment by andrewlewis** [comment] 2017-12-19 10:51
Let's use #3606 for this.
