### ISSUE TITLE
Exoplayer not playing video in Android 11

### ISSUE THREAD

**Issue by abhiroop-medtronic** [google/ExoPlayer#11207] opened 2023-06-12 09:24 UTC
Hi,

I am using custom IMX8MPlus board with Android 11.2.6 NXP release. 
I am trying to play few short videos via exoplyaer.

The video info are attached.
![video_codec_info](https://github.com/google/ExoPlayer/assets/136320514/edb9e086-062b-4024-a98d-2ddc1ebeb2ad)

But the video is not playing nd I am getting these logs:
D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.7A0032, video/avc] [c2.imx.avc.decoder, video/avc]

Please let me know how can I resolve this issue.
Do I need to change the video or need to add ay extra code?

Thanks and regards,
Abhiroop Nandi Ray

**Comment by rohitjoins** [comment] 2023-06-13 13:12
Duplicate of [#455](https://github.com/androidx/media/issues/455)

**Closed as completed by rohitjoins** 2023-06-13 13:12 UTC
Labels: question, needs triage
