### ISSUE TITLE
Using MergingMediaSource with ClippingMediaSource

### ISSUE THREAD

**Issue by xiaos** [google/ExoPlayer#7467] opened 2020-06-04 14:59 UTC
I am using ExoPlayer to play multiple audios simultaneously, according to this: https://github.com/google/ExoPlayer/issues/4261#issuecomment-389429159
I implemented successfully, but now I have a requirement to clip the mediaSource, then merge.

So I have two ClippingMediaSource.
s1 = ClippingMedisSource(progressiveMediaSource1,  2000000, 4000000);
s2 = ClippingMedisSource(progressiveMediaSource2,  5000000, 9000000);
mergingMediaSource = MergingMediaSource(s1, s2);

But when I play, I found they are not playing simultaneously because the different start/end time of ClippingMedisSource,  May I know how to fix this?

**Comment by andrewlewis** [comment] 2020-06-08 09:24
This may be a duplicate of #6103. Please could you try the flag added in 0a89d0e8c3b0fa1a5e211e72ef95d35a1c69b5b3?

**Comment by xiaos** [comment] 2020-06-08 10:30
@andrewlewis   thanks, but I tried actually, it's not working. 
If I set enableInitialDiscontinuity =false.

s1 = ClippingMedisSource(progressiveMediaSource1, 2000000, 4000000);  -- Master, provide clock.
s2 = ClippingMedisSource(progressiveMediaSource2, 5000000, 9000000);  

Then the two audios play together, s1 play from 2nd second, but s2 also play from 2nd second (I am expecting to play from 5th second).

**Comment by andrewlewis** [comment] 2020-06-08 10:41
If you read on there is a new flag `adjustPeriodTimeOffsets`. Please could you try setting that to true?

**Comment by xiaos** [comment] 2020-06-08 13:00
@andrewlewis   sorry, i didn't find anywhere to set the flag: adjustPeriodTimeOffsets, can you please help?

**Comment by xiaos** [comment] 2020-06-08 13:18
@andrewlewis  I just tried, it's working. May I know when does this change release? 

Another question, as I play multiple audio tracks together, is it possible to set volume for each audio track?  any tips to change the code? Thanks.

**Comment by andrewlewis** [comment] 2020-06-08 14:57
Glad to hear it works. We generally don't commit to a specific release schedule I'm afraid.

There are a couple of ways of handling audio mentioned in #4261. If you have separate `DefaultAudioSinks`/`AudioTracks` in each renderer, you can set volumes on them individually. If you have implemented a mixing audio processor, you can include multiplication by channel-dependent volume when mixing the samples in the audio processor.

**Closed as completed by andrewlewis** 2020-06-08 14:57 UTC
Labels: question

**Comment by xiaos** [comment] 2020-06-11 01:26
@andrewlewis   thanks for your suggestion.  But I still have a small issue when set volume for AudioSinks in MediaCodecAudioRenderer,  I cannot find the mapping between renderer and mediaSource,  so I don't know which volume to set for the renderer. 

Btw, is it possible to play multiple video tracks? render to multiple surfaceView/TextureView.

**Comment by andrewlewis** [comment] 2020-06-11 12:25
Please avoid asking unrelated follow-up questions like this in future. New issues should be filed for those (having checked if they have already been answered on the issue tracker), to keep each issue focused and easy to follow.

> But I still have a small issue when set volume for AudioSinks in MediaCodecAudioRenderer, I cannot find the mapping between renderer and mediaSource, so I don't know which volume to set for the renderer.

`MergingMediaSource` periods merge child source tracks in the same order they were passed-in when creating the source. I think your custom track selection code can associate with renderers in order and signal to the renderers which track they are getting.

> Btw, is it possible to play multiple video tracks? render to multiple surfaceView/TextureView.

Yes, but you'll need to do some work in your track selector to support multiple renderers, like for audio. It may be simpler to use separate player instances.
