### ISSUE TITLE
Duplicate : Degradation of the reading of a 50 fps stream between 2.12 and 2.16

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#10096] opened 2022-03-21 09:40 UTC
Hello,

This topic is a duplicate of the ticket https://github.com/google/ExoPlayer/issues/10032  that was closed. (I can't reopen the  https://github.com/google/ExoPlayer/issues/10032 ticket.)

I will close it as soon as the other one is open.

Thank you

BR,

**Comment by icbaker** [comment] 2022-03-21 12:13
Duplicate of https://github.com/google/ExoPlayer/issues/10032

**Closed as completed by icbaker** 2022-03-21 12:13 UTC
Labels: duplicate
