### ISSUE TITLE
Track Selection not updating on change in network quality for m3u8 file

### ISSUE THREAD

**Issue by saurabhdtu** [google/ExoPlayer#6376] opened 2019-09-03 11:07 UTC
using exoplayer 2.10.2
@andrewlewis I am also facing problem regarding bandwidth and track adaptability. Here's the issue
I am playing a m3u8 file using the following code
`TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory); simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(this); hlsDataSource = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "Rooter")); simpleExoPlayer.setRepeatMode(Player.REPEAT_MODE_ONE); HlsMediaSource hlsMediaSource = new HlsMediaSource.Factory(hlsDataSource).createMediaSource(uri); concatenatingMediaSource.addMediaSource(hlsMediaSource); simpleExoPlayer.prepare(concatenatingMediaSource);`
The track selection based on network speed is only working when the video from the playlist changes. When the first track loads the bandwidth of the previous m3u8 file is used and doesn't change till the file ends or I am seeking the file to a different unbuffered timestamp.
Basically the exoplayer keeps on buffering with the high bitrate unless untill the exoplayer is seeked to m3u8 file.

**Comment by andrewlewis** [comment] 2019-09-03 11:58
Duplicate of #6375

**Closed as completed by andrewlewis** 2019-09-03 11:58 UTC
Labels: duplicate
