### ISSUE TITLE
Exoplayer can get stuck in preparing state when preparing HLS content with small ts chunk size

### ISSUE THREAD

**Issue by elixiroflife4u** [google/ExoPlayer#756] opened 2015-09-04 06:27 UTC
I have found a race condition bug inside HlsSampleSource in Exoplayer 1.3.3. It is specially more reproducible if the TS chunk is of small duration (~2 second). I do not know if this issue also affects Exoplayer 1.4.2 or dev branch. At this time, I am also unable to share a sample HLS content which shows the problem.

I decided to raise an issue so that others who may have encountered this issue could try the workaround I have found, as well as to raise awareness of this issue potentially lurking in the 1.4.2/dev branch, and other renderer builders. I would also love to hear your thoughts in case there is a problem with the workaround.

[Symptom of the problem]
On calling prepare on Hls, the exoplayer remains stuck in preparing state even though the TS chunk has been fully downloaded. However, the player can sometimes finish preparing if the chunk load complete comes after a call to HlsSampleSource to prepare.

[Cause of the issue]
I traced the problem traced down to the HlsSampleSource and was happening due to a race condition between call to prepare and onLoadCompleted. 
Basically, the prepare is called in a polling loop every 10msec. The chunk download proceeds independently, and the data is read by the TSExtractor. Once the TS extractor has enough data, it does some processing in it's consume function and sets up a flag. If this flag is then read by HlsSampleSource/HlsExtractorWrapper on the prepare call and everything is great. However, if the chunkOnLoadComplete for a TS chunk (in HlsSampleSource) happens to precede the prepare call, because it doesn't see any tracks, it proceeds to clear the extractor state which also clears the previous flag (see https://github.com/google/ExoPlayer/blob/r1.3.3/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L356). Therefore on the next call of prepare, the HlsExtractorWrapper fails to find anything and fails to prepare and simply keeps trying without ever succeeding.
It seems to me that the code assumed that the chunk load complete (for a TS chunk) won't happen before the extractor/sample source has been prepared.

[My solution to this issue]
I put a simple if check here:
https://github.com/google/ExoPlayer/blob/r1.3.3/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L359 ( in the else), just before clearState() etc.
Basically, the function returns immediately if the HlsSampleSource is not prepared and the currentLoadable is ts chunk.
.....
 else {
if(!prepared && isCurrentLoadableTsChunk) return; 
...
This prevents the clearing of state and allows the next call to prepare find what it is looking for and transition to next state.

I am still testing it, but i haven't seen any problems with it thus far.

**Comment by ojw28** [comment] 2015-09-04 11:56
Yes, this was a bug. I'm pretty sure it's fixed in 1.4.0 and later (onLoadCompleted doesn't call clearState at all).

**Closed by ojw28** 2015-09-04 11:56 UTC

**Comment by ojw28** [comment] 2015-09-04 11:57
I'd strongly encourage you to update to a newer version of the library by the way. There were significant stability improvements for HLS in 1.4.0 and 1.4.1.

**Comment by elixiroflife4u** [comment] 2015-09-04 16:26
Thanks for the information @ojw28 . I will plan a move to 1.4.2.
I also wrote this post in part to help others who are using 1.3.3, but can't immediately move either. :)

**Comment by Zo2m4bie** [comment] 2015-12-22 14:53
I faced of with the same problem on 1.5.0. Of course it can be another problem, but my app goes to preparing state and nothing happened.
https://github.com/google/ExoPlayer/blob/r1.5.0/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L402 return true.
onLoadCompleted calls every, maybe, 5sec. 
https://github.com/google/ExoPlayer/blob/r1.5.0/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L414 calls every time but I don't see frames and don't hear any voice

Logs:
EventLogger: start [0]
EventLogger: state [0.00, false, P]
EventLogger: state [0.00, true, P]

Can you help me with this problem? Or at least can I understand that video won't be played?

**Comment by Zo2m4bie** [comment] 2015-12-28 10:16
Just a little more information. My .ts  chunk is ~2 second

**Comment by Zo2m4bie** [comment] 2015-12-28 20:32
Do you have any suggestions for fixing it or at least get rid of infinite preparing?

**Comment by Zo2m4bie** [comment] 2015-12-29 08:35
@elixiroflife4u I tried to return to 1.3.3 and tried to use your solution. It didn't help. Did you add something more? I added 
     
    if(!prepared && isCurrentLoadableTsChunk) return;

in else statement
All function:

     @Override
     public void onLoadCompleted(Loadable loadable) {
       long now = SystemClock.elapsedRealtime();
       long loadDurationMs = now - currentLoadStartTimeMs;
       chunkSource.onChunkLoadCompleted(currentLoadable);
       boolean isCurrentLoadableTsChunk = false;
       if (isTsChunk(currentLoadable)) {
         isCurrentLoadableTsChunk = true;
         TsChunk tsChunk = (TsChunk) loadable;
         loadingFinished = tsChunk.isLastChunk;
         notifyLoadCompleted(currentLoadable.bytesLoaded(), tsChunk.type, tsChunk.trigger,
             tsChunk.format, tsChunk.startTimeUs, tsChunk.endTimeUs, now, loadDurationMs);
       } else {
         notifyLoadCompleted(currentLoadable.bytesLoaded(), currentLoadable.type,
             currentLoadable.trigger, currentLoadable.format, -1, -1, now, loadDurationMs);
       }
       if (!currentLoadableExceptionFatal) {
         clearCurrentLoadable();
       }
       if (enabledTrackCount > 0) {
         maybeStartLoading();
       } else {
         if(!prepared && isCurrentLoadableTsChunk) return;
         clearState();
         allocator.trim(0);
       }
     }

I will be very thankful if you help me

**Comment by ojw28** [comment] 2016-01-03 20:49
Note to anyone seeing similar symptoms to this issue - The root cause is likely different. Please open a separate issue containing [sufficient information](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).
