### ISSUE TITLE
Strange ghost trail stuttering 

### ISSUE THREAD

**Issue by wazerstar** [google/ExoPlayer#10080] opened 2022-03-16 18:02 UTC
[tivimate](https://play.google.com/store/apps/details?id=ar.tvplayer.tv&hl=da&gl=US) developer updated to latest exoplayer version from r2.16.1 -> r2.17.1

I'm doing a test version from him where he implemented the missing IDR for [mpeg-ts](https://exoplayer.dev/troubleshooting.html#why-do-some-mpeg-ts-files-fail-to-play) streams in order to see if that fixed most playback issues which seems to fix most hiccups, there's still some left(very rare)..

However in one of the live channels testing I found some strange endless/infinity ghost trail stuttering, I recorded the stream and tested it in playback in the test version, same thing occurred right away.

I then went back to use the latest official version from him version 4.20 which uses exoplayer r2.16.1 and used the same record and stream with same ongoing show to see if the stuttering had same effect, there was nothing to be found.

This is a one time experience I'm back on the test version and the same channel is no longer effected, I suspect the hdhomerun stream data information that was broadcasted might had different/missing data exoplayer relies on.

- ExoPlayer version number r2.17.1
- Android version 11
- Android device Nvidia Shield 2019 
- Shield Android TV SW Version 9.0.1(33.1.0.283)

[Video .ts record file from stream](https://mega.nz/file/hNYHhaBT#07b28mJje-CKXyrZwKCntrdUOM4v7V2xlN9GW4IPf5I)

File info
```
General
ID/String                        : 12 (0xC)
CompleteName                     : Den_utrolige_Dr._Pol_20220316_165043.ts
Format/String                    : MPEG-TS
FileSize/String                  : 31.4 MiB
Duration/String                  : 23 s 720 ms
OverallBitRate_Mode/String       : Variable
OverallBitRate/String            : 11.0 Mb/s

Video
ID/String                        : 1173 (0x495)
MenuID/String                    : 10205 (0x27DD)
Format/String                    : AVC
Format/Info                      : Advanced Video Codec
Format_Profile                   : Main@L4
Format_Settings                  : 4 Ref Frames
Format_Settings_CABAC/String     : No
Format_Settings_RefFrames/String : 4 frames
CodecID                          : 27
Duration/String                  : 23 s 560 ms
BitRate_Mode/String              : Constant
BitRate/String                   : 10 000 kb/s
Width/String                     : 1 920 pixels
Height/String                    : 1 080 pixels
DisplayAspectRatio/String        : 16:9
FrameRate/String                 : 25.000 FPS
Standard                         : PAL
ColorSpace                       : YUV
ChromaSubsampling/String         : 4:2:0
BitDepth/String                  : 8 bits
ScanType/String                  : MBAFF
ScanType_StoreMethod/String      : Interleaved fields
ScanOrder/String                 : Top Field First
Bits-(Pixel*Frame)               : 0.193
StreamSize/String                : 27.8 MiB (89%)
colour_range                     : Limited

Audio #1
ID/String                        : 4147 (0x1033)
MenuID/String                    : 10205 (0x27DD)
Format/String                    : MPEG Audio
Format_Version                   : Version 1
Format_Profile                   : Layer 2
CodecID                          : 3
Duration/String                  : 23 s 712 ms
BitRate_Mode/String              : Constant
BitRate/String                   : 224 kb/s
Channel(s)/String                : 2 channels
SamplingRate/String              : 48.0 kHz
FrameRate/String                 : 41.667 FPS (1152 SPF)
Compression_Mode/String          : Lossy
Video_Delay/String               : -1 s 119 ms
StreamSize/String                : 648 KiB (2%)
Language/String                  : English

Audio #2
ID/String                        : 4236 (0x108C)
MenuID/String                    : 10205 (0x27DD)
Format/String                    : MPEG Audio
Format_Version                   : Version 1
Format_Profile                   : Layer 2
CodecID                          : 3
Duration/String                  : 23 s 712 ms
BitRate_Mode/String              : Constant
BitRate/String                   : 192 kb/s
Channel(s)/String                : 2 channels
SamplingRate/String              : 48.0 kHz
FrameRate/String                 : 41.667 FPS (1152 SPF)
Compression_Mode/String          : Lossy
Video_Delay/String               : -1 s 119 ms
StreamSize/String                : 556 KiB (2%)
Language/String                  : Hungarian

Audio #3
ID/String                        : 4237 (0x108D)
MenuID/String                    : 10205 (0x27DD)
Format/String                    : MPEG Audio
Format_Version                   : Version 1
Format_Profile                   : Layer 2
CodecID                          : 3
Duration/String                  : 23 s 712 ms
BitRate_Mode/String              : Constant
BitRate/String                   : 128 kb/s
Channel(s)/String                : 2 channels
SamplingRate/String              : 48.0 kHz
FrameRate/String                 : 41.667 FPS (1152 SPF)
Compression_Mode/String          : Lossy
Video_Delay/String               : -1 s 47 ms
StreamSize/String                : 370 KiB (1%)
Language/String                  : Czech

Text
ID/String                        : 6597 (0x19C5)
MenuID/String                    : 10205 (0x27DD)
Format/String                    : DVB Subtitle
CodecID                          : 6
Duration/String                  : 21 s 960 ms
Video_Delay/String               : 1 s 160 ms
Language/String                  : Danish
```

I also managed to actually capture and screen record the video it self playing through tivimate by using [scrcpy](https://github.com/Genymobile/scrcpy)

Example here where you can clearly see what happens.
https://streamable.com/oiwkvh

**Comment by icbaker** [comment] 2022-03-21 11:19
Does the issue reproduce in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html)?

**Comment by wazerstar** [comment] 2022-03-21 12:30
> Does the issue reproduce in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html)?

Yes to some degree, its not the entire picture but some of it being effected when using the demo

**Comment by icbaker** [comment] 2022-05-25 08:47
> This is a one time experience I'm back on the test version and the same channel is no longer effected, I suspect the hdhomerun stream data information that was broadcasted might had different/missing data exoplayer relies on.

Given that the issue no longer reproduces on the problematic channel, it seems reasonable to assume this issue is due to a problem with the media. As such, I'm going to close this as 'bad media, not reproducible' as I don't think there's a clear indication of a bug in the library.

**Closed as completed by icbaker** 2022-05-25 08:47 UTC
Labels: bad media, wont fix: not reproducible
