### ISSUE TITLE
How to get the frame of video at specific position continuesly.

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#7075] opened 2020-03-12 12:54 UTC
I have used this example for retrieving frames of video  . Is there any way to get the frames of video continuously . 
https://github.com/rubensousa/PreviewSeekBar

**Comment by tonihei** [comment] 2020-03-12 13:00
Sounds like a duplicate of #5076? Please check Andrew's answer to this question

**Comment by tonihei** [comment] 2020-03-12 13:00
Closing for now, feel free to reopen if it's not a duplicate.

**Closed as completed by tonihei** 2020-03-12 13:00 UTC
Labels: duplicate, question

**Comment by waqasyousafy** [comment] 2020-03-12 13:15
i did not understand that example . I am beginner level developer of exoplayer . I am now working on showing the frame at seeking the seekbar . And find only one example of this as i mentioned above . But this is not correct example as a studied .

**Comment by tonihei** [comment] 2020-03-12 13:29
It's unfortunately not that easy. The feature you describe is called Picture-in-Picture mode and it's usually implemented by having a separate stream with keyframes only or sideloaded bitmaps that can be shown for seek points.  If it's a local video, you could also setup a second ExoPlayer with the same media that renders to the smaller surface and then call seekTo very often to immediately show the new frame.

**Comment by waqasyousafy** [comment] 2020-03-12 13:31
No brother it is not picture in picture mode . I am just talking about getting frames on seeking the seekbar and showing the frame in imageview like above example . 
As that link i mentioned

**Comment by tonihei** [comment] 2020-03-12 13:33
There are multiple things called picture-in-picture as far as I'm aware. But irrespective of the name, the other points above still apply.

**Comment by waqasyousafy** [comment] 2020-03-13 04:33
Above example do this already to load sideloaded images and the show on points . But i want to show the show current frame of video in image view or pic in pic as whatever you called. I have reference player is xplayer in googleplaystore.

**Comment by tonihei** [comment] 2020-03-13 10:14
If you just want to show the current frame in another view, you can probably just assign a new output surface to ExoPlayer?  If your plan is to show the same video in both views, then this is just not easily possible (see #6939 for a more detailed answer).
