### ISSUE TITLE
RTMP Play 

### ISSUE THREAD

**Issue by SudoDios** [google/ExoPlayer#9334] opened 2021-08-25 13:09 UTC
```
private val url = "rtmp://192.168.217.130:8080/live/MyLive"

private fun initializePlayer() {
        val videoTrackSelectionFactory = AdaptiveTrackSelection.Factory()
        val trackSelector = DefaultTrackSelector(this, videoTrackSelectionFactory)
        trackSelector.setParameters(trackSelector.buildUponParameters().setMaxVideoSizeSd())
        player = SimpleExoPlayer.Builder(this)
            .setTrackSelector(trackSelector)
            .setBandwidthMeter(DefaultBandwidthMeter.getSingletonInstance(this))
            .build()
        player.prepare()
        playVideo()
    }
private fun playVideo() {
        val videoSource = ProgressiveMediaSource.Factory(RtmpDataSourceFactory())
            .createMediaSource(MediaItem.fromUri(Uri.parse(url)))
        player.setMediaSource(videoSource)
        player.playWhenReady = true
}
```

get error

```
2021-08-25 17:34:31.225 6556-6661/com.sdidev.work.sockettets E/LoadTask: Unexpected exception loading stream
      java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.google.android.exoplayer2.util.ParsableBitArray.readBits(ParsableBitArray.java:175)
        at com.google.android.exoplayer2.audio.AacUtil.getAudioObjectType(AacUtil.java:331)
        at com.google.android.exoplayer2.audio.AacUtil.parseAudioSpecificConfig(AacUtil.java:196)
        at com.google.android.exoplayer2.audio.AacUtil.parseAudioSpecificConfig(AacUtil.java:179)
        at com.google.android.exoplayer2.extractor.flv.AudioTagPayloadReader.parsePayload(AudioTagPayloadReader.java:105)
        at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:59)
        at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:265)
        at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:170)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2021-08-25 17:34:31.242 6556-6659/com.sdidev.work.sockettets E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=0; index=0
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:430)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.google.android.exoplayer2.util.ParsableBitArray.readBits(ParsableBitArray.java:175)
        at com.google.android.exoplayer2.audio.AacUtil.getAudioObjectType(AacUtil.java:331)
        at com.google.android.exoplayer2.audio.AacUtil.parseAudioSpecificConfig(AacUtil.java:196)
        at com.google.android.exoplayer2.audio.AacUtil.parseAudioSpecificConfig(AacUtil.java:179)
        at com.google.android.exoplayer2.extractor.flv.AudioTagPayloadReader.parsePayload(AudioTagPayloadReader.java:105)
        at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:59)
        at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:265)
        at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:170)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by icbaker** [comment] 2021-08-25 13:18
The stack trace suggests the media might be invalid.

We'll need access to the media to diagnose further. Please either post a publicly accessible link here or send it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by SudoDios** [comment] 2021-08-25 21:44
I'm using [Node Media server](https://github.com/illuspas/Node-Media-Server).
I tested all the software that played rtmp and the stream was done.  
But it has problems with exoplayer.  
So the problem is not the source

**Comment by SudoDios** [comment] 2021-08-26 09:16
It worked and was healthy when I streamed it along with the video.
But when only audio was streamed, there was a problem without video.
How do I configure audio only?

**Comment by icbaker** [comment] 2021-08-26 10:08
> I tested all the software that played rtmp and the stream was done.
> But it has problems with exoplayer.
> So the problem is not the source

The media may be invalid (per the relevant spec) and still playable with some media players. When media doesn't meet its spec the result when playing it is [undefined behaviour](https://en.wikipedia.org/wiki/Undefined_behavior), so it's expected that some players will play it and others may not. I'm not saying the media is definitely invalid, it may be valid and there may be a bug in ExoPlayer, but it's impossible to tell without access to media to reproduce the problem you're seeing. The fact that it plays successfully in other players is not sufficient evidence to show a bug in ExoPlayer. 

----

> It worked and was healthy when I streamed it along with the video.
> But when only audio was streamed, there was a problem without video.
> How do I configure audio only?

If you're asking how to configure your RTMP stream to only include audio I'm afraid that's out of scope for this issue tracker - we can't offer help on the correct preparation of media.

If you want to configure ExoPlayer to play only the audio track from a stream that includes both audio and video then you should configure the [track selection](https://exoplayer.dev/track-selection.html) to disable the video track. The easiest way is probably by [disabling the video renderer](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.ParametersBuilder.html#setRendererDisabled(int,boolean)).

**Comment by SudoDios** [comment] 2021-08-26 11:18
I did this, but the problem was not solved

**Comment by icbaker** [comment] 2021-08-26 11:21
We need to be able to reproduce the problem to investigate further.

**Comment by SudoDios** [comment] 2021-08-26 14:01
How to setup rtmp with udp transport ??

**Comment by icbaker** [comment] 2021-08-26 14:07
Looks like RTMP-over-UDP is known as RTMFP: https://en.wikipedia.org/wiki/Real-Time_Media_Flow_Protocol#Difference_between_RTMP_and_RTMFP

And it looks like the LibRtmp-Client-for-Android that ExoPlayer's RTMP extension depends on has some references to `rtmfp`: https://github.com/ant-media/LibRtmp-Client-for-Android/search?q=rtmfp

I'd suggest trying an `rtmfp://` URI and seeing what happens. If it doesn't work it's probably something to discuss with the maintainers of LibRtmp-Client-for-Android.

**Comment by SudoDios** [comment] 2021-08-26 14:37
Thanks !

**Comment by icbaker** [comment] 2021-09-01 17:11
Closing as I think the question has been answered.

**Closed as completed by icbaker** 2021-09-01 17:11 UTC
Labels: question
