### ISSUE TITLE
Unable to play multicast video chunks in Exoplayer.

### ISSUE THREAD

**Issue by shekharbhadange-tudip** [google/ExoPlayer#3403] opened 2017-10-28 14:49 UTC
### Issue description

Actually, I am working on one live streaming video android application. In that, we have a multicast proxy server broadcaster which sends multicast chunks to Exoplayer. I am able to receive those chunks using UdpDataSource class but failed to play that chunks. Previously we don't have a multicast server at that time video plays nicely using the .mpd file for that I have used "DashMediaSource". but now when I am playing multicast chunks (basically it is .m4s chunks) it's giving following error:

### A full bug report captured from the device

```
10-28 19:24:39.214 5473-5473/com.google.android.exoplayer2.demo E/EventLogger: internalError [282.60, loadError]
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:722)
    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:645)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
```

### Link to test content
I have provided you test broadcaster at dev.exoplayer@gmail.com.

### Version of ExoPlayer being used
I am using com.google.android.exoplayer:exoplayer:r2.4.3 version.

I have also tried ExtractorMediaSource to play multicast chunks. but still, it gives the same error.

**Comment by ojw28** [comment] 2017-11-01 18:39
I see a receive timeout when trying to play the multicast stream. I'm also unable to play it in VLC. Please could you check this?

**Comment by shekharbhadange-tudip** [comment] 2017-11-02 09:59
I have sent you one email with multicast broadcaster which sends .m4s chunks to Exoplayer. I am unable to play those chunks. Please give a try to it.
Thanks!

**Comment by ojw28** [comment] 2017-11-02 15:12
VLC doesn't recognize the file you've provided as a media file. Neither does mediainfo. I don't think it's a media file.

**Comment by shekharbhadange-tudip** [comment] 2017-11-02 16:50
I have sent you a config file and broadcaster in an earlier mail, keep those file in one folder and then start broadcaster which basically broadcast multicast .m4s chunks.
For receiving multicast chunk on the device, please make sure broadcaster and device must be on one network (it will able to receive chunks on localhost only).

For receiving multicast chunks in UdpDataSource "open" method we need to connect to a multicast address, in which the host and port number already shared in the config file.
After receiving chunks in "read" method we need to parse packet like below.

    socket.receive(packet);
    ByteArrayInputStream stream = new ByteArrayInputStream(packet.getData());
    DataInputStream reader = new DataInputStream(stream);
       if (reader.read() == 1) {
                        byte[] fileUuidBuffer = new byte[24];
                        reader.read(fileUuidBuffer, 1, 16);
                        int fnameLen = reader.readInt();
                        int chnukCount = reader.readInt();
                        buffer2 = new byte[chnukCount];
                        reader.read(buffer2);
                        packet.setData(buffer2);
                    } else if (reader.read() == 2) {
                        byte[] fileUuidBuffer = new byte[24];
                        reader.read(fileUuidBuffer, 1, 16);
                        int chunkNum = reader.readInt();
                        int chunkLen = reader.readInt();
                        buffer2 = new byte[chunkLen];
                        reader.read(buffer2);
                        packet.setData(buffer2);
                    }


After parsing this packet when I return this packet further for playing video, It gives above mention error.
Please give a try to it. Again, thanks for helping me.

**Comment by ojw28** [comment] 2017-11-02 16:56
We're not going to run executables that are emailed to us, sorry. You'll need to provide some easier reproduction steps for us to investigate.

**Comment by ojw28** [comment] 2017-11-13 22:05
Closing due to lack of acceptable reproduction steps. If you're able to provide better reproduction steps, please respond here and we'll re-open the issue.

**Closed as completed by ojw28** 2017-11-13 22:05 UTC
Labels: need more info
