### ISSUE TITLE
HLS + CMAF + Playready/CBC support

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#5404] opened 2019-01-17 16:24 UTC
### Issue description
Playback of HLS CMAF test contents results on the following error:
...
2019-01-17 16:33:10.333 26942-27094/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2494)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1016)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
...
Does ExoPlayer 2.9.3 supports playback of HLS CMAF streams? If so, are you planning to add any sample contents to the demo app in the future?

### Reproduction steps
Attempt to start the playback of the HLS CMAF test contents

### Link to test content
Link to test contents will be sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
ExoPlayer 2.9.3

### Device(s) and version(s) of Android being used
Amazon Fire TV Stick 4K (2018)

### A full bug report captured from the device
A full bug report log will be sent to dev.exoplayer@gmail.com

**Comment by erdemguven** [comment] 2019-01-22 10:24
@AquilesCanta could you take a look at this.

**Comment by moacir69** [comment] 2019-02-08 12:02
Hi,
Do you have any news regarding this issue?
Thank you,

Moacir

**Comment by AquilesCanta** [comment] 2019-02-11 17:41
> If so, are you planning to add any sample contents to the demo app in the future?

Unfortunately we don't have any that can be publicly shared. 

>  Does ExoPlayer 2.9.3 supports playback of HLS CMAF streams? 

Yes. The clear version of the stream that you provided works well. The play ready version doesn't contain the right keyformat (for playready, it should be `com.microsoft.playready`) and a license server url also needs to be provided. Have a look at the demo app's media.exolist.json file to see how that can be provided in the demo app.

**Comment by moacir69** [comment] 2019-02-12 08:49
Thanks for the information. We will update the sample contents and will retry the playback.
Warm regards,

Moacir

**Comment by moacir69** [comment] 2019-02-18 12:09
Hi @AquilesCanta,
We have checked the playback behavior of the Microsoft HLS and/or MPEG-DASH contents mentioned in https://test.playready.microsoft.com/Content/Content4Xs in the latest ExoPlayer 2.9.5 demo app running on the following devices:
* Amazon Fire TV Stick Gen 2 (2016) / Fire OS 5.2.2.0
* Samsung Galaxy Tab S2 (SM-T710) / Android 7.0
* Google Pixel 2 / Android / Android 9

And with all of them, there is the following error at application level:
...
Media includes video tracks, but none are playable by this device
...
Media includes audio tracks, but none are playable by this device
...

We have confirmed that the test contents that we have provided by email are using "com.microsoft.playready" as key format, but with those ones the error is different:
...
02-18 13:00:25.986 6790-8130/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
    android.media.MediaCodec$CodecException: Error 0xffffffea
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:978)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1016)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
...

Can you please reopen this issue?
Thank you,

Moacir

**Comment by AquilesCanta** [comment] 2019-02-18 13:55
Hi Moacir, none of the playlists I can see in the e-mail you sent me contain the correct key format. Please send me another e-mail with a single link so I don't have to go through all content to make sure none of them contains the required keyformat. 

EDIT: I removed the provided stream. It doesn't contain encryption tags. I'll try to post another one once I find one.

Regarding the "Media includes video tracks, but none are playable by this device" toasts, it make sense, considering you need to try the streams on a device that actually supports playready. I am pretty sure neither Pixel 2 or Galaxy Tab support playready. I don't know about the fire TV stick.

**Comment by moacir69** [comment] 2019-02-19 09:46
Hi @AquilesCanta,
Thanks for your feedback. Indeed only the Amazon Fire TV Stick Gen 2 supports hardware DRM.
Is there a minimum Android OS version required in order to support CMAF?
A link to a single test content will be sent by email.
Warm regards,

Moacir

**Comment by AquilesCanta** [comment] 2019-02-19 10:57
> Is there a minimum Android OS version required in order to support CMAF?

CMAF support is android-version independent.

If the content is encrypted using CDM-DRM (Widevine or Playready), then support [does depend on the Android version](https://google.github.io/ExoPlayer/supported-formats.html). Please post here once the e-mail is sent. Also include a bugreport captured shortly after playing the content, please.

**Comment by moacir69** [comment] 2019-02-20 16:17
Hi @AquilesCanta,
When using an Amazon Fire TV 4K (2018) like this one https://developer.amazon.com/docs/fire-tv/device-specifications.html?v=ftvstick4kgen1, the related error log messages are the following:
...
2019-02-20 17:12:19.964 22053-22978/com.google.android.exoplayer2.demo E/MediaDrm-JNI: Illegal state exception: Failed to get key request: Unsupported scheme or data format (-2006)
2019-02-20 17:12:19.968 22053-22988/com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
2019-02-20 17:12:19.975 22053-22053/com.google.android.exoplayer2.demo E/EventLogger: internalError [2.14, 0.00, window=0, period=0, drmSessionManagerError]
    android.media.MediaDrm$MediaDrmStateException: Failed to get key request: Unsupported scheme or data format
        at android.media.MediaDrm.getKeyRequest(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:136)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:388)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:327)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:164)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:559)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1075)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
...
This is happening with the following content taken from https://test.playready.microsoft.com/Content/Content4X:

"name": "cmaf_protected",
"uri": "https://test.playready.microsoft.com/media/dash/APPLEENC_CBCS_BBB_1080p/1080p_alternate.m3u8",
"drm_scheme": "playready",
"drm_license_url": "http://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(persist:false,ck:W31bfVt9W31bfVt9W31bfQ==,ckt:aescbc)"

I will attach the related bug report.
Thanks,


Moacir

**Comment by moacir69** [comment] 2019-02-20 16:18
[bugreport-NS6258-2019-02-20-17-12-25.zip](https://github.com/google/ExoPlayer/files/2885451/bugreport-NS6258-2019-02-20-17-12-25.zip)

**Comment by AquilesCanta** [comment] 2019-02-20 18:24
I think it's worth contacting the device manufacturer, since MediaDrm.getKeyRequest is failing to recognize the key request data. 

I have seen this in the past for PlayReady 4.3.0.0 (Internal ref: b/112135619 and b/112139868), which is the version that includes support for ALGID="AESCBC". Besides contacting the device manufacturer, I think it's worth trying to play AES-CTR streams, which in my experience do work.

I'll keep this github issue open to track support for CBC in Playready in Android devices (note: this doesn't include fire tv devices, since that's out of my reach).

**Comment by moacir69** [comment] 2019-02-22 13:28
Hi @AquilesCanta ,
Thanks for the update. When a new software update is available for that device, we will check if there are improvements. We will also check the playback behaviour in other Android TV devices with AES/CBC and or AES/CTR contents.
Can you provide a list of Android devices/versions where CMAF playback has been positively verified?
Warm regards,

Moacir

**Comment by AquilesCanta** [comment] 2019-02-22 13:38
Sorry, I had thought I had added a to linked this. [This is the first page](https://google.github.io/ExoPlayer/supported-formats.html) to look at. Try PlayReady+CTR on Android TV, or widevine CBC or CTR. Just keep in mind API level support.

**Comment by moacir69** [comment] 2019-02-22 13:40
Indeed you have added the link above, but I meant if you could provide a list of specific Android device models.
Thanks,

Moacir

**Comment by AquilesCanta** [comment] 2019-02-22 13:52
I've just realized that PlayReady had accidentally been removed from the HLS supported formats page. I can confirm that widevine works as expected on devices I've tested on. PlayReady works in CTR mode. 

If you run into issues in any of these 3 scenarios (Widevine CBC/CTR, Playready CTR) please file a new issue including all info requested in the issue template.

**Comment by moacir69** [comment] 2019-02-22 14:06
OK, thank you.
Warm regards,

Moacir

**Comment by AquilesCanta** [comment] 2019-05-09 19:55
I'll be closing this issue since it's not tracking an ExoPlayer issue. We have reported issues with PlayReady + CBC in [internal ref: b/112139868].

**Closed as completed by AquilesCanta** 2019-05-09 19:55 UTC
Labels: enhancement
