### ISSUE TITLE
Some Samsung devices crashes - CryptoException: Error decrypting data.

### ISSUE THREAD

**Issue by haitech** [google/ExoPlayer#655] opened 2015-07-24 12:35 UTC
We are having issue with some samsung devices that crashes on live stream after few seconds. The stream is a dash + widevine. And the current version we are using is ExoPlayer 1.4.1 (commit 9e0ca9e).
I added some logs and what type of devices we have been testet on. And sent you a separate mail with stream url. All test was performed with the ExoPlayer demo app (commit 9e0ca9e) - below you will see the modified code.

I think this is related to issue #614 

If you are missing some information let me know, thanks.

### DemoPlayer code modify
Samples.java:
```Java
new Sample("My Dash stream", "http://xxxx.mpd", PlayerActivity.TYPE_DASH),
```
WidevineTestMediaDrmCallback.java:
```Java
  public WidevineTestMediaDrmCallback(String videoId) {
    defaultUri = "http://OurWideVineServer.com/?ourKey";
  }
```
PS! I sent you a mail (olly.exoplayer) with correct informations with stream URL and widevine URL.

### Tested On:
* [Google Nexus 6] (http://www.gsmarena.com/motorola_nexus_6-6604.php), Android 5.1.1 - Works.
* [Samsung Galaxy Tab 3 10.1] (http://www.gsmarena.com/samsung_galaxy_tab_3_10_1_p5220-5491.php), GT-P5520, Android 4.4.2 - Works.
* [Samsung Galaxy Note 2] (http://www.droidgod.com/2014/06/samsung-galaxy-note-2-gt-n7105-full-specifications-and-features/), GT-N7105, Android 4.4.2 - Works.
* [Samsung Galaxy S5] (http://www.gsmarena.com/samsung_galaxy_s5-6033.php), SM-G900F, Android 5.0.0 - Works.
* [Samsung Galaxy S4] (http://www.gsmarena.com/samsung_i9505_galaxy_s4-5371.php), GT-I9505, Android 4.4.2 - Crashes.
* [Samsung Galaxy Note 10.1](http://www.gsmarena.com/samsung_galaxy_note_10_1_(2014_edition)-5677.php), SM-P600, Android 4.4.2 - Crashes and reboots.

### Log:
[Samsung S4] (https://gist.github.com/haitech/a7bb8686d4d1b96ffc9b)
[Samsung Galaxy Note 10.1] (https://gist.github.com/haitech/5e9b13bea38c151e948c)

**Comment by jatago** [comment] 2015-09-02 16:28
Any progress in this issue? We are experiencing similar behaviour with our streams. Trying to figure out if there is any differences as some content seems to be playing just fine and some other content gets this CryptoException. 

Will post any findings.

**Comment by artnalban** [comment] 2015-11-20 19:44
We are having exactly the same problem on latest ExoPlayer (1.5.2). Device that we can easily reproduce this problem is Samsung GT-I9500.

**Comment by nosyjoe** [comment] 2015-12-02 14:14
experiencing the same issue (Crash& Reboot) on a Samsung Galaxy S5 mini (SM-G800F) with Android 4.4.2 using exoplayer 1.5.2

```
Caused by: android.media.MediaCodec$CryptoException: Error decrypting data.
                         E      at android.media.MediaCodec.queueSecureInputBuffer(Native Method)
```

**Comment by tajoumal** [comment] 2015-12-10 04:27
We have the same issue here on Samsung devices and LG G4 / 5.1.1. 

This is a critical issue, any workaround?

**Comment by wvpaf** [comment] 2016-05-03 22:10
I see that issue #614 was closed as a content issue. If this is a dupe as stated in the original report, I will close. 

If any participant feels differently please provide a full log, not filter and including system messages, and  an ADB bug report. 

Thanks.

**Comment by giladna** [comment] 2016-06-02 11:50
We have the same Issue sending info via email

**Comment by itaykinnrot** [comment] 2016-06-02 17:34
We found the issue,
When the duration time in the licence response is relatively small the license plays fine.
When the duration is big (e.g: 1464944739) there is failures on some of the devices.(S4 for example)

Try to make sure the license response duration is not too big.
Thanks @giladna

**Comment by wvpaf** [comment] 2016-06-21 21:11
Thank you for the follow up. will close the issue now.

**Closed by wvpaf** 2016-06-21 21:11 UTC
Labels: need more info
