### ISSUE TITLE
How to resolve intermittent IndexOutOfBoundsException?

### ISSUE THREAD

**Issue by appstronautstudios** [google/ExoPlayer#8739] opened 2021-03-19 21:28 UTC
## Crash details

In rare instances our app will crash due to an **IndexOutOfBoundsException**. We have never been able to reproduce this locally and from the Android crash report it is very rare to affect a user more than once and only affects a small portion of our userbase. If affects users on a wide range of supported versions (**crashes found on SDK 26-30**). The stacktrace is as follows:

```
java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.get (ArrayList.java:437)
  at com.google.android.exoplayer2.source.dash.DefaultDashChunkSource.updateManifest (DefaultDashChunkSource.java:219)
  at com.google.android.exoplayer2.source.dash.DashMediaPeriod.updateManifest (DashMediaPeriod.java:161)
  at com.google.android.exoplayer2.source.dash.DashMediaSource.processManifest (DashMediaSource.java:1023)
  at com.google.android.exoplayer2.source.dash.DashMediaSource.lambda$new$0 (DashMediaSource.java:648)
  at com.google.android.exoplayer2.source.dash.DashMediaSource.lambda$2x_pcv0Hm1_v2pXJ1pxCT1ggRhc (DashMediaSource.java)
  at com.google.android.exoplayer2.source.dash.-$$Lambda$DashMediaSource$2x_pcv0Hm1_v2pXJ1pxCT1ggRhc.run (Unknown Source:2)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.os.HandlerThread.run (HandlerThread.java:65)
```

The affected line has been highlighted on our version of ExoPlayer:

![image](https://user-images.githubusercontent.com/75040301/111841047-916bfc80-88ba-11eb-933d-13eda66992c2.png)

## Environment Details

- minSdkVersion 22
- targetSdkVersion 29
- implementation 'com.google.android.exoplayer:exoplayer:2.12.3'

#### Usage of DefaultDashChunkSource

```
  DashChunkSource.Factory dashChunkSourceFactory = new DefaultDashChunkSource.Factory(dataSourceFactory);
  DashMediaSource.Factory mediaSourceFactory = new DashMediaSource.Factory(dashChunkSourceFactory, dataSourceFactory);
  mediaSourceFactory.setManifestParser(new LenientDashManifestParser());
  DashMediaSource mediaSource = mediaSourceFactory.createMediaSource(uri);
```

We subclassed `DashManifestParser` as `LenientDashManifestParser` to make `parseInt` return default value in the case of a `NumberFormatException`. (Our stream provider uses String as the datatype for AdaptationSet "id" which is invalid)
 
## Question

How can we debug or workaround this internal crash? Any comments or suggestions would be appreciated

**Comment by andrewlewis** [comment] 2021-03-22 10:38
Given the issue is very rare I guess it won't be practical for us to try and reproduce the error. Looking at the code, is it possible that representations are being removed from the DASH manifest? I think that would generally require switching to a new period.

@ojw28 Please could you take a look?

**Comment by ojw28** [comment] 2021-03-29 12:07
>  Looking at the code, is it possible that representations are being removed from the DASH manifest? I think that would generally require switching to a new period.

`DashMediaSource.lambda$new$0 (DashMediaSource.java:648)` is a simulated manifest update. The manifest is unchanged in this case, so I don't think this can be the cause.

> We subclassed DashManifestParser as LenientDashManifestParser to make parseInt return default value in the case of a NumberFormatException. (Our stream provider uses String as the datatype for AdaptationSet "id" which is invalid)

Given you have some custom logic to work around a known issue with the streams that you're using, and given that you're the only person to have reported this error, I think your custom logic needs to be the prime suspect here. Returning a default value could presumably result in multiple `AdaptationSet` instances being assigned the same ID within a containing period, which is invalid and could cause problems. If the streaming provider is using strings, and if those strings are unique within the containing periods, then it might be a better option to fall back to using the string's hash code as the ID in this case.

Closing this issue for now, since I don't think there's really anything actionable for us to do here at this point.

**Closed as completed by ojw28** 2021-03-29 12:07 UTC
Labels: question

**Comment by appstronautstudios** [comment] 2021-03-29 16:51
> Returning a default value could presumably result in multiple AdaptationSet instances being assigned the same ID within a containing period, which is invalid and could cause problems. If the streaming provider is using strings, and if those strings are unique within the containing periods, then it might be a better option to fall back to using the string's hash code as the ID in this case.

This is a good suggestion thank you!
