### ISSUE TITLE
[Question] What's the best way to implement seamless manual switching for HLS streams?

### ISSUE THREAD

**Issue by Gensoukyou1337** [google/ExoPlayer#5191] opened 2018-12-04 09:06 UTC
I've read issue #676 in which the Exoplayer team said they had no immediate plans to implement seamless manual switching between HLS video tracks, so I decided to look into the source code to figure out a workaround for that.

Right now, I settled for clamping the bitrate estimate of my custom implementation of the BandwidthMeter, introducing both a floor limit and a ceiling limit, so as to force it above the track I wanted to choose, but below other tracks I don't want that are higher than that. The problem is that this approach assumes that the bandwidth stays good - that the bitrate estimate stays well above the bitrate requirements of the best quality track all the time. Also that it requires playlist-specific hard-coded values for the limits.

The `TrackSelector` parameters approach as described in #676 and others just creates a new `AdaptiveTrackSelection` that ends up resetting the tracks, setting the playback back by a few seconds/segments, so it's neither seamless nor always-live (for me, that is).

I could set up a variable storing the very first `AdaptiveTrackSelection` created by its factory, but I'm worried about the side effects (like the `BehindLiveWindowException`s and what happens then).

So, what other approaches should I consider for this?

**Comment by tonihei** [comment] 2018-12-05 09:32
This is a duplicate of #2250. 

Such a feature is not currently supported out-of-the-box, but you can implement your own `TrackSelection` (similar to the existing `AdaptiveTrackSelection`) which filters the tracks dynamically. Please be aware that the track selection methods are called on the internal playback thread and you'll need to have some kind of synchronization or message passing to update the selection from the app code.

**Closed as completed by tonihei** 2018-12-05 09:32 UTC
Labels: duplicate
