### ISSUE TITLE
When Exoplayer will throw BaseRenderer.createRendererException

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#7745] opened 2020-08-12 18:40 UTC
### [REQUIRED] Searched documentation and issues
Searched documentation and went through https://github.com/google/ExoPlayer/issues/7491 raised by us but we dont understand why this issue happens randomly on same device

### [REQUIRED] Question
When exoplayer throws BaseRenderer.createRendererException ?

### A full bug report captured from the device
We are seeing random errors on certain devices even though we are playing the same stream.
There is no ad playback involved which means there is only one player at a time. Only one content is playing.

Below is the error we see

```
08-12 21:11:48.838 24271 24271 D EventLogger: tracks [eventTime=12.43, mediaPos=3154.57, window=0, period=0
08-12 21:11:48.838 24271 24271 D EventLogger:   Renderer:0 [
08-12 21:11:48.838 24271 24271 D EventLogger:     Group:0, adaptive_supported=YES [
08-12 21:11:48.839 24271 24271 D EventLogger:       [ ] Track:0, id=1, mimeType=video/avc, bitrate=3500000, codecs=avc1.640028, res=1920x1080, fps=25.0, supported=YES
08-12 21:11:48.839 24271 24271 D EventLogger:       [ ] Track:1, id=2, mimeType=video/avc, bitrate=2000000, codecs=avc1.64001f, res=1280x720, fps=25.0, supported=YES
08-12 21:11:48.840 24271 24271 D EventLogger:       [ ] Track:2, id=3, mimeType=video/avc, bitrate=1200000, codecs=avc1.64001f, res=1280x720, fps=25.0, supported=YES
08-12 21:11:48.840 24271 24271 D EventLogger:       [X] Track:3, id=4, mimeType=video/avc, bitrate=900000, codecs=avc1.64001f, res=960x540, fps=25.0, supported=YES
08-12 21:11:48.840 24271 24271 D EventLogger:       [X] Track:4, id=5, mimeType=video/avc, bitrate=664000, codecs=avc1.4d401e, res=640x360, fps=25.0, supported=YES
08-12 21:11:48.840 24271 24271 D EventLogger:       [X] Track:5, id=6, mimeType=video/avc, bitrate=412000, codecs=avc1.4d4015, res=512x288, fps=25.0, supported=YES
08-12 21:11:48.841 24271 24271 D EventLogger:       [X] Track:6, id=7, mimeType=video/avc, bitrate=224000, codecs=avc1.4d400d, res=384x216, fps=25.0, supported=YES
08-12 21:11:48.841 24271 24271 D EventLogger:     ]
08-12 21:11:48.841 24271 24271 D EventLogger:   ]
08-12 21:11:48.841 24271 24271 D EventLogger:   Renderer:1 [
08-12 21:11:48.841 24271 24271 D EventLogger:     Group:0, adaptive_supported=N/A [
08-12 21:11:48.841 24271 24271 D EventLogger:       [X] Track:0, id=8, mimeType=audio/mp4a-latm, bitrate=64000, codecs=mp4a.40.2, sample_rate=48000, language=und, supported=YES
08-12 21:11:48.841 24271 24271 D EventLogger:     ]
08-12 21:11:48.841 24271 24271 D EventLogger:   ]
08-12 21:11:48.842 24271 24271 D EventLogger:   Renderer:2 [
08-12 21:11:48.842 24271 24271 D EventLogger:     Group:0, adaptive_supported=N/A [
08-12 21:11:48.842 24271 24271 D EventLogger:       [ ] Track:0, id=ENG, mimeType=text/vtt, language=en, supported=YES
08-12 21:11:48.842 24271 24271 D EventLogger:     ]
08-12 21:11:48.842 24271 24271 D EventLogger:     Group:1, adaptive_supported=N/A [
08-12 21:11:48.842 24271 24271 D EventLogger:       [ ] Track:0, id=ENG, mimeType=text/vtt, language=en, supported=YES
08-12 21:11:48.842 24271 24271 D EventLogger:     ]
08-12 21:11:48.842 24271 24271 D EventLogger:   ]
08-12 21:11:48.842 24271 24271 D EventLogger: ]
08-12 21:11:48.918 24271 24271 D EventLogger: videoSize [eventTime=12.51, mediaPos=3154.65, window=0, period=0, 960, 540]
08-12 21:11:48.963 24271 24271 D EventLogger: renderedFirstFrame [eventTime=12.52, mediaPos=3154.65, window=0, period=0, Surface(name=null)/@0xfdc9556]
08-12 21:11:50.087 24271 24271 D EventLogger: state [eventTime=13.68, mediaPos=3155.82, window=0, period=0, true, BUFFERING]
08-12 21:11:50.101 24271 24271 D EventLogger: isPlaying [eventTime=13.69, mediaPos=3155.82, window=0, period=0, false]
08-12 21:11:50.442 24271 24271 D EventLogger: decoderInputFormat [eventTime=14.03, mediaPos=3155.82, window=0, period=0, video, id=7, mimeType=video/avc, bitrate=224000, codecs=avc1.4d400d, res=384x216, fps=25.0]
08-12 21:11:50.458 24271 24271 D EventLogger: downstreamFormat [eventTime=14.05, mediaPos=3155.82, window=0, period=0, id=7, mimeType=video/avc, bitrate=224000, codecs=avc1.4d400d, res=384x216, fps=25.0]
08-12 21:11:55.064 24271 24271 D EventLogger: decoderDisabled [eventTime=18.66, mediaPos=3155.82, window=0, period=0, video]
08-12 21:11:55.080 24271 24271 D EventLogger: decoderDisabled [eventTime=18.67, mediaPos=3155.82, window=0, period=0, audio]
08-12 21:11:55.133 24271 24271 D EventLogger: mediaPeriodReleased [eventTime=18.73, mediaPos=3155.82, window=0, period=0]
08-12 21:11:55.136 24271 24271 E EventLogger: playerFailed [eventTime=18.73, mediaPos=3155.82, window=0, period=0
08-12 21:11:55.136 24271 24271 E EventLogger:   com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
08-12 21:11:55.136 24271 24271 E EventLogger:       at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
08-12 21:11:55.136 24271 24271 E EventLogger:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:735)
08-12 21:11:55.136 24271 24271 E EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
08-12 21:11:55.136 24271 24271 E EventLogger:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
08-12 21:11:55.136 24271 24271 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:103)
08-12 21:11:55.136 24271 24271 E EventLogger:       at android.os.Looper.loop(Looper.java:237)
08-12 21:11:55.136 24271 24271 E EventLogger:       at android.os.HandlerThread.run(HandlerThread.java:67)
08-12 21:11:55.136 24271 24271 E EventLogger:   Caused by: java.lang.IllegalStateException
08-12 21:11:55.136 24271 24271 E EventLogger:       at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
08-12 21:11:55.136 24271 24271 E EventLogger:       at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2726)
08-12 21:11:55.136 24271 24271 E EventLogger:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1053)
08-12 21:11:55.136 24271 24271 E EventLogger:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:722)
08-12 21:11:55.136 24271 24271 E EventLogger:       ... 5 more
08-12 21:11:55.136 24271 24271 E EventLogger: ]
```

Here is the bugreport from one such device: https://drive.google.com/file/d/1M42Jet-5woRp7_0urOp5zKryHcptrVL2/view?usp=sharing
On the same device we see random failure for the same stream.

Can you please help us to understand the following

1. When will exoplayer throw this kind of error?
2. Can it happen that exoplayer and renderer release takes time because of which createrenderer fails next time randomly?
2. How can we avoid this error?

**Comment by andrewlewis** [comment] 2020-08-13 11:11
Please could you update the sharing settings for the bug report shared via drive, or attach it to an email to `dev.exoplayer@gmail.com`? At the moment I don't have permission to view it.

To answer the questions:
1. As soon as we get such an error from `MediaCodec` we post it back to the player error event listener. For underlying errors related to resource usage it's likely that `MediaCodec` will throw from `configure` or `start` but the error can also be notified via other methods. From this app perspective this can happen as early as we are buffering the stream (as part of that we will render the first frame so we have to decode it).
1. `Player.release` will block until it is safe to reacquire resources, so if you are using multiple players it is necessary to serialize releasing one and creating the next, if you want to avoid trying to acquire multiple decoders of the same type concurrently. (Similarly we strongly recommend releasing ExoPlayer when your app goes into the background, within one of the Android app lifecycle methods called on the main thread, in case the user immediately switches to another app that tries to acquire the resources being released.)
1. It's difficult to say without understanding what caused the error (the information provided doesn't give many clues to the underlying cause). I'm pretty sure this error could be caused by the codec not being able to acquire resources. Or it could be that the stream exceeds the device capabilities. A full bug report may well have more useful information logged just before the error occurred.

Should we duplicate this to #7491 or is there something different to track here?

**Comment by krackjack234** [comment] 2020-08-13 11:19
Hi @andrewlewis  you can check the bugreport here: https://drive.google.com/file/d/1M42Jet-5woRp7_0urOp5zKryHcptrVL2/view?usp=sharing


In #7491 we were having 2 players at same time, one was IMA default player (using VideoView) and another is exoplayer (for content playback). We fixed it on those platforms (mostly tvs) by having either the ima player or the exoplayer alive in the system but not both at the same time.

But here we have only 1 player and we this issue.

Below is the sequence of player init and release sequence

```
08-12 20:53:45.232 23004 23004 I ExoPlayerImpl: Init b0ed76a [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29]
08-12 20:58:18.335 23004 23004 I ExoPlayerImpl: Release b0ed76a [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29] [goog.exo.core, goog.exo.hls, goog.exo.ui, goog.exo.dash]
08-12 21:01:22.169 24271 24271 I ExoPlayerImpl: Init cd1585a [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29]
08-12 21:09:20.774 24271 24271 I ExoPlayerImpl: Release cd1585a [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29] [goog.exo.core, goog.exo.hls, goog.exo.ui, goog.exo.dash]
08-12 21:11:36.403 24271 24271 I ExoPlayerImpl: Init cdbff04 [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29]
08-12 21:11:55.315 24271 24271 I ExoPlayerImpl: Release cdbff04 [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29] [goog.exo.core, goog.exo.hls, goog.exo.ui, goog.exo.dash]
08-12 21:12:13.720 24271 24271 I ExoPlayerImpl: Init 1fef8b4 [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29]
08-12 21:26:51.266 24271 24271 I ExoPlayerImpl: Release 1fef8b4 [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29] [goog.exo.core, goog.exo.hls, goog.exo.ui, goog.exo.dash]
08-12 21:27:32.102 24271 24271 I ExoPlayerImpl: Init 66beea [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29]
08-12 21:36:43.431 24271 24271 I ExoPlayerImpl: Release 66beea [ExoPlayerLib/2.11.4] [m21, SM-M215F, samsung, 29] [goog.exo.core, goog.exo.hls, goog.exo.ui, goog.exo.dash]
```

Here I dont see multiple exoplayer instances at any time. Still the issue happened at 08-12 21:11:55.136

Do let us know what other information will help to analyse this issue.

**Comment by andrewlewis** [comment] 2020-08-13 11:35
The bug report doesn't seem to include `ExoPlaybackException`. Please could you share a bug report taken just after seeing the error so we can look at media framework logging just before it?

**Comment by krackjack234** [comment] 2020-08-14 16:41
Hi @andrewlewis  we have shared the logs to dev.exoplayer@gmail.com

**Comment by andrewlewis** [comment] 2020-08-17 13:14
There isn't much useful in the framework logging unfortunately:

```
08-14 21:52:32.372 10392 12319 16055 E ACodec  : signalError(omxError 0x80001001, internalError -110)
08-14 21:52:32.373 10392 12319 16054 E MediaCodec: Codec reported err 0xffffff92, actionCode 0, while in state 6
```

Before this `libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)` suggests the decoder is getting into a bad state. The device's DRM service is also getting killed somehow:

```
08-14 21:52:29.357  1046  4412  7470 W OMXNodeInstance: getConfig(0xeba5a000:Exynos.avc.dec, ??(0x7f030009)) (0x8000101a)
08-14 21:52:29.357 10392 12319 16055 W ACodec  : [OMX.Exynos.avc.dec] getting HDRStaticInfo failed even though codec advertises support
08-14 21:52:29.359 10099 16696 16696 I SEMS:DataAdapterLog_11.1.0: [2][AppContext] already set
08-14 21:52:29.359  lmkd  4346  4346 I lmkd    : cached 1, sandbox(not0) 0
08-14 21:52:29.362  1046  4412 16056 I EXYNOS_BASE_PORT: [0xebab8800][Exynos_OMX_PortDisableProcess] Before disabling output port, do flush
08-14 21:52:29.363 10099 16696 16696 I SEMS:DataAdapterLog_11.1.0: [2][AppContext] already set
08-14 21:52:29.363  1046  4412  3366 E EXYNOS_VIDEO_DECCONTROL: [0xebab8800][Exynos_OMX_FreeBuffer] Buffer can't be freed because this(0xeba42460) is already in component
08-14 21:52:29.363  1046  4412  3366 E EXYNOS_VIDEO_DECCONTROL: [0xebab8800][Exynos_OMX_FreeBuffer] output port : invalid state : comp state(0x3), port state(0x2), enabled(0x1)
[...]
08-14 21:52:29.366  lmkd  4346  4346 I lmkd    : Reclaim Mem 'android:drmService' (11208), uid 1000, oom_adj 999, state 11 to free 126796kB
08-14 21:52:29.367  1046  4412 16061 W libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
```

A NuPlayer instance was active just before this (`MediaPlayerService` logging), although maybe it was released in time. Please do double check that the lifetime of any MediaPlayer/VideoView instance cannot possibly overlap with the ExoPlayer instance anyway.

Do you see any warnings if you play the same stream with another player like ffmpeg or VLC? I think I've seen `libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)` logged when the stream was not valid in the past. However, if that is the problem, I'd expect the error to occur every time you try to play the stream (not intermittently). Are there any other devices where this stream doesn't play properly? If not, unfortunately I think this will need to be reported to Samsung.

**Comment by krackjack234** [comment] 2020-08-17 13:52
> Please do double check that the lifetime of any MediaPlayer/VideoView instance cannot possibly overlap with the ExoPlayer instance anyway.

@andrewlewis  Do you mean to say having multiple instances of MediaPlayer/VideoView/Exoplayer can cause renderer to fail on some devices based on device limitations?

**Comment by andrewlewis** [comment] 2020-08-17 13:59
The problem is having too many video decoders acquired at the same time. This is why it's important to ensure you release one player before trying to create another. See also #1286. If you reboot the device and play just this one stream in the ExoPlayer demo app do you see the same error?

**Comment by krackjack234** [comment] 2020-09-05 04:33
Hi, we are not able to reproduce this with vanilla exoplayer app. We will check more on this

**Comment by andrewlewis** [comment] 2020-10-05 13:04
Closing on the assumption that this was an app issue.

**Closed as completed by andrewlewis** 2020-10-05 13:04 UTC
Labels: wont fix: app issue
