### ISSUE TITLE
the input format and output format 's height and width are different

### ISSUE THREAD

**Issue by linyongsheng** [google/ExoPlayer#3031] opened 2017-07-06 01:58 UTC
Hi team:
I use ExoPlayer to play live stream in Tmall TV Box S1。The live stream is HTTP-FLV。I find some live stream the input format's width and height are different to output format's width and height。
I change the code in class 'MediaCodecVideoRenderer' follow:
```
protected void onOutputFormatChanged(MediaCodec codec, MediaFormat outputFormat) {
    boolean hasCrop = outputFormat.containsKey(KEY_CROP_RIGHT)
        && outputFormat.containsKey(KEY_CROP_LEFT) && outputFormat.containsKey(KEY_CROP_BOTTOM)
        && outputFormat.containsKey(KEY_CROP_TOP);
    currentWidth = hasCrop
        ? outputFormat.getInteger(KEY_CROP_RIGHT) - outputFormat.getInteger(KEY_CROP_LEFT) + 1
        : outputFormat.getInteger(MediaFormat.KEY_WIDTH);
    currentHeight = hasCrop
        ? outputFormat.getInteger(KEY_CROP_BOTTOM) - outputFormat.getInteger(KEY_CROP_TOP) + 1
        : outputFormat.getInteger(MediaFormat.KEY_HEIGHT);
    currentPixelWidthHeightRatio = pendingPixelWidthHeightRatio;
    if (format != null) {
        currentHeight = format.height;
        currentWidth = format.width;
    }
.....
}
```
is OK?

**Comment by ojw28** [comment] 2017-07-07 11:46
Is this an issue report, or is it a question? It's a little unclear what you're asking. If it's a question, can you try and phrase it more precisely, and provide a concrete example that we can use to reproduce what you're seeing? Thanks.

**Comment by ojw28** [comment] 2017-07-19 20:20
Closing due to lack of information.

**Closed as completed by ojw28** 2017-07-19 20:20 UTC
Labels: question, need more info
