### ISSUE TITLE
The video stuck only playback audio

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#4473] opened 2018-07-05 05:35 UTC
ExoPlayer 2.8.1
Device Galaxy s8+ 8.0
this video https://ufile.io/bw922 playback only have audio, the video stuck,only show one frame

**Comment by tonihei** [comment] 2018-07-05 09:42
That file contains an edit list which crops the video from frame 3 to frame 256. Unfortunately, the key frames needed to decode the video are at frame 0 and frame 250. So what happens is that we play the audio only until we reach the time of the frame 250. And only then start displaying the last 16 frames in the video. 

That's a duplicate of #1659. We are unlikely to support that any time soon. If you control the creation of the content, please consider repacking without edit lists or ensure that the edit list always starts at a key frame.

**Closed as completed by tonihei** 2018-07-05 09:42 UTC
Labels: duplicate
