### ISSUE TITLE
ExoPlayer with IMA SDK not playing mid-roll ads for Live Channels stream type

### ISSUE THREAD

**Issue by bhaskarraj** [google/ExoPlayer#7322] opened 2020-05-03 15:35 UTC
I am using Exoplayer for streaming Live TV channels and movies. Also, I have integrated IMA SDK which allows playing instream ads and its working perfectly for movies. Pre, Mid and Post-roll Ads are working fine for movies but for Live TV Channel streaming it's only able to load pre-roll ads and mid-roll is not working for this condition. While trying to play mid-roll ads the player freezes.

The reference to my code is the same as this:
[https://qiita.com/mehdi/items/e1de77dbbfd595314c41](url)

I am using the following adTagUrl to test:

[https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=](url)

Also, I am not getting error in logcat

**Comment by andrewlewis** [comment] 2020-05-05 16:16
We don't currently support midrolls in live streams (see #4565). I will mark this as a low-priority enhancement for now, but if you need a fix soon you may want to look into doing server-side ad insertion.

**Comment by andrewlewis** [comment] 2020-05-05 16:17
At the moment, I don't think we have a sensible way to address this issue from #4546: "The ad tags have fixed cue points and it's unclear how to handle the player position when resuming the live stream after playing a midroll."

**Comment by bhaskarraj** [comment] 2020-05-26 05:56
Thank you for the information.

**Comment by andrewlewis** [comment] 2020-05-26 07:14
Reopening to track the enhancement.

**Comment by okycelt** [comment] 2020-06-02 11:52
@andrewlewis, we're also interested in having midrolls in live streams. Actually, Shaka Player already supports this. The way it works is that it resumes the live stream in the same position where it stopped before. So the delay from the live edge is gradually increasing. In our tests, we've used fixed cue points and it wasn't a problem.

If it helps, we could provide a testing live stream together with VMAP URL which you could use for development.

**Comment by andrewlewis** [comment] 2020-06-02 12:17
@okycelt That would be helpful, especially if the stream/ad tag don't expire for a while (I'm not sure when we will get round to doing this). Thanks.

**Comment by okycelt** [comment] 2020-06-02 16:06
@andrewlewis, I've sent you the links via email. The VMAP is generated dynamically. There should be a midroll every 20 seconds or so for the following 5 hours after you request the VMAP. If any of the links expire, just ping us here or via email. We'll provide new links.

Thank you

**Comment by okycelt** [comment] 2020-06-09 15:08
Btw. while in 2.11.4 the player freezes when trying to play a mid-roll on live stream, in 2.11.5 the player crashes with the following exception:
```
E/ImaAdsLoader: Internal error in loadAd
      java.lang.IllegalStateException: Failed to find cue point
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.getAdGroupIndexForAdPod(ImaAdsLoader.java:1457)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.loadAd(ImaAdsLoader.java:845)
        at com.google.ads.interactivemedia.v3.internal.akf.a(IMASDK:23)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:177)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:44)
        at com.google.ads.interactivemedia.v3.internal.ake.b(IMASDK:28)
        at com.google.ads.interactivemedia.v3.internal.akc.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
        at Dx.a(PG:1)
        at ic.a(PG:22)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:152)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx, PID: 3880
    java.lang.NullPointerException: throw with null exception
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.playAd(ImaAdsLoader.java:910)
        at com.google.ads.interactivemedia.v3.internal.akf.a(IMASDK:16)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:177)
        at com.google.ads.interactivemedia.v3.internal.akb.a(IMASDK:44)
        at com.google.ads.interactivemedia.v3.internal.ake.b(IMASDK:28)
        at com.google.ads.interactivemedia.v3.internal.akc.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
        at Dx.a(PG:1)
        at ic.a(PG:22)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:152)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by ojw28** [comment] 2020-06-11 18:56
Is this tracking something different to https://github.com/google/ExoPlayer/issues/6388, and if not can they be duped together?

**Comment by andrewlewis** [comment] 2020-06-11 19:59
Duplicate of #6388

**Closed as completed by andrewlewis** 2020-06-11 19:59 UTC
Labels: duplicate
