### ISSUE TITLE
android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: DRM vendor-defined error: -2990                                                                            

### ISSUE THREAD

**Issue by rranjithk** [google/ExoPlayer#3220] opened 2017-08-30 05:18 UTC
Issue description

This issue happen when we are trying to play widevine Dash:Mp4,H264(WV:Secure HD) format video does not play.
We'd like to know what this error code.

Note: exoplayer demo app(Github)  itself this issue is there

Version of ExoPlayer 
2.0

Device:
 MI 4A

Android Version:
6.0.1

A full bug report captured from the device

```
8449-12848/com.google.android.exoplayer2.demo E/MediaDrm-JNI: Illegal state exception: Failed to get provision request: DRM vendor-defined error: -2990 (-2990)
08-29 18:37:07.251 8449-12848/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                          android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: DRM vendor-defined error: -2990
                                                                                              at android.media.MediaDrm.getProvisionRequestNative(Native Method)
                                                                                              at android.media.MediaDrm.getProvisionRequest(MediaDrm.java:881)
                                                                                              at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getProvisionRequest(FrameworkMediaDrm.java:111)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.postProvisionRequest(DefaultDrmSessionManager.java:451)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:437)
                                                                                              at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:372)
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:792)
                                                                                              at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219)
                                                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)
                                                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
08-29 18:37:07.255 8449-8449/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [1.43]
                                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: DRM vendor-defined error: -2990
                                                                                   at android.media.MediaDrm.getProvisionRequestNative(Native Method)
                                                                                   at android.media.MediaDrm.getProvisionRequest(MediaDrm.java:881)
                                                                                   at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getProvisionRequest(FrameworkMediaDrm.java:111)
                                                                                   at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.postProvisionRequest(DefaultDrmSessionManager.java:451)
                                                                                   at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:437)
                                                                                   at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:372)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:792)
                                                                                   at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219)
                                                                                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)
                                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                   at android.os.Looper.loop(Looper.java:154) 
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by ojw28** [comment] 2017-08-30 13:24
Please try reproducing with a more recent ExoPlayer release (2.5.x). Thanks.

**Comment by ojw28** [comment] 2017-08-30 13:27
I think this was fixed in 2.0.3 (the corresponding entry in the release notes is: "Fixed L3 Widevine provisioning"). I'd strongly advise upgrading to 2.5.x.

**Comment by rranjithk** [comment] 2017-09-07 10:52
I tried with 2.5.x but I am facing the same issue

A full bug report captured from the device:

```
09-07 16:14:38.275 26650-26786/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                           android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: DRM vendor-defined error: -2990
                                                                                               at android.media.MediaDrm.getProvisionRequestNative(Native Method)
                                                                                               at android.media.MediaDrm.getProvisionRequest(MediaDrm.java:881)
                                                                                               at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getProvisionRequest(FrameworkMediaDrm.java:111)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.postProvisionRequest(DefaultDrmSessionManager.java:451)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:437)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:372)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:792)
                                                                                               at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
09-07 16:14:38.279 26650-26650/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [2.36]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: DRM vendor-defined error: -2990
                                                                                     at android.media.MediaDrm.getProvisionRequestNative(Native Method)
                                                                                     at android.media.MediaDrm.getProvisionRequest(MediaDrm.java:881)
                                                                                     at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getProvisionRequest(FrameworkMediaDrm.java:111)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.postProvisionRequest(DefaultDrmSessionManager.java:451)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:437)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:372)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:792)
                                                                                     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 


```

**Comment by ojw28** [comment] 2017-09-07 14:34
In that case this is quite likely (although not definitely) a device specific issue. Marking as such for now. We'll need to find a device to reproduce the issue to know for sure.

**Comment by JacksonFoo** [comment] 2017-09-15 07:15
@ojw28 
I found out Samsung S7 is having this same issues.

Issue description
Facing same error as above mentioned, where this issues is happening in Exo player V1 
"com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902", where I try to switching quality from Auto to lower resolution. Once I hit this error I unable to play any video unless i need switch back to auto bitrate.

Link to test content
none

Version of ExoPlayer being used
r1.5.16

Device(s) and version(s) of Android being used
Samsung Galaxy S7
Android 7.0
Build Number: NRD90M.G930FXXS1DQHV

Mi5
Android 7.0
Build Number: V8.2.2.0.NAAMIEB

Widevine Info Returned by Widevine Server
https://www.dropbox.com/s/giu9rmoswwzeptw/widewine_S7.json?dl=0

A full bug report captured from the device
https://www.dropbox.com/s/kzrctpv7sum1293/samsung_s7.txt?dl=0

Thank you and best regards,

**Comment by wvpaf** [comment] 2018-01-02 23:26
Thank you for the ADB log snippet we can see the -2990 error however having the entire log may be helpful.

**Comment by wvpaf** [comment] 2018-01-16 20:59
@JacksonFoo  any luck with the full log?

**Comment by JacksonFoo** [comment] 2018-02-01 09:39
@wvpaf Sorry for late reply, Unfortunately I unable to get any full log for now as I currently I upgrading from exoplayer 1 to exoplayer 2. I will try again with exoplayer 1 later on to get a full log for you. Thanks

**Comment by wvpaf** [comment] 2018-02-13 22:16
@JacksonFoo any luck?

**Comment by wvpaf** [comment] 2018-02-27 21:47
closing due to inactivity. please open again if able to repro and provide a full adb bugreport.

**Closed as completed by wvpaf** 2018-02-27 21:47 UTC
Labels: need more info, bug: device specific, bug: in platform drm

**Comment by mojzis** [comment] 2018-06-05 16:29
This should actually be fixed in the current build of Xiaomi OS checkout the story how we were trying to figure out what was wrong :)
https://tech.showmax.com/2018/06/making-video-on-demand-work-for-everyone/
