### ISSUE TITLE
Noise when playing FLAC content

### ISSUE THREAD

**Issue by tomislavturcic** [google/ExoPlayer#6601] opened 2019-10-30 14:01 UTC
### Question
Initially this was opened as a bug [here](https://github.com/google/ExoPlayer/issues/6593), but after much further investigation, it appears to be an error on my client or server side. 
Using ConcatenatingMedia and a MediaSources which are a mix of 16bit and 24bit music tracks, static and noise appear when switching from certain 24bit sources to 16bit sources. This happens when switching from 44.1KHz/24bit source to any 16bit source. 
During the static, following error is repeatedly logged:
`AudioTrack: Discontinuity detected [expected 'some value', got 'some other valuej']`

 I've found out that LibflacAudioRenderer returns FORMAT_UNSUPPORTED_TYPE when supportsFormatInternal method is called. That is because format.sampleMimeType is "audio/raw". Therefore FlacDecoder is never created. Any advice?

And for additional info, here's my ExoPlayer construction:
```
SimpleExoPlayer exoPlayer = ExoPlayerFactory.newSimpleInstance(context, 
                createRenderersFactory(context), 
                new DefaultTrackSelector());
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "ExoPlayerTest"));
```
Creating RenderersFactory instance. (I've tried various options here, all lead to same results).
```
private RenderersFactory createRenderersFactory(Context context) {
        DefaultRenderersFactory factory = new DefaultRenderersFactory(context);
        factory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);
        return factory;
}
```
Creating MediaSources for ConcatenatingMediaSource:
```
private MediaSource createMediaSource(PlayerTrack track) {
        return new ProgressiveMediaSource.Factory(dataSourceFactory)
                .setTag(track)
                .createMediaSource(Uri.parse(track.url));
}
```

**EDIT:**
**Playback is normal when I downgrade to 2.9.x ExoPlayer.** So perhaps this really is a bug. Any way to make this work on Exo 2.10.x ?

**EDIT2:**
I am also unable to build FLAC libs on 2.10.6 version. 

### A full bug report captured from the device
[logcat.txt](https://github.com/google/ExoPlayer/files/3789242/logcat.txt)

### Link to test content
Test content sent to dev.exoplayer@gmail.com.

**Comment by herintsoaRazaf** [comment] 2019-10-31 13:56
I'm facing the same issue after an update of Exoplayer to 2.10.5 version.

**Comment by andrewlewis** [comment] 2019-10-31 16:05
> I've found out that LibflacAudioRenderer returns FORMAT_UNSUPPORTED_TYPE when supportsFormatInternal method is called. That is because format.sampleMimeType is "audio/raw". Therefore FlacDecoder is never created. Any advice?

I think this part is working as intended assuming you are playing audio in a .flac container file. `FlacExtractor` outputs PCM because of the way the file is structured. (`LibflacAudioRenderer` is needed for decoding FLAC without using a platform decoder where the audio comes from another container like Matroska.)

> I am also unable to build FLAC libs on 2.10.6 version.

Looks like we need to switch to NDK 20, which also requires using c++_static not gnustl_static. I will make the fix.

> Playback is normal when I downgrade to 2.9.x ExoPlayer. So perhaps this really is a bug. Any way to make this work on Exo 2.10.x ?

Still investigating this.

**Comment by kgrevehagen** [comment] 2019-11-13 10:26
Look at [this comment](https://github.com/google/ExoPlayer/issues/6608#issuecomment-553336828) in #6608 for a potential cause and fix for the one you are still investigating.

**Comment by andrewlewis** [comment] 2019-11-13 12:14
As mentioned in #6608: I think the issue is probably that the audio sink is not reconfigured despite the PCM bit depth changing. When I was fixing this I uncovered another issue with draining audio processors which I'm looking into at the moment (this additional issue prevents this working even with a fix not to keep the codec).

**Comment by ojw28** [comment] 2019-11-27 22:47
This should be fixed in the `dev-v2` and `dev-v2-r2.11.0` branches.

**Closed as completed by ojw28** 2019-11-27 22:47 UTC
Labels: bug
