### ISSUE TITLE
exoplayer throws excepton when i set seekbar outside of buffered part

### ISSUE THREAD

**Issue by roninshahi** [google/ExoPlayer#5761] opened 2019-04-12 09:53 UTC
hi 
I m using exoplayer to play a video from sd card .and there is a problem .it seems that exoplayer is buffering the video from sd card and if I use seek bar to move forward to the not buffered parts, the video stops buffering and throws an exception :

here is my code

```
private PlayerView playerView;
    SimpleExoPlayer player;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        playerView=(PlayerView)findViewById(R.id.ff);

    }
@Override
    protected void onStart() {
        super.onStart();
        player=ExoPlayerFactory.newSimpleInstance(this,new DefaultTrackSelector());
        playerView.setPlayer(player);

        DefaultDataSourceFactory dataSourceFactory=new DefaultDataSourceFactory(this,Util.getUserAgent(this,"exoplayer"));
        ExtractorMediaSource mediaSource=new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(Environment.getExternalStorageDirectory().toString()+"/gh.mp4"));
        player.prepare(mediaSource);
        player.setPlayWhenReady(true);
    }

    @Override
    protected void onStop() {
        super.onStop();
        playerView.setPlayer(null);
        player.release();
        playerView=null;


    }
```

and here is my exceptions

```
E/ExoPlayerImplInternal: Source error.
com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.EOFException
    at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:70)
    at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:784)
 Caused by: java.io.EOFException
    at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:67)
    at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844) 
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
    at java.lang.Thread.run(Thread.java:784)
```

i played a 60 sec video and bcuz it buffered fast there isnt a problem but if i try to play for example 6 min video it happens.

**Comment by ojw28** [comment] 2019-04-12 09:56
This is not something we've seen before, and I'm pretty sure it doesn't happen in the general case. It's most likely an issue specific to the piece of media you're trying to play, probably because it's malformed. Please provide us with a link to some content that reproduces the issue.

**Comment by ojw28** [comment] 2019-05-05 18:20
Closing due to lack of required information (i.e. a link to some content that reproduces the issue). Please respond here if you're able to provide this information, and we'll reopen the issue.

**Closed as completed by ojw28** 2019-05-05 18:20 UTC
Labels: question, need more info
