### ISSUE TITLE
Error after many content seeks

### ISSUE THREAD

**Issue by chladto1** [google/ExoPlayer#10770] opened 2022-11-10 22:08 UTC
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

Pixel 4a running Android 13

### Devices that do not reproduce the issue

Samsung Galaxy S9 running Android 10

### Reproducible in the demo app?

Not tested

### Reproduction steps

- Do 10 - 20 seeks in content
- The error is thrown

The issue was reported by a client, I have no Pixel 4a to test.

### Expected result

The media plays successfully

### Actual result

The error is thrown after many (10 - 20) seeks.

### Media

Looks like it not depends on played content.
[error.txt](https://github.com/google/ExoPlayer/files/9984864/error.txt)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by 247az** [comment] 2022-11-11 00:15
I have the same issue.
https://github.com/google/ExoPlayer/issues/10661
And you should update your OS 13 version to QPR1 Beta 2 or Beta 3 to resolve the issue.

**Comment by tonihei** [comment] 2022-11-11 09:30
Yes, that's a duplicate of #10661 and should be fixed once devices update to QPR1

**Closed as completed by tonihei** 2022-11-11 09:30 UTC
Labels: duplicate
