### ISSUE TITLE
 [New Feature]:Change the video volume when playing the video by adjusting the sound amplitude

### ISSUE THREAD

**Issue by JeffMony** [google/ExoPlayer#7868] opened 2020-09-08 14:24 UTC
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Use case description
The Users don't want to adjust the phone's volume, But every video has the different volume.
If exoplayer support the feature about adjusting the sound volume when playing the video

### Proposed solution
https://github.com/JeffMony/PlayerSDK/commit/0d8b6ee34233ef050c608647d11bdbbb64c46c3f

**Comment by JeffMony** [comment] 2020-09-08 14:24
Sonic can change the sound amplitude

**Comment by JeffMony** [comment] 2020-09-08 14:25
@ojw28 
Could you check it?

**Comment by kim-vde** [comment] 2020-09-09 17:30
I think this is a duplicate of #3349. Can you confirm @JeffMony ?

#7476 could also be of interest for you.

**Closed as completed** 2020-09-11 16:55 UTC
Labels: duplicate
