### ISSUE TITLE
How to change MediaItem.ClippingConfiguration

### ISSUE THREAD

**Issue by GreenVegetables** [google/ExoPlayer#11185] opened 2023-05-27 02:52 UTC
Hi, I have met some problems and do not know how to do it, please help me.

exoplayer version is 2.18.7

By calling the ```addMediaItem``` method, I add a ```mediaitem```. how to dynamically change has been added ```mediaitem``` ```MediaItem.ClippingConfiguration``` attribute, I want to modify the startPositionMs and endPositionMs properties of the ```mediaitem``` in the playlist.I can't find a way to modify it in the documentation.What should I do？

**Comment by icbaker** [comment] 2023-05-30 16:45
Changing the clipping configuration during playback is not supported, it is tracked by https://github.com/google/ExoPlayer/issues/3163.

Closing this as a duplicate of that.

**Closed as completed by icbaker** 2023-05-30 16:45 UTC
Labels: duplicate
