### ISSUE TITLE
Error while implement RTMP

### ISSUE THREAD

**Issue by patelakshay13890** [google/ExoPlayer#9316] opened 2021-08-19 12:45 UTC
I have to used both lib as below but I am getting error as shown in image...
  implementation 'com.google.android.exoplayer:exoplayer:2.15.0'
    implementation 'com.google.android.exoplayer:extension-rtmp:2.15.0'
Please Help me out with sample example for latest Exo RTMP lib ??

![image](https://user-images.githubusercontent.com/6092323/130070238-c048bb74-3833-4c97-b108-1189f94124e0.png)

**Comment by icbaker** [comment] 2021-08-23 16:06
Duplicate of https://github.com/google/ExoPlayer/issues/9322

**Closed as completed by icbaker** 2021-08-23 16:06 UTC
Labels: duplicate
