### ISSUE TITLE
Support EMSG events during DASH playbacks

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2176] opened 2016-12-10 02:11 UTC
Hi,
In one of the closed issue (https://github.com/google/ExoPlayer/issues/1414) you mentioned that:
```
For DASH and SmoothStreaming custom data can be embedded directly into the media in 
EMSG boxes, which we'll be adding support for in 2.x.
```
Is there any updates on this case so far for the version 2.0.4?

**Comment by ojw28** [comment] 2016-12-11 20:40
This is not supported yet. Let's use this issue to track the enhancement.

**Comment by ChernyshovYuriy** [comment] 2016-12-11 23:36
Thanks for feedback!
Can you spot a class to start investigate from?
Perhaps, if you have not enough resources for this issue, I can start to implement and submit pull request later?

**Comment by Rohit-Varma1** [comment] 2017-02-01 22:31
Doesn't seem to work. Tested with 2 DASH streams using the DEMO app provided.  Doesn't prints out the EMSG in the EventLogger. The same streams work in SHAKA player when tested on web.

**Comment by ojw28** [comment] 2017-02-02 00:32
The work is not finished (which is why the issue hasn't been closed). It's not expected to work at this point.

**Comment by ChernyshovYuriy** [comment] 2017-02-02 00:41
@rohitvarma1986 , there is dedicated branch that works fine:
https://github.com/google/ExoPlayer/tree/dev-v2-emsg-experimental

**Comment by Rohit-Varma1** [comment] 2017-02-02 17:02
@ojw28 : Thank you for the prompt reply. Is there any estimate at this point , regarding when it would be done ?

**Comment by jlacivita** [comment] 2017-02-07 22:35
Hi @ojw28. For context, this feature is very important for ExoPlayer/DASH adoption in North America, particularly for OTT apps streaming content originally aired on TV. Nielsen provides a critical viewership measurement SDK that requires access to eMSG data during playback. Any OTT app considers Nielsen integration to be a requirement at some point, and they're all waiting for this.

Until we have eMSG data, north american OTT apps are forced to stick with HLS, which means they can't use DRM on Android.

**Comment by ojw28** [comment] 2017-02-12 10:34
Note from ref'd issue: An additional test stream is available at http://se-mashup.fokus.fraunhofer.de:8080/dash/assets/adinsertion-samples/events/inband/dash.mpd

**Comment by ojw28** [comment] 2017-03-12 13:57
This functionality should be working now in `dev-v2`. Please give it a try.

There's still one technical issue where events might go missing when seeking short distances and/or toggling the event tracks on and off, so the issue is kept open to track fixing that. It's unlikely to be much of an issue in practice, however.

**Comment by ojw28** [comment] 2017-03-16 16:41
Marking as fixed. We'll track the remaining minor issue separately.

**Closed as completed by ojw28** 2017-03-16 16:41 UTC
Labels: enhancement
