### ISSUE TITLE
Setting HTTP Headers to MediaItem

### ISSUE THREAD

**Issue by xeinebiu** [google/ExoPlayer#10607] opened 2022-09-11 12:27 UTC
## Use Case

While migrating from `MediaSource` to `MediaItem`, I cannot find a way how to inject HTTP Headers for individual `MediaItem`.

````kotlin
            MediaItem
                .Builder()
                .setUri(stream.uri)
                .setTag(media)
                .setHeaders(....) // <-- no such method
                .build()
````

Is there any way to use `MediaItem` with individual `HTTP Headers` ?

**Comment by icbaker** [comment] 2022-09-12 06:31
Duplicate of https://github.com/google/ExoPlayer/issues/6166

**Closed as completed by icbaker** 2022-09-12 06:31 UTC
Labels: duplicate
