### ISSUE TITLE
AVI FORMATS ARE NOT PLAYING 

### ISSUE THREAD

**Issue by Usman-Click** [google/ExoPlayer#10360] opened 2022-06-20 13:14 UTC
HI,
When i play a video (AVI format) exoplayer says cannot play this video 

What am I missing ?

**Comment by icbaker** [comment] 2022-06-20 14:00
Duplicate of https://github.com/google/ExoPlayer/issues/2092.

Initial AVI support is available on the `dev-v2` branch, which you can access by depending on ExoPlayer locally: https://github.com/google/ExoPlayer#locally

It will also be included in 2.19.0.

**Closed as completed by icbaker** 2022-06-20 14:00 UTC
Labels: duplicate

**Comment by Usman-Click** [comment] 2022-06-20 14:23
Really appreciate
Thanks 😊

**Comment by Usman-Click** [comment] 2022-06-20 14:29
> Duplicate of https://github.com/google/ExoPlayer/issues/2092.
> 
> Initial AVI support is available on the `dev-v2` branch, which you can access by depending on ExoPlayer locally: https://github.com/google/ExoPlayer#locally
> 
> It will also be included in 2.19.0.

When will you release 2.19.0.

**Comment by Usman-Click** [comment] 2022-07-22 16:51
> > Duplicate of #2092.
> > Initial AVI support is available on the `dev-v2` branch, which you can access by depending on ExoPlayer locally: https://github.com/google/ExoPlayer#locally
> > It will also be included in 2.19.0.
> 
> When will you release 2.19.0.

HI,

As you said in the above comment that I should depend on the exoplayer-dev-2 branch locally for AVI formats to be supported, well I depend on the exoplayer-dev-2 branch locally but the AVI formats are still not playing,

what am i missing ?

is there anything else that I will have to do ?

thanks.
