### ISSUE TITLE
Notification forward Backward button not visible in Android 13

### ISSUE THREAD

**Issue by YogeshSinghPathania** [google/ExoPlayer#10952] opened 2023-01-30 18:26 UTC
### ExoPlayer Version

2.16.0

### Devices that reproduce the issue

Android 13

### Devices that do not reproduce the issue

Android 12

### Reproducible in the demo app?

Yes

### Reproduction steps

Play any song and than check the notification

### Expected result

Forward and Backward button have to be shown. 

### Actual result

Notification buttons shows similar like other version. I already use UAMP demo. where i enable these property but its not working. 
 notificationManager.setUseRewindAction(true)
        notificationManager.setUseFastForwardAction(true)

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by YogeshSinghPathania** [comment] 2023-01-30 18:53
Hi @marcbaechinger if you know anything how to resolve this please guide me its been 3 days i was working on this issue.

**Comment by marcbaechinger** [comment] 2023-01-30 18:54
Since Android 13 and with an app that targets SDK 33 and higher, the mini player (media notification) is not based on the notification but on the media session (see [announcement](https://developer.android.com/about/versions/13/behavior-changes-13#playback-controls)). 

Given your information I'd say this is not a bug in the library but an enhancement required in that app the screenshot is from. It needs a proper state of the media session playback state as described in the resource linked above.  Given the missing forward button-problem that you are describing, it seems to me that the media session doesn't properly [declare the queue ](https://developer.android.com/reference/android/support/v4/media/session/MediaSessionCompat#setQueue(java.util.List%3Candroid.support.v4.media.session.MediaSessionCompat.QueueItem%3E)) and/or the [current active queue item ID](https://developer.android.com/reference/android/support/v4/media/session/PlaybackStateCompat.Builder#setActiveQueueItemId(long)) or the [playback state actions](https://developer.android.com/reference/android/support/v4/media/session/PlaybackStateCompat.Builder#setActions(long)) are misconfigured. 

One way to do this is using an `MediaSessionConnector` together with the `PlayerNotificationManager`. A more future proof way is the Media3 [session module of the `androidx.media` ](https://developer.android.com/guide/topics/media/media3) project.

I'm closing this issue. Please re-open if you think something needs to be added.

**Closed as completed by marcbaechinger** 2023-01-30 18:54 UTC
Labels: question

**Comment by YogeshSinghPathania** [comment] 2023-01-30 19:02
I also add the addAction in function 
   protected open fun actions(mediaSession: MediaSessionCompat): List<NotificationCompat.Action> = listOfNotNull(
        actionPrevious(mediaSession), actionRewind(mediaSession), actionPlay(mediaSession), actionPause(mediaSession),
        actionFastForward(mediaSession), actionNext(mediaSession)
    )


        actions(mediaSession).forEach {
            addAction(it)
        }
