### ISSUE TITLE
HLS plays first 20 seconds and throw Unrecognized media format 

### ISSUE THREAD

**Issue by fabiel-leon** [google/ExoPlayer#9596] opened 2021-10-23 15:15 UTC
using hls the media gets played for the first 20 seconds and  then throws  a Unrecognized media format 

https://s3.temazo.f-l.cyou/temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m3u8

using any online hls player works fine 
https://hls-js.netlify.app/demo/?src=%20https%3A%2F%2Fs3.temazo.f-l.cyou%2Ftemazo%2Fcms%2FDia_De_Pago_Ovi_DUKI_128_611277a45d.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==

---------------------
i am using react-native-video this is the error i receive 

{
    "errorException": "com.google.android.exoplayer2.ExoPlaybackException: java.io.EOFException",
    "errorString": "Unrecognized media format"
}

adb bugreport
```
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal: Source error
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:   java.io.EOFException
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:292)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:74)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:336)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:310)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:376)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:343)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:314)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-23 10:55:05.712 10193 26991 27415 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:764)
10-23 10:55:05.713  1041   599   928 E AudioFlinger: open /proc/26991/cmdline error
10-23 10:55:05.713  1041   599   928 I AudioFlinger: setAppName(), name=[], active=[0]
10-23 10:55:05.713  1041   546   974 V EffectMiSound: MiSound_command() start, cmdCode=23
10-23 10:55:05.713  1041   546   974 V EffectMiSound: MiSound_Command EFFECT_CMD_SET_APP_NAME: stream=3, name=-
10-23 10:55:05.752 10193 26991 26991 E ExoPlayer Exception: com.google.android.exoplayer2.ExoPlaybackException: java.io.EOFException
10-23 10:55:05.755 10193 26991 26991 D ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
10-23 10:55:05.810  1041   599   599 W AudioOut_1D: type=1400 audit(0.0:14638): avc: denied { write } for name="logd" dev="tmpfs" ino=16776 scontext=u:r:audioserver:s0 tcontext=u:object_r:logd_socket:s0 tclass=sock_file permissive=0
10-23 10:55:05.819  1000 24602 24624 I PowerCheckerService: uid:10193change to inactive
10-23 10:55:05.819  1000 24602 24620 I AppActiveChecker: uid:10193change to inactive
```

```
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:45 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m3u8 HTTP/2.0" 200 1862 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:45 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 764 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:45 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 41449 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:46 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 40956 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:46 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 4 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:48 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 4 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:50 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 4 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:53 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 4 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:57 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 4 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:55:02 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 4 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
```
- ExoPlayer version number 2.11.4
- Android 9
- Android device REDMI 8A

conversion command 

```
ffmpeg -i "$fullname" -f hls -vn -map_metadata -1 -c:a libfdk_aac -profile:a aac_he_v2 -b:a 32k -hls_time 10 -hls_playlist_type vod -hls_segment_type fmp4 -hls_flags single_file "$filename".m3u8
```
---------------------------------------------------------------

PD: If i play the m3u8' refered audio file it gets played fine 
https://s3.temazo.f-l.cyou/temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s

**Comment by ojw28** [comment] 2021-10-26 19:23
I tried to play https://s3.temazo.f-l.cyou/temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m3u8 in the ExoPlayer demo app, with both the latest release 2.15.1, and also with 2.11.4. In both cases playback was fine or me. I don't know where the HTTP request logging that you've posted is coming from, but things go wrong on this line:
```
s3.temazo.f-l.cyou 152.206.235.232 - - [23/Oct/2021:10:54:46 -0400] "GET /temazo/cms/Dia_De_Pago_Ovi_DUKI_128_611277a45d.m4s HTTP/2.0" 206 4 "-" "ReactNativeVideo/1.7.0 (Linux;Android 9) ExoPlayerLib/2.11.4" "-"
```
Based on previous lines, the `4` is either the number of bytes requested, or the number of bytes transferred, or both. In either case it's wrong because it should be `40921`.

Please could you also try and reproduce with the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html)? If you can't reproduce there then I think it's more likely to be something weird in `ReactNativeVideo`, or some bad caching either client side (by `ReactNativeVideo`, presumably) of server side.

**Closed as completed** 2021-11-24 02:04 UTC
Labels: question, closed-by-bot
