### ISSUE TITLE
can we control playback speed in ExoPlayer nw

### ISSUE THREAD

**Issue by nzala** [google/ExoPlayer#2310] opened 2017-01-10 12:38 UTC
can we control playback speed in ExoPlayer nw

**Comment by ojw28** [comment] 2017-01-10 12:41
Please don't spam the issue tracker. This is a duplicate of #26.

**Closed as completed by ojw28** 2017-01-10 12:41 UTC
Labels: duplicate

**Comment by nzala** [comment] 2017-01-10 13:07
but i can find playback speed

**Comment by PaulWoitaschek** [comment] 2017-01-10 21:00
Sorry for the repeated request but it would be really helpful if you could update the referenced ticket with the updated schedule. @ojw28

**Comment by mseroczynski** [comment] 2017-01-11 10:46
Maybe controlling playback speed of audio should be another issue (I think most of issuers just need to control audio playback speed yet still issues get referenced to "Change playback rate of video track" which - for me - is not very intuitive). And.. it's starting to be a bit awkward for me but kindly please update schedule for audio speed.
