### ISSUE TITLE
Video stuttering after 15 minutes of playback

### ISSUE THREAD

**Issue by alexeyr15** [google/ExoPlayer#6343] opened 2019-08-26 18:47 UTC
### [REQUIRED] Issue description
Video is getting worse (not smooth) after about 15 minutes of playback on Nvidia Shield.

### [REQUIRED] Reproduction steps
1. Open the provided stream in the demo app on Nvidia Shield
2. Wait about 15 minutes
3. Video becomes not smooth, with dropped frames

### [REQUIRED] Link to test content
Provided by email

### [REQUIRED] A full bug report captured from the device
-

### [REQUIRED] Version of ExoPlayer being used
2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
Nvidia Shield, Android 9

**Comment by alexeyr15** [comment] 2019-09-05 08:24
Hi. Did you have the chance to look into this issue?

**Comment by kaazvaag** [comment] 2019-09-25 13:42
I have the same issue. This is very annoying when watching football matches. Please fix this bug!

**Comment by marcbaechinger** [comment] 2019-09-25 13:54
I tested this out with two different nvidia boxes. The movie run through two hours.

@alexey-rabets I know it's a while. Your stream your sent gives me a 404 probably because it's expired.

@kaazvaag What app are you referring to re: football matches? Is this an app I can install and test with?

**Comment by kaazvaag** [comment] 2019-09-25 14:19
@marcbaechinger I use an IPTV app called Tivimate that uses exoplayer2 (you can install the app from the play store on the ShieldTV). 
The weird thing is that the streams are good for about the first 15 minutes. After 15 minutes there are framedrops (stutter). Many other ShieldTV owners have the same issue with different iptv apps using exoplayer. The issue occurs with interlaced streams (1080i). (For now a workaround has been created by the app developer which is a codec reset after 13 minutes (which freezes the picture for a second)).
But a real fix in exoplayer or the ShieldTV hardware codecs would be a much better solution

If you need more information please let me know.

**Comment by kaazvaag** [comment] 2019-10-07 13:58
After some research I discovered that this issue has been on the ShieldTV in combination with exoplayer since a few YEARS. 
https://forums.plex.tv/t/live-tv-starts-to-skip-or-drop-frames-after-10-or-so-minutes-on-shield-tv/195165
@marcbaechinger Is it possibe to fix this issue?

**Comment by ojw28** [comment] 2019-10-07 14:16
@sureshcnvidia @IanDBird - I don't suppose either of you have insight into this issue, do you?

**Comment by marcbaechinger** [comment] 2020-01-07 22:29
Closing due to inactivity. Please re-open if required.

**Comment by kentherzz** [comment] 2020-01-08 02:16
This is for sure not fixed. Please reopen!
I have the same issue on NVIDIA SHIELD 2019, so it is not a hardware issue. Reported to NVIDIA and they are looking into it as well. I can see from the logs that Shield use ExoPlayerLib/2.10.7

**Comment by kentherzz** [comment] 2020-01-08 02:18
@marcbaechinger , can you please reopen this?

**Comment by Ninjouz** [comment] 2020-01-09 06:46
Not fixed @marcbaechinger , bug only on interlaced stream IIRC.

**Comment by kentherzz** [comment] 2020-01-10 00:11
For me it seems like it only happens with 1080i and not 720i... Only affects Full HD...
Really strange bug!

**Comment by kentherzz** [comment] 2020-01-31 09:13
@marcbaechinger , dont you understand that this is not fixed? Why dont you reopen it?

**Comment by kehongnvidia** [comment] 2020-02-03 19:30
@alexey-rabets can you share your problematic video clip?

**Comment by alexeyr15** [comment] 2020-02-04 03:46
The link to the live video stream sent by email with the subject "Issue #6343" is still available. You can use it to reproduce the issue.

**Comment by marcbaechinger** [comment] 2020-02-04 11:24
When I try that url it gives me a 301 (moved permanently) with a redirect to an url with an ip address and a hash which then gives me a 404.

**Comment by alexeyr15** [comment] 2020-02-04 11:29
I have shared the interlaced video sample of 30 minutes duration to reproduce the issue:
https://yadi.sk/d/itbdzxNqcpJFAw

**Comment by alexeyr15** [comment] 2020-02-05 17:45
@kehongnvidia It seems, enabling "Optimize video playback for timestamp drift" option in Developer options fixes this issue. Maybe, is it worth to enable it by default in the next firmware update?

**Comment by ojw28** [comment] 2020-02-05 20:03
Reassigning to @kehongnvidia since this sounds like a device specific issue with Nvidia Shield.

**Comment by kentherzz** [comment] 2020-02-06 21:41
> @kehongnvidia It seems, enabling "Optimize video playback for timestamp drift" option in Developer options fixes this issue. Maybe, is it worth to enable it by default in the next firmware update?

This option does not exist on Nvidia Shield 2019 Tube Version. Only on the Pro version?
What does it do exactly?

**Comment by kehongnvidia** [comment] 2020-02-06 21:44
@kentherzz the option is available with 2019 Tube version as well.  Enable developer option and it's under "Media".  

BTW we were able to reproduce the issue and is under debugging right now.

**Comment by kentherzz** [comment] 2020-02-06 21:46
@kehongnvidia has this option always been there? I had the Tube version for 2 weeks ago and it was not there. The 2019 Pro version has it and this is the device I have now. The issue happens on both version of 2019 Shield. Will try to toggle this option, can Nvidia confirm that it helps on the problem?

**Comment by kehongnvidia** [comment] 2020-02-06 21:50
based on comment from alexey above, it fixed the issue.  We have not tried with the option enabled though.  I'll update once we have root caused the issue.   This issue is observed on both old (2015/2017) and new (2019) shield TVs.

**Comment by kentherzz** [comment] 2020-02-06 21:54
@kehongnvidia all right, thanks Nvidia! I was seriously just about to return the Shield and go for Apple TV. Will do some tests myself:-) I have a ticket on this 200104-000793. It was set to the dev team but I have not heard anything for weeks.

**Comment by kehongnvidia** [comment] 2020-02-11 07:28
We've been able to reproduce and root cause this to an overflow which mixes up time calculation and causes the stutters. We've come up with a fix and tested the fix. The fix will be included in upcoming releases of both 2015/2017 and 2019 SHIELDs.

**Comment by ojw28** [comment] 2020-02-11 09:59
Thanks! Closing this, since it's not an ExoPlayer issue.

**Closed as completed by ojw28** 2020-02-11 09:59 UTC
Labels: bug: device specific

**Comment by Ninjouz** [comment] 2020-02-12 17:56
@kehongnvidia where are you releasing this ?

**Comment by kehongnvidia** [comment] 2020-02-12 18:02
@Ninjouz  soon.  We do not have ETA yet.  

For 2015/2017 Shield TV, you need to sign up hotfix release

https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/340245/20152017-shield-experience-upgrade-802-hotfix-imag/

Please sign up here if you'd like to get the HotFix images for 8.0.2+:
https://docs.google.com/forms/d/e/1FAIpQLSca8NzAjFyhT00HvUH7KN2Ae2zbTnNqqNVLb0qqBdaXa7uUBw/viewform?usp=pp_url&entry.1352533101=DONTDELETE-

For 2019 Shield TV,  it will be part of next update.
