### ISSUE TITLE
App crash due to 'too many files open' error when using multiple ExoPlayer instances

### ISSUE THREAD

**Issue by dnutcracker** [google/ExoPlayer#936] opened 2015-11-08 08:38 UTC
Relevant error log:
 A/art: art/runtime/indirect_reference_table.cc:76] Check failed: table_mem_map_.get() != nullptr ashmem_create_region failed for 'indirect ref table': Too many open files
E/Parcel: dup failed in Parcel::read, fd 1 of 2
                                                     dup(1009) = -1 [errno: 24 (Too many open files)]
                                                     fcntl(1009, F_GETFD) = 1 [errno: 24 (Too many open files)]
                                                     flat 0xb3731870 type 1936206469

In our app we're opening and closing many ExoPlayers(1.5.2) very quickly for playing local mp4 files.
For every given moment a maximum of 9 instances are playing but they can be quickly scrolled off-screen and new ones come in.

I have 2 questions here:
1. I've seen that FileDataSource uses RandomAccessFile for reading the mp4 files and seems that the datasource.close() is invoked on every seek - why is that? wouldn't be more efficient to just skip ahead in the file? (and save the release and re-creation of the RandomAccessFile)
2.Seems like some instances of the ExoPlayerImplInternal handler thread are not released as expected and are holding references to expensive resources(FileDataSource is one of them) - this may be the reason one the files are not being released. I've attached a screenshot from the MemoryAnalyzer tool -

![screen shot 2015-11-08 at 10 31 50](https://cloud.githubusercontent.com/assets/6896501/11019516/6cf3c6f8-8604-11e5-88ff-c17f9a30155b.png)

Thanks.

**Comment by ojw28** [comment] 2015-11-08 21:00
1. It's not possible to completely optimize every possible way of loading data whilst still retaining a clear design for how `DataSource`s work. In practice I suspect the difference in performance between what happens and what you suggest should happen is pretty negligible.
1. The existence of objects in MAT only tells you that they haven't been garbage collected yet. A `FileDataSource` is not in any way expensive, unless it's actually in the open state. So it could just be that the garbage collector hasn't run recently.

Are you certain that your application is correctly calling `release()` on ExoPlayer instances when they're no longer required? If you think ExoPlayerImplInternal:Handler instances really aren't able to be garbage collected, then I think you're either not doing this, or your app is holding references to `ExoPlayer` instances that you no longer need. You should look at the "paths to GC roots" in MAT to determine why each instance is not able to be garbage collected. See [here](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.mat.ui.help%2Fgettingstarted%2Fbasictutorial.html) for some details.



2.Seems like some instances of the ExoPlayerImplInternal handler thread are not released as expected and are holding references to expensive resources(FileDataSource is one of them) - this may be the reason one the files are not being released. I've attached a screenshot from the MemoryAnalyzer tool -

**Comment by ojw28** [comment] 2015-11-08 21:02
Note - This is more likely to be a bug in application code than in ExoPlayer, at this point in the investigation.

**Comment by dnutcracker** [comment] 2015-11-09 09:15
1.My only concern regarding the FileDataSource is that opening and closing RandomAccessFile many times very quickly might create a queue of requests to close the file by the underlying platform creating edge cases where too many files are open (even for a short time) resulting in a crash - that's only a guess of course but in general I guess we both agree that reusing the file access instead of quick open/close operation is less prone to problems. (I might write a dedicated test that opens and closes RandomAccessFile quickly and check if I encounter the same crash)

2.My application calls release() in every opportunity it has to release the ExoPlayer as soon as possible. I've verified that using Android Device Monitor and MAT.

Regarding holding references to ExoPlayer instances I no longer need - you can clearly see here that there are 0 ExoPlayer instances while there are 23 instances of ExoPlayerImpl* 
![screen shot 2015-11-09 at 11 06 51](https://cloud.githubusercontent.com/assets/6896501/11029840/6557079c-86d2-11e5-92da-fa467e1d3b00.png)
All references to ExoPlayerImpl are made by the ExoPlayerImplInternal:Handler threads even through all ExoPlayers have been released()!
![screen shot 2015-11-09 at 11 11 13](https://cloud.githubusercontent.com/assets/6896501/11029875/ae2fb46e-86d2-11e5-8931-3e2716761106.png)

Another interesting fact - I've revised the code to try and reuse the ExoPlayer instances as much as possible and instead of releasing it and creating a new one - I'm now using its stop() method and just preparing it again with new renderers - this has yielded better results! - the crash still happens, but from my latest experiments it happens more rarely.
So, could it be that invoking ExoPlayer release() multiple times quickly might not release all related threads/resources as expected? from my peek at the code it seems like there isn't any problem - but the results here may suggest otherwise.
I'm also aware that this use-case of multiple ExoPlayers that are released and allocated very quickly is not so common, so this problem might not have been visible.

**Comment by ojw28** [comment] 2015-11-09 09:52
1.I don't agree. Closing and re-opening should be fine, and there's no actual evidence to suggest otherwise.
1. Doesn't that path-to-roots indicate that there's still a message in the `ExoPlayerImpl.eventHandler` message queue? You'll need to find out what that message is, and why it isn't being handled. Are you creating your ExoPlayer's on a thread other than the application's main thread, by any chance?

**Comment by dnutcracker** [comment] 2015-11-09 10:56
I'm creating all ExoPlayer instances on the main application thread.
Also I suspect there is relation between this issue and issue #937 since the error message here and there always come together.

**Comment by ojw28** [comment] 2015-11-09 11:04
Possibly, but the specific issue preventing the objects from being GC'd is the pending message that appears to be in the message queue. So you should find out what that is, how it gets there, and why it isn't being processed.

**Comment by dnutcracker** [comment] 2015-11-09 11:36
Ok - I'll investigate it some more. Do you have any suggestion as to how to
query the message queue in this scenario?

**Comment by ojw28** [comment] 2015-11-09 11:42
It should be possible using a debugger and/or printing log statements.

**Comment by smw1218** [comment] 2015-11-30 03:13
Hi, we're having the same issue on 1.5.1 and 1.5.2 (but not 1.5.0).  We think we have it isolated to a single commit: https://github.com/google/ExoPlayer/commit/bcb9f8282df7b05a66329e5115511c67f1651d2d.  The cause isn't obvious looking at the commit.  Maybe making the frameReleaseTimeHelper on by default causes issues.  We have a similar design as @dnutcracker; multiple ExoPlayers reading local files.  We were passing null for this parameter before it was internalized.  
We also have confirmed leaking file descriptors for a minimal test case using lsof on a rooted device.  For us the issue is also mitigated on Marshmallow.

**Comment by ojw28** [comment] 2015-11-30 05:18
- Can you provide the output from `lsof -p <pid>`, where <pid> is the process id of your app when it's reproducing the issue? That should shed some light on exactly what the open file descriptors are.
- Do you also see multiple instances of ExoPlayerImpl being leaked via ExoPlayerImplInternal:Handler, as @dnutcracker was seeing? If so, can you try and find out exactly what's causing this.

**Comment by smw1218** [comment] 2015-11-30 18:50
I forgot to mention, we reproduced this using the ExoPlayer Demo application.  We ran the dizzy demo multiple times and observed that the FD counts increased each time.  I have this dump from when we originally found the issue:

[lsof_after_dizzy_runs.txt](https://github.com/google/ExoPlayer/files/47649/lsof_after_dizzy_runs.txt)

It's only a few descriptors each run for dizzy, but our real app is creating ExoPlayers much more frequently than the demo.
We have already reverted back to 1.5.0 for our main app so I'm not sure how much more effort we can put in to debugging this.  I just happened to run across this bug and hoped I could add a little info that might help.

**Comment by ojw28** [comment] 2015-12-16 14:27
Most likely a dupe of #1066, which gives reproduction steps.

**Closed by ojw28** 2015-12-16 14:27 UTC
Labels: need more info

**Comment by dnutcracker** [comment] 2015-12-16 18:55
I hope this will indeed solve the problem, though it was also observed on Android M where the Choreographer bug said to be fixed...
Eventually I managed to workaround the problem by using my own pool of ExoPlayer instances and reusing them all over the app.(instead of using release() and new)

**Comment by ojw28** [comment] 2015-12-16 19:05
Was it (observed on M)? The post 5 above this one suggests the issue doesn't reproduce on M. The 4th post of #1066 corrects the top of that issue also (i.e. it wasn't observed on M).

**Comment by dnutcracker** [comment] 2015-12-16 21:34
As far as I remember it was.
But I'll try verify that again and post the results.
