### ISSUE TITLE
FLV - Playback fails if SCRIPTDATA segment has invalid name type

### ISSUE THREAD

**Issue by yanshanshu** [google/ExoPlayer#7675] opened 2020-07-27 01:38 UTC
播放一个没有没有音频输出的视频流，报com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.ParserException 异常

**Comment by ojw28** [comment] 2020-07-27 09:51
ExoPlayer supports video streams that do not also contain audio, so this should work fine. For us to help, you'll need to provide us with a piece of sample media that reproduces the problem.

**Comment by yanshanshu** [comment] 2020-07-27 10:10
http://221.226.74.203:9111/live?port=1554&app=liveonly&stream=5 这是测试的流媒体。
view我用的TextureView。下面文件是具体代码
[PlayerActivity.txt](https://github.com/google/ExoPlayer/files/4981363/PlayerActivity.txt)

**Comment by ojw28** [comment] 2020-07-27 10:54
It looks like the media contains an invalid `SCRIPTDATA` segment, which violates the FLV specification.

We can make ExoPlayer ignore the segment rather than fail playback in this case, however please note that the media is malformed, and that's the root cause of this issue.

**Comment by yanshanshu** [comment] 2020-07-28 01:14
请问怎么设置ExoPlayer ignore the segment继续播放？我需要帮助

**Comment by ojw28** [comment] 2020-07-28 08:59
The media should play successfully when using the `dev-v2` branch, as of the change above. This change will be included in the 2.12 release.

**Closed as completed by ojw28** 2020-07-28 08:59 UTC
Labels: bug, bad media
