### ISSUE TITLE
What causes the MediaCodec$CodecException?

### ISSUE THREAD

**Issue by TaruiTakashi** [google/ExoPlayer#8176] opened 2020-11-06 10:54 UTC
Searched documentation and issues

・ExoPlayer Javadoc.
・ExoPlayer Issues

Question

When playing a dash video, MediaCodec $ CodecException occurs and playback fails.
The license has been successfully issued.
What is the cause of the `MediaCodec$CodecException:Error 0xffffffe0`?

The device that occurs is the Pixel 5 on Android 11 and not all devices.

Error log

```
ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CodecException: Error 0xffffffe0
ExoPlayerImplInternal: 	at m.c.b.b.z.a(BaseRenderer.java:14)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:48)
ExoPlayerImplInternal: 	at m.c.b.b.j0.b(ExoPlayerImplInternal.java:161)
ExoPlayerImplInternal: 	at m.c.b.b.j0.handleMessage(ExoPlayerImplInternal.java:24)
ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:223)
ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:67)
ExoPlayerImplInternal: Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0
ExoPlayerImplInternal: 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
ExoPlayerImplInternal: 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2821)
ExoPlayerImplInternal: 	at m.c.b.b.o1.r.a(SynchronousMediaCodecAdapter.java:6)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.q(MediaCodecRenderer.java:81)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:37)
```

Version of ExoPlayer being used: 2.12.1

### A full bug report captured from the device
sorry.
This error is caused by a user who is using the app we are releasing, so we cannot get the bug report.
If I need a bug report, I ask the user to submit a bug report.
Please let us know if you need a bug report.
Ask the user to submit a bug report.

**Comment by lcf87** [comment] 2020-11-06 17:26
There can be a bunch of reasons, but we would need a bug report to help! Could you provide us a bug report?

**Comment by TaruiTakashi** [comment] 2020-11-11 02:23
@lcf87 
I have sent the bugreport to dev.exoplayer@gmail.com.
Please check it out.

**Comment by TaruiTakashi** [comment] 2020-12-14 11:50
@lcf87 
How has the progress been since then?

**Comment by bhumeshvr7github** [comment] 2021-07-07 12:40
i am also facing this issue on  device Pixel 3 with version 11
how to fix it.
Error- MediaCodec$CodecException:Error 0xffffffe0

**Comment by saravanans-github** [comment] 2021-12-10 06:33
We are also facing the same issue on OPPO phone using `ExoPlayerLib/2.12.0`. 

FULL adb log of the crash here -  [oppo-crash.log](https://github.com/google/ExoPlayer/files/7690490/oppo-crash.log)

from our debugging we think -
1. from the log it seems the crash was in the `WVCdm` process.
2. the same stream works on other Android devices
3. removing the audio streams i.e video only STILL crashes
 
@lcf87 we can try to share a sample URL that crashes the OPPO device if that'll help you reproduce.

**Comment by icbaker** [comment] 2021-12-10 10:46
@TaruiTakashi the bug report provided over email does not contain `CodecException` anywhere in its logcat output. I also don't see any references to ExoPlayer, not even the line that's logged every time a player is instantiated: 
https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L172-L180

Please reproduce the problem immediately before taking the bug report. It will be particularly helpful if you can reproduce using [our demo app](https://exoplayer.dev/demo-application.html) as it includes extra logging that can help to diagnose problems.

@saravanans-github please file a new issue. Many MediaCodec errors have very similar stack traces but completely different root causes, so it's going to be clearer if we investigate your issue separately from this one.

**Closed as completed** 2022-01-10 02:04 UTC
Labels: question, closed-by-bot
