### ISSUE TITLE
 App crash with SIGABRT -6 when using software renderer since ExoPlayer 1.5

### ISSUE THREAD

**Issue by dnutcracker** [google/ExoPlayer#895] opened 2015-10-24 13:14 UTC
We're using ExoPlayer with software renderer and it works flawlessly - until ExoPlayer 1.5.
Since then we're experience app hard-crash (quick app restart - not even a crash dialog) occasionally with no apparent reason/cause.
The crash happens across multiple android versions(4,5 and 6) and across multiple devices.

I don't know what changed in ExoPlayer 1.5 that started causing this - but we're quite sure it didn't happen on 1.4.

I've attached the native stack of the crash hoping it would help shed some light on this.
(Seems like the crash happens due to an assert in the android SoftwareRenderer)

Crashed: 
       at tgkill(Unknown Source)
       at pthread_kill(Unknown Source)
       at raise(Unknown Source)
       at (Missing)(Unknown Source)
       at abort(Unknown Source)
       at __android_log_assert(Unknown Source)
       at android::SoftwareRenderer::render(void const*, unsigned int, long long, void*, android::sp<android::AMessage> const&)(Unknown Source)
       at android::MediaCodec::onReleaseOutputBuffer(android::sp<android::AMessage> const&)(Unknown Source)
       at android::MediaCodec::onMessageReceived(android::sp<android::AMessage> const&)(Unknown Source)
       at android::ALooperRoster::deliverMessage(android::sp<android::AMessage> const&)(Unknown Source)
       at android::ALooper::loop()(Unknown Source)
       at android::Thread::_threadLoop(void*)(Unknown Source)
       at android::AndroidRuntime::javaThreadShell(void*)(Unknown Source)
       at (Missing)(Unknown Source)
       at (Missing)(Unknown Source)
       at (Missing)(Unknown Source)

Please let me know if I need to add any more information.
Thanks.

**Comment by ojw28** [comment] 2015-10-25 21:45
- By "software renderer", do you mean that you're using the H264 software decoder, or something else? I'm unclear about exactly what your setup is. Also, what media are you playing, exactly (i.e. what's the container, and what's inside of it)? Please provide a link to test media if possible.

- When you say "multiple devices", does this include Nexus devices? If so which one(s)? Can you reproduce the issue with the demo app by forcing the software decoder there? If so, please provide steps. Thanks!

**Comment by dnutcracker** [comment] 2015-10-26 09:24
* By software renderer I mean H264 software decoder provided by google on the device.
* I'm playing local mp4 containers containing H264 encoded video files (that were d/l first and then played) which were recorded by android/iphone front camera.
* Multiple devices does include the Motorola Nexus 6 device (Also Samsung, LG and other Motorola devices)
* Regarding reproduction - the problem is that the exact scenario is still unknown - after using the app for a few minutes it 'just happens' - my guess is that it's related to a background thread that releases resources since I've once witnessed that the crash happened a couple of seconds after I've already left the video playing activity.
* I'm not sure how can I reproduce it using the demo app since we're allocating, rendering and releasing multiple instances of ExoPlayer simultaneously while the demo only handles a single video.
* Keep in mind that this doesn't happen when using ExoPlayer 1.4.2. (What changed in 1.5 that could be related?)
* If it's any help I can provide a link to the app (which is available in beta) on the play store.

Thanks

**Comment by dnutcracker** [comment] 2015-11-01 12:27
@ojw28 I've added more info - please say if you need anything else

**Comment by ojw28** [comment] 2015-11-02 17:06
It's going to be pretty hard for us to work out what's happened here, to be honest. I can't think of any changes that would be related. You may have to do a binary search on the individual commits between the two versions to work out exactly which commit introduced the problem. Which is time consuming, but which would give us more to go on.

**Comment by dnutcracker** [comment] 2015-11-03 08:34
Well...That's bad news...
For the time being 1.4.2 does the work for us.
When I'll get around to doing the enjoyable binary search - I'll let know about the results.

P.S
In my opinion - a crash at the native level surely indicates a bug since the code should protect itself and populate the problem as a manageable exception but I guess investigating this native code is out of the scope of ExoPlayer but perhaps you can direct me to the people at Google that are responsible for that code and I can try help them figure out the problem. (There are some more native crashes that I encounter regularly)

Thanks.

**Comment by ojw28** [comment] 2015-11-06 12:00
You should file issues with the platform using Android's [issue tracker](https://code.google.com/p/android/issues/list). Note that you'll need to provide full bug reports for any issues you file to be actionable. Logcat output isn't sufficient for figuring out what went wrong.

If you do file issues with bugreports attached, feel free to link to them from this post and I can route them to the right people.

**Comment by dnutcracker** [comment] 2015-11-08 08:19
Ok.I'll to that.

**Comment by allenmosesw** [comment] 2015-11-16 06:40
Updating from Exoplayer 1.4 to 1.5 has a lot of missing classes. i,e MultiTrackChunkSource etc. Is there an alternative for this

**Comment by ojw28** [comment] 2015-11-16 10:44
@allenmosesw Please file unrelated issues separately from existing threads. I'm going to delete this part of the thread, but to answer your question, there are proper multi-track APIs on the ExoPlayer interface now, which mean that MultiTrackChunkSource should no longer be needed. See [here](https://google.github.io/ExoPlayer/2015/09/30/r1.5.0.html) for a very brief overview.

**Comment by ojw28** [comment] 2016-02-21 21:13
Closing due to lack of further information.

**Closed by ojw28** 2016-02-21 21:13 UTC
Labels: need more info
