### ISSUE TITLE
Codec failure when playing media multiple times

### ISSUE THREAD

**Issue by Manli123** [google/ExoPlayer#10858] opened 2022-12-12 11:36 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

android 8.1

### Reproducible in the demo app?

Yes

### Reproduction steps

```
 exoPlayer = new ExoPlayer.Builder(itemView.getContext()).build();

            exoPlayerListItems.add(exoPlayer);


//                exoPlayer.release();


            exoPlayer.addListener(new Player.Listener() {
                @Override
                public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                    Player.Listener.super.onPlayerStateChanged(playWhenReady, playbackState);

                    if (playbackState == Player.STATE_BUFFERING) {
                        mProgressBar.setVisibility(View.VISIBLE);
                        playBtn.setVisibility(View.GONE);
                    } else if (playbackState == Player.STATE_READY) {
                        mProgressBar.setVisibility(View.GONE);
                    }
                }

                @Override
                public void onPlayerError(PlaybackException error) {
                    Player.Listener.super.onPlayerError(error);
                    Log.e("play_error",""+error.getMessage().toString()+""+error.errorCode);
//                    Toast.makeText(context, "Can't play this video", Toast.LENGTH_SHORT).show();
                }
            });


                mVideoView.setPlayer(exoPlayer);

            mVideoView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM);
            mVideoView.setShutterBackgroundColor(Color.TRANSPARENT);
            exoPlayer.seekTo(0);
            exoPlayer.setRepeatMode(Player.REPEAT_MODE_ONE);

            DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context);
// DefaultHttpDataSource.Factory def=new DefaultHttpDataSource.Factory();
//            mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(MediaItem.fromUri(Uri.parse(videoItem.videoURL)));
//

            mediaSource = new ProgressiveMediaSource.Factory(
                    new CacheDataSource.Factory()
                            .setCache(SimpleMediaPlayer.getInstance(mContext))
                            .setUpstreamDataSourceFactory(new DefaultHttpDataSource.Factory()
                                    .setUserAgent(mContext.getString(R.string.app_name)))
                            .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
            ).createMediaSource(MediaItem.fromUri(videoItem.videoURL));

            exoPlayer.addMediaSource(mediaSource);

            exoPlayer.prepare();

            exoPlayer.setPlayWhenReady(true);
            exoPlayer.play();

```

### Expected result

video should play without error

### Actual result
```
I/MediaCodec: release
I/MediaCodec: kWhatStop or kWhatRelease
I/ACodec: initiateShutdown kWhatReleaseCodecInstance
I/ACodec: mIsVivoLogEnable = 0
I/OMXClient: Treble IOmx obtained
I/MediaCodec: release
I/MediaCodec: kWhatStop or kWhatRelease
I/ACodec: initiateShutdown kWhatReleaseCodecInstance
I/MediaCodec: ~MediaCodec
W/MediaCodecRenderer: Preferred decoder instantiation failed. Sleeping for 50ms then retrying.
I/MediaCodec: MediaCodec constructor
D/MediaCodec: MediaCodec CreateByComponentName name:OMX.qcom.video.decoder.avc, pid:-1
I/ACodec: mIsVivoLogEnable = 0
I/OMXClient: Treble IOmx obtained
D/SurfaceUtils: connecting to surface 0x793b53a010, reason connectToSurface
I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 17717251
D/SurfaceUtils: disconnecting from surface 0x793b53a010, reason connectToSurface(reconnect)
D/SurfaceUtils: connecting to surface 0x793b53a010, reason connectToSurface(reconnect)
I/ACodec: [OMX.qcom.video.decoder.avc]configureCodec AMessage(what = 'conf', target = 12) = {
      int32_t max-height = 1080
      string mime = "video/avc"
      int32_t priority = 0
      int32_t color-standard = 1
      Buffer csd-1 = {
        00000000:  00 00 00 01 28 ee 3c b0                           ....(.<.
      }
      int32_t color-transfer = 3
      int32_t max-width = 1920
      int32_t width = 1920
      int32_t color-range = 2
      float frame-rate = 30.000000
      int32_t rotation-degrees = 0
      int32_t max-input-size = 290158
      int32_t height = 1080
      Buffer csd-0 = {
        00000000:  00 00 00 01 27 64 00 28  ac 56 c0 78 02 27 e5 9a  ....'d.(.V.x.'..
        00000010:  80 80 80 81                                       ....
      }
      RefBase *native-window = 0x793b53a000
    }
I/ExtendedACodec: setupVideoDecoder()
E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -12
E/ACodec: signalError(omxError 0x80001001, internalError -12)
E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 3
D/SurfaceUtils: disconnecting from surface 0x793b53a010, reason disconnectFromSurface
E/MediaCodec: configure failed with err 0xfffffff4, resetting...
I/MediaCodec: reset
I/MediaCodec: release
I/MediaCodec: kWhatStop or kWhatRelease
I/ACodec: initiateShutdown kWhatReleaseCodecInstance
I/ACodec: mIsVivoLogEnable = 0
I/OMXClient: Treble IOmx obtained
I/MediaCodec: release
I/MediaCodec: kWhatStop or kWhatRelease
I/ACodec: initiateShutdown kWhatReleaseCodecInstance
I/MediaCodec: ~MediaCodec
W/MediaCodecRenderer: Failed to initialize decoder: OMX.qcom.video.decoder.avc
      android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at android.media.MediaCodec.configure(MediaCodec.java:1872)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:113)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:916)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:192)
        at android.os.HandlerThread.run(HandlerThread.java:65)
E/MediaCodecVideoRenderer: Video codec error
      com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(2, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:916)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:192)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at android.media.MediaCodec.configure(MediaCodec.java:1872)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:113)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:916) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
E/recyclerPosition: 2
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:571)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:192)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(2, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:916)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at android.media.MediaCodec.configure(MediaCodec.java:1872)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:113)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:916) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:994) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:495) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
E/poDAtta: 0
I/MediaCodec: flush
I/ExoPlayerImpl: Release ce14a22 [ExoPlayerLib/2.18.2] [1811, vivo 1811, vivo, 27] [goog.exo.core, goog.exo.database, goog.exo.ui, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
I/MediaCodec: flush
V/PlayerBase: baseStop() piid=47463
D/AudioFeatures: PlaybackDetectionCallBack start:android.media.PlayerBase$IPlayerWrapper@638c569
I/MediaCodec: release
I/MediaCodec: kWhatStop or kWhatRelease
I/ACodec: initiateShutdown kWhatReleaseCodecInstance
V/PlayerBase: baseRelease() piid=47463 state=4
W/PlayerBase: baseStop state not match:4
V/AudioTrack: ~AudioTrack, releasing session id 59473 from 17302 on behalf of 17302
D/SurfaceUtils: disconnecting from surface 0x794f345010, reason disconnectFromSurface
I/MediaCodec: ~MediaCodec
I/MediaCodec: release
I/MediaCodec: kWhatStop or kWhatRelease
I/ACodec: initiateShutdown kWhatReleaseCodecInstance
I/MediaCodec: ~MediaCodec
I/View: updateSystemUiVisibility, blackBackground = false, getVisibility() = 0, getWindowVisibility() = 0, viewBounds = Rect(-755, -1187 - 1476, 68), windowBounds = Rect(0, 56 - 720, 1520), view = TextureView:android.view.TextureView{5a73a04 V.ED..... ........ 0,0-2231,1255}
E/pos: 1
E/play_error: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, 30.0], [-1, -1]), format_supported=YES4001
V/FA: Inactivity, disconnecting from the service
```
### Media

any video

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by sysmind** [comment] 2022-12-12 11:43
Hey Floks,

I'm facing below problem- 


```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:607)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:268)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     **Caused by: com.google.android.exoplayer2.ParserException: Missing CodecPrivate for codec V_MPEG4/ISO/AVC**
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.getCodecPrivate(MatroskaExtractor.java:2548)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$Track.initializeOutput(MatroskaExtractor.java:2074)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.endMasterElement(MatroskaExtractor.java:812)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$InnerEbmlProcessor.endMasterElement(MatroskaExtractor.java:1947)
        at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:88)
        at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:512)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)

And here is my code -


  player = new ExoPlayer.Builder(Objects.requireNonNull(getActivity())).build();
        simpleExoPlayerView.setPlayer(player);
        MediaItem mediaItem = MediaItem.fromUri(videoUri);
        player.setMediaItem(mediaItem);
        player.prepare();
        player.play();
```

**Comment by marcbaechinger** [comment] 2022-12-12 12:18
@sysmind This looks like malformed content as the exception says. Not sure if we can do something about it. If you think you want someone to look into that, then please file a new issue and provide a URI to the media. Without the media this is not actionable for us.

**Comment by marcbaechinger** [comment] 2022-12-12 12:19
@Manli123 Sorry, but I'm going to close this issue without looking at it. You have filed the same issue now several times and I'm not sure why you think you get a different response when you file it again. I don't think that this is an issue caused by caching, but when it fails when you played more often than once, it may be that the app does not release the player properly and codecs are not available. If you want us to further look into your issues, then go back to one of those that you've already created and add some new and sorted information there.  So I'm closing this as won't fix. If you want us to convince it's a library easy please do in one single report.

**Closed as completed by marcbaechinger** 2022-12-12 12:19 UTC
Labels: duplicate, wont fix: app issue

**Comment by sysmind** [comment] 2022-12-12 12:50
> @sysmind This looks like malformed content as the exception says. Not sure if we can do something about it. If you think you want someone to look into that, then please file a new issue and provide a URI to the media. Without the media this is not actionable for us.

file url-
https://cdnmedia-fm.melpapp.com/7a14c9d8-c99a-42d6-8a55-cc02395ee339/0d53@screencapture.webm?sessionid=7zoijdm41s00
