### ISSUE TITLE
Motorola G5: Multi-period DASH - corruption when new period is from different encoder with no level switch

### ISSUE THREAD

**Issue by olivier-yospace** [google/ExoPlayer#6711] opened 2019-11-29 11:43 UTC
### Reproduction steps
Play the Live Streams and watch when there is a new Period (on Android 8)

### Link to test content
Test URL (provided by Email )

### A full bug report captured from the device
Full Bug Capture report from device (provided by Email)

### Version of ExoPlayer being used
We are using Exo Player v2.10.8 on Android 8

### Device(s) and version(s) of Android being used
We have tested this on a Motorolla G5 running Android 8.1.0.

On Android 9 (using a Samsung Galaxy S10), we cannot reproduce the issue with Exo Player v2.10.8.

### Link to test content
Test URL (provided by Email)

### A full bug report captured from the device
Full Bug Capture report from device (provided by Email)

### Version of ExoPlayer being used
We are using Exo Player v2.10.8

### Device(s) and version(s) of Android being used
We have tested this on a Motorolla G5 running Android 8.1.0.
We have also tested on a Samsung Galaxy S10 running Android 9 (and Exo Player v2.10.8) and the issue does not appear.

**Comment by ojw28** [comment] 2019-12-20 18:32
Have you found any devices other than the Motorola G5 that reproduce the problem? Thanks!

**Comment by ojw28** [comment] 2019-12-20 18:34
Note to self: This is another issue that appears to be specific to the Motorola G5: https://github.com/google/ExoPlayer/issues/6189

**Comment by olivier-yospace** [comment] 2019-12-30 12:12
Hi,

We were only able to reproduce on our G5 (But we don't have so many different devices).

**Comment by ojw28** [comment] 2021-06-07 15:44
This is a device specific issue. The device is 4+ years old, and discontinued. Realistically, we can't dedicate resources to investigating further on our side. Even if we were to root cause an issue in the underlying platform, it seems unlikely that it would be fixed. Hence closing this as obsolete.

**Closed as completed by ojw28** 2021-06-07 15:44 UTC
Labels: bug: device specific
