### ISSUE TITLE
JCenter is shutting down -> MavenCentral?

### ISSUE THREAD

**Issue by EAvallone** [google/ExoPlayer#8758] opened 2021-03-24 17:24 UTC
JCenter is shutting down: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

So, please consider publishing to Maven Central. The deadline is May 1st.

**Comment by andrewlewis** [comment] 2021-03-24 17:36
Duplicate of #5246

**Closed as completed by andrewlewis** 2021-03-24 17:36 UTC
Labels: question
