### ISSUE TITLE
FATAL EXCEPTION Exoplayer  without subtitleButton

### ISSUE THREAD

**Issue by sontn-fabbi** [google/ExoPlayer#8086] opened 2020-10-19 07:43 UTC
checkNotNull(subtitleButton)
          .setImageDrawable(subtitleIsOn ? subtitleOnButtonDrawable : subtitleOffButtonDrawable);

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: jp.co.tvtokyo.webapi.stg2, PID: 13538
    java.lang.NullPointerException: throw with null exception
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
        at com.google.android.exoplayer2.ui.StyledPlayerControlView$TextTrackSelectionAdapter.init(StyledPlayerControlView.java:2005)
        at com.google.android.exoplayer2.ui.StyledPlayerControlView.initTrackSelectionAdapter(StyledPlayerControlView.java:1280)
        at com.google.android.exoplayer2.ui.StyledPlayerControlView.updateTrackLists(StyledPlayerControlView.java:1248)
        at com.google.android.exoplayer2.ui.StyledPlayerControlView.access$1800(StyledPlayerControlView.java:298)
        at com.google.android.exoplayer2.ui.StyledPlayerControlView$ComponentListener.onTracksChanged(StyledPlayerControlView.java:1813)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$4$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:1425)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$sJrY7lA_vUJy5MdfV-ndTSxVTXI.invokeListener(Unknown Source:2)
        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:285)
        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1491)
        at com.google.android.exoplayer2.ExoPlayerImpl.access$100(ExoPlayerImpl.java:56)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:1422)
        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1321)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:949)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:913)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$0$ExoPlayerImpl(ExoPlayerImpl.java:162)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$c3953g1V6xPbTIQ95lEUPxO10qU.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by andrewlewis** [comment] 2020-10-19 08:14
Duplicate of #7962

**Closed as completed by andrewlewis** 2020-10-19 08:14 UTC
Labels: duplicate
