### ISSUE TITLE
Video freeze when seekTo is called after midroll ads

### ISSUE THREAD

**Issue by usopphammer** [google/ExoPlayer#10274] opened 2022-05-18 20:12 UTC
Our QA team observes the same bug - https://github.com/google/ExoPlayer/issues/7161
When we call Player.seekTo() method a video freezes and the player doesn't react to any media event. It's very hard to reproduce, on my devices it happens 1 time out of 1000.

We use the latest 2.17 version of the Player. There are no deprecated classes in our code. Timeouts are set by default.
It happens for any ads, even for ads from this list https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags 

Do you have any ideas about what can be a root cause? Any possible fix or workaround?

**Comment by icbaker** [comment] 2022-05-19 08:48
Can you provide a little more information about your setup? Specifically:

* Is the content between the ads protected with DRM?
    * If so, how do you configure the DRM playback? A sample code snippet of instantiating a `MediaItem` or `MediaSource` would be helpful here, as well as any direct `DrmSessionManager` configuration e.g. via `DefaultDrmSessionManager.Builder`.
* Precisely how are you triggering `Player.seekTo()` 'after midroll ads'? Are you reacting to an event, e.g. from `Player.Listener` or `AnalyticsListener` or are you using just time-based triggering e.g. with `ExoPlayer.createMessage`?

**Comment by denis-solomko-deltatre** [comment] 2022-05-30 13:17
@icbaker 
1. Yes we use DRM

**DRM creation**
```
private fun buildDrmSessionManager(
        context: Context,
        drmSchemeUuid: UUID?,
        drmLicenseUrl: String
): DefaultDrmSessionManager {

        val drmCallback = HttpMediaDrmCallback(
            drmLicenseUrl,
            DefaultHttpDataSource.Factory().setUserAgent(getUserAgent(context))
        )

        releaseMediaDrm()

        try {
            frameworkMediaDrm = FrameworkMediaDrm.newInstance(drmSchemeUuid!!)
        } catch (exception: UnsupportedDrmException) {
            AxisLogger.instance().e(exception.message)
        }

        return DefaultDrmSessionManager.Builder()
            .setUuidAndExoMediaDrmProvider(drmSchemeUuid!!, FrameworkMediaDrm.DEFAULT_PROVIDER)
            .build(drmCallback)
}
```

**MediaSource creation**
```
 /**
   * Builds the [MediaSource] object containing the main video Media Source.
   *
   * @param videoUri the videoUrl
   * @return MediaSource instance
   */
private fun buildDASHMediaSource(
        uri: Uri,
        drmSessionManager: DrmSessionManager // a previously created DRM session manager
): MediaSource {
        return DashMediaSource.Factory(
            DefaultDashChunkSource.Factory(mediaDataSourceFactory!!),
            mediaDataSourceFactory
        )
            .setDefaultSettings(drmSessionManager, createLoadErrorPolicy())
            .createMediaSource(createMediaItem(uri))
}
```

**AdsMediaSource creation**
```
 private fun createAdsMediaSource(
        playerView: StyledPlayerView,
        mediaSource: MediaSource, // a previously created dash media source
        drmEngine: DrmSessionManager, // a previously created DRM session manager
        adTagUri: Uri,
): MediaSource {

        adsLoader = ImaAdsLoader.Builder(playerView.context).build().apply {
            setPlayer(playerView.player)
        }

        val adMediaSourceFactory = AdsMediaSourceFactory(this::buildDASHMediaSource)
            .setDrmSessionManagerProvider {drmEngine }

        return mediaSource.mediaItem.localConfiguration?.let {
            // this code duplicates DefaultMediaSourceFactory.maybeWrapWithAdsMediaSource
            val adTagDataSpec = DataSpec(adTagUri)
            val adsId = ImmutableList.of(mediaSource.mediaItem.mediaId, it.uri, adTagUri)
            AdsMediaSource(mediaSource, adTagDataSpec, adsId, adMediaSourceFactory, adsLoader!!, playerView)
        }
            ?: mediaSource
}
```

our AdsMediaSourceFactory
```
class AdsMediaSourceFactory(
    val buildMediaSourceFactoryMethod: (Uri, DrmSessionManager) -> MediaSource
) : MediaSource.Factory {

    private var drmSessionManagerProvider: DrmSessionManagerProvider? = null

    override fun setDrmSessionManagerProvider(drmSessionManagerProvider: DrmSessionManagerProvider?): MediaSource.Factory {
        this.drmSessionManagerProvider = drmSessionManagerProvider
        return this
    }

    override fun setLoadErrorHandlingPolicy(loadErrorHandlingPolicy: LoadErrorHandlingPolicy?): MediaSource.Factory {
        return this
    }

    override fun getSupportedTypes(): IntArray {
        return intArrayOf(C.TYPE_DASH, C.TYPE_OTHER)
    }

    override fun createMediaSource(mediaItem: MediaItem): MediaSource {
        val drmSessionManager = drmSessionManagerProvider?.get(mediaItem)
            ?: throw IllegalStateException("drmSessionManager is null")

        return mediaItem.localConfiguration?.uri
            ?.let {
                buildMediaSourceFactoryMethod(it, drmSessionManager)
            } ?: let {
                throw IllegalStateException("uri is null")
            }
    }
}
```

2. we trigger `seekTo` in a button click listener

**Comment by icbaker** [comment] 2022-05-30 15:02
Are you able to try [depending on ExoPlayer locally](https://github.com/google/ExoPlayer#locally)? If so please try applying [this patch](https://github.com/google/ExoPlayer/files/8799290/0001-Ensure-DRAIN_ACTION_FLUSH_AND_UPDATE_DRM_SESSION-is-.patch.txt) on top of r2.17.1 and see if it fixes the issue.

We think there's a theoretical problem with the way we handle seeking after a format switch (like ad -> content) in DRM content - but we've not been able to reproduce a problem at all in our demo app. We're reluctant to submit the fix to the library without being able to directly see it fix something - so since you seem to have a repro case it would be great if you could report back with your findings (either to let us know that it worked, or that it didn't make a difference (or that it made things worse!)). Thanks!

**Comment by icbaker** [comment] 2022-06-15 10:58
I'm closing this because I hope it's fixed with the commit linked above, which will be included in the next release.

**Closed as completed by icbaker** 2022-06-15 10:58 UTC
Labels: bug

**Comment by denis-solomko-deltatre** [comment] 2022-06-15 11:46
@icbaker I sent a build for our qa team, but unfortunately, they haven't checked it yet as they have a lot of other work to do. They will be able to test it only next week. Please don't close the ticket now, I will write an update later.

**Comment by denis-solomko-deltatre** [comment] 2022-06-16 15:37
@icbaker I've received info from ous QAs. The bug is not reproducible with this approach. Thanks!

**Comment by denis-solomko-deltatre** [comment] 2022-06-16 15:41
@icbaker Could you tell me when the next release will be?

**Comment by icbaker** [comment] 2022-06-20 07:59
3 days ago :)

https://github.com/google/ExoPlayer/releases/tag/r2.18.0
