### ISSUE TITLE
Exoplayer crossfade support

### ISSUE THREAD

**Issue by adoudech** [google/ExoPlayer#8753] opened 2021-03-24 08:52 UTC
Is it possible to support crossfade transition between two medias using Merging/Clipping/Concatenating media source without overriding the behavior of some internal Exoplayer classes such as `MediaCodecAudioRenderer`?
If not, what is the easiest way to implement this feature and what you recommend?
Thank you

**Comment by andrewlewis** [comment] 2021-03-24 09:29
I'm afraid this isn't supported. See also #3438.

**Comment by andrewlewis** [comment] 2021-03-24 09:29
Duplicate of #3438

**Closed as completed by andrewlewis** 2021-03-24 09:29 UTC
Labels: duplicate
