### ISSUE TITLE
Exoplayer doesn't stream some of m3u8 links

### ISSUE THREAD

**Issue by shlomivman** [google/ExoPlayer#8395] opened 2020-12-23 22:36 UTC
Hello everyone,
first of all, I am using the NEWEST demo sample (not edited at all).

I am trying to play an URL of m3u8 from a website,
the website link is https://www.mako.co.il/mako-vod-live-tv/VOD-6540b8dcb64fd31006.htm

There are 2 links that appear in the chrome dev network tab:
1) https://keshethlslive-i.akamaihd.net/hls/live/512033/CH2LIVE_HIGH/index.m3u8?hdnea=st%3D1608762442%7Eexp%3D1608763342%7Eacl%3D%2F*%7Ehmac%3D86b547e7644d605dd7b3a9e22cbb71b085fac86147ff595e3ac28a0064df35c3
This one **WORKS**

2) https://keshethlslive-i.akamaihd.net/hls/live/512033/CH2LIVE_HIGH/index_850.m3u8?hdntl=exp=1608848962~acl=/*~data=hdntl~hmac=fc3b5651065231b2983d9dce1c0f30216bcb2ba34fd86bd5a4fe4b73ee80eeef

this one **DOES NOT** work

if I test the links on a website like https://www.hlsplayer.net/ which play the links for me to test, they BOTH works just fine, so there is no issue with the link at all.

I have tried to change the default agent and it didn't help to fix the issue

the error that that it gives me when trying to run:

```
E/EventLogger: internalError [eventTime=3.48, mediaPos=0.00, window=0, loadError
      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:486)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:764)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:579)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
    ]
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:486)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:764)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:579)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
E/EventLogger: playerFailed [eventTime=3.49, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.ext.cronet.CronetDataSource.open(CronetDataSource.java:486)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:764)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:579)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

Please help me to deal with the issue,
Thanks!

**Comment by ojw28** [comment] 2020-12-23 22:56
I also tried the links you provided on the website you provided, and they do not play for me. I see an HTTP 403 error (see the text in red on the right hand side of the screenshot below). This is the exact same error you're seeing from ExoPlayer.

![Screenshot 2020-12-23 at 22 53 29](https://user-images.githubusercontent.com/7881572/103042489-b24ddb80-4571-11eb-8a54-feb375599125.png)

So, it appears that the streaming provider is denying access to these streams. It's possible that access is being granted based on some cookies that your browser has obtained as a result of you navigating around the `https://www.mako.co.il` website. These cookies are obviously not available if you're using ExoPlayer directly, having not done anything to obtain them. It's probably working as intended by the stream provider that they're forbidding access to the streams. Closing on that basis.

**Closed as completed by ojw28** 2020-12-23 22:56 UTC
Labels: wont fix: intended behavior

**Comment by shlomivman** [comment] 2020-12-23 23:48
Hi Oliver @ojw28 ,
First of all thanks for the quick answer,
I have a question you can easily answer,
In the demo project, where to setup the default agent?
is it in file PlayerManager?
private static final String USER_AGENT = "HERE";

or I have to set it up in other place?

and if I want to set some cookies to get the player work, how to do that? where exactly (in the demo project) I have to insert the cookies?

Thanks!

**Comment by ojw28** [comment] 2021-01-05 17:35
It looks like it's not actually that easy to change the user agent when using Cronet (we should fix that!). If you change [this piece of the demo app](https://github.com/google/ExoPlayer/blob/r2.12.2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoUtil.java#L84) to use `DefaultHttpDataSourceFactory` instead then it does become trivial, since there are constructors for that factory that take a `userAgent` argument as per the [Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultHttpDataSourceFactory.html).

For cookies, I think you can probably set the [Cookie request header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie) directly using something like:

```
 httpDataSourceFactory.getDefaultRequestProperties().set("Cookie", <your cookies here>);
```

If using `DefaultHttpDataSourceFactory` you can probably also inject the cookies into `DEFAULT_COOKIE_MANAGER`, which is in the demo application's `PlayerActivity` class.

**Comment by shlomivman** [comment] 2021-01-07 16:51
I have got everything to work,
thank you very much, I really appreciate your help/work!

**Comment by ojw28** [comment] 2021-01-07 19:33
No worries! We will also be making it easier to set the user agent when using Cronet in a future release (probably `2.13.0`).
