### ISSUE TITLE
video freeze about 8 seconds at the beginning

### ISSUE THREAD

**Issue by shadowor1982a** [google/ExoPlayer#8808] opened 2021-04-10 19:13 UTC
**Issue description:**
Video plays after static frame about 8 seconds, and Audio plays well all the time. The sample video file plays well by Android browser app and android.widget.VideoView .

**Smaple video file:**
http://81.70.232.219/uploads/material_upload/video/2021/material_1613878758.6868_2.21%20%E5%A4%96%E6%95%99%E8%A7%86%E9%A2%91%20Wash%20Hands%20Step2%20Narrative%20-%20Screen.mp4

**Version of ExoPlayer:**
2.13.2

**Device(s) and version(s) of Android:**
Android 8 (Xiaomi 5)
Android 10 (Huawei Mate30 5G)
Android 11 (Android Virtual Device)

**Reproduce steps:**
1) Follow https://exoplayer.dev/demo-application.html to run exoplayer2 demo to play above sample video file
2) the issue still exits when playing above sample video file located on phone storage

**Logcat messages:**
2021-04-11 02:59:22.645 11215-11215/com.google.android.exoplayer2.demo I/Timeline: Timeline: Activity_launch_request time:50217783 intent:Intent { act=com.google.android.exoplayer.demo.action.VIEW dat=http://81.70.232.219/... cmp=com.google.android.exoplayer2.demo/.PlayerActivity (has extras) }
2021-04-11 02:59:22.688 11215-11258/com.google.android.exoplayer2.demo D/ViewContentFactory: initViewContentFetcherClass
2021-04-11 02:59:22.688 11215-11258/com.google.android.exoplayer2.demo I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
2021-04-11 02:59:22.688 11215-11258/com.google.android.exoplayer2.demo D/ViewContentFactory: createInterceptor took 0ms
2021-04-11 02:59:22.690 11215-11258/com.google.android.exoplayer2.demo I/ContentCatcher: Interceptor : Catcher list invalid for com.google.android.exoplayer2.demo@com.google.android.exoplayer2.demo.PlayerActivity@222479677
2021-04-11 02:59:22.690 11215-11258/com.google.android.exoplayer2.demo I/ContentCatcher: Interceptor : Get featureInfo from config pick_mode
2021-04-11 02:59:22.779 11215-11222/com.google.android.exoplayer2.demo I/zygote64: Do partial code cache collection, code=490KB, data=325KB
2021-04-11 02:59:22.780 11215-11222/com.google.android.exoplayer2.demo I/zygote64: After code cache collection, code=490KB, data=325KB
2021-04-11 02:59:22.780 11215-11222/com.google.android.exoplayer2.demo I/zygote64: Increasing code cache capacity to 2MB
2021-04-11 02:59:22.780 11215-11222/com.google.android.exoplayer2.demo I/zygote64: Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
2021-04-11 02:59:22.795 11215-11215/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init beb5afa [ExoPlayerLib/2.13.2] [gemini, MI 5, Xiaomi, 26]
2021-04-11 02:59:22.798 11215-11215/com.google.android.exoplayer2.demo D/AudioManager: getStreamVolume isRestricted mode = 0
2021-04-11 02:59:22.806 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: playWhenReady [eventTime=0.00, mediaPos=0.00, window=0, true, USER_REQUEST]
2021-04-11 02:59:22.813 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=0.01, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
2021-04-11 02:59:22.814 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
2021-04-11 02:59:22.814 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=true]
2021-04-11 02:59:22.814 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: ]
2021-04-11 02:59:22.815 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: mediaItem [eventTime=0.01, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
2021-04-11 02:59:22.817 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: state [eventTime=0.01, mediaPos=0.00, window=0, BUFFERING]
2021-04-11 02:59:22.866 11215-11222/com.google.android.exoplayer2.demo I/zygote64: Compiler allocated 8MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
2021-04-11 02:59:22.893 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: surfaceSize [eventTime=0.09, mediaPos=0.00, window=0, 1080, 1848]
2021-04-11 02:59:22.898 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=0.09, mediaPos=0.00, window=0, period=0, true]
2021-04-11 02:59:22.900 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=0.09, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2021-04-11 02:59:22.900 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
2021-04-11 02:59:22.900 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   window [?, seekable=false, dynamic=false]
2021-04-11 02:59:22.900 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: ]
2021-04-11 02:59:22.946 11215-11269/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllActiveAnimators on 0x7f82d94800 (ExpandableListView) with handle 0x7f769271e0
2021-04-11 02:59:23.027 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: timeline [eventTime=0.22, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
2021-04-11 02:59:23.028 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   period [105.10]
2021-04-11 02:59:23.028 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   window [105.10, seekable=true, dynamic=false]
2021-04-11 02:59:23.028 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: ]
2021-04-11 02:59:23.033 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: videoEnabled [eventTime=0.23, mediaPos=0.00, window=0, period=0]
2021-04-11 02:59:23.035 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: audioEnabled [eventTime=0.23, mediaPos=0.00, window=0, period=0]
2021-04-11 02:59:23.036 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: tracks [eventTime=0.23, mediaPos=0.00, window=0, period=0
2021-04-11 02:59:23.036 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   MediaCodecVideoRenderer [
2021-04-11 02:59:23.036 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2021-04-11 02:59:23.036 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, codecs=avc1.64001F, res=1280x720, fps=13.540002, supported=YES
2021-04-11 02:59:23.036 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:     ]
2021-04-11 02:59:23.036 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   ]
2021-04-11 02:59:23.036 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   MediaCodecAudioRenderer [
2021-04-11 02:59:23.036 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
2021-04-11 02:59:23.037 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=1, sample_rate=48000, language=und, supported=YES
2021-04-11 02:59:23.037 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:     ]
2021-04-11 02:59:23.037 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   ]
2021-04-11 02:59:23.037 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   TextRenderer []
2021-04-11 02:59:23.037 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   MetadataRenderer []
2021-04-11 02:59:23.037 11215-11215/com.google.android.exoplayer2.demo D/EventLogger:   CameraMotionRenderer []
2021-04-11 02:59:23.037 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: ]
2021-04-11 02:59:23.042 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: downstreamFormat [eventTime=0.24, mediaPos=0.00, window=0, period=0, id=1, mimeType=video/avc, codecs=avc1.64001F, res=1280x720, fps=13.540002]
2021-04-11 02:59:23.046 11215-11513/com.google.android.exoplayer2.demo I/OMXClient: Treble IOmx obtained
2021-04-11 02:59:23.072 11215-11512/com.google.android.exoplayer2.demo I/MediaCodec: MediaCodec will operate in async mode
2021-04-11 02:59:23.075 11215-11512/com.google.android.exoplayer2.demo D/SurfaceUtils: connecting to surface 0x7f769de010, reason connectToSurface
2021-04-11 02:59:23.075 11215-11512/com.google.android.exoplayer2.demo I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 11484165
2021-04-11 02:59:23.075 11215-11512/com.google.android.exoplayer2.demo D/SurfaceUtils: disconnecting from surface 0x7f769de010, reason connectToSurface(reconnect)
2021-04-11 02:59:23.075 11215-11512/com.google.android.exoplayer2.demo D/SurfaceUtils: connecting to surface 0x7f769de010, reason connectToSurface(reconnect)
2021-04-11 02:59:23.077 11215-11513/com.google.android.exoplayer2.demo I/ExtendedACodec: setupVideoDecoder()
2021-04-11 02:59:23.083 11215-11513/com.google.android.exoplayer2.demo I/ExtendedACodec: Decoder will be in frame by frame mode
2021-04-11 02:59:23.103 11215-11513/com.google.android.exoplayer2.demo D/SurfaceUtils: set up nativeWindow 0x7f769de010 for 1280x720, color 0x7fa30c06, rotation 0, usage 0x20002900
2021-04-11 02:59:23.125 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: videoDecoderInitialized [eventTime=0.32, mediaPos=0.00, window=0, period=0, OMX.qcom.video.decoder.avc]
2021-04-11 02:59:23.127 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: videoInputFormat [eventTime=0.32, mediaPos=0.00, window=0, period=0, id=1, mimeType=video/avc, codecs=avc1.64001F, res=1280x720, fps=13.540002]
2021-04-11 02:59:23.129 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: downstreamFormat [eventTime=0.32, mediaPos=0.00, window=0, period=0, id=2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=1, sample_rate=48000, language=und]
2021-04-11 02:59:23.132 11215-11519/com.google.android.exoplayer2.demo I/OMXClient: Treble IOmx obtained
2021-04-11 02:59:23.139 11215-11519/com.google.android.exoplayer2.demo I/MediaCodec: MediaCodec will operate in async mode
2021-04-11 02:59:23.140 11215-11519/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -2147483648)
2021-04-11 02:59:23.144 11215-11519/com.google.android.exoplayer2.demo I/ACodec: codec does not support config priority (err -2147483648)
2021-04-11 02:59:23.145 11215-11519/com.google.android.exoplayer2.demo I/ACodec: codec does not support config operating rate (err -2147483648)
2021-04-11 02:59:23.148 11215-11519/com.google.android.exoplayer2.demo W/ExtendedACodec: Failed to get extension for extradata parameter
2021-04-11 02:59:23.165 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: audioDecoderInitialized [eventTime=0.36, mediaPos=0.00, window=0, period=0, OMX.google.aac.decoder]
2021-04-11 02:59:23.166 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: audioInputFormat [eventTime=0.36, mediaPos=0.00, window=0, period=0, id=2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=1, sample_rate=48000, language=und]
2021-04-11 02:59:23.203 11215-11510/com.google.android.exoplayer2.demo D/AudioTrack: Client defaulted notificationFrames to 7688 for frameCount 15376
2021-04-11 02:59:29.534 11215-11513/com.google.android.exoplayer2.demo D/SurfaceUtils: set up nativeWindow 0x7f769de010 for 1280x720, color 0x7fa30c06, rotation 0, usage 0x20002900
2021-04-11 02:59:29.609 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: videoSize [eventTime=6.80, mediaPos=0.00, window=0, period=0, 1280, 720]
2021-04-11 02:59:29.622 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: renderedFirstFrame [eventTime=6.81, mediaPos=0.00, window=0, period=0, Surface(name=null)/@0xab4c0f1]
2021-04-11 02:59:29.663 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: surfaceSize [eventTime=6.86, mediaPos=0.00, window=0, period=0, 1080, 607]
2021-04-11 02:59:29.703 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: state [eventTime=6.90, mediaPos=0.00, window=0, period=0, READY]
2021-04-11 02:59:29.708 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: isPlaying [eventTime=6.90, mediaPos=0.00, window=0, period=0, true]
2021-04-11 03:00:16.254 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=53.45, mediaPos=46.40, window=0, period=0, false]
2021-04-11 03:00:16.601 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=53.79, mediaPos=46.75, window=0, period=0, true]
2021-04-11 03:00:18.025 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=55.22, mediaPos=48.18, window=0, period=0, false]
2021-04-11 03:00:19.856 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=57.05, mediaPos=50.01, window=0, period=0, true]
2021-04-11 03:00:20.134 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=57.33, mediaPos=50.29, window=0, period=0, false]
2021-04-11 03:00:23.109 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=60.30, mediaPos=53.26, window=0, period=0, true]
2021-04-11 03:00:23.135 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: loading [eventTime=60.33, mediaPos=53.28, window=0, period=0, false]
2021-04-11 03:01:14.501 11215-11510/com.google.android.exoplayer2.demo D/AudioTrack: stop() called with 5044929 frames delivered
2021-04-11 03:01:14.950 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: state [eventTime=112.14, mediaPos=105.10, window=0, period=0, ENDED]
2021-04-11 03:01:15.030 11215-11215/com.google.android.exoplayer2.demo D/EventLogger: isPlaying [eventTime=112.22, mediaPos=105.10, window=0, period=0, false]
2021-04-11 03:02:11.629 11215-11222/com.google.android.exoplayer2.demo I/zygote64: Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()

**Comment by AquilesCanta** [comment] 2021-04-13 11:25
Hey @kim-vde, would you mind taking a look at this? 

Note that using VLC to play this, the first 10 seconds seem corrupted, which seems to suggest media could be malformed. I haven't tried playing on MediaPlayer, though. If MediaPlayer is able to play the file, it might make sense putting some time into diagnosing this. What do you think?

**Comment by shadowor1982a** [comment] 2021-04-13 16:02
@AquilesCanta Thanks for your diagnosing. I find both Chrome on Android and android.widget.VideoView control are able to play the file smoothly. The frame rate of the video is 13.54.  Maybe there is something wrong when handling low frame rate case.

```
    void play() {
        mVideoView = findViewById(R.id.video_view);
        mMediaController = new MediaController(this); 
mVideoView.setVideoPath("http://81.70.232.219/uploads/material_upload/video/2021/material_1613878758.6868_2.21%20%E5%A4%96%E6%95%99%E8%A7%86%E9%A2%91%20Wash%20Hands%20Step2%20Narrative%20-%20Screen.mp4");
        mVideoView.setMediaController(mMediaController);
        mVideoView.seekTo(0);
        mVideoView.requestFocus();
        mVideoView.start();
    }
```

**Comment by kim-vde** [comment] 2021-04-14 17:08
This is a duplicate of #1659.

The video track contains an edit list which requires the video to start at a frame which is not a key frame. As a result, ExoPlayer drops the subsequent frames until it finds a key frame and the video starts late.

**Closed as completed** 2021-04-28 08:35 UTC
Labels: duplicate
