### ISSUE TITLE
How to make a thumbnail of a local video?

### ISSUE THREAD

**Issue by silvershort** [google/ExoPlayer#7285] opened 2020-04-24 06:48 UTC
https://i.stack.imgur.com/pC4rn.jpg

I am trying to implement a seekbar using a thumbnail like the link above.

To implement the function, need to import thumbnail of the video.

How to extract thumbnail images from local video?

**Comment by kim-vde** [comment] 2020-04-24 13:40
This is currently not possible with ExoPlayer. We already have an enhancement for providing a metadata extraction API (#3609).

**Comment by kim-vde** [comment] 2020-04-24 13:42
Duplicate of #3609.

**Closed as completed by kim-vde** 2020-04-24 13:42 UTC
Labels: duplicate, question

**Comment by silvershort** [comment] 2020-04-27 01:03
> Duplicate of #3609.

thank you
