### ISSUE TITLE
How to add new strategy when to reselect the track manually?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#6067] opened 2019-06-20 03:21 UTC
### [REQUIRED] Use case description
When manually switching the track,(e.g. 720p->1080p),  current implementation logic is flushing the already buffered data immediately and maybe destroy-reinit the decoder. It wastes the datas of old track which already buffered.  And the player's state becomes BUFFERING, if at this time, the network becomes bad, maybe player costs more time in BUFFERING state.  

### Proposed solution
When user manually switching the track,(e.g. 720p->1080p), the player not switchs immediately,   just set a flag indicates users want to switch track and record the track which user wants to select , at a proper time (e.g. start to buffer the next ts (HLS) segment which belongs to new select) to switch.  Ensure the data in the existing buffer is not wasted， and the smoothing of the switch can be guaranteed.

**Comment by tonihei** [comment] 2019-06-20 08:01
That's a duplicate of #2250. But you can implement that yourself by extending `AdaptiveTrackSelection` and overriding `canSelectFormat`. In there, you could then limit the available formats dynamically based on the your constraints. Note that the method is called on the playback thread, so you need to do some kind of message passing or synchronization to make that work correctly.

**Closed as completed by tonihei** 2019-06-20 08:02 UTC
Labels: duplicate
