### ISSUE TITLE
SimpleExoPlayer scaling issue on Samsung Galaxy S21 Ultra

### ISSUE THREAD

**Issue by a-blekot** [google/ExoPlayer#9586] opened 2021-10-20 12:35 UTC
We use StyledPlayerView to play RTSP live video stream. 

We configure it like this
```
exoPlayerView.apply {
    resizeMode = AspectRatioFrameLayout.RESIZE_MODE_FILL
    player = createPlayer()
}

private fun StyledPlayerView.createPlayer() =
SimpleExoPlayer.Builder(context)
    .setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)
    .setLoadControl(getLoadControl())
    .build()
    .apply {
        setMediaSource(getMediaSource())
        prepare()
        play()
    }
```

This was working perfectly before we found this issue on Samsung Galaxy S21. Could it be related to Samsung's GameMode?? I attach two screenshots to demonstrate a problem.
I have created an emulator with screen size 6.8' and dimensions: 1440 * 3200 (like Galaxy S21 Ultra) but I could not reproduce it on the emulator.
```
resizeMode = AspectRatioFrameLayout.RESIZE_MODE_FILL
.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)
```

### **The first picture is bad, second is good))**

![bad](https://user-images.githubusercontent.com/66264959/138093564-f8950bc0-9a11-4cbc-86e4-f74a50458939.jpg)
![good](https://user-images.githubusercontent.com/66264959/138093580-50314908-b9a3-4ac8-bbc2-092d74e86062.jpg)

**Comment by tonihei** [comment] 2021-10-22 17:00
Could you provide the example stream and ideally a bugreport taken shortly after the issue happened? If you can, it would also be ideal if you could check whether the issue is reproducible in the ExoPlayer demo app to make sure it's not related to your app code. Alternatively, please provide any other reproduction steps needed, e.g. what kind of surface you are using.

**Comment by a-blekot** [comment] 2021-11-01 09:59
**C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING** - this option does not work for Samsung Galaxy S21 Ultra

We have added **if_samsung** condition in our code =))
```
if (Build.MANUFACTURER == "Samsung" && Build.MODEL == "sm-g998b") {
StyledPlayerView.scaleX = 1.9
 ...
SimpleExoPlayer.Builder(context)
    .setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT)
```

**Comment by a-blekot** [comment] 2021-11-01 12:08
* we are using SurfaceView

**Comment by tonihei** [comment] 2021-11-15 13:53
As far as I can tell, this is probably a known issue where some devices have issues applying `VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING` on `SurfaceViews` (internal ref: b/34159087) when the video is rendered using software decoders. 

I'll close this issue as device-specific as we are not aware of any workarounds we could apply on ExoPlayer side. Feel free to also report this issue to the device manufacturer.

**Closed as completed by tonihei** 2021-11-15 13:53 UTC
Labels: bug: device specific
