### ISSUE TITLE
live dash does not work can u help me?

### ISSUE THREAD

**Issue by qodiriy** [google/ExoPlayer#3571] opened 2017-12-10 15:01 UTC
trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        player.setPlayWhenReady(shouldAutoPlay);

        playerView = (SimpleExoPlayerView) findViewById(R.id.player_view);
        playerView.requestFocus();
        playerView.setPlayer(player);

        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "OnlineTvActivity"), (TransferListener<? super DataSource>) bandwidthMeter);

        DashMediaSource mediaSource = new DashMediaSource(Uri.parse("https://watch.mtrk.uz:443/24/24.stream/manifest.mpd"),
                dataSourceFactory, new DefaultDashChunkSource.Factory(dataSourceFactory), null, null);

        player.prepare(mediaSource);

Source error.
                                                                       com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://watch.mtrk.uz:443/24/24.stream/manifest.mpd
                                                                           at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)

**Comment by ojw28** [comment] 2017-12-10 22:31
The SSL certificate isn't trusted. The important part of the error is:
```
E EventLogger: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```
See [this thread on StackOverflow](https://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection). If you check https://watch.mtrk.uz at https://www.digicert.com/help/, it says:

> SSL Certificate is not trusted
> The certificate is not signed by a trusted authority (checking against Mozilla's root store). If you bought the certificate from a trusted authority, you probably just need to install one or more Intermediate certificates. Contact your certificate provider for assistance doing this for your server platform.

Closing since this is a server configuration issue.

**Closed as completed by ojw28** 2017-12-10 22:31 UTC
Labels: wont fix: infeasible, bad media

**Comment by qodiriy** [comment] 2017-12-10 22:51
Is it possible solve this problem without buy ssl?

**Comment by ojw28** [comment] 2017-12-10 23:19
Unsure. This is a server configuration issue that's not even ExoPlayer specific. You'd be better off asking somewhere like StackOverflow. Good luck!

**Comment by sandersaares** [comment] 2017-12-11 05:27
I suspect the problem is that the server is returning only the leaf certificate instead of the full chain (minus root). This is known to cause issues on Android, even though it generally works on PC. The certificate file the server is configured with should include all intermediate certificates, as well.

**Comment by qodiriy** [comment] 2017-12-11 05:37
But this dash works on https://bitmovin.com/hls-mpeg-dash-test-player/ it means there will be outway
