### ISSUE TITLE
onPlayerError not called when there is a SocketTimeOutError

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#11134] opened 2023-04-25 10:49 UTC
### Bug

Descriptiion: 

When there is an error (SocketTimeout) Using even logger I can see that onLoadError is called but onPlayerError is not called at all.

**Step to reproduce issue:** 

1. Open playback and observer that playback is working
2. Using charles proxy create a rule to force a timeout error
3. Observe that EventLogger is reporting the timeout but onPlayerError callback function is not being called. 

Exoplayer version: 2.18.4
Using drm license: yes
Protocl use: DASH
Content: Live

**Comment by icbaker** [comment] 2023-04-27 11:03
Duplicate of https://github.com/androidx/media/issues/361

Please don't file duplicate issues on both trackers.

**Closed as completed by icbaker** 2023-04-27 11:03 UTC
Labels: duplicate
