### ISSUE TITLE
m3u8 occured an IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Jacko07** [google/ExoPlayer#9228] opened 2021-07-27 09:47 UTC
hi, I have used exoplayer to play hls,m3u8 steam,this  steam occured an IndexOutOfBoundsException when  played for over 4minutes(maybe longer time):
[https://d46c0ebf9ef94053848fdd7b1f2f6b90.mediatailor.eu-central-1.amazonaws.com/v1/master/81bfcafb76f9c947b24574657a9ce7fe14ad75c0/live-prod/9a087b26-8be4-11eb-a7de-bacfe1f83627/0/master.m3u8?uid=97748f06-a7ae-42f5-947a-9b77118303dc&optout=0&vendor=philips&country=GB
](url)

```
Caused by: java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1402)
        at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1384)
        at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextMediaSequenceAndPartIndex(HlsChunkSource.java:723)
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.createMediaChunkIterators(HlsChunkSource.java:587)
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:341)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:708)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:371)
        at com.google.android.exoplayer2.source.MaskingMediaPeriod.continueLoading(MaskingMediaPeriod.java:226)
        at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:221)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:2222)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:2185)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:500)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

these below are my config:

```

    implementation 'com.google.android.exoplayer:exoplayer:2.14.1'
    implementation 'com.google.android.exoplayer:extension-ima:2.14.1'
    implementation 'com.google.android.exoplayer:extension-cronet:2.14.1'

```

```

boolean preferExtensionDecoders = false;
RenderersFactory renderersFactory =
        WLPlayerUtil.buildRenderersFactory(/* context= */ this, preferExtensionDecoders);
DataSource.Factory dataSourceFactory = WLPlayerUtil.getDataSourceFactory(/* context= */ this);
MediaSourceFactory mediaSourceFactory =
        new DefaultMediaSourceFactory(dataSourceFactory)
                .setAdsLoaderProvider(this::getAdsLoader)
                .setAdViewProvider(playerView);

DefaultTrackSelector trackSelector = new DefaultTrackSelector(/* context= */ this);
DefaultTrackSelector.ParametersBuilder builder =
        new DefaultTrackSelector.ParametersBuilder(/* context= */ this);
DefaultTrackSelector.Parameters trackSelectorParameters = builder.build();
trackSelector.setParameters(trackSelectorParameters);

player =
        new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
                .setMediaSourceFactory(mediaSourceFactory)
                .setTrackSelector(trackSelector)
                .build();

```

**Comment by christosts** [comment] 2021-07-27 16:51
I have not been able to reproduce the error using the test content on demo app with r2.14.2 (several playback attempts of 5-10 minutes each). The stack-trace copied on the issue description indicates the playlist had no segments. While I don't exclude the possibility of a bug in the player, I'd start by looking whether the playlists returned by the server were correct.

Please let me know if the error still occurs to you, otherwise I'll close this issue as we can't reproduce.

**Comment by Jacko07** [comment] 2021-07-28 06:07
> I have not been able to reproduce the error using the test content on demo app with r2.14.2 (several playback attempts of 5-10 minutes each). The stack-trace copied on the issue description indicates the playlist had no segments. While I don't exclude the possibility of a bug in the player, I'd start by looking whether the playlists returned by the server were correct.
> 
> Please let me know if the error still occurs to you, otherwise I'll close this issue as we can't reproduce.

please try to play this stream, it's easily reproduce.besides this stream seems to play well on google chrome by use extensions: Native HLS Playback
https://d46c0ebf9ef94053848fdd7b1f2f6b90.mediatailor.eu-central-1.amazonaws.com/v1/master/81bfcafb76f9c947b24574657a9ce7fe14ad75c0/live-prod/5c2d61e8-8be9-11eb-a7de-bacfe1f83627/0/master.m3u8?uid=97748f06-a7ae-42f5-947a-9b77118303dc&optout=0&vendor=philips&country=GB

**Comment by christosts** [comment] 2021-07-28 14:55
I could not reproduce. I am testing on a Pixel 4. The stream played fined for 5+ minutes (2-3 attempts). Note, I am using the latest version which is 2.14.2 at the moment of writing this comment. 

Does the issue occur to you on a specific device and/or older version of ExoPlayer?

**Closed as completed** 2021-08-26 01:04 UTC
Labels: wont fix: not reproducible, closed-by-bot
