### ISSUE TITLE
Playing VAST ads with AdsLoader changes  player buttons' and random layouts' color theme from dark to day mode

### ISSUE THREAD

**Issue by Nephys222** [google/ExoPlayer#10902] opened 2023-01-04 13:44 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

* Pixel 6 running Android 13
* HTC One M9 running Android 7

### Reproducible in the demo app?

No

### Reproduction steps

1. Implement Exoplayer with custom UI player
2. Implement client-side ads following steps from: https://exoplayer.dev/ad-insertion.html
3. Play video in activity/fragment

### Expected result

The media plays and the layout theme does not change

### Actual result

The fragment/activity theme changes from dark mode to Light mode on random layouts including text fields

In logcat this error occurs:

```
2023-01-04 18:38:38.398 22869-23003 JavaBinder              com.test.app.debug              E  !!! FAILED BINDER TRANSACTION !!!  (parcel size = 328)
2023-01-04 18:38:38.398 22869-23003 GmsClient               com.test.app.debug              W  IGmsServiceBroker.getService failed
                                                                                                    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:584)
                                                                                                    	at WE.b(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:288)
                                                                                                    	at com.google.android.gms.common.internal.BaseGmsClient.p(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:53)
                                                                                                    	at BB.run(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:1849)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at Sp0.dispatchMessage(chromium-TrichromeWebViewGoogle6432.apk-stable-495157437:223)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
``` 

### Media

Sample tags from: 
https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by Nephys222** [comment] 2023-01-05 11:46
@marcbaechinger Can you please help on this issue. Do you think it roots to the IMA SDK?

**Comment by icbaker** [comment] 2023-01-05 14:04
There isn't enough detail in your reproduction instructions for us to reproduce the issue. In particular it seems a lot of complexity is likely covered by the phrase "Implement Exoplayer with custom UI player" - especially if you're not able to reproduce the problem in the demo app (since this suggests it's related to your 'custom UI player' rather than something intrinsic in ExoPlayer).

I'm not aware of any theme-related logic in ExoPlayer's IMA extension, so I suspect this is likely to do with either your app or the IMA SDK. If you believe this is related to the IMA SDK, I suggest you report the issue directly to them: https://groups.google.com/g/ima-sdk

**Comment by Nephys222** [comment] 2023-01-05 15:26
@icbaker Thanks for your reply. With phrase 'custom UI player' I mean custom player controls by overriding the Styledplayerview's xml file. It was working normal until I added the client side ad integration.  Ad and content plays normally, but after some time the random layouts (icons', textviews' color change to system theme e.g. from dark mode to light mode).

Is there could be something about registering player controls?

**Comment by icbaker** [comment] 2023-01-05 17:22
Providing a fully custom XML layout to change the look/behaviour of `StyledPlayerView` is not supported I'm afraid. The supported customisation for `StyledPlayerView` is documented in its javadoc. You may well be able to make it work, but we're not able to offer help if you discover issues (like this one).

I'm going to close this issue because I'm afraid there's nothing further we can do without being able to reproduce the problem.

**Closed as completed by icbaker** 2023-01-05 17:22 UTC
Labels: question
