### ISSUE TITLE
Subtitle default position is changed in ExoPlayer v2.17.1 as compare to v2.11.4

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#10552] opened 2022-08-24 17:14 UTC
I am seeing one inconsistency in the subtitle positioning. In v2.11.4, I can see there is padding in the subtitle placement on the screen.

<img src="https://user-images.githubusercontent.com/38206744/186480030-f6dff7a9-18e9-4706-b797-c429b0013ecc.png" width="200" height="400" />

But in v2.17.1, you can check the subtitle placement does not have any bottom padding.
<img src="https://user-images.githubusercontent.com/38206744/186480166-ea2787a0-2021-49cd-ba9d-56588c5f5777.png" width="200" height="400" />

I am attaching the APK for both the version for the ease of verification. Media is location **HLS -> Harold**

https://drive.google.com/drive/folders/1mgA3lQ1rFMlORFk56LMMp1CulF0wNQPP?usp=sharing 

-Thanks

**Comment by icbaker** [comment] 2022-08-24 17:24
Is this WebVTT subtitles? If so, this is likely a duplicate of #7934. See https://github.com/google/ExoPlayer/issues/7934#issuecomment-694063859 for more details.

**Comment by GouravSna** [comment] 2022-08-25 13:27
thanks @icbaker

**Closed as completed** 2022-08-25 13:27 UTC
Labels: duplicate
