### ISSUE TITLE
Caused by android.view.InflateException Binary XML file line #45 exo_player_control_view: Error inflating class ImageButton

### ISSUE THREAD

**Issue by shafqatkamaldin** [google/ExoPlayer#10832] opened 2022-12-05 11:04 UTC
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Devices that getting crash according to firebase statistics

![Screenshot 2022-12-05 at 3 46 10 PM](https://user-images.githubusercontent.com/106583709/205618637-8f5d9b46-7afd-4b3b-ade9-82e160da0234.png)

### Devices that do not reproduce the issue

Pixel 2
Pixel 3 
Vivo 1933
Opp A54

### Reproducible in the demo app?

No

### Reproduction steps

Hello,

We are unable to reproduce the issue but we are getting too much crashes in firebase crashlytics. 

### Expected result

Video should be played properly like other devices playing the video.

### Actual result

Here is all crash statistics every user getting crash like this. I just hide the package id for security reason so please ignore red mark point in below screenshot.

![Screenshot 2022-12-05 at 3 49 24 PM](https://user-images.githubusercontent.com/106583709/205621087-eeda8917-de80-4499-ac60-3bdcc7ab1e3e.png)

I want to tell you I thought may be issue in 2.18.2 exoplayer version because its deprecated now. SO i decided to move on media3 after implementing media 3 still i am getting same issue in media 3 library. 

Its mean something is wrong in your library even exoplayer or even media3 you have to check it whats the going wrong. 10% Users are getting same crash according to Firebase Crashlytics. And 10% is too much for us we cant afford these crashes anymore. 

This is our last attempt to fix this issue if still not fix then we have to change the media player.

### Media

You can use any m3u8 link for creating this issue all specific devices that i have mentioned above.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment] 2022-12-05 11:39
Thanks for reporting. It's worth to migrate to `Media3`  as exoplayer will be discontinued at some point. However, in this case this shouldn't be the issue. 

> We are unable to reproduce the issue but we are getting too much crashes in firebase crashlytics.

Yeah, this is difficult to investigate on our end as well if it's not possible to repro. This works on our demo app. Looks like the `InflateException` you are seeing is caused by resources not being found.  This is often the case when an app is being downloaded by users and some split APKS are missing. 

This stackoverflow article gives a good overview and also has advice on how to detect this: https://stackoverflow.com/questions/50471888/android-app-bundle-introduces-resource-not-found-crash-in-android-app

I don't think we can do much on the library side.

**Comment by shafqatkamaldin** [comment] 2022-12-05 12:01
@marcbaechinger Thank for your reply and i hope you are doing well.

I want to tell you we have migrated into media3 everything is working perfectly but still getting above issue. I got 1000 crashes out of 10000 active users. Please tell me what is the best solution to fix this problem. How we can rid from this issue. 

This is very important for us because we have implemented media3 and we totally depended on you This is very hard to change the media player for rightnow. Please give us a best solution to fix this problem. And explain in steps through which we can fix this problem. 10% crashes too much for us. 

What do you think if we publish APK into googleplay store not AAB. Will this solution work or not?

Regards

**Comment by icbaker** [comment] 2022-12-05 14:50
This is a duplicate of https://github.com/google/ExoPlayer/issues/10409

Closing because as @marcbaechinger has explained and linked above, it's a problem related to your app build & distribution (likely users sideloading rather than via Play Store), not this library - there's nothing we can do to resolve this by changes to this library.

**Closed as completed by icbaker** 2022-12-05 14:50 UTC
Labels: duplicate

**Comment by shafqatkamaldin** [comment] 2022-12-05 14:54
Hello,
 
I have shared all statistics. You must understand what problem i am asking. Regarding siteloading we have implemented App Check Token. This is mean this app will not work if any user installed this app except playstore. 

You must have to know what is the purpose of play integrity. Closing the bug its not a solution. You can close this bug to make your self comfortable. But This is bug if you dont want to understand this is your concern. 

I have shared my complete feedback. Thank you
