### ISSUE TITLE
Low latency player start up

### ISSUE THREAD

**Issue by tbeyou** [google/ExoPlayer#10319] opened 2022-06-06 21:31 UTC
Hi Explayer team,

I am trying to create a low latency player for live streaming with a custom `DataSource` with a `ProgressiveMediaSource`.
The stream is an audio and video MPEG-TS (so it uses `TSExtractor`).

Exoplayer already reads the stream.

Unfortunately,  I notice that Exoplayer reads the first frame, *random delay (0 to 1s)*, then it plays the stream. As I want my live stream to be low latency, I expect to reduce this *random delay* as much as possible.

I don't get where this *random delay* comes from. Could you give me hint about the delay source? The `ProgressiveMediaPeriod` loader? The `TSExtractor`? Is there a way I can reduce this *random delay*?

Example:
In the following video, the time counter is stuck at 24:00:00 before resuming the stream. I would expect it directly resume the stream.

https://user-images.githubusercontent.com/48099985/172252286-e6e06b8f-17fc-4f3e-bc7b-8020dc8d3e7f.mp4

Thanks :pray:

**Comment by tonihei** [comment] 2022-06-09 09:44
This looks like working as intended because, by default, the player waits until it has 2.5 seconds of buffered media before starting playback. The first frame is still shown as soon as it's decoded.

You can try to reduce the value (even down to 0), in `DefaultLoadControl`:
```
Player player =
    new ExoPlayer.Builder(context)
        .setLoadControl(
            new DefaultLoadControl.Builder()
                .setBufferDurationsMs(
                    DEFAULT_MIN_BUFFER_MS,
                    DEFAULT_MAX_BUFFER_MS,
                    /* bufferForPlaybackMs= */ 0,
                    /* bufferForPlaybackAfterRebufferMs= */ 0)
                .build())
        .build();
```

Note that this buffer is meant to reduce the chance of rebuffers immediately after starting playback. So reducing `bufferForPlaybackMs` could result in an increased number of rebuffers. 

> create a low latency player for live streaming

It looks like you are trying to directly play a live TS stream. You will get a better live media streaming experience if you use chunked playback with either DASH or HLS (see this [blog post](https://medium.com/google-exoplayer/low-latency-live-streaming-with-exoplayer-8552d5841060)). If you do that and configure the stream to be low-latency, the player will also automatically adjust the live offset to play as close as possible to your target offset without changing the `DefaultLoadControl` parameters.

**Comment by tbeyou** [comment] 2022-06-09 20:03
Thanks for your great answer.

> You can try to reduce the value (even down to 0), in `DefaultLoadControl`

I already did that (I set all setBufferDurationMs parameters to 0 - not sure it is appropriate though). It reduces latency to ~1s. Unfortunately it is not low enough for my usage.

> Note that this buffer is meant to reduce the chance of rebuffers immediately after starting playback. So reducing `bufferForPlaybackMs` could result in an increased number of rebuffers.

As it is already playing smoothly, I don't think rebuffering happens here.

> It looks like you are trying to directly play a live TS stream. You will get a better live media streaming experience if you use chunked playback with either DASH or HLS (see this [blog post](https://medium.com/google-exoplayer/low-latency-live-streaming-with-exoplayer-8552d5841060)).

I am trying to reach a latency far under 1s aka ultra low latency. Unfortunately, DASH and LL-HLS can't guaranty such latency. 

> If you do that and configure the stream to be low-latency, the player will also automatically adjust the live offset to play as close as possible to your target offset without changing the `DefaultLoadControl` parameters.

This is what I am trying to achieve.
I am OK with the fact of creating a specific `MediaSource` or `MediaPeriod` if needed.
I also try to force the `TSExtractor` to HLS mode. Is this what your are talking about? Could you point me to this parts of code?

I notice that the latency tends to be a bit random for the same stream... Do you see a reason for this?

Best regards :)

**Comment by tonihei** [comment] 2022-06-15 07:59
Despite instructing the player to start immediately, there will still be some delay in parsing the file, extracting data, setting up a decoder, etc. I don't usually expect this to take a full second though. It could also be related to your TS stream itself. have you tried one of the flags suggested in https://exoplayer.dev/troubleshooting.html#why-do-some-mpeg-ts-files-fail-to-play?

 > I am trying to reach a latency far under 1s aka ultra low latency. Unfortunately, DASH and LL-HLS can't guaranty such latency.

They are definitely capable of sub-second latency if the network is fast enough and the stream is setup correctly. If you are trying to use low-latency playback adjustments for a progressive TS stream, you'd need to make two adjustments to the `Timeline` published by the `MediaSource` (untested):
  1. The `Timeline.Window` needs to define a `liveConfiguration` with a `targetOffsetMs != C.TIME_UNSET`. This value indicates the intended live offset you'd like the player to achieve. You can theoretically set this to 0 and let the player get as close to the live edge as it can (the logic will only get closer to the live edge if it deems it safe to do so).
  2. The `Timeline.Window` also needs to set `elapsedRealtimeEpochOffsetMs` to indicate the offset between the current system time and the media time (relative to the Unix epoch), see value Javadoc. This is needed so that the player can figure out how far away from the live edge it is currently playing.

You can modify the Timeline by wrapping the `ProgressiveMediaSource`. The `LoopingMediaSource` is a simple example of how such a CompositeMediaSource works. It's changing the timeline in other ways than you need but it does the same wrapping approach that you need:
 - pass the child media source to the constructor
 - override `prepareSourceInternal` and call `prepareChildSource(/* id= */ null, childMediaSource)`
 - implement `onChildSourceInfoRefreshed(Void id, MediaSource mediaSource, Timeline timeline)` and call 
 `refreshSourceInfo(new MyWrapperTimeline(timeline))` while `MyWrapperTimeline` is making the window adjustments. You can use `ForwardingTimeline` to implement this wrapper.
 - delegate `getMediaItem`, `createPeriod` and `releasePeriod` to the child media source 1:1

**Comment by tonihei** [comment] 2022-06-17 13:23
Closing this as the initial question was answered and we can't provide more detailed customization advice than already given above.

**Closed as completed by tonihei** 2022-06-17 13:23 UTC
Labels: question
