### ISSUE TITLE
How to show vtt subtitles from link in m3U8 HLS stream

### ISSUE THREAD

**Issue by jazimm** [google/ExoPlayer#2649] opened 2017-04-04 19:59 UTC
### Issue description
Not able to find procedure for displaying vtt subtitles using Exoplayer v2.3. Link to vtt file is included in m3u8 link, so the link to the subtitle file is unknown and cannot be added using the method mentioned in issue #2017 where the link is included as a parameter in the SingleSampleMediaSource object. In the demo app the subtitle can be turned on in the TrackSelectionHelper class by using the selector.setSelectionOverride method and using the FixedTrackSelection.Factory() as a parameter in SelectionOverride object but I'm not sure if this is the appropriate method to just turn on subtitles in an HLS stream or if there is a better procedure as I'm not sure this method still utilizes adaptive streaming for the video?

### Version of ExoPlayer being used
version 2.3.1

### Device(s) and version(s) of Android being used
Nexus 5 running Android 6.0.1

**Comment by AquilesCanta** [comment] 2017-04-05 10:55
I am a bit confused about what the issue is. 
> Link to vtt file is included in m3u8 link

Assuming the m3u8 file you mention is a master playlist, there should be no actual vtt files referenced there, but rather a media playlist, which in turn points to the vtt files. You can have a look at HLS media samples with VTT subtitles in the demo app.
>In the demo app the subtitle can be turned on in the TrackSelectionHelper class by using the selector.setSelectionOverride method

Selection overrides are an alternative `DefaultTrackSelector` parameters. Subtitles should be enabled by default in the demo app, generally.
> I'm not sure this method still utilizes adaptive streaming for the video

As long as you don't provide overrides for video selections, video should remain adaptive.

You also ignored some of the elements from the issue template, the media would have been particularly helpful to understand your issue.

**Comment by AquilesCanta** [comment] 2017-04-05 14:29
Just a clarification, which @ojw28 pointed out: The DefaultTrackSelector only enables text tracks by default when they declare the preferred language (as defined by the selection parameters), when they are marked as DEFAULT, or as FORCED. This is the case of Apple 16x9 basic stream, so you can look into this in the demo app. But keep it in mind in case your media does not meet these criteria.

**Comment by jazimm** [comment] 2017-04-05 20:16
Thanks for the reply. Yes you are correct there are not vtt files referenced in the master m3U8 file, just the URI pointing to the files. Subtitles "Default" and "FORCED" it set to NO as we only wish to turn them on programmatically  if the user has captions turned on in the device settings. Otherwise we don't want to display captions for users who don't require them. We also plan to have other languages available for captions in the future and have users in many countries so we don't wish to default to english. So with this in mind, what would the best method be of turning on captions programmatically if DEFAULT=NO in the m3u8 file if using an override is not recommended? Also I have not added the link to the m3U8 in the post on purpose but will email it to you for your review. Thanks again.

**Comment by AquilesCanta** [comment] 2017-04-06 09:04
In that case, probably something like:
```
// To keep any existing parameters we modify the current ones.
DefaultTrackSelector.Parameters selectionParameters = defaultTrackSelector.getParameters();
// The language string format is defined in RFC 5646.
defaultTrackSelector.setParameters(selectionParameters.withPreferredTextLanguage("spa"));
```
This should be made effective immediately. I hope this helps.

**Closed as completed by AquilesCanta** 2017-04-06 09:04 UTC

**Comment by ojw28** [comment] 2017-04-06 10:45
To answer the original question: Using selection overrides is absolutely fine, and is the recommended approach if you want to select a specific track.

The parameters based approach @AquilesCanta outlines is good/better if you want to select a track based on rules (e.g. "I want to enable the Spanish track" in the example above). It's simpler because you don't have to look at the details of each track and its format. You can also configure the rule before you know what the tracks are.

**Comment by jazimm** [comment] 2017-04-06 19:45
Thanks guys, that's exactly what I needed. Would be great to include that in the demo as well. Much appreciated.
