### ISSUE TITLE
DASH live stream does not play correctly on Android 11 emulator

### ISSUE THREAD

**Issue by Stonos** [google/ExoPlayer#7903] opened 2020-09-14 13:51 UTC
### [REQUIRED] Issue description
When trying to watch a DASH live stream on an Android 11 emulator the video appears to be playing too fast. Eventually, it reaches too close to the live edge which causes constant buffering since it plays faster than realtime.

You can see an example here:
https://drive.google.com/file/d/1l6E6dTVbE2rOfQc9XN05YuGH4p2Vn3lc

Notice how fast the seconds change, and how choppy the playback is. This does not happen on VODs or an Android 10 emulator.

### [REQUIRED] Reproduction steps
Play a live stream.

### [REQUIRED] Link to test content
```json
{
  "name": "Live stream test",
  "uri": "https://live.unified-streaming.com/scte35/scte35.isml/.mpd?dvr_window_length=3600",
  "extension": "mpd"
}
```

### [REQUIRED] A full bug report captured from the device
[bugreport-sdk_gphone_x86-RSR1.200819.001.A1-2020-09-14-16-43-19.zip](https://github.com/google/ExoPlayer/files/5218831/bugreport-sdk_gphone_x86-RSR1.200819.001.A1-2020-09-14-16-43-19.zip)

### [REQUIRED] Version of ExoPlayer being used
2.12.0

### [REQUIRED] Device(s) and version(s) of Android being used
Android Emulator v30.1.3-6821655
Nexus 5X with Android 11 Google Play Intel x86 Atom System Image

Host system specs:
Windows 10
Intel 5820K
NVIDIA GTX 970

**Comment by icbaker** [comment] 2020-09-14 17:26
Thanks for the report, and the test content.

I can reproduce what you describe with a Nexus 5X emulator running Android 11. I also tried with a Pixel 4 emulator running Android 11 and see the same behaviour.

A Pixel 3 emulator running Android 10 doesn't behave the same (it seems to play at 'normal' speed and never catches up/rebuffers).

Assigning to @tonihei for further investigation.

**Comment by tonihei** [comment] 2020-09-15 11:16
I can reproduce the issue and it seems to be caused by a malfunctioning `MediaCodec` version (`OMX.android.goldfish.h264.decoder`) that is part of the emulator system image. I'll try to file an issue internally to get this fixed [internal ref: b/168593698].

**Comment by tonihei** [comment] 2020-09-15 16:57
If you want, it seems you can workaround this problem for now by using one of the following options:
 - Remove the `HardwareDecoder=on` in `system-images/android-30/google_apis_playstore/x86/advancedFeatures.ini`
 - Launch emulator with `-feature -HardwareDecoder`

**Comment by tonihei** [comment] 2021-03-09 14:32
The emulator issue above was fixed and should be available in some upcoming version of it.

**Closed as completed by tonihei** 2021-03-09 14:32 UTC
Labels: bug: in platform
