### ISSUE TITLE
sending message to a Handler on a dead thread when extracting metadata.

### ISSUE THREAD

**Issue by Empressia** [google/ExoPlayer#9108] opened 2021-06-24 12:17 UTC
When I extracted metadata from an audio file in an asynchronous thread, I got the following exceptions (warning).

* code sample (called in an  asynchronous thread)

    > ListenableFuture<TrackGroupArray> future = MetadataRetriever.retrieveMetadata(context, mediaItem);

* exception 1

    >     java.lang.IllegalStateException: Handler (android.os.Handler) {b98d7d2} sending message to a Handler on a dead thread
    >         at android.os.MessageQueue.enqueueMessage(MessageQueue.java:563)
    >         at android.os.Handler.enqueueMessage(Handler.java:778)
    >         at android.os.Handler.sendMessageAtTime(Handler.java:727)
    >         at android.os.Handler.sendMessageDelayed(Handler.java:697)
    >         at android.os.Handler.post(Handler.java:427)
    >         at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1054)
    >         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
    >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    >         at java.lang.Thread.run(Thread.java:923)

* exception 2

    >     java.lang.IllegalStateException: Handler (android.os.Handler) {35c9495} sending message to a Handler on a dead thread
    >         at android.os.MessageQueue.enqueueMessage(MessageQueue.java:563)
    >         at android.os.Handler.enqueueMessage(Handler.java:778)
    >         at android.os.Handler.sendMessageAtTime(Handler.java:727)
    >         at android.os.Handler.sendMessageDelayed(Handler.java:697)
    >         at android.os.Handler.post(Handler.java:427)
    >         at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.onUpstreamFormatChanged(ProgressiveMediaPeriod.java:706)
    >         at com.google.android.exoplayer2.source.SampleQueue.format(SampleQueue.java:571)
    >         at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readInternal(Mp3Extractor.java:251)
    >         at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:216)
    >         at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
    >         at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049)
    >         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
    >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    >         at java.lang.Thread.run(Thread.java:923)

I searched for the issues and found a similar issue.
https://github.com/google/ExoPlayer/issues/426

But it was calling ExoPlayer on ui thread.

Can I avoid warnings in this case?

**Comment by icbaker** [comment] 2021-06-24 16:09
You can safely ignore those warnings (for the same reason explained in the comments of #426).

I suspect they're happening because the `Loader` inside `ProgressiveMediaPeriod` is released asynchronously here:
https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/core/src/main/java/com/google/android/exoplayer2/source/ProgressiveMediaPeriod.java#L219

But `MetadataRetriever` quits the thread used to instantiate the periods & sources (and back `ProgressiveMediaPeriod#handler`) immediately after releasing the period (at which point the Loader probably won't have finished releasing yet): https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/core/src/main/java/com/google/android/exoplayer2/MetadataRetriever.java#L163-L169

`ProgressiveMediaPeriod#onLoaderReleased` (called when the loader finishes releasing) doesn't pass on the release message in any way that we could wait for:
https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/core/src/main/java/com/google/android/exoplayer2/source/ProgressiveMediaPeriod.java#L225-L231

Assigning to @Samrobbo to take a look and see if there's an easy way to avoid these logs, otherwise I suspect we'll ask you to just keep ignoring them, they are fundamentally harmless.

**Comment by Samrobbo** [comment] 2021-06-25 11:15
Despite my work on Metadata, @kim-vde is the go to guru for `MetadataRetriever`, especially with `ListenableFuture`s and async operations. I'll reassign to her in case she wants to do anything about the logs, but ultimately I think ignoring them is fair.

**Comment by kim-vde** [comment] 2021-07-01 15:56
+1 to ignoring these for now. As stated in #426, it is unfortunate that the platform prints these logs as they can be the result of an intended behaviour.

**Closed as completed by kim-vde** 2021-07-01 15:56 UTC
Labels: question
