### ISSUE TITLE
Offline download speed

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#5319] opened 2018-12-28 07:27 UTC
I am using offline download feature like in the demo app.But the download speed is very slow.I have checked in a 4g network.Is there a way i can increase the speed of downloading

**Comment by AquilesCanta** [comment] 2018-12-28 16:19
Is this question related to ExoPlayer? Do you think the downloader is not using all the available bandwidth? If so, can you provide something that indicates this is happening? There is not enough information here for us to help.

**Comment by ParthiviPokuri** [comment] 2018-12-31 04:21
Exoplayer downloading chunks sequentially, so that it is taking more time to download the content. Is there any way to use multiple threads to download the content?
I think the similar feature  already requested https://github.com/google/ExoPlayer/issues/4273

**Comment by ojw28** [comment] 2019-01-02 11:44
Marking as a duplicate of https://github.com/google/ExoPlayer/issues/4273.

**Closed as completed by ojw28** 2019-01-02 11:44 UTC
Labels: duplicate
