### ISSUE TITLE
Getting event with schemeIdUri='urn:mpeg:dash:event:callback:2015': no HTTP Get to messageData URL

### ISSUE THREAD

**Issue by chihebbn** [google/ExoPlayer#5258] opened 2018-12-14 14:51 UTC
### Issue description
According to ISO/IEC 23009-1/A3:2016 the EventStream with urn:mpeg:dash:event:callback:2015: part 5.10.4.X.1: the player should send an HTTP GET request to the URL indicated by the messageData and ignore the HTTP response (which should be 2xx).
Example: for this URL: "http://vm2.dashif.org/livesim/periods_60/mpdcallback_30/testpic_2s/Manifest.mpd", the EXOPlayer should ask for the messageData ("https://vm2.dashif.org/livesim/mpdcallback/") at the begining of the period in order to inform the server of one tracking event. This function seems not yet been supported by EXOPlayer (even version r2.9.2). (no HTTP GET request was sent to the URL indicated by messageData).
Adding this functionality to EXOPlayer is mandatory to be in conformity with ISO/IEC 23009-1/A3:2016.

### Reproduction steps
tested with this link http://vm2.dashif.org/livesim/periods_60/mpdcallback_30/testpic_2s/Manifest.mpd.
I have also tested with nother local mpd stored in my Apache server, using messageData that indicates the url of a file stored in my apache server. There is no HTTP Get to this file (verification from the apache access logs).

### Link to test content
http://vm2.dashif.org/livesim/periods_60/mpdcallback_30/testpic_2s/Manifest.mpd

### Version of ExoPlayer being used
r2.9.2

### Device(s) and version(s) of Android being used
Samsung SM-T819 (Android 7.0, API 24).

**Comment by ojw28** [comment] 2018-12-14 18:08
That manifest doesn't look correct to me. Shouldn't `messageData` be defined on an `Event` inside the `EventStream`, rather than being defined directly on the `EventStream` itself?

**Comment by ojw28** [comment] 2018-12-14 18:13
Note that if the manifest were structured as I describe above, I think the event would be delivered to `MetadataOutput`s registered with `SimpleExoPlayer.addMetadataOutput`. Application code can therefore register a metadata output and make the desired GET request.

**Comment by chihebbn** [comment] 2018-12-14 18:17
What I tested locally is in conformity with DASH ISO/IEC 23009-1/A3:2016: I put the messageData inside an Event of EventStream. I have always no HTTP Get request !

**Comment by ojw28** [comment] 2018-12-14 18:20
As already noted above:
1. I don't think the manifest you've linked to is correct. Perhaps yours is, but you haven't linked to that!
1. We don't make the HTTP GET request automatically. Application code can do that by registering as a metadata output.

**Comment by chihebbn** [comment] 2018-12-14 18:40
1. yes I should rather give you the mpd that I've used for my tests.
2. I did not see any HTTP GET request to the url defined in messageData during video playback at any time.  

I just want to verify if schemeIdUri 'urn:mpeg:dash:event:callback:2015' is already supported by ExoPlayer or not, and if it has been tested before.
Thanks,

(I will give you the mpd that I've used locally for my tests once I will be back in my office next week)

**Comment by ojw28** [comment] 2018-12-14 18:43
Please read my second point in the response above carefully, since it already answers the question you keep asking. Thanks.

**Comment by ojw28** [comment] 2018-12-19 15:39
Closing because I think this is working as intended. As described above, you should be able to listen for the events using `SimpleExoPlayer.addMetadataOutput`. You can register a simple `MetadataOutput` using this method, whose implementation should fire the HTTP GET requests that you want to occur.

As an aside, the sample manifest provided was confirmed has being incorrect by the DASH-IF people.

**Closed as completed by ojw28** 2018-12-19 15:39 UTC
