### ISSUE TITLE
seekTo and duration of mp3 is incorrect with exoplayer2.9.6

### ISSUE THREAD

**Issue by cr1944** [google/ExoPlayer#5982] opened 2019-06-02 07:13 UTC
### [REQUIRED] Issue description
When I use exoplayer 2.5.4 for play mp3, everything works correct. However, after I upgrade exoplayer to 2.9.6, seekTo always slower for about 1 second, and the duration is not correct too.(compared to playing in Chrome)
### [REQUIRED] Reproduction steps
1) Use ExoPlayer Demo and Chrome to play the mp3 below.
The duration in Chrome is "4:53", but is "4:55" in ExoPlayer Demo.
2) Try seekTo "4:11" and listen, the voice from demo app come out slower than Chrome

### [REQUIRED] Link to test content
here is the mp3 for test:
https://ra.namibox.com/tina/static/d/tape5a/006002_%E8%8B%B1%E8%AF%AD%EF%BC%88%E6%B9%98%E5%B0%91%E7%89%88%EF%BC%89/hiq/000001_Unit%201_What%20does%20she%20look%20like.mp3?20160630100005

### [REQUIRED] A full bug report captured from the device
NONE

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
every device

**Comment by AquilesCanta** [comment] 2019-06-05 11:17
Regarding 1. Not much we can do, since the file doesn't contain any metadata that ExoPlayer can use for seeking and knowing the duration. I can only suggest you either remux the content into a more seeking-friendly container format, or you add seeking metadata to the file.

Regarding 2, could you please try the dev-branch (and possibly the latest release branch) and let me know if you can reproduce the issue? I couldn't find anything wrong in my device, so I suspect this might have been fixed fixed in a later version.

**Comment by AquilesCanta** [comment] 2019-06-19 19:01
Closing due to lack of activity.

**Closed as completed by AquilesCanta** 2019-06-19 19:01 UTC
Labels: need more info, bad media
