### ISSUE TITLE
Can't launch content playback again after error during playback

### ISSUE THREAD

**Issue by t-ester** [google/ExoPlayer#3490] opened 2017-11-22 13:20 UTC
We're developing Live DASH Playback application with ExoPlayer.
Now we're facing the following problem:

### Issue description
Can't relaunch the same content playback after it failed once.
Need to restart application to make it work.

### Reproduction steps
1. start live DASH content playback.
2. wait about 30min for any error: 
one of server related:
```
- Top bit not zero: -1
- java.io.EOFException
- Skipping atom with length > 2147483647 (unsupported).
```
3. Close activity containing SimpleExoPlayer object (SimpleExoPlayer#release is called)
4. Launch the same content
- Current result:
One of the above errors appear again and again (we are not able to play the content again)
- Recovery:
Kill the whole application, after restart, playback starts again

We did not implement any cache. Is there any default ExoPlayer (or system) cache that should be cleared to prevent such errors?

Only clue I found is that after crash it throws errors like:
```
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
```
when we try to launch the movie again. But i'm not sure if its related.

### Link to test content
Due to licence issues we can't provide our contents.

### Version of ExoPlayer being used
2.5.3

### Device(s) and version(s) of Android being used
Tested on multiple devices with different OS versions

**Comment by ojw28** [comment] 2017-11-22 16:34
Sounds like you are not creating a new `MediaSource` instance and re-preparing the player after failure. You need to do this.

**Comment by t-ester** [comment] 2017-11-22 21:01
After the failure the whole activity is closed and so the player instance (SimpleExoPlayer) is released. When going back to the activity new player instance is created but the error still occures. Wouldn't MediaSource item be recreated in this situation?

**Comment by ojw28** [comment] 2017-11-22 21:02
It's your code that will be creating the `MediaSource`. So it depends on what your code does.

**Comment by t-ester** [comment] 2017-11-23 08:05
Every time I start new playback we create new activity and new player instance:
```
private SimpleExoPlayer player;
...
player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector);
MediaSource mediaSource = mediaSources.length == 1 ? mediaSources[0] : new ConcatenatingMediaSource(mediaSources);
player.prepare(mediaSource, !haveResumePosition, false);
```

And after each failure we call this:
`player.release();`

This code is basically a copy of demo application. There was nothing extra done on the player or on the media source.
I assume that `player.release();` calls `releaseSource` on each mediaSource object.
But just to be sure I will call extra `releaseSource` on MediaSource after failure, before closing activity.
We'll see...

**Comment by ojw28** [comment] 2017-11-23 12:30
Is mediaSources[0] a new `MediaSource` instance each time? If the code is a copy of the demo application, can you reproduce the same issue in the demo application? If so then how? If not, that suggests there's a difference.

**Comment by t-ester** [comment] 2017-11-23 13:01
`mediaSource.release()` didn't help.

`mediaSource[0]` is new array created each time activity containing the player launches.
It is created with `MediaSource `objects are created with `MediaSourceHelper#buildMediaSource` method, based on uri.

I will try to reproduce the same behavior on ExoPlayer demo. There is a lot changes to the code (regarding soundtracks/subtitles logic and dialog or ui) but the main functions like launching and releasing the player are the same like in demo.
I've also created my own version of `HttpMediaDrmCallback` with only difference that `executeKeyRequest` is parsing array of bytes as json object to get "license" string.

**Comment by ojw28** [comment] 2017-11-23 13:08
`MediaSourceHelper` is not part of ExoPlayer, so we have no idea what it does. Please ensure it creates a new `MediaSource` each time it's used.

**Comment by t-ester** [comment] 2017-11-23 13:20
True, `MediaSourceHelper` is our code.
But it's basically wrapper to couple functions from example so `buildMediaSource` behaves the same as ExoPlayer demo - Yes it creates new `MediaSource` each time.

**Comment by ojw28** [comment] 2017-11-28 19:24
* There's no way for us to reproduce this with the information provided, and neither is there a bug report captured shortly after encountering the issue (with `adb bugreport`, as requested in the issue template). We need at least one of these to make further progress.
* It looks like the initial playback failure is caused by incorrectly packaged media, although again without any further information it's hard to be more specific.

**Comment by ojw28** [comment] 2018-01-02 18:32
Closing due to lack of required information.

**Closed as completed by ojw28** 2018-01-02 18:32 UTC
Labels: question, need more info
