### ISSUE TITLE
When playing Dash Content with empty CEA608 crash is observed

### ISSUE THREAD

**Issue by himaswetha** [google/ExoPlayer#5800] opened 2019-04-24 18:19 UTC
```
04-24 23:47:27.039 6995-7152/com.ericsson.MediaFirstUC.tv E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.updatePeriodTrackSelection(ExoPlayerImplInternal.java:1662)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.reselectTracksInternal(ExoPlayerImplInternal.java:919)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:386)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
04-24 23:47:27.040 6995-7149/com.ericsson.MediaFirstUC.tv E/UCExoEventHandler: onPlayerError
04-24 23:47:27.041 6995-7162/com.ericsson.MediaFirstUC.tv V/ACodec: [OMX.broadcom.video_decoder.secure] Now Executing->Idle
04-24 23:47:27.042 6995-7149/com.ericsson.MediaFirstUC.tv E/UCExoPlayer: handlePlayerError
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:408)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.updatePeriodTrackSelection(ExoPlayerImplInternal.java:1662)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.reselectTracksInternal(ExoPlayerImplInternal.java:919)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:386)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by himaswetha** [comment] 2019-04-24 18:19
Can you explain me when this crash will come?

**Comment by himaswetha** [comment] 2019-04-24 18:22
We are using r2.5.4 version of exoplayer and how i can add the fix for this version only? also i tried by backporting changes related to disassociateNoSampleRenderersWithEmptySampleStream and associateNoSampleRenderersWithEmptySampleStream functions also but its not working. Please let me know why this crash will come? and why the assertion check is failing from the below code                        
      hasEnabledTracks = false;
      for (int i = 0; i < sampleStreams.length; i++) {
        if (sampleStreams[i] != null) {
          Assertions.checkState(trackSelections.get(i) != null);
          hasEnabledTracks = true;
        } else {
          Assertions.checkState(trackSelections.get(i) == null); // its failing here
        }
      }

**Comment by himaswetha** [comment] 2019-04-25 06:46
Can any please check this issue?

**Comment by himaswetha** [comment] 2019-04-25 09:29
while adding  trackselections we are not checking for null or not but Assertions.checkState(trackSelections.get(i) == null) is added during updatePeriodTrackSelection() why it is so?


 /**
   * @param trackSelections The selections. Must not be null, but may contain null elements.
   */
  public TrackSelectionArray(TrackSelection... trackSelections) {
    this.trackSelections = trackSelections;
    this.length = trackSelections.length;
  }

**Comment by ojw28** [comment] 2019-04-25 14:41
If the issue is fixed in a more recent release then the solution is for you to upgrade. It's not scalable for us to provide advice on how to backport individual fixes. If the issue is still present in the latest release, please properly fill out the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=), including all of the required information. Thanks!

**Comment by ojw28** [comment] 2019-05-02 12:10
Closing because there's no actionable information here. If the stream doesn't work in the latest release, please properly fill out the issue template, including all of the required information, and we'll re-open the issue. Thanks!

**Closed as completed by ojw28** 2019-05-02 12:10 UTC
Labels: need more info
