### ISSUE TITLE
How to pass FLAG_ALLOW_NON_IDR_KEYFRAMES in HLS

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#2979] opened 2017-06-21 13:00 UTC
When using ExtractorMediaSource, I can pass a customized DefaultExtractsFactory and set FLAG_ALLOW_NON_IDR_KEYFRAMES on it. When but using HlsMediaSource, I don't see a way to achieve the same.

**Comment by AquilesCanta** [comment] 2017-06-21 13:11
This is a duplicate of #2833.

**Closed as completed by AquilesCanta** 2017-06-21 13:11 UTC
