### ISSUE TITLE
Frame drops in the exoplayer 2.11.6

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#7547] opened 2020-06-26 08:44 UTC
### [REQUIRED] Issue description
Continous frame drops in the Exoplayer and video gets stucks

droppedFrames [eventTime=11.21, mediaPos=3.60, window=0, period=0, 50]
droppedFrames [eventTime=28.00, mediaPos=20.40, window=0, period=0, 50]
droppedFrames [eventTime=30.40, mediaPos=22.81, window=0, period=0, 50]
droppedFrames [eventTime=38.46, mediaPos=30.85, window=0, period=0, 50]
droppedFrames [eventTime=56.25, mediaPos=48.64, window=0, period=0, 50]
droppedFrames [eventTime=67.96, mediaPos=60.36, window=0, period=0, 50]
droppedFrames [eventTime=77.41, mediaPos=69.81, window=0, period=0, 50]
droppedFrames [eventTime=79.75, mediaPos=72.15, window=0, period=0, 50]
droppedFrames [eventTime=82.17, mediaPos=74.57, window=0, period=0, 50]
droppedFrames [eventTime=84.03, mediaPos=76.43, window=0, period=0, 50]
droppedFrames [eventTime=86.18, mediaPos=78.57, window=0, period=0, 50]
droppedFrames [eventTime=88.12, mediaPos=80.52, window=0, period=0, 50]
droppedFrames [eventTime=90.34, mediaPos=82.73, window=0, period=0, 50]
droppedFrames [eventTime=91.86, mediaPos=84.26, window=0, period=0, 52]
audioTrackUnderrun [eventTime=92.28, mediaPos=84.36, window=0, period=0, 76960, 400, 401]]
audioTrackUnderrun [eventTime=94.69, mediaPos=86.67, window=0, period=0, 76960, 400, 394]]

### [REQUIRED] Reproduction steps
While playing the secure dash video

### [REQUIRED] Link to test content
I share the sample test Apk link, code and video URLs to your mail

### [REQUIRED] Version of ExoPlayer being used
**Exoplayer -  2.11.6**

### [REQUIRED] Device(s) and version(s) of Android being used
Sony E6533 and version 7.1.1

**Comment by icbaker** [comment] 2020-06-26 09:22
I can't access the URL provided in the email/APK. I get a 403 when I try and load it in my web browser, and when I  try and run the provided APK I get the same 403:

```
2020-06-26 10:19:41.701 16765-16765/com.frost.livestream E/PushEventLogger: internalError [eventTime=0.21, mediaPos=0.00, window=0, loadError
      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    ]
```

**Comment by gokulkalagara** [comment] 2020-06-26 10:23
Sorry, there is geo-restriction, for that reason you got 403 error, I will attach a new URL to your email that can access from anywhere.

**Comment by gokulkalagara** [comment] 2020-06-26 12:06
@icbaker I sent mail which contains sample-apk, dash URL, sample DRM implementations, event logger files, and device bug report. please cross-check if you need anything just ping me back

**Comment by icbaker** [comment] 2020-06-26 13:22
Thanks for the new URL and updated APK.

When I run the provided APK on my Pixel 3A XL on Android 10 I don't see any `droppedFrame` events in logcat and the video looks smooth.

I can see the events in the BRs you've provided.

I'm going to mark this as 'device specific' and assign to @ojw28 to take a look.

**Comment by gokulkalagara** [comment] 2020-06-26 13:28
Same issues raise in the
**ANOTHER DEVICE**
Redmi Note 9 Pro, OS: 10
Redmi Note 9 Pro Max, OS: 10
Redmi Note 8 Pro, OS: 9

**Event Logger File**
[livestrea-4677a-bbdbd23ef00cb92e-export (1) (1).xlsx](https://github.com/google/ExoPlayer/files/4837152/livestrea-4677a-bbdbd23ef00cb92e-export.1.1.xlsx)

There are frame drops please cross-check

After updating from Exoplayer from 2.11.2 to 2.11.6
Number of devices are getting frame drops please help us

**Comment by gokulkalagara** [comment] 2020-06-26 14:25
**Gradle dependencies**

    //exoplayer
    implementation 'com.google.android.exoplayer:exoplayer:2.11.6'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.11.6'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.11.6'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.11.6'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.11.6'

**Comment by gokulkalagara** [comment] 2020-06-29 17:36
**SAMSUNG**
Model: SM-G615F, OS Version: 8.1.0
Model: SM-J810G, OS Version: 9

In this devices also

**Comment by gokulkalagara** [comment] 2020-07-15 16:20
If you need any extra information or I miss anything you need?
Please tell me, I will forward that information also

**Comment by gokulkalagara** [comment] 2020-07-22 09:37
@ojw28 can I know the status, it's almost 26 days, not even single replay from you

**Comment by ojw28** [comment] 2022-07-12 12:01
Let's treat this as a duplicate of https://github.com/google/ExoPlayer/issues/9062.

**Closed as completed by ojw28** 2022-07-12 12:01 UTC
Labels: duplicate, bug: device specific
