### ISSUE TITLE
EIA-608 closed captions not displayed

### ISSUE THREAD

**Issue by dhir-pratap** [google/ExoPlayer#295] opened 2015-02-16 09:36 UTC
We have a video which has 4 CC chanels. CC1 and CC2 are EIA-608 where as CC3 and CC4 are EIA-708. We are able to display the CC using VLC or other media player but the Exo player fails to display them.
Going through the code we found that the Eia608Parser Class has a 'parseHeader' method, which performs the check '(payloadType != PAYLOAD_TYPE_CC)'. This check is failing for our video. The expected value is 4 but we are getting 1. 

Can you tell the scenarios in which this will happen? What can we do to fix this issue?

**Comment by ojw28** [comment] 2015-02-17 00:07
payloadType=1 is pic_timing, which is unrelated to subtitles. So I'm not sure that what you're seeing is actually the subtitle, and it's likely that something else is going wrong. Could you provide a publicly accessible test stream to allow us to reproduce the issue?

**Comment by tringhub** [comment] 2015-02-17 17:06
Hi,

Can you please share your email id, so that we can send you the production url. At present we don't have any test stream url to share.

Thanks,

**Comment by ojw28** [comment] 2015-02-18 00:34
Please use olly.exoplayer [at] gmail.com

[This is a throwaway account for use here].

**Comment by ojw28** [comment] 2015-02-18 15:08
Thanks for the streams. I made some progress debugging the issue. It seems there are a few problems:

1. We don't unescape the sei_rbsp before we try to parse it.
2. We don't handle the case of multiple sei_message entries inside an sei_rbsp

When those are fixed, I was able to see captions, although they appeared to be unrelated to what was actually on the screen. I'll wait for the streams to go live again and see if the captions work correctly.

**Comment by tringhub** [comment] 2015-02-18 17:24
Thanks for the update.

Since it is live stream, the audio and caption won't be in sync, There
would be a delay of 5 to 6 secs. To verify whether the captions are
displaying fine with exo player , you can paste the url in Safari (either
web Mac or any iOS device) and play the video there and compare it with
Exoplayer

Thanks,

**Comment by ojw28** [comment] 2015-02-18 19:15
I have this working now, I think. We'll push a fix later today or tomorrow, and do a bug-fix release into master too. The issues were as described above, plus an off-by-one error fixed in https://github.com/google/ExoPlayer/commit/abac6b7dd6662bb4893566a4a04bf9804ee0599d.

**Closed** 2015-02-19 11:35 UTC
Labels: bug

**Comment by tringhub** [comment] 2015-02-19 17:14
Thanks for the update,  will check and let you know if it is working fine.


---------- Forwarded message ----------

**Comment by dhir-pratap** [comment] 2015-02-23 08:27
I have verified the CC. It is working.

**Comment by steve6** [comment] 2016-01-13 16:28
Hi  @dhir-pratap, @ojw28  are you able to see multiple CC inside exoplayer?
Because I have try to play this video on Exoplayer: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8 that have multiple CC tracks and in the sample app undex text I see only one track with name unknown.

Any idea?

Thanks
Steve

**Comment by ojw28** [comment] 2016-01-13 16:30
The captions in that sample are WebVTT, not EIA-608. The issue that's tracking listing captions of that type is #151.

**Comment by steve6** [comment] 2016-01-13 23:34
Thank you @ojw28 fow the answer it's clear.
Do you have a sample stream with inside multiple CC EIA-608?
I need it for some test.

Thank you.
