### ISSUE TITLE
Exoplayer's app:surface_type="texture_view" in xml not working

### ISSUE THREAD

**Issue by sunit-poddar-zz** [google/ExoPlayer#4214] opened 2018-05-07 06:59 UTC
I want to rotate video in exoplayer for which I explicitly gave `texture_view` instead of exoplayer's by default `surface_view` in xml but only the audio plays and the player view is blacked out. The media files are present locally on the device (mostly .mp4 files).

Here's my code in xml:
`<com.google.android.exoplayer2.ui.SimpleExoPlayerView`
`android:id="@+id/playerView"`
`android:layout_width="match_parent"`
`android:layout_height="match_parent"`
`android:visibility="gone"`
`app:use_controller="true"`
`app:fastforward_increment="3000"`
`app:rewind_increment="3000"`
`app:controller_layout_id="@layout/custom_playback_control_with_fullscreen"`
`app:show_timeout="1000"`
`app:use_artwork="true"`
`app:hide_on_touch="true"`
`app:surface_type="texture_view"`
`app:resize_mode="fit"`
`/>`

I'm changing the visibility of `playerView` programatically in `ExoPlayer.STATE_READY`. Wierd thing is that the same video files plays perfectly with `surface_view`.
For rotating video in exoplayer, i'm using 
`playerView.setRotation(90);`

I'm using exoplayer version `r2.4.4`. I've tried the same by downgrading exoplayer version to `r2.4.1` but resultant is the same backed out screen with audio continuing to play.

**Comment by tonihei** [comment] 2018-05-08 09:32
I tried to reproduce your problem by using the exact same properties for the `PlayerView` in our demo app (except for your custom controller layout). And in `onPlayerStateChanged`, I added the following code:
```
if (playbackState == Player.STATE_READY) {
  playerView.setVisibility(View.VISIBLE);
  playerView.setRotation(90);
}
```

This works fine with the latest ExoPlayer version. Could you please provide more detailed reproduction steps in our demo app? Or try our latest version to see if that problem still persists.

**Comment by sunit-poddar-zz** [comment] 2018-05-08 13:03
Thanks for replying @tonihei. I'm trying to make a video editing application and using `ConcatenatingMediaSource` for multiple videos one after the other. I've done the same thing as suggested by you on the overridden function `onPlayerStateChanged` and changed the playerView's visibility to View.Visible.

For rotation, I'm performing `playerView.setRotation(90)` on the overridden function `onPositionDiscontinuity`.

**Reproduction Steps**
I just added `app:surface_type="texture_view"` in the xml and the playerView started to blackout with audio playing. 

One weird thing that i noticed, I created a fresh demo app with only Exoplayer in it and the textureView was working perfectly fine, but with the exact same code in my project I'm observing this unusual behavior.

**Comment by tonihei** [comment] 2018-05-08 13:14
> I created a fresh demo app with only Exoplayer in it and the textureView was working perfectly fine, but with the exact same code in my project I'm observing this unusual behavior

That sounds as if the problem lies somewhere in your app ;) Can you figure how this fresh demo app is different from your actual app? Maybe some method isn't called or in an unexpected order.

**Comment by sunit-poddar-zz** [comment] 2018-05-08 15:32
Only the gradle dependencies are different in the two applications (demo and my original project). 

I've created a new demo activity inside my project only for playing a video file present locally but the resultant is same. I've also tried by replacing`SimpleExoPlayerView` with TextureView and provided it to SimpleExoPlayer by 

`TextureView textureView = (TextureView) findViewById(R.id.textureView);`
`SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(new DefaultRenderersFactory(context), new DefaultTrackSelector(), new DefaultLoadControl());`
`player.setVideoTextureView(textureView);`.

 I don't understand  how it could be called in unexpected order or something is not called at all.

**Comment by tonihei** [comment] 2018-05-09 08:13
What I mean is that your problem sounds as if `playerView.setVisibility(View.VISIBLE);` is either not called at all or called before the player view is available (and ready to be set visible). Or there is another call which sets the visibility to `View.GONE`. 

From what you say, it seems it's actually not an ExoPlayer problem (because your code works in your and our demo app) but rather a generic Android problem of setting things visible.

**Comment by sunit-poddar-zz** [comment] 2018-05-11 15:41
I know there's some issue with my project itself. I've mentioned in my question above that the app works perfectly with `surface_view`. When I'm changing surface_type to `texture_view`, I see a blacked out playerview with audio playing. 

Please note that I've not changed anything else in the code but I see 2 different exoplayer behaviors with different surface_view types. With the exact same code in my demo project, it works as desired there as well (with both surface_view and texture_view)

**Comment by tonihei** [comment] 2018-05-14 09:04
Unfortunately, we can't help you to debug an issue with your project if it's not an ExoPlayer problem. 
I would encourage you to find the difference between your demo app and the actual project to figure out at which point the problem occurs.

Closing the issue for now, but feel free to reopen if it turns out ExoPlayer related after all.

**Closed as completed by tonihei** 2018-05-14 09:04 UTC
Labels: need more info
