### ISSUE TITLE
Large native memory consumption when playing 4K HEVC 50/60fps content

### ISSUE THREAD

**Issue by mkocus** [google/ExoPlayer#9824] opened 2021-12-30 15:53 UTC
We are using ExoPlayer on our products and observe large native memory usage after starting video with params: 4k, 50/60fps, HEVC, DASH, Widevine DRM. The used native memory does not revert to baseline after leaving the player. But it also does not increase further after launching another videos.

### Details

It looks like that on Android Studio Profiler:

Android 9:
![memory usage](https://user-images.githubusercontent.com/57733529/147766292-c704aba8-9414-4a12-bb19-b2e8b0ebbdd3.png)
In this diagram I've started playing video in about 15-20s.

Android 10:
![sdmc_x4](https://user-images.githubusercontent.com/57733529/147766715-127d7704-c4cf-4e0c-b4ae-632978d8b19e.JPG)

The video is playing normally, but the usage of native memory is disturbing. It stabilize after a few minutes. 

### Versions

We've tested ExoPlayer 2.12.3 and 2.15.1.
We are testing this on Set-Top-Box (Android 9 & 10) and also various mobile Android devices.

### Question

What is the reason of that? Could it be reduced? On Set-Top-Box especially we have limited memory constraints.

**Comment by tonihei** [comment] 2022-01-11 13:32
> The used native memory does not revert to baseline after leaving the player. But it also does not increase further after launching another videos.

This sounds as if it's working as intended. The native memory is most likely used by the Android platform to allocate buffers for decoding the video and some buffers may also be allocated by the ExoPlayer library during the buffering process. The fact that it doesn't increase any further is a good sign that there is no leak and this is just working as intended. Note that playing 4K, 60fps videos naturally requires lots of memory at all stages. 

After playback ended, buffers may be kept to avoid re-allocation for new playback (both by ExoPlayer and the Android platform), but this memory can be reclaimed once ExoPlayer is released or another codec operation is started on the platform. That means, while the playback is running you probably want to use these buffers to ensure smooth playback. And after playback finished, the only thing you need to ensure is to release the player once you definitely don't need it anymore. 

If you want to limit the number of bytes ExoPlayer uses when pre-buffering (this is mostly in the "Java" part of your usage chart though), you can set the target memory usage in the `DefaultLoadControl.Builder` with `setTargetBufferBytes`. The default is around 130 MB.

**Comment by tonihei** [comment] 2022-01-31 13:59
Closing issue as the question was answered.

**Closed as completed by tonihei** 2022-01-31 13:59 UTC
Labels: question
