### ISSUE TITLE
Unable to import exoplayer with andriodx, always writing Failed to resolve error after downloading

### ISSUE THREAD

**Issue by urboihotshot** [google/ExoPlayer#7768] opened 2020-08-17 10:24 UTC
![imagedesc](https://user-images.githubusercontent.com/58696605/90386060-88405600-e073-11ea-877b-087e55d745f2.PNG)

**Comment by marcbaechinger** [comment] 2020-08-17 11:14
Closing as a duplicate of #7769

**Closed as completed by marcbaechinger** 2020-08-17 11:14 UTC
Labels: question
