### ISSUE TITLE
IndexOutOfBoundsException by getting Period from DashTim

### ISSUE THREAD

**Issue by userdimi** [google/ExoPlayer#5333] opened 2019-01-02 07:53 UTC
In my Bugsnag report I have a lot of events with this stacktrace:

```
Assertions.java:68com.google.android.exoplayer2.util.Assertions.checkIndex	
DashMediaSource.java:1153com.google.android.exoplayer2.source.dash.DashMediaSource$DashTimeline.getPeriod	
Timeline.java:757com.google.android.exoplayer2.Timeline.getPeriodByUid	
ExoPlayerImpl.java:492com.google.android.exoplayer2.ExoPlayerImpl.getCurrentWindowIndex	
AnalyticsCollector.java:632com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime	
AnalyticsCollector.java:650com.google.android.exoplayer2.analytics.AnalyticsCollector.generatePlayingMediaPeriodEventTime	
AnalyticsCollector.java:442com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged	
ExoPlayerImpl.java:839com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners	
ExoPlayerImpl.java:776com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo	
ExoPlayerImpl.java:713com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo	
ExoPlayerImpl.java:658com.google.android.exoplayer2.ExoPlayerImpl.handleEvent	
ExoPlayerImpl.java:129com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage	
Handler.java:102android.os.Handler.dispatchMessage	
Looper.java:135android.os.Looper.loop	
ActivityThread.java:5597android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
Method.java:372java.lang.reflect.Method.invoke	
ZygoteInit.java:984com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	
ZygoteInit.java:779com.android.internal.os.ZygoteInit.main 
```
In my application I use the exoplayer version 2.9.0 and this application is build for TV's. This issue occurs on different Amazon FireTV Sticks and on different SmartTV's models. I tried to reproduce the issue but until now it was not successful

**Comment by tonihei** [comment] 2019-01-02 09:59
Sounds like a duplicate of #5240. But it's still unclear what could cause this to happen. One potential reason is using ExoPlayer from multiple threads, but there may be another reason given that we got multiple reports of the same problem. 

I'll use the other issue to track this. If you happen to find a way to reproduce the issue or can provide further information about the circumstances of the event, please let us know.

**Closed as completed by tonihei** 2019-01-02 09:59 UTC
Labels: duplicate
