### ISSUE TITLE
the player keep playing the old video audio

### ISSUE THREAD

**Issue by H1-N1** [google/ExoPlayer#4305] opened 2018-05-28 01:17 UTC
hi 
sorry for my bad english im not a native speaker.
i face issues with exoplayer when i play multiple video on the same player !
when i play different url stream the player keep playing the old video audio in background with the new video !

```
private void play(final M3UItem item) {
		if (item.getStreamURL() != null) {
			Interlude loading = new Interlude(this, new Interlude.Task(false) {
				
				@Override
				public void execute() {
                 //  Toast.makeText(this, "portrait", Toast.LENGTH_SHORT).show();

					exoPlayer.stop();
					//exoPlayer.release();
				//	SimpleExoPlayer = null;

					//mVideoView.stopPlayback();
				}
			});

			BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
			TrackSelector trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));
			exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);

			loading.setCallback(new Interlude.Callback() {
				
				@Override
				public void onCompleted() {

					try {


						DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory("exoplayer_video");
						ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();


						Uri videoURI = Uri.parse(item.getStreamURL());
						MediaSource mediaSource = new ExtractorMediaSource(videoURI, dataSourceFactory, extractorsFactory, null, null);


						exoPlayerView.setPlayer(exoPlayer);
						exoPlayer.prepare(mediaSource);
						exoPlayer.setPlayWhenReady(true);
					}catch (Exception e){
						Log.e("MainAcvtivity"," exoplayer error "+ e.toString());
					}



//					mVideoView.setVideoURI(Uri.parse(item.getStreamURL()));//http://iptv.ndasat.com:88/live/550290029873347/550290029873347/68.tsitem.getStreamURL()
//					mVideoView.start();
				}
			});
			loading.excute();
			//mMenu.setVisibility(View.GONE);
		} else {
			new MessageBox(this, getString(R.string.error),
					getString(R.string.error_invalid_url), MessageBox.MB_OK);
		}
	}
```

**Comment by botaydotcom** [comment] 2018-05-31 08:42
One immediate issue I can spot in your code is that you are always creating new player every time, and immediately assign it to your existing `exoPlayer` field.
```
exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
```
When your `loading.execute()` is called, it's stopping the new instance, instead of the old one. To solve this, either try to stop/release the player instance before creating the new one, or reusing the old player instance to play a new item.
Anyway, I think this is not a bug in ExoPlayer code, but more like a problem with your app code. We recommend asking such questions on StackOverflow instead. Thank you very much.

**Closed as completed by botaydotcom** 2018-05-31 08:42 UTC
Labels: question

**Comment by masday86** [comment] 2018-11-22 07:41
i have same problem, when changing the url when the player loads the url, the old video sound will still run.
how to fix this
