### ISSUE TITLE
shrink build fails

### ISSUE THREAD

**Issue by loki666** [google/ExoPlayer#4890] opened 2018-09-28 11:37 UTC
### Issue description
when shrinking a build (not using proguard), the build fails

### Reproduction steps
using exoPlayer 2.9.0

add to build.gradle
```
    buildTypes {
        debug {
            minifyEnabled true
            useProguard false
        }
    }
```

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
emulator API 26

### A full bug report captured from the device
```
:app:transformClassesWithAndroidGradleClassShrinkerForDebug
com/google/android/exoplayer2/upstream/DefaultDataSource.getResponseHeaders:()Ljava/util/Map; references unknown class member: com/google/android/exoplayer2/upstream/DataSource.getResponseHeaders:()Ljava/util/Map;
com/google/android/exoplayer2/upstream/cache/CacheDataSource.getResponseHeaders:()Ljava/util/Map; references unknown class member: com/google/android/exoplayer2/upstream/DataSource.getResponseHeaders:()Ljava/util/Map;
```

**Comment by erdemguven** [comment] 2018-10-01 09:52
I can not reproduce the issue on the ExoPlayer demo app. I copied your configuration to demos/main/build.gradle. The app builds and runs fine. If you can reproduce the issue on the demo app please let us know.

**Comment by ojw28** [comment] 2018-10-01 10:30
It looks like your setup isn't properly handling default methods (e.g. DataSource.getResponseHeaders), which is a Java 8 feature. It might be a good idea to try updating Android Studio, the version of build tools that you're using etc. I suspect doing this will resolve the issue.

If you happen to be including ExoPlayer as source, please also see the [RELEASE NOTES](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md) for an extra step.

**Comment by loki666** [comment] 2018-10-01 11:52
can't reproduce with the demo either...

I'm using an compiled dependancy using latest Android Studio and build tools.

I'll try include ExoPlayer a source dependancy

**Comment by ojw28** [comment] 2018-10-01 11:53
You really shouldn't need to include it as a source dependency. That's just making things more difficulty. What `buildToolsVersion` is specified in the gradle file of whatever you're building?

**Comment by ojw28** [comment] 2018-10-01 11:57
Actually, I think the important thing is probably the `com.android.tools.build:gradle` dependency you have. Not sure :).

**Comment by loki666** [comment] 2018-10-01 12:24
bah my project doesn't like to use ExoPlayer as source
something with annotation package (I've migrated to androidX)

**Comment by loki666** [comment] 2018-10-01 12:34
buildToolsVersion: '28.0.3'
classpath "com.android.tools.build:gradle:3.2.0"

adding
-dontwarn com.google.android.exoplayer2.upstream.DataSource
to my proguard-rules.pro fixed it

**Comment by ojw28** [comment] 2018-10-03 11:56
I think it sounds a like a pro-guard or some other tool issue, in that case? I'm going to close this for now, since it's only a single report. It still seems possible something in your toolchain is out of date. If we get additional reports then we'll look at getting the proguard config to the library, so developers don't need to figure this out for themselves. Thanks for reporting how to fix it!

**Comment by cemrich** [comment] 2018-10-10 15:26
I have the same issue with the same buildTools and gradle version and an up to date Android Studio installation (3.2). 

@loki666 s dontwarn directive fixed the build error, but causes the exo player instance to throw exceptions:

```
Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:249)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:389)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:455)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:249) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:389) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
        at libcore.io.IoBridge.open(IoBridge.java:441)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128) 
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:249) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:389) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

I am pretty sure the exceptions is caused by the shrinking but I cannot confirm right now, because I've hit the DEX limit. I will report back as soon as I find out more.

**Comment by loki666** [comment] 2018-10-10 20:46
I don't have this crash, but I'm not using FileDataSource

**Comment by ojw28** [comment] 2018-10-10 21:48
It seems more likely that the file uri is incorrect, given the stack trace.

**Comment by cemrich** [comment] 2018-10-14 12:18
You were right, my issue was related to loading subtitles and had nothing to do with proguard. I am sorry for causing confusion.

In the process of finding this out I made a minimal test app to reproduce the Proguard issue: https://github.com/cemrich/ExoTestApp-4890. You can edit https://github.com/cemrich/ExoTestApp-4890/blob/master/app/proguard-rules.pro and comment out the single line to provoke the error when doing a debug build.

**Comment by ojw28** [comment] 2018-10-17 21:13
Thanks. I was able to reproduce a problem. It seems shrinking has a problem with default methods being called in implementing subclasses using `InterfaceName.super.methodName` syntax. We'll fix this one way or another (e.g. by not calling default methods like that, or by adjusting the library proguard file) for the next release.

**Closed as completed** 2018-10-20 13:28 UTC
Labels: bug
