### ISSUE TITLE
HLS Playlist URLs which include port fail to play

### ISSUE THREAD

**Issue by fougere-mike** [google/ExoPlayer#351] opened 2015-03-11 16:54 UTC
There is an issue which prevents playlist URLs which include a port specifier from working. It appears android.net.Uri.toString() is urlencoding the port specifier.

HttpDataSource.java:387:
URL url = new URL(dataSpec.uri.toString());

Should be changed to:
URL url = new URL(Uri.decode(dataSpec.uri.toString()));

**Comment by ojw28** [comment] 2015-03-11 19:31
Can you share an example HLS manifest that has problematic URLs? I'm not sure about this. THanks!

**Comment by fougere-mike** [comment] 2015-03-12 15:22
The issue happens for me when I have a url to a .m3u8 file which contains a port specifier. For example: http://192.168.1.2:80/stream/playlist.m3u8

If I remove the ':80', everything works great. I use that URL in my RendererBuilder; it gets passed to a ManifestFetcher<HlsPlaylist> in buildRenderers(), and to an HlsChunkSource in onManifest().

**Comment by ojw28** [comment] 2015-03-12 16:36
I tried adding ":80" into the URLs of a few internal test streams we have, and everything still worked fine for me on both the master and dev branches. Furthermore, in HttpDataSource, if I add in a check to see what the decode actually does, it says that it doesn't do anything. In other words, this evaluates to true:

```
TextUtils.equals(dataSpec.uri.toString(), Uri.decode(dataSpec.uri.toString()))
```

Can you provide a concrete example of what uri.toString() is giving you at L387 of HttpDataSource when you're seeing this issue, and also what Uri.decode(uri.toString()) is in this case?

**Comment by hansvdg** [comment] 2015-03-23 14:07
In the current master branch the function getMergedUri in Util.java returns an encoded URL.
The dev branch has some refactoring in this area, maybe this is already fixed there.

**Comment by ojw28** [comment] 2015-03-23 14:10
I couldn't reproduce the issue on either branch.

**Comment by hansvdg** [comment] 2015-03-23 14:25
In my case on the master branch the issue happens when using a non standard port (i.e. 10583) and variant urls with relative paths.

Master playlist url: http://<ip>:10583/12507.m3u8

Master playlist:
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=431648,RESOLUTION=0x0
/12507/0.m3u8

**Comment by ojw28** [comment] 2015-03-23 15:25
Ah. Does the dev branch fix the issue for you?

**Comment by hansvdg** [comment] 2015-03-23 15:41
Yes in the dev branch the issue is fixed.

**Comment by ojw28** [comment] 2015-03-23 15:42
Thanks for the info. I'm going to close this on the assumption that the issue is the same.

**Closed by ojw28** 2015-03-23 15:42 UTC
Labels: bug
