### ISSUE TITLE
Cache-Control: no-cache

### ISSUE THREAD

**Issue by tanpuer** [google/ExoPlayer#6076] opened 2019-06-21 09:49 UTC
I request some videos with http response: "Cache-Control: no-cache". I hope exoplayer will not cache this video using CacheDataSource, but it didn't. So should I custom another DataSource or modify some code?

**Comment by tanpuer** [comment] 2019-06-21 10:56
![image](https://user-images.githubusercontent.com/16443498/59918086-465b5600-9456-11e9-986b-460e58ed36eb.png)
Can i add a judgement before dataSink.write(buffer, offset, bytesRead) ?

**Comment by marcbaechinger** [comment] 2019-06-21 13:55
Yes, do not wrap your data source with `CacheDataSource` for those streams you don't want to cache.

**Comment by tanpuer** [comment] 2019-06-22 13:09
@marcbaechinger I must always use CacheDataSource and later determine whether to cache according to Cache-Control in response header.

**Comment by kgrevehagen** [comment] 2019-07-04 11:02
@marcbaechinger Is this a duplicate of 4188? If yes, do you have any status or ETA on when this will be implemented?

**Comment by marcbaechinger** [comment] 2019-07-05 08:32
Closing this due to duplicate #4188

**Closed as completed by marcbaechinger** 2019-07-05 08:32 UTC
Labels: duplicate, question
