### ISSUE TITLE
Subtitle bottomPaddingFraction not applied for VTT subtitles

### ISSUE THREAD

**Issue by TheBeastLT** [google/ExoPlayer#10428] opened 2022-07-12 09:52 UTC
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

Android TV API 29

### Reproducible in the demo app?

Not tested

### Reproduction steps

Set `bottomPaddingFraction` in `SubtitleView` and try to play sideloaded `VTT` type subtitles, they will be positioned at the bottom.

### Expected result

`VTT` sideloaded subtitles should respect the `bottomPaddingFraction` positioning variable

### Actual result

`VTT` subtitles are positioned at the bottom of the view, not respecting `bottomPaddingFraction`, where it respects all other styling parameters (text size, color, outline, etc.)

Tried setting both `setApplyEmbeddedFontSizes` and `setApplyEmbeddedStyles` to `false`, but that didn't help, even though these subtitles are sideloaded.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment] 2022-07-12 10:28
Duplicate of #7934 (this is working as intended, not a bug)

**Closed as completed by icbaker** 2022-07-12 10:28 UTC
Labels: duplicate
