### ISSUE TITLE
matroska video only support audio track. video track not supported.

### ISSUE THREAD

**Issue by hahafamilia** [google/ExoPlayer#4146] opened 2018-04-18 09:17 UTC
Before filing an issue:
-----------------------

When reporting a bug:
-----------------------

### Issue description
matroska video only support audio track. video track not supported.

### Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app.

### Link to test content
mail to dev.exoplayer@gmail.com 

### Version of ExoPlayer being used
2.7.3

### Device(s) and version(s) of Android being used
SM-A500L, Android 6.0.1

### Android Studio Logcat
 D/EventLogger: timelineChanged [periodCount=1, windowCount=1, reason=DYNAMIC
 D/EventLogger:   period [5914.00]
 D/EventLogger:   window [5914.00, true, false]
 D/EventLogger: ]
 W/AudioCapabilities: Unsupported mime audio/mpeg-L1
 W/AudioCapabilities: Unsupported mime audio/mpeg-L2
 W/AudioCapabilities: Unsupported mime audio/x-ms-wma
 W/AudioCapabilities: Unsupported mime audio/x-ima
 W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
 W/AudioCapabilities: Unsupported mime audio/evrc
 W/AudioCapabilities: Unsupported mime audio/qcelp
 W/AudioCapabilities: Unsupported mime audio/qcelp
 W/AudioCapabilities: Unsupported mime audio/evrc
 W/VideoCapabilities: Unsupported mime video/wvc1
 W/VideoCapabilities: Unsupported mime video/x-ms-wmv
 W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
 W/VideoCapabilities: Unsupported mime video/wvc1
 W/VideoCapabilities: Unsupported mime video/x-ms-wmv
 W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
 W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
 W/VideoCapabilities: Unsupported mime video/mp43
 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
 W/VideoCapabilities: Unsupported mime video/sorenson
 D/EventLogger: audioEnabled [1.02]
 D/EventLogger: Tracks [
 D/EventLogger:   Renderer:0 [
 D/EventLogger:     Group:0, adaptive_supported=N/A [
 I/ACodec:  [] Now uninitialized
 D/EventLogger:       [ ] Track:0, id=2, mimeType=video/x-unknown, res=1280x720, supported=NO_UNSUPPORTED_TYPE
 D/EventLogger:     ]
 D/EventLogger:   ]
 D/EventLogger:   Renderer:1 [
 D/EventLogger:     Group:0, adaptive_supported=N/A [
 D/EventLogger:       [X] Track:0, id=1, mimeType=audio/mp4a-latm, channels=1, sample_rate=44100, language=und, supported=YES
 D/EventLogger:     ]
 D/EventLogger:   ]
 D/EventLogger: ]
 I/ACodec: [] onAllocateComponent
 I/OMXClient: Using client-side OMX mux.
 I/ACodec: [OMX.SEC.aac.dec] Now Loaded
 I/ACodec: [OMX.SEC.aac.dec] Now Loaded->Idle
 I/ACodec: [OMX.SEC.aac.dec] Now Idle->Executing
 I/ACodec: [OMX.SEC.aac.dec] Now Executing
 D/EventLogger: audioDecoderInitialized [1.07, OMX.SEC.aac.dec]
 D/EventLogger: audioFormatChanged [1.07, id=1, mimeType=audio/mp4a-latm, channels=1, sample_rate=44100, language=und]
 D/EventLogger: audioSessionId [123]

### Video MediaInfo
General
Unique ID                                : 144185819702368129642976846741758313457 (0x6C792DC401D146A47318D86EF9E883F1)
Complete name                            : C:\tmp\ExoSample\matroska.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 2.85 GiB
Duration                                 : 1 h 38 min
Overall bit rate                         : 4 142 kb/s
Writing application                      : PotEncoder
Writing library                          : PotEncoder

Video
ID                                       : 2
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1 h 38 min
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 FPS
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 1
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : A_AAC
Duration                                 : 1 h 38 min
Channel(s)                               : 1 channel
Channel positions                        : Front: C
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Default                                  : Yes
Forced                                   : No

### ExoPlayer Code
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
      

        dataSourceFactory = new DefaultDataSourceFactory(this, BANDWIDTH_METER
                , new DefaultHttpDataSourceFactory(Util.getUserAgent(this, "SampleExoPlayer"), BANDWIDTH_METER));
        mainHandler = new Handler();

        setContentView(R.layout.activity_simple_exo_player);

        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        Thread.setDefaultUncaughtExceptionHandler(new ExceptionHandler(this));

        playerView = (PlayerView) findViewById(R.id.player_view);
        debugTextView = findViewById(R.id.debug_text_view);

    }

    private void initializePlayer(Uri mp4VideoUri) {

        // 1. Track Selector
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(BANDWIDTH_METER);
        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        eventLogger = new EventLogger((MappingTrackSelector) trackSelector);

        DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(this, null,
                DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);

        DefaultAllocator defaultAllocator = new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE);
        loadControl = new DefaultLoadControl(defaultAllocator,
                DefaultLoadControl.DEFAULT_MIN_BUFFER_MS ,
                DefaultLoadControl.DEFAULT_MAX_BUFFER_MS,
                DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS,
                DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS,
                DefaultLoadControl.DEFAULT_TARGET_BUFFER_BYTES,
                DefaultLoadControl.DEFAULT_PRIORITIZE_TIME_OVER_SIZE_THRESHOLDS
        );

        // 2. Create the player
        player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl );
        player.addListener(new PlayerListener());
        player.addListener(eventLogger);
        player.addMetadataOutput(eventLogger);
        player.addAudioDebugListener(eventLogger);
        player.addVideoDebugListener(eventLogger);
        player.setPlayWhenReady(true);

        playerView.setPlayer(player);

        playerView.setPlaybackPreparer(this);
        debugViewHelper = new DebugTextViewHelper(player, debugTextView);
        debugViewHelper.start();

        DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

        MediaSource videoSource = new ExtractorMediaSource.Factory(dataSourceFactory).setExtractorsFactory(extractorsFactory)
                .createMediaSource(mp4VideoUri, mainHandler, eventLogger);

        // Prepare the player with the source.
        player.prepare(videoSource);

    }

**Comment by ojw28** [comment] 2018-04-22 21:33
Given your response to https://github.com/google/ExoPlayer/issues/3026, I'm guessing this is a duplicate of that issue. Closing as a duplicate. Please let us know if this is something different. Thanks!

**Comment by ojw28** [comment] 2018-04-22 21:52
Ah, this is a different issue. @botaydotcom - Looks like we need to be handling `compression == 0x34363248` in MatroskaExtractor.parseFourCcPrivate for this stream?

**Comment by hahafamilia** [comment] 2018-04-23 01:55
I am not familiar with video encoding and decoding techniques.
I do not know what compression == 0x34363248 is.
I read other issues here.
mastroska format will fail to play in some cases.
I wonder if playback fails in some cases.
Because when ExoPlayer can not play, I have to let the users know.
I am sorry that I can not answer your question properly.
What more should I tell you?

**Comment by ojw28** [comment] 2018-07-13 18:21
Hi. I think we can fix this fairly easily, but unfortunately the test content provided is no longer accessible. Please could you send it again?

**Comment by ojw28** [comment] 2018-07-17 20:27
@CHOJUIL - Are you able to provide the test content again? If not we may have to close this issue, since we don't have any media with which to validate any fix.

**Comment by ojw28** [comment] 2018-08-01 13:27
Closing due to lack of test content, unfortunately. Please let us know if you're able to provide the file again.

**Closed as completed by ojw28** 2018-08-01 13:27 UTC
Labels: bug
