### ISSUE TITLE
how to build a DashManifest with custom xml string?

### ISSUE THREAD

**Issue by michael-eddy** [google/ExoPlayer#7687] opened 2020-07-28 09:40 UTC
the content just like:
```
xml <MPD xmlns="urn:mpeg:DASH:schema:MPD:2011" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="dynamic" availabilityStartTime="2018-07-07T22:52:44Z" publishTime="2018-07-07T22:52:44Z" minimumUpdatePeriod="PT30S" minBufferTime="PT3S" timeShiftBufferDepth="PT120S">
	<Analytics statslink="" stalledlink=""/>
	<Period id="1" start="PT0S">
		<AdaptationSet id="video" segmentAlignment="true" startWithSAP="1" maxWidth="1280" maxHeight="720">
			<ContentComponent id="1" contentType="video"/>
			<Role schemeIdUri="urn:mpeg:DASH:role:2011" value="main"/>
			<SegmentTemplate timescale="1000" duration="2000" startNumber="1" media="" initialization=""/>
			<Representation id="1" mimeType="video/mp4" codecs="avc1.4d4032" startWithSAP="1" bandwidth="5000000" frameRate="30" width="1280" height="720"> </Representation>
			<Representation id="2" mimeType="video/mp4" codecs="avc1.4d4032" startWithSAP="1" bandwidth="1000000" frameRate="30" width="854" height="480"> </Representation>
			<Representation id="3" mimeType="video/mp4" codecs="avc1.4d4032" startWithSAP="1" bandwidth="400000" frameRate="30" width="640" height="360"> </Representation>
		</AdaptationSet>
		<AdaptationSet id="audio" segmentAlignment="true" startWithSAP="1" lang="und">
			<ContentComponent id="1" contentType="audio"/>
			<Role schemeIdUri="urn:mpeg:DASH:role:2011" value="main"/>
			<SegmentTemplate timescale="1000" duration="2000" startNumber="1" media="" initialization=""/>
			<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" startWithSAP="1" bandwidth="160000"> </Representation>
		</AdaptationSet>
	</Period>
</MPD>
```

how can i do makes the string content converts to a DashManifest object?

**Comment by tonihei** [comment] 2020-07-31 12:30
If you have the manifest as a string already, you could try to use a `ByteArrayDataSource` to read this data in a `DashMediaSource`. Alternatively, you can try to use `DashManifestParser` to read the data from an `InputStream`.

**Comment by michael-eddy** [comment] 2020-08-01 08:21
> If you have the manifest as a string already, you could try to use a `ByteArrayDataSource` to read this data in a `DashMediaSource`. Alternatively, you can try to use `DashManifestParser` to read the data from an `InputStream`.

is that any demo for this?i try the way just like u but it is does not work...

**Comment by tonihei** [comment] 2020-08-03 08:48
"it does not work." isn't very helpful to understand what the problem is :) 

`DashMediaSource.Factory` provides a constructor to set the `manifestDataSourceFactory`. This could be used to load your manifest from files, or from a byte array using `ByteArrayDataSource`. The `DashMediaSource.Factory` also has a `createMediaSource` method that accepts a pre-parsed `DashManifest` object that could be obtained by using `DashManifestParser` and your string manifest.

**Comment by michael-eddy** [comment] 2020-08-06 06:39
> "it does not work." isn't very helpful to understand what the problem is :)
> 
> `DashMediaSource.Factory` provides a constructor to set the `manifestDataSourceFactory`. This could be used to load your manifest from files, or from a byte array using `ByteArrayDataSource`. The `DashMediaSource.Factory` also has a `createMediaSource` method that accepts a pre-parsed `DashManifest` object that could be obtained by using `DashManifestParser` and your string manifest.

thank's for your help.but i try it in this code ,this's a part of my code:
`var source = new ByteArrayDataSource (mpdString.ToBytes ());
var dataSourceFactory = new DefaultHttpDataSourceFactory ("userAgent", null);
var mediaSource = new ExtractorMediaSource.Factory (dataSourceFactory).SetExtractorsFactory (new DefaultExtractorsFactory ()).CreateMediaSource (source.Uri);
Player.Prepare (mediaSource);`
but the player throw  a object null refrence,it's that i got the wrong code?

**Comment by tonihei** [comment] 2020-08-06 08:25
Please read the guide on how to play DASH streams: https://exoplayer.dev/dash.html#creating-a-mediasource
You need to use `DashMediaSource` and then follow one of two options I explained above.

**Comment by michael-eddy** [comment] 2020-08-08 16:07
> Please read the guide on how to play DASH streams: https://exoplayer.dev/dash.html#creating-a-mediasource
> You need to use `DashMediaSource` and then follow one of two options I explained above.

thank's my friend.i copy the wrong code before.know i using the `DashManifestParser.parse(uri,mpdStream) `,but the exoplayer throw a excption `{Com.Google.Android.Exoplayer2.ParserException: Unable to determine duration of static manifest.`the mpd string content is from [here](https://github.com/xiaoyaocz/biliuwp/blob/master/BiliBili.UWP/Helper/PlayurlHelper.cs#L1094). this error looks like some mpd data is missing?and the uri like `http://upos-sz-mirrorkodo.bilivideo.com/upgcxcode/84/99/206259984/206259984-1-30033.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1596909515&gen=playurl&os=kodobv&oi=1885262959&trid=bbd19e450e5a49fab2fb315f87db8f70u&platform=pc&upsig=6750789fa16868c13d0603db5bdd5189&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=38717198&orderid=0,3&agrr=0&logo=80000000`,how can i locate the cause of this problem?

oh ye,i tried u the uri only,create a DashMediaSourceFactory with createMediaSource in it.player can play the video without voices.and sorry my english is too rubbish.hahaha.

                                                                                                                                                                     best wishes.michael

**Comment by ojw28** [comment] 2020-08-10 13:40
The manifest is invalid because it doesn't specify the duration of the period. The DASH specification provides a few different options for doing this, but it must be possible to determine the period duration from the manifest, one way or another. `MPD@mediaPresentationDuration` is documented in the specification as:

> This attribute shall be present when neither the attribute MPD@minimumUpdatePeriod nor the Period@duration of the last Period are present.

where-as the manifest you're generating doesn't do any of these things. Generating valid content is outside the scope of this issue tracker, so I think we can close this. If you have questions about generating valid content, perhaps try StackOverflow.

**Closed as completed by ojw28** 2020-08-10 13:40 UTC
Labels: question
