### ISSUE TITLE
MediaDrm.release not called in all cases

### ISSUE THREAD

**Issue by nahojkap** [google/ExoPlayer#4721] opened 2018-08-23 16:19 UTC
While reviewing playback issues with PlayReady DRM on Android TV devices, I noticed that the MediaDRM#release method is never called when the DRM session manager is released. 

Not sure it has an impact but for completeness, the DefaultDrmSession#release method should probably do this when it is called?

**Comment by ojw28** [comment] 2018-08-24 11:40
In the demo app it's application code that both instantiates and releases the `MediaDrm` instance, and this is one way of doing it. We do however have static methods like `DefaultDrmSessionManager.newFrameworkInstance` where the `MediaDrm` is instantiated internally, and not also released internally, which doesn't seem right.

We need to figure out what the best thing to do here is. It may tie in with some other DRM changes that we need to make.

**Comment by nahojkap** [comment] 2018-08-30 15:55
I see, we are indeed now releasing it as part of our cleanup.

Curious about the 'other DRM changes' you are referring to, anything you can share?

**Comment by ram992** [comment] 2018-09-07 11:15
Hello @ojw28, can this bug be the cause of issue discussed in #4674  that I am experiencing.

**Comment by ojw28** [comment] 2018-09-07 11:16
I doubt it (but if you want to find out, why don't you just try using `DefaultDrmSessionManager` in a way that ensures the instance is released, as in the demo app?).

**Comment by ram992** [comment] 2018-09-07 11:20
Nice Idea, will try that out ASAP

**Comment by ojw28** [comment] 2019-05-31 13:12
`DefaultDrmSessionManager` and `OfflineLicenseHelper` both have this problem. @AquilesCanta - How would you feel about adding a `release()` method to both, which does nothing if the application injected the `mediaDrm` itself, but releases the `mediaDrm` if it was constructed internally?

**Comment by ojw28** [comment] 2019-07-08 12:06
@AquilesCanta - It would be good to get this fixed. See the issue duped above for a bit more information on why.

**Comment by ojw28** [comment] 2019-11-15 07:26
The last fix needed for this was submitted in https://github.com/google/ExoPlayer/commit/51711a0c97e6ed012356951591ef07135ef2a20b.

**Closed as completed by ojw28** 2019-11-15 07:26 UTC
Labels: bug
