### ISSUE TITLE
Player speeding playback after few hours of playing or issue high-pitched sounds 

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#4138] opened 2018-04-17 07:30 UTC
### Issue description
I am using Exoplayer in app which allow users to listen online radios (shoutcast). Now user report this: 

> listen to the radio a few hours each day but after some time of 3 hours or more, listen in a row app as take high-pitched sounds and in some cases even music is accelerating.

### Link to test content
There is app: https://play.google.com/store/apps/details?id=com.dev.franek.pavol.ceskoslovenskeradia
but I think this is not important.

### Version of ExoPlayer being used
2.7.0

### Device(s) and version(s) of Android being used
Device Galaxy S8 (dreamlte) 
Manufacturer Samsung Device
Type Phone Device Language English 
Processor Type Samsung Processor Model Exynos 8895 Native Platform armeabi-v7a, armeabi, arm64-v8a
OpenGL ES 3.2 
Operating System Android 8.0

I'm not sure where the problem might be. I do not do anything special in the player, nor do I set up any playback params. This problem occurs after several hours of play, so it's also difficult to simulate it. If it is not a bug but it is necessary to change something in the code I will be grateful for the help.

Code:
[issue.txt](https://github.com/google/ExoPlayer/files/1918529/issue.txt)

**Comment by andrewlewis** [comment] 2018-04-17 10:47
The code looks fine. If you're not calling `player.setPlaybackParameters` anywhere then there isn't really a way for ExoPlayer to speed up the audio.

I don't think we've had reports mentioning high pitched sounds and changes in speed before. Have you been able to reproduce the problem on any devices? Any idea if it's device-specific? Could the problem be on the content serving side? To diagnose what's going on it would be useful for have logcat or (preferably) a bug report captured with `adb bugreport` shortly after the problem manifests itself.

**Comment by ojw28** [comment] 2018-06-05 21:26
Closing due to lack of requested information.

**Closed as completed by ojw28** 2018-06-05 21:26 UTC
Labels: need more info
