### ISSUE TITLE
Unknown enum constant AnnotationTarget.ANNOTATION_CLASS

### ISSUE THREAD

**Issue by inat-tv** [google/ExoPlayer#7007] opened 2020-02-23 23:44 UTC
I didn't touch anything. This error occurs when you compile the project.

![image](https://user-images.githubusercontent.com/31779629/75122541-86429f00-56af-11ea-8bc1-eb0e3bcb731e.png)

**Comment by tonihei** [comment] 2020-02-24 12:04
That's a known issue caused by the fact that a Kotlin annotation for Java code is defined in Kotlin instead of Java (see [here](https://youtrack.jetbrains.com/issue/KT-33141)). This should be fixed as soon as we can update our dependency version to 1.3.70.

But it's not an actual problem and you can ignore the warning for now.

**Comment by inat-tv** [comment] 2020-02-24 22:24
Ok thanks bro

**Comment by inat-tv** [comment] 2020-02-24 22:24
> That's a known issue caused by the fact that a Kotlin annotation for Java code is defined in Kotlin instead of Java (see [here](https://youtrack.jetbrains.com/issue/KT-33141)). This should be fixed as soon as we can update our dependency version to 1.3.70.
> 
> But it's not an actual problem and you can ignore the warning for now.

Ok thanks bro

**Comment by tonihei** [comment] 2020-03-12 09:48
This issue is fixed now, closing.

**Closed by tonihei** 2020-03-12 09:48 UTC
Labels: bug: in dependency
