### ISSUE TITLE
HLS video playback throws "Unexpected runtime error" after video complete : "E/ExoPlayerImplInternal: Playback error"

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#8035] opened 2020-10-02 17:01 UTC
### [REQUIRED] Issue description
When I play HLS stream and scrub it to the end or let it play through very end, ExoPlayer throws an error. Strange thing is it completes the whole video and then throws an error.
 
### [REQUIRED] Reproduction steps
Able to reproduce in demo app

### [REQUIRED] Link to test content
Can you share an email address where I can send test content?

### [REQUIRED] A full bug report captured from the device
```java
2020-10-02 12:52:38.433 19015-19015/? E/exoplayer2.dem: Unknown bits set in runtime_flags: 0x8000
2020-10-02 12:52:49.084 19015-19162/com.google.android.exoplayer2.demo E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2020-10-02 12:53:03.765 19015-19146/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
        at com.google.android.exoplayer2.text.TextRenderer.getNextEventTime(TextRenderer.java:328)
        at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:201)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2020-10-02 12:53:03.812 19015-19015/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=15.48, mediaPos=400.96, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
        at com.google.android.exoplayer2.text.TextRenderer.getNextEventTime(TextRenderer.java:328)
        at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:201)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
2020-10-02 12:53:15.862 19015-20290/com.google.android.exoplayer2.demo E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2020-10-02 12:53:16.877 19015-19146/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
        at com.google.android.exoplayer2.text.TextRenderer.getNextEventTime(TextRenderer.java:328)
        at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:201)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2020-10-02 12:53:16.933 19015-19015/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [eventTime=28.60, mediaPos=400.96, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
        at com.google.android.exoplayer2.text.TextRenderer.getNextEventTime(TextRenderer.java:328)
        at com.google.android.exoplayer2.text.TextRenderer.render(TextRenderer.java:201)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]
```

### [REQUIRED] Version of ExoPlayer being used
2.12.0

### [REQUIRED] Device(s) and version(s) of Android being used
API 21 and above [physical devices + emulators]

**Comment by tonihei** [comment] 2020-10-06 17:17
This is most likely a duplicate of #8017 and should be fixed on the dev branch.

**Closed as completed by tonihei** 2020-10-06 17:17 UTC
Labels: bug, duplicate

**Comment by nishantkp** [comment] 2020-10-14 19:57
@tonihei do you have an ETA for the next release?

**Comment by ojw28** [comment] 2020-10-15 18:37
This will be picked up in a minor release (2.12.1), for which you shouldn't have to wait too long (probably the end of this month).

**Comment by nishantkp** [comment] 2020-10-16 13:34
thanks @ojw28
