### ISSUE TITLE
first parameter of Clippingmediasource can only accept Mediasource type and not Concatenatingmediasource type?

### ISSUE THREAD

**Issue by PeOS-China** [google/ExoPlayer#8289] opened 2020-11-27 06:29 UTC
I use clipping media source (mediasource, 0, 3_ 000_ 000) create a clippingmediasource object. Mediasource is of mediasource type. Exoplayer can play normally, but use clippingmediasource (concatenatingmediasource, 0,3)_ 000_ 000), concatenatingmediasource is of concatenatingmediasource type, exoplayer cannot play. Whether the first parameter of clippingmediasource can only accept Mediasource type and not Concatenatingmediasource type
The code is as follows：
`       
      val application: BarbellApplication = requireActivity().application as BarbellApplication

        val dataSourceFactory = CacheDataSourceFactory(application.getDownloadCache(), upstreamSourceFactory)
        val playlist = ConcatenatingMediaSource(true)
        var m : MediaSource? = null
        
        lesson.Exercises.forEach {
            if(it.PlaybackURLs.isNotEmpty()) {
                it.PlaybackURLs.forEach { url ->
                    if(url.isNotEmpty()) {
                        val uri = Uri.parse(url)
                        val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri)
                        playlist.addMediaSource(mediaSource)
                        if(null == m) {
                            m = mediaSource
                        }
                    }
                }
            }
        }

        mediaSource = playlist

      val clippingMediaSource1 = ClippingMediaSource(playlist, 0, 3_000_000)
        val clippingMediaSource2 = ClippingMediaSource(m, 0, 3_000_000)
        
        player.addListener(getPlayerListener())
        player.repeatMode = Player.REPEAT_MODE_ONE
        player.prepare(clippingMediaSource1)
        player.playWhenReady = true
`

**Comment by AquilesCanta** [comment] 2020-11-27 16:16
> first parameter of Clippingmediasource cannot accept Concatenatingmediasource

This is correct. You can only pass a "leaf" media source (DashMS, HlsMS, ProgressiveMs, etc).

Can you explain what the expected behavior of ClippingMediaSource(ConcatenatingMediaSource, ...) is? Perhaps we can find an alternative way of achieving the same?

**Comment by PeOS-China** [comment] 2020-11-30 01:54
> > first parameter of Clippingmediasource cannot accept Concatenatingmediasource
> 
> This is correct. You can only pass a "leaf" media source (DashMS, HlsMS, ProgressiveMs, etc).
> 
> Can you explain what the expected behavior of ClippingMediaSource(ConcatenatingMediaSource, ...) is? Perhaps we can find an alternative way of achieving the same?

I need to link multiple videos into a video that can be played seamlessly. This video is a two-dimensional array composed of concatenatingmediasource. Multiple videos in the first dimension are played circularly and called player.next The second dimension video will be played when () player.next (), there will be a one second stuck delay. These videos are all local videos. The code is as follows:
`
       val upstreamSourceFactory = DefaultDataSourceFactory(activity, Util.getUserAgent(requireActivity(), "dongmi-device"))
        val application: BarbellApplication = requireActivity().application as BarbellApplication
        val dataSourceFactory = CacheDataSourceFactory(application.getDownloadCache(), upstreamSourceFactory)

        val playlist = ConcatenatingMediaSource()
        lesson.Exercises.forEach {
            val exerciseVideoList = ConcatenatingMediaSource(true)
            if(it.PlaybackURLs.isNotEmpty()) {
                it.PlaybackURLs.forEach { url ->
                    if(url.isNotEmpty()) {
                        val uri = Uri.parse(url)
                        val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri)
                        exerciseVideoList.addMediaSource(mediaSource)
                    }
                }

                if(exerciseVideoList.size > 0) {
                    playlist.addMediaSource(exerciseVideoList)
                }
            }
        }
       player.repeatMode = Player.REPEAT_MODE_ONE
       player.prepare(playlist)
`

**Comment by AquilesCanta** [comment] 2020-11-30 10:24
@tonihei, mind looking at this? I'm under the impression that it looks similar to [Internal ref: b/174093168]?

**Comment by tonihei** [comment] 2020-11-30 10:42
@PeOS-China  Am I right in assuming that you want to merge all video of one lesson together as if they were one single video?
  - They will be played together seamlessly.
  - The total duration as shown in our default time bar UI will show the total duration all videos in one lesson.
  - When calling `player.next()` the player will start playing the next lesson.
  - Setting `REPEAT_MODE_ONE` will loop the entire lesson.

If these are your requirements, then this is duplicate of #4868. Please follow this issue for updates.

If you have different requirements to the above, please clarify again. In particular, your second post above no longer mentions `ClippingMediaSource` and I'm not sure where the clipping requirement comes into play :)

**Comment by PeOS-China** [comment] 2020-12-01 01:37
> @PeOS-China Am I right in assuming that you want to merge all video of one lesson together as if they were one single video?
> 
> * They will be played together seamlessly.
> * The total duration as shown in our default time bar UI will show the total duration all videos in one lesson.
> * When calling `player.next()` the player will start playing the next lesson.
> * Setting `REPEAT_MODE_ONE` will loop the entire lesson.
> 
> If these are your requirements, then this is duplicate of #4868. Please follow this issue for updates.
> 
> If you have different requirements to the above, please clarify again. In particular, your second post above no longer mentions `ClippingMediaSource` and I'm not sure where the clipping requirement comes into play :)

When calling player.next (), there will be one second stuck.The data structure I set for the player is as follows：
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/8873336/100700226-eb15ed00-33d7-11eb-83a1-b2cea960e49c.png">

**Comment by tonihei** [comment] 2020-12-01 10:02
> When calling player.next (), there will be one second stuck.

This is probably related to the fact that the player needs to load and decode the next media first. There is also #3327 that tracks improving this use case.

So in summary, I think you mentioned multiple work in progress enhancements that are tracked elsewhere:
 1. Support clipping of multi-period content (for example a ConcatenatingMediaSource): #6234
 2. Support merging multiple items to one playlist item in all regards: #4868
 3. Preload next playlist item so that calling player.next() is almost instant: #3327 

Unless there is something else I'm missing, I'm closing the issue as duplicate now because these separate issues are tracked elsewhere. If there is something else I'm missing, please let me know :)

**Closed as completed by tonihei** 2020-12-01 10:02 UTC
Labels: duplicate, question
