### ISSUE TITLE
MediaSessionConnector: Having a RatingCompat in the extras will crash the system Bluetooth app

### ISSUE THREAD

**Issue by hacker1024** [google/ExoPlayer#4931] opened 2018-10-10 23:45 UTC
### Issue description
This is actually an issue because of a bug in the AOSP Bluetooth app. It's not Exoplayer's fault, but it will need to be worked around anyway.

When a `RatingCompat` object is in a MediaDescriptionCompat for the playing song's queue item, [Exoplayer will copy the object into the MediaSession extras bundle.](https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L725)

When Bluetooth is on, the Bluetooth app will try to read the extras bundle to check for additional media metadata. It will attempt to unparcel all parcels in the bundle, including the `RatingCompat`. The problem is, the Bluetooth app doesn't include the `RatingCompat` class. It will crash, with an `android.os.BadParcelableException`. [Here's a stacktrace](https://hastebin.com/igucusahun.txt).

I reported the bug to my LineageOS device maintainer, as I thought it was a bug with LineageOS. He realised the problem was in AOSP and submitted a [patch](https://android-review.googlesource.com/c/platform/packages/apps/Bluetooth/+/783256) to fix it.

It will be a long time before it's merged into AOSP, though, and older Android versions can't be fixed.

### Reproduction steps

1. Set up a MediaSession, MediaSessionConnector, and ConcatenatingMediaSource (or manually manage a queue)
2. Implement a `QueueNavigator`, and use it with the MediaSessionConnector. Make sure to add a RatingCompat object to the MediaDescriptionCompat extras bundle in the overriden function `getMediaDescription`.
3. Turn on Bluetooth
4. Play the music.

### Version of ExoPlayer being used
`dev-v2` branch, commit 7849a5e
The issue should also be there for r2.9.0.

### Device(s) and version(s) of Android being used
Tested on Pie, I don't know if the issue is there on other Android versions.

**Comment by tonihei** [comment] 2018-10-11 08:39
I'm afraid there is not much we can actually do here. There is no way for ExoPlayer to know how other apps (including the Bluetooth app) use the data. 

Do you have any suggestions on how this can be prevented? I guess the only way is not to set the rating in your app (unless you are sure the device includes the patch).

**Comment by hacker1024** [comment] 2018-10-11 23:08
Until the patch is merged into AOSP, [this bit of code](https://github.com/google/ExoPlayer/blob/r2.9.2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L733) should be removed.

**Comment by tonihei** [comment] 2018-10-12 09:09
I don't think that would solve the issue because the patch in AOSP doesn't end up automatically on all devices. That depends on the update policy of the device manufacturers. 

As I said above, if you think you can detect the existence/non-existence of the patch in your app code, then you could just decide not to set the custom rating object. Also, there would be no point allowing developers to set the rating object in the MediaSessionConnector if we don't forward it to the actual MediaMetadataCompat object in the end.

**Comment by tonihei** [comment] 2018-10-12 09:30
We noticed that MediaMetadataCompat only uses the RatingCompat class on API level 18 and below. Can you check again which Android version you are testing on?

**Comment by hacker1024** [comment] 2018-10-13 23:53
I'm 100% testing on Pie 9.0 (API 28).

> Also, there would be no point allowing developers to set the rating object in the MediaSessionConnector if we don't forward it to the actual MediaMetadataCompat object in the end.

The RatingCompat object if being forwarded from the queue item description into the MediaSession. It's still useful for developers to access the rating of queue items (which is what I'm doing), even if it isn't forwarded into the MediaSession.

**Comment by tonihei** [comment] 2018-10-15 15:49
> I'm 100% testing on Pie 9.0 (API 28).

That's strange, because if you look at the [code which sets the rating](https://android.googlesource.com/platform/frameworks/support/+/support-library-27.1.1/media-compat/java/android/support/v4/media/MediaMetadataCompat.java#827), the Bundle should not contain a RatingCompat object but a Rating object directly. Your stack trace however indicates that the bluetooth app fails because it can't read a RatingCompat object.

**Comment by ojw28** [comment] 2018-10-22 11:44
@hacker1024 - Any idea why you're seeing this on Pie given the code snippet linked to above? It seems pretty clear that `RatingCompat` is only written into the bundle on API level 18 and below?

**Comment by hacker1024** [comment] 2018-10-27 23:09
> It seems pretty clear that RatingCompat is only written into the bundle on API level 18 and below?

That's really weird... It looks like it is only written on 18 and below. However, the [stacktrace](https://hastebin.com/igucusahun.txt) I'm getting on Pie shows the RatingCompat object is still somehow making its way into the bundle.

I suppose the real bug is in the Android Support Library.
Is there some way to trace the RatingCompat object, and see which methods it's being passed to? That's the easiest way I can think of to debug this.

In case this is relevant: I'm using AndroidX, but I think the media packages haven't been refactored yet.

**Comment by ojw28** [comment] 2018-10-28 15:58
Do you think it's possible something else is parsing and then re-creating the bundle? For example [this code](https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/media/src/main/java/android/support/v4/media/session/MediaControllerCompat.java?autodive=0%2F%2F#2388)?

**Comment by hacker1024** [comment] 2018-10-30 05:05
> 
> 
> Do you think it's possible something else is parsing and then re-creating the bundle? For example [this code](https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/media/src/main/java/android/support/v4/media/session/MediaControllerCompat.java?autodive=0%2F%2F#2388)?

No, that code only runs after a rating has been set on the MediaSession. The RatingCompat object is still in the bundle if this doesn't happen.

**Comment by tonihei** [comment] 2018-10-30 11:20
You could try stepping through the code with the debugger to see if the calls from ExoPlayer are writing a RatingCompat?

**Comment by ojw28** [comment] 2018-11-23 21:33
@hacker1024 - Did you get any further with this?

**Comment by hacker1024** [comment] 2018-11-26 03:30
> Did you get any further with this?

I haven't got further, I've decided to just use booleans instead of RatingCompat objects.

> You could try stepping through the code with the debugger to see if the calls from ExoPlayer are writing a RatingCompat?

I don't have an ExoPlayer dev setup. Maybe someone who does could try this?

**Comment by ojw28** [comment] 2018-12-19 11:02
I tried and failed to reproduce this.

Interestingly, using the version of the support library ExoPlayer picks (27.1.1), you can't even get as far as the code you say we should remove. The process with the ExoPlayer in it will have already crashed at [this line](https://github.com/google/ExoPlayer/blob/r2.9.2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L713). This is due to a bug in the support library where the wrong `ClassLoader` is used. In this case the `RatingCompat` is included in the binary, but the `ClassLoader` that's used can't load it. This was fixed in support library 28.0.0, I think by [this change](https://github.com/aosp-mirror/platform_frameworks_support/commit/b3a3539e40612b6a3cc405fa4f35f111159c9f6e).

I wasn't able to reproduce the bluetooth issue even after fixing the issue with support library.

**Comment by hacker1024** [comment] 2018-12-27 07:56
> This was fixed in support library 28.0.0, I think by this change.

I'm using the Adroid Jetpack Jetifier to use AndroidX insteal of the legacy support library. This means in my app, ExoPlayer's using the latest AndroidX library.

**Comment by tonihei** [comment] 2019-01-18 17:53
Closing the issue as we don't have any more information and can't reproduce.

**Closed as completed by tonihei** 2019-01-18 17:53 UTC
Labels: question, need more info
