### ISSUE TITLE
Out of Memory Exception during playing LiveTV in Exoplayer

### ISSUE THREAD

**Issue by bonbon2106** [google/ExoPlayer#3424] opened 2017-11-03 14:44 UTC
Hi ExoPlayer team,
I create a MediaPlayer HLS apk using ExoPlayer lib (branch release-v2). And I get an error OOM while playing a Live TV channel over 3 hours. I don't know why ExoPlayer creates too many new allocation.
I'm using Amlogic S805 box with android 4.4.
 Please help me to check it.
Thanks!

```
11-03 21:17:43.329 D/DefaultAllocator( 1432): create new allocation [2949] with size is 65536
11-03 21:17:43.339 D/DefaultAllocator( 1432): create new allocation [2950] with size is 65536
11-03 21:17:43.349 D/DefaultAllocator( 1432): create new allocation [2951] with size is 65536
11-03 21:17:43.359 D/DefaultAllocator( 1432): create new allocation [2952] with size is 65536
11-03 21:17:43.369 D/DefaultAllocator( 1432): create new allocation [2953] with size is 65536
11-03 21:17:43.449 I/dalvikvm-heap( 1432): Clamp target GC heap from 195.951MB to 192.000MB
11-03 21:17:43.449 D/dalvikvm(  519): WAIT_FOR_CONCURRENT_GC blocked 48ms
11-03 21:17:43.449 I/dalvikvm-heap( 1432): Forcing collection of SoftReferences for 65552-byte allocation
11-03 21:17:43.479 I/dalvikvm-heap( 1432): Clamp target GC heap from 195.951MB to 192.000MB
11-03 21:17:43.479 E/dalvikvm-heap( 1432): Out of memory on a 65552-byte allocation.
11-03 21:17:43.479 I/dalvikvm( 1432): "Loader:HlsSampleStreamWrapper" prio=5 tid=15 RUNNABLE
11-03 21:17:43.479 I/dalvikvm( 1432):   | group="main" sCount=0 dsCount=0 obj=0x4177c320 self=0x72bbdfb8
11-03 21:17:43.479 I/dalvikvm( 1432):   | sysTid=1449 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=1924916240
11-03 21:17:43.479 I/dalvikvm( 1432):   | state=R schedstat=( 203828428000 126906821000 371525 ) utm=16242 stm=4140 core=2
11-03 21:17:43.479 I/dalvikvm( 1432):   at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:~108)
11-03 21:17:43.479 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:614)
11-03 21:17:43.479 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
11-03 21:17:43.479 I/dalvikvm( 1432):   at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:114)
11-03 21:17:43.479 I/dalvikvm( 1432):   at com.google.android.exoplayer2.extractor.ts.PesReader.consume(PesReader.java:132)
11-03 21:17:43.479 I/dalvikvm( 1432):   at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:296)
11-03 21:17:43.479 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:266)
11-03 21:17:43.479 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:202)
11-03 21:17:43.479 I/dalvikvm( 1432):   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
11-03 21:17:43.479 I/dalvikvm( 1432):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-03 21:17:43.479 I/dalvikvm( 1432):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-03 21:17:43.479 I/dalvikvm( 1432):   at java.lang.Thread.run(Thread.java:841)
11-03 21:17:43.479 I/dalvikvm( 1432): 
11-03 21:17:43.529 I/dalvikvm-heap( 1432): Clamp target GC heap from 195.887MB to 192.000MB
11-03 21:17:43.569 I/dalvikvm-heap( 1432): Clamp target GC heap from 195.949MB to 192.000MB
11-03 21:17:43.569 I/dalvikvm-heap( 1432): Forcing collection of SoftReferences for 65552-byte allocation
11-03 21:17:43.599 I/dalvikvm-heap( 1432): Clamp target GC heap from 195.949MB to 192.000MB
11-03 21:17:43.599 E/dalvikvm-heap( 1432): Out of memory on a 65552-byte allocation.
11-03 21:17:43.599 I/dalvikvm( 1432): "Loader:HlsSampleStreamWrapper" prio=5 tid=15 RUNNABLE
11-03 21:17:43.599 I/dalvikvm( 1432):   | group="main" sCount=0 dsCount=0 obj=0x4177c320 self=0x72bbdfb8
11-03 21:17:43.599 I/dalvikvm( 1432):   | sysTid=1449 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=1924916240
11-03 21:17:43.599 I/dalvikvm( 1432):   | state=R schedstat=( 203926697000 126922503000 371588 ) utm=16250 stm=4142 core=2
11-03 21:17:43.599 I/dalvikvm( 1432):   at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:~108)
11-03 21:17:43.599 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:614)
11-03 21:17:43.599 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
11-03 21:17:43.599 I/dalvikvm( 1432):   at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:114)
11-03 21:17:43.599 I/dalvikvm( 1432):   at com.google.android.exoplayer2.extractor.ts.PesReader.consume(PesReader.java:132)
11-03 21:17:43.599 I/dalvikvm( 1432):   at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:296)
11-03 21:17:43.599 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:266)
11-03 21:17:43.599 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:202)
11-03 21:17:43.599 I/dalvikvm( 1432):   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
11-03 21:17:43.599 I/dalvikvm( 1432):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-03 21:17:43.599 I/dalvikvm( 1432):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-03 21:17:43.599 I/dalvikvm( 1432):   at java.lang.Thread.run(Thread.java:841)
11-03 21:17:43.599 I/dalvikvm( 1432): 
11-03 21:17:44.719 I/dalvikvm-heap( 1432): Clamp target GC heap from 195.887MB to 192.000MB
11-03 21:17:44.779 I/dalvikvm-heap( 1432): Clamp target GC heap from 195.949MB to 192.000MB
11-03 21:17:44.789 I/dalvikvm-heap( 1432): Forcing collection of SoftReferences for 65552-byte allocation
11-03 21:17:44.849 I/dalvikvm-heap( 1432): Clamp target GC heap from 195.949MB to 192.000MB
11-03 21:17:44.849 E/dalvikvm-heap( 1432): Out of memory on a 65552-byte allocation.
11-03 21:17:44.849 I/dalvikvm( 1432): "Loader:HlsSampleStreamWrapper" prio=5 tid=15 RUNNABLE
11-03 21:17:44.849 I/dalvikvm( 1432):   | group="main" sCount=0 dsCount=0 obj=0x4177c320 self=0x72bbdfb8
11-03 21:17:44.849 I/dalvikvm( 1432):   | sysTid=1449 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=1924916240
11-03 21:17:44.849 I/dalvikvm( 1432):   | state=R schedstat=( 204126625000 126969378000 372119 ) utm=16267 stm=4145 core=2
11-03 21:17:44.849 I/dalvikvm( 1432):   at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:~108)
11-03 21:17:44.849 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:614)
11-03 21:17:44.849 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:553)
11-03 21:17:44.849 I/dalvikvm( 1432):   at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:114)
11-03 21:17:44.849 I/dalvikvm( 1432):   at com.google.android.exoplayer2.extractor.ts.PesReader.consume(PesReader.java:132)
11-03 21:17:44.849 I/dalvikvm( 1432):   at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:296)
11-03 21:17:44.849 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:266)
11-03 21:17:44.849 I/dalvikvm( 1432):   at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:202)
11-03 21:17:44.849 I/dalvikvm( 1432):   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
11-03 21:17:44.849 I/dalvikvm( 1432):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-03 21:17:44.849 I/dalvikvm( 1432):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-03 21:17:44.849 I/dalvikvm( 1432):   at java.lang.Thread.run(Thread.java:841)
```

**Comment by AquilesCanta** [comment] 2017-11-03 14:57
Are you able to reproduce this in the Demo app? If so, would you kindly provide a link to the stream at dev.exoplayer@gmail.com?

**Comment by bonbon2106** [comment] 2017-11-04 03:13
Hi AquilesCanta,

the Demo app has the same as error. You can check this error on the following channel:

http://cmghlslive-i.akamaihd.net:80/hls/live/224709/KOKI/master.m3u8

I really don't understand why you create the allocate() function in file 

DefaultAllocator.java :

@Override
public synchronized Allocation allocate() {
  allocatedCount++;
  Allocation allocation;
  if (availableCount > 0) {
    allocation = availableAllocations[--availableCount];
    availableAllocations[availableCount] = null;
  } else {
    allocation = new Allocation(new byte[individualAllocationSize], 0);
  }
  return allocation;
}

If the allocation is faster than release, ExoPlayer always creates the new allocation, so it will use more and more memory.

Thanks & Best regards!

**Comment by ojw28** [comment] 2017-11-05 21:27
The idea is allocation shouldn't happen faster than release...!

I tried playing the stream provided using the latest `release-v2`, which is `r2.5.4`, and could not reproduce after ~3.5 hours of playback. Could you please specify exactly which version of ExoPlayer you're using? `release-v2` is not a version; are you sure you've got an up to date copy of it? Also, exactly how do you reproduce the problem in the demo app? Simply playing the provided stream did not reproduce the issue for me.

**Comment by ojw28** [comment] 2017-11-23 20:03
Closing due to lack of actionable information.

**Closed as completed by ojw28** 2017-11-23 20:03 UTC
Labels: need more info
