### ISSUE TITLE
Live Smoothstreaming request manifest every 5 seconds

### ISSUE THREAD

**Issue by juanpef** [google/ExoPlayer#8912] opened 2021-05-07 12:51 UTC
Hello,

I have a streming application based on Smoothstreaming. I'm using ExoPlayer 2.7.3. We faced an issue because Exoplayer is requesting the manifest every 5 seconds, so it is affecting to our servers. Is there any way to modify this time?

Regards

**Comment by christosts** [comment] 2021-05-07 13:14
Just to make sure we're talking about the same thing, your application is playing a live stream, right?

I see the 5 seconds interval is hard coded and I can't see a clear way of overriding it.

https://github.com/google/ExoPlayer/blob/4b531dcc5211ef9cb1c2adea5c12642f549c4c78/library/smoothstreaming/src/main/java/com/google/android/exoplayer2/source/smoothstreaming/SsMediaSource.java#L242

@ojw28 is there a way to modify the manifest refresh interval for smooth streaming live streams that I can't see? In 2.7.3 in particular.

**Comment by juanpef** [comment] 2021-05-10 06:48
Thank you for your answer.

Yes, our application is playing live stream, using Smooth Streaming. If we modify this MINIMUM_MANIFEST_REFRESH_PERIOD_MS to 1 minute, for example, then manifest will be requested every minute? It would help tou our platform (server side) performance.

**Comment by ojw28** [comment] 2021-05-10 09:33
To reduce the frequency of manifest refreshes in a sensible way, I think it would be necessary for us to support https://github.com/google/ExoPlayer/issues/855. SmoothStreaming is pretty low priority for us at the moment because DASH and HLS are much more widely used, so it's unlikely we'll look at this any time soon.

Marking as a duplicate of https://github.com/google/ExoPlayer/issues/855.

**Closed as completed by ojw28** 2021-05-10 09:33 UTC
Labels: duplicate
