### ISSUE TITLE
playback problems after upgrade

### ISSUE THREAD

**Issue by AntonAndev** [google/ExoPlayer#5582] opened 2019-02-28 07:55 UTC
Hello, 

[REQUIRED] Issue description
I updated the ExiPlayer library version to 2.8.4 as the last one, about which the Gradle informs,
 from 2.4.4 for playing live HLS streams. After that, I began to receive complaints from users of some devices, mainly from TV set-top boxes. 

The user of device H96Pro reported a problem:
Couldn't create decoder for OMX.amlogic.avc.decoder.awesome.
The user of device X92 reported a problem:
Video freezing or black screen, but sound plays
The user of device Nokia 6, Android 9 reported a problem :
instant application crash

I do not see any errors in the Crashlytics and Android Vitals regarding the errors of the ExoPlayer.
I can't reproduce it on my devices Samsung Galaxy S9, Sony Z3 Compact.

I collect feedback from users and ask them questions and will update this topic
[REQUIRED] Reproduction steps

Run app on the X92, Beelink GT1 Ultimate devices, play HLS after showing Interstitial ad.

[REQUIRED] Version of ExoPlayer being used
2.8.4
Gradle:
implementation 'com.google.android.exoplayer:exoplayer:2.8.4'
Proguard rules:
-keep class com.google.android.exoplayer.** {*;}
-keep class com.google.android.exoplayer2.** {*;}

**Comment by AntonAndev** [comment] 2019-02-28 11:23
With help from 2 users with devices X92 and Beelink GT1 Ultimate we have found following:
this problem with video codec occurs after showing Admob interstitial ads if we close ads by tapping back button. **There is some problem with ExoPlayer reinitialization**. Before showing ad OnPause() and OnStop() are called. We destroy ExoPlayer. After showing ad we recreate ExoPlayer in the OnResume() method:
```
@Override
    public void onStart() {
        super.onStart();
        if (Util.SDK_INT > 23) {
            initExoPlayer();
        }
    }

    @Override
    protected void onPause() {
        super.onPause();
        if (Util.SDK_INT <= 23) {
            if (mFullScreen && !adWasShown) {
                setFullScreen();
            }
            simpleExoPlayerView.setVisibility(View.INVISIBLE);
            releaseExoPlayer();
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
 if ((Util.SDK_INT <= 23 || exoPlayer == null)) {
            initExoPlayer();
        }
}
 @Override
    protected void onStop() {
        super.onStop();

        if (Util.SDK_INT > 23) {
            if (mFullScreen  && !adWasShown) {
                setFullScreen();
            }
            simpleExoPlayerView.setVisibility(View.INVISIBLE);
            releaseExoPlayer();
        }
}

 private void releaseExoPlayer() {
        if (exoPlayer != null) {
            exoPlayer.stop();
            exoPlayer.release();
            exoPlayer = null;
            trackSelector = null;
            dataSourceFactory = null;
            bandwidthMeter = null;
            mainHandler = null;
        }
    }

private void initExoPlayer() {

        if (exoPlayer == null) {
            mainHandler = new Handler();
            bandwidthMeter = new DefaultBandwidthMeter();

            dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, userAgent), bandwidthMeter);

            TrackSelection.Factory adaptiveTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
            trackSelector = new DefaultTrackSelector(adaptiveTrackSelectionFactory);

            exoPlayer = ExoPlayerFactory.newSimpleInstance(context, trackSelector);
            //exoPlayer.addListener(this);
            // 2.8.4
            exoPlayer.addListener(new PlayerEventListener());
            simpleExoPlayerView.setPlayer(exoPlayer);
        }
    }
```

**Comment by andrewlewis** [comment] 2019-02-28 11:39
It sounds like resources may not be getting released before the app resumes. I'll follow up with the AdMob team to check how they release resources.

If you can get the output of `adb bugreport` just after the error that might help confirm this is what's going on. You could also try introducing a pause before trying to initialize the player as a workaround.

**Comment by AntonAndev** [comment] 2019-02-28 11:48
Hello Andrew. One user also found an interesting moment. If he closes ad by pressing Back button, he has codec issue, if he close ad by pressing X button, no problem with codec

**Comment by AntonAndev** [comment] 2019-02-28 12:18
Also it depends on type of ad which was displayed.

**Comment by JeanCarlosChavarriaHughes** [comment] 2019-03-01 06:41
@Andevity  curious about the codec issue. Can you please provide the full stack trace or debug logs of the codec issue) ?. Some time ago I remember to have seem a similar issue in FireTV (No the same Exo player core but very similar).

**Comment by andrewlewis** [comment] 2019-03-01 08:26
@Andevity The workaround suggestion from the AdMob team is to post player initialization to the main thread, instead of doing it directly in the lifecycle method. (After closing the ad various cleanup tasks have been queued on the main thread and posting will ensure player initialization happens after they've run.)

**Comment by AntonAndev** [comment] 2019-03-01 10:51
@andrewlewis I did it as in the example project. I am afraid to do something wrong. Could you please provide an example how to initialise and to destroy?

**Comment by andrewlewis** [comment] 2019-03-04 17:03
I think the suggestion is to do something like:

```
  @Override
  public void onResume() {
    super.onResume();
    new Handler().post(this::initializePlayer);
  }
```

... instead of calling initializePlayer directly. The hypothesis is that somehow AdMob's cleanup tasks end up being queued on main thread after your `onResume` lifecycle method is queued. For the record, properly fixing the issue by having the ad player releasing synchronously on the main thread is tracked by [internal: b/127281295].

**Comment by AntonAndev** [comment] 2019-03-05 16:49
Hello, I tried to add Handler, send new version to the user with Beelink GT1 Ultimate device, he said about same error with codec. How can we get all dump from user device?

**Comment by andrewlewis** [comment] 2019-03-07 13:59
@Andevity If you can reproduce this on a device with debugging enabled, the output of `adb bugreport` just after seeing the error may help us confirm what's going on.

**Comment by andrewlewis** [comment] 2019-05-05 18:44
Closing as this seems to be an AdMob issue rather than an ExoPlayer issue. If you can provide a bug report we can take a look anyway.

**Closed as completed by andrewlewis** 2019-05-05 18:44 UTC
Labels: question
