### ISSUE TITLE
[Question] How to get the startTime and endTime from TextRenderer.Output cues

### ISSUE THREAD

**Issue by sergiomartinez4** [google/ExoPlayer#3563] opened 2017-12-07 19:28 UTC
Hi there!
I'm currently implementing the TextRenderer.Output to received the List of Cues for WebVtt captions, and then I'm displaying those captions in our custom caption view.
The problem is that WebvttCue class is package-private so we can't cast it, so that we can use the startTime and endTime.
Is there a reason to keep that class as package-private? What alternative do I have?

Thanks!

**Comment by botaydotcom** [comment] 2017-12-08 10:35
Hi @sergiomartinez4 ,
Could you explain your use-case clearer, and why do you need to get access to startTime and endTime in order to display these Cues in your custom view?
By design, the player will parse these time values from underlying stream, and perform calculations internally to find out when to display these subtitles with respect to other tracks (video/audio etc...). Then the TextRenderer will output the List<Cue> to be displayed at the right time, and the client application only needs to handle displaying these Cues immediately upon receiving them. Attempting to parse startTime and endTime, without understanding fully the timing model of the player, may lead to wrong presentation time.

Please elaborate more on your use case and the reasoning behind, and we can answer your question better. Thank you very much.

With that said, because of other changes, WebvttCue class has been made public in dev-v2 branch, and may be released as such in the future (I don't know when). However, unless it's really necessary, I don't think you should rely on that given the problem I described.

**Comment by sergiomartinez4** [comment] 2017-12-08 15:15
@botaydotcom thanks for the reply.

The real concern is not about when to display them, as we display them as soon as the onCues method is called, but it's about when to stop displaying the captions. A caption duration property in the Cue object will be enough for our purposes.

Without any sense of time, we can either just stop displaying one caption after the next one appears or we can set a default duration timeout (or a combination both). We could also adjust the duration depending on the length of the text and with this approach we can only hope to get a good approximation, but it wouldn't be the exact times as specified in the Webvtt document.

Having the public WebvttCue will make it easier with our current implementation, we only need to cast the Cue to WebvttCue and get the extra info, but If I'm missing something or there's an easier or better way to do it, I'm happy to try it out.

Best!

**Comment by botaydotcom** [comment] 2017-12-08 15:31
Hi @sergiomartinez4 ,
I think I understand your idea, but it is unfortunately it is not our intention behind `TextOutput` interface.
The idea with `TextOutput` is whenever the player sends a Cue list, the application should just take it and display as it is. If any of the cues are changed (some added, some removed etc...), the player will invoke that method again with a new Cue list reflecting the new state. So you don't need to time the display yourself or find out when to remove the displayed captions. The next time you receive a new list of cues, just remove everything and re-display the whole list accordingly (note that the list might be null if there's nothing to be displayed on the screen).

I think an easy way to follow this is to check out `com.google.android.exoplayer2.ui.SubtitleView`, which follows this approach. Hope that help.

**Comment by sergiomartinez4** [comment] 2017-12-08 20:11
@botaydotcom, removing the captions when getting empty cues did the trick. It makes sense now.
Thanks a lot for the help.

**Comment by botaydotcom** [comment] 2017-12-11 10:41
Cool! Glad that it helps.

**Closed as completed by botaydotcom** 2017-12-11 10:41 UTC
Labels: question
