### ISSUE TITLE
Failure parsing AAC Audio specific config

### ISSUE THREAD

**Issue by florinmandache** [google/ExoPlayer#1229] opened 2016-02-03 16:11 UTC
```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                           at com.google.android.exoplayer.util.ParsableBitArray.readBits(ParsableBitArray.java:162)
                                                           at com.google.android.exoplayer.util.CodecSpecificDataUtil.parseAacAudioSpecificConfig(CodecSpecificDataUtil.java:110)
                                                           at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseAudioSampleEntry(AtomParsers.java:846)
                                                           at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:534)
                                                           at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:70)
                                                           at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:289)
                                                           at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:237)
                                                           at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:122)
                                                           at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:725)
                                                           at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                           at java.lang.Thread.run(Thread.java:818)
```

on a video file:

```
 Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:45:00.03, start: 0.000000, bitrate: 771 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x576 [SAR 64:45 DAR 16:9], 630 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 135 kb/s (default)
    Metadata:
      handler_name    : SoundHandler


Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 248 MiB
Duration                                 : 45mn 0s
Overall bit rate mode                    : Variable
Overall bit rate                         : 772 Kbps
Writing application                      : Lavf56.40.101

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.0
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 44mn 58s
Bit rate                                 : 631 Kbps
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.061
Stream size                              : 203 MiB (82%)

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 45mn 0s
Bit rate mode                            : Variable
Bit rate                                 : 135 Kbps
Maximum bit rate                         : 138 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 43.5 MiB (18%)
Language                                 : English
```

**Comment by ojw28** [comment] 2016-02-03 18:30
You will have to provide us with sample content that reproduces the issue in order for us to take a look. Please either post it here, or mail it to `dev.exoplayer@gmail.com` (and update this issue so we know to look out for it :)). Thanks!

**Comment by ojw28** [comment] 2016-02-14 23:34
Closing due to insufficient information.

**Closed by ojw28** 2016-02-14 23:34 UTC
Labels: need more info
