### ISSUE TITLE
Mp4 Clear content stop working with 2.9.6

### ISSUE THREAD

**Issue by rajeshghosh1978** [google/ExoPlayer#5815] opened 2019-04-29 18:33 UTC
### [REQUIRED] Content description
I am unable to play a trailer (Mp4), which is a clear content with 2.9.6 Release v2. The same content is working with 2.9.3. I didn't try with other versions like 2.9.5 and 2.9.4.

I have checked the same through Charles, where I can see first call was successful with a 200 Ok, but after that player trying to get same content appending a header "Range: bytes 127000-" which cause failure from the server due to 416 error. 

Here is the exception I am getting

`2019-04-29 12:33:25.150 22357-22366/com.google.android.exoplayer2.demo I/zygote64: Do full code cache collection, code=248KB, data=207KB
2019-04-29 12:33:25.151 22357-22366/com.google.android.exoplayer2.demo I/zygote64: After code cache collection, code=242KB, data=165KB
2019-04-29 12:33:25.290 22357-22357/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init 8900f67 [ExoPlayerLib/2.9.6] [dreamqlteue, SM-G950U1, samsung, 26]
2019-04-29 12:33:25.294 22357-22357/com.google.android.exoplayer2.demo D/EventLogger: state [0.00, 0.00, window=0, true, BUFFERING]
2019-04-29 12:33:25.299 22357-28518/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-04-29 12:33:25.299 22357-28518/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-04-29 12:33:25.302 22357-22357/com.google.android.exoplayer2.demo D/ViewRootImpl@91a3a80[PlayerActivity]: setView = DecorView@cfe18b9[PlayerActivity] TM=true MM=false
2019-04-29 12:33:25.304 22357-22357/com.google.android.exoplayer2.demo D/ViewRootImpl@44326f0[SampleChooserActivity]: MSG_WINDOW_FOCUS_CHANGED 0
2019-04-29 12:33:25.306 22357-22357/com.google.android.exoplayer2.demo D/EventLogger: timelineChanged [0.01, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
2019-04-29 12:33:25.306 22357-22357/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
2019-04-29 12:33:25.306 22357-22357/com.google.android.exoplayer2.demo D/EventLogger:   window [?, false, false]
2019-04-29 12:33:25.306 22357-22357/com.google.android.exoplayer2.demo D/EventLogger: ]
2019-04-29 12:33:25.307 22357-22357/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodCreated [0.01, 0.00, window=0, period=0]
2019-04-29 12:33:25.307 22357-22357/com.google.android.exoplayer2.demo D/EventLogger: loading [0.01, 0.00, window=0, period=0, true]
2019-04-29 12:33:25.314 22357-22357/com.google.android.exoplayer2.demo D/ViewRootImpl@91a3a80[PlayerActivity]: dispatchAttachedToWindow
2019-04-29 12:33:25.327 22357-22357/com.google.android.exoplayer2.demo V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
2019-04-29 12:33:25.327 22357-22357/com.google.android.exoplayer2.demo D/ViewRootImpl@91a3a80[PlayerActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1080,2220] result=0x7 surface={valid=true 511758331904} changed=true
2019-04-29 12:33:25.336 22357-22426/com.google.android.exoplayer2.demo D/OpenGLRenderer: eglCreateWindowSurface = 0x772804db10
2019-04-29 12:33:25.339 22357-22366/com.google.android.exoplayer2.demo I/zygote64: Do partial code cache collection, code=250KB, data=181KB
2019-04-29 12:33:25.339 22357-22366/com.google.android.exoplayer2.demo I/zygote64: After code cache collection, code=250KB, data=181KB
2019-04-29 12:33:25.339 22357-22366/com.google.android.exoplayer2.demo I/zygote64: Increasing code cache capacity to 1024KB
2019-04-29 12:33:25.343 22357-22357/com.google.android.exoplayer2.demo D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity@bcf14fe@0) android.view.SurfaceView{bcf14fe V.E...... ......ID 0,0-1080,2148}
2019-04-29 12:33:25.359 22357-22357/com.google.android.exoplayer2.demo V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
2019-04-29 12:33:25.359 22357-22357/com.google.android.exoplayer2.demo D/SurfaceView: surfaceCreated 1 android.view.SurfaceView{bcf14fe V.E...... ......ID 0,0-1080,2148}
2019-04-29 12:33:25.360 22357-22357/com.google.android.exoplayer2.demo D/SurfaceView: surfaceChanged (1080,2148) 1 android.view.SurfaceView{bcf14fe V.E...... ......ID 0,0-1080,2148}
2019-04-29 12:33:25.360 22357-22357/com.google.android.exoplayer2.demo D/EventLogger: surfaceSizeChanged [0.07, 0.00, window=0, period=0, 1080, 2148]
2019-04-29 12:33:25.363 22357-22357/com.google.android.exoplayer2.demo D/ViewRootImpl@91a3a80[PlayerActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
2019-04-29 12:33:25.363 22357-22357/com.google.android.exoplayer2.demo D/ViewRootImpl@91a3a80[PlayerActivity]: MSG_WINDOW_FOCUS_CHANGED 1
2019-04-29 12:33:25.365 22357-22357/com.google.android.exoplayer2.demo V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@a05845f nm : com.google.android.exoplayer2.demo ic=null
2019-04-29 12:33:25.365 22357-22357/com.google.android.exoplayer2.demo I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-04-29 12:33:25.381 22357-22357/com.google.android.exoplayer2.demo D/ViewRootImpl@91a3a80[PlayerActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x3 surface={valid=true 511758331904} changed=false
2019-04-29 12:33:25.412 22357-22426/com.google.android.exoplayer2.demo D/OpenGLRenderer: eglDestroySurface = 0x7727d30600
2019-04-29 12:33:25.412 22357-22426/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllActiveAnimators on 0x772815b000 (ExpandableListView) with handle 0x77360fe780
2019-04-29 12:33:25.433 22357-22357/com.google.android.exoplayer2.demo D/ViewRootImpl@44326f0[SampleChooserActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x5 surface={valid=false 0} changed=true
2019-04-29 12:33:25.833 22357-22357/com.google.android.exoplayer2.demo D/ViewRootImpl@44326f0[SampleChooserActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=false 0} changed=false
2019-04-29 12:33:25.920 22357-28518/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-04-29 12:33:25.921 22357-28518/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-04-29 12:33:26.069 22357-22357/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.78, 0.00, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:303)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-04-29 12:33:26.070 22357-28518/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-04-29 12:33:26.252 22357-22357/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.96, 0.00, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:303)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-04-29 12:33:27.275 22357-28518/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-04-29 12:33:27.279 22357-28518/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-04-29 12:33:27.490 22357-22357/com.google.android.exoplayer2.demo E/EventLogger: internalError [2.19, 0.00, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:303)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-04-29 12:33:29.512 22357-28518/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-04-29 12:33:29.517 22357-28518/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-04-29 12:33:29.751 22357-22357/com.google.android.exoplayer2.demo E/EventLogger: internalError [4.46, 0.00, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:303)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-04-29 12:33:29.754 22357-28517/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:303)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-04-29 12:33:29.757 22357-22357/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodReleased [4.46, 0.00, window=0, period=0]
2019-04-29 12:33:29.760 22357-22357/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [4.47, 0.00, window=0]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:351)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:303)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-04-29 12:33:29.762 22357-22357/com.google.android.exoplayer2.demo D/EventLogger: loading [4.47, 0.00, window=0, false]
2019-04-29 12:33:29.764 22357-22357/com.google.android.exoplayer2.demo D/EventLogger: state [4.47, 0.00, window=0, true, IDLE]
`

### [REQUIRED] Link to test content
I can send you the content securely. Please provide me your email address.

### [REQUIRED] Version of ExoPlayer being used
Release v2 - 2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used

No specific device required. I have tried with Galaxy S8 with Android 8.0.0

**Comment by tonihei** [comment] 2019-04-30 09:58
Can you please send the content to dev.exoplayer@gmail.com?

**Comment by rajeshghosh1978** [comment] 2019-04-30 14:04
@tonihei I have sent you the sample mp4 file. Please let me know your findings.

**Comment by tonihei** [comment] 2019-04-30 15:11
I tested the provided content on the latest release (2.10.0-alpha1) and it plays perfectly fine. Could you check the current release to see if it's fixed?

**Comment by rajeshghosh1978** [comment] 2019-04-30 15:22
I have just tested with the latest code (The last commit says "Fix bad merge"), still not working for me. Maybe the server you hosted the sample.mp4 support "Range" parameter. Could you share the same link you created to test if it is not a local server?

**Comment by tonihei** [comment] 2019-04-30 15:28
I tested to play the file locally. Can you provide a link to the file on the test server where it isn't working?

**Comment by rajeshghosh1978** [comment] 2019-04-30 15:36
Here is the URL : http://pdl.verizon.net/previews/VUBM0000000073169101P_EM-iPHONE.mp4

**Comment by tonihei** [comment] 2019-04-30 16:32
Thanks. I was now able to reproduce the problem on 2.9.6. But it seems to be fixed in the latest release already. So nothing else needs to be done here and I'll close the issue.

**Closed as completed by tonihei** 2019-04-30 16:32 UTC
Labels: need more info, content not playing

**Comment by rajeshghosh1978** [comment] 2019-04-30 18:19
@tonihei : As I told you earlier, I have the latest Release V2 codebase and I am able to reproduce this issue easily. Are you talking about the latest dev branch?

In any case, we can't upgrade to the new release, as there are a significant amount of changes has been done in the download section. Could you please guide me to fix the same in 2.9.6 version?

**Comment by tonihei** [comment] 2019-05-01 11:32
I'm not sure what exactly fixed it from 2.9.6. to 2.10.0 (could for example be related to #5694), but I would recommend to either wait until the upgrade to 2.10.0 can be done on your side or downgrade to 2.9.3 in the meantime.
