### ISSUE TITLE
getDuration() returns -1 if video on server

### ISSUE THREAD

**Issue by don11995** [google/ExoPlayer#910] opened 2015-10-31 19:25 UTC
Hi, I have some videos on my server and I want play them on phone, but have some problems:
1. getDuration() returns always -1. I need duration to link it with the progressbar
2. seekTo() works sometimes incorrectly. Say, I want to seek to 10 seconds, I call seekTo(10000), but video begin play from 5th-7th second. This isn't too important to me, it's more a remark.
What I'm doing wrong? Or this function not work properly yet? Thanks a lot.

**Comment by ojw28** [comment] 2015-11-02 16:18
Most likely the media you're playing doesn't define its duration or an index to enable seeking within it. It it did, then getDuration() would be expected to work correctly, as would seeking. In any case, you'd need to provide a link to the media or at least tell us what type of media you're trying to play, for us to be sure.

**Comment by don11995** [comment] 2015-11-02 20:37
I can't provide video from my server because it has Auth2.0 and dynamic links that changes every 4 seconds, but I will find some videos where this error persists and write it here tomorrow.

**Comment by don11995** [comment] 2015-11-04 09:17
ok, I tried some other videos on different servers and downloaded local - seek and getDuration() not work at all on all videos (no matter what format) - duration always -1, seekTo always sets the position to 0 and video plays from begining.

**Comment by don11995** [comment] 2015-11-04 20:08
I found issue: my video from server perceives as a stream and that's why getDuration returns -1. But my server returns Content-Length in response header (in bytes). How I can attach this length to player and get getDuration to work?

**Comment by ojw28** [comment] 2015-11-05 03:21
The content length (size) isn't the same as the duration (time). My answer above still applies (i.e. the media you're playing probably doesn't define its duration or an index to enable seeking within it). You need to either confirm this yourself, provide a test stream that reproduces the issue, or at least indicate what type of media you're playing.

**Comment by don11995** [comment] 2015-11-05 08:48
For example: stream has next format 
```
2015-11-05 10:15:50.129 StalkerClient[36934:2933451] codec->name h264
2015-11-05 10:15:50.129 StalkerClient[36934:2933451] codec->long_name H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
```
ExoPlayer can't seek within it and it's duration is -1, but ffmpeg, for example, getDuration works normally and returns the microseconds of the stream. 
We devoloping app for Android and iOS. In  iOS we using only ffmpeg, because no normal alternatives exist. But on iOS duration and seek work normal.
Also I tried VLC and it returns duration 0, but seek works, while in ExoPlayer no. Sorry for my English.
```
http://st1.infomir.com.ua/media/st1/00:00:00:01:00:02/9937.mpg
```
Link for example stream, but I don't know will it expire or not (our server sometimes refreshing all the links).

**Comment by ojw28** [comment] 2015-11-06 13:47
Closing due to lack of information needed to help. The link has expired.

**Closed by ojw28** 2015-11-06 13:47 UTC
Labels: need more info

**Comment by londhenamdev** [comment] 2016-11-29 13:52
I am also facing the same issue like whenever I will play the HLS url(m3u8) then it returns UNKNOWN_TIME (-1).  I am using a Live stream URL. When I am going to play the same stream in other player, then it shows the amount of duration that has been already played. So, Kindly provide us work around to get cat-up duration in case of live stream URL.
