### ISSUE TITLE
Is it possible to preload multiple streams with Exoplayer and Play multiple Videos simultaneously

### ISSUE THREAD

**Issue by faisalvv** [google/ExoPlayer#7148] opened 2020-03-26 19:03 UTC
I want to start precahing next song in ConcatenatingMediaSource when the current song is played 10 second(or any other duration).How can I achieve that?
By default exoplayer starts precahing when current song is near its end.
Moreover what is the precahing policy, like can I define how many segments to precache for next song

**Comment by ojw28** [comment] 2020-03-27 23:53
This is a duplicate of https://github.com/google/ExoPlayer/issues/3327.

**Closed as completed by ojw28** 2020-03-27 23:53 UTC
Labels: duplicate
