### ISSUE TITLE
How to switch FfmpegAudioRenderer and MediaCodecAudioRenderer by play hls(m3u8) ?

### ISSUE THREAD

**Issue by liuguangsen** [google/ExoPlayer#11115] opened 2023-04-13 06:34 UTC
I used exoPlayer (with ffmpeg extension open) to play a link to my m3u8 like this . I found that ExoPlayer always uses FfmpegAudioDecoder and cannot switch to MediaCodecAudioRenderer?

#EXTM3U
#EXT-X-VERSION:7
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.34"
000_00000.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=320000,CODECS="mp4a.40.34"
001_00000.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=999000,CODECS="mp4a.40.34"
002_00000.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=1000000,CODECS="flac"
003_00000.m3u8

**Comment by icbaker** [comment] 2023-04-13 08:34
Duplicate of https://github.com/androidx/media/issues/317

**Closed as completed by icbaker** 2023-04-13 08:34 UTC
Labels: duplicate
