### ISSUE TITLE
Download state is changing into complete before content is fully downloaded

### ISSUE THREAD

**Issue by vimal1695** [google/ExoPlayer#8429] opened 2021-01-05 13:09 UTC
Good evening ,

I'm trying to download a content for offline playback but sometimes download will get stuck at 99% because state of the download item gets complete even though there is few more bytes to download.
This issue occur when trying to download multiple items.
Content length : 76169163
Content downloaded :  76167168
Progress: 99.3%

![Image4](https://user-images.githubusercontent.com/11749730/103649661-d9020e00-4f84-11eb-8d67-981061e67b7a.png)

**Comment by andrewlewis** [comment] 2021-01-05 13:23
@marcbaechinger Please could you take a look?

**Comment by marcbaechinger** [comment] 2021-01-07 17:08
It's hard to say what the reason for this behavior is from the information available. When trying with the demo app I can not repro this. Assuming you are downloading progressive media I would expect that the `CacheWriter` reads from the upstream data source either until the given content length has been downloaded or until the resource the data source is reading from reaches the end of the stream. When finished without error it is marked as completed.

Without more information I can only speculate. The content length is taken from the response header of the server so it might be worth to check whether the reported length matches the actual length of the source.
Can you provide me with a url of a download that fails this way? That would be best for me to try to repro.

Also, can you give a bit of more details how this behavior is actually a problem for your app? :) 

You are saying that the download is reported as completed, so you are aware that the download is done and you can update/remove notifications at this moment. That should not be an issue. 

Can you play the downloaded content offline afterwards? Is there a problem at the very end of playback like the cache can not deliver the last few bytes and the player goes into STATE_BUFFERING?

Best would be you can repro this for the same resource multiple times and then you can send me the uri to that resource.

**Comment by vimal1695** [comment] 2021-01-28 02:03
Due to customer privacy terms , i am unable to share you the uri.
Right now i always update status of download to complete only if the content length equal to downloaded length.
This is hard to reproduce and also same asset will be able to download without any issue. This happen randomly with any assets. 
I will get source error if try to play incomplete download asset.

**Comment by ojw28** [comment] 2021-04-01 16:18
There's nothing actionable for us to do here, since there are no reproduction steps. Closing.

**Closed as completed by ojw28** 2021-04-01 16:18 UTC
Labels: question
