### ISSUE TITLE
Report non-fatal errors through callbacks and not just as logcat warning

### ISSUE THREAD

**Issue by fguinet** [google/ExoPlayer#6384] opened 2019-09-04 11:51 UTC
Hi, 

in case of an Audio discontinuity detected (cf. DefaultAudioSink line 644 : _Log.e(TAG, "Discontinuity detected [expected_ ...) nothing is raised to the AnalyticsListener (such as for onPositionDiscontinuity).
Is it a bug, a new feature to be explored or simply as designed ?
I would be very happy to have this on a coming version to better track the audio discontinuity of some live streams.

Best regards,

Fabien

**Comment by ojw28** [comment] 2019-09-04 15:34
@tonihei - Seems worth propagating to `AudioRendererEventListener` and `AnalyticsListener`?

**Comment by tonihei** [comment] 2019-09-04 15:59
As far as I can see there are 3 reasons why such a discontinuity in `DefaultAudioSink` can happen:
1. A regular, expected discontinuity because something changed in the track selection, the media queue, or the media period reports a discontinuity in the source. This gets all handled in `ExoPlayerImplInternal` and gets reported as `onPositionDiscontinuity`. The `DefaultAudioSink` ends up with the `START_NEED_SYNC` flag because the audio renderer position is reset and needs syncing.
2. Buffers in the audio renderer are skipped on purpose because they are marked as decode-only. Given that this is likely only happening after a seek or other expected discontinuities, there is no reason to report that again.
3. Unexpected discrepancies between the expected media timestamp and the actual media timestamp. That's the warning on L644 in `DefaultAudioSink` you mentioned. If I remember correctly, you only end up in there if you have malformed media. For all other media issues, we tend to just log a warning as long as we can continue playback as in this case. So I'm not sure we should report it. 

@andrewlewis may know more details about the cases for which this particular warning can occur.

> I would be very happy to have this on a coming version to better track the audio discontinuity of some live streams.

Can you explain in more detail what you are seeing and what you expect to see? Might be that you are actually looking for audible audio underruns, which are already reported via onAudioUnderrun.

**Comment by fguinet** [comment] 2019-09-04 16:12
In think we are in the third case. We are playing a Live stream media and
there is sometimes a PCR shift at the packager level. Indeed this is an
issue from the packager we are using, but we would like to track that kind
of QoS issue and report them when they occur (analytics).
Does that make sense ?

**Comment by tonihei** [comment] 2019-09-05 08:38
That makes complete sense. 

I just wonder if that case is any different from many other non-fatal warnings we have across our code base. Whenever we log something with the warning level, it means we recognized a problem but the problem is most likely non-fatal and we can just continue playback. But in all cases, it would we be good to report this to analytics systems if possible to know that an unexpected situation occurred. So far, the only non-fatal errors reported through the listeners are load errors that can be retried. I think if we report this kind of non-fatal error, we should think about a way to report all of them and not just this particular one. 

Marking as an enhancement again to track reporting generic non-fatal errors.

**Comment by tonihei** [comment] 2021-02-17 09:55
We decided to report non-fatal errors with more targeted callbacks corresponding to the area in which they occurred (for example `onAudioSinkError`, `onAudioCodecError` or `onVideoCodecError`. So no need for the generic non-fatal callback anymore. 

The initially requested reporting of the non-fatal but unexpected audio timestamp discontinuities will be reported as `AudioSink.UnexpectedDiscontinuityException` through `onAudioSinkError` in the future.

**Closed as completed by tonihei** 2021-02-17 09:55 UTC
Labels: enhancement
