### ISSUE TITLE
Play/pause should have different behavior at end of video

### ISSUE THREAD

**Issue by eldad-evie** [google/ExoPlayer#3689] opened 2018-01-09 19:25 UTC
(I'm not sure if this qualifies as a bug or a feature request)

I'm running the sample app, and at the end of the video the pause/play button stops having any effect. The icon changes when tapped, but nothing else happens. 

On YouTube, reaching the end of a video changes the button from play to a third state - replay. Pressing it seeks to the beginning and starts playback again. I think that makes for a far better user experience.

I've tried to accomplish the same thing with a PlaybackControlView.ControlDispatcher that checks the current time in dispatchSetPlayWhenReady() and if it's identical to the duration of the video, calls player.seekTo(0) then player.setPlayWhenReady(true) - this does jump back to the beginning of the video but a second press is required to actually start playback. What am I missing?

**Comment by marcbaechinger** [comment] 2018-01-09 20:02
The current behaviour of the PlaybackControlView works as intended as it reflects the state of the player (playWhenReady=true and position at the very end).

Instead of providing your own dispatcher you could wait for the state Player.STATE_ENDED with a Player.EventListener and then do

```
player.setPlayWhenReady(false);
player.seekTo(C.TIME_UNSET);
```

Now the player state is playWhenReady=false an position=0 and the UI reflects this. When the user taps play it starts from the beginning.

Note, that the first frame of the video will be displayed at this stage.

**Comment by eldad-evie** [comment] 2018-01-10 00:47
Thank you. I understand your solution and see that it works, but I really feel that for many apps having the controls reflect the player state doesn't provide the best experience.

To get around the issue of jumping to the first frame, I think I can do something like this for my own apps at least:

1. When onPlayerStateChanged receives the STATE_ENDED event, call setPlayWhenReady(false) to pause the video, and seek to just before the end (say, 10ms) - possibly not in this order.

2. Set a dispatcher that, if dispatchSetPlayWhenReady is called when playWhenReady == true and the current position is just before the end, calls seekTo(0) before dispatching playWhenReady(true).

(I realize this is an ugly hack).

**Comment by ojw28** [comment] 2018-01-10 13:40
@marcbaechinger - Do we have assets for a replay button already?

**Comment by marcbaechinger** [comment] 2018-01-10 16:02
Nope. I checked with the Material Design Icons and there is one when I search for 'replay'.

https://material.io/icons/

**Comment by ojw28** [comment] 2018-01-10 16:53
It could also be valid (and possibly nicer) to use the play button for the replay case, rather than using the replay asset.

**Comment by ojw28** [comment] 2018-01-23 19:52
This is fixed in the `dev-v2` branch. We now show the play button on ended, and pressing it will play from the default position of the current window (i.e. if you're just playing a single piece of on-demand content, it will start from the beginning).

**Closed as completed by ojw28** 2018-01-23 19:52 UTC
Labels: enhancement
