### ISSUE TITLE
ArrayIndexOutOfBoundsException in guessMediaTimeBasedOnElapsedRealTime

### ISSUE THREAD

**Issue by shashachu** [google/ExoPlayer#9257] opened 2021-08-04 21:26 UTC
We recently started using `PlaybackStatsListener` in our app, and we're seeing low-medium volume crashes that we haven't been able to reproduce locally:

```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at e.d.a.a.a.l(Unknown:5)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener$PlaybackStatsTracker.guessMediaTimeBasedOnElapsedRealtime(PlaybackStatsListener:775)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener$PlaybackStatsTracker.maybeUpdateMediaTimeHistory(PlaybackStatsListener:770)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener$PlaybackStatsTracker.onEvents(PlaybackStatsListener:577)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener.onEvents(PlaybackStatsListener:257)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$setPlayer$1(AnalyticsCollector:137)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$setPlayer$1$AnalyticsCollector(AnalyticsCollector:1)
        at com.google.android.exoplayer2.analytics.-$$Lambda$AnalyticsCollector$4Pupd4CGdtbqprZwT2MGLeu1J-0.invoke(-:1)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet:294)
        at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet:239)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$eEvjP-IE0x3J2lRvKfFbbjRFRvc(ListenerSet:9)
        at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$eEvjP-IE0x3J2lRvKfFbbjRFRvc.handleMessage(-:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7094)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

Examining the code, you can see how entering `maybeUpdateMediaTimeHistory` in a playback state other than `PLAYBACK_STATE_PLAYING` could lead to this crash:

```
private void maybeUpdateMediaTimeHistory(long realtimeMs, long mediaTimeMs) {
      if (!keepHistory) {
        return;
      }
      if (currentPlaybackState != PlaybackStats.PLAYBACK_STATE_PLAYING) {
        if (mediaTimeMs == C.TIME_UNSET) {
          return;
        }
        if (!mediaTimeHistory.isEmpty()) {
          long previousMediaTimeMs = mediaTimeHistory.get(mediaTimeHistory.size() - 1)[1];
          if (previousMediaTimeMs != mediaTimeMs) {
            mediaTimeHistory.add(new long[] {realtimeMs, previousMediaTimeMs});
          }
        }
      }
      mediaTimeHistory.add(
          mediaTimeMs == C.TIME_UNSET
              ? guessMediaTimeBasedOnElapsedRealtime(realtimeMs)
              : new long[] {realtimeMs, mediaTimeMs});
    }

private long[] guessMediaTimeBasedOnElapsedRealtime(long realtimeMs) {
      long[] previousKnownMediaTimeHistory = mediaTimeHistory.get(mediaTimeHistory.size() - 1);
      long previousRealtimeMs = previousKnownMediaTimeHistory[0];
      long previousMediaTimeMs = previousKnownMediaTimeHistory[1];
      long elapsedMediaTimeEstimateMs =
          (long) ((realtimeMs - previousRealtimeMs) * currentPlaybackSpeed);
      long mediaTimeEstimateMs = previousMediaTimeMs + elapsedMediaTimeEstimateMs;
      return new long[] {realtimeMs, mediaTimeEstimateMs};
    }
```

I'm happy to put up a PR to make the code more robust, but I'm wondering if this instead points to us using the analytics improperly in our app since I couldn't find any other reports of this same crash.

- ExoPlayer version number: 2.14.0
- Android version: All (our minSDK is 19)
- Android device: Various

**Comment by halizton** [comment] 2021-08-04 22:25
(from the same team as @shashachu)

Note that we have `keepHistory` set to be true as well in our code base.

`PlaybackStatsTracker(boolean keepHistory, EventTime startTime)`

**Comment by christosts** [comment] 2021-09-09 16:51
Thanks for filing the issue with details. Before we add a check in the code, I'd like to understand more of the context under which you observe this error. I cannot see a straightforward path for the PlaybackStatsListener to reach that state, and there may be another bug hidden somewhere in there. 

Have you managed to reproduce locally? Or, do you have any indications under what use-case this error occurs (from any kind of logging you may be collecting)? Also, do you add the PlaybackStatsListener on the player right after creating the player or later?

Context for the last question: For `guessMediaTimeBasedOnElapsedRealtime()` to throw:
1. `mediaTimeHistory` must be empty
2.  the PlaybackStatsListener must be in PLAYBACK_STATE_PLAYING
3.  the `mediaTimeMs` passed in `maybeUpdateMediaTimeHistory ` must be C.TIME_UNSET ([link to 2.14.0 version](https://github.com/google/ExoPlayer/blob/r2.14.0/library/core/src/main/java/com/google/android/exoplayer2/analytics/PlaybackStatsListener.java#L244)).

I wasn't able to figure out a straightforward path for this happen. For example, 1 & 2 can be achieved if you add the PlaybackStatsListener on an already playing player. Yet, deciding that an event does not belong to a session could happen between item transitions, but still the PlaybackStatsListener handles such cases. 

If you have more data on what context this error occurs, it would help us fix a potentially trickier bug.

Thanks

**Comment by greyski** [comment] 2021-09-09 17:39
(from the same team as @shashachu)

> Have you managed to reproduce locally?

We have not been able to reproduce locally and have set `keepHistory` to `false` for all our instances of `PlaybackStatsListener` since reporting to resolve the issue. e.g. `PlaybackStatsListener(false, null)`

> Or, do you have any indications under what use-case this error occurs (from any kind of logging you may be collecting)?

From our breadcrumbs we see 2 things:

- 1 or more videos may be playing on-screen at once
- 2 or more instances of ExoPlayer may be present in memory

> Also, do you add the PlaybackStatsListener on the player right after creating the player or later?

We attach the `PlaybackStatsListener` in our overridden `VideoView.setPlayer(player: Player?)` method like so:
```
    override fun setPlayer(player: Player?) {
        val oldPlayer = (getPlayer() as? SimpleExoPlayer)
        playbackStatsListener.run {
            oldPlayer?.removeAnalyticsListener(this)
        }
        super.setPlayer(player)
        playbackStatsListener.run {
            newPlayer?.addAnalyticsListener(this)
        }
    }
```
But to answer your question: _Usually_ right after creating an `ExoPlayer` instance, but _sometimes_ later as we keep a cache of already instantiated `ExoPlayer`s for re-use.

In theory, we shouldn't be adding this listener to an already playing instance of `ExoPlayer` as our playback callbacks happen _after_ `setPlayer` is called, and the players we cache have already called `stop()` prior to entering the said-cache.

**Comment by christosts** [comment] 2021-09-10 10:59
> * 1 or more videos may be playing on-screen at once
> * 2 or more instances of ExoPlayer may be present in memory

Does this mean the same PlaybackStatsListener instance may be attached to two players playing at the same time? (more related to point 1 above)

**Comment by christosts** [comment] 2021-09-20 08:49
We added a check in `maybeUpdateMediaTimeHistory` to avoid the error - see the linked commit above. We haven't been able to repro locally to verify under what circumstances this error can be raised. Per my comment above, avoid using the same listener instance on two players in parallel (in case that happens).

Closing the issue as a fix is submitted. Thanks.

**Closed as completed by christosts** 2021-09-20 08:49 UTC
Labels: bug, need more info

**Comment by greyski** [comment] 2021-09-23 21:49
Thank you, we'll add an assert for this.
