### ISSUE TITLE
How to gather HAR(HTTP Archive) file with ExoPlayer?

### ISSUE THREAD

**Issue by crystal-s-han** [google/ExoPlayer#11363] opened 2023-12-16 10:51 UTC
### This project is deprecated

- [X] I understand this project is deprecated and this issue will be closed with no response.

**Comment by icbaker** [comment] 2023-12-18 10:08
Duplicate of https://github.com/androidx/media/issues/902

**Closed as completed by icbaker** 2023-12-18 10:08 UTC
