### ISSUE TITLE
Exoplayer HLS ABR issue

### ISSUE THREAD

**Issue by jayachandrak** [google/ExoPlayer#2358] opened 2017-01-23 09:05 UTC
Issue: Player lag while playing the ABR stream
Player version; 2.1.1
CPU :Amlogic s805 mbox

Description:
I have sample HLS stream which has multiple bit rates 

it got three bit rates where as individual streams are working fine and when we try to play the ABR observe the player lag and frame drop

I have tested the same stream with device default player and i confirm that it is playing with out any issue

I have attached the log file below do needful 
[exoplayer.txt](https://github.com/google/ExoPlayer/files/723047/exoplayer.txt)

**Comment by AquilesCanta** [comment] 2017-01-23 10:09
Could you please provide said stream to dev.exoplayer@gmail.com?

**Comment by jayachandrak** [comment] 2017-01-23 10:14
Email sent to dev.exoplayer@gmail.com
Thanks

**Comment by jayachandrak** [comment] 2017-01-30 05:26
Hi Team,

Any update on the same?

Thanks

**Comment by AquilesCanta** [comment] 2017-01-31 10:18
No e-mail was received. Are you sure you sent it? Make sure you include the issue number in the subject.

**Comment by jayachandrak** [comment] 2017-01-31 10:25
Sent e-mail again

**Comment by AquilesCanta** [comment] 2017-01-31 10:37
I'd say "actually sent e-mail this time". I will have a look.

Edit: Nope, you had actually sent it. Since it didn't include the information requested information in the issue template it got archived. Thanks for the patience!

**Comment by AquilesCanta** [comment] 2017-01-31 12:09
Can you please provide a bugreport? Looks like device specific.

**Comment by jayachandrak** [comment] 2017-01-31 12:10
here is the log file
https://github.com/google/ExoPlayer/files/723047/exoplayer.txt

**Comment by AquilesCanta** [comment] 2017-01-31 12:14
That is the logcat output. What I need is a bugreport: [Look here.](http://stackoverflow.com/questions/26789107/how-to-write-an-android-bug-report-to-a-file-via-adb)

**Comment by jayachandrak** [comment] 2017-01-31 12:51
Here is the bugreport
[bugreport.txt](https://github.com/google/ExoPlayer/files/741964/bugreport.txt)

**Comment by AquilesCanta** [comment] 2017-01-31 13:47
Could you please clarify a bit what the issue is? I have been able to reproduce the stream in three different devices turning on random adaptation seemingly without issues. How noticeable is the frame drop and what does 
> the player lag

mean? I don't have access to the mentioned device. Have you been able to reproduce in another device? Also, considering 
> individual streams are working fine 

Have you made sure that, when playing with the default player, adaptation was happening?

**Comment by jayachandrak** [comment] 2017-01-31 14:15
Sent video file to the email

**Comment by AquilesCanta** [comment] 2017-01-31 15:11
I noticed through the provided bug report that you don't seem to be using exoplayer but rather a wrapper. Have you tried reproducing in the exoplayer demo app? It would be good if you tried the last release version: 2.2.0 at the time of writing. Kindly provide the bugreport for this as well, please.

**Comment by jayachandrak** [comment] 2017-01-31 15:18
I have tried with demo app as well with version 2.1.1

**Comment by AquilesCanta** [comment] 2017-01-31 15:50
Please read the issue threads #678, #488, and related. One of them explains how to blacklist decoders. Try blacklisting OMX.amlogic.avc.decoder.awesome, and see what happens. An alternative is checking what decoder MediaPlayer is using. It's likely that a software decoder is also available.
In any case, I would also suggest you follow up with the manufacturer of the device. I cannot reproduce the issue on any device I have, and I don't count with enough information to make an educated guess of what the problem is. 

Please do update if you find out additional information. The issue template provides a lot of useful information to speed things up.

**Comment by AquilesCanta** [comment] 2017-02-20 15:02
Closing due to lack of updates.

**Closed as completed by AquilesCanta** 2017-02-20 15:02 UTC
