### ISSUE TITLE
how to use exoplayer player directly

### ISSUE THREAD

**Issue by azhar5678** [google/ExoPlayer#6287] opened 2019-08-13 07:56 UTC
i am using exoplayer  directly but  app crashes, i want to know what other objects i need to initialize
to code to work
because im unable to get error (runtime)

 SimpleExoPlayerView exoPlayerView = (SimpleExoPlayerView) findViewById(R.id.exo_player_view);

    DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "ExoPlayer"));
    Uri uri = Uri.parse("http://localhost:8000/stream.mpd");
    DashMediaSource dashMediaSource = new DashMediaSource(uri, dataSourceFactory,
            new DefaultDashChunkSource.Factory(dataSourceFactory), null, null);

    BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
    TrackSelector trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));

    SimpleExoPlayer simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);

    exoPlayerView.setPlayer(simpleExoPlayer);
    simpleExoPlayer.prepare(dashMediaSource);

**Comment by jakoss** [comment] 2019-08-13 09:36
I think you should provide error content if you want the issue to get resolved.

Are you positive that localhost is correct address of your stream? If you're testing it on emulator then you cannot use localhost to access host machine. You should use 10.0.2.2 instead (more: https://developer.android.com/studio/run/emulator-networking.html)

**Comment by azhar5678** [comment] 2019-08-13 09:45
vedio playing fine on localhost with ur demo app by seting address
localhost in json file.

please provide me code sample
That run one file from localhost directly.

**Comment by jakoss** [comment] 2019-08-13 09:51
Just use 10.0.2.2 instead of localhost (if you are using Android Emulator)

**Comment by azhar5678** [comment] 2019-08-13 09:57
Iam not using emulator. Iam play vedio from usb otg with nanohttpd and
vedio are playing fine but i want to play  vedio with a click of button not
from sample chooser activity.

**Comment by jakoss** [comment] 2019-08-13 10:05
Ok. Please provide error message and possibly stack trace. You can intercept errors using this: https://exoplayer.dev/listening-to-player-events.html#player-errors

**Comment by azhar5678** [comment] 2019-08-13 10:30
APP CRAHING NO ERROR NOT EVEN
WITH EXCEPTION HANDLER WHICH GIVING ME ERRORS IN A FILE BEFORE.

I just need a simple activity which play file from localhost on click of a button.


I dont know what to initialize before starting player. What data values the player need before playing except for address.

**Comment by jakoss** [comment] 2019-08-13 10:36
did you set `simpleExoPlayer.setPlayWhenReady` to true?

**Comment by azhar5678** [comment] 2019-08-13 11:55
Same result app crashing.

here is the whole activity
public class MainActivityexo extends AppCompatActivity {

    private boolean useExtensionRenderers;
    private DownloadTracker downloadTracker;
    private MenuItem preferExtensionDecodersMenuItem;
    private MenuItem randomAbrMenuItem;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ExceptionReporter reporter = ExceptionReporter.register(this);

        super.onCreate(savedInstanceState);
        setContentView(R.layout.player_activity);
        DemoApplication application = (DemoApplication) getApplication();
        useExtensionRenderers = application.useExtensionRenderers();
        downloadTracker = application.getDownloadTracker();


        SimpleExoPlayerView exoPlayerView = (SimpleExoPlayerView) findViewById(R.id.player_view);

        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "ExoPlayer"));
        Uri uri = Uri.parse("http://localhost:8000/manifest.mpd");
        DashMediaSource dashMediaSource = new DashMediaSource(uri, dataSourceFactory,
                new DefaultDashChunkSource.Factory(dataSourceFactory), null, null);

        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelector trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));

        SimpleExoPlayer simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);

        exoPlayerView.setPlayer(simpleExoPlayer);
        simpleExoPlayer.prepare(dashMediaSource);
        simpleExoPlayer.setPlayWhenReady(true);
        }
    public void hello(String serversdd)
{

}
}

**Comment by AquilesCanta** [comment] 2019-08-14 11:36
Without knowing what kind of error you are getting, there is no way we can help. Aside, if the app is crashing, as opposed to hitting a player error, then the crash is most likely caused by app code. Please fill the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md) and we will try to assist.

**Comment by azhar5678** [comment] 2019-09-01 19:55
How and where to.increase the.buffer size so that video segments load
faster.

**Comment by ojw28** [comment] 2019-09-02 11:50
There isn't a coherent problem description or anything actionable for us here (the last question seems unrelated). Closing.

**Closed as completed by ojw28** 2019-09-02 11:50 UTC
Labels: wont fix: app issue

**Comment by chima94** [comment] 2019-10-07 08:04
App keep crashing with the error message getapplication() cant be cast to DemoApplication
