### ISSUE TITLE
set the horizontal padding for the subtitle with background and the corner radius for the subtitle background

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#11171] opened 2023-05-22 13:15 UTC
I have a subtitle with dark background

I can only make the subtitle as shown below:
![Untitled09](https://github.com/google/ExoPlayer/assets/30954955/b74501d9-12a4-4f9d-8ae2-28607ceb32d1)

but I wanna make that as shown below:
![Untitled11](https://github.com/google/ExoPlayer/assets/30954955/66f43ab5-8a09-407f-a178-f1cc28e4cefa)

I wanna set horizontal space between the subtitle text and background text, but I can't find any solutions. I set space for the start and the end of the text with OnCue fun, but it didn't work.

**Comment by sajjadshahbazi** [comment] 2023-05-22 13:19
I don't have a separate subtitle player. I initiated the subtitle in the principal player view.

**Comment by nigelmegitt** [comment] 2023-05-22 13:33
IMSC and EBU-TT-D support the styling attribute [ebutts:linePadding](https://www.w3.org/TR/ttml-imsc1.2/#text-linePadding) to achieve this effect; I am not sure how well supported it is in ExoPlayer, but I would certainly advocate that it _should_ be supported.

**Comment by sajjadshahbazi** [comment] 2023-05-22 13:48
> IMSC and EBU-TT-D support the styling attribute [ebutts:linePadding](https://www.w3.org/TR/ttml-imsc1.2/#text-linePadding) to achieve this effect; I am not sure how well supported it is in ExoPlayer, but I would certainly advocate that it _should_ be supported.

I saw your solution in other same issues, but I can't figure out how to set ebutts to Exoplayer, please, can you send an example for this solution?

**Comment by nigelmegitt** [comment] 2023-05-22 14:20
You need to provide an IMSC Text Profile or an EBU-TT-D profile TTML subtitle file that applies the desired value of `ebutts:linePadding`. I can't provide any more detail than that at the moment.

**Comment by icbaker** [comment] 2023-05-23 08:41
ExoPlayer does not support TTML's `linePadding` attribute. Support is tracked by https://github.com/google/ExoPlayer/issues/7521

I'm afraid I don't have anything more to suggest beyond what's discussed in https://github.com/google/ExoPlayer/issues/7516, so I'm going to close this as a duplicate of that.

**Closed as completed by icbaker** 2023-05-23 08:41 UTC
Labels: duplicate
