### ISSUE TITLE
 get Duration() of player method always returns  -1 How can i solve this issue

### ISSUE THREAD

**Issue by rspapneja** [google/ExoPlayer#5588] opened 2019-03-01 09:45 UTC
get Duration() of player method always returns  -1 How can i solve this issue
Link: https://open.http.mp.streamamg.com/p/3000464/sp/300046400/playManifest/entryId/0_dt6h9rus/format/applehttp/protocol/https/uiConfId/30012740/a.m3u8

**Comment by AquilesCanta** [comment] 2019-03-01 11:02
Playing the provided content correctly yields 6 seconds as media duration. 

I added logging like so:

`System.out.println("Duration is: " + player.getDuration());`

Which outputs:

`/com.google.android.exoplayer2.demo I/System.out: Duration is: 6000`

I will close this issue as working as intended. Please clarify below if I misunderstood something and I will reopen.

**Closed as completed by AquilesCanta** 2019-03-01 11:02 UTC
Labels: question
