### ISSUE TITLE
Library artifacts are published to jcenter only, which will close in 3 months

### ISSUE THREAD

**Issue by entibaldi** [google/ExoPlayer#8548] opened 2021-02-04 11:38 UTC
### Use case description
Hello! Your library is published only to jcenter. Please consider publishing it also to mavenCentral, as jcenter is [shutting down in May](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

### Proposed solution
[Here](https://central.sonatype.org/pages/producers.html) is some info on how to publish artifacts to mavenCentral.

**Comment by icbaker** [comment] 2021-02-04 12:04
Duplicate of #5246

**Closed as completed by icbaker** 2021-02-04 12:04 UTC
Labels: enhancement
