### ISSUE TITLE
MKV test suite not passed in 1.4.0

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#631] opened 2015-07-17 02:26 UTC
Based on the Matroska test suite (http://www.matroska.org/downloads/test_w1.html) I'm trying to test the container reading capabilities of ExoPlayer.

All below based on b3bf8fea20c1e82abef9a9a2699b3d7147672dd3.

Here's how the player is instantiated:

```
final String videoPath = getIntent().getStringExtra("videoPath");
final Uri uri = Uri.parse("file://" + videoPath);
final int numRenderers = 3;

final ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri,
        new ContentDataSource(this), new WebmExtractor(), new DefaultAllocator(65534), 10485760);

final TrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(sampleSource, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
final TrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);
final TrackRenderer subtitleRenderer = new TextTrackRenderer(sampleSource, new TextRenderer() {
    // ...
}, Looper.myLooper(), new TtmlParser(), new WebvttParser());

exoPlayer = ExoPlayer.Factory.newInstance(numRenderers);
exoPlayer.addListener(new ExoPlayer.Listener() {
    @Override
    public void onPlayerStateChanged(final boolean playWhenReady, final int playbackState) {
        if (playbackState == ExoPlayer.STATE_READY) {
            for (int i = 0; i < sampleSource.getTrackCount(); i++) {
                // Print track information.
            }
        }
    }

    // ...
});

exoPlayer.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, new Surface(surface));
exoPlayer.prepare(videoRenderer, audioRenderer, subtitleRenderer);
exoPlayer.setPlayWhenReady(true);
```
### test1.mkv
- Audio playback OK
- Video playback NOT OK, the screen will not display anything
- Tracks: audio/mpeg
### test2.mkv
- Audio playback OK
- Video playback OK
- Tracks: video/avc, audio/mp4a-latm
### test3.mkv
- Audio playback OK
- Video playback OK
- Tracks: video/avc, audio/mpeg
### test4.mkv

Currently crashes:

```
com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
        at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:255)
        at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:113)
        at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:271)
        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:197)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
 Caused by: java.io.EOFException
        at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:97)
        at com.google.android.exoplayer.extractor.webm.DefaultEbmlReader.read(DefaultEbmlReader.java:121)
        at com.google.android.exoplayer.extractor.webm.WebmExtractor.read(WebmExtractor.java:231)
        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:633)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:848)
```
### test5.mkv
- Audio playback OK
- Video playback OK
- Tracks: video/avc, audio/mp4a-latm
### test6.mkv
- Hangs / will not play - and no error message is recorded
- No tracks are read.
- Standard android Media Player (MTK-based) will play, but only AUDIO, not video
### test7.mkv
- Loads first frame, then stops
- No tracks are read
- Crashes after 1 second:

```
com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException
        at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:513)
        at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
 Caused by: java.io.EOFException
        at com.google.android.exoplayer.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:97)
        at com.google.android.exoplayer.extractor.webm.DefaultEbmlReader.read(DefaultEbmlReader.java:121)
        at com.google.android.exoplayer.extractor.webm.WebmExtractor.read(WebmExtractor.java:231)
        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:633)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:848)
```
### test8.mkv
- Audio playback OK
- Video playback OK
- Tracks: video/avc, audio/mp4a-latm

**Comment by ojw28** [comment] 2015-07-17 15:41
Thanks for the summary. Some initial findings:

- Test1 - Contains MPEG4 Part 2 video. It's unclear whether Android provides support for this format. Android supports H.263, but MPEG4 Part 2 is an enhancement of H.263. If it's not supported, then playing without video is working as intended. We'll find out. Note that we'd normally expect video to be H.264.

- Test4 - Shouldn't fail in this way. Although it contains Theora video, so it's unlikely we'll be supporting the video part of this test stream.

- Test6 - This file is unusual because it omits a Cues that would be required for seeking. We should probably handle this case (by allowing playback but disabling seek, as noted in the release notes that accompany the test suite). Whether we play the video in this stream is the same as in Test1.

- Test7 - This is a robustness issue related to skipping under garbage in the stream. We don't expect streams to contain this kind of garbage, but we should cope with it and playback should succeed.

So action items here are:

1. Fix the extractor to work properly for Test7.
2. Fix Test6 to allow playback without seeking.
3. Fix Test4 to not fail in the way that it does fail.
4. Investigate whether MPEG4 Part 2 video and Theora video are supported by Android. I'm doubtful in both cases, but we should take a look.

**Comment by ojw28** [comment] 2015-07-17 16:03
Note that Test2 is broken after seeking.

**Comment by ojw28** [comment] 2015-07-21 16:44
Test videos 2 and 6 now work (seeking doesn't work in 6, but this is working as intended due to the omitted Cues element). Remaining action items are:

1. Fix the extractor to work properly for Test7.
1. Fix Test4 to not fail in the way that it does fail.
1. Investigate whether MPEG4 Part 2 video and Theora video are supported by Android. I'm doubtful in both cases, but we should take a look.

**Comment by ojw28** [comment] 2017-02-15 19:57
The tests that still fail are appear to be hypothetical cases that shouldn't occur for correctly formed media. We've not seen any actual issues with real content as a result of these tests not passing, therefore I'm going to close this issue.

**Closed by ojw28** 2017-02-15 19:57 UTC
Labels: bug
