### ISSUE TITLE
seekToDefaultPosition() doesn't work on radio stream when getBackBufferDurationUs is overriden

### ISSUE THREAD

**Issue by mkaflowski** [google/ExoPlayer#4493] opened 2018-07-10 11:17 UTC
When I override getBackBufferDurationUs in DefaultLoadControl and use seekToDefaultPosition() on radio stream it doesn't go to live edge position but it goes to the beginning of buffer. Any seek methods give me the same results.

**Comment by botaydotcom** [comment] 2018-07-12 10:21
Hi @mkaflowski,
Please provide more information as required by the issue template, including:
- Link to the test content.
- What version ExoPlayer is used.
- Steps to reproduce the issue.
That will help us to analyze this issue much faster. Thank you.

**Comment by ojw28** [comment] 2018-08-14 09:55
This is a bug, but it's also unclear why you would modify `getBackBufferDurationUs` when playing progressive live streams, since seeking within such streams wont work either way.

**Comment by ojw28** [comment] 2018-08-16 16:17
Fixed in `dev-v2`.

**Closed as completed by ojw28** 2018-08-16 16:17 UTC
Labels: bug
