### ISSUE TITLE
Playback of 60fps video with faster speed(2.0) cause Video Discontinuity

### ISSUE THREAD

**Issue by workspace** [google/ExoPlayer#5885] opened 2019-05-14 01:53 UTC
I tried to update ExoPlayer's version from 2.9.6 to 2.10.0, however, it seems playback of 60fps video with faster speed has problem with frame release(drop a lot of frames!). My device is Galaxy S9 plus(SM-G965), so it is not related with device's performance. With same media, 2.9.6 does not have problem with fast playback, so I think some changes in 2.10.0 cause this problem.

I'm sorry for leaving issue without test content. I really want to provide json snippet with our media for testing, however, playback requires dynamically issued drm token which expires in just few hour. So...if you have some 60 fps video for testing, could you test with it? I think it will have a problem, too

Here is bugreport when discontinuity has occurred.after 10:15:30, I tried to play media with 2.0 speed.
[bugreport-2019-05-14-10-15-51.zip](https://github.com/google/ExoPlayer/files/3175505/bugreport-2019-05-14-10-15-51.zip)

**Comment by ojw28** [comment] 2019-05-15 20:47
> I'm sorry for leaving issue without test content. I really want to provide json snippet with our media for testing, however, playback requires dynamically issued drm token which expires in just few hour.

We really need test content for this. Can you not just host a single sample file somewhere else, or just put it on Google Drive or similar and share the link with `dev.exoplayer@gmail.com`?

**Comment by workspace** [comment] 2019-05-16 00:11
I'll send a guide to get token and json snippet via email. Thank you!

**Comment by ojw28** [comment] 2019-05-17 12:42
It looks from your email that you're seeing ~90% of all frames being dropped. Is that correct, and does that occur consistently? I tried the test video on a Galaxy S8 and see about 65% frame drop on 2.9.6 and 2.10.0, so I don't see a regression. I'll try and get hold of an S9 for some further testing.

Are you sure you haven't done something else to cause you to measure worse performance on 2.10.0? For example attaching the debugger during one run but not the other, or somehow building the demo app differently in a way that would make it not a fair test?

**Comment by workspace** [comment] 2019-05-20 01:02
It is my mistake to think that a version upgrade has affected performance. I also get frame drop on 2.9.6 and 2.10.0 either. I think ExoPlayer has a problem with 2.0 speed playback of 60fps video(maybe buffer release logic?). I will try playback with another 60fps sample.

**Comment by ojw28** [comment] 2019-05-20 13:02
I'm not sure it's entirely reasonable to expect that the device would be able to play back at 120fps. Are you sure you're not just hitting the performance limit of the device? Also, note that dropping 50% of the frames would actually be optimal, rather than 0%, given 120fps is double the display refresh rate.

**Comment by ojw28** [comment] 2019-06-24 16:26
Please disregard the @google-oss-bot comment.

**Comment by ojw28** [comment] 2019-06-24 16:28
Closing this because it's likely just hitting device/player performance limits. We have some open issues for investigating ways of improving player performance (e.g. https://github.com/google/ExoPlayer/issues/5796), which you might be interested in tracking.

**Closed as completed by ojw28** 2019-06-24 16:28 UTC
Labels: question
