### ISSUE TITLE
Timebar Customization

### ISSUE THREAD

**Issue by CanerGures** [google/ExoPlayer#8146] opened 2020-11-02 08:26 UTC
Hello, I am trying to customize timebar and duration/position timers for playing live videos. I want to achive [this](https://linkpicture.com/q/Ads%C4%B1z_81.png). But I couldnt find anything about this topic on neither in https://exoplayer.dev/ or somewhere else.
        
                Log.e("timeline", "live:"+ player!!.isCurrentWindowLive)
                Log.e("timeline", "duration:"+ player!!.duration)
                Log.e("timeline", "contentduration:"+ player!!.contentDuration)
                Log.e("timeline", "renderer count:"+ player!!.rendererCount)
                Log.e("timeline", "contentPosition:"+ player!!.contentPosition)
                Log.e("timeline", "currentPosition:"+ player!!.currentPosition)
                Log.e("timeline", "timeline:$timeline")
                

I am trying to make a meaningful deduction from these logs but even if I am, these variables are "_val_". When live videos are playing I want to set the slider on the right end side and on the right end side I want to set the time of the video backward like minus value. Can you check the [picture](https://linkpicture.com/q/Ads%C4%B1z_81.png)? You will understand what I meant.

my repo [this](https://github.com/CanerGures/ExoPlayer-Application)

**Comment by CanerGures** [comment] 2020-11-02 13:56
I have achieved the representing cached time as minus value with that code.

                val duration = player!!.duration
                val hours = String.format("%02d", TimeUnit.MILLISECONDS.toHours(duration))
                val minutes = String.format(
                    "%02d",
                    TimeUnit.MILLISECONDS.toMinutes(duration) - TimeUnit.HOURS.toMinutes(
                        TimeUnit.MILLISECONDS.toHours(
                            duration
                        )
                    )
                )
                val seconds = String.format(
                    "%02d",
                    TimeUnit.MILLISECONDS.toSeconds(duration) - TimeUnit.MINUTES.toSeconds(
                        TimeUnit.MILLISECONDS.toMinutes(
                            duration
                        )
                    )
                )
                if (hours == "00") {
                    val timeFormat = "-$minutes.$seconds"
                    Log.e("timeline", "timeFormat:$timeFormat")
                    timeBarDuration.text = timeFormat
                } else {
                    val timeFormat = "-$hours.$minutes.$seconds"
                    Log.e("timeline", "timeFormat:$timeFormat")
                    timeBarDuration.text = timeFormat
                }
 But current position is dynamic and bound to _"id/exo_position"_ . I couldn't see a way to do it as I mentioned in the question.

**Comment by lcf87** [comment] 2020-11-02 14:02
Setting the negative time part is not supported at the moment by default. Marked as enhancement to track the support. 

As for keeping the scrub bar at the right most position, you could make a custom timebar view and replace the default one with it.

Maybe issue #7912 will also help.

**Comment by ojw28** [comment] 2021-04-25 23:09
Duplicate of https://github.com/google/ExoPlayer/issues/2213

**Closed as completed by ojw28** 2021-04-25 23:09 UTC
Labels: duplicate, enhancement, low priority
