### ISSUE TITLE
Exoplayer livestream seekbar customisation

### ISSUE THREAD

**Issue by rajinikanth0602** [google/ExoPlayer#8859] opened 2021-04-22 21:41 UTC
We are currently using exoplayer 2.13.3 for HLS livestreaming where we are not so satisfied with the existing exoplayer seekbar for live streams. 

### _Problems with ExoPlayer Seekbar_

- The scrub position is always behind the edge even when in sync with live.
- Scrub position will go back by (segment_size secs) when new segment is added.

### _What we are trying to acheive_

- Youtube like seekbar where the scrub will be at the edge when in sync with live.

### _Solutions we currently have_

- Cloning the StyledPlayerControlView, and DefaultTimeBar and setting the timebar duration to defaultPosition. (Upgrading the exoplayer will be difficult with this approach)
- Creating own seekbar and binding it to player. (lot of effort and may introduce bugs) 
- Get the instance of attached TimeBar and set duration to window.defaultPositionUs/1000 (but I didn't find a way to get the TimeBar instance)

Out of these solutions, I feel 3rd one is the best approach, is there a way we can get instance of TimeBar without using reflection ? or Do we have any other simpler way we can achieve this functionality? 

Below diagram maps the player position to timebar position as per our requirement.

![SeekBar-3](https://user-images.githubusercontent.com/12000793/115787932-8daf2680-a3e0-11eb-8d49-c67a81a3d4bb.jpg)

**Comment by ojw28** [comment] 2021-04-25 23:09
Duplicate of #2213. As of now, writing your own UI components (possibly by forking those in the library as a starting point) is the recommended solution if the provided components don't accommodate your use case.

**Closed as completed by ojw28** 2021-04-25 23:09 UTC
Labels: duplicate
