### ISSUE TITLE
TrackSelectionDialog : androidx.appcompat.app.AppCompatDialog.setTitle

### ISSUE THREAD

**Issue by nuclearmagneton** [google/ExoPlayer#10634] opened 2022-09-20 02:27 UTC
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Android: 10
Android Build: QP1A.190711.020
Manufacturer: vivo
Model: V2027

### Reproducible in the demo app?

Yes

### Reproduction steps

I have received this in crashlytics

### Expected result

show the dialog

### Actual result

android.content.res.Resources$NotFoundException: String resource ID #0x0
  at android.content.res.Resources.getText(Resources.java:408)
  at android.content.Context.getText(Context.java:626)
  at android.app.Dialog.setTitle(Dialog.java:660)
  at androidx.appcompat.app.AppCompatDialog.setTitle(AppCompatDialog.java)
  at com.google.android.exoplayer2.demo.TrackSelectionDialog.onCreateDialog(TrackSelectionDialog.java:14)
  at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java)
  at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java)
  at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java)
  at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java)
  at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java)
  at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
  at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java)
  at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java)
  at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java)
  at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java)
  at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java)
  at com.google.android.exoplayer2.demo.PlayerActivity.onStart(PlayerActivity.java:36)
  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1479)
  at android.app.Activity.performStart(Activity.java:7919)
  at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3579)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
  at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loop(Looper.java:230)
  at android.app.ActivityThread.main(ActivityThread.java:7880)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

### Media

any demo url

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment] 2022-09-22 16:30
Possibly duplicate of #10409

**Comment by icbaker** [comment] 2022-10-13 08:54
I'm un-duping this because the stack traces in #10409 refer to real resource IDs that our library does define, they just can't be found for some reason - whereas this one refers to a wrong/invalid (?) resource ID (`0x0`), so I think we should probably keep this separate.

**Comment by icbaker** [comment] 2022-12-22 14:54
@nuclearmagneton Do you have any more information we can use to reproduce this? Without that there's little we can do I'm afraid.

**Closed as completed** 2023-01-19 02:06 UTC
Labels: closed-by-bot
