### ISSUE TITLE
StyledPlayerView: onVisibilityChange 0 (erratic behavior)

### ISSUE THREAD

**Issue by onikaii** [google/ExoPlayer#10644] opened 2022-09-22 21:38 UTC
Hi, I am trying to implement setControllerVisibilityListener with StyledPlayerView , the callback always receives 0  even when the controls are no longer visible.

Or when I touch close the controls the visibility listener receives "0" 2 times and after a second receives  "8"(status GONE), please check the log section

Layout

```
    <com.google.android.exoplayer2.ui.StyledPlayerView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#000000"
        android:visibility="visible"
        app:controller_layout_id="@layout/exo_player_control_view"
        app:show_buffering="when_playing"
        app:show_previous_button="true"
        app:show_rewind_button="true"
        app:show_timeout="2000"
        app:visibilityMode="normal"
        tools:layout_editor_absoluteX="153dp"
        tools:layout_editor_absoluteY="-43dp" />
```

Callback
```
        binding.videoView.setControllerVisibilityListener(StyledPlayerView.ControllerVisibilityListener { visibility ->
            when (visibility) {
                View.GONE -> {
                    Log.d(TAG, "initializePlayer() called with: visibility GONE  = $visibility")
                }
                View.VISIBLE -> {
                    Log.d(TAG, "initializePlayer() called with: visibility VISIBLE = $visibility")
                }
            }
        })
```

Log
```
D/XXX VideoPlayerActivity: initializePlayer() called with: visibility VISIBLE = 0 // touch screen to open
D/XXX VideoPlayerActivity: initializePlayer() called with: visibility GONE  = 8
D/XXX VideoPlayerActivity: initializePlayer() called with: visibility VISIBLE = 0
D/XXX VideoPlayerActivity: initializePlayer() called with: visibility VISIBLE = 0
D/XXX VideoPlayerActivity: initializePlayer() called with: visibility VISIBLE = 0 // touch to close
D/XXX VideoPlayerActivity: initializePlayer() called with: visibility VISIBLE = 0 
D/XXX VideoPlayerActivity: initializePlayer() called with: visibility VISIBLE = 0
D/XXX VideoPlayerActivity: initializePlayer() called with: visibility GONE  = 8
```

```
    def version_exoplayer = "2.18.1"
    implementation "com.google.android.exoplayer:exoplayer-core:$version_exoplayer"
    implementation "com.google.android.exoplayer:exoplayer-ui:$version_exoplayer"
```

I have checked this link, but it didn't help me
https://github.com/google/ExoPlayer/issues/9815

thanks

**Comment by marcbaechinger** [comment] 2022-09-26 17:06
I don't see the timings in your log, but from what you report and from what I see in the demo app, I think this is working as intended.

I think the listener is called multiple times with `0` (VISIBLE) while the animation is running and then finally sends an `8` for `GONE` or `0` (VISIBLE) at the end of the animation.

Can you clarify how the log lines in your example correlates to actual user interactions? Probably just repeat your interactions slowly so that there is enough duration between them and the send a log snipppet that includes the times, so that you can see where opening/closing ends?

That's what I see:
```
// show
09-26 09:54:59.553  1968  1968 D visibility: onVisibilityChanged(): 0
09-26 09:54:59.812  1968  1968 D visibility: onVisibilityChanged(): 0
// hide
09-26 09:55:01.390  1968  1968 D visibility: onVisibilityChanged(): 0
09-26 09:55:01.646  1968  1968 D visibility: onVisibilityChanged(): 8
// show
09-26 09:55:03.466  1968  1968 D visibility: onVisibilityChanged(): 0
09-26 09:55:03.729  1968  1968 D visibility: onVisibilityChanged(): 0
// hide
09-26 09:55:05.358  1968  1968 D visibility: onVisibilityChanged(): 0
09-26 09:55:05.613  1968  1968 D visibility: onVisibilityChanged(): 8
// show
09-26 09:55:06.680  1968  1968 D visibility: onVisibilityChanged(): 0
09-26 09:55:06.929  1968  1968 D visibility: onVisibilityChanged(): 0
// hide
09-26 09:55:08.390  1968  1968 D visibility: onVisibilityChanged(): 0
09-26 09:55:08.646  1968  1968 D visibility: onVisibilityChanged(): 8
```

**Closed as completed** 2022-10-25 01:04 UTC
Labels: question, closed-by-bot
