### ISSUE TITLE
Adaptive bitrate / throttling question

### ISSUE THREAD

**Issue by jonfhancock** [google/ExoPlayer#2599] opened 2017-03-23 19:10 UTC
in Version 2.3.0, DefaultBandwithMeter reports its estimated bitrate in bps.

But AdaptiveTrackSelection's determineIdealSelectedIndex method is comparing that to kbps values in the format.bitrate field.

As a result, it always chooses the highest bitrate format because it doesn't realize that internet speed has slowed to a crawl.

**Comment by ojw28** [comment] 2017-03-23 19:16
Format.bitrate is also in bps?

**Comment by jonfhancock** [comment] 2017-03-23 19:18
I should have provided some sample values to begin with. I'll get those now.

**Comment by jonfhancock** [comment] 2017-03-23 19:45
I'm at a bit of a loss for what is actually happening here.  

I've introduced throttling that makes every network request take 30 seconds longer than it should. Which means that even if it were to switch down, it would still take a long time to transfer data.

Even still, the bitrate estimate is far greater than the bitrates of any format. 

I tried just dividing the bitrate estimate by 1000 immediately after calculation, but it resulted in very low bitrate estimates even with no throttling, causing the lowest quality track to always be selected.

I'm turning my attention now toward SlidingPercentile.

![screenshot 2017-03-23 12 41 15](https://cloud.githubusercontent.com/assets/561521/24266989/0e0414fc-0fc6-11e7-9a68-28ec2c383d95.png)

**Comment by ojw28** [comment] 2017-03-23 20:08
Most likely you've implemented throttling in a way that doesn't have any effect on the bitrate estimate (or, worse, has the opposite effect to what you want). SlidingPercentile has been left pretty much unchanged for years; it's unlikely there's anything wrong with it.

**Comment by jonfhancock** [comment] 2017-03-23 21:48
The problem seems to be somewhere in OkHttpDataSourceFactory.

![screenshot 2017-03-23 14 49 14](https://cloud.githubusercontent.com/assets/561521/24271837/f1076e6e-0fd7-11e7-9fdf-9cfd046fb159.png)


That doesn't change even if I throttle my connection down to Edge speeds.


Whereas with DefaultHttpDataSourceFactory, I get expected results. Throttling down resulted in a drop from ~10mbps to ~1mbps.

![screenshot 2017-03-23 14 49 58](https://cloud.githubusercontent.com/assets/561521/24271856/04ff9fc2-0fd8-11e7-8557-397b73e135d4.png)

**Comment by jonfhancock** [comment] 2017-03-23 21:55
The amount of time spent loading seems particularly suspicious. 

25 ms for 1269kb vs the more realistic 800ms.

**Comment by ojw28** [comment] 2017-03-23 22:10
As per my previous response, I suspect you've implemented throttling in a way that doesn't have the intended effect on the bitrate estimate. It's unclear how you're actually doing the throttling (e.g. server vs. client side). If you've done it client side in an unrealistic way, that may well confuse the bitrate estimate. For example if you've done something that will sleep the loading thread for 30 seconds, but OkHttp is still loading data into its own buffer whilst the sleep takes place, then it's plausible that when the loading thread resumes it may be able to provide a large amount of data extremely quickly. That would be in no way realistic and is liable to confuse a bitrate estimate.

If I take the demo app and do nothing except swap between DefaultHttpDataSourceFactory and OkHttpDataSourceFactory, I see similar (sensible) estimates in both cases. Please try to reproduce in the demo app, without any local modifications related to throttling. If you can still reproduce the issue please provide concrete reproduction steps. Thanks!

**Comment by jonfhancock** [comment] 2017-03-23 22:12
I'll try to reproduce in the demo app. 

The logs above were captured while using charles proxy to throttle so that the threads aren't an issue. 

As far as the in-app approach to throttling, I have an interceptor on the OkHttpClient that sleeps the thread prior to proceeding the chain.  So it's preventing OkHttp from downloading data.  Though. looking at the internals of OkHttpDataSource now, I think I'm sleeping at call.execute().  But that is several lines before listener.startTransfer().

**Comment by ojw28** [comment] 2017-03-24 14:54
Closing for now. I think this is probably something wrong with your local setup and/or modifications.

**Closed as completed by ojw28** 2017-03-24 14:54 UTC
Labels: question
