### ISSUE TITLE
OutOfMemoryError {ExoPlayerImplInternal:Handler}

### ISSUE THREAD

**Issue by srinivasstpl** [google/ExoPlayer#4221] opened 2018-05-08 11:51 UTC
Google Analytics reflects that one particular device Huawei DUK-L09 Honor 8 Pro keeps encountering this issue. Unfortunately, the only information I get regarding this is `OutOfMemoryError {ExoPlayerImplInternal:Handler}`

**Comment by tonihei** [comment] 2018-05-08 12:18
This device seems to have 4 or 6 GB of RAM. So, it's definitely not a low-end device which may have issues buffering media with ExoPlayer. Note that the maximum we aim to keep in the buffer at the moment is around 16MB only.

Is there any other indication as to what may happen on this device? For example, do you know what media item the device was playing? Or whether your app may allocate memory for other reasons such that no memory is left for ExoPlayer?

**Comment by srinivasstpl** [comment] 2018-05-09 07:52
Thanks for the prompt response, I am certainly considering the aspect wherein no memory is left for ExoPlayer. For the content that ExoPlayer is playing, it's an mp4 video. Is it possible that if the video resolution that's being supplied to ExoPlayer is far more than the device's screen resolution, this issue may occur?

**Comment by tonihei** [comment] 2018-05-09 08:07
What video resolution are we talking about? By default, ExoPlayer tries to buffer at least 15 seconds worth of media (irrespective of the 16MB mentioned above). So for very high res videos, this may easily exceed 16 MB.
Not sure how easy you can test this, but there is an option in our `DefaultLoadControl` that lets you prefer the size threshold over the time threshold (i.e. set `prioritizeTimeOverSizeThresholds=false`). This would as far as possible prevent exceeding the the max buffer size in bytes even for high resolution videos.

An alternative explanation is that there are problems with bad interleaving in MP4 files (see #3481 or #3670). It's of course impossible to say without example media whether this is the problem here. We also recently pushed a workaround that should prevent this from happening for most cases (from ExoPlayer 2.7). Which version are you using?

**Comment by srinivasstpl** [comment] 2018-05-18 07:35
Apologies for the delayed response, I finally received the stacktrace of the aforementioned issue in the Google Play Console:

```
java.lang.OutOfMemoryError: 
  at android.media.MediaCodec$BufferInfo.dup (MediaCodec.java:1544)
  at android.media.MediaCodec.dequeueOutputBuffer (MediaCodec.java:2649)
  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer (MediaCodecRenderer.java:1005)
  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render (MediaCodecRenderer.java:567)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork (ExoPlayerImplInternal.java:518)
  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage (ExoPlayerImplInternal.java:301)
  at android.os.Handler.dispatchMessage (Handler.java:104)
  at android.os.Looper.loop (Looper.java:166)
  at android.os.HandlerThread.run (HandlerThread.java:65)
```

I hope this can help diagnose the issue further.

**Comment by tonihei** [comment] 2018-05-18 08:10
That's unfortunately not helpful for an OOM because the point where the system eventually is out of memory is most of the time independent from the cause of excessive memory usage.

To reproduce the issue, it would be helpful if
 - You can confirm it really only occurs for Huawei Honor 8 phones. That would speak for a device specific issue.
 - Provide us with an example of a media file which caused the OOM.

**Comment by tonihei** [comment] 2018-06-21 08:27
Closing as we don't have any more info to go on. If you have additional information which would help to solve the issue, please reopen.

**Closed as completed by tonihei** 2018-06-21 08:27 UTC
Labels: need more info
