### ISSUE TITLE
Notification "large icon" low quality

### ISSUE THREAD

**Issue by WildOrangutan** [google/ExoPlayer#10650] opened 2022-09-26 08:59 UTC
Hey,

I'm trying to use "large icon" for notification image with media session extension. When I image is set to notification, it has very low quality.

My image resolution is good enough ([4k](https://images5.alphacoders.com/912/912442.jpg)) and above notification size limit (320x320 dp).

I thought this was due to notification size limit, but it seems like there's a way, since other apps can do it.

[my notification](https://user-images.githubusercontent.com/5972966/192235305-35836487-3a3d-45dd-a9d9-6bb2b9b8c48d.png)
[spotify notification](https://user-images.githubusercontent.com/5972966/192235405-0c74ec3f-9b94-4245-a3ea-1b391ed2a5f6.png)

```kotlin
class NotificationDescriptionAdapter : PlayerNotificationManager.MediaDescriptionAdapter {

    override fun getCurrentLargeIcon(
        player: Player,
        callback: PlayerNotificationManager.BitmapCallback,
    ): Bitmap? {
        val url = "https://images5.alphacoders.com/912/912442.jpg"
        downloadImage(url, callback::onBitmap)
        return null
    }

    private fun downloadImage(url: String, onDownload: (Bitmap) -> Unit) {
        Glide.with(context)
            .asBitmap()
            .load(url)
            .into(object : CustomTarget<Bitmap>() {
                override fun onResourceReady(
                    resource: Bitmap,
                    transition: Transition<in Bitmap>?,
                ) {
                    onDownloaded(resource)
                }
                override fun onLoadCleared(placeholder: Drawable?) {}
            })
    }

    // Rest of the code omitted
    // ...
}
```

**Comment by marcbaechinger** [comment] 2022-09-26 10:20
This is a duplicate of  https://github.com/androidx/media/issues/168

**Closed as completed by marcbaechinger** 2022-09-26 10:20 UTC
Labels: duplicate, question
