### ISSUE TITLE
Playback error : Response code: 416

### ISSUE THREAD

**Issue by happysingh23828** [google/ExoPlayer#8474] opened 2021-01-18 13:02 UTC
There are some s3 video URLs that are opening fine on the web and mobile chrome. but on ExoPlayer it keeps retrying to connect with the server and in last it throws 416 response code.

It is happening only for 20 min + duration videos. URL starts with HTTPS and there is no redirection to HTTP. although I have added HTTP clearing traffic.

Logs 
```
2021-01-18 18:12:41.448 8666-8896/com.yusufcakmak.exoplayersample I/chatty: uid=10279(com.yusufcakmak.exoplayersample) Loader:Progress identical 2 lines
2021-01-18 18:12:41.450 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:12:41.771 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest>>
2021-01-18 18:12:41.773 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest<<
2021-01-18 18:12:45.684 8666-8896/com.yusufcakmak.exoplayersample I/System.out: port:443
2021-01-18 18:12:45.921 8666-8677/com.yusufcakmak.exoplayersample I/exoplayersampl: Background concurrent copying GC freed 19897(1812KB) AllocSpace objects, 4(96KB) LOS objects, 49% free, 3MB/6MB, paused 15.752ms total 339.351ms
2021-01-18 18:12:46.323 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:12:46.329 8666-8896/com.yusufcakmak.exoplayersample I/chatty: uid=10279(com.yusufcakmak.exoplayersample) Loader:Progress identical 2 lines
2021-01-18 18:12:46.331 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:12:46.338 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest>>
2021-01-18 18:12:46.340 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest<<
2021-01-18 18:12:54.406 8666-8896/com.yusufcakmak.exoplayersample I/System.out: port:443
2021-01-18 18:12:55.630 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:12:55.644 8666-8896/com.yusufcakmak.exoplayersample I/chatty: uid=10279(com.yusufcakmak.exoplayersample) Loader:Progress identical 2 lines
2021-01-18 18:12:55.650 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:12:55.665 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest>>
2021-01-18 18:12:55.671 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest<<
2021-01-18 18:12:57.954 8666-8896/com.yusufcakmak.exoplayersample I/System.out: port:443
2021-01-18 18:12:58.749 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:12:58.762 8666-8896/com.yusufcakmak.exoplayersample I/chatty: uid=10279(com.yusufcakmak.exoplayersample) Loader:Progress identical 2 lines
2021-01-18 18:12:58.768 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:12:58.781 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest>>
2021-01-18 18:12:58.785 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest<<
2021-01-18 18:13:02.121 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest>>
2021-01-18 18:13:02.123 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest<<
2021-01-18 18:13:03.948 8666-8896/com.yusufcakmak.exoplayersample I/System.out: port:443
2021-01-18 18:13:04.451 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:13:04.458 8666-8896/com.yusufcakmak.exoplayersample I/chatty: uid=10279(com.yusufcakmak.exoplayersample) Loader:Progress identical 2 lines
2021-01-18 18:13:04.461 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:13:04.469 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest>>
2021-01-18 18:13:04.472 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest<<
2021-01-18 18:13:07.769 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest>>
2021-01-18 18:13:07.774 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest<<
2021-01-18 18:13:09.650 8666-8896/com.yusufcakmak.exoplayersample I/System.out: port:443
2021-01-18 18:13:10.140 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:13:10.155 8666-8896/com.yusufcakmak.exoplayersample I/chatty: uid=10279(com.yusufcakmak.exoplayersample) Loader:Progress identical 2 lines
2021-01-18 18:13:10.161 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:13:10.176 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest>>
2021-01-18 18:13:10.182 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest<<
2021-01-18 18:13:13.043 8666-8896/com.yusufcakmak.exoplayersample I/System.out: port:443
2021-01-18 18:13:13.660 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:13:13.674 8666-8896/com.yusufcakmak.exoplayersample I/chatty: uid=10279(com.yusufcakmak.exoplayersample) Loader:Progress identical 2 lines
2021-01-18 18:13:13.681 8666-8896/com.yusufcakmak.exoplayersample D/OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
2021-01-18 18:13:13.699 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest>>
2021-01-18 18:13:13.704 8666-8896/com.yusufcakmak.exoplayersample I/System.out: [OkHttp] sendRequest<<
2021-01-18 18:13:15.388 8666-8893/com.yusufcakmak.exoplayersample E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:341)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:346)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)
```

![Screenshot from 2021-01-18 18-22-55](https://user-images.githubusercontent.com/26920113/104918918-7e70a500-59bb-11eb-900b-b5b35a7206b2.png)

- ExoPlayer version number
**2.12.3**
- Android version
**pie**
- Android device
Panasonic Tab 8 inch

**Comment by ojw28** [comment] 2021-01-18 16:47
Most likely the media is invalid, but without reproduction steps it's impossible to be sure. Please provide a link to test content that reproduces the issue, if you'd like for us to investigate further. You can do so by emailing `dev.exoplayer@gmail.com` if you'd prefer not to post publicly, although if you do this please also respond on this GitHub issue so that we know you've done so. Thanks!

**Comment by happysingh23828** [comment] 2021-01-19 05:45
@ojw28  I have downloaded the media and played from the local, it is playing. I guess it's more related to s3 links. as it throwing 416 status code, 

as it is working in mobile chrome as well as in all browsers on the web and mobile, 
![image (1)](https://user-images.githubusercontent.com/26920113/104992603-6c3c4880-5a47-11eb-9873-f0fd8c065a86.png)

**Comment by ojw28** [comment] 2021-01-19 09:52
As per my previous response, please provide a link to test content that reproduces the issue, if you'd like for us to investigate further. You can do so by emailing dev.exoplayer@gmail.com if you'd prefer not to post publicly, although if you do this please also respond on this GitHub issue so that we know you've done so. Thanks!

**Comment by happysingh23828** [comment] 2021-01-19 11:08
As URL contains very sensitive information we will be not able to share the data, I have observed that link which not working is getting redirected to the raw s3 path, but when we use raw path it is working fine, but when you put the masked layer, it is getting failed.

2nd thing is the range in request headers is setting out of range, our file size is 158 MB but the range in bytes going for 3.3GB.
![Screenshot from 2021-01-19 16-38-18](https://user-images.githubusercontent.com/26920113/105026626-c0115680-5a74-11eb-9f05-a05c6007aef3.png)
![Screenshot from 2021-01-19 16-02-51](https://user-images.githubusercontent.com/26920113/105026474-935d3f00-5a74-11eb-9d09-421e7bbdbcd4.png)

is redirection is causing the problem?

**Comment by ojw28** [comment] 2021-01-19 11:28
The player does appear to be requesting an invalid range, however it's not possible to say why this is happening without having a way to reproduce the problem. One possibility is that there was a previous request that returned invalid content, for example. Given you say that everything works fine without redirection, I would guess that the issue is most likely to be a server issue rather than an issue with ExoPlayer.

Sorry, but there's really nothing we can do to help without reproduction steps, so I'm going to go ahead and close this. If you're able to provide reproduction steps we can actually use, then please reply here and we will re-open the issue.

**Closed as completed by ojw28** 2021-01-19 11:28 UTC
Labels: wont fix: not reproducible

**Comment by happysingh23828** [comment] 2021-01-20 08:27
@ojw28  The issue is fixed by **increasing the read and connect timeout to 30 sec**, the default timeout is 8 sec.

**Comment by ojw28** [comment] 2021-01-20 09:06
I find it hard to understand how that could have an effect on 416 errors, but I'm happy you've solved your problem!
