### ISSUE TITLE
Player not switch to ENDED state when finish play HLS VOD

### ISSUE THREAD

**Issue by anhlevfx** [google/ExoPlayer#5180] opened 2018-12-02 06:46 UTC
### Issue description
The exoplayer play some shorts HLS VOD (under 10 mins) from our wowza server stuck buffering at the end of stream. Normally, exoplayer will change state to ENDED when get #EXT-X-ENDLIST tag. But, it don't do that, it just switch to BUFFERRING mode and not fire ENDED event. 

### Reproduction steps
Try play link I will send you to test. On demo app, I just write some code to listen event when player change state, and it return buffer state when play to last second of VOD.

### Link to test content
I will send you, please check email.

### Version of ExoPlayer being used
Exoplayer 2.9.1 and 2.8.4.

### Device(s) and version(s) of Android being used
Android TV 8.0.

### A full bug report captured from the device
Not provide.

**Comment by andrewlewis** [comment] 2018-12-03 11:24
Looks like the content is the same as the stream @AquilesCanta tested in the (off-topic) comments in #5005. I tested the stream and saw the same thing: the player transitions to the ENDED state as expected.

Can you reproduce the issue in the (unmodified) demo app?

**Comment by anhlevfx** [comment] 2018-12-10 07:03
Hello, I sent you email 5 days ago. In this email I have some new information and test link for you.

**Comment by anhlevfx** [comment] 2018-12-10 07:13
Hello, I test it again with the demo app and It worked, but the ads tag I use to tested is google sample ads tag. In the case I figure out  this issue I use another ads tag and I sent an email with more information for you. Please check it and let me know If you have new information

**Comment by tonihei** [comment] 2019-05-07 14:33
@andrewlewis Did you check the test data provided via email?

**Comment by andrewlewis** [comment] 2019-05-29 14:53
@anhlevfx Sorry for the delay looking at this. I tried to reproduce using the content and ad tag provided via email. The ad tag loads but eventually IMA arrives at an empty ad for the preroll so there is nothing to play. To see this please set `ImaAdsLoader.DEBUG` to true and look at the logging from the IMA SDK.

Regarding the behavior when reaching the end of the stream, I think the problem is that the ad tag defines an ad at 600 seconds but the media is only ~ 280 seconds long. I suggest removing this ad break, moving it within the duration of the content or marking it as a postroll.

**Closed as completed by andrewlewis** 2019-05-29 14:53 UTC
Labels: question
