### ISSUE TITLE
action&ReceiveClass : android.net.conn.CONNECTIVITY_CHANGE&com.google.android.exoplayer2.upstream.DefaultBandwidthMeter$ConnectivityActionReceiver.

### ISSUE THREAD

**Issue by lizuojing** [google/ExoPlayer#9569] opened 2021-10-15 06:40 UTC
action&ReceiveClass :
android.net.conn.CONNECTIVITY_CHANGE&com.google.android.exoplayer2.upstream.DefaultBandwidthMeter$ConnectivityActionReceiver.
exoplayer verison infomation:
implementation "com.google.android.exoplayer:exoplayer-core:2.12.2"
implementation "com.google.android.exoplayer:exoplayer-ui:2.12.2"
implementation "com.google.android.exoplayer:exoplayer-hls:2.12.2"

[report_log_2021-09-14_05_47_15_251.txt](https://github.com/google/ExoPlayer/files/7351392/report_log_2021-09-14_05_47_15_251.txt)

exoplayer version:2.12.2
android version:android 11
android device:xiaomi

please help determining whether this bug is fixed.

**Comment by claincly** [comment] 2021-10-15 09:25
Hi! Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by lizuojing** [comment] 2021-11-10 03:14
hi:
   please review report_log_2021-09-14_05_47_15_251.txt. I had uploaded the bugreport, and i have no other information.
please analysis this issue.

**Comment by ojw28** [comment] 2021-11-10 13:18
You haven't stated what the issue is. All I can see in the log file is some debug logging that does not appear to be indicative of a problem.

If you want us to look at something here, please reply here clearly describing what the issue is that you'd like us to analyze. In the meantime, I'll go ahead and close this issue. We will reopen it if further information is provided.

**Closed as completed by ojw28** 2021-11-10 13:18 UTC
Labels: question, need more info
