### ISSUE TITLE
Audio, Volume levels on Mp4 are lower than normal 

### ISSUE THREAD

**Issue by Ioan1995** [google/ExoPlayer#9512] opened 2021-09-30 12:23 UTC
[demo.log](https://github.com/google/ExoPlayer/files/7259448/demo.log)
I installed the ExoPlayer-demo application and added the following link to the media.exolist.json file: http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 also, I put the cleartextTrafficPermitted = true, to be able to play content. 
I just noticed that the audio output is lower than normal on mp4. So I had to set the android device to maximum volume, in order to hear the sound, since the TV was set at maximum volume.

**Comment by Ioan1995** [comment] 2021-11-05 08:53
Hello, can I get some info, please?
 Is this a bug or there is a way to increase the player volume since I have to set the device and TV volume to max to hear?

**Comment by krocard** [comment] 2021-11-05 18:33
Does this occur only with this media or with all media? Are other app playback affected? Could your AndroidTV be connected to an AV receiver that is set on a low volume?

**Comment by krocard** [comment] 2021-11-05 18:34
I checked the media and it has a normal loudness level.

**Comment by Ioan1995** [comment] 2021-11-09 10:58
There is no AV receiver. I also tested this link https://www2.cs.uic.edu/~i101/SoundFiles/StarWars60.wav and I have the same sound level. Maybe it's something related to android? These tests are done on android 7. Can this be a factor in this context and another implementation needs to be done?

**Comment by krocard** [comment] 2021-11-09 11:03
Does it occur only with just this file or with all media in the demo app? It could be that your media volume of your setup is low.

**Comment by krocard** [comment] 2021-11-09 11:04
Check your volume sliders in android sound settings.

**Comment by Ioan1995** [comment] 2021-11-09 11:24
It is the same on all files in the demo app. I also checked on an android 9 and there is a noticeable difference. I checked the volume and try to set it at the maximum possible. audioManager.setStreamVolume(AudioManager.STREAM_MUSIC,audioManager.getStreamMaxVolume(AudioManager.STREAM_MUSIC), 0)
![Screenshot 2021-11-09 at 13 23 56](https://user-images.githubusercontent.com/34036790/140915585-49ec450b-6a7b-4609-b3d4-12c6f0972e5f.png)

**Comment by krocard** [comment] 2021-11-09 16:18
If loudness is different depending on the same ExoPlayer version with different Android version, it seems the issue is either with your Android device or its setup.

As a result I don't see how we could help you. You might want to try a factory reset, but that is out of scope of this issue tracker. Sorry we can't help you more.

I will close this issue, please reopen if you have any additionally clues that ExoPlayer might be the culprit.

**Closed as completed by krocard** 2021-11-09 16:18 UTC
Labels: question
