### ISSUE TITLE
setVideoScalingMode not working - Video is stretched to fill the SurfaceView

### ISSUE THREAD

**Issue by suhaskam** [google/ExoPlayer#8882] opened 2021-04-28 13:28 UTC
I am using a SurfaceView and using SimpleExoPlayer for playback. 
The issue is that the video is stretched. No black borders appear on the left and right side of the video.

setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING) does not seem to have any effect.
Called this API while building SimpleExoPlayer too. No effect.
The video is rotated by 90, however , cropping does not work on removing the rotation metadata either.

**Comment by ojw28** [comment] 2021-04-28 17:28
Duplicate of https://github.com/google/ExoPlayer/issues/2484

**Closed as completed by ojw28** 2021-04-28 17:28 UTC
Labels: bug: in platform
