### ISSUE TITLE
Playback position accuracy for HLS gets worse over time

### ISSUE THREAD

**Issue by daynesh** [google/ExoPlayer#1684] opened 2016-07-19 14:38 UTC
Calling the ExoPlayer's `getCurrentPosition()` method later on in an HLS stream results in inaccurate playback position times. That is, a scene that should show at 2591000ms (43:11) actually appears at around 2584000ms (43:04).  

This is a significant problem for clients that use SSDAI streams where we expect an Ad to be shown at 43:11 and thereby render Ad-specific overlay controls at that time but, for this example, it will essentially be rendered 7 seconds too late.
### Notes:
- Calling this method earlier on in a stream appears to be close to accurate
- This issue is not being observed on other players (QuickTime, Brightcove Player, etc.)
- This is happening on both a real device as well as emulators

**Comment by ojw28** [comment] 2016-07-20 10:48
We have not received any other reports of this issue, which suggests that it doesn't happen in all cases. If you play the first HLS sample in the demo app you can observe that it displays the elapsed time in the video, and that it remains in sync with the progress bar throughout playback up to 30 minutes.

You'll need to provide some concrete reproduction steps that we can use if we're to investigate this issue, starting from the ExoPlayer demo app and providing sample content that can be used to reproduce the problem.

Also, please could you clarify what ground truth you're using (i.e. what are you assuming is the "correct" elapsed time, and how is this calculated)? There are multiple ways that you could derive elapsed time during an HLS playback, so it's unclear what assumptions you're making. Thanks!

**Comment by ojw28** [comment] 2016-08-02 15:49
We'll close this soon if no further information is provided. Thanks.

**Comment by daynesh** [comment] 2016-08-02 16:18
Sorry...I've been working on some other issues and haven't had the opportunity to get back to this.

We encode our videos through another process and use a third party to stitch the ads at specific times that they identify for us.  The reason why we can't really use the HLS sample in the demo app for testing this issue is because it has no Ads stitched in which would indicate the playback time when a particular ad should show up.

What's slowed us down here is providing a non-proprietary stream with something resembling Ads stitched into an HLS stream that we can make available here.  Not impossible though...just may take some time to generate a stream for you to test with on your end.

As far as ground truth, to summarize - we use a third party HLS provider that stitches in Ad breaks at times decided by either them or our Ad platform.  Once a stream is dynamically created for us, the Ad start times are also communicated to us prior to playing the stream.  It is these Ad start times that we use to compare between different video players.

**Comment by ojw28** [comment] 2016-08-08 13:41
Please file a new issue when you're able to provide a sample stream for us to look at. It seems equally likely to me that the source content, once ads have been stitched, is inaccurate (e.g. because the sum of the segment durations in the HLS media playlist drifts over time, which would be a violation of the HLS spec). Other players not experiencing this issue is not necessarily indicative of an ExoPlayer bug.

**Closed as completed by ojw28** 2016-08-08 13:41 UTC
Labels: need more info
