### ISSUE TITLE
MediaSessionId is zero if play song by clicking next in exoplayer.

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#7195] opened 2020-04-06 11:24 UTC
### [REQUIRED] Question
I am using sessionid for my equalizer functionality i got zero at every time i click on next button to play next song . Equalizer not working on next song if comes with click . 
If song complete then session id is generated greater than zero for second song after completion of first song. 
On click session id is zero every time .

i am beginner of exoplayer. Plz help me . 
I am using lollipop android version . I have searched and find that you have solved it but it is not sufficient for me .

**Comment by waqasyousafy** [comment] 2020-04-06 11:59
Any one here 
@icbaker ....

**Comment by AquilesCanta** [comment] 2020-04-06 12:16
Seems this is a duplicate of #7194. Please clarify if not, and I'll reopen.

**Closed as completed by AquilesCanta** 2020-04-06 12:16 UTC
Labels: duplicate

**Comment by waqasyousafy** [comment] 2020-04-06 12:49
I did not find any solution. I have search alot . I found sessionid zero every time i click next or previous button in exoplayer.
Plz help me .
