### ISSUE TITLE
Cannot play video that can be played by MediaPlayer lib

### ISSUE THREAD

**Issue by elr0nda10** [google/ExoPlayer#3574] opened 2017-12-11 11:35 UTC
### Issue description
Can I assume that video that can played using MediaPlayer can be played by ExoPlayer too?

If yes, then I have video with following specification:
1. Video format: AVC(PAL) (Main@L3) (3 Ref Frames)
2. Audio format: MPEG Audio (version 1) (Layer 2).

When played using ExoPlayer it didn't contain any error, but the video just blank (black screen), but the streaming still continue until finish.

### Reproduction steps
Sorry, but please just try the test content that I send, because I am not able to play anything using demo, but I just use standard exoplayer code (Using SimpleExoPlayer, DefaultDataSourceFactory, DefaultExtractorFactory and DefaultBandwidthMeter).

### Link to test content
https://www.dropbox.com/sh/ckep40ursacnuks/AAD3pVc9ZO5ecyqThzv-3nOxa?dl=0

### Version of ExoPlayer being used
r2.5.4

### Device(s) and version(s) of Android being used
MXa-4k android version 5.0

### A full bug report captured from the device
I'm sorry, because I cannot debug on device, and debug log from emulator seems not relevant, so I cannot provide output from logcat.

**Comment by erdemguven** [comment] 2017-12-11 14:23
Tried the given media on the demo app on Nexus 6:
```
12-11 14:18:52.505 I/DefaultRenderersFactory: Loaded LibvpxVideoRenderer.
12-11 14:18:52.505 I/DefaultRenderersFactory: Loaded LibopusAudioRenderer.
12-11 14:18:52.505 I/DefaultRenderersFactory: Loaded LibflacAudioRenderer.
12-11 14:18:52.506 I/DefaultRenderersFactory: Loaded FfmpegAudioRenderer.
12-11 14:18:52.506 I/ExoPlayerImpl: Init 30633945 [ExoPlayerLib/2.6.0] [shamu, Nexus 6, motorola, 21]
12-11 14:18:52.510 D/EventLogger: state [0.01, true, I]
12-11 14:18:52.517 D/EventLogger: state [0.01, true, B]
12-11 14:18:52.517 D/EventLogger: timelineChanged [periodCount=1, windowCount=1, reason=PREPARED
12-11 14:18:52.517 D/EventLogger:   period [?]
12-11 14:18:52.517 D/EventLogger:   window [?, false, false]
12-11 14:18:52.517 D/EventLogger: ]
12-11 14:18:52.518 D/EventLogger: loading [true]
12-11 14:18:52.793 I/OMXClient: Using client-side OMX mux.
12-11 14:18:52.808 D/EventLogger: Tracks [
12-11 14:18:52.808 D/EventLogger:   Renderer:0 [
12-11 14:18:52.808 D/EventLogger:     Group:0, adaptive_supported=N/A [
12-11 14:18:52.808 D/EventLogger:       [X] Track:0, id=19/257, mimeType=video/avc, res=720x576, supported=YES
12-11 14:18:52.808 D/EventLogger:     ]
12-11 14:18:52.808 D/EventLogger:   ]
12-11 14:18:52.808 D/EventLogger:   Renderer:2 [
12-11 14:18:52.808 D/EventLogger:     Group:0, adaptive_supported=N/A [
12-11 14:18:52.808 D/EventLogger:       [ ] Track:0, id=19/258, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=NO_UNSUPPORTED_TYPE
12-11 14:18:52.808 D/EventLogger:     ]
12-11 14:18:52.808 D/EventLogger:   ]
12-11 14:18:52.808 D/EventLogger:   Renderer:6 [
12-11 14:18:52.808 D/EventLogger:     Group:0, adaptive_supported=N/A [
12-11 14:18:52.808 D/EventLogger:       [ ] Track:0, id=19/8449, mimeType=application/cea-608, supported=YES
12-11 14:18:52.808 D/EventLogger:     ]
12-11 14:18:52.808 D/EventLogger:   ]
12-11 14:18:52.809 D/EventLogger: ]
12-11 14:18:52.809 D/EventLogger: videoEnabled [0.30]
12-11 14:18:52.880 D/EventLogger: videoDecoderInitialized [0.38, OMX.qcom.video.decoder.avc]
12-11 14:18:52.880 D/EventLogger: videoFormatChanged [0.38, id=19/257, mimeType=video/avc, res=720x576]
                                  
                                  [ 12-11 14:18:52.886 28574:21199 E/         ]
                                  not in avi mode
                                  
                                  [ 12-11 14:18:52.887 28574:21199 E/         ]
                                  not in avi mode
12-11 14:18:53.425 D/EventLogger: timelineChanged [periodCount=1, windowCount=1, reason=DYNAMIC
12-11 14:18:53.425 D/EventLogger:   period [104.75]
12-11 14:18:53.425 D/EventLogger:   window [104.75, false, false]
12-11 14:18:53.425 D/EventLogger: ]
12-11 14:18:53.425 D/EventLogger: loading [false]
12-11 14:18:53.451 D/EventLogger: state [0.95, true, R]
```

**Comment by AquilesCanta** [comment] 2017-12-11 15:24
This is a duplicate of #1894.

Try enabling `FLAG_ALLOW_NON_IDR_KEYFRAMES` for the `DefaultTsPayloadReaderFactory`. If you are using the `DefaultExtractorsFactory`, it can easily be done with `DefaultExtractorsFactory#setTsExtractorFlags`.

**Closed as completed by AquilesCanta** 2017-12-11 15:24 UTC
Labels: bug
