### ISSUE TITLE
Update trackselector parameters without clearing the buffered data

### ISSUE THREAD

**Issue by rajinikanth0602** [google/ExoPlayer#8898] opened 2021-05-04 19:49 UTC
We are providing 3 different player sizes for users to watch HLS videos and we want to restrict the video resolution to the player size, we are using `DefaultTrackSelector.ParametersBuilder.setMaxVideoSize()` and `trackselector.setParameters()` for updating the `maxVideoSize` dynamically, it is working fine but the buffered data is getting cleared and reloading, which is interrupting the users with buffering, exoplayer internally invalidating and reselecting the tracks whenever we call `DefaultTrackSelector.setParameters()`, is there a way to just update the max video height and max video width without clearing the buffered data?

**Comment by christosts** [comment] 2021-05-06 10:33
@tonihei can you please take a look?

**Comment by tonihei** [comment] 2021-05-06 11:52
That's a duplicate of #2250.

You can implement a custom solution if you like by subclassing `AdaptiveTrackSelection.canSelectFormat`. In there you can filter out unwanted formats during playback. Be mindful that `AdaptiveTrackSelection.canSelectFormat` is called on an internal playback thread and you need some form of message passing or synchronization to prevent threading issues.

**Closed as completed by tonihei** 2021-05-06 11:52 UTC
Labels: duplicate

**Comment by rajinikanth0602** [comment] 2021-05-19 11:19
@tonihei `canSelectFormat` helped me solve the issue if we don't have to clear the downloaded segments in both the cases `Adaptive -> Resolution (Ex: 720p)` and `Resolution -> Adaptive`, How can I achieve like youtube where I it clears downloaded segments in the case of `Adaptive -> Resolution` but not `Resolution -> Adaptive`, I tried clearing buffer using `TrackSelector.invalidate()` but it is not working.

**Comment by tonihei** [comment] 2021-05-19 12:25
You probably need to look into `TrackSelection.evaluateQueueSize` to clear already loaded segment from the playback queue.

**Comment by rajinikanth0602** [comment] 2021-05-20 16:51
@tonihei tried returning 0 in `evaluateQueueSize()`, it's not clearing the entire buffer, I know it is expected in older versions (https://github.com/google/ExoPlayer/issues/7969#issuecomment-700280622) and also youtube(Android) takes some time for applying the quality may be due to the same reason, do we have any solution with the latest version of exoplayer or any plans to fix this in future?, If not, what will be the maximum time player will take to apply the new resolution when we return 0 in `evaluateQueueSize()`?

**Comment by tonihei** [comment] 2021-05-20 17:36
The player can't clear the entire buffer without stopping playback because some of the samples were already consumed by the decoders and the rest of the output pipeline. If you return 0 in `evalauteQueueSize`, the player will discard as many chunks as possible and load the new format as soon as possible without interrupting playback.

**Comment by rajinikanth0602** [comment] 2021-05-31 20:00
@tonihei I am facing an issue with 2.14.0 related to blocking the formats using `canSelectFormat`.

Our test hls video has `256p`, `640p`, `1280p` and `1920p` (Url : https://cph-msl.akamaized.net/hls/live/2000341/test/master.m3u8), I am trying to achieve the seamless trackselection with custom adaptive track selection class overriding `canSelectFormat` and `evaluateQueueSize`. 

In case of Adaptive selection, we are blocking high resolution formats, for above test video, we are blocking `1920p`.
In case of non-Adaptive selection(like for ex: `256p` was selected), we are blocking all the formats except `256p`.

Ideally Exoplayer has to start loading the `256p` format once we start blocking all the other formats, but the player starts loading the `256p` only on seeking to some position, attached the logs below for the same.

At `00:52:37.331` in logs : User is in Adaptive mode, so we are returning `true` in `canSelectFormat` for `256p`, `640p`, `1280p` and the player has selected the `1280p`.

At `00:52:39.682` : User has selected `256p` track, we are returning `false` in `canSelectFormat` for all formats except `256p`, but in the logs you can see the player has started loading `1280p` at `00:52:44.010`, it continues to load 1280p till I seek to some position at `00:52:51.812`, after that it starts loading the correct format.  

`onLoadStarted` log is printed from AnalyticsListener callback. 

[logs_exoplayer.txt](https://github.com/google/ExoPlayer/files/6571989/logs_exoplayer.txt)
