### ISSUE TITLE
Exoplayer is not working on Micromax MT500 android 4.1.2 ,API 16

### ISSUE THREAD

**Issue by manishmips** [google/ExoPlayer#1725] opened 2016-08-08 05:43 UTC
here is logcat of player 

```
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
                                                                       at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:78)
                                                                       at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110)
                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:273)
                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:264)
                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                    Caused by: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
                                                                       at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:189)
                                                                       at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:129)
                                                                       at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:106)
                                                                       at com.google.android.exoplayer.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:35)
                                                                       at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.handlesTrack(MediaCodecAudioTrackRenderer.java:216)
                                                                       at com.google.android.exoplayer.MediaCodecTrackRenderer.handlesTrack(MediaCodecTrackRenderer.java:293)
                                                                       at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:76)
                                                                       at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110) 
                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:273) 
                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:264) 
                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:137) 
                                                                       at android.os.HandlerThread.run(HandlerThread.java:60) 
                                                                       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                    Caused by: java.lang.IllegalArgumentException
                                                                       at android.media.MediaCodecList.getCodecCapabilities(Native Method)
                                                                       at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:211)
                                                                       at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfosInternal(MediaCodecUtil.java:160)
                                                                       at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfos(MediaCodecUtil.java:129) 
                                                                       at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:106) 
                                                                       at com.google.android.exoplayer.MediaCodecSelector$1.getDecoderInfo(MediaCodecSelector.java:35) 
                                                                       at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.handlesTrack(MediaCodecAudioTrackRenderer.java:216) 
                                                                       at com.google.android.exoplayer.MediaCodecTrackRenderer.handlesTrack(MediaCodecTrackRenderer.java:293) 
                                                                       at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:76) 
                                                                       at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110) 
                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:273) 
                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:264) 
                                                                       at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                       at android.os.Looper.loop(Looper.java:137) 
                                                                       at android.os.HandlerThread.run(HandlerThread.java:60) 
                                                                       at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Comment by ojw28** [comment] 2016-08-08 09:50
Please can you upgrade the version of ExoPlayer that you're using to `1.5.9`. Does the issue still reproduce once you do that? If so, please provide the logcat output again, since we started logging something more useful in `1.5.9` for this type of failure. Please also provide a full bug report as requested in the issue template.

**Comment by ojw28** [comment] 2016-08-16 22:14
@manishmips28 - Please provide the requested information, or we'll close this issue. Thanks.

**Closed as completed** 2016-09-09 20:11 UTC
Labels: need more info
