### ISSUE TITLE
Embedded subrip titles are not visible past version 2.6.1

### ISSUE THREAD

**Issue by vrayv** [google/ExoPlayer#8370] opened 2020-12-18 09:14 UTC
Sub rip embedded subtitles are missing when playing videos with ExoPlayer library.

I noticed that this is working properly with version 2.6.1 but with the latest builds the functionality has been broken. I have been playing with the library code and determined 
that the problem is with decoder not properly activating for a selected track.

Sending the example video in the mail.

**Comment by tonihei** [comment] 2020-12-18 17:52
We didn't receive any email for this issue. Please make sure you put "Issue #8370" in the subject line of the email sent to exoplayer.dev@gmail.com. As this issue description doesn't contain much information so far, please also make sure to include all reproduction steps including example media that allows us to reproduce the problem. Thanks!

**Comment by vrayv** [comment] 2020-12-19 07:37
https://20.download.real-debrid.com/d/QUMAJXVVOKBHC/Greenland.2020.720p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv

Here you go.

**Comment by tonihei** [comment] 2020-12-21 09:58
I can see the subtitles for both English and Dutch in this file if I select the respective tracks. Please also provide a clear description of what you are seeing and what you expect to see.

**Comment by vrayv** [comment] 2020-12-21 18:43
It seems the problem is default track selection. Build 2.6.1 automatically selects the track. What is the command to do it with the latest build?

**Comment by tonihei** [comment] 2020-12-22 10:23
It looks like there was a bug back in 2.6.1. that got fixed by the PR in #4480. 

The file specifically specifies that the text track is **NOT** a default track that should be auto-selected. In 2.6.1 we accidentally parsed this information to set the `isForced` flag to `false` instead of the `isDefault` flag. So `isDefault` stayed at its initial value of `true` and we auto-selected the text track. In later versions after the bug fix, the flag was correctly parsed and we no longer auto-select this text track. 

If you'd like to display the text track, please turn it on manually (e.g. by setting parameters in the `DefaultTrackSelector`, see https://exoplayer.dev/track-selection.html).

**Closed as completed by tonihei** 2020-12-22 10:23 UTC
Labels: wont fix: intended behavior

**Comment by vrayv** [comment] 2020-12-22 22:52
thanks for clarification.
