### ISSUE TITLE
Exoplayer on android Q

### ISSUE THREAD

**Issue by EasonLiu09** [google/ExoPlayer#6139] opened 2019-07-08 09:21 UTC
### [REQUIRED] Issue description
Play system music folder's file will cause exoplayer NotFindFileException [permission denied],
but I already granted the permission at runtime both read and write permission.

compileSdkVersion 29
targetSdkVersion 29

### [REQUIRED] Reproduction steps

Path that cause this problem : /storage/emulated/0/Music/[FileName]

`
        
    private fun play(path: String) {
        val dataSpec = DataSpec(Uri.parse(path))
        val fileDataSource = FileDataSource()

        try {
            fileDataSource.open(dataSpec)
            val factory = DataSource.Factory { fileDataSource }

            val source = ProgressiveMediaSource.Factory(factory, extractorFactory)
                .createMediaSource(Uri.parse(path))

            player!!.prepare(source, true, false)

        } catch (e: Exception) {
            e.printStackTrace()
        }
    }`

### [REQUIRED] Link to test content

The problem is playing local music file so i provide a link where i download the file for my app,
http://freemusicarchive.org/music/Dee_Yan-Key/Classical_Lounge/01-A_Little_Night_Romance_1472

### [REQUIRED] A full bug report captured from the device
<img width="1063" alt="螢幕快照 2019-07-08 17 13 29" src="https://user-images.githubusercontent.com/16751638/60798473-cba77000-a1a3-11e9-98fd-d49348bd1b8e.png">

### [REQUIRED] Version of ExoPlayer being used
'com.google.android.exoplayer:exoplayer-core:2.10.2'

### [REQUIRED] Device(s) and version(s) of Android being used
pixel 3 Q beta4 does not work

Nokia TA1032 android Pie and it works

**Comment by tonihei** [comment] 2019-07-08 09:31
That's a duplicate of #6039. Android Q no longer allows direct access to random files.

**Closed as completed by tonihei** 2019-07-08 09:31 UTC
Labels: duplicate

**Comment by EasonLiu09** [comment] 2019-07-08 09:36
Thanks!!
