### ISSUE TITLE
EXT-X-START:TIME-OFFSET regEx implemented incorrectly

### ISSUE THREAD

**Issue by will-work** [google/ExoPlayer#2507] opened 2017-02-27 13:20 UTC
https://github.com/google/ExoPlayer/issues/1544 implements support for the `EXT-X-START:TIME-OFFSET` tag, however the regular expression defined in `HlsPlaylistParser` is incorrect because it does not recognise negative offsets. However, the code in `HlsMediaPlaylist` that sets the offset is correctly implemented because it does take into account negative numbers.

The fix is therefore a simple one: in com/google/android/exoplayer2/source/hls/playlist/HlsPlaylistParser the string `REGEX_TIME_OFFSET` should be changed from 

`private static final Pattern REGEX_TIME_OFFSET = Pattern.compile("TIME-OFFSET=([\\d\\.]+)\\b");`
to 

`private static final Pattern REGEX_TIME_OFFSET = Pattern.compile("TIME-OFFSET=([-\\d\\.]+)\\b");`

To reproduce, set the offset value in a media playlist to a negative number and run the demo app.

Reproduced on version 2.2 release using Samsung GT-I9295 (Android 5.0.1 API21)

Logcat snippet:

```E/EventLogger: internalError [0.34, loadError]
               com.google.android.exoplayer2.ParserException: Couldn't match TIME-OFFSET=([\d\.]+)\b in #EXT-X-START:TIME-OFFSET=-20
                   at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parseStringAttr(HlsPlaylistParser.java:375)
                   at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parseDoubleAttr(HlsPlaylistParser.java:383)
                   at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:287)
                   at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:128)
                   at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:41)
                   at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:115)
                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                   at java.lang.Thread.run(Thread.java:818)
```

**Comment by AquilesCanta** [comment] 2017-02-27 14:08
This is a duplicate of #2495. A fix will be available soon.

**Closed as completed by AquilesCanta** 2017-02-27 14:08 UTC
