### ISSUE TITLE
Background artwork for audio in Cast

### ISSUE THREAD

**Issue by enzobelli** [google/ExoPlayer#10126] opened 2022-03-29 14:49 UTC
Using `com.google.android.exoplayer2.MediaMetadata` it's possible to add only one artwork with `.setArtworkUri()`.
On a cast device with display, that artwork would display next to the title with no possibility to set a background, leaving the screen black when the playing controls disappear after a few settings.
A background artwork was displayed up until version 15 when we could use 'MediaMetadata.loadItems'.
Is there a way to display a background again?

**Comment by marcbaechinger** [comment] 2022-03-29 16:09
Thanks for reporting. I marked this as an enhancement, so we can provide this feature out of the box. Not sure when we will get to do this I'm afraid.  We can at least define a constant that defines a key that allows to add an additional URI for a background image in the `mediaMetadata.extras` bundle and then make `DefaultMediaItemConverter` take this into account.

Can you tell me what Cast API you would use to define the background image? We are currently using 

```
metadata.addImage(new WebImage(mediaItem.mediaMetadata.artworkUri));
``` 
to set the image. After a quick look into the API of the [`MediaInfo`](https://developers.google.com/android/reference/com/google/android/gms/cast/MediaInfo) I didn't find what that would be. Can you give me a nudge?

With the current version you can achieve this yourself by adding the property in the extras `Bundle` of `MediaMetadata`. You can then pass a custom `MediaItemConverter` to the constructor of the `CastPlayer` that takes the URI from the extras and puts it into Casts's `MediaInfo` object by using the API I was asking for above. :)

**Comment by enzobelli** [comment] 2022-03-31 17:12
Hi,
up until version 15 it was working out of the box by using `CastPlayer.loadItems()` because was accepting an array of `MediaQueueItem`. I was using `com.google.android.gms.cast.MediaMetadata` where I could use `metadata.addImage(new WebImage())` and the same artwork was used as background using some blurring effect. The display would also stayed on displaying the info. 
Now the Cast interface has completely changed and the display goes on timeout after a few seconds leaving the display completely black.

**Comment by abdurahmanadilovic** [comment] 2022-05-17 11:52
same issue, can't find an alternative to addImage on MediaItem and MediaItem is needed for .setMediaItem() on the CastPlayer. Also, the Chromecast TV interface dims after a couple of seconds, I assume because there is only one image loaded.

Looking at the CastPlayer it does internally convert MediaItem to MediaQueueItem before its sends data to the cast device, I think it would make sense to open the interface and make CastPlayer accept MediaQueueItem.

@marcbaechinger The issue is I think that currently there can be only one image set on the MediaItem, even if there is a custom converter class, MediaItem builder has an option to set only setArtworkUri() and I think we are missing something like setBackgroundArtworkUri(). The way that was done before was by calling addImage() multiple times.

**Comment by marcbaechinger** [comment] 2022-05-17 14:55
> The issue is I think that currently there can be only one image set on the MediaItem

For now you need to use the `MediaMetadata.extras` to add the second image and then use that in your custom `MediaItemConverter`. 

>  The way that was done before was by calling addImage() multiple times.

Thanks for the hint. That is useful.

**Comment by abdurahmanadilovic** [comment] 2022-05-17 15:22
> > The issue is I think that currently there can be only one image set on the MediaItem
> 
> For now you need to use the `MediaMetadata.extras` to add the second image and then use that in your custom `MediaItemConverter`.
> 
> > The way that was done before was by calling addImage() multiple times.
> 
> Thanks for the hint. That is useful.



> > The issue is I think that currently there can be only one image set on the MediaItem
> 
> For now you need to use the `MediaMetadata.extras` to add the second image and then use that in your custom `MediaItemConverter`.
> 
> > The way that was done before was by calling addImage() multiple times.
> 
> Thanks for the hint. That is useful.


What key can we use for the second image? I can only see one method in the MediaItem builder class and that is setArtworkUri()

**Comment by marcbaechinger** [comment] 2022-05-17 15:46
You can add it to the extras with your own key and then take it from there in the `MediaItemConverter`:

```
MediaItem.Builder builder = new MediaItem.Builder();
Bundle extras = new Bundle();
extras.putString(MY_KEY_CAST_BACKGROUND_IMAGE_URI, backgroundImageUri);
builder.setMediaMetadata(
    new MediaMetadata.Builder()
        .setExtras(extras)
        .build());
MediaItem mediaItem = builder.build();
```

Then in the `MediaItemConverter` you can get the image uri from `mediaItem.mediaMetadata.extras.getString(MY_KEY_CAST_BACKGROUND_IMAGE_URI)` and use it to create a cast `WebImage` to be added to the cast item.

**Comment by abdurahmanadilovic** [comment] 2022-05-18 13:48
> You can add it to the extras with your own key and then take it from there in the `MediaItemConverter`:
> 
> ```
> MediaItem.Builder builder = new MediaItem.Builder();
> Bundle extras = new Bundle();
> extras.putString(MY_KEY_CAST_BACKGROUND_IMAGE_URI, backgroundImageUri);
> builder.setMediaMetadata(
>     new MediaMetadata.Builder()
>         .setExtras(extras)
>         .build());
> MediaItem mediaItem = builder.build();
> ```
> 
> Then in the `MediaItemConverter` you can get the image uri from `mediaItem.mediaMetadata.extras.getString(MY_KEY_CAST_BACKGROUND_IMAGE_URI)` and use it to create a cast `WebImage` to be added to the cast item.

After passing in the custom MediaItemConverter to CastPlayer I was able to make it work as before, with no issues with the dimming on the Chromecast TV preview, the background image is visible. 👍

**Comment by marcbaechinger** [comment] 2022-05-27 16:30
I tested this with several Cast devices and I never got it working to show two different images. I also can not repro that no background image is displayed. It actually always behaves the same which is it used the first image that I add as a `WebImage` and uses this as the thumbnail as well as the background image:

![0](https://user-images.githubusercontent.com/584321/170740035-49549b13-bec6-462c-a9c9-386e5a349d50.jpg)

When I use the standard `MediaItemConverter` with a `MediaItem` that has a `mediaItem.mediaMetadata.artworkUri` the Chromecast TV and Sony Bravia both show the image as the background and  the thumbnail:

```
if (mediaItem.mediaMetadata.artworkUri != null) {
   metadata.addImage(new WebImage(mediaItem.mediaMetadata.artworkUri));
}
```

If I modify this for testing like this:

```
if (mediaItem.mediaMetadata.artworkUri != null) {
   metadata.addImage(new WebImage(Uri.parse("https://storage.googleapis.com/automotive-media/album_art_3.jpg")));
   metadata.addImage(new WebImage(mediaItem.mediaMetadata.artworkUri));
}
```

I'm using `MEDIA_TYPE_MUSIC_TRACK`:

```
new MediaMetadata(MediaMetadata.MEDIA_TYPE_MUSIC_TRACK)
```

It shows the first image for background and thumbnail again.

Can you give me some more information how you manage two show two different images? Or how to show the UI without a background image?


What device Cast device are you using?
Which Cast receiver app are you using on that device?
Can you send me a screenshot of the screen with a background image that is different than the thumbnail?

The screenshot above is with the `ExoPlayer Default receiver` and I get the same for the "Default receiver" (app id: CC1AD845)

**Comment by marcbaechinger** [comment] 2022-05-30 10:10
I tested with the devices below with a `single image, MediaMetadata.MEDIA_TYPE_MUSIC_TRACK`:

* Sony Bravia
* Chromecast Ultra
* Chromecast Google TV
* Android TV Nvidia Shield
* Nest Hub

The result was the same on all TV screen devices like Sony Bravia, Chromecast Ultra. Chromecast Google TV and Nvidia Shield. In all cases the background image was displayed by only adding a single image while adding a second image did not change something. Display on Nest Hub is a bit different but there is always a (blurry) background image used:

- Displays title and artist/album_artist, album.
- First image as the background.
- Large thumbnail with first image and progress bar below image.
- Displays pos and duration when paused.
- Always on.
 
If someone is seeing a different behavior please let me know with details about:

- what device is being used
- which cast Receiver applicationn (and version) is running on the Cast device  
- what ExoPlayer version is being used
- what Android Cast SDK version is being used
- what Cast APIs are called to achieve the improved behavior and how this changed the behavior on which devices.
- media file format being played

 
I'm changing the issue state to `won't fix obsolete` (and close the issue soon). Because it is unclear what is not working, how to fix this and for quick fixes people can use the `MeidaItemConverter` to do their own thing.  I would prefer to have this properly fixed in the library but it's unclear what the issue actually is and how to fix it.

**Closed as completed** 2022-06-28 01:04 UTC
Labels: wont fix: not reproducible, closed-by-bot
