### ISSUE TITLE
When play my own HLS stream, having mosaic appear occasionally

### ISSUE THREAD

**Issue by xuyunyu** [google/ExoPlayer#2033] opened 2016-11-04 07:04 UTC
Dear ExoPlayer team,

I have build EXOPlayer v2 demo, and add some my own HLS stream to play.
It dosn't work well , having some mosaic shown occasionally, but works well Using System build-in MediaPlayer. 
I have tested it on my android tv (android sdk version : 22) and phone (android sdk version : 23), both devices produced the same phenomenon.

Link to the stream:
http://cdn02.duolebo.com/HLS_jiayou02_149431L_ren/2200/jiayou02_149431L_ren_2200.m3u8

below is bug report file
[bug-report.TXT](https://github.com/google/ExoPlayer/files/570752/bug-report.TXT)

Thanks in advance.

**Comment by xuyunyu** [comment] 2016-11-14 01:39
Hope to get your reply. Thank you.

**Comment by AquilesCanta** [comment] 2017-01-31 14:42
This is most likely a duplicate of #1978. Shouldn't be reproducible in the last version of Exoplayer. Please reply to this issue if this is not the case. Confirmation would also be appreciated.

**Closed as completed by AquilesCanta** 2017-01-31 14:42 UTC
