### ISSUE TITLE
ExoPlayer crashes when switching from clear to widevine protected Media at the same resolution

### ISSUE THREAD

**Issue by steffencbc** [google/ExoPlayer#2924] opened 2017-06-08 09:14 UTC
### Issue description
On Nexux 5X with Android 7.1.2:
ExoPlayer crashes with java.lang.IllegalStateException at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method) android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2570) at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:899)

When Exoplayer is first playing an unprotected mp4 (e.g. dash stream) and switching to an widevine protected stream at the same video resolution.
This happends only in landscape mode.

On Nexus 9 with Android 7.1.1
The whole device gets broken. The video plays but every color on the screen is broken until the device is rebooted. (https://drive.google.com/file/d/0B7ITwTK_exuqbWxkalFmNFprTFU/view)

### Reproduction steps
In the ExoPlayer Demo app use the playlist configuration in media.exolist.json given below.
Start Demo App and rotate to landscape mode. 
Watch the video for some time. Make sure the player uses highest available quality, so that the second video starts at the same quality.
Now hit the skip Button (or seek till the end of the first video) to switch to the second (widevine protected) video at the same resolution. 
ExoPlayer crashed and device freeze for a on the Nexus 5 moment.
ExoPlayer plays the content but display items (except the video itself)  is broken (wrong color strange pixel)

### Link to test content
 {
        "name": "crashes if video 2 starts in the same resulution as video 1 ends..",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?video_id=d286538032258a1c&provider=widevine_test",
        "playlist": [
          {
            "uri": "https://storage.googleapis.com/wvmedia/clear/h264/tears/tears.mpd"
          },
          {
            "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd"
          }
        ]
      },

### Version of ExoPlayer being used
r2.4.1

### Device(s) and version(s) of Android being used
Nexus 5x with Android 7.1.2
Nexus 9 with Android 7.1.1

### A full bug report captured from the device
Nexus 5X
[bugreport-N2G47O-2017-06-08-10-20-04.zip](https://github.com/google/ExoPlayer/files/1060330/bugreport-N2G47O-2017-06-08-10-20-04.zip)
Nexus 9
[bugreport-N4F27B-2017-06-08-11-06-27.zip](https://github.com/google/ExoPlayer/files/1060467/bugreport-N4F27B-2017-06-08-11-06-27.zip)

**Comment by yqritc** [comment] 2017-06-27 12:38
@ojw28 
I'm also facing this issue. Any workaround for this?
maybe this issue is the same as #1806.

**Comment by steffencbc** [comment] 2017-06-28 07:42
Yes it is.
My workaround is to set a new view to the player when switching the video.
Since you have to refresh this view by yourself you are unable to use a ConcatenatingMediaSource.

**Comment by ojw28** [comment] 2017-06-28 08:55
Forcing usage of the secure decoder for playback of both the clear and protected content probably also works around the issue (and allows you to use ConcatenatingMediaSource). I'd suggest giving that a try.

**Comment by yqritc** [comment] 2017-06-28 11:43
@ojw28 
thanks for your advice!
I had a look at [MediaCodecRenderer](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L293) class to figure out how to force using secure decoder.
Is there any simple way to achieve this?
or do I need to create dummy drmInitData and open drm session like normal drm flow?

**Comment by ojw28** [comment] 2017-06-28 12:01
You could inject a custom `MediaCodecSelector` implementation that wraps the default one and forces selection of secure decoders when available. The `getDecoderInfo` method would look something like:

```
if (MimeTypes.isVideo(mimeType)) {
  // Always prefer secure video decoders, if available.
  MediaCodecInfo secureCodecInfo = wrappedSelector.getDecoderInfo(mimeType, true);
  if (secureCodecInfo != null) {
    return secureCodecInfo;
  }
}
return wrappedSelector.getDecoderInfo(mimeType, requiresSecureDecoder);
```

**Comment by yqritc** [comment] 2017-06-28 12:47
@ojw28 
yes, I did similar workaround.
but [codec.start()](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L359) throw Fatal signal 11.
The log shows
```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
```
maybe I need the right mediaCrypto when calling [configureCodec](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L356)?

**Comment by ojw28** [comment] 2017-06-28 19:04
Ah yes, my suggestion above probably doesn't work for the reason you describe. For a clean workaround we'd need to make more invasive changes. For example we'd need to allow acquisition of a `DrmSession` without any `DrmInitData`, so as to obtain the `MediaCrypto` up front. We'd then need to put the workaround into `MediaCodecRenderer`, I think. It wouldn't be necessary to have a custom codec selector.

**Comment by yqritc** [comment] 2017-06-30 09:49
thanks for your info.
I changed the code as you described.
I skipped the key request & key response of `mediaDrm` logic and then obtained `MediaCrypto`, but `codec.start()` throws `android.media.MediaCodec$CryptoException: Operation not supported in this configuration`.

**Comment by ojw28** [comment] 2017-07-03 11:09
That's unfortunate! We'll probably need to look at this in more detail, in that case.

**Comment by yqritc** [comment] 2017-07-03 11:54
@ojw28 
Sorry!! My testing branch was a bit old. After trying the above workaround based on the latest `dev-v2` and `release-v2` branches, it works now!

**Comment by yqritc** [comment] 2017-08-16 10:32
Forcing security level L3 may be also the workaround for this issue.
I have not confirmed with Nexus 5X and 9, but I've checked other 2 devices having the crash when switching content.

@ojw28 
I'm not familiar with widevine security levels, so could you please tell me the followings?
1. The issue is fixed because both the clear and protected contents are played by non-secure decoder? (The name of codec used for playing widevine content does not have ".secure" suffix)
2. Could you please tell me if this workaround cause any bad side effects?

**Comment by ojw28** [comment] 2017-08-16 12:39
1. It's likely that the issue only occurs when switching between secure and non-secure output, yes.
1. The side effect is that L3 is less secure than L1. Content providers may require you to use L1 for their content. If you're producing your own content, you'll need to decide for yourself what level of protection is acceptable to you.

**Comment by ojw28** [comment] 2020-02-05 00:22
Closing as part of a scrub of device specific issues that were filed more than 2 years ago.

**Closed as completed by ojw28** 2020-02-05 00:22 UTC
Labels: bug: device specific
