### ISSUE TITLE
Ideal delay in between calling release of Exoplayer and building it again with different asset.

### ISSUE THREAD

**Issue by SaurabhOfficial** [google/ExoPlayer#10417] opened 2022-07-07 13:03 UTC
When filing a question:
-------------------------
What would be the ideal duration to delay between building a new player with a new media asset and releasing the previous player instance? would it help with the failure rate with devices with restricted resources giving enough time to reclaim its resources?
cc @LuGO0

**Comment by christosts** [comment] 2022-07-07 15:32
`Player.release()` is blocking until all underlying resources are free, therefore the API intention is to be able to create a new player instance immediately after another instance is released. 

That said, we've seen errors  coming from lower-level components not being released immediately, either due to bugs in the platform or the OEM-implemented parts. Are you're seeing issues with resources  not released immediately? If yes, does this happen on specific ExoPlayer versions, Android OS versions and/or specific devices?

**Comment by dino-saurabh** [comment] 2022-07-07 20:33
Yes exactly, we are facing AudioTrackInitExceptions(<=28 API level) and IllegalStateExceptions(>=29 API level) while creating AudioTracks specifically in some devices, primarily Android Boxes.
In addition, we were also facing some `MediaCodec.CodecException.ERROR_INSUFFICIENT_RESOURCE` on some mobile devices as well. I can dig up the exact CPU models if that would be helpful @christosts

**Comment by christosts** [comment] 2022-07-08 10:47
I don't think there is a single delay value that you can use in your app and which will solve all these problems.
It could be that on a specific device a delay of 100-200ms works, but this delay is subject to the device and likely to be tuned with a try-and-error approach. Let me repeat that by design, no such delay is needed.

If it's not a big burden for you, I would consider adding this delay only on the devices that raise the errors you are observing and you think they are remedied from the delay. That's so you maintain as-good-as-possible behavior on the well performing devices.

For the specific errors (AudioTrack, MediaCodec), I'd advice to raise separate issues for each one, along with the additional information requested in the bug form (such as ExoPlayer version, Android OS, device, bug-report, content if possible). This is for two reasons. First, tracking one problem per github issue helps the conversation focus on one thing, especially if someone refers to an issue later.. Second, we may be able to offer specific solutions/workarounds for each individual solution.

Thank you.

**Comment by SaurabhOfficial** [comment] 2022-07-08 10:54
> For the specific errors (AudioTrack, MediaCodec), I'd advice to raise separate issues for each one, along with the additional information requested in the bug form (such as ExoPlayer version, Android OS, device, bug-report, content if possible). This is for two reasons. First, tracking one problem per github issue helps the conversation focus on one thing, especially if someone refers to an issue later.. Second, we may be able to offer specific solutions/workarounds for each individual

Yes, I have already done that but I thought we might need to have some discussion on delay as I feel all these errors are in one way or the other related to resource crunch on the device.
We will try and experiment with a few delay values for specific devices and update any positive results here.

**Comment by christosts** [comment] 2022-07-08 10:59
Thank you.

I'm closing this issue for now, please feel free to update it with any data that comes up after experimentation.

**Closed as completed by christosts** 2022-07-08 10:59 UTC
Labels: question
