### ISSUE TITLE
EXO PLAYER not playing some HD IPTV channels.

### ISSUE THREAD

**Issue by littlelitleStar** [google/ExoPlayer#4925] opened 2018-10-09 18:54 UTC
Hello everyone.

Im developing an app for IPTV, i have integrated EXO PLAYER , and its workin fine.
But i dont know why.

Some channels it doesnt play  ( usually those in HD )

Does anyone HAD this problem and knows how to fix it ?

**Comment by littlelitleStar** [comment] 2018-10-09 19:23
how to implement (TSExtrator) to setup workaround flag in default constructor.
how to use FLAG_DETECT_ACCESS_UNITS and FLAG_ALLOW_NON_IDR_KEYFRAMES

**Comment by Danishbutt1122** [comment] 2018-10-09 21:38
hello @psycomani  i also developing iptv app, and channles working fine on mobile but the issue is when i run app in android box, its just buffering.
in FAQ they said to add FLAGS but i dont know how to add flags
here is my code , to play and build mediasources

    `public void play(String url) {
        try {
            MediaSource mediaSource = buildMediaSource(Uri.parse(url));


            simpleExoPlayerView.setPlayer(player);


            player.prepare(mediaSource, true, false);
            player.setPlayWhenReady(true);
        } catch (Exception e) {

            Log.e("googo1", e.getMessage());
        }
    }

    private MediaSource buildMediaSource(Uri uri) {


       
        return new ExtractorMediaSource.Factory(
                new DefaultHttpDataSourceFactory(mHandler.userAgent)).
                createMediaSource(uri);
    }`

**Comment by Danishbutt1122** [comment] 2018-10-10 23:39
@ojw28 hello sir please slove that issue

**Comment by littlelitleStar** [comment] 2018-10-10 23:49
Does anyone gives a shit about these issues ,or you just fucking opened this fucking issues page. to fucking let people post here for no reason.

**Comment by tonihei** [comment] 2018-10-11 08:26
In order to help you with that we need more information about the actual problem. Please provide example media, used devices, ExoPlayer version and a bugreport as requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by littlelitleStar** [comment] 2018-10-11 21:05
tonihei !

there is no info that i can give to you. 
EXOPLAYER isnt playing some channels *mostly HD channels, I saw some problems like this and all answers were to add some FLAGS on EXO.

Flags are at this website https://google.github.io/ExoPlayer/faqs.html
on this section.
![image](https://user-images.githubusercontent.com/21010751/46833855-fe097580-cda9-11e8-9ee3-44d460fb551b.png)

But the problem is that i dont know how to add them.
Do you know how to add these FLAGS on exo ?( FLAG_ALLOW_NON_IDR_KEYFRAMES and FLAG_DETECT_ACCESS_UNITS )

**Comment by tonihei** [comment] 2018-10-12 09:21
As noted in the FAQ article you linked, you can use `setTsExtractorFlags` in the `DefaultExtractorsFactory`. 
And you can set the extractors factory when creating your media source (e.g. with `ExtractorMediaSource.Factory.setExtractorsFactory`).

**Comment by littlelitleStar** [comment] 2018-10-12 09:26
Can we contact in any other ways ( whatsapp or anything else) ?
I really dont get how to put this.

**Comment by tonihei** [comment] 2018-10-12 09:34
In your code above:
```
DefaultExtractorFactory extractorsFactory = new DefaultExtractorsFactory();
extractorsFactory.setTsExtractorFlags(/* your flags here */);
return new ExtractorMediaSource.Factory(
         new DefaultHttpDataSourceFactory(mHandler.userAgent))
     .setExtractorsFactory(extractorsFactory)
     .createMediaSource(uri);
```

**Comment by psycomani** [comment] 2018-10-12 09:36
https://ufile.io/02ytz

Here it is my exoPlayer.java , CODE.
i dont have any default extractorfacotry

**Comment by tonihei** [comment] 2018-10-12 10:01
Unfortunately, we don't have time to debug your code. Please try to set the extractor flags as in my post above.

**Comment by littlelitleStar** [comment] 2018-10-12 10:15
oh., I thought you could do this.

**Comment by littlelitleStar** [comment] 2018-10-12 19:33
Does anyone else , can give some HELP ?

**Comment by littlelitleStar** [comment] 2018-10-12 21:34
Hello tonihei !!
I fixed that, i ADDED ALLOW_NON_IDR_FRAMES , AND its working.
but i have another problem.

It plays channels with PIXELS 
![image](https://user-images.githubusercontent.com/21010751/46895121-5ce8f080-ce77-11e8-840b-8e8cd7aad2df.png)

Can we fix this ?

**Comment by tonihei** [comment] 2018-10-15 13:33
Second question is tracked by #4951. Closing this issue because the first question was answered.

**Closed as completed by tonihei** 2018-10-15 13:33 UTC
Labels: need more info
