### ISSUE TITLE
Key rotation questions

### ISSUE THREAD

**Issue by meladc** [google/ExoPlayer#3763] opened 2018-01-28 14:31 UTC
Hi,

We are trying to play live DASH streams with key rotation, with signaling both in the manifest and media segments, using standard keyIDs (i.e withotu key hirerachy schemes). We have the following questions:

1. Upon tune, the application reactively triggers a license request and gets a license with the current key and multiple future keys. The idea is that the application will not need to send future license requests if the keys are already included in an already acquired valid license.
What we see is that the player triggers a license request each time the PSSH in the media segments changes. I guess this is the expected behavior, but have the following questions:
  

- Assuming the app knows which keyIDs are available within the valid license, is there a way for the app/player to control whether to request a license challenge ?
-  Assuming the license challenge has already been generated for a non-required key, can the player/app decide to ignore it and filter out the license request? in this case, can the app return a dummy license response? this works for Shaka...
-  We also noticed that if a new license is returned, then the old one is invalidated. For example, if a the initial license include key1, key2 and key3, and the new license includes only key2, then playback will fail when the content reaches key3. Is this the expected behavior?

2. Questions regarding PSSH signaling:

- We noticed that if PSSH exists in the MPD, then the player will not trigger license requests based on PSSHs from the media segments? is this the expected behaviour?
- Is there a configuration that allows the player to ignore the PSSH from the MPD (Shaka has such configuration), or to act upon new PSSH from the media segments even if there is PSSH in the MPD?

Many thanks,
M

**Comment by ojw28** [comment] 2018-02-02 11:34
Key rotation is really something that we're doing a pretty bad job of supporting currently. Unfortunately it'll take some time to resolve. It's made significantly more complicated by `MediaDrm.KeyStatus` and `MediaCrypto.setMediaDrmSession` only being available from Marshmallow onward. We need to decide to what extent we want to try and support key rotation on a best-effort basis prior to Marshmallow, or whether to focus on Marshmallow+ only.

I'll try to answer your questions as best I can, given the above:

> Assuming the app knows which keyIDs are available within the valid license, is there a way for the app/player to control whether to request a license challenge ?

I don't think there's an easy way to do this at the moment, although if you're willing to go to the lengths of implementing your own `DrmSessionManager` then that would give you a huge amount of flexibility (probably enough to do both this and much more). You could of course fork the library provided implementation as a starting point.

> Assuming the license challenge has already been generated for a non-required key, can the player/app decide to ignore it and filter out the license request? in this case, can the app return a dummy license response? this works for Shaka...

Ditto.

> We also noticed that if a new license is returned, then the old one is invalidated. For example, if a the initial license include key1, key2 and key3, and the new license includes only key2, then playback will fail when the content reaches key3. Is this the expected behavior?

I think we need to more properly investigate key rotation to answer this question.

> We noticed that if PSSH exists in the MPD, then the player will not trigger license requests based on PSSHs from the media segments? is this the expected behaviour?

This is expected behaviour, although it could probably be changed trivially by modifying `FragmentedMp4Extractor.onMoofContainerAtomRead` to not ignore the media segment PSSH boxes in this case.

Why would it make sense to put a PSSH in the MPD if you're doing key rotation? Logically, wouldn't that PSSH be relevant to the whole duration of the period, since that's the level at which it's being defined? And if so, isn't that fundamentally at odds with key rotation?

If it does make sense, we can change the behavior of `FragmentedMp4Extractor` to match.

> Is there a configuration that allows the player to ignore the PSSH from the MPD (Shaka has such configuration), or to act upon new PSSH from the media segments even if there is PSSH in the MPD?

No, although see above. Same question applies.

**Comment by ojw28** [comment] 2018-04-22 21:59
Closing as answered.

**Closed as completed by ojw28** 2018-04-22 21:59 UTC
Labels: question
