### ISSUE TITLE
FLV - Unexpected exception loading stream

### ISSUE THREAD

**Issue by brucetoo** [google/ExoPlayer#1137] opened 2016-01-12 02:48 UTC
Hi, I meet the problem when use latest ExoPlayer, My Flv video url :http://pull.v.cc.163.com/pushstation/4f9415f3c37beb3d4eb927514878tc2.flv?wsSecret=db6ddbd68f23611af34b14ff23cd2ab0&wsTime=56946458&ccid=33515091&src=ccandroid&sid=052961d8002e8ab3

**If the url is not available, i will offer another one**
Log : 
```java

01-12 10:40:05.276 30339-31990/? E/LoadTask: Unexpected exception loading stream
                                             java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
                                                 at com.google.android.exoplayer.util.ParsableBitArray.readBits(ParsableBitArray.java:162)
                                                 at com.google.android.exoplayer.util.CodecSpecificDataUtil.parseAacAudioSpecificConfig(CodecSpecificDataUtil.java:125)
                                                 at com.google.android.exoplayer.extractor.flv.AudioTagPayloadReader.parsePayload(AudioTagPayloadReader.java:95)
                                                 at com.google.android.exoplayer.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:87)
                                                 at com.google.android.exoplayer.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:235)
                                                 at com.google.android.exoplayer.extractor.flv.FlvExtractor.read(FlvExtractor.java:142)
                                                 at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:753)
                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                 at java.lang.Thread.run(Thread.java:818)
```

Phone : Nexus 5x,  OS 6.0.1

I just change the sample code about MISC sample like : 
```java

 new Sample("Big Buck Bunny (FLV Video)",
        "http://pull.v.cc.163.com/pushstation/4f9415f3c37beb3d4eb927514878tc2.flv?wsSecret=db6ddbd68f23611af34b14ff23cd2ab0&wsTime=56946458&ccid=33515091&src=ccandroid&sid=052961d8002e8ab3", PlayerActivity.TYPE_OTHER),
 
```

**Comment by ojw28** [comment] 2016-01-12 10:18
@jeoliva - Can you please take a look at this?

**Comment by ojw28** [comment] 2016-01-13 15:45
The video is not available. Please could you provide a working link to a sample that reproduces the issue? Thanks!

**Comment by brucetoo** [comment] 2016-01-13 15:51
Sorry,the url is dynamic,This is a new one. http://pull.v.cc.163.com/pushstation/4e856d456b7e4e08cf2535945241.flv?wsSecret=ed643a5d70e44bd8766d613e2dd2ffba&wsTime=5696721f&ccid=520222&src=ccandroid&sid=052961d8002e8ab3

**Comment by brucetoo** [comment] 2016-01-13 15:53
If the url is not available again when you test it, Just reply ,i will offer new one immediately

**Comment by ojw28** [comment] 2016-01-13 16:25
Seems to be dead again. Is it possible to provide one that will remain valid for more than ~30 minutes?

**Comment by ojw28** [comment] 2016-01-13 16:28
Note: Another 30 minute one will be ok for the time-being, whilst you figure that out!

**Comment by brucetoo** [comment] 2016-01-13 16:39
It's a online live url, i can not ensure how long it will be available because that live show will be closed at anytime,here are new one,I hope it will hold on longer time http://pull.v.cc.163.com/pushstation/e63c793d24e4364ce2ba836039.flv?wsSecret=4c0eeda52551e6ad32f2fadde7c6aa16&wsTime=56967cf7&ccid=520666&src=ccandroid&sid=052961d8002e8ab3

**Comment by brucetoo** [comment] 2016-01-13 16:43
maybe cc.163.com has enough test url for you,but need one step to web debug proxy.Sorry again for this

**Comment by ojw28** [comment] 2016-01-13 17:02
Thanks. There are two problems:
- The media specifies its duration explicitly as 0.0. We currently take this to mean the media really is of 0 duration, but we should probably treat a value of 0 as unknown instead.
- The audio specific config parsing is incorrect.
I have fixes. We'll push them to the dev branch sometime this week.

**Comment by ojw28** [comment] 2016-01-14 17:19
Fixed on the dev branch.

**Closed by ojw28** 2016-01-14 17:19 UTC
Labels: bug, need more info
