### ISSUE TITLE
CastPlayer - STATE_ENDED never called in onPlayerStateChanged callback

### ISSUE THREAD

**Issue by JulienArzul** [google/ExoPlayer#6462] opened 2019-09-24 02:28 UTC
### [REQUIRED] Issue description
When using CastPlayer with a EventListener attached, when a media reaches the end, the `onPlayerStateChanged` callback is always called with STATE_IDLE instead of STATE_ENDED as expected (this is the behaviour of `SimpleExoPlayer`).

I've had a look at the code and this is because the RemoteMediaClient of the Cast SDK returns `PLAYER_STATE_IDLE` when a media is finished. However, you can access the "idle reason" via `remoteMediaClient.getIdleReason()`. If it returns `MediaStatus.IDLE_REASON_FINISHED`, it means that the media reached the end.

The fix would be pretty simple. In CastPlayer l.694, you should change the case that decides which STATE to report like this:
```
 /**
   * Retrieves the playback state from {@code remoteMediaClient} and maps it into a {@link Player}
   * state
   */
  private static int fetchPlaybackState(RemoteMediaClient remoteMediaClient) {
    int receiverAppStatus = remoteMediaClient.getPlayerState();
    switch (receiverAppStatus) {
      case MediaStatus.PLAYER_STATE_BUFFERING:
        return STATE_BUFFERING;
      case MediaStatus.PLAYER_STATE_PLAYING:
      case MediaStatus.PLAYER_STATE_PAUSED:
        return STATE_READY;
      case MediaStatus.PLAYER_STATE_IDLE:
        if (remoteMediaClient.getIdleReason() == MediaStatus.IDLE_REASON_FINISHED) {
          return STATE_ENDED;
        } else {
          return STATE_IDLE;
        }
      case MediaStatus.PLAYER_STATE_UNKNOWN:
      default:
        return STATE_IDLE;
    }
  }
```

### [REQUIRED] Reproduction steps
Cast a media to a Chromecast using the CastPlayer and read it until the end. Observe which state is emitted by `onPlayerStateChanged`

### [REQUIRED] Link to test content
It will happen with any media that has an ending.

### [REQUIRED] A full bug report captured from the device
I don't have a bug report

### [REQUIRED] Version of ExoPlayer being used
2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
Reproduced on a Pixel 3 with Android 10.
But this should happen on any device as it's related to the Cast implementation.

**Comment by AquilesCanta** [comment] 2019-09-24 09:52
Duplicate of #3969.

**Closed as completed by AquilesCanta** 2019-09-24 09:52 UTC
Labels: bug, duplicate

**Comment by JulienArzul** [comment] 2019-09-25 00:01
Duplicate of itself? 😕

**Comment by tonihei** [comment] 2019-09-25 08:18
Updated comment above to correct duplicate issue.

**Comment by AquilesCanta** [comment] 2019-09-25 10:25
Sorry! Copy paste fail!
