### ISSUE TITLE
The es data demux by exoplayer is incorrect

### ISSUE THREAD

**Issue by songqianglu** [google/ExoPlayer#9168] opened 2021-07-09 02:38 UTC
Hi:
 
   We need to use exoplayer for **HDR** authentication，but the test case  about "**SEI Message to VSIF conversion and Video / 
Metadata frame accuracy**." is failed . We dumped the es data **dumuxed** by exoplayer , and find the es data is incorrect, maybe some important frame data is been dropped. Please help us to solved this issue.

  We use the tool of elecard to check the es data,and find the first three frames(not only first frames) dumuxed by exoplayer is wrong:

![eyecleard](https://user-images.githubusercontent.com/73336352/125014231-e61cc880-e09f-11eb-9a25-77b5a81fd872.png)
  
   Use ffmpeg to play es data has error too:
![ffmpeg](https://user-images.githubusercontent.com/73336352/125015031-4c561b00-e0a1-11eb-9e4e-5c60bb83845a.png)

  We use the other player like **kodi** , and find the dumped data is right.

  The test file is mp4 and format is HEVC. So we think the Mp4Extractor maybe has some bug to parse the mp4 files. 

  
- ExoPlayer version number: The version we used is **2.12** , and the latest version **2.14** is still has this problem.
- Android version: android 11
- Android device: [Amlogic/ohm/ohm:11/RTT0.210618.002/58:userdebug/release-keys]
 3. The test media file of mp4 :
https://user-images.githubusercontent.com/73336352/125013780-09934380-e09f-11eb-9dd5-7dd0a3b61f75.mp4
4. The dumped data file dumuxed by exoplayer  and dumuxed by kodi:
[temp.zip](https://github.com/google/ExoPlayer/files/6788316/temp.zip)

**Comment by ojw28** [comment] 2021-07-21 22:10
There are a couple of differences between the dumped data that I can spot:

1. ExoPlayer is using 4 byte NALU start codes (0x00000001), where-as Kodi is using 3 byte codes (0x000001). I doubt this is causing a problem.
2. ExoPlayer is outputting data starting at sample 21 (zero-indexed). This is due to the file containing an edit list that drops the first couple of samples, together with [this code that advances to the next random access point](https://github.com/google/ExoPlayer/blob/r2.14.2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/AtomParsers.java#L644).

Could you try and reproduce the problem again with edit list processing disabled? You can do this by building the player using:

```
player =
    new SimpleExoPlayer.Builder(/* context= */ this)
        .setMediaSourceFactory(
            new ProgressiveMediaSource.Factory(
                new DefaultDataSourceFactory(/* context= */ this),
                new DefaultExtractorsFactory().setMp4ExtractorFlags(
                    Mp4Extractor.FLAG_WORKAROUND_IGNORE_EDIT_LISTS))
        )
        .build();
```

If you observe correct results in this case, I would hypothesise that sample 21 isn't really a random access point as it claims to be, and in fact relies on some data contained in some of the earlier samples.

**Comment by ojw28** [comment] 2021-07-21 22:28
I think the MP4 container is incorrect in marking sample 21 (zero-indexed) as a random access point. I think the next random access point after sample 0 is sample 24. I think you will find that disabling edit lists resolves the problem, in which case:

* Skipping to sample 21 is due to the combination of the edit list in the content and the limitation in the code as referenced above.
* The three green frames are due to sample 21 being incorrectly marked as a random access point in the MP4 container.

**Comment by songqianglu** [comment] 2021-08-13 05:32
@ojw28 Thankyou very much! Under your help the problem has been resolved, thank you !

**Closed as completed** 2021-08-13 05:32 UTC
Labels: question
