### ISSUE TITLE
Subtitle showing delayed in exoplayer library sample  version r2.18.7

### ISSUE THREAD

**Issue by bhaveshdotstudio** [google/ExoPlayer#11237] opened 2023-07-03 13:00 UTC
### Bug

- I have downloaded the sample of exoplayer library, and tried to add below URL to load and check the close caption is working or not. When I tried to play the video and check close caption at that time it is showing delay in showing the close caption text and the audio is moved forward.

Is there any way to change the close caption delay so that it can match with the audio. 
Is there any way to give margin to the substitle?

I have attached the screenshot of the video which I am trying to play and test it with the example.

URL : https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8
VTT File: https://bitmovin-a.akamaihd.net/content/sintel/hls/subtitles_en.vtt

the screenshot is also attached.
<img width="1334" alt="Screenshot 2023-07-03 at 6 17 04 PM" src="https://github.com/google/ExoPlayer/assets/108920283/95903405-18e4-4bf0-a922-a12949009b35">

**Comment by icbaker** [comment] 2023-07-03 14:54
I played this URL in the demo app (https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8), and selected the English subtitles, and didn't observe any sync problems between the subtitle text and the audio.

I didn't need to explicitly pass the WebVTT URL you pasted to the demo app, since the HLS stream already contains the necessary info to show subtitles.

Please can you clarify your reproduction steps? If you've added a JSON snippet to the demo app, can you paste it here for completeness? Maybe include a video with audio so I can see exactly the sync problem you're observing (the screenshot you've included doesn't seem to show a sync problem, the "Hey, sit still" line happens very close to that timestamp).

**Comment by bhaveshdotstudio** [comment] 2023-07-04 09:12
@icbaker yes it's showing very close to that timestamp.  But can we customization? if vtt file and exoplayer duration are showing subtitles same time.

Can we add a bottom margin in the subtitle?

I have checked with SubtitleView.setBottomPaddingFraction but showing any effect

**Comment by icbaker** [comment] 2023-07-04 09:37
Customising the offset between video file and sideloaded subtitles is not possible, it is tracked by https://github.com/google/ExoPlayer/issues/854. However that won't help for subtitles that are served as part of an HLS playlist (as in your example here). In that case I would recommend preparing the media so the subtitles are in sync (i.e. there should be no need for an app to mess with any custom offsets, because the stream should be correct).

You can customise the position of the WebVTT subtitles by setting the `line` attribute in the source file, or customising the `Cue` objects before they're displayed. More explanation of why `setBottomPaddingFraction` has no effect for WebVTT subtitles - and a discussion of these options here: https://github.com/google/ExoPlayer/issues/7934#issuecomment-694063859

I'm closing this because there appears to be no sync problem and I think the other questions have been answered.

**Closed as completed by icbaker** 2023-07-04 09:37 UTC
Labels: question, needs triage
