### ISSUE TITLE
TS HD video not playing on android 4.4 samsung

### ISSUE THREAD

**Issue by adetheprince** [google/ExoPlayer#1926] opened 2016-10-11 05:34 UTC
Hi there
Just tested the demo as it is, but I am not sure why the TS file that is HD is not playing.
Its giving me a n error ( but none are playable by this device ) but video playing fine with vlc?

**Comment by AquilesCanta** [comment] 2016-10-11 09:20
Since no additional information was provided, I will assume this is a duplicate of #1894.

**Closed as completed by AquilesCanta** 2016-10-11 09:20 UTC
Labels: duplicate

**Comment by adetheprince** [comment] 2016-10-11 15:36
And yet no answer given? both thread

**Comment by AquilesCanta** [comment] 2016-10-12 09:43
This thread is not getting an answer because it contains close to no information. That's why it was closed. The other thread did get an answer.
