### ISSUE TITLE
Does Exoplayer support the RTMPS URL ? While open the RTMPS link getting RtmpClient$RtmpIOException.

### ISSUE THREAD

**Issue by Jethvasagar** [google/ExoPlayer#5354] opened 2019-01-09 06:34 UTC
Following RTMPS link I trying to open in ExoPlayer-2.7.3.

`rtmps://hostname.net/.........../Video/64174.mp4`

Gettting following Exception

` E/ExoPlayerImplInternal: Source error.
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)`

Code

       
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector =
                new DefaultTrackSelector(videoTrackSelectionFactory);
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        PlayerView playerView = findViewById(R.id.simple_player);
        playerView.setPlayer(player);
        RtmpDataSourceFactory rtmpDataSourceFactory = new RtmpDataSourceFactory();

          path = "rtmps:///hostname.net/..../64174.mp4";

        MediaSource videoSource = new ExtractorMediaSource.Factory(rtmpDataSourceFactory)
                .createMediaSource(Uri.parse(path));

        player.prepare(videoSource);
    
        player.setPlayWhenReady(true);

Gradle implaementation 

  
    implementation 'com.google.android.exoplayer:exoplayer:2.7.3'
    implementation 'com.google.android.exoplayer:extension-rtmp:2.7.3'

**Comment by andrewlewis** [comment] 2019-01-09 13:27
Looking in the librtmp sources, I think rtmps:// should be supported ([here](https://github.com/ant-media/LibRtmp-Client-for-Android/blob/e23dd39/rtmp-client/src/main/cpp/librtmp/parseurl.c#L63)). The provided error information doesn't really help figure out exactly what is going wrong unfortunately. @ojw28 may have ideas.

If I were you I'd try turning on debug-level logging for librtmp and setting it up to log to logcat, then check if there are any other errors logged before the exception is thrown. You could also check [existing issues](https://github.com/ant-media/LibRtmp-Client-for-Android/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++rtmpioexception) in librtmp and file a new one if needed.

**Comment by ojw28** [comment] 2019-01-12 22:19
Probably a duplicate of #4200.

**Closed as completed by ojw28** 2019-01-12 22:19 UTC
Labels: duplicate

**Comment by Jethvasagar** [comment] 2019-01-16 05:44
It's not duplicate @ojw28, above question about RTMP Stream link and my question is regarding to RTMPS Stream.

**Comment by ojw28** [comment] 2019-01-16 08:57
Once it's established that RTMPS is expected to be supported (as per Andrew's comment above), it becomes likely to be a duplicate (as per my comment above). Not least because the stack trace is identical.

**Comment by Jethvasagar** [comment] 2019-01-17 12:58
Thank you for reply, If Exo-player support the RTMPS url then send me demo or sample code which one rtmps link play in Exo-player.
