### ISSUE TITLE
AudioTrack$WriteException: AudioTrack write failed: -2

### ISSUE THREAD

**Issue by markymark1988** [google/ExoPlayer#391] opened 2015-04-13 18:12 UTC
I am attempting to stream HLS videos using ExoPlayer. 

The two sample HLS videos I am using are:
http://a-hls.blip.tv/07/18/7396/Polaristest-RYANGOSLINGINTHEHAUNTEDMANSION-TheDailyByte659.m3u8
http://a-hls.blip.tv/07/18/7396/Polaristest-RYANGOSLINGINTHEHAUNTEDMANSION-TheDailyByte659.m3u8

Here is a link to the demo app I am using and the file that I changed. 
https://github.com/markymark1988/ExoPlayerDemo/blob/master/ExoPlayer-master/demo/src/main/java/com/google/android/exoplayer/demo/Samples.java
Only changed a couple lines. Search for the text "Test" to see where I changed it

I am simply using the demo app from the ExoPlayer library and changing the video URL. During playback at times I get the following exception:

04-13 10:55:29.761  22056-25992/? E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.audio.AudioTrack$WriteException: AudioTrack write failed: -2
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:255)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:753)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:448)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.audio.AudioTrack$WriteException: AudioTrack write failed: -2
            at com.google.android.exoplayer.audio.AudioTrack.handleBuffer(AudioTrack.java:457)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:251)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:753)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:448)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
04-13 10:55:29.783  22056-22056/? E/EventLogger﹕ playerFailed [9.83]
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.audio.AudioTrack$WriteException: AudioTrack write failed: -2
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:255)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:753)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:448)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.audio.AudioTrack$WriteException: AudioTrack write failed: -2
            at com.google.android.exoplayer.audio.AudioTrack.handleBuffer(AudioTrack.java:457)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.processOutputBuffer(MediaCodecAudioTrackRenderer.java:251)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:753)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:448)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by markymark1988** [comment] 2015-04-13 18:15
This actually precedes the exception above

04-13 11:13:16.104    1338-1756/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
04-13 11:13:25.645    1338-1850/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
04-13 11:13:25.678    1338-1732/com.google.android.exoplayer.demo E/android.media.AudioTrack﹕ AudioTrack.write() called with invalid size (6784) value

**Comment by ojw28** [comment] 2015-04-13 18:33
I can reproduce this on master, but not on the dev branch. So it's likely that this has been fixed already.

**Comment by ojw28** [comment] 2015-04-13 18:33
Please verify that you also see correct behavior with the dev branch.

**Comment by markymark1988** [comment] 2015-04-13 20:59
The dev branch does seem to have the correct behavior. Thank you for the fast reply!

**Comment by markymark1988** [comment] 2015-04-13 21:01
Will this be merged into master today? We're planning on releasing an app tomorrow morning and this seems to be the only problem. Thanks!

**Comment by ojw28** [comment] 2015-04-13 21:21
No. The dev branch contains major changes, and it'll be quite a while before it gets merged into master (> 2 weeks). Sorry.

**Comment by markymark1988** [comment] 2015-04-13 22:27
Ok I'll replace the ExoPlayer library in our project with the one from the dev branch.

**Comment by markymark1988** [comment] 2015-04-13 22:50
After adding the library from the dev branch I am getting compile errors. Is there a specific commit that you would recommend going back to so that I can add it to my project? 

Error:(48, 8) error: DemoPlayer is not abstract and does not override abstract method onDownstreamFormatChanged(int,Format,int,int) in BaseChunkSampleSourceEventListener
Error:(431, 3) error: method does not override or implement a method from a supertype
Error:(479, 3) error: method does not override or implement a method from a supertype
Error:(486, 3) error: method does not override or implement a method from a supertype
Error:(520, 3) error: method does not override or implement a method from a supertype
Error:(541, 3) error: method does not override or implement a method from a supertype
Error:(547, 3) error: method does not override or implement a method from a supertype

Error:(70, 8) error: DashRendererBuilder is not abstract and does not override abstract method onSingleManifestError(IOException) in ManifestCallback
Error:(110, 23) error: no suitable constructor found for ManifestFetcher(MediaPresentationDescriptionParser,String,String,String)
constructor ManifestFetcher.ManifestFetcher(String,HttpDataSource,Parser<MediaPresentationDescription>,Handler,EventListener) is not applicable
(actual and formal argument lists differ in length)
constructor ManifestFetcher.ManifestFetcher(String,HttpDataSource,Parser<MediaPresentationDescription>) is not applicable
(actual and formal argument lists differ in length)
Error:(115, 3) error: method does not override or implement a method from a supertype
Error:(204, 38) error: no suitable constructor found for DashChunkSource(ManifestFetcher<MediaPresentationDescription>,int,int[],DataSource,AdaptiveEvaluator,int)
constructor DashChunkSource.DashChunkSource(ManifestFetcher<MediaPresentationDescription>,MediaPresentationDescription,int,int[],DataSource,FormatEvaluator,Clock,long,long) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(ManifestFetcher<MediaPresentationDescription>,int,int[],DataSource,FormatEvaluator,long,long) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(MediaPresentationDescription,int,int[],DataSource,FormatEvaluator) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(DataSource,FormatEvaluator,List<Representation>) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(DataSource,FormatEvaluator,Representation...) is not applicable
(actual argument ManifestFetcher<MediaPresentationDescription> cannot be converted to DataSource by method invocation conversion)
Error:(228, 34) error: no suitable constructor found for DashChunkSource(ManifestFetcher<MediaPresentationDescription>,int,int[],DataSource,FormatEvaluator,int)
constructor DashChunkSource.DashChunkSource(ManifestFetcher<MediaPresentationDescription>,MediaPresentationDescription,int,int[],DataSource,FormatEvaluator,Clock,long,long) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(ManifestFetcher<MediaPresentationDescription>,int,int[],DataSource,FormatEvaluator,long,long) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(MediaPresentationDescription,int,int[],DataSource,FormatEvaluator) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(DataSource,FormatEvaluator,List<Representation>) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(DataSource,FormatEvaluator,Representation...) is not applicable
(actual argument ManifestFetcher<MediaPresentationDescription> cannot be converted to DataSource by method invocation conversion)
Error:(275, 35) error: no suitable constructor found for DashChunkSource(ManifestFetcher<MediaPresentationDescription>,int,int[],DataSource,FormatEvaluator,int)
constructor DashChunkSource.DashChunkSource(ManifestFetcher<MediaPresentationDescription>,MediaPresentationDescription,int,int[],DataSource,FormatEvaluator,Clock,long,long) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(ManifestFetcher<MediaPresentationDescription>,int,int[],DataSource,FormatEvaluator,long,long) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(MediaPresentationDescription,int,int[],DataSource,FormatEvaluator) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(DataSource,FormatEvaluator,List<Representation>) is not applicable
(actual and formal argument lists differ in length)
constructor DashChunkSource.DashChunkSource(DataSource,FormatEvaluator,Representation...) is not applicable
(actual argument ManifestFetcher<MediaPresentationDescription> cannot be converted to DataSource by method invocation conversion)
Error:(120, 3) error: method does not override or implement a method from a supertype
C:\Users\Mark\Desktop\maker\ExoPlayerDemo-master\ExoPlayer-master\demo\src\main\java\com\google\android\exoplayer\demo\player\DefaultRendererBuilder.java
Error:(23, 43) error: package com.google.android.exoplayer.source does not exist
Error:(24, 43) error: package com.google.android.exoplayer.source does not exist
Error:(50, 5) error: cannot find symbol class DefaultSampleSource
Error:(51, 13) error: cannot find symbol class DefaultSampleSource
Error:(51, 37) error: cannot find symbol class FrameworkSampleExtractor
C:\Users\Mark\Desktop\maker\ExoPlayerDemo-master\ExoPlayer-master\demo\src\main\java\com\google\android\exoplayer\demo\player\HlsRendererBuilder.java
Error:(44, 8) error: HlsRendererBuilder is not abstract and does not override abstract method onSingleManifestError(IOException) in ManifestCallback
Error:(65, 9) error: no suitable constructor found for ManifestFetcher(HlsPlaylistParser,String,String,String)
constructor ManifestFetcher.ManifestFetcher(String,HttpDataSource,Parser<HlsPlaylist>,Handler,EventListener) is not applicable
(actual and formal argument lists differ in length)
constructor ManifestFetcher.ManifestFetcher(String,HttpDataSource,Parser<HlsPlaylist>) is not applicable
(actual and formal argument lists differ in length)
Error:(69, 3) error: method does not override or implement a method from a supertype
Error:(74, 3) error: method does not override or implement a method from a supertype
C:\Users\Mark\Desktop\maker\ExoPlayerDemo-master\ExoPlayer-master\demo\src\main\java\com\google\android\exoplayer\demo\player\SmoothStreamingRendererBuilder.java
Error:(62, 8) error: SmoothStreamingRendererBuilder is not abstract and does not override abstract method onSingleManifestError(IOException) in ManifestCallback
Error:(95, 23) error: no suitable constructor found for ManifestFetcher(SmoothStreamingManifestParser,String,String,String)
constructor ManifestFetcher.ManifestFetcher(String,HttpDataSource,Parser<SmoothStreamingManifest>,Handler,EventListener) is not applicable
(actual and formal argument lists differ in length)
constructor ManifestFetcher.ManifestFetcher(String,HttpDataSource,Parser<SmoothStreamingManifest>) is not applicable
(actual and formal argument lists differ in length)
Error:(100, 3) error: method does not override or implement a method from a supertype
Error:(105, 3) error: method does not override or implement a method from a supertype
Note: C:\Users\Mark\Desktop\maker\ExoPlayerDemo-master\ExoPlayer-master\demo\src\main\java\com\google\android\exoplayer\demo\player\DebugTrackRenderer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Error:Execution failed for task ':demo:compileDebugJava'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED

**Comment by ojw28** [comment] 2015-04-13 22:59
The dev branch has API breaking changes. We don't guarantee API stability between releases - to do so would slow our ability to quickly evolve the player, particularly given the huge number APIs that the library defines.

The compiler error is actually in your own code (which was probably forked from the demo app, but has not been updated in the same way that the demo app code has been updated).

**Comment by ojw28** [comment] 2015-04-14 13:26
Marking as closed because it doesn't reproduce on the dev branch.

**Closed by ojw28** 2015-04-14 13:26 UTC
Labels: bug
