### ISSUE TITLE
Video Freeze and audio continues in tunneled playback of 4k content

### ISSUE THREAD

**Issue by PratimMallick** [google/ExoPlayer#7602] opened 2020-07-06 11:56 UTC
### [REQUIRED] Issue description
Video freezes at a random time and audio keeps playing while playing 4k content in tunneled mode. Our manifest has layers from 480p to 2160p with the peak bitrate of 25mbps

### [REQUIRED] Reproduction steps
Play a 4k content. Turn on tunnel mode from the mainActivity. After some time the video freezes and audio keeps playing. This happens particularly more often on flacky internet connection(something to do with layer switches)

### [REQUIRED] Link to test content
trying to get test content 

### [REQUIRED] A full bug report captured from the device
https://drive.google.com/file/d/1AT2J_hfq5bcT-nzRez2hn32k5I0SlljE/view?usp=sharing

### [REQUIRED] Version of ExoPlayer being used
2.11.7

### [REQUIRED] Device(s) and version(s) of Android being used
Amazon firestick 4k(AFTMM)

**Comment by tonihei** [comment] 2020-07-07 16:55
@andrewlewis  Do you mind taking an initial look to see if that sounds familiar? Feel free to reassign if it needs further investigation.

@PratimMallick  We likely can't do any investigation unless we have some media to test with. Does it also reproduce with any of the streams in our demo app?

**Comment by andrewlewis** [comment] 2021-01-05 11:02
I couldn't find anything in the bug report to help track down the cause of freezing video. With video tunneling the implementation is mostly in control of the device manufacturer so I suggest filing a bug with Amazon (if you haven't done so already).

If you find evidence of an ExoPlayer bug related to use of tunneling APIs or otherwise, or if you have a reference number for a bug with Amazon it would be good if you could post further information here. I will close this issue now as I don't think there's anything else we can feasibly do to address the issue. We are working towards improving compatibility of video tunneling in future Android versions but the effects of that won't be visible for a while.

**Closed as completed by andrewlewis** 2021-01-05 11:02 UTC
Labels: bug: device specific
