### ISSUE TITLE
When Android TV play video with rotation metadata, some time get wrong stream decode rotation.

### ISSUE THREAD

**Issue by how8570** [google/ExoPlayer#11038] opened 2023-03-06 07:58 UTC
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

Adnrdoi studio ide build-in Emulator:
- Android TV (1080p) API 30 x86
- Android TV (1080p) API 30 x86 - AOSP version

Real Device
- Sony BRAVIA device build-in Android 10
  - Sometime may not reproduce. Click quicker when app start is easier to reproduce.

### Devices that do not reproduce the issue

Chromecast with Google TV

### Reproducible in the demo app?

No

### Reproduction steps

1. Open the app witch I provide.
2. Click buttons and check those videos. Check the playback rotation correct.

### Expected result

Those videos's rotation correct.

### Actual result

The track was squeezed on those devices.

### Media

I will submit the video files, the app and demo beheavior via e-mail.

===================================================
I am not sure witch column to fill the additional disgustion/symptoms , so I leave here.

It may reproduce on Sony BRAVIA itself app call "Media Player" or VLC app.
If the video track contain rotation metadata, it may play wrong direction.
I also tried the [media3](https://developer.android.com/jetpack/androidx/releases/media3) `androidx.media3:media3-exoplayer:1.0.0-rc01`, it get the same result.
Witch i guess it probably relate to hardware decode timing issue? 

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.
  - submited with related videos.
  - The videos with rotation metadata are on source code dir `app\src\main\res\raw`, I forgot attach additional.

**Comment by DevMehta1206** [comment] 2023-03-10 00:58
Hello @christosts can i please join you to solve this issue.

**Comment by christosts** [comment] 2023-03-20 09:33
@how8570 thank you for the detailed information and data, I will check them and update this issue.

@DevMehta1206 thank you for offer to help, if you have any experience with rotation that you want to share, please feel free. However any content and data that were sent to us via email cannot be shared without a permission from @how8570

**Comment by christosts** [comment] 2023-03-20 10:47
I can repro on Android TV emulator for API 30 and 31, but not 33. Also, I'm not able to repro on a phone. I'll forward this to the Android TV team too to see if there is something in the platform.

[internal ref  274415985]

**Comment by how8570** [comment] 2023-03-20 12:14
@christosts thanks your concern and look forward to your good news! (ゝ∀･)b

@DevMehta1206 I can share you the data if you need it, feel free to ask. (´・ω・)つ📑

**Comment by DevMehta1206** [comment] 2023-03-20 12:21
@christosts @how8570  I think this error or bug is device specific. or may be due to bug in that device OS version.

**Comment by how8570** [comment] 2023-04-07 02:07
Hi guys, is there any new update or discover?

**Comment by how8570-syno-dev** [comment] 2024-01-17 07:55
Hi @christosts, is there any update?

**Comment by how8570** [comment] 2024-01-17 09:49
Hi @christosts, is there any update?

**Comment by christosts** [comment] 2024-01-19 12:04
Some news from the TV: this cannot be fixed retroactively on the specific TV and the Android TV emulator on API 33 does not repro.

I can provide assistance to work-around this on the app by tweaking ExoPlayer. Please let me know which version you are using currently and whether you are using the exoplayer UI or built your own.

**Comment by how8570-syno-dev** [comment] 2024-01-25 02:00
Hi @christosts 
Sorry for the late reply

I'm using media3 embedded ExoPlayer, here is my ExoPlayer version.
```gradle
final media3_version = "1.0.0-beta02"

implementation "androidx.media3:media3-exoplayer:$media3_version"
implementation "androidx.media3:media3-ui:$media3_version"
```

I'm using exoplayer UI `PlayerView` with xml like following
```
<androidx.media3.ui.PlayerView  
    android:id="@+id/player_view"  
    android:layout_width="match_parent"  
    android:layout_height="match_parent"  
    app:auto_show="false"  
    app:use_controller="false" />
```

And we also found that if we set  PlayerView `app:surface_type="texture_view"`. 
It can play the stream in the correct direction, witch solve this problem,
but unfortunately, the video playback **stutters**. (Because texture view need graphic sync?)

If there a work around may solve both direction & stutters?

---

I hope those info helpful.
We also can update the `media3_version` if needed.

**Comment by christosts** [comment] 2024-01-26 13:17
Looks like you found the way to rotate the video with the TextureView. if you want to use a SurfaceView, you'd need to use ExoPlayer.setVideoEffects() (you need to bundle the `effect` module on your apk). In general, you need to:
- call ExoPlayer.setVideoEffects() before playback starts
- don't let the player pass the rotation information on the codec
- apply a rotation effect when playback of the video starts

Getting things to work end-to-end with correct timings might be hard if you don't know the video rotation degress upfront, or if you have videos with different rotation metadata in one playlist. 

But before diving further, can you just try to call ExoPlayer.setVideoEffects({empty_list})? I tried a custom setup for this answer on the Android TV emulator but the rotation issue seems fixed just by calling Exoplayer.setVideoEffects(empty_list). Can you repeat the same test on your emulator and Sony TV?

**Comment by how8570** [comment] 2024-01-29 07:46
I tried the add `player.setVideoEffects({empty_list})` workaround, the playback seems become blank(black screen, but can hear audio).
The devices i tried:
 - Emulator (API 30)
 - GGwGTV 4k (physical device, Android 12, API 31-ext1).
 - [Not tried Sony TV yet, will update here later]

I pick the newer version media3 `1.2.1` for test.
And get following logcat:
<details>
<summary>Click to expand(running on Emulator)</summary>

```
15:10:51.085 ExoPlayerImpl            I  Init 69acd17 [AndroidXMedia3/1.2.1] [generic_x86, AOSP TV on x86, Google, 30]
15:10:51.226 libc                     E  Access denied finding property "vendor.display-size"
15:10:51.841 VideoCapabilities        I  Unsupported profile 4 for video/mp4v-es
15:10:51.985 HostConnection           D  HostConnection::get() New Host Connection established 0xf69bb1f0, tid 9388
15:10:52.022 HostConnection           D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
15:10:52.038 EGL_emulation            D  eglCreateContext: 0xf69a22f0: maj 2 min 0 rcv 2
15:10:52.070 EGL_emulation            D  eglMakeCurrent: 0xf69a22f0: ver 2 0 (tinfo 0xc69e3e90) (first time)
15:10:52.249 EGL_emulation            E  eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
15:10:52.249 EGL_emulation            E  tid 9388: eglQueryContext(2019): error 0x3004 (EGL_BAD_ATTRIBUTE)
15:10:52.407 OMXClient                I  IOmx service obtained
15:10:52.414 SurfaceUtils             D  connecting to surface 0xf1311528, reason connectToSurface
15:10:52.415 MediaCodec               I  [OMX.google.h264.decoder] setting surface generation to 9482241
15:10:52.415 SurfaceUtils             D  disconnecting from surface 0xf1311528, reason connectToSurface(reconnect)
15:10:52.415 SurfaceUtils             D  connecting to surface 0xf1311528, reason connectToSurface(reconnect)
15:10:52.415 SurfaceUtils             D  legacy buffer drop disabled: target sdk (34)
15:10:52.418 ACodec                   E  [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
15:10:52.434 ACodec                   I  codec does not support config priority (err -1010)
15:10:52.508 OMXClient                I  IOmx service obtained
15:10:52.519 ACodec                   I  codec does not support config priority (err -2147483648)
15:10:52.814 MediaCodec               D  [OMX.google.h264.decoder] setting dataspace on output surface to #104
15:10:52.828 Gralloc4                 W  allocator 3.x is not supported
15:10:52.850 SoftwareRenderer         D  setting dataspace on output surface to #104
15:10:53.320 AudioTrack               D  getTimestamp_l(21): device stall time corrected using current time 4509032684800
15:10:53.519 System                   W  A resource failed to call end. 
15:11:12.414 AudioTrack               D  stop(21): called with 855040 frames delivered
15:11:13.082 HostConnection           D  HostConnection::get() New Host Connection established 0xf69be1a0, tid 9702
15:11:13.087 HostConnection           D  HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
15:11:13.101 EGL_emulation            D  eglCreateContext: 0xf69a2d00: maj 2 min 0 rcv 2
15:11:13.103 EGL_emulation            D  eglMakeCurrent: 0xf69a2d00: ver 2 0 (tinfo 0xc69dd130) (first time)
15:11:13.105 EGL_emulation            E  eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
15:11:13.105 EGL_emulation            E  tid 9702: eglQueryContext(2019): error 0x3004 (EGL_BAD_ATTRIBUTE)
15:11:13.110 ExoPlayerImpl            I  Release 69acd17 [AndroidXMedia3/1.2.1] [generic_x86, AOSP TV on x86, Google, 30] [media3.common, media3.ui, media3.exoplayer, media3.decoder, media3.datasource, media3.extractor]
15:11:13.117 SurfaceUtils             D  connecting to surface 0xf1307e08, reason connectToSurface
15:11:13.117 MediaCodec               I  [OMX.google.h264.decoder] setting surface generation to 9482242
15:11:13.117 SurfaceUtils             D  disconnecting from surface 0xf1307e08, reason connectToSurface(reconnect)
15:11:13.117 SurfaceUtils             D  connecting to surface 0xf1307e08, reason connectToSurface(reconnect)
15:11:13.117 SurfaceUtils             D  legacy buffer drop disabled: target sdk (34)
15:11:13.117 SurfaceUtils             D  disconnecting from surface 0xf1311528, reason disconnectFromSurface
15:11:13.146 SurfaceUtils             D  disconnecting from surface 0xf1307e08, reason disconnectFromSurface
```

</details>


Is there any others settings should I set?

**Comment by christosts** [comment] 2024-01-29 10:01
Looking at the logs, it looks like the issue occurs with your app and not the demo app, right? If that's correct, may I ask two things:
- are you using the same app that you sent us when you raised this issue? Can you send us another email with a sample project that reproduces the issue?
- on your app/project, please attach an `EventLogger` on the ExoPlayer instance with `ExoPlayer.addAnalyticsListener(new EventLogger())`. That would produce additional logs for callbacks raised by the player.

**Comment by how8570** [comment] 2024-01-29 10:18
> Looking at the logs, it looks like the issue occurs with your app and not the demo app, right? If that's correct, may I ask two things:
> 
> * are you using the same app that you sent us when you raised this issue? 

Yeah, I tried those on another production app.
But sorry I'm not allow to share more this part infomation with you.

> Can you send us another email with a sample project that reproduces the issue?
> * on your app/project, please attach an `EventLogger` on the ExoPlayer instance with `ExoPlayer.addAnalyticsListener(new EventLogger())`. That would produce additional logs for callbacks raised by the player.

Okay, I will prepare another sample with those later on.
But it probably may take few days. When email sent to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com), I will also comment here to notify you guys.
Thanks 🙇

**Comment by how8570** [comment] 2024-01-30 08:02
Hi @christosts,
I sent the email to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with subject `Issue #11038 (follow up)`.

And I also provide a video that I occur the video playback become blank issue in the attachment,
Hope those data helps.

If you require any additional information, please feel free to ask. 🙇

**Comment by christosts** [comment] 2024-01-30 11:36
thank you for sending the project so soon. Can you grant me access to download the file? I've sent a request.

**Comment by how8570** [comment] 2024-01-30 11:37
Granted 👍

**Comment by christosts** [comment] 2024-01-30 15:49
I see the issue. Thanks again for sharing the project. 

The issue is  fixed on the main branch and should be included in the 1.3.0 rc01 and stable releases. We are already in 1.3.0-alpha01 so rc01 should be out within a month's time. Can you try to checkout Media3 source code and use the main branch with your app and verify?

**Comment by how8570** [comment] 2024-01-31 10:18
I tried the "1.3.0-alpha01" with `player.setVideoEffects({empty_list})` workaround on sampel app and my production app.

Tried Device:
- Emulator (API 30)
- GGwGTV 4k (physical device, Android 12, API 31-ext1).
- Sony TV

Besides a little part of video still play stutters and
when starting playing, there is a little blinking,
it work almost perfect 👍. (fix the rotation issue)

I think the solution is good to go.

But still, is there a way to fix the stutter and blinking issue?
If need, I can send the demo video to you.

**Comment by christosts** [comment] 2024-01-31 10:33
> I tried the "1.3.0-alpha01" with `player.setVideoEffects({empty_list})` workaround on sampel app and my production app.

The blinking issue is fixed in the main branch but not included in 1.3.0-alpha01 or the upcoming 1.3.0-beta01. The fix is scheduled to be in 1.3.0-rc01 and 1.3.0 stable. You can try the fix if you checkout the library sources, use the main branch and set your project to use the local Media3 checked out code rather than fetching the library binaries. There are some instructions at https://github.com/androidx/media?tab=readme-ov-file#locally

**Comment by how8570-syno-dev** [comment] 2024-02-01 10:53
I tried [main](https://github.com/androidx/media/tree/main) (current on [554530a](https://github.com/androidx/media/commit/554530a4268567ea77a9f5635424e634ddf9dc08))
and fix some build issue/skip some test issue on it.

I build those app via Android Studio and istall with adb connection.
It seems perfectlt solve the stutter/blinking issue.  🎉

Thanks!

---

But when I try to build apk and install to device via USB + File Explorer app, It cannot be install.
The device show a dialog only display `There was a problem while parsing the package.`
(apk with `$adb install` can perform install)
(import  `1.3.0-alpha01` with maven server, build apk can perform install via  File Explorer app)

Do you have any idea of this problem?

**Comment by christosts** [comment] 2024-02-01 15:21
> Do you have any idea of this problem?

I'm afraid I can't help, I have not come across this issue before . 

Since the rotation/blinking issue will be solved with 1.3.0-rc01 onward, I'll close this issue. Please feel free to re-open if needed.

**Closed as completed by christosts** 2024-02-01 15:21 UTC
Labels: bug, needs triage

**Comment by how8570** [comment] 2024-02-05 02:14
I found that might be File Explorer app issue, I change another one and everything works fine.

Thanks again.

**Comment by how8570** [comment] 2024-03-26 02:32
Hey @christosts sorry to bother you again.🙇

Since we found there another seeking issue ([media#1166](https://github.com/androidx/media/issues/1166)) on this workaround (add `ExoPlayer.setVideoEffects()`),
Can you provide any other workaround to solve this problem?
