### ISSUE TITLE
How to select closed caption track with DefaultTrackSelector?

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#7833] opened 2020-09-01 02:43 UTC
I'm using a `SimpleExoPlayer` instance with a `DefaultTrackSelector` to play a MPEG/TS stream. I'm trying to make the track selector to select a closed caption (cea608) track if present in the stream, using something like:
```
mTrackSelector.setParameters(
        mTrackSelector.getParameters()
                .buildUpon()
                .setPreferredTextRoleFlags(C.ROLE_FLAG_CAPTION)
                .build());
```
However, this doesn't work, because both `SeiReader` and `UserDataReader` create the text track with `Format.createTextSampleFormat`, which always end up setting `roleFlags` to `0`.

If you don't know beforehand the stream content and/or structure, what is the correct way to set the track selector parameters such that the closed caption track is selected if it exists in the stream?

**Comment by tonihei** [comment] 2020-09-01 13:05
To solve your problem, I think you should be able to use `setSelectUndeterminedTextLanguage(true)` to instruct the player to select a track without language information.

Besides that, your proposal seems to make sense on a logical level. @AquilesCanta Do you know whether TS streams define the default semantics of the text track somehow? For example, would it be valid to assume they have `C.ROLE_FLAG_CAPTION`?

**Comment by goffioul** [comment] 2020-09-01 14:04
@tonihei Would that also work if the stream contain both closed captions and a subtitle track with undefined language? Or if there's no closed captions at all, only a subtitle track with undefined language (in which case, I don't want that track to be selected)?

**Comment by tonihei** [comment] 2020-09-01 14:08
I assumed you only have one unmarked track in the TS stream. If there are multiple tracks, how do know which one is the subtitle track and which is the closed caption one?

**Comment by goffioul** [comment] 2020-09-01 14:17
Well, that's my problem. You can't guide track selection with `DefaultTrackSelector` in that case. You could use mimetype (as it'll be different), but it's not exposed in the track selector. Or you could use `roleFlags`, but it's not used/set.

At the moment, I have to resort to creating a custom `DefaultTrackSelector` and override `selectTextTrack` to return the wanted selection based on the mimetype. I was wondering whether there was a way to achieve the same with regular `DefaultTrackSelector` and `roleFlags`, but I found out the role wasn't set.

**Comment by tonihei** [comment] 2020-09-01 14:26
Setting the role flag would be ideal to support your use case. To do that though, the stream needs to contain some metadata that tell ExoPlayer which role flag to use.

If you have multiple tracks that are already loaded, you can also override the selection directly by using `SelectionOverride` (see "Selecting specific tracks" in [this JavaDoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html)).

**Comment by goffioul** [comment] 2020-09-02 12:01
When `UserDataReader` or `SeiReader` creates the caption track, the role pretty much known and could at least contain `ROLE_FLAG_CAPTION`. Similarly when `DvbSubtitleReader` creates the track, the role could contain `ROLE_FLAG_SUBTITLE`.

**Comment by AquilesCanta** [comment] 2020-09-02 15:29
> if the stream contain both closed captions and a subtitle track with undefined language? Or if there's no closed captions at all, only a subtitle track with undefined language (in which case, I don't want that track to be selected)?

From the description, it sounds to me like the problem is complex enough that the best solution is either writing your own `selectTextTrack` as mentioned, or using track selection overrides (as Toni mentioned). From my overall understanding, the constraints seem more "static", in which case a TrackSelector customisation approach seems like a better fit.

Regarding the suggestion:

> When UserDataReader or SeiReader creates the caption track, the role pretty much known and could at least contain ROLE_FLAG_CAPTION. Similarly when DvbSubtitleReader creates the track, the role could contain ROLE_FLAG_SUBTITLE

It sounds to me that the proposed role flags are a proxy for the mime type (application/dvbsubs vs application/cea-608). Is this correct?

The role flags are intended to describe the role of the tracks independently of their type, and I think the presence of the role flags should be tied to the presence of role-metadata. A DVB subtitle or 608 caption could have either a subtitle or a captioning role, as far as I'm aware. Aside, I'd be surprised to see a stream containing both 608 and dvb text tracks.

Please let me know if the question is still unanswered.

**Comment by goffioul** [comment] 2020-09-02 16:07
> It sounds to me that the proposed role flags are a proxy for the mime type (application/dvbsubs vs application/cea-608). Is this correct?

Sort of. Using the role flag was the next best option, as you can't control track selection using the mimetype with `DefaultTrackSelector`.

> Please let me know if the question is still unanswered.

From your description, I see that I misunderstood the purpose of `roleFlags`, and it will never be set when playing a plain MPEG/TS stream (e.g. UDP multicast). So using a custom track selector is the only way to go.

For the record, I've encountered streams with both CC and DVBSUB on DVD.

**Comment by AquilesCanta** [comment] 2020-09-02 16:15
> you can't control track selection using the mimetype with DefaultTrackSelector.

That's correct (track overrides aside).

> the purpose of roleFlags

The current purpose is to describe the role of the content. For example, one track could contain just a translation of the audio (subtitle), while the other additionally include a description of the audio track (captions). Hope this is something you've seen around. I don't think the type of the text track inherently means one or the other. Specially considering DVB subtitles and 608 correspond to different TV standards, which I thought were mutually exclusive in the general practice.

> For the record, I've encountered streams with both CC and DVBSUB on DVD.

That's great to know. Thanks!

I'll be closing this for now. Please let me know if I missed anything here and I'll reopen.

**Closed as completed by AquilesCanta** 2020-09-02 16:15 UTC
Labels: question
