### ISSUE TITLE
Exoplayer 2.2.0 Application crashes when playing HLS playlist.

### ISSUE THREAD

**Issue by JGecys** [google/ExoPlayer#2525] opened 2017-03-03 13:53 UTC
When playing HLS playlist (index.m3u8) that has a list of mono.m3u8 streams with different bitrates, application crashes with this error:

`/ACodec.cpp:1016 CHECK(def.nBufferSize >= size) failed.`

HLS playlist format:
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=1328000
/mono1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1828000
/mono2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2628000
/mono3.m3u8

I've found similar issue (#877) with this error message, where it suggested added RESOLUTION tag to playlist. After I've tested with RESOLUTION tag added: some resolutions worked, while others didn't. For example: 1380x768 worked, 1920x1080 crashed.
After I downgraded to v2.0.4 there's no problems.
Not all devices crashes, but there are a lot of complaints.

**Comment by ojw28** [comment] 2017-03-03 20:53
Please provide sample content so we can reproduce the issue, together with a full bug report captured with `adb bugreport`, as is clearly requested in the issue template.

**Comment by ojw28** [comment] 2017-03-09 22:30
Closing due to lack of required information.

**Closed as completed by ojw28** 2017-03-09 22:30 UTC
Labels: need more info
