### ISSUE TITLE
Audio stuck in a loop since 1.5.0 version

### ISSUE THREAD

**Issue by victordigio** [google/ExoPlayer#1161] opened 2016-01-18 11:55 UTC
I have upgraded Exoplayer version from 1.3 to 1.5.0. After that, users with Samsung Galaxy S2 & S3 with Android 4.1 has several issues with Audio playback. Just after audio starts, it stuck in a 1 second loop and the playback doesn't continue. I can reproduce this error with several audios, like the next one: http://mvod.lvlt.rtve.es/resources/TE_S180GRA/mp3/2/8/1452683909582.mp3. This problems happens after app was updated with 1.5.0 version. It's seems to be a device specific issue, but a lot of users has this problem now. This error is easy to reproduce using the sample project and the link provided, in a Galaxy S2 or S3 with Android 4.1. In logcat, messages like the next ones appear all the time:
Discontinuity detected [expected 22729414, got 22410138]
Discontinuity detected [expected 22781657, got 22462383]
Discontinuity detected [expected 22833902, got 22514628]
Discontinuity detected [expected 22886147, got 22566873]
Discontinuity detected [expected 22938393, got 22619118]
Discontinuity detected [expected 22990637, got 22671363]

**Comment by ojw28** [comment] 2016-01-18 14:57
FYI - This is probably the same as #398?

**Comment by victordigio** [comment] 2016-01-18 15:16
True, it's seems to be the same error, any updates?

**Comment by andrewlewis** [comment] 2016-01-18 15:23
Closing as a duplicate of #398. I'll follow up on that bug.

**Closed by andrewlewis** 2016-01-18 15:23 UTC
