### ISSUE TITLE
how can we monitor for when an audio track has just completed in a ConcatenatingMediaSource ?

### ISSUE THREAD

**Issue by SogoGolf** [google/ExoPlayer#6972] opened 2020-02-13 06:08 UTC
Kind of struggling with this one. What we need to listen for / monitor - is when an audio track, that is in a ConcatenatingMediaSource (eg a list of 5 audio tracks), has just finished playing ? Is there an event for this, or a "combo" of events that we can monitor to know when this occurs ?

**Comment by kim-vde** [comment] 2020-02-13 13:48
Did you try using [`Player.EventListener#onTrackChanged`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onTracksChanged-com.google.android.exoplayer2.source.TrackGroupArray-com.google.android.exoplayer2.trackselection.TrackSelectionArray-)? It seems to be what you are looking for.  For more info, see our [listeners documentation page](https://exoplayer.dev/listening-to-player-events.html).

**Comment by kim-vde** [comment] 2020-02-13 14:20
Duplicate of #4707

**Closed as completed by kim-vde** 2020-02-13 14:20 UTC
Labels: duplicate, question
