### ISSUE TITLE
change cache and file directory  

### ISSUE THREAD

**Issue by karamgharam** [google/ExoPlayer#8061] opened 2020-10-10 10:01 UTC
hi I have an app that has 4 profile for one account , so I want when changing profile change cash and folder directory without restart app

**Comment by marcbaechinger** [comment] 2020-10-10 17:21
You need to create all media sources that are using a `CacheDataSource` again, with a new `SimpleCache` pointing to the new cached directory which is dedicated to a single user.

I think easiest would be to release the player and create a new one when the user profile is changed. This does not need a restart of the app, but you need to make sure  that all sources with a cache data source are created again. Creating the player again does make sure this is the case.

**Comment by karamgharam** [comment] 2020-10-12 07:20
> You need to create all media sources that are using a `CacheDataSource` again, with a new `SimpleCache` pointing to the new cached directory which is dedicated to a single user.
> 
> I think easiest would be to release the player and create a new one when the user profile is changed. This does not need a restart of the app, but you need to make sure that all sources with a cache data source are created again. Creating the player again does make sure this is the case.

thanks but my case is with download when change profile I want to change the cache directory for download, not for the player 
when change  can't download anything because the download failed, the app must restart to can download anything

**Comment by marcbaechinger** [comment] 2020-10-12 13:13
With the information you provide I can not really understand how you are approaching things. Can you please let me no a bit more of what you are doing?

From what you say I assume you are using a `DownloadService` for downloading. The download service has an abstract method `getDownloadManager` it is called in the services `onCreate` method and returns a `DownloadManager` your app has to provide. The `DownloadManager` takes a `DatabaseProvider` and a `Cache` object as arguments to its constructor. 

So if you want to achieve this you would have to make sure that the `DownloadService` is completely terminated when the user profile changes (`onCreate` of the service needs to be called again). Then you need to setup a specific `DatabaseProvider` and `Cache` for each user profile meaning your download service needs to know the current user and setup a specific database provider and cache. These are passed to the constructor of the `DownloadManager` which is returned by `DownloadService.getDownloadManager`. 

You then also need to make sure that the media sources are looking at the correct cache as explained above.

Please note that this is kind of an advanced implementation you are doing. We are likely not able to give you close 1:1 guidance. So beside reading the the[ Developer Guide page about downloading](https://exoplayer.dev/downloading-media.html) you should look into the source code of the components you are using like [`DownloadService`](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadService.java), [`DownloadManager`](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadManager.java) or [`DefaultDatabaseProvider`](https://github.com/google/ExoPlayer/blob/44293e8f45fc62ff918001b4425c44d0ded5ffc9/library/core/src/main/java/com/google/android/exoplayer2/database/DefaultDatabaseProvider.java). The [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo) that is using a `DownloadService` has some resources as well. Aremd with this, you should be able to ask concrete questions about your implementation which we can answer here.

Please not, that using the issue template speeds up things usually. So a good idea them for future issues. :)

**Comment by ojw28** [comment] 2020-10-12 19:21
> So if you want to achieve this you would have to make sure that the DownloadService is completely terminated when the user profile changes (onCreate of the service needs to be called again). Then you need to setup a specific DatabaseProvider and Cache for each user profile meaning your download service needs to know the current user and setup a specific database provider and cache. These are passed to the constructor of the DownloadManager which is returned by DownloadService.getDownloadManager.

I don't think this works, because `DownloadService` statically caches `DownloadManager` instances. As a result, `getDownloadManager` will not be called again even if the service is recreated.

I think the use case being described is probably just not supported, as things stand currently.

**Comment by marcbaechinger** [comment] 2020-10-13 11:46
Ok, thanks. I've hidden my comment from above to try to minimize the confusion I created.

**Comment by karamgharam** [comment] 2020-10-22 06:33
how to release manger then reinitialize it , and recreate demo download service @marcbaechinger  @ojw28

**Comment by marcbaechinger** [comment] 2020-10-22 10:56
Like ojw28 says above. The `DownloadService` caches `DownloadManager` instances in a static map. So there is no way to re-initialize the service with a download manager pointing to a user specific directory without restarting the app I'm afraid.

**Comment by karamgharam** [comment] 2020-10-22 11:37
thanks @marcbaechinger can you give me the best way to restart my app

**Comment by marcbaechinger** [comment] 2020-10-27 11:58
I don't know a way to restart the app I'm afraid. The user probably needs to do that.

**Comment by anonrootkit** [comment] 2020-10-27 12:22
@ojw28 
> I don't think this works, because `DownloadService` statically caches `DownloadManager` instances. As a result, `getDownloadManager` will not be called again even if the service is recreated.
> 
> I think the use case being described is probably just not supported, as things stand currently.

Then how Youtube and most apps (uses exoplayer) are able to switch between download mangers, when the user selects download in `sd card` and change the DownloadManager download directory to respective path.

**Comment by marcbaechinger** [comment] 2020-10-27 12:32
I don't know, but I suspect they are not using `DownloadService` and instead are having their own service or download component for this. ExoPlayer can play offline content from any `Cache` so you can fill the cache in any way you like. `DownloadService` and other offline components of the library is one way to fill the cache out-of-the-box. There are other ways to achieve that.

**Comment by marcbaechinger** [comment] 2020-10-27 12:39
You are right, @anonrootkit There is a duplicate of this issue which is #5993 I apologize for not having noticed this earlier. 
I think best is to keep discussion on a single issue, so we can keep everything together.

**Closed as completed by marcbaechinger** 2020-10-27 12:39 UTC
Labels: duplicate, question
