### ISSUE TITLE
State problem with multiple player instances

### ISSUE THREAD

**Issue by madhurkapadia** [google/ExoPlayer#1656] opened 2016-07-07 07:19 UTC
I have two exoplayer instance in which one i'm playing content and particular adpoints i'm playing advertise but when i am trying multiple MID ads exo player doesn't play the ad videos, it goes to PREPARING STATE and doesnt reach BUFFERING or END STATE, it happens after playing 2 ads repeatedly on 3rd AD and it gives below error:

```
MessageQueue: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {2b0939e5} sending message to a Handler on a dead thread
                                                                     java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {2b0939e5} sending message to a Handler on a dead thread
                                                                         at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                         at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                         at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                         at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                         at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
                                                                         at android.os.Handler.sendEmptyMessage(Handler.java:519)
                                                                         at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:212)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:818)
```

**Comment by andrewlewis** [comment] 2016-07-07 07:25
The stack trace is likely unrelated (see #426).

More information is needed to diagnose this. Can you reproduce the failure to complete preparation when playing the same media in the demo app? Please attach a bug report or send it to dev.exoplayer@gmail.com.

**Comment by ojw28** [comment] 2016-08-08 13:38
Closing due to lack of information.

**Closed as completed by ojw28** 2016-08-08 13:38 UTC
Labels: need more info
