### ISSUE TITLE
When paused, the current video frame sometimes takes a long period of time to update after a seek

### ISSUE THREAD

**Issue by jgarner** [google/ExoPlayer#564] opened 2015-06-18 23:49 UTC
Hey,

I was just wondering if there is anyway to refresh the current video frame when using seekTo when the video is paused?

Sometimes the frame does update after awhile but when I start the video playing again the frame pretty much loads straight away.

I did try a few things such as playing the video while seeking and trying to use the STATE_READY event to repause the video in hope the frame would update but this didn't work.

Thanks in advance.

Update: I'm playing a MP4 video

Josh

**Comment by ojw28** [comment] 2015-06-19 09:10
This should "just work". Are you using ExtractorSampleSource or FrameworkSampleSource? If you're using FrameworkSampleSource, read the warning at the top and use ExtractorSampleSource instead (which will likely resolve your issue).

**Comment by jgarner** [comment] 2015-06-19 09:51
Thanks for the reply.

I'm using ExtractorSampleSource.

I am rendering to a TextureView since I need to do some animations, maybe this could be the cause?

**Comment by jgarner** [comment] 2015-06-19 12:07
Funny thing,

I changed to using the deprecated FrameworkSampleSource and the frame updates while seeking when paused.

**Comment by ojw28** [comment] 2015-06-19 12:30
This should definitely work using ExtractorSampleSource (and definitely will not work in some cases for FrameworkSampleSource - in particular when the media doesn't have particularly even interleaving of audio and video samples).

Can you reproduce this in the ExoPlayer demo app? Can you reproduce it with the Big Buck Bunny sample video in the demo app, or is the issue specific to the media you're trying to play?

**Comment by jgarner** [comment] 2015-06-19 12:42
Ok, I tried the Big Buck Bunny video using the ExtractorSampleSource with the player I've built using the TextureView and it works fine :) so must be something up with the mp4 videos I'm trying to play, will need to investigate. Thanks for the help.

Josh

**Comment by ojw28** [comment] 2015-06-19 12:45
If you're able to share a sample video then it would be interesting to take a look. It's possible that your sample has extremely uneven audio/video sample interleaving, but my understanding was that FrameworkSampleSource is significantly worse at handling this, not better :).

If you are able to provide a sample video, please attach or link to it in an email to olly.exoplayer@gmail.com. No worries if not!

**Comment by jgarner** [comment] 2015-06-19 13:01
Thanks, I've sent you an example.

**Comment by ojw28** [comment] 2015-06-19 15:26
I'm pretty sure we're always rendering the frame eventually, but you're right, it sometimes takes a long time. There are two things going on here:

- The server is serving the content pretty slowly (at least where I am - I can't stream the video without it repeatedly re-buffering). The main issue, however, is described below.

- There's a line of code that allows the player to transition to the READY state before the first video frame has rendered. This is ironically to work around an issue with FrameworkSampleSource not handling sub-optimal interleaving as well as it should. The line in question is:

`|| getSourceState() == SOURCE_STATE_READY_READ_MAY_FAIL`

In the [MediaCodecViceoTrackRenderer](https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.java#L283) class. 

Once the player has transitioned into the READY state, but whilst it is still paused, it enters a mode where it executes its rendering loop at very low frequency, according to `IDLE_INTERVAL_MS` defined in the [ExoPlayerImplInternal](https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/ExoPlayerImplInternal.java#L61) class. It can require potentially many executions of the rendering loop body for the first frame to be rendered, because we do frame accurate seeking which can require feeding multiple frames through the decoder to reach the first one that we want to render.

So what happens in this case is the player enters the READY state having not drawn the first frame, and then the low frequency of the loop together with the fact it needs to be called many times results in the first frame not being rendered for a long time. When you press play the rendering loop is executed at a high frequency again, which is why the frame appears immediately in this case.

To fix this locally you could delete the offending line from MediaCodecViceoTrackRenderer. It's only there to work around a problem with FrameworkSampleSource, which you're not using. You could alternatively make IDLE_INTERVAL_MS much smaller, but this is undesirable because it will waste CPU/Battery when the player is paused.

On our side, we'll be deleting this line of code ourselves if/when FrameworkSampleSource finally goes away for good. We may also consider an intermediate term solution, if we can find one.

**Comment by jgarner** [comment] 2015-06-20 02:10
Awesome! thanks for the detailed explanation. I'll see what I can do locally :)

**Comment by jgarner** [comment] 2015-06-20 03:00
Confirmed fix. 

Patched MediaCodecViceoTrackRenderer class and removed '|| getSourceState() == SOURCE_STATE_READY_READ_MAY_FAIL'. 

Thanks heaps.

**Comment by ojw28** [comment] 2015-09-07 13:27
I think this was fixed by https://github.com/google/ExoPlayer/pull/628. Please let us know if not.

**Closed by ojw28** 2015-09-07 13:27 UTC
Labels: bug, question
