### ISSUE TITLE
Facing incorrect Duration with Exo Player player.getCurrentPosition function

### ISSUE THREAD

**Issue by vinoth56060** [google/ExoPlayer#3891] opened 2018-02-23 11:29 UTC
Hi Team,

 

We have an app where we use Exo Player Version: 1.5.12.

 

With the above mentioned player in order to get the exact duration of the content consumption we use player.getCurrentPosition function of the player.

 

Here we are facing issue with this function as at times we are getting random values from this function (for ex., 97391 seconds) instead of 30 seconds when user pause the video.

 

Hence we need your support and guidance in order to fix the issue because duration is very crucial for us to monitor the consumption of contents.

 

We agree that the player version is old and we can upgrade however will appreciate if you can share the release notes of the latest version of the player highlighting that the above mentioned issue is fixed in that particular release.

**Comment by vishal105** [comment] 2018-02-23 11:33
try to update player library and check it. it solved in 2.7.0 version.

**Comment by vinoth56060** [comment] 2018-02-23 13:04
I have checked the release notes for version 2.7.0 , but i couldn't find the solution for this issue in release notes, please highlight the solution for this issue if it is there in release notes or if anyone have any supporting doc related to this issue share the link.

**Comment by vishal105** [comment] 2018-02-23 14:40
Did you check in project?  try this https://github.com/vishal105/ExoPlayerSample

**Comment by ojw28** [comment] 2018-02-25 16:59
As you note, 1.5.12 is very old. If the issue is fixed in 2.7.0 then this is no longer an issue. I'm not sure exactly when the issue was fixed. If you're sufficiently motivated to find out, you could binary search of releases between 1.5.12 and 2.7.0 to find out.

**Closed as completed by ojw28** 2018-02-25 16:59 UTC
Labels: question
