### ISSUE TITLE
Opus NDK Build - libopus.mk referring to incorrect filename

### ISSUE THREAD

**Issue by Brahmasmi** [google/ExoPlayer#945] opened 2015-11-10 16:26 UTC
The libopus.mk file in the ExoPlayer/extensions/opus/src/main/jni directory contains the following line
```LOCAL_SRC_FILES += celt/arm/armopts_gnu.s.neon```
(https://github.com/google/ExoPlayer/blob/master/extensions/opus/src/main/jni/libopus.mk#L40)

However, there is no "armopts_gnu.s.neon" file within that directory. There is a "armopts_gnu.s" file generated from the "armopts.s.in" file. The "armopts_gnu.s" file is generated by running the "convert_android_asm.sh" script, as per the installation instructions on the opus extension readme.

Should we refer to the "armopts_gnu.s" file in libopus.mk or should the convert_android_asm.sh script output the extension for the armopts file as "_gnu.s.neon"? The next line in libopus.mk seems to substitute the ".s" filename with "_gnu.s.neon"
```LOCAL_SRC_FILES += $(subst .s,_gnu.s.neon,$(CELT_SOURCES_ARM_ASM))```
(https://github.com/google/ExoPlayer/blob/master/extensions/opus/src/main/jni/libopus.mk#L41)

**Comment by vigneshvg** [comment] 2015-11-10 18:37
Won't Fix - Working as intended

The .neon extension is passed on to ndk-build to indicate it to use that file only if the target architecture supports neon instructions. This will ensure that the resulting library will not contain neon instructions if the target architecture doesn't support it.

Here's the page that documents this rule: http://developer.android.com/ndk/guides/cpu-arm-neon.html#uns

**Closed by vigneshvg** 2015-11-10 18:37 UTC

**Comment by Brahmasmi** [comment] 2015-11-10 20:15
1) The following lines in the convert_android_asm.sh generate the "armopts_gnu.s" file.
```
# Generate armopts.s from armopts.s.in
sed \
  -e "s/@OPUS_ARM_MAY_HAVE_EDSP@/1/g" \
  -e "s/@OPUS_ARM_MAY_HAVE_MEDIA@/1/g" \
  -e "s/@OPUS_ARM_MAY_HAVE_NEON@/1/g" \
  libopus/celt/arm/armopts.s.in > libopus/celt/arm/armopts.s.temp
${ASM_CONVERTER} "libopus/celt/arm/armopts.s.temp" > "libopus/celt/arm/armopts_gnu.s"
rm "libopus/celt/arm/armopts.s.temp"
echo "Converted all ASM files and generated armopts.s successfully."
```
(https://github.com/google/ExoPlayer/blob/master/extensions/opus/src/main/jni/convert_android_asm.sh#L39-L47)

2) The following lines in the libopus.mk include the relevant ARM and NEON specific sources
```
ifneq ($(findstring armeabi-v7a, $(TARGET_ARCH_ABI)),)
LOCAL_SRC_FILES += $(CELT_SOURCES_ARM)
LOCAL_SRC_FILES += celt/arm/armopts_gnu.s.neon
LOCAL_SRC_FILES += $(subst .s,_gnu.s.neon,$(CELT_SOURCES_ARM_ASM))
LOCAL_CFLAGS += -DOPUS_ARM_ASM -DOPUS_ARM_INLINE_ASM -DOPUS_ARM_INLINE_EDSP \
                -DOPUS_ARM_INLINE_MEDIA -DOPUS_ARM_INLINE_NEON \
                -DOPUS_ARM_MAY_HAVE_NEON -DOPUS_ARM_MAY_HAVE_MEDIA \
                -DOPUS_ARM_MAY_HAVE_EDSP
endif
```
(https://github.com/google/ExoPlayer/blob/master/extensions/opus/src/main/jni/libopus.mk#L38-L46)

From what I understand, the armopts.s.in will always get converted to armopts_gnu.s, which implies that the NDK .neon logic will never get activated. This would happen even if the armeabi-v7a device does have support for the NEON instruction set. If this proposition is true, could you please share your perspective on the case in which the following line would be useful?
```
LOCAL_SRC_FILES += celt/arm/armopts_gnu.s.neon
```
The next line seems to always substitute the .s file extension with _gnu.s.neon for the files in the CELT_SOURCES_ARM_ASM source set
```
LOCAL_SRC_FILES += $(subst .s,_gnu.s.neon,$(CELT_SOURCES_ARM_ASM))
```
On a cursory glance, this seems to happen irrespective of whether the armeabi-v7a device does or does not support NEON. So would this be a risk on an armeabi-v7a device without NEON support?

Thinking aloud, from what I understand, armeabi-v7a mandates support only for the VFPv3-D16 fpu. Most armeabi-v7a devices do seem to support NEON, but some don't. So, I am not sure whether the .neon file extension logic is the appropriate idea on the armeabi-v7a ABI. Technically, determining the NEON support can happen only at runtime for armeabi-v7a. On the other hand, we may want to enable NEON support for the arm64-v8a ABI, since it is mandated to have NEON support.

Please let me know your thoughts on this.

**Comment by vigneshvg** [comment] 2015-11-12 17:43
The .neon tweak is just to ensure that it builds correctly without forcing -mfpu.

Opus actually does runtime detection to determine whether or not to use neon code: http://git.xiph.org/?p=opus.git;a=blob;f=celt/arm/armcpu.c;h=5e5d10c344474f7ae6eae6ed9264245671ca38f6;hb=refs/heads/master#l93
