### ISSUE TITLE
Exoplayer shows only one audio track

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#6101] opened 2019-06-27 11:07 UTC
### [REQUIRED] Issue description
Exoplayer shows only one audio track: russian. VLC shows two audio tracks: russian and english.

Exoplayer's output:
```
06-27 14:04:26.309 D/EventLogger( 4371): tracksChanged [0.24, 70.56, window=0, period=0, 
06-27 14:04:26.309 D/EventLogger( 4371):   Renderer:0 [
06-27 14:04:26.309 D/EventLogger( 4371):     Group:0, adaptive_supported=YES [
06-27 14:04:26.309 D/EventLogger( 4371):       [X] Track:0, id=0, mimeType=video/hevc, bitrate=1800000, res=720x576, supported=YES
06-27 14:04:26.309 D/EventLogger( 4371):       [X] Track:1, id=1, mimeType=video/hevc, bitrate=500000, res=352x282, supported=YES
06-27 14:04:26.309 D/EventLogger( 4371):     ]
06-27 14:04:26.309 D/EventLogger( 4371):     Metadata [
06-27 14:04:26.309 D/EventLogger( 4371):       com.google.android.exoplayer2.source.hls.HlsTrackMetadataEntry@b0dd75f
06-27 14:04:26.309 D/EventLogger( 4371):     ]
06-27 14:04:26.309 D/EventLogger( 4371):   ]
06-27 14:04:26.309 D/EventLogger( 4371):   Renderer:1 [
06-27 14:04:26.310 D/EventLogger( 4371):     Group:0, adaptive_supported=N/A [
06-27 14:04:26.310 D/EventLogger( 4371):       [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=rus, supported=YES
06-27 14:04:26.310 D/EventLogger( 4371):     ]
06-27 14:04:26.310 D/EventLogger( 4371):   ]
06-27 14:04:26.310 D/EventLogger( 4371):   Renderer:2 [
06-27 14:04:26.310 D/EventLogger( 4371):     Group:0, adaptive_supported=N/A [
06-27 14:04:26.310 D/EventLogger( 4371):       [ ] Track:0, id=1/8228, mimeType=application/cea-608, supported=YES
06-27 14:04:26.310 D/EventLogger( 4371):     ]
06-27 14:04:26.310 D/EventLogger( 4371):   ]
06-27 14:04:26.311 D/EventLogger( 4371):   Renderer:3 [
06-27 14:04:26.311 D/EventLogger( 4371):     Group:0, adaptive_supported=N/A [
06-27 14:04:26.311 D/EventLogger( 4371):       [X] Track:0, id=1/21, mimeType=application/id3, supported=YES
06-27 14:04:26.311 D/EventLogger( 4371):     ]
06-27 14:04:26.311 D/EventLogger( 4371):   ]
06-27 14:04:26.311 D/EventLogger( 4371): ]
```
ffmpeg's output:
```
Input #0, hls,applehttp, from 'http://80.77.52.234:21013/hls/relay/adaptive/MZmxiZ4/index.m3u8':
  Duration: N/A, start: 17616.264100, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 1800000
    Stream #0:0: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 720x576 [SAR 16:11 DAR 20:11], 25 fps, 25 tbr, 90k tbn, 25 tbc
    Metadata:
      variant_bitrate : 1800000
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 1800000
    Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 1800000
    Stream #0:3: Data: bin_data ([6][0][0][0] / 0x0006)
    Metadata:
      variant_bitrate : 1800000
    Stream #0:4: Data: bin_data ([6][0][0][0] / 0x0006)
    Metadata:
      variant_bitrate : 1800000
  Program 1 
    Metadata:
      variant_bitrate : 500000
    Stream #0:5: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 352x282 [SAR 16:11 DAR 256:141], 25 fps, 25 tbr, 90k tbn, 25 tbc
    Metadata:
      variant_bitrate : 500000
    Stream #0:6: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 500000
    Stream #0:7: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 500000
    Stream #0:8: Data: bin_data ([6][0][0][0] / 0x0006)
    Metadata:
      variant_bitrate : 500000
    Stream #0:9: Data: bin_data ([6][0][0][0] / 0x0006)
    Metadata:
      variant_bitrate : 500000
```

### [REQUIRED] Reproduction steps
Play content.

### [REQUIRED] Link to test content
http://80.77.52.234:21013/hls/relay/adaptive/MZmxiZ4/index.m3u8

### [REQUIRED] A full bug report captured from the device
[bugreport.txt](https://github.com/google/ExoPlayer/files/3334235/bugreport.txt)

### [REQUIRED] Version of ExoPlayer being used
ExoPlayer 2.10.0

### [REQUIRED] Device(s) and version(s) of Android being used
Android 6.0.1
STB GIEC MP1113 (chip Amlogic s905x)

**Comment by ojw28** [comment] 2019-06-28 08:43
Duplicate of https://github.com/google/ExoPlayer/issues/2014.

**Closed as completed by ojw28** 2019-06-28 08:43 UTC
Labels: duplicate
