### ISSUE TITLE
Help needed with playing *.mov file

### ISSUE THREAD

**Issue by andro-jedi** [google/ExoPlayer#11113] opened 2023-04-11 20:38 UTC
_Hi there, I've read all the information in your issue tracker and readme files. I tried different solutions but I can't play `*.mov` files like the attached one._ 

Please, help to find out if there is a way to play it via ExoPlayer maybe using some custom decoders or custom setup.
I was able to play mov files downloaded from the internet but not attached one.

[Video examples (google drive).](https://drive.google.com/drive/folders/1HGfhe0z6nR9MoO1AXWAX9G_nYvcfTA3f?usp=sharing) 

I'm using your demo project (latest `dev-v2 branch`) to attempt playing the video. I have a feeling that problem is in color profile yuv422p10le (there is one video in examples with converted color profile to yuv420 and it works). Maybe you will see what is wrong with the video (color profile, bitrate etc...) and why video track is not available in ExoPlayer. You have such a nice player but I can't use it without .mov files support. Thanks

[log_only_audio.txt](https://github.com/androidx/media/files/11186054/log_only_audio.txt)
[log_not_supported.txt](https://github.com/androidx/media/files/11186056/log_not_supported.txt)
[Libgav1VideoRenderer.txt](https://github.com/androidx/media/files/11186169/Libgav1VideoRenderer.txt)

[bugreport-zeus_eea-TKQ1.220807.001-2023-04-10-15-13-08.zip](https://github.com/androidx/media/files/11190698/bugreport-zeus_eea-TKQ1.220807.001-2023-04-10-15-13-08.zip)

Thanks in advance! _Sorry for creating issue here_ ¯\_(ツ)_/¯

**Comment by icbaker** [comment] 2023-04-12 07:12
Duplicate of https://github.com/androidx/media/issues/308

**Closed as completed by icbaker** 2023-04-12 07:12 UTC
Labels: duplicate
