### ISSUE TITLE
Does ExoPlayer support keyframe accurate seeking before an HLS media item is prepared?

### ISSUE THREAD

**Issue by ggabdol** [google/ExoPlayer#10497] opened 2022-08-02 17:25 UTC
Does ExoPlayer support keyframe accurate seeking before an HLS media item is prepared?

**Comment by icbaker** [comment] 2022-08-03 08:55
This looks like a duplicate of https://github.com/google/ExoPlayer/issues/10486

**Closed as completed by icbaker** 2022-08-03 08:55 UTC
Labels: duplicate
