### ISSUE TITLE
Trouble when trying to play some video link with a header

### ISSUE THREAD

**Issue by Marx-Hong** [google/ExoPlayer#6021] opened 2019-06-12 09:38 UTC
### [REQUIRED] Content description
hi , i am trying to play some video link with a header in exoPlayer ,but is always wrong. like this: 

```
ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 462
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:306)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```
this is my code: 

```
RenderersFactory renderersFactory = new DefaultRenderersFactory(context);
simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(videoView.getContext(), renderersFactory, trackSelector, loadControl);
// Produces DataSource instances through which media data is loaded.
DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent(context, context.getResources().getString(R.string.app_name)));
dataSourceFactory.getDefaultRequestProperties().set(Utils.USER_AGENT, (String) videoView.dataSource.headerMap.get(Utils.USER_AGENT));
if (videoView.dataSource.headerMap.get("Referer") != null) {
    dataSourceFactory.getDefaultRequestProperties().set("Referer", (String) videoView.dataSource.headerMap.get("Referer"));
}
String currUrl = videoView.dataSource.getCurrentUrl().toString();
MediaSource videoSource;
if (currUrl.contains("m3u8")) {
    HlsDataSourceFactory hlsDataSourceFactory = new DefaultHlsDataSourceFactory(dataSourceFactory);
    videoSource = new HlsMediaSource.Factory(hlsDataSourceFactory).createMediaSource(Uri.parse(currUrl), mainHandler, null);
} else if (currUrl.contains("mpd")) {
    videoSource = new DashMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(currUrl));
} else {
    videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(currUrl));
}
simpleExoPlayer.prepare(videoSource);
simpleExoPlayer.addVideoListener(this);
simpleExoPlayer.addListener(this);
simpleExoPlayer.setPlayWhenReady(true);
callback = new onBufferingUpdate();

simpleExoPlayer.setVideoSurface(new Surface(videoView.textureView.getSurfaceTexture()));
```

but the android.media.MediaPlayer can play this without any issue.I don't know where the issue is.

### [REQUIRED] Link to test content
link: https://cn-hbyc2-dx-v-18.acgvideo.com/upgcxcode/81/83/92558381/92558381-1-30032.m4s?expires=1560340800&platform=pc&ssig=b-ziF6i65w2kj7NuXI9gtg&oi=1903446436&trid=8679f1631a224dffb1bacfbfc307abcd&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1&mid=0
header: {"key":"Referer", "value":"https://www.bilibili.com/video/av52898645?spm_id_from=333.334.b_62696c695f646f756761.6"}
### [REQUIRED] Version of ExoPlayer being used
2.10.1
### [REQUIRED] Device(s) and version(s) of Android being used
any devices i can try

**Comment by marcbaechinger** [comment] 2019-06-12 21:11
The logs you provide show, that you are receiving a HTTP response code: 462  :) 

When I try this myself, it gives me a 403, Forbidden.
Can you check and make sure there is no server issue involved and try again?

**Comment by ojw28** [comment] 2019-06-17 10:07
This is a duplicate of https://github.com/google/ExoPlayer/issues/5911. Please don't file duplicate issues; it wastes valuable resources on our side. Please reply to the existing issue.

**Closed as completed by ojw28** 2019-06-17 10:07 UTC
Labels: duplicate
