### ISSUE TITLE
Messenger Audio incorrectly stop Exoplayer

### ISSUE THREAD

**Issue by mobile-pablo** [google/ExoPlayer#9287] opened 2021-08-11 15:24 UTC
I am using exoplayer in foreground service

Link : https://github.com/polonez-byte-112/Altas-Notas
ExoPlayer version: 2.14.2
Phone : Xiaomi Redmi Note 10 pro
Android version : 11 RKQ1.200826.002

I tried to record audio when ExoPlayer stopped ( correctly) but View was showing like its still playing. I need to pause and replay to get back to that state

**Comment by claincly** [comment] 2021-08-12 09:01
Are you saying the video starts playing after you start recording audio?

Please rephrase your question, like what is "view", what "state" you are getting back to.

**Comment by mobile-pablo** [comment] 2021-08-12 09:25
I am saying that mp3 stops playing when I start recording audio in messenger but PlayerView doesnt show its stopped

**Comment by ojw28** [comment] 2021-08-16 12:10
If the messenger app is acquiring transient audio focus, then this is working as intended. If this is the case, the messenger app is indicating that it's only going to need audio focus for a limited period, and will allow the app that was interrupted to automatically resume playback once it's done. The user intention that audio should be playing therefore still applies, and this is reflected in the UI. Note that if the UI didn't work this way, then it would be impossible for a user to tell the app not to automatically resume playback when exiting the transient state. The only choice that the user would have is between resuming playback immediately and resuming playback automatically when the messenger app releases its transient audio focus. The play/pause button would also toggle briefly to paused and then (by itself) back to playing again for most cases where another app only needs transient audio focus for a short period, which feels a bit strange to me.

We have seen some cases where an app will acquire transient audio focus and hold it indefinitely (e.g., https://github.com/google/ExoPlayer/issues/7182). In this case the app that was interrupted will be in a slightly strange state where the user has to toggle to paused and back to play in order to resume playback. This is unfortunate, but is a bug in the app that's not releasing transient audio focus rather than in the app whose UI is in the strange state. If the messenger app is not releasing transient audio focus when you stop recording, then you should report the issue to the relevant app team (it's unclear which messenger app you're referring to).

**Comment by mobile-pablo** [comment] 2021-08-16 12:12
I dont think You understand. Focus works but View doesnt update that its paused

**Comment by ojw28** [comment] 2021-08-16 12:17
I don't think anything I wrote is inconsistent with that. The audio app will stop playback when the messenger app requests audio focus (which I think is what you mean by "focus works), but because it's only a request for transient audio focus, the audio app expects that it'll be able to continue playback automatically after an expected short period during which the messenger app is holding transient focus. The UI is not updated in this expected short period of time, for the reasons I describe above.

**Comment by mobile-pablo** [comment] 2021-08-16 13:24
Thanks for explaining. I think We can close this issue.

**Comment by ojw28** [comment] 2021-08-16 13:28
Thanks!

**Closed as completed by ojw28** 2021-08-16 13:28 UTC
Labels: question
