### ISSUE TITLE
Buffer lost when seeked to backward and on orientation change if handling it using 2 different layout

### ISSUE THREAD

**Issue by Faiyyaz** [google/ExoPlayer#4984] opened 2018-10-19 14:41 UTC
### Issue description
Whenever i play a video in demo app and seek backwards then i lost all the buffered position till that time and it start buffering again. Also i have 2 layouts for different 1 for each orientation so if i toggle orientation and i release the player so cache is lost. And i m using HLS Stream. Is there a way to cache adaptive HLS strean?

### Reproduction steps
Play any video in demo app and do the above mentioned points.

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
LG Q6 8.1.0

**Comment by ojw28** [comment] 2018-10-19 16:41
> so if i toggle orientation and i release the player so cache is lost

If you release the player then that's just what happens. This is working as intended.

You need to either handle the orientation change manually to avoid the activity recreation, or alternatively retain the player instance across the orientation change. Closing because this doesn't seem like an ExoPlayer problem. You have to do one of these things when using e.g. MediaPlayer as well.

**Closed as completed by ojw28** 2018-10-19 16:41 UTC
Labels: should merge
