### ISSUE TITLE
Video stuttering after changing selected audio track with tunneling enabled

### ISSUE THREAD

**Issue by danielgliga3ss** [google/ExoPlayer#9993] opened 2022-02-21 16:47 UTC
If we try to change the selected audio track while the playback is paused, somehow the playback is resumed without changing PlayWhenReady state (playWhenReady is still false) but also not playing normally, the video is stuttering.
Please check this video: https://drive.google.com/file/d/1JmdOpIbZ59JAA_LzKRAvxlThXUB3bd_4/view?usp=sharing

Steps to reproduce the problem:
1. Pause the playback
2. Select an audio track (different than the one already selected)

The problem is reproducible only when tunneling is enabled and when it happens I can see many logs with this error:
`02-21 16:53:03.681  5131 21183 E bomx_video_decoder: FifoEmptyEvent: the video source FIFO becomes empty during normal decode`
We also contacted the device provider and they suggested that the problem is coming from the app/Exoplayer.
As far as I saw this is reproducible with any stream having multiple audio tracks. 

Logs:
[logcat.txt](https://github.co
[bugreport-uzx8020chm-PTT1.210912.001-2022-02-21-16-53-34.zip](https://github.com/google/ExoPlayer/files/8110893/bugreport-uzx8020chm-PTT1.210912.001-2022-02-21-16-53-34.zip)
m/google/ExoPlayer/files/8110892/logcat.txt)

ExoPlayer version: 2.16.1
Android device: Technicolor UZX8020CHM (https://sites.google.com/view/droid-tv/pay-tv-provider/com-hem-tv-hub) -> Android 9

**Comment by danielgliga3ss** [comment] 2022-03-24 09:16
Any news on this issue?

**Comment by christosts** [comment] 2022-03-25 14:32
I've been able to repro with the demo app (v2.17.1). We've seen issues with tunneling and being paused in the past. Probably, this is a duplicate of #5397. Such issues are coming from the layer's underneath the player. I'll check if there's an easy workaround we can do (or suggest) at the player level, but so far we have avoided to add workarounds (see conversation on #5397) and there is a high chance this will continue to be the case.

I'll also check with the platform team to see if there's something to be done at the framework level for new OS releases, or whether this has to be addressed solely by the OEM.

**Comment by christosts** [comment] 2022-03-25 16:06
Update: Previous issues have pointed at AudioTrack advancing its position although the player is paused, so I quickly attempted to `pause()` the AudioTrack instance created after the track change, and also not flushing the old AudioTrack instance. Both of these do not fix the issue. At the moment, this appears to be a behavior the player cannot control.

I'm afraid my only advice is to avoid using tunneling on this device, if you expect this symptom to cause a problem to your app. I would advise to reach out to the device manufacturer too. From prior experience however, even if the issue is fixed, it would either require a firmware update or an OS upgrade, which both require some time. 

[internal ref b/142856618].

I will close this issue as I don't think we can solve it inside the player, feel free to re-open though if you need additional help.

**Closed as completed by christosts** 2022-03-25 16:06 UTC
Labels: bug

**Comment by danielgliga3ss** [comment] 2022-03-28 08:00
Thank you @christosts 
We will check again with Technicolor.
