### ISSUE TITLE
Proximity sensor and audio mode

### ISSUE THREAD

**Issue by baole** [google/ExoPlayer#5997] opened 2019-06-05 14:12 UTC
### [REQUIRED] Searched documentation and issues
I'm looking for our specific use case but not sure how to handle it

### [REQUIRED] Question
Our app plays audio files with C.USAGE_MEDIA (probably equivalent to AudioManager.MODE_NORMAL). The sound is playing in the loud speaker (bottom speaker on many device)

```
                exoPlayer.setAudioAttributes(new AudioAttributes.Builder()
                        .setContentType(C.CONTENT_TYPE_SPEECH)
                        .setUsage(C.USAGE_MEDIA)
                        .build());
```

When the user raises the phone to ear, we are using proximity sensor to detect the event and switches the output to "phone call" top speaker (which is softer, not to disturb people around). It's done by changing the AudioManager's mode to AudioManager.MODE_IN_COMMUNICATION:
```
audioManager = (AudioManager) getSystemService(AUDIO_SERVICE);
audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
```
It works. However, the device takes  1-2 seconds to switch between modes. 

What is the proper way to handle that use case using ExoPlayer?

**Comment by AquilesCanta** [comment] 2019-06-05 17:56
@andrewlewis could you take a look at this?

**Comment by andrewlewis** [comment] 2019-06-19 06:57
To clarify, does the audio take two seconds to switch modes after calling `setMode`, or is the proximity sensor event delayed by two seconds? If it's the former, does stopping and re-preparing the player when switching modes fix the issue?

I wonder if the problem is related to the audio track having buffered data at the moment of changing modes, so clearing the buffer might help and is a quick thing to try. This would be a bit strange however. It seems more likely that this is a platform issue in which case the best approach would be to [file an Android bug](https://source.android.com/setup/contribute/report-bugs).

**Comment by andrewlewis** [comment] 2019-06-19 07:29
Another thing that might be worth trying would be to set new `AudioAttributes` to switch to voice communication usage: `player.setAudioAttributes(new AudioAttributes.Builder().setUsage(C.USAGE_VOICE_COMMUNICATION).build())`. Before API 21 (Lollipop) this will be the same as setting the stream type to voice call.

**Comment by baole** [comment] 2019-06-19 07:59
@andrewlewis it takes two seconds to switch modes after calling `setMode`. The audio is stored in the cloud. I will try with your suggested solution and get back with the result soon.

**Comment by mny459** [comment] 2019-07-15 12:55
> @andrewlewis it takes two seconds to switch modes after calling `setMode`. The audio is stored in the cloud. I will try with your suggested solution and get back with the result soon.

Have you fix it ？

**Comment by andrewlewis** [comment] 2020-05-07 09:44
Closing as it seems the main issue was addressed a while ago. If there's more to do please reply here or open a new issue.

**Closed as completed by andrewlewis** 2020-05-07 09:44 UTC
Labels: question
