### ISSUE TITLE
Video freezes wheen stream end

### ISSUE THREAD

**Issue by Stinger2198** [google/ExoPlayer#10046] opened 2022-03-09 18:50 UTC
- ExoPlayer version 2.17.0
- Android version 7
- Android device - Amazon Fire tv stick

When watching a video (streaming from the link), the video comes to the end of time but seconds continue to go further (for example, the video 30 seconds, when the video came to the end, the picture hangs, but the seconds continue to go 56/30) before updating the library, the OnPlayerStateChanged method from Playereventlistener class worked fine and now it is randomly, it can work immediately, and can after 30 seconds over time the video duration (59 out of 30 seconds) can work in a minute of 90 out of 30 seconds.
I can add apk for you test or example code from app.
My company using your player a long time and we never have had problem with that, but it came.
Thank you for help!!!

**Comment by Stinger2198** [comment] 2022-03-10 05:59
Exoplayer version 2.17.0 (last)

**Comment by ojw28** [comment] 2022-03-14 01:32
Please fully complete the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) if you want us to help with this issue. Please copy the issue template and fill it out inside this issue, rather than creating a new one. Thanks!

**Comment by Stinger2198** [comment] 2022-03-15 15:31
> Please fully complete the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) if you want us to help with this issue. Please copy the issue template and fill it out inside this issue, rather than creating a new one. Thanks!

Updated, please check.

**Comment by ojw28** [comment] 2022-04-22 14:01
Duplicate of https://github.com/google/ExoPlayer/issues/10083

**Closed as completed by ojw28** 2022-04-22 14:01 UTC
Labels: duplicate

**Comment by Stinger2198** [comment] 2022-04-22 14:51
Updated my question, please check

пт, 22 апр. 2022 г. в 17:01, Oliver Woodman ***@***.***>:
