### ISSUE TITLE
Redmi Note 3: DecoderInitializationException playing any MP3

### ISSUE THREAD

**Issue by rustyshelf** [google/ExoPlayer#2542] opened 2017-03-09 06:29 UTC
### Issue description
We just released a new version of our app that uses ExoPlayer. It fixed a tonne of issues we've had over the years with Android MediaPlayer and other related libraries, so firstly: thanks!

The only issue we've encountered so far is that two specific devices seem unable to playback any MP3 files. The devices in question are: 

> Xiaomi - Redmi Note 3
> Wiko Getaway

On those devices attempting to play an MP3 results in the following exception:
```
com.google.android.exoplayer2.ExoPlaybackException
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:376)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.y(MediaCodecRenderer.java:363)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.b(MediaCodecRenderer.java:770)
	at com.google.android.exoplayer2.audio.e.b(MediaCodecAudioRenderer.java:213)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.v(MediaCodecRenderer.java:501)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:484)
	at com.google.android.exoplayer2.f.f(ExoPlayerImplInternal.java:464)
	at com.google.android.exoplayer2.f.handleMessage(ExoPlayerImplInternal.java:300)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
	at com.google.android.exoplayer2.util.n.run(PriorityHandlerThread.java:40)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.AUDIO.DECODER.MP3, Format(null, null, audio/mpeg, -1, null, [-1, -1, -1.0], [2, 44100])
	... 11 more
Caused by: android.media.MediaCodec$CodecException: Error 0xffffffc3
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:580)
	at com.google.android.exoplayer2.audio.e.a(MediaCodecAudioRenderer.java:195)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.y(MediaCodecRenderer.java:352)
```

Is there any workarounds we could try to get around this?

### Reproduction steps
Attempt to use SimplePlayer to play any MP3 file.

### Link to test content
N/A

### Version of ExoPlayer being used
Release 2.2.0

### Device(s) and version(s) of Android being used
Xiaomi - Redmi Note 3, Wiko Getaway. Android 4.4.2.

### A full bug report captured from the device
Would love to provide this but unfortunately we don't have either phone here in house, these are customer reports.

**Comment by ojw28** [comment] 2017-03-09 22:23
Can you provide some more information about the two devices individually? The Redmi Note 3 didn't ever ship with Android 4.4.2, as far as I can tell. I'm not sure how you got hold of the stack trace, but normally there would be a build fingerprint or some more detailed device information if you're getting it back via an analytics service / feedback mechanism.

Also, is the stack trace exactly the same for the two devices, or slightly different? In particular is `OMX.MTK.AUDIO.DECODER.MP3` identical in both, or does it differ?

It's likely the problem can be solved by blacklisting the problematic decoders, but we may need the information above if we're to do that. Thanks!

**Comment by rustyshelf** [comment] 2017-03-09 22:57
Sure happy to. 

Here are some sample details of users who emailed us from a Redmi Note 3:
> Phone: Xiaomi - Redmi Note 3 - Redmi Note 3 - hennessy
> Kernel: 3.10.61+ - build.redmi.co
> Android version: 5.1.1 SDK 22

> Phone: Xiaomi - Redmi Note 3 - Redmi Note 3 - hennessy
> Kernel: 3.10.61+ - sicmosh-G53JW
> Android version: 5.1.1 SDK 22

And for the Wiko Getaway

> Phone: WIKO - GETAWAY - GETAWAY - wiko
> Kernel: 3.4.67 - HTSVR8
> Android version: 4.4.2 SDK 19

And here are the exceptions broken down specifically to a device:

First Redmi Note 3:
```
com.google.android.exoplayer2.ExoPlaybackException
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:376)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.y(MediaCodecRenderer.java:363)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.b(MediaCodecRenderer.java:770)
	at com.google.android.exoplayer2.audio.e.b(MediaCodecAudioRenderer.java:213)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.v(MediaCodecRenderer.java:501)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:484)
	at com.google.android.exoplayer2.f.f(ExoPlayerImplInternal.java:464)
	at com.google.android.exoplayer2.f.handleMessage(ExoPlayerImplInternal.java:300)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
	at com.google.android.exoplayer2.util.n.run(PriorityHandlerThread.java:40)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.AUDIO.DECODER.MP3, Format(null, null, audio/mpeg, -1, null, [-1, -1, -1.0], [2, 44100])
	... 11 more
Caused by: android.media.MediaCodec$CodecException: Error 0xffffffc3
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:580)
	at com.google.android.exoplayer2.audio.e.a(MediaCodecAudioRenderer.java:195)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.y(MediaCodecRenderer.java:352)
	... 10 more
```

And from the Wiko Getaway:
```
com.google.android.exoplayer2.ExoPlaybackException
	at com.google.android.exoplayer2.f.handleMessage(ExoPlayerImplInternal.java:350)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
	at com.google.android.exoplayer2.util.n.run(PriorityHandlerThread.java:40)
Caused by: java.lang.IndexOutOfBoundsException: offset=0, count=20924, length=4096
	at java.nio.Buffer.checkGetBounds(Buffer.java:167)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:113)
	at au.com.shiftyjelly.pocketcasts.player.o.a(ShiftyAudioRenderer.java:92)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.b(MediaCodecRenderer.java:907)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:489)
	at com.google.android.exoplayer2.f.f(ExoPlayerImplInternal.java:464)
	at com.google.android.exoplayer2.f.handleMessage(ExoPlayerImplInternal.java:300)
	... 4 more

```

That second one is clearly different (my apologies for not adding that to the issue originally) and rather than complaining about the decoder it seems to throw an IndexOutOfBounds where I think it's not meant to. Relevant code from our AudioRenderer:
```
@Override
    protected boolean processOutputBuffer(long positionUs, long elapsedRealtimeUs, MediaCodec codec, ByteBuffer buffer, int bufferIndex, int bufferFlags, long bufferPresentationTimeUs, boolean shouldSkip) throws ExoPlaybackException {
...
bytesAvailable = buffer.remaining();
...
buffer.get(inputBuffer, 0, bytesAvailable); <--- this is line 92 referenced above.
```

**Comment by rustyshelf** [comment] 2017-03-09 23:35
Actually on investigating this issue further I think that second one might be our fault for not allocating enough inputBuffer. So this issue is only related to the Redmi Note 3 getting a DecoderInitializationException. Apologies for the confusion.

**Comment by ojw28** [comment] 2017-03-10 00:21
Thanks for the information! We should be able to get hold of a Redmi Note 3 to see if blacklisting the problematic decoder fixes the problem.

p.s. I saw which app this is for in the stack trace. It's great; happy to see you adopting ExoPlayer!

**Comment by rustyshelf** [comment] 2017-03-10 00:40
@ojw28 not as happy as we are! We used to have 3 different players in our app using various technologies, ExoPlayer has been a huge win for us and it's allowed us to move to one single player for everything. Version 6.2 onwards ships with ExoPlayer and so far the response has been great. Fixed a lot of outstanding bugs we had.

Finally: hats off to you and the team for being so responsive.

**Comment by ojw28** [comment] 2017-03-10 14:34
Apparently there are two Redmi Note 3 variants:

1. Mediatek based: http://www.gsmarena.com/xiaomi_redmi_note_3_(mediatek)-7769.php
1. Qualcomm based: http://www.gsmarena.com/xiaomi_redmi_note_3-7863.php

I've got hold of a Qualcomm one and playback is fine there, so the issue must be specific to the Mediatek variant (which makes sense given it's a Mediatek decoder that's failing).

**Comment by ojw28** [comment] 2017-03-10 14:43
It's likely that the issue can be fixed by adding the following to `MediaCodecUtil.isCodecUsableDecoder`:
```
    // Work around https://github.com/google/ExoPlayer/issues/2542
    if (Util.SDK_INT < 23 && "OMX.MTK.AUDIO.DECODER.MP3".equals(name)
        && "hennessy".equals(Util.DEVICE)) {
      return false;
    }
```
How hard would it be for you to get a modified version of your app to one of the affected users, so they can confirm that it does fix the issue? We'd be happy to merge the change if it's confirmed successful.

**Comment by rustyshelf** [comment] 2017-03-11 06:52
@ojw28 it should be feasible for us to confirm that works. Will get in touch with some people having that issue and add them to our beta. From there we can put that in a beta build and see if the issue goes away.

**Comment by ojw28** [comment] 2017-03-12 14:13
Great. Let us know the outcome and we'll go from there.

**Comment by rustyshelf** [comment] 2017-03-15 04:20
We made that change but now the user is reporting: 

> 6.2.3 : no sound at all. It's playing, but without sound.

Eg: no more exception initializing that dodgy codec, but something else is still not playing the file correctly it seems. Is that something you guys have seen before? If not we can investigate more but I figured it might be worth asking in case you go "Yeah that would definitely be xxxx".

**Comment by ojw28** [comment] 2017-03-15 09:19
The reason blacklisting a decoder in the suggested way often works is that most devices also ship Google's software decoders as well. In this case blacklisting the problematic decoder results in the Google one being used instead. Unfortunately those symptoms would tend to indicate that this device only has the single MP3 decoder, in which case blacklisting isn't an option.

I doubt we'll be able to do anything to address this issue without getting hold of the physical device and trying to see if there's some way of feeding data into the MP3 decoder that it's happy with. It's possible that the MP3 decoder is just completely broken, in which case it wont be possible to fix the issue.

As an aside, you could blacklist if you were to include the FFMPEG extension in your project with `–enable-decoder=mp3`. I doubt you'd want to do that though, particularly if this issue only affects a single device.

**Comment by rustyshelf** [comment] 2017-03-15 23:07
Seems perfectly reasonable and thanks for the extra info. Feel free to close out this bug with a wont-fix if that's a thing on GitHub :)

**Closed as completed** 2017-03-29 20:12 UTC
Labels: wont fix: infeasible, bug: device specific
