### ISSUE TITLE
Exoplayer not switching bitrate on the basis of Bandwidth for audio only.

### ISSUE THREAD

**Issue by palvaibhav89** [google/ExoPlayer#8245] opened 2020-11-18 08:58 UTC
Using version : 2.12.1

Issue: Exoplayer is not automatically switching bitrates on the basis of Bandwidth for HLS audio only streaming.

class ExoplayerUtils(private val ctx: Context) : LifecycleObserver {

    companion object {
        private const val BUFFER_FOR_PLAYBACK_MS = 1500
        private const val MAX_BUFFER_MS = 60000
        private const val CHANNEL_ID = "EXOPLAYER_CHANNEL_ID"
        private const val MEDIA_SESSION_TAG = "MEDIA_SESSION_TAG"
        private const val NOTIFICATION_ID = 8673
        //private const val DEFAULT_MAX_CACHE_SIZE = 100 * 1024 * 1024
    }

    //private var cacheDirectory: File? = null
    private var bandwidthMeter: DefaultBandwidthMeter
    private var player: SimpleExoPlayer? = null
    private var exoPlayerNotification : PlayerNotificationManager? = null

    init {
        bandwidthMeter = getBandwidthMeter(ctx)
        (ctx as AppCompatActivity).lifecycle.addObserver(this)
    }

    fun bindExoplayerForStreaming(
            playerView: PlayerControlView,
            listener: Player.EventListener
    ) {
        player = getSimplePlayer().apply {

            addListener(listener)
            //experimentalSetOffloadSchedulingEnabled(true)
            if(BuildConfig.DEBUG) {
                addAnalyticsListener(EventLogger(trackSelector as MappingTrackSelector, "ExoPlayerEventLogger"))
            }

            playerView.player = this
        }

        setNotificationManager()
    }

    fun playWithUrl(hlsUri: String) {

        getHlsMediaSource(hlsUri).apply {
            addEventListener(Handler(Looper.getMainLooper()), object : MediaSourceEventListener {
                override fun onDownstreamFormatChanged(windowIndex: Int, mediaPeriodId: MediaSource.MediaPeriodId?, mediaLoadData: MediaLoadData) {
                    Log.d("ExoPlayerEventLogger :: onDownstreamFormatChanged ", "${mediaLoadData.trackFormat}")
                }
            })
            player?.setMediaSource(this)
        }

        player?.prepare()

        player?.playWhenReady = true
    }

    private fun setNotificationManager() {
        exoPlayerNotification = PlayerNotificationManager.createWithNotificationChannel(
                ctx,
                CHANNEL_ID,
                R.string.media_notification_channel_name,
                R.string.media_notification_channel_desc,
                NOTIFICATION_ID,
                DescriptionAdapter()
        ).apply {

            val mediaSession = MediaSessionCompat(ctx, MEDIA_SESSION_TAG).apply {
                isActive = true
            }
            MediaSessionConnector(mediaSession).apply {
                setPlayer(player)
            }

            setMediaSessionToken(mediaSession.sessionToken)
            setUseChronometer(false)
            setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
            setPlayer(player)
        }
    }

    private fun getSimplePlayer() : SimpleExoPlayer {

        //Load Control
        val loadControlBuilder = DefaultLoadControl.Builder().apply {
            setBufferDurationsMs(
                    DefaultLoadControl.DEFAULT_MIN_BUFFER_MS,
                    MAX_BUFFER_MS,
                    BUFFER_FOR_PLAYBACK_MS,
                    DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS
            )
        }

        //For Audio
        val audioOnlyRenderersFactory = RenderersFactory { handler: Handler?,
                                                           _: VideoRendererEventListener?,
                                                           audioListener: AudioRendererEventListener?,
                                                           _: TextOutput?,
                                                           _: MetadataOutput? ->
            arrayOf(MediaCodecAudioRenderer(ctx, MediaCodecSelector.DEFAULT, handler, audioListener))
        }

        SimpleExoPlayer.Builder(ctx, audioOnlyRenderersFactory, ExtractorsFactory.EMPTY).apply {

            setLoadControl(loadControlBuilder.build())
            setBandwidthMeter(bandwidthMeter)
            setTrackSelector(DefaultTrackSelector(ctx, AdaptiveTrackSelection.Factory()))

            return build()
        }
    }

    private fun getBandwidthMeter(ctx: Context): DefaultBandwidthMeter {
        return  DefaultBandwidthMeter.Builder(ctx).build().apply {
            addEventListener(Handler(Looper.getMainLooper())) { elapsedMs, bytesTransferred, bitrateEstimate ->
                Log.d("onBandwidthSample", "$elapsedMs $bytesTransferred $bitrateEstimate")
            }
            //defaultBandwidthMeter.setNetworkTypeOverride(C.NETWORK_TYPE_4G)
        }
    }

    private fun getHlsMediaSource(hlsUri: String): HlsMediaSource {

        val client = OkHttpClient.Builder()
                .connectTimeout(2, TimeUnit.MINUTES)
                .readTimeout(2, TimeUnit.MINUTES)
                .writeTimeout(2, TimeUnit.MINUTES)
                .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
                //.cache(if (getCacheDirectory() != null) Cache(getCacheDirectory()!!, DEFAULT_MAX_CACHE_SIZE.toLong()) else null)
                .build()

        val dataSourceFactory = OkHttpDataSourceFactory(
                client,
                Util.getUserAgent(ctx, ctx.getString(R.string.app_name)),
                bandwidthMeter
        )

        return HlsMediaSource.Factory(DefaultDataSourceFactory(ctx, bandwidthMeter, dataSourceFactory))
                //.setAllowChunklessPreparation(true)
                .setExtractorFactory(HlsExtractorFactory.DEFAULT)
                .createMediaSource(MediaItem.fromUri(hlsUri))
    }

    /*private fun getCacheDirectory() : File? {
        if(cacheDirectory == null) {
            cacheDirectory = BaseApplication.ctx.externalCacheDir
            if (cacheDirectory == null) {
                cacheDirectory = BaseApplication.ctx.cacheDir
            }
        }
        return cacheDirectory
    }*/

    @OnLifecycleEvent(Lifecycle.Event.ON_DESTROY)
    fun onDestroy() {
        Log.d("ExoplayerUtils", "OnDestroy")
        release()
    }

    private fun release() {
        exoPlayerNotification?.setPlayer(null)
        player?.release()
    }
}

**Comment by icbaker** [comment] 2020-11-18 09:51
Please provide a test stream that demonstrates the problem in the ExoPlayer [demo app](https://exoplayer.dev/demo-application.html).

Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by tonihei** [comment] 2020-11-18 10:16
This is also likely a duplicate of #3342. Our bandwidth adaptation for audio is slower than for video because internal thresholds to calculate a bandwidth measurement are geared towards video playback.

**Comment by palvaibhav89** [comment] 2020-11-19 04:15
@icbaker i have sent an email with the required hls audio only master.m3u8 url which we are using.

**Comment by palvaibhav89** [comment] 2020-11-19 05:17
@tonihei For me it is not slower. It actually never changes. Please suggest if i am doing something wrong in above code.

> This is also likely a duplicate of #3342. Our bandwidth adaptation for audio is slower than for video because internal thresholds to calculate a bandwidth measurement are geared towards video playback.

**Comment by ojw28** [comment] 2020-11-19 10:04
This is probably actually a duplicate of https://github.com/google/ExoPlayer/issues/5313. Given you'd found that issue already, it's unclear why you've filed this one as well. #3342 is also relevant (I think we'd need to fix both for HLS audio adaptation to work really nicely).

**Comment by icbaker** [comment] 2020-11-19 10:43
Thanks for pointing that out @ojw28, closing this as a dupe of #5313.

**Closed as completed by icbaker** 2020-11-19 10:43 UTC
Labels: duplicate
