### ISSUE TITLE
Change/disable subtitle track with ffmpeg enabled stops playback

### ISSUE THREAD

**Issue by Jamesters** [google/ExoPlayer#8287] opened 2020-11-26 16:42 UTC
###  Issue description
If ffmpeg is enabled and currently being used for audio decoding, when you change or disable (or enable) subtitle tracks, playback stops, but it doesn't pause or stop the video (Exoplayer thinks it's still playing, but video & audio do not progress.

### Reproduction steps
This code from TrackSelectionDialogBuilder:
```
            trackSelector.setParameters(
                TrackSelectionUtil.updateParametersWithOverride(
                    selectionParameters,
                    rendererIndex,
                    rendererTrackGroups,
                    newIsDisabled,
                    newOverrides.isEmpty() ? null : newOverrides.get(0)));
```
Causes the error if
`RendersFactory rendersFactory = new DefaultRenderersFactory(getActivity()).setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER)`
is used 100% of the time.

If
`RendersFactory rendersFactory = new DefaultRenderersFactory(getActivity()).setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON)`
is used, then the problem only surfaces if ffmpeg is used as a fallback

I don't know if this is an ffmpeg issue, or if it's something with the way that Exoplayer is processing the override. I should note that overriding the audio does not cause playback to stop.
There are no messages in the debug log to indicate that an error occured.

ffmpeg was compiled with all the codecs supported by Exoplayer (per the documentation of supported formats)

### Link to test content
n/a - should be reproducible with any internet stream when using ffmpeg to decode audio

### A full bug report captured from the device
n/a

### Version of ExoPlayer being used
Exoplayer 2.12.1, ffmpeg 4.2 and 4.3 both tried.

### Device(s) and version(s) of Android being used
It seems to happen on all devices where the ffmpeg codec is currently being used to decode audio. I've tested on Tivo Stream 4k (API 28), Fire Stick 4k (API 25), Android Emulator with Android TV builds, APIs 26, 27, 28, 30.

**Comment by ojw28** [comment] 2020-11-26 16:44
Duplicate of https://github.com/google/ExoPlayer/issues/8203

**Closed as completed by ojw28** 2020-11-26 16:44 UTC
Labels: bug, duplicate
