### ISSUE TITLE
CryptoException occurs when playing Widevine DASH on certain devices.

### ISSUE THREAD

**Issue by TaruiTakashi** [google/ExoPlayer#7849] opened 2020-09-03 06:49 UTC
### Searched documentation and issues
・ExoPlayer Javadoc.
・ExoPlayer Issues

### Question
CryptoException occurs when playing Widevine DASH on certain devices.
Exception occurs only for P01MA terminals.
No error occurs for other terminals.
Why does it happen?

```
com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Unknown Error
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1202)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:722)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.media.MediaCodec$CryptoException: Unknown Error
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1193)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:722) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61)
```
ExoPlayer version: r2.11.8

Device name: ASUS ZenPad S 8.0
Model number: P01MA
Model name: Z580CA
Android version: 6.0.1

### A full bug report captured from the device
I have sent the bugreport to dev.exoplayer@gmail.com.

### Link to test content
I have sent the media file URL and the license server URL to dev.exoplayer@gmail.com.

**Comment by christosts** [comment] 2020-09-03 13:40
I can see from the attached bug report that the device is starting an L1 WV session and then there are a few errors logged from the device's crypto module. @rrfrias can you please take a look? (content and bugreport have already been sent).

Note that in the bug-report one of ExoPlayer's logs mentions `NO_UNSUPPORTED_DRM` but there was a bug in ExoPlayer where this was misreported so this log might be misleading.

**Comment by rrfrias** [comment] 2020-09-06 10:12
It does appear that the device's crypto module is failing a decrypt request. We can check with Asus since this is a vendor supplied module but the device is running an old build (android M - MMB29P.JP_P01M-V5.5.0-20160922). Even if they are able to root cause it, it is possible they might not roll out an update. 

I do not have a similar device to reproduce. Can you see if this is a problem with the encoding? Try testing with the Exoplayer Demo content (clips from "Widevine DASH:MP4,H264"->"WV: Secure HD (cenc, MP4,H264)". 

Also, would you consider using a lower security level (L3) for this device? That might not experience the same problems. If you need information on how to set a lower security level, please contact Widevine support at https://www.widevine.com/contact

**Comment by TaruiTakashi** [comment] 2020-09-08 08:35
@rrfrias 
> I do not have a similar device to reproduce. Can you see if this is a problem with the encoding? Try testing with the Exoplayer Demo content (clips from "Widevine DASH:MP4,H264"->"WV: Secure HD (cenc, MP4,H264)".

```
{
  "name": "WV: Secure HD (cenc,MP4,H264)",
  "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears_hd.mpd",
  "drm_scheme": "widevine",
  "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
},
```
I tested it in the video above.
The image was distorted for about 2 seconds from about 9 seconds after the movie started, but other parts could be played normally.


```
{
  "name": "Secure UHD (cenc)",
  "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears_uhd.mpd",
  "drm_scheme": "widevine",
  "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
},
```
Also, when the above video was played, "Unable to instantiate decoder OMX.Intel.VideoDecoder.AVC.secure" was displayed.

> Also, would you consider using a lower security level (L3) for this device? That might not experience the same problems. If you need information on how to set a lower security level, please contact Widevine support at https://www.widevine.com/contact

We are not currently considering using L3.

**Comment by rrfrias** [comment] 2020-09-09 10:00
> Also, when the above video was played, "Unable to instantiate decoder OMX.Intel.VideoDecoder.AVC.secure" was displayed.

Is there more information about what caused the instantiation error. You can share the log with dev.exoplayer@gmail.com for us to look into it.

From the original bugreport that you shared with us, here are the error logs that preceded the CryptoException

```
09-03 15:33:13.915   288   761 E /system/bin/mediaserver: doIoctl: DxDI::SEPAPP_COMMAND_INVOKE: DXDI_RET_ESEP (0x60000011)
09-03 15:33:13.915   288   761 E libsep  : tee_invoke_cmd():306: ERROR - TEE invoke command error(0x60000011), cmd_id(0x4000000b)
09-03 15:33:13.916   288   761 E libsep  : drm_wv_mod_decrypt_ctr():818: ERROR - Chaabi returned error value 0x60000011.
09-03 15:33:13.916   288   761 E MDRMOemCrypto: TranscryptToIED failed: ERROR_INVALID_SESSION
09-03 15:33:13.916   288   761 E MDRMOemCrypto: Transcryption of encrypted data to IED failed (0xeab406f0)
09-03 15:33:13.916   288   761 E WVCdm   : Decrypt error result in session sid2 during unencrypted block: 1
09-03 15:33:13.920  3946  3973 E ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(video-avc1-3, null, null, video/avc, avc1.4D401F, 1110658, null, [852, 480, 29.975552], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM
09-03 15:33:13.920  3946  3973 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Unknown Error
```

Given that this device is still running android M, it is unlikely that ASUS is going to roll out an update. Some options are try tweaking the encoding to something that works on this device or fallback to L3.

**Comment by TaruiTakashi** [comment] 2020-09-11 11:31
@rrfrias 

>Is there more information about what caused the instantiation error. You can share the log with dev.exoplayer@gmail.com for us to look into it.

I have sent the bugreport to dev.exoplayer@gmail.com.

>Given that this device is still running android M, it is unlikely that ASUS is going to roll out an update. Some options are try tweaking the encoding to something that works on this device or fallback to L3.

I will consider how to adjust the encoding options.

**Comment by rrfrias** [comment] 2020-09-12 08:50
Thanks for the bugreport. The UHD playback failure seems to originate from an OMX insufficient resource error. Given that the device is running an old release and chances for an update are unlikely, changing the encoding seems the only viable path forward. Let us know if there are any open questions, otherwise i will close this, in a few days.

```
09-11 19:34:33.796   292   808 E OMXNodeInstance: setParameter(32:Intel.Decoder.AVC.secure, ParamPortDefinition(0x2000001)) ERROR: InsufficientResources(0x80001000)
09-11 19:34:33.796  5957  6003 E ACodec  : [OMX.Intel.VideoDecoder.AVC.secure] configureCodec returning error -12
09-11 19:34:33.796  5957  6003 E ACodec  : signalError(omxError 0x80001001, internalError -12)
09-11 19:34:33.796  5957  6002 E MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 3
09-11 19:34:33.798  5957  5981 E MediaCodec: configure failed with err 0xfffffff4, resetting...
09-11 19:34:33.799   292   292 I OMXVideoDecoderAVCSecure: OMXVideoDecoderAVCSecure is destructed.
```

**Comment by rrfrias** [comment] 2020-09-26 06:54
Closing this since the device is running an old release and chances for an update to address this issue are unlikely. Working around this by modifying the encoding seems the only path forward. If there are any remaining questions, please reopen.

**Closed as completed by rrfrias** 2020-09-26 06:54 UTC
Labels: question, bug: in platform drm
