### ISSUE TITLE
sync subtitle

### ISSUE THREAD

**Issue by Mohammadfazel03** [google/ExoPlayer#10278] opened 2022-05-20 05:54 UTC
i have subtitle and video but not sync. how to implement timing subtitle like faster or slower time subtitle ?

how to fixed that?

in the issue #6061 its have not correctly response

**Comment by icbaker** [comment] 2022-05-20 09:56
https://github.com/google/ExoPlayer/issues/6061#issuecomment-503516228 is still correct. This is a duplicate of #854.

**Closed as completed by icbaker** 2022-05-20 09:56 UTC
Labels: duplicate
