### ISSUE TITLE
ExoPlayer doesn't render 4:3 aspect ratio video properly with TextureView surface

### ISSUE THREAD

**Issue by AlinaVoronkovaEpam** [google/ExoPlayer#6179] opened 2019-07-12 12:49 UTC
### Issue description
HLS 4:3 aspect ratio video is cropped when TextureView surface is used for some Android devices (find the list of devices below).

### Reproduction steps
- Open the demo app and add a test video that mentioned below
- Change `PlayerView` in `player_activity.xml` by setting `app:surface_type` as `texture_view`
```
  <com.google.android.exoplayer2.ui.PlayerView android:id="@+id/player_view"
      xmlns:app="http://schemas.android.com/apk/res-auto"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:surface_type="texture_view"/>
```
- Launch the demo app
- Select the manifesting video 
- Play the video and observe the white border around the video content

#### Actual Result
A white border on the right and bottom sides of the video content are not visible.

#### Expected Result:
The video should have a white border on all sides of the video content.

### Link to test content
```
      {
        "name": "3:4 HLS Asset",
        "uri": "https://player.ooyala.com/hls/player/iphone/FwaXZjcjrkydIftLal2cq9ymQMuvjvD8.m3u8?ssl=true&secure_ios_token=VXQ5QkcyRmlZQm5PVm1PaUdYMWdNZi9GUHNORnAwWi9ka0NXNjZXWEV2S0pGZ0lveU44N1BmUk1CYTVECm1rRGpaZGZmM0NGT3ZkK0hzVUF1b2l5NUt3PT0K"
      }
```

### A full bug report captured from the device
A captured bug report has sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
ExoPlayer 2.10.2
The issue is reproduced from ExoPlayer 2.5.6+ (probably early versions are affected too)

#### The issue is seen:
- Pixel 2 XL + Android 9
- Xiaomi A1 + Android 9
- Xiaomi Mi 5 + Android 7
- Huawei Nexus 6P (Android 8.1.0)
- Moto E4 (Android 7.1.1)
- Motorola Nexus 6 (Android 5.1)

#### The issue is not seen:
- Nexus 6P + Android 6
- Samsung S9 + Android 9

**Comment by ojw28** [comment] 2019-07-15 09:51
I think this is a duplicate of a bug we've filed internally on the Android platform team [Internal ref: 80516628]. I'll chase up on that.

**Comment by ojw28** [comment] 2022-04-22 13:58
This has been fixed in the platform in Android T.

**Closed as completed by ojw28** 2022-04-22 13:58 UTC
Labels: bug: in platform
