### ISSUE TITLE
AndroidX ClassNotFoundException: com.google.android.exoplayer2.ui.SubtitleView

### ISSUE THREAD

**Issue by BastienCalone** [google/ExoPlayer#7700] opened 2020-07-31 07:56 UTC
Hello there,

Since i move my application to AndroidX i struggle with the SubtitleView of exoplayer. I can't inflate it. For the context, i have the subtitle view in a module that i use in my app as a dependency, there is no proguard configuration. 
Also if we use debug config, meaning we use local project dependencies  , the app works fine, but when we use the released module uploaded, this error is thrown

### **[REQUIRED] Issue description**

We checked with my team for inflating issues and find that for some case 
` compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }`
was a solution but for us it didn't fixed the problem.
We checked around a lot, nothing seems to talk about this kind of problem, so this is our last solution to come here bothering you with our problems

### **[REQUIRED] Reproduction steps**
Add an app on Android X, 
add an external module with exoplayer dependencies and a layout using SubtitleView
Use this layout into your application
Build a release version of your app

### **[REQUIRED] Link to test content**
I can't give you a link to test since it's a production app i don't own ..

### **[REQUIRED] A full bug report captured from the device**

     Caused by: android.view.InflateException: Binary XML file line #4 in fr.tf1.player.sample:layout/activity_vidar_player: Error inflating class fr.tf1.player.ui.vidar.VidarPlayerView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at fr.tf1.player.sample.ui.base.PlayerBaseActivity.setContentView(PlayerBaseActivity.kt:101)
        at fr.tf1.player.sample.ui.PlayerVidarActivity.onCreate(PlayerVidarActivity.kt:25)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #7 in fr.tf1.player.sample:layout/tf1_player_vidar_player_view: Binary XML file line #11 in fr.tf1.player.sample:layout/tf1_player_vidar_simple_player_view: Error inflating class com.google.android.exoplayer2.ui.SubtitleView

E/AndroidRuntime: Caused by: android.view.InflateException: Binary XML file in fr.tf1.player.sample:layout/tf1_player_vidar_simple_player_view: Error inflating class com.google.android.exoplayer2.ui.SubtitleView

    Caused by: java.lang.ClassNotFoundException: com.google.android.exoplayer2.ui.SubtitleView
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.view.LayoutInflater.createView(LayoutInflater.java:815)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at android.view.View.inflate(View.java:26298)
        at fr.tf1.player.ui.vidar.VidarPlayerView.<init>(VidarPlayerView.kt:89)
        at fr.tf1.player.ui.vidar.VidarPlayerView.<init>(VidarPlayerView.kt:52)
        at fr.tf1.player.ui.vidar.VidarPlayerView.<init>(Unknown Source:6)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at fr.tf1.player.sample.ui.base.PlayerBaseActivity.setContentView(PlayerBaseActivity.kt:101)
        at fr.tf1.player.sample.ui.PlayerVidarActivity.onCreate(PlayerVidarActivity.kt:25)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: com.google.android.exoplayer2.ui.SubtitleView
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:815) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084) 
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481) 
        at android.view.View.inflate(View.java:26298) 
        at fr.tf1.player.ui.vidar.VidarPlayerView.<init>(VidarPlayerView.kt:89) 
        at fr.tf1.player.ui.vidar.VidarPlayerView.<init>(VidarPlayerView.kt:52) 
        at fr.tf1.player.ui.vidar.VidarPlayerView.<init>(Unknown Source:6) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:854) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at fr.tf1.player.sample.ui.base.PlayerBaseActivity.setContentView(PlayerBaseActivity.kt:101) 
        at fr.tf1.player.sample.ui.PlayerVidarActivity.onCreate(PlayerVidarActivity.kt:25) 
        at android.app.Activity.performCreate(Activity.java:7825) 
        at android.app.Activity.performCreate(Activity.java:7814) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
     Caused by: java.lang.ClassNotFoundException: com.google.android.exoplayer2.ui.SubtitleView
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:815) 

### **[REQUIRED] Version of ExoPlayer being used**
version : 2.11.7

### **[REQUIRED] Device(s) and version(s) of Android being used**
Android Sdk Version 29
All devices running on Android X

**Comment by tonihei** [comment] 2020-07-31 15:27
As you noted, the issue is probably not really ExoPlayer related, but a more a generic Android problem where you may get more luck on StackOverflow or similar sites. A quick searchs suggests it could be related to multidexing for example: https://stackoverflow.com/questions/31684361/classnotfoundexception-when-inflating-custom-button-works-on-phone-exception-o or you just need to use a dependency on the exoplayer UI module because the library isn't declaring one itself. 

I'll close the issue again under the assumption that there is nothing we can do about this really. If you think there is, feel free to reopen.

**Closed as completed by tonihei** 2020-07-31 15:27 UTC
Labels: question
